### PR TITLE
Fix GameUI text staying visible during shutdown.

### PR DESCRIPTION
**Pull request by FoxLoveFire**
Hello! This pull request is reopened( i had some problems). This PR fixing GameUI text witch  visible during shutdown.
image
(Screenshot was taken from my custom client)

## How to test
 Compile it.

### CODE REVIEW

**Review by grorp — CHANGES_REQUESTED** [review]
The fix works, the code looks good.

There's still whitespace at the end of some lines. Please remove it.

**Comment by FoxLoveFire** [comment]
> The fix works, the code looks good.
> 
> There's still whitespace at the end of some lines. Please remove it.

Whitespace at some lines? I do not understand about you talking....

**Comment by grorp** [comment]
> Whitespace at some lines? I do not understand about you talking....

White space at *the end of* some lines, better known as "trailing whitespace".

If you're on Linux, you can (for example) use this command to get rid of it:

```bash
sed -i 's/[ \t]*$//' ./src/client/game.cpp ./src/client/gameui.cpp ./src/client/gameui.h
```

(https://stackoverflow.com/a/4438318)

If you're using a different OS, you can search the web for `<your OS or your tool/IDE> remove trailing whitespace`. You'll probably find something. Removing trailing whitespace manually is also possible.

**Comment by FoxLoveFire** [comment]
> > Whitespace at some lines? I do not understand about you talking....
> 
> White space at _the end of_ some lines, better known as "trailing whitespace".
> 
> If you're on Linux, you can (for example) use this command to get rid of it:
> 
> ```shell
> sed -i 's/[ \t]*$//' ./src/client/game.cpp ./src/client/gameui.cpp ./src/client/gameui.h
> ```
> 
> (https://stackoverflow.com/a/4438318)
> 
> If you're using a different OS, you can search the web for `<your OS or your tool/IDE> remove trailing whitespace`. You'll probably find something. Removing trailing whitespace manually is also possible.

Done.

**Review by grorp — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
Does what it says.

**Pull request merged**
