### PR TITLE
Move generation from settingtypes and make it a bit simpler to read.

### PR DESCRIPTION
**Pull request by t4im**
Generates the identical files to right now
(the only difference was intentional and is committed here, too)

---

Avoids unreachable code linter warning by moving generation code
(of minetest.conf.example and settings_translation_file.cpp)
out of dlg_settings_advanced and tidies the code up a bit.

Instead of activating the code by changing the active if-clauses,
its activation is done by uncommenting the loadfile() statement.

### CODE REVIEW

**Comment by est31** [comment]
Maybe make two commits, one for actual moving, and the other one for the refactoring? Commits copying 100 lines around and modifying them in the process are not nice to review.

**Comment by t4im** [comment]
You got it :-)

**Comment by est31** [comment]
Thanks :+1:

**Comment by est31** [comment]
@paramat you know lua, can you review this PR (and possibly merge it, not squashing it)?

**Comment by paramat** [comment]
Yeah i'll try, it has some lua i'm not familiar with. I support the PR concept.

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
ba501273094b0c6c77404610f2dee81c031d0074

6590140260d0338ab5a0fd2bbcd4c72f07dd963d

**Pull request closed without merging**
