### PR TITLE
Main menu redesign

### LINKED ISSUE #6733: Improve mainmenu
A thread to discuss general UX issues with the main menu.

Supersedes https://github.com/minetest/minetest/pull/3818

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #6733. Requires #8524 and #8383

See this comment for future plans: https://github.com/minetest/minetest/issues/6733#issuecomment-506017301

image

image

## Todo

- [x] Separate widget for sidebar tabs, to not break API
- [ ] Redesign all tabs
  - [x] Local
  - [x] Join
  - [ ] Content
  - [ ] Settings
  - [ ] Credit
- [ ] Implement change game
- [ ] Load icons from games

### CODE REVIEW

**Comment by tacotexmex** [comment]
`Play World` (Why "Play World"?) is currently in the middle section while `Connect` is in the right. It's inconsistent. The primary action button should be situated in the same place on each page.

**Comment by tacotexmex** [comment]
I've compiled and tested this design. What does it improve? What are its goals? If the goal is to enable more space for content areas that actually needs it, it doesn't:

bild

bild

**Comment by rubenwardy** [comment]
>  (Why "Play World"?)

I changed it to those when I had a "Change Game" option

> What does it improve? What are its goals? 

The aim is to give each game its own menu, which it will be able to customise in the future, and to also use a better design than tabs

> If the goal is to enable more space for content areas that actually needs it, it doesn't

This is a work in progress PR. The only tabs that have been updated are local and online. You can see this in my todo list in the first post. Other tabs need to be converted to `real_coordinates`.

**Comment by tacotexmex** [comment]
> The only tabs that have been updated are local and online. You can see this in my todo list in the first post. Other tabs need to be converted to real_coordinates.

Does this mean you'll increase the area for some tabs but not for others? That would be very inconsistent.

**Comment by rubenwardy** [comment]
> Does this mean you'll increase the area for some tabs but not for others? That would be very inconsistent.

All tabs will be the same size

**Comment by tacotexmex** [comment]
> The aim is to give each game its own menu, which it will be able to customise in the future, and to also use a better design than tabs

Will each game have an entry in the sidebar?

**Comment by rubenwardy** [comment]
Note that the form is the same size as before, just with a sidebar on the left. 

The real coordinates system removes padding and spacing from positions, which shrinks GUIs.

> Will each game have an entry in the sidebar?

https://github.com/minetest/minetest/issues/6733#issuecomment-506017301

**Comment by tacotexmex** [comment]
> All tabs will be the same size

So you mean a larger one than in the current PR? Will it be full width and height or just larger? If so, how large?

**Comment by tacotexmex** [comment]
> The real coordinates system removes padding and spacing from positions, which shrinks GUIs.

Do you mean that all this work is for a few pixels larger content area?

**Comment by Fixer-007** [comment]
Title should be on top, not behind IMO. Also a very good chance to make _unified_ Content tab, merge it with CDB into one good list of installed mods with update(all)/remove functionality.

**Comment by MoNTE48** [comment]
Perhaps it is worth dividing guiSkin and MainMenu changes by 2 PR?

**Comment by rubenwardy** [comment]
It already is in 2 PRs. This PR depends on another PR, but there's no way for GitHub to know that so it lists the required PRs in the changes

**Comment by MoNTE48** [comment]
Sounds good. Your work looks great! I really like the idea of transferring this to MC, but it scares me when I look at the list of changes and the number of PRs. :-D
The menu is really outdated for a long time and this fresh look is necessary.

**Comment by twoelk** [comment]
maybe while a lot is changed one could use the oppertunity to change the credits link into an about link. For now it could still lead directly to the credits window but in a next change the about page could be used to lead to other informative pages including the credits page of now.

**Comment by ClobberXD** [comment]
> maybe while a lot is changed one could use the oppertunity to change the credits link into an about link. For now it could still lead directly to the credits window but in a next change the about page could be used to lead to other informative pages including the credits page of now.

This is out of the scope of this PR and can also be done separately later, as this PR is already quite large. But I like the idea of having an about page, with credits being its sub-widget or smth.

**Comment by rubenwardy** [comment]
The first commit in this PR makes it possible to define layouters to render the navigation differently. The aim for this is to make it much easier for games to customise their menu

# Builtin Layouters

## tabs

The current system

## vertical

tabs are on the side, the original form of this PR. With formspec scaling, this would become the fullscreen version

image

image

## mainmenu

image

image

**Comment by rubenwardy** [comment]
superseded by #8758

**Pull request closed without merging**
