### PR TITLE
Extruded plants and torches.

### PR DESCRIPTION
**Pull request by RealBadAngel**
Deault set to false, use "extruded_meshes = true" in config to enable it.
screenshot_3663404224
screenshot_3735214406

### CODE REVIEW

**Comment by paramat** [comment]
ocd_2


Here's an example of how 3D plants should be done, using nodeboxes, which are now converted into fast meshnodes thanks to RBA. OCD by Bas080. These are low resolution but could be slightly higher resolution and still look suitable, i feel a 1/16th resolution is too high though.
The plantlike drawtype is so extremely simple and abstract it only looks right with a suitably matching extremely simple and abstract texture: completely flat and not extruded.

**Comment by NathanSalapat** [comment]
@paramat Those plants look very good.

**Comment by HybridDog** [comment]
https://github.com/HybridDog/minetest/commit/bcefdb78ab9156690dfe46ba349371408326cea8

**Comment by paramat** [comment]
This should be closed now.

**Comment by est31** [comment]
For reference, its: #3496

**Pull request closed without merging**
