### PR TITLE
make maintab text readable

### PR DESCRIPTION
**Pull request by Kezii**
- Goal of the PR
make maintab text readable
- How does the PR work?
trivailly
- Does it resolve any reported issue?
#7060
- If not a bug fix, why is this PR needed? What usecases does it solve?
because maintab text is not readable

This PR is Ready for Review.

Edit: screenshots removed, look at last messages

### CODE REVIEW

**Comment by paramat** [comment]
See my issue #7060 , the tab text readability is a problem, especially with custom backgrounds or if it overlaps the header texture.

Black text helps a little when seen against sky, but you can see that the problem remains when a tab is over a dark background, so your change will only help in some situations, and will make some situations worse. So i am unsure about supporting this.

The primary problem is that the alpha of the tabs is too low, meaning background colours maintain most of their strength, which will cause unreadability whatever colour the text is.
Changing the tab theme is not easy and is discussed here https://github.com/minetest/minetest/issues/7060#issuecomment-504713388 , since we have forked Irrlicht perhaps it might be easier now.
@rubenwardy any thoughts on this?

**Comment by Kezii** [comment]
immagine

**Comment by paramat** [comment]
Ahh, you updated just as i made my last comment, this is much better now.

**Comment by Kezii** [comment]
> Ahh ... you updated just as i made my last comment, this is much better now.

Yeah, sorry, someone pointed it out and I started digging again on the code, I had not seen your comment

I'm not really sure about the scope of this change, I don't notice obvious regressions

**Comment by v-rob** [comment]
This does make it more readable, but it changes the background for all tabheaders, not just the main menu.

**Comment by Zughy** [comment]
Relevant: #9802

**Comment by Kezii** [comment]
> This does make it more readable, but it changes the background for all tabheaders, not just the main menu.

I tried to get a scientific source for this and failed, so talking by anecdotal evidence, I see that most users set the opacity for GUI elements in Linux themes at a value of at least 60%, up to 95% for "active" elements, minetest now uses ~40% for a lot of elements

so maybe it's appropriate to increase the opacity a bit for the whole theme?

**Comment by v-rob** [comment]
I'm not opposed, but how does it look with white text?  Since all Minetest tabheaders have white text by default, this increased opacity might make all other tabheaders be less readable.  It might be more beneficial to make tabheader background color gray or black by default instead of white, but this might be contentious.

**Comment by Kezii** [comment]
> I'm not opposed, but how does it look with white text? Since all Minetest tabheaders have white text by default, this increased opacity might make all other tabheaders be less readable. It might be more beneficial to make tabheader background color gray or black by default instead of white, but this might be contentious.

Yeah, hadn't thought about that

immagine
?

**Comment by paramat** [comment]
I prefer formspec-consistent white text on a dark background, as i suggested in the issue, your latest screenshot looks much better.

**Comment by Kezii** [comment]
immagine

**Comment by LoneWolfHT** [comment]
Looks a *lot* better. :+1: if mods can change how their tabs look.

**Comment by v-rob** [comment]
Looks much better, better than I thought.  I like how the color is very similar to buttons and matches the default dark gray theme of everything else.  👍

**Comment by Andrey2470T** [comment]
The grayed tabheaders with the white text really look like fine and well-combined with the current mainmenu theme.   :+1:

**Comment by paramat** [comment]
@rubenwardy , considering what you wrote here https://github.com/minetest/minetest/issues/7060#issuecomment-504713388 are there any problems with this implementation?
I think it is fine, in fact desirable, if all tabheaders are changed this way.

**Comment by rubenwardy** [comment]
I'm fine with the proposed change

**Comment by paramat** [comment]
Great, i will test this and probably approve.

**Comment by paramat** [comment]
screenshot_20200823_181014

Tested.
Alpha is high enough that backgrounds do not affect readability at all.
Looks really good, a big improvement to tabbed formspecs.
:+1:

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
