### PR TITLE
Add font selection dialog to the main menu

### LINKED ISSUE #11455: Make Unifont and OpenMoji the default fonts
## Problem
People can't see some writing systems like Arabic in game, as well as emoji.

## Solutions
Make Unifont and OpenMoji the default fonts. Unifont supports as many writing systems as possible and is pixelated, suitable for the game's pixel art style; OpenMoji is an emoji font covering the latest Unicode version.

http://unifoundry.com/unifont/index.html
https://openmoji.org/

### PR DESCRIPTION
**Pull request by yw05**
This PR implements a simple font selection dialog ~~and adds Unifont as an optional font~~. This _might_ partially fix #11455.

## To do

This PR is a Work in Progress.

- [x] ~~Fix: Random segfaults when clicking on the dropdown~~ (appears to be gone now - I have tried to reproduce this for 5 minutes with no luck)
- [x] Fix font preview
- [ ] Better coverage
- [ ] Support "truetype=false"
- [ ] Allow changing the fallback font?
- [ ] Add strings to the translation template

## Note
- ~~The Japanese variant of Unifont is also added because certain glyphs with slight writing differences in Chinese and Japanese are unified to the same codepoint.~~
- Unifont was originally part of the PR but was dropped due to the lack of bold and italic variants.

## How to test

A "Change Font" button is available in the Settings tab.

### CODE REVIEW

**Comment by hecktest** [comment]
Does this font even support italic and bold styles?

**Comment by yw05** [comment]
Partially. Currently it simply adds `-Bold`, `-Italic`, and `-BoldItalic` between the filename and the extension (replacing `-Regular` if present). So for `NotoSans-Regular.ttf` it sets the variants `NotoSans-Bold.ttf`, `NotoSans-Italic.ttf`, and `NotoSans-BoldItalic.ttf`.

This obviously doesn't work for every font, however, which is something that needs to be improved before I mark it as ready.

**Comment by hecktest** [comment]
> As for Unifont, I simply make every variant use the same TTF font file because there is not bold/italic variant.

That is pretty bad. Not only Unifont doesn't work properly outside of its intended 16px size, but it also doesn't support bold and italic styles - which means any `hypertext[` styling will be broken. I would not ship a font like this as one of the defaults, it's just poor quality.

For CJK support it would be much better to supply a dedicated fallback font separately for each of these languages, rather than use two almost identical copies of Unifont that only differ by a few kanji. Or even better, ask the OS for a font.

**Comment by yw05** [comment]
> For CJK support it would be much better to supply a dedicated fallback font separately for each of these languages, rather than use two almost identical copies of Unifont that only differ by a few kanji.

Some stroke differences can affect characters in an entire range (e.g. 793A-79B7, 7A74-7ACA, 8279-864C, 8FB6-9090)

Regardless of that, proving different fallback fonts should be enough. I use Noto Sans CJK and it works well so far, at least for me. That would be a lot, however, unless Minetest has support for `.ttc` fonts (which, in the case of Noto Sans CJK, is much smaller)

> Or even better, ask the OS for a font.

I am thinking about using fontconfig for font selection, except I currently need to figure out how to implement it properly.

**Comment by rubenwardy** [comment]
Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed. These PRs can also have preapproval if they fix an issue that is concept approved

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label. In the future, you can open an issue first to get preapproval before working on something

**Comment by yw05** [comment]
Sorry. but I have not really been focusing on Minetest (or logged in to Github) recently, and the implementation of proper font support in a way that does not break existing configurations does not appear to be something that I have the skill to implement.

**Pull request closed without merging**
