### PR TITLE
Add tooltips for many elements of the main menu

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds a lot of tooltips throughout the main menu for the menu elements where I thought that they may need more explanation.

Included:
- Almost all checkboxes everywhere
- All drop-down menus
- Most non-obvious buttons
- “Arrow buttons” of the buttonbar

You will probably notice 2 problems:
- (now fixed) “\,” is written in tooltips where it should just be “,”. This is a bug with tooltips in Minetest, see #2428
- The drop-down menu appear to have no tooltips. They actually have tooltips, they are not shown because of another bug in Minetest, see: #1577 

Fixing those bugs is _not_ a goal of this PR, those are problems which should be handled in different commits (IMHO).

This PR is slightly WIP, but mostly finishe. Basically I just want to have some feedback to ensure that everything is OK.

I would like to hear comments in particular about the tooltips themselves. Please proofread them for factual accuracy. I am not a pro in graphics programming, so a couple of settings tooltips may be wrong.
A tooltip for the checkbox “Generate normalmaps” is missing, because I don't really know what is actually happening there. Suggestions for a tooltip text are welcome. (Also an explanation of what this does :-))

### CODE REVIEW

**Comment by LeMagnesium** [comment]
The idea is good, but the "\" are annoying, even if you can't do anything else to show ','. Some of the tooltips are a bit too large for the window, most of them are helpful (in the setttings tab for example), but there is one missing : "generate normalmaps" (if my translation is right). For example, this one is too large :

Link to picture

However, good work.

**Comment by nerzhul** [comment]
needs some improvements but good idea

**Comment by Wuzzy2** [comment]
@nerzhul: Meh, this comment was unhelpful. What improvements exactly?

@LeMagnesium: Reading helps. As I said, I don't know how to explain it. Someone who has a better understanding of the engine might help?!
And the problem with tooltips may be another issue of Minetest, as I view it. But as long it is unfixed, I think I can work around it by limiting the length of a tooltip to about 80 lines or so.

**Comment by nerzhul** [comment]
You need to fix tooltip size :)

**Comment by Wuzzy2** [comment]
@nerzhul: Done, see 5558ed0.

**Comment by BlockMen** [comment]
Tooltips like "Your player name used on the server" make no sense at all. if you think you should inform the player about something then tell them the name is server only, no "global" username like MC has.
Also useless: "This slider determines the size of all GUI elements". It is kinda obvious that the slider changes the size of the gui.

"A non-negative integer used for the map generator"
^ you can also use strings, its not integer only.

"The renderer is the most basic component which calculates and draws almost everything you will see in Minetest."
^
This is also too much. You don't need to explain general game components here, explain the player the differences, thats enough. 
Also terms like "OpenGL is the best and fastest" is not useful at all and even wrong. Its depending on your graphics card, etc. DirectX (direct3d9) [which is not even mentioned at all] can be much faster than OpenGL.
Tell useful things like shaders are only supported by OpenGL...


This PR is as is an overkill and has the opposite effect it aims for. So please reduce the tooltips amount and don't add obvious things or the same info in the tooltips.

**Comment by Wuzzy2** [comment]
> Also useless: "This slider determines the size of all GUI elements". It is kinda obvious that the slider changes the size of the gui.

Agreed, redundancy is bad. I removed the first sentence.

> "A non-negative integer used for the map generator"
> ^ you can also use strings, its not integer only.

Fixed. I wonder whether strings are “stable”, meaning that they will map to the same number in future versions.

> This is also too much. You don't need to explain general game components here, explain the player the differences, thats enough.

I disagree. One goal of this PR is to explain non-obvious things. Some people do not know what a “renderer” is, and they also many terms on the settings are very cryptic to many newbies. I still don't know the meaning of some settings by myself (“Generate normalmaps” does what *exactly*?). So I don't see a valid reason to remove this sentence.

> Also terms like "OpenGL is the best and fastest" is not useful at all and even wrong. Its depending on your graphics card, etc. DirectX (direct3d9) [which is not even mentioned at all] can be much faster than OpenGL.
> Tell useful things like shaders are only supported by OpenGL...

Thanks, that's why I was asking for feedback. I didn't know Minetest also supports DirectX. I really need to do more research here, so my next commit might still not be perfect regarding this tooltip.

> don't add obvious things or the same info in the tooltips.

Redundancy removed. But remember that not everything which is obvious to you is obvious to other people, so we might disagree on what is obvious.


If anyone is aware of other factual mistakes, please report them!

This PR has become a bit chaotic by now, I will probably rebase the whole thing as soon it is finished and you are fine with it.

**Comment by kilbith** [comment]
> Some people do not know what a “renderer” is, and they also many terms on the settings are very cryptic to many newbies.

This is why Google and Wikipedia exists - not our job. If you want to be indicative, you should be much more succinct and only where it's needed (eg. the visual settings in the 1st column don't need explanation, names are clear and players are likely preferring check themselves).

**Comment by Wuzzy2** [comment]
> names are clear and players are likely preferring check themselves

This is a contradiction. If the names are clear, then the players don't need to check themselves. But if they need to check, then the names weren't clear enough.
Also, the argument that players could just check themselves is missing the point.
The whole point of tooltips is convenience.
Having tooltips is more convenient. I see no reason to replace having convenience with *not* having convenience.
Also, some of these options on the left are not always immediately obvious by trying them, i.e. the “Connected Glass” setting doesn't change anything in minetest_game because it doesn't use this drawtype so far.

Regarding the left part of the settings: The following terms are clearly non-obvious and/or slightly misleading: “Node Highlighting” (“node” is a Minetest technical term), “Fancy Trees” (vague, also not limited to trees and leaves, actually), “Opaque Water” (actually it is not only water), “Connected Glass” (must not neccessarily be glass only).
The other 2 terms may be slightly more clear, but the tooltips are not redundant and offer more explanation.

Also, I think the Wikipedia and Google argument is stupid. *Maybe* someone uses those if there is *one* term which is not understood. But *all of them*? Probably not. Players are lazy. And this argument fails for “Node Highlighting”.

I *can* however understand the argument that some tooltips are too long. Maybe I could try to make them shorter, but I am not sure if I could do so without removing any information.

Most importantly: If you have a complaint, please specify the exact tooltip, and comment this.
It would be also very helpful if you provide an alternative, better text so I could use this.

**Comment by kilbith** [comment]
> This is a contradiction. If the names are clear, then the players don't need to check themselves. But if they need to check, then the names weren't clear enough.

No sorry, that syllogism ain't suitable here. By "checking" I meant that players want to see if an option is looking good enough in-game for them, not if the effect is according to the name itself (and the aforementioned are lexically obvious).

**Comment by BlockMen** [comment]
> I disagree. One goal of this PR is to explain non-obvious things. Some people do not know what a “renderer” is, and they also many terms on the settings are very cryptic to many newbies. I still don't know the meaning of some settings by myself (“Generate normalmaps” does what exactly?). So I don't see a valid reason to remove this sentence.

Why don't you explain engine then? Or other game specific terms? It still to much information, especially in this tooltip. And you can't replace the wiki with that. Just put the most important infos, not complete explanations. 

> [...]  i.e. the “Connected Glass” setting doesn't change anything in minetest_game because it doesn't use this drawtype so far.

umm... https://github.com/minetest/minetest_game/commit/7f44a49d99fe1793b31263527ae8af653300a515

**Comment by paramat** [comment]
Many players (such as myself) find tooltips irritating, pop-up boxes are distracting, visually irritating and messy and would be turned of by all players and not used very soon after they start to play the game. Such information for newbies should be stored elsewhere in an optional tutorial or a separate text file. Thus is spoon feeding newbies to the extent of annoying the vast majority of players, so shouldn't be added at all.

**Comment by ShadowNinja** [comment]
@paramat: Tooltips have a delay.  If you don't want them just don't hover for a long time or ignore them.  A agree that there shouldn't be tooltips for obvious things though.

**Comment by nerzhul** [comment]
What about adding a checkbox to disable it ?

**Comment by Zeno-** [comment]
No, don't add a feature to disable tooltips (if this PR/idea goes ahead). Tooltips are a normal feature

**Comment by Wuzzy2** [comment]
> Many players (such as myself) find tooltips irritating, pop-up boxes are distracting, visually irritating and messy and would be turned of by all players and not used very soon after they start to play the game.

Proof it.

> The main menu is fairly clear and self-explanatory as it is so i see no need for tooltips.

Do Minetest newbies agree?

> Such information for newbies should be stored elsewhere in an optional tutorial or a separate text file.

Why? You just said that the main menu is self-explanantory, so there would not be a need for a tutorial of additional help tab either.

> How about combining this with this PR #2135 (…)

I have no idea at all what you mean with “combining” them. You just argued against the tooltips, so what's the point of combining this PR with the other one?


What you say does not make much sense to me.

**Comment by est31** [comment]
Tooltips are no manual. No graphics setting should be explained by a 10 line tooltip that fills the whole screen. Manuals should.
But generally a good idea.

**Comment by paramat** [comment]
Oops sorry, unnecessary aversion, i deleted my post. I'm not bothered about making them optional as long as there is a good delay of 2 seconds =)

**Comment by Zeno-** [comment]
I'm fine with this  but I agree that they should be more concise

**Comment by Wuzzy2** [comment]
Give me any suggestions for better tooltip texts and I apply them if it sounds reasonable.

**Comment by ObaniGemini** [comment]
Tooltips should be short and explicit, not a long description. If players want more informations, they should read docs.

te_address = fgettext("Host name or IP address of the server")
te_port = fgettext([[Port of the server. Must be a number]])
cb_public_serverlist = fgettext([[Show public servers list]])
btn_mp_connect = fgettext([[Join the server]])
te_name = fgettext([[Your in-game name]])
te_pwd = fgettext([[Your password on this server]])
cb_creative_mode = fgettext([[That game mode brings you infinite resources to build]])
cb_enable_damage = fgettext([[Enable damages for players]])

This seems better to me @Wuzzy2

**Comment by paramat** [comment]
:-1: Texts are far too long.
Tooltips are usually a few words and used with non-obvious icons, we have buttons with text so tooltips are not really needed. This kind of detailed help information should be in a seperate tab or text folder.
Tooltips should be optional otherwise they will irritate everyone except beginners.

**Comment by Wuzzy2** [comment]
Either we include tooltips or we don't include them, but don't make them “optional”, that's just silly, we should not make every stupid little thing configurable just for the sake of it.
But we can discuss about the tooltip contents.
I have the following compromise solution:
* Add a few tooltips (NOT optional), but not for those elements which explain themselves
* For the elements which do not explain themselves, we could consider a small redesign in order that it explains themselves
* If a field does not explain itself and can also not be redesigned easily, I still suggest to have that tooltip

But the question is: How short? As a cultural pessimist, I assume you would allow no more than a single line with 140 characters, like Twitter. xD Probably its not that extreme, but if even that is too long for you, then I give up. Close this issue / PR then.

Now, before I change anything in this PR, here is stuff

* Creative Mode → short description of what this does. Too bad this is highly subgame-dependent now. There MAY be a creative inventory and a stronger hand, but this is not guaranteed. A subgame could theoretically give you a nyan cat if creative inventory is enabled because why not? ;-) It could do whatever. So the honest tooltip would be “does something”. xD Maybe this is more a problem with creative mode itself, so I have no idea of what a sensible tooltip would say
* Field for player name: Allowed characters. Maybe?
* Port number input fields: Tooltip saying whether its UDP or TCP port, quite important since some people have to use port-forwarding
* “Public server list” checkbox in client tab. It is NOT obvious that when the checkbox is off, a list of favourites is shown. The tooltip-free solution would be to redesign that tab a bit. Maybe instead of a checkbox, use a button to toggle the display mode, it says “Favourites” or “Public server list”, depending on what mode you are in
* Most settings are NOT self-explanationary. Also, the “players could find out by trial-and-error” argument is invalid since some changes are pretty much subtle.
 We could at least say very roughly what it will look like. And also point out stuff that may be a performance break
    * Antialiasing: “Smoothens rough edges at the cost of performance”
    * Mipmap: “Scales textures. May increase performance slightly”
    * Texturing: “No filter makes the textures look pixelated, filters make them look more smooth or blurry”
    * All shader checkboxes except the “Waving” stuff, esp. possible impact on performance. Also, the advanced settings help is not useful on shader stuff. It just says, like, “Enables parralax occlusion” -_-
    * Simple/Opaque/Fancy leaves: Either add a tooltip or maybe rename “fancy leaves”, the difference between simple and fancy is not that obvious. But this is of low importance
    * Node highligthing/outlining: This is confusing and also wrong. Confusing since “node” is Minetest slang. It is also wrong since not only nodes are highlighted, but also objects. What would you say about renaming this to “Highlight pointed things” and “Outline pointed things”? I hope this should be clear enough then to not require an additional tooltip
* World creation:
    * Seed: “Equal seeds lead to equal worlds. Enter non-negative integer here or leave empty for a random seed.”
* Mod config menu:
    * Hide MP content: “Hide mods which are inside modpacks” (because of “MP”)
    * Enable/Disable MP: “Enable modpack”/“Disable modpack”
    * Hide game: “Hide core mods from the current game” (“Hide game” is kind of a misnomer, actually, but there is not much space :-( )
    * OOOOOOR you figure a way to fully write out the true meaning of the buttons/checkboxes so no tooltips are needed

I don't get it why I am not allowed to explain the settings, because Minetest already gives detailed descriptions in the advanced settings.

But then I would probably have to throw this PR away and start over since it is pretty outdated now anyways. But first let's see what you have to say. It I am good to go with those suggestions, I probably just open another PR. If not, I probably just give up and close this one.

**Comment by ObaniGemini** [comment]
Tooltips might be useful for settings

**Comment by ObaniGemini** [comment]
`

    Creative Mode → short description of what this does. Too bad this is highly subgame-dependent now. There MAY be a creative inventory and a stronger hand, but this is not guaranteed. A subgame could theoretically give you a nyan cat if creative inventory is enabled because why not? ;-) It could do whatever. So the honest tooltip would be “does something”. xD Maybe this is more a problem with creative mode itself, so I have no idea of what a sensible tooltip would say`

Good subgames always have a creative mode. This is up to the developpers.

`Field for player name: Allowed characters. Maybe?`

Unuseful, 90% of the players don't care about it. 90% of the rest know what are the allowed characters.

`Port number input fields: Tooltip saying whether its UDP or TCP port, quite important since some people have to use port-forwarding`

Science proved that 99.999% of the people in the world didn't know about UDP or TCP. If you consider such things important, read the docs.

`Most settings are NOT self-explanationary.`

Should they ?
A cat is a cat, antialiasing is antialiasing. A quick search with your favorite search engine will bring you the answer.

`OOOOOOR you figure a way to fully write out the true meaning of the buttons/checkboxes so no tooltips are needed`

**LMAO**
That's just what you did with your 10000 characters descriptions. A tooltip should be about 60/70 characters max. Just as in your Github comments. You could write a line and you write a book, that nobody will read but everybody will approve, because there are many lines. What a good politician.

`Seed: “Equal seeds lead to equal worlds. Enter non-negative integer here or leave empty for a random seed.”`

Who cares about "entering non-negative integer" ?
You've got a problem with explanations, you always want to explain everything to the users. The more you give them infos the less they will search. Also those infos are just boring and, say what, *not self-explanatory *for most of our users.

**Comment by Wuzzy2** [comment]
> Good subgames always have a creative mode. 

That's not my point. The question is what it does exactly. I have no idea what to write in a tooltip for this checkbox. So I ended up with … none.

>> Field for player name: Allowed characters. Maybe?

> Unuseful, 90% of the players don't care about it. 90% of the rest know what are the allowed characters.

OK.

> Science proved that 99.999% of the people in the world didn't know about UDP or TCP. If you consider such things important, read the docs.

Actually, no. Port forwarding is quite common in the Internet. Even if the average user does not want to learn about this shit, there's a chance the user has to. Otherwise the games won't work! Plain and simple. So the end user is exposed to terms like “TCP” and “UDP”. And it'll be a tooltip as short as “UDP port” (unless we change the label) ... If THIS is too long for you, then I can't help you.

> Seed: “Equal seeds lead to equal worlds. Enter non-negative integer here or leave empty for a random seed.”

Change that to:

“Equal seeds lead to equal worlds. Leave empty for a random seed.”
I just figured out the user can enter anything into this field, so this integer stuff can be removed.

> LMAO
> That's just what you did with your 10000 characters descriptions. A tooltip should be about 60/70 characters max. Just as in your Github comments. You could write a line and you write a book, that nobody will read but everybody will approve, because there are many lines. What a good politician.

Oh STFU please. I already tried to make a compromise here. I am no longer suggesting the long tooltips from the original PR.

> Should they ?
> A cat is a cat, antialiasing is antialiasing. A quick search with your favorite search engine will bring you the answer.

It would be great if the terms themselves would be self-explanationary but they aren't. We can't fix that because this is just how English works. But whether those terms have a tooltip is a different question.
You are falsely assuming the user is online at all times. Also, read the Wikipedia page(s) on anti-aliasing and tell me if this is understandable for the average Joe. I guess not. Third, the term “anti-aliasing” has multiple meanings, now the average Joe must find out which is the correct one. Besides, what is wrong with adding a single and *short* sentence as a mere *convenience*? It's, like, being nice to the user. :-)

> The more you give them infos the less they will search.

So … What's your point? Do you *want* Minetest to be unusable for the average user without searching a lot through the docs first?
I just wanted to give the info as a convenience. Also, does the Minetest Wiki already explain those settings, especially those specific to Minetest? As far I know, no. And even if, this works only as long the user is online …

Also, you are sending mixed messages. Now is it a good or a bad thing that I suggested tooltips for the settings?

**Comment by ObaniGemini** [comment]
Lol just found that I wrote that on an angry morning so this is some parts of the reason why I was so harsh :D

First point : if creative is modding side so it shall be available on mods side. Agree on your point.

Second point (port) : The users needing such infos are the server hosters, that SHOULD read the docs or ask question on IRC before making a server. This is not useful to know when you connect a server.

Third point (seed) : No explanation needed there, seed is way to much complicated to understand, tips might be more like a short definition. Not uesful there.

Fourth point : so change them...?

Fifth point : Not any games I know gives a desrciption of anti-aliasing because it's to hard to define, and easier to understand by testing it. At least for antialiasing it's easy to define as a tip but for normal maps ?...

Sixth point : I don't want Minetest to be unusable. Do you think Minetest is unusable without anti anti aliasing ? Also looking into the settings, players will see that option, and even if they don't know abou it will test it to see what it does. That's how a game works, no need of tons of explanations, they will understand by themself. You don't like at first a game for its graphics, or you're not a player.

Conclusion : well implemented in the right place, tool tips are a good idea :p

**Comment by paramat** [comment]
I think using tooltips for explanation is not a good idea. Any tooltip long enough to provide useful information will certainly be too long for a tooltip, because they will be non-optional this means large amounts of text will pop up every time a player hovers over a button.
Some would say 'don't hover over a button for more than a second', the fact is even an expernced user of software will often unconciously hover over a button, it just happens when using sotware in a relaxed way.
Even a beginner would find this visually irritating and doesn't want the information every time they are over a button.
Knowing that one must avoid hovering to avoid large amounts of pop-up text will itself make the menu more irritating to use, less relaxed and intuitive.
It's okay in Gimp because tooltips are used for icons, and are just 1 or 2 words confirming the tool you are about to use. Because the icons are graphical i still often like to have confirmation of what i am about to use.

So your desire to inform is much appreciated but i think you're going in the wrong direction, move all this useful and information into a help tab, then the text can be longer and more useful.
I think this should be closed, any other devs agree?

**Comment by Wuzzy2** [comment]
So you are opposed to tooltips even if they explain obscure abbreviations like “MP” for “modpack”?

**Comment by est31** [comment]
I have no issue with a tooltip "hide modpack content" on a checkbox "hide MP content", but I do object to tooltips of the form "This check box will allow you to hide the mods that are contained in a mod pack and only display the modpack's name instead of showing the full list of mods in the mod pack".

**Comment by paramat** [comment]
Better to relabel that to 'hide modpack content' than use a tooltip.

**Comment by est31** [comment]
@paramat yeah in the case of this checkbox that would be the better solution, as we have enough space for writing out "modpack".

**Comment by Wuzzy2** [comment]
I gave up on this PR because the resistance is too strong, and I am to lazy to put more time into it. If anyone wants to get this done, feel free to pick this up, but you are on your own now.

**Comment by paramat** [comment]
Ok perhaps we will keep this open for a while in case someone wants to take over, close in a month?

**Pull request closed without merging**
