### PR TITLE
Fix rapidly repeating footstep sounds

### LINKED ISSUE #1460: Footstep sound repeats on ladders (and rapidy in other situations)
When you hold shift on a ladder - you reached the bottom - then it plays the "footstep" sound again and again.

Low priority

### PR DESCRIPTION
**Pull request by random-geek**
Fixes #1460. (See [this comment](https://github.com/minetest/minetest/issues/1460#issuecomment-415388275) for explaination/alternate solution.)

With this fix, there's only one footstep sound upon reaching the bottom of a ladder, water, etc. instead of Minetest's iconic tap-dance "footstep fart."

The issue seems to be that `collisionMoveSimple` immediately returns a blank `collisionMoveResult` if the object's speed is zero. Even if the object is touching the ground, `result.touching_ground` is left false. My solution is to remove the speed check at the beginning, and instead only skip the collision-check loop if the speed is zero. This way, the value of `touching_ground` is always correct.

SmallJoker's proposed solution would also work, but it seems kind of hacky.

## To do

This PR is ~Ready for Review~ WIP.

## How to test

Try descending towards the ground while flying, swimming, or climbing on a ladder. Only one footstep should be heard when the player reaches the ground.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Note to reviewers: "Hide whitespace changes" is your friend. :)

**Comment by TheTermos** [comment]
The issue is about local player, but collision detection is done for all the objects, including all server side objects which don't care about sounds at all, so reorganizing collision detection just for this probably seems a little bit much.

Maybe it would be better to identify what exactly the cause is and fix it just for players?

Just quickly fooling around, I've been able to achieve decent results by changing this:
https://github.com/minetest/minetest/blob/0fc51db7722f9aa1e0aa2dacade6041c932b0731/src/client/game.cpp#L284-L287
to **0.4**

Chances are that's the reason why that timer has been put there in the first place, 0.03 is just way too short.

**Comment by paramat** [comment]
> The issue is about local player, but collision detection is done for all the objects, including all server side objects which don't care about sounds at all, so reorganizing collision detection just for this probably seems a little bit much.

I agree. The rapid footsteps problem is minor, i am concerned that this much change in code that is not directly related will cause unforseen bugs.
I prefer a simple fix even if it is not perfect.

**Comment by sfan5** [comment]
> SmallJoker's proposed solution would also work, but it seems kind of hacky.

His solution sounds better to me actually. If the client code calls `collisionMoveSimple` multiple times it should also handle its return values correctly.

> Just quickly fooling around, I've been able to achieve decent results by changing this [...] to **0.4**

This causes the player to make far too few footsteps when running quickly.

**Comment by random-geek** [comment]
I agree that changing collision code is dangerous, but it bothers me that `touching_ground` doesn't really mean that the object is touching the ground. Could it be changed to something else, e.g. `collided_with_ground`?

**Comment by SmallJoker** [comment]
What if you would:
1) set `LocalPlayer::touching_ground = false` before the physics calculations
2) OR `touching_ground` with the moveresult of each step?

This means the sound will be played the first time the player collides, than the state is kept until the next step occurs.

**Comment by random-geek** [comment]
`touching_ground` affects stuff like sneaking and jumping too, so there's a chance of breaking things either way.

**Comment by TheTermos** [comment]
Guys, there's no need of tampering with touching_ground.

SmallJoker got it right two years ago, the answers are in ClientEnvironment::step() in the loop around 193.
There are two problems:
- the loop is so dumb so it keeps going even when speed goes zero (this is possible only when `free_move` or `is_climbing` or gravity is off) hence the empty executions of move() and empty moveresult. It should break out of the loop as soon as speed goes 0,0,0
- controls are applied only once so they affect only the first loop run, they should be applied in the loop.

Personally I'd try more radical approach and ditch the loop altogether, it probably does nothing good, unless we're concerned with clients running 10fps.
I tried bypassing the loop by setting `dtime_max_increment = 0.5`. Farting was gone, everything else went on as normal.

**Comment by sorcerykid** [comment]
Just wanted to reference a related issue #2974.

**Comment by random-geek** [comment]
A similar phenomenon occurs when sneak-running on a fencepost. (Not referring to the faster-than-usual footsteps when walking on a fence, this is different.)

**Comment by random-geek** [comment]
A third solution would be to only update `touching_ground` if the player's speed is zero. Unfortunately, it doesn't solve the fencepost sneak-running phenomenon, but it seems to fix all the other issues.

**Comment by TheTermos** [comment]
> A third solution would be to only update `touching_ground` if the player's speed is zero.

This one is even worse than the original, such a change would be actively harmful.
Please everyone, leave `touching_ground ` alone, it isn't the cause of rapidly repeating sounds.

**Comment by random-geek** [comment]
> This one is even worse than the original, such a change would be actively harmful.
Please everyone, leave touching_ground alone, it isn't the cause of rapidly repeating sounds.

@TheTermos Sorry, I meant to say "When the player's speed is *not* zero." I assume that's why you say it would be actively harmful?

**Comment by random-geek** [comment]
<details>
<summary>Fencepost sneak-running bug explaination</summary>

The fencepost bug I mentioned is different. It seems to happen when `collisionMoveSimple` "overshoots" the node and returns `result.touching_ground = false`. Then `LocalPlayer::move` constrains the player's position to be on top of the node (since the player is sneaking) and sets the speed to zero. On the next step, the horizontal speed is zero, so `collisionMoveSimple` returns `result.touching_ground = true`. Thus, oscillation. The same thing occurs if you sneak-run on a regular node with a torch or plant placed beside it.
</details>

I can see now that changing collisionMoveSimple is probably unnecessary (at least for the fixing the original issue). With all this in mind, what is the best way to proceed?

**Comment by TheTermos** [comment]
> Fencepost sneak-running bug explaination

Sneak is a separate issue, it's all kinds of broken, it largely relies on bypassing collision detection and setting player position arbitrarily.

> what is the best way to proceed?

I'd try the following two modifications:
https://github.com/minetest/minetest/blob/083b285f4319c470f307f0b52f03a2fb68facd38/src/client/game.cpp#L287
Change it to 0.4. 
Why? Because max duration of grass footstep sfx in MTG is 0.4 and it is shorter than the time interval between 2 consecutive head bobs which generate footstep sound.

https://github.com/minetest/minetest/blob/083b285f4319c470f307f0b52f03a2fb68facd38/src/client/clientenvironment.cpp#L179-L180
Change it to 0.05
Why? Because minimum 100 moves per second is overkill and kills framerate on low end and mobile. (e.g. at around 10 fps there are 10-11 moves per frame)
20 seems to allow to perform the same jumps as 100, much lower than that it starts to deteriorate quickly, around 11 mps player can't jump a full node, around 3 jumping stops working altogether. 
(note: multiple moves per frame only make a slight difference for accelerated movement like jumping, otherwise it's a waste of cpu cycles most of the time).

The result: 
fps >=20 it's one move per frame, no repeating whatsoever.
fps < 20 some repeating, but no farting because of increased interval
plus significantly improved client performance, two birds with one stone.

**Comment by sfan5** [comment]
> Change it to 0.4.
> Why? Because max duration of grass footstep sfx in MTG is 0.4 and it is shorter than the time interval between 2 consecutive head bobs which generate footstep sound.

As I've said before in this issue: This causes the player to make far too few footsteps when running quickly.

> plus significantly improved client performance, two birds with one stone.

How significant is this?

**Comment by TheTermos** [comment]
> This causes the player to make far too few footsteps when running quickly.

As in faster than default, with speed overridden?
0.4 isn't a strong suggestion, if it's too slow then it should be sped up within reasonable boundaries, 0.2 for example should also make the farting sensation go away.

> How significant is this?

The principle is the slower the framerate -> the more moves per frame -> the higher cpu usage per frame - > the slower the framerate,
so unless the cost of LocalPlayer::Move is insignificant compared to everything else, this has to be a problem at slow fps.

**Comment by sfan5** [comment]
> As in faster than default, with speed overridden?

No. Open a minetest_game world, grant yourself `fast` and hold E; you will find that 0.4 is too high.

**Comment by TheTermos** [comment]
> No. Open a minetest_game world, grant yourself `fast` and hold E; you will find that 0.4 is too high.

It is, 0.2 seems adequate for that particular feature.

> This is the big question here which should ideally be benchmarked.

I guess it should, I think I've seen some timetaker facility in the code somewhere,
apart from that it's a good idea to try and not to use more resources than necessary.

**Comment by paramat** [comment]
Since repeating footsteps is a minor issue rarely triggered, i suggest, for now at least, just increasing the step timer. Simple and low risk.

**Comment by random-geek** [comment]
@paramat Why not update `touching_ground` only when the player is moving? It's about as simple as any solution, and seems pretty safe (the speed won't be zero in most cases). Plus, it doesn't result in footsteps when the player isn't moving. The sneaking issue can also be solved by setting `touching_ground = true` when the sneak code overrides the player's position.

**Comment by sfan5** [comment]
I do not understand all this discussion about alternative solutions when one has been proposed 2 years ago: https://github.com/minetest/minetest/issues/1460#issuecomment-415388275

**Comment by random-geek** [comment]
I tested SmallJoker's solution, and it turns out the player can jump twice as high as usual in certain circumstances, since `touching_ground` is reset in `move`, after `applyControl` has already been called. It might be possible to work around this (reset `touching_ground` after the loop in `ClientEnvironment::step`?) but it might be messy and/or cause other bugs.

**Comment by paramat** [comment]
I do not oppose the other more complex solutions, but they are more risky, and for a very minor issue.
So i suggest considering the simple and zero-risk solution.

**Comment by TheTermos** [comment]
> I do not understand all this discussion about alternative solutions when one has been proposed 2 years ago: [#1460 (comment)](https://github.com/minetest/minetest/issues/1460#issuecomment-415388275)

Probably because that solution hasn't materialized for 2 years.
Also it certainly isn't the best possible solution, the cause is in clientenvironment.cpp and ideally should be solved there.

The sole cause is that controls are applied only before the first move in a step, so if we're lucky (that is the code hasn't adapted to this bug ) all it takes is to move the applyControl() call from  client.cpp to clientenvironment.cpp in the loop at 194, every other solution is a workaround.

I made the modification as of writing this reply, 
1. comment out this one:
https://github.com/minetest/minetest/blob/58f523e363099d377d2927f16244073d104c07e9/src/client/client.cpp#L465
2. insert the following in clientenvironment.cpp after 220:
`lplayer->applyControl(dtime_part, this);`

This fixes the problem and no obvious immediate issues so chances are this is it, needs testing though.

**Comment by sfan5** [comment]
> Also it certainly isn't the best possible solution, the cause is in clientenvironment.cpp and ideally should be solved there.

Of course not, the ideal solution here would be to remove the dtime look stuff around LocalPlayer::move.

> The sole cause is that controls are applied only before the first move in a step, so if we're lucky (that is the code hasn't adapted to this bug ) all it takes is to move the applyControl() call from client.cpp to clientenvironment.cpp in the loop at 194, every other solution is a workaround.

That raises the question of whether it's correct to apply controls multiple times per step to which I'd say, probably not.

<hr />

Here's @SmallJoker's suggested solution and from what I can tell it works just fine:
```diff
diff --git a/src/client/clientenvironment.cpp b/src/client/clientenvironment.cpp
index 6840f2db3..9e212809f 100644
--- a/src/client/clientenvironment.cpp
+++ b/src/client/clientenvironment.cpp
@@ -189,6 +189,8 @@ void ClientEnvironment::step(float dtime)
                Stuff that has a maximum time increment
        */
 
+       bool actually_touching_ground = false;
+
        u32 loopcount = 0;
        do
        {
@@ -256,9 +258,12 @@ void ClientEnvironment::step(float dtime)
                        */
                        lplayer->move(dtime_part, this, position_max_increment,
                                &player_collisions);
+                       actually_touching_ground |= lplayer->touching_ground;
                }
        } while (dtime_downcount > 0.001);
 
+       lplayer->touching_ground = actually_touching_ground;
+
        bool player_immortal = lplayer->getCAO() && lplayer->getCAO()->isImmortal();
 
        for (const CollisionInfo &info : player_collisions) {
```

**Comment by TheTermos** [comment]
> the ideal solution here would be to remove the dtime loop stuff around LocalPlayer::move.

Only if we accept variable player jump performance depending on fps. I gave a few examples already, another one: at 21fps player can jump a 3 node gap, at 20 he can't.
If we do accept it then by all means, that was my suggestion too.

> That raises the question of whether it's correct to apply controls multiple times per step to which I'd say "probably not".

That raises the question of why that raises the question for you.
The purpose of multiple moves per step is to increase resolution, as if it always were at least 100fps, but every move is suspect to the same laws, the first one isn't any different, and controls can't be released mid step.
It's not only about soundfart, for example that's one of the reasons why in the last couple of versions false positive player collisions were so apparent at low fps - because after the collision player kept going sideways for a few moves as if controls in that direction were released.

Controls should be applied to every move for same reasons why they should be applied every frame when there's only one move per frame, that's pretty obvious stuff.

> Here's @SmallJoker's suggested solution and from what I can tell it works just fine:

'actually' touching ground ;) It sure might work.
MT code already looks like Frankenstein monster, does it need another stitch?

**Comment by sfan5** [comment]
> That raises the question of why that raises the question for you.

I don't know, intuition I guess.
But as you've explained I am wrong about this (and the dtime loop too), which is good because then we have a 100% good solution.

>  MT code already looks like Frankenstein monster, does it need another stitch?

When you want to fix a bug close to release without accepting unknown implications of a different fix, then yes I'd say it "needs another stitch".
Nothing prevents the fix being replaced with a proper one later, which is the obvious thing to do.

**Comment by random-geek** [comment]
I tested sfan5's solution, and it works for me, although it isn't quite the same as SmallJoker's solution. It doesn't have the double-jumping problem (at least, not that I noticed), but it also doesn't fix the sneaking issue.

Perhaps it be better to wait until after the release and try to implement a better solution, since this isn't a debilitating issue?

Here's my idea for reference:
```diff
@@ -333,7 +333,10 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,
                Player is allowed to jump when this is true.
        */
        bool touching_ground_was = touching_ground;
-       touching_ground = result.touching_ground;
+
+       if (initial_speed.getLength() != 0)
+               touching_ground = result.touching_ground;
+
        bool sneak_can_jump = false;

        // Max. distance (X, Z) over border for sneaking determined by collision box
@@ -359,6 +362,8 @@ void LocalPlayer::move(f32 dtime, Environment *env, f32 pos_max_d,

                // (BS * 0.6f) is the basic stepheight while standing on ground
                if (y_diff < BS * 0.6f) {
+                       touching_ground = true;
+
                        // Only center player when they're on the node
                        position.X = rangelim(position.X,
                                bmin.X - sneak_max.X, bmax.X + sneak_max.X);
```

**Comment by TheTermos** [comment]
> When you want to fix a bug close to release without accepting unknown implications of a different fix, then yes I'd say it "needs another stitch".

Oh dear, is it close to release again?

Aren't the stitches one of the reasons why modifications tend to have unknown implications in the first place? That obviously happens when the code is full of hacks that mean to solve problems in distant parts of the code and don't make logical sense where they are. 
My opinion is introducing such solutions only because some release date coming near is evil (maybe even worse than trailing whitespaces ;)) we'd better off leaving the bug be.

Also I can't help but notice that you seem to assume the hack won't have any unknown implications, or maybe you know every occurence of touching_ground and can foresee all the side effects, I don't know.

**Comment by sfan5** [comment]
> Oh dear, is it close to release again?

There is no decided date yet, but somewhat yes.

> My opinion is introducing such solutions only because some release date coming near is evil (maybe even worse than trailing whitespaces ;)) we'd better off leaving the bug be.

That's also a reasonable alternative, since this bug is nowhere near critical.

> Also I can't help but notice that you seem to assume the hack won't have any unknown implications

The reasoning here is as follows:
* `touching_ground` is set correctly before and after `LocalPlayer::move()` calls (previously it was set to false erroneously)

vs.
* every variable touched by `LocalPlayer::move()` is potentially different before and after calls to it, `move()` may also behave differently since intermediate variables are different

**Comment by paramat** [comment]
:-1: 
It is wrong to make such huge changes to collision code, which affects everything, for a very minor sound bug that is only an issue for the local player. Especially when an alternative and very simple zero-risk fix is possible.
To much risk of creating far worse unforseen problems in highly critical movement behaviour.
Seems controversial to other core devs too.

**Comment by random-geek** [comment]
😕 We had already ruled out the idea of changing collision code. I didn't commit anything because there was no consensus on what to do.

I'd still like to see a real fix for this bug, because it's probably one of the most common (and annoying) bugs in the game.

**Pull request closed without merging**
