### PR TITLE
Autogenerate settings header

### LINKED ISSUE #6454: Settings performance
Settings performance is not very optimal due to a too generic backend using strings.
it's nice for mods to help them store settings, but it's totally unoptimal in core engine and needs to add caching variables everywhere to solve performance issues.

In my old fork, 2 years ago, i added a new generic + specific backend to store settings which improved massively performance, using a simple std::array per setting type with enum KEY permitting to select setting value directly. I suggest to backport my backend to MT to improve setting fetch performance

Implementation is something like this

```
enum u32setting: u8 {
U32SETTING_MAX_USERS,
U32SETTING_MISC_SETTING,
...
U32SETTING_MAX
};

Settings:get(u32 k) 
{
  assert(k < U32SETTING_MAX);
  return m_u32_setting[k];
}

u32 max_users = g_settings->get(U32SETTING_MAX_USERS);
```

There is no translation, no map, just a direct access to the value

### PR DESCRIPTION
**Pull request by numberZero**
The generated header (`settings_builtin.h`) ~looks like:~ *is included in the PR code.*

Currently there are some settings with non-ID names (containing dots, hyphens); that’s not really a problem but is annoying a bit. But there is also a setting present in 2 categories: `serverlist_url`. That’s really strange.

@nerzhul Does this look like a way to fix #6454 ?

### CODE REVIEW

**Comment by nerzhul** [comment]
@numberZero it's a format way to fix it yes, less generic and flexible than my backend but more accurate. The only thing you should fix is you should use std::atomic_bool and some atomics shared between main thread and other threads.
Don't forget we always need the highly generic interface for mods and a conversion model between this and lua as lua can lookup general settings

**Comment by numberZero** [comment]
> Don't forget we always need the highly generic interface for mods and a conversion model between this and lua as lua can lookup general settings

Of course.
My plan is to make that structure constant and update it only through the generic interface (using some hooks).

> you should use std::atomic_bool

That’s not a problem, for bools and ints; although the performance may be lower than with non-atomic values, using `relaxed` memory order should reduce the hit. But what’s about strings? Do you want me to write atomic strings? That’s possible, and may even be rather performant using a variation of the copy-on-write technique, but is that really the right way? Many settings can’t be sensibly changed at runtime at all.

**Comment by rubenwardy** [comment]
I'm wondering if it would be possible to have CMake generate this somehow when configuring the project, and then have the file ignored

**Comment by numberZero** [comment]
@rubenwardy CMake can use any tool to generate a file, including project-supplied tool. Thus that is perfectly possible.

**Comment by numberZero** [comment]
Should work.

**Comment by numberZero** [comment]
Guess what? #6766

**Comment by numberZero** [comment]
@nerzhul This seems to work fine now.

**Comment by numberZero** [comment]
@rubenwardy It appears to be not that easy to make CMake generate everything. While that’s certainly possible, I feel that should be in a PR of its own. I opened an issue #6851 for that.
@nerzhul Should I add anything to this PR?

**Comment by numberZero** [comment]
Rebased&updated.
5d242c3 adds the new settings system.
2123c6d adds the autogenerated files to the repo.
Everything else replaces g_settings->get* calls with builtin_settings.* reads.

**Comment by numberZero** [comment]
This PR seems to be too large. Should I split it?
Note that the main part is finished; it consists of 5d242c3 and 2123c6d. 5e6ceaf is rather important as it fixes duplication, and ec3a8a2 fixes some cases where restart was needed to change a setting. Others are, basically, find&replace, not changing behavior.

**Comment by SmallJoker** [comment]
The PR looks promising but I haven't looked at the implementation yet.
Can different default values be set for Android and Windows if required?

**Comment by numberZero** [comment]
@SmallJoker Not directly. Default values are set in the `settingtypes.txt` file, as before. Although some magic could be implemented for that, but that’s certainly out of scope of this PR.

**Comment by paramat** [comment]
I'm guessing this was too big and too difficult to rebase.

**Comment by numberZero** [comment]
This PR isn’t that big, largest files are autogenerated. These files
shouldn’t be in the repository, of course, but that’s the way it’s done
currently with e.g. `minetest.conf.example`.

The reason for close is that it wouldn’t be merged in any foreseeable
future anyway. I don’t drop the code, though, and it should always be
possible to resurrect the idea.

**Pull request closed without merging**
