### PR TITLE
[no sq] Add unit tests for collisionMoveSimple

### PR DESCRIPTION
**Pull request by sfan5**
let's not introduce silly regressions again

note: the tests will stay broken until #15375 /  #15381 is fixed.

### CODE REVIEW

**Comment by kno10** [comment]
Does the test also check that we do not hit the `collisionMoveSimple: Loop count exceeded, aborting to avoid infinite loop` case? It seems that #15378 is not yet enough to fix this completely:
https://github.com/minetest/minetest/pull/15378#issuecomment-2463445610

**Comment by sfan5** [comment]
Added.

**Comment by kno10** [comment]
Thank you. Does the test pass on 5.9.1? It may be worth including a test for the issues (bouncyness, incorrect speed, etc.) we were trying to fix, too.

**Comment by kno10** [comment]
#15408 passes these tests.

**Comment by kno10** [comment]
Can you add the following test setup, to down view, best also with xz flipped or even all rotations.
```
##   #/
/o   #o
```
where `o` are the moving object, `#` is a wall and `/` are suitable stairs, and the velocity + acceleration is diagonal, so that the object collides with the wall and the stairs instantly and at the same time. To pass the test, the object should step up the stairs.

**Comment by sfan5** [comment]
I do not plan to extend the tests in this PR. It's only supposed to cover basic stuff.

> Does the test pass on 5.9.1?

It does not, since the old versions calculates acceleration incorrectly.

**Review by SmallJoker — APPROVED** [review]
Looks good and works.

**Review by SmallJoker — APPROVED** [review]
Works, looks good and makes sense. That's a nice cleanup.

**Pull request merged**
