### PR TITLE
Dual Wielding: A Prototype

### PR DESCRIPTION
**Pull request by LizzyFleckenstein03**
The goal is to give minetest players the ability to make use of two hands. The concept used here is similar to how dual wielding works in the "other" famous Voxelgame.
See issue #10345.

## To do

This is a prototype. To determine whether the second hand should be used, only node_placement_prediction is taken into concern. Also, there is no way for the server to detect whether the client supports dual wielding or not.

## How to test

You need to activate the second hand via Lua API (by simply creating the left_hand list and giving the player a way to access it):
```lua
minetest.register_on_joinplayer(function(player)
	player:get_inventory():set_size("left_hand", 1)
end)

minetest.register_chatcommand("swap", {
	description = "Swap items in left and right hand.",
	func = function(name)
		local player = minetest.get_player_by_name()
		local inv = player:get_inventory()
		local wield = player:get_wielded_item()
		player:set_wielded_item(inv:get_stack("left_hand", 1))
		inv:set_stack("left_hand", 1, wield)
	end
})
```

### CODE REVIEW

**Comment by EliasFleckenstein03** [comment]
Any thoughts? Any idea to check whether a rightclick handler was registered or not?

**Comment by LoneWolfHT** [comment]
I'll be trying this out in a few weeks but I don't have the time atm. I'll probably have suggestions then

**Comment by kilbith** [comment]
Demo: https://youtu.be/rka0C9d9h-A

**Comment by EliasFleckenstein03** [comment]
> Demo: https://youtu.be/rka0C9d9h-A

https://www.elidragon.com/member/Fleckenstein/dual_wielding.webm

**Comment by hecktest** [comment]
Bloat.
What exactly does this do that I can't already do in lua? Look, custom inv lists for equipment slots. A whole 21 of them. What makes the left hand special, other than Minecraft having it?
invlists

The only actual feature this adds is the left hand in the hud. That should be a hud feature. Proper viewmodels will still make it obsolete.

**Comment by EliasFleckenstein03** [comment]
For example if you have a tool in the right hand and building blocks in the other, the tool is used when you try to dig a block and the building blocks when you use them. This can become very handy for mining by having the torches in the one hand and the pickaxe in the other - that way you don't need to always change the wield index.

**Comment by EliasFleckenstein03** [comment]
And to be honest: I think that "Minecraft has that feature" is actually a proper reason. Players are less likely to choose the Open Source to something if it lacks features and it's only advantage seems to be being Open Source. In my opinion the only way for Minetest's community to grow to a size where 10 players online on a single server is not considered a lot by making it possible to implement all Minecraft features using a subgame. Most voxelgame players prefer Minecraft, therefore we should offer everything that Minecraft supports (not mandatory, but it should be at least possible) if we really want to attract new players.

**Comment by EliasFleckenstein03** [comment]
So, is anyone gonna comment on this further? Like I said, I'm kinda stuck as I don't know how to detect whether the item has a rightclick callback.

**Comment by LoneWolfHT** [comment]
I grab item nodedefs in my PR this way: https://github.com/minetest/minetest/pull/9441/files#diff-780cb5145d57633f7f77ad2c0a9be785f9712af8a2b34af4e2114f016545526bR317

**Comment by hecktest** [comment]
And what if the tool in the right hand has an RMB action already defined? Which one takes priority? What if I need to flip this priority? What if I need to do that on an individual basis, for some items but not for others? There's a ton of logical problems with just bolting on a second main slot to an already established control scheme. A feature this impactful needs some serious thinking, and none has been done here so far.

Someone just told me that MC does not have right mouse button support for the right hand tool. I guess this explains the lack of forethought about this. In that case, **you can already emulate Minecraft's behavior with pure lua code**. All you need is a viewmodel feature to show the left hand in first person. Imagine a situation where that is implemented, but this "left hand" is too, and now it can't be deleted because oh no, it'll break someone's minecraft clone.

This feature is poorly thought out and its motivation is nearsighted. #10345 #10588 #10666 There's been a wave of "please port XYZ from Minecraft" requests with no regard for long term consequences, and no effort to try and use the existing tools before jumping to engine changes. We are still being bitten in the ass by tech debt from the earlier hardcoded features, the last thing you want to do is add more of that to the pile.
Next thing someone is gonna ask for engine support for shields, and someone is gonna hardcode that without thinking twice about it. Then it's gonna be handheld treasure maps, and some idiot is gonna demand that as well. Why stop there, let's make a hardcoded sprint key because Minecraft does it, complete with that silly fov effect. Let's just lobotomize ourselves and replace every subgame with Minecraft, because this is what squeaky Discord users demand from us in 2020.

**Comment by kneekoo** [comment]
@hecktest Regarding #10588 #10666 - no one suggested to hardcode anything and no one's throwing a fit here over what Minetest has to become. The hostile way you react is unjustified. You can't assume that everyone leaving feedback here is fully aware of the engine's capabilities and that they're trying to push some agenda. The developers can easily reject or postpone anything until it makes sense for something to be implemented. The devs can easily say: _we won't implement this_ or _we need to get rid of some old code before anything, so this will be reevaluated at that time_.

Regarding this issue, having torches in the left hand, while mining, is great - not only to place a torch without switching slots, but also to have it as a light source - which is useful even when navigating at night or in mine shafts, ravines, etc. Carrying a shield in the Nether or some dangerous place is also useful at times.

As a player, all I can hope is that the Minetest-based games will add it. This looks like an attempt to support the feature from the engine itself. **Good or bad** an idea, only the Minetest devs know, but there's no reason to hate, out of principle, Minecraft or requests based on stuff that exists in that game. The Minetest Game (and engine itself) replicates a lot of what Minecraft offers - even mechanics that make no sense in the real world. I can understand why the developers would veer off from certain design/behaviour decisions if it's about possible legal issues with Mojang/Microsoft, if such a thing would be possible, but [Minecraft didn't invent everything](https://notch.tumblr.com/post/227922045/the-origins-of-minecraft), and they also made changes and additions based on community feedback (and keep doing it) throughout the years. The devs always have the final say, but useful features shouldn't be disregarded just because they were _not invented here™_.

**Comment by EliasFleckenstein03** [comment]
@hecktest I'm a bit annoyed because I opened an issue to ask whether dual wielding for the engine is wanted before I started doing anything, and now after I've made it I'm getting offended for not giving it enough thought and that what I've done is not necessary at all. I literally asked whether the community does want it! And now, after I'm done with the biggest part you just tell me "the idea of this sucks".

**Comment by LoneWolfHT** [comment]
> And what if the tool in the right hand has an RMB action already defined? Which one takes priority? What if I need to flip this priority? What if I need to do that on an individual basis, for some items but not for others?

Minecraft has a key that swaps the wield-item with the secondwield-item. I think this is a good approach.
One way we could do ^ is add on_keypress to the MT API, add aux2 to allow modders to bind more things to keys/buttons (in the case of mobile). Then set up some disable-able (via lua) lua code in `builtin` that swaps the secondwield-item with the wield-item on aux2

> Someone just told me that MC does not have right mouse button support for the right hand tool. I guess this explains the lack of forethought about this.

In Minecraft I press F, rightclick, and press F again.

> Next thing someone is gonna ask for engine support for shields.

Shields will already be possible if this PR is added.

> Why stop there, let's make a hardcoded sprint key because Minecraft does it, complete with that silly fov effect.

Already have the hardcoded sprint key, aux1 (Haven't seen any other use for it). The fov effect is also already easily added

**Comment by runsy** [comment]
LOL. Not only Minecraft, but Hytale has this feature. It's not original of course, because ALL sword fighting games implement it indeed, not only Minecraft, let's say it's a standard. What you have to ask yourself is: should Minetest have it?

Actually yes: Torches, shields, drums, double swords...

**Comment by EliasFleckenstein03** [comment]
Also, Minetest has already taken a lot of concepts from Minecraft anway. Placing / Interacting with RMB, Hitting / Digging with LMB, the complete Inventory concept etc.

**Comment by EliasFleckenstein03** [comment]
Crap, sometimes I really hate git.

**Pull request closed without merging**
