### PR TITLE
WIP: Convert Docs To Markdown, Improve Navigation and Linking

### PR DESCRIPTION
**Pull request by benrob0329**
# Goal of the PR
To convert the half-markdown docs to actual, navigable GHF Markdown.

# How does the PR work?
I spend hours in a text editor manually reviewing and reformatting the docs section-by-section. Any sections linked in the TOC are "done" (they will be improved with feedback). I am **not** rewriting the contents of these sections, although I can see areas that could use some work it's Out Of Scope :tm: 

# Does it resolve any reported issue?
Lots, but none in particular? I'd rather not link the plethora of lua_api.txt issues just to have none of them quite be the reason for this PR.

# If not a bug fix, why is this PR needed? What usecases does it solve?
People have been complaining about the half-assed feel that the sort-of but not really formatted docs have for years. This PR aims to improve the overall navigation of it, and the readability in rendered mode (although many areas also have better text-only readability as well IMO).

Some advantages of rendered markdown:
* It looks better, and can better take advantage of the screen space
* Source code blocks get highlighting
* Permalinks, not just line-linking (which cannot be relied on long-term) but actual links to defined sections and areas
* Inner-linking between sections, meaning that readers can go directly to the part of the document where something is explained instead of just Ctrl+F'ing for it
* Table Of Contents, and sub-TOCs for individual sections for better navigation
* No need to host the docs elsewhere for improved usability

# To do
- [ ] Fully Reformat Other (non lua_api) Docs
- [ ] Make all parameters `h4` elements for linking
- [ ] Actually hyperlink section references
- [ ] Re-convert tabs -> spaces
- [ ] Make important examples linkable

## How to test
Look at the rendered version (and source) of the API docs, report issues with navigation and formatting.

### CODE REVIEW

**Comment by v-rob** [comment]
Welp, changing it to `lua_api.md` is going to force basically all PRs to rebase.  Oh well, I can see the benefit.

**Comment by benrob0329** [comment]
I'm not sure how to convert these to tables, considering Markdown doesn't have a good way to make a left-side label. Any ideas are appreciated.

-----

Table of resulting digging times:

|                 | level | 0     | 1    | 2    | 3    | 4   |
| ---------------:| -----:|:----- |:---- |:---- |:---- |:--- |
|     **crumbly** | **0** | 0     | -    | -    | -    | -   |
|                 | **1** | 0.80  | 1.60 | 1.60 | -    | -   |
|                 | **2** | 0.60  | 1.20 | 1.20 | -    | -   |
|                 | **3** | 0.40  | 0.80 | 0.80 | -    | -   |
|                 |       |       |      |      |      |     |
| **level diff:** |       | 2     | 1    | 0    | -1   | -2  |

Table of resulting tool uses:

| crumbly | level |     |     |     |     |
| ------- | ----- | --- | --- | --- | --- |
| 0       |   -   |  -  |  -  | -   | -   |
| 1       | 180   | 60  | 20  | -   | -   |
| 2       | 180   | 60  | 20  | -   | -   |
| 3       | 180   | 60  | 20  | -   | -   |

**Comment by SmallJoker** [comment]
Please don't rename the files to `*.md`. In #7028, #5451 and #6707 it was decided that the file extension should be kept to ease access for Windows users, and to link specific lines in the web interface.
Also avoid the GitHub notation (```lua, for example) to display code correctly on regular Markdown readers. See https://github.com/minetest/minetest_game/pull/2624#issuecomment-604622923 for more information.

**Comment by benrob0329** [comment]
> .md disables being able to link to a line, needed daily when
quickly referring people to particular lines.

You don't need to link a line when you have explicit hyperlinks to sections and properties readily accessible.

> Search returns results in .md files, but you cannot then click
the line number to go to that line in the document, making searching
difficult.

I'd test this, but Github's search doesn't seem to work at all for me. I always use Ctrl+F, but if someone could test this who actually uses Github search that'd be great.

> Line numbers are not displayed for .md documents.

Redundant with the first issue and not a problem if you aren't linking by line numbers (which you shouldn't be because those links become unusable the moment the document changes)

> Also avoid the GitHub notation (```lua, for example) to display code correctly on regular Markdown readers.

Considering the _massive_ readability improvements having code highlighting gives, the fact that this project is hosted _on_ GitHub for the foreseeable future (and all alternative platforms I know of support the notation), and that I've never seen a Markdown viewer that didn't support the tripple-backtick notation, this feels like a really dated restriction without any examples of situations where this would actually be a problem.

**Comment by rubenwardy** [comment]
Markdown isn't standardised and most markdown editors I use support code fences. If they don't, then the worst that will happen is "lua" appearing on the first line

Linking to specific lines is terrible, and compatibility on windows can be helped by renaming the file automatically in windows builds

**Comment by benrob0329** [comment]
Is it really that hard to rightclick on the file, select "Open With", clicking on your text editor/markdown viewer of choice (checking the box to remember the application) and just carrying on with life? Its not like any potential modder will be free from having to edit Markdown files just because our docs are txt files.

Heck, most people just reference them online anyways. I fail to see any hurdle a Windows user would need to make that isn't regular old Windows stuff that I've been doing since I was like 8.

**Comment by paramat** [comment]
> Please don't rename the files to *.md

I agree. .md extension makes these files very difficult to work with and develop, as explained in the linked issues. I will disapprove this PR if .md is used.
> You don't need to link a line when you have explicit hyperlinks to sections

I need to link to specific lines very often, a hyperlink to a section is not good enough as sections can be large.
> if someone could test this who actually uses Github search that'd be great.

I tested again. Try to go to line 129, it just goes to the whole document:
https://github.com/minetest/minetest/search?q=Compiling+on+GNU%2FLinux&unscoped_q=Compiling+on+GNU%2FLinux
> Line numbers are not displayed for .md documents.

To explain further: So that on Github one can no longer click the line number to get a permalink (link does not break when document changes) to that line. This is needed very often.

It is easy to view a MD-formatted .txt file in MD form, but it is not easy for developers to avoid the problems caused by a .md extension.
I understand the benefit to users, but please remember that helping developers is also very important, especially as we are unpaid volunteers with very little time, and are overwhelmed in an understaffed project. We need all the help we can get.

**Comment by rubenwardy** [comment]
> I agree. .md extension makes these files very difficult to work with and develop, as explained in the linked issues

An .md file is easier to maintain than one in .txt format - I'm unsure if that's what you meant by "work with and develop"

**Comment by benrob0329** [comment]
> I agree. .md extension makes these files very difficult to work with and develop, as explained in the linked issues. I will disapprove this PR if .md is used.

This is rather unhelpful and vague, not to mention I've already replied to the highlights in the linked issues.

> I need to link to specific lines very often, a hyperlink to a section is not good enough as sections can be large.

https://github.com/benrob0329/minetest/blob/md_api/doc/lua_api.md#paramtype--light

_Look at that_, I can link to a specific paramtype argument. This is because I can place these permalink-able headers anywhere, and they won't be tied to a specific version of the document.

> I tested again. Try to go to line 129, it just goes to the whole document:

Yes it seems Github still has an issue with it's search. Has anyone reported this bug? I can still just use the browser/viewer search but it is annoying if searching a whole repo (which I don't do from the web interface but can understand the use). I don't think this is enough to warrant a disapproval considering there are tons of other ways to search these files and using MD has several advantages while still allowing those who prefer it to view the raw text (with syntax highlighting in many editors to-boot!)

Other than the search issue (which can easily be worked around), I fail to see navigation and linkage issues which cannot be fixed by this PR (which is, in-fact the entire reason this PR exists).

**Comment by rubenwardy** [comment]
Closed due to merge conflicts and controversial nature. I suggest doing the work in txt form, and finding a way of fixing concerns when moving to .md form

**Pull request closed without merging**
