### PR TITLE
Make `minetest.write_json` use "[]" instead of "null" for empty tables

### PR DESCRIPTION
**Pull request by Desour**
- Problem:
  `minetest.write_json` writes `null` for empty tables. When parsed back to lua via `minetest.parse_json`, it results in `nil`.
  This can be considered a bug because empty tables are not equivalent to `null`.
- Fix by this PR:
  It writes `[]` instead.
  (`{}` would work too. I've chosen `[]` because empty arrays are probably more common than empty dictionaries.)

## To do

This PR is a Ready for Review.

Should I add a flag to `minetest.features`? Edit: Probably useless as mods can easily test.

## How to test

- `//lua print("'"..assert(minetest.write_json({})).."'")`
  master: `'null'`
  PR: `'[]'`
- `//lua print("'"..assert(minetest.write_json({{}})).."'")`
  master: `'[null]'`
  PR: `'[[]]'`

### CODE REVIEW

**Comment by rubenwardy** [comment]
There's no way to know if it should be `[]` or `{}`.  Inserting null is equally wrong in both situations, so is probably the best output

**Comment by SmallJoker** [comment]
`fastWriteJson` (MT) uses the class `BuiltStyledStreamWriter` from JsonCPP which properly serializes empty arrays in `BuiltStyledStreamWriter::writeArrayValue`.

So this issue is indeed in Minetest, but wouldn't it be better to specify `dropNullPlaceholders` here?

https://github.com/minetest/minetest/blob/837cea6b4a2315966b9670ae50cff9d3679bcff4/src/convert_json.cpp#L26-L32

**Comment by Desour** [comment]
To explain the implementation change a bit:
`read_json_value` is used by (and (apart from recursion) only by) `minetest.write_json`, which gives a default initialized (value-type defaults to null) `root`:
https://github.com/minetest/minetest/blob/837cea6b4a2315966b9670ae50cff9d3679bcff4/src/script/lua_api/l_util.cpp#L143-L145
For tables, `read_json_value` iterates through the table and uses an array if it finds a number key, and a dict if it finds a string key. If the table is empty, the value-type of root remains null. (Maybe the special case of empty tables was overlooked.)
This PR handles that case by setting the value-type to array.

-----------------------------------------

@SmallJoker  How would `dropNullPlaceholders` help?
According to doc in the json lib's header file, it just writes "" instead of "null" in some (or all; does js allow that?!) cases:
```
   *  - "dropNullPlaceholders": false or true
   *  - Drop the "null" string from the writer's output for nullValues.
   *    Strictly speaking, this is not valid JSON. But when the output is being
   *    fed to a browser's JavaScript, it makes for smaller output and the
   *    browser can handle the output just fine.
```

>EDIT: In case there's no array/object to serialize, create one here if necessary:

I don't quite understand. Do you mean insert something into the table if it's empty? That would be unnecessarily hacky and ugly.

**Comment by SmallJoker** [comment]
@Desour The idea was to not serialize `null` values (although I totally missed the note about JSON format warning) at all, and instead initialize `root` to an array/object. However, after that initialization, the formatting flag would no longer be necessary.

After all I ended up with technically the same implementation that you proposed in this PR. I do see that neither "array" notation is correct. Alternatively the behaviour could be documented, stating that empty tables are serialized to a `nil`-equivalent.

**Comment by appgurueu** [comment]
This has the potential to break mods relying on the serialization removing empty tables (say a mod uses a `if mytab.myfield` check during initialization where `myfield` is supposed to be `null` to see if it's empty due to this property of the serializer).

TBF I don't remember relying on this; I usually just have `or something` in my code to default to an empty table for certain fields which might have been cleared by the serialization (actually I usually use the Lua serializer).

**Comment by Desour** [comment]
>This has the potential to break mods relying on the serialization removing empty tables [...].

Indeed.

Would someone privileged mind to run a grep on cdb for `write_json` (https://content.minetest.net/zipgrep/)?

**Comment by rubenwardy** [comment]
Here you are: https://content.minetest.net/zipgrep/f74ef56f-b7a7-4ad7-b6ab-3848630ea028/

**Comment by Desour** [comment]
After skimming through all of the results, I've found nothing that obviously relies on getting nil back.
But I've found:
- One mod (lwcomputers) that (I think) is giving `write_json` to players.
- Multiple mods send the output of `write_json` via the http api. (The other end might handle `[]` and `{}` differently, so empty tables becoming `[]` should be documented.)

Conclusion:
- It does not seem necessary to add a new parameter or similar to fix this bug.
- If I've overlooked something (very possible), or some http server makes use of this feature, we can still blame them for (ab)using something undocumented.
- Because of non-lua stuff using receiving the json output, the new behaviour needs to be documented.

(Btw. it would be useful to have the grep results split in mods and subgames because the code in the subgames is mostly duplicated from their mods.)

**Review by appgurueu — APPROVED** [review]
Looks fine to me

**Comment by x2048** [comment]
Discussed at the [coredev meeting](https://irc.minetest.net/minetest-dev/2022-06-05#i_5982463), we'd like to have a parameter to control whether empty tables are serialized at 'null', '[]' or '{}'. This will avoid breaking changes and give control to the caller to match the implementation on the other side.

Lua-json-Lua roundtrip is not considered a concern, since in this case Lua serialization should be used instead of JSON serialization.

**Comment by Desour** [comment]
> a parameter to control whether empty tables are serialized at 'null', '[]' or '{}'. This will avoid breaking changes and give control to the caller to match the implementation on the other side.

One parameter to control the output of all empty tables in the value? This would still leave it impossible to satisfy an other end that uses both sorts of tables, eg. something of the format `{foo: <possibly empty array>, bar: <possibly empty dictionary>}`.
It would also bloat the implementation with a "keep bug" parameter.

> Lua-json-Lua roundtrip is not considered a concern, since in this case Lua serialization should be used instead of JSON serialization.

The lua deserialisation is inferior to json deserialisation: You must make sure that you can trust the serialized string. Otherwise someone might have added ie. a `while true do end` or some code that uses the string metatable in weird ways.
This is why I'd normally not use lua serialisation, and definitely not suggest using it in all cases.

**Pull request closed without merging**
