### PR TITLE
Improve digging/placing animation

### PR DESCRIPTION
**Pull request by oilboi**
Add compact, short information about your PR for easier understanding:

- Goal of the PR

Make the arm more swingy

- How does the PR work?

Makes the arm more swingy

- If not a bug fix, why is this PR needed? What usecases does it solve?

Aesthetics

## To do

Ready for Review.

## How to test

Dig/place stuff

### CODE REVIEW

**Comment by Moth-Tolias** [comment]
this really doesn't seem like the sort of thing an engine should have hardcoded.

**Comment by LoneWolfHT** [comment]
I'd love it if this was configurable in the itemdef

**Comment by FreeLikeGNU** [comment]
Why not have the animation defined in the player model file and referenced in lua like any other animation?

**Comment by paramat** [comment]
I will test soon, but it would be good to be a little more descriptive in the first post to help people who are not building and testing. You seem to be resisting the request for a reasonably descriptive first post.
By 'more swingy', and looking at the code, does this increase the vertical motion to create a more circular motion?

Something to consider:
This movement has to be suitable for the hand when punching, a wielded node when placing, and a wide variety of tools and usable items, not just ones that 'swing' like a pickaxe.
When punching or using certain tools, a more forward-backwards motion is suitable So if your PR almost doubles vertical motion, as the code suggests, the motion becomes less suitable for certain uses.
More vertical motion will also obstruct vision more.

The current motion is like a horizontally-elongated oval, with more forward-backward than vertical motion, which seems a good compromise between punching and swinging motions, as it has a little of both.

**Comment by paramat** [comment]
Tested.
I find this unpleasant and careless, and a much worse movement than currently, sorry :-1: 

The speed of the movement has been greatly increased, it looks insanely and unrealistically fast now. Such a fast movement is unsuitable for swinging heavy tools and makes them look weightless.
The motion is more circular, ok for a pickaxe, but making it unsuitable for punching type movements.
There is much more vertical motion: The hand now punches towards a point 3/4 of the way up the screen, instead of towards screen centre as it should. And therefore also, is more visually intrusive and obstructive.

I think instead we should leave the default movement as it is and add tool-specific movement, as has already been requested in #2811

**Comment by hecktest** [comment]
Can we just have a viewmodel API already?

**Comment by SmallJoker** [comment]
An alternative implementation allowing control outside the source code seems to be wanted rather than this tweak. Closing PR for lack of interest.

**Pull request closed without merging**
