### PR TITLE
Menu music (WIP)

### PR DESCRIPTION
**Pull request by RealBadAngel**
Added main menu music.
Allow subgames have own scores (kept in /menu folder).
Game starts with main score, subgame music is played when clicked subgame button.

TODO: 
- add volume settings, controls in main menu for them (perhaps separate audio tab?)
- crossfading of tunes (if possible)

Any opinions? Suggestions?

### CODE REVIEW

**Comment by indriApollo** [comment]
Is this dead ?

**Comment by paramat** [comment]
I feel this needs to be reworked to have the functionality and option to add music to a subgame if wanted, but the music supplied here should be removed. It might take a long time (if it happens at all) to find something suitable for MTGame (if music is suitable for such a general all-purpose subgame), and it should be very short music for small file size.

**Comment by C1ffisme** [comment]
The issue might have stopped conversation, but it can be ressurected.

**Comment by RealBadAngel** [comment]
Why the fuck  mt can be the only one game in the world without music at all?
Are all others devs deaf or something? :P

**Comment by kilbith** [comment]
Because tastes on music are extremely diverse and some might be dead irritating for the ears.

**Comment by nerzhul** [comment]
Sorry but i don't think the blocker tag is adapted here. Blocked is reversed to blocking bugs before releasing.

**Comment by paramat** [comment]
I'm not opposed, but first we need something really short (1 minute) that is composed exclusively for Minetest Game by someone who has played it or loves voxel games. Then whatever is chosen most won't like it, and it takes up a lot of memory, so it's difficult. I guess it's best being very short and fairly atmospheric / ambient / gentle.
Not having music means players can supply their own favourite music, i'm usually listening to music when playing. Doing something only because others do it is no good reason, i find a game without music quite refreshing, if some are put off by this they are shallow, no loss to us.

**Comment by PilzAdam** [comment]
@RealBadAngel because "Minetest" is a game engine, not a game.

**Comment by indriApollo** [comment]
So just play the score from selected subgame (the first one by default amirigth) and everyone's happy.

**Comment by paramat** [comment]
:-1:
Celeron55 is also strongly opposed to this.
@RealBadAngel unless this PR is fundamentally changed it should be closed.
Will close in 1 month if no response.

**Pull request closed without merging**
