### PR TITLE
Use the faster table insertion method (dlg_settings_advanced.lua only)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sofar** [comment]
Not really critical or anything hotpath, but still fine I think.

**Comment by Rui914** [comment]
>>Not really critical or anything hotpath

Yes. But I think the faster the better :)

**Comment by kilbith** [comment]
On non-critical code you need readability and ease of maintenance more than a micro-optimization.

There are other ways to make the insertion faster, but it would be dumb to lose the readability for 3 ms. faster here...

**Comment by paramat** [comment]
:+1:

**Comment by kaeza** [comment]
```
tinsert(t,v)      2365273
t[#t+1]=v         2522097
n=n+1 t[n]=v      7909498
```
The numbers are insertions per second using different approaches (tested under LuaJit, stock Lua may be different; benchmark [here](https://gist.github.com/kaeza/96a30d36c58dfae4a55e)).

Still agree with @kilbith.

**Comment by sofar** [comment]
lua-5.1.2, tested with the pasted link by kaeza:

```
DESC              TOT
tinsert(t,v)      1938457.3333333
t[#t+1]=v         2280419.3333333
n=n+1 t[n]=v      3821620.6666667
```

**Comment by sofar** [comment]
For reference, here is a full spread of test data across versions:
```
=== lua-5.1.4 ====
DESC              TOT
tinsert(t,v)      1894375.3333333
t[#t+1]=v         2231591.6666667
n=n+1 t[n]=v      3757611
=== lua-5.2.3 ====
DESC              TOT
tinsert(t,v)      1820607.6666667
t[#t+1]=v         2076934.3333333
n=n+1 t[n]=v      3404882.3333333
=== lua-5.3.2 ====
DESC              TOT
tinsert(t,v)      1957116.6666667
t[#t+1]=v         2088806.6666667
n=n+1 t[n]=v      3481470.6666667
=== luajit ====
DESC              TOT
tinsert(t,v)      2392461
t[#t+1]=v         2597967
n=n+1 t[n]=v      4398963.3333333
```

**Comment by HybridDog** [comment]
DESC              TOT
tinsert(t,v)      1970276.3333333
t[#t+1]=v         2045646.3333333
n=n+1 t[n]=v      3062939.6666667

**Comment by Rui914** [comment]
I will close this PR and revert 24e8b0a with new PR.

**Comment by HybridDog** [comment]
l put the benchmark code to builtin/game/register.lua:
```
DESC              TOT
tinsert(t,v)      1574746.3333333
t[#t+1]=v         1645546
n=n+1 t[n]=v      2365312.6666667
```

**Pull request closed without merging**
