### PR TITLE
Add in vector.abs()

### PR DESCRIPTION
**Pull request by oilboi**
Adds in ability to math.abs() a table

### CODE REVIEW

**Comment by SmallJoker** [comment]
`vector.apply` was added for this kind of maths functions. Is this function used frequently somewhere, or does `vector.apply` suffice?

**Comment by oilboi** [comment]
> `vector.apply` was added for this kind of maths functions. Is this function used frequently somewhere, or does `vector.apply` suffice?

This is useful for an easy way to check if an entity or player is within the x,z,and y of a node, 2d or 3d. Also we have math.abs why would we have to make a player call a function to absolute a vector when it would make more logical sense to call vector.abs(v) and then work from there?

**Comment by v-rob** [comment]
```
local v = vector.new(1, -1, -10)
print(dump(vector.abs(v)))
print(dump(vector.apply(v, math.abs)))
```
Both print statements should return the same value, so I don't see much point in having an extra function to do something already easily possible.

**Comment by paramat** [comment]
Currently this does not seem justified to me.

**Comment by tacotexmex** [comment]
Seems to be explained at length [here](https://www.youtube.com/watch?v=2GOsXSeNgQw).

**Comment by Desour** [comment]
:-1: 
`vector.abs` seems too specialized. Component-wise unary operations can easily be done with `vector.apply`.
(`vector.round` and `vector.floor` can be justified with minetest's voxel-grid, maybe (at least `vector.round`). `vector.floor` is probably just there because it was always there.)

Post scriptum:
@oilboi: For things like pressure-plates, node-timers make more sense than abms.
(Btw. I didn't know that abm intervals smaller than 1 second possible.)

**Pull request closed without merging**
