### PR TITLE
Allow setting item texture from stack metadata

### PR DESCRIPTION
**Pull request by lisacvuk**
Solves #5686  

## To do  

This PR is a Work in Progress  

- [ ] Fix things like rails not properly changing texture in both wield model and inventory  
- [x] Use ItemStack::getTexture in more places instead of manually checking if metadata exists  

## How to test  
 ```lua
minetest.register_chatcommand("test",` {  
    params = "",  
    func = function(name, param)  
               local player = minetest.get_player_by_name(name)  
               local stack = player:get_wielded_item()  
               stack:get_meta():set_string("texture", "default_leaves.png")  
               player:set_wielded_item(stack)  
           end,  
})  
```

### CODE REVIEW

**Comment by sorcerykid** [comment]
Correct me if I'm wrong, but doesn't this have the potential to break mods that already use the "texture" field of itemstack metadata? As more and more specialized fields like this are added, I'm concerned that this will cause conflicts down the road.

Perhaps it should have been decided that specialized fields be denoted using a underscore prefix or some other convention so that there's never any risk of naming collisions when the API is changed.

**Comment by Df458** [comment]
> Perhaps it should have been decided that specialized fields be denoted using a underscore prefix or some other convention so that there's never any risk of naming collisions when the API is changed.

While I don't expect that many (any?) mods use this particular field, I definitely support adopting a standard naming convention for metadata fields used by the engine.

**Comment by lisacvuk** [comment]
I can make this use "_texture", it shouldn't be difficult to change description to "_description" as well.

**Comment by sorcerykid** [comment]
That is great news, and thanks for the clarification!

I am very much looking forward to this PR. I can't even imagine all the potential applications. Once this is merged, hopefully it sets a precedent for the long awaited ability to dynamically change textures of nodes using the same methodology. One step at a time, but at least this is a great step in that direction :)

**Comment by Skamiz** [comment]
I believe it is worth noting that the documentation on item definitions encurages modders to use an underscore for custom item/node definition fields.
[https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6578](url)
```
        _custom_field = whatever,
        -- Add your own custom fields. By convention, all custom field names
        -- should start with `_` to avoid naming collisions with future engine
        -- usage.
`

**Comment by sorcerykid** [comment]
Those are item definition fields, which are separate and distinct from metadata fields that are serialized within the itemstack or node.

**Comment by paramat** [comment]
PR is WIP but no progress for 4 months, is @lisacvuk still interested in continuing work?
Feature has core dev support in the feature request.

**Comment by sorcerykid** [comment]
I would like to respectfully retract my earlier suggestion of using underscores for reserved fields in consideration of the fact that `infotext` and `formspec` are widely used already for node meta. Since no standard was picked early on, it's probably best not to introduce an more confusion by switching the naming scheme now.

My secondary impetus, however, is that I've been considering opening a PR to streamline private node meta by prefixing an underscore to the name, rather than having to use the somewhat obfuscated method `mark_as_private` and storing an extra boolean value in the database. So I feel that would be a better application of the underscore.

**Comment by lisacvuk** [comment]
I will close this for now, as I don't have time (or interest) to work on it right now. Feel free to take over if you wish.

**Comment by velartrill** [comment]
if there's still interest in this (read "it's likely to eventually be merged") i'd be willing to take it over

**Comment by rubenwardy** [comment]
There's definitely interest in this feature, haven't checked this specific implementation though

**Pull request closed without merging**
