### PR TITLE
Better arrow, clear, refresh and search icons

### PR DESCRIPTION
**Pull request by Zughy**
**Before**

image
image

**After**
image
image

## To do

This PR is Ready for Review.

## How to test
Use your eyes

### CODE REVIEW

**Comment by appgurueu** [comment]
Beautiful, but somehow looks out of place (in the second screenshot for instance, the arrows are still ugly). Might require a full makeover of all base textures.

**Comment by Zughy** [comment]
You're 100% right, it actually requires a complete makeover of the whole menu. I simply thought about starting with the most common ones, while I work on a separate mockup

**Comment by Andrey2470T** [comment]
If you want to make a redesign of those icons, then, yes, it is necessary to remake also another icons of other buttons/images, because it looks like a bit incompatible and in a good way the whole menu makeover.

 I would rather suggest to create a PR as a draft with the full menu redesign as I think the current PR can not be merged for that reason.

**Comment by Zughy** [comment]
fine, give me 10 minutes for the arrows then

**Comment by Zughy** [comment]
done, screenshot updated

**Comment by runsy** [comment]
I prefer the white one = Simpler. Colored ones are a bit outdated for me: 90's/2000's. New tendency is minimalism.

**Comment by G1ov4** [comment]
> 
> 
> I prefer the white one = Simpler. Colored ones are a bit outdated for me: 90's/2000's. New tendency is minimalism.

Honestly, the white ones seem "cheap" (the magnifying glass handle border, for example, is thicker than the lens, and that is not today's tendency), the fact that they are white doesn't really help. I think that having well-done pixel art icons could help create a unique style for the launcher, making it less anonymous and visually appealing (but still coherent with the kind of games that the engine allows making).

**Comment by tukkek** [comment]
I like the new icons a lot but the original arrows look cleaner.

**Comment by paramat** [comment]
The `next prev clear search` textures were taken from MTG creative mod, those and `start end refresh` are all '128px plus blur' because that greatly improves the ugly texture distortion caused by formspec scaling.
You should check the effect of formspec scaling on your textures, try adjusting game window size while looking at the textures.
I suggest perhaps making the new textures fairly large (around 128px) and adding a small radius blur.

Personally, i find your new textures rather dark and unclear, and they have a design that is inconsistent with the clean, simple appearance of the rest of the menus.

**Comment by Anulo2** [comment]
> The `next prev clear search` textures were taken from MTG creative mod, those and `start end refresh` are all '128px plus blur' because that greatly improves the ugly texture distortion caused by formspec scaling.

And they are ugly. Those icons remember me of what I was using when trying visual basic around when I was 12. They probably the same or some really similar version. Nowadays I wouldn't use them even against my biggest enemy, they are simply that ugly

> You should check the effect of formspec scaling on your textures, try adjusting game window size while looking at the textures.
> I suggest perhaps making the new textures fairly large (around 128px) and adding a small radius blur.

this problem should not bother artists, it's an engine problem and should be threated as that
also, a pixelart that big (128px as you said) when used at those dimensions is not anymore a pixelart but an image, it could even be a photo scaled down.

> Personally, i find your new textures rather dark and unclear, and they have a design that is inconsistent with the clean, simple appearance of the rest of the menus.

This last one is really a personal opinion and I respect that, even though I highly disagree with you. 
Other than that, I would suggest to leave graphic designs and related things to people that do that as a job (like Zughy) and probably have a better taste of what people like. 
Yes, the community response is really important but that comes with a tradeoff, people have to be willing to change their opinions and to leave what has been created in years behind. Something that could be ok some years ago is not necessaraly ok today. 
It could be better, it could be worse. 
IMO those icons have never been ok, but that's my opinion and you don't have to agree with me.

**Comment by Zughy** [comment]
> The `next prev clear search` textures were taken from MTG creative mod, those and `start end refresh` are all '128px plus blur' because that greatly improves the ugly texture distortion caused by formspec scaling.

Yes, we actually talked about that on the IRC [today](https://irc.minetest.net/minetest-dev/2020-12-29#i_5768880), but unfortunately it doesn't work with upscaled pixel art

> I suggest perhaps making the new textures fairly large (around 128px) and adding a small radius blur

I agree with Zaizen, the problem is in the rendering engine and it shouldn't be up to me to find a workaround. I know very little of that, maybe @v-rob can enlighten us

**Comment by v-rob** [comment]
> I know very little of that, maybe @v-rob can enlighten us

I don't know for certain, but the problem might be with `draw2DImageFilterScaled`.  Since it's our own software scaler, I wouldn't be surprised if there are some problems with the algorithm, or if the algorithm is just bad.  On the other hand, there's Irrlicht's own `IVideoDriver::draw2DImage`.  It can also scale (except with the software driver).  I don't know if the quality's better, but it's easy to check: use an `image[]` element to see if it has the same problems since it uses Irrlicht's scaling, not our own.  If `image[]` is better, the solution is simple to fix, but if not, there's something else at play.

**Comment by appgurueu** [comment]
> `draw2DImageFilterScaled`
To add on that: Under the hood, that uses `guiScalingResizeCached` which again uses `imageScaleNNAA`, a nearest neighbor scaling algorithm. Have a look at the [comparison of image scaling algorithms](https://en.wikipedia.org/wiki/Comparison_gallery_of_image_scaling_algorithms) in order to see why that might be unsuitable.

**Comment by Zughy** [comment]
So, it's been 5 days to evaluate 7 simple icons, where no code has been touched. This thing should require 5 minutes. So, can I have a response?

**Comment by rubenwardy** [comment]
I don't think this icons match at all. I think changes like this are best done when there's an idea of what the GUI should look like

**Comment by tukkek** [comment]
> can I have a response?

Speaking only for myself here but if you want a definitive response rather than a discussion, it seems (judging by the reactions on the first post) that opinions are roughly evenly divided between people liking and disliking the new icons. This seems supported by the talk too. I guess It's a hard sell to push a PR if people can't agree, at least to some extent that it's making the game better.

You can probably get a more positive reception by taking some of the criticism here into account and trying again.

**Comment by Zughy** [comment]
> You can probably get a more positive reception by taking some of the criticism here into account and trying again

The point is, there is no criticism, just dislikes. I can't read people's mind. About the cleaner thing: yes, previous ones will always be cleaner than anything else, because they're pure white silhouettes on an almost black button. The only way to make it cleaner is to have a jet black button, which will be even worse in terms of style. Because, just for the record, the colours I used are highly saturated: so if my pixel arts seem dark, maybe the problem isn't in my colours, but in how colours are managed AROUND my pixel arts.  
The other "criticism" is about an engine problem, which is not a responsibility of mine (also because I don't even know where to start).

> I think changes like this would make more sense when there's an idea of what the GUI should look like

There are two issues that have been going on for years. As an artist, I can say that those issues are pretty much useless and I don't want to waste my time reading wall of texts and theorising something nobody here is able to manage but probably me, when it's obvious you all lack the practical experience (this is not an offense, this is a fact). It takes way less time if I just do it. These PRs were meant to offer a soft transitioning, because I have no intention of restyling piece by piece this atrocious thing we call menu and which is, by the way, one of the reasons people don't open MT twice - believe it or not. But, well, it seems people love the current ones.

I just hope I won't be hindered when I'm done with the new menu. If anyone wants to give feedback: https://forum.minetest.net/viewtopic.php?p=387004#p387004

**Comment by sfan5** [comment]
Personally I like the icons proposed here but I can understand wanting to delay new icons until the whole menu style\* gets a makeover.

\* Just the style. If everything else looked to match the icons it'd be fine, no need to change the layout or wait for the whole navigation to be redesigned.

> If anyone wants to give feedback: https://forum.minetest.net/viewtopic.php?p=387004#p387004

Off-topic here, but here's my first thought: The fonts are awfully unreadable.
I'm sure it's meant to follow the pixel art-y style but you just can't expect people to read that.

**Comment by Zughy** [comment]
> The fonts are awfully unreadable

No no, that's just a mockup, I didn't want to open Inkscape in a trial and error process every time I had to put a font, so I just drew them in pixel art to make people understand what's gonna be there

**Pull request closed without merging**
