### PR TITLE
Wieldmesh: Natural orientation depending on pitch

### PR DESCRIPTION
**Pull request by kilbith**
Demo : https://youtu.be/m2-Msf_nZw0 but best testing it yourself.

Also PTAL at https://github.com/minetest/minetest/issues/5174

### CODE REVIEW

**Comment by paramat** [comment]
May need tuning but i like it.

**Comment by tobyplowy** [comment]
@kilbith +1

**Review by SmallJoker — APPROVED** [review]

**Comment by kilbith** [comment]
Will be closed in a week if no interest.

**Comment by ExeterDad** [comment]
I gave my thumbsup in the original pull. Here's some words to let you know I'm interested. It looks awesome!

**Comment by kilbith** [comment]
No further interest, closing.

**Comment by SmallJoker** [comment]
Please point out the disagreement of other core devs in the IRC logs or re-open this in a new pull. I would like to see this little tweak ingame.

**Pull request closed without merging**
