### PR TITLE
Ability to define and use LUA wield animations

### PR DESCRIPTION
**Pull request by TheMrAmazing**
I found this old pull request: #7517
that added several wield animations in C++ that could be added to tools, such as an eating animation or a digging animation. It looks like it was rejected because you could not define new animations in LUA, making it not particularly useful for modding. I really liked the concept, so I added the ability to add new wield animations through the LUA.

This is my first time contributing, so I'm sure I've made some mistakes, but I'm happy to fix whatever is needed to get this feature added to the game

This is my second pull request for this feature, because I made a mess of the commit history on the last one

### CODE REVIEW

**Comment by TheMrAmazing** [comment]
@SmallJoker Is this better now?

**Comment by paramat** [comment]
This PR has 4000 changed lines. Looking at the changes, there are many unrelated changes, mostly bad formatting changes that make the code less readable. They look like the bad changes that the Clang Format build check would like do to the code.

The Mr Amazing, have you perhaps tried to apply what Clang Format requests? If so, please do not, Clang Format makes many very bad formatting requests which you should ignore. But, it is useful to look through the CF requests, using human judgement, to see if it has caught any valid mistakes.

So this PR needs cleaning up.

This again reminds me we should somehow make clear to contributors to not do everything CF asks, just use it as a check, and explain it makes many bad requests, perhaps in `contributing.md`?

**Comment by TheMrAmazing** [comment]
So it can be pushed without passing the cpp_lint / clang_format check?

**Comment by TheMrAmazing** [comment]
Need to get rid of automatic clang formating

**Comment by paramat** [comment]
Because many of the CF formatting requests are bad, what we often do in a PR is 'whitelist' the file by adding it to https://github.com/minetest/minetest/blob/master/util/ci/clang-format-whitelist.txt , this disables CF checks for that file so that CF does not flag the build as failing.
Consequently, most MT files are in the whitelist. Of course, this is crazy, but is the only way we can avoid CF marking builds as failed.
So in this way, yes, very many PRs are merged that CF would complain about if it was allowed to.

Sorry we did not make the CF situation clear, we really should do this. I feel bad you have done a huge amount of invalid formatting work in this PR. The CF build check misleads contributors often and i am again left wondering when are we going to fix this crazy situation?

We have discussed the problems of CF often, and i have often complained about this situation. I suggested a way to solve this problem but the other core devs opposed this, see #9074

**Comment by paramat** [comment]
@TheMrAmazing to be clear, did you try to do everything CF requested? How many lines of the 4000 changed lines was satisfying CF?

**Comment by TheMrAmazing** [comment]
The vast majority, without the clang stuff it's about 740 new lines

**Comment by TheMrAmazing** [comment]
@paramat do I need to add it to the whitelist myself somehow before it will get reviewed?

**Comment by paramat** [comment]
> The vast majority, without the clang stuff it's about 740 new lines

Aaaaa ... i feel so bad about this.
I will make a PR to alter the contributing statement to try to warn contributors.

You should add the files to the whitelist in your PR as a last step, after you have looked through the CF requests to check for any valid requests. Essentially, any file where CF is making silly requests that are unnecessary changes or mess up code readability should be added to the whitelist. About 80% of CF requests are bad and should be ignored.

**Comment by paramat** [comment]
Replaced by #10411

**Pull request closed without merging**
