### PR TITLE
Catch and log `SerializationError` exceptions in object (de)serialize.

### PR DESCRIPTION
**Pull request by red-001**

### CODE REVIEW

**Comment by nerzhul** [comment]
sorry but it's not a good option to catch all attributes as this can make the object very very inconsistent and hide devel errors.

**Comment by sfan5** [comment]
this is a horrible idea, how would the caller of `ObjectProperties::serialize()` know that serialization was incomplete due to an error?

**Comment by nerzhul** [comment]
@sfan5 i think we should close this, as it's a horrible hack :(

**Comment by red-001** [comment]
should the try catch also be removed from `ObjectProperties::DeSerialize()`? if not then the improvements to that could still be useful.

**Comment by nerzhul** [comment]
let it in deserialization, it exists and it's sufficient safe for current portability between versions, but serialization error means you did devel error, we should never hide devel error in an exception. Assert are there for that

**Pull request closed without merging**
