### PR TITLE
Extract and pull up assignFreeId from CAO/SAO

### PR DESCRIPTION
**Pull request by JosiahWI**
This unifies most of the duplicated logic in registerObject and should make further refactoring easier.

### CODE REVIEW

**Comment by JosiahWI** [comment]
This PR goes along with #13560 and whichever one gets merged second will need a rebase.

**Comment by Zughy** [comment]
@JosiahWI the aforementioned PR has been merged, are we ready to proceed here?

**Comment by JosiahWI** [comment]
Yes we are.

**Comment by Desour** [comment]
Sorry, but I think this makes the code harder to read and understand.
It moves code that is only relevant for `registerObject` into 4 different member function procedures, where some of them are even polymorphic. => Worse locality.
And if we ever wanted to change the code independently in client and server aomgr, we'd get into troubles.
The risk of accidentally changing one and not the other is low, because we know there are two so similar classes.
Overly detailed analysis ends here.

**Comment by JosiahWI** [comment]
If someone could glance over PRs and make these comments before the author invests hours maintaining and rebasing the PR, that would be very helpful.

**Comment by Desour** [comment]
Yes, sorry! I lost track of this PR.
I'm currently taking a measure to get better in this regard.

**Pull request closed without merging**
