### PR TITLE
Credits: Make that easy to add/remove

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Seems way better organized :+1:

**Comment by C1ffisme** [comment]
Pretty Smart. :+1:

**Comment by ObaniGemini** [comment]
This is a good idea and very simple. Could it be reviewed quickly and then merged for upcoming 0.4.14 ?
@paramat 
@est31 
@celeron55 
...

**Comment by celeron55** [comment]
:+1:

**Comment by est31** [comment]
:+1:

**Comment by C1ffisme** [comment]
While we are here, should we remove Blockmen from the list of Core Contributors?

**Comment by est31** [comment]
Updating the list is IMO tracked by a separate PR, it covers more than just removing blockmen, we also got sofar.

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
21c479688b4ee93c58f41d20f5c7555a41e4ad97

**Pull request closed without merging**
