### PR TITLE
Confirm exit on escape in main menu

### LINKED ISSUE #10332: Pressing ESC in the main menu error screen should not close the client
##### Minetest version
```
Minetest 5.3-stable
```

##### Summary
Pressing ESC in an error screen of the main menu to quickly dismiss the message instead closes Minetest. This is very unintuitive and destructive behavior. In Windows and Mac operating systems, the ESC key is not customarily used to quit an application.

For the longest time I figured this was just a personal nuiscance, so I didn't report it. But then I noticed the same concern raised in https://github.com/minetest/minetest/issues/8930#issuecomment-531357588, so I decided to go ahead and open an issue.

### PR DESCRIPTION
**Pull request by yamanq**
Closes #10332 by adding confirmation dialog.

## To do

Ready for Review.

## How to test

1. Open Minetest
2. Press escape

image

### CODE REVIEW

**Comment by NathanSalapat** [comment]
What happens if somebody hits escape when the confirmation window is open?
I personally use escape to quit minetest, but I can adapt to alt+f4 if needed.

**Comment by rubenwardy** [comment]
> What happens if somebody hits escape when the confirmation window is open?

Yeah, this should exit Minetest

**Comment by lhofhansl** [comment]
Hmm... I like it the way it is. But double ESC (to get to the dialog and then exit) is fine too.

**Comment by rubenwardy** [comment]
Actually, this doesn't fix #10332. 

ESC should only be registered once when pressed, this is typically done by binding to ESC up or down rather than pressed

**Comment by randomMesh** [comment]
Please make it optional with a configuration option. These kind of confirmation dialogues are the first i turn off in every application i use. If i want to exit the app, i want to exit the app.

**Comment by rubenwardy** [comment]
No, I don't think this is very useful if the bug fixed

**Pull request closed without merging**
