### PR TITLE
Fix list spacing and size (again)

### LINKED ISSUE #10862: Slot size of >1 ignores height size
Engine commit: https://github.com/minetest/minetest/commit/ad9adcb88444b4a7063d5c2f5debd85729e8ce42

Test code: `style_type[list;size=1.2,1.2;spacing=0.15]`

While `1.2` is applied for the width, it remains `1.0` for the height.
The first slot is `1.2` in width until it decreases to `1.0` on the last slot of the line.

Capture d’écran de 2021-01-24 00-52-46

This is `size=1.1,1.1` for example: https://i.imgur.com/hDsPaXv.png

@v-rob

### LINKED ISSUE #10866: List styling exception
Engine commit: https://github.com/minetest/minetest/commit/8dae7b47fcc1c26251c8006efbc9ee8af152f87a

Test code: `style_type[list;size=0.01;spacing=0]` and hover the list.

```
Thread 1 "minetest" received signal SIGFPE, Arithmetic exception.
0x000055555582ca86 in GUIInventoryList::getItemIndexAtPos(irr::core::vector2d<int>) const()
```

@v-rob

### PR DESCRIPTION
**Pull request by v-rob**
Fixes #10866 and fixes #10862 as well as making old coordinate system custom spacing more sane and making rounding behavior more consistent with the rest of formspec elements.

Devtest should look like this:
image

### CODE REVIEW

**Comment by kilbith** [comment]
Tested. I'm not exactly sure whether your PR changes the size or the spacing but the behavior has changed between `upstream/HEAD` and your branch.

### Before
Capture d’écran de 2021-01-26 02-13-24

### After 
Capture d’écran de 2021-01-27 19-29-19

**Comment by kilbith** [comment]
Ok confirmed, this PR changes the slot size to make it bigger than currently.

**Comment by v-rob** [comment]
Sorry, still haven't had time to do all the testing I want to.  I will look into that as soon as I can.

**Comment by v-rob** [comment]
I found the problem; i3 is using inconsistent units.  Note how here, size and spacing are set to 0.96 and 0.15 respectively:

https://github.com/minetest-mods/i3/blob/89c2249bcba1145725042f80fc3f51c6ef14e4a2/init.lua#L2236

On the other hand, the gradient slot boxes use size and spacing of 1 and 0.1, respectively:

https://github.com/minetest-mods/i3/blob/89c2249bcba1145725042f80fc3f51c6ef14e4a2/init.lua#L2242

Changing the original line to have 1 and 0.1 for size and spacing fixes it.  I guess that this was using the incorrect behaviour from pre-#10861, so it appeared incorrect in this PR.

However, your mod exposed one problem, which is that this PR uses `round` which gives better behaviour in some circumstances while worse in others.  I will change it back to floor behaviour to keep it consistent with everything else.  It might be possible to make the rounding behaviour better than either, but rounding is a problem shared universally by formspecs, so I'll leave it alone for now.

**Comment by kilbith** [comment]
> On the other hand, the gradient slot boxes use size and spacing of 1 and 0.1, respectively:
>
> https://github.com/minetest-mods/i3/blob/89c2249bcba1145725042f80fc3f51c6ef14e4a2/init.lua#L2242

Nope, it has `size` as size which is `0.96`, not `1`.

**Comment by v-rob** [comment]
My mistake, but my point still stands.  The width and height of the slots are the same, but the spacing and positions are not.  If you change the size and spacing to 1 and 0.1, they will align.  Or, you could use 0.96 and make sure the position of the gradients also uses this value.  Either way, the PR is not in error here.

**Comment by kilbith** [comment]
> If you change the size and spacing to 1 and 0.1, they will align

I confirm that. But I don't get why the spacing _has_ to be different between slot and box when size is `<1` for slot + box, and why it can be kept the same when it's size `1`.

**Comment by v-rob** [comment]
> I confirm that. But I don't get why the spacing has to be different between slot and box when size is <1 for slot + box, and why it can be kept the same when it's size 1.

It doesn't; in the original PR, this was true (because it had buggy `imgsize` handling), but that was fixed in #10861.  Both slot size and slot spacing are fractions of the coordinate and not dependent on each other.  Here's an image of the current behaviour:

image

So, to fix i3's slot backgrounds to use any size/spacing, change line 2242:
```lua
-- From
fs(fmt("box", i + inv_x + (i * 0.1), inv_y, size, size, ""))
-- To
fs(fmt("box", i * size + inv_x + (i * spacing), inv_y, size, size, "")) -- Notice the added `* size` to fix positioning and using `spacing` instead of `0.1`
```
And then any value for `size` or `spacing` will work for both list and boxes.  No change needs to be made for the list because that's not the issue.

(BTW, i3 is a really nice inventory, and it really uses the new formspec features to their potential.)

**Comment by v-rob** [comment]
Fixed rounding behaviour and did more thorough testing.  Everything looks good to me.

**Comment by kilbith** [comment]
Tested the last commit and it does indeed fix some rounding issues I had when adjusting the size with floating values.

So I guess I can give a :+1:  to this PR now.

**Review by sfan5 — APPROVED** [review]
Looks good.

**Review by SmallJoker — APPROVED** [review]

**Pull request merged**
