### PR TITLE
Biome API: Add 'get heat / humidity / biome at pos'

### PR DESCRIPTION
**Pull request by paramat**
Very WIP.
Attends to #3685 and many requests.
I'm stuck in l_mapgen.cpp, i somehow need to access class 'biomegen'.

### CODE REVIEW

**Comment by proller** [comment]
https://github.com/freeminer/freeminer/blob/master/src/script/lua_api/l_env.cpp#L1103
https://github.com/freeminer/freeminer/blob/master/src/fm_map.cpp#L213

**Comment by paramat** [comment]
Thanks but that's a completely different implementation of 'heat' and 'humidity'.

**Comment by paramat** [comment]
Sorry proller looks like that was useful, i might have to add functions to serverMap, the existing 'calcBiomeAtPoint()' in biomegen original is probably not for this type of use.

**Comment by paramat** [comment]
Another attempt #6455

**Pull request closed without merging**
