### PR TITLE
Display pitch angle in debug menu

### PR DESCRIPTION
**Pull request by xerox123official**
Since pitch-fly was added, it makes sense that the pitch angle is added to the debug menu.

EDIT: [Demonstration](https://youtu.be/S4KyCDlLIVw)

### CODE REVIEW

**Comment by paramat** [comment]
> Since pitch-fly was added, it makes sense that the pitch angle is added

Not really, as we've always had view pitch, so there isn't really any change.

Why is view pitch useful? Not disputing, but it needs to be for a reason.

**Comment by Raider4** [comment]
Sounds gud, can't wait 👍

**Comment by xerox123official** [comment]
> Why is view pitch useful? Not disagreeing, but it needs to be for a reason.

The pitch of the player has had no effect on the motion of the player until the addition of pitch-fly, that's why I think it should be in F5

**Comment by DS-Minetest** [comment]
> > Why is view pitch useful? Not disagreeing, but it needs to be for a reason.
> 
> The pitch of the player has had no effect on the motion of the player until the addition of pitch-fly, that's why I think it should be in F5

Do you need to see a number to know if you are looking up or down? I don't think so.
(For yaw this is different because you can turn around yourself infinitely (try it out, maybe it's fun).)

**Comment by paramat** [comment]
I have actually occasionally found it would be useful to have pitch, i think it will be useful.

**Comment by paramat** [comment]
> The pitch of the player has had no effect on the motion of the player until the addition of pitch-fly,

Good point, sorry i didn't realise earlier, when travelling in 3D space the pitch direction will be as useful as yaw.

**Comment by paramat** [comment]
A screenshot would be nice to see.

**Comment by xerox123official** [comment]
> A screenshot would be nice to see.

Demonstration: https://youtu.be/S4KyCDlLIVw

**Comment by paramat** [comment]
:+1: 
Nah length is ok =)

**Pull request merged**
