### PR TITLE
Fix dropped craftitems/tools not using light_source values

### PR DESCRIPTION
**Pull request by LoneWolfHT**
Was trying to use https://github.com/minetest/minetest/pull/9200 to make my dropped lava items glow, when I realized that the PR only supported glowing node items. This PR fixes that. I've tested and it works

### CODE REVIEW

**Comment by MoNTE48** [comment]
https://github.com/minetest/minetest/pull/9200#discussion_r359468864

**Comment by LoneWolfHT** [comment]
How's that?

**Comment by sfan5** [comment]
Not sure if `light_source` should be added to items if its only purpose it to make dropped items glow.
Is `light_source` respected when you hold an item in your hand?

**Comment by LoneWolfHT** [comment]
> Is `light_source` respected when you hold an item in your hand?

Not yet. I'm looking into doing that in a separate PR

**Comment by LoneWolfHT** [comment]
Separate PR has been created. Be nice if this could be merged first

**Comment by LoneWolfHT** [comment]
Does this count as a bugfix or is it a feature?

**Comment by sfan5** [comment]
Feature.

**Comment by LoneWolfHT** [comment]
Oh, oops. Guess I need to use git for this

**Comment by LoneWolfHT** [comment]
Conflicts fixed, ready for review

**Comment by LoneWolfHT** [comment]
Ready for review again, Github's conflict resolver ain't too bad for simple things

**Comment by LoneWolfHT** [comment]
Bump after another month and the end of the (second?) feature freeze :smirk:

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
