### PR TITLE
Restore simple settings tab and add advanced settings as dialog

### PR DESCRIPTION
**Pull request by kilbith**
Rebased version of https://github.com/minetest/minetest/pull/3514. Fixes https://github.com/minetest/minetest/issues/3486 (blocker).

It has 2 approvals on the original PR and just stands there to be merged.

Credit is of course given to @BlockMen.

Cc: @paramat

### CODE REVIEW

**Comment by paramat** [comment]
Thanks for doing this.

**Comment by paramat** [comment]
Some minor code style issues.

**Comment by kilbith** [comment]
Fixed'em all.

**Comment by PilzAdam** [comment]
Which window is displayed after clicking "Save" in the change settings dialog? The advanced menu again or the simple settings tab? (sorry, I currently can't test this myself)

**Comment by kilbith** [comment]
@PilzAdam As currently : the advanced menu.

**Comment by PilzAdam** [comment]
@kilbith that's good. :+1:.

**Comment by paramat** [comment]
Tested and seems to work.
One strange thing is when shaders are disabled and i toggle a graphics setting like 'smooth lighting', the shaders bars go green:

screenshot from 2016-02-19 19 00 33

**Comment by kilbith** [comment]
@paramat This glitch has always existed but fixed now.

By the way, I trashed the code of the viewing range scrollbars that I added in the past. BlockMen removed these scrollbars already but not some remaining code. Anyways it was destined to be obsolete as you (core-devs) intend to trash the auto viewing range very soon.

**Comment by paramat** [comment]
That all sounds good :+1:

**Comment by Fixer-007** [comment]
I think this also needs two have at least two additions:
+ "Tone mapping" above bumpmapping
+ "View range" slider below "Antialiasing" (there is PR that will discard autorange here https://github.com/minetest/minetest/pull/3749)

**Comment by paramat** [comment]
Tone mapping, maybe.
View range slider, no, that's easily adjusted in-game (the only place you know what range is optimum) and sliders are imprecise.

**Comment by paramat** [comment]
This PR should go in fast because it's delaying other stuff, so above issues can be another commit.
:+1:

**Comment by paramat** [comment]
:Tested, i will merge soon.

**Comment by paramat** [comment]
ecc8b70182b9ad3aaec910d7c8b32fc54cac824a

**Pull request closed without merging**
