### PR TITLE
lua_api.txt: Add link to Minetest Modding Book

### LINKED ISSUE #8825: Add a link to Minetest Modding Book to Lua_api.txt
Just a proposal/suggestion to add
https://rubenwardy.com/minetest_modding_book/en/index.html

to
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6

of
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt

It is currently _the_ most useful documentation related to modding.
Of the existing two, the first one basically loops back to the Lua.api.txt, 
the second brings one to a page known to be outdated and often no longer accurate for the most part (as devs and others will often tell new comers to modding)

Not meant as an insult, just an observation.
SO adding a link tot eh modding book only makes a ton of sense.

### PR DESCRIPTION
**Pull request by ClobberXD**
Please advise regarding the wording and the placement of this point, and whether this should be a proper sentence with more details, instead of a bullet point.

Closes #8825

### CODE REVIEW

**Comment by TumeniNodes** [comment]
Dang, you beat me to it xD
Hopefully this gets good support (I think it will)

**Comment by ClobberXD** [comment]
> Dang, you beat me to it xD

You could've made a PR straightaway, lol :P

I thought you didn't want to make one, and hence created an issue instead.

**Comment by TumeniNodes** [comment]
I'm kidding, it's not a big deal ; )
The important bit, is seeing it get added

**Comment by pandaro** [comment]
it would be a good idea

**Comment by SmallJoker** [comment]
I'm undecided whether to declare RW's modding book as official. It's a good addition to the Lua API for sure, but should IMO be listed as "Additional references" or "Further tutorials".

**Comment by rubenwardy** [comment]
You should link to the language independent page

`https://rubenwardy.com/minetest_modding_book/`

**Comment by ClobberXD** [comment]
Done

**Comment by paramat** [comment]
:+1: good idea.

(The wiki seems just as unofficial as the modding book)

**Pull request merged**
