### PR TITLE
Online menu: Do not show ping to server list, use `lag` instead.

### PR DESCRIPTION
**Pull request by sofar**
The `ping` value is an entirely nonsense indicator, which gives players
an entirely wrong indication about game performance and in-game lag:

1. Since it indicates the value from the game server to the
servers.minetest.net serverlist, it bears zero correlation to the
actual ping of the player to the server list.

2. Because that relationship is absent, the player could actually
get a better ping than the serverlist server, since, a US player
connecting to a US server would get a much lower ping than indicated.

3. A player thinking that a low ping server would be good, could be
choosing a server that is high ping for them, since a player in Japan
or Australia isn't actually going to ever get a good ping value to
a server in Europe.

Fortunately, we already have a good number that indicates the game
server performance, it's just not based on network latency, but based
on `max_lag` - the indicator as to how well the server is capable of
handling game ticks in time.

As our default servertick is 0.09, and was 0.10, we should expect
most idle servers to be a few ms above 0.100. Busy servers will peak
out above 0.2.

I've studied the server list and made several spreads of the max_lag
values reported by each server. It turns out that of the 200 or so
servers reporting, 90% is under 0.105, and this indicates that they're
idle. We label these as "green".

We see only 10 or so servers that have loads above ~2x that value,
so I've chosen .205 as "red" indicating high load. At that value,
players are experiencing 100ms+ delays in all their actions, so it's
a good indication that the server isn't capable of keeping up or is
seeing "lag" spikes.

I've divided up the remaning gap between .105 and .205 in two equal
sections for "yellow" and "orange".

I believe this measure is much more fair than ping values. Yes it can
possibly be cheated by a server operator, but so can ping values,
because one can just choose a cloud host that is in germany and
completely lie to the userbase. All english spoken servers are likely
focussed more on US player base, and are needlessly penalized with
"high ping" icons, and the same for many of the non-EU local servers
that target local player bases.

### CODE REVIEW

**Comment by nerzhul** [comment]
sounds nice, i perfer the previous image than this image which is not clear

**Comment by Fixer-007** [comment]
>Since it indicates the value from the game server to the
servers.minetest.net serverlist

Now this is a huge downside, why nobody told this on merge? :/ On the other hand I would like proper latency measurement and display (incl showing ping/lag on hover), maybe somehow combined with server lag?

**Comment by paramat** [comment]
I approve concept, i prefer that the previous bars icon is used coloured.

**Comment by paramat** [comment]
Also maybe the maths behind the value might need reconsideration, there is some concern, see discussion http://irc.minetest.net/minetest-hub/2017-10-07#i_5100772 onwards.

**Comment by paramat** [comment]
2 server owners are not happy with using 'max lag' as a playability indicator, and i agree with them, the value decreases to half in roughly 5mins so is affected for a long time by rare large lag spikes, which players don't mind if the rest of the time has low lag.

**Comment by sfan5** [comment]
> This is a huge downside, how nobody mentioned this on merge? :/

When discussing the respective PR the focus probably was on how it looks (and it did look nice),
instead of considering the technicalities behind it.
> because one can just choose a cloud host that is in ~~germany~~ the netherlands and
completely lie to the userbase

FTFY

**Comment by rubenwardy** [comment]
Creative servers with minimal PvP will be fine up to 0.22s steps or so

So I think it should be:

| Average Server Step | Color of indicator |
|---------------------|--------------------|
| x <= 0.1s             | Green              |
| 0.1s < x <= 0.2s    | Green-yellow       |
| 0.2s < x <= 0.3s    | Yellow             |
|  0.3s < x <= 0.5    | Orange             |
| x > 0.5               | Red                |

Note checks should be 0.005 above the limit, to allow slight variations

Whether m_lag is a good stat to use is another matter

**Comment by rubenwardy** [comment]
Another thing - it needs to be confirmed whether this is `m_lag` or `max_lag`. Max_lag takes 30  minutes to recover from a second spike - say worldedit - which is way too long.

**Comment by shivajiva101** [comment]
max_lag isn't the most useful value to use to weight the display icon, it's just a different deficiency than the current method given how heavily it factors lag spikes...

**Comment by paramat** [comment]
Keep in mind some (very playable) servers use a serverstep of 0.2, i agree that serverstep should be included in the value we use, as it is a measure of experienced lag, but we should be lenient enough that those servers with 0.2 do not get a low rating just because of that.

**Comment by Ezhh** [comment]
max_lag isn't very helpful for this purpose as has already been said.

It's also worth considering that not all servers need to meet the same requirement to be perfectly playable (for example, a CTF server vs. a creative server). A lot depends on the type of server, so the green category should be broad enough in range for this.

**Comment by paramat** [comment]
> It turns out that of the 200 or so
servers reporting, 90% is under 0.105, and this indicates that they're
idle.

> We see only 10 or so servers that have loads above ~2x that value,
so I've chosen .205 as "red" indicating high load.

These 10 are probably the ones in use, so should not be 'red', as you wrote the 90% are probably idle (not generating new terrain). Most servers have intensive mods that will cause high lag spikes.

**Comment by paramat** [comment]
maybe include #6493 in this PR?

**Comment by sofar** [comment]
@paramat 

> 2 server owners are not happy with using 'max lag' as a playability indicator, and i agree with them, the value decreases to half in roughly 5mins so is affected for a long time by rare large lag spikes, which players don't mind if the rest of the time has low lag.

Every server operator with a server outside of the EU disagrees with displaying ping to servers in the EU. If only 2 server operators disagree with showing lag, that's a huge gain in support.

**Comment by sofar** [comment]
> those servers with 0.2

This is somewhat illogical, since those server operators deliberately chose to lower the games' responsiveness. I don't see why that shouldn't count against them, they can always adjust it back.

**Comment by sofar** [comment]
> sounds nice, i perfer the previous image than this image which is not clear

The old image was very ambiguous. Does 1 bar mean low ping? Does 4 bars mean better phone signal? It doesn't make sense in many ways, lower-is-better is really hard to put into a graph with higher-is-better visuals, which is why I don't like the old graph.

I'll take suggestions, but I'd like to stay away from using higher-is-better visuals entirely here myself.

**Comment by nerzhul** [comment]
@sofar invert the bars, it's like phone, then known :) 4 bars + green, 2 bars + yellow, 1 bar + red

**Comment by sofar** [comment]
https://github.com/minetest/minetest/blob/master/src/server.cpp#L572

This is using `m_lag`

**Comment by sofar** [comment]
Maybe this is more logical as a visual. More bars -> better. Turns orange/red.

As can be seen, not a lot of servers even show up yellow or worse, I had to look for them in the server list. And given the time (saturday) the player could is very high atm.

**Comment by nerzhul** [comment]
@sofar i like it

**Comment by paramat** [comment]
> Every server operator with a server outside of the EU disagrees with displaying ping to servers in the EU. If only 2 server operators disagree with showing lag, that's a huge gain in support.

I actually agree with removing ping, see my comments. The reduction in numbers opposing cannot be used as an argument for the new implementation because we're all agreed the ping is meaningless. Something extremely bad being removed is no argument for something less bad but still bad.

> This is somewhat illogical, since those server operators deliberately chose to lower the games' responsiveness. I don't see why that shouldn't count against them, they can always adjust it back.

You misunderstood, i am arguing that their serverstep should be included in the lag value used. I'm just saying that a server with step 0.2 which is otherwise lightweight and playable shouldn't be marked with a low rating like red.

> The old image was very ambiguous. Does 1 bar mean low ping? Does 4 bars mean better phone signal? 

Good point, but if we use bars like a phone then more bars == better == lower lag.

**Comment by sofar** [comment]
@paramat 

> 0.2 which is otherwise lightweight and playable

I'm not argueing the `0.2` value. The fact is that increasing server step values cause a delay in server responsiveness, it is literally a definition of it. So, therefore, increasing server_step should never be interpreted as "better" simply because it can never be better than a server which services events at 10x per second.

Math, basically.

**Comment by sofar** [comment]
I pushed new scale values: (in parenthesis, number of servers exceeding this limit with current data)

0.275+ - red (7/200 - 3%)
0.225+ - orange (9/200 - 4%)
0.125+ - yellow (21/200 - 10%)

0.125- - green (179 - 89%)

**Comment by paramat** [comment]
> The fact is that increasing server step values cause a delay in server responsiveness, it is literally a definition of it. So, therefore, increasing server_step should never be interpreted as "better" simply because it can never be better than a server which services events at 10x per second.

I totally agree =)

**Comment by jastevenson303** [comment]
89% of total servers will be green.  By this metric, an idle sever is "performing" better than an active one.  (This is not accuracy.)

Currently you have to spend money to cheat the server list, or at least move to the Netherlands.  With this patch, one would simply need to edit a line in the source file.  Talk about leveling the playing field.

Please do not replace the ping bars with a dumb max_lag interpretation.  Fix the ping to be client->server ping, instead of current server->serverlist ping.  Add the max_lag indicator somewhere/somehow else, if even at all.

**Comment by sofar** [comment]
@jastevenson303 I look forward to your patch that does what you suggest is to be done.

**Comment by kilbith** [comment]
> The ping value is an entirely nonsense indicator

Tell that to Valve. Pretty much all commercial games sort their serverlist by the ping. It just happens that the way Minetest gets this information sucks balls by design.

> When discussing the respective PR the focus probably was on how it looks (and it did look nice),
> instead of considering the technicalities behind it.

Indeed, though I have [asked](http://irc.minetest.net/minetest-dev/2017-02-03#i_4802778) but almost nobody cared (is this surprising?).

> 89% of total servers will be green

Likely because some influential admins in the -hub crew are just too afraid to have their servers being discriminated in the serverlist?

**Comment by sofar** [comment]
Hahaha, I like that response. Yes, there was a certain amount of complaining in -hub.

I guess I didn't pay attention when the original patch adding this was merged, but now that I run a server myself (with 0.05 m_lag thank you) I do believe that players have the right to data that is representative and meaningful, not data that is correct but meaningless to everyone except EU players.

If this is still to sour to bite through for some of the server operators, the next PR I send will just remove all the ping display, and that's a loss to all *players*. So, a casual +1 from you would help, I think.

**Comment by kilbith** [comment]
Obviously +1 from me, this is less worse than it is currently.

**Review by nerzhul — APPROVED** [review]

**Comment by nerzhul** [comment]
👍 
Note: ping indicator in proprietary software is done by client itself not the serverlist, and is a mor accurate latency indicator

**Comment by shivajiva101** [comment]
> Hahaha, I like that response. Yes, there was a certain amount of complaining in -hub.

Possibly due to you deciding to listen to yourself as the authority on this

> I guess I didn't pay attention when the original patch adding this was merged, but now that I run a server myself (with 0.05 m_lag thank you) I do believe that players have the right to data that is representative and meaningful

sounds like an admission that you didn't really care about what went into Minetest before you started running a server.

> If this is still to sour to bite through for some of the server operators, the next PR I send will just remove all the ping display, and that's a loss to all players. So, a casual +1 from you would help, I think.

Stunning, it seems like a threat to remove ping if you don't get what you want, what makes you think that PR would be accepted...

If you want to do something meaningful with latency, you should add it to the client like proprietary software does.

**Comment by Ezhh** [comment]
When the values set discriminate against servers that players have actually (and consistently) reported they feel have great performance, and where those servers have a consistently stable performance, yes, I'll complain. It does not matter if it's my server or anyone else's, but it tells me the boundaries you use are off. You have since adjusted them, which fixes that point, though I still have concerns it will mean adjusting server step (note: on servers where the adjustment does not worsen player experience) will now come with a penalty in the form of an indicator that is not reflective of the playability of that server.

You will also note that most of the complaints were regarding max_lag, which it turns out isn't what you are using at all. You did not know what the max_lag values being discussed mean, so you should not be surprised about complaints on that point.

You'll also note I've at no point disputed ping is bad, or claimed that adjusting server step to a higher value is good for all servers. It is simply that, depending on the server type, small adjustments can have no noticeable affect.

shivajiva's message above really sums up the rest of what I'm thinking.

**Comment by sfan5** [comment]
Since I haven't really followed this closely, has it been considered to hold `creative` servers lag values to different standards than non-`creative` servers.
It has been [pointed out](http://irc.minetest.net/minetest-hub/2017-10-07#i_5101312) a few times that creative servers do not need the same low lag to provide a good player experience.

**Comment by IhrFussel** [comment]
I set my server step from 0.2 to 0.15 now and it's STILL not enough?

Are you kidding me? You expect me to set the step to 0.1 or lower with 160(!) mods installed???

My server is neither creative nor PvP-focused ... it is "social survival" so lag doesn't matter that much

When I started my server NOBODY told me that setting the server_step setting to something else than 0.1 would EVER give me a disadvantage and I find that disgusting that you try to decide on a general measurement for "server performance" now instead of checking the performance PER-SERVER, taking server_step setting into calculation.

**Comment by paramat** [comment]
> I set my server step from 0.2 to 0.15 now and it's STILL not enough?

I see on IRC you mean 'not enough for green'. Your server doesn't justify the highest rating because, as you admit, it is one of the slower servers, however it also doesn't deserve red which it will mostly avoid with the new encoding.

> When I started my server NOBODY told me that setting the server_step setting to something else than 0.1 would EVER give me a disadvantage

It's not a disadvantage to get yellow or orange, the colours are simply an encoding of a value, and for that encoding to be useful as an indication of a value some of the slower servers have to be yellow or orange.
It's like encoding lag with numbers 0-10, and no-one wants to be anything other than 1, but if most lags are 1 then the encoding is meaningless.

It seems to me the issue is that we are colour-conditioned to see green as 'ok', but yellow or orange as 'potential danger' and therefore a negative thing. So everyone now wants to be green.
Players also have this colour-conditioning and will inevitably see yellow or orange as 'potentially bad' which is the wrong interpretation.

It seems that encoding with colour is the problem, perhaps either use a plain number which has no associations, or use a new colour coding that uses blue too so that most servers can be blue or green both seem 'ok'.

> taking server_step setting into calculation.

As i wrote on IRC, server step has to be included because that affects experienced lag, subtracting that means a server with a step of 1s (unplayable) could easily be green whilst good servers with step 0.1 could be yellow / orange, if that happened server owners would complain.

I'm thinking don't use colours, use a number or a height bar or something neutral.

**Comment by paramat** [comment]
jastevenson303

> Fix the ping to be client->server ping, instead of current server->serverlist ping.

Please read the discussions, that is not actually possible.

**Comment by paramat** [comment]
Some people, including devs are questioning how the serverlist 'max lag' value responds to a brief lag spike, the calculation of the value encoded here may need reconsideration.

**Comment by jastevenson303** [comment]
The whole thing is pointless, because max_lag, or m_lag, or whatever are indicators of the host machine local to itself.  When people on the internet read "lag", they usually think about network lag.  Yes, I mean ping.

Anything is possible.

**Comment by paramat** [comment]
'Anything is possibe' is just a silly comment that ignores reality or practicality. Ideally i guess it should be correct network ping plus server lag, but as i wrote, correct ping is difficult or impossible, go read for yourself why.

**Comment by nerzhul** [comment]
it's neitheir difficult nor impossible it just needs to be coded

**Comment by rubenwardy** [comment]
I do not want my client to ping all servers on start up. It's slow and also privacy infringing, IMO. I don't want even my IP address to be recorded unless I decide to connect to a server

**Comment by jastevenson303** [comment]
I don't mean to step out of line; I've read, and re-read this discussion now.  I am coming from an open source game engine that does this behavior, and always wondered why Minetest did/does not.

Let us separate and acknowledge that this PR and what is happening has nothing to do with network latency, and thus remove the wireless signal bars, which almost explicitly represent network latency.

**Comment by celeron55** [comment]
If load is indicated, it should be indicated with a load bar like originally suggested by sofar, not with a signal strength indicator. As a ping indicator, like we've had until now, the use of the signal strength symbol is fine. It's very confusing to any technical person to do otherwise.

Otherwise I think indicating the server's ability to keep up with load is currently more important than indicating ping, as load tends to be a larger problem with MT servers.

**Comment by SmallJoker** [comment]
I agree with @celeron55 -  the signal strength symbol looks nice but isn't really suited to display lag.

_The following idea/suggestion goes outside the builtin code:_
As we allow configuring the server step, we should also care about this when calculating the lag. Server load will be noticeable by increased execution time per step. Depending on how big this difference to the setting is, we can determinate how busy the server is.

(pseudocode) `(lag - custom_server_step) / custom_server_step` (value towards 0 = best)
1) Clear feedback for server owners about their server configuration
2) Tells how well the server can process the steps
3) Slower machines can save calculations using a slightly higher server step as compensation

**Comment by paramat** [comment]
Ok so correct ping may be possible but it is controversial as the discussions show.
I agree that server lag is much more significant that correct ping alone.

**Comment by paramat** [comment]
(pseudocode) (lag - custom_server_step) / custom_server_step (value towards 0 = best)

A server with a long unplayable server step could still get an excellent rating that doesn't reflect player experience of server lag.

**Comment by Ezhh** [comment]
@paramat If looking at removing penalties for different server steps, there should be a max acceptably good server step agreed on. Anything above that value should get a lower rating, since something unplayable needs to reflect that. We just need to acknowledge that leaving the default (0.09) behind a little isn't going to, in many cases, give a worse experience for players. I can speak for 0.15 being fine on a creative server, and I'd imagine 0.2 is fine as well for such servers (based on what others, including devs, have said). So maybe up to 0.2 should be considered the acceptable range and should be given some leniency within the ratings, then any server step higher than this should be penalised.

**Comment by sofar** [comment]
I fully admit I opened a can of worms when I made this PR, and I certainly did *not* consider all the aspects of the contents of said can of worms.

Here is how I do software engineering:
1) determine problem
2) consider solutions
3) discuss solutions
4) propose a solution
5) listen to feedback
6) revise solution

If you think that this is an unfair way to do engineering, please remove your github account and do not join a knitting group, ever, in your life. Woodworking is more likely to be a good hobby for you.

If you think I didn't do item (3) well enough, you are correct, because this patch is not even 20 lines long and sometimes code is a better way to discuss solutions and negative sides.

Here's what I've learned so far:

- I called the "thing" displayed "load" from the start, even the tooltip is marked "load" in my PR. People still think it's ping. Just because I expressed "load" in a "time" value.
- Yes the complaining is annoying, but I just almost cut my finger off this morning, and that hurt a lot more. You want pictures? very bloody.
- Load (m_lag) can be spoofed by the server owner. Nobody is really worried about this.
- the current ping-to-serverlist is unacceptable if you ask me, but the idea of removing it is met with resistance as well, so people *do* want their servers to be *judged* by players. Everyone wants to be at the top of the list. A small pissing contest ensues.
- btw, the load value should have just been calculated without server_step entirely, and solely reflect the time spent being *active*. So if your server uses a server_step of 0.1 seconds, and it takes your server 0.009 seconds to return back to sleeping, the value returned to the serverlist should be 0.009 and not 0.109. That way, we actually would get a lot better data about minetest server performance and get data that is independent of server_step. Alas, we can't fix existing deployed servers in the field.

I'm squarely all for doing pings from the client to the server. People who run a public server should be agreeable with accepting these requests and can block ICMP or UDP pings trivially. If we do UDP pings to the actual game port, this might be really well doable. I mean, @nerzhul could probably do it. But I owe him like a crate of wine at least at this point. I think it's bizarre that some people cringe at the privacy aspect of clients pinging servers, and at the same time those server operators are probably in spectator mode watching every little bit that the players do on their servers.

Barring real ping values, a proper self-reported load value is really not a bad idea. I even wouldn't mind it if servers opt-out of reporting those values, which is better than cheating them anyway.

**Comment by rubenwardy** [comment]
\*bump\*.    I think it might just be worth removing this indicator

**Comment by paramat** [comment]
^ I agree, i'll +1 that.
@sofar

**Review by Megaf — APPROVED** [review]

**Comment by paramat** [comment]
The 'approval' feature is more for core devs. best not use it as it could cause confusion at a quick glance.

**Comment by NewbProgrammer101** [comment]
"As an end-user, all I want is to pick a server with good connection."

**Comment by paramat** [comment]
Neglected, closing for now. I'll support a simple removing of ping.

**Pull request closed without merging**
