### PR TITLE
Fixes building on OSX caused by e4bff8b (refs #2613)

### PR DESCRIPTION
**Pull request by neoascetic**
Was failing because include was in context of namespace

### CODE REVIEW

**Comment by neoascetic** [comment]
@ShadowNinja here the fix for that OSX issue

**Comment by ShadowNinja** [comment]
This uses spaces instead of tabs.

**Comment by neoascetic** [comment]
Fixed

**Comment by neoascetic** [comment]
Ok, there are lot of labels in this PR now, and they are cool, but why don't you simply accept it?

**Comment by celeron55** [comment]
The #ifndef _WIN32_WINNT block has to be moved before the windows.h #include. It modifies stuff that is included from there.

**Comment by est31** [comment]
@SmallJoker can you try this pr, whether it builds for you?

**Comment by neoascetic** [comment]
Bump

**Comment by est31** [comment]
@neoascetic we have to get confirmation by windows users first, not that this commit breaks their build now. bumping is useless.

**Comment by neoascetic** [comment]
Why no one tested the game on OSX when that breaking PR was applied then? 

I think it would be awesome if travis setup will not only build the game, but also put binaries somewhere to speed up test process.

**Comment by est31** [comment]
This will fix #3124 as well, I guess.

**Comment by est31** [comment]
Looks good to me as well.

**Comment by est31** [comment]
merged with reworded commit msg in 588f0c1fb03db162c573ac92b13f0de465e3040c

**Pull request closed without merging**
