### PR TITLE
Add chat message length limiting

### PR DESCRIPTION
**Pull request by zaoqi**
`/me X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X `...

### CODE REVIEW

**Comment by rubenwardy** [comment]
This would cause long messages to just be dropped, it would be better to send the limit to the client as well and have the text box also be limited

**Comment by SmallJoker** [comment]
We have the settings
```
chat_message_max_size = 500
chat_message_limit_per_10sec = 8.0
chat_message_limit_trigger_kick = 50
``` 
but [their documentation](https://github.com/minetest/minetest/commit/d4c76258e#diff-8a7fb2fa05891dc5f28dac610384b12cR777) seems to be gone.

**Comment by rubenwardy** [comment]
the culprit: https://github.com/minetest/minetest/commit/211d919b546e25e798982dd8df24ec82ecee2d6b

**Comment by zaoqi** [comment]
Is chat_message_max_size implemented?

**Comment by nerzhul** [comment]
all is implemented, just tune them.

**Pull request closed without merging**
