### PR TITLE
Add WordWrapper util (with unit tests, ellipsis truncation, and fixes)

### LINKED ISSUE #10285: Long infotexts are cut off
##### Minetest version
```
5.3.0
```

##### Summary
If you point to a node with a long infotext, the displayed infotext might eventually cut off. To me, it happens at around the 4th line.

##### Steps to reproduce
Place a sign in MTG and write a lot of text into it.

### PR DESCRIPTION
**Pull request by rubenwardy**
This util is currently used by StaticText and EditBoxes. I plan on making a `label[]` with a size and ellipsis truncation in a future PR - this will be used in ContentDB's dialog.

* Reduce code duplication by creating a word wrap util.
* Fixed support for `\r\n`.
* Add ellipsis (`…`) when text is truncated, to avoid text being cut off.
* Added unit tests.
* Fixed support for soft hyphens (a unicode control character).

Fixes #10285

See also https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap

Long info text:

image

## To do

- [x] Fix support for `\r\n`
- [x] Add support for ellipsis
- [x] Fix support for soft hyphens
- [x] Fix not wrapping soon enough in StaticText causing text to clip
- [x] Fix EditBox selection issue
- [x] Readd support for disabling `/n` in singleline text boxes with wrapping
- [ ] DRY-ify WordWrapper
- [ ] ~~Break words~~
- [ ] ~~Add support other unicode control characters~~

## How to test

Run unit tests, try it out with various formspec and infotexts.

See meta editor in https://github.com/minetest/minetest/pull/10431

### CODE REVIEW

**Comment by Wuzzy2** [comment]
I like this, except the fact that you changed the ellipsis for no apparent reason. Now it "kisses" the final letter (no space), which is not how all languages work.
There was a reason why I put the ellipsis in an extra line.

Suggestion: Put ellipsis in extra line and in parenthesis. Like so:

> Lorem ipsum
> dolo sit amed
> (…)

Maybe make the whole elipsis thing translatable as well (including the parenthesis), just to be sure. :)

**Comment by Wuzzy2** [comment]
Dumb question: Why this?:

```
s32 height_line = font->getDimension(L"A").Height + font->getKerningHeight();
```

Why "A" instead of "Ay", which was used before?

**Comment by rubenwardy** [comment]
> I like this, except the fact that you changed the ellipsis for no apparent reason.
> There was a reason why I put the ellipsis in an extra line.

This means that you will lose a line. It would look super weird in the ContentDB dialog, for example.

This functionality is based on Android's [ellipsize](https://developer.android.com/reference/android/widget/TextView#attr_android:ellipsize) feature

>  Now it "kisses" the final letter (no space), which is not how all languages work.

Good point, I'll make sure this can be translated for different languages.

> Why "A" instead of "Ay", which was used before?

I copied this from StaticText, it was "A" there before this PR. This is probably incorrect, though, I'll change to "Ay"

**Comment by v-rob** [comment]
`font->getDimension(L"Any string you like").Height` returns the same for every string; only width varies.

**Comment by Wuzzy2** [comment]
I think “Break words“ should be removed from the TODO list, that's something different (because of the complex and inconsistent rules that many langauges have fror this). Unless you actually already have a solution in mind.

**Comment by rubenwardy** [comment]
> I think “Break words“ should be removed from the TODO list, that's something different (because of the complex and inconsistent rules that many langauges have fror this). Unless you actually already have a solution in mind.

I don't really have any idea how to do this properly, so yeah I could just remove it

Arabic words can get longer when you remove characters, which is fun

**Comment by rubenwardy** [comment]
closing as wip

**Comment by Wuzzy2** [comment]
What features/bugfixes specifically are missing for this PR to be mergable?

**Comment by rubenwardy** [comment]
My time, mostly

**Comment by rubenwardy** [comment]
Possibly the biggest problem with this is RTL language support - but Minetest didn't support this properly before anyway

**Pull request closed without merging**
