### PR TITLE
Use tangent space meshes only when shaders are enabled

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by paramat** [comment]
Thanks will test soon.

**Comment by est31** [comment]
:+1: looks good.

**Comment by nerzhul** [comment]
:+1:

**Comment by paramat** [comment]
FPS up from 42 to 52, 42 is 81% of 52 so a 19% drop, close enough to 21% so PR seems good.
bf884e37a06e0a8dd6c31789a69921f07ec5a9a9

**Pull request closed without merging**
