### PR TITLE
Add extra leeway to player anticheat to deal with attached move_to()

### LINKED ISSUE #10908: Anticheat misbehaving by resetting players location and viewdirection when attached to entity with move_to(pos, true) being called
##### Minetest version

```
Minetest 5.4.0-yl_0.1.2-40ad976-dirty (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3

--note that yl_0.1.2 indicates a version for YourLand game, but the 2 minor changes that it makes have nothing to do with the following bug report
```

##### Summary

AliasAlreadyTaken and I tested my Wormball minigame with 5.4 dev. It completely breaks the game. Wormball creates entities to attach players to. Then players are attached, and every 0.4 sec (in a globalstep) players are moved by moving the entity with `ent:move_to(pos,true)` Players' view direction is used to steer and determine which cardinal direction to move next. 

-BUG/antifeature-
5.4 differs from 5.3 in that when move_to is called on the entities, the players view direction is set to the entity's forward direction.

This completely breaks gameplay and makes Wormball annoying, confusing, and difficult to use.

note that mods, if they _wish_ to set players' view direction after a move_to(), are perfectly capable of doing so. However, there will be other applications like my Wormball minigame that doing this ruins the mod.

##### Steps to reproduce

to reproduce exactly, install arena_lib, signs_lib, and Wormball on a 5.4 and a 5.3 version. Set up arenas in both, and compare gameplay (or the lack thereof in 5.4)

For a simple test of the anti-feature, create a mod that attaches a player to an entity, then repeatedly call move_to(pos,true) on that entity with the player attached. While you are riding the entity, try to look around. Your view point will be repeatedly snapped back to the entity's forward direction.

https://content.minetest.net/packages/Zughy/arena_lib/
https://content.minetest.net/packages/VanessaE/signs_lib/
https://notabug.org/MisterE123/wormball

### PR DESCRIPTION
**Pull request by sfan5**
This is **not** the ideal solution but simple and good enough for now.

fixes #10908

## To do

This PR is a Ready for Review.

## How to test

See test mod in https://github.com/minetest/minetest/issues/10908#issuecomment-774481432

I can also suggest testing this with extra local latency: https://daniel.haxx.se/blog/2010/12/14/add-latency-to-localhost/

### CODE REVIEW

**Comment by TheTermos** [comment]
Why?
The causes of the problem are known by now and the other one is close, Why try to last minute an uninformed one?
Isn't the code rotten enough already?

**Comment by sfan5** [comment]
I know that this is a worse solution.
The perspective here is that changing attached player position to server authority last minute is more likely to break something, so this solution might be preferable to get 5.3.0 out the door.

**Comment by TheTermos** [comment]
> changing attached player position to server authority last minute is more likely to break something,

You might have a point there if it were the case that it's being changed to server authority, but it isn't. Server always acted as if it had the authority, it's just at some point somebody had a bright idea that the client should have a say as well, so most problems, if not all come from client and server fighting for control.
We can't have that, and the authority belongs where the parent's authority is, for obvious reasons.

There's nothing to be coy about, this bug must be fixed, and this PR works in the opposite direction.

**Comment by sfan5** [comment]
You're right, the premise this PR is built on is wrong. Attachments *do* have server-side authority (more on that in another comment).

Claiming it works contrary to fixing the bug is nonsense however, this PR literally makes the specific bug reported go away. It "just" does it awfully wrongly.

**Pull request closed without merging**
