### PR TITLE
Update singleplayer tab in mainmenu

### PR DESCRIPTION
**Pull request by poet-nohit**
This fixes the situation where it would give you "builtin/mainmenu/tab_singleplayer.lua:167: attempt to index a nil value" where you have nothing selected (for example, switch to minimal game, delete all your old worlds, and then click the toggle buttons for creative or damage).

### CODE REVIEW

**Comment by kilbith** [comment]
This fixes that : https://github.com/minetest/minetest/issues/2548

**Comment by fz72** [comment]
In tab server is the same algorithm implemented. It should be fixed there, too.

**Comment by poet-nohit** [comment]
There may be other cases where this sort of checking should take place. Incidents of this may be rare, but it does take down the main menu, which is kind of important IMHO.

**Comment by nerzhul** [comment]
@poet-nohit please rebase

**Comment by poet-nohit** [comment]
Something wrong? I don't see a merge conflict.

**Comment by poet-nohit** [comment]
Let me try this again...

**Pull request closed without merging**
