### PR TITLE
Fix optional dependencies causing cascading failures with dependent mods

### LINKED ISSUE #8601: Optional dependencies being overridden/turned into hard dependencies
This issue is very similar to #3136
(very nearly a duplicate, in fact, but that one's old, and long since closed)

Using 5.0.1-release, singleplayer

Consider this example dependency tree:

Mod A hard depends on mod C.  
B hard depends on D, optional-depends on F
C depends on nothing
D optional-depends on E
E hard depends on F

Now disable mod F.  Let's say you're doing this to test a feature in B that changes behavior depending on the presence of F.

In this case, E of course doesn't load, but D won't load either, because now the engine treats it as if it *hard-depends* on E, contrary to its `depends.txt`/`mod.conf`.  This causes B not to load as well, since it needs D.

So while one expects A, B, C, and D to load in this example, only A and C get loaded, thus preventing the modder from doing the test they wanted (to check B's behavior without F).

OK, now try it in a real setup:

* Download Dreambuilder
* Create a new world,
* Enable the whole modpack in that world's config
* Now disable just `mesecons` (the one base mod from that project), leaving everything else enabled
* Start the world.
* Many mods that should have loaded won't, for example `homedecor_lighting` (it has a number of dependencies, but mesecons is strictly optional)

Now, go back into the world config and disable all of the `mesecons*` mods (there are about 30, all grouped together), then save and start the world.  You'll find that many of the items that should have loaded the first time work now, even though you were turning things *off* in the config.

It's as though hard dependencies propagate upwards through the dependency tree once a mod can't be satisfied, overriding cases where mods are explicitly set to be optional.

### PR DESCRIPTION
**Pull request by IceDragon200**
Add compact, short information about your PR for easier understanding:

This is an attempt to fix #8601 

The mod resolution has function has been replaced by a simple class and recursive function that iterates through each dependency and attempts to resolve it as well.

From my quick test it resolved the issue as expected, but may require more testing for larger dependency trees, as recursion can get pretty dicey when not handled properly.

## To do

Maybe more testing?

## How to test

See #8601 for the failure case, and test if it loads as expected

### CODE REVIEW

**Comment by numberZero** [comment]
yay, it copies a metric ton of stuff during resolving... (both old and new code)

still, circular dependencies should be checked IMO, esp. circular optional dependencies as they are more likely to appear yet would break ordering otherwise, causing weird bugs.

**Comment by IceDragon200** [comment]
@numberZero Okay I've made some changes and added support for the circular dependency tracking, could you give it a look again and see if the copying issue has been somewhat resolved, I've tried to use references in most places.

**Comment by SmallJoker** [comment]
There's one more interesting case: ([reported here](https://github.com/minetest-mods/unified_inventory/issues/177))

 * Mod A soft-depends on mod B
 * Mod B hard-depends on another mod which is not enabled
 * Mod A fails to load because mod B failed to load (turned into a hard-dependency)

How to test: MineClone2 game + unified_inventory

**Comment by IceDragon200** [comment]
@SmallJoker I'm going to go out on a leg here and say my PR behaves exactly as intended, `unified_inventory` has a hard dependency on `default`

And just to prove my point, I've tested my PR against `Mine Clone 2 master 8e931e92f` and `unified_inventory master afd38e0`.

MineClone2 refused to load at first, because my PR broke a undocumented behaviour of the previous mod loader (alphabetical ordering without explicit dependencies), which I believe is a bug to begin with, they shouldn't be relying on something that flaky, in short you can't guarantee that `_mcl_autogroup` will be loaded after every mod.

My solution  was to add a hard dependency on `mcl_autogroup` (which was the bare minimum needed to define all the functions) and then offloaded the overwrite:
```
minetest.register_on_mods_loaded(overwrite)
```

I also had to move the hardness values into the overwrite function as well (once again it's relying on implicit ordering)

Afterwards other mods began failing because they were relying on mods that weren't explicitly declared.

List of mods that needed additional explicit dependencies:

* `mcl_armour` needed `mcl_damage`
* `mcl_brewing` needed optional `mesecons_mvps`, I would just optionally pull all of the `mcl_mesecons` in, but bare minimum was that
* `mcl_playerplus` needed `mcl_sprint`

So I'd say instead of my changes failing to load these mods, these bugs have always existed and were ignored by the old resolver, but are now forced to be properly declared.

So no, my PR does not turn soft dependencies into hard dependencies, it exposes implicit dependencies which breaks non-conforming mods.

All they have to do is address the missing dependencies and everything works as intended.

Here is a snippet from the mod loader:

```
2021-07-10 10:59:15: ERROR[Main]: mod "unified_inventory" has unsatisfied dependencies:  "default"
2021-07-10 10:59:15: WARNING[Main]: mod "awards" has unsatisfied dependencies (optional):  "sfinv"
2021-07-10 10:59:15: WARNING[Main]: mod "doc" has unsatisfied dependencies (optional):  "sfinv_buttons" "central_message" "inventory_plus"
2021-07-10 10:59:15: WARNING[Main]: mod "doc_identifier" has unsatisfied dependencies (optional):  "doc_basics"
2021-07-10 10:59:15: WARNING[Main]: mod "mcl_armor" has unsatisfied dependencies (optional):  "ethereal" "bakedclay"
2021-07-10 10:59:15: WARNING[Main]: mod "mcl_mobs" has unsatisfied dependencies (optional):  "cmi"
2021-07-10 10:59:15: WARNING[Main]: mod "mobs_mc" has unsatisfied dependencies (optional):  "default" "bones" "mesecons_materials"
2021-07-10 10:59:15: WARNING[Main]: mod "mcl_craftguide" has unsatisfied dependencies (optional):  "sfinv" "sfinv_buttons"
2021-07-10 10:59:15: WARNING[Main]: mod "mcl_skins" has unsatisfied dependencies (optional):  "intllib"
```

Notice that all 'optional' dependencies are marked as warnings, it doesn't mean the mod wasn't loaded.

Also note: `mod "unified_inventory" has unsatisfied dependencies:  "default"`, which means the mod loader refused to load it, since the dependencies could not be satisfied.

If `default` is intended to be optional, then `unified_inventory` needs to change it accordingly.

So if you can pinpoint the exact mod that isn't loading, I'll be happy look at it and see if it's an issue with the mod or with my PR.

**Comment by SmallJoker** [comment]
Yes indeed. You're totally right. I also found a bunch of missing dependencies in other parts of the game which depended on the undefined mod loading order but didn't catch the obvious `depends = mcl_autogroup` in `_mcl_autogroup/mod.conf`. The errors looked like a daisy-chain failure as seen in master - except they weren't caused by soft->hard dependency changes.

Here's an interesting scenario with three mods, each hard-depending on each other in a circle. Strictly speaking one mod will be loaded before its dependency, hence incorrect loading. Although that's nitpicking.
`2021-07-10 18:44:04: WARNING[Main]: circular dependency triggered by "a_depends_on_b" check mods in chain; resolution-chain:  "a_depends_on_b" "b_depends_on_c" "c_depends_on_a"`

**Comment by IceDragon200** [comment]
@SmallJoker Yeah, originally it was just ignored, and it is possible to load them but the order can't be guaranteed, it's a warning for now so mod developers can address it.

But it should be fairly easy to change it to a hard error if need be

**Comment by Df458** [comment]
From quick glance, this and #11438 are both aiming to resolve the same general issues but the latter has gotten further in the review process and seems likely to replace this. Probably worth keeping both PRs open until one or the other is merged though.

@IceDragon200, do you have any particular opinions on the other PR? You don't appear to have tested it yourself, since you've been in the same space I imagine you'd be in a position to help verify that it works and/or suggest anything from here that it may be missing.

**Comment by rubenwardy** [comment]
See #12217

**Pull request closed without merging**
