### PR TITLE
Redesign main menu content browser

### PR DESCRIPTION
**Pull request by rollerozxa**
This PR redesigns the main menu content browser. Very work in progress.

image

image

## To do
This PR is Work in Progress.

### CODE REVIEW

**Comment by rollerozxa** [comment]
Thanks for the feedback. Hopefully I'll have some time soon to sit down and finish this.

**Review by grorp — COMMENTED** [review]
I like this redesign. Some suggestions:

- Since there is now a separate "Installed" tab (I like that!), I think all the package sorting code should be removed. It could still be useful to show updatable packages before other packages on the "Installed" tab, but not on the other tabs. 

- The buttons in the new dialog are taller than any other buttons in the mainmenu (regular 0.8 vs. your buttons 1.0). While this is great on Android, it looks oversized on my desktop computer.
   
   Perhaps you could make the button height 1.0 on Android, but 0.8 on desktop?

- On my desktop device, the screenshots in the package list also look too big to me. Currently, they have a width of 5 and a spacing of 0.25. I tested with a width of 4.5 and a spacing of 0.5 and that looked a lot better in my eyes.
   
  However, this of course depends on screen sizes. On my Android device, the current screenshot size looks great.

- The number of tabs is kind of overwhelming. Perhaps you could add a little bit of space between "Installed" and the other tabs?

- I miss a "currently downloading [number] packages" indicator in the package list, similar to the one in the old dialog.

**Comment by AdityaMH** [comment]
now impossible to get this one.

**Comment by rubenwardy** [comment]
Closed as WIP with no progress for ages, with merge conflicts. This can be reopened if/when you're able to work on this again

**Comment by rollerozxa** [comment]
Ok, no worries, I'll get back to it sometime. If someone feels inclined to pick it up before I do then they are also free to do so.

**Comment by RustoMCSpit** [comment]
why remove adoption needed tag?

**Comment by rubenwardy** [comment]
because: #14510

**Comment by RustoMCSpit** [comment]
> because: #14510

ahh so it's a duplicate. can you check this https://github.com/minetest/minetest/issues/6733#issuecomment-2291882258

**Pull request closed without merging**
