### PR TITLE
Backport 0.4

### LINKED ISSUE #6198: Mirrored statbars
I request statbars to be able to be mirroed. “Mirrored” means the symbols go from right to left instead of left to right. The symbols themselves are not mirrored.

For example, a normal statbar with value 11 looks like this:
unbenannt

The mirrored version would look like this:
unbenann2t

### LINKED ISSUE #6471: 2D player sprite: Incorrect offset
2D player sprites are still used by a few old mods and the minimal game itself.
The new feet position of the player messed up the offset of the texture, another change shrinked the texture.

Primary issue, the zero position:
grafik
EDIT: Custom player texture from the active texture pack, but doesn't matter in terms of the position.

### LINKED ISSUE #6576: auth.txt Corruption
Both Vanessa and myself have experienced the auth.txt file corrupting (apparently fully deleted with only new entries for that day present). This has been observed on three of Vanessa's worlds and one of mine, all running 0.4.16 (not current dev).

### PR DESCRIPTION
**Pull request by sfan5**
List of commits that were backported to the `backport-0.4` branch

<b>Last updated</b>*: 2018-05-13

\*when someone last went through all missing commits and backported them

Guidelines:
* no refactoring & no protocol bump
* no mapgen, csm or formspec features
* no features that require client-server cooperation (client-side / server-side alone is fine)
* cosmetic fixes / tuning is allowed
* changes that cause too many merge problems for questionable benefit were omitted too

Bugfixes / Maintenance:
* Fix segmentation fault with tool capabilities (#5899)
https://github.com/minetest/minetest/commit/7786521f151b6006656768fdd308f1d7e1635645 
* Fix typos/mistakes in the documentation for colour related functions. (#5936)
https://github.com/minetest/minetest/commit/33b513f76cc17629a7cba47ed52db6e382f068ee
* make ret variable in /builtin/mainmenu/tab_credits.lua local (#5942)
https://github.com/minetest/minetest/commit/00dfced1956a3608311b846c85665c9b495b4056
* Fix sending color codes to clients that don't support them. (#5950)
https://github.com/minetest/minetest/commit/740b4bec07b0a43943c9d4a20a2dc1abf4c90db9
* fix an example in lua_api (#5604)
https://github.com/minetest/minetest/commit/07be63b28747714903281a4051cecea0dc3e1cb7
* (Re)spawn players within 'mapgen_limit'
https://github.com/minetest/minetest/commit/842acbfad2b70550c562f6429d02c980912d2273
* Verify HudSetParams input when hotbar textures are set (#6013)
https://github.com/minetest/minetest/commit/4dcc5985df4c94705ed7e4932a8b82a6e8c61f58
* Fix console not being properly resized after window size changed (#6020)
https://github.com/minetest/minetest/commit/318106223fc7351bd879980c17ee9c4bee65a272
* Fix console resize issue when maximising game window (#6023)
https://github.com/minetest/minetest/commit/76074ad81abe68aa2b7af4d072b659f60f1af38c
* Fix render order of overlays (#6008)
https://github.com/minetest/minetest/commit/12aad731adef495dec03f384d10b4f8f57b6a1d3
* Mgv7: Avoid divide-by-zero errors
https://github.com/minetest/minetest/commit/34e8e0e5ce2887391f55d5d7285088ec2c0f5761
https://github.com/minetest/minetest/commit/cad10ce3b747b721fd63784915e05f12bc488128
https://github.com/minetest/minetest/commit/6d2833a8879b5dd64936991bf2a3e407f26357a7
* Fix for empty key/value when reading item string with wear but no metadata (#6058)
https://github.com/minetest/minetest/commit/85d7b18d851504e6d9f637c4373cf896b1ce8e4c
* Noise: Prevent unittest crash caused by division by zero
https://github.com/minetest/minetest/commit/765fd9a0bc0bb9f08d12713dc586e7f4c59c421d
* Fix crash when using --go in command line
https://github.com/minetest/minetest/commit/80ded73f68ddd90cbf4d3b445f12ed8d94682d7f
* Fix player coordinate rounding in collisionMoveSimple() (#6197)
https://github.com/minetest/minetest/commit/0c893ea1232c96f43d6934bdce8f954ae05b1203
https://github.com/minetest/minetest/commit/248a1a8d65c483edcab328d898cc570071d6a182
* serialize: use a temporary for SerializeException
https://github.com/minetest/minetest/commit/e2a6b7c8d29a674504f80b7948a71c4a36af4ad0
* Fix Android node selection distance (#6187)
https://github.com/minetest/minetest/commit/01c319d7784c3db614a53745e5af62c43cf45c90
* Android stepheight: Only increase if 'touching ground' (#6313)
https://github.com/minetest/minetest/commit/0e0643df3567437b658431e9dad1e0eec2137a58
* Statbars: fix incorrect half-images in non-standard orientations (fixes #6198)
https://github.com/minetest/minetest/commit/520b4813832f3623f7b0b0408ecf26f36cda720b
* Fix empty legacy meta being persisted
https://github.com/minetest/minetest/commit/557bbc670451f82c384032383df80a1a92ffe724
* Fix core.wrap_text and make its behaviour consistent with the docs
https://github.com/minetest/minetest/commit/6fa2f6b4aa42683fc85a6ce4a2a03a4b47c36974
* ServerEnv: Clean up object lifecycle handling (#6414)
https://github.com/minetest/minetest/commit/04839f233f37faa9af406ea66fc6c199127781eb
* Fix Rotate Node Placement (#6424)
https://github.com/minetest/minetest/commit/5b6d4482eeee1925331d6ec122dd10cdc1aa7a30
* Set placer to nil instead of a non-functional one in item_OnPlace (#6449)
https://github.com/minetest/minetest/commit/5a3b8e34b36a1f9b1f38f91483fc25d23b142f21
* Fix blocks written by vmanip not being marked as modified
https://github.com/minetest/minetest/commit/d5a97e00eaac54def16fb53b68cfed7300af0854
* Document orientation parameter of set_attach (#6473)
https://github.com/minetest/minetest/commit/5258f3b857b289702078241e00fc7fe8aadde180
* Localplayer: Fix disable_jump effect and getStandingNodePos()
https://github.com/minetest/minetest/commit/f729b5d2bdc65ce3c51f1004c58cb93a37504b49
* Fix attached particle spawners far from spawn (#6479)
https://github.com/minetest/minetest/commit/8c16f18fdbe99aa6781a0e6e6c5b9c50d4c0b874
https://github.com/minetest/minetest/commit/b9fb3cea33f495f0c9c9d7d74ed67af6aab78b04
* Unkown nodes: Provide position on interact (#6505)
https://github.com/minetest/minetest/commit/f547452685b299712ff5aa15bf06b4cd6069deec
* Replace deprecated WINAPI GetVersionInfoEx (#6496)
https://github.com/minetest/minetest/commit/c830347a57c63698f14803233dfc43adeb3fd51f
* NetworkPacket::putRawPacket: resize m_data to datasize + memcpy
https://github.com/minetest/minetest/commit/9d295906efc7eec58dba3f7494f4e444d2c8d00f
* Thread: fix a crash on Windows due to data race condition on Thread::m_start_finished_mutex (#6515)
https://github.com/minetest/minetest/commit/32ae4926578844eac1a7b72fcd4e26eb854eb7e5
* Profiler: Fix var args not being passed to callback register function
https://github.com/minetest/minetest/commit/9f3a5859378ac01648ca0caf01b04ad57c871baa
* Don't try to craft a non-existent item
https://github.com/minetest/minetest/commit/90e7d42375918636bf65fd6273675a576530778d
* Correct `prot_vers` in lua_api.txt.
https://github.com/minetest/minetest/commit/c60abb2aeccba2920d55a518fcffd2ad57f9f59a
* Fix default item callbacks to work with nil users (#5819)
https://github.com/minetest/minetest/commit/a5d5728f241fec8644ba65cb3b98c7dd1be2eee3
* Fix day_night_ratio_do_override not being initialised server-side
https://github.com/minetest/minetest/commit/cd1140f69cf31c6c3885dd81c64e505ac1559487
* httpfetch: Enable gzip support
https://github.com/minetest/minetest/commit/21f3237fe95a18e97421ea80762f989c7841a181
* Do not scale texture unless necessary.
https://github.com/minetest/minetest/commit/6be6fb78a4becc9bf4e999ff5aaa3c2d75fcc428
* Fix Settings tab formspec alignment (#6585)
https://github.com/minetest/minetest/commit/a07d2594e3b9372cabbeedc98bb98903137f56b3
* Fix issue Minetest crash when custom font path is not exist
https://github.com/minetest/minetest/commit/9526c686997285700f500b975a9d971c3ca0a188
* Add minetest.safe_write_file() to script API
https://github.com/minetest/minetest/commit/b692454f70cb661a8ce733a4bcbbadcb5edd0049
* Make use of safe file writing in auth handler (fixes #6576)
https://github.com/minetest/minetest/commit/fc9747eb4b7f75e59a28957bc50f7a78256b3d66
* Remove incorrect entry from settingtypes
https://github.com/minetest/minetest/commit/66ec50db3a07f863ee0dd4ea12da4421917ae3bc
* Lua_api.txt: Add documentation of required mapgen aliases
https://github.com/minetest/minetest/commit/4d83eb796b317901df3b2be8f3c8ace339f9bb95
* Biome dust node: Only place on 'walkable' cubic non-liquid drawtypes
https://github.com/minetest/minetest/commit/ec93893c7f34bcab35b1c356497d8def47d1bf1c
* core.rotate_node: Run callbacks like with any regular placed node (#6648)
https://github.com/minetest/minetest/commit/f7733f41ea36e7d4531fea61a4cd4b679514d263
* Improve documentation for player:set_attribute()
https://github.com/minetest/minetest/commit/76eb3f2b7ab3a88509d70f3bb936b850d5d83e86
* Update documentation regarding authentication handler and related functions
https://github.com/minetest/minetest/commit/ab947bd58280637e7dbef44c983b6a27f6e7637b
* Ensure no item stack is being held before crafting (#4779)
https://github.com/minetest/minetest/commit/2b5341c51864660bb1a434a520f7cca9ce3619e6
* Damage: Remove damage ignore timer
https://github.com/minetest/minetest/commit/03caa1e31902d99d60ad3c015c681a3fee679638
* Builtin: Fix handle_node_drops crash with nil digger 
https://github.com/minetest/minetest/commit/b19241b9bc43e2d9721927ab32e5e56345721652
* Fix wrong scrolling (#6809)
https://github.com/minetest/minetest/commit/257626ceedc986de822eac5f9708e505b41ec87d
* Fix undefined behaviour on getting pointer to data in empty vector
https://github.com/minetest/minetest/commit/7354d0f3d8ea2d48a85479426bf0c055ff4926b4
* Fix dancing text
https://github.com/minetest/minetest/commit/189daf87a00d1ec0d8444d2664ca45da6c53e87d
* Fix rounding error in g/set_node caused by truncation to float
https://github.com/minetest/minetest/commit/026ad912af0ad147071da79201a335ec84bd6ce9
* Fix Wstringop-overflow warning from util/srp.cpp (#6855)
https://github.com/minetest/minetest/commit/e7b44c3295b904ee12ed4192ea4feff4ea4c6226
* Fix buffer parameter not working in LuaPerlinNoiseMap::l_getMapSlice()
https://github.com/minetest/minetest/commit/63f4ee21b05266f926ed883ba86f3411b1499933
* Fix off-by-one in log output line length (#6896)
https://github.com/minetest/minetest/commit/f77f19a9412c9ae9f6b54a8794af219861a5e2e2
* Move `setlocale` from Lua to C++.
https://github.com/minetest/minetest/commit/1e94a7feaff940494a474ee549d4f2dc61f6a869
* Falling.lua: Delete falling node entities on contact with 'ignore'
https://github.com/minetest/minetest/commit/737f0b447380597ffa1e4c39beeab847e96ed6b2
* Item entity: Delete in 'ignore' nodes
https://github.com/minetest/minetest/commit/1156088db740fed69051201fb943feaff3b4f678
* Fix "Ignoring CONTENT_IGNORE redefinition" warning (#4393)
https://github.com/minetest/minetest/commit/46bbacee95b8cc68b7e531232a319ed46c2e1560
* Check argument types inside MetaDataRef Lua API (#7045)
https://github.com/minetest/minetest/commit/3f2e0c1206ed3d4dfe8a58048170a4ce3309b059
* /shutdown can't do countdown when using reconnect and/or shutdown message (#7055)
https://github.com/minetest/minetest/commit/cf98f5bbc03c41501f15a76c039b15735d53f18e
* Delete world dialog: Move buttons to avoid double click deletion
https://github.com/minetest/minetest/commit/0f015b28a30f77e006528a36c8d5b7705b0d6423
* Fix liquid post effect colour behaviour in third person view
https://github.com/minetest/minetest/commit/e7f16119913f7b2c98059398085d410684c9d8c0
* Generate Notifier: Clear events once after all 'on generated' functions
https://github.com/minetest/minetest/commit/07622bf9b49830aae2a5e12b5616471da6a8b19a
* macOS: don't require X11 libraries during compilation (#7149)
https://github.com/minetest/minetest/commit/9802e59724ac05e7304f9fbd4c93204f7bd00a3d
* core.rotate_node: Do not trigger after_place_node (#6900)
https://github.com/minetest/minetest/commit/8f827ee6800974ee451f0e82ac5eafdff63b835e
* upright_sprite: Fix texture position for players Fixes #6471
https://github.com/minetest/minetest/commit/d58801ab3204757e6c49892a05633281144f4f44
* Fix for translating empty strings
https://github.com/minetest/minetest/commit/9a06d6aa9fa2676a3fb4fa494f9318d0c5d7becb
https://github.com/minetest/minetest/commit/22ebbe136a8a90bc23d7f910a3dee5bf41632115
* Cavegen: Fix variable typo that broke mgvalleys large cave distribution (#7249)
https://github.com/minetest/minetest/commit/cca925377b7929276de3bb04553ca6ee2012d35d
* Fix i386 bit build at OpenBSD (#7259)
https://github.com/minetest/minetest/commit/cb92cdf3a4656379cda5569754e748904417687d
* Dungeons: Mostly fix missing stair nodes
https://github.com/minetest/minetest/commit/454f80a0f78b99cf0b595d91e4ad7d847cfbbcc4
* Fix luajit include not being found
https://github.com/minetest/minetest/commit/50c33d9638c31e70e6111687b19d58ee990e744b

Features:
* Add a server-sided way to remove color codes from incoming chat messages (#5948)
https://github.com/minetest/minetest/commit/25ae0739ed70be8b6a46bdc98aee4b7e33f478ab
* find_nodes_in_area: Extend maximal count to U32_MAX
https://github.com/minetest/minetest/commit/6eb03c135f17f05d48dd13fe8957bfe0f9654b00
* Automatic item and node colorization (#5640)
https://github.com/minetest/minetest/commit/0fcaf9fb1b61caaf8ed78a5d3005b1d9d1c43b57
* Tile material: Add 'TILE_MATERIAL_OPAQUE', use for drawtype 'NDT_NORMAL'
https://github.com/minetest/minetest/commit/6e5588c8e1a6cf79005b5e95c75cbfacf7c75589
https://github.com/minetest/minetest/commit/c3580043685671c4f767e1c380ae7c3e237f8b8b
* Sneak: Stripped down version
https://github.com/minetest/minetest/commit/a5c37717ffea387f8aa694f22ccc2f2f449826ac
* Full viewing range key message clarified
https://github.com/minetest/minetest/commit/e44f13aecb39e778d5b67c0894077cba2157742b
* Trigger on_rightclick regardless on the formspec meta field
https://github.com/minetest/minetest/commit/4381fe0a0a0921e6ba79c072045be2dc04be646a
* Make dropped items colorable
https://github.com/minetest/minetest/commit/71b02d626f4a9629e0f282adef908eedc8ed252a
* ClientInterface: add a function to verify (correctly) if user limit was reached (#6258)
https://github.com/minetest/minetest/commit/1d8d01074fdb52946f81110bebf1d001185b394b
https://github.com/minetest/minetest/commit/8432efa308e0d6c56ad61df189981ed03b0af463
* Leveled nodebox: Change levels from 1/63rds to 1/64ths
https://github.com/minetest/minetest/commit/d8f20d029a17551dab35a850bed48a62c1a02618
* Positional sound: Limit volume when closer than 1 node
https://github.com/minetest/minetest/commit/a455297d297c0819a7eff89e51e5f01a5ac731c3
https://github.com/minetest/minetest/commit/0df3671a3462f020f798e375ca9943a032225733
* CAO footstep sounds: Reduce gain to balance volume
https://github.com/minetest/minetest/commit/ee0bfbede1f5eb17e76cd00444ea9749869d9adb
* Add setting for near plane distance. (#6395)
https://github.com/minetest/minetest/commit/3c93a56e16f03893f97b7d28b0a8a0e302cb55ca
* Avoid filtering low-res textures for animated meshes (incl. players) (#6562)
https://github.com/minetest/minetest/commit/610ea6f21629933be3b38c2b5fce53a35c5aac3a
* Add sha1 to lua utils. (#6563)
https://github.com/minetest/minetest/commit/65c5539035139428ee8354d7c96565fc392112d2
* Improve Settings tab button alignments
https://github.com/minetest/minetest/commit/5b7687c08c02dc79a9307cd6917ee2c9981117d4
* Inventory: Restrict access from too far away
https://github.com/minetest/minetest/commit/990d0b0264cae3f05fb0d1353294c94b18faa4c8
* Hint at problematic code when logging deprecated calls
https://github.com/minetest/minetest/commit/813d819d153c78eb81893c208ba73c56237ea3d4
* Shut down mapgen threads before other shutdown tasks (#6689)
https://github.com/minetest/minetest/commit/83b12ed481fdb1f0c86a97de8a2887acaa32079e
* Apply physics overrides correctly during anticheat calculations (#6970)
https://github.com/minetest/minetest/commit/de2c40c8fc189eeeeba010a0aaa1d28aed588c68
* Refine movement anticheat again (#7004)
https://github.com/minetest/minetest/commit/cf0bcebc7620ff2a4bfb44bcbc4909ff9dbe8d24
* Add minetest.is_player (#7013)
https://github.com/minetest/minetest/commit/87e08b1b3af097e5ba86d31179e58fe38477fe15
* Allow dumping userdata (#7012)
https://github.com/minetest/minetest/commit/a6bb2c4ea8cfcfeeb6f78129663a3c3237891ce2
* Find nodes in area (under air): Raise volume limit and document it
https://github.com/minetest/minetest/commit/673f7196a2200a8f77d04a0470f642f729a4f94b
* SAO limits: Allow SAOs to exist outside the set 'mapgen limit'
https://github.com/minetest/minetest/commit/359a940dde0d0d85b288c8af6b10bccbd021f9c1
* CollisionMoveSimple: Collide with 'ignore' nodes
https://github.com/minetest/minetest/commit/6c9df2ffa7ee81a05b28fdd6123a926abd284c72
* Minetest ASCII art: Move from actionstream to rawstream
https://github.com/minetest/minetest/commit/cd6bcef6d9f387d43fa8fa34b93722ab0b8ba895
* Huge LBM lookup performance improvement on mapblock loading (#7195)
https://github.com/minetest/minetest/commit/392e80e3f13c977b5499eb424fa7d65085fb08f5
* Builtin auth handler: Speed up file writing (#7252)
https://github.com/minetest/minetest/commit/36eb823b1cebc92cd7802368ab0bdc5b3679a3cd

Backport-only fixes:
* Fix C++11 feature detection for undefined _MSC_VER (#7255) 
https://github.com/minetest/minetest/commit/01f76a1d22a68349c696481739f44a2f212b9a2c
* "static constexpr v3s16 light_dirs[8]" fails to compile, sync it with master!
https://github.com/minetest/minetest/commit/4bd98f26113a6da706a4b9c51b47eddece2348a4
* Fix C++03 compiling due to C++11 initialization issues in backport 
https://github.com/minetest/minetest/commit/537265264204e702017fb1a0491bdb08ffafaf3b
* C++03 backports for mapnode, localplayer, content_cao
https://github.com/minetest/minetest/commit/816a3c90201826c41ee877b36c19eabecce9e1e5

TODO:
* consider adding 4bb41a19dc74fa31cb021dc3b5622814d67fbd6f
* update buildbot to make win32/64 travis work (@sfan5)

### CODE REVIEW

**Comment by paramat** [comment]
TODO

673f7196a2200a8f77d04a0470f642f729a4f94b "Find nodes in area (under air): Raise volume limit and document it"
on request of VanessaE.

**Comment by red-001** [comment]
I would suggest 4bb41a19dc74fa31 is added, since its a purely server-sided fix and improves the security of badly written mods.

**Comment by Wayward1** [comment]
https://github.com/minetest/minetest/commit/22a891a925d68a096420d3383a2e31b58e3eb244 (the Android c++11 build fix) should probably added as well

**Comment by nerzhul** [comment]
@Wayward1 0.4 doesn't use C++11

**Comment by SmallJoker** [comment]
* core.rotate_node: Do not trigger after_place_node
8f827ee

**Comment by paramat** [comment]
TODO:
Important cave fix:
*  Cavegen: Fix variable typo that broke mgvalleys large cave distribution
cca925377b7929276de3bb04553ca6ee2012d35d

**Comment by paramat** [comment]
Crash reported see http://irc.minetest.net/minetest-dev/2018-05-12#i_5304795 onwards.

Suggested code:
```
		if node == nil then
			-- Don't infinetly fall into unloaded map
			self.object:setvelocity({x = 0, y = 0, z = 0})
			self.object:setacceleration({x = 0, y = 0, z = 0})
			self.physical_state = false
			self.object:set_properties({physical = false})
			return
		-- Delete in 'ignore' nodes
		elseif node.name == "ignore" then
			self.itemstring = ""
			self.object:remove()
 			return
 		end
```

**Comment by paramat** [comment]
Better code, tested:
```
	on_step = function(self, dtime)
		self.age = self.age + dtime
		if time_to_live > 0 and self.age > time_to_live then
			self.itemstring = ''
			self.object:remove()
			return
		end
		local p = self.object:getpos()
		p.y = p.y - 0.5
		local node = core.get_node_or_nil(p)
		-- Delete in 'ignore' nodes
		if node and node.name == "ignore" then
			self.itemstring = ""
			self.object:remove()
			return
		end

		-- If node is nil (unloaded area), or node is not registered, or node is
		-- walkably solid and item is resting on nodebox
		local v = self.object:getvelocity()
		if not node or not core.registered_nodes[node.name] or
				core.registered_nodes[node.name].walkable and v.y == 0 then
			if self.physical_state then
				local own_stack = ItemStack(self.object:get_luaentity().itemstring)
				-- Merge with close entities of the same item
				for _, object in ipairs(core.get_objects_inside_radius(p, 0.8)) do
					local obj = object:get_luaentity()
					if obj and obj.name == "__builtin:item"
							and obj.physical_state == false then
						if self:try_merge_with(own_stack, object, obj) then
							return
						end
					end
				end
				self.object:setvelocity({x = 0, y = 0, z = 0})
				self.object:setacceleration({x = 0, y = 0, z = 0})
				self.physical_state = false
				self.object:set_properties({physical = false})
			end
		else
			if not self.physical_state then
				self.object:setvelocity({x = 0, y = 0, z = 0})
				self.object:setacceleration({x = 0, y = -10, z = 0})
				self.physical_state = true
				self.object:set_properties({physical = true})
			end
		end
	end,
```
I added `not node or` to the conditional that results in the item having it's vel/acc set to zero. To avoid the item falling into an unloaded area.

**Comment by nerzhul** [comment]
I dropped the GCC minimum version check which is C++11 only, this will permit to compile on a non c++11 compiler and we will see what issues to fix

**Comment by sfan5** [comment]
I don't think it's a good idea to convert all code back to C++03, instead c++11 should be made a requirement for 0.4.17.

**Comment by nerzhul** [comment]
i don't know why do we changed our mind, 0.5 first goal was C++11, it's why we did a major bump.

Anyway i pushed another patchset to return back to C++03 (and in localplayer.cpp it was just crazy the constructor has both worlds... incomplete in the c++03 side)

**Comment by paramat** [comment]
@rubenwardy could you test this code https://github.com/minetest/minetest/pull/6746#issuecomment-388591177 on your server? It's strange that i was unable to produce a crash, even when dropping an item into an unloaded area.

**Comment by paramat** [comment]
I think we should freeze now. Any very important bugfixes to go in last minute? I have made some minor bugfixes recently but am not asking they go in, they can wait until 0.4.18.

**Pull request closed without merging**
