### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alwayshopeless**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
- How does the PR work?
- Does it resolve any reported issue?
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
- If not a bug fix, why is this PR needed? What usecases does it solve?

## To do

This PR is a Work in Progress / Ready for Review.

- [ ] List
- [ ] Things
- [ ] To do

### CODE REVIEW

**Comment by NathanSalapat** [comment]
Why remove the word free, are we planning on charging for Minetest in the future?

**Comment by kromka-chleba** [comment]
If we're changing anything there then I'd suggest adding "free/libre".
It seems user freedom became a "controversial" topic lately.

**Comment by alwayshopeless** [comment]
> Why remove the word free, are we planning on charging for Minetest in the future?

The main reason for the changes is that Minetest is not a game engine, or a voxel game engine. This is a platform.

**Comment by oong819** [comment]
Free here mean freedom to use, modify, distribute, etc (depend on license) not just free in price

I think Minetest should be called an game engine instead of game creation platform because Minetest only run the game/mod not an IDE or something like Roblox studio XD

**Pull request closed without merging**
