### PR TITLE
Fix extract zip writing lowercase files

### PR DESCRIPTION
**Pull request by rubenwardy**
This is likely to cause problems on Windows

EDIT by paramat: Attends to #8203 (possibly partially).

### CODE REVIEW

**Comment by paramat** [comment]
Works for me on Linux :+1:

**Comment by rubenwardy** [comment]
To test this:

1. Download something using CDB that you've not downloaded before.
2. Check that the capitalisation matches the files in the zip.
3. Modify the capitalisation of a file directly, using your file manager.
4. Modify mod.conf/game.conf/etc, lower the `release` number.
5. Click *update*.
6. On Windows, there shouldn't be any duplicates. On Linux, there should be 2 versions of each file - original spelling, new spelling

**Comment by paramat** [comment]
In what way might this be a problem on windows?
Since few mods use uppercase for filenames shall we merge this and consider this good enough for 5.0.0?

**Comment by Thomas--S** [comment]
I tested this on Windows 10 using a cross-compiled build of this PR.

I followed the steps provided by rubenwardy above and everything seems to work.

If you want me to provide further details, feel free to ask.

**Comment by paramat** [comment]
LINT has some reasonable requests @rubenwardy

**Pull request merged**
