### PR TITLE
Update tab_credits.lua

### PR DESCRIPTION
**Pull request by Zeno-**
Removed persons not applicable for the forthcoming release

### CODE REVIEW

**Comment by gregorycu** [comment]
While I think your eagerness to cleanup the credits is laudable, I can't help but feel the work I did on superfluous shaders updates represents a non-trivial amount of work. I am interested to know who will second this, however.

**Comment by Zeno-** [comment]
@gregorycu I will close this PR if you ask me to

**Comment by Zeno-** [comment]
@gregorycu As you may have rightly pointed out, your input into that code might be significant. If so, then of course you belong in the credits. Just say the word.

**Comment by gregorycu** [comment]
If you could give me credit for this release, I think that would be appropriate. (Consider the word said.)

**Comment by Zeno-** [comment]
Done. You were right.

**Pull request closed without merging**
