### PR TITLE
find_path: consider walkable instead of CONTENT_AIR

### PR DESCRIPTION
**Pull request by sofar**
The path finding code works fairly well except that it considers
anythin not CONTENT_AIR to be "above the surface". This results
in paths that are unwalkable for entities since e.g. plants
are not walkable. The path would force them to jump on top of
grass plants, etc..

The obvious solution is not to use CONTENT_AIR as a criteria, but
instead distinguish between walkable and non-walkable nodes. This
results in paths that properly walk through grass nodes.

This was extensively tested by a flock of electric sheep.

### CODE REVIEW

**Comment by PilzAdam** [comment]
Now you do a ton of nodedef lookups. How does that affect performance?

**Comment by sofar** [comment]
Considering this function is effectively useless without this fix, I've just made it a ton more performant?

**Comment by PilzAdam** [comment]
@sofar fair enough.

**Comment by sofar** [comment]
In all seriousness, as long as you'd avoid getting stuck inside a plant, the function would work. But if you set your target position inside a grass plant, and then in a subsequent find_path() attempt to find a path out of it, it would never find a path.

The tradeoffs are that likely the paths are more flat, so better paths at the cost of more lookups to contentFeatures.

**Comment by sofar** [comment]
Note this doesn't affect the "getting stuck on a node edge" issue. I still see that problem.

**Comment by sofar** [comment]
https://www.youtube.com/watch?v=avkzrF7J96U

**Comment by C1ffisme** [comment]
Wow. I can't wait to use this...

What about some tests high in the sky on a bridge, or through a maze?

**Comment by est31** [comment]
I have 4 commits regarding the pathfinder, changing lots it in #3894 . Would probably make more sense to rebase this onto those, and not the other way round. I'll do a separate PR to make it possible to merge the changes without the noclip enforcement.

**Comment by est31** [comment]
#4037

**Comment by sofar** [comment]
This is merged into 4037. Tested still OK.

**Pull request closed without merging**
