### PR TITLE
Client eventmanager refactor

### PR DESCRIPTION
**Pull request by nerzhul**
Refactor client event manager

* Use non too generic type for events as it's a code fixed size
* Drop some unused functions
* Move EventManager which is only attached to client to the client folder
* Add unittess on EventManager
* Fix various float declared as double
* Various other clenaups

### CODE REVIEW

**Comment by nerzhul** [comment]
@TODO: add some unittests

**Comment by nerzhul** [comment]
PR is ready for a merge

**Comment by nerzhul** [comment]
Yes it's a header problem, but i assume if this is solved you are okay ?

**Comment by SmallJoker** [comment]
@nerzhul Yes. The changes look good, so if you fix the compiling: :+1:

**Comment by NewbProgrammer101** [comment]
@nerzhul I have no idea what unit tests are. Can you point me to useful documentation for it?

**Comment by nerzhul** [comment]
@NewbProgrammer101 unittests are small functional test on small code parts to test all possible cases of a one or more functions. Look at src/unittests to have our current set.
Look at https://en.wikipedia.org/wiki/Unit_testing

**Comment by NewbProgrammer101** [comment]
Thanks.

**Pull request merged**
