### PR TITLE
Add API function minetest.activate_objects_in_area

### LINKED ISSUE #11599: Detection of objects in inactive areas
## Problem

It seems that `minetest.get_objects_inside_radius` and `minetest.get_objects_in_area` don't find inactive objects. This makes sense, as they have to return `ObjectRef`s. As far as I know, there is at the moment no straightforward way to detect inactive objects.

## Solutions

It would be nice if there were alternatives to `minetest.get_objects_inside_radius` and/or `minetest.get_objects_in_area` that could detect inactive objects. I don't care much about the specifics. These functions could return lists of tables representing both active and inactive objects. These tables could contain object positions and more information depending on the kind of object (for example, Lua entities could have a name field.) It might also be useful for tables representing active objects to contain the corresponding `ObjectRef`s.

## Alternatives

* I think you could first activate the area with forceloading then search for objects. However, this isn't ideal, due to the cap on forceloaded blocks.
* You can periodically scan for objects in the area when it is active using an ABM or node timer, storing the result for use when the area is inactive. This may rarely give an incorrect result, unless you run the check every globalstep.

## Additional context

I ran into this issue when working on [area_containers](https://github.com/TurkeyMcMac/area_containers). Currently I use the second alternative I laid out above. This particular mod only needs to detect whether there are any objects in a block. It doesn't need any information about the objects.

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
  - The goal is to add a way to synchronously find the objects in any area.
- How does the PR work?
  - The API function finds the mapblocks containing the given area. Then it goes through each of them and activates the objects using a new method of `ServerEnvironment`. The objects are activated like during regular mapblock activation, except that only those within the given area are activated.
  - The function cannot be called when activation or deactivation is going on. I don't think this restriction is very significant, although I could be wrong. Basically it just means you can't call the function in `on_activate` or `on_deactivate`. I had to change several places in the code to get this to work. It wouldn't be safe to let mods call the function in these places, since the activation and deactivation procedures are not written to be re-entrant.
- Does it resolve any reported issue?
  - Fixes #11599
  - The predecessor of this PR is #11609
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
  - It broadens the interface for objects/entities.
  - It counts as taking feedback from a modder.
- If not a bug fix, why is this PR needed? What usecases does it solve?
  - I mentioned my usecase in the issue and the previous PR. It's for my mod area_containers.
  - @ElCeejo mentioned that my previous PR would be very useful to them in their work with objects, and this PR does basically the same thing in that regard.

## To do

This PR is Ready for Review.

## How to test

1. Load a devtest world with this mod installed: [test_activate_objects.tar.gz](https://github.com/minetest/minetest/files/7165874/test_activate_objects.tar.gz)
2. Run the command `/grantme all`.
3. Start flying.
4. Execute these commands:
  a. `/teleport 0 6001 0`
  b. `/make_platform (0,6000,0)`
  c. `/teleport 0 10 0`
5. After the objects are deactivated, run `/check_platform (0,6000,0)`. It should tell you that it activated the area and detected two objects.
6. If you want to test that `minetest.activate_objects_in_area` throws an error in the right places, you can uncomment one or both of the latter two calls to the function in the mod's `init.lua`. These two calls are at the bottom of the file where the `on_activate` and `on_deactivate` methods of `__builtin:item` are overridden.

I've also now added a devtest command `test_activate_objects` for activating an arbitrary area.

### CODE REVIEW

**Comment by loffren174** [comment]
Does this allow to remove said objects then, as in, they could be listed with get_objects_in_radius and then removed one-by-one?
I assume so, but in #11599 sfan mentioned:
> I don't see the point of having a list of static objects (that's what they're called) when there is no way to interact with them. For example you couldn't remove them.

 An object equivalent to accompany the clearing of nodes between two positions would be very nice indeed for loading and unloading various schematic levels in the same worldspace without 'leftover' entities.

**Comment by TurkeyMcMac** [comment]
@loffren174 I haven't tested the specific case of removing the objects, but it definitely should work. `minetest.activate_objects_in_area` would let you obtain the active object handles with which to remove the objects.

(I _have_ tested manipulating the activated objects. For example, you can move them to an active mapblock to prevent them from being deactivated again.)

**Comment by rubenwardy** [comment]
Thanks for the contribution! Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed.

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label. In the future, you can open an issue first to get preapproval before working on something

**Comment by TurkeyMcMac** [comment]
Could this be considered for reopening/inclusion in 5.6.0?

**Comment by SmallJoker** [comment]
This PR was brought up in today's meeting.
https://irc.minetest.net/minetest-dev/2022-04-10#i_5959121

1. What are the use-cases of this function? In which situation do you need to know entities of unloaded mapblocks?
2. What are the downsides of #11609 ? That PR is more generic (allows more different operations), such as map changes.
3. Is there a need for synchronous loading? A callback-based approach would be more efficient to not block the Lua side for too long.

**Comment by TurkeyMcMac** [comment]
@SmallJoker

My specific use case is my mod [area_containers](https://github.com/TurkeyMcMac/area_containers). These containers are nodes which contain physical areas, in which one can put nodes and objects. I don't want people to be able to destroy containers which still have nodes or objects inside. Detecting nodes is easy, but detecting objects in a foolproof way is as yet impossible. My current mostly-working solution is to periodically store the count of objects inside whenever the mapblock representing the inside chamber is active. I could solve this cleanly using the function this PR adds.

Since the `can_dig` callback is synchronous, I need a synchronous function; the result must be available immediately.

The problem with #11609 was the potential reentrancy inherent to a synchronous API. There are many times during the activation of a mapblock when Lua callbacks can be called (e.g. ABMs, node timers.) Theoretically any of these callbacks could call the area loading function, with unpredictable results. The activation process was not written to be reentrant AFAICT. A safe solution is to use a "lock" to prevent reentrancy, as is done in this PR. However, if the function activated entire mapblocks, it would then be impossible to use it within node timer callbacks, object activation callbacks, ABMs, or LBMs. A function which only activates objects is only uncallable during object activation (and deactivation.) My main goal in the first place was the activation of objects; I don't see much point of doing the other stuff when you can already access nodes in inactive blocks.

**Comment by sfan5** [comment]
Someone brought up `can_dig` and I suspected that this was the reason you want it a sync API, the thing is I am very wary of adding any sync APIs because they block the entire server waiting for one particular thing (especially with emerging this is risky).

A function to activate a particular mapblock (not synchronous) sounds generally useful but in the end I think have to give up on solving your usecase directly. Maybe you'd be fine with some creative workarounds like only allowing your nodes to be dug after a short delay during which the relevant blocks are activated...

**Comment by TurkeyMcMac** [comment]
Is there evidence that activating objects is especially expensive? Blocks may have to be loaded from the disk, but this is already a possibility with existing synchronous APIs such as `minetest.load_area`. Furthermore, just about any API can cause lag if a mod uses it poorly. I don't think APIs should be left out because of this.

The alternative to this PR is forceloading blocks. Besides being asynchronous, this isn't even guaranteed to work, since there is a limit on the number of blocks forceloaded. Given that objects are so important in Minetest, the impossibility of reliably detecting static objects seems like a significant issue. There should at least be a reliable asynchronous API, but I think a synchronous API would be highly preferable.

**Comment by sfan5** [comment]
Nothing about it is particularly expensive, I'm just wary of adding more sync apis.

> Furthermore, just about any API can cause lag if a mod uses it poorly. I don't think APIs should be left out because of this.

Having *only* a synchronous API can be considered a problem too, then.

**Comment by TurkeyMcMac** [comment]
I could rename the function to `minetest.activate_objects_in_area_sync` then implement an async version something like this:

```lua
function core.activate_objects_in_area(pos1, pos2, callback)
  assert(type(pos1) == "table" and type(pos2) == "table" and type(callback) == "function", "Invalid invocation of minetest.activate_objects_in_area")
  pos1 = vector.copy(pos1)
  pos2 = vector.copy(pos2)
  core.after(0, function()
    callback(core.activate_objects_in_area_sync(pos1, pos2))
  end)
end
```

**Pull request closed without merging**
