### PR TITLE
Revert 6587 - Optimize entity-entity collision

### PR DESCRIPTION
**Pull request by lhofhansl**
Reverts 528908a4c3dd190cb7a6007df1e3fcd8e4604bfa

Shame, but seems to be the safest. See comments in #6587 
@numberZero @rubenwardy

### CODE REVIEW

**Comment by SmallJoker** [comment]
Should be delayed so that numberZero has the chance to find a better solution.

**Comment by lhofhansl** [comment]
Up to @numberZero . The entity stuff is pretty hairy, so I doubt there'll be a quick change, especially because the code all *looks* good, and *should* perform much better than the older code.

**Comment by rubenwardy** [comment]
There does seem to be a lot of issues with entities. It's maybe worth making a document describing how they currently work and integrate with the rest of the project, and identifying issues with them. I personally haven't spent much time on them

**Comment by lhofhansl** [comment]
Looking a bit more at mobs_redo I will say that I have have active_object_send_range_blocks set to 30 (so that entities work right with zooming).

mobs_redo has a count check that check the volume of
`max(active_block_range, active_object_send_range_blocks) * 16`
for spawning.

Of course this is an expensive check. With the old code it seems to work fine. Now the hashmap gets too big it seems.

Since active_object_send_range_blocks just has to do with the client (or with zoom) mobs redo should not use that one anyway. I'll send a PR for mobs_redo as well.

**Comment by lhofhansl** [comment]
See https://notabug.org/TenPlus1/mobs_redo/issues/1

**Comment by lhofhansl** [comment]
I can confirm the collision detection problems with dmobs are caused by this. When I 6587 everything works as expected.

As sorry as I am, I strongly vote for reverting this for now, then regrouping and later reapply with modifications.

**Comment by paramat** [comment]
:+1: No harm in reverting while a fix is investigated, and improves performance in the meantime. There's no benefit to delaying.

**Comment by numberZero** [comment]
Have to agree with paramat. The code became somewhat dirty through development, so it’s better to rethink it.

**Pull request merged**
