### PR TITLE
Darwin platform build fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**
the event header seemingly being generic with libevent
 thus renaming it to rightfully including the minetest's
openal and opengl are deprecated on newer macOs releases
 thus suppressing the build warnings for those.

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
LGTM. Does this also supersede #10370?

**Comment by devnexen** [comment]
did not see that one. I would say so.

**Comment by sfan5** [comment]
I still dislike renaming the event header. I have successfully built Minetest on Linux systems with `/usr/include/event.h` present for many years, yet macOS apparently can't manage that (anymore?).

But I guess for lack of a better solution (or someone spending time to find out wtf is wrong with Apple's toolchain), this is okay.

**Comment by SmallJoker** [comment]
I experienced similar errors also when including system headers again manually in the Makefile. However, it might also be possible that Apple's compiler does not differentiate `#include <header>` and `#include "header.h"`.

**Pull request merged**
