### PR TITLE
game.conf: Add setting to use volatile a map backend

### LINKED ISSUE #11883: allow games to set backend to dummy
## Problem

allow games to set the backend to dummy from game.conf. this is useful for games that dont need to save the map and allows games to do it much cleaner than they already do (see alternatives)

## Solutions

allow games to set the backend to dummy from game.conf.

## Alternatives

change the backend on first player join and restart the server like https://github.com/AFCMS/Subway-Miner/blob/0950b4cc038c304ab874287b7d366df886868e57/mods/sm_game/init.lua#L47 does

## Additional context

core dev views: sfan5 on irc has agreed that it has a use https://irc.minetest.net/minetest-dev/2021-11-24#i_5901174 as well as warr1024 on discord

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #11883. (by implementation)

## To do

This PR is Ready for Review.

## How to test

1. Edit `game.conf`
2. Add `map_persistent = false` (-> dummy) or `map_persistent = true` (-> sqlite3)
3. Test it.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Not a fan of the API. Instead of specifying _specific_ backend, games should instead be able to specify whether they need map persistence or not and have dummy selected based on that

**Comment by snowyu** [comment]
This should be the same logic in the minetest.conf.

**Comment by SmallJoker** [comment]
Changed the setting to a boolean. I did want to have it as generic as possible but must admit that such free choice is not really needed here.

@snowyu The global `minetest.conf` overwrites the game's `minetest.conf`. I did intentionally use `game.conf` to give games the dominance (see also: disallowed mapgens in the main menu).

**Comment by sfan5** [comment]
thoughts on https://github.com/minetest/minetest/issues/11883#issuecomment-1000849748?
> As an addition to this I can also imagine a setting that says "this game does not need a persistent world".
The mainmenu would hide the entire world stuff and just plaster a big start game button.

doesn't need to be done now ofc

**Review by TurkeyMcMac — APPROVED** [review]

**Comment by lhofhansl** [comment]
We should allow this to work together with #7544

@SmallJoker

**Comment by SmallJoker** [comment]
How?

@lhofhansl

**Comment by lhofhansl** [comment]
Maybe #7544 needs to be adapted. I always wanted to way to edit a map, then switch to volatile mode while keeping the map created earlier. And it also would be nice if games could ship a base map. Maybe I'm dreaming :)

**Pull request merged**
