### PR TITLE
Make git version discovery work on master

### PR DESCRIPTION
**Pull request by est31**
This change was neccessary as git-describe only can track tags, and the 0.4.12 release was a non-linear one, with the 0.4.12 tag being on its own branch. Thanks for @sfan5 for pointing this out.

Two things changed for the "outside":
1. Workspaces with changes don't have a "-dirty" appended anymore. This can be added later, however.
2. The commit that represents a version change on the master branch has now to be set manually inside the CMakeLists.txt

### CODE REVIEW

**Comment by ShadowNinja** [comment]
This is a horribly ugly hack and adds yet another step to the release process.

I wonder of merging stable-0.4 into master would solve this.  It's also ugly, but it's better than this IMO.

**Comment by nerzhul** [comment]
I think we could tag 0.5.0 the branch as soon as network break is done.

**Comment by est31** [comment]
As other option, we could give the `0.4.12-dev` tag to the 0.4.12 version bump commit in master.

**Comment by est31** [comment]
I see there are disadvantages of this method over the "merge" method @ShadowNinja suggested in this PR. I think we should do that (merge, no rebase). Both mine and ShadowNinja's methods require additional steps, but the merge way works better with github. Also, the funcionality of this PR can only be used for the `0.4.12` release -- [after that the release model has changed](http://dev.minetest.net/Git_Guidelines#Upstream_branch_rules). Therefore, closing this.

**Pull request closed without merging**
