### PR TITLE
Randomwalk caves: Add parameters for number and proportion flooded. Allow small randomwalk caves

### LINKED ISSUE #8599: Per-mapgen parameters for randomwalk cave rarity
Currently the tunnels and giant caverns are very adjustable.
The randomwalk caves (liquid caves) have no adjustment for rarity, which would be very useful.
https://github.com/minetest/minetest/blob/f2c73def4b0c7fcfab521c0c54ada82a94b065c5/src/mapgen/mapgen.cpp#L864
I suggest 2 parameters, setting the lower and higher pseudorandom limits for number of caves in a mapchunk.

### PR DESCRIPTION
**Pull request by paramat**
Commit 1:

Randomwalk caves: Add parameters for number and proportion flooded

Add mapgen parameters to set the range of the random number of
randomwalk caves per mapchunk, and to set the proportion that are
flooded with liquids.
Default values are, for now, unchanged from the previous hardcoded
values.
//////////////////////////////////////////////////////
Commit 2:

Add parameters to allow small randomwalk caves

Disabled by default for now, later we could possibly add small
randomwalk caves to the non-mgv6 mapgens.
//////////////////////////////////////////////////////

screenshot_20190913_013441

^ 4 large caves per mapchunk, none flooded, all other caves disabled

Closes #8599
The PR may look large but most is whitespace changes for alignment, so i recommend usng the 'hide whitepace changes' option in the 'files changed' tab.
Also, a lot of the changes are duplicated across the 6 mapgens.
The changes themselves are quite simple.

The 'randomwalk caves', also called 'large caves', are the underground caves that are sometiimes flooded. They are created by pseudorandom number generators instead of 3D noise.
To clarify, mapgen uses 2 other types of cave:
* 'tunnels' that intersect the surface, created by two 3D noises.
* 'caverns', extremely large and deep underground, also created by 3D noise.

Previously, the number of randomwalk caves per mapchunk was hardcoded to a random range of 0 to 2. The proportion flooded by liquids was also hardcoded, at 50%.

The new parameters allow setting the min and max of the random range of the number per mapchunk, and allow fine control over the proportion that are flooded by liquids.

Because the randomwalk caves have lightweight generation not requiring noise, the number of these per mapchunk can be safely significantly increased to create a more interconnected underground network of caves.

//////////////////////////////////////////////

Commit 2 adds parameters to allow the non-mgv6 mapgens to have 'small randomwalk caves'.
Also with settings for min and max of a random range per mapchunk.
Small caves are disabled by default for now, as these have never been present in these mapgens, but a later commit could possibly add some in to make the default underground more interesting.

The non-mgv6 randomwalk cave code actually has the ability to create small RW caves too, because this code was derived from mgv6 cave code. However the small RW caves are unused in non-mgv6 mapgens, partly because we have the 3D noise tunnels.

In a future PR i will create a way to disable the 3D noise tunnels so that users can use small RW caves instead, this will remove the (intensive) calculation of two 3D noises, allowing a lot of small RW caves to be used with no performance loss.

////////////////////////////////

How to test.

In minetest.conf or 'All Settings' menu, use:
mg_flags = light,caves,nodungeons,nodecorations,nobiomes
to remove dungeons.

For any of the 6 relevant mapgens (here fractal for example):
Use:
mgfractal_cave_width = 1000
to reduce tunnel width to zero to disable the 3D noise tunnels.

Use:
mgfractal_small_cave_num_min = 0
mgfractal_small_cave_num_max = 0
mgfractal_large_cave_num_min = 0
mgfractal_large_cave_num_max = 0
with zero values and various random ranges, and fly underground to check for expected behaviour.
Remember that large RW caves only appear below y = -32 (and below y = -256 in mgv5).

With large RW caves present and small RW caves disabled, use:
mgfractal_large_cave_flooded = 0.0
With values between 0.0 and 1.0 to check for expected behaviour. Here it is helpful to make water a light source for easy checking.

### CODE REVIEW

**Comment by paramat** [comment]
Added documentation, no longer WIP.
I set limits to the 'all settings' values to avoid cave number being set negative. Because the parameter is an unsigned integer a negative value may be converted to an insanely large number of caves.
Maximum number of caves per mapchunk is 64 (4^3), more than enough for any usage.

**Comment by paramat** [comment]
WIP again as i want to consider adding the option of generating 'small randomwalk caves' (as used in mgv6). The randomwalk code used by non-mgv6 mapgens does have the ability to generate small caves but this ability is currently unused.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/b49dfa92ce3ef37b1b73698906c64191fb47e226/src/mapgen/cavegen.cpp#L367-L370
I am testing what value of 'insure' is required to avoid cave nodes being 'out of area' and therefore creating flat cave walls.
In testing with 64 (!) large caves per mapchunk, flying underground, a value of 2 only resulted in 9 'out of area' nodes in 5min of flying, extremely rare. A value of 1 caused many 'out of area' nodes, but still not many.
We can therefore reduce 'insure' to 2, this will increase large cave size, make them extend into the mapchunk shell further to increase the chance of overlap and interconnection.
I will make this a 2nd commit here.

**Comment by paramat** [comment]
WIP again as i want to consider adding the option of generating 'small randomwalk caves' (as used in mgv6). The randomwalk code used by non-mgv6 mapgens does have the ability to generate small caves but this ability is currently unused.

**Comment by v-rob** [comment]
So wait, are the lava/water caves in v6 small or big randomwalk, and are the tunnels small randomwalk?  Because if there's any chance of having v6 caves in other mapgens instead of their default tunnels, I'm all in.

**Comment by paramat** [comment]
Caves are confusing, and the settings terminology used for them doesn't help.

Ignoring mgv6 there are 3 types of cave, each generated differently:

* Randomwalk caves: The underground caves that are sometimes flooded. These are the classic larger caves from mgv6. Created by pseudorandom number generators and a randomwalk path instead of 3D noise. Settings affecting these use the words 'large cave'.
* Tunnels/fissures: These intersect the surface. Created by 2 3D noises named 'cave1' and 'cave2'. The setting 'cave width' controls the width of these.
* Caverns: Extremely large and deep underground, created by a 3D noise named 'cavern'. Related settings use the word 'cavern'.

So currently, non-mgv6 mapgens do not use the smaller randomwalk caves from mgv6 (the narrow tubelike tunnels), but i am considering adding settings to make that possible if desired, they would be disabled by default. This would add a 4th type of cave.
The code for the smaller randomwalk caves is already present and ready for use so it seems a waste to not make it usable.

**Comment by paramat** [comment]
screenshot_20191024_175359

^ The 'small randomwalk caves', just 1 per mapchunk here to test

I am now adding the ability to have parameter-controlled small randomwalk caves. In testing they have a nice structure which at high density will create interesting networks.
This will allow users the option of disabling the 3D noise tunnels (which are very intensive) and use these small RW caves instead.

Note to myself: Make overgeneration vertical too?

**Comment by paramat** [comment]
screenshot_20191024_231320

^ 64 small caves per mapchunk becomes very interconnected (all other caves disabled)

**Comment by paramat** [comment]
Complete and tested, no longer WIP.

**Comment by paramat** [comment]
Note, the changes here are simple, and being mapgen, i am very confident about them. So i suggest this only needs a concept approval and maybe a quick look over the code.

Most line changes are alignment/whitespace, so it is best to use the 'hide whitespace changes' option. Also, many changes are duplicated across the 6 mapgens. So although it may look a big PR, it is not.

**Comment by paramat** [comment]
*Please* can this be reviewed/approved, or at least just a concept approval?

The changes here are very simple, you can trust me with them, so i do not think this particularly needs code review or testing (i have tested very carefully and completely). So i think in this case a concept approval is enough.
Or at least, skip the extremely simple setting-related changes and just look at the rest, which is a simple 5 min review.
I am inspired to work on cavegen currently and have 2 follow-up improvements to do which are being delayed by this. This is unbearable and my inspiration is being wasted.

I am beginning to think we should trust other core devs with code changes if they are obviously very competant in that area (such as me in most of mapgen, rubenwardy in CDB) and very confident about them, and just give a concept approval.
Rigidly following the current merging rules is, i think, causing more harm than good in the delay and frustration caused, especially as we have fewer active core devs and an ever more complex project. I suspect that the slightly higher risk of errors will be outweighed by the advantages.
To be clear i am not suggesting changing the rules for non-core dev contributions.

If no-one has time to review, please just approve the concept and approve trusting the code changes, they are borderline trivial.

@SmallJoker 
@sfan5 
@rubenwardy 
@lhofhansl

**Comment by v-rob** [comment]
I hate delays as well.  I've given the code a run-through, and while I don't know much about mapgen, I don't see anything against the code style and all the changes seem to make sense and add up.

**Comment by jastevenson303** [comment]
I also hate delays and feel as though my inspiration is being wasted.

**Comment by nerzhul** [comment]
okay for me

**Comment by paramat** [comment]
Thanks nerzhul.

**Pull request merged**
