### PR TITLE
wip irrlicht particles

### PR DESCRIPTION
**Pull request by obneq**
some parts for moving mt particles to irrlicht.

currently this places particle burst when node is punched or breaks. collision detection seems to work ok.

### CODE REVIEW

**Comment by nerzhul** [comment]
If other PR are broken they need to rebase or they became useless.
@obneq can you rebase, your work is very interesting.

**Comment by obneq** [comment]
rebased for what its worth, also uses collisionMoveSimple now, looks bad.

**Comment by nerzhul** [comment]
Hi @obneq , i note some problems on intel GPU before rebase, a performance issue when the particules are generated (FPS < 10). Also collision between particles let some particles to be thrown in the air with a high speed.
Does the collisionMoveSimple fix it ?

**Comment by obneq** [comment]
collisionMoveSimple fixes runaway particles. However it looks dull, no bounce and orthogonal sliding.

Note that performance can not just be compared to current particles, as this pull as is creates the same (higher than before) number of particles for both punch and dig, and the particles stay alive for much longer. 

This rebase is mostly copy paste work and broke camera offset correction, so  test within limit of 200 nodes in any direction.

**Comment by nerzhul** [comment]
Ok, this is cool, i'll test PR as soon as feature freeze is finished or new devel branch is created

**Comment by kilbith** [comment]
> Note that performance can not just be compared to current particles

It's not really matter of number of particules. I tested your PR with an Intel GMA45... From a smooth 35-40 FPS, the first apparition of those particules has brutally dropped the game to <10 FPS.

After a deco/reco, it's better. Each punch results in a decrease of ~5 FPS. But you can observe a remarkable instability.

**Comment by nerzhul** [comment]
@obneq i tested your rebased PR. Performance issue is solved.
Now i think we must tune the lifetime of the particles. And the particles slip down the ground, it's not very good :(. I think the particle lifetime must be divided by 1.5 or 2

**Comment by obneq** [comment]
@nerzhul this pull is more for information purposes than straight merge. current particles were done this way because it was widely believed that irrlicht particles can not do collision. particle lifetime and all for punch and node should, if this is the way forward, be done just as they look now. 

However we need discussion about some things that change: irrlicht has no acceleration field in particles, and mt allows to spawn single particles.

**Pull request closed without merging**
