### PR TITLE
couple of memory leak fixes

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by est31** [comment]
Nice addition, but can you fix git? Something like `git rebase -i c8b4bedaa89ac5246161b1bb9e3826dcce083fcf`, then deleting all lines except the one with the actual commit, then forcepushing.

**Comment by est31** [comment]
Especially your first commit is unwanted in this PR. We have merged your port fix change already, in commit b6eef1c0c2e76e56f148bf296a42fb3a4bae4a55 .

**Comment by devnexen** [comment]
good point

**Comment by nerzhul** [comment]
:+1:

**Comment by est31** [comment]
Err seems you have merged your commit with one from the master branch...

**Comment by devnexen** [comment]
I see I ve probably squashed rather. I can t undo for now until in 5/6 hours, is it possible to merge the diff however ?

**Comment by nerzhul** [comment]
Squash can be done on merge

**Pull request closed without merging**
