### PR TITLE
recompress all pngs

### PR DESCRIPTION
**Pull request by ibmibmibm**
saved 42.85KB
```
 build/android/src/main/res/drawable-hdpi/irr_icon.png                   | Bin 5490 -> 4275 bytes
 build/android/src/main/res/drawable-ldpi/irr_icon.png                   | Bin 2262 -> 1853 bytes
 build/android/src/main/res/drawable-mdpi/irr_icon.png                   | Bin 3110 -> 2517 bytes
 build/android/src/main/res/drawable-xhdpi/irr_icon.png                  | Bin 7610 -> 5656 bytes
 fonts/mono_dejavu_sans_100.png                                          | Bin 56121 -> 55445 bytes
 fonts/mono_dejavu_sans_110.png                                          | Bin 67613 -> 66823 bytes
 fonts/mono_dejavu_sans_120.png                                          | Bin 73938 -> 72841 bytes
 fonts/mono_dejavu_sans_140.png                                          | Bin 89073 -> 88259 bytes
 fonts/mono_dejavu_sans_160.png                                          | Bin 101939 -> 100883 bytes
 fonts/mono_dejavu_sans_180.png                                          | Bin 122274 -> 121746 bytes
 fonts/mono_dejavu_sans_200.png                                          | Bin 138662 -> 137829 bytes
 fonts/mono_dejavu_sans_220.png                                          | Bin 152844 -> 152416 bytes
 fonts/mono_dejavu_sans_240.png                                          | Bin 170247 -> 169951 bytes
 fonts/mono_dejavu_sans_280.png                                          | Bin 200848 -> 200734 bytes
 fonts/mono_dejavu_sans_40.png                                           | Bin 15668 -> 15437 bytes
 fonts/mono_dejavu_sans_60.png                                           | Bin 29291 -> 28961 bytes
 fonts/mono_dejavu_sans_80.png                                           | Bin 45552 -> 44746 bytes
 fonts/mono_dejavu_sans_90.png                                           | Bin 50995 -> 50154 bytes
 games/minimal/menu/background.png                                       | Bin 392 -> 342 bytes
 games/minimal/menu/icon.png                                             | Bin 218 -> 216 bytes
 games/minimal/mods/bucket/textures/bucket.png                           | Bin 182 -> 141 bytes
 games/minimal/mods/bucket/textures/bucket_lava.png                      | Bin 183 -> 167 bytes
 games/minimal/mods/bucket/textures/bucket_water.png                     | Bin 180 -> 167 bytes
 games/minimal/mods/default/textures/bubble.png                          | Bin 273 -> 146 bytes
 games/minimal/mods/default/textures/crack_anylength.png                 | Bin 255 -> 252 bytes
 games/minimal/mods/default/textures/default_apple.png                   | Bin 109 -> 102 bytes
 games/minimal/mods/default/textures/default_book.png                    | Bin 157 -> 154 bytes
 games/minimal/mods/default/textures/default_bookshelf.png               | Bin 515 -> 452 bytes
 games/minimal/mods/default/textures/default_brick.png                   | Bin 457 -> 433 bytes
 games/minimal/mods/default/textures/default_cactus_top.png              | Bin 121 -> 117 bytes
 games/minimal/mods/default/textures/default_chest.png                   | Bin 263 -> 163 bytes
 games/minimal/mods/default/textures/default_clay.png                    | Bin 318 -> 261 bytes
 games/minimal/mods/default/textures/default_clay_brick.png              | Bin 173 -> 143 bytes
 games/minimal/mods/default/textures/default_clay_lump.png               | Bin 140 -> 108 bytes
 games/minimal/mods/default/textures/default_cloud.png                   | Bin 83 -> 70 bytes
 games/minimal/mods/default/textures/default_coal_lump.png               | Bin 138 -> 106 bytes
 games/minimal/mods/default/textures/default_cobble.png                  | Bin 374 -> 344 bytes
 games/minimal/mods/default/textures/default_dirt.png                    | Bin 1586 -> 788 bytes
 games/minimal/mods/default/textures/default_fence.png                   | Bin 480 -> 402 bytes
 games/minimal/mods/default/textures/default_furnace_fire_bg.png         | Bin 220 -> 131 bytes
 games/minimal/mods/default/textures/default_furnace_fire_fg.png         | Bin 719 -> 670 bytes
 games/minimal/mods/default/textures/default_furnace_front.png           | Bin 159 -> 135 bytes
 games/minimal/mods/default/textures/default_furnace_front_active.png    | Bin 283 -> 260 bytes
 games/minimal/mods/default/textures/default_furnace_side.png            | Bin 125 -> 124 bytes
 games/minimal/mods/default/textures/default_glass.png                   | Bin 210 -> 145 bytes
 games/minimal/mods/default/textures/default_grass.png                   | Bin 782 -> 700 bytes
 games/minimal/mods/default/textures/default_grass_footsteps.png         | Bin 771 -> 716 bytes
 games/minimal/mods/default/textures/default_grass_side.png              | Bin 878 -> 263 bytes
 games/minimal/mods/default/textures/default_gravel.png                  | Bin 172 -> 171 bytes
 games/minimal/mods/default/textures/default_iron_lump.png               | Bin 140 -> 123 bytes
 games/minimal/mods/default/textures/default_ladder.png                  | Bin 368 -> 328 bytes
 games/minimal/mods/default/textures/default_lava.png                    | Bin 172 -> 170 bytes
 games/minimal/mods/default/textures/default_lava_flowing_animated.png   | Bin 7818 -> 7700 bytes
 games/minimal/mods/default/textures/default_lava_source_animated.png    | Bin 3145 -> 2881 bytes
 games/minimal/mods/default/textures/default_leaves.png                  | Bin 1683 -> 652 bytes
 games/minimal/mods/default/textures/default_mese.png                    | Bin 129 -> 125 bytes
 games/minimal/mods/default/textures/default_mineral_coal.png            | Bin 142 -> 116 bytes
 games/minimal/mods/default/textures/default_mineral_iron.png            | Bin 922 -> 161 bytes
 games/minimal/mods/default/textures/default_mossycobble.png             | Bin 603 -> 574 bytes
 games/minimal/mods/default/textures/default_nc_back.png                 | Bin 186 -> 182 bytes
 games/minimal/mods/default/textures/default_nc_front.png                | Bin 204 -> 202 bytes
 games/minimal/mods/default/textures/default_nc_rb.png                   | Bin 137 -> 134 bytes
 games/minimal/mods/default/textures/default_nc_side.png                 | Bin 148 -> 145 bytes
 games/minimal/mods/default/textures/default_paper.png                   | Bin 139 -> 123 bytes
 games/minimal/mods/default/textures/default_papyrus.png                 | Bin 165 -> 133 bytes
 games/minimal/mods/default/textures/default_rail.png                    | Bin 437 -> 399 bytes
 games/minimal/mods/default/textures/default_rail_crossing.png           | Bin 388 -> 353 bytes
 games/minimal/mods/default/textures/default_rail_curved.png             | Bin 375 -> 355 bytes
 games/minimal/mods/default/textures/default_rail_t_junction.png         | Bin 374 -> 359 bytes
 games/minimal/mods/default/textures/default_river_water.png             | Bin 716 -> 527 bytes
 games/minimal/mods/default/textures/default_sand.png                    | Bin 762 -> 542 bytes
 games/minimal/mods/default/textures/default_sandstone.png               | Bin 744 -> 684 bytes
 games/minimal/mods/default/textures/default_sapling.png                 | Bin 328 -> 288 bytes
 games/minimal/mods/default/textures/default_scorched_stuff.png          | Bin 164 -> 163 bytes
 games/minimal/mods/default/textures/default_sign_wall.png               | Bin 416 -> 404 bytes
 games/minimal/mods/default/textures/default_steel_block.png             | Bin 128 -> 121 bytes
 games/minimal/mods/default/textures/default_steel_ingot.png             | Bin 144 -> 118 bytes
 games/minimal/mods/default/textures/default_stick.png                   | Bin 120 -> 93 bytes
 games/minimal/mods/default/textures/default_stone.png                   | Bin 389 -> 313 bytes
 games/minimal/mods/default/textures/default_tnt_bottom.png              | Bin 98 -> 97 bytes
 games/minimal/mods/default/textures/default_tnt_side.png                | Bin 129 -> 113 bytes
 games/minimal/mods/default/textures/default_tnt_top.png                 | Bin 146 -> 142 bytes
 games/minimal/mods/default/textures/default_tool_mesepick.png           | Bin 155 -> 147 bytes
 games/minimal/mods/default/textures/default_tool_steelaxe.png           | Bin 140 -> 119 bytes
 games/minimal/mods/default/textures/default_tool_steelpick.png          | Bin 163 -> 155 bytes
 games/minimal/mods/default/textures/default_tool_steelshovel.png        | Bin 144 -> 128 bytes
 games/minimal/mods/default/textures/default_tool_steelsword.png         | Bin 169 -> 155 bytes
 games/minimal/mods/default/textures/default_tool_stoneaxe.png           | Bin 141 -> 120 bytes
 games/minimal/mods/default/textures/default_tool_stonepick.png          | Bin 155 -> 150 bytes
 games/minimal/mods/default/textures/default_tool_stoneshovel.png        | Bin 144 -> 122 bytes
 games/minimal/mods/default/textures/default_tool_stonesword.png         | Bin 168 -> 149 bytes
 games/minimal/mods/default/textures/default_tool_woodaxe.png            | Bin 134 -> 108 bytes
 games/minimal/mods/default/textures/default_tool_woodpick.png           | Bin 149 -> 143 bytes
 games/minimal/mods/default/textures/default_tool_woodshovel.png         | Bin 135 -> 117 bytes
 games/minimal/mods/default/textures/default_tool_woodsword.png          | Bin 147 -> 128 bytes
 games/minimal/mods/default/textures/default_torch.png                   | Bin 146 -> 125 bytes
 games/minimal/mods/default/textures/default_torch_on_ceiling.png        | Bin 137 -> 117 bytes
 games/minimal/mods/default/textures/default_torch_on_floor.png          | Bin 138 -> 115 bytes
 games/minimal/mods/default/textures/default_tree.png                    | Bin 1445 -> 658 bytes
 games/minimal/mods/default/textures/default_tree_top.png                | Bin 177 -> 172 bytes
 games/minimal/mods/default/textures/default_water.png                   | Bin 302 -> 293 bytes
 games/minimal/mods/default/textures/default_wood.png                    | Bin 1400 -> 610 bytes
 games/minimal/mods/default/textures/heart.png                           | Bin 248 -> 204 bytes
 games/minimal/mods/default/textures/player.png                          | Bin 157 -> 142 bytes
 games/minimal/mods/default/textures/player_back.png                     | Bin 149 -> 137 bytes
 games/minimal/mods/default/textures/treeprop.png                        | Bin 757 -> 692 bytes
 games/minimal/mods/default/textures/wieldhand.png                       | Bin 212 -> 135 bytes
 games/minimal/mods/experimental/textures/experimental_dummyball.png     | Bin 399 -> 304 bytes
 games/minimal/mods/experimental/textures/experimental_tester_tool_1.png | Bin 160 -> 138 bytes
 games/minimal/mods/legacy/textures/apple_iron.png                       | Bin 119 -> 113 bytes
 games/minimal/mods/legacy/textures/cooked_rat.png                       | Bin 145 -> 132 bytes
 games/minimal/mods/legacy/textures/dungeon_master.png                   | Bin 3007 -> 2855 bytes
 games/minimal/mods/legacy/textures/fireball.png                         | Bin 279 -> 252 bytes
 games/minimal/mods/legacy/textures/firefly.png                          | Bin 99 -> 86 bytes
 games/minimal/mods/legacy/textures/oerkki1.png                          | Bin 165 -> 157 bytes
 games/minimal/mods/legacy/textures/oerkki1_damaged.png                  | Bin 210 -> 206 bytes
 games/minimal/mods/legacy/textures/rat.png                              | Bin 141 -> 107 bytes
 misc/minetest-icon-24x24.png                                            | Bin 587 -> 582 bytes
 misc/minetest-xorg-icon-128.png                                         | Bin 11241 -> 7881 bytes
 textures/base/pack/air.png                                              | Bin 225 -> 127 bytes
 textures/base/pack/camera_btn.png                                       | Bin 729 -> 549 bytes
 textures/base/pack/chat_btn.png                                         | Bin 399 -> 179 bytes
 textures/base/pack/debug_btn.png                                        | Bin 895 -> 637 bytes
 textures/base/pack/down.png                                             | Bin 1328 -> 955 bytes
 textures/base/pack/down_arrow.png                                       | Bin 373 -> 364 bytes
 textures/base/pack/drop_btn.png                                         | Bin 1035 -> 654 bytes
 textures/base/pack/fast_btn.png                                         | Bin 875 -> 559 bytes
 textures/base/pack/fly_btn.png                                          | Bin 720 -> 498 bytes
 textures/base/pack/gear_icon.png                                        | Bin 1005 -> 610 bytes
 textures/base/pack/halo.png                                             | Bin 144 -> 81 bytes
 textures/base/pack/ignore.png                                           | Bin 234 -> 133 bytes
 textures/base/pack/inventory_btn.png                                    | Bin 343 -> 122 bytes
 textures/base/pack/jump_btn.png                                         | Bin 434 -> 312 bytes
 textures/base/pack/left_arrow.png                                       | Bin 400 -> 387 bytes
 textures/base/pack/logo.png                                             | Bin 12188 -> 11461 bytes
 textures/base/pack/menu_bg.png                                          | Bin 124 -> 78 bytes
 textures/base/pack/menu_header.png                                      | Bin 1628 -> 740 bytes
 textures/base/pack/minimap_mask_round.png                               | Bin 1858 -> 1100 bytes
 textures/base/pack/minimap_mask_square.png                              | Bin 420 -> 229 bytes
 textures/base/pack/minimap_overlay_round.png                            | Bin 22044 -> 9753 bytes
 textures/base/pack/minimap_overlay_square.png                           | Bin 1686 -> 1649 bytes
 textures/base/pack/no_screenshot.png                                    | Bin 586 -> 153 bytes
 textures/base/pack/noclip_btn.png                                       | Bin 1087 -> 807 bytes
 textures/base/pack/object_marker_red.png                                | Bin 449 -> 222 bytes
 textures/base/pack/player_marker.png                                    | Bin 2178 -> 2011 bytes
 textures/base/pack/progress_bar.png                                     | Bin 413 -> 155 bytes
 textures/base/pack/progress_bar_bg.png                                  | Bin 354 -> 141 bytes
 textures/base/pack/rangeview_btn.png                                    | Bin 1476 -> 1210 bytes
 textures/base/pack/rare_controls.png                                    | Bin 349 -> 116 bytes
 textures/base/pack/right_arrow.png                                      | Bin 396 -> 382 bytes
 textures/base/pack/server_flags_creative.png                            | Bin 273 -> 269 bytes
 textures/base/pack/server_flags_damage.png                              | Bin 713 -> 654 bytes
 textures/base/pack/server_flags_favorite.png                            | Bin 916 -> 573 bytes
 textures/base/pack/server_flags_pvp.png                                 | Bin 1048 -> 886 bytes
 textures/base/pack/server_ping_1.png                                    | Bin 251 -> 118 bytes
 textures/base/pack/server_ping_2.png                                    | Bin 244 -> 119 bytes
 textures/base/pack/server_ping_3.png                                    | Bin 245 -> 122 bytes
 textures/base/pack/server_ping_4.png                                    | Bin 213 -> 104 bytes
 textures/base/pack/smoke_puff.png                                       | Bin 202 -> 139 bytes
 textures/base/pack/sunrisebg.png                                        | Bin 4231 -> 3975 bytes
 textures/base/pack/unknown_item.png                                     | Bin 292 -> 286 bytes
 textures/base/pack/unknown_node.png                                     | Bin 193 -> 188 bytes
 textures/base/pack/unknown_object.png                                   | Bin 254 -> 252 bytes
 textures/base/pack/up_arrow.png                                         | Bin 373 -> 365 bytes
 164 files changed, 0 insertions(+), 0 deletions(-)
```

### CODE REVIEW

**Comment by paramat** [comment]
Which compression is used and what does it do?
Some compressions can break certain textures, for example leaf textures which need to retain a certain chosen background colour when 'opaque leaves' is used.
Some textures need to remain as RGBA and not be changed to indexed.
So we have to be careful here.

**Comment by ibmibmibm** [comment]
I use [Efficient-Compression-Tool](https://github.com/fhanau/Efficient-Compression-Tool) to compress these files. It use genetic algorithm to find nearly best filter code for each row of png image chunks, and use zopfli to get the optimal comression size.
It also transform RGBA files to RGB only when no alpha channel is used on these image.
I've check these texture is work on my archlinux machine and ubuntu machine.

Here's some [screenshots](http://imgur.com/a/RDGNQ) on my ubuntu machine.

Here's a list of file that type changed:
```
games/minimal/mods/bucket/textures/bucket.png                              8-bit colormap -> 8-bit gray+alpha
games/minimal/mods/bucket/textures/bucket_lava.png                         8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/bucket/textures/bucket_water.png                        8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_bookshelf.png                  8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_brick.png                      8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_chest.png                     8-bit/color RGB -> 4-bit colormap  
games/minimal/mods/default/textures/default_clay_brick.png                 8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_clay_lump.png                  8-bit colormap -> 8-bit gray+alpha
games/minimal/mods/default/textures/default_cloud.png                      1-bit colormap -> 1-bit grayscale 
games/minimal/mods/default/textures/default_coal_lump.png                  2-bit colormap -> 8-bit gray+alpha
games/minimal/mods/default/textures/default_fence.png                      8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_furnace_fire_bg.png            4-bit colormap -> 8-bit gray+alpha
games/minimal/mods/default/textures/default_furnace_front.png              8-bit colormap -> 8-bit grayscale 
games/minimal/mods/default/textures/default_furnace_front_active.png       8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_furnace_side.png               1-bit colormap -> 8-bit grayscale 
games/minimal/mods/default/textures/default_glass.png                      8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_iron_lump.png                  8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_ladder.png                     8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_mineral_coal.png               2-bit colormap -> 8-bit gray+alpha
games/minimal/mods/default/textures/default_mineral_iron.png               8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_mossycobble.png                8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_nc_side.png                    8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_paper.png                      8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_papyrus.png                    4-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_rail.png                       8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_rail_crossing.png              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_rail_curved.png                8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_rail_t_junction.png            8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_sand.png                       8-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_sapling.png                    8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_steel_block.png                1-bit colormap -> 8-bit grayscale 
games/minimal/mods/default/textures/default_steel_ingot.png                8-bit colormap -> 8-bit gray+alpha
games/minimal/mods/default/textures/default_stick.png                      8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tnt_bottom.png                 2-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_tnt_side.png                   4-bit colormap -> 8-bit/color RGB 
games/minimal/mods/default/textures/default_tool_mesepick.png              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_steelaxe.png              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_steelpick.png             8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_steelshovel.png           8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_steelsword.png            8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_stoneaxe.png              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_stonepick.png             8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_stoneshovel.png           8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_stonesword.png            8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_woodaxe.png               8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_woodpick.png              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_woodshovel.png            8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_tool_woodsword.png             8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_torch.png                      4-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_torch_on_ceiling.png           4-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/default_torch_on_floor.png             4-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/heart.png                              8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/player.png                             8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/player_back.png                        8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/treeprop.png                           8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/default/textures/wieldhand.png                          8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/experimental/textures/experimental_dummyball.png        8-bit colormap -> 4-bit colormap  
games/minimal/mods/experimental/textures/experimental_tester_tool_1.png    8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/legacy/textures/cooked_rat.png                          8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/legacy/textures/dungeon_master.png                      8-bit colormap -> 4-bit colormap  
games/minimal/mods/legacy/textures/fireball.png                            8-bit colormap -> 4-bit colormap  
games/minimal/mods/legacy/textures/oerkki1.png                             8-bit colormap -> 8-bit/color RGBA
games/minimal/mods/legacy/textures/rat.png                                 8-bit colormap -> 8-bit/color RGBA
textures/base/pack/camera_btn.png                                        8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/chat_btn.png                                            2-bit colormap -> 1-bit colormap  
textures/base/pack/debug_btn.png                                         8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/down.png                                                8-bit colormap -> 8-bit gray+alpha
textures/base/pack/down_arrow.png                                          2-bit colormap -> 1-bit colormap  
textures/base/pack/drop_btn.png                                          8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/fast_btn.png                                          8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/fly_btn.png                                           8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/gear_icon.png                                         8-bit/color RGBA -> 8-bit colormap  
textures/base/pack/inventory_btn.png                                       2-bit colormap -> 1-bit colormap  
textures/base/pack/jump_btn.png                                            8-bit colormap -> 8-bit gray+alpha
textures/base/pack/left_arrow.png                                          2-bit colormap -> 1-bit colormap  
textures/base/pack/menu_bg.png                                             1-bit colormap -> 8-bit/color RGB 
textures/base/pack/menu_header.png                                       8-bit/color RGBA -> 8-bit colormap  
textures/base/pack/minimap_mask_round.png                                  2-bit colormap -> 1-bit colormap  
textures/base/pack/minimap_mask_square.png                                 2-bit colormap -> 1-bit colormap  
textures/base/pack/minimap_overlay_round.png                             8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/no_screenshot.png                                     8-bit gray+alpha -> 1-bit colormap  
textures/base/pack/noclip_btn.png                                        8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/progress_bar.png                                      8-bit/color RGBA -> 2-bit colormap  
textures/base/pack/progress_bar_bg.png                                   8-bit/color RGBA -> 2-bit colormap  
textures/base/pack/rangeview_btn.png                                       8-bit colormap -> 8-bit/color RGBA
textures/base/pack/rare_controls.png                                     8-bit/color RGBA -> 1-bit colormap  
textures/base/pack/right_arrow.png                                         2-bit colormap -> 1-bit colormap  
textures/base/pack/server_flags_pvp.png                                    8-bit colormap -> 8-bit/color RGBA
textures/base/pack/smoke_puff.png                                        8-bit/color RGBA -> 8-bit gray+alpha
textures/base/pack/up_arrow.png                                            2-bit colormap -> 1-bit colormap  
```

**Comment by red-001** [comment]
this would be more useful for minetest game since that has more images.

**Comment by nerzhul** [comment]
yes. optipng is a nicer program to do those optimizations

**Comment by paramat** [comment]
I'm concerned that https://github.com/fhanau/Efficient-Compression-Tool seems to be a not-well-known tool, is there detailed documentation somewhere of what it does? There's none in the repo.

**Comment by paramat** [comment]
> steel_block.png                1-bit colormap -> 8-bit grayscale 

Not sure we should go this far.

**Comment by paramat** [comment]
Docs are MS word here https://github.com/fhanau/Efficient-Compression-Tool/blob/master/doc/Manual.docx

**Comment by paramat** [comment]
Efficient Compression Tool (ECT)
Losslessly optimizes Files/Images
Supported formats: PNG, JPEG, GZIP, ZIP


Usage: ect [Options] Folders/Files
Short options (with one -) can be abbreviated, e. g. -p for -progressive.
Options:
-quiet
	Show no report when program is finished; print only warnings and errors.
-#
	Select compression level [1-9] (default: 3).
For detailed information on performance read Performance.html.
Advanced usage:
A different syntax may be used to achieve even more compression for deflate compression if time (and efficiency) is not a concern. If the value is above 10000, the blocksplitting-compression cycle is repeated # / 10000 times. If # % 10000 is above 9, level 9 is used and the number of iterations of deflate compression per block is set to # % 10000. If # % 10000 is 9 or below, this number specifies the level.
-strip
	Discard metadata.
-progressive
Use progressive JPEG. When this is specified the program can choose whether it uses 	progressive or baseline (nonprogressive). Progressive is usually smaller and starts 	displaying faster while downloading as it can display a low resolution version of the image first but increases decoding time. When not specified, baseline encoding is always used.
-gzip
Create a RFC 1952 conforming, gzipped version of the. If the file is already in the GZIP format, it will be optimized.
-help
	Show a summary of the options.
-zip
Enables ZIP mode. If the  first file after this command is a zip file, all included files will be recompressed and files listed after the zip archive are added to it. If no zip file is specified, a new ZIP file is created to store the listed files. The file name will be constructed based on the name of the first file.


If folder support is enabled, folders may be zipped. If –recurse is used, subfolders will be included
-keep
Keep the file modification time.

Advanced Options:
--strict 
Enable strict losslessness. Without this, image data under fully transparent pixels can be 	modified to increase compression. This data is normally invisible and not needed. However, you may want to use this option if you are still going to edit the image.
--arithmetic
Enable arithmetic coding of JPEGs. This is not compatible with most decoders, but increases compression.
--reuse
	Use the filter strategy of the original image.
--pal_sort=n
Attempt to sort the palette of PNG images. Only has an effect on files where palette may be used.  n specifies the number of different strategies tried, the maximum is 120. Multiplies the compression time.
--allfilters
	Try most png filter strategies. Multiplies the compression time.
--allfilters-b
Try all the filter strategies of allfilters and also the ‘brute force’ genetic filtering, which is even slower. Genetic filtering may be ended by the user, more information on the command line.
--allfilters-c
	Try several png filter strategies. Cheaper than regular allfilters, but still improves 	compression.
--mt-deflate
--mt-deflate=n
Use several threads to compress png, gzip, and zip files. Multithreading is not used on very small files. If a number is specified, n threads are used, otherwise the number of logical cores is used. May decrease compression ratio.

Additional features when Folder support is compiled:
This allows you to use folders as input. All compatible files in the folder will be optimized.
-recurse
	Also optimize files in subfolders.
--disable-png, –disable-jpg
	Disable formats.

**Comment by nerzhul** [comment]
i think it's better to use optipng as a step before packaging releases instead of doing it sometimes

**Comment by ibmibmibm** [comment]
I'm using this command:
`ect -strip -9 --allfilters-b --pal_sort=120`

**Comment by paramat** [comment]
I agree with nerzhul.

**Comment by srifqi** [comment]
How about PNGGauntlet?

**Comment by nerzhul** [comment]
closing as there is an issue for this

**Pull request closed without merging**
