### PR TITLE
[no squash] Drop ENABLE_GLES

### LINKED ISSUE #13257: Drop ENABLE_GLES
`ENABLE_GLES` predates forking Irrlicht. Its primary use was to distinguish Irrlicht-ogles from mainstream version as Minetest could be compiled with either. That’s not necessary anymore, and gets in the way sometimes.

### PR DESCRIPTION
**Pull request by sfan5**
* MenuTextureSource changed to better delete textures
* near_plane setting removed
* video_driver chosen at runtime, default value is now `""`

closes #13257

## To do

This PR is Ready for Review.

## How to test

* compile & run Minetest with OpenGL
* compile & run Minetest with OpenGL ES 2
* run Minetest on Android

### CODE REVIEW

**Comment by numberZero** [comment]
See also #13284 for video driver autoselect

**Review by numberZero — COMMENTED** [review]
LGTM, except `near_plane` is still in `settingtypes.txt`

**Comment by sfan5** [comment]
Good catch.

**Comment by Desour** [comment]
There could be a separate compile option for allowing the `near_plane` setting.
But idk if we need the setting. It probably makes sense for low bit-depth depth buffers, I guess. But it makes cheating easier.
It would be good to have some rationale for why the setting is completely removed.

**Comment by sfan5** [comment]
The rationale is that it never really made much sense and is now more work to keep than to remove.

**Pull request merged**
