### PR TITLE
Add sound to press events of some formspecs elements

### PR DESCRIPTION
**Pull request by pyrollo**
This PR adds the possibility associate play sound to some formspecs client events (mouse clicks on items).
Sound is played by the client before any client-server-client dialog, avoiding any lag.

Sounds are fetched:
- among mods and game media when in game;
- in "sounds" folder when in main menu (sounds forlder is at same level as textures forlder);

## To do

This PR is Ready for Review

## How to test

Try this formspec using minetest_game:
```
size[5,3]
no_prepend[]
style[player;sound=player_damage]
button[3,1;1,1;player;player]
style_type[button;sound=default_sand_footstep]
button[1,1;1,1;sand;sand]
```

### CODE REVIEW

**Comment by Andrey2470T** [comment]
A question: can sounds be played when any button is being at hovered state also (currently afaik only buttons support states)?

**Comment by pyrollo** [comment]
> A question: can sounds be played when any button is being at hovered state also (currently afaik only buttons support states)?

No, for now it's just on clicks. But technically, nothing prevents that sort of addition.

But this brings a new problem: sounds should be attached to events (enter, exit, click, release, ...) not states (pressed, hovered). So maybe the style states are not adapted to sounds.

**Comment by SmallJoker** [comment]
How does it work? I tried the following code but there's no sound: (devtest/testformspec)
```
	style[one_btn1;sound=soundstuff_mono.ogg]
	button[0,0;2.5,0.8;one_btn1;Button]
```

If you have a working snippet, would you please be so nice to add it to devtest as well?

**Comment by kilbith** [comment]
You need to remove the “.ogg” part

**Comment by SmallJoker** [comment]
:facepalm: haha. Modder newbie mistakes do happen. Thanks, it works now just fine.

**Review by SmallJoker — APPROVED** [review]
Works \o/

**Comment by SmallJoker** [comment]
78273027b

**Comment by Jipok** [comment]
@SmallJoker 
For the sake of interest, why did you close this pr?
I see that you have  committed the changes, but the closed pr is discouraging

**Comment by v-rob** [comment]
I wish I had been paying attention to this earlier, but I don't think this PR should have been merged in its present state.  Since the sound only applies to press despite any states, it will be hard to change the behaviour without breaking compatibility.  I'm also not too happy with the implementation as it puts more stuff in GUIFormSpecMenu.

**Comment by kilbith** [comment]
_QED_: https://irc.minetest.net/minetest-dev/2020-12-02#i_5757118

**Comment by kilbith** [comment]
Nothing prevents you to revert since it's not released yet.

**Pull request closed without merging**
