### PR TITLE
Revert CSM particles commit to fix bug for 5.0.0

### PR DESCRIPTION
**Pull request by paramat**
Attends to #8256 by reverting https://github.com/minetest/minetest/commit/5dab7426451842793b183fbd961ad2ae83c8acbd
Simplest and safest solution this close to release. Then after release we could attempt to re-add the CSM feature but without causing the bug.

Note this is an exact code revert without me completely understanding the code, so if for some reason an exact revert is wrong in some way i will not be aware of this. However if merged it will likely get some testing.

screenshot_20190226_030337

Works, using the same test code posted in the issue.

### CODE REVIEW

**Comment by sofar** [comment]
meh, this is like my second most wanted feature in CSM :(

**Comment by jastevenson303** [comment]
For weather, right?

**Comment by sofar** [comment]
No, not particularly weather - although that is an obvious candidate. The first thing I'd make is a good client side torch/fire smoke CSM decorator mod. Weather is more complex. But there are a dozen other uses besides weather (fighting effects, footsteps, water splashing, etc. etc.).

**Comment by nerzhul** [comment]
not acceptable. The registration code should be fixed instead.

**Comment by rubenwardy** [comment]
How about reverting _when you find a fix_

**Comment by nerzhul** [comment]
The fix has been produced. See #8289

**Comment by paramat** [comment]
Reverting on your own decision is against the rules, doing so had no advantage at all, this could have been the backup solution while we test your new PR. You reverted this before you even attempted a fix. Will re-commit.

**Pull request merged**
