### PR TITLE
Trim whitespaces from the input of the `/privs` command.

### PR DESCRIPTION
**Pull request by red-001**
This is identical to #4551. I accidentally closed that PR.

### CODE REVIEW

**Comment by paramat** [comment]
Is the code identical to the approved previous PR?

**Comment by red-001** [comment]
@paramat  yes

**Comment by paramat** [comment]
Assuming 2 approvals then.

**Comment by paramat** [comment]
Applying: Trim whitespaces from the input of the `/privs` command.
error: patch failed: builtin/game/chatcommands.lua:147
error: builtin/game/chatcommands.lua: patch does not apply
Patch failed at 0001 Trim whitespaces from the input of the `/privs` command.

**Comment by red-001** [comment]
Rebased

**Comment by paramat** [comment]
c7d569b8636d8046393715e46fca40e58138183f

**Pull request closed without merging**
