### PR TITLE
Update android dependencies (openssl/curl/irrlicht)

### PR DESCRIPTION
**Pull request by sapier**
Update openssl to 1.0.2e
Make openssl use gmp library
Update curl to 7.46.0
Update irrlicht to recent opengl-es branch

Recent openssl android builds don't seem to support disabling certain ciphers any longer we shoult try from time to time to disable them again

### CODE REVIEW

**Comment by MoNTE48** [comment]
I checked and it works fine for me. :+1:

**Comment by MoNTE48** [comment]
You can include this https://github.com/inetic/ogg-vorbis-for-android ?

**Comment by MoNTE48** [comment]
Bugs: You disable openssl_arch.patch
I open Credits tab or write cyrillic latters on textform and all text on minetest 
becomes invisible

**Comment by est31** [comment]
This will fix #3366 then.

**Comment by sapier** [comment]
You're right about the arch patch, I thought it's not necessary any longer but didn't look carefull enough. It still might b relevant for mips and old arm which aren't default. I'll update that patch too.

**Comment by MoNTE48** [comment]
The last 3 years did not come out, no phone or tablet on MIPS. On armv6 in Minetest you get FPS 3-4. This is how to put Windows 10 on 512 RAM. This will work, but no one will never use it.

**Comment by sapier** [comment]
https://github.com/inetic/ogg-vorbis-for-android is about 3 years old. If I remember correct I did try to use that code on initial integration but it didn't work.

**Comment by MoNTE48** [comment]
@sapier , you can change version ogg and vorbis libs on this file https://github.com/inetic/ogg-vorbis-for-android/blob/master/build.sh

**Comment by MoNTE48** [comment]
I think you need to put Labels WIP or No merge, as now Irrlicht is not yet fully completed. The problem I described above.

**Comment by sapier** [comment]
Could you provide at least basic information about your problem prior calling it a blocker?
Basic information is:
*exact device name as well as hw version (there may be regional specifics or hw updates)
*exact version of android installed (e.g. stock android 5.0, cyanogen mod 6.0 ...)

**Comment by MoNTE48** [comment]
Heh :)
Asus Zenfone 2, Android 5.1, stock.
LG G4 CyanogenMod 13 (6.0.1).
Russian locale. I open Creit tabs and all text just disappeared in the game. If you want, I can check on all versions of 4.1-5.0 on a lot of phones that will be in my office tomorrow

**Comment by sapier** [comment]
Monte48 that be great, not because of this bug but I could update the list of supported devices if you have successfully tested them ;-)

How do you switch to russion, "language = ru" in minetest.conf doesn't have any effect and language selection dialog is broken (way to big and positioned wrong) ... haven't tried on current release but I guess it's there too

**Comment by MoNTE48** [comment]
@sapier, no-no. On my phone set russian locale. Minetest on english lang.

**Comment by sapier** [comment]
Monte48 that's crazy ;-) locale handling is completely messed up on android I'm astonished it does work at all ;-). My first guess is irrlicht guys did improve locale support thus getting trouble with broken android configs ... maybe we should just make sure no locales are picked up at all.
Btw locales are a huge mess on windows too ...

**Comment by MoNTE48** [comment]
One note - I have to delete the folder locale! I removed a lot of things in MultiCraft :)
You could edit apk from me with your changes?
Yes, locale is driving me crazy. As well as the need for a large number of png and xml files on fonts folder, the removal of which did not change anything for me. In addition to reducing apk sized -5 MB!

**Comment by sapier** [comment]
true those xml and png files are only required for builds without fontconfig and android build obviously does support fontconfig. The only reason for them beeing there is because asset copy target is quite stupid. Just cleaning them prior building the apk wont do any harm to the android version.
http://www.file-upload.net/download-11126883/Minetest-debug.apk.html

**Comment by MoNTE48** [comment]
NativeActivity crash on start

**Comment by sapier** [comment]
ok ok did only work because I didn't delete the old mt folder, checking once again

**Comment by MoNTE48** [comment]
screenshot_20151216-010928

**Comment by MoNTE48** [comment]
And you can update this https://github.com/sapier/minetest/blob/update_android_libs_dec15/build/android/Makefile#L636
 on .41 ver

**Comment by sapier** [comment]
curl binary wtf? who did add this and even more important WHY?

**Comment by MoNTE48** [comment]
@sapier , Hehe ;)
Newest openAL
https://github.com/Wemersive/openal-soft
or try branch https://github.com/apportable/openal-soft/branches 1.15.1

**Comment by MoNTE48** [comment]
Freetype Android https://github.com/android/platform_external_freetype https://github.com/CyanogenMod/android_external_freetype https://github.com/Kazade/freetype2

**Comment by est31** [comment]
@sapier agree binary download is best to be removed.

**Comment by sapier** [comment]
Split to those parts which don't cause regressions and those which do, obviously irrlicht 1.9 still has issues

**Comment by sapier** [comment]
well android test failing is quite obvious as gcc is updated to 4.9 which isn't honored by build env

**Comment by sapier** [comment]
Jenkins doesn't:
Invalid toolchain name: arm-linux-androideabi-4.9
Please use --toolchain=<name> with the name of a toolchain supported by the source NDK.
Try one of:  arm-linux-androideabi-4.6 arm-linux-androideabi-4.8 arm-linux-androideabi-clang3.3 arm-linux-androideabi-clang3.4 llvm-3.3 llvm-3.4 mipsel-linux-android-4.6 mipsel-linux-android-4.8 mipsel-linux-android-clang3.3 mipsel-linux-android-clang3.4 renderscript x86-4.6

**Comment by MoNTE48** [comment]
He-he, wow. Nrz very cool. How long to build jenkins? 10 min?

**Comment by nerzhul** [comment]
@MoNTE48 a little bit more i think. Maybe i should update NDK to a greater version

**Comment by MoNTE48** [comment]
@nerzhul , yes, update NDK the SDK.
Which processor you use and Hard or SSD? Thank you!

**Comment by nerzhul** [comment]
Hosting is done on a dedicated server. For ndk some things should be tested before upgrading

**Comment by MoNTE48** [comment]
@nerzhul, but ssd or hard ? :)

**Pull request closed without merging**
