### PR TITLE
Implement override.txt support for special tiles

### LINKED ISSUE #10132: Texture Packs - Add support for overriding special_tiles
## Problem
`override.txt` allows texture packs to override node textures, primarily the `tiles` field. However, certain node drawtypes use a secondary field, `special_tiles`, in order to provide additional textures. It is currently impossible to override these texture slots on nodes.

To my knowledge, this affects the following drawtypes:
- `glasslikeliquidlevel` - Liquid texture
- `allfaces_optional` - Texture used when 'simple leaves' is enabled
- `plantlike_rooted` - The plant drawn above the 'root' node
-  `flowingliquid` - Undocumented, seems to provide top/side textures?

## Solutions

The only viable solution that I see is to add support for replacing the `special_types` field from a texture pack. I see a couple possible ways of doing this:
- Provide special_tiles_1, special_tiles_2, etc. targets to allow texture pack makers to replace specific entries in the table (simple and 'forward-compatible' with new drawtypes, but not particularly user-friendly)
- Provide custom target names for the affected drawtypes, with names that make the purpose of the replaced texture clear

Both options have their benefits and drawbacks and they aren't really mutually exclusive, but I think we should probably just pick one to keep things simple.

## Alternatives

The only real alternative is to do nothing, and let texture pack makers try to persuade mod authors to change their nodes in a way that permits them to be retextured properly. IIRC, the method to do this is really dirty and not ideal for code quality (and also requires the modder to care enough to make the change). I don't see it as an ideal or even particularly viable solution.

### PR DESCRIPTION
**Pull request by Df458**
Resolves #10132

This PR adds override targets for all `special_tiles` entries in node definitions, allowing texture packs to replace these textures. This makes overrides work properly with a variety of drawtypes.

The targets are named `special1` through `special6`, covering the the current length of the special_tiles array.

## Testing
To test, make a texture pack and try setting overrides on the `special1` / `special2` targets of appropriate drawtypes
- `flowingliquid`
- `allfaces_optional` (with **simple** leaves)
- `glasslike_framed` (with `paramtype2 = "glasslikeliquidlevel"`)
- `glasslike_framed_optional` (with `paramtype2 = "glasslikeliquidlevel"`)
- `plantlike_rooted`
Appropriate nodes can be found in devtest.

Alternatively, You can grab this texture pack: [testure_pack.zip](https://github.com/minetest/minetest/files/4873006/testure_pack.zip)
It will override the relevant drawtype test nodes in devtest for you.

### CODE REVIEW

**Comment by Df458** [comment]
Ready for review. clang_format reports one issue, but I believe the current code passes the coding guidelines as written and this change wouldn't improve readability.

**Comment by sfan5** [comment]
You should put the code into a `// clang-format off` - `// clang-format on` block then so the CI won't fail.

**Comment by Df458** [comment]
Wasn't aware that was an option. I'll do it right away!

**Comment by Df458** [comment]
Rebased on 5.4.0, ready for review

**Pull request merged**
