### PR TITLE
Remove controls listed in the pause menu (no touchscreen)

### LINKED ISSUE #13278: Don't show controls in the pause menu
## Problem
If I want to know what key does what, I can just hit "Change keys". It makes the pause menu more crowded for no reason, also because not every key is listed (e.g. zoom key)

## Solutions
Remove them

### PR DESCRIPTION
**Pull request by Zughy**
Closes #13278

I've left instructions on touchscreens, as peole have no way to change controls there, even if it's even worse than on non touchscreen platforms (graphically speaking). In general the pause menu should be reworked and, I think, made overridable by the API. But hey, still better than before

## To do

This PR is Ready for Review.

## How to test
Before:
immagine

After:
immagine

### CODE REVIEW

**Comment by Zughy** [comment]
Yes, Nephele, you don't like it, we've got it already (https://github.com/minetest/minetest/issues/13278#issuecomment-1465120266). Muting this PR, please devs tag me if some change is needed

**Comment by Zughy** [comment]
BUMP

I think this is even more relevant now that MTG is going away with 5.8. Again, there are games that don't use all those keys (e.g. Slidespace, PRANG! to name a few) and MT is not displaying all the keys anyway (zoom, minimap)

**Comment by Zughy** [comment]
Renamed "Change Keys" into "Controls" as requested on IRC by @rubenwardy https://irc.minetest.net/minetest-dev/2023-09-30#i_6118689

**Review by sfan5 — APPROVED** [review]

**Comment by sfan5** [comment]
Needs rebase.

**Comment by Montandalar** [comment]
Unlike nephele's complaint, I will say this is fine, because the user can still see the keys under the keybindings menu. It just reduces clutter. But just taking them out without resizing the menu, it feels like there's a gap where they were. I feel like the info on the left should maybe move to the top. But I'd have to see if that would be too big on small (e.g. mobile) screen sizes.

**Comment by Zughy** [comment]
That can be done in a different PR. Can we please merge this silly PR that's taking a year?

**Review by rubenwardy — APPROVED** [review]
I was a little hesitant to remove this with the change keys dialog in its current state, but all the keys listed in the pause menu are there so it's just the mouse help that'll be missing. If this proves to be a concern/issue, someone can make a quick PR to add some text about the mouse to the controls menu

In the future, the Controls dialog should be redesigned. Should also support showing/changing controls on Android. Issue: #11209 

The justification for this is to remove the clutter on the pause menu and just have one place to view and change controls. This is common with most games

**Review by grorp — APPROVED** [review]
Well spoken, rubenwardy.

**Pull request merged**
