### PR TITLE
Content store: Fix storage leak by storing screenshots in cache

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by nerzhul** [comment]
this is a storage leak too. when this folder is purged ?

**Comment by rubenwardy** [comment]
The storage here is bounded by the number of packages. Whereas before the storage used when you open up CDB would never be used again, with this PR the storage is in the cache and the same data will be reused. This means you won't get multiple copies of the same data.

A memory leak is defined as:

> a failure in a program to release discarded memory, causing impaired performance or failure.

Before this PR, the screenshots would be discarded and never used again, but not deleted. With this PR, the screenshots would never be discarded and will be used again on next start up

-------------

AFAIA, the media cache also isn't deleted.

**Comment by nerzhul** [comment]
okay, but we really should cleanup that at a point in a future version

**Comment by rubenwardy** [comment]
Also worth noting that each image is at most 14KB, so the most space that will be taken up is 5MB

**Pull request merged**
