### PR TITLE
Fix some Spanish translations

### PR DESCRIPTION
**Pull request by Panquesito7**
This PR enhances the translation for Spanish.

- Fixes some translations

## To do

This PR is Ready for Review.

### CODE REVIEW

**Comment by jastevenson303** [comment]
Lgtm

**Comment by rubenwardy** [comment]
Hey, thanks for your contribution. Unfortunately, we're only able to receive translations on the weblate website:

https://hosted.weblate.org/projects/minetest/minetest/

**Comment by Panquesito7** [comment]
> Hey, thanks for your contribution. Unfortunately, we're only able to receive translations on the weblate website:
> 
> https://hosted.weblate.org/projects/minetest/minetest/
> 
> Please sign up there and resubmit your translations

Hey, @rubenwardy.
I'm not really sure if I can do that (especially, if I need to use my real name and other sensitive information).
Could you please do that for me?

**Comment by rubenwardy** [comment]
You can use a pseudonym and the same email address you use for Github

Note that git exposes your email address anyway

**Comment by Panquesito7** [comment]
> You can use a pseudonym and the same email address you use for Github
> 
> Note that git exposes your email address anyway

Well, I actually don't want to put my email publicly, so, I don't know.
I will see what I can do. Thank you.

**Comment by Panquesito7** [comment]
> You can use a pseudonym and the same email address you use for Github
> 
> Note that git exposes your email address anyway

Will other people be able to see my email?
BTW, I don't use Git. 😋

**Pull request closed without merging**
