### PR TITLE
Minor fixes in translations

### PR DESCRIPTION
**Pull request by ngosang**
Translates 8 strings and increases labels size for non English languages.

### CODE REVIEW

**Comment by ngosang** [comment]
@nerzhul This is simple to review. I rebased it.

**Comment by nerzhul** [comment]
Can you squash your commits ?

**Comment by ngosang** [comment]
Done.

**Comment by nerzhul** [comment]
commited: c7a78037809a2f9c431441f7ef91f84eb8744fff

**Pull request closed without merging**
