### PR TITLE
Load media from subfolders

### LINKED ISSUE #7818: Load textures from the subfolders in mods' textures folders
##### Issue type
 - Feature request

##### Summary
With #6412 in place I believe it would be even more coherent if mods' `textures` directory behave in the same way so that content of that directory's subdirectories are accepted when loading the mod.

### PR DESCRIPTION
**Pull request by Desour**
- This PR implements a requested feature.
- The dirs are added recursively. A media file is not loaded if a media file with the same name is in the parent directory if that is still a valid dir. Everything else in the priority should be undefined. (Apart from files in `textures/server` and `subgame/textures` being loaded first, in this order and being prioritized in this order.)
- How does the PR work?
- Closed #7818.

## To do

This PR is a Ready for Review.

## How to test

- Start a game in devtest and see how `dirt_with_grass` still looks normal.
- (Alternatively use https://github.com/DS-Minetest/smtt.)
- Rename subfolders (eg. add a `.` in the name) and play around and see if everything works as expected.

### CODE REVIEW

**Comment by DeltaNedas** [comment]
Please merge; this would be amazing for organisation of 3rd party mods and default, instead of it just being one giant lump of stuff.

**Comment by DS-Minetest** [comment]
Documentation added.

**Comment by tacotexmex** [comment]
:shipit:

**Comment by Desour** [comment]
There are now textures in minimal for testing.

**Comment by Desour** [comment]
Squashed and rebased.

**Comment by MoNTE48** [comment]
My only question is why is it still not merged?
This will allow authors to bring order to the texture in large fashions such as armor, default, trains, etc.

**Comment by pyrollo** [comment]
Tested and worked. I was a bit afraid of bringing unwanted files to media (moders could put dev/doc stuff in subfolders) but as parent files have precedence, mods behavior won't be affected.

**Comment by Desour** [comment]
:O This didn't even take one year.

**Pull request merged**
