### PR TITLE
Update debug menu.

### PR DESCRIPTION
**Pull request by FoxLoveFire**
## Update Debug menu.
Hello everyone! I think the driver name is in the wrong place. So from the window title I moved it to the debug menu. I also added the maximum FPS, as you can see in the screenshot ( | FPS: 19/60)

image

## How to test
Compile it.

### CODE REVIEW

**Comment by srifqi** [comment]
I can see the usefulness of the maximum FPS in the debug info. However, I am not sure about moving the driver information. Maybe other devs can give opinions?

**Comment by FoxLoveFire** [comment]
> I can see the usefulness of the maximum FPS in the debug info. However, I am not sure about moving the driver information. Maybe other devs can give opinions?
I want

**Comment by FoxLoveFire** [comment]
> I can see the usefulness of the maximum FPS in the debug info. However, I am not sure about moving the driver information. Maybe other devs can give opinions?
I'm interested to know the developers' opinion. I think we need less text on the window title.

**Comment by appgurueu** [comment]
Not a core dev, but I think this just unnecessarily clutters the debug info with static values.

**Comment by FoxLoveFire** [comment]
> Not a core dev, but I think this just unnecessarily clutters the debug info with static values.

Why? Isn't max FPS useful? And the driver name 100% should not be on the window title.

**Comment by appgurueu** [comment]
> Why? Isn't max FPS useful?

Maybe for others, but not for me. I know my max FPS (60) by pure virtue of that being the value my FPS maxes out at already.

> And the driver name 100% should not be on the window title.

Probably, but I find this more obtrusive. I don't really care about the window title most of the time (I often have Minetest in fullscreen mode) and there's plenty of space there.

**Comment by rollerozxa** [comment]
The reported renderer name is honestly a bit too technical to have to put it in the window title. But instead of moving it into the debug info, you could just remove it in-game altogether since its value is already exposed in the about tab.

**Comment by SmallJoker** [comment]
I don't see any need for this change.

1. The most important text of the window title already comes first. There's enough space to also contain the used video driver. Whereas not relevant for most players, it does not hurt either.
2. The maximal FPS display is not correct when vsync is used or the game is paused. What matters most is the mean 99% FPS percentile (AFAIK currently an average value is used) and the jitter. Maximal FPS may only hint towards a wrong `minetest.conf` configuration which is entirely the user's fault.

**Comment by FoxLoveFire** [comment]
Closed because it's useless

**Pull request closed without merging**
