### PR TITLE
Add in-place operations for vectors

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
  - The goal is to add some in-place vector operations.
- How does the PR work?
  - Most of the new functions take an addition vector as their first argument, separate from their operands. Instead of returning a new vector, these functions store their result in the components of the first argument.
    - I chose to have the destination separate from the first operand, as this provides more flexibility. If you want the destination to double as the first operand, you can pass the same vector for both the relevant arguments.
  - Unlike `vector.multiply` and `vector.divide`, `vector.set_multiply` and `vector.set_divide` do not accept a vector as their final argument, as this behavior was deprecated in the prior two functions.
- Does it resolve any reported issue?
  - No.
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
  - Only in that it could count as taking feedback from a modder.
- If not a bug fix, why is this PR needed? What usecases does it solve?
  - These are general utility functions. Often there is no need for vector operations to create a new vector. Using the in-place functions can reduce unnecessary copying/allocation.
  - #10328 did the same thing, and I think it would have been useful to have merged. My PR is basically a redo of that PR.

## To do

This PR is Ready for Review.

## How to test

I have added unit tests for the new functions.

### CODE REVIEW

**Comment by v-rob** [comment]
Personally, I don't like this idea very much for three reasons:
* Lua doesn't have combined assignment in general (e.g. no `+=`), so it would be inconsistent for vectors to.
* This will bloat vector operations.  If we add `set_add` and company, why shouldn't we add `set_floor` or `set_apply`?  We might get close to doubling the number of functions with this.
* Copying vectors is has no performance impact compared to modifying in place -- there were benchmarks once upon a time somewhere in IRC, I think it was.

Finally, which is easier to type anyway? `v1 = v1 + v2` or `v1:set_add(v2)`?  The first is shorter and more idiomatic.

**Comment by TurkeyMcMac** [comment]
@v-rob My replies in order:

1. True, but I don't think vector operations need 1-1 correspondence with scalar operations.
2. Since this PR is just for optimization, I only added in-place equivalents to the vector methods probably used a whole lot.
3. Following is a crude benchmark:

File `old.lua`:

```lua
dofile("builtin/common/vector.lua")

local v = vector.zero()

for i = 1, 10000000 do
	v = v:add(1)
end
```

File `new.lua`:

```lua
dofile("builtin/common/vector.lua")

local v = vector.zero()

for i = 1, 10000000 do
	v:set_add(v, 1)
end
```

I just used the `time` command to measure running time:

```
$ time lua old.lua

real	0m7.319s
user	0m7.314s
sys	0m0.001s
$ time lua new.lua

real	0m3.939s
user	0m3.933s
sys	0m0.004s
```
This benchmark used Lua 5.1.5.

**Comment by Desour** [comment]
- I like this 3 argument form.
- Try benchmarking with luajit.

**Comment by TurkeyMcMac** [comment]
@Desour I have now run a benchmark with LuaJIT.

Running the previous benchmark code didn't work so well due to LuaJIT's optimizations. In both cases, I believe it managed to do away with the vector table entirely within the tight loop. I should note that there was still some difference in times. The new code ran a bit faster. However, when I changed the code to call the functions as `vector.func` rather than `v:func`, the old code was actually somewhat faster. As far as I can tell, LuaJIT generated slightly faster code in the inner loop for some reason. I don't know how often this situation will come up in actual mod code, but it might be significant.

I devised a new benchmarking program `bench.lua` to test how different solutions perform when the vectors actually exist as tables:

```lua
print("Version: " .. (jit and jit.version or _VERSION))

dofile("builtin/common/vector.lua")

local USE_NEW = arg[1] == "new"
local SIZE = tonumber(arg[2]) or 10000
local REPS = tonumber(arg[3]) or 10000

math.randomseed(50)

local vs = {}
for i = 1, SIZE do
	vs[i] = vector.zero()
end

local start = os.clock()

for i = 1, REPS do
	for j = 1, SIZE do
		if USE_NEW then
			vs[j]:set_add(vs[j], math.random(-1, 1))
		else
			vs[j] = vs[j]:add(math.random(-1, 1))
		end
	end
end

local elapsed = os.clock() - start

print(("vs[1] = (%f, %f, %f)"):format(vs[1].x, vs[1].y, vs[1].z))
print("Elapsed time: " .. elapsed)
print("Memory usage now: " .. collectgarbage("count") .. " KB")

return vs
```
I got this result with the old version:

```
$ luajit bench.lua old
Version: LuaJIT 2.1.0-beta3
vs[1] = (44.000000, 44.000000, 44.000000)
Elapsed time: 14.446108
Memory usage now: 2885.5419921875 KB
```

And this result with the new version:

```
$ luajit bench.lua new
Version: LuaJIT 2.1.0-beta3
vs[1] = (44.000000, 44.000000, 44.000000)
Elapsed time: 1.755861
Memory usage now: 1425.669921875 KB
```

In this case, the new version is much faster and uses less memory.

**Comment by rubenwardy** [comment]
Thanks for the contribution! Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed.

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label. In the future, you can open an issue first to get preapproval before working on something

**Pull request closed without merging**
