### PR TITLE
Android: Update build system for ndk-r16

### PR DESCRIPTION
**Pull request by stujones11**
This PR fixes the android build system for the latest development kits you get with Android Studio (tm)

While this does allow all of our dependencies to successfully build again, it does not fix the numerous minetest build errors which seem mostly related to the c++11 changes, rendering-engine abstraction and other code refactoring. These mostly seem to be easy fixes, however, I think some may need to be dealt with on an individual basis.

Merging this PR will enable more devs and contributors to help address these issues.

### CODE REVIEW

**Comment by Reedych** [comment]
Will it be compatible with android 4.0+?

**Comment by basicer** [comment]
I was able to get android to build doing similar changes, however switching from gnustl to c++ made minetest crash on load for me.

**Comment by stujones11** [comment]
> switching from gnustl to c++ made minetest crash on load for me.

I didn't get that far yet, if that's the case we probably need to switch to clang, although afaik the STL's should be interchangeable. If this is not the case then the alternative is a lot of hacky workarounds to continue using ` gnustl_static`

**Comment by sfan5** [comment]
:+1: looks fine to me
however haven't tested, especially the c+11 & STL change should be checked

**Comment by stujones11** [comment]
> the c+11 & STL change should be checked

Unfortunately, we have no way of knowing for sure until the MT build errors are fixed so it's a bit of a catch 22 really. BTW do you know of any good reason for not simply switching to llvm?

**Comment by basicer** [comment]
https://github.com/buildwithpiper/minetest/commit/302275beb780995e2c06094c2f8072e1fb511aa1 was my attempt at using c++ stl but it crashes on launch.   I got a bit farther using gnustl and a bunch of c++11 comparability hacks.  That version shows the loading bar and then crashes on a pure virtual call.

**Comment by stujones11** [comment]
@basicer Thanks, that does seems pretty conclusive but I will give it another go now that I can fix the build errors. I have now removed the c++11 changes since they are not really relevant to this PR which was mostly about supporting the latest NDK 'unified headers'. I will look into this more over the weekend and will provide a more complete fix if I am able.

**Comment by nerzhul** [comment]
seems good to me

**Comment by stujones11** [comment]
I was finally able to create an apk using @basicer's patches plus a few other minor updates. This does, however, crash on load for me also with which looks to be `libc` related. Branch is here if anyone's interested: https://github.com/stujones11/minetest/commits/android-build-c11

**Comment by stujones11** [comment]
@basicer According to https://developer.android.com/ndk/guides/standalone_toolchain.html we also need to tell the standalone toolchain we're using the LLVM libc++ STL otherwise it defaults to gnustl which is clearly not good. It also looks like we should be using the static variant but also enforce static linking with -static-libstdc++ I have added these to the Makefile but still it crashes, however, I am not sure that I added the linker flags properly. I've pushed the changes to my WIP branch linked above.

**Comment by stujones11** [comment]
Yay, I was finally able to make it work with yet more changes to the out-dated makefiles. It seems it does at least work with `c++_shared`.

I also updated this PR for the new stable ndk-r16, however, these are workarounds rather than fixes. We desperately need a better build system written in bash or maybe even python?

**Comment by nerzhul** [comment]
good job

**Comment by stujones11** [comment]
@nerzhul Thanks, it would be nice to get these fixed merged before they get stale. If this  PR can be merged then either @basicer or I can submit the additional changes as a separate PR. Alternatively you can pull the changes directly from my repo, I don't mind, it's mostly basicer's work, I only got the darn thing to link properly.

It would be nice to have a working build system again, even though it's far from ideal. This will enable people to improve the app ready for 0.5. I will have some more time to spend over the holidays and might even have a go at improving the controls, After all. I am partly responsible for the current setup.

**Comment by basicer** [comment]
@stujones11 In C++, getting things to link can often be most of the work.

I pulled your patch and it works great :).  The only thing I've changed in my version is that I don't load ssl or crypto in the native activity because they are static linked.  Trying to load the dynamic version caused an annoying dialog on my phone.

The only thing I cant figure out at present is that my camera position seems to be in the ground on a mineclone2 based server, and my menus were way too large (though I fixed the later by setting gui_scale=0.5).

**Comment by stujones11** [comment]
> my camera position seems to be in the ground on a mineclone2 based server

Is the server running a development build? Otherwise I'd say that's likely due to the player offset. Thanks for testing, though I'm still not sure why I can't get it to link statically as it was with gnustl, nor am I sure of the ramifications of dynamic linking, I will continue to investigate :)

**Comment by paramat** [comment]
Is this ready for merge? Has 2 approvals.

**Comment by stujones11** [comment]
It can do no harm in it's current form, the rest of the changes will require more scrutiny and discussion, which is why I'd like to keep those separate.

**Comment by paramat** [comment]
Ok will merge.

**Comment by stujones11** [comment]
Thanks, just a reminder that this should also close #6588 :)

**Comment by paramat** [comment]
2507d32afe05c73bb27ed221c2a592b0894fdc68

**Pull request closed without merging**
