### PR TITLE
Change some colors of send message on some commands

### PR DESCRIPTION
**Pull request by Toby1710**
For example: when you type /kick and it failed it's red and it didn't fail then it's green.
I changed "Message sent." color, "DM from ..name.." also changed.
Also I changed "Failed to ban player", "Player is not online", "Banned", "Kicked", "Unbanned", "Failed to unban player/IP", "Failed to kick player" colors. I hope you like it!

### CODE REVIEW

**Comment by MoNTE48** [comment]
`minetest.colorize("#e32110"` => `minetest.colorize("red"`
https://github.com/minetest/minetest/blob/master/src/util/string.cpp#L466-L612

**Comment by rubenwardy** [comment]
This doesn't really make sense and will result in inconsistent colors. What you could do is make is so every false return from a chat command is colored red by default

**Comment by Toby1710** [comment]
> This doesn't really make sense and will result in inconsistent colors. What you could do is make is so every false return from a chat command is colored red by default

Yeah, I was thinking about it

**Comment by MoNTE48** [comment]
image
```
local colorize = minetest.colorize
local function green(s) return colorize("limegreen", s) end
local function red(s) return colorize("red", s) end
```

**Comment by Toby1710** [comment]
> local colorize = minetest.colorize
> local function green(s) return colorize("limegreen", s) end
> local function red(s) return colorize("red", s) end

What's this?

**Comment by MoNTE48** [comment]
Just a few random lines from the code of my game that express my subjective point of view, according to which Ruben is wrong.

**Comment by rubenwardy** [comment]
image

**Comment by randomMesh** [comment]
> that express my subjective point of view

You should read up on [the w3.org WCAG 2.0 guidelines on contrast accessibility](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).

**Comment by Toby1710** [comment]
What should I change?

**Comment by rubenwardy** [comment]
You should make it colour all chat commands based on the success value

However, you should wait for concept approval first. I'm neutral on that feature

**Comment by Toby1710** [comment]
> You should make it colour all chat commands based on the success value
> 
> However, you should wait for concept approval first. I'm neutral on that feature

Ok

**Comment by daytonnvpaul** [comment]
Does anyone ever consider that some people are colorblind?

**Comment by 0-afflatus** [comment]
> Does anyone ever consider that some people are colorblind?

Yes, that's what the document on contrast accessibility is about. It's best to avoid red/green and blue/orange at the same level of contrast. Designers who consider accessibility issues usually consider colour blindness as well. Of course there are others who think we can all read 9pt sans comfortably and don't even provide means for changing the UI font size. I'm looking at you Flightgear!

**Comment by MoNTE48** [comment]
> Does anyone ever consider that some people are colorblind?

Someone thought that creating dye, colored wool and other mods could complicate their game? And then there are people with inhibited motor skills and they cannot play multiplayer with PVP or mobs_monster enabled...
Sorry, this is nonsense. Colors can be easily made optional as part of "accessibility," like in macOS (I can control my MacBook hands-free using the built-in camera and easy-to-activate face, eye and facial tracking.)

**Comment by daytonnvpaul** [comment]
@MoNTE48, I'm so sorry you think that its nonsense to put down people with disABILITIES. 

Text is much more important in any game, than the objects in the game.  You're comparing apples to oranges.  The colored text should be optional, not the default.

Generally speaking, people should consider how disABILITIES can affect people, rather than proclaiming they have no problem.  AKA: The, "It works for me" syndrome.

With your view on this specific subject of colored text, are you implying that I should have never promoted one of the colorblind players on my server to moderator?  Why did it become my responsibility to find a server based workaround to disable colored IRC text in the game, rather than leaving it as an option in client settings?  This is the part that's nonsensical.

For what its worth, a personal friend of mine, and the main person that triggered my interest in minetest, was a fire fighter that lost both of his legs in a house fire while trying to saving the pet cat of a child.  The accident and the trauma involved, is what seemed to make his vision very similar to those of inherited colorblindness.

The real ironic part of this accident, was the rescued 8 year old cat,  had been adopted from a shelter, and had lost one of its legs prior to the family's adopting of it.

Please note that the subject of this PR is 'colored chat text', not 'colored wool' or 'dye colors'.

Sorry, but to put your assertions ahead of considering a debate of an issue, is the actual nonsense.

Here's a link for some basic education regarding colorblindness, and an eye opener (pun intended) about just how common this disorder is.

https://www.color-blindness.com/wp-content/documents/Color-Blind-Essentials.pdf

I trust I brought just a little more brightness to your day. -- sarcasm intended.

**Pull request closed without merging**
