### PR TITLE
Add Lua methods set_attach_position and set_attach_rotation (as well as get_attach_position/rotation) for attached entities.

### PR DESCRIPTION
**Pull request by CoderForTheBetter**
This PR allows attached entities' positions and rotations to be modified without the need for calling `set_detach()` and then reattaching again to do so.

**Why?**
Because calling `set_detach` and then attaching again uses a lot of CPU time and bandwidth. This only modifies the position or rotation and sends either one of those over the network instead of a whole call to `set_attach`. Also, if a player is attached, calling `set_detach` and then `set_attach` multiple times a second will make the player's view flicker (an unconfirmed bug that I found when playing around).

**Uses?**
If we ever implement [Voxel Area Entities (scroll down)](https://forum.minetest.net/viewtopic.php?t=9177) then this will be needed if players want to 'walk' around a boat for example. It will also allow for players to move around trains and other vehicles. Having access to these also just makes sense.

As far as I can tell, this should not break the network (it might though, not sure) but that should not matter if merged before 0.5.0.

I have tested this and found that the position is still scaled weird and that rotation is not exact. Can anyone confirm if rotation is off when using set_attach only? From my own testing, a rotation of 90 degrees is actually about 9 when using the new Lua methods this PR adds. Position is also scaled by  1/10 it [seems](https://github.com/minetest/minetest/issues/894#issuecomment-202079670).

For testing, here's a mod with some commands: [attachtest](https://github.com/CoderForTheBetter/attachtest)

### CODE REVIEW

**Comment by ClobberXD** [comment]
Good idea, great feature. Will test it out within a day.

**Comment by SmallJoker** [comment]
> Because calling set_detach and then attaching again uses a lot of CPU time and bandwidth.

`set_attach` can be used alone without `set_detach`. So after all it's two 3d-float vectors, a string and the GANERIC_CMD number which is sent to the player. It might require a little more CPU time due to the detection of the bone node. That's why I'm not sure whether your PR will bring much of a benefit here.

> It will also allow for players to move around trains and other vehicles.

Sounds good but this movement would be controlled by mods on each server step unless the attachment system is changed.

**Comment by stujones11** [comment]
> set_attach can be used alone without set_detach

I must admit I was thinking the same thing. The only real advantage I can see here is that you would not need to supply the parent object and re-set the attachment bone each time. I guess it depends just how costly that is.

**Comment by CoderForTheBetter** [comment]
@SmallJoker you're right, no need to call `set_detach` I forget why I thought you might. I understand that the server would need to handle the moving around of vehicles. I already have a mod where I handle each player's up/down and left/right input that is attached an entity.

@ClobberXD that warning was from a variable that I forgot to remove (fixed now). The fact that the box (child) got small after destroying the axis (parent) has always been a bug in Minetest I think. Anyways, I didn't mess with anything that involves the `set_attach` or `set_detach` methods, so if you were to do the same thing without this PR this should still happen.

I guess this PR might not be worth it. The only other reasons I can think of it being a good idea for is that it is more intuitive for a new modder to think of using the methods this PR introduces then using set_attach again to change position/rotation.

I'll just point these out. The two biggest places where performance can take a hit (even if small) are [here:](https://github.com/CoderForTheBetter/minetest/blob/5cb03446e3f141b7c3d2bcb4cb54a814e8ebeddb/src/content_cao.cpp#L1432-L1467)
```
	} else if (cmd == GENERIC_CMD_ATTACH_TO) {
		u16 parent_id = readS16(is);
		u16 &old_parent_id = m_env->attachement_parent_ids[getId()];
		if (parent_id != old_parent_id) {
			if (GenericCAO *old_parent = m_env->getGenericCAO(old_parent_id)) {
				old_parent->m_children.erase(std::remove(
					m_children.begin(), m_children.end(),
					getId()), m_children.end());
			}
			if (GenericCAO *new_parent = m_env->getGenericCAO(parent_id))
				new_parent->m_children.push_back(getId());


			old_parent_id = parent_id;
		}


		m_attachment_bone = deSerializeString(is);
		m_attachment_position = readV3F1000(is);
		m_attachment_rotation = readV3F1000(is);


		// localplayer itself can't be attached to localplayer
		if (!m_is_local_player) {
			m_attached_to_local = getParent() != NULL && getParent()->isLocalPlayer();
			// Objects attached to the local player should be hidden by default
			m_is_visible = !m_attached_to_local;
		}


		updateAttachments();
	} else if (cmd == GENERIC_CMD_SET_ATTACH_POSITION) {
		m_attachment_position = readV3F1000(is);
		updateAttachmentPosition();


	} else if (cmd == GENERIC_CMD_SET_ATTACH_ROTATION) {
		m_attachment_rotation = readV3F1000(is);
		updateAttachmentRotation();


	} else if (cmd == GENERIC_CMD_PUNCHED) {
```


and also [here](https://github.com/CoderForTheBetter/minetest/blob/5cb03446e3f141b7c3d2bcb4cb54a814e8ebeddb/src/content_cao.cpp#L1220-L1280)
```
void GenericCAO::updateAttachments()
{


	if (!getParent()) { // Detach or don't attach
		scene::ISceneNode *node = getSceneNode();
		if (node) {
			v3f old_position = node->getAbsolutePosition();
			v3f old_rotation = node->getRotation();
			node->setParent(m_smgr->getRootSceneNode());
			node->setPosition(old_position);
			node->setRotation(old_rotation);
			node->updateAbsolutePosition();
		}
		if (m_is_local_player) {
			LocalPlayer *player = m_env->getLocalPlayer();
			player->isAttached = false;
		}
	}
	else // Attach
	{
		scene::ISceneNode *my_node = getSceneNode();


		scene::ISceneNode *parent_node = getParent()->getSceneNode();
		scene::IAnimatedMeshSceneNode *parent_animated_mesh_node =
				getParent()->getAnimatedMeshSceneNode();
		if (parent_animated_mesh_node && !m_attachment_bone.empty()) {
			parent_node = parent_animated_mesh_node->getJointNode(m_attachment_bone.c_str());
		}


		if (my_node && parent_node) {
			my_node->setParent(parent_node);
			my_node->setPosition(m_attachment_position);
			my_node->setRotation(m_attachment_rotation);
			my_node->updateAbsolutePosition();
		}
		if (m_is_local_player) {
			LocalPlayer *player = m_env->getLocalPlayer();
			player->isAttached = true;
		}
	}
}


void GenericCAO::updateAttachmentPosition()
{
	if (getParent()) {	// Make sure parent exists (child is attached to parent)
		scene::ISceneNode *node = getSceneNode();
		if (node) {
			node->setPosition(m_attachment_position);
		}
	}
}


void GenericCAO::updateAttachmentRotation()
{
	if (getParent()) {	// Make sure parent exists (child is attached to parent)
		scene::ISceneNode *node = getSceneNode();
		if (node) {
			node->setRotation(m_attachment_rotation);
		}
	}
}
```

Compare the new methds for postion and rotation to the old. Seems like a lot of work just to set one thing. Sorry for all the code.

**Comment by stujones11** [comment]
I suppose this could be quite beneficial for mods that frequently need to switch attachment position or rotation, without changing parent or bone. My own `wield3d` mod is a good example of this.

**Comment by CoderForTheBetter** [comment]
Exactly. Like I said in the OP, if for example, you have a player attached to an entity, such as a boat, and you want them to be able to walk around, then their key input would be handled on the server and a new position could be calculated base on parent and child yaw. Once a new position is ready then it is as simple as using the methods this PR has instead of `set_attach`. Calling `set_attach` multiple times for multiple players is going to get bad pretty quick, I think.

**Comment by CoderForTheBetter** [comment]
This is ready for review when someone has time.

**Comment by raymoo** [comment]
>If we ever implement Voxel Area Entities (scroll down) then this will be needed if players want to 'walk' around a boat for example. It will also allow for players to move around trains and other vehicles. Having access to these also just makes sense.

Or, since VAEs would be an engine feature anyway, have a new attachment mode that puts the player in the reference frame of the VAE for the purposes of physics and movement. This would be better than using set_attach_position to move the player around the VAE because it would allow the client to simulate player movement and avoid the movement delays that would come from mod code implementing movement on the server.

I still think this PR might be useful for the reasons stu mentioned.

**Comment by CoderForTheBetter** [comment]
Tested this more. There are some bugs. The position is scaled I think ten times (definitely isn't the same pos that an entity would be attached at if using `set_attach`) and rotation is incorrect. I will do more testing and show results when done, for now, it is WIP.

**Comment by paramat** [comment]
@CoderForTheBetter is this abandoned?

**Comment by CoderForTheBetter** [comment]
Yes, go ahead and close it if you want. I may come back sometime to complete this after some other stuff.

**Comment by paramat** [comment]
Ok will close due to the amount of time with no progress, but we will re-open it if/when you want to work on it again.

**Pull request closed without merging**
