### PR TITLE
Added the option to hold objects in the left hand

### PR DESCRIPTION
**Pull request by Mappaschreck**
# Left-handed mode

Unbenannt

- left-handed-mode added
- added an entry in the settings menu

Add compact, short information about your PR for easier understanding:

- Goal of the PR: Add the option to use Minetest immersively even as a left-hander
- How does the PR work? Customise the camera.cpp
- Does it resolve any reported issue? No.
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)? From my point of view, yes
- If not a bug fix, why is this PR needed? What usecases does it solve? See Goal

## To do

This PR is a Work in Progress

- [ ] Add left-handed-mode in 3d-person-view
- [x] Add an option in the settings menu to activate left-handed mode more easily
- [ ] Rewriting into a Lua-based implementation

## How to test

Activate the option "Enable Left-Hand Mode under "Settings -> Graphics and sound -> User interfaces -> HUD

### CODE REVIEW

**Comment by sfence** [comment]
This will be possibly in conflict with #14427.

**Comment by cx384** [comment]
> I'm looking forward to the discussion here about generalizing this

Here we go.

IMO, using a setting for this is not the way to go, because it makes the HUD even more unpredictable, scatters HUD related things (high cohesion low coupling principle), and it's not very flexible.

I still think it would be best to turn the hand into a Lua HUD element.
This way, you can also move the hand to the left and change its rotation, like it would be done with your setting.

**Comment by Desour** [comment]
There was an old issue about this: #1465

---

>Add left-handed-mode in 3d-person-view

FYI, this is implemented by mods. So you'll need to send the handedness to the server, and add a function to the API.

>Add an option in the settings menu to activate left-handed mode more easily

Just needs an edit in builtin's settingtypes.txt.

---

>I still think it would be best to turn the hand into a Lua HUD element.
>This way, you can also move the hand to the left and change its rotation, like it would be done with your setting.

But there's still an engine default. So it wouldn't be unreasonable for the engine to also provide a setting for this default.

**Comment by Mappaschreck** [comment]
> > Add an option in the settings menu to activate left-handed mode more easily
> 
> Just needs an edit in builtin's settingtypes.txt.

Thank you! I have added the option to the settings menu.

**Comment by cx384** [comment]
> But there's still an engine default. So it wouldn't be unreasonable for the engine to also provide a setting for this default.

IMO, it would better to force people to use `core.hud_replace_builtin()` and for client side eventually support HUD changes via CSM, but if you are ok with occasionally overlapping and inconsistent HUD things I guess this is no problem. I mean, some people also want to keep the `hud_hotbar_max_width` setting. So, fine, add this setting if you think it is worth the trouble.

**Comment by ezileicorreia** [comment]
We've been waiting for the "perfect" feature for 4 years!

**Comment by Mappaschreck** [comment]
> > I'm looking forward to the discussion here about generalizing this
> 
> Here we go.
> 
> IMO, using a setting for this is not the way to go, because it makes the HUD even more unpredictable, scatters HUD related things (high cohesion low coupling principle), and it's not very flexible.
> 
> I still think it would be best to turn the hand into a Lua HUD element. This way, you can also move the hand to the left and change its rotation, like it would be done with your setting.

I will try to make the left-handed mode a Lua-based implementation so as not to overload the engine code.

**Comment by Zughy** [comment]
Closing due to the different opinions which will unlikely bring to an approval. Unfortunately the wielding hands are a complex subject and we probably need more discussions (and agreements) before attempting any PR of sort

**Pull request closed without merging**
