### PR TITLE
[no squash] Android stuff

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by SmallJoker** [comment]
What should be tested here? Whether the build process still works? Whether the app start up?

**Comment by sfan5** [comment]
Both, I suppose.

**Comment by rubenwardy** [comment]
I'm confident with all the commits except for [Skip Android deps download if they already exist](https://github.com/minetest/minetest/pull/14382/commits/07fc136bf593f106030413b16cc71de073641915).

I don't know gradle/groovl, so I don't know if programmatically changing the number of registered tasks would have side effects. How confident are you with this? It's possible it would mess with the task dependency graph. Googling finds the following promising looking things:

* Task.onlyIf - only run a task if a condition is met
* outputs.file/dir - maybe this allows you to tell gradle about the files, so it doesn't rerun the task if they exist?

**Comment by sfan5** [comment]
I have tested it and it works so I'd rather not rewrite it around `onlyIf`. AFAIK gradle also revaluates all build files & the dependency graph every time you run it so that shouldn't be an issue in practice.

**Review by rubenwardy — APPROVED** [review]
Tried to break Gradle and couldn't so looks good to me

**Pull request merged**
