### PR TITLE
Sort ObjectRef API functions

### PR DESCRIPTION
**Pull request by Zughy**
**BEFORE YOU PANIC SEEING THE DIFF LINES: KEEP READING**

I didn't change any code. I only sorted these functions in order to follow a logic order. In short:
* functions with a similar context (e.g. movement ones) are now next to each other. The fastest way to check it is by having a look [here](https://github.com/Zughy/minetest/blob/object_order/src/script/lua_api/l_object.cpp#L2290) . This applies both to `object.h`, `object.cpp` and `lua_api.txt`
* some Player-only functions were in the generic SAO section: they've been moved accordingly
* getters before setters: they were put arbitrarily
* there was a unused function in `object.h` called `hud_get_next_id`. No trace in the .cpp, in the whole code, nor in the API. Deleted
* `set_armor_groups()` in the API had no definition, so I put one
* a few getters in the API lacked of `()` at the end, which I put

EDIT: apparently I'm an idiot and there are also the commits of my previous PR even if it's another branch. Don't mind them, they've already been merged into master

## To do

This PR is Ready for Review.

## How to test

Check the "here" link. You don't want to check every line of code

### CODE REVIEW

**Comment by SmallJoker** [comment]
Makes sense. This would break a few PRs but rebasing those shouldn't be a big deal as long the code is only moved.

**Comment by sfan5** [comment]
Change for the sake of being different, if you have an editor with source code navigation (even Ctrl+F works) this will not make a difference.
:-1:

**Comment by Zughy** [comment]
Yes, that doesn't make a difference in the lua_api _if_ a modder already knows what to look for, but I don't think that's true for a newcomer. Also, in my PR defense, I must say that if it weren't for this cleaning, I wouldn't have noticed things like `remove()`, which should be a LuaEntitySao function only (but that's for another PR). Or the one I deleted which was lying there just because

**Comment by paramat** [comment]
A logical order is ideal and in a different kind of project desirable of course, but unfortunately i think we need to keep in mind the lack of core dev time, such that unnecessary changes like reordering are probably an unwise prioritisation of time. With this approach to code, we could easily use up most of core dev time just on unnecessary code perfectionism.

However, other parts of this are more useful and i support these:
> some Player-only functions were in the generic SAO section: they've been moved accordingly
there was a unused function in object.h called hud_get_next_id. No trace in the .cpp, in the whole code, nor in the API. Deleted
set_armor_groups() in the API had no definition, so I put one
a few getters in the API lacked of () at the end, which I put

I suggest the PR is redone to contain just these more useful changes. Personally, i could face reviewing these, but re-ordering as well makes this harder to review and makes me not want to review this.
Sorry, i do appreciate your inspiration for cleaning up, i am like this too, as i am naturally 'organisational'.

**Comment by Zughy** [comment]
I agree with you, Paramat, but as I didn't really change functions, I thought it was more of a matter of trust than code review. I don't think anybody would like to review this. But sure, if we're not there (yet?), I guess I'll do a different PR. I'd like to wait at least for another core dev if this seems reasonable before closing it, though, as for now it's 1 v 2 and I'd really like not to redo kind of everything

**Comment by paramat** [comment]
Although this is closed, here are some further comments:

Was the contribution the last commit only? Looking at the commits it is very difficult to work out which have already been merged.
Also confusingly, the last commit seems to contain lots of unrelated changes to lua_api.txt.

If so, there was another problem. If you mix the reordering and the line changes/deletions into one commit it becomes very difficult to review, because the line changes/deletions are lost in the diff of the reordering, it is very difficult to know which lines have been changed/deleted and which have been moved.

So just a request for future PRs: Please try to split work into commits in a way that makes it easier to review, if not doing so makes it hard to review, as here. So here the reordering woud be one commit, the line changes/deletions another.
> but as I didn't really change functions, I thought it was more of a matter of trust than code review.

Erm ... =) ... nothing is merged on trust, even long experienced core devs require PR review and approval on their contributions.
The only exception is when a core dev has a small and trivial change.
This is stated in the dev rules in the dev wiki, worth reading.
Besides, if you have mixed reordering and line changes/deletions in 1 commit, it could not be trusted even if the reordering was trusted.

**Comment by sfan5** [comment]
> Yes, that doesn't make a difference in the lua_api _if_ a modder already knows what to look for, but I don't think that's true for a newcomer. 

I didn't specifically mean lua_api.txt. Cleaning up docs is fine and can be useful, but all those changes to l_object.cpp are not.

**Pull request closed without merging**
