### PR TITLE
Remove unused light updating code

### PR DESCRIPTION
**Pull request by juhdanad**
Also remove the unit test that tests the removed algorithms.

### CODE REVIEW

**Comment by srifqi** [comment]
What is the implication if this applied?

**Comment by nerzhul** [comment]
@juhdanad is this possible to port unittests to the new light code ?

**Comment by juhdanad** [comment]
> What is the implication if this applied?

Nothing besides smaller code size. These functions were never called by the engine. If the unused code is still required for something, it will be in the project's history.

> Is this possible to port unittests?

It is difficult, because the removed code updates light in voxel manipulators, but the current implementation updates light directly in the map (the functions require a `Map` object). I would not make it in this PR.

**Comment by paramat** [comment]
Was this code ever used? Or is it unused since your changes to light code?

**Comment by juhdanad** [comment]
@paramat: Some functions were used before #4655, some were unused even then.

**Comment by paramat** [comment]
:+1: i assume it's tested.

**Comment by lhofhansl** [comment]
Big 👍 for removing all this code if unused.

I've looked through the lighting code every now and then for various reasons, and was baffled by the size of it - but I never checked if all it was used.

**Pull request merged**
