### PR TITLE
InventoryManager: Disallow resizing or deleting inventory lists that are in use

### LINKED ISSUE #13358: Crash caused by InvRef:set_list(LISTNAME, nil) in allow* callbacks
##### Minetest version
Version 5.7.0-dev baf99f826c

```
Thread 19 "Server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb3fff640 (LWP 9688)]
0x0000555555b69a66 in IMoveAction::apply(InventoryManager*, ServerActiveObject*, IGameDef*) ()
(gdb) bt
#0  0x0000555555b69a66 in IMoveAction::apply(InventoryManager*, ServerActiveObject*, IGameDef*) ()
#1  0x000055555593b995 in Server::handleCommand_InventoryAction(NetworkPacket*) ()
#2  0x0000555555c123ac in Server::ProcessData(NetworkPacket*) ()
#3  0x0000555555c125a7 in Server::Receive() ()
#4  0x0000555555c26ef2 in ServerThread::run() ()
```

##### OS / Hardware
Linux x86_64

##### Summary
 * put & take work flawlessly
 * move segfaults (list name `detached:PLAYERNAME_workbenchX` where X is any of 3,4,5)

##### Steps to reproduce
1. https://github.com/cornernote/minetest-workbench/
2. Place a workbench
3. Open
4. Move items
5. Crash (sometimes it works due to overlapping memory areas)

For reference, #11882 very likely suffers from the same issue.

### PR DESCRIPTION
**Pull request by SmallJoker**
Naive solution to prevent InventoryList UAF and OOB ItemStack access

Fixes #13358 by preventing shrink/clear operations on InventoryLists that are in use by the inventory action.

## To do

This PR is Ready for Review.

## How to test

1. https://github.com/cornernote/minetest-workbench/
2. Place a workbench
3. Open
4. Move items
5. Minetest no longer segfaults occasionally but throws a proper error,

I do not know when Minetest became incompatible with this mod, but I assume it was caused by the callback fixes years ago.

### CODE REVIEW

**Review by Desour — COMMENTED** [review]
`meta:from_table()` isn't handled. Maybe add checks in `inv::deleteList`?

I'm not sure if this handles all cases, but it's a step into the right direction. :+1:

(In the long term we should probably redesign such callback designs, i.e. by only doing one call to builtin, from where we then implement the apply function with the lua API.)

**Comment by SmallJoker** [comment]
`inv::deleteList` is already protected, however `~Inventory` was not. I now made sure that the exception are thrown properly in that case as well.

**Comment by Desour** [comment]
Destructors are `noexcept` by default. If you throw an exception in `~Inventory()` (via `clear()`), `std::terminate` is called. A lua error would be better. For that, you'll have to check the lock before destructing, e.g. in `NodeMetadataList::remove` (or declare the destructor `noexcept(false)`).

---

Also suggestion: https://github.com/SmallJoker/minetest/pull/2 :-)

**Comment by SmallJoker** [comment]
> A lua error would be better. For that, you'll have to check the lock before destructing, e.g.

This IMO involves too deep integration into otherwise unrelated code. If this PR can catch all invalid operations before the inventory itself is being deleted, that's fine by me as a first solution.

**Review by Desour — APPROVED** [review]
LGTM.

**Pull request merged**
