### PR TITLE
Sao refactor

### PR DESCRIPTION
**Pull request by Rogier-5**
SAO refactorization, split off from #4743. See the discussion there for more details.

The first commit is PR 4743; the refactorization is based on that code. IMO there is no point splitting the two, only to have to rebase this again after 4743 is merged.

### CODE REVIEW

**Comment by paramat** [comment]
It might be too close to release for a refector now, but the first commit may be good to merge before release.

**Comment by est31** [comment]
Yes, its nice, but let's wait for after 0.4.15.

**Comment by paramat** [comment]
Ah i see, the bugfix part would be merged with #4743 not here.

**Comment by Rogier-5** [comment]
Rebased

**Comment by nerzhul** [comment]
@est31 what do you think about splitting this PR in two part, first part constness + moving some attributes to UnitSAO if they are common (which is just code factorization)

Second part, the clientInitdata refactor

**Comment by est31** [comment]
@nerzhul I think I agree, as long as it isn't too unreasonable (if the number of changed lines per change doesn't decrease then its unreasonable).

**Comment by nerzhul** [comment]
@est31 with two parts it permits to push this PR before release easily and if you want to wait on the clientinitdata refactor after release (the tricky part) could be done :)

**Comment by Rogier-5** [comment]
Refactor operation split. See PR 4764 for the clientinitdata part.

**Comment by est31** [comment]
Its good that they areseparate, but I'd prefer if both of these changes were merged after release.

**Comment by nerzhul** [comment]
superseed by https://github.com/minetest/minetest/pull/4764

**Pull request closed without merging**
