### PR TITLE
Attempt to improve performance by combining 6 vectors into one using a struct

### PR DESCRIPTION
**Pull request by ShadowNinja**
Alternative to #3534.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Better than the original pull :+1:

**Comment by PilzAdam** [comment]
And is this attempt successful? Does it improve performance?

**Comment by sofar** [comment]
> And is this attempt successful? Does it improve performance?

I'm succumbing to spontaneous combustion due to the suspense myself :D

**Comment by gregorycu** [comment]
This will improve performance on windows debug builds for sure.

Also, is better code. More structure than a lot of vectors for each thing.

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
Shall we merge this then? Build fail is the usual thing that can be ignored.

**Comment by paramat** [comment]
6e30dd05f40a97106752d724d176443b184eaf27

**Pull request closed without merging**
