### PR TITLE
As indicated in its name m_client_event_queue should be a queue

### PR DESCRIPTION
**Pull request by nerzhul**
Change std::list to std::queue to improve the queue performance

### CODE REVIEW

**Comment by nerzhul** [comment]
@est31 can you review and push if you agree please ?

**Comment by est31** [comment]
@nerzhul have you checked at every place that container is used that the behaviour of the method is the same? We had an error once caused by one such container change where the method had the same name, but behaviour changed, and caused problems.

**Comment by nerzhul** [comment]
As you see in the PR the container is only called there. It's only called on the ClientEnvironment, there are no insertion with sorting , it's only a fifo queue

**Comment by est31** [comment]
Merged, with edited commit msg (split up the long line :p ): 1f1e14ab7fe1680eae12955929be004af7f39fe4

**Pull request closed without merging**
