### PR TITLE
Change ASCII art letters to make them fit into the terminal window

### PR DESCRIPTION
**Pull request by HybridDog**
Obviously the original one is from there:
http://patorjk.com/software/taag/#p=display&f=Graffiti&t=minetest

Before:
2016-03-05-132918_1920x1080_scrot

After:
2016-03-05-132904_1920x1080_scrot

### CODE REVIEW

**Comment by MoNTE48** [comment]
My variant:
http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Big&t=minetest
http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Stop&t=minetest
http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Stforek&t=minetest

**Comment by sfan5** [comment]
You can barely recognize what it means anymore.
Also, just resize your terminal, problem solved.

:-1:

**Comment by HybridDog** [comment]
>Also, just resize your terminal, problem solved.

The problem is back when l open another one.

**Comment by 0-afflatus** [comment]
Why not allow the boilerplate to be printed out without the timestamps, which are utterly egregious.
This should be < 80 chars wide - that is the default width for a terminal screen.

> Also, just resize your terminal, problem solved.

IMO that's a workaround, not a solution.

**Comment by ShadowNinja** [comment]
Printing to `cerr`/`clog` instead sounds like a good solution.

**Comment by paramat** [comment]
Your 'after' screenshot looks completely wrong though.

**Pull request closed without merging**
