### PR TITLE
Settings Tab : Regroup dropdown datas in tables

### PR DESCRIPTION
**Pull request by kilbith**
To sort out the mess and make the function names better readable.

Moving these datas into tables look cleaner.

Cc: @est31 @paramat

### CODE REVIEW

**Comment by kilbith** [comment]
It's not WIP in this case. My mission is accomplished here (unless you have some remarks).

**Comment by est31** [comment]
looks good

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
04e311a36d15ad6c1e4436f169fe6b45e855009f

**Pull request closed without merging**
