### PR TITLE
WIP: Save selected server description and display it when we restart the game

### PR DESCRIPTION
**Pull request by Dumbeldor**

### CODE REVIEW

**Comment by paramat** [comment]
Do you mean "Save selected server description and display it when we restart the game"? Title is unclear and there is no description.

**Comment by Dumbeldor** [comment]
Yes I wanted to say that

**Comment by rubenwardy** [comment]
This looks like a hack to me, you should read the description from the server list instead :-1:

**Comment by Dumbeldor** [comment]
The ip of the current server is stored in the same way. 😕 
But i'll see if it's possible to do better.

**Comment by rubenwardy** [comment]
Closed as this is a hacky fix to whatever problem it is

**Pull request closed without merging**
