### PR TITLE
Mark overloaded-virtual warning as an error

### PR DESCRIPTION
**Pull request by nerzhul**
Mark overloaded-virtual warning as an error

### CODE REVIEW

**Comment by Zeno-** [comment]
:-1: (see my IRC comments)

**Comment by nerzhul** [comment]
Fixed, flag is applied on every UNIX build if enabled

**Comment by sfan5** [comment]
:-1: http://blog.schmorp.de/2016-02-27-tidbits-for-the-love-of-god-dont-use-werror.html

**Comment by nerzhul** [comment]
Maybe we should ignore Windows builds with GCC but for UNIX it's good to fix it.
BSD kernels enable -Werror and they work fine, you should just do things right

**Comment by nerzhul** [comment]
PR changed to mark only overloaded functions as an error

**Comment by nerzhul** [comment]
Approved by @sfan5  http://irc.minetest.ru/minetest-dev/2017-01-14#i_4786970 but Windows build is broken atm

**Comment by nerzhul** [comment]
PR is now fine and show bad code on ABM inheritance

**Pull request closed without merging**
