### PR TITLE
Add configurable timestamp to console messages

### LINKED ISSUE #3716: Minetest console (F10) should have DATE/TIME:
Proposing to add date+time to the F10 in-game terminal, something like this:

```
2015-11-10 17:22:06 # *** Guest007 joined the game
2015-11-10 17:22:20 # Guest0242342: test
2015-11-10 17:22:30 # /grant singleplayer fly
2015-11-10 17:22:31 # singleplayer was grunted fly
2015-11-10 17:22:31 # /emergeblocks x y z
2015-11-11 20:34:59 # ... done emerging blocks
```

If it looks too big, date can be dropped.

Posted on forum about this earlier: https://forum.minetest.net/viewtopic.php?f=5&t=13559

### PR DESCRIPTION
**Pull request by ShadowNinja**
Closes #3716.

This also does some chat backend cleanup (to fix a bug) and getTime cleanup (so overflow won't be an issue).

### CODE REVIEW

**Comment by Fixer-007** [comment]
:+1:

**Comment by ShadowNinja** [comment]
I'll have to add a fallback to the unsafe `localtime`.

**Comment by ShadowNinja** [comment]
@Fixer-007: I've added fallbacks, try now.

**Comment by paramat** [comment]
Adding 'one approval' as the author's approval.

**Comment by ShadowNinja** [comment]
@paramat: Nope, still has an important bug, see description.
I don't know what the cause of the bug is.  I'm guessing it's something in `formatChatLine`, but it's really hard to understand what that code is doing.

**Comment by ShadowNinja** [comment]
I rewrote `formatChatLine` from scratch.  Now it works and the code is *much* simpler.

Also, I removed the `age` field from chat messages and replaced it with a monotonic `time_raw` value that doesn't have to be constantly updated.  I also switched the getTime helpers to 64-bit so that overflow won't be an issue.

**Comment by Fixer-007** [comment]
Can't compile, error: https://i.imgur.com/GbaLnWW.png

**Comment by ShadowNinja** [comment]
@Fixer-007: Fixed that, I was using a Vista function but we force the XP API.  Compiles on Windows now.

**Comment by Fixer-007** [comment]
/me, join and exit messages are tripled for some reason and F10 menu in minetest does not have timestamps that I've requested in issue #3716

**Comment by ShadowNinja** [comment]
I've fixed the server command issue.  You should see timestamps unless you have console_timestamp_format set to the empty string or your `strftime`/`localtime` is broken.

**Comment by sofar** [comment]
Tested basic functionality, works OK!

**Comment by Fixer-007** [comment]
Tested, works for me.

**Comment by Fixer-007** [comment]
Suddenly there are already CSM mods available that add data/time info into chat console. 
Is this PR still viable?

**Comment by nerzhul** [comment]
i think it can be made obsolete

**Pull request closed without merging**
