### PR TITLE
Make map_generation_limit per-world specific

### PR DESCRIPTION
**Pull request by SmallJoker**
EDIT: Successfully tested with MSVC as compiler.
EDIT2: I have no clue how to fix the unittest part.

### CODE REVIEW

**Comment by paramat** [comment]
IRC discussion http://irc.minetest.ru/minetest-dev/2016-07-19#i_4653842

**Comment by paramat** [comment]
20:02 hmmmm        map_generation_limit is implemented in a crummy manner to begin with
20:03 hmmmm        why is it so far overreaching?
20:03 hmmmm        the map_generation_limit should limit map generation.  not everything else in the entire universe.
20:04 hmmmm        instead what the guy did who implemented it first added a parameter to a fundamental function that just about everything uses to make sure objects or positions are not out-of-bounds and will cause bugs or errors
20:04 hmmmm        when in reality it should simply... limit the map generation

Indeed i've been fixing bugs caused by stuff happening on the world edge, maybe i'll look into applying what hmmmm suggests here.

**Comment by paramat** [comment]
See #5388

**Comment by paramat** [comment]
Related #1608

**Comment by paramat** [comment]
#5388 merged.

Next step is making this per-world. However there is now much less chance of bugs when changing the limit in a world.

**Comment by rubenwardy** [comment]
> Next step is making this per-world. However there is now much less chance of bugs when changing the limit in a world.

All settings should be made per world, when set using /set or minetest.setting_set imo

**Comment by paramat** [comment]
See #5440 for a new version of this PR.

**Comment by paramat** [comment]
#5440 merged.

**Pull request closed without merging**
