### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by yyt16384**
Just as the title says.

### CODE REVIEW

**Comment by nerzhul** [comment]
can you rebase and add the missing translations before review ?
thanks

**Comment by yyt16384** [comment]
that is done now :)

**Comment by yyt16384** [comment]
Closed because there are better translations in 45a77c8bf1a744edc1642d717579281cf988f8dd

**Comment by Zeno-** [comment]
@yyt16384 If there are move improvements then please, of course, make another PR. I didn't merge the other PR because I thought it was better, I just didn't realise there were two new translations for the same language. Thanks for the help and I'm sorry I didn't see this PR.

**Comment by yyt16384** [comment]
@Zeno- I think that one does it better and this is not adding much value.

**Pull request closed without merging**
