### PR TITLE
Minor adjustments now that OpenGLES 2 is the default driver on Android

### PR DESCRIPTION
**Pull request by rollerozxa**
This PR makes OpenGLES 2 the default driver on Android.

OpenGLES 2 was released in 2007, and Minetest Android has a minimum support level of API 16, which is Android 4.1 released in 2012. This means that basically all devices that can run Minetest right now should support OpenGLES 2 and can take advantage of both the slight improvement in performance and shaders.

However there might be some issues with the OGLES2 driver in its current form (Settings description alludes to this: "stick with OGLES1 if unsure! App may fail to start otherwise."). Only issue I know of personally is #12390, which I've tried to solve (but not fully fix!) by enabling shaders by default as well so the likelihood of running into it is smaller. 

On that note, this breaks OGLES1 if you don't also disable shaders as Minetest dutifully respects `enable_shaders` and tries to compile the OGLES2 shaders for it. I had the idea of hardcoding a check in settings.cpp but there's probably a better option. (or should OGLES1 be dropped entirely if OGLES2 is stable enough?)

## To do
This PR is a Work in Progress.
- Need to check whether OGLES2 causes any new issues compared to OGLES1
- Force shaders to be disabled when video driver is set to OGLES1 or drop it entirely

## How to test
📱👀

Also check so OGLES2 does not blow up in your face on your device I guess.

### CODE REVIEW

**Comment by IrrlichtMt4** [comment]
For some reason when I use Sfan5's gles build for Minetest I get an error saying: 
2021-07-05 10:32:53: ERROR[Main]: Irrlicht: Cannot initialize, extension not supported: WGL_EXT_create_context_es2_profile
2021-07-05 10:32:54: ERROR[Main]: Irrlicht: Cannot create a GL device context: No suitable format.
2021-07-05 10:32:54: ERROR[Main]: Irrlicht: Creating GLES context is impossible.

**Comment by AbduSharif** [comment]
What's your GPU and driver?

**Comment by rollerozxa** [comment]
> For some reason when I use Sfan5's gles build for Minetest I get an error saying: 2021-07-05 10:32:53: ERROR[Main]: Irrlicht: Cannot initialize, extension not supported: WGL_EXT_create_context_es2_profile 2021-07-05 10:32:54: ERROR[Main]: Irrlicht: Cannot create a GL device context: No suitable format. 2021-07-05 10:32:54: ERROR[Main]: Irrlicht: Creating GLES context is impossible.

are you even running this on a phone?

**Comment by IrrlichtMt4** [comment]
No, I'm not on phone. Also, I meant to post this issue at https://github.com/minetest/minetest/issues/12390.

**Comment by IrrlichtMt4** [comment]
Sorry, I'm a noob at tech. How do I find my CPU

**Comment by IrrlichtMt4** [comment]
I use a 64bit laptop. N

**Comment by rollerozxa** [comment]
> No, I'm not on phone.

Then this is *completely irrelevant* both to this PR and the issue you linked. OpenGLES is used primarily on mobile devices and your graphics card clearly does not support OpenGLES 2.

**Comment by IrrlichtMt4** [comment]
Thanks for information

**Comment by sfan5** [comment]
You probably want to add the following to the android manifest:
`<uses-feature android:glEsVersion="0x00020000" />`

**Comment by Zughy** [comment]
@rollerozxa is this still WIP?

**Comment by okias** [comment]
ping, can be merged?

**Comment by rollerozxa** [comment]
switch the video driver in the settings and restart.

**Comment by sfan5** [comment]
@rollerozxa can you rebase this?
ogles2 is now the default but there are other useful changes in here, plus we should change the description of `video_driver`

**Comment by rollerozxa** [comment]
yes

**Review by sfan5 — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
Tested on Android 6 (hacky-signed apk). No issues found after a proper installation.

**Pull request merged**
