### PR TITLE
Avoid drawing clipped out formspec elements

### PR DESCRIPTION
**Pull request by EvidenceBKidscode**
This PR avoid drawing formspecs elements that are outside of their clipping rect.

This is done by avoiding calling Irrlicht `IGUIElement::draw()` method to draw child element, replacing it by:
- A `draw()` method in `GUIScrollContainer`;
- A loop in `GUIFormSpecMenu::drawMenu()`;

Both of these loops over child element (like default `draw` method does) and check if their position rectangle intersects clipping rectangle.

Now we have `GUIScrollContainer`, it is possible to have huge containers (with complex children) with only a small part displayed. Drawing all hidden stuff could cause some FPS drops.

## To do

Ready for Review.

## How to test

1 - Formspecs should be displayed correctly (no change);
2 - Big scroll containers should induce much less FPS drop;

### CODE REVIEW

**Comment by Desour** [comment]
Not clipped elements still need to be drawn, even if their clipping rect is outside of the guiformspecmenu rect.

:+1: however for the change at scroll container. Not-clipped elements inside scroll-containers make no sense. But it should be documented in `lua_api.txt` that children of scroll containers can not be not-clipped.

**Comment by pyrollo** [comment]
I'm sorry, I dont understand why. If I'm right, draw() methods always end ups in clipping drawn stuff into the absolute clipping rect. This pr avoid useless draw() calls.

The only reason I see for not avoiding calling draw() is if it ever does something else than drawing. But that would be a design mistake.

**Comment by Desour** [comment]
Minetest supports making elements not-clipped.
Eg. for checkboxes:
https://github.com/minetest/minetest/blob/b9f618746c0f673ea1f851bb2473fb3ca9410093/src/gui/guiFormSpecMenu.cpp#L628

See http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_element.html#a814d322989acafa74c895e5c13908b86:
>Sets whether the element will ignore its parent's clipping rectangle.

Those elements aren't clipped away.

This formspec might be suitable for testing (I didn't test):
```
formspec_version[3]
size[1,1]
style[chkbx;noclip=true]
checkbox[0,-1;chkbx;Foo;false]
```

I wish this feature wouldn't exist.

**Comment by pyrollo** [comment]
Ok I'll simply include noclip gui elements then.

**Comment by pyrollo** [comment]
Test on "noclip" added. If an element is styled as "noclip" it is drawn when outside of its formspec or scroll_container.

**Comment by pyrollo** [comment]
> Test on "noclip" added. If an element is styled as "noclip" it is drawn when outside of its formspec or scroll_container.

Actually done now (did something wrong previously, did not push any change).

**Comment by Desour** [comment]
:thinking: Is it even necessary to use `isRectCollided`? You could use `getAbsoluteClippingRect`, afaik these rects will be of size 0 iff they are clipped away.

Anyway, PR still looks fine. :+1:

**Review by SmallJoker — APPROVED** [review]
LGTM

**Comment by paramat** [comment]
As pyrollo is now a core dev, this can be merged.

**Pull request merged**
