### PR TITLE
Fix updateFastFaceRow tiling issue

### PR DESCRIPTION
**Pull request by SmallJoker**
Pull request for #4091

### CODE REVIEW

**Comment by paramat** [comment]
Good to see someone finally made a PR for this. Have you checked it by making the mesh tiles visible?

**Comment by SmallJoker** [comment]
No, I haven't checked it but obneq already did that in the issue.

**Comment by paramat** [comment]
@Zeno- and kwolekr seem to approve of this in #4091 , let's wait until they re-approve this PR.

**Comment by Zeno-** [comment]
+1

**Comment by paramat** [comment]
:+1: from hmmmm / kwolekr https://github.com/minetest/minetest/issues/4091#issuecomment-225943570

**Comment by paramat** [comment]
@SmallJoker please can you test this? i wouldn't dare merge this without it being tested first, so i was going to test it but decided to ask you to do so :) Please apply the line specified to make tiles visible, then apply this patch to check it works ok. Then i'll merge it.

**Comment by Fixer-007** [comment]
I tested this for 1 hour or so of game time, have not found any issues so far.

**Comment by paramat** [comment]
Ok i'll merge it then.

**Comment by paramat** [comment]
@SmallJoker Seems to cause segfault, i should have insisted you test.

**Comment by paramat** [comment]
Tested with wireframe graphics and confirmed long rows of tiled nodes.

**Pull request closed without merging**
