### PR TITLE
Allow selecting screenshot format.

### PR DESCRIPTION
**Pull request by kaeza**
Due to git[hub] fuckup, new version of #3825. Sorry about that.

### CODE REVIEW

**Comment by kilbith** [comment]
An acronym is always uppercase'd (i.e. `png` -> `PNG`).

**Comment by rubenwardy** [comment]
It's a file extension

**Comment by sofar** [comment]
default jpg quality is ```0```. Which is default. But is 255 best, or is 1 best? -> document.

**Comment by kaeza** [comment]
Changed quality setting to more common 1-100 range.

@sofar Partly addressed your issue. Documented 1=worst, 100=best, I have no idea what 0 really means; it's what Irrlicht uses as default parameter value. Feel free to review libjpeg and suggest an alternative description, and while you're at it, please also document exactly what "worst" and "best" means.

**Comment by kaeza** [comment]
Bump. I'd like this to be merged before release.

@ShadowNinja and @sfan5 can you give explicit :+1:?

**Comment by sfan5** [comment]
:+1:

**Comment by ShadowNinja** [comment]
2c72f6da7b7595d2e180937f05f902c510ef1c14

**Pull request closed without merging**
