### PR TITLE
Mick/rename python to minetest gymnasium

### PR DESCRIPTION
**Pull request by mickvangelderen**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
- How does the PR work?
- Does it resolve any reported issue?
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
- If not a bug fix, why is this PR needed? What usecases does it solve?

## To do

This PR is a Work in Progress / Ready for Review.

- [ ] List
- [ ] Things
- [ ] To do

### CODE REVIEW

**Comment by rubenwardy** [comment]
Please disassociate Astera-org from being a GitHub fork of Minetest/Minetest. You can do this by filing a support ticket with GitHub. Once is an accident. Many times is just bad process

If you don't, we may ban you from the Minetest org, to block you from opening pull requests here

**Comment by mickvangelderen** [comment]
I am equally annoyed. No need to threaten me immediately.

**Comment by SmallJoker** [comment]
Another approach would be to convert the fork into a separate repository. Both git trees will stay compatible due to sharing the same base.  For that, it seems that you'd have to contact the GitHub support: https://stackoverflow.com/a/16052845

**Comment by mickvangelderen** [comment]
We were able to disassociate the fork through a support ticket.

**Pull request closed without merging**
