### PR TITLE
Update to Lua 5.2

### PR DESCRIPTION
**Pull request by ShadowNinja**

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Rebased.

**Comment by ShadowNinja** [comment]
As of 2015-1-12 Lua 5.3 is out, making this outdated.

Maybe I'll update this, but I'd like to see more interest from the core developers before I waste my time on something that'll be ignored.

Also, 5.1 is about nine years old now.

**Comment by HybridDog** [comment]
Is there interest in this, too?
http://terralang.org/

**Comment by kilbith** [comment]
@ShadowNinja : just from point of interest... you intend to upgrade to Lua 5.3 ?

**Comment by ShadowNinja** [comment]
@kilbith I don't intend to update this unless it's actually likely to get merged.  I don't remember hearing any good reasons not to merge this, but I remember being told "no" by a few people.

**Comment by nerzhul** [comment]
I agree with upgrading to last stable Lua version. If this break some things, dev-0.5 is here for that, 0.5 series can break some things, and we must inform our users.
What are the improvements for Lua 5.2 and 5.3 ?

**Comment by Zeno-** [comment]
I think the major concern is *potential* problems or subtle differences between Lua and LuaJIT, which *may* (or may not) cause differences between mods running under Lua and those that under LuaJIT.

The question is: Do the advantages of upgrading Lua outweigh the potential disadvantages?

**Comment by HybridDog** [comment]
l still want this http://terralang.org/

**Comment by SoniEx2** [comment]
Why not both? (use dlmopen() on linux, screw windows and BSD (osx))

**Comment by est31** [comment]
So, the problem is that the language spec is getting more and more updates, and the slow reference implementation too, but there isn't any performant implementation that's actively being developed. LuaJIT's last update has been one year ago. So either we wait until LuaJIT developers make proper 5.2 (and, one day, 5.3) support, or we implement scripting with better maintained scripting engines like V8.

**Comment by ShadowNinja** [comment]
@nerzhul: Here's some of the main features: http://www.lua.org/versions.html
@SoniEx2 also suggests that it's faster, although it probably depends on what you're doing.

@Zeno-: LuaJIT doesn't implement all of 5.2's features, but it implements most of them, and it implements at least one 5.3 feature (`string.dump` `strip` argument).

@HybridDog: Please open a separate issue for that.

@est31: Adding Support for other languages seems O.K., but it won't be easy.  Implementing even a fraction of the Lua API for another language will take a long time and a lot of code.

**Comment by HybridDog** [comment]
> Please open a separate issue for that.

But l recently changed my opinion. l don't want it so much, but only a bit.

**Comment by kwolekr** [comment]
According to the Lua mailing list, there won't be 5.2 compatibility for LuaJIT: http://lua-users.org/lists/lua-l/2012-01/msg00787.html

"(Do not hold out for a fully 5.2-compatible version of LuaJIT, if you are thinking of it. Mike Pall has made it clear that he dislikes and disagrees with many of the choices made by the Lua team for this version, and has no intention of moving away from a primarily 5.1-based LuaJIT.)"

I would argue that LuaJIT compatibility is more important than plain Lua since that's the implementation most use.  The whole selling point of LuaJIT is that it works as a drop-in replacement for Lua (and vice versa).
Most distros distribute 5.1, so there's yet another reason to not update.

**Comment by est31** [comment]
Every release of lua is basically a new language. They don't care at all about backwards compatibility.

**Comment by MirceaKitsune** [comment]
I think it needs to be pointed out that Lua 5.1 won't be around forever, like any software that receives updates. Even if Lua breaks compatibility (which I totally disagree with), support for future versions should certainly not be dropped, in my opinion. I hope someone finds another way to do this soon.

**Comment by asiekierka** [comment]
They partially do, they partially don't. Since LuaJIT's author announced he hates 5.3 despite it introducing some highly beneficial changes, you should probably choose Lua or LuaJIT, *not* both.

**Comment by est31** [comment]
We can't have pure lua, because of performance, and we can't have pure luajit, because we need to be abled to do valgrind.

**Comment by asiekierka** [comment]
Time to move away from Lua, then. The two languages have pretty much forked away from each other. :)

**Comment by est31** [comment]
As I said, we need lua for valgrind. Luajit just simply doesnt work with it, and valgrind is needed, sometimes.

**Comment by MirceaKitsune** [comment]
I guess we can simply go with the highest Lua version that has both (normal Lua plus Luajit).

In all honesty however, I think the Luajit people are being unreliable. Refusing to update to the latest Lua version because "the admin doesn't like it" is very dumb. There might be users who need Luajit for 5.2 or 5.3, and run into issues with their software because someone doesn't like the latest Lua update. It might be questionable whether sticking to Luajit over pure Lua remains an option considering this.

**Comment by est31** [comment]
Agree to the first sentence.

To the second paragraph: unless I'm wrong. Luajit has only one developer. If that one doesn't like the language, we have lost. I think that not many people will agree with you that some syntactic sugar improvements (or basically any language change) are worth the performance decrease that dropping lua will mean. The luajit developer still maintains his branch.

**Comment by MirceaKitsune** [comment]
@est31 I thought Luajit is run by some sort of team. Depending on a product that a single developer, which is probably not part of Minetest either, maintains and updates... personally I don't see this working out in the long run. Maybe one day that developer will just walk away and Luajit dies... Minetest goes on, it can't stay on a deprecated product for years.

What could perhaps work, if it's an effort the Minetest team can afford and licenses allow it, would be including our own fork of Luajit with Minetest. That way we can keep it updated with latest Lua, and even make any changes we want. Question is if it's something the Minetest team can maintain long term.

**Comment by nerzhul** [comment]
@MirceaKitsune i agree with your point of view. I don't think we have time to maintain LuaJit ourselves.
The better choice is for a developper to upgrade our Lua implementation on a separate branch and we do a benchmark.

**Comment by est31** [comment]
I wonder, @MirceaKitsune what feature of lua > 5.1 is so important that you need?

**Comment by MirceaKitsune** [comment]
@nerzhul Personally, I can't say I see a huge need for Luajit at this moment. I use Minetest with normal Lua, since I couldn't find Luajit in the openSUSE repositories. Some scripts in mods, typically those with a lot of loops or that use expensive minetest.* functions, will indeed freeze the server for even a few seconds... which obviously is not something we want. Still, I wonder if there might be other ways to improve script performance as well... such as a builtin Minetest function to pre-compile some functionality at server startup.

@est31 To be honest, I don't even know what features Lua > 5.1 adds. The only problem is staying up to date with the latest software, which is still maintained by its developers and receives other optimizations. I simply wouldn't want to see Minetest in a situation where 5 years from now, when there will probably be Lua 6.* and Lua 5.* might not even be distributed in Linux distros any more, Minetest still has Lua 5.1 because Luajit didn't update.

**Comment by est31** [comment]
@MirceaKitsune luajit is still [receiving](http://repo.or.cz/w/luajit-2.0.git/shortlog) "other optimisations", with the last release being one month ago.

**Comment by SoniEx2** [comment]
@nerzhul Lua 5.2 brings some performance improvements over Lua 5.1.

@MirceaKitsune LuaJIT is only fast if you use the FFI, otherwise most code gets blacklisted for JITting. This means that for best LuaJIT performance, Minetest would have to provide a C API, and bind to it with Lua/FFI code.

**Comment by est31** [comment]
LuaJIT also has an assembler-writen interpreter for the non JIT case. Here, luaJIT is still 2x to 4x faster than plain old lua.

**Comment by SoniEx2** [comment]
2x to 4x is still pretty slow compared to JITted code.

**Comment by est31** [comment]
If we do FFI, we basically have to support a completely new scripting engine. Then we might also perhaps look for languages which are better supported by engines.

**Comment by SoniEx2** [comment]
No, you just have to support a C API.

The Lua API can stay the same, as long as you write the glue code in Lua. (if it isn't already)

**Comment by SoniEx2** [comment]
Maybe this would be more interesting? http://the-ravi-programming-language.readthedocs.org/en/latest/ravi-overview.html

**Comment by est31** [comment]
Sounds very good. But adding a C API isn't a matter of hours, and many devs are very conservative about this. But using LLVM is a very wise choice. Ravi is a quite young project though, and whether its supported or not is even more insecure.

**Comment by SoniEx2** [comment]
If it's a C API it doesn't have to be "safe". Make it so the API client has to do most validation (as it should). Split Lua from the core so we can add Python and Rust.

I don't get why Minetest chose to limit itself to Lua... It's quite sad.

**Comment by est31** [comment]
I'm heavily against python, and rust's compiler needs much improvement.

**Comment by SoniEx2** [comment]
I'm heavily against limiting the end-user against their own will. Kinda makes you sound like a proprietary software advocate...

**Comment by est31** [comment]
Please, lets go to IRC. You know how to connect to freenode #minetest-dev?

Python is intended as learner language, but apart from hello world it does everything wrong. Just too many broken concepts mangled together (and the non-broken ones were broken!). And I very much like rust, but (apart from the compiler problem) having one single language makes it easier to talk about code, maintain it, share it, and write examples. "You use the ruby or the clojure API? > No I use the go API > Then I can't help, sorry" "Can you give me an example for how to add a node with javascript? I've only found a nim example". We should follow the KISS principle here, and make modding as easy as possible, not be a slave of language hippies who want to use their newest pet language for everything they touch.

But ravi should be given definitely a second look. Perhaps in 5 years (or earlier) we can judge whether to switch.

Also, we don't dictate anything, minetest is open source, you can do with the code everything the LGPL allows, including writing your very own language support, as user.

Can you point to an example with the FFI stuff in action?

**Comment by SoniEx2** [comment]
LuaJIT currently doesn't JIT the io lib. Here's Lua 5.2's io lib ported to LuaJIT, using FFI: https://gist.github.com/SoniEx2/78d81eea571fcd2c84d7 (The port is currently incomplete, but it's pretty damn good)

**Comment by est31** [comment]
From what I see with that is that it uses the same API as minetest. The lua and c parts are somehow intermangled, but that's not the issue, is it?

**Comment by SoniEx2** [comment]
I simply ported Lua 5.2's C code to use Lua and LJ's FFI, doing some small tweaks for performance. The fact that LuaJIT can "see" that code means it can optimize it up to the FFI calls (which I tried to avoid), so instead of having a loop, the JITted code might just do a direct FFI call.

**Pull request closed without merging**
