### PR TITLE
Making details more visible in logo

### PR DESCRIPTION
**Pull request by MrRar**
I added an overlay gradient and raised the contrast of the logo.

minetest
corresponding PR: https://github.com/minetest/minetest_game/pull/1720

### CODE REVIEW

**Comment by paramat** [comment]
:-1: Bevel on left edge is too wide and overall it does not look right. Also (see MTG PR) i want to redo these myself.

**Comment by MrRar** [comment]
@paramat well then do it. I don't care who does it, I just think something should be done.

**Comment by paramat** [comment]
Yes i will add more bevel shading.

**Comment by paramat** [comment]
The MTG PR was disapproved so closing.

**Pull request closed without merging**
