### PR TITLE
Revert 60dc01d

### PR DESCRIPTION
**Pull request by zhangjunphy**
Basically this pr reverts https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c, then changes the variable `d` in the last few lines of `collisionMoveSimple()` to `COLL_ZERO`. 
This should not introduce the side effects in https://github.com/minetest/minetest/issues/3767 and https://github.com/minetest/minetest/issues/3773.

### CODE REVIEW

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
Thanks for this, much appreciated, however we would like the revert to be done first, and then consider fixes later. Please can you edit this PR to be revert-only, then open a new PR for your fix?

**Comment by zhangjunphy** [comment]
The commit is edited to revert 60dc01d only.

**Comment by zhangjunphy** [comment]
The commit is edited to revert 60dc01d only.

**Comment by ShadowNinja** [comment]
@zhangjunphy: So this doesn't actually fix edge jumping anymore?

**Comment by zhangjunphy** [comment]
@ShadowNinja No, as @paramat requested this only reverts 60dc01d now.

**Comment by kilbith** [comment]
There are things that wasn't in https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c. This is not a proper revert :-1:

Reverting is done in 2 short commands and is the job of a core-dev.

**Pull request closed without merging**
