### PR TITLE
Shaders: fix fog not affecting opaque liquids

### PR DESCRIPTION
**Pull request by RealBadAngel**
Fix for #3757

### CODE REVIEW

**Comment by Fixer-007** [comment]
Will test today.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Approval from Est31 http://irc.minetest.ru/minetest-dev/2016-02-23#i_4543058

**Comment by paramat** [comment]
e8a3d22cbef3aa2764c1ad217585667276df8c80

**Pull request closed without merging**
