### PR TITLE
Revert 24e8b0a

### PR DESCRIPTION
**Pull request by ghost**
This PR revert #3448.
See: #3823

### CODE REVIEW

**Comment by est31** [comment]
Ermm, why?

**Comment by Rui914** [comment]
kilbith said:
>On non-critical code you need readability and ease of maintenance more than a micro-optimization.

**Comment by est31** [comment]
That's @kilbith 's opinion, he voiced it but we still merged the PR.

For me, `table.insert(settings, {` is as equally readable as `settings[#settings + 1] = {`.

**Comment by est31** [comment]
Ah we didn't merge it.... well, still there is no need to revert it, its not that bad IMO.

**Comment by Rui914** [comment]
Should I re-open #3823?

**Comment by est31** [comment]
No, no need for it.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/pull/3448/files#diff-7b4242351dd3cf5b2a70c8aa9d12149bL470

Not much verbose, eh ?

**Comment by est31** [comment]
Well if this PR finds two core devs who +1 it, it can go in. But i won't +1 it.

**Comment by paramat** [comment]
:-1: No need to revert, the new code is fine.

**Comment by nerzhul** [comment]
:-1:

**Comment by 0-afflatus** [comment]
A little more explanation in the OP would save some of us the trouble of trying to understand issues that are really of no concern to us.

**Pull request closed without merging**
