### PR TITLE
Update guiFormSpecMenu.cpp to use title if the item has metadata

### PR DESCRIPTION
**Pull request by mtango688**
This changes the tooltip in drawList() so that it gives you the title found in metadata rather the description of the item.

On the plus side, this seems to work already with written books. On the minus side, there may be some issues with this I haven't thought of.

### CODE REVIEW

**Comment by sofar** [comment]
No

This isn't the proper solution. We've been here already and custom designing a deserializer isn't going to do us any good. The proper way is being worked on in #3984

**Comment by mtango688** [comment]
As the author of this PR, I completely agree. That said, what do you think of the idea behind this? Good, right?

**Comment by sofar** [comment]
I wrote the same thing in #3449

**Comment by mtango688** [comment]
FWIW, I've fixed a little goof on my part. If https://github.com/minetest/minetest/pull/3984 gets merged, I wouldn't mind closing this PR.

**Comment by mtango688** [comment]
I think closing this is the right decision, considering that meta is likely to be taken from JSON rather than a string, at some point.

**Pull request closed without merging**
