### PR TITLE
Reset override material in anaglyph

### LINKED ISSUE #11437: `3d_mode = anaglyph` is broken
##### Minetest version

```
Minetest 5.5.0-dev-e9bc59e (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu 20.04.2 LTS
CPU: Intel® Celeron(R) N4100 CPU @ 1.10GHz × 4 

GPU model: Mesa Intel® UHD Graphics 600 (GLK 2)
OpenGL version: 4.6

##### Summary
Switching 3d_mode setting to something different than "none" lead into a weird image.
Re switching 3d_mode to "none" needs a restart to get the normal image

See the video for more details.
https://youtu.be/V24gQRaigqY

##### Steps to reproduce
Switch 3d_mode to something different than "none"

### PR DESCRIPTION
**Pull request by x2048**
Fixes #11437 

## To do

This PR is Ready for Review.

## How to test

* Enable 3d mode = anaglyph
* Put your red-blue glasses on
* Start a world
* Enjoy the 3d game - no black (or white) textures

### CODE REVIEW

**Comment by x2048** [comment]
@AFCMS Would you be able to check if this fix works for you?

**Comment by AFCMS** [comment]
I will try to review soon (too busy right now)

**Review by sfan5 — APPROVED** [review]
Works.

**Comment by x2048** [comment]
Adding to 5.5.0?

**Pull request merged**
