### PR TITLE
Mapgen: Add flat mapgen

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20151031_002818

In hidden form.
See details of development below.

### CODE REVIEW

**Comment by kwolekr** [comment]
Looks good but, why the separate CaveFlat?

**Comment by paramat** [comment]
I wasn't aware we could re-use an existing cavegen, if so this could possibly use the cavefractal cavegen.

**Comment by BlockMen** [comment]
> The mg_flag 'trees' decides whether decorations are placed.

Sounds like an abuse. Why not adding a new flag ```decorations``` ?

**Comment by kwolekr** [comment]
Yes, you can reuse a Caves implementation from another mapgen.
The reason why there is a split in the first place is because I wanted to further develop (and change the output of) that same implementation for V7.  So, the original implementation remains CavesV6 and CavesV7 is the version that could be freely modified without concern with backward compatibility.

If CavesV5 is the same, functionality-wise, as CavesV7, you can merge the two together.

**Comment by paramat** [comment]
CaveV5, CaveFractal and CaveFlat are identical.

Yes i'd prefer to rename the 'trees' mgflag to 'decorations', just thinking about compatibility.
Perhaps the mgv6 trees flag should become an mgv6 spflag.

**Comment by BlockMen** [comment]
@paramat sounds good and compatiblity could be kept aswell when setting the flags corresponding to mapgen that is used.

mgv6: mgflag ```tree``` -> mgv6 spflag ```tree``` 
every other mapgen: mgflag ```tree``` ->  mgflag ```decorations```

**Comment by paramat** [comment]
Much of this flag stuff will have to be another commit, but i can edit this commit to be ready for the new decoration global flag, mgflat is after all hidden.

**Comment by paramat** [comment]
In trying to access cavefractal from mgflat, i'm using:

		CaveFractal cave(this, &ps);
		cave.makeCave(node_min, node_max, max_stone_y);

And get errors:

/minetest/src/mapgen_flat.cpp: In member function ‘void MapgenFlat::generateCaves(irr::s16)’:
/minetest/src/mapgen_flat.cpp:520:29: error: no matching function for call to ‘CaveFractal::CaveFractal(MapgenFlat* const, PseudoRandom*)’
   CaveFractal cave(this, &ps);
                             ^
/minetest/src/mapgen_flat.cpp:520:29: note: candidates are:
In file included from /minetest/src/mapgen_flat.cpp:35:0:
/minetest/src/cavegen.h:207:2: note: CaveFractal::CaveFractal(MapgenFractal*, PseudoRandom*)
  CaveFractal(MapgenFractal *mg, PseudoRandom *ps);
  ^
/minetest/src/cavegen.h:207:2: note:   no known conversion for argument 1 from ‘MapgenFlat* const’ to ‘MapgenFractal*’
/minetest/src/cavegen.h:206:2: note: CaveFractal::CaveFractal()
  CaveFractal() {}
  ^
/minetest/src/cavegen.h:206:2: note:   candidate expects 0 arguments, 2 provided
/minetest/src/cavegen.h:168:7: note: CaveFractal::CaveFractal(const CaveFractal&)
 class CaveFractal {
       ^
/minetest/src/cavegen.h:168:7: note:   candidate expects 1 argument, 2 provided

**Comment by ShadowNinja** [comment]
Doesn't MVv6 have a `flat` flag for this?  That's what my server uses.

**Comment by C1ffisme** [comment]
Here's what I think.

Flat worlds look too flat for realism. But they are good for building that. Saying that, why not make this "semi-flat" where elevation still exists, but it's a LOT more spread out, like 10 nodes before the elevation gets any higher. If you absolutely need true flatness, you can use the ```flat``` flag.

**Comment by rubenwardy** [comment]
That's completely irrelevant, c1ffisme to this pull - we're making a flat mapgen not a semi flat mapgen - and you can just modify the map gen noise parameters to make semi flat.

**Comment by paramat** [comment]
> Doesn't MGv6 have a flat flag for this?

Yes but the biomes, tree designs and caves are different in mgv6, and the biome API unusable in mgv6.
The flat flag doesn't have effect in mgv5/v7/fractal, it would be messy to make those able to become flat, better to have a separate simple biome API flat mapgen. The biome API then allows you to choose the layers of materials used.

> "semi-flat"

I did consider an option to add lakes, to make a world of flat continents / islands, it would just need a single 2D noise.At least then there would be some water around to provide all resources and make the world more playable.

**Comment by C1ffisme** [comment]
> and you can just modify the map gen noise parameters to make semi flat.

Uh-huh. I'm sure those math geniuses who come from school with frowns and a D- on their test will just love to hear that. Do you even know how hard just using noise parameters for ```minetest.register_decoration``` is??

**Comment by rubenwardy** [comment]
much_harder

Turns out that it was harder than I thought it would be. But it should still be possible. My point is that there's no need for a completely new mapgen, just a setting or open in select map gen.

**Comment by paramat** [comment]
Yes it is possible to make existing mapgens semi-flat, but this needs some knowledge of noise use.

**Comment by paramat** [comment]
Can anyone help with my error above? I spent several hours trying to solve it but i suspect this may be beyond my limited c++ programming capabilities.

**Comment by PilzAdam** [comment]
@paramat change the type of the first parameter of the CaveFractal constructor to a pointer to the common parent class of MapgenFlat and MapgenFractal, i.e. Mapgen.

**Comment by paramat** [comment]
Thanks!

**Comment by paramat** [comment]
screenshot_20151102_013241

Optional simple lakes, to add sand, clay, papyrus, waterlilies etc. to a flat world and make it more playable.

**Comment by paramat** [comment]
@PilzAdam close, but now i get errors of this type:

/minetest/src/cavegen.cpp: In constructor ‘CaveV5::CaveV5(Mapgen*, PseudoRandom*)’:
/minetest/src/cavegen.cpp:42:29: error: ‘class Mapgen’ has no member named ‘c_water_source’
  this->c_water_source = mg->c_water_source;
                             ^
/minetest/src/cavegen.cpp: In member function ‘void CaveV5::makeTunnel(bool)’:
/minetest/src/cavegen.cpp:153:40: error: ‘class Mapgen’ has no member named ‘ystride’
   u32 index = (p.Z - node_min.Z) * mg->ystride + (p.X - node_min.X);
                                        ^

It cannot access content ids or ystride of class MapgenFractal.

**Comment by C1ffisme** [comment]
That actually looks really cool. It's not too bad even if it is very flat. :+1:

**Comment by kwolekr** [comment]
Looks good and all, but shouldn't the documentation be updated to reflect this new mapgen?

**Comment by paramat** [comment]
It should yes, i'll label this as a WIP.

**Comment by paramat** [comment]
screenshot_20151107_073043

Added optional hills as well, now you can have flat buildable land between hills and lakes.
The lake and hill noise thresholds are settable to control the relative area taken up by each.
The steepness of the lake and hill slopes are also settable, therefore controlling lake depth and hill height.

**Comment by paramat** [comment]
Build fails but branch compiles fine locally @nerzhul 

make[2]: Leaving directory `/usr/local/jenkins/workspace/minetest-Android-OfficialRepository/build/android'
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/local/openjdk8/bin/java
Makefile:788: recipe for target 'apk' failed
make[1]: *** [apk] Error 1
make[1]: Leaving directory '/usr/local/jenkins/workspace/minetest-Android-OfficialRepository/build/android'
Makefile:175: recipe for target 'debug' failed
make: *** [debug] Error 2
Build step 'Execute shell' marked build as failure

**Comment by paramat** [comment]
PilzAdam's advice helped a little but i still can't make this mapgen use an existing cavegen.
The problem being that some content ids and ystride are not members of class Mapgen.

**Comment by PilzAdam** [comment]
@paramat either move these members to the parent class, or cast the pointer type in the cavegen.

**Comment by paramat** [comment]
Thanks, i don't much understand pointers but will see what i can do.

**Comment by RHRhino** [comment]
The flat mapgen + hills screenshot looks great! :+1:
 I'm looking forward to build my stuff on that mapgen! :smile:

**Comment by paramat** [comment]
Thanks PilzAdam i possibly have the cave stuff working now.

**Comment by paramat** [comment]
screenshot_20151109_060633

Now successfully uses mgv5 cavegen.

**Comment by celeron55** [comment]
When will this be made not hidden? Is there some kind of a plan?

**Comment by kilbith** [comment]
> From the user's standpoint, hidden mapgens are as good as none.

Agreed. An user would extensively use the flat mapgen as primary environment for building cities (this is what Minecraft provides already).

**Comment by paramat** [comment]
There are some changes to mapgen flags coming, this mapgen needs a new global flag for decorations to make them optional. So i was planning to merge this, then make the flags changes in separate commits, then unhide mgflat after that.

**Comment by paramat** [comment]
76c9abe4c89f6c8170b82558182837259efdd2ea

**Pull request closed without merging**
