### PR TITLE
Add a `on_try_to_interact` callback

### PR DESCRIPTION
**Pull request by Thomas--S**
* Called when a player tries to interact without the interact privilege
* May be triggered very often in a short time span
* Useful e.g. to display a form where the player has to agree to the rules.

### CODE REVIEW

**Comment by Ferk** [comment]
Maybe a client-side (CSM) ``on_missing_priviledge(priv)`` would be another option and it wouldn't matter how often it's called.
Too bad sending client-side lua from the server is still not implemented.

**Comment by Thomas--S** [comment]
I think a CSM `on_missing_privilege(priv)` is a good idea, but not as an alternative for this PR, but as an additional feature. Usually, the server-side one would be used for different things than the CSM one.

**Comment by sfan5** [comment]
I dislike all the indentation changes

**Comment by Thomas--S** [comment]
@sfan5: Actually, I only wanted to indent it one more level because it is now wrapped in one more if clause. I think I didn't else regarding the indentation. However, I'll check again soon, if my IDE betrayed me.

**Comment by sofar** [comment]
CSM does not know anything about privileges.

**Comment by sofar** [comment]
I strongly dislike the implementation, and I think it is not needed.

instead, you could just properly handle the formspec and kick the player if they `escape` out of it, and use a timer to make sure that they actually complete the form within an allotted time frame. You could also track movement (which isn't possible if a formspec is open) and kick there.

**Comment by Thomas--S** [comment]
Actually, I also think that this is maybe not the best implementation.

I think I will close this PR tomorrow if there are no objections.

If there is a need for such a feature at a later point in time, maybe there is a better way to implement it?

**Pull request closed without merging**
