### PR TITLE
Menu docs: clarify that images must be escaped to correctly render on Windows

### PR DESCRIPTION
**Pull request by Zughy**
I was pretty confused when a main menu of mine was rendering basically nothing on Windows, whilst perfectly displaying every picture on Linux. It took me a while to understand why, as I never use Windows ("understand" meaning "browsing MT main menu code after frustrating trial and errors")

## To do

This PR is Ready for Review.

## How to test
:eye:

### CODE REVIEW

**Comment by appgurueu** [comment]
*All* strings must be escaped in formspecs, otherwise they may be interpreted as formspec code. In this case, `\` is itself interpreted as an escape character, and needs to be escaped to be treated as a literal backslash.

This is just one of many possible consequences of missing formspec escaping. Other possible issues are e.g. with semicolons or commata (which may cause subsequent text to be treated as subsequent parameters). Another recent example is https://github.com/minetest/minetest/pull/15064, which is about square brackets.

Ultimately I feel this doc change is thus a bit narrow: It basically prominently mentions just one example of what can go wrong when you forget to escape (and creates a bit of a false impression that this is somehow unique to Windows or images). This might still be a good idea as an example of what can go wrong, but ultimately I think we need a big fat warning that tells modders to *always* think about "formspec injection" when putting strings inside formspecs.

**Comment by Zughy** [comment]
> It basically prominently mentions just one example of what can go wrong when you forget to escape

True, but if you work with main menus, you're gonna stumble upon it 100%, because you do need images and you do need to use `DIR_DELIM` to navigate through folders. This is not true for normal formspec development, where escape characters are way harder to encounter, as you don't need to specify any path to load an image

> but ultimately I think we need a big fat warning that tells modders to always think about "formspec injection" when putting strings inside formspecs

I can expand the section, calling it something like "Before starting: formspec escape", explaining why it's important and providing the current image example. Something similar could be placed in the `lua_api.md` file, or simply link to the main menu docs. Right now `lua_api.md` only says  

"When displaying text which can contain formspec code, e.g. text set by a player, use minetest.formspec_escape"  

which is surely not enough

**Comment by appgurueu** [comment]
> I can expand the section, calling it something like "Before starting: formspec escape", explaining why it's important and providing the current image example.

Sounds good to me. What's most important to me is just that users don't get a false impression that this problem is somehow unique to images or Windows.

**Review by sfan5 — APPROVED** [review]
given this is the menu docs, it is okay.

**Comment by Zughy** [comment]
@appgurueu after attempting a better wording, the more I try the more it gets complicated. Like, you shouldn't sanitize *every* string. If a string is just a random number, for instance, there's no need to sanitize it. I've simply expanded the title to "Image and 3D models".  

I've also documented `DIR_DELIM`, in case @sfan5 wants to have a look at it again

**Pull request merged**
