### PR TITLE
Schematics: Add core.place_schematic_on_vmanip API

### PR DESCRIPTION
**Pull request by kwolekr**
This commit adds a new API function minetest.place_schematic_on_vmanip(), which does... exactly what it says it does.
Also, fix a memory leak in minetest.place_schematic() and slightly refactor some Schematic code

### CODE REVIEW

**Comment by paramat** [comment]
Rotation 'random' doesn't work.
In docs 'minetest.' is missng from before 'place_schematic_on_vmanip()'
Otherwise it works.

**Comment by paramat** [comment]
:+1: When those are fixed.

**Comment by kwolekr** [comment]
Oops, great catch on the (L, 6).

**Comment by paramat** [comment]
I guess this can be used with the non-mapgen-object vm too?

**Comment by kwolekr** [comment]
Yes, either-or.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/1384108f8c32f309852c1d1665a613f2a3e3fcc2

**Comment by paramat** [comment]
@kwolekr yes the documentation is okay as it is, it's consistent with the other documentation in being concise :+1:

**Pull request closed without merging**
