### PR TITLE
Update Spanish translations

### PR DESCRIPTION
**Pull request by ngosang**
Updated Spanish translations

### CODE REVIEW

**Comment by ngosang** [comment]
Do not merge until that #2313.

**Comment by ShadowNinja** [comment]
Update the PO file only for the translation you're making, otherwise it breaks all tye other translation PRs.

**Comment by ngosang** [comment]
Ok, now It's just for Spanish language.

**Comment by nerzhul** [comment]
Is this ok @ShadowNinja ? Can i merge?

**Comment by ShadowNinja** [comment]
@nerzhul Yes, seems fine now.

**Comment by nerzhul** [comment]
Merged, commit 5eb0eda626942882fa9ac4e040da51c644a2bbbd, thanks.

**Pull request closed without merging**
