### PR TITLE
Faster insertion into table

### PR DESCRIPTION
**Pull request by Rui914**
https://github.com/minetest/minetest_game/pull/732

```
-- table.insert
local time1 = os.clock()
local testtable1 = {}
for i = 1, 1000 do
	table.insert(testtable1, i)
end
print(os.clock()-time1)

-- tbl[#tbl+1]
local time2 = os.clock()
local testtable2 = {}
for i = 1, 1000 do
	testtable2[#testtable2+1] = i
end
print(os.clock()-time2)
```

table.insert :```0.00020699999999996```
tbl[#tbl+1] :```0.00011100000000003```

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by PenguinDad** [comment]
:+1:

**Comment by PilzAdam** [comment]
What about Lua vs. LuaJIT? Is it better for both?

Also you probably shouldn't waste your time optimizing not performance critical code.

**Comment by ShadowNinja** [comment]
My timings (with iterations multiplied by 1000 for better sample size):
```
Lua 5.3.2:
0.266029
0.16961
LuaJIT 2.0.4:
0.141926
0.126934
```

**Comment by est31** [comment]
We don't use 5.3 we use 5.1.

**Comment by ShadowNinja** [comment]
@est31: Yes, but I don't have Lua 5.1 installed, I'd have to turn the script into a mod and run it through Minetest by starting a world.

**Comment by sapier** [comment]
doesn't seem to cause side effects on non indexed (key based) tables too

**Comment by sapier** [comment]
come on guys this is a minor change can those denying it please explain why?

**Comment by est31** [comment]
From reading http://www.lua.org/manual/5.1/manual.html#2.5.5 I saw that #tablename +1 is guaranteed to be nil. thats very fine

:+1: if the whitespace issue (`tablename[#tablename+1]`) is fixed (should be `tablename[#tablename + 1]`).

**Comment by Rui914** [comment]
Updated.

**Comment by est31** [comment]
:+1: looks good

**Comment by Rui914** [comment]
idea:
```
local previous_table_insert = table.insert
function table.insert(tbl, pos_or_value, value)
    if value ~= nil then
        previous_table_insert(tbl, pos_or_value, value)
    else
        tbl[#tbl +1] = pos_or_value
    end
end
```

**Comment by Rui914** [comment]
Rebased.

**Comment by paramat** [comment]
:+1: Will merge soon.

**Comment by paramat** [comment]
24e8b0ac1ea45719937948607259f13866c8bc64

**Pull request closed without merging**
