### PR TITLE
Nodes shader: Decrease amplitude of waving leaves and plants

### PR DESCRIPTION
**Pull request by paramat**
Fix initialisation of variable 'disp'
Fix a few minor code style issues
Add independent X motion combining 2 prime frequencies
////////////////////////

New version of #3887 and #3500 
Hopefully this will be mergeable now that line endings have been corrected in a recent commit.

The X motion has a smaller amplitude due to wind direction being in Z.

### CODE REVIEW

**Comment by kilbith** [comment]
Why the movement is still uni-directional and bizarre ? (almost no waving on Y and Z axis).

I liked the old waving before https://github.com/minetest/minetest/commit/0b875560481ca16782ace98b0bace9f02d18b22d

**Comment by paramat** [comment]
It's mostly Z movement because that's the wind direction, sruff gets blown -Z anf rebounds to +Z, but also for simplicity. There is some X and Y movement to avoid texture-fighting when they overlap.
I'm trying to keep it as simple as possible because this shader is applied to every vertex.

The waving previous to mine looked like slowly writhing jelly-aliens, it had no multiple-frequency motion, the motion was a steady single frequency. I changed it to 3 prime frequencies combining to create a complex organic motion which changes amplitude over the minutes. It's much more natural-lookig.

**Comment by kilbith** [comment]
I was sure you'd answer that.

An uni-directional waving is unrealistic. This is a shader, it's _meant_ to be eye-candy and demanding on ressources, not minimal and simple as possible. And you don't even use it anyways, I'm not sure you understand the expectations of the users of advanced effects.

Anyways that's still an improvement over the current waving.

**Comment by paramat** [comment]
I felt i had to keep it simple because the 3 frequencies i use make the code more complex, so to compensate i made the application of the motion to vertexes simpler, i was trying to keep the code as lighweight as it was before. It is somewhat unrealistic of course, but to me it looks good enough and i judged a more complex motion was not worth the large increase in processing it would need.

**Comment by paramat** [comment]
Okay thanks you've convinced me. Since plants only have XZ motion, and since that will be good enough for trees, i'll add in X motion, but make it a little simpler, using 2 frequencies not 3.

**Comment by kilbith** [comment]
Another request : does the 2 planes from the plantlike drawtype can move independantly from each other like before, please ?

**Comment by paramat** [comment]
Okay updated.
The 2 planes independent looked wrong to me, stuff was sliding through itself, it looks more like one structure this way, more lightweght too.

**Comment by kilbith** [comment]
Tested, that's better.

**Comment by kwolekr** [comment]
LGTM +1

**Comment by Fixer-007** [comment]
Looks nice

**Comment by paramat** [comment]
597c1d73da38ab299eb440a3429fce04da10cf05

**Pull request closed without merging**
