### PR TITLE
Apply texture pack main menu textures immediately

### PR DESCRIPTION
**Pull request by rollerozxa**
This PR makes texture pack main menu textures apply immediately after being enabled. Previously it would only take effect after restarting Minetest.

## To do
This PR is Ready for Review.

## How to test
1. Apply the changes in this PR, and install [this](https://github.com/minetest/minetest/files/7966319/menu_texturepack.zip) texture pack for testing.
2. Open Minetest and enable the texture pack. This should make the main menu immediately switch to the texture pack's textures.
3. Disable the texture pack. It should immediately switch back to the default textures and the built-in sky background.

### CODE REVIEW

**Review by Df458 — CHANGES_REQUESTED** [review]
Using the buttons work, but you'll need something similar for `handle_doubleclick` or else double-clicking a texture pack will change the pack without updating the menu theme

**Comment by rollerozxa** [comment]
Forgot that is a thing too... >.>

Fixed, please review again.

**Review by Df458 — APPROVED** [review]
Looks good

**Review by SmallJoker — APPROVED** [review]
Works.

**Pull request merged**
