### PR TITLE
Make mgv7 the default mapgen in UI.

### PR DESCRIPTION
**Pull request by sofar**
The actual menu default comes from defaultsettings.cpp.

### CODE REVIEW

**Comment by sofar** [comment]
@paramat  without this change, the UI will still set v6 as the default mapgen with an empty minetest.conf.

**Comment by paramat** [comment]
Oops.

**Comment by paramat** [comment]
needs changing in conf.example too.

**Comment by sofar** [comment]
gotcha, pushed.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
78bf7c46e5fe8845e9a9f65b98db32b0ff398ad3

**Pull request closed without merging**
