### PR TITLE
Formspec Refactor

### LINKED ISSUE #9358: Formspec Refactor
**This thread is for technical discussion about the code behind formspecs. It's not about the formspec language itself, but the implementation of it. Please do not request any user-facing features here**

Formspecs and GUIs have been improving significantly lately. Now, all physical formspec elements create IGUIElements.

Discussion: http://irc.minetest.net/minetest-dev/2020-02-02

## Aims

* Separate Formspec parsing and formspec-knowing code from the rest of the GUI code. This will allow us to change the serialisation format in the future
* Integrate most logic into IGUIElements rather than in the guiFormspecGUI class, so that it can be shared
* To be discussed

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #9358

### CODE REVIEW

**Comment by Df458** [comment]
Good to see this get some traction! I will definitely take a look at the code when I get the time :)

**Comment by rubenwardy** [comment]
The plan for this is to migrate elements across individually, by checking the parser look up table before falling back to the old method

**Comment by rubenwardy** [comment]
If I were forced to do this, I'd call it cruel and unusual punishment

**Comment by v-rob** [comment]
I somehow don't think that cruel and unusual really covers it that well...

I think it might be best if all other formspec PRs were put on a complete halt for now except for critical bugfixes to minimize any rebasing needed.  This is already complicated enough as it is without the added need to rebase.

I don't know the best way to help (you probably know a lot better what needs the most work), but I am willing to help whenever I have time.

**Comment by rubenwardy** [comment]
I'm currently stuck on how to do dependency injection. Most element require some dependencies. For example, `image`s require the texture source, and `list`s require the inventory manager and GUIFormspecMenu for selection/drag/drop.

Currently, the parsers are just functions. Doing construction-time dependencies would require turning them into classes. An alternative would be to have a struct

**Comment by v-rob** [comment]
I suggest giving the actual string parser `FormspecElement` the texture source and then give it a member function `getTexture`.  The individual parsers don't require this, so don't give them it.  I don't know about inventories; I don't know much about the internals of `list`s or inventory code.

Secondly, I hope this is considered: https://github.com/minetest/minetest/issues/9358#issuecomment-649118843.  I consider it an integral part of formspec refactoring.  I've only just written that because I've only just really realized it.  All the same, I hope it's useful at this stage.

**Comment by Df458** [comment]
FYI--Ruben has put this down for the time being, so I'm picking it up. I'll be making my first refactor PR soon, hopefully this week. My approach is going to be quite different, but my end goal still reflects the design discussed in #9358.

**Pull request closed without merging**
