### PR TITLE
Save creative_mode and enable_damage setting for each world in world.mt

### PR DESCRIPTION
**Pull request by fz72**
implement feature request of #2486

### CODE REVIEW

**Comment by MT-Modder** [comment]
:+1: I can't count the amount of times I've entered a world in the wrong mode.

**Comment by SmallJoker** [comment]
Great stuff!

**Comment by nerzhul** [comment]
:+1: for me. @Zeno- @ShadowNinja @sfan5 ?

**Comment by MoNTE48** [comment]
:+1:

**Comment by C1ffisme** [comment]
:+1: Thank you, @fz72 .

**Comment by LeMagnesium** [comment]
:+1: Fine, it's useful, very useful.

**Comment by nerzhul** [comment]
I tested it's good for me except one point. For existing worlds please update the configuration file at server connection to save the parameters else the switch doesn't work

**Comment by fz72** [comment]
@nerzhul now old worlds are updated and new worlds get the settings on initialisation.

**Comment by Zeno-** [comment]
looks good to me
:+1:

**Comment by nerzhul** [comment]
I do a last test and i merge it if it works perfect. Thanks for the modification

**Comment by nerzhul** [comment]
Thanks. Merged 8ca08a850ff2494652aa0ac2daa3d00f03aa4e7a

**Pull request closed without merging**
