### PR TITLE
WIP: Add callback parameter for core.emerge_area()

### PR DESCRIPTION
**Pull request by kwolekr**

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Seems useful, however lua_api.txt documentation seems to be missing.  Also, what do you think about having this accepr varargs to pass like minetest.after?

**Comment by kwolekr** [comment]
It's a work-in-progress as indicated by the title..

**Comment by PilzAdam** [comment]
Something is messed up here.

**Comment by kwolekr** [comment]
Hrmm, I'll have to re-open another PR, this time not on my repo's master branch.

**Pull request merged**
