### PR TITLE
Update menu header image

### PR DESCRIPTION
**Pull request by kilbith**
For consistency with the default game, and because it's low-resolution, pixel-ish and looks better than the current header.

Credits given to @paramat 

capture d ecran de 2016-03-20 16-06-21

### CODE REVIEW

**Comment by PilzAdam** [comment]
Consistency with minetest_game isn't important here, but this looks way better than the old header. :+1:.

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
I'm ok with this, but note that 1 pixel spaces have been added between the letters, so it's not identical to the game version, however that doesn't bother me much.

**Comment by paramat** [comment]
Because this is a header for the engine, i'd prefer the same lettering but with a metallic appearence. The stone texture is refering to MTGame, 'metallic' would suggest 'engine' and be more abstract and universal.

**Comment by kilbith** [comment]
Oh my god, I feel this is going to be hard to change the header...

The 1px spacing has been added for a little more readability (especially around the 'I').

**Comment by ObaniGemini** [comment]
I think this should be added now. If someone wants to change it later, he will still be abled to do so.

**Comment by paramat** [comment]
I really don't like the spaces. As this is a texture it can be changed during freeze so no rush. I might attempt a metallic version.

**Comment by paramat** [comment]
This is just a

screenshot from 2016-03-24 04 23 40

with obsidian colours and light blue highlighting.

**Comment by kilbith** [comment]
Sorry to say but... horrible :-1: 

@est31 Can you merge this PR right now as I have 3 approvals ? By the way this PR is not WIP, I haven't declared it so, except for **one** dev who don't like the current proposal.

EDIT: 4 approvals now (see below).

**Comment by 0-afflatus** [comment]
What current header? I don't see the need for any of this, so I'm giving a big 
:-1: on this whole PR.

It is one thing to present a reasonably complete graphic as a PR as it is possible to give a clear yea or nay in response. Once anyone starts pixel-pushing the whole thing moves back to brainstorming / drawing board mode, personally I think this is bad practice.

Can we please have a decision on kilbith's OP first and then look at other options separately?

I currently have a big empty space above the main menu and I'm quite happy with that, so AFAIC this discussion is a complete waste of time.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by est31** [comment]
The current header image added by this PR is nice, and in fact I do like the spaces. I think I wouldn't like them in the mtgame logo, but the engine logo has only one word, it would look crammed if there was no space.

Also I agree with @kilbith that they should be mostly consistent.

As @paramat says he wants to make an alternative suggestion, we should wait a bit with merging IMO, to give him a chance to propose an alternative image. Not that I would think the image in this PR wouldn't be okay, in fact i really like it, or we should take what @paramat proposes, but just to not add an image to the VCS history that then gets overwritten again in the case @paramat 's proposal turns out to be the preferred one.

**Comment by paramat** [comment]
Removed the WIP label, sorry about that.
This PR as it is seems popular, i'll make an attempt at an alternative but if it isn't as popular then of course this PR can be merged. No rush as this can be done during freeze.

**Comment by paramat** [comment]
Because the header image is so important i feel it's a good idea to give this lots of time for various submissions and edits. I suggest we remove the milestone and make this a 0.4.15 thing. I don't feel confident i can do a header justice in 2-3 weeks.
The problem with this PR is that it uses a texture from MTGame. I feel the engine needs something more universal and abstract.

I had some inspiration to use the same structure but in a dark, smooth, abstract form, i was looking through MTGame textures for possible colour palettes and saw obsidian. I thought a dark blue would be good to represent space or night sky, and a light-blue edge highlight seemed suitable as the header appears against a blue sky background and can be the reflection of clouds and sky.

So this is just an early experiment, i was considering adding a diagonal shine similar to what we have on the new steel sign texture.

screenshot from 2016-03-24 05 53 49

**Comment by kilbith** [comment]
@paramat It's not because you can't do a decent header within 2-3 weeks than the milestone should be delayed. Also why should we absolutely wait you ? It's not **your** game.

But that doesn't matter anyways. I have 4 approvals, twice more than required to get it merged.

**Comment by paramat** [comment]
Just changed hat, i mean "I don't feel confident we can do a header justice in 2-3 weeks."

**Comment by est31** [comment]
@paramat what about shipping 0.4.14 with this header, then we still have enough time to change it.

**Comment by paramat** [comment]
Other devs can merge this as it has approvals, i'm just suggesting we spend more time on this, and that we don't use a texture from MTGame.
I don't have much confidence in myself that i can do a header justice, but i might try anyway.
This is not essential for 0.4.14 so removing milestone.

**Comment by ObaniGemini** [comment]
-.-
wow

**Comment by est31** [comment]
0fde86dd93d77ad3ff2662a049eeb90ad432575e

**Pull request closed without merging**
