### PR TITLE
Consistent HP and damage types

### PR DESCRIPTION
**Pull request by SmallJoker**
Also removes legacy code in the first commit (unproblematic, partially solves #8075).

**How to test:**
1) Increase your player's hp_max to >255 ([change strength=100](https://github.com/SmallJoker/upgrade_packs/blob/master/packs.lua#L5), equip 3 times)
2) Fall down without interrupt from 1600m and lose ~300 HP
3) The logs show up >255 HP damage
4) It works

EDIT2: Rewording.

EDIT by paramat: Replaces #7348

### CODE REVIEW

**Comment by rubenwardy** [comment]
code LGTM on inspection, haven't tested

**Comment by paramat** [comment]
What do you mean by 'partially solves #8075 ', how can that be partially fixed? Is it a good enough fix for 5.0.0?

**Comment by paramat** [comment]
@SmallJoker i can't get your upgrade_packs mod to work, i have 3 +100 hearts in inv but have less than 300HP.

**Comment by paramat** [comment]
Fell from y = 2000 `2019-02-07 18:48:35: ACTION[Server]: singleplayer damaged by 266 hp at (0,27.634,0)`. Not sure this is good enough testing.

**Comment by SmallJoker** [comment]
@paramat According to your damage log output I assume you were able to extend the maximal HP of the player. That you got damaged by more than 255 HP means that it works as expected.

**Comment by paramat** [comment]
No i died when i received 266 damage so i assume i had 20HP.

**Comment by paramat** [comment]
New test.

Used a mod to set my max HP to 500 on join.
Edited apple to give 400 HP, ate one, health bar becomes 80% full (420 out of 500).
Fell from 2000 nodes, received 266 HP damage, 3 hearts remain, still alive, proving i had more than 266 HP.
More falling, needed 158 more damage to die, 266 + 158 = 424 HP.

**Comment by paramat** [comment]
Looked through code, seems ok, so considering rubenwardy's comment plus my testing as a :+1:

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-dev/2019-02-10#i_5493575

19:10 paramat   Krock what do you mean by 'partially solves #8075', in 8167. is it a complete fix or not?
19:10 ShadowBot https://github.com/minetest/minetest/issues/8075 -- Hudbars displays twice in 5.0
19:11 paramat   maybe #7360 is a fix?
19:11 ShadowBot https://github.com/minetest/minetest/issues/7360 -- Statbars: Reduce initial update interval by SmallJoker
19:14 Krock     paramat: double statbars will be gone
19:14 paramat   anyway once 8167 is merged i'll retest the hudbar bug
19:14 Krock     7360 fixes the issue where HP and breath aren't scaled correctly on join when mods alter hp_max
19:14 paramat   ok
19:14 Krock     also the id=0 issue should be gone, but I haven't tested that

**Pull request merged**
