### PR TITLE
smol update to openSUSE dependencies

### PR DESCRIPTION
**Pull request by jordan4ibanez**
needs a very smol libjack0 to compile the smol binary

### CODE REVIEW

**Comment by sfan5** [comment]
What happens if this is missing? Minetest shouldn't need JACK.

**Comment by jordan4ibanez** [comment]
> What happens if this is missing? Minetest shouldn't need JACK.

```
... jack warnings continue up here
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libportaudio.so.2: undefined reference to `jack_on_shutdown'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libportaudio.so.2: undefined reference to `jack_get_client_name'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libportaudio.so.2: undefined reference to `jack_set_xrun_callback'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libportaudio.so.2: undefined reference to `jack_client_open'
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libportaudio.so.2: undefined reference to `jack_port_by_name'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:5301: bin/minetest] Error 1
make[1]: *** [CMakeFiles/Makefile2:732: src/CMakeFiles/minetest.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
geckolinux pantheon which is opensuse tumbleweed under the hood

**Comment by sfan5** [comment]
Sounds like a packaging mistake in libportaudio. I'd report this to the distro.

**Comment by jordan4ibanez** [comment]
womp womp womp

**Pull request closed without merging**
