### PR TITLE
GUIFormSpecMenu::OnEvent

### PR DESCRIPTION
**Pull request by Joooo**
I started editing the GUIFormSpecMenu::OnEvent function and plan to rewrite it.

### CODE REVIEW

**Comment by Joooo** [comment]
Right clicking and draggin a stack will keep the stack selected until left clicking. Will take me some more time to really understand all that's happening.

**Comment by paramat** [comment]
Old PR.

**Comment by Zeno-** [comment]
Unfinished work that is very unlikely to be finished and changes to the codebase since this PR was opened means that rewriting would be easier than rebasing. Author has no github activity in over 18 months. Closing.

**Comment by paramat** [comment]
I agree to a close.

**Pull request closed without merging**
