### PR TITLE
Play footstep sound when a dropped item touches ground

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by RealBadAngel** [comment]
why footsteps? since when items are walkin? ;)
cant you get a new sound for it?

**Comment by nerzhul** [comment]
i think this could be anoying with > 5 items drowning due to node breaking no ? :)

**Comment by paramat** [comment]
Footstep sound is fine, as it is an object hitting ground, ideal.

**Comment by RealBadAngel** [comment]
If a footstep sound is ideal then use it for everything. Why having many sounds when you can have only one to rule them all? ;)

**Comment by HybridDog** [comment]
>i think this could be anoying with > 5 items drowning due to node breaking no ? :)

l'm not sure if l understand you correctly, the mod which overrides digging to drop the drops instead of adding them to player inventory can also easily override the __builtin:item

**Comment by kaeza** [comment]
it's hard to make something even pseudo-realistic for this.

Let's take for example a metal pipe. Dropping on grass makes almost no sound from the pipe, it should be mostly grass sound. But if you drop it on stone, you expect to hear the pipe *and* the stone sounds.

For a different example, let's take a pillow, rug or something like that. Grass should make sound, but not stone.

How to specify every combination?

Also, what about dropping into e.g. water or lava?

I think playing footsteps is a nice compromise.

Re: code, shouldn't unrelated changes be in separate commits? (`or 900`)

**Comment by HybridDog** [comment]
Maybe the engine could get changed to allow adding specific sounds to objects (table with groups as fields with simple sound spec tables as values), the footstep sound of stepping on stone could then be assigned to the player (sam's shoes).

>Also, what about dropping into e.g. water or lava? (okay, that's another topic).

It works great, but only to me because l merged that pull request adding footstep sounds to water and lava.

**Comment by BlockMen** [comment]
:-1: Kinda annoying IMO. Also footsteps sounds played by entities via this method are played 20 or 30 nodes far (idr the excact value right now) which makes this even more annoying.

Since this can be done by mods anyway, I see no reason to merge this.

PS: see general discussion about builtin_items things here: https://github.com/minetest/minetest/pull/3358#issuecomment-174171657

**Comment by HybridDog** [comment]
@proller, how do you think about this?

**Pull request closed without merging**
