### PR TITLE
Update ContentDB dialog

### PR DESCRIPTION
**Pull request by rubenwardy**
* Updated to use formspec_version 3
* Padding/alignment fixed
* Uses a button for center-alignment on the page/max label
* Icons for pagination buttons

image

image

## How to test

Use it

### CODE REVIEW

**Comment by ClobberXD** [comment]
Tested; works. I love the button-hack. :+1:

The icons give the UI a good amount of polish, IMO. :)

**Comment by rubenwardy** [comment]
Colored uninstall button:

image

**Comment by paramat** [comment]
I think the red is unnecessarily alarming and too visually intrusive.
I see no problem with having 'uninstall' buttons the same colour.
Lighter grey would reduce text contrast, red text would make it harder to read, and is again too alarming.

**Comment by rubenwardy** [comment]
> I see no problem with having 'uninstall' buttons the same colour.

The point is to make it clearer whether a mod is installed, rather than having to read text. But I've reverted that for now

**Comment by ClobberXD** [comment]
I too think red is unnecessary. If the intention is purely visual, then I suggest going with more neutral colours like blue, or even adding an installed indicator next to the package title (a small green tick mark?) instead.

**Comment by SmallJoker** [comment]
> Maybe a lighter grey button? Red text? Idk

I agree that installed content should be visually highlighted, especially because "Install" and "Uninstall" are in the same place and share most characters (various languages).

I'd suggest a less dominant red -> more towards the default grey buttons. You could also take blue colors for "Install" to separate it even more.

**Comment by paramat** [comment]
I see, i missed the fact that 'Install' and 'Uninstall' buttons do look a little similar.

**Comment by appgurueu** [comment]
Probably out of scope for this PR, but I'd like to see CDB take advantage of `hypertext` and displaying mod Readme's in-game (not having users open the browser unless required).

**Pull request merged**
