### PR TITLE
Irrlicht 1.9 support

### PR DESCRIPTION
**Pull request by sfan5**
addresses #3834

I couldn't figure out how to fix pageflip for 1.9 so I had to disable it.

### CODE REVIEW

**Comment by paramat** [comment]
Sorry nerzhul but the 0.4.16 milestone is pointless at the moment.

**Comment by nerzhul** [comment]
@paramat stop that shit, the milestone permits to know which PR are interesting for the next release permitting to know on which PR focus for merging fast.

**Comment by paramat** [comment]
Then use 'high priority' instead? Milestones are usually used when preparing for a release, i think it's too early to use those, if somethng is high priority then it should be merged as soon as possible, instead of 'anytime before next release'.

**Comment by Zeno-** [comment]
Looks good to me

**Comment by nerzhul** [comment]
Okay for me too

**Comment by sfan5** [comment]
084cdea6862cb65fe4bb807a211a9e1c17cffec8

**Pull request closed without merging**
