### PR TITLE
Far map and improved map transfer and rendering (WIP)

### PR DESCRIPTION
**Pull request by celeron55**
This does two things like the title says: far map rendering and improved map transfer, and includes a couple of supporting commits.

I request testing and comments about whether this is upstream-worthy. This is causing a lot of conflicts at the moment because people are eager to work on the map transfer which this reworks heavily.

You can see the original spammy commit log by looking at celeron55:far_map_wip_2.

This is my to-do list at the moment of posting this PR. All of the items on this list are strongly "maybe", subject to changes and/or practically undecipherable.

```
- Check how empty MapBlocks and FarBlocks are handled and possibly improve it

? Make it so that empty FarBlocks don't consume huge amounts of memory

- Rename enable_far_map to enable_far_map_system to indicate that it completely
  switches it into and out of use

- Merge gregorycu's patch

- Rename TOSERVER_SET_WANTED_MAP_SEND_QUEUE to TOSERVER_SET_MAP_SENDS

? Add max_simultaneous_block_sends to TOSERVER_SET_WANTED_MAP_SEND_QUEUE

- Unload FarBlocks sometimes
    - May have to use IVideoDriver::removeHardwareBuffer

? Increase default target FPS to 60

? Should FarBlocks be aligned with map generator chunks?

? Make FarBlocks to be scene nodes so that irrlicht will render them on its own

- Maybe store zlib-compressed data on ServerFarBlocks

- The server has to do occlusion culling for FarBlocks due to network usage
    * Or maybe not?

- The server must be able to tell the client that a FarBlock was culled and may
  not be actually empty

- Add a setting for disabling far map on server side

- Use frustum culling when rendering FarBlocks

- The client has to do occlusion culling for FarBlocks due to the GPU having a
  limited amount of space for VBO meshes

- Inform FarMap about blocks that were found to not exist too

- far_map_enable_maximum_resolution: Basically the "ultra" setting of Minetest
    - ServerFarMapPiece::content_max_res

- Add a minimal logging subsystem for map transfer that can be turned on

- Profile some useful stuff:
    - Number of MapBlocks sent
    - Number of FarBlocks sent

- Time out and drop FarBlock meshes that are not rendered at all

- Add a setting for maximum far map send distance on the server

- far_map_allow_generate_to_distance (replace)

- Maybe do something to Z fighting that happens sometimes, or at least explain
  it somehow

- The far map generation limits should be a world-specific setting so that if
  you want to have a large world with a lot of wasted hard drive space, you can
  set it as such, and if not, you don't accidentally bloat it up by leaving some
  global setting enabled

- Allow the client to tell the server how many meshes it wants per second so
  that systems that get choppy framerates with 20 meshes per frame but work fine
  with 5 meshes per frame can be made playable
```

### CODE REVIEW

**Comment by paramat** [comment]
> - Remove auto view range

Reading the forum many players (including me) are choosing to set min and max equal to disable the auto adjust, i feel this won't be missed much.

For a guide to the vertical range farmap should cover, mgv7 can occasionally have mountains up to 500, mgwatershed up to 1000. I guess 'far map generation limits' will have separate horizontal and vertical limits?

**Comment by Fixer-007** [comment]
Will be nice to have both 'Far map rendering' and 'improved map transfer' in Minetest :)

>Make it so that empty FarBlocks don't consume huge amounts of memory

Could be a problem on 32 bit builds (it is already susceptible to crashes in big forests).

>Paramat: Reading the forum many players (including me) are choosing to set min and max equal to disable the auto adjust, i feel this won't be missed much.

I myself use equal min and max when playing on actual multiplayer servers (it gives me some compromise, I'm not perfectly happy with it either).
Auto view range positive sides for me:
+ can enlarge view range dramatically in simple env (usually in singleplayer it is all the way to 240).
+ lowers view to increase fps in very crowded places (obviously).
Negative sides:
+ view range oscillation that is very noticeable in areas near forests when you walk forward (and quite irritating btw).
+ looking back at high range will dramatically slow fps (renders huge chunk of previously loaded blocks) and will reduce range fast.
Current auto view range needs rewrite or be removed.

>Increase default target FPS to 60

+1

**Comment by VanessaE** [comment]
Seems to work fairly well for me, with one caveat:  the farmap blocks are fully lit even at night.

**Comment by sofar** [comment]
Pulled this just today, only 1 tiny merge conflict (trivial).

Had a blast with farmap range at 2000. I didn't see any issues at all, whatsoever. It's like a giant minimap.

**Comment by red-001** [comment]
I get about 40 build error when I try to build using Visual studio 2013. Most of them in `atlas.h`.

**Comment by C1ffisme** [comment]
Is this in any way laptop friendly?

Just wondering, I just thought what @sofar 's comment was :+1: worthy. I normally have to keep my render distance at 5 - 25 (because of heat), and this would help.

**Comment by Fixer-007** [comment]
Can't cross compile it on linux via mingw-w64 for my windows desktop, gives me declaration errors in clientiface.cpp

**Comment by red-001** [comment]
@celeron55  you need to include `stdint.h` in `clientiface.cpp`, `atlas.cpp` and `atlas.h` for it to build in Visual studio 2013.

**Comment by lisacvuk** [comment]
I just tested it. Specs:
Pentium D 820,
3GB RAM,
GeForce 210 (1GB),
Kubuntu 14.04.
Wanted FPS: 30.
Stable 30 FPS on 500, when I remove wanted FPS it lags about 1000 range. I didn't notice any rendering anomalies.

**Comment by celeron55** [comment]
I rebased this today. Feel free to check if I broke any recent commits.

**Comment by HybridDog** [comment]
How about rendering far blocks without rendering near ones, take a picture of them, and then render only near blocks and use the picture as background image?

> Remove auto view range

automatic view range adjusting is already removed

**Comment by Fixer-007** [comment]
Well check it out.

**Comment by celeron55** [comment]
@Fixer-007 You could try it now again.

**Comment by Fixer-007** [comment]
Tried just now, error: https://i.imgur.com/AQSM6Yt.png

**Comment by Fixer-007** [comment]
Windows users (64bit) can finally try it out!
[minetest-0.4.13-089f9bb-win64-far-map-PR3810.zip](https://github.com/minetest/minetest/files/171254/minetest-0.4.13-089f9bb-win64-far-map-PR3810.zip)
Have fun and bug report.

Also, it looks like this PR eliminates most of stutters that plagued some people like me for so long.

**Comment by paramat** [comment]
screenshot_20160313_114910

^ Mgfractal.
A quick 30min test, with farmap range 1024, normal view range 330. FPS was 23 and memory usage levelled out at 2GB.

**Comment by sofar** [comment]
https://youtu.be/gQ8fo5VBKEM

a few unused compile warnings is all.

**Comment by C1ffisme** [comment]
@sofar That... is amazing.

**Comment by ShadowNinja** [comment]
I noticed from sofar's video that the block disappears for a second when it switches from the farmap version to the full version, it would be nice if this flicker could be removed.

**Comment by sofar** [comment]
There's also a noticable gap if you log on and look at the minimap - farmap updates the outer range of the minimap, and the inside of the normal map is covered as well, but there's exactly 1 black square at mid range on the minimap unless you move.

**Comment by Fixer-007** [comment]
```
<celeron55> i wonder if the farmap PR should be merged with the farmap part being disabled by default
<celeron55> the reworked map sending code is probably worth it
<celeron55> ... it's a bit more reliable and more maintainable
<celeron55> ... reacts somewhat faster to player movement
```
If that "reworked map sending code" is responsible to very good smoothness I have observed in my testing even with farmap off, could be a good idea (I've observed the difference on localhost and it is day and night difference for me). Can developers consider this?

**Comment by paramat** [comment]
It should be considered, i'm suggesting a long freeze of around 2 weeks so maybe enough time to thoroughly check it, if added in disabled form.
Or, if not, i'm suggesting adding fully enabled farmap soon after release.

**Comment by kilbith** [comment]
A 6000-lines change on the rendering (critical area) so close to the release is definitely **not wise** at all.

This has not even been reviewed and there are higher priorities currently. Also no feature added in feature-freeze time.

**Comment by nerzhul** [comment]
i agree with  @kilbith FarMap should be added AFTER 0.4.14 release. There is not enough time to review a so huge PR

**Comment by Fixer-007** [comment]
Another way is to somehow seperate map sending code to seperate PR, that will allow to review it before 0.4.14 and it will eliminate most of stutters. And farmap itself can be improved/merged/etc later.

**Comment by paramat** [comment]
> so close to the release is definitely not wise at all.

Yes that's what i'm concerned about.

I noticed farmap cubes changing to ultra-low res cubes at 1000 nodes, too close for me. I'd prefer these to not appear at all or appear at much larger distance, as 8^3 seems good out to 2000 nodes.

**Comment by celeron55** [comment]
I'm finding some performance issues in this that aren't easy to fix, so I don't recommend this for 0.4.14 even with farmap disabled by default.

@paramat As for the rough stuff at large distance: It's not something that can be removed for simplification but it can be disabled in normal operation for sure. The very, very lightweight and rough version of the farmap mesh exists primarily to allow something to be rendered even when all of the finer farblock meshes haven't been generated or have been unloaded to save memory, until the farmap mesh generator gets around to generate the primary meshes again.

**Comment by Fixer-007** [comment]
Looks like there is a memory leak, it starts to eat memory until slight freezes and warning by windows. Mem usage at that moment near 4gb.

**Comment by paramat** [comment]
```
s32 render_range_nodes = getEnv().getClientMap().getMapDrawControl().wanted_range;
s32 render_range_mapblocks_1d = render_range_nodes / MAP_BLOCKSIZE + 1;
s32 render_range_mapblocks_3d = render_range_mapblocks_1d * render_range_mapblocks_1d *
render_range_mapblocks_1d;
s32 limit_required_for_rendering = render_range_mapblocks_3d * 1;
```
Volume of a sphere is 4/3 * pi * r^3 ~= 4.2 * r^3
The default 5000 limit allows a fully rendered sphere with view range of 170 nodes, not much.
I'm concerned your code would not allow enough mapblocks for a certain view range, it would only increase the limit at 5000 ^ 0.33333 * 16 = 274 nodes view range.

**Comment by celeron55** [comment]
Oh, looks like it should be something like `render_range_nodes * 2 / MAP_BLOCKSIZE + 1` instead of `render_range_nodes / MAP_BLOCKSIZE + 1`. I thought I did it like that but apparently I didn't.

**Comment by celeron55** [comment]
4 months ago I split out the map transfer portion of this and forgot to mention here: https://github.com/celeron55/minetest/commits/block_transfer_v2

That branch could use some testing. I know it contains the same bugs this branch has though.

**Comment by paramat** [comment]
Related, here's an interesting alternative approach to LOD for MC-like games https://0fps.net/2018/03/03/a-level-of-detail-method-for-blocky-voxels/

**Comment by paramat** [comment]
I can't see a point keeping this open.

**Comment by paramat** [comment]
Here are sofar's videos of the farmap feature:
[https://www.youtube.com/watch?v=gQ8fo5VBKEM](url)
[https://www.youtube.com/watch?v=WLO-Mn4DcOs](url)
[https://www.youtube.com/watch?v=tJH6lqLVce4](url)

**Comment by LoneWolfHT** [comment]
Those links are broken somehow, you have to manually copy them

**Comment by paramat** [comment]
Thanks, fixed.

**Pull request closed without merging**
