### PR TITLE
Pause animations while game is paused 

### PR DESCRIPTION
**Pull request by numberZero**
Pause all mesh animations while game is paused.

## To do

This PR is Ready for Review.

## How to test

Open a singleplayer world, look at a walikng mob, pause game. Walking animation should supsend.

### CODE REVIEW

**Comment by MoNTE48** [comment]
A similar thing has been used in **MultiCraft** for a long time (actually several years).
This implementation is much better and I will be glad if it appears in Minetest!
(@lhofhansl, check this. Less resource consumption in the pause menu should be important too!)

**Comment by MoNTE48** [comment]
Should be rebased now...

**Comment by MoNTE48** [comment]
@rubenwardy, any reason why this simple patch cannot be merged before 5.4.0?
It's so ugly to see a mob standing still wiggling its legs in the pause menu.

**Comment by runsy** [comment]
Please, do optional. I like mobs doing their own while paused.

**Review by sfan5 — APPROVED** [review]

**Review by SmallJoker — APPROVED** [review]
Works

**Pull request merged**
