### PR TITLE
Fix URL escaping in content store

### PR DESCRIPTION
**Pull request by sfan5**
<i>less code = better</i> or something

Replaces #11578

## To do

This PR is Ready for Review.

## How to test

* Download https://github.com/Df458<i></i>'s beautiful "rpg16" texturepack
* Verify it shows as installed
* Click the rightmost buttom and verify it leads to CDB in browser

### CODE REVIEW

**Comment by rubenwardy** [comment]
This looks good, apart from the fact that you lose case information when constructing URLs.

Given the username "FooBar", the id for a mod would be `foobar/mymod` but the URL should be `/packages/FooBar/mymod`.
Currently, usernames are case insensitive on ContentDB. I've just realised this may lead to duplicate URLs, I should probably introduce redirects or canonical links

**Comment by rubenwardy** [comment]
There's already a place where `package.id` is used where it should the capitalised version. Might be worth making this less error prone by generating the URLs in one place, or having something like "package.url_base`

**Comment by sfan5** [comment]
Done, I named it `package.url_part`

**Review by SmallJoker — APPROVED** [review]
No issues found.

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
