### PR TITLE
Client side scripting (first step)

### PR DESCRIPTION
**Pull request by nerzhul**
Here is the first two commits to start making client side scripting a reality.

It init in client a cleaned Lua stack using some of our helpers

At this moment it only permits to load builtin itself and you have a on_shutdown, on_receiving_chat_message, on_sending_chat_message callbacks permitting to fetch informations and do builtin things with it

Mod security is enabled without condition client side

I think it should be merged as-is and we should start add more and more callbacks and then plug mods and to finish, maybe, in the future, a mod store ?

When merging will be okay i will remove examples from PR

### CODE REVIEW

**Comment by nerzhul** [comment]
capture d ecran de 2017-01-21 16-44-23

Example of callbacks on_shutdown, receive & send

**Comment by GreenXenith** [comment]
So client-side lua is gonna be possible?

**Comment by nerzhul** [comment]
Yes it's possible but it's the early stage

**Comment by nerzhul** [comment]
As discussed on IRC first things will be done in a separated branch and we should communicate about it-------- Message original --------Objet : Re: [minetest/minetest] Client side scripting (first step) (#5086)De : GreenXenith À : minetest/minetest Cc : Loïc Blot ,Author So client-side lua is gonna be possible?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/minetest/minetest","title":"minetest/minetest","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/minetest/minetest"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GreenXenith in #5086: So client-side lua is gonna be possible?"}],"action":{"name":"View Pull Request","url":"https://github.com/minetest/minetest/pull/5086#issuecomment-274275621"}}}

**Comment by nerzhul** [comment]
Closed, this is now supersede by #5088

If you want to help to have additions please do PR against client_side_modding branch

**Pull request closed without merging**
