### PR TITLE
lua_api.txt: Move 2 fields to nodedef

### PR DESCRIPTION
**Pull request by ClobberXD**
Move `node_placement_prediction` and `node_dig_prediction` from item def to node def section

### CODE REVIEW

**Comment by t4im** [comment]
While i agree that this seems more intuitive, you'd hide that you can set those on other item types as well.
There are cases where you might want to set prediction on craft items or tools for example, where these might spawn or despawn nodes. Since minetest supports that functionality, it should probably remain documented until such a functionality is removed.

**Comment by ClobberXD** [comment]
> There are cases where you might want to set prediction on craft items or tools for example, where these might spawn or despawn nodes.

If I'm correct, the nodes that are spawned by the craftitem should be registered too. And these fields would be defined in that nodedef. Do correct me if I'm wrong, since I assumed that these fields were used only in nodedefs

**Comment by t4im** [comment]
Well, lets look at a concrete example.

@tenplus1 's `ethereal:light_staff` is a tool that replaces a node with a `ethereal:glostone`.

If the light-staff tool sets `node_dig_prediction = ethereal:glostone`, the client should know even during lag or general network latency what to predict when you dig a node with the staff.

This is independent of a prediction of `glostone`-placement when holding a glostone, because the client doesn't know of the staff-stone relationship except due to that additional prediction field we'd be adding.

**Comment by ClobberXD** [comment]
That's a very suitable example here, but again, I still think that the dug node (`default:stone` or `default:cobble`) should define `node_dig_prediction`, and not the tool that digs the node.

Here's the light staff registration code:
```lua
minetest.register_tool("ethereal:light_staff", {
	description = S("Staff of Light"),
	inventory_image = "light_staff.png",
	wield_image = "light_staff.png",
	sound = {breaks = "default_tool_breaks"},
	stack_max = 1,
	on_use = function(itemstack, user, pointed_thing)
		...
	end,
})
```

As you can see, there's no `node_dig_prediction` field here. I also don't think that Ethereal modifies the nodedef of `default:cobble` or `default:stone`. It would be great if you could provide another example, preferably one that uses this field in a craftitem registration. :)

**Comment by ClobberXD** [comment]
Interesting. I hope it works. Meanwhile, I found this:
https://github.com/minetest/minetest/blob/18a8fbf465b47c4780d63f34c960af7a52d0cf82/doc/lua_api.txt#L5768-L5780
Looks like MT checks if item is node only for `node_placement_prediction` and not `node_dig_prediction`. Or does it apply to both? I agree that the relevant documentation needs to be improved for more clarity.

**Comment by t4im** [comment]
Skimming over the code it appears to me as if `node_dig_prediction` generally assumes "air" by default for everything.

I only tested the placement prediction, not the dug prediction on non-nodes so far.
It's possible that indeed `node_dig_prediction` only works on nodes then, if it does not predict the item use but its despawning.

**Comment by paramat** [comment]
Seems to me that `node_placement_prediction` belongs in itemdef as it is usable for items, the documentation makes it clear it is not only for nodes.
`node_dig_prediction` seems to be only usable when a node is dug, so could possibly be moved to nodedef.

**Comment by ClobberXD** [comment]
The whole point of this PR is to move the two fields to nodedef as it belongs there (or so I thought). If they are used non-nodes as well, they should remain as-is.

Closing; thanks for explaining this to me @t4im :)

**Pull request closed without merging**
