### PR TITLE
[no squash] Init & gettext cleanups

### PR DESCRIPTION
**Pull request by sfan5**
## To do

This PR is  Ready for Review.

## How to test

* test that Minetest + localization still works on linux :heavy_check_mark: 
* same for windows :heavy_check_mark: 
* same for android :heavy_check_mark:

### CODE REVIEW

**Comment by SmallJoker** [comment]
My findings on Android 6.0

* 5.7.0: locale works
* 5.8.0: locale works
* master cad8e89: locale broken (English only) (self-signed apk)
 * this PR: locale broken (English only) (self-signed apk)

I compared the verbose logs but could not find any difference. Only `INFO[Main]: Message locale is now set to: C`  is logged for all of them.

**Comment by grorp** [comment]
I tested this on Android too. For me, localization (including automatic locale selection) still works on the latest "master" branch. However, it's broken by this PR.

**Comment by sfan5** [comment]
Fixed and re-tested.
Android behaves a bit weird and requires `LANG` to be set even though `LANGUAGE` should suffice and have higher priority.

**Review by SmallJoker — APPROVED** [review]
This time, gettext works properly on Android.
Works on Linux, 64-bit.

The code changes look correct.

**Pull request merged**
