### PR TITLE
Alphabetical sorting of texture packs in menu (fixes #3487)

### LINKED ISSUE #3487: Alphabetize the Texture Pack List in the Texturepack Tab
Currently, the list of installed textured packs, under the main menu's "Texturepacks" tab is a jumbled, random sorting. It would be nice if the list of installed texture packs were alphabetized.

### PR DESCRIPTION
**Pull request by kilbith**
Title says it all (fixes https://github.com/minetest/minetest/issues/3487).

capture d ecran de 2015-12-25 22-01-16

### CODE REVIEW

**Comment by PilzAdam** [comment]
Searching for "None" afterwards is really ugly. Better start with an empty table, and insert "None" afterwards.

**Comment by kilbith** [comment]
@PilzAdam Done.

**Comment by PilzAdam** [comment]
:+1:

**Comment by est31** [comment]
382ab969d4de29cd5f74db2de433a37254d40d2a

**Pull request closed without merging**
