### PR TITLE
API for chat position.

### PR DESCRIPTION
**Pull request by FoxLoveFire**
Now it is possible to set the chat position using the Lua API. I think this is a really useful thing because you can change the chat position for the player.

The methods are made only for the ObjectRef player. That is, you will first need to get a player.

Let's take a callback to join the game:
```lua
minetest.register_on_joinplayer(function(player)
        player:set_chat_position(50, 20) -- Now x = 50, y = 20
end)
```
As you understand, the `set_chat_position` method sets the chat position. From top left corner.
It is also possible to get the player's chat position using the `get_chat_position` method.

```lua
minetest.register_on_joinplayer(function(player)
        player:get_chat_position() 
end)
```
This will return a table with the fields chat_posX and chat_posY

```lua
minetest.register_chatcommand("get_chat_pos", {
    func = function(name)
            local player = minetest.get_player_by_name(name)
            local pos = player:get_chat_position()
            minetest.chat_send_player(name, "X: " .. pos["chat_posX"] .. " Y: " .. pos["chat_posY"])
    end
})
```
image

## How to test
Compile it and use my examples of code.

### CODE REVIEW

**Comment by Andrey2470T** [comment]
Generally works :+1: Also for a note: this is a purely client feature, so in theory it could be implemented through CSM without transfering the packet from the server. But since the most mods work on the server, it may be omitted.

**Comment by Zughy** [comment]
You're still not following the template as asked in #15146. Also, I think this is a debatable solution, as it doesn't allow further expansion of chat features; instead I think it should be a HUD type. See #10372 .

**Comment by FoxLoveFire** [comment]
> You're still not following the template as asked in #15146. Also, I think this is a debatable solution, as it doesn't allow further expansion of chat features; instead I think it should be a HUD type. See #10372 .

What does template mean? Since when do we have to write according to templates?
This pull request was clearly not made according to the template:
https://github.com/minetest/minetest/pull/15144

**Comment by rollerozxa** [comment]
> What does template mean? Since when do we have to write according to templates?

It is what the PR description box is always automatically populated by. You should read it and keep the headers of it.

image

**Comment by cx384** [comment]
IMO, the chat is part of the HUD, so should be managed like all others HUD things by a Lua HUD element. E.g. to support the `z_index` also see #9270 and #13588 for other elements. Scattering HUD things would only create a confusing mess.

**Comment by rollerozxa** [comment]
The API itself seems to be a bit of an XY problem and I assume what you're wanting to implement using this functionality is a Minecraft-style chat HUD that is on a lower part of the screen. But since there is a setting to customise how many chat messages are displayed on the HUD it will lead to messages falling off the screen since the chat buffer is anchored at the top and new chat messages are appended below without shifting previous messages (until they fade away). Minecraft chat is anchored at the bottom and new chat messages shift older messages upwards until they fade out from inactivity. For such an usecase you'd also want to control this chat flow behaviour in addition to changing the position of the chat HUD.

**Comment by Andrey2470T** [comment]
> But since there is a setting to customise how many chat messages are displayed on the HUD it will lead to messages falling off the screen since the chat buffer is anchored at the top and new chat messages are appended below without shifting previous messages (until they fade away).

The new messages will shift previous ones if total count of messages exceeds the `recent_chat_messages` in the box. Otherwise, it would be possible to fill the whole screen with spam waiting until it fades out for a while. If you mean because of the large count of displayed messages allowed, well, then just the client should decrease it before the count when the last messages don't fall off the screen (if the chatbox is located too low).

**Pull request closed without merging**
