### PR TITLE
Use active object id in objrefs instead of pointers 

### PR DESCRIPTION
**Pull request by Desour**
- objrefs currently carry pointers, which can be problematic
- With this PR, objrefs use active object ids and lookup the ServerActiveObject on each access.
- Invalid objrefs no longer have a nullptr, but the id 0.
- Anonymous active objects also have id 0, hence they are also counted as invalid. This means that you can't interact with them from lua.
  It's like a goblin that died and became a ghost, you can't interact with the ghost, but did you ever interact with a goblin? If so, please tell me about it.
- The pointer to the ServerActiveObject was boxed in the ObjectRef, and a pointer to that was stored in the userdata. I have no idea why this extra boxing happened, and so I've removed it. The ObjectRef is now directly stored in the userdata buffer.

## To do

This PR is a Ready for Review.

## How to test

I don't know.

@rubenwardy

### CODE REVIEW

**Comment by sfan5** [comment]
There's a simpler, ~10 line fix to problem you are attempting to fix.

**Comment by Desour** [comment]
I don't know what this 10 line fix is. A shorter-than-this-PR fix that I've found still changes 70 lines: 
https://github.com/Desour/minetest/commit/09eca608c7b08a66548dd04dc2d648d7021d21b5

**Comment by sfan5** [comment]
```diff
diff --git a/src/script/cpp_api/s_base.cpp b/src/script/cpp_api/s_base.cpp
index f965975a3..60af22d94 100644
--- a/src/script/cpp_api/s_base.cpp
+++ b/src/script/cpp_api/s_base.cpp
@@ -390,7 +390,7 @@ void ScriptApiBase::removeObjectReference(ServerActiveObject *cobj)
 	lua_pushnumber(L, cobj->getId()); // Push id
 	lua_gettable(L, objectstable);
 	// Set object reference to NULL
-	ObjectRef::set_null(L);
+	ObjectRef::set_null(L, cobj->getId());
 	lua_pop(L, 1); // pop object
 
 	// Set object_refs[id] = nil
diff --git a/src/script/lua_api/l_object.cpp b/src/script/lua_api/l_object.cpp
index 8ae99b929..ebaf1b7c5 100644
--- a/src/script/lua_api/l_object.cpp
+++ b/src/script/lua_api/l_object.cpp
@@ -2284,9 +2284,11 @@ void ObjectRef::create(lua_State *L, ServerActiveObject *object)
 	lua_setmetatable(L, -2);
 }
 
-void ObjectRef::set_null(lua_State *L)
+void ObjectRef::set_null(lua_State *L, u16 expected_id)
 {
 	ObjectRef *obj = checkobject(L, -1);
+	if (obj->m_object)
+		FATAL_ERROR_IF(obj->m_object->getId() != expected_id, "core.object_refs was messed with");
 	obj->m_object = nullptr;
 }
 
diff --git a/src/script/lua_api/l_object.h b/src/script/lua_api/l_object.h
index db3a3a7cf..35bc62abb 100644
--- a/src/script/lua_api/l_object.h
+++ b/src/script/lua_api/l_object.h
@@ -41,7 +41,7 @@ class ObjectRef : public ModApiBase {
 	// Not callable from Lua; all references are created on the C side.
 	static void create(lua_State *L, ServerActiveObject *object);
 
-	static void set_null(lua_State *L);
+	static void set_null(lua_State *L, u16 expected_id);
 
 	static void Register(lua_State *L);
 

```

**Comment by Desour** [comment]
Ah, but that doesn't work, I think: One can still keep an old objref and wait until the id gets reassigned and then use the old objref as dummy. Actually, you could still use any invalidated objref as dummy.

**Comment by sfan5** [comment]
That's easy to fix:
`FATAL_ERROR_IF(!obj->m_object || obj->m_object->getId() != expected_id, "core.object_refs was messed with");`

**Comment by Desour** [comment]
Hm, yes.
But anonymous objects would still be handled incorrectly, because of lost control.
Also, a fatal error seems a bit harsh. Mods shouldn't cause minetest to be killed, if possible.

**Comment by sfan5** [comment]
Anonymous objects are not (afaik) and should not be used anywhere.
No, a fatal error is exactly right. Everything else would be unsafe and it's exactly what mods deserve when they meddle with internals.

**Pull request closed without merging**
