### PR TITLE
Set param2 to the node pointed at when placing default:tree holding aux1

### PR DESCRIPTION
**Pull request by HybridDog**
l also set a local param2 instead of all those core.set_nodes to short code.

### CODE REVIEW

**Comment by est31** [comment]
:-1: this behaviour is common I don't think we should force all the users to re-learn everything.

**Comment by HybridDog** [comment]
There is nothing to re-learn. It's just an additional useful feature.

**Comment by est31** [comment]
Additonally, placer:get_player_control is subject to lag, therefore usage of it is bad.

**Comment by HybridDog** [comment]
>Additonally, placer:get_player_control is subject to lag, therefore usage of it is bad.

lt doesn't get executed more times than before.
https://github.com/minetest/minetest/pull/3573/files#diff-a09c7fe45339eba9cdf21f4b9c25b146L468

**Comment by est31** [comment]
Being subject to lag is different than causing lag. placer:get_player_control gets the player control from the TOSERVER_PLAYERPOS packet sent every now and then. The controls the server might think the client has don't neccessarily match those the client actually has pressed. On laggy servers, this causes problems. E.g. when wanting to pick up minecarts you sometimes accidentially start them, and you have to run after them. So when you want to place stuff in fast succession, it might even cause greater problems.

**Comment by paramat** [comment]
:-1:

**Comment by HybridDog** [comment]
@est31 l only experienced the problem with the on_use, see the fullautomatic weapons. The replacer tool mod of @Sokomine works without problems l think.

**Comment by red-001** [comment]
Doesn't this set param2 for all nodes not just tree?

**Comment by HybridDog** [comment]
>Doesn't this set param2 for all nodes not just tree?

the default:tree is the best known node which uses the rotate on place l think, so l used is as example

**Comment by est31** [comment]
@red-001 yes.

**Pull request closed without merging**
