### PR TITLE
Add noclip parameter to button formspec element

### PR DESCRIPTION
**Pull request by pauloue**
Same as the parameter for `item_image_button`.

### CODE REVIEW

**Comment by rubenwardy** [comment]
This conflicts with #8383, and I generally don't like adding more parameters for formatting

**Comment by pauloue** [comment]
Will the style tag allow enabling noclip? I guess it's already possible by using an image_button and not specifying an image.

**Comment by rubenwardy** [comment]
I've now

**Comment by SmallJoker** [comment]
Also, the way formspec elements are guarded, you cannot add a new parameter without either
1) breaking backwards compatibility or
2) increasing the formspec version

Older clients would throw errors if this new notation is used. Thus, I think the solution using `style[]` is a better approach.

**Pull request closed without merging**
