### PR TITLE
Mapgen: Make mgv7 the default mapgen for 0.4.15

### PR DESCRIPTION
**Pull request by paramat**
Addresses #3655 
The biome system has been much improved for release, but is not officially stable (it may never be).
Mgv7 terrain is now stable, apart from the experimental floatlands which are disabled by default.

Anyone who has used Minetest for a while has tried the mapgens and knows which to use, the only way the default is important is concerning those new to the game and reviewers.
I make a daily check on all new Minetest videos on Youtube and all of those new to the game use the default mgv6. I guess when faced with the choice of mapgens they don't know what to do so just use the default, perhaps assuming the default has been set as being the mapgen most representative and most developed, our best work.

Obviously mgv6 is none of these:

It has hardcoded biomes and some hardcoded decorations and doesn't use the biome API.
It has 6 biomes instead of 12 plus iceberg, sand dune and swamp sub-biomes.
It lacks aspen, temperate pine and acacia trees, dry grasses, logs, large cacti, bushes and coral reefs.
It has no sandstone.
Hills don't pass y = 47 and there are no mountains or overhangs.
There are no rivers.
The terrain and biomes become repetitve on a smaller scale, travel 500 nodes and you've seen everything.

It drives me nuts to see all these people missing our best work and not getting the best impression, and making videos that others watch.
So, even if you have no personal preference please support to give a better impression of Minetest.

### CODE REVIEW

**Comment by est31** [comment]
The problem with mgv7 is that if you have a map, and update minetest, and then generate stuff that wasn't generated before, it might create big cliffs at the mapchunk border, which are quite ugly. So I'm not sure if mgv7, as long as its unstable like this, should ever become the default mapgen.

**Comment by est31** [comment]
So :-1: unless you ensure that the terrain stays 100% stable and hmmm is okay with this as well (have you asked him?). I don't want him to break mgv7 in the future because he's not aware of the change.

**Comment by rubenwardy** [comment]
According to @paramat

> Mgv7 terrain is now stable, apart from the new default-off floatlands.

Would be nice to unit test these though

**Comment by juhdanad** [comment]
@est31 You could 'freeze' mgv7 and clone it as mgv8, then update v8 as needed.

**Comment by est31** [comment]
@juhdanad I could agree with such a way to approach this. Then there is a mapgen that can be tuned, and two which are 98% stable.

**Comment by paramat** [comment]
Don't worry, the biomes are just what is placed on the terrain, the terrain itself remains unchanged, and has been stable for a release cycle now.

**Comment by paramat** [comment]
The biomes may never be officially stable, however they have just been much improved and are in a good state.

**Comment by paramat** [comment]
@est31 hmmmm is neutral.

**Comment by garywhite207** [comment]
I think v7 should become default and v5 should get dumped as it is by now an old mapgen.

**Comment by paramat** [comment]
Actually mgv5 is much newer than mgv6 because it is a recoding of the original mgv5.

**Comment by C1ffisme** [comment]
@garywhite207 IMHO, v6 should be dumped for not supporting biome parameters and generating rathe bland terrain compared to v5 or v7.

**Comment by paramat** [comment]
Heh we cannot delete either, many worlds and servers use mgv6.

**Comment by paramat** [comment]
Since this is a very simple change that won't introduce bugs, it could be merged during feature freeze.
Currently waiting for more opinions.

**Comment by juhdanad** [comment]
I would like v7 to be the default one.

**Comment by tobyplowy** [comment]
@paramat +1 for v7 standard

**Comment by Amaz1** [comment]
:+1: for v7 as default

**Comment by garywhite207** [comment]
v7 is a much nicer mapgen

**Comment by paramat** [comment]
Updated first post with more information to make a stronger argument.

**Comment by maikerumine** [comment]
Please please make maphen v7 default.
V6 sucks, very badly and makes minetest look like garbage.

Raise of hands, who actually uses and likes v6?  I don't.

**Comment by ErrorNull0** [comment]
all i use is mapgen v7. i don't see enough benefits for v6 to ever go back.

**Comment by Fixer-007** [comment]
If you think v7 terrain is more or less stabilised than it is good idea to make it default, I like it.

**Comment by est31** [comment]
I think this PR is okay to get an exception from the feature freeze. MGv7 is well tested and with the stability promise :+1:

**Comment by SpaghettiDeveloper** [comment]
Use only mapgen v7, I created many maps with v7, I'm okay to enter the mapgen v7 default. . .

- Generate more beautiful worlds and advanced than the mapgen v6
- The mapgen v7 works very well and adds a lot of valuable content.

I vote for mapgen v7!

**Comment by octacian** [comment]
Even though I've played MT for over a year now, I just realized how much better mgv7 has become, and have finally switched over to it. To prevent something like this happening to new player, yes, mgv7 should become the default.

So, yeah, I vote mgv7.

**Comment by Thomas--S** [comment]
I also prefer v7.

**Comment by tenplus1** [comment]
V7 all the way.

**Comment by Gael-de-Sailly** [comment]
> Raise of hands, who actually uses and likes v6? I don't.

Many, many, many people use v6: those that are not curious enough to test other mapgens. They don't know what they miss.

I prefer v7 from far.

**Comment by NPXcoot** [comment]
We are in the v7 team!

**Comment by garywhite207** [comment]
Type +1 if you like V6, -1 if you don't

**Comment by tobyplowy** [comment]
+1000

**Comment by tobyplowy** [comment]
@garywhite207 +1 and +1000

**Comment by tobyplowy** [comment]
@garywhite207 v6 is not so good -1

**Comment by paramat** [comment]
> Type +1 if you like V6, -1 if you don't

Please don't, this is confusing, +1 should mean support for the PR.
This is not about how much you like mgv6, it's about whether you think mgv7 will make a better impression to newbies or reviewers.

**Comment by tobyplowy** [comment]
@paramat I think mgv7 will make a better impression on newbies and reviewers.

**Comment by sofar** [comment]
I'm making this my official :+1:. Since I started working with minetest, I've always used and played with v7, and whenever I fall back to v6 or something else, I'm just shocked at the scale of richness that the other mapgens do not have.

So, this is about time.

PS. I do agree that we'll have to consider v7 stable now.

**Comment by paramat** [comment]
On request of sfan5 i'm going to check tunnel width again, now before release, as he suggests it gets too narrow sometimes. I'll do this check before merging this.
The floatlands are not stable, and the registered biomes may never be, but the terrain is.

**Comment by paramat** [comment]
I flew 16000 nodes underground looking for narrow tunnels, only found 2 impassable passages. However it was my intention to avoid any impassable passages so i will see if i can very slightly widen the tunnels to avoid these.

**Comment by paramat** [comment]
Default is 0.2.
One passage becomes passable at 0.14 (smaller value = wider tunnel).

**Comment by paramat** [comment]
38abc91802ec12996d4fbb1e2f0ba4365d86b545

**Comment by sfan5** [comment]
@paramat 
Actually I wanted caves to be more than just walkable, I wanted them to have some space so it doesn't feel going through a small tunnel instead of caves (which I associate with larger air masses).

**However** I have tested `mgv7_cave_width = 0.09` and it produces absolutely perfect amount of space to walk through in caves.

**Comment by paramat** [comment]
@sfan5 yeah what i mean by passable is passable at their narrowest, their width varies a lot over large distances so doing this means tunnels are often wide and spacious, which i like. Thanks for the PR.

**Pull request closed without merging**
