### PR TITLE
Change light banks meaning

### LINKED ISSUE #5155: Change light banks meaning
Currently there are 2 light banks: day and night. That could be faster in the early days, but now both are used to compute actual lighting, and such split seems to only mess things up.
My suggestion is to split it in another way: sunlight and artificial light. This way, light update will be simpler; also many sunlight-detection quirks will be gone.
@sofar What do you think about this idea?

### PR DESCRIPTION
**Pull request by numberZero**
Fix #5155. Seems to work.
All the meshgen uses old-style light values (as they can always be reconstructed).

**WARNING:** converts the map to a new version. You will not be able to load the map in other Minetest versions. Making backup before testing is strongly recommended. (the conversion should always be reversible but MT can’t handle it. I wrote [a tool](https://github.com/numberZero/minetest-toolset) for that but it is barely tested and supports sqlite only).

## To do

This PR is Ready for Review. Let me know if I forgot anything.

## How to test

Play with various sunlight&artificial light combinations. Try using client from this PR with server from master or vice versa. If it looks right it is probably right but light testing tool (devtest) may also be helpful (pay attention to `param1`, first digit is artificial light, second digit is sunlight).

### CODE REVIEW

**Comment by Zughy** [comment]
@numberZero please rebase

**Comment by TurkeyMcMac** [comment]
Please rebase.

**Comment by TurkeyMcMac** [comment]
I think `LuaVoxelManip::l_set_lighting` also needs to be changed.

**Comment by TurkeyMcMac** [comment]
It seems the old light format is documented: https://github.com/minetest/minetest/blob/b3503e7853a52a8c16431f6b983e30c9d25951bc/doc/lua_api.txt#L1039-L1041

How much of a problem would this compatibility break be?

**Pull request closed without merging**
