### PR TITLE
Documentation: Clarify global and mapgen-specific mapgen flags

### PR DESCRIPTION
**Pull request by paramat**
Clarifies text and makes clear how the flag string modifies the engine flag defaults.

### CODE REVIEW

**Comment by kaeza** [comment]
Shouldn't this be added to `builtin/settingtypes.txt` and let builtin regenerate the other files?

**Comment by rubenwardy** [comment]
> Shouldn't this be added to builtin/settingtypes.txt and let builtin regenerate the other files?

Yes, it should be

**Comment by paramat** [comment]
Yes doing that next.

**Comment by paramat** [comment]
Updated.

**Comment by paramat** [comment]
6f325070dde739ab942286bd6e368930ea41cb42

**Pull request closed without merging**
