### PR TITLE
Password generator and selector

### PR DESCRIPTION
**Pull request by DeltaNedas**
Add compact, short information about your PR for easier understanding:

This draft PR/idea removes the password box when connecting to servers.
The client will generate, or use an existing, password for any username and server.

The generator randomly creates 64 visible ASCII characters for new passwords.
This gives great security where a normal player would likely pick an easily guessed/cracked one.
It also removes the burden of keeping a different password for each server and username.

**Need feedback and suggestions!**

## Todo

This PR is a **Work in Progress**
- [ ] *See if builtin can even use mod storage*
- [ ] Test that it always works as intended
- [ ] Make sure only the user or anything else with filesystem access is able to read stored passwords, not any unprivileged mods.
- [ ] Replace `Name / Password` in locale with just `Name`
- [ ] Make change password button not lock you out of a server

## How to test

1. Build or replace your tab_online.lua
2. Join some servers and look at the storage afterwards.
Key `pwd:server:username` is the key for a generated password

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
Sounds like it wouldn't work well if you wanted to log into the same server from both sides of a dualboot

What if you used the 'change password' button in the ESC field?

**Comment by DeltaNedas** [comment]
good point about change password, maybe i should add some way to manually override the generated password?

**Comment by LoneWolfHT** [comment]
> good point about change password, maybe i should add some way to manually override the generated password?

That sounds best. And to reply to IRC:

>  no it wouldnt, unless you used the same username and the server was a-ok with that, and you copied the storage

It's easy for me to copy to Linux from a Windows dualboot but if I want to access a Linux client's storage (I use Linux 95% of the time) I'll have to copy the storage to a USB and back again after booting into the Windows OS

**Comment by ClobberXD** [comment]
What if I create an account with a client and try to login from another client? Do I have to copy the password? What about logging in across devices? Personally, I think a password generator could be helpful, but it shouldn't take so much control over my logins.

**Comment by BuckarooBanzay** [comment]
> Servers each get their own password to prevent malicious servers from stealing passwords used on other servers and doing bad stuff.

Last time i checked minetest uses SRP (https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) for the password exchange, so a server-operator wouldn't even know your password.

**Comment by DeltaNedas** [comment]
edited

**Comment by SmallJoker** [comment]
How about base64-encoding the passwords, so that they're at least not searchable directly within files?

**Comment by paramat** [comment]
@DeltaNedas this PR has been inactive for 7 months. Please could you clarify why? Is it because you need feedback and suggestions to proceed?
If this is WIP but you have lost interest this should probably be closed as 'neglected'.
We will close this PR in 1 month if no response (according to dev rules).

**Comment by rubenwardy** [comment]
Closing WIP PR due to inactivity

**Pull request closed without merging**
