### PR TITLE
Don't cache active_block_range setting in a static

### PR DESCRIPTION
**Pull request by lhofhansl**

### CODE REVIEW

**Comment by paramat** [comment]
:+1: 
Split off from #4881 to merge immediately, approval was given there.

**Comment by est31** [comment]
This probably means a small performance regression, but the bugfix is more important.

**Comment by paramat** [comment]
See discussion http://irc.minetest.net/minetest-dev/2016-12-12#i_4761416 'static' has been wrongly added elsewhere too. There seems to be some debate whether this PR should be merged for release.

**Comment by lhofhansl** [comment]
Closing this one in favour of the bigger discussion that seems to be in order.

**Pull request closed without merging**
