### PR TITLE
Add persistent unique identifiers for objects

### PR DESCRIPTION
**Pull request by Desour**
- Goal of the PR: Assign each luaentity object a per-world-unique id that is persistent as long as the world exists, and make this id accessible in lua. Players also have an id, which uses their name.
- How it works:
  - The guid (global unique identifier) (a string) is generated by the GUIDGenerator (or created from the playername for players).
  - This generator has basically an unlimited precision integer, which it increments for each new guid.
  - A guid for luaentities looks like this: `"v1guid1005"` The `1` after `v` is a version num, to allow futuristic changes.
  - For players it looks like this: `"vpguidceleron55"`
  - (There are unittests for the genereator.)
  - The next guid for luaentites is stored over server restarts in `env_meta.txt`.
  - Objects from old worlds get a new id when loaded.
- Does it resolve any reported issue? maybe
- usecases: makes modding easier

## To do

This PR is a Ready for Review.

The one bugfix with the forced staticdata save is maybe a little bit ugly, feel free to suggest improvements.
The reason why it's needed is because the staticobject data doesn't change, because the guid is set in the constructor, and therefore the new guid isn't saved, I think.

## How to test

- Run the unitests.
- Use this small mod to inspect guids of objects:
<details>

```lua
local function printc(msg)
	print(msg)
	minetest.chat_send_all(msg)
end

--~ local branch_is_master = false
local branch_is_master = true

local function get_guid(obj)
	if branch_is_master then
		return "master,eh"
	else
		return obj:get_guid()
	end
end

minetest.register_craftitem("obj_info_staff:staff", {
	description = "Object info staff",
	groups = {},
	inventory_image = "default_tool_steelaxe.png",
	stack_max = 1,

	on_secondary_use = function(itemstack, user, pointed_thing)
		for _, o in ipairs(minetest.get_objects_inside_radius(user:get_pos(), 2)) do
			printc("objref guid: " .. tostring(get_guid(o) or nil))
		end
	end,

	on_use = function(itemstack, user, pointed_thing)
		if not pointed_thing or pointed_thing.type ~= "object" then
			return
		end
		local obj = pointed_thing.ref

		printc("objref guid: " .. get_guid(obj))
	end,
})


minetest.register_entity("obj_info_staff:ent", {
	initial_properties = {
		physical = false,
		collisionbox = {-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
		selectionbox = {-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
		pointable = true,
		visual = "cube",
		visual_size = {x = 1, y = 1, z = 1},
		textures = {},
		static_save = true,
	},

	on_activate = function(self, staticdata, dtime_s)
		printc("on_activate of "..get_guid(self.object))
	end,

	--~ on_step = function(self, dtime, moveresult),

	on_punch = function(self, puncher, time_from_last_punch, tool_capabilities, dir)
		printc("on_punch of "..get_guid(self.object))
	end,

	on_rightclick = function(self, clicker)
		printc("on_rightclick of "..get_guid(self.object))
	end,

	get_staticdata = function(self)
		printc("get_staticdata of "..get_guid(self.object))
	end,
})
```

</details>

### CODE REVIEW

**Comment by sfan5** [comment]
I strongly suggest using Type 4 UUIDs instead of inventing some weird(?) number-based thing(??).

**Comment by nerzhul** [comment]
we can create a UUIDv4 yeah, but how will it be indexed ? in postgresql there is a type, but others ?
We will need to store those entities as a separate thing no ? instead of being embedded in mapblocks ?

**Comment by sfan5** [comment]
I was thinking that since it's virtually impossible for an UUID to collide we can leave the ids "unmanaged" so to say.

**Comment by Desour** [comment]
What are the advantages of UUIDs over my guids?

**Comment by Desour** [comment]
I thought it would be useful if all objects would return a guid, so I've added something for players: "vpguid"+playername

**Comment by nerzhul** [comment]
> What are the advantages of UUIDs over my guids?

it's just a standard way to do unique identifier. It's better to stick with industry standards than invent our own.

Obviously we will need to embed a uuid generator.
If we use those things i really think we may need to have entities stored in their own way instead of being in the mapblock directly.

**Comment by rubenwardy** [comment]
> I thought it would be useful if all objects would return a guid, so I've added something for players: "vpguid"+playername

Players already have a universally unique ID: their name

**Comment by Desour** [comment]
> > What are the advantages of UUIDs over my guids?
> 
> it's just a standard way to do unique identifier. It's better to stick with industry standards than invent our own.

Is it really that special to use an incrementing number for identifiers? 
It looks like UUIDs are for parties not knowing each other to generate unique ids. But this is not what we need here, the ids only need to be unique inside one minetest world (having (not-minetest-)world-wide uniqueness too might be useful too, but was not explicitly requested yet), which is governed by one minetest instance. It is more important to be 100% sure not having collisions, imo. Also, generating ids by counting is super simple and fast.

> > I thought it would be useful if all objects would return a guid, so I've added something for players: "vpguid"+playername
> 
> Players already have a universally unique ID: their name

Yes, but you can't mix playernames with the guids of luaentites. A player could name themselves "v1guid1234" to cause a collision.

**Comment by sorcerykid** [comment]
When it comes to uniquely identifying objects, I believe this is already possible without significant changes to the engine:

* For players, a unique and persistent ID can be obtained via obj:get_player_name()
* For entities, a unique and persistent ID can be serialized within the static data string and restored upon activation.

Admittedly, it might be worthwhile to provide an application-wide API for generating IDs incrementally, perhaps by means of a helper class. But I think that incorporating such functionality directly into LuaEntitySAOs is a bit too specialized.

After a bit of brainstorming, this is what I came up with for a rudimentary API:

* **UniqueIDGenerator(category)**  
Return a handle to the unique ID generator for the given category. It is permissible to call this function multiple times, and it will simply return a handle to the same object. Categories names may consist of alphanumeric characters and underscores. Forward slashes can optionally be used to designate hierarchical categories; e.g. "entities/mobs"

* **UniqueIDGenerator::next()**  
Increment the category counter and return the next unique ID as a string; i.e. "entities/mobs/1035"

* **UniqueIDGenerator::next_raw()**  
Increment the category counter and return the raw value as an integer; i.e. 1035

* **UniqueIDGenerator::last()**  
Return the last unique ID of the category as a string; i.e. "entities/mobs/1034"

* **UniqueIDGenerator::last_raw()**  
Return the raw value of the category counter as an integer; i.e. 1034

The counter values can be stored in the "env_meta.txt" file in the following format:

```
unique_ids = entities/mobs~1035;
```
Of course, this idea is a WIP, and still in need of refinement. I'm more than open to feedback and suggestions. But I feel confident that an API such as this would be more versatile for modding in the long-term, beyond just entity management.

**Comment by Desour** [comment]
@sorcerykid Most of what you suggested is pretty much exactly what already happens in this PR.

I'm not sure what categories would be good for, except for making ids more human-readable.

>- UniqueIDGenerator::next_raw()
Increment the category counter and return the raw value as an integer; i.e. 1035

What exactly would this be needed for? Also, if we limit ids to a max of 2^64 or something, people will complain about it, the same way as they complain about too small maps, and we couldn't easily waste quadrillions of ids.

Thinking about it, it might be useful to expose the id generator to lua (not the seed function though), and use one generator for everything. The generator is just bound to luaSAOs because I currently don't see any other usecase in the engine.

People will probably request features such as a `get_object_by_guid` function or the ability to lookup unloaded static entities. I thought that could be done in a follow-up PR. And doing it in this PR is not worth the effort if coredevs dislike counted ids anyways. `¯\_(ツ)_/¯`

Btw., another idea that I'm having is that we generate ids by combing a counter value with a random UUID: When generating a new id, count the counter, and generate a new UUID and return `"v1guid"..counter..","..UUID`. This would combine the advantages of both id types, guaranteed absence of collisions in a world and very probable inter-world uniqueness, and one could still not easily find the world for a given id.

**Comment by Desour** [comment]
Lost interest.

**Pull request closed without merging**
