### PR TITLE
Add "ccache" for better compiling performance.

### PR DESCRIPTION
**Pull request by maciejczyzewski**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Were you able to measure the speed difference of the compiler before and after?

**Comment by maciejczyzewski** [comment]
> The performance of ccache depends on a lot of factors, which makes it quite hard to predict the improvement for a given use case.

https://ccache.samba.org/performance.html

Disabled:

```
$ export CCACHE_DISABLE=1
$ cmake . -DRUN_IN_PLACE=TRUE -DSKIP_CCACHE=TRUE
$ # changes into source code (reverse 10 commits)
$ time make -j1
$ # 376.03s user 26.97s system 95% cpu 7:03.38 total
```

Enabled:

```
$ export CCACHE_DISABLE=0
$ cmake . -DRUN_IN_PLACE=TRUE
$ # changes into source code (reverse 10 commits)
$ time make -j1
$ # 364.31s user 23.89s system 96% cpu 6:43.45 total
```

**Comment by nerzhul** [comment]
the difference is not interesting. 10sec gain over 6min isn't sufficient to add a new dep. if we want to speedup only ajust core numbers

**Comment by maciejczyzewski** [comment]
Ccache is default (there is no need to add dep). I added this pull request because on some distr. of linux ccache is not linked properly. https://travis-ci.org/minetest/minetest/jobs/166047146#L540

**Comment by sfan5** [comment]
This adds a huge load of warnings to travis builds, hell no

:-1:

**Comment by HybridDog** [comment]
Wouldn't this significantly speed up rebuilding after switching branches?

**Pull request closed without merging**
