### PR TITLE
World space line renderer

### PR DESCRIPTION
**Pull request by hecktest**
Feature requested by #10593 with additional bells and whistles.

## To do

This PR is a Work in Progress
- [x] Line rendering itself
- [ ] ObjectRef visual mode
- [ ] ObjectRef hosted mode (convenient, but technically redundant)
- [ ] Attaching the endpoint to ObjectRefs and bones
- [ ] World space HUD element mode
- [ ] fix formatting
- [ ] add license pasta

As far as I understand, persistent attachment is currently impossible in Minetest and thus any object-to-object lines may not survive a server reboot.

## How to test

Set the visual of an entity to "line". The entity's texture will be used, everything else is mocked up at the moment as I figure out where and how to store this stuff.

### CODE REVIEW

**Comment by hecktest** [comment]
Question to gurus: what happens to an object that gets out of a player's range? Does it just get deleted client side?

**Comment by sfan5** [comment]
> what happens to an object that gets out of a player's range? Does it just get deleted client side?

Basically yes. The server sends the client a packet indicating that that object was removed and the client will do so, this is indistinguishable from an object being deleted for real.

**Comment by hecktest** [comment]
Guess I have no choice but to hide the line until the target reappears.

**Comment by metacoma** [comment]
> Guess I have no choice but to hide the line until the target reappears.

hey @hecktest! how it's going? I am very interested in this feature

**Comment by hecktest** [comment]
@metacoma 
Sorry, I've been sidetracked by bugfixes.
I'm trying to think of a sane API and rules for this to avoid problems like #4624 from the very beginning. The rendering was the easy part, but the data model needs careful design.

**Comment by metacoma** [comment]
> Sorry, I've been sidetracked by bugfixes.
> I'm trying to think of a sane API and rules for this to avoid problems like #4624 from the very beginning. The rendering was the easy part, but the data model needs careful design.

Okay, got it, thank you for the update! 🤝

**Comment by mewnst** [comment]
> @metacoma
> Sorry, I've been sidetracked by bugfixes.
> I'm trying to think of a sane API and rules for this to avoid problems like #4624 from the very beginning. The rendering was the easy part, but the data model needs careful design.

I really love this feature and decided to contribute a little to its BountySource bounty. Thanks for the hard work!

**Comment by rubenwardy** [comment]
Possible close due to inactivity, I would like to see this though

**Pull request closed without merging**
