### PR TITLE
Player collisionbox: Raise top to match player height

### PR DESCRIPTION
**Pull request by paramat**
Box height 1.75 -> 1.77.
////////////

screenshot_20170719_150242

Addresses #6152

### CODE REVIEW

**Comment by stujones11** [comment]
Seems trivial enough but can we be sure there are to 1.75 high passage/door ways that would become impassable? I'd say it's best left alone, at least until settable collision boxes are a thing.

**Comment by paramat** [comment]
If there are they will be very very rare, 0.5 gives us a good excuse for a minor breakage and to match it to model height, otherwise it looks sloppy..

**Comment by stujones11** [comment]
See my comments in #6152, the height of 1.75 seems to be correct, the reason it protrudes the collision box is because the player if floating slightly above the ground.

**Comment by paramat** [comment]
Ahh the hair, of course.

**Comment by nerzhul** [comment]
player collision box settable should be added to 0.5 too

**Comment by paramat** [comment]
Yeah the PRs for settable colisionbox are ready to go.

**Comment by paramat** [comment]
This may be applied in #6007

**Comment by SmallJoker** [comment]
#6007 merged.

**Comment by lhofhansl** [comment]
Hmm... Other players look like they 1/2 in the ground and even looking at the same player (F7) shows the same.
Server and client(s) both just recompiled.

**Comment by lhofhansl** [comment]
game is also up-to-date

**Comment by lhofhansl** [comment]
Oh... It's the [playeranim](https://github.com/minetest-mods/playeranim) mod.

**Comment by lhofhansl** [comment]
Break MineClone2 in the same way.

**Comment by lhofhansl** [comment]
Actually it's #6007 not this one. Sorry.

**Pull request closed without merging**
