### PR TITLE
Fix GCC class-memaccess warnings

### LINKED ISSUE #8292: Warning about “writing to an object of type 'struct NoiseParams' with no trivial copy-assignment” in file src/noise.cpp when compiling
##### Issue type

 - Build issue
 
##### Minetest version

```
$ git rev-parse HEAD
111f1dc9c5f336f5b4f12c15940dc4cc2cbe7f82
```

##### OS / Hardware

Operating system: Linux 4.20.6-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

GNU Make 4.2.1
cmake version 3.13.4

##### Summary
When compiling Minetest as described in the readme at one point the following warning appears.

```
/home/dirk/test/minetest/src/noise.cpp: In constructor 'Noise::Noise(NoiseParams*, irr::s32, irr::u32, irr::u32, irr::u32)':
/home/dirk/test/minetest/src/noise.cpp:432:29: warning: 'void* memcpy(void*, const void*, size_t)' writing to an object of type 'struct NoiseParams' with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  memcpy(&np, np_, sizeof(np));
                             ^
In file included from /home/dirk/test/minetest/src/noise.cpp:27:
/home/dirk/test/minetest/src/noise.h:103:8: note: 'struct NoiseParams' declared here
 struct NoiseParams {
        ^~~~~~~~~~~
```

##### Steps to reproduce
1. Compile the latest available version (when writing this it’s 111f1dc9c5f336f5b4f12c15940dc4cc2cbe7f82)
2. Watch the build output

### LINKED ISSUE #10237: gcc warning: -Wclass-memaccess in mapblock_mesh.cpp getNodeVertexDirs
Hello, just found a warning while compiling

## Issue type

- Build issue
- commit: 3ce03d1c2a63d261c83f5962cd13212697f19472
- related to #8292, and #8117 (maybe others)
- Possible already merged fix on another instance of the warning: #8122

## Gcc version
gcc:
```
g++ --version
g++ (Ubuntu 10.1.0-2ubuntu1~18.04) 10.1.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
## Warning
Here the warning:
```
[ 37%] Building CXX object src/CMakeFiles/minetest.dir/client/mapblock_mesh.cpp.o
minetest/src/client/mapblock_mesh.cpp: In function ‘void getNodeVertexDirs(const v3s16&, v3s16*)’:
minetest/src/client/mapblock_mesh.cpp:422:64: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘v3s16’ {aka ‘class irr::core::vector3d<short int>’} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  422 |  memcpy(vertex_dirs, &vertex_dirs_table[idx], 4 * sizeof(v3s16));
      |                                                                ^
In file included from minetest/src/irr_v3d.h:24,
                 from minetest/src/irrlichttypes_bloated.h:25,
                 from minetest/src/irrlichttypes_extrabloated.h:22,
                 from minetest/src/client/mapblock_mesh.h:22,
                 from minetest/src/client/mapblock_mesh.cpp:20:
/usr/include/irrlicht/vector3d.h:22:8: note: ‘v3s16’ {aka ‘class irr::core::vector3d<short int>’} declared here
   22 |  class vector3d
      |        ^~~~~~~~
```

## Affected code

 https://github.com/minetest/minetest/blob/5311a275235d2132443643199330953c877b794a/src/client/mapblock_mesh.cpp#L404-L422

If the fix is not to hard, and if it's possible I can be mentored to fix it. :)

Edit: Removed "personnal" part of the paths for clarity.

### PR DESCRIPTION
**Pull request by pauloue**
Fixes #10237, fixes #8292

### CODE REVIEW

**Comment by sfan5** [comment]
With this change both GCC and Clang generate significantly more code for `getNodeVertexDirs`:
Bildschirmfoto_2020-07-29_20-48-28

The compiler is correct that the code bypasses the copy constructor defined in [vector3d.h](https://github.com/minetest/irrlicht/blob/master/include/vector3d.h#L32), but this is done intentionally. Therefore the correct fix is to disable the warning for this code, not to change the code.

**Comment by pauloue** [comment]
Thanks, I can confirm. `std::copy` uses the the copy assignment operator in a for loop.
2020-07-30T12:28:13,676110957-04:00
The following macro mess disables the warning for GCC while avoiding an unrecognized pragma warning for clang which doesn't have -Wclass-memaccess. 
```cpp
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wclass-memaccess"
#endif
       memcpy(vertex_dirs, &vertex_dirs_table[idx], 4 * sizeof(v3s16));
#if defined(__GNUC__) && !defined(__clang__)
#pragma GCC diagnostic pop
#endif
```

**Comment by SmallJoker** [comment]
Would it be possible to drop the `#if` checks? Other compiles should not listen to unknown `#pragma`s.

**Comment by pauloue** [comment]
clang generates this warning:
```
src/client/mapblock_mesh.cpp:424:32: warning: unknown warning group '-Wclass-memaccess', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wclass-memaccess"
```

**Comment by orbea** [comment]
This is not a fix, this is a hack...

**Comment by sfan5** [comment]
How do you think a "fix" should look then?

**Comment by orbea** [comment]
A fix should fix the warnings, not hide them.

**Comment by pauloue** [comment]
A warning is just a warning, not a bug, and they are sometimes false positives. GCC generates this warning because vector3d defines a copy assignment operator which could do something other than the default of just copying the memory. It doesn't, so it's perfectly safe to use memcpy, which is faster than copying each vector individually.

**Comment by orbea** [comment]
If its truly a gcc bug it should be ignored and then reported upstream so it can be fixed. At the very least it should be guarded for specific gcc versions so its not used everywhere even when its not needed.

I would suggest leaving preproccesor hacks only for deal breaking compiler issues, for example an infinite compile loop or a segfault while building.

**Comment by SmallJoker** [comment]
@orbea Compiler warnings are hints for programmers to ensure the code will work as intended. Usually such warnings should be respected and the suggested actions applied.
In this case, the compiler is _technically_ right about the non-trivial type. Please have a look at `vector3d<s16>`: it's three trivial variables of the same type with helper functions. This will likely never change. For any other class this compiler warning would be appropriate - just not for this "trivial class".

**Comment by orbea** [comment]
Trivial or not it should be fixed if the compiler is right, not swept under the rug. Best case scenario this is a terrible precedent.

**Comment by Desour** [comment]
I'm getting compiler warnings:
```
src/client/mapblock_mesh.cpp:424:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wclass-memaccess"
                                ^~~~~~~~~~~~~~~~~~~
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Pull request merged**
