### PR TITLE
Makefile change

### PR DESCRIPTION
**Pull request by MoNTE48**
ARMv7 default build
Update curl
Update OpenSSL

### CODE REVIEW

**Comment by Zeno-** [comment]
looks ok to me
:+1:

**Comment by est31** [comment]
it builds fine (with usual android build problems).

**Comment by nerzhul** [comment]
Ok for me too

**Comment by MoNTE48** [comment]
ARMv7 build much faster ARM. Now I have 60 FPS (on ARM 25) and download speed card above 2 times. Galaxy Note Pro 12.2

**Comment by Zeno-** [comment]
commit c788b1732225ed0c118ed11b184bb5d3b35e1f7c

**Pull request closed without merging**
