### PR TITLE
Support IrrLicht 1.9 (again)

### PR DESCRIPTION
**Pull request by numberZero**
There are some more changes in IrrLicht 1.9/ogl-es, as of https://github.com/MoNTE48/irrlicht. The one with `ZWriteEnable` is tricky: field type was changed without version change; fortunately `setFlag` still works.

### CODE REVIEW

**Comment by sfan5** [comment]
See also #10729 or https://github.com/minetest/minetest/compare/master...sfan5:irr19 (from issue #10763).

Did you test this? I have found that access to `exposedData.OpenGLLinux.X11Display` is broken on Linux with Irrlicht 1.9.

**Comment by nerzhul** [comment]
@minetest/engine we should really define what we want to do with irrlicht for next release.
Support the mainline which is broken on some OS since ages ?
Use 1.8.4, modify & backport interesting changes from irrlicht mainline ?
I suggest that we open a discussion somewhere about it.

**Comment by numberZero** [comment]
> Did you test this? I have found that access to exposedData.OpenGLLinux.X11Display is broken on Linux with Irrlicht 1.9.

Ugh, I tested it with my own [Irrlicht fork](/numberZero/irrlicht) where I fixed that... (the problem was that Irrlicht authors didn’t realize that GLX window id is *not* an X11 window id, and stored the former in the `X11Window` field).

> Support the mainline which is broken on some OS since ages ?
> Use 1.8.4, modify & backport interesting changes from irrlicht mainline ?

But... it is forked already) The primary reason is simple: OpenGL ES support is still not in trunk, after **12 years** of development, so Android version can’t use mainline Irrlicht. And you’re developing another fork based on SDL2. So the next step is obvious: merge all the useful parts into IrrlichtMT)

**Comment by sfan5** [comment]
> I tested it with my own Irrlicht fork where I fixed that... (the problem was that Irrlicht authors didn’t realize that GLX window id is not an X11 window id, and stored the former in the X11Window field).

Good to hear we have a fix.

**Pull request closed without merging**
