### PR TITLE
Add sized labels and text alignment to various FormSpec elements

### PR DESCRIPTION
**Pull request by v-rob**
Adds `halign` and `valign` properties to align text in buttons, textareas, and sized labels as well as just `halign` in fields and pwdfields.  This also adds sized labels of the form `label[<X>,<Y>;<label>;<W>,<H>]` and increases the formspec version number to 4 as a result.

Fields and pwdfields don't have `valign` because a) it isn't really useful and b) it isn't natively supported in Irrlicht anyway for some reason.

image

## To do

This PR is Ready for Review.

## How to test

When using the screenshot code, also mess around with newlines and long lines of text to make sure Irrlicht's alignment works right.
<details><summary><b>Screenshot Code</b></summary>

```
formspec_version[3]
size[12,8]

style[left;halign=left]
style[hcenter;halign=center]
style[right;halign=right]
style[top;valign=top]
style[vcenter;valign=center]
style[bottom;valign=bottom]

button[1.5,0;3,1;;Default]
button[0,1;3,1;left;Left]
button[0,2;3,1;hcenter;Center]
button[0,3;3,1;right;Right]
button[3,1;3,1;top;Top]
button[3,2;3,1;vcenter;Center]
button[3,3;3,1;bottom;Bottom]

container[6,0]
textarea[1.5,0;3,1;def;;Default]
textarea[0,1;3,1;left;;Left]
textarea[0,2;3,1;hcenter;;Center]
textarea[0,3;3,1;right;;Right]
textarea[3,1;3,1;top;;Top]
textarea[3,2;3,1;vcenter;;Center]
textarea[3,3;3,1;bottom;;Bottom]
container_end[]

container[0,4]
field[0,0;3,1;def;;Default]
field[0,1;3,1;left;;Left]
field[0,2;3,1;hcenter;;Center]
field[0,3;3,1;right;;Right]
container_end[]

container[3,4]
pwdfield[0,0;3,1;def;]
pwdfield[0,1;3,1;left;]
pwdfield[0,2;3,1;hcenter;]
pwdfield[0,3;3,1;right;]
container_end[]

container[6,4]
box[3,0;3,1;#000]
label[0,0;Default;3,1]
style_type[label;halign=left]
box[0,1;3,1;#000]
label[0,1;Left;3,1]
style_type[label;halign=center]
label[0,2;Center;3,1]
style_type[label;halign=right]
box[0,3;3,1;#000]
label[0,3;Right;3,1]
style_type[label;halign=;valign=top]
label[3,1;Top;3,1]
style_type[label;valign=center]
box[3,2;3,1;#000]
label[3,2;Center;3,1]
style_type[label;valign=bottom]
label[3,3;Bottom;3,1]
container_end[]
```
</details>

### CODE REVIEW

**Comment by v-rob** [comment]
OK, I changed my mind; seeing as no one has even touched this PR and it's super basic as it was, I went and added sized labels with alignment.  Unlike my earlier PR, there is only normal alignment like everything else, and there is no newline spacing, `*line` options, or anything of that sort, and it is actual alignment.  As such, it is much simpler.  It goes by the form of
```
label[<X>,<Y>;<text>;<W>,<H>]
```
Width and height are after the text so older clients can render the text, although they won't size or align it right.  The formspec version was bumped to 4 as well, of course.

(I would suggest hiding whitespace changes in GitHub.  It butchers it otherwise)

**Comment by v-rob** [comment]
OK, I changed my mind; seeing as no one has even touched this PR and it was super basic as it was, I went and added sized labels with alignment.  Unlike my earlier PR, there is only actual alignment like everything else, and there is no newline spacing, `*line` options, or anything of that sort.  As such, it is much simpler.  It goes by the form of
```
label[<X>,<Y>;<text>;<W>,<H>]
```
Width and height are after the text so older clients can still render the text, although they won't size or align it right.  The formspec version was bumped to 4 as well for the new parameter, of course.

(I would suggest hiding whitespace changes in GitHub.  It butchers it otherwise)

**Comment by v-rob** [comment]
Good ole' Irrlicht had a problem with bottom alignment for StaticText where it would cut off any newlines, only showing the first line.  This has been fixed.

**Comment by v-rob** [comment]
Since #9496 has been merged, might I suggest that this be added to the 5.4.0 milestone as well because this increments the formspec version to 4 as well?

**Comment by pyrollo** [comment]
> ```
> label[<X>,<Y>;<text>;<W>,<H>]
> ```
> Width and height are after the text so older clients can still render the text, although they won't size or align it right.  The formspec version was bumped to 4 as well for the new parameter, of course.

I feel like it's a mistake to have W and H at the end. Historical reasons almost always prove to be bad reasons after a while.
It would complicate the code a bit to have both syntax (`[X,Y;W,H;Text]` and `[X,Y;Text]`) but I'm pretty sure it's better in long term.

Apart from that aspect, Yeah! At last a sized label :+1:

**Comment by v-rob** [comment]
TBH, I'm not especially worried about the syntax for this.  Formspecs already have a very inconsistent syntax, and I feel that this wouldn't make much difference.  I can change it if you think it's that important, but imagine the confusion of a user on an older client that sees `3,1` on their screen instead of `Text` because the label is defined like `label[1,1;3,1;Text]`.

Hopefully, we'll have a formspec replacement in the future which fixes everything anyway (ooh, JSON serialization sounds soo nice).

**Comment by pyrollo** [comment]
> Hopefully, we'll have a formspec replacement in the future which fixes everything anyway (ooh, JSON serialization sounds soo nice).

Sounds good, just hoping future is not to far away :)

**Comment by SmallJoker** [comment]
Needs rebase and formspec version bump to support all clients properly

**Comment by v-rob** [comment]
Closing; see https://github.com/minetest/minetest/pull/10291#issuecomment-770002906.

**Comment by kilbith** [comment]
Please re-open.

**Comment by v-rob** [comment]
Seems useful enough for the amount of code to be reopened.  I'll fix it up again and reopen when I can.

**Comment by kilbith** [comment]
I'm still interested in these features.

**Comment by kilbith** [comment]
@Df458 if it isn't too much asking you, I'd like it to be merged also.

**Comment by Df458** [comment]
Just leaving a note here that while my health is no longer a major factor blocking the work, for various other reasons I will not be continuing my work on the rebase of this PR. I apologize to anyone who was looking forward to this functionality, and given its clear utility I hope someone else out there picks it up in time.

**Pull request closed without merging**
