### PR TITLE
Display an access denied message when client detects a server timeout

### PR DESCRIPTION
**Pull request by kahrl**

### CODE REVIEW

**Comment by nerzhul** [comment]
:+1: for me

**Comment by est31** [comment]
:+1: looks good.

**Comment by est31** [comment]
Will test whether it works, please wait.

**Comment by est31** [comment]
I've tested it twice, one time it worked, the other time there was a crash. It might be unrelated, I'm not sure.

**Comment by est31** [comment]
Tested it three additional times, it worked all 3 times. Sometimes minetest crashes for me when I leave to main menu, so I guess its not related. Ok for merge.

**Comment by kahrl** [comment]
9c76f379acb12246fb1e282661e67b9da4cdcb62

**Pull request closed without merging**
