### PR TITLE
Improve menu_header.png slightly

### PR DESCRIPTION
**Pull request by Desour**
As suggested in <https://github.com/minetest/minetest/pull/15294#discussion_r1805100586>.

* 3D shaded cubes, instead of drop shadows.
* Selection box as cute little detail.

master:
master

PR:
pr2

PR (old version, brighter, with selection box):
pr old

I don't expect this design to stay for many versions. But I think it's nicer than the current one.

## To do

This PR is a Ready for Review.

## How to test

:eye: :tongue:  :eye:

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]
this is very cool

**Comment by cx384** [comment]
I like the 3D shaded cubes.
The selection box detail looks a little weird to me, but maybe this is a good thing.

**Comment by sfan5** [comment]
Let's just remove the selection box then because I think the 3d cube shading adds a very fitting touch to the (temporary) logo.

**Comment by grorp** [comment]
-1 for the selection outline from me, otherwise OK

**Comment by Desour** [comment]
Removed the selection box. And made the dark sides darker.

**Review by Zughy — APPROVED** [review]

**Comment by swagtoy** [comment]
Fix the kerning on the "T" please, it's too far away from "n" to me. Maybe the "i" too, but not sure.

**Review by grorp — APPROVED** [review]

**Comment by Desour** [comment]
> Can you fix the kerning on the "T" please? it's too far away from "n" to me. Maybe the "i" too, but not sure.

I think the font grorp used decided about the kerning.
Also it looks fine to me. :shrug: 
And this image is still only meant to be temporary. It's not perfect at all.

**Pull request merged**
