### PR TITLE
Replace vector<bool> with vector<char>

### PR DESCRIPTION
**Pull request by gregorycu**
vector<bool> is very slow on windows debug, especially in this hotpath. I'm not sure the size optimisation we get with vector<bool> is useful at all.

### CODE REVIEW

**Comment by est31** [comment]
Can you try to create a struct with all the bools and the aabb3f as its elements? Then only one vector is required. Is it faster than vector<char>?

**Comment by est31** [comment]
Other than that, it makes sense that vector<char> is faster here.

**Comment by sapier** [comment]
Does this only apply to windows debug build or is same performance penalty for othersm especially for release builds too?

According to this one: https://isocpp.org/blog/2012/11/on-vectorbool there can be a huge difference in speed depending on actual implementation of vector<bool> ... yet I haven't tested it so I can't be sure he's right

**Comment by gregorycu** [comment]
You should know if it effects your platforms release build in the same way.
Performance takes like a 20x to 50x performance hit.

I don't mind changing the code so that only uses char in Windows debug.

The suggestion above about combining the three bools into one struct may
also be better.

**Comment by nerzhul** [comment]
:-1: debug builds are not dedicated to performance.

**Comment by gregorycu** [comment]
It's unplayable.

**Comment by gregorycu** [comment]
By the way, that's a pretty dumb comment. You think I don't know what debug
builds are for?

**Comment by est31** [comment]
The idea was to combine all of `cboxes`, `is_unloaded`, `is_step_up`, `bouncy_values`, `node_positions` and `is_object` into one struct.

**Comment by ShadowNinja** [comment]
I implemented @est31's suggestion here: https://github.com/ShadowNinja/minetest/tree/collision-struct-speed-improvement  Haven't tested the speed though.

**Comment by kwolekr** [comment]
vector<bool> is a bunch of crap, I can't help but agree with gregory here.  +1 from me.

**Comment by est31** [comment]
I :+1: @ShadowNinja 's implementation it is even better than `vector<char>`.

**Comment by kwolekr** [comment]
Is this PR still relevant, or has it been superceded by ShadowNinja's implementation?
@gregorycu, could you test that branch to see if it solves the issue just as well?

**Comment by gregorycu** [comment]
I'm withdrawing this as ShadowNinja's implementation will be as fast, and better structured.

**Comment by est31** [comment]
Have you tested it? knowing that it is just as fast would be good :)

**Comment by gregorycu** [comment]
Unless it uses a vector<bool> somewhere it will (comparably) be fast enough. My goal wasn't to make Debug under Windows fast. It was to make it playable. I don't think people understand how slow using a vector<bool> on Windows Debug in a hot path is :)

**Comment by ShadowNinja** [comment]
This should probably stay open until one of the patches is merged, so this isn't forgotten.

**Comment by paramat** [comment]
#4076 merged.

**Pull request closed without merging**
