### PR TITLE
Rewrite falling entity + another feature

### LINKED ISSUE #4781: Falling nodes can be used to break protected blocks.
This is because the `on_step` function of `__builtin:falling_node` does not check if the node it will replace is protected when it lands and converts itself to a real node. This allows players to "sand bomb" players' gardens on multiplayer servers by bridging over them and dropping sand or another falling node off the side.

I have fixed this on my own server by overriding the `__builtin:falling_node` definition and making it call `minetest.is_protected()`. If the node it will replace is protected (and is not air), the falling node drops itself as an entity. I'm not sure if this is legal from a code perspective, but it works. It does require me to update the definition whenever a bugfix is introduced to the definition that exists in core.

I wonder if the original behavior is official and expected, and whether modders are expected to override this entity definition if they need to, or whether my fix is likely to break due to being an undocumented hack.

I am not aware whether using `minetest.register_entity()` to override builtin entities is allowed. It would be nice if this became an official part of the API, or failing that, it would be great if `__builtin:falling_node` respected protection by default.

### LINKED ISSUE #5313: Items drop when a stack of falling nodes impacts ground at high speed
If you have a large stack of falling nodes (such as sand), and then dig a solid node below it (such as dirt) so that all the falling nodes fall down a deep hole, it is likely some of the falling nodes will drop as items instead of properly becoming nodes at the end again.
When you make 10 nodes fall at a height of 10 nodes, usually at least one item drops, so that only 9 nodes appear at the bottom. This number appears to vary often.

You can see good screenshots here:
https://forum.minetest.net/viewtopic.php?f=6&t=16702

Tested in version 0.4.15. Happens in all subgames I've played so far without exception.

### LINKED ISSUE #9293: Falling nodes fall infinitely on overhigh collisionbox
##### Minetest version
```
5.1.0
```

##### Summary
When a falling node falls on a node with an overhigh collision box (i.e. upper collision box Y > 1.0), the falling node stops (because it collides), then it teleports a short distance upwards, then falls again, and stops again at the overhigh collisionbox, etc. In other words, the falling node is stuck in an infinite loop. This is really bad.

##### Steps to reproduce
1. Place a node with an overhigh collisionbox
2. Make a node above it fall on it

You can use `devtest` <https://git.minetest.land/Wuzzy/devtest>.

##### Additional context
#6985 attempted to fix this, but failed. The solution in this PR was bad.

### LINKED ISSUE #9787: Collision info should contain references to collided objects.
## Problem

Recently, the on_step function has a new argument, the collision info. It's nice but one serious thing is missing. When the object collides with another object, it only receives that it has collided with A OBJECT but it doesn't get any information about what kind of object it is. It is quite common in games that colliding with different objects has different results. For example, when an arrow hits an animal, it should damage only the hit animal. If you do it vice-versa, the animal has to know somehow that it was hit by an arrow and not by a different object. Currently, there's no way to do this in any of those two ways.

## Solutions

Add a reference to the collided object into the collision info.

## Alternatives

I don't see any alternative solution here.

## Additional context

SuperTux :D https://github.com/SuperTux/supertux/blob/master/src/collision/collision_listener.hpp

EDIT by SmallJoker: Fix link.

### PR DESCRIPTION
**Pull request by sfan5**
<b>don't squash</b>

first commit: fixes #9787
second commit: fixes #4781, fixes #9293
third commit: fixes #5313

## To do

This PR is a Ready for Review.

## How to test

1 Drop sand on:
* a door
* a slab
* snow cover
* a torch
* a normal node

2 Run `//lua core.registered_nodes["default:gravel"].groups.float = 1` and drop gravel on water

3 Drop sand inside protected area (should drop as item instead of placing)

4 Create a high stack of sand and let it fall

5 Let sand fall on a players head

6 Find a falling & leveled node and let it fall on a node of the same type

7 Drop sand on a node with `walkable = false` and `diggable = false`

### CODE REVIEW

**Comment by sfan5** [comment]
In its current state the PR makes #8307 much worse, since by the time the bottom falling nodes has been placed the top one has often already entered the space where the bottom node belongs.
Suggestions appreciated.

**Comment by TheTermos** [comment]
Have you tried `collide_with_objects`? Should be a bit faster now.

**Comment by sfan5** [comment]
I have and that does fix it, but not sure if we want falling nodes sitting on the player's and/or mobs' head.

**Comment by paramat** [comment]
So this fixes #4781 ?
Please could you list the resolved bugs/issues?

**Comment by sfan5** [comment]
The reference to fixed bugs is inside the commit description, I have now added it to the PR description too.

**Comment by TheTermos** [comment]
> first commit: fixes #9787

This is huge.
Does it also work in lua for players, who collide with caos rather then saos?

**Comment by sfan5** [comment]
> Does it also work in lua for players

Yes, a player is ServerActiveObject like any other.
(Any CAO handling applies to the client only.)

**Comment by TheTermos** [comment]
I meant I think what really happens to player is decided clientside rather than serverside, so results obtained from player SAO aren't always correct. Hopefully that's not going to be a big deal.

How do I access player's moveresult in lua?

**Comment by sfan5** [comment]
Oh, I suspected you meant something different.
The moveresult is only computed for Lua entities, a player can show up in there. The server does not perform collision detection for players, so you can't retrieve a players moveresult. Such a thing could easily be added to CSM though.

**Comment by sfan5** [comment]
Video of the new falling sand stacks behaviour: https://0x0.st/i2zr.mp4
Sand will still fall through a players head.

**Comment by TheTermos** [comment]
> The server does not perform collision detection for players, so you can't retrieve a players moveresult.

Had my hopes up for a moment there.
On a side note: maybe there's something that could be done about it? There are big problems with high velocity head on player-object collisions, they often pass through each other and it can't be solved by collision detection. (ranged weapons anyone?)
Maybe serverside player collision could help working around that.

**Comment by nerzhul** [comment]
rebase is needed

**Pull request merged**
