### PR TITLE
FreeType: address font license issue, remove non-freetype builds.

### PR DESCRIPTION
**Pull request by sofar**
It appears we were shipping font files without license text,
and I had my doubts about the bitmap fonts being usable directly.

A logical solution therefore presents itself:

1) remove non-freetype builds support. This removes the bitmap
fonts entirely (which helps to reduce size).

2) replace existing TTF fonts with Apache-2.0 licensed fonts
from chome core (Cousine, Arimo, Tinos). Include the full
license file for all three fonts.

This addresses the concerns and refreshes the font look of minetest
with better readable fonts (these are a logical evolution of
screen font evolution).

### CODE REVIEW

**Comment by MoNTE48** [comment]
I always wondered why Minetest need 3 font? :)

**Comment by sfan5** [comment]
:-1: Keep the possiblity of non-freetype

**Comment by sofar** [comment]
@sfan5 one of the non-ttf fonts AFAICS isn't something we can ship legally, so we have to remove it irregardless. Now, I can't make the pleistocene irrlicht font tool work, and instead of relying on ancient bit rot junk, we should stop shipping 9.4 megabytes of dead weight.

So, either someone replaces lucida sans bitmaps, or we just nuke it and remove the massive space that these bitmapped fonts consume.

**Comment by red-001** [comment]
Is there any use-case for non-freetype font rendering? It seems kinda unnecessary to have two different ways to render fonts.

**Comment by sofar** [comment]
@sfan5 please state the reason for keeping this code around.

**Comment by numberZero** [comment]
Where is the serif font used? Have never seen it in MT.

**Comment by sofar** [comment]
We can remove it. Some people may prefer it, that's all.

**Comment by sofar** [comment]
@sfan5 @celeron55 @nerzhul @ShadowNinja @Ekdohibs @Zeno- @sapier 

I'm considering this a double license vialation. This patch solves both violaitons at once. Therefore this is IMHO extremely urgent and should not sit for long. I can come up with alternative solutions, but if there's no feedback I will push a change.

**Comment by sofar** [comment]
#5230 replaces and (sadly) does not make freetype required. It also therefore only keeps dejavu mono around for non-freetype, forcing non-freetype builds into monospaced only fonts.

And it is still URGENT that this gets resolved.

**Pull request closed without merging**
