### PR TITLE
Code style - proper spacing for input/output operators

### PR DESCRIPTION
**Pull request by KaylebJay**
## Goal of the PR
I noticed that about 80% of the input/output C operators used in Minetest are spaced properly, the rest have absolutely no spacing, or wrong spacing (see [Code Style Guidelines](https://dev.minetest.net/Lua_code_style_guidelines)). This is an ugly inconsistency, so I plan to fix it.

## To do

This PR is a Work in Progress/Draft.

TODO: Fix all cases of this (right now, just a few are fixed for demonstration) and double-check again that everything is fixed. Then, rebase it ;)

It would be nice to know if the devs wanted code that is commented out to be fixed too. Then I could make some kind of script to fix this :-)

### CODE REVIEW

**Comment by ClobberXD** [comment]
@LoneWolfHT That's why we have a clang-format linter. Ideally, running it on our repo should format all the code according to our code-style. The (only) problem is that it needs to be [configured](https://github.com/minetest/minetest/blob/master/.clang-format) to do so. :)

**Comment by LoneWolfHT** [comment]
Hopefully my VSCode extension detects that. I'm now able to run clang-format on files I edit

**Comment by ClobberXD** [comment]
Most files have been whitelisted, as clang-format incorrectly (or rather correctly) detects them to be badly-formatted, because our clang-format config is incomplete. That might explain why clang-format doesn't bother too much about existing code.

**Comment by KaylebJay** [comment]
Replaced (more or less) by https://github.com/minetest/minetest/pull/10029

**Pull request closed without merging**
