### PR TITLE
Inventory: Restrict access from too far away

### PR DESCRIPTION
**Pull request by sofar**
Backport from `master`

### CODE REVIEW

**Comment by rubenwardy** [comment]
Wrong branch, put into backport-0.4

**Comment by rubenwardy** [comment]
Also, it's probably better to backport and fixes before this, so we don't miss them

**Comment by sfan5** [comment]
That's not how I intended the backports branch to work.
Instead someone should go through all commits from the point at which it was last updated to now, and cherry pick each commit in the correct order.

Not doing so might make merging messy and complicates keeping track of what was backported and what wasn't. It gets even worse when you decide that you want to remove a backported commit (and honor the no forcepush rule).

**Comment by sfan5** [comment]
done

**Pull request closed without merging**
