### PR TITLE
Android: Resize jump and crunch buttons' touch target

### PR DESCRIPTION
**Pull request by srifqi**
Resize jump and crunch buttons' touch target so that they fill empty space below them.
First discussed: https://github.com/minetest/minetest/commit/b1e58c9c35ae3eb6167a0745086cdb0ddb1dd9d7#r29473361

Before: (ignore the AUX button)
touch target (before)
After: (not final texture, read below)
touch target (after)

### CODE REVIEW

**Comment by paramat** [comment]
How about this: Keep the buttons the same width but extend them upwards a little to make them square, then move the icons down a little to the centre of the buttons?

**Comment by SmallJoker** [comment]
My only concern is that the images should be vertically centred, because that's where buttons usually are pressed.

**Comment by srifqi** [comment]
@paramat @SmallJoker Done.

**Comment by paramat** [comment]
Screenshot please.

**Comment by paramat** [comment]
Or perhaps: Place the icons where it is comfortable to press when using a case (that may be where they are currently), create a square button around the icon with the icon at the centre, then extend the button down to the screen edge.

**Comment by stujones11** [comment]
> Screenshot please.

screen

**Comment by paramat** [comment]
Jump and sneak buttons look ok.
Please could you show a screenshot with the AUX button enabled?

**Comment by stujones11** [comment]
> Please could you show a screenshot with the AUX button enabled?

https://github.com/minetest/minetest/pull/7477#issuecomment-401560983

**Comment by paramat** [comment]
:+1:

**Comment by srifqi** [comment]
Thank you. I'm still away from my computer. So, I can't provide any screenshots etc.

**Pull request merged**
