### PR TITLE
Fixes a freeze on the phone or NativeActivity LockScreen

### PR DESCRIPTION
**Pull request by MoNTE48**
No magic. Just a small addition :)

### CODE REVIEW

**Comment by MoNTE48** [comment]
Mmm, I accidentally combined 2 different commits. Excuse me, I'm still not good at GitHub

**Comment by est31** [comment]
How does the freeze occur? Any way to reproduce it?

**Comment by est31** [comment]
No problem about the additional commit, it can be filtered out later.

**Comment by MoNTE48** [comment]
If you start the game and then did not pause to turn off the phone and turn it on, then there is little likelihood that it will hang on the LockScreen, or after the unlock will be a black screen. This fixes this bug.

**Comment by nerzhul** [comment]
Please fix your comments tabs if you want the second commit :)

**Comment by MoNTE48** [comment]
@nerzhul, Please tell me how to do it?

**Comment by nerzhul** [comment]
Open with your editor and tip the TAB key ?

**Comment by MoNTE48** [comment]
@nerzhul, I do not use github client, I made changes through the web site. Not editor.

**Comment by est31** [comment]
nrz is right, Minetest uses tabs for indentation (no spaces), so you should fix it. However, its no big deal, because the person merging the pr can fix it as well, so its no blocking issue, unlike nrz said.

Quoting the [android manual](http://developer.android.com/guide/topics/manifest/activity-element.html):
> However, if your application targets API level 12 or lower, then your activity always handles this configuration change itself (this configuration change does not restart your activity, even when running on an Android 3.2 or higher device). 

So it seems this should only be an issue if we move our API target up. Even then we should merge it, as we won't see the bug if/when that target move is done. What's the target API for multicraft?

**Comment by MoNTE48** [comment]
Now I know what you mean. Sorry.
MultiCraft use API 16, but all the code is compatible with the API 14 too. All Android 2.3-3.1 devices so weak that playing Minetest almost impossible. Therefore MultiCraft build for Android 4+ only.

**Comment by ShadowNinja** [comment]
@MoNTE48: I tried applying this patch along with a target API bump, but I just got this error:
```
     [aapt] .../build/android/bin/AndroidManifest.xml:18: error: Error:
            String types not allowed (at 'configChanges' with value
            'orientation|keyboard|keyboardHidden|navigation|screenSize').
```

Your fork doesn't seem to have this patch either.  Do have any clues as to why this is happening?

**Comment by MoNTE48** [comment]
Bro, I do not remember, it was a long time ago. I'm not going through aapt, i use Android Studio and use apk manually.
For a long time java part deals with my colleague, he rewrote all the code, and I did not understand what he did, to be honest.

**Pull request closed without merging**
