### PR TITLE
DevTest: Change texture for node-aligned node

### LINKED ISSUE #12559: Devtest tiled:tiled_n texture is misleading
##### Summary

`scale` is only documented for work for world-aligned nodes. But `tiled:tiled_n` sets it to 8 and also uses the tiled texture that has 8x8 parts.
To an observer this falsely suggests that the tiling is broken.

It should use a different texture and not attempt to set scale=8.

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #12559.

### CODE REVIEW

**Review by rubenwardy — APPROVED** [review]

**Review by TurkeyMcMac — APPROVED** [review]
Looks good except for the missing license notice.

**Comment by Wuzzy2** [comment]
Tbh, I don't think most images in DevTest even apply to copyright in the first place because they're trivial, especially those test nodes. There is a bunch of other textures in DevTest that I have created when I made the big DevTest rework. If you still want this to be documented, please say so and I make a separate PR for all these files at once.

**Comment by TurkeyMcMac** [comment]
Your choice.

**Comment by rubenwardy** [comment]
> If you still want this to be documented, please say so and I make a separate PR for all these files at once.

Technically you should do, as the default license for Minetest is CC BY-SA requires attribution and it's hard to do that without knowledge of where the textures come form

**Comment by Wuzzy2** [comment]
So is this an official request to create a 2nd PR or not?
But be warned: It will be a LONG list of files and all DevTest images I made were hastily scribbled together in seconds, those aren't works of art.

**Comment by rubenwardy** [comment]
I wouldn't worry about it unless someone complains. Maybe at most you could add a line like "Unless otherwise stated, devtest textures are by Wuzzy" but idk

**Pull request merged**
