### PR TITLE
Play 'player_jump' when player jumps

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds a new sound `player_jump` which is played when the local player jumps.

## To do

Ready for Review.

## How to test

* Add a mod with a sound file: `sounds/player_jump.ogg`
* Turn on the loudspeakers and volume to 100%
* Start the game and jump

### CODE REVIEW

**Comment by paramat** [comment]
This was discussed in #6355 , i suggested using the footstep sound but louder, like you are pushing hard off the node.
For most games i cannot see some kind of abstract arcade 'boing!' or 'boouup!' sound suitable, so this seems an incomplete implementation, although it will be fine for more unusual games.

https://github.com/minetest/minetest/issues/6355#issuecomment-419887989
> Jump off a node (use footstep sound)

> Kinda, but it would be better (more artistic freedom) if a separate sound is allowed, with footstep as the fallback. Note it would not significantly increase the complexity either.

I think the footstep (but louder) should be an option here, as it will be more suitable for most games.

**Comment by LoneWolfHT** [comment]
Maybe use the footstep sound with a volume increase by default but allow that to be overriden with the method this PR adds

**Comment by paramat** [comment]
For most games, which tend to be a little like MTG or MC, i do not consider a single jump sound being particularly useful. MT sounds tend to be loosely realistic, and jumping does not really make a sound.
This would however be useable by more unusual games that want an abstract arcade type 'boing!' or 'boouwp!' sound. However, i think this feature needs to be useful for many games.

The only loosely realistic sound i can think occurring when jumping is a heavy footstep, so as suggested and discussed in #6355 perhaps play a louder footstep sound? I think that would then be the primary feature here, with the custom sound as an option.

**Comment by LoneWolfHT** [comment]
I was assuming by 'footstep sound' you meant the sound that would play when the player walks on the node they are currently standing on.

One use for this feature would be playing a "huh!" sound as if it was coming from the player with every jump they make. This is done in Skyrim and IMO works quite well

**Comment by style-nine** [comment]
Jumping in video games is already an unrealistic action, given how you immediately launch into the air the moment you hit the jump button (as the player expects). I think playing a boing along with it would actually be a good way to reinforce the fact that you are using a super power, and not actually doing a realistic jump.

**Comment by paramat** [comment]
> I was assuming by 'footstep sound' you meant the sound that would play when the player walks on the node they are currently standing on.

Correct.

Using a voice sound for jump is problematic, which gender do you choose? Which age do you choose? If it is a human sound then any player using an alien or monster or ghost skin has an unsuitable sound. This is why it is best to not have any kind of vocal sound, because it is so inflexible.

**Comment by benrob0329** [comment]
> Using a voice sound for jump is problematic, which gender do you choose? Which age do you choose? If it is a human sound then any player using an alien or monster or ghost skin has an unsuitable sound. This is why it is best to not have any kind of vocal sound, because it is so inflexible.

For MTG, since Sam is a (presumably middle-aged British) male you would end up with _just_ that. But other games would have to be able to override this per-player to make it work with other character options. I believe that per-player override is important for this feature because of that.

**Comment by Wuzzy2** [comment]
I'm predicting this PR isn't going anywhere …
lol

**Comment by paramat** [comment]
Sam is gender-neutral, although the skin does not do a good job of that currently.
> But other games would have to be able to override this per-player

I was dreading someone suggesting that. That suggestion lacks a sense of 'appropriate complexity'. You do tend to suggest ridiculously over-complex implementations, please keep in mind we are not a professional development company and we have extremely limited time currently. MT has to be simpler than other games and we have to prioritise effort.

Wuzzy2, do not worry. To be clear, i am only suggesting playing the node footstep sound on jump, possibly at a slightly higher volume, and using the custom sound if defined. This way the feature is useful for all games instead of some or a minority.

**Comment by MoNTE48** [comment]
The @Wuzzy2 implementation is pretty darn simple and doesn't change anything for games that don't want it. Let the modders decide on their own whether they want this and, if so, what kind of sound they will use.

_Show Sam to 10 children and ask if this is a boy or a girl. If the children are healthy, they will say that this is a boy. Let's leave gender-neutral conversations elsewhere._

**Comment by benrob0329** [comment]
> I was dreading someone suggesting that. That suggestion lacks a sense of 'appropriate complexity'.

I don't see how checking for a globally set sound is any more complex than checking what node the player is standing on if a sound doesn't exist.

> I'm predicting this PR isn't going anywhere

I feel like this is simple but useful enough it _could_ just be merged.

**Comment by Wuzzy2** [comment]
@SmallJoker: Thank you for actually commiting that small tweak directly. It seems this is the first time a core dev actually used this feature (at least to my knowledge). :D

**Pull request merged**
