### PR TITLE
Remove settings properly

### LINKED ISSUE #7674: Advanced Settings: Restore Default does not work
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-74d27642 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=RELEASE
RUN_IN_PLACE=0
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"


```

##### OS / Hardware

Operating system:linux
CPU:intel

##### Summary

The `Restore Default` button does not unset a setting but sets it to the value it currently defaults to (configured in settingtypes.txt) if it was unset.
This breaks settings which are handled differently when they are unset, and when the default setting value changes, the old one is kept in minetest.conf.
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/builtin/mainmenu/dlg_settings_advanced.lua#L984
Not being able to see if a setting is not in minetest.conf is also very inconvenient.

##### Steps to reproduce

Remove static_spawnpoint from minetest.conf if it's set there, then start minetest.
Go to Advanced Settings, set static_spawnpoint to some value.
Click on `Restore Default` to attempt undoing the static_spawnpoint setting.
Exit minetest and look at minetest.conf, static_spawnpoint is now set to an empty string.

When static_spawnpoint is unset, minetest automatically puts the player onto surface when spawning, but when it's set to an empty string, the player is always put to {x=0, y=0, z=0}.

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #7674

### CODE REVIEW

**Comment by t4im** [comment]
This also seems to let the unit test mentioned in #2264 pass finally. Good job :)

**Comment by SmallJoker** [comment]
Whoops! I totally forgot about this PR. @t4im would you please be so nice and check whether it surely fixes your issue? Otherwise will merge this soon - works here.

**Comment by t4im** [comment]
I run the test against this PR and it passed, so as far as i can tell `remove()` is now deleting the entries from the config. :+1:
The restore button regarding #7674 also works as expected now and removes the line from the config.

**Comment by paramat** [comment]
:+1:

**Pull request merged**
