### PR TITLE
add a way to add chat placeholders

### PR DESCRIPTION
**Pull request by boulbousNaranha**
implements #14930 

## To Do

This PR is Ready for Review.

## How to test

1. define a placeholder
```lua
minetest.register_placeholder("rank", function(name, message)
	return "admin"
end)
```

2. set `chat_message_format` to `[@rank] <@name> @message`

3. send a chat message and observe the change

### CODE REVIEW

**Comment by cx384** [comment]
If I understand it correctly, you want to maintain compatibility between a mod which formats chat massages, and mods which introduce special chat commands.

I don't think this is a good solution to your use case. It is rather a flaw of `minetest.register_on_chat_message`, since you can't use it to prepend functions (and we don't have reverse mod dependencies).

An overwritable `minetest.handle_chat_message` function (which gets executed after the registered things) may be a better solution, just like `minetest.is_protected`, `minetest.handle_node_drops`, or `minetest.send_join_message`.
It could be used to format messages, or even completely replace how the chat works.

Alternately, mods could agree on their own chat library to avoid incompatibilities, but good luck with that, and to me, it seems like `minetest.register_on_chat_message` was never intended to handle all messages such that you can format them.

(Also, `minetest.register_placeholder` is a terrible name. It doesn't contain any indication that it talks about the chat message format.)

**Comment by boulbousNaranha** [comment]
> An overwritable minetest.handle_chat_message function (which gets executed after the registered things) may be a better solution

afaik that is what `minetest.format_chat_message` does, but it also adds `@name`, `@message` and `@timestamp` placeholders, so i thought that adding a way to register additional placeholders would be a good idea.

I guess we could remove the `chat_message_format` setting (i doubt anyone uses it) and place a note under `minetest.register_on_chat_message` documentation pointing them to override `minetest.format_chat_message` if they want to change how messages are displayed.

This solution is problematic if many mods try to override that function at once. They could override it and call the previous definition but i can think of cases where these dont work together well. eg

- mod overrides `minetest.format_chat_message` to return the value of old `minetest.format_chat_message` prepended with a rank string
- mod overrides `minetest.format_chat_message` so messages are different color if the player is near you, this dosent call the old `minetest.format_chat_message` because that wouldnt make sense 

In this case only the second mod takes effect. the first mod might try to load late but in my opinion this is meh and easily to overlook, so the placeholder solution is better (though overriding minetest.format_chat_message does fix my use case of special chat commands)

**Comment by Zughy** [comment]
@cx384 if you haven't changed your mind, please close it (also @appgurueu due to the thumbs up)

**Comment by cx384** [comment]
Just to clarify things, this is not a particular bad feature, but for me, it falls into the "better done in a third party mod" category as it has not sufficiently many use cases, can already be done by a mod, and it clutters the API if every feature of this kind would be added.

**Pull request closed without merging**
