### PR TITLE
Network breakage: Send real floats

### LINKED ISSUE #5521: Server hangs when exceeding position x/y/z near 229367
As reported by @bigfoot547 

https://github.com/minetest/minetest/pull/5511#issuecomment-291691769

> you can hang the server after about x/y/z 229367.

### PR DESCRIPTION
**Pull request by SmallJoker**
Pilot version tested with Xubuntu client to BSD server.
As of 170825 13:00 UTC, `web.unix-experience.fr 30001` is built on 7551acc but the protocol bump is contained in a56e5b7, so you'll get a message for a version-incompatibility. Thanks to @nerzhul for providing this server.

This PR will make servers send real float values instead of a multiplied value, sent as a regular integer. To prevent any overhead, the backwards compatibility is dropped entirely.
By this PR caused deprecated code segments are removed too.

Fixes #5521 and various runtime errors caused by Lua mods that send values outside the allowed range.

### CODE REVIEW

**Comment by sfan5** [comment]
This is a hilariously bad idea since you can't rely on `float` being 4 bytes ([source](https://stackoverflow.com/questions/25524355/what-is-the-size-of-float-and-double-in-c-and-c#answer-25524458)) or IEEE 754 exactly working the same on all platforms ([source](https://stackoverflow.com/questions/2724359/are-there-any-modern-platforms-with-non-ieee-c-c-float-formats#answer-2724668)).

Now for the "testing":
What you tested was interchange between an IEEE-compliant 64-bit little-endian platform with another 64-bit little-endian platform with likely identical IEEE compliance/support. This makes the result (<i>it works!</i>) entirely meaningless.
Meaningful testing results would be achieved by testing:
* big-endian machines
* softfloat support (embedded platforms in particular)
* as many different CPU architectures as possible

**Comment by nerzhul** [comment]
@sfan5 nice shot for 32b and ARM, if someone as a RPI or android build, let's go

**Comment by nerzhul** [comment]
here is an interesting paper to read about this, the choosen method seems to be interesting

https://beej.us/guide/bgnet/output/html/singlepage/bgnet.html#serialization

**Comment by nerzhul** [comment]
in protobuf, they read uint32_t :
https://github.com/google/protobuf/blob/dd7265e1a2cf78fd0333f62d8e74d40a0781f83b/src/google/protobuf/wire_format_lite_inl.h#L135

 a union is used to encode decode float to uint32_t, see:
 https://github.com/google/protobuf/blob/ba4e54724d2e6a1881c4fe88664d81fbacaf8c08/src/google/protobuf/wire_format_lite.h#L804

**Comment by electromatter** [comment]
@nerzhul there are also the standard functions frexp and ldexp for accessing the exponent and significand of a float which is probably the most portable way to encode floats

**Comment by SmallJoker** [comment]
@electromatter So is this about what you had in mind?
```C++
u32 writeF32(f32 v)
{
	u32 dat = 0;

	float fraction;
	s32 exponent;
	fraction = frexp(v, &exponent);

	fraction *= 0x400000;
	//assert(exponent <= 0xFF)
	//assert(exponent >= -0x100)
	dat = (u32)exponent << 23 | ((u32)fraction & 0x7FFFFF);
	return dat;
}

float readF32(u32 v)
{
	u32 fraction_i = v & 0x7FFFFF;
	u32 exponent_i = v >> 23;
	if (v & 0x00400000)
		fraction_i |= 0xFF800000;
	if (v & 0x80000000)
		exponent_i |= 0xFFFFFE00;

	float fraction = (s32)fraction_i / (float)0x400000;

	return ldexp(fraction, (s32)exponent_i);
}
```

**Comment by electromatter** [comment]
@SmallJoker Yeah, something like that. But careful, the standard function takes an int (which might not be u32 on some platforms?). Also, what about NaNs, infinity, and denormal numbers (-0.f)? And, what should the wire format be? I think IEEE 754 binary32 would be nice and on most platforms would make this just a memcpy/byteswap. C99 has [fpclassify and signbit](https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html) which should make this easier.

**Comment by SmallJoker** [comment]
Dead PR. Possibly the ideas here can be helpful if we don't switch to another networking library.

**Pull request closed without merging**
