### PR TITLE
Add missing entity documentation

### PR DESCRIPTION
**Pull request by Wuzzy2**
What it says on the tin.

### CODE REVIEW

**Comment by paramat** [comment]
Some of the single lines have '.' at the end, some do not. I think the giudeline is no '.' if a single line comment.

**Comment by SmallJoker** [comment]
If it's an entire sentence, add a full stop. If not, don't

**Comment by SmallJoker** [comment]
Are there rules regarding full stops? It makes at least sense to put full stops for complete sentences.
Nonetheless, this PR was approved twice so it's fine.

**Comment by Extex101** [comment]
I'd suggest listing compatible model types in the mesh

**Pull request merged**
