### PR TITLE
Remove old docs. We have VCS history anyways.

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by neoascetic** [comment]
Hm, that test still failing on OSX, sad...

**Comment by est31** [comment]
:+1: I don't think its of much use to anybody but historians. And those can look at the VCS history :)

**Comment by paramat** [comment]
:-1: 'ancient main comment' contains lots of interesting suggestions that are still relevant, so i think only remove the 'changelog'.

**Comment by paramat** [comment]
:+1:

**Comment by nerzhul** [comment]
:+1:

**Pull request merged**
