### PR TITLE
Set window caption to subgame name

### PR DESCRIPTION
**Pull request by NO411**
- The title of the window should be the name of the game and not the name of the engine since you are playing a game and not an engine.
- I didn't open an issue because it didn't take much effort to change this. I think it can be discussed here...

## To do

Ready for Review.

- [ ] (Maybe put the caption on the server game name too, how could that be done? Or just display "Minetest Client"?)

## How to test

- Start worlds in different games, check that the caption shows the game title.
- Join servers, the caption should still be the name of the engine + version.

### CODE REVIEW

**Comment by FreeLikeGNU** [comment]
there seems to be a conflict between the comment and code.  This seems to change the caption when NOT in SP:
```
// set caption to subgame name in singleplayer mode
	std::wstring str = utf8_to_wide(start_data.game_spec.title);
	if (!simple_singleplayer_mode)
	{
		str = utf8_to_wide(PROJECT_NAME_C);
		str += L" ";
		str += utf8_to_wide(g_version_hash);
	}
```

**Comment by NO411** [comment]
> there seems to be a conflict between the comment and code. This seems to change the caption when NOT in SP:
> 
> ```
> // set caption to subgame name in singleplayer mode
> 	std::wstring str = utf8_to_wide(start_data.game_spec.title);
> 	if (!simple_singleplayer_mode)
> 	{
> 		str = utf8_to_wide(PROJECT_NAME_C);
> 		str += L" ";
> 		str += utf8_to_wide(g_version_hash);
> 	}
> ```

fixed

**Comment by Zughy** [comment]
Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved (it's lasted 7 months, sorry), otherwise they should be closed. These PRs can also have preapproval if they fix an issue that is concept approved.  

I'd like to underline that we prioritise things because our time is limited and we can't take care of everything (at least not without leaving people waiting for months, if not years): it's a way for us to respect both contributors and ourselves. 

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label

**Comment by kneekoo** [comment]
Sorry, why was this closed? It's barely any code to be reviewed, and it does make sense to see the name of the game you're playing.

The rules are fine for large PRs, but the rules should have exceptions for tiny PRs that don't require more than 10 minutes of thinking and reviewing. And this is something a core developer can ask another trusted contributor to take a look at, if even those 10 minutes are unavailable. A bit of flexibility would help everyone.

**Comment by Zughy** [comment]
@kneekoo https://irc.minetest.net/minetest-dev/2023-05-28#i_6087645

**Comment by kneekoo** [comment]
Thanks, that looks like useful feedback that could've been passed here for the contributor to look into - without closing the issue. Now it looks like no one is even interested in any change, although the limitation of having this for local games only is still a good addition.

**Pull request closed without merging**
