### PR TITLE
Rename logfile to minetest.log by default

### PR DESCRIPTION
**Pull request by ClobberXD**
#### Changes

- Make logfile name configurable. Relevant `minetest.conf` setting: `logfile_name`.
- `logfile_name` defaults to `minetest.log`.
- Replace all hard-coded occurrences of `debug.txt` in the code with the actual logfile name
- Report selected logfile name (incl. full path) to terminal on startup.

#### A couple of reasons for the proposed changes

- Customizable logfile name is a fundamental feature, IMHO.
- The default logfile name of `debug.txt` makes Minetest sound more like a beta game, which it isn't. :)
- The proposed default logfile name makes Minetest sound more polished. (This is basically an extension of the previous point)
- There are so many other things that are logged in that file other than just warnings and errors.
- The `.log` file extension is the de-facto standard for log files.

### CODE REVIEW

**Comment by paramat** [comment]
> The .log file extension is the de-facto standard for log files.

It doesn't matter what the standard is, and there's no harm in using .txt. It helps by making clear it is a simple text document like the many other .txt documents found in Minetest.
How about 'log.txt'?

**Comment by benrob0329** [comment]
Things tend to be standard for a reason. If most software behaves in a certain way, its usually because its sane behavior that users expect.

**Comment by paramat** [comment]
I mostly agree and i didn't state otherwise. It's useful to consider the standard as it may be a good idea, but it's not necessarily right for MT.

**Comment by rubenwardy** [comment]
I don't think that the benefits of this are worth changing all the documentation and any bash scripts that rely on this

**Comment by ClobberXD** [comment]
> I don't think that the benefits of this are worth changing all the documentation and any bash scripts that rely on this

I'll add a setting for logfile name - I'd consider the setting essential, even without this PR.

**Comment by ClobberXD** [comment]
Added a new setting for customizing logfile name - `logfile_name` (duh :P). See the updated first post for current status of this PR.

**Comment by rubenwardy** [comment]
We really don't need more configuration options

https://github.com/search?q=minetest+debug.txt&type=Code

**Comment by ClobberXD** [comment]
> Also, look how many times debug.txt appears in random deployment things

Should I retain the default name then?

> This would make more sense as a command line argument

We already have a `--logfile` switch.

Keeping these points in mind, what should be done now?

**Comment by paramat** [comment]
I agree with rubenwardy and SmallJoker (emoticon support).
A setting is certainly overkill.
:-1:

**Pull request closed without merging**
