### PR TITLE
Digging animations tweaks.

### PR DESCRIPTION
**Pull request by RealBadAngel**
- Allow disabling crack animations
- Make highlighting show digging progress
- Increase slightly number of digging particles

### CODE REVIEW

**Comment by kilbith** [comment]
Demo : https://www.youtube.com/watch?v=wjG1bUBFPB0

**Comment by paramat** [comment]
I support the disabling of the crack animation, because of how it causes mesh updates.
But disagree with increasing the number of particles, it's okay as it is now.
Highlighting showing dig progress seems okay but i'm rather neutral about that.
So currently :-1:

**Comment by paramat** [comment]
PR has been quiet for a year, will close in 1 month if no progress or response.

**Comment by sofar** [comment]
Maybe you want to split the PR up and separately submit the punch particle count?

**Comment by Fixer-007** [comment]
I do like crack a lot, but those slowdowns it makes...

**Comment by Dragonop** [comment]
What would happend to players like me that have particles disabled and use the selection box when pointing at nodes instead of highlighting?

**Comment by paramat** [comment]
Disabling crack animation is optional, so you would i guess continue to use that if you want digging feedback.

**Comment by RealBadAngel** [comment]
I will reuse some ideas from this PR while moving cracks out of mesh gen. Let it stay open for a while.

**Comment by paramat** [comment]
The issue of crack animations updating meshes should be considered of course, but this PR is mixed in with increases in particle number which is a bad idea. Obviously and unfortunately the author cannot update this so i think it should be closed.

**Comment by paramat** [comment]
I'll close this in one month unless a good reason to keep it open is presented.

**Comment by kwolekr** [comment]
Agreed with paramat on the last point.  Since what it does is quite trivial I think we can close this PR out, and if somebody is still interested, they can open a new a version that addresses the other concerns.  :-1: from me for the particle increase, :+1: on the crack animation disable, neutral on the node highlighing color change (maybe it would make sense as an alternative way to indicate progress if cracking animations were disabled).  And :-1: for the code review because of the way this PR restricts crack animation lengths to 16.

**Comment by paramat** [comment]
Time to close this.

**Comment by paramat** [comment]
Just searched for this because i would like an option to not use crack animations, due to how, as far as i know, each crack frame updates the whole mesh. I would be happy with just particles.
I might see if i can extract the crack option from this.

**Pull request closed without merging**
