### PR TITLE
Add wield light

### PR DESCRIPTION
**Pull request by Zeg9**
Hold a torch or any light source in a dark area to see the change.
This only works with shaders enabled, and only the player who holds the torch see the light.
Please merge https://github.com/minetest/minetest_game/issues/188 if you merge this one.

### CODE REVIEW

**Comment by neoascetic** [comment]
Wow, that's really cool if it works as expected. I even wrote a little [plugin] (https://github.com/neoascetic/minetest_flaming_torch) to implement this!

**Comment by C1ffisme** [comment]
:+1:

**Comment by Calinou** [comment]
> @Calinou Yes, but it would be extremely slow, since lighting updates would have to run multiple times a second.

It might be possible to run it only once or twice a second.

**Comment by C1ffisme** [comment]
So far, the results have been positive. Can you please rebase???

**Comment by est31** [comment]
Not to be merged in the current form (shaders which affect gameplay, not settable by game), code kept around for reference purposes [here](http://pastebin.com/rpTBYad4). Please also dont delete the branch, the pastebin is a backup.

**Comment by CandyKitty** [comment]
Screenshots?

**Comment by C1ffisme** [comment]
@CandyKitty You might want to look at the close date on this.

>  est31 closed this on **Jun 28, 2015**

Besides that, I'm not really a fan of this anymore, since it just means when I carry certain items blocks update every time I move. I'd rather the screen get brighter or blocks become more visible within a certain radius whenever I'm holding certain items.

**Pull request closed without merging**
