### PR TITLE
Update Indonesian language using Weblate

### PR DESCRIPTION
**Pull request by srifqi**

### CODE REVIEW

**Comment by kilbith** [comment]
Please do that here instead : https://hosted.weblate.org/projects/minetest/minetest/id/

Then wait for the dev to merge it, don't open a PR for this.

**Comment by est31** [comment]
As @kilbith said.

**Comment by srifqi** [comment]
Okay, thanks. But, how can I notice that it has already merged?

**Comment by kilbith** [comment]
In the commits tree.

**Comment by srifqi** [comment]
Okay, thanks!
Just come to my mind that this link exist: https://github.com/minetest/minetest/commits/master/po/id/minetest.po

**Pull request closed without merging**
