### PR TITLE
LINT: add clang-tidy step

### PR DESCRIPTION
**Pull request by nerzhul**
clang-tidy should permit to correctly use CPP and improve the code quality/performance.

Enable it, partially, just for testing, but it should be added to LINT with interesting rules

Before-fix clang-tidy build: https://travis-ci.org/minetest/minetest/builds/360207556

Tool documentation: https://clang.llvm.org/extra/clang-tidy/
All checks: https://clang.llvm.org/extra/clang-tidy/checks/list.html

Note:
* push_back -> emplace_back (modernize-use-emplace) is now a blocking check as i fixed them in the second commit
* performance-* checks are enabled as a warning (only)

Maybe define more warnings to add, and work on improving the quality

### CODE REVIEW

**Comment by nerzhul** [comment]
@sfan5 i'm working on a such step to enhance the code quality input in PR, it's a clang-tidy subset check, i just need to fix the travis integration

**Comment by paramat** [comment]
Will it make checks more strict? We already whitelist most files because LINT doesn't like our codestyle, so more strict may not be helpful.

**Comment by nerzhul** [comment]
@paramat clang-tidy is code quality, not code style, yes it's stricter, but because it catch common C++ mistakes in terms of performance when writing code

**Comment by paramat** [comment]
Ok, no objection from me.

**Comment by nerzhul** [comment]
Rebase done, i'm trying to implement it correctly in the CI with a single test

**Comment by nerzhul** [comment]
PR is now finished and totally functional.
We just need to define which rule add in warning and which in error.
I propose the following rules for a first step (i will fix one of them in a second commit in this PR after travis pass)

* performance-* rules as a warning
* modernize-use-emplace as an error
* modernize-avoid-bind as a warning

We can add more rule in the future, after fixing/promoting many warnings as errors

**Comment by nerzhul** [comment]
@sfan5 @SmallJoker @rubenwardy please review.
I hope we can integrate a such thing. This will permit to add many interesting rules to prevent some bad C++ coding and ensure we keep a good code quality

**Comment by paramat** [comment]
I welcome the feedback this will give, i'm just wondering if this will cause a build to be marked as 'failed'? The suggestions this will give are useful to consider, but some suggestions may not be suitable and we will want to ignore some of them. If this causes a build to 'fail' then it will just increase the number of files added to the whitelist, which then disables these checks for that file.
This problem has been happening already with the current silly codestyle checks, i'm concerned this will increase this problem.

Is there a way for these code suggestions to be given without marking a build as 'failed'? That would be ideal.

**Comment by nerzhul** [comment]
@paramat there is 3 categories of checks we can configure

* Mandatory checks => failure
* Optional checks => just printed as warning on the build (non blocking)
* Non enabled checks => not interesting checks in our context

We should at least enable all interesting checks as warning and after fixing the most interesting quality checks mark them as mandatory

**Comment by nerzhul** [comment]
@paramat see this line:

https://github.com/minetest/minetest/pull/6295/files#diff-aca3ef8b4b2c821477396f9f6aafe17cR21

checks are what we check, default in warning.
warningaserrors define which check will mark the build as failure

**Comment by paramat** [comment]
Thanks, ok that sounds reasonable.

**Comment by nerzhul** [comment]
yes, just remember all of them should not be fixed, it depend on the check. emplace_back check is important for example and non subject to discuss as it's just correct use of the STL
Somes can be added for std::fabs as a warning too, we have many tidy issues reported due to ::fabs usage which cast float to double to cast result to float, it's not very good

**Comment by paramat** [comment]
So i give a concept approval, but can't officially +1 as can't judge the code.

**Comment by nerzhul** [comment]
@SmallJoker @rubenwardy can you just approve that too ? i need to merge it and will continue to improve code quality and add quality gates by normalizing this usage

**Pull request merged**
