### PR TITLE
 Client-side translations: gettext and plural support

### PR DESCRIPTION
**Pull request by Ekdohibs**
This PR is a rebase of #10451.

----

Add gettext support for client-side translations. This allows using existing gettext tooling, and will allow using plurals in translated strings (`ngettext` and the like).

Testing is needed, but the PR is otherwise complete.

### CODE REVIEW

**Comment by Ekdohibs** [comment]
I added a commit for testing, and fixed a few bugs that were still there that I found.
To test:
- add the following to `po/fr/minetest.po` (this is not committed, as weblate takes care of translations):
```
msgid "0"
msgid_plural "1"
msgstr[0] "0"
msgstr[1] "1"
```
- set your locale to `"fr"`
- start the devtest game and run `/testtranslations`.

This should test all three types of translation files, as well as plural translations for both `.po` and `.mo` files (plurals are unsupported in `.tr` files).

**Comment by Zughy** [comment]
@Ekdohibs please rebase
core devs: please show interest

**Comment by Wuzzy2** [comment]
Was this closed due to success or due to failure?

**Comment by Zughy** [comment]
@Wuzzy2 author has disappeared. Also, more than 30 days after having asked for a rebase

**Pull request closed without merging**
