### PR TITLE
Add setting for improved 3d sounds with headphones (HRTF)

### PR DESCRIPTION
**Pull request by rubenwardy**
[Head-related Transfer Function](https://en.wikipedia.org/wiki/Head-related_transfer_function) is a technique that improves the quality of 3d sounds when wearing headphones. Rather than just changing stereo balance/volume, it also changes the time offset. This results in sounds being much clearer and easier to locate.

**See this video for the difference: https://www.youtube.com/watch?v=jXkDmJRI1yg**

OpenAL is supposed to automatically enable HRTF when it detects headphones. Unfortunately, it's unable to do this on pipewire, or ALSA, and it's unreliable on Windows or pulseaudio. (Citation: #openal on liberachat).

It's possible to enable it system wide by adding `htrf = true` to `~/.alsoftrc` but this isn't discoverable currently.

The PR adds a setting that allows the user to force enable this feature. With the settings redesign, this become a lot more prominent.

This PR also includes #12628 for testing reasons

### Alternatives

With the settings redesign, we could add a button to a help page telling users how to enable HRTF system wide, rather than just for Minetest

## To do

This PR is a Work in Progress

- [ ] Add support for changing at run time. This is possible, but I'm unsure of where to actually hook this in

## How to test

Wear headphones and use `/test3dsound` in devtest.

Also check whether the "Audio: Global Initialized: OpenAL" log says HRTF is enabled or not

### CODE REVIEW

**Comment by Desour** [comment]
If you do this, you should also properly convert the vectors. (Minetest currently just passes vectors from its left-handed coordinates system, but openal uses a right-handed one. The sounds are currently upside-down.)
(Btw. users can already force HRTF on via `alsoft-config`.)

**Comment by rubenwardy** [comment]
>  Btw. users can also force HRTF on system-wide via the alsoft-config gui.

Oh that's cool, didn't know this existed

**Comment by rubenwardy** [comment]
> If you do this, you should also properly convert the vectors. (Minetest currently just passes vectors from its left-handed coordinates system, but openal uses a right-handed one. The sounds are currently upside-down.)

Is there an issue for this?

>  Btw. users can also force HRTF on system-wide via the alsoft-config gui.

Oh that's cool, didn't know this existed

**Comment by Desour** [comment]
> > If you do this, you should also properly convert the vectors. (Minetest currently just passes vectors from its left-handed coordinates system, but openal uses a right-handed one. The sounds are currently upside-down.)
> 
> Is there an issue for this?

I don't think so. You can't hear it normally.

To test this, you can use a technic music player or similar, stand before it, look down and change your yaw.

**Comment by rubenwardy** [comment]
Ok, I think the solution to this problem will be to add better documentation and maybe show whether HRTF is enabled in the Sound tab when the new settings GUI is here. It doesn't necessarily make a lot of sense to have an explicit override

**Comment by rubenwardy** [comment]
> Edit: Btw., seeing that sounds are getting more attention lately, I should probably mention that I've been working on some big sounds PR some long time ago: [Desour/minetest@sound_stuff](https://github.com/Desour/minetest/tree/sound_stuff?rgh-link-date=2022-08-01T22%3A34%3A58Z) (It's still unfinished though.)

Good to see! Sound is definitely underappreciated. I'd like to see better attached sounds, doppler effect, absorption, and echos

**Comment by lhofhansl** [comment]
Even just with laptop speakers you get a better sense of direction.

**Comment by SmallJoker** [comment]
What would be the downside of always using HRTF? Even with speakers it does still sound pretty good.

**Comment by lhofhansl** [comment]
@SmallJoker Exactly.
Then again, it's not the task of Minetest to do so (IMHO). But we could clearly document it (where?), log the status upon startup, and suggest it be turned on.

**Comment by rubenwardy** [comment]
Closed as discussed

**Pull request closed without merging**
