### PR TITLE
Fix format of src/content/mods.cpp

### PR DESCRIPTION
**Pull request by EliasFleckenstein03**
Fixes the code style of src/content/mods.cpp (Using the clang-format script)

This PR is ready for review.

### CODE REVIEW

**Comment by sfan5** [comment]
In #10740 we decided on a soft line length limit of 95 so not all of these changes are necessary and I'd even say none of them need to be done.

**Comment by EliasFleckenstein03** [comment]
Ok, but then the script should be changed. All I did here was running 
```
source util/ci/clang-format.sh 
fix_format
```

**Comment by sfan5** [comment]
That's what #10792 wanted to do, but clang-format was still enabled at the time which caused lots of fallout since it was suddenly unhappy with alignment/indentation everywhere.

**Comment by EliasFleckenstein03** [comment]
Oh, ok,

**Pull request closed without merging**
