### PR TITLE
Fix wielditem node materials

### LINKED ISSUE #1857: Cannot use node as entity anymore...
With the latest updates my protector mod can no longer use defined nodes as an entity for the purple glow for when you punch the protector block, nothing appears now and changing it to a cube entity does not show while inside the entity itself... any ideas ?

### PR DESCRIPTION
**Pull request by me4**
This fixes #1857 which is caused by material.MaterialType being set incorrectly.

This more closely matches the way textures and shaders are handled in mapblock_mesh.cpp.

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Up, seems forgotten :p

**Comment by paramat** [comment]
#1857 is apparently fixed in MT0.4.14.

**Comment by me4** [comment]
Textures with partial transparency are still broken for wielded nodes, while displaying fine when the node is placed. This is still because "use_texture_alpha = true" is ignored for wielded items, always setting TILE_MATERIAL_BASIC.

I considered this a bug because it originally worked way back with 45ebaa3524a47e12ae1020c4803e3dd499487808. But, browsing more recent issues involving use_texture_alpha, maybe we're not worried about fully supporting partial transparency.

---

I tested with the current master, using a [framedglass](https://github.com/minetest-technic/framedglass) node. The semi-transparent glass pixels become completely invisible when wielded (and also in inventory):

screenshot_20161029_140916

If I simply change src/wieldmesh.cpp to use TILE_MATERIAL_ALPHA instead of TILE_MATERIAL_BASIC, the wield display is fixed:

screenshot_20161029_140928

We wouldn't want to always use TILE_MATERIAL_ALPHA due to performance, but it's been a while and I don't know the proper way to fix without breaking something else. At least it looks like a separate wielded_shader was added last year, which might make it easier.

---

If this is something that shouldn't be fixed, let me know and I'll close this.

**Comment by paramat** [comment]
Thanks, see #95 for details on alpha problems, its use is often avoided.

**Comment by me4** [comment]
Ignoring rare transparency bugs sounds reasonable.

**Pull request closed without merging**
