### PR TITLE
getTime refactoring

### PR DESCRIPTION
**Pull request by Selat**
Some refactoring of getTime() functions.

### CODE REVIEW

**Comment by nerzhul** [comment]
Hi @Selat can you rebase ?

**Comment by Selat** [comment]
Rebased.

**Comment by nerzhul** [comment]
I think using a static class like TimeMgr:: would be great, this permit to export it into a separate library.
@Zeno- what do you think about it ?

**Comment by kwolekr** [comment]
I would like this merged, but it needs a rebase, some minor cleanup, and testing.

**Comment by nerzhul** [comment]
as me and @kwolekr wants to see this merged, tag it for next release

**Comment by SmallJoker** [comment]
Looks good to me. Please rebase this pull, @Selat

**Comment by Selat** [comment]
Can I remove [IrrlichtTimeGetter](https://github.com/minetest/minetest/blob/master/src/client/clientlauncher.h#L35) and use functions from porting.h instead?

**Comment by SmallJoker** [comment]
`TimeGetter` is only used in clientlaucher.c, so replacing it with the porting functions is okay.

**Comment by Selat** [comment]
Rebased.

**Comment by Selat** [comment]
I think failing [test](https://travis-ci.org/minetest/minetest/jobs/132086966#L586) isn't related to the pull request as there are no significant changes in threading-related files.

**Comment by ShadowNinja** [comment]
I actually re-implemented this change here for something else: https://github.com/minetest/minetest/pull/3811/commits/3625a31cd2899997d75900a91ee9591c174cfcac

Looks good, but could you merge in the `u32`->`u64` change from my commit?  It goes with this commit, and that way I don't have to rebase my commit.

**Comment by Selat** [comment]
I cherry picked your commit, but for some reason github doesn't see it. You can see this commit by cloning my repository and viewing log of gettime-refactoring branch.

**Comment by paramat** [comment]
Bump.

**Comment by SmallJoker** [comment]
Please reopen this pull after rebasing. (Closed due inactivity)

**Comment by Ekdohibs** [comment]
Replaced by #5597.

**Pull request closed without merging**
