### PR TITLE
Allow main menu gamebar scroll to loop

### PR DESCRIPTION
**Pull request by Kazooo100**
The Goal of this PR is to add functionality to the previous button on page one and the next button on the last page of the gamebar.

This PR works by adding 2 elseif conditions in the local buttonbar_buttonhandler function.
The first elseif condition works by setting the page to the last page if there are no previous pages.
The second elseif condition on line - works by setting the page to one if there are no further pages.
These combined make it go in a seamless loop.

This PR will close issue (#14835)
This PR helps improve the main menu, which is part of the UI improvements outlined in section 2.3 of the roadmap.
This PR will make it easier to navigate the gamebar and prevent frustration from clicking a button and it doing nothing.

## To do

This PR is Ready for Review.

- [ ] List
- [ ] Things
- [ ] To do

## How to test

1. Boot minetest
2. Have at least 2 pages of games installed
3. Click previous on first page or forward on last page.

(Sorry If I wrote any of this bad, writing isn't my strong suite. I can go more in depth on how it works if required.)

### CODE REVIEW

**Comment by SwissalpS** [comment]
consider this structure type:
```lua
if fields[self.btn_next_name]  then
	if self.cur_page < self.num_pages then
		self.cur_page = self.cur_page + 1
	else
		self.cur_page = 1
	end
	return true
end
```
IMO it is more readable when there are less repeating ``and`` clauses.

**Comment by Kazooo100** [comment]
I can switch to that tomorrow, if that is best?

**Review by grorp — APPROVED** [review]
Seems fine. I was worried that this could be confusing, but since there is always the "CDB plus" button at the end, it's easy to see when it's looping.

**Comment by Kazooo100** [comment]
So should I switch it or not?

**Comment by Kazooo100** [comment]
Oops sorry

**Comment by Kazooo100** [comment]
Will need a squash, will try to see how to squash so it just says "Allow main menu gamebar scroll to loop (minetest#14835)"

**Comment by SwissalpS** [comment]
> Will need a squash, will try to see how to squash so it just says "Allow main menu gamebar scroll to loop (#14835)"

Yes, typically the maintainers squash when merging.

**Review by SmallJoker — APPROVED** [review]
Works. Tested with the following modification (to avoid installing many more games):
```Lua
	add_button = function(self, name, caption, image, tooltip)
		if caption == nil then caption = "" end
		if image == nil then image = "" end
		if tooltip == nil then tooltip = "" end
		for i = 0, 3 do
		table.insert(self.buttons, {
			name = name,
			caption = caption,
			image = image,
			tooltip = tooltip,
		})
		end
	end,
```

**Pull request merged**
