### PR TITLE
slove macos/freebsd missing endian.h and add windows endian

### PR DESCRIPTION
**Pull request by qiukeren**

### CODE REVIEW

**Comment by est31** [comment]
Other than it should use tabs, it looks good, if it makes the build work for you.

**Comment by est31** [comment]
Seems to fix the same as #2627 . Don't know why we haven't merged neither of those two yet.

**Comment by qiukeren** [comment]
It works on macos EL Capitan.

What's more, `ifdef` code comes from `src/cguittfont/irrUString.h`,line 45 - 54.

And #2627 is truely an elegant solution.

**Comment by est31** [comment]
I think this is one of the commits that are best tested while in master.

**Comment by sapier** [comment]
Agreed, someone plz merge it to be tested

**Comment by est31** [comment]
848b050a567e360e857577c50dee82494b14973b

**Pull request closed without merging**
