### PR TITLE
Bump animation frame count from u8 to u16

### LINKED ISSUE #9951: Crash with 256 frame 4096x16 flowing lava texture in texture pack
##### Minetest version

```
Minetest 5.2.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Windows 10
CPU:AMD Ryzen Threadripper 1920X 12-Core Processor

GPU model: NVIDIA GeForce GTX 1060 6GB
OpenGL version: ???? (NVIDIA doesn't say)

##### Summary

from what I can gather, when a certain block, or even node, is loaded in game with the provided texture pack the game exits before even saving an error code. Stable with default textures.

##### Steps to reproduce

load a certain node while using the texture pack, possibly. or it could be world file specific. Unhelpful (to me) verbose Debug text file

##### Provided Files
[First World.zip](https://github.com/minetest/minetest/files/4692792/First.World.zip)
[Painterly.zip](https://github.com/minetest/minetest/files/4692795/Painterly.zip)
[debug.txt](https://github.com/minetest/minetest/files/4692796/debug.txt)

### PR DESCRIPTION
**Pull request by appgurueu**
Closes #9951

### CODE REVIEW

**Comment by SmallJoker** [comment]
From a quick look into the code, this is backwards-compatible. The next boundary is `TileAnimationParams::determineParams` of type `int`. Far enough frames.

**Comment by paramat** [comment]
How about u16? On the principle of types not being larger than they need to be.
u32 is not harmful of course, but there is no reason to choose u32 instead of u16, 65000+ frames is more than enough =)

**Comment by hecktest** [comment]
Does this apply to sheet_2d? Because it's still possible to run out of u16 in sheet_2d mode. You only need a 2048x2048 texture for that at 8x8 tiles.

**Comment by paramat** [comment]
I assume that 'sheet_2d' is just a different, more compact, way to organise frames on an animation sheet? If so, it would still be an animation using 65536 frames, which seems more than excessive and enough for anyone.
Or is there a different way to use a 2D animation sheet that makes the ability to use a 2D array larger than 256x256 more necessary?

**Comment by hecktest** [comment]
Sure, it's a lot of frames. You could fit almost an hour of footage in that. But it's still crashable under otherwise valid conditions, you only need a 256x256 frame grid, so technically a 256x256 texture can do it. Meanwhile, u32 requires a 64Kx64K texture to run out, many cards won't even let you use a texture this big. u16 is "should not happen", u32 is "will not happen".
Furthermore, is this sent or stored anywhere? Is it sent more than once? If not, will the difference in RAM exceed even 1 KB? Do any of the target architectures have 16 bit registers? Just _what_ is being optimized here?

**Comment by sfan5** [comment]
`struct TileSpec` (and thus `struct TileLayer`) are very frequently used and copied during mesh generation, so structure size is a valid concern for CPU caching, see #5638.

(Though I feel the `std::shared_ptr` in there probably destroys any performance advantages.)

**Comment by paramat** [comment]
> You only need a 2048x2048 texture for that at 8x8 tiles.

> Sure, it's a lot of frames. You could fit almost an hour of footage in that. But it's still crashable under otherwise valid conditions, you only need a 256x256 frame grid

Although a 2048x2048 texture of 8x8 frames (which is a practical texture size) can hit the u16 frame limit, i think we should only consider number of frames when deciding what is unnecessarily excessive, and 65536 frames is more than enough.
We could always add a frame number check that prints an error message if we are concerned about someone being insane enough to try to use more than 65536 frames in an animation, it does not have to crash.

**Comment by hecktest** [comment]
A static check when creating the texture should be good. As long as it can prevent a seemingly random crash to desktop. If somebody did crash because of this, it would be extremely hard to guess the cause without a debugger.

**Pull request merged**
