### PR TITLE
Use range-based fog instead of z-plane based.

### LINKED ISSUE #4626: Plane/z based fog looks weird
I noticed that the fog in Minetest looks weird. An object looked at head-on may be hidden in the fog, as I turn it becomes visible again, and the edges to the left and right are not smooth.

As long as no shaders are used this is just telling Irrlicht to do range based fog, which looks much better, as the visible area (not surprisingly) appears round:

```
diff --git a/src/game.cpp b/src/game.cpp
index 4f89aa6..e8e8eee 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -4166,7 +4166,7 @@ void Game::updateFrame(ProfilerGraph *graph, RunStats *stats,
                                runData->fog_range * 1.0,
                                0.01,
                                false, // pixel fog
-                               false // range fog
+                               true // range fog
                );
        } else {
                driver->setFog(

```

I tried to change the shaders accordingly, but I must be missing something as the effect is unchanged even as I change from using the view position's z coordinate to its length. (I know nothing about fragment shaders, really)

The following does NOT work (maybe someone can help me here):
```
diff --git a/client/shaders/nodes_shader/opengl_fragment.glsl b/client/shaders/nodes_shader/opengl_fragment.glsl
index 6862842..5d3f6a2 100644
--- a/client/shaders/nodes_shader/opengl_fragment.glsl
+++ b/client/shaders/nodes_shader/opengl_fragment.glsl
@@ -197,13 +197,13 @@ void main(void)
 #if MATERIAL_TYPE == TILE_MATERIAL_LIQUID_TRANSPARENT
 	float alpha = gl_Color.a;
 	if (fogDistance != 0.0) {
-		float d = max(0.0, min(vPosition.z / fogDistance * 1.5 - 0.6, 1.0));
+		float d = max(0.0, min(length(vPosition) / fogDistance * 1.5 - 0.6, 1.0));
 		alpha = mix(alpha, 0.0, d);
 	}
 	col = vec4(col.rgb, alpha);
 #else
 	if (fogDistance != 0.0) {
-		float d = max(0.0, min(vPosition.z / fogDistance * 1.5 - 0.6, 1.0));
+		float d = max(0.0, min(length(vPosition) / fogDistance * 1.5 - 0.6, 1.0));
 		col = mix(col, skyBgColor, d);
 	}
 	col = vec4(col.rgb, base.a);
diff --git a/client/shaders/water_surface_shader/opengl_fragment.glsl b/client/shaders/water_surface_shader/opengl_fragment.glsl
index 1fa6695..ab53c6c 100644
--- a/client/shaders/water_surface_shader/opengl_fragment.glsl
+++ b/client/shaders/water_surface_shader/opengl_fragment.glsl
@@ -153,13 +153,13 @@ vec4 base = texture2D(baseTexture, uv).rgba;
 #if MATERIAL_TYPE == TILE_MATERIAL_LIQUID_TRANSPARENT || MATERIAL_TYPE == TILE_MATERIAL_LIQUID_OPAQUE
 	float alpha = gl_Color.a;
 	if (fogDistance != 0.0) {
-		float d = max(0.0, min(vPosition.z / fogDistance * 1.5 - 0.6, 1.0));
+		float d = max(0.0, min(length(vPosition) / fogDistance * 1.5 - 0.6, 1.0));
 		alpha = mix(alpha, 0.0, d);
 	}
 	col = vec4(col.rgb, alpha);
 #else
 	if (fogDistance != 0.0) {
-		float d = max(0.0, min(vPosition.z / fogDistance * 1.5 - 0.6, 1.0));
+		float d = max(0.0, min(length(vPosition) / fogDistance * 1.5 - 0.6, 1.0));
 		col = mix(col, skyBgColor, d);
 	}
 	col = vec4(col.rgb, base.a);
diff --git a/client/shaders/wielded_shader/opengl_fragment.glsl b/client/shaders/wielded_shader/opengl_fragment.glsl
index 75dd1b6..bd30bbd 100644
--- a/client/shaders/wielded_shader/opengl_fragment.glsl
+++ b/client/shaders/wielded_shader/opengl_fragment.glsl
@@ -107,7 +107,7 @@ void main(void)
 	vec4 col = vec4(color.rgb, base.a);
 	col *= gl_Color;
 	if (fogDistance != 0.0) {
-		float d = max(0.0, min(vPosition.z / fogDistance * 1.5 - 0.6, 1.0));
+		float d = max(0.0, min(length(vPosition) / fogDistance * 1.5 - 0.6, 1.0));
 		col = mix(col, skyBgColor, d);
 	}
 	gl_FragColor = vec4(col.rgb, base.a);
```

Lastly I noticed that the tone mapping in the shaders tend to make objects such seem to appear, since the fog color does not match the sky color anymore - but that's a different issue.

### PR DESCRIPTION
**Pull request by lhofhansl**
Fixes #4626

### CODE REVIEW

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
I guess this only works with the basic nodes shader enabled? Not a problem though.

**Comment by paramat** [comment]
Maybe i misunderstand, i am under the impression that anything in 'client/shaders' is only enables when basic shaders are enabled, many player disable basic shaders for performance.

**Comment by lhofhansl** [comment]
It should work with or without shaders. The change in game.cpp is for the case when shaders are disabled.

Now according Irrlicht's doc not all H/W supports range-fog.
What I found on my machine (which has both Intel and Nvidia OpenGL drivers):
- the shader code works in both cases
- without the shader it works correctly with Nvidia, but _not_ with Intel

So without shaders it depends on what Irrlichs supports, it seems.

**Comment by paramat** [comment]
Ok i'll test with my intel integrated graphics.

**Comment by sofar** [comment]
Tested on:
```
(--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 4600
```

(opengl-3.0, UXA acceleration)

Seems I see the jagged edges, not the smooth circular one, even if I make sure all the edge blocks are loaded. (so, no regression).

**Comment by lhofhansl** [comment]
Yeah. Irrlicht doesn't seems to support range fog on the integrated Intel graphics - shame.
Does it work when you turn the shaders on?

**Comment by sofar** [comment]
@lhofhansl no, as I pointed out in my edit, I play with shaders enabled by default...

**Comment by sofar** [comment]
Actually, I take it back

This pach works with shaders enabled: No matter where I look, the fog is perfectly consistent with distance. With shaders enabled, I can see the old behavior.

So, this is actually working on Intel HD video with shaders enabled.

**Comment by Fixer-007** [comment]
Interesting, will check it out.

**Comment by sofar** [comment]
@lhofhansl  perhaps slightly reduce the fog range so that the jagged edging disappears in the fog?

**Comment by Fixer-007** [comment]
I hope it does not decrease viewing distance much.

**Comment by paramat** [comment]
Confirmed on Intel integrated graphics (Intel® Haswell Desktop) that fog is circular when basic shaders enabled, but as before with basic shaders disabled.
Might be best to not enable range fog for the shaders off case?

**Comment by lhofhansl** [comment]
The fog range is related to many other settings. At least these two:
max_block_send_distance, max_block_generate_distance

I have them set to:
max_block_send_distance = 11
max_block_generate_distance = 12

Since these are mapblocks, I have my fog range set to 160 (i.e. 10 mapblocks). That way the terrain is generated and sent by the time it becomes visible.

I also change these, so that mobs are roughly out of sight before they "vanish" (but you need a fast server for this).
active_object_send_range_blocks = 8
active_block_range = 7

(Unrelated... These could be something to configure together maybe, maybe limit the fog-range to 10x `min(max_block_send_distance, max_block_generate_distance)` or something)

**Comment by lhofhansl** [comment]
@paramat With other cards (GeForce GT 730M, don't have anything else to test on) it looks right with and without shaders enabled, and on intergrated Intel graphics it falls back gracefully, so I think it's fine and even better to leave it on.

@sofar , @Fixer-007 It does not change the fog distance at all, just enforces it on the sides. (a head on vertex in eye coordinates is exactly as far away as its z-coordinate)

When I get more time I'll also look into the tone-mapping, which looks bad with fog enabled right now, and also the fog color, exponential fog, and perhaps a shorter range but only starting at certain distance, so it looks more real.

**Comment by paramat** [comment]
> so I think it's fine and even better to leave it on.

FIne by me.

**Comment by Fixer-007** [comment]
Comparison in real environment:
* New fog, horizon level
New fog:
on
Old fog:
off

* Viewing sky
New fog:
on2
Old fog:
off2

As you can see new fog obscures more in all directions (since it is ranged).
ATI Radeon HD6870, shaders enabled.

**Comment by lhofhansl** [comment]
@Fixer-007 cool thank! It works in Radeon too.

The part to point out is that before the change it just used the eye-z-coordinate to render the fog, not the actual distance.
So whatever is right in front of you (where the cross it) has the same amount of fog - and I think that's what I am seeing in your screen shots.
As you turn, before the change things shrouded in the fog would become visible again, and edged are jagged even when the terrain has already be generated. That is what this fixes.
One way to try this is to look at what's in front of you and see how it gets more visible as you turn and see it from the side.

**Comment by sofar** [comment]
:+1: - This is a great improvement.

**Comment by Fixer-007** [comment]
Performance seems good. :+1:

**Comment by paramat** [comment]
I'm still not sure about enabling it when basic shaders are disabled, what is the performance of Irrlicht range fog like?

**Comment by lhofhansl** [comment]
@paramat that's cool.

Irrlicht's range fog does work for example on Nvidia GeForce GT 730M (without shaders).

Not quite sure I follow the 2nd part. The change in game.cpp just switches from z-depth fog to range-fog, it doesn't enable fog - unless I misunderstand the code. Where is MTs own fog implementation?

**Comment by paramat** [comment]
I was wrong, removed comment.

**Comment by paramat** [comment]
See http://irc.minetest.net/minetest-dev/2016-10-13#i_4724094

**Comment by sfan5** [comment]
0ad40fd484f57ab5d0536f9aaa892997f8aa9bd2

**Comment by lhofhansl** [comment]
Thanks!

In "real life" I work on large, distributed databases, so looking at the Minetest code is/was very refreshing :)

**Comment by paramat** [comment]
We need the help too.

**Comment by nerzhul** [comment]
@lhofhansl you work for cirusdata ?

**Comment by lhofhansl** [comment]
@nerzhul should I? :)
no, I work at Salesforce. We run some distributed databases over a few dozen thousand machines, mostly HBase and related stuff.

**Pull request closed without merging**
