### PR TITLE
Server list cleanup

### PR DESCRIPTION
**Pull request by ShadowNinja**
This removes the hacky server_dedicated pseudo-setting.

IIRC there was also a bug with the dedicated flag not being set properly in some scenarios, but I don't remember what the conditions were ATM.
Split out of #2604.

### CODE REVIEW

**Comment by sfan5** [comment]
what did `server_dedicated` even do?

also it should probably be removed from the server list HTML page

**Comment by ShadowNinja** [comment]
@sfan5: It was essentially a hacky way of storing a global variable.  It got written out the the conf file but was never supposed to be read from there since it was set at runtime.

**Comment by SmallJoker** [comment]
:+1: for removing this setting entirely.

**Comment by SmallJoker** [comment]
b8484ef

**Pull request closed without merging**
