### PR TITLE
Colorblindness correction support

### PR DESCRIPTION
**Pull request by Minetest-j45**
Do not be mistaken by the name of this PR ("Colourblind correction"), this doesnt give colour blind people the ability to see colours as normal people can, for more information about what colour blind correction shaders do, see https://tylerdavidhoward.com/thesis/ and http://blog.noblemaster.com/2013/10/26/opengl-shader-to-correct-and-simulate-color-blindness-experimental/. These colour blind correction shaders would make minetest more inclusive to colour blind people.

For more information bout colour blindness in general, see https://www.colourblindawareness.org/

## To do

This PR is Ready for Review.

## How to test
(you cant really tell if it helps if you see colours normally, like me, but you can just trust the theory, which i do, and even ask someone colour blind that you know, which i did, and ask if it helps them, ofc **you will need to change the shader to the right one for their colour blindness**, btw, the person i asked said it helped them)
1) first, just open a singleplayer game(or server if you want) to see that normal colours still work
2) navigate to the settings tab and go to graphics->in-game->shaders and change the setting colour_blind_correction this is set by default to 0, meaning no colourblind correction, if changed to 1, then the protanopia correction shader would be enabled, if changed to 2, the deuteranopia shader would be enabled and finally, if changed to 3, the tritanopia shader would be enabled.
3) open a single player game now(or server if you want) and see the difference

## Screenshots

image
image
image

## Credit

I got the functions that filter the normal colours to make it correct for colour blindness from https://www.shadertoy.com/view/XslyzX

### CODE REVIEW

**Comment by Wuzzy2** [comment]
So, a few questions: Is this only applied to the 3D world, and nothing else? What about the inventory, GUI, menus, etc? From the screenshots it seems the entire GUI is unaffected. Is this intentional? And why?

Also, what type of color blindness did your tester have?

Sorry, I am not well-versed in the topic of color blindness so forgive me for stupid questions, lol.

**Comment by Minetest-j45** [comment]
First of all, i want to say that none of your questions are stupid...

The colour blind correction shaders are only applied to nodes, objects(entities and wielditen) and the minimap. I guess the main reason for this is because i couldn't figure out how to apply the correction to the things you listed, btw i just messaged my friend and they say that they dont normally struggle seeing stuff in the inventory or main menus(but this might vary between the types of colour blindness)

My friend has deutranopia

**Comment by rubenwardy** [comment]
Perhaps I'm reading the shaders wrong - is this just applying a filter on the colors? What's the difference between this and [color correction options like this one](https://community.windows.com/en-us/stories/color-filter)

**Comment by appgurueu** [comment]
This is to be done in a second rendering pass and not through copy-paste.

**Comment by hecktest** [comment]
> This is to be done in a second rendering pass and not through copy-paste.

Right, it doesn't even capture the GUI in this way. This should at least be a postprocess shader inserted right before the buffer swap.

**Comment by SmallJoker** [comment]
Whereas this PR looks promising, it is not the correct implementation approach. No core dev approval in well over a week. Closing.

**Pull request closed without merging**
