### PR TITLE
Make colourized mainmenu text more readable

### PR DESCRIPTION
**Pull request by HybridDog**
Before:
2017-02-11-114127_1920x1080_scrot

After:
2017-02-11-114054_1920x1080_scrot

### CODE REVIEW

**Comment by paramat** [comment]
Nice, but now the green is brighter than the others, how about leaving green unchanged?
Is the hue of blue unchanged?
Also to consider: since modpacks have a '+' is it necessary to have a different green colour for them? I think using the same green would be ok.

**Comment by HybridDog** [comment]
> now the green is brighter than the others

green was brighter before, too
Coloured text should not get high saturation for readability.

>Is the hue of blue unchanged?

lt has a bit more green than red now.
If you increase brightness of bare blue, it looks rather violet.

**Comment by paramat** [comment]
Yes, but the green doesn't need to be brighter, it's easier on the eyes if all collours are similar brightness. This PR makes blue and dark green readable but now the green is too bright.

**Comment by HybridDog** [comment]
You need to consider (not in the screenshot) that disabled mods are coloured white.
2017-02-11-201937_1920x1080_scrot
2017-02-11-202138_1920x1080_scrot

**Comment by paramat** [comment]
Sorry, this is ok then.

**Comment by paramat** [comment]
2bd10022cb06850a404f180c455954ed2f817ce3

**Pull request closed without merging**
