### PR TITLE
Add minetest.global_exists()

### PR DESCRIPTION
**Pull request by ShadowNinja**
Allows for global existence checks without warnings.

### CODE REVIEW

**Comment by t4im** [comment]
Checking for a mod is not equivalent to checking for a functionality.
* A mod can lack a functionality in an earlier version. Testing for a mod then instead might yield nil problems when a mod was not updated fast enough to use the new api etc. A problem that could be easily avoided.
* You might want to check if a given minetest api function is declared before actually using it around its introduction. If something was added in latest git, you could use it conditionally then without breaking compatibility with stable clients.
* Multiple mods might provide the same functionality:
  * imagine a intllib replacement of a mod called intllib-ng should intllib itself get stale and not be developed further… checking for intllib functionality instead of mod existance allows for drop-in replacements
  * Duplication via mod-fallbacks is occuring. `homedecor:plastic*` is being added by more than 3 mods already if there should be no homdecor loaded. It's not unreasonable to assume to see the same with functions or tables if one looks for it. Why have your code add another fallback, if one was already provided by another mod?

As explained in #2236, not having an option to do these checks intentionally with supressed warning leads to people to worsen code by increasing coupling and lessen functional guarantees just to avoid the warning.
:+1: for a function like this.

Though i would suggest using some name that is closer to natural language usage:
* `minetest.is_declared(…)`
* `minetest.exists_globally(…)`
* `minetest.is_set(…)`
* `minetest.is_nil(…)`
* `minetest.get(…) ~= nil`

The latter would also allow for extensions of tables like technic is doing:
`technic = minetest.get("technic") or {}`
Which would allow someone to extend or configure technic before it was even loaded.

**Comment by nerzhul** [comment]
jenkins rebuild please

**Comment by nerzhul** [comment]
I agree with minetest.global_exists name. If you want to merge it, no problem for me

**Comment by est31** [comment]
436cb468e9a832d15009d527d80c8dfe86bb2772

**Pull request closed without merging**
