### PR TITLE
[No Squash] Use .md extension for markdown files

### PR DESCRIPTION
**Pull request by rubenwardy**
This renames documention files to .md, including lua_api.txt -> lua_api.md.

### Why?

Because they're markdown files. Using the correct extension allows GitHub and editors to show syntax highlighting and render the markdown nicely.

It also allows anchor links to work

### But what about line numbers?

Linking to line numbers is very brittle, and should be discouraged in favour of anchor links where possible. Linking to sections/headings is much better when it comes to keeping links alive. We should make sure to add more subheadings to make it easier to link to the correct section.

**If you still want to link to a line number, you can append ?plain=1 to GitHub's URL, ex: https://github.com/rubenwardy/minetest/blob/md/doc/lua_api.md?plain=1#L123**  This is a new feature, added since this was last discussed.

### What about Windows users?

~~What's a Windows user?~~

Most of the documentation online links to the GitHub web version. Being able to open text files is a fairly important skill, and something that will be needed to edit eg: .conf and .lua files.

### What about broken links?

I've added a stub lua_api.txt file to link to the new .md file. As for line numbers, they break regularly between releases anyway

## To do

This PR is Ready for Review

## How to test

View it: https://github.com/rubenwardy/minetest/blob/md/doc/lua_api.md

### CODE REVIEW

**Comment by appgurueu** [comment]
This will lead to merge conflicts in practically all PRs.

**Comment by rubenwardy** [comment]
> This will lead to merge conflicts in practically all PRs

Git can handle renaming files. The file's content has not changed

> this is no reason not to use the proper file extension though as ?plain exists

Exactly

**Comment by sfan5** [comment]
How it looks: https://github.com/rubenwardy/minetest/blob/md/doc/lua_api.md

**Comment by appgurueu** [comment]
I've tested this using https://github.com/minetest/minetest/pull/12388 by making a PR against rubenwardy's `md` branch and indeed I am getting a merge conflict for `lua_api.txt`.

**Comment by rubenwardy** [comment]
> I've tested this using #12388 by making a PR against rubenwardy's `md` branch and indeed I am getting a merge conflict for `lua_api.txt`.

This only happens because I readded the lua_api.txt file with a link to the new file. If I remove that commit, Git does handle the rename correctly

**Comment by Desour** [comment]
(Imho plain text is prettier and easier to read (and write).)

While you are at renaming the file, why not give it a more suitable name, i.e. something like `server_modding_api.md`. After all, there are many things in there that have nothing to do with lua.
(Properly splitting the file into its topics would be even better...)

**Comment by Zughy** [comment]
I must say, I agree with @Desour . It's way too spread, focusing is harder
imagen

But that's a GitHub issue, because the same document on GitLab looks like this:
imagen

**Comment by runsy** [comment]
Good idea.

**Comment by Zughy** [comment]
I've actually changed my mind: I think, since these documents are just for modders, info are faster to gather with plain text formats (Ctrl+F). For tutorials and the like we already have the modding book and the minetest docs repo

**Comment by rubenwardy** [comment]
The fact is that the file format is just wrong. It's a markdown document with a .txt extension, it makes no sense. It's super easy to change to plaintext view in GitHub

> (Imho plain text is prettier and easier to read (and write).)

It's still a plain text document, this PR doesn't make it binary. It just gives it the correct file extension. The format also depends on the CSS

**Comment by Zughy** [comment]
sfan5 take: https://irc.minetest.net/minetest-dev/2022-08-28#i_6010987
x2048 take: https://irc.minetest.net/minetest-dev/2022-08-28#i_6010995

**Comment by SmallJoker** [comment]
Markdown rendering could be more appealing to modders, so I am not opposed to this change.

Is it possible to prepend some CSS to control the line spacing to fix up GItHub's shortcomings? That would solve the last concern that I'd have.

**Comment by kwolekr** [comment]
:+1:

**Review by Abdou-31 — CHANGES_REQUESTED** [review]
You missed `^ spec = SimpleSoundSpec (see lua-api*.txt*)` , in doc/menu_lua_api.txt, line 79.
In #12882 , I've fixed that to `lua_api.txt`.

**Comment by rubenwardy** [comment]
To rebase other PRs without conflicts:

```
git remote add upstream https://github.com/minetest/minetest

git fetch upstream
git rebase --onto b1786e88ac8921d9c4f0cfe366fdf7e2c965984c $(git merge-base HEAD upstream/master)
git pull --rebase upstream master
```

**Pull request merged**
