### PR TITLE
Disable dynamic shadow dropdown on OGLES2

### PR DESCRIPTION
**Pull request by rollerozxa**
As dynamic shadows will not be functional on OGLES2 for 5.6.0, the relevant dropdown should be hidden in the settings to prevent someone accidentally enabling it.

## To do
This PR is Ready for Review.

## How to test
Check so the dynamic shadow dropdown doesn't show up on OGLES2.

### CODE REVIEW

**Comment by JayAsPro** [comment]
Hello! Sorry for the question.
Does this mean that it will be impossible to use dynamic shadows on Android? If so, why? There is some technical limitation or obstacle? I really missed it while following the development.
Thanks!

**Comment by Extex101** [comment]
> Hello! Sorry for the question. Does this mean that it will be impossible to use dynamic shadows on Android? If so, why? There is some technical limitation or obstacle? I really missed it while following the development. Thanks!

The shaders would have to be completely rewritten for Ogles2. 
So this change doesn't do much but prevent bugs/crash by removing the option to enable it when Ogles2 is enabled

**Comment by rollerozxa** [comment]
> Hello! Sorry for the question. Does this mean that it will be impossible to use dynamic shadows on Android? If so, why? There is some technical limitation or obstacle? I really missed it while following the development. Thanks!

Yes, the current dynamic shadows implementation does not work on OGLES2, see #11339.

**Comment by sfan5** [comment]
If I check the shader checkbox this happens and the mainmenu never works afterwards:
```
2022-08-03 21:27:14: ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): minetest/bin/../builtin/mainmenu/tab_settings.lua:232: bad argument #2 to 'set' (string expected, got boolean)
2022-08-03 21:27:14: ERROR[Main]: stack traceback:
2022-08-03 21:27:14: ERROR[Main]: 	[C]: in function 'set'
2022-08-03 21:27:14: ERROR[Main]: 	minetest/bin/../builtin/mainmenu/tab_settings.lua:232: in function 'get_formspec'
2022-08-03 21:27:14: ERROR[Main]: 	minetest/bin/../builtin/fstk/tabview.lua:66: in function 'get_formspec'
2022-08-03 21:27:14: ERROR[Main]: 	minetest/bin/../builtin/fstk/ui.lua:101: in function 'update'
2022-08-03 21:27:14: ERROR[Main]: 	minetest/bin/../builtin/fstk/ui.lua:145: in function 'handle_buttons'
2022-08-03 21:27:14: ERROR[Main]: 	minetest/bin/../builtin/fstk/ui.lua:186: in function <minetest/bin/../builtin/fstk/ui.lua:172>
```

**Comment by rollerozxa** [comment]
looks like I forgot to use `set_bool`, I'll fix that real quick

**Comment by sfan5** [comment]
You're also setting the boolean everytime the formspec is generated, that seems suboptimal.

**Comment by rollerozxa** [comment]
Yeah I personally don't think the setting should be explicitly set to disabled like that, but it was a suggestion from Krock yesterday to prevent someone from accidentally enabling it.

**Comment by sfan5** [comment]
If at all that's the job of C++ imo.

**Comment by rollerozxa** [comment]
Yeah so adding `&& g_settings->get("video_driver") == "opengl"` to every check for the `enable_dynamic_shadows` setting in C++?

**Comment by rollerozxa** [comment]
Done. Please test this, as I haven't tested the C++ changes (still compiling)

**Review by sfan5 — APPROVED** [review]
Tested

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
