### PR TITLE
Don't crash on bad env_meta.txt file

### LINKED ISSUE #2663: [Request] Improve EnvArgsEnd errors
Instead of an error being thrown when the EnvArgsEnd is missing:
https://github.com/minetest/minetest/blob/master/src/environment.cpp#L532

Why not just have minetest reset the file?

Not sure if this has already been looked at before, but for such a simple error i cant see any reason why this hasnt been done already.

### PR DESCRIPTION
**Pull request by Splizard**
Fixes #2663

### CODE REVIEW

**Comment by PilzAdam** [comment]
What relies on the timestamps? I think it may not be good to (almost) silently ignore this. I'd prefer a system similar to `ignore_world_load_errors`, where the server admin has to actively accept that data might be corrupted.

**Comment by Splizard** [comment]
The point is if that file is corrupted then there is no point in an error since your only option is to remove the file anyway. Why not automate this? I am thinking from an end user perspective. If I play minetest and this error comes up I might just think that the entire world is corrupted and will never load again. As an end user (a child for example) I may not know how to find the world folder and delete the required meta file.

**Comment by rubenwardy** [comment]
Maybe something like:

> A problem occurred when reading the ingame time. We've corrected this, and it should be fine, but you may notice weird behaviour. 

Although that is a bit long.

**Comment by Splizard** [comment]
Yea something like that would be alright :)

**Comment by PilzAdam** [comment]
@Splizard I was thinking about server admins that would rather restore a backup than continue with invalid data.

There also may be mods that rely on timestamps being accurate. Thats why I was asking what exactly is influenced by randomly changing `game_time`. Node timers? ABMs with catch up behavior?

**Comment by kahrl** [comment]
Does the server still write incomplete env_meta.txt files? I was hoping this would be fixed since commit 64c060e1f2d94d8277246d8cdd8a886010564770.

**Comment by 0-afflatus** [comment]
> If I play minetest and this error comes up I might just think that the entire world is corrupted and will never load again. 

I had exactly this experience last week.
I have restored this file from all sorts of odd places. The side effects of changing game_time do not appear to be critical. Some mobs hanging around and the game age is reported incorrectly on http://servers.minetest.net/ It would be ideal if this file isn't left blank on a server crash.

**Comment by rubenwardy** [comment]
I feel like this just fixes the symptom of the files getting corrupted

**Comment by nerzhul** [comment]
i agree closing on this, game_time is used on several mods and can make game inconsistent, just have backups

**Pull request closed without merging**
