### PR TITLE
Docs: add "flip moon texture" into breakage file

### PR DESCRIPTION
**Pull request by Zughy**
As someone who both makes art and develop, the flipped moon still annoys me (yes, it is flipped if you've had to document it #11940). Considering the "controversial" tag in #11902, this should be an approach that makes everyone happy in the long run

## To do

This PR is Ready for Review.

## How to test
read

### CODE REVIEW

**Comment by appgurueu** [comment]
> > Second, only you seem to think there is a “right” way up.
> 
> imagen
> 

Oh so we're going with popularity here? Guess what:

Bildschirmfoto von 2022-06-09 17-48-06

Note that "thumbsup" on the *issue* does *not* endorse any specific way of "resolving" it. Documenting it solved the issue.

**Review by rubenwardy — APPROVED** [review]

**Comment by corarona** [comment]
once you have broken everything at least one time, will you consider making the world larger ? :(

**Comment by rubenwardy** [comment]
Yes, that should be added to this file

Please note that this file is not binding, it's notes about things to consider when doing 6.0. I don't think the moon direction is important, either convention is fine, I just don't want to spend any more time talking about it

**Comment by appgurueu** [comment]
> I don't think the moon direction is important, either convention is fine, I just don't want to spend any more time talking about it

Then close this PR.

**Comment by rubenwardy** [comment]
If anyone cares about this when we get to 6.0 then we can have the discussion then. I cba to go through this discussion again for such a tiny issue

**Comment by rubenwardy** [comment]
Actually, I'll just unsubscribe from this thread

**Comment by celeron55** [comment]
I would be fine either way, so if any core dev wants this in I give them my approval.

**Review by sfan5 — APPROVED** [review]
`<+sfan5> it will be reassesed anyway when the time actually comes so we can just add it to the file`

**Pull request merged**
