### PR TITLE
Customizable loading screen

### PR DESCRIPTION
**Pull request by kilbith**
Because people should be entertained even during that long (and boring) loading screen. This PR makes it customizable with texture packs.

A `tips.txt` file (placed at root dir) has been added, each tip separated by a newline. That and the background image included in this PR are just for showcasing and can be safely removed prior merging.

There's room for improvements: `tips.txt` and `loading_screen.png` should be fetched from games. Same for the progress bar textures. And a sound could be played. But... laziness.

Enjoy.

**Demo video:** https://www.youtube.com/watch?v=p7wD159t-8Q

Capture d’écran du 2022-12-19 21-41-22

### CODE REVIEW

**Comment by PrairieAstronomer** [comment]
Since this has the tips as global as of writing, may I suggest a few tips?

- Minetest is not Minecraft.
- Minetest Game is better played with mods.
- Go to the Content tab to download more games and mods.
- You can choose which installed mods are loaded in each world.
- Lua Rocks!

**Comment by PrairieAstronomer** [comment]
There is an issue where not having a loading_screen.png image will throw an error and a dummy image will be built.
image

**Comment by SmallJoker** [comment]
Might it be possible to download this media file before any other upon connect? That would extend the use-case of this feature to any server and not just local games.

**Comment by kilbith** [comment]
I'm not capable of dealing with the network code, but feel free to.

**Comment by sorcerykid** [comment]
Thanks for the hard work on this PR. Once again very promising endeavor. I too think this would have a lot of benefit if it could be engineered to work with servers too. For reference, my comment here https://github.com/minetest/minetest/issues/9549#issuecomment-603994155

**Pull request closed without merging**
