### PR TITLE
util/travis/: Allow common.sh and lint.sh to be executable

### PR DESCRIPTION
**Pull request by ClobberXD**
The lack of exec. permission on lint.sh caused quite a bit of confusion on my end, when I was trying to run LINT. Hopefully there's no risk in making these files executable.

### CODE REVIEW

**Comment by nerzhul** [comment]
common.sh doesn't intend to be executed directly it's a "lib"

**Comment by ClobberXD** [comment]
I see. Is it not possible to execute the scripts in the terminal, and then call the functions they define?

**Comment by nerzhul** [comment]
sourcing doesn't require exec privs

**Comment by ClobberXD** [comment]
Neato

**Pull request closed without merging**
