### PR TITLE
Ability to define and use LUA wield animations

### PR DESCRIPTION
**Pull request by TheMrAmazing**
I found this old pull request: #7517
that added several wield animations in C++ that could be added to tools, such as an eating animation or a digging animation. It looks like it was rejected because you could not define new animations in LUA, making it not particularly useful for modding. I really liked the concept, so I added the ability to add new wield animations through the LUA.

This is my first time contributing, so I'm sure I've made some mistakes, but I'm happy to fix whatever is needed to get this feature added to the game

This is my second pull request for this feature, because I made a mess of the commit history on the last one

### CODE REVIEW

**Comment by paramat** [comment]
Thanks, i appreciate you having the patience to try again.
Because you have little experience of MT codestyle it is probably best to almost completely ignore CF, as you will not know what is acceptable codestyle. Only take notice of it if it highlights something that is very obviously an error.

**Comment by davidjohnbell** [comment]
This is a really exciting change, any news on this?

**Comment by rubenwardy** [comment]
Is this ready for review?

**Comment by TheMrAmazing** [comment]
> 
> 
> Is this ready for review?

Absolutely! I'm hoping for feedback, as soon as possible because I really want to start making mods with this feature.

**Comment by paramat** [comment]
@TheMrAmazing #10468 documents how to work with ClangFormat, any comments welcome.

**Comment by appgurueu** [comment]
Please add documentation, fix your todos and resolve the merge conflict.

**Comment by appgurueu** [comment]
Related: #10360 also allowing for custom wield animations

**Comment by TheMrAmazing** [comment]
> Please add documentation, fix your todos & the code style. Also resolve the merge conflict.

Is this still something I should bother with, it has been months and very little interest seems to have been shown?

**Comment by appgurueu** [comment]
> > Please add documentation, fix your todos & the code style. Also resolve the merge conflict.
> 
> Is this still something I should bother with, it has been months and very little interest seems to have been shown?

I would sure like to use this feature. Fixing the merge conflict, code style & adding documentation is not that much work. I don't know about the TODOs, I only skimmed them.

I would not like to see those seven hundred lines of code go to waste.

**Comment by ZedekThePlagueDoctor** [comment]
I too would like to see this implemented. Viewmodels / wielding could use a lot of work and extension in general.

**Comment by sfan5** [comment]
Here's a list of problems I identified:
* Code style
* Lack of documentation
* unused functions/global variables, debug-looking code still lying around, code commented out instead of deleted
* repository of wield animations is just a global variable, no transfer from server to client. This doesn't work. (the serialization code seems to exist already?!)
* `read_wield_animation` should be side-effect free (not handle repository init and insertion, only read and return the animation)
* `read_wield_animation` has some code duplication, also not sure if the vector + sort is necessary (lua tables should already be sorted)
* code modernization in splinesequence especially manual iterator usage

**Comment by rubenwardy** [comment]
Closed due to lack of response

**Pull request closed without merging**
