### PR TITLE
F5 Debug info: More compact, return to 2 lines 

### PR DESCRIPTION
**Pull request by paramat**
F5 Debug info: More compact, return to 2 lines

All data fits on width 960, most useful data still visible on width 800.
//////////

screenshot_20171125_205533

^ 960x720

screenshot_20171125_205810

^ 800x600 with 'view all loaded blocks' enabled. Only param2 is cut off

Attends to #6666 

Makes F5 debug similar to how it was before i made a mess of it in #6125 
Removes unnecessary spaces, brackets and equals signs, and shorten 'pointng_at' to 'Pointed', to make more compact and clearer.
'Range all' has been combined with 'View range' using code from #6225 

This allows us to move 'pointed node' back to the end of the 2nd line, and move chat up 1 line.

### CODE REVIEW

**Comment by rubenwardy** [comment]
The contractions are unacceptably unreadable

**Comment by paramat** [comment]
Looks like we can expand them a little, luckily.

**Comment by paramat** [comment]
Updated, just enough room.

**Comment by Ezhh** [comment]
No commas between the different pieces of information makes it much harder to read. Could those be kept?

**Comment by basicer** [comment]
Is seed needed? Seems like it has a low length to usefulness ratio.

**Comment by MarkuBu** [comment]
No, don't remove param2. That was helpful

**Comment by IhrFussel** [comment]
Are you serious with removing param2???

Who needs the map seed in F5? What is its usefulness other than making it so others can "steal" your map? Just look into your map_meta.txt if you need to know it, it really isn't that hard.

param2 helped e quite a few times in my server development, it showed me which nodes store param2 and how. I cannot describe enough how important it is to keep.

**Comment by MarkuBu** [comment]
Suggestion: add a second debug page with more detailed information and without looking at the screen size.

And to prevent cheating the server can disable the debug function. 

But removing useful information just to save a bit of space for the 3 people who still need to play on a 800*600 screen is ridiculous 

Look at the debug screen from Minecraft. That is a mess and fills the whole screen, but it has lots of information I would expect from such a function. Just the presentation could be better

**Comment by Ezhh** [comment]
I woke up thinking:
Default screensize is currently 1029 by 644. Why are we using 800 by 600 as the size to develop for?

**Comment by Ezhh** [comment]
@IhrFussel I've built on your map. Am I stealing if I want a copy of my own buildings and the ability to create a world were the mapgen (hopefully) matches what I was working with? Servers shutdown, maps get reset, yet players might have spent hundreds of hours on them.  (Seed is not even the thing that permits copying buildings from a map in the first place.)

I really do not want to make seed inaccessible to a normal player; is there an alternative place we can put it where  a normal player can still retrieve it from?

**Comment by MarkuBu** [comment]
1029 by 644? What kind of screensize is that? Is there really anybody out there who is not able to play the game at 720p?

**Comment by Ezhh** [comment]
@MarkuBu  They didn't want to go that high. 1029 by 644 is a weird one, but from what I recall was the compromised reached since anything else the devs were willing to move to meant actually reducing one dimension. 

Regardless of what the default is though, it's wider than 800, so I find it odd that we'd need to horizontally cram things together, even to the extent of removing commas, just to fit it into 800.

**Comment by MarkuBu** [comment]
Indeed, it's ridiculous

**Comment by SmallJoker** [comment]
```
Minetest 0.5.0-dev-githash-dirty, 59 FPS (3 ms, 5% jitter), 40 View range, 1 ms RTT
(1337.3, -5.5, -666.6), 3.5° North [X+], Pointed: (default:stone_with_some_ingredients, param2 = 2)
```
1) Seed is not helpful
2) Compressed FPS, dtime and jitter information, as all belong together
3) Comma separation and first letter in capitals for easier reading
4) Coordinate indicator for the view direction

My two cents.

**Comment by Ezhh** [comment]
I'd agree completely with SmallJoker's example above, apart from not seeing why the full "North [Z+]" is needed, and wanting to make sure seed is kept somewhere a player can get it.

I also really wonder why the version info is needed in F5. Sure, it's good to have, but can't it go somewhere else as well so that you don't need it taking up so much space where it's not constantly needed?

**Comment by MarkuBu** [comment]
Well, seed and version are helpful if you want to share a screenshot for some reason. But as I suggested before a second and more verbose debug page would solve many of these issues

**Comment by IhrFussel** [comment]
@Ezhh I didn't mean such a case like you described.

But in my personal experience I only was once in a situation where I needed the seed. Other people "stealing" the seed to copy your server world and making it public isn't nice either.

Seed can remain if param2 remains. That's my opinion.

Maybe move the Minetest version hash somewhere else (pause menu, later debug stage etc).

**Comment by Fixer-007** [comment]
Unreadable

**Comment by BluebirdGreycoat** [comment]
*Don't* remove existing information from debug info. *Do* allow server to disable debug info if some server owner needs to prevent players from seeing coords or nodetype or param2, etc. *Do* add another page for this info if you cannot bring yourself to cram it over the gameplay screen like MC does.

**Comment by paramat** [comment]
Default screen size is 1024x600, a common 'small screen size'.

>  Is there really anybody out there who is not able to play the game at 720p?

That's ridiculous snobbery, MT is used, and is designed to be used, by very many people in countries rich and poor, with old or low powered machines. I have a mid-power desktop with Intel core i5 and i use a smaller game window than 720 HD for performance reasons. 720 HD is HD after all and a very nice mid size, in no way small.

I'll add commas.
I'll add -X +X etc.
Seed will stay, it's essential for screenshots to reproduce what you see.
I'll re-add param2, i don't mind.

SmallJoker variable names after is counterintuitive. Seed is essential. Leaving out variable names is sloppy, dtime is not drawtime and neither are implied by FPS.
However i agree with:

> Comma separation and first letter in capitals for easier reading
Coordinate indicator for the view direction

Will do those.

I'm not going to make it completely configurable as that is far too overcomplex. Splitting info onto different stages of F5 will cause extreme bikeshedding and arguments, i can't face that.

**Comment by paramat** [comment]
Updated, does look better due to some of your suggestions. I'm now working with 960x720 as a 'small screen size', only param2 is cut off if 800x600 is used.

**Comment by Fixer-007** [comment]
what it the reason for; upper case first letter after comma? Induces OCD

**Comment by Ferk** [comment]
Note that Minetest supports expressing the seed in hexadecimal when prefixed with "0x" ([see read_seed code](https://github.com/minetest/minetest/blob/20a85d76d94c9c5c7fbe198c3d0e1fbee97a485f/src/util/string.cpp#L451-L465)).
You could reduce the length of the seed string by using hex instead of decimal (it'd also make it easier to share seeds when they are shorter).

**Comment by paramat** [comment]
Fixer, readability, helps the eye move to the start of variable names.

Hex would be a pain to convert, people want human readable seed.

**Comment by Ferk** [comment]
A 24 digit number is not exactly human readable. Precisely making it shorter using hex or base64 would help the readability, imho. It's a pain to copy 24 numbers manually, specially since it's typically in a screenshot.
The users would not need to convert it back, since it's already supported by Minetest off the bat, you type "0xffff" as seed in the word generation dialog and you get seed "65535".

**Comment by paramat** [comment]
Ok, didn't know it was supported when entering a seed. But still, i think we prefer to have it in base 10 because it's a more familiar number system, and anyway, there's no need to shorten it for the purpose of this PR.

**Comment by HybridDog** [comment]
I think the debug info should get different fonts: small monospaced font. And monospace font size should be configurable separately for chat, big chat (F10) and debug info.
As side effect, this would also fix the `default` and `defauIt` looking the same problem in the nodename.
If the info fits into the window width (you can use a heuristic to find it out), it's shown in two lines, else three lines.
Also, it should use two colours, one for the names (e.g. `Minetest`) and one for the values (e.g. `0.5.0-dev-smell`)

**Comment by paramat** [comment]
ea1ae07beb4c65b29a356c64971e49249f7c5118

**Pull request closed without merging**
