### PR TITLE
Support 6 textures for more drawtypes

### LINKED ISSUE #6929: Allow 6 different textures for more drawtypes
Many drawtypes can only accept 1 texture, seems based on basic usage in early MTG.
@numberZero would this have any performance impact?

EDIT: Making an existing drawtype support 6 tiles may affect performance, testing is required to find out. If so, it might be better to add a new drawtype specifically for when multiple tiles are needed.

### PR DESCRIPTION
**Pull request by numberZero**
Fix #6929
@paramat here is the PR. Currently it supports allfaces and glasslike. glasslike_framed works as documented. glasslike_framed_optional works.

### CODE REVIEW

**Comment by numberZero** [comment]
@paramat Before this PR, `glasslike_framed_optional` was treated as either `glasslike` or `glasslike_framed`, depending on client’s settings, without any conversion. So, depending on these settings, second tile was either unused or used for the frame. That actually means I could not add 6-texture support to `glasslike` not changing `glasslike_framed_optional`.

In this PR, I managed to keep backward compatibility, while adding full 6-tile support to all `glasslike*` drawtypes. Current tile definitions are supported, but canonical form now is to use first special tile for frame and normal tiles for details in `glasslike_framed` and `glasslike_framed_optional`; `glasslike` uses normal tiles only, for sides. In conversion from `glasslike_framed_optional`, tiles are overlaid with first special tile to ensure frame presence. That’s imperfect (e.g. disregards tile colors) but should be acceptable.
```lua
minetest.register_node("nodes:glass", {
	description = "Glass",
	drawtype = "glasslike_framed_optional",
	paramtype = "light",
	paramtype2 = "facedir",
	tiles = {
		{name="glass_details.png", color="#FF0000"},
		{name="glass_details.png", color="#FFFF00"},
		{name="glass_details.png", color="#00FF00"},
		{name="glass_details.png", color="#00FFFF"},
		{name="glass_details.png", color="#0000FF"},
		{name="glass_details.png", color="#FF00FF"},
	},
	special_tiles = {{name="glass_frame.png"}},
	groups = {cracky=3, oddly_breakable_by_hand=1},
})
```

**Comment by paramat** [comment]
Ok thanks lets consider this.

**Comment by paramat** [comment]
Do you know what mapblock mesh generation function i should be profiling?

**Comment by paramat** [comment]
I was thinking of timing the mesh generaton for mapblocks when spawning a player in identical places in identical worlds, in a forest. Then changing leaves to glasslike to also test that drawtype.

**Comment by numberZero** [comment]
@paramat It’s okay if you measure generation time of each mapblock separately, and do several measurements for each. Otherwise noise (like block load order, thread scheduling, etc.) may affect results too much.
Alternatively, you can run MT long enough to let the noise compensate itself. In that case, you probably need to do several identical runs per configuration to make sure the results don’t differ much.

**Comment by paramat** [comment]
No response from author, can reopen later.

**Comment by numberZero** [comment]
@paramat This PR was waiting testing, as a label suggests. It may probably be extended if necessary, unsure (don’t remember).

**Comment by paramat** [comment]
Thanks. Sorry for the close, there's a dev rule for closing if no response to a question.

**Comment by paramat** [comment]
For simplicity i think it is best to not include 'glasslike framed' or 'glasslike framed optional' in this, as issue #9210 suggests.
This probably needs adoption (and i suggest simplification).

**Comment by paramat** [comment]
For simplicity and avoiding potential problems i think that 'glasslike framed' and 'glasslike framed optional' should not be included in this. They are unsuitable for 6 tile usage due to the frame feature, a modder can always use normal glasslike instead. So, they are unnecessary.

**Comment by numberZero** [comment]
@paramat Am I right this is expected to alter `glasslike` and `allfaces` only?

> new drawtypes may be needed instead

The performance difference should be negligible. Even if it isn’t, it should be possible to map single Lua-side drawtype to several internal drawtypes to prevent problems described in #9210.

**Comment by paramat** [comment]
My personal preference is that this ability is only added to 'allfaces' and normal 'glasslike'. For simplicity, and because 6 tiles is not of much use for a node that can be framed, there is not much usefulness in having 6 different 'glass detail' tiles for a framed drawtype, and that has never been requested.

However that is just my opinion. The issue and this PR has had no input from other core devs, so i suggest it is best to wait for their input.

I understand from the first paragraph in https://github.com/minetest/minetest/pull/7233#issuecomment-380185081 that you had to make some changes to framed glass to make normal glass support 6 tiles, that is fine.

Even if the performance impact is small, it is in a very critical process that is a bottleneck for MT (meshgen), so i would not consider the feature worth it. I think we will probably have to do as you suggested:
> it should be possible to map single Lua-side drawtype to several internal drawtypes to prevent problems

**Comment by numberZero** [comment]
> it is best to wait for their input

@paramat This PR is here for **2 years** already.

**Comment by paramat** [comment]
LOL yes =D

**Comment by numberZero** [comment]
@paramat... If you want this feature, take action. Run it. Measure performance. Complain. Or merge. Revert is easy, will it be necessary. Do anything, just *do*.

**Comment by paramat** [comment]
My opinion of this PR is explained in https://github.com/minetest/minetest/pull/7233#issuecomment-634324659
I have already complained =)
So i disapprove of merging it in current state :-1: 

However, i certainly do not expect you to work further on this, it is labelled for adoption.
I also consider it fairly low priority, so i personally cannot justify spending time on it.
I apologise for opening an issue then later considering it low priority.

**Comment by numberZero** [comment]
> I also consider it fairly low priority, so i personally cannot justify spending time on it.

So don’t, neither mine nor yours. Will #6929 be wanted again, feel free to ping me.

**Pull request closed without merging**
