### PR TITLE
Fast place settings in controls menu

### PR DESCRIPTION
**Pull request by FoxLoveFire**
Fast place settings in controls menu

### CODE REVIEW

**Comment by srifqi** [comment]
This PR is related with #13536, #13537, and #13538. I think that the author wanted to create a PR with multiple file changes.

**Comment by Zughy** [comment]
@FoxLoveFire please make a single PR with all these changes (just edit this branch, patch-3)

**Comment by FoxLoveFire** [comment]
> @FoxLoveFire please make a single PR with all these changes (just edit this branch, patch-3)
Sorry, i noob here and now i think i make now again mistake

**Comment by ammobox** [comment]
'ery nice

**Comment by Desour** [comment]
Why would we need this feature?

**Comment by rollerozxa** [comment]
I think this feature might be considered a cheat by some.

**Comment by FoxLoveFire** [comment]
> 

I'm tired of switching every time after the game CTF

**Pull request closed without merging**
