### PR TITLE
README: make -j$(nproc)

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by Calinou** [comment]
Note that `nproc` isn't available on *BSD or macOS. This is probably fine if the instructions are worded to be Linux-only, but you may want to keep that in mind.

**Comment by paramat** [comment]
:-1: it's clearer and more widely applicable (see Calinou's comment) to state 'number of processors'.

**Comment by zaoqi** [comment]
`Compiling on GNU/Linux`

**Comment by paramat** [comment]
Sorry, my mistake, i'm neutral then.

**Pull request merged**
