### PR TITLE
Add node texture variants

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Closes https://github.com/minetest/minetest/issues/9193.

This PR adds texture variants controlled by some section of param2 that can by chosen independently from paramtype2. The number of variants is specified in a node definition with `variant_count = ...`. The part of param2 used is specified with `param2_variant = {width = ..., offset = ...}` (measurements in bits). The tiles set with `tiles` apply for variant 0, while other variant tile sets are specified in the list `variant_tiles`. The same goes for `overlay_tiles` and `special_tiles`.

## To do

This PR is ready for review.

- [x] Make tiles for all variants default to the variant 0 tiles.
- [x] Allow `overlay_tiles` and `special_tiles` to vary by variant.
- [x] Display variant textures in wield meshes. What key should be used to specify the variant in an ItemStack? `variant`? `variant_index`?
  - `variant` was chosen.
- [x] Add Lua helpers for dealing with variants.
- [x] Add documentation.
- [x] Test combining variants with various tile properties.
- [x] Test on old clients.
- [x] Test with old servers.
- [x] Test mesh generation performance.
  - Performance seems unaffected. 
- [x] Add `BitField` unit tests.

## How to test

You can test by messing around with the nodes in `games/devtest/mods/testnodes/variants.lua`. Also try connecting to an old server with a new client and vice versa.

### CODE REVIEW

**Comment by LandonAConway** [comment]
What exactly does this do? Correct me if I'm wrong but what I'm getting from this is that it adds multiple textures to a node so a node texture can change while the engine is running?

**Comment by TurkeyMcMac** [comment]
Correct, you can choose different textures from among a set without changing the content ID. This is mainly to get around the content ID limit.

**Comment by LandonAConway** [comment]
Is there some kind of limit on how many textures can be added to a node and will this be possible with nodeboxes/glass/and other paramtypes or just regular square nodes? This would be amazing for registering a single node for many colors whilist getting around a lot of the limitations of hardware coloring...

**Comment by TurkeyMcMac** [comment]
It works for any drawtype. Unfortunately it's still limited by the size of param2. A facedir node can only have 8 different variants. Changes could be put in place later to allow for reading the variant/color from metadata, but that would be a bit complicated.

**Comment by fluxionary** [comment]
> Is there some kind of limit on how many textures can be added to a node

yes, param2 values are 8 bits, so you'll have 256 possibilities per node ID.

> and will this be possible with nodeboxes/glass/mesh npdes/and other paramtypes or just regular square nodes

i admit i haven't read the whole discussion, but it's technically possible if it's not implemented here yet. however, be aware that some drawtypes (nodebox, mesh, etc) often rely on param2 to provide the ability to rotate a node (e.g. "facedir"). though see [this comment](https://github.com/minetest/minetest/issues/9193#issuecomment-1293954418) for an interesting proposal. taking that proposal 1 step further, perhaps the full 16 bits of "param" could be factored into discrete components using bit-packing magic.

**Comment by v-rob** [comment]
I like the `param2_variant` field; it scales much better than the `color<type>` paramtype variants.  It would be nice if hardware coloring were implemented the same way...

**Comment by LandonAConway** [comment]
Is this planned for the next release?

**Comment by TurkeyMcMac** [comment]
This will probably be ready in time for the next release.

**Comment by Desour** [comment]
What are the criteria on whether a nodedef field should be variant-dependent or not? I.e. what about `mesh` or `posteffect_color`?

**Comment by Desour** [comment]
Ah I see, that's nice.

My concern was rather API-design wise, what's holding us back to use a separate bitfield for every nodedef field? Or the other way around, which fields should always be grouped together and selected by a common bitfield (i.e. because choosing `special_tiles` independently from `tiles` is not useful)?
If we choose to group *all* variant-able fields together and choose with *only one* bitfield (as the current API suggests), we can't for example choose `mesh` independently from `tiles`. So I wonder how much better it will be in the end compared to registering separate nodes.
Anyway, I guess it's too early for such concerns. (I just wondered if you had some far-future design ideas to that regard. PR is design-wise fine enough. :-))

**Comment by TurkeyMcMac** [comment]
You can simulate independent properties by adding a variant for each possible combination of properties. E.g. if you had 3 tiles and 3 meshes, you would have to create 9 variants. It's a bit clunky, but it's no worse than registering separate nodes for each combination.

**Comment by runsy** [comment]
This is a must !!!

It would resolve a 12 year old request that was never implemented because... no idea why. Because the idea was easy.

For example, I find that I want to implement flowerpots in Samz and it's a nightmare. Something that should be simple.

A lot of talk that Minetest should be an engine, and this makes it easy.

I wish and hope it will be for the next release.

**Comment by fluxionary** [comment]
> For example, I find that I want to implement flowerpots in Samz

i want to implement flowerpots as an "item-frame" type node, but i have 0 skill w/ creating 3d models, and someone would have to make those available for such a behavior. 

if this PR gets accepted, that'd probably not be as big of an issue.

**Comment by runsy** [comment]
I want to test this.

How can I change the texture? settting variant in meta? setting param2? setting param2_variant?

**Comment by TurkeyMcMac** [comment]
You set param2 with `minetest.set_param2_variant` like so:

```lua
local variant = 5 -- Replace this with the desired variant
local pos = vector.new(0, 0, 0) -- Replace this with the desired node position
local node = minetest.get_node(pos)
node.param2 = minetest.set_param2_variant(node.param2, variant, minetest.registered_nodes[node.name])
minetest.swap_node(pos, node)
```

**Comment by runsy** [comment]
param2_variant is neccesary? Cos I think is related to variant_count. So setting variant _count could be atomatically calculated. What are width and offset, the meaning is lost in the docs?

**Comment by TurkeyMcMac** [comment]
`param2_variant` specifies which bits of param2 to use for the variant. Theoretically the bit width could be determined from `variant_count`, but the bit offset could not.

For an example, take this bit field: `{width = 3, offset = 2}`. It would use the bits of param2 marked with Xs: `000XXX00`.

**Comment by SmallJoker** [comment]
Feedback/input for later work: https://irc.minetest.net/minetest-dev/2023-01-08#i_6046142

**Comment by runsy** [comment]
May anyone adopt this? Please.

**Comment by refreshthat** [comment]
I really hope this PR does not get thrown away like some of the other great PRs that did. I hope that it is not considered "too ambitious".

**Comment by RecentRunner** [comment]
Why was this closed without any explanation? Did @refreshthat accidentally manifest it's closing?

**Comment by rubenwardy** [comment]
> Why was this closed without any explanation? Did @refreshthat accidentally manifest it's closing?

The author unfortunately [passed away](https://forum.minetest.net/viewtopic.php?f=18&t=29161), someone needs to adopt this PR

**Comment by RecentRunner** [comment]
> > Why was this closed without any explanation? Did @refreshthat accidentally manifest it's closing?
> 
> The author unfortunately [passed away](https://forum.minetest.net/viewtopic.php?f=18&t=29161), someone needs to adopt this PR

Oh my god I'm sorry, I didn't realize. I hope his family is coping well with his loss

**Comment by runsy** [comment]
Nooo! Why? I wanted this one to go ahead. It's almost finished. I checked it and it's going well.

Someone should be forced to take it up. I mean if it were up to me. :-D

**Pull request closed without merging**
