### PR TITLE
Use object property "stepheight" for player stepheight too. 

### PR DESCRIPTION
**Pull request by sapier**
This enables mods to modify the players stepheight.

And some code cleanup to better find things you're looking for.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
@SmallJoker Because they aren't tab-width-independent unless your editor supports elastic tabs.

These items don't really need to be aligned though.

**Comment by ShadowNinja** [comment]
@sapier

Could you split the commits into the change and the style fixes / moving?

I'm concerned that this won't work as expected with Android clients with modified step height.  That might be O.K. though.

**Comment by paramat** [comment]
Good idea.

**Comment by sapier** [comment]
I'm considering this as example and don't plan to spend work on it till I actually need this feature or someone asks for it

**Comment by paramat** [comment]
I would like this, would go well with settable collisionbox.

**Comment by paramat** [comment]
IRC:
19:30 paramat     nice idea
19:32 sfan5       agree
19:34 nerzhul     strangely the PR is not in good form, but idea is good

**Comment by Ekdohibs** [comment]
Replaced by #5710.

**Comment by paramat** [comment]
Reopen as is reverted and a better implementation is needed (cannot reopen #5710).
Note Android stepheight should only be increased by 0.6 if 'touching ground'.

**Comment by paramat** [comment]
This could now be re-applied as part of 0.5 breakage.

**Comment by paramat** [comment]
`inline f32 getStepheight() const` oops camelcase.

**Comment by paramat** [comment]
Re-aaplied in #6217

**Pull request closed without merging**
