### PR TITLE
Fix spelling of noise_threshold

### PR DESCRIPTION
**Pull request by zhangjunphy**
Deprecate `noise_threshhold`.
Addressing this issue https://github.com/minetest/minetest/issues/3321 .

### CODE REVIEW

**Comment by est31** [comment]
:+1:  Looks good, if squashed.

**Comment by paramat** [comment]
:+1: If squashed.

**Comment by zhangjunphy** [comment]
Squashed.

**Comment by BlockMen** [comment]
a78dd7f2b6b0e1fefdbaa1ae21b722dd4459e4f4

**Pull request closed without merging**
