### PR TITLE
Check item_drop amount clientside

### PR DESCRIPTION
**Pull request by BlockMen**
Backport from https://github.com/blockplanet/blockplanet. Since I'm the copyright holder and doin this PR here it can be used ofc.

### CODE REVIEW

**Comment by kaeza** [comment]
I've been using a hack to remove the ability of a player to drop items, simply by defining an empty body for `core.item_drop` from a mod like this:

```lua
function minetest.item_drop(itemstack)
  return itemstack
end
```

Does this pull break this usage? From my look at the code it shouldn't, but just making sure.

:+1: in any case.

**Comment by MoNTE48** [comment]
@BlockMen, I want to get permission to use it in my LGPL fork even if it will not be added to Minetest. I can?

**Comment by BlockMen** [comment]
@MoNTE48 By my statement above it should be clear that I'm aware of publishing this under LGPL, so yes, ofc you can.

**Comment by MoNTE48** [comment]
@BlockMen, Thank you!

**Comment by LNJ2** [comment]
Is there a reason why this doesn't get merged?

**Comment by rubenwardy** [comment]
#6242

**Pull request closed without merging**
