### PR TITLE
Use newer IrrlichtMt

### LINKED ISSUE #14131: add sdl2 package to compiling instructions
### Minetest version

```true
any version since https://github.com/minetest/irrlicht/commit/9a439a3646b26b1fceda3e5d70630b0bb4b48aca
```

### Active renderer

_No response_

### Irrlicht device

_No response_

### Operating system and version

all

### CPU model

_No response_

### GPU model

_No response_

### OpenGL version

_No response_

### Summary

since the linked commit, minetest needs the sdl2 package for compiling, making an issue as this was reported/asked about on discord

### Steps to reproduce

try compiling minetest

### PR DESCRIPTION
**Pull request by sfan5**
now with SDL2
Fixes #14131

### CODE REVIEW

**Comment by lhofhansl** [comment]
Tried. Works.

**Comment by superfloh247** [comment]
MacOS 14.2, apple silicon 

works

**Comment by sfan5** [comment]
@superfloh247 can you maybe also test with `-DUSE_SDL2=1`?
if everything works the About tab should show "irrlicht device: SDL".

**Comment by superfloh247** [comment]
Irrlicht lastest master or a specific tag?

**Comment by sfan5** [comment]
Latest master or 1.9.0mt14 either is okay.

**Comment by superfloh247** [comment]
```
-- Found SDL2: SDL2::SDL2
-- Found IrrlichtMt 1.9.0.14
```

compiles, no issues

noteworthy:
- HUD elements and texts are way larger
- shift keys (left and right) to fly downwards do not work
- FPS approx just 50% of usual values

-USE_SDL2=1
Bildschirmfoto 2024-01-18 um 12 17 14

w/o any extra SDL parameter to cmake
Bildschirmfoto 2024-01-18 um 12 28 00

**Comment by sfan5** [comment]
Looks like that needs some work but good to know it works in principle.
Thanks for testing.

**Comment by superfloh247** [comment]
Glad to help

**Pull request merged**
