### PR TITLE
TouchScreenGUI: Read coordinates directly for virtual joystick

### LINKED ISSUE #12436: Improve Android virtual joystick movement
## Problem
I'm always frustrated when moving around in the Android version of Minetest. You are given a D-Pad disguised as a shoddy joystick which makes it feel extremely stiff and unresponsive since it can only go at full speed in 9 different directions.

## Solutions
Rework the touchscreen joystick to give the user 360 degrees of freedom and the ability to control the fraction of the movement speed by how far out the joystick handle has been pulled. Essentially, bring it up to par with Minetest's regular joystick support on desktop.

## Alternatives
Don't, I guess.

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
This PR makes the input handler to use virtual joystick's coordinate directly instead of using keyboard event so that the movement can be smooth and not limited to 8 direction and full speed.

[YouTube video](https://youtu.be/FEWO15rOSyk)

**How does the PR work?**
The movement's direction and speed are calculated directly from the virtual joystick button's screen coordinate.

The only virtual joystick status left is for Aux1 button (used if `virtual_joystick_triggers_aux1` is enabled).

**Does it resolve any reported issue?**
This PR tries to fix #12436.

**Does this relate to a goal in the roadmap?**
Probably, this PR tries to fix a reported UX issue.

## To do

This PR is a Ready for Review.

## How to test

1. Run Minetest on a touch-screen device.
2. Play in a world or on a server.
3. Use the virtual joystick with incrementing distance from its centre.
4. The movement's speed should be linearly proportional to the button's distance from its container's centre.
5. Back to Menu.
6. Enable `virtual_joystick_triggers_aux1`.
7. Play in a world or on a server with a sprinting mod.
8. Use the virtual joystick to move forward until the button is outside its container.
9. The Aux1 button should be pressed automatically while moving forward (e.g. sprinting is happening).

**Android: APK builds**
- [armeabi-v7a](https://drive.google.com/file/d/1lxGAmjfd2GT1ZNICN-VGTd3DhlqCdtcw/view)
- [arm64-v8a](https://drive.google.com/file/d/18JiRD-VGNYGm3WvAStFQp4NheRB3-dvb/view)
- [x86](https://drive.google.com/file/d/1CPr46jx4x8SHxPyiHWBwBMzI3qkBAQHj/view)
- [x86_64](https://drive.google.com/file/d/1z0CYD03RvaVkZbNL14eC17ZyDOHv9QA7/view)

### CODE REVIEW

**Comment by grorp** [comment]
This is definitely an improvement to the user experience. I tested this PR both with and without `fixed_virtual_joystick` and `virtual_joystick_triggers_aux1` and everything worked as expected.

The code also looks good. The only problem I see is that it removes physical joystick support on Android, but I doubt anyone is using a physical joystick on Android, and joystick support seems to be quite broken anyway.

**Comment by AbduSharif** [comment]
I got the build from here, but it lead to the irrlicht crash, does anyone have a build to test this or is rebase enough?

**Comment by grorp** [comment]
> I got the build from "Actions" here, but it lead to the irrlicht crash, does anyone have a build to test this or is a rebase enough?
> 
> Edit: a rebase won't do (?).

A rebase won't help, all Android builds will be broken until the IrrlichtMt revision is bumped. That's because the Android build downloads a pre-compiled IrrlichtMt. The only way to get a working build is to compile IrrlichtMt yourself.

**Comment by srifqi** [comment]
> [...] The only problem I see is that it removes physical joystick support on Android, but I doubt anyone is using a physical joystick on Android, and joystick support seems to be quite broken anyway.

Should I use the `enable_joysticks` setting in addition with the preprocessor directive? I do not have any physical joystick, so I can not test it.
```cpp
#ifdef HAVE_TOUCHSCREENGUI
		if (!g_settings->getBool("enable_joysticks"))
			return m_receiver->m_touchscreengui->getMovementSpeed();
#endif
		return joystick.getMovementSpeed();
```

-------

> [...] does anyone have a build to test this [...]

I attached the APK builds in the first post with the recent IrrlichtMT build (09af5ac).

**Comment by grorp** [comment]
Just to make the available information more complete: Physical joysticks don't seem to be supported at all on Android at the moment, as Irrlicht doesn't support them on Android.

**Review by sfan5 — APPROVED** [review]
LGTM

**Pull request merged**
