### PR TITLE
Readme PR

### PR DESCRIPTION
**Pull request by numuhwana**
I added how to pull request in the Linux with git, and how to set mouse sensitivity for the Linux user.
This will be a good guide line for the newbi of git hub.

### CODE REVIEW

**Comment by GrapeCandy** [comment]
I wonder why this has a build error...
Please comment here!

**Comment by rubenwardy** [comment]
Pull request info is already in the contributing read me. Mouse sensitive should probably be moved to the simple settings menu

**Comment by SmallJoker** [comment]
I agree with @rubenwardy -  [CONTIBURING.md](https://github.com/minetest/minetest/blob/master/CONTRIBUTING.md#code) already contains the relevant information. If Git help should be more present there (for all platforms), then consider linking to existing pages instead of re-inventing the wheel.
Also: The buildbot fail is unrelated to your change.

**Comment by paramat** [comment]
Already done in the linked file, so closing, thanks anyway :)

**Pull request closed without merging**
