### PR TITLE
Android: EditText dialog minor improvements

### PR DESCRIPTION
**Pull request by oong819**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
improve the dialog
- How does the PR work?
not even tested
- Does it resolve any reported issue?
probally 1 but that issue to ambigous
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
no?
- If not a bug fix, why is this PR needed? What usecases does it solve?
probally fix a bug that sometimes edittext not fullscreen

## To do

Ready for Review.

- [ ] test it

## How to test
0. chat
1. the edittext should be fullscreen without tapping the smaller dialog

### CODE REVIEW

**Comment by srifqi** [comment]
Using `git bisect`, I found that reverting my PR (c1e430ef68271b8769ae8852b2b4a2fa0fb7ccac) fixes the issue. I am still trying to find the exact cause.

**Comment by oong819** [comment]
Can we just use `` InputMethodManager.SHOW_IMPLICIT `` instead?

**Comment by srifqi** [comment]
That would not work, I think, at least with current implementation. Have you tried it?

**Comment by rubenwardy** [comment]
It would be good to find a solution that works for newer target sdk versions, as google will eventually require us to target 33

**Comment by oong819** [comment]
probally we should replace `` toggleSoftInput() `` with `` showSoftInput `` && `` hideSoftInput ``?

**Comment by oong819** [comment]
> That would not work, I think, at least with current implementation. Have you tried it?

not yet, my device ran out of storage space

**Comment by srifqi** [comment]
I found [this blog post](https://developer.squareup.com/blog/showing-the-android-keyboard-reliably/) by Helios Alonso titled "Showing the Android Keyboard Reliably". I tried to apply it for Minetest's Android GUI and it works! You can see [my commit on my branch](https://github.com/srifqi/minetest/commit/ade23a5b88c3c544d24d8783c81bc59a1c3c3111) or the diff below:

<details>
<summary>Diff</summary>

```diff
diff --git a/android/app/src/main/java/net/minetest/minetest/CustomEditText.java b/android/app/src/main/java/net/minetest/minetest/CustomEditText.java
index 8d0a503d0..7a38d0965 100644
--- a/android/app/src/main/java/net/minetest/minetest/CustomEditText.java
+++ b/android/app/src/main/java/net/minetest/minetest/CustomEditText.java
@@ -29,17 +31,52 @@ import androidx.appcompat.widget.AppCompatEditText;
 import java.util.Objects;
 
 public class CustomEditText extends AppCompatEditText {
+	private int editType = 2; // single line text input as default
+	private boolean wantsToShowKeyboard = false;
+
 	public CustomEditText(Context context) {
 		super(context);
 	}
 
+	public CustomEditText(Context context, int _editType) {
+		super(context);
+		editType = _editType;
+	}
+
 	@Override
 	public boolean onKeyPreIme(int keyCode, KeyEvent event) {
-		if (keyCode == KeyEvent.KEYCODE_BACK) {
+		// For multi-line, do not close the dialog after pressing back button
+		if (editType != 1 && keyCode == KeyEvent.KEYCODE_BACK) {
 			InputMethodManager mgr = (InputMethodManager)
 					getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
 			Objects.requireNonNull(mgr).hideSoftInputFromWindow(this.getWindowToken(), 0);
 		}
 		return false;
 	}
+
+	@Override
+	public void onWindowFocusChanged(boolean hasWindowFocus) {
+		super.onWindowFocusChanged(hasWindowFocus);
+		tryShowKeyboard();
+	}
+
+	public void requestFocusTryShow() {
+		requestFocus();
+		wantsToShowKeyboard = true;
+		tryShowKeyboard();
+	}
+
+	private void tryShowKeyboard() {
+		if (hasWindowFocus() && wantsToShowKeyboard) {
+			if (isFocused()) {
+				CustomEditText that = this;
+				post(() -> {
+					final InputMethodManager imm = (InputMethodManager)
+							getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
+					imm.showSoftInput(that, 0);
+				});
+			}
+			wantsToShowKeyboard = false;
+		}
+	}
 }
diff --git a/android/app/src/main/java/net/minetest/minetest/GameActivity.java b/android/app/src/main/java/net/minetest/minetest/GameActivity.java
index 958fe9ccb..c5c94e7f8 100644
--- a/android/app/src/main/java/net/minetest/minetest/GameActivity.java
+++ b/android/app/src/main/java/net/minetest/minetest/GameActivity.java
@@ -31,7 +31,6 @@ import android.view.View;
 import android.view.WindowManager;
 import android.view.inputmethod.InputMethodManager;
 import android.widget.Button;
-import android.widget.EditText;
 import android.widget.LinearLayout;
 
 import androidx.annotation.Keep;
@@ -97,21 +96,11 @@ public class GameActivity extends NativeActivity {
 		container.setOrientation(LinearLayout.VERTICAL);
 		builder.setView(container);
 		AlertDialog alertDialog = builder.create();
-		EditText editText;
-		// For multi-line, do not close the dialog after pressing back button
-		if (editType == 1) {
-			editText = new EditText(this);
-		} else {
-			editText = new CustomEditText(this);
-		}
+		CustomEditText editText = new CustomEditText(this, editType);
 		container.addView(editText);
 		editText.setMaxLines(8);
-		editText.requestFocus();
 		editText.setHint(hint);
 		editText.setText(current);
-		final InputMethodManager imm = (InputMethodManager) getSystemService(INPUT_METHOD_SERVICE);
-		Objects.requireNonNull(imm).toggleSoftInput(InputMethodManager.SHOW_FORCED,
-				InputMethodManager.HIDE_IMPLICIT_ONLY);
 		if (editType == 1)
 			editText.setInputType(InputType.TYPE_CLASS_TEXT |
 					InputType.TYPE_TEXT_FLAG_MULTI_LINE);
@@ -120,7 +109,8 @@ public class GameActivity extends NativeActivity {
 					InputType.TYPE_TEXT_VARIATION_PASSWORD);
 		else
 			editText.setInputType(InputType.TYPE_CLASS_TEXT);
-		editText.setSelection(editText.getText().length());
+		editText.setSelection(Objects.requireNonNull(editText.getText()).length());
+		final InputMethodManager imm = (InputMethodManager) getSystemService(INPUT_METHOD_SERVICE);
 		editText.setOnKeyListener((view, keyCode, event) -> {
 			// For multi-line, do not submit the text after pressing Enter key
 			if (keyCode == KeyEvent.KEYCODE_ENTER && editType != 1) {
@@ -144,12 +134,13 @@ public class GameActivity extends NativeActivity {
 				alertDialog.dismiss();
 			}));
 		}
-		alertDialog.show();
 		alertDialog.setOnCancelListener(dialog -> {
 			getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
 			messageReturnValue = current;
 			messageReturnCode = -1;
 		});
+		alertDialog.show();
+		editText.requestFocusTryShow();
 	}
 
 	public int getDialogState() {

```
</details>

**Comment by oong819** [comment]
can you open a new PR for that? look good!

wait, -> are in Java 8, can device running SDK < 24 run that?

**Comment by srifqi** [comment]
Oh, by the way, if that is a problem, we can turn off suggestions for migration to Java version 8+.

Java language level migration aids settings

**Comment by oong819** [comment]
closing pr cuz this dont really help improve the dialog

**Pull request closed without merging**
