### PR TITLE
Disallow empty messages

### PR DESCRIPTION
**Pull request by DiamondPlane**
Disallows empty messages, with a message "-!- Empty message"

### CODE REVIEW

**Comment by SmallJoker** [comment]
An empty chat message shouldn't even get this far.

1. Do not send it in the client (DONE)
https://github.com/minetest/minetest/blob/4d0fef8ae87aa7b940d43485e7f6466eaa3d111e/src/client/client.cpp#L1557-L1559

2. Do not process it server-side
https://github.com/minetest/minetest/blob/4d0fef8ae87aa7b940d43485e7f6466eaa3d111e/src/network/serverpackethandler.cpp#L773-L775
```C++
if (message.empty())
	return;
```

Also what about whitespace-only messages?

**Comment by DiamondPlane** [comment]
> Also what about whitespace-only messages?
What do you mean?

**Comment by SmallJoker** [comment]
> What do you mean?

When someone sends a message containing only spaces, for example: `"     "`
I cannot send empty messages in the newest Minetest version, so what you might have seen on a server is the example above. Someone sent a message that looked empty, but in fact is not (spaces).

Request: Simply ignore empty messages server-side (see code location above) and depending on your choice, disallow whitespace-only messages as well.

**Comment by nerzhul** [comment]
we may need a trim filtering in order to drop empty whitespaces messages no ?

**Comment by SmallJoker** [comment]
a8b7c8f

**Pull request closed without merging**
