### PR TITLE
Remove fly mode in simple main menu

### PR DESCRIPTION
**Pull request by srifqi**
As the fly mode option is avaiable in-game, this is not used anymore.
Also, the button moved + resized to fit.
minetest-201504251013 mainmenu_simple main tab

### CODE REVIEW

**Comment by indriApollo** [comment]
Is this android only ?

**Comment by est31** [comment]
Yes

**Comment by est31** [comment]
Looks good, just don't forget to also remove the part where the checkbox is read again: `core.setting_set("enable_damage", fields["cb_damage"])`.

**Comment by srifqi** [comment]
@est31 Sorry I'm forgot. I will update ASAP.

**Comment by srifqi** [comment]
Updated. Removed `fields["cb_fly_mode"]` handler.

Squashed.

**Comment by Zeno-** [comment]
Fine with me

**Comment by Zeno-** [comment]
1c7c3492647aada9a60c7e11662a0defe3f4385c

**Comment by srifqi** [comment]
Okay, accepted.

Deleted.

**Comment by srifqi** [comment]
Okay, accepted.

Deleted.

**Pull request closed without merging**
