### PR TITLE
[no squash] Buildbot improvements

### LINKED ISSUE #9181: Buildbot script does not package mingw64 DLLs
Building a Windows executable from Linux with mingw64, using the build scripts in the repo, results in a zip that isn't ready to run; it's missing three DLLs that must be manually copied over from wherever mingw64 keeps them.
**Request:**
Mention this in the build instructions, or make the build scripts at least attempt to find and pack the required libraries.

### PR DESCRIPTION
**Pull request by sfan5**
`which` is deprecated on at least [Debian](https://groups.google.com/g/linux.debian.devel/c/1h7vtg5ty0U) and might not be installed automatically anymore, `command -v` is specified in POSIX so a better replacement

the second commit fixes #9181

## To do

This PR is Ready for Review.

## How to test

* Observe CI results

### CODE REVIEW

**Comment by erlehmann** [comment]
Important information for anyone who reads this: `command -v` and `which` do not behave in exactly the same way in bash if shell aliases exist:

```
$ which ls
/bin/ls
```

vs

```
$ command -v ls
alias ls='ls --color=auto'
```

Both commands seem to work the same way in POSIX mode though.

**Review by rubenwardy — APPROVED** [review]

**Comment by chrisx8** [comment]
I tried this on my system and it still doesn't seem to find the DLLs. Here's what I found in the GitLab CI output: `The compiler runtime DLLs could not be found, they might be missing in the final package.`

It seems like line 47 of `util/buildbot/buildwin64.sh` does not find the relevant DLLs:
```bash
tmp=$(dirname "$(command -v $compiler)")/../x86_64-w64-mingw32/bin
```

I'm trying to figure out what's the issue here and working on a fix.

**Comment by sfan5** [comment]
It might be that some distributions have the DLLs under `/usr/x86_64-w64-mingw32/lib` instead of `bin`, the current code works with all I use anyway.

**Comment by chrisx8** [comment]
I used the same MinGW tarball that you use with GitLab CI. I think the issue is there's a typo around line 23 in `util/buildbot/buildwin64.sh`. It should be
```bash
compiler=x86_64-w64-mingw32-gcc
```
instead of 
```bash
compiler=x86_64-w64-mingw32
```

The 32-bit build script ``util/buildbot/buildwin32.sh` doesn't have this issue.

After this change the Windows build works just fine with all DLLs present. A PR with a fix is ready (#11759). I'll also get some updated documentation ready (hopefully within a week) for building Windows binaries using MinGW.

**Pull request merged**
