### PR TITLE
Revert some of the recent gui changes

### LINKED ISSUE #13743: Input not working properly on Android
##### Minetest version

```
Commit 7b3ed32 (master branch)
```

Active renderer:
Irrlicht device: ANDROID

##### OS / Hardware

Operating system: Android 12, AOSP on Xiaomi Redmi 9

GPU model:
OpenGL version:

##### Summary

The joystick and camera works, the hotbar too, the UI too, but the three dots, jump, shift, cog wheel, and Aux1 buttons do not work. Changing touch threshold settings and setting fixed virtual joystick doesn't help.
##### Steps to reproduce

Start world, try to play

### PR DESCRIPTION
**Pull request by Desour**
Reverts that commit from #13732 to fix #13743.

Can't easily test, sorry. Someone else should implement the change properly.

## To do

This PR is a Ready for Review.

## How to test

Try #13743.

### CODE REVIEW

**Comment by grorp** [comment]
This doesn't seem to fix the issue. The issue is fixed if I additionally revert 16da954bd70b326f21cec9547237f55de18d4253 and 45e7a800575f6d96ea307d99f1945aeb6c22a4e1.

**Comment by Desour** [comment]
Are you sure? You said before that the first bad commit is https://github.com/minetest/minetest/commit/f7f3aaf43c88179bafd255f3c67275f316cff91a, so this means there might be two separate bugs.
Or, does it work if you only revert https://github.com/minetest/minetest/commit/16da954bd70b326f21cec9547237f55de18d4253 and https://github.com/minetest/minetest/commit/45e7a800575f6d96ea307d99f1945aeb6c22a4e1?

**Comment by grorp** [comment]
Yes, this sounds like there are two separate problems.

These don't work:
https://github.com/minetest/minetest/compare/master...grorp:minetest:tsg-bad-1
https://github.com/minetest/minetest/compare/master...grorp:minetest:tsg-bad-2
https://github.com/minetest/minetest/compare/master...grorp:minetest:tsg-bad-3

This works:
https://github.com/minetest/minetest/compare/master...grorp:minetest:tsg-good

I have no idea why. Maybe I made a mistake while testing...

**Comment by Desour** [comment]
Well, then let's revert them too. Sorry for the disturbance.

**Pull request merged**
