### PR TITLE
Show game buttonbar only if more than one game is present

### PR DESCRIPTION
**Pull request by BlockMen**
Backport from https://github.com/blockplanet/blockplanet. Since I'm the copyright holder and doin this PR here it can be used ofc.

### CODE REVIEW

**Comment by paramat** [comment]
:-1: We usually have 2 games, MTGame and minimal.
With only MTGame present we would lose the only occurence of the Minetest icon.

**Comment by RobertZenz** [comment]
This might actually be interesting if a game/subgame wants to deliver an "all inclusive/hassle free" package. One could package the Minetest executables together with *the* game, which makes it look like a stand-alone client...sort of, if you get my drift.

**Comment by est31** [comment]
:-1: agree with @paramat

**Comment by rubenwardy** [comment]
With only one subgame, it's less obvious what the bar is for.

**Comment by HybridDog** [comment]
l like it, you could add a setting to minetest.conf "menu_always_show_games", disabled by default, to allow paramat, est31, etc. to still have that icon in their menu.

**Comment by rubenwardy** [comment]
This has two disapprovals, unless there's any change in opinion it's worth closing this.

I still personally think the bar is confusing if there's only one icon, so it would be worth adding some text that says "Filter by subgame" or similar

> We usually have 2 games, MTGame and minimal, so would have little effect (or is minimal not counted?).

I suggest not distributing minimal to end users.

**Comment by SmallJoker** [comment]
Showing the game button bar gives players the hint that there could be more to be added. Hiding it would could reduce the popularity of other subgames for new players.

Closing this PR.

**Pull request closed without merging**
