### PR TITLE
Enable segment heap on Windows

### PR DESCRIPTION
**Pull request by sfan5**
It turns out Microsoft has magic knobs you can turn to improve things, you just need to know about them.

this is supposed to help with #14015 and (allegedly) also lowers memory usage

@lhofhansl is probably in the best position to test this

according to the [docs](https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#heaptype) it only does something on version 2004 (build 19041) or later.

## To do

This PR is Ready for Review.

## How to test

:grey_question:

### CODE REVIEW

**Comment by lhofhansl** [comment]
I can take the artifacts generated by the build script and test it on the my son's desktop :)
Lemme try this one.

**Comment by sfan5** [comment]
Try now.

**Comment by lhofhansl** [comment]
This is sooo much better.
Still some stuttering when meshes are build, but instead of over 200ms, the worst I have seen is around 50ms, and most of the time it hovers around 20-30ms.
And absolutely no hanging on shutdown.

This is usable now at large viewing_ranges!

**Comment by lhofhansl** [comment]
We might even want to backport this to a 5.8.1.

**Comment by lhofhansl** [comment]
Actually I now notice that the MT actually crashes when you exit a game :(

I did not notice before, because I was exiting to the OS and Windows gave _no_ indication about that. (Maybe that's why there was absolutely no wait upon exit.)

But when I "Exit to Menu" I see that it crashes. Meh.

The in-game performance is still awesome!

**Pull request merged**
