### PR TITLE
Mapgen Watershed development

### PR DESCRIPTION
**Pull request by paramat**
WIP:
Settingtypes.txt documentation needed.

This mapgen is a result of my interests in particular mapgen ideas, but also seems to address some common requests concerning scale, realism, large flat areas for building, continents etc.

It is currently a little less intensive than mgv7.

Currently the player is spawned at a fixed position that may be either high in the air or inside a mountain. Disable damage when testing and enable 'fly' and 'freemove' if underground.

Map scaling feature
-------------------------
When parameter 'mgwatershed_map_scale' is not '1' it shrinks the mapgen down to create a 3D stone map of the world surface.
For example with scale 15.5 a 4000x4000 node area represents 62000x62000 nodes, this can then be mapped (the mapper has a maximum area of 4000x4000 nodes) to create a 3D surface map of the entire world.
For technical reasons, when map scaling is used it unfortunately has to disable caves, dungeons, biomes and decorations.

All the maps shown in this post are created using this map scaling feature.

Mapgen features
---------------------
* Continents and large oceans.

Most mapgens tend to become repetitive on scales above 2000 nodes. This mapgen has variation on scales up to 12000+ nodes with the intention of creating a few, somewhat separated, continents. These create interesting new types of multiplayer gameplay as a few continent states could be formed.

mgw2_s0_ms15_4000_half_ind

^ 4000x4000 nodes with map scale 15, so maps a 60000x60000 node area, almost a complete world. Note the tops of high mountains have been chopped off to limit the volume emerged.

mgw2_s0_ms4_n4500n2813_crop_ind

^ 1700x1700 nodes with map scale 4, so maps a 6800x6800 node area to show the terrain features listed below.

* Large lakes / inland seas.
Within continents.
* Flat areas.
Completely flat large lowland areas for cities and large builds.
* Hills.
* Mountains.
Up to 2000 nodes high.
No crazy 3D noise structures as in mgv7, uses 'absvalue' 2D noise.
* Plateaus.
* Canyons.
Where rivers pass through plateaus.
* Cliffs.
3D noise cliffs as river canyon walls, at plateau edges and where plateaus meet coast.
* Rivers.
Sloping rivers with 'river water' as in Mapgen Valleys.
Rivers become narrower with altitiude until they taper to nothing near cloud level.
Combines 2 mgv7-type networks for a more complex, more interconnected river network, to make rivers more suitable as travel networks.

Underground is identical to mgv7 and a few other non-mgv6 mapgens, so it uses the shared code.

Continent area parameter
---------------------------------
Often users want to alter the ratio of water to land. Doing this by altering 'water_level' is problematic as biomes and decorations will also need to be altered. Usually this is best done by raising or lowering terrain, but this is problematic in this mapgen, so i added the 'mgwatershed_continent_area' parameter to control the ratio.

The maps below are show a range of values, default being the 2nd map.
2000x2000 nodes with map scale 15, so maps a 30000x30000 node area, roughly a quarter of a world.
Best way to see the effect is to open all 3 images somewhere and switch between them.

mgw2_s0_ms15_can1p5_half_ind

^ -1.5.

mgw2_s0_ms15_cadef_half_ind

^ -0.9 default.

mgw2_s0_ms15_ca0_half_ind

^ 0.0.

### CODE REVIEW

**Comment by sofar** [comment]
I'm not seeing the large amount of waters in the pictures above. It's more mostly rivers, and some larger lakes. Are those screens really of the "default" variables?

**Comment by paramat** [comment]
Yes, perhaps you're in a particularly large continent?
Also, depending on worldseed, sometimes the continents are not so well separated, i'll tune 'continent area' for more separation.

**Comment by random-geek** [comment]
How are biomes managed? It would be great to see some proper height-affected biomes in a default mapgen.

**Comment by sofar** [comment]
biomes and decorations are orthogonal to mapgen. This patch doesn't change them.

**Comment by Gael-de-Sailly** [comment]
Tested, this looks great, I'm glad to see it's finally (almost) ready for merging!

I was playing around with rivers noises to make river branching looking more realistic, here is my result:
screenshot_20190206_121057
screenshot_20190206_121154
The idea is to hierarchize the river layers (layer 1 being major rivers and layer 2 minor ones) and to use a different seed for minor rivers at both sides of major ones.
Branch: https://github.com/Gael-de-Sailly/minetest/tree/mgwatershed2-tworivers

**Comment by vladtcvs** [comment]
Mountains looks great! But i think, biomes should fit. Jungles in mountains looks wrong.

**Comment by Gael-de-Sailly** [comment]
I assume you mean the same than random-geek (scroll up!).
Elevation-dependent temperature would be a very nice feature but unfortunately it's currently not possible to do it cleanly.
The way it is implemented on `valleys` mapgen is very hacky and leads to artifacts on chunk limits, so don't expect it to be generalized. This kind of stuff should be supported by the biome generator itself, not by individual mapgens.

**Comment by paramat** [comment]
Added some megastructures, this one has a nice boathouse on the river =)

screenshot_20190214_004754

Gael-de-Sailly that's a nice idea, unfortunate that it requires another 2D noise. This is interesting, thanks.

**Comment by sofar** [comment]
I hope that the megastructures above ground level are not default? They are impressive, but they would make this mapgen less suitable for many players, I think.

**Comment by benrob0329** [comment]
The megastructures are really cool but I agree with sofar they should only be below ground by default.

**Comment by Gael-de-Sailly** [comment]
I agree too. This odd cubic thing doesn't fit at all with the landscape. Would be a nice maze to explore underground, however.

**Comment by jastevenson303** [comment]
I'm sure it was just for illustration purposes, though it's hard to know
for sure since there was no comment on it.  If it's an option that by
default disabled, even better, because some may _want_ these
mega-structures above-ground.

**Comment by paramat** [comment]
Yes i'll put them below oceanbed level by default, they have ymin/ymax limits.
They protrude into air so will still exist like this in the massive caverns, so will be a little like MC's nether fortresses.

**Comment by paramat** [comment]
```
		// River valley 2
		float n_river2 = noise_river2->result[index2d];
		// River valley 2: take noise 2A if noise 1 is positive, and noise 2B is noise 1 is negative.
		float n_river2 = (n_river1 > 0 ? noise_river2a : noise_river2b)->result[index2d];
```
Gael-de-Sailly that is an interesting idea, thanks for sharing. I probably will not use it here but it is good to learn a new river technique.

I have removed all the mega-dungeon code, as the mapgen-shared dungeon code is currently being improved, mega-dungeons may be added to the shared code and become usable in all mapgens.

Rebased if anyone wants test this.

I am still a little unhappy with the canyon walls being so smooth, might experiment with those.
Also unsure about using a 'volcanic rock' node as most games do not have this. However, without it, there will be vast lava floods in underground caves. So, also unsure about having volcanic vents.

I would like to merge this soonish (before next release hopefully) but with the understanding it is unstable and that i will be continuing to improve it. Having worked on this so long (years) i really do not like it still being unmerged, however i certainly do not want to call it 'finished'.
I think it may be quite nice to have an unstable mapgen that people can use with the understanding that it is unstable.

**Comment by paramat** [comment]
screenshot_20191030_180448

The new rough canyon slopes.

**Comment by paramat** [comment]
I am still regularly working on this, and working towards a mergeable state, i would like to offer this for merging fairly soon.

**Comment by paramat** [comment]
In the interest of reducing PR count i will close this for now, as it is still probably a few months away from being ready.

**Comment by Extex101** [comment]
> In the interest of reducing PR count i will close this for now, as it is still probably a few months away from being ready.

Is there any further development on this? I'd love to see this get completed.

**Comment by 0siribix** [comment]
Same question here. Is this stable?

**Comment by Opons1** [comment]
Will this come back?

**Comment by sfan5** [comment]
No.

**Pull request closed without merging**
