### PR TITLE
Add slippery

### PR DESCRIPTION
**Pull request by Zeg9**
Title says about it.

### CODE REVIEW

**Comment by nerzhul** [comment]
Hi, please fix the following things if you want a merge:
- Coding style
- Rebase 
- Handle the error, don't use a try .. catch

**Comment by Zeno-** [comment]
It would take longer to rebase this than write it from scratch. Best closed IMO

**Comment by kilbith** [comment]
No valid reason to trash it while most people were enthusiastic.
Please someone re-open that for rebasing and/or not sinking this into oblivion.

@est31 @paramat

**Comment by est31** [comment]
What @Zeno-  said is probably right, but I guess its not that large of a PR, therefore its ok to be open as well. Reopening on special request of @kilbith .

**Comment by C1ffisme** [comment]
Wouldn't it kill two birds with one stone just to make [ObjectRef](http://dev.minetest.net/ObjectRef) slip, and if an entity does not need to slip, change a variable like object.slip?

**Comment by est31** [comment]
@C1ffisme that's something separate, and not as simple as you describe it. And, the effect this PR wants to obtain would not be possible to achieve in a lag-free manner.

**Comment by sapier** [comment]
What's use of keeping this one alive if there's obviously noone interested in the feature?

**Comment by kilbith** [comment]
> What's use of keeping this one alive if there's obviously noone interested in the feature?

At least 2 core-devs are expressly interested.

**Comment by cmdskp** [comment]
I've updated this to master and to allow slipping off nodes, with a physics override for mods to utilise per player (e.g. grippy boots):

https://github.com/minetest/minetest/compare/master...cmdskp:master

And test values to try for minetest-game:
https://github.com/minetest/minetest_game/compare/master...cmdskp:master

Just need help with how to check the protocol version in "content_cao.cpp", before I can offer it in a pull.

**Comment by ObaniGemini** [comment]
What's up with it ?

**Comment by paramat** [comment]
@Zeg9 very old PR, any comments?
This needs reassessment and ghost's version considered.
@ghost can you open a new PR so we can consider it and close this one?

**Comment by paramat** [comment]
> At least 2 core-devs are expressly interested.

BlockMen has left, est31 isn't necessarily supporting the feature.
Zeg9 has been inactive on Github for a year.
I think this can be closed soon.

**Comment by Wuzzy2** [comment]
Is it really neccessary to rebase a PR which only has one commit? ;-)

**Comment by paramat** [comment]
Time to close this.
@Ekdohibs just notifying you in case you want to copy this code for your own use in a new PR.

**Comment by paramat** [comment]
#6237 merged.

**Pull request closed without merging**
