### PR TITLE
Rename and move basicmacros.h to util/basic_macros.h

### PR DESCRIPTION
**Pull request by est31**
@minetest/team-minetest Please vote on this rename PR until Nov 4, then if two more devs :+1: ed it than :-1: ed it, it gets merged, not merged otherwise.

### CODE REVIEW

**Comment by est31** [comment]
:+1: It clearly is an utilitary header, that's what the `util/` subdir is about. And we should have underscores in names.

**Comment by kwolekr** [comment]
The reason why I put basicmacros.h in the main directory is because it's supposed to be sort of a counterpart to irrlichttypes.h and so on, i.e. very fundamental includes that define universal, fundamental things but aren't quite *utilities*.

I think we could use this PR as a place to discuss what util/ is and what util/ isn't.
If util/ really were a base library, then it should be independent of the parent directory.  This isn't the case at all, though.
To me, util/ is just a place to organize miscellaneous odds and ends that support the existing code.  We're not (well, at least _I'm_ not) trying to make a universal basic framework library for every other projects.

**Comment by paramat** [comment]
Okay i understand the issue now.
:-1:

**Comment by nerzhul** [comment]
The two point of view are defendable but i prefer the idea to have this header in util too because it's a toolkit :) :+1:

**Comment by sfan5** [comment]
The stuff in basicmacros.h seems kinda utility-like so it makes sense to put it into util/ :+1:

**Comment by PilzAdam** [comment]
:+1:

For me util contains common functions that are helpful when coding other stuff. ```basicmacros.h``` is clearly such a thing.

**Comment by BlockMen** [comment]
:+1: Has for me more the character of a toolkit, which belongs clearly to ```/util/```
Also +1 for renaming to basic_macros.h

**Comment by ShadowNinja** [comment]
:+1:

**Comment by kwolekr** [comment]
Alright then, there you have it folks.  We'll move and rename it.

@est31 I recommend you work on removing util/'s dependencies on the top directory :-)

**Comment by celeron55** [comment]
I would rename it to util/misc.h or something like that. Organizing things to different files based on whether they are macros or not makes no sense.

**Comment by kwolekr** [comment]
note to self: move UNUSED() to this file

**Comment by est31** [comment]
util/misc.h sounds good.
About moving other stuff to util as well: I'd agree with that (e.g. areastore), but the goal isn't that util has no dependencies from src/ anymore. I'd just make the descision for every single file independently whether sth from util/ depends on it.

**Comment by paramat** [comment]
Hi, sorry i caused some controversy by trusting hmmmm's opinion before understanding the issue, soon after i began to feel i should have abstained instead. Perhaps at that time it was quiet on IRC and i wanted a quick resolution so wanted to contribute a vote, and i do trust hmmmm's opinion, from 3 years of following IRC logs and from experience, not blind allegiance.

**Comment by est31** [comment]
965d112bf4fa5e61d5e87949dfa19ad7278ad412

**Comment by est31** [comment]
sorry have to fix it first

**Comment by est31** [comment]
Fixed version here : eabfe091b5ecfa6e53b70e08faf76df7f0684529 got it in inside the 10 minutes window so no trace of my failure in history :)

**Pull request closed without merging**
