### PR TITLE
Mgvalleys: Correct spawn problems

### PR DESCRIPTION
**Pull request by duane-r**
Increase maximum spawn altitude to reduce spawn issues.

### CODE REVIEW

**Comment by paramat** [comment]
The changes to mgvalleys are fine and i will support those.
But please no changes to spawn search, it is deliberately unchanged from classic behaviour, but just continues out to 4000 nodes instead of 1000. If mgvalleys is having spawn problems thse should be fixed within mgvalleys itself.
Also please return the max spawn height to y = water_level + 16, this helps with spawning.

**Comment by paramat** [comment]
Also i should merge your other PR so you can rebase this on that.

**Comment by paramat** [comment]
Feel free to increase max spawn altitude to 32 nodes above water level.

**Comment by duane-r** [comment]
I'm not sure that this PR is a good idea anymore.

https://github.com/minetest/minetest/issues/3789#issuecomment-189802668

**Comment by duane-r** [comment]
Ok, this uses MoNTE48's idea for flattening the ground near origin. Since it only flattens base ground, it won't work every time, but it still looks good. I'm not able to spot any artifacts (though showing up at 0,0 is kind of a giveaway), and it usually results in spawns close to origin.

The spawn area is sometimes dull, but I have spawned on a steep mountainside and in several canyons. It also makes spawning on island chains more common.

Changing adjustedTerrainLevelFromNoise is not vital. However, I spawned over water a couple of times when the existing version said terrain was above water_level and it turned out not to be.

**Comment by paramat** [comment]
:-1:  See issue.
Just increase max spawn y to water_level + 64 (but no higher). That's fine and is fathful to the lua version.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Please could you update the first comment in this thread to avoid confusion?

**Comment by duane-r** [comment]
It looks like this was not the problem anyway. There may not be any need to merge this.

**Comment by paramat** [comment]
Well feel free to increase it to water_level + 32 if needed.

**Comment by paramat** [comment]
:+1: Will merge soon as a trivial fix.

**Comment by paramat** [comment]
af714c7ade02d3f645671276a0f0514f5099b59e

**Pull request closed without merging**
