### PR TITLE
Implement a autohiding button bar for settings buttons used every now an...

### PR DESCRIPTION
**Pull request by sapier**
...d then

http://imgur.com/WUUNvRL,obWiGmQ

I guess we need a better button image but I'll leave this for someone else.

It's autohiding after 3 seconds.

### CODE REVIEW

**Comment by MoNTE48** [comment]
Yes! Very good.
The eject button is also necessary to hide

**Comment by ezraanderson** [comment]
Great idea.

**Comment by ShadowNinja** [comment]
The icon should be a `•••` (...) button.  You can get it in the action bar icon pack [here](https://developer.android.com/design/downloads/index.html).
Also, either the menu button (Android hardware / virtual) should open this or the menu button shouldn't be enabled (it shows up but does nothing).

**Comment by KodexKy** [comment]
Maybe something like this 
menu19 It's unobtrusive enough and a well known icon. I'd like to keep freemove and drop icons visible. Toggling freemove via double tap jump is a little buggy (my kids kept killing themselves accidentally that way), and drop is used very frequently while on servers.

**Comment by sapier** [comment]
I'm not sure if ". . ." is best idea for a button beeing aligned exactly different direction? Doesn't anyone have a suggestion beeing higher then wide?

**Comment by ShadowNinja** [comment]
@sapier The same thing vertical.  The pack I linked should have both variants.

**Comment by ShadowNinja** [comment]
@sapier Why did you close this?

**Comment by MoNTE48** [comment]
This realy bad idea. Now more buttons is bad on 4" screen.

**Pull request closed without merging**
