### PR TITLE
Fix 6th line of infotext being cut off in half

### PR DESCRIPTION
**Pull request by Wuzzy2**
Attends to (but does not fully fix) #10285.

Currently, the infotext is truncated if it is too long. This is expected as we can't display infinite amounts of text on the HUD.
However, the cutoff is ugly because it cuts right through the last line, so you only see parts of the text line. This annoys me every time.

The PR fixes this by changing the cutoff height. I increased the number of rendered lines from "5 lines and a broken 6th line" to 6 normal lines cuz the current height seems way too little. In testing, increasing the new infotext height doesn't seem to break anything.
I think 6 lines is still very short but better than nothing. I'm deliberately very conservative here to keep this PR as uncontroversial as possible.

A screenshot explains more than 1,000 words: https://satoshiupload.com/images/2XG5TM6kbl.png

## To do

Ready for review.

## How to test

Use the Node Meta Editor in DevTest and use it to set the "infotext" key of any ordinary node you like.

If you want to compare with my screenshot, here is the text I used:

> The only official Lua API documentation is lua_api.txt. You can find this file in your Minetest installation, in the doc directory. Use this file to look up functions, core features of the Lua API, etc. This file is maintained by the core developers of Minetest and every change to it goes through a quality control process. This document explains everything you need to know about the Lua API in concise form, but may be daunting for newbies to read.

## Additional context

This PR is a greatly simplified version of #10431 and is kept as minimal as possible. Unlike #10431, this new PR doesn't try to calculate truncating height or append an ellipsis or anything like that. It really is just concerned about the ugly text line that is cut in half, so that only required changing some numbers.
I also added a few minor documentation fixes on top of that, but that's it.

I hope this makes the new PR more "mergable" than the other one.

### CODE REVIEW

**Comment by SmallJoker** [comment]
If even, it should display 5.5 lines. Why? To players it looks like the text is incomplete, and they have no way of telling whether that's the case or whether the text is just cut off. The half line afterwards would at least indicate them that there's more, but that the text is too small.
If you're somewhat bothered by too long texts being cut-off, then I'd rather have #10431.

**Comment by Wuzzy2** [comment]
That seems like a non-fix to me. You just make the ugly sliced-through text look different, but still ugly. Text being cut in half looks like a bug. But yeah, I agree it's a problem if the fact that the text is incoplete isn't visible …

I also really like to have #10431, but rubenwardy rejected it. I basically must completely refactor word-wrapping before getting rubenwardy's approval. That's too much for me.

**Comment by rubenwardy** [comment]
I didn't formally reject it. Given that it's taking me a while to do word wrapping, I'm not against that PR being merged.

I don't like the approach - it means that gameui.cpp now needs to know about text rendering, and the ellipsis placement feels weird to me - but if the bug isn't something that can be born, then it's a simple fix

**Review by sfan5 — APPROVED** [review]
LGTM

**Comment by SmallJoker** [comment]
(Rebase needed)

**Review by nerzhul — APPROVED** [review]

**Pull request merged**
