### PR TITLE
Raise collision check range

### PR DESCRIPTION
**Pull request by Thomas--S**
Suggested here: https://github.com/minetest/minetest/issues/2612#issuecomment-107087504

Notice: I don't understand what happens here.

You can close this if you want to; I'm only suggesting this because it solves this annoying bug in the homedecor mod.

### CODE REVIEW

**Comment by juhdanad** [comment]
This patch increases the range of nodes checked by the collision code. Since Homedecor stairs have a height of 3 nodes, they must be checked even if they are 2 nodes far from the player.

**Comment by paramat** [comment]
> This can be "fixed" if the limits for the search in collision.cpp are increased (replace 1 with 2,3,4, etc.), but out of performance reasons, this can't be raised indefinitely

It's not justified to lower performance just for one structure in a mod, better that structure is changed or fixed :-1:

**Comment by Thomas--S** [comment]
The question is, if a value of 2 really leads to a noticeable worse performance. @est31 is talking about raising it "indefinitely" would cause performance issues.

However, if you don't think this should be merged, it is ok for me, too.

This also fixes the problem, where you have been able to walk through 2 node wide nodes (e.g. homedecor desk, homedecor benches) from one side.

**Comment by paramat** [comment]
It wouldn't be humanly 'noticeable' but with software significant performance drops are usually too small to be humanly noticeable.The point is to not lower performance just for a few rare and unusual mod nodes.

**Comment by nerzhul** [comment]
i agree with paramat this will add a huge performance penalty. It's better to have a proper collision box

**Comment by Thomas--S** [comment]
And how would a proper collision box look like in my examples?

**Pull request closed without merging**
