### PR TITLE
Raise minimum compiler versions

### PR DESCRIPTION
**Pull request by sfan5**
super old versions were broken anyway (not only because of MT but also system libs not working etc.) and barely tested by anyone

I verified on Ubuntu 16.04 that **gcc 5.4 and clang 3.5** can successfully build Minetest.

## To do

This PR is a Ready for Review.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Does this mean we can raise to C++14 or C++17?

**Comment by rubenwardy** [comment]
Both GCC 5.4 and Clang 3.5 fully support C++14, so we could update to that standard. That would allow removing our `make_unique` implementation

I'd like to update to C++17, as that gives us `std::filesystem` which will be super useful in reduce the amount of code we have

**Comment by nerzhul** [comment]
@rubenwardy filesystem is very nice to drop our filesystem.h compat obviously. It depends on we use it, the generic way is sometimes slower (as far i tested it 3 years ago when sstandard was released) than the linux direct use one

**Comment by nerzhul** [comment]
it seems gcc doesn't like the unique_ptr :)

**Comment by sfan5** [comment]
Is there anything else in C++14 that could be useful for us?
This looks like a good overview: https://en.cppreference.com/w/cpp/14

:+1: from me generally, but that should be done in a separate PR.

**Comment by nerzhul** [comment]
@sfan5 
* we have std::make_unique for all unique_ptr we instanciate
* generic lambda may be interesting in some places
* maybe some libstdc++ optimisations related to c++14 too

**Review by SmallJoker — APPROVED** [review]
LGTM

**Pull request merged**
