### PR TITLE
Prevent the remain rotation angles to be nullified after set_yaw() call.

### PR DESCRIPTION
**Pull request by Andrey2470T**
This is a minor bugfix PR that fixes 'x' and 'z' angles to be nullified after call `set_yaw()` of an object ref.

## To do

This PR is Ready for Review.

## How to test
1. Set some angles in `set_rotation()`, particularly 'x' and 'z'.
2. `set_yaw()`.
3. Debug the remain angles.

### CODE REVIEW

**Comment by sfan5** [comment]
Was this bug a regression?

**Comment by Andrey2470T** [comment]
Yes, of course. It should not reach these angles and nullify them, because this sets only yaw.

**Comment by sfan5** [comment]
No, what I mean is: did this bug exist in 5.3.0 or was it newly introduced in the dev version?

**Comment by Andrey2470T** [comment]
I didn`t check it in 5.3.0 and earlier versions, I only noticed it in my current minetest_5.4.0-dev-41a6136f7 build.

**Comment by ElCeejo** [comment]
I can confirm this bug is present in 5.3 and 5.2

**Comment by v-rob** [comment]
I noted this in https://github.com/minetest/minetest/pull/10512#discussion_r507966533.

**Comment by rubenwardy** [comment]
Due to XYZ order, this may not be setting yaw as expected

**Comment by Andrey2470T** [comment]
> Due to XYZ order, this may not be setting yaw as expected
>

I wonder why another orders are not allowed. Because of that it is even impossible (I`m not sure, maybe possible, but by some tricky way) to set some kinds of a wanted orientation of an object.

About setting yaw, I think the result will always expected, because Y axis is global and therefore always static. And therefore, here can not be anomalies.

**Comment by paramat** [comment]
I disagree this is a bugfix.
The code being changed was added by @DevyHeavy in https://github.com/minetest/minetest/commit/faa358e797128ab07bb5644ce305a832d59e5596 #7395 in the implemention of yaw-pitch-roll rotation, so it is intentional.
I think the current behaviour is correct.

'Set yaw' is part of the old rotation API preserved to support the mods using it.
In the old rotation API, 'set yaw' sets yaw in a rotation system which only has yaw rotation, so i think it should stay this way, otherwise it is no longer the old rotation API. Therefore it must set pitch and roll to zero.
Even if the change in this PR does not break mods, the current behaviour is still more suitable and more logical.

Another problem:
'Get yaw' (when used together with 'set yaw') should return all the information needed to describe rotation, because that is what it did in the old rotation API. But with this PR now it does not, it only returns the yaw angle and misses out pitch and roll which can be any value because they have not been set to zero. So 'get yaw' is also changed from the old behaviour.

I also agree with this:
> Due to XYZ order, this may not be setting yaw as expected

@DevyHeavy any comments?

:-1: for this PR.
However, to avoid confusion (possibly the confusion that generated this PR), the documentation of 'set/get yaw' should be improved:
* 'set/get yaw' should be described as old preserved APIs, for 'yaw only rotation' usage only.
* 'set yaw' should be documented as setting any pitch and roll to zero.

I think confusion is caused because although we could have deprecated 'set/get yaw' we did not (maybe we should?). So some people do not realise these are preserved APIs and might think 'set/get yaw' is used with yaw-pitch-roll rotation.

**Comment by paramat** [comment]
Anyone using yaw-pitch-roll rotation should only be using 'set/get rotation', because that is the yaw-pitch-roll rotation API. This is fairly obvious but is not made clear in docs.
Therefore this PR has no benefit.

If 'set/get yaw' was intended to be used with yaw-pitch-roll rotation (it would be redundant, pointless and silly to do so) then we would also have 'set/get pitch' and 'set/get roll', but we do not have those.

**Comment by Andrey2470T** [comment]
Ah, well ok. I didn`t know this is an old unused in new versions function, preserved only for supporting the backward compatibility. Then, yes, probably it would make sense to add it if there were also 'set_pitch/set_roll()'.

**Pull request closed without merging**
