### PR TITLE
Pathfinder cleanup

### PR DESCRIPTION
**Pull request by est31**
Four commits to clean up and improve the pathfinder:

1. Move pathfinder classes to the cpp file
2. Style cleanup
3. Use irrlicht box type instead of self created one
4. Greatly speed up pathfinder for larger distances
5. (by @sofar): Use walkable instead of CONTENT_AIR checks for the pathfinder

### CODE REVIEW

**Comment by paramat** [comment]
Code looks okay in first 2 commits.

**Comment by gregorycu** [comment]
est31, if it's easy for you, would you mind sharing the code you used to test this out. I'd like to profile on windows to see if there is any more low hanging fruit we can trim out on Windows.

**Comment by est31** [comment]
@gregorycu take a look at the last commit of this PR: #3894 it executes the pathfinder on player movement (outside of singleplayer), then also uncomment the `PATHFINDER_CALC_TIME` macro in `src/pathfinder.cpp`, and best also add a print about the distance between start and end positions, the performance of the pathfinder depends on it.

**Comment by sofar** [comment]
This has been tested on my system for 3+ days without issues.

**Comment by gregorycu** [comment]
Thanks. I've found one:

http://www.gregorycurrie.com/fark.jpg

**Comment by sofar** [comment]
I believe that issue was present before the changes.

**Comment by gregorycu** [comment]
Yeah, I've found some additional speed improvements, but nowhere near the magnitude of est31's fixes. This is good to go in my eyes (I'm not a core dev however).

**Comment by kwolekr** [comment]
Lots of style cleanup here but what's up with keeping the opening function brace on the same line as the declaration?

**Comment by kwolekr** [comment]
If walkable is used instead of air, isn't this going to lead entities to walk through water?

**Comment by sofar** [comment]
@kwolekr correct. Of course swimming under water is much more simple - LoS can solve most of the path generation there. They are essentially like flying mobs.

I'm thinking that we may have to make special algorithms for flying mobs and for swimming mobs. The whole code right now is fixated to walking _on_ the surface. It also doesn't account for e.g. spiders walking on ceilings, it doesn't account for ladder climbing or wall climbers either.

**Comment by gregorycu** [comment]
Just a suggestion, it's possible we want more options as part of pathfinding. We already have largest drop and largest drop. We may want can climb, can swim options. Or even weighting, where a certain greater cost is associated with swimming. (So mobs will try to avoid it if possible). But all future enhancements.

**Comment by sofar** [comment]
@gregorycu that seems the right solution, yes

**Comment by est31** [comment]
@gregorycu great idea, like it. Note that currently this maxjump / maxdrop thing doesn't really work AFAIK. Its another thing that needs to be fixed.

**Comment by sofar** [comment]
#4049 for tracking

**Comment by paramat** [comment]
Some of this is way beyond me, but i approve of what commits 1, 2, 3, and 5 do, and have looked through those. I don't feel qualified to +1 this though, as much as i would like to.

**Comment by est31** [comment]
Okay, rebased and incorporated @kwolekr 's suggestion: the function braces now start on a new line.

**Comment by paramat** [comment]
Approved by nore http://irc.minetest.ru/minetest-dev/2016-05-01#i_4599101

**Pull request merged**
