### PR TITLE
Restore buggy texture overlay modifier

### LINKED ISSUE #14847: Texture alpha overlays appear to have become much darker
### Minetest version

```true
Minetest 5.9.0-dev-0e9fe7f19 (Linux)
```

### Irrlicht device

X11

### Operating system and version

Parabola

### CPU model

_No response_

### GPU model

_No response_

### Active renderer

OpenGL 4.5

### Summary

The hotbar slots in the inventory for Repixture 3.15.1 have become significantly darker in the `-dev` version compared to Minetest 5.8.0. This appears to be a regression.

The inventory slot graphics are created with texture overlays in the `rp_formspec` mod with `ui_itemslot.png^ui_itemslot_dark.png`. The first texture uses an alpha value of 12 (4.7%) (excluding the border) and the second texture a value of 102 (40%).

Interestingly, the color of normal slots (created with `ui_itemslot.png` alone) is unchanged.

### Steps to reproduce

1. Start Repixture 3.15.1
2. Open inventory

### PR DESCRIPTION
**Pull request by Desour**
Should fix #14847.

## To do

This PR is a Ready for Review.

## How to test

I've exported the test texture from #14448 into the screenshort dir.

Here are the branches for reproduction:
* 5.8.0 https://github.com/Desour/minetest/tree/restore_weird_texture_overlay_tmp_texexport_5.8.0
* master https://github.com/Desour/minetest/tree/restore_weird_texture_overlay_tmp_texexport_master
* PR https://github.com/Desour/minetest/tree/restore_weird_texture_overlay_tmp_texexport

And here are the resulting images:
* 5.8.0 
* master master
* PR pr

Results:
5.8.0 and PR look similar in my eyes. But sha256 hash values of the files, as well as `magick compare`, show that they're not exactly the same. I guess it's because of different rounding.

### CODE REVIEW

**Comment by Desour** [comment]
Testing done.

**Comment by Desour** [comment]
> I think the behavior of alpha for textures should be documented (including the quirk with when 2 semi-transparent textures are combined) so the modder knows what to expect.

I don't think knowing the exact formula for the semi transparent on semi transparent case is too useful. And I don't want to encourage users to rely on this bug.

I've added documentation for the (semi-)correct case. (Semi, because it's in srgb, which is also wrong.)

**Comment by appgurueu** [comment]
Is there a way to do correct blending in texture modifiers after the buggy behavior is restored?

**Comment by Desour** [comment]
> Is there a way to do correct blending in texture modifiers after the buggy behavior is restored?

No, not that I knew of.

**Comment by appgurueu** [comment]
It might make sense to add a new `^[blend` texture modifier for the correct behavior then.

**Comment by Desour** [comment]
Maybe. But it's feature freeze, and this would be a new feature. => Not in this PR.

**Review by SmallJoker — APPROVED** [review]
comparison

Works.

**Comment by HybridDog** [comment]
For the `testnodes:alpha_compositing` node, I have created the `testnodes_alpha_compositing_bottom.png` and `testnodes_alpha_compositing_top.png` textures such that two neighbouring vertical texels have the same color and the left and right side look the same if the blending works as expected. This PR hasn't updated the textures, so the test node could be broken now I think.

Furthermore, according to the `blit_pixel` documentation comment, a pixel with alpha=64 drawn atop a pixel with alpha=128 should yield a pixel with alpha=160. Is this still true?

**Pull request merged**
