### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by Zeno-**
Self explanatory

### CODE REVIEW

**Comment by rubenwardy** [comment]
I was also made [a core dev in august](http://irc.minetest.net/minetest-dev/2016-08-03#i_4666081)

And was a conclusion made in #4769?

**Comment by paramat** [comment]
+1 if rubenwardy is added.

**Comment by Zeno-** [comment]
Updated

**Comment by paramat** [comment]
:+1:

**Comment by Zeno-** [comment]
P.S. Sorry @rubenwardy :)

**Comment by sfan5** [comment]
:+1:

**Comment by est31** [comment]
@Zeno- don't forget @juhdanad

**Comment by paramat** [comment]
^ Yeah.

**Comment by Zeno-** [comment]
@juhdanad please let me know if you want the text changed. I used the username and email address from your last merged commit (in the past it was different)

**Comment by paramat** [comment]
:+1:

**Comment by ShadowNinja** [comment]
It'd like to see the non-core developers lists reworked a bit as discussed in #4769, but this is fine for now.

:+1:

**Comment by juhdanad** [comment]
@Zeno- could you replace it with "Dániel Juhász (juhdanad) <juhdanad@gmail.com>", please?

**Comment by Zeno-** [comment]
@juhdanad done

**Comment by juhdanad** [comment]
Thanks!

**Comment by sofar** [comment]
While you are updating this, can you take out the dedication to RBA?

**Comment by paramat** [comment]
^ Yes that should be removed.

**Comment by Zeno-** [comment]
Yep

**Comment by paramat** [comment]
:+1:

**Comment by kwolekr** [comment]
:+1:

**Comment by est31** [comment]
:+1:

**Pull request merged**
