### PR TITLE
http client fetch

### PR DESCRIPTION
**Pull request by devnexen**
adding optional download progress proposal via
 `curl_showprogress` boolean setting.

## To do

This PR is Ready for Review.

### CODE REVIEW

**Comment by kilbith** [comment]
This makes it possible to show the download progress on CDB, correct?

**Comment by devnexen** [comment]
CDB ? :-)

**Comment by SwissalpS** [comment]
> CDB ? :-)

Content Data Base, the official DB accessible by website and from the game menu.

**Comment by devnexen** [comment]
well it goes to the logging part at least.

**Comment by appgurueu** [comment]
I don't think this is particularly useful in it's current state (i.e. not exposed to the HTTP API, just logged to the verbose log).

**Comment by Emojigit** [comment]
And it's impossible to expose it, as HTTP API object is syncing. How do you expect a syncing function to yield progress bars? (It's possible to return the timed used to request, BTW.)

**Comment by sfan5** [comment]
This patch looks very unfinished and doesn't really do anything useful in this state:
* With the setting enabled, it applies to all HTTP requests with no indication what the current request might relate to.
* It prints `dtotal` which is the _total_ bytes to download. This value won't change during a request, no progress will be visible.
* Even if you run Minetest from the CLI (ordinary users don't), verbosestream is not visible by default. So nobody will see these log messages.

**Comment by rubenwardy** [comment]
This was discussed in the core dev meeting and we decided not to accept due to above reasons + limited usability (not many users use MT from a cli, this is new setting with limited usefulness)

Adding API support for http progress would make more sense

**Pull request closed without merging**
