### PR TITLE
Rename tab headers

### PR DESCRIPTION
**Pull request by ThomasMonroe314**
Closes issue #5982
@paramat

### CODE REVIEW

**Comment by paramat** [comment]
Hehe look what i did #6956

**Comment by paramat** [comment]
Please could you change the commit message to something like:
"Main menu: Change tabs to 'Start Game' and 'Join Game'"?

**Comment by ThomasMonroe314** [comment]
> Uh look what i did #6956 =)

lol

**Comment by nerzhul** [comment]
don't capitalize Game then :)

**Comment by rubenwardy** [comment]
It's kinda rude to work on PRs when someone has already said they're doing it, especially how trivial it is

**Comment by ThomasMonroe314** [comment]
> It's kinda rude to work on PRs when someone has already said they're doing it, especially how trivial it is

@paramat I'm sorry, I mis-read the comment, made the PR, then realized what you had said, but you had already closed yours.

**Comment by paramat** [comment]
No problem. I did say i'd make a PR but that was a month ago and i forgot, so someone else adopting the task is fine. Yesterday we both spontaneously and simultaneously made the exact same PR, unaware that the other was too =D This one was made first so has priority over mine.
:+1:

**Comment by ThomasMonroe314** [comment]
> Yesterday we both spontaneously and simultaneously made the exact same PR, unaware that the other was too.

Yeah, that was quite hilarious to be honest. :rofl:

**Pull request merged**
