### PR TITLE
Added "[sheet" to the texture special commands.

### PR DESCRIPTION
**Pull request by sofar**
"[sheet:W:H:X:Y" assumes the base image is a tilesheet with W*H tiles
on it and crops to the tile at position X,Y.  Basically it works
like "[verticalframe" but in 2d.

For testing, I combined the four default_chest images into one.

### CODE REVIEW

**Comment by sofar** [comment]
This is a rebased, and tested #1686.

**Comment by sofar** [comment]
This had one :+1: from @sfan5? @nerzhul ok with this rebase?

**Comment by est31** [comment]
Blocked by feature freeze.

**Comment by maikerumine** [comment]
Dang.  I really like this feature, use one image for many nodes.  Or locate a mob face in a texture to make a head.  This would be a great resource saver.

**Comment by HybridDog** [comment]
> Or locate a mob face in a texture to make a head.

UV maps are supported for mesh drawtype

**Comment by sfan5** [comment]
> And is it possible to improve performance by applying multiple modifiers at once instead of one after another?

I'm assuming you mean the code, it makes absolutely zero difference. Additionally this would cause inefficiencies with textures already partially generated in the past.

**Comment by pithydon** [comment]
Cool, I could use this for my rdis mod.

**Comment by paramat** [comment]
This PR now included in #4952

**Pull request closed without merging**
