### PR TITLE
Use tree to list mods rather than textlist

### PR DESCRIPTION
**Pull request by rubenwardy**
Video: https://youtu.be/Edamw7svDOk

Adding nested modpack support is out of scope of this PR

### CODE REVIEW

**Comment by numberZero** [comment]
Looks very nice) Can you add background to the tree view?
Anyway, I want this to be merged)

**Comment by rubenwardy** [comment]
> Can you add background to the tree view?

Out of scope, but I'll add it to my todo list

**Comment by numberZero** [comment]
> Out of scope

I mean simply restoring black background for the mod list. Do you mean that is not supported by formspec?

**Comment by rubenwardy** [comment]
Fixed

**Comment by sofar** [comment]
:+1:

I like how this simplifies the code significantly as well.

**Comment by paramat** [comment]
bb4db84bdbc7038a6ac495dd5f732f89ac40bfcc

**Pull request closed without merging**
