### PR TITLE
Statbars: Reduce initial update interval

### PR DESCRIPTION
**Pull request by SmallJoker**
This PR fixes the `on_joinplayer` HUD management race, which messes up the mod `hudbars` (see #7052) and others. It also ensures that the health and breath is scaled correctly by registering the `on_joinplayer` callback as last, when the mods decided what the player's maximal health and breath is.

**Mods to test**
[hudbars](https://forum.minetest.net/viewtopic.php?t=11153)
[upgrade_packs](https://github.com/SmallJoker/upgrade_packs) (`/giveme upgrade_packs:hp_10`, `/giveme upgrade_packs:breath_5`)

Glue to use both at once:
```diff
diff --git a/init.lua b/init.lua
index fc43f85..79e4ce0 100644
--- a/init.lua
+++ b/init.lua
@@ -432,8 +432,8 @@ end
 
 --register built-in HUD bars
 if minetest.settings:get_bool("enable_damage") or hb.settings.forceload_default_hudbars then
-	hb.register_hudbar("health", 0xFFFFFF, S("Health"), { bar = "hudbars_bar_health.png", icon = "hudbars_icon_health.png", bgicon = "hudbars_bgicon_health.png" }, 20, 20, false)
-	hb.register_hudbar("breath", 0xFFFFFF, S("Breath"), { bar = "hudbars_bar_breath.png", icon = "hudbars_icon_breath.png", bgicon = "hudbars_bgicon_breath.png" }, 10, 10, true)
+	hb.register_hudbar("health", 0xFFFFFF, S("Health"), { bar = "hudbars_bar_health.png", icon = "hudbars_icon_health.png", bgicon = "hudbars_bgicon_health.png" }, 61, 61, false)
+	hb.register_hudbar("breath", 0xFFFFFF, S("Breath"), { bar = "hudbars_bar_breath.png", icon = "hudbars_icon_breath.png", bgicon = "hudbars_bgicon_breath.png" }, 30, 30, true)
 end
 
 local function hide_builtin(player)
@@ -455,8 +455,8 @@ local function custom_hud(player)
 		hb.init_hudbar(player, "health", player:get_hp(), nil, hide)
 		local breath = player:get_breath()
 		local hide_breath
-		if breath == 11 and hb.settings.autohide_breath == true then hide_breath = true else hide_breath = false end
-		hb.init_hudbar(player, "breath", math.min(breath, 10), nil, hide_breath or hide)
+		if false and hb.settings.autohide_breath == true then hide_breath = true else hide_breath = false end
+		hb.init_hudbar(player, "breath", breath, nil, hide_breath or hide)
 	end
 end
 
@@ -474,11 +474,11 @@ local function update_hud(player)
 		--air
 		local breath = player:get_breath()
 		
-		if breath == 11 and hb.settings.autohide_breath == true then
+		if false and hb.settings.autohide_breath == true then
 			hb.hide_hudbar(player, "breath")
 		else
 			hb.unhide_hudbar(player, "breath")
-			hb.change_hudbar(player, "breath", math.min(breath, 10))
+			hb.change_hudbar(player, "breath", breath)
 		end
 		--health
 		update_health(player)
```

EDIT: To fix the rest of #7052, we need to improve the queue handling and packet order.

### CODE REVIEW

**Comment by nerzhul** [comment]
@SmallJoker the packet ordering is assured by the low level code. If i remember we use a vector on client we must use a unordered map to ensure hud ids are correctly received in the correct order

**Comment by nerzhul** [comment]
definitively a better solution, it seems my new registration call was useful :)

**Comment by paramat** [comment]
Made a blocker as the remaining hudbar bugs may be considered a blocker.
@Wuzzy2 could you test this PR to see if it fixes the remaining hudbar bugs?

**Comment by Wuzzy2** [comment]
This PR is a complete FAILURE! Line 73 starts with a space instead of a tab. Unacceptable!

And with this PR I also FAIL to reproduce any of the HUD bar breakage in all of MTG, MCL2 and Minimal! Yes, the HUD bars behave correctly with this PR now.

:P

**Comment by paramat** [comment]
```
Applying: Statbars: Reduce initial update interval
.git/rebase-apply/patch:61: space before tab in indent.
 			hud_def.number = number
warning: 1 line adds whitespace errors.
```

**Comment by paramat** [comment]
Some testing:
Using a mod that sets player HP max to 200 'on joinplayer' the healthbar is now scales correctly from the start, shows 1 heart for 20/200. Previously it didn't.
Altering apples to give 100 HP, eating one gives 6 hearts 120/200.
Codestyle looks ok.

**Comment by paramat** [comment]
Setting player breath max to 50 'on joinplayer' the healthbar is now scales correctly from the start, shows 2 bubbles for 11/50.
This PR is tested well now.

**Comment by paramat** [comment]
Merged eea1fdaf2574fec38316527cfc463ff2427c5775

**Pull request closed without merging**
