### PR TITLE
THST library; helper PR for WIP spatial indexing improvements

### PR DESCRIPTION
**Pull request by JosiahWI**
Adds the THST library required by #11973

### CODE REVIEW

**Comment by lhofhansl** [comment]
QQ: Can we rip out SpatialIndex now?

**Comment by JosiahWI** [comment]
Already done in the other PR as far as the build is concerned, but I haven't yet removed all references to it in the code. It's easy to do anytime, but is there any reason to do it before THST is fully integrated?

**Comment by sfan5** [comment]
I don't know why this PR was opened because it just adds a bunch of code that is neither compiled nor used.
If you want confirmation that we are fine with this library then an issue is the correct way. ([discussed in meeting](https://irc.minetest.net/minetest-dev/2022-04-24#i_5965871))

**Comment by JosiahWI** [comment]
I opened this PR at the request of lhofhansl so that the THST code wouldn't get in the way of the review process for the other PR. If I commit all these files in that same PR, whoever reviews it will have to sift through a hundred third party files to find what the PR authors actually did.

**Comment by Zughy** [comment]
Closing (see also https://irc.minetest.net/minetest-dev/2022-05-26#i_5979887)

**Pull request closed without merging**
