### PR TITLE
Italian Translation by Bassa31

### PR DESCRIPTION
**Pull request by ghost**
Hello,
I am a new user of Minetest, your work is great!
I'm updating italian translation for next version of minetest ( 0.4.14?)
This is a WIP! 
Thanks and cheers

Riccardo Montanari (Bassa31)

### CODE REVIEW

**Comment by kilbith** [comment]
Please do that here : https://hosted.weblate.org/projects/minetest/minetest/it/

Don't open pull-requests for translations.

**Comment by est31** [comment]
As @kilbith said, the tool for contributing translations is weblate. We don't want translations be done by two systems, as it will lead to merge conflicts.

**Comment by Bassa31** [comment]
Sorry... I don t know it...

**Comment by est31** [comment]
No problem :)

**Pull request closed without merging**
