### PR TITLE
Rename lua_api.txt to lua_api.md

### PR DESCRIPTION
**Pull request by jtrent238**
The file should be named with `.md` extention.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Most recent PR: https://github.com/minetest/minetest/pull/5451
Closed due reason given here: https://github.com/minetest/minetest/pull/6707

**Comment by paramat** [comment]
.md makes files impossible to work with in Github for the reasons in  , which is why the client api file was changed to .txt.
:-1:

**Comment by rubenwardy** [comment]
http://rubenwardy.com/minetest_modding_book/lua_api.html

**Comment by jtrent238** [comment]
Ok I see!

**Pull request closed without merging**
