### PR TITLE
World-aligned textures

### LINKED ISSUE #5222: Upside-down stairs, slaps, etc. should have “upside-down textures”, too
When placing stairs and slaps, etc. upside-down (i.e. aiming for a block above and placing the node) they’re upside-down which is absolutely fine.

Unfortunately their texture seems not to be altered to match the regular textures (default textures).

screenshot_20170212_194145

Here’s another example (top row: stone bricks, middle row: regular stair, upside-down stair, regular stair, bottom row: stone bricks, all seen from behind).

screenshot_20170212_194614

The best thing would be, rotating the texture upside-down, too. This would result in properly aligned textures.

### PR DESCRIPTION
**Pull request by numberZero**
#5993 
***UPD: Superseded by #6105 (merged)***
~~Right now, it fixes #5222; but now it acts unconditionally, that should be changed. IMO there should be new tile properties for that, smth like `world_align` (bool) and `scale` (float).~~
***UPD:** Fixes #5222 adding new `world_align` tile property. `scale` will be added in another PR.*
screenshot_20170702_234954
*Old screenshots:*

**Before**
screenshot_20170629_021008

**After**
screenshot_20170629_020901

Right now it works for nodeboxes *and solid nodes* only; for meshes that’s not that trivial, but correct rotation is achievable, at least. *But that seems to be out of scope of this PR.*

P.S. You may find first two commits in some other my PR...

### CODE REVIEW

**Comment by paramat** [comment]
Am i right in thinking this will use the upright-brick texture on rotated stairs when it detects the same texture being used on a neighbouring node that is in the same plane? Looks good.

**Comment by numberZero** [comment]
@paramat This is WIP, yes. But doing it the way you imagine is too complicated and bug-prone. My approach is to let the modder decide should the texture be rotated with the node (regardless of the environment), or should it be world-aligned (again, regardless of the environment). All world-aligned texture instances (with the same params, if any) fit each other, just like those on solid nodes.

This way, solid-material nodes, like stairs, should use world-aligned textures to look better, while others should use standard node-aligned textures for the same reason.

**Comment by Fixer-007** [comment]
I was waiting for this for long time, this will help harmonise lots of builds. Also, not the best choice for screenshots (too dark)

**Comment by DS-Minetest** [comment]
>Also, not the best choice for screenshots... too dark.

Yeah, and afaics the part at that you shall look at is on the upper left corner where much chat and debug text is.
Or is there something interesting in the dark that can't be seen? (I'm just wondering. The screenshot confuses me a bit.)

**Comment by numberZero** [comment]
> Also, not the best choice for screenshots... too dark.

Sorry, hadn’t time to find anything better than my base. But that’s just an example; I’ll show more later.

> the part at that you shall look at

...is the upper part of the gate (below chat)

**Comment by paramat** [comment]
Ok sounds good.

**Comment by Wuzzy2** [comment]
I think https://github.com/minetest/minetest/issues/682 solves the original problem much more elegantly.

But tbh I have no idea what this PR does, and I don't like to play “spot the difference”.

**Comment by numberZero** [comment]
@Wuzzy2 That’s exactly what I do. Thanks for the idea of using yet another `param2` type; that will be something like `CPT2_FACEDIR_WORLD_ALIGNED` and `CPT2_COLORED_FACEDIR_WORLD_ALIGNED` (or only the colored version—is that acceptable? It may have all-white palette by default, thus effectively ignoring color bits if no palette is given; not sure is that implemented already).

**Comment by Wuzzy2** [comment]
If it solves the problem, I am probably fine with the solution even if it does not involve `param2`.

**Comment by paramat** [comment]
> `CPT2_FACEDIR_WORLD_ALIGNED` and `CPT2_COLORED_FACEDIR_WORLD_ALIGNED` (or only the colored version—is that acceptable?

Not keen on using param2 for this, maybe a nodedef parameter? But if this must check that parameter for every tile would using a nodedef parameter cause a significant performance hit?

`CPT2_COLORED_FACEDIR_WORLD_ALIGNED` is not possible, color param2 uses up all spare bits where it is used, so it may have to be a nodedef.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/682#issuecomment-312471070
I think texture world alignment is best stored per-tile as a tile property.

**Comment by numberZero** [comment]
Thanks for your opinions and suggestions.
screenshot_20170702_234954
As you see, both node-aligned and world-aligned textures are supported. To differentiate, a tile attribute is used.
For information, see `doc/lua_api.txt:4100`
**Note:** this PR updates the protocol!

**Comment by numberZero** [comment]
So, should I add/fix anything in this PR?

**Comment by paramat** [comment]
I feel 'world aligned' is unclear, all textures a re world aligned in all rotations.
Perhaps 'no_rotate'? 'non_rotatable'?

**Comment by paramat** [comment]
Sorry accidental close.

**Comment by numberZero** [comment]
1. `non_rotatable` sound very bad IMO,
2. while `world_aligned` doesn’t explain how does it work, it should be easy to remember that it is used when you care more of consistency than of node identity.
3. I plan to extend meaning of `world_aligned` to exactly that (in a compatible way, of course) in another PR, so that it will do more than preventing rotation.

So I’d prefer to keep the current name. Note that I documented it: https://github.com/minetest/minetest/pull/6075/commits/559728da2f7cd94543346d2635a7eb166f83e921.

**Comment by paramat** [comment]
Ok that's fine then.

**Comment by paramat** [comment]
Good feature i like it.

**Comment by numberZero** [comment]
rebased

**Comment by C1ffisme** [comment]
Just a nitpick, those last two screenshots are really dark, and you should probably pick better ones...


...But I'm definitely interested in this pull.

**Comment by numberZero** [comment]
#6105 merged

**Pull request closed without merging**
