### PR TITLE
[Adoption] of GreenXenith's ssr shaders.

### LINKED ISSUE #4219: Water reflections?
Can water reflect stuff

### PR DESCRIPTION
**Pull request by DragonWrangler1**
- Goal of the PR
make actual water reflections. And it also added tinted sunlight.
- How does the PR work?
when shaders are enabled it makes actual water reflections. it also adds tinted sunlight.
- Does it resolve any reported issue?
fixes #4219 . The creator closed the issue thinking water reflections wouldn't happen.
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
could be considered part of 2.1

## To do

This PR is a Work in Progress.
 - Review the code.
 - Test to ensure it works properly.

## Notes.
This pr is largely based on GreenXenith's bfs minetest branch, the main differences are that I ported it to 5.9.0 and I modified the shaders, so they aren't as elegant, but they perform on average 5-10 times better. I got 4 fps on GreenXenith's, but I get and average of anywhere between 20-40 on mine. I made this since that branch seems to have been abandoned for 9 months now.

## How to test

compile. Go into your world and look at the water to ensure it reflects properly.

## Known bugs
 there is a slight visual bug with it since porting to 5.9.0 when your pitch is below 0 the shader starts to make a circle around the player that isn't shaded.

Screenshots as requested. This is of what works. See below for what doesn't work. the following 4 images are outdated. Not much changed though.                                                                                                                                                                                 Screenshot from 2024-07-07 16-48-41
Screenshot from 2024-07-07 16-49-46
Screenshot from 2024-07-07 16-50-12
Screenshot from 2024-07-07 16-51-46

Most recent screenshots
Screenshot from 2024-07-08 10-46-56

And the picture of what doesn't work.
Screenshot from 2024-07-08 10-44-43

### CODE REVIEW

**Comment by superfloh247** [comment]
screenshot_20240707_164356

impressive

can this be merged with #14610 ?

**Comment by DragonWrangler1** [comment]
It probably could be... By the way GreenXenith did make most of this, I just made some performance improvements.

**Comment by DragonWrangler1** [comment]
the most recent commit greatly improves the visuals, by removing the unecessary waves (since we already have other waves) and then it also increases the average performance. I had gotten an average of 13fps. Now I get around 40.

**Comment by DragonWrangler1** [comment]
just a few pictures.
Screenshot from 2024-07-07 16-48-41
Screenshot from 2024-07-07 16-49-46
Screenshot from 2024-07-07 16-50-12
Screenshot from 2024-07-07 16-51-46

**Comment by Wbjitscool** [comment]
Awesome

**Comment by Wbjitscool** [comment]
dose it do players too and entity's aswell?

**Comment by DragonWrangler1** [comment]
> does it do players too and entity's aswell?

from every test I have done so far it did.

**Comment by Wbjitscool** [comment]
cool

**Comment by Wbjitscool** [comment]
now just to fix that problem with the camera thing

**Comment by Wbjitscool** [comment]
I also noticed it's missing the sun glowing part too

**Comment by superfloh247** [comment]
looks broken now, depending on the view angle the reflections are missing

screenshot_20240708_074256


screenshot_20240708_074323

**Comment by Wbjitscool** [comment]
yeah ik i have it compiled

**Comment by Wbjitscool** [comment]
hmm maybe have tiny small ripples in the water too

**Comment by nerzhul** [comment]
i think we could iterate merging this post release. it's amazing and make minetest another game. I need to find time to work on entities to make world more living and less raw low level than now

**Comment by DragonWrangler1** [comment]
> I also noticed it's missing the sun glowing part too in the reflections part for the sunrays 
ya, they don't do that. Yet.

> looks broken now, depending on the view angle the reflections are missing

Ya they've been like that since I ported it to 5.9.0, it just got way more noticable in the last commit.

> hmm maybe have tiny small ripples in the water too that are closer together
I'll have to experiment with the ripples, since they can cause a very large performance drop.

**Comment by GefullteTaubenbrust2** [comment]
It's a little strange to have the PR not from Green himself, but I'll just set that aside. This is a really awesome feature and I really want to see it in game. There's a few glaring problems though that need adressing. First is it doesn't handle anything off-screen well. This is inherent to SSR, but there should be at least some effort dedicated to hiding the artefacts. I'm thinking maybe you could even sample the sky cubemap? The water waves also seem not to apply properly and it looks like that's just because the correct normals aren't passed to the SSR shader. 
Something else I noticed is the PR also adds tinted sunlight, which should probably be in the description. Some screenshots to go with the description would also be appreciated. Hoping we get reflections in the game soon :D

**Comment by DragonWrangler1** [comment]
went ahead and posted a few pics in the description.

**Comment by DragonWrangler1** [comment]
> hmm maybe have tiny small ripples in the water too that are closer together

Wbjitscool. re-added the waves under a different faster noise function. (pretty much all of it came from nodes_shader).

Fixed the circle part not being shaded. Now to just finish fixing the issue. (the last part remaining is still pitch affected. It only shows the skybox color and not reflections)

**Comment by DragonWrangler1** [comment]
I'm converting this to a draft, so noone accidently merges it. (not like that's very likely.)

**Comment by GefullteTaubenbrust2** [comment]
> Looks like silly me accidently added some of the code meant for my shaderpack into this.... oopsie.
Nah those are from his branch, i checked. Unless you added additional stuff aside from the tinted sunlight... Either way the original point stands.

**Comment by DragonWrangler1** [comment]
I added that into the description earlier. No need to remove it.

**Comment by GefullteTaubenbrust2** [comment]
> > hmm maybe have tiny small ripples in the water too that are closer together
> 
> Wbjitscool. re-added the waves under a different faster noise function. (pretty much all of it came from nodes_shader).
> 
> Fixed the circle part not being shaded. Now to just finish fixing the issue. (the last part remaining is still pitch affected. It only shows the skybox color and not reflections)
> 
> The ripples in the image are without waving water enabled. Screenshot from 2024-07-08 10-46-56

I find this approach kind of strange... Instead I feel like how this should work is you would have the correct normals written in the nodes shader and just use that in the reflection shader, right? I get this isn't trivial to do from the vertex shader, but there's an exact gradient function for the snoise function that generates the waves which can be used to get the normals.

**Comment by DragonWrangler1** [comment]
since I just started working on this two days ago many things have changed. My plan was to eventually move that to the nodes shader. My main goal today is fixing that one bug though.

**Comment by lhofhansl** [comment]
If it's not too much of a detour I'd suggest we merge https://github.com/minetest/minetest/pull/14610, and then this one.

**Comment by DragonWrangler1** [comment]
> If it's not too much of a detour I'd suggest we merge https://github.com/minetest/minetest/pull/14610, and then this one.
Depending on how expensive real water reflections are, we might even want to keep the simpler (sun only) reflections as a config option.

I was hoping that one would be merged first. By the way. These reflections aren't too bad, I average 30-35 fps with these and shadows enabled, which is also what I average with just shaders. And this is on a view of 290.

**Comment by DragonWrangler1** [comment]
> I find this approach kind of strange... Instead I feel like how this should work is you would have the correct normals written in the nodes shader and just use that in the reflection shader, right? I get this isn't trivial to do from the vertex shader, but there's an exact gradient function for the snoise function that generates the waves which can be used to get the normals.

The approach is only temporary.

**Comment by DragonWrangler1** [comment]
> looks broken now, depending on the view angle the reflections are missing

I found where the issue originates. So It'll hopefully be fixed shortly.

**Comment by DragonWrangler1** [comment]
Tomorrow I’ll add a setting that will toggle the reflections so they aren’t enabled by default.

**Comment by Wbjitscool** [comment]
cool

**Comment by Wbjitscool** [comment]
then I hope we can merge GefullteTaubenbrust2's visual vol no.1 pr for the other shaders the improves on the clouds and block specular etc but keep this pr's reflective water

**Comment by Wbjitscool** [comment]
I really like the ripples

**Comment by Wbjitscool** [comment]
hmm it still has a camera transparency issue with it with facing in different directions but it's better now without that circle
screenshot_20240709_204118

**Comment by Wbjitscool** [comment]
or is that just the sky reflection just being too reflective on the water

**Comment by DragonWrangler1** [comment]
Wbjitscool: I do believe it’s a bug. I’m still trying to figure out why it does that.

**Comment by Wbjitscool** [comment]
yeah same thing for under the water too
screenshot_20240709_230946

**Comment by DragonWrangler1** [comment]
oh, underwater too ? k, thanks.

**Comment by Wbjitscool** [comment]
yep and np

**Comment by DragonWrangler1** [comment]
I'll just make a list.

- [ ] looking at trees through certain angles leaves visual artifacts.
- [ ] same thing for large floating structures closer than the water is.
- [ ] at a certain pitch shaders start breaking.

**Comment by Wbjitscool** [comment]
and around certain corners too

**Comment by DragonWrangler1** [comment]
I really wonder what happened between 5.8.0-dev and now that caused so many changes that'd break this feature. Anyway. I'd best get back to work.

**Comment by DragonWrangler1** [comment]
> hmm it still has a camera transparency issue with it with facing in different directions but it's better now without that circle

I know that in 5.8.0 the reflections did the same thing, except it was supposed to, and it was blended well.

**Comment by DragonWrangler1** [comment]
Something that GefullteTaubenbrust2 said caught my attention. mainly this: > First is it doesn't handle anything off-screen well. Which could explain all the artifacts, and the pitch issue. If I could fix this, then those issues would be mostly fixed as well.

**Comment by superfloh247** [comment]
screenshot_20240709_144413
screenshot_20240709_144410
screenshot_20240709_144406

**Comment by DragonWrangler1** [comment]
Ya. The issue still isn't fixed (yet.)

**Comment by DragonWrangler1** [comment]
since lava is the same tile as water, I'm not sure if those can be differentiated. Porting from 5.8.0-dev to 5.9.0-dev introduced several bugs. I'll try to fix them all very soon. Also, yes I'm aware of the flickering artifacts.

**Comment by superfloh247** [comment]
OK, good to know that you're aware and that it's not a Mac specific thing

**Comment by DragonWrangler1** [comment]
in the most recent commits. It adds a new setting behind the waving water shader. 
It doesn't fix the pitch bug however.

**Comment by GreenXenith** [comment]
I was waiting on #14610 to be merged before I rebased ... I also have some fixes from Andrey2470T to merge, and some other improvements. I'm also not sure I even like the idea of all these shaders being added without a way for games to control them :/

**Comment by DragonWrangler1** [comment]
GreenXenith: I see. Just say the word and I'll close this pr.

**Comment by superfloh247** [comment]
2024-07-10 07:59:38: ERROR[Main]: Irrlicht: GLSL (> 2.x) shader failed to compile: shaderType: 35633
2024-07-10 07:59:38: ERROR[Main]: Irrlicht: ERROR: 0:271: Use of undeclared identifier 'p'
ERROR: 0:272: Use of undeclared identifier 'p'
ERROR: 0:272: Use of undeclared identifier 'a'
ERROR: 0:273: Use of undeclared identifier 'd'
ERROR: 0:273: Use of undeclared identifier 'd'
ERROR: 0:273: Use of undeclared identifier 'd'
ERROR: 0:273: Use of undeclared identifier 'd'
ERROR: 0:275: Use of undeclared identifier 'a'
ERROR: 0:276: Use of undeclared identifier 'b'
ERROR: 0:277: Use of undeclared identifier 'k1'
ERROR: 0:277: Use of undeclared identifier 'b'
ERROR: 0:279: Use of undeclared identifier 'k2'
ERROR: 0:279: Use of undeclared identifier 'a'
ERROR: 0:280: Use of undeclared identifier 'c'
ERROR: 0:281: Use of undeclared identifier 'c'
ERROR: 0:283: Use of undeclared identifier 'k3'
ERROR: 0:284: Use of undeclared identifier 'k4'
ERROR: 0:286: Use of undeclared identifier 'o2'
ERROR: 0:286: Use of undeclared identifier 'd'
ERROR: 0:286: Use of undeclared identifier 'o1'
ERROR: 0:286: Use of undeclared identifier 'd'
ERROR: 0:287: Use of undeclared identifier 'o3'
ERROR: 0:287: Use of undeclared identifier 'd'
ERROR: 0:287: Use of undeclared identifier 'o3'
ERROR: 0:287: Use of undeclared identifier 'd'
ERROR: 0:289: Use of undeclared identifier 'o4'
ERROR: 0:289: Use of undeclared identifier 'd'
ERROR: 0:289: Use of undeclared identifier 'o4'
ERROR: 0:289: Use of undeclared identifier 'd'
ERROR: 0:290: Use of undeclared identifier 'noiseValue'

2024-07-10 07:59:38: ERROR[Main]: generate_shader(): failed to generate "nodes_shader", addHighLevelShaderMaterial failed.

**Comment by DragonWrangler1** [comment]
Should be fixed. I accidentally copied something twice, and once was in the wrong area.

**Comment by DragonWrangler1** [comment]
Since GreenXenith has returned now. I am put in an interesting position. So I have prepared this long comment to determine whether or not to close this.

In the past several years a few prs have been closed due to the fact that it took so long to add a feature, and the creator lost interest, and overtime the likelyhood of that feature being adopted decreased due to the amount of changes made to the game, making it hard to add. GreenXenith has already said that he's waiting on #14610 before he starts the rebase, but waiting for something to be added before even rebasing this, might prove to take several months.

So here is my proposal. Currently this pr is open, not ready to be merged, but I'm pretty positive that I can get the bugs out. Even after (asuming it does) get merged, GreenXenith can make any modifications he wants.

@superfloh247 
@Wbjitscool 
@nerzhul 
@GefullteTaubenbrust2 

This is currently at the table, and could be ready for merging in probably a few weeks. GreenXenith's branch is far from it currently. As he said he is waiting for a pr to be merged before he begins rebasing.

Should this pr be thrown out, and we wait for possibly a few more months before it gets added. Or should this be added, and GreenXenith make modifications later on ? I'm not saying this should be merged in it's buggy state. But I do believe I can fix these bugs. They're all visual anyway.

**Comment by Wbjitscool** [comment]
I am not too sure tbh

**Comment by lhofhansl** [comment]
Up to @GreenXenith I guess. In any case, even if we use this PR the first commits are @GreenXenith's and should be under his name.

**Comment by tigercoding56** [comment]
> since lava is the same tile type as water, I'm not sure if those can be differentiated. Porting from 5.8.0-dev to 5.9.0-dev introduced several bugs. I'll try to fix them all very soon. Also, yes I'm aware of the flickering artifacts.

reflective lava sounds cool , maybe we should just mark that a feature

**Comment by Wbjitscool** [comment]
Yeah I like the reflective lava too also reflective ice?

**Comment by DragonWrangler1** [comment]
Might be slightly harder to do reflective ice since this checks for water image or in other words liquid. Ice is a solid so it'd affect other nodes too.

**Comment by DragonWrangler1** [comment]
Closing due to lack of interest. And since I’m not hearing from @GreenXenith . If there is interest in this in the future. I’ll see what. I can do.

**Comment by GreenXenith** [comment]
It's not really up to me, you're doing the work right now. If I see things to change I can change them later.

Side note, reflective lava is not acceptable.

**Comment by ezileicorreia** [comment]
I hope #14427 #14610 #14828 will be merged before version 5.999.0!

**Comment by Andrey2470T** [comment]
I can confirm that the reflections work much faster only for singleplayer however (stable 59-60 FPS even looking only at the water). On multiplayer it drops down up to 10 frames (I'm not sure, maybe there are other reasons for that, probably many translucent nodes around causing an intensive transparency sorting). The videocard is NVIDIA GeForce GTX 1050.

Also this PR adopts many artifacts as the broken normals at the water sides, see-through water blocks if they are behind solid ones, the broken transparency for leaves. A part of them my branch fixes: https://github.com/Andrey2470T/minetest/tree/water_reflections

Except that, I noted the new visual glitch representing continuous flickerings when the look dir is changed:

https://github.com/user-attachments/assets/da095b46-e56b-40eb-b584-2c0a8ede2570

**Comment by DragonWrangler1** [comment]
Ya that flickering was due to me removing the skycolor as the fallback since the skycolor had its own problems (like a giant circle under the player, and color not matching correctly

**Comment by DragonWrangler1** [comment]
I may end up closing this again, but we'll see how much time I have to work on it.

**Comment by lhofhansl** [comment]
Note that #14610 just got merged. If we wanted we can proceed with this one now. @DragonWrangler1 @GreenXenith

**Comment by MirceaKitsune** [comment]
Very happy for #14610 being merged, but it's also exciting to discover this PR which further builds on the improvements! I wonder how the two shaders interact without duplicating existing functionality: With the first merged this can hopefully either improve what the other PR added or include what it didn't yet. The screenshots look amazing and appear to add proper reflections which weren't mentioned in the previous PR.

**Comment by GreenXenith** [comment]
Ill try rebasing my changes and see what still needs to be done.

**Comment by DragonWrangler1** [comment]
@GreenXenith If you want I can close this pr, so you can open one, then I'll just make a pr on your branch, for the actual performance improvements. Since I'm a bit busy doing other stuff.

**Comment by MirceaKitsune** [comment]
We discussed reflections on Discord a bit, figured I'd post the takeaway and points I made or agree with.

Now that a reflection system is being added, we definitely want it to be usable for all nodes not just water: Reflections are just as welcome on surfaces like metal, marble, ice, glass, etc. Speaking of water and glass, using a reverse reflection pass should allow adding refraction in the same change. By blurring the cubemap we should be able to simulate roughness and replace the simple specularity added in last night's PR with proper detail, metalicity could then be simulated by changing its blending. Yes, we can end up having actual PBR in Minetest using our lighting system!

The idea was shared by GreenXenith so I take no credit for it: With aggressive optimization we should be able to get away with rendering a cubemap per node thus a reflection probe every 1x1x1 meters. That scale can increase with distance to render fewer probes further away, for very distant nodes reflections can be disabled entirely. Cubemap resolution and draw distance don't need to be too high, if need be we may also skip frames for updating them.

The last essential effect to get the full set will be normal mapping. From what I understand Minetest is already aware of the direction light sources shine from on a surface: This means normal map support should be doable if anyone can figure out how to interpret them in the shader! I think we don't need to do it per light especially for the time being, if each pixel knows the average direction it's lit from and uses the normal map with that it would still be a great improvement, like if a pixel sits between two torches you get the relief from their average direction.

Normal and roughness maps will need to be generated for all textures and texture packs that want to use this. If it helps I'll try looking for a tutorial on obtaining them procedurally with ImageMagick or Blender or other tools: If I can make a script to compile all textures into an atlas then decompile them back, I can use Blender to bake the normal maps. Sadly I'm not good enough with GLSL to do the shaders myself, especially since Lua doesn't let you define your own shaders without having to edit the C++ definitions and recompile, but hopefully this helps at least.

**Comment by GefullteTaubenbrust2** [comment]
> We discussed reflections on Discord a bit, figured I'd post the takeaway and points I made or agree with.
> 
> Now that a reflection system is being added, we definitely want it to be usable for all nodes not just water: Reflections are just as welcome on surfaces like metal, marble, ice, glass, etc. Speaking of water and glass, using a reverse reflection pass should allow adding refraction in the same change. By blurring the cubemap we should be able to simulate roughness and replace the simple specularity added in last night's PR with proper detail, metalicity could then be simulated by changing its blending. Yes, we can end up having actual PBR in Minetest using our lighting system!
> 
> The idea was shared by GreenXenith so I take no credit for it: With aggressive optimization we should be able to get away with rendering a cubemap per node thus a reflection probe every 1x1x1 meters. That scale can increase with distance to render fewer probes further away, for very distant nodes reflections can be disabled entirely. Cubemap resolution and draw distance don't need to be too high, if need be we may also skip frames for updating them.
> 
> The last essential effect to get the full set will be normal mapping. From what I understand Minetest is already aware of the direction light sources shine from on a surface: This means normal map support should be doable if anyone can figure out how to interpret them in the shader! I think we don't need to do it per light especially for the time being, if each pixel knows the average direction it's lit from and uses the normal map with that it would still be a great improvement, like if a pixel sits between two torches you get the relief from their average direction.
> 
> Normal and roughness maps will need to be generated for all textures and texture packs that want to use this. If it helps I'll try looking for a tutorial on obtaining them procedurally with ImageMagick or Blender or other tools: If I can make a script to compile all textures into an atlas then decompile them back, I can use Blender to bake the normal maps. Sadly I'm not good enough with GLSL to do the shaders myself, especially since Lua doesn't let you define your own shaders without having to edit the C++ definitions and recompile, but hopefully this helps at least.

I had a pretty crude but procedural method in #14508 for bump maps, perhaps could be of interest. This simple way to get normal/roughness maps with the current engine is to just reuse the color data. Proper texture maps should feasible but probably a major pain to implement...

**Comment by GreenXenith** [comment]
So I didn't realize it until now but this PR is not based on just my changes, it's also based on x2048's. BFS is not mine, only SSR. I just based it on x2048's BFS branch https://github.com/x2048/minetest/tree/bfs/ because at the time he intended to get that merged, but that never happened. If you want to adopt cascaded shadow maps (https://github.com/minetest/minetest/pull/13956) that should go in a separate PR. Tinted sunlight also belongs in a separate PR.

**Comment by DragonWrangler1** [comment]
> So I didn't realize it until now but this PR is not based on just my changes, it's also based on x2048's

Actually, I hand picked each of your commits out of that branch into this one. I never put x2048's commits in.

**Comment by GreenXenith** [comment]
> > So I didn't realize it until now but this PR is not based on just my changes, it's also based on x2048's
> 
> Actually, I hand picked each of your commits out of that branch into this one. I never put x2048's commits in.

Well I never added tinted sunlight.

**Comment by DragonWrangler1** [comment]
Ah, I see. Understood.

**Comment by DragonWrangler1** [comment]
@GreenXenith Since you are obviously ready to work on this. I’ll close this pr and let you take over. I managed to accomplish my goal (improving performance.) I look forward to seeing your updates :-)

**Pull request closed without merging**
