### PR TITLE
Client-side node text render

### LINKED ISSUE #1367: Proper display of text on the surface of a node(box)
Sapier requested that I put this into a feature request so as not to get lost.

As it stands, in order to display text on the surface of a node or nodebox, it is necessary to convert the text into an image and use an entity to display it, as this is the only method the API seems to allow for creating/updating an image in realtime on the client and no method to actually put text into the world exists yet aside from Waypoints and other HUD elements.

As many people know, the entity-based method started from jin_xi's painting mod, the method of which was then used in PilzAdam's/xyz's signs mod and now signs_lib in Homedecor.  It is my and others' opinion that signs_lib implements the most complete possible way of handling these signs under the engine's present capabilities; see here for details: https://forum.minetest.net/viewtopic.php?pid=26061

Particularly, the signs are now capable of this:

image

Doing it the way we do now is of course hacky and uses a lot of texture memory (about 90 kB per sign).  It works well for PCs but not so much so for tablets: a typical spawn might have 200 or so signs around it, leading to round about 18 MB of texture memory used just for these signs, in addition to hundreds, possibly a few thousand bytes per sign for the compositing string that actually constructs the text on the client.  This, in turn, costs FPS, drastically so on some systems.  Of course the proper way to do this would be to use the display/rendering engine to actually place text onto the node/nodebox's surface instead of using an entity.

Regarding the signs API, they just need these things:  
* Exactly what the shape and textures of the node or nodebox are on which the text will be placed.  At present, this is accomplished by just defining a node in the usual manner and passing that node definition to the library when registering a new sign.
* Where within that node's space to put the text.
* Which way the text faces.
* How much text fits on a sign.  Currently, a sign holds 6 rows, with the number of characters per line being variable due to the use of a proportional font.

The way the text is styled needs a few things also:
* Colored text.  Currently, we use `#x` where `x` is a single hex digit from the standard CGA/Linux/IRC color palette to change the text color.  That palette is shown numerically in the bottom row of the sign in the image above.  Thus, `#9foo` would for example display "foo" in light blue.  Any number of color changes may be used on a sign.
* Line breaks.  Currently we use `<space><enter>` to force a line break, which works like `\n` elsewhere.
* Text is currently centered left-to-right per line, and displayed starting from the first allocated line on the sign.
* Font size.  Currently, signs_lib ships with a 15px font as its default, with other sizes included that can be swapped in as desired, for the sake of higher or lower levels of detail at the same apparent size.  Later, these other resolutions may be re-purposed to display text in other apparent sizes with the same level of detail (or we may just change the size of the entity, or do both.  This has not been decided upon yet).

### PR DESCRIPTION
**Pull request by numberZero**
Fix #1367. With this PR, any tile layer can be used to display text. Currently one text per node is supported (it may still be shown on several sides).

screenshot_20200622_045731

## To do

This PR is a Work in Progress

- [x] Lua API
- [x] Network serialization
- [x] Sequencing (multi-threading? batching? event listening?)
- [ ] Documentation
- [ ] Cleanup
- [ ] Client-side settings

## Feature requests

These are nice but non-essential features that may be added on top of this PR.

 * Multiple texts per node
 * Colored text support*
 * Different font support
 * Clipping*
 * Masking
 * Proper text alignment
 * Proper background support

*I’d like to implement everything but the time is finite, so I will consider these features first.

### CODE REVIEW

**Comment by KaylebJay** [comment]
Awesome. Finally. :)

**Comment by numberZero** [comment]
I like API like:
```lua
tiles = {
    {name = "top.png"},
    {name = "bottom.png"},
    {text = {
        type = "simple",
        meta = "infotext",
        line_count = 4,
        align = "center", -- left, right-top, or whatever
        color = "#FF0000", -- tile color becomes font color automatically
    },
    {name = "sides.png"},
},
```
or
```lua
tiles = {
    {text = "main"},
    {name = "bottom.png"},
    {text = "main"},
    {text = "side"},
},
text = {
    main = {
        type = "simple",
        meta = "infotext",
        line_count = 4,
        align = "center",
        color = "#FF0000",
    },
    side = {
        type = "simple",
        meta = "infotext",
        line_count = 6,
        align = "top",
        color = "#990000",
    },
}
```

**Comment by appgurueu** [comment]
Regarding color: Please support get_color_escape_sequence

**Comment by VanessaE** [comment]
See also #1367.

**Comment by VanessaE** [comment]
Looks like a good start!

**Comment by SmallJoker** [comment]
FYI: `EnrichedString` contains color escapes and is supported by `CGUITTFont`. Example usage:
https://github.com/minetest/minetest/blob/7ec0e3df35a11b66b48eababf0123170f2453a50/src/irrlicht_changes/static_text.cpp#L115-L130

**Comment by numberZero** [comment]
> Regarding color: Please support get_color_escape_sequence

Sure, but I’d prefer to keep non-essential features in separate PRs, there is enough work already.

**Comment by v-rob** [comment]
Is limiting the area in which the text can be displayed an objective of this PR, or should that be for a future one instead?  For instance, a sign in MTG takes up less than a full node in width and height, so defining the bounding box of the text would be important there.

Also, nice PR number: 9999.

**Comment by numberZero** [comment]
Can 99d48fa work on Android? I remember there were problems with off-screen rendering. If it can’t, I will need to implement software text rendering as well (not a great problem, just a few more code lines. OTOH it will be possible to off-load rendering to a thread in this case. It may even be faster due to less CPU-GPU synchronization).

**Comment by numberZero** [comment]
Works for me.
screenshot_20200622_045731
See `devtest` for examples.
Note: FreeType is required.

**Comment by numberZero** [comment]
Testing is needed!

**Comment by pyrollo** [comment]
Wouldn't it be much better and much more flexible to pass texture specifier rather that text ?
This would allow to do much more. There are many mods using an entity to fake dynamic textures, and not only for signs, they could be quickly adapted.
Furthermore, font and layout management could be very complex and there are already several Lua implementations for generating texture from text (in signs_lib mod, in digiline lcd screen and in font_api mod).

**Comment by LoneWolfHT** [comment]
> Wouldn't it be much better and much more flexible to pass texture specifier rather that text ?
> This would allow to do much more. There are many mods using an entity to fake dynamic textures, and not only for signs, they could be quickly adapted.
> Furthermore, font and layout management could be very complex and there are already several Lua implementations for generating texture from text (in signs_lib mod, in digiline lcd screen and in font_api mod).

See the discussion in the issue this fixes

**Comment by pyrollo** [comment]
Ok, too bad. I hope this will evolve later. In the current state, entity based displays are not likely to be abandoned.

**Comment by numberZero** [comment]
If you want this feature, test it please. I need to know should I polish the code or rework it radically. I do test myself but I can’t cover each and every possible case. Also systems differ so at least performance will definitely differ, it may be okay on my machine but not okay on some older one. Also I have no Windows™ system. And so on.

**Comment by numberZero** [comment]
okay

**Comment by sfan5** [comment]
I know it's not very motivating when code keeps lying around, but are there time constrains that prevent this PR from being completed at a later point?

**Comment by rubenwardy** [comment]
Any update on this?

**Comment by kilbith** [comment]
Yes, what’s the point on sabotaging your own PR?

**Comment by ExeVirus** [comment]
I might take this up myself, we'll see.

**Pull request closed without merging**
