### PR TITLE
Add 'multiface', 'colormultiface' paramtype2 and 'multiface' nodebox type

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds a new paramtype2 and nodebox type `"multiface"`. This drawtype toggles the rendering of each of the 6 possible sides/faces of the node "on" and "off".

The paramtype2 supports the drawtypes signlike and nodebox.
Signlike can be used to make simple vines in multiple sides of the same node. It's as if you put multiple signlikes into the same node.
Nodeboxes can be used for more complicated constructions.

https://satoshiupload.com/images/gNGZYUU3bo.png
https://satoshiupload.com/images/9Xe39i21Kw.png

Additionally, a new paramtype2 `"colormultiface"` is added which is the same as `"multiface"` but it uses the first 2 bits for color.

https://satoshiupload.com/images/oGBCMJtcwC.png

## How it works
Bits 0-5 control each of the 6 sides of a cube with value 1 meaning "side exists".

If all 6 bits are 0, then a fallback rendering will appear so the node is never invisible.

The signlike faces render exactly as you expect, the only difference is that if you use the multiface paramtype2, multiple sides might be occupied.

The nodebox behaves pretty much analog to the signlike stuff and also has a lot of useful defaults. It's recommended to use the default multiface nodebox for the multiface signlike.

For `"multiface"`, the first 2 bits are ignored, but for `"colormultiface"`, they are used for coloring.

## Todo
Testing.
Code quality.

## What does not work
Automatic placement in the right direction, building more on the same node, etc. This is not implemented and I don't know yet if I will add a rule for this PR (analog to wallmounted placement rules). But might be done in a later PR. Or not (let's be real ...).

For now, the game/mod author has to figure out proper placement behavior.

### Use cases

* Have multiple vines, ladders or other flat wall deorations at different angles in the same node. Great for decoration
* Powerful catwalk nodes in which you can turn the railings on/off with param2
* Complex window corner node systems
* Possibly simplify some of your complex 3D nodebox collections down to a single node

## To do
Testing.

## How to test

Play around with the new multiface nodes in DevTest and use the Param2 tool.
Read the documentation and construct your own multiface nodes.

### CODE REVIEW

**Comment by hecktest** [comment]
>     * Powerful catwalk nodes in which you can turn the railings on/off with param2

How would the collision for that work?

**Comment by Wuzzy2** [comment]
Simple: If the box is present, then it collides, if not, then it doesn't. Exactly like `connected_to` stuff. Also keep in mind that you can define collisionboxes separately from the (visible) nodebox. The collisionbox is completely independent from the rendering. It has been like that for years and this fact is not touched by this PR.

Let me repeat: Collision mechanics are NOT touched by this PR.

**Comment by Wuzzy2** [comment]
I have decided to drop the rotation of the fallback thingie.

But instead, I added a new paramtype2 `"colormultiface"` which uses the first 2 bits for color.
https://satoshiupload.com/images/oGBCMJtcwC.png

**Comment by rubenwardy** [comment]
Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed. These PRs can also have preapproval if they fix an issue that is concept approved

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label

**Comment by Wuzzy2** [comment]
:-(

**Pull request closed without merging**
