### PR TITLE
added simple quit button to main menu

### LINKED ISSUE #8681: Add "Exit The Game" Button for Main Menu.
## Problem
I'm User of Ubuntu Linux 19.10

First of all: When Minetest is in a Fullscreen Mode, it is always on top of the screen. It is just not possible to turn on Process manager and kill Minetest.

I'm frustrated when I'm in a Fullscreen Mode and There is no easy way to exit the game.
This especially horrible experience happens in Linux, since I do not know any of the keyboard shortcuts to kill the Minetest. So I have to shut down the whole computer or log out of the Linux User.

## Solutions
I want to see an Exit The Game Button somewhere in the Main Menu.

Screenshot from 2019-07-16 12-33-31

### PR DESCRIPTION
**Pull request by sgooding**
Fixes #8681

- Goal of the PR
 * Adds quit to the main menu.
- How does the PR work?
  * Click Quit and the program ends.
- Does it resolve any reported issue?
  * Fixes #8681 Add quit button
## To do

This PR is a Work in Progress
- [ ] Add pop-up menu

## How to test
1. Run app.
2. Click Quit button.

Screenshot from 2020-03-21 10-00-14

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
Not aligned with the other buttons and I don't think it should even be in the menu. I'd suggest a X button in the top-left if that text wasn't there. Maybe the text could be moved to the bottom left

**Comment by sgooding** [comment]
Regarding the "X button", what text are you referring to in the top-left?

**Comment by sgooding** [comment]
Screenshot from 2020-03-21 11-24-17

**Comment by LoneWolfHT** [comment]
> Regarding the "X button", what text are you referring to in the top-left?

"Minetest Game"

**Comment by sgooding** [comment]
Thanks. Any thoughts on where to start to add an additional button to the main display? lua/c++

**Comment by Desour** [comment]
You could place a button there by using negative coordinates and setting the button not clipped (with style or so).
However, this will probably not work well for any display/window sizes.

**Comment by LoneWolfHT** [comment]
Well, ESC closes the main menu, we could just wait for ruben's mainmenu PR

**Comment by sgooding** [comment]
I don't see an easy way to add an additional button outside the mainmenu form. Hopefully, ruben's approach makes this a bit easier.

**Pull request closed without merging**
