### PR TITLE
Finally set a window icon on X11

### PR DESCRIPTION
**Pull request by est31**
Since the creation of minetest, it had no window icon on X11.
Now we have one.

Generating a header file that contains a giant integer array
is not really the nicest way to specify data, but the
alternatives require lots of code for this very simple task:

1. convert the png each time we start minetest. This would
	require lots of additional code, and probably be slower

2. store the image in a custom binary format. X11 doesn't
	specify a on-disk format, so we would have to invent
	one. Straight writing of the array to a file e.g. with
	a fwrite(buffer, sizeof(buffer), 1, stdout); call
	isn't enough as the format is not cross-platform due
	to endianness issues. Therefore we'd have to apply
	conversions on loading and storing. This would be
	lots of additional code as well.

In fact, the 8 bytes per long that are required for a
straight-forward binary format require *more* disk space
than if the icon is stored in ASCII format
(10272 bytes vs 10252).

### CODE REVIEW

**Comment by sofar** [comment]
Looks OK, maybe break up the ginormously long lines (every 8 bytes or so?)

**Comment by est31** [comment]
I've thrown clang-format at it, the file size has increased from 11k to 17k.

**Comment by est31** [comment]
Hmm I also have a sed-only version that only adds about 200 characters, but only newlines. I'll use that I think.

**Comment by est31** [comment]
OK, I've added a 64x64 version, now the text file is 40kb large. But I feel it is needed, as otherwise the icon gets rendered in a blurry way.

**Comment by est31** [comment]
Without a 64x64 icon (only 16 and 32 ones):
without

With a 64x64 icon:
with

**Comment by Fixer-007** [comment]
First screenshot looks much better (without 64x64), it is very smooth and nice, while second one is corrupted.

**Comment by est31** [comment]
Err sorry, I've mixed up the captions, of course its the other way around. Edited the post.

**Comment by Zeno-** [comment]
+1

**Comment by t4im** [comment]
Nice!
Wouldn't including a xbm or xpm file work, too? `#include "minetest-icon.xpm"`
Since gimp can handle those natively iirc, it could simplify things a bit.

**Comment by est31** [comment]
I've changed the PR to load from a png file instead of manually specifying it in a special header. @Zeno- re-approved via IRC pm.

**Comment by Zeno-** [comment]
Still +1 for me after the changes

**Pull request merged**
