### PR TITLE
Remove caching from getTextureDirs

### LINKED ISSUE #6655: Change of texture pack requires full restart of minetest
As of engine 24c1c2fd, that is clearly a bug.

### PR DESCRIPTION
**Pull request by numberZero**
Fixes #6655

### CODE REVIEW

**Comment by numberZero** [comment]
Note: IMO all that `static threal_local` magic should be dropped everywhere in favor of proper object-oriented approach.

**Comment by sfan5** [comment]
seems fine to me :+1:

**Comment by nerzhul** [comment]
are you sure it's not too heavy to remove caching ? how many times it's called per step ? it's a recursive directory fetch, it can be huge

**Comment by rubenwardy** [comment]
I was just looking into this, not sure it's the best idea

**Comment by sfan5** [comment]
This function is always called just once (not in a loop) or its results are cached (inside e.g. `SourceImageCache`)

**Comment by lhofhansl** [comment]
> IMO all that static threal_local magic should be dropped everywhere in favor of proper object-oriented approach.

I'll second that. I started doing that for RemoteClient, but there're many, many more instances.

On this issue... It does not seem too unreasonable to restart the client when the texture packed is changed.

**Comment by paramat** [comment]
'thread local' has been added in at least one other place, as a solution to the 'program restart needed to change setting' thing.

**Comment by numberZero** [comment]
That’s not a solution in any way. That may be considered a work-around, but it only works if the cached value is not accessed from the main thread.

**Comment by SmallJoker** [comment]
It's not just called once. Called for each texture that isn't cached yet:
https://github.com/minetest/minetest/blob/f7733f41ea36e7d4531fea61a4cd4b679514d263/src/client/tile.cpp#L119-L132
This PR isn't the optimal solution for now, caching the directories in-game makes sense and is helpful to not do useless lookups. However, we need a solution to refresh (or re-initialize later) the vector in the mainmenu. If that already happens now, then we're probably searching the bug in the wrong code snippet.

**Comment by numberZero** [comment]
> how many times it's called per step ?

About of 0. It is used mostly on load.

> caching the directories in-game makes sense
> However, we need a solution to refresh (or re-initialize later) the vector in the mainmenu.

Thus either use different threads (`thread_local`!) or use a class to store all that stuff. I can write an ad-hoc class to do that, but I certainly don’t want to increase entropy acting that way, it’s too high already. It may be better to let this wait for some refactoring.

**Comment by nerzhul** [comment]
@numberZero the problem is the setting generic ugly interface, i think we need to drop that too heavy too modular settings interface in favor or enum based k/v store specialized per variable type for core, and let the generic backend for mods.

enum FloatSetting {
FSETTING_RANGE,
FSETTING_MAX,
};

std::array<float, FSETTING_MAX> m_float_settings;

**Comment by numberZero** [comment]
Note: if you don’t mind such syntax:
```c++
enum_class(Name,
	Entry1,
	Entry2,
	Entry3, // the comma here is either mandatory or forbidden, depending on the enum_class macro definition
);

enum_array<Name, float> some_settings;
```
then some more type safety may be ensured using smth like [this](https://gist.github.com/numberZero/c3ff76f6f3009638e8b5943d5019ebff)

**Comment by nerzhul** [comment]
@numberZero sexy :)

**Pull request merged**
