### PR TITLE
Improving readibility on small areas

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by est31** [comment]
:-1: this does more harmful changes than it does good changes, and it edits mini gmp, which we only bundle.

**Comment by nerzhul** [comment]
:-1:

**Comment by est31** [comment]
I think enough reasons were given to reject this PR.

**Comment by RyDroid** [comment]
@est31 I understand that readability is not a priority, so that you reject this PR. But in what way is it harmful?

**Comment by est31** [comment]
What do you even mean with readability on small areas.

**Comment by RyDroid** [comment]
@est31 A small area could be a small screen or a small part of it (for example to work on multiple files at once, like you can do it by splitting the view in Emacs). https://www.gnu.org/software/emacs/images/teaser.png

**Pull request closed without merging**
