### PR TITLE
Update Android depends, -O3 optimization, remove old arm config

### PR DESCRIPTION
**Pull request by MoNTE48**
- Update OpenSSL (thanks @sapier, i use he patch!), Curl and SQLite3.
- Remove old arm config (Currently there are no phones that use ARMv5 or ARMv7. Almost all of them have 1 core and 256-512 RAM, it's about 2-5 FPS.)
- -O3 optimization for libs and remove -fexpensive-optimizations for Minetest (-O3 include this! Read gcc docs).

### CODE REVIEW

**Comment by est31** [comment]
It conflicts parts of #3454 (most notably the second commit).

I :+1: the sqlite changes, and the `-O3 optimization and remove old arm config` commit.

And, if @sapier agrees, we can also merge the whole PR (squashed ofc, and with nicer commit msg than "Update $filename").

**Comment by MoNTE48** [comment]
@est31, thanks, but I did not quite understand. How do I change the name of pull?

**Comment by est31** [comment]
Well, probably it can be merged as is. Just squash all changes, and give it a nice commit message.

**Comment by est31** [comment]
(and it requires a second :+1: )

**Comment by MoNTE48** [comment]
Pfft, I did it!) Unfortunately, I can not find the time to learn to work with Github :)

**Comment by MoNTE48** [comment]
Thank's https://github.com/minetest/minetest/issues/3658
I completely forgot about it!

**Comment by est31** [comment]
Can you squash the commits?

**Comment by est31** [comment]
:+1: if squashed

**Comment by MoNTE48** [comment]
@est31, done. But there is the second developer to confirm it, no one cares. So I created my fork to my changes are not ignored. ;)

**Comment by ShadowNinja** [comment]
LGTM.

**Comment by paramat** [comment]
096a01ffef032a11239bd97e548a9ebb3c6add4a

**Pull request closed without merging**
