### PR TITLE
Make some improvements to minetest.after

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
  - I wanted to try addressing some problems with `minetest.after`.
- How does the PR work?
  - Jobs are now stored in a heap data structure. I saw this suggested on one of the IRC channels, I think by @appgurueu. Without this change, inserting a job is `O(1)` complexity and removing an expired job is `O(n)` complexity (worst case; `n` is the number of jobs.) With the change, both insertion and deletion are `O(log n)` complexity (worst case.) I haven't found the new way to be faster when used with actual mods. In fact, it may be a microsecond or two slower. It should be noted that, as the number of jobs expiring at once approaches the total number of jobs, the complexity of the old way of removing expired jobs approaches `O(1)`. However, it seems like the number of jobs expiring at once is usually pretty small. The new heap-based method is preferable because it has a better complexity per-job on average and is thus more scalable. I have found it to be faster when a situation is induced such that there are many pending jobs only a few of which expire per globalstep.
  - The number of allocations per call to `minetest.after` has been reduced from 3 to 1. Firstly, the `cancel` method is now dispatched using a shared metatable, and the job table itself is returned. Secondly, the callback arguments are stored directly in the job table. I saw this technique used in @appgurueu's modlib.
  - Arguments are now reliably passed to the callback. Before, if one of the arguments was `nil`, no arguments after it would be passed. This was a bug.
  - There are now unit tests for `minetest.after`.
  - `minetest.after` now throws an error when given NaN.
  - Jobs should now expire in chronological order, even when they expire in the same globalstep. This is just due to the structure of the heap.
- Does it resolve any reported issue?
  - Not that I know of.
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
  - It makes the Lua API more flexible (removing one of its potential performance limitations,) which might relate to something on the road map.
- If not a bug fix, why is this PR needed? What usecases does it solve?
  - It's partially a bug fix. Again, it also makes the API more flexible.

## To do

This PR is ready for review, although maybe it could use more testing.

## How to test

There are unit tests for the API now.

It's important to test this with actual mods. I haven't seen any issues, but they might be hard to spot. It would be nice to test it with mods that made very heavy use of the API in order to test performance accurately.

To test performance, first apply this patch:

```patch
diff --git a/builtin/common/after.lua b/builtin/common/after.lua
index 85169cb70..126c0ed3e 100644
--- a/builtin/common/after.lua
+++ b/builtin/common/after.lua
@@ -65,6 +65,8 @@ end
 local time = 0.0
 local time_next = math.huge
 
+local n, avg = 0, 0
+
 core.register_globalstep(function(dtime)
 	time = time + dtime
 
@@ -72,6 +74,8 @@ core.register_globalstep(function(dtime)
 		return
 	end
 
+	local before = core.get_us_time()
+
 	-- List of jobs that have to expired; to be built.
 	local expired = {}
 
@@ -93,6 +97,13 @@ core.register_globalstep(function(dtime)
 			func(unpack(job, 1, job.n_args))
 		end
 	end
+
+	local after = core.get_us_time()
+
+	local cost = (after - before) / #expired
+	n = n + 1
+	avg = (avg * (n - 1) + cost) / n
+	core.chat_send_all("Avg. cost per expired job: " .. avg)
 end)
 
 local job_metatable = {__index = {}}
```

You can use this mod to continuously create a bunch of jobs that do nothing:  [test_after.tar.gz](https://github.com/minetest/minetest/files/7893528/test_after.tar.gz)

### CODE REVIEW

**Comment by appgurueu** [comment]
If I'm not missing something, you forgot to mention that it also fixes `minetest.after` cutting off at `nil`s.

> Jobs should now expire in chronological order, even when they expire in the same globalstep. This is just due to the structure of the heap.

Generally a preferrable, but unfortunately a breaking change. See https://github.com/minetest/minetest_docs/pull/28/ - calling `minetest.after(0, func)` within `minetest.after` should defer something to the next step - which is frequently relied on by mods.

I also believe many mods might rely on the reverse order of execution - imagine a mod requiring it's `minetest.after` to run before that of another mod, for instance if an after-loop is used instead of a globalstep. This is probably the trickiest to fix - during the execution of jobs, jobs should only be queued, and inserted in the heap the next step in reverse order.

Finally, cancelled jobs *could* be removed from the heap (with significantly more effort though). Most likely not worth it.

**Comment by TurkeyMcMac** [comment]
Because the code collects all expired jobs then executes them, `minetest.after(0, func)` still defers execution until the next step.

I thought about removing cancelled jobs from the heap, but that seems like it would be `O(n)` complexity, so I decided against it.

I'll try to restore reverse execution. Hopefully doing so does not incur a significant performance penalty.

**Comment by appgurueu** [comment]
> I thought about removing cancelled jobs from the heap, but that seems like it would be `O(n)` complexity, so I decided against it.

A naive implementation indeed. But if each job stores it's index, removing is as simple as swapping the element with the last element and then deleting the last element, heapifying up or down depending on whether the new element at the index is less than the previous one. I recently implemented such a thing [somewhere else](https://github.com/TheAlgorithms/Lua/commit/f4203cf78c1681c19ca5dbf877577094f3c19d77) (not storing the index in the table though) and will probably use it for modlib.

**Comment by TurkeyMcMac** [comment]
True. It would increase the complexity of the code to put indices into the job tables and keep them updated. The increased complexity might be worth it if cancelling jobs is a common occurrence.

**Comment by TurkeyMcMac** [comment]
I have done some testing, and it seems that `after` loops do not reliably execute in reverse order of registration. To run the test, add this code to a mod:

```lua
local n = 0
local function p(m)
	if n < 20 then
		print(m)
		minetest.after(0, p, m)
	end
	n = n + 1
end
minetest.after(0, p, "a")
minetest.after(0, p, "b")
```

I ran this code in a devtest world, and the output was something like this:
```
b
a
a
b
a
b
a
b
...
```

When other jobs expire, they may mess up the order of the `after` loops.

**Comment by appgurueu** [comment]
> I have done some testing, and it seems that `after` loops do not reliably execute in reverse order of registration using the old implementation. To run the test, add this code to a mod:

Then you're free to break this. Looks fine to me!

**Comment by TurkeyMcMac** [comment]
I'm going to close this in favor of https://github.com/minetest/minetest/pull/12043, which has better guarantees and better complexity in some cases.

**Pull request closed without merging**
