### PR TITLE
Leaner minimap arrow makes it easier to see the direction

### PR DESCRIPTION
**Pull request by JRottm**
The arrow symbolizing the player in the square minimap looks almost like a
triangle, making it a bit hard to see which direction it is currently
pointing in when in a hurry.

Redraw it leaner, pointier. Colors unchanged. I'm NOT very skilled at gimp
or graphics design, there is definitley still room for improvement if
someone feels up to it.

### CODE REVIEW

**Comment by SmallJoker** [comment]
From my point of view you should remove the bottom-middle edge to make it look less squashed like it is right now. It will result in a triangle, where you have a noticeable shorter side and two longer ones, which may already be an improvement compared with the current texture.

**Comment by JRottm** [comment]
Hmmmm, no, sorry, I do like the indentation in the bottom edge. I deliberately made it even more pronounced than it was originally, because I find that it helps recognizing the direction.

Yes, I know the arrow appears smaller than before, because it's narrower, but for me that's good, because it will block less of the map. I even tried a hole in the arrow so you could see the area of the map where you are standing, but that didn't work out.

I do like my arrow as it is. (By writing "room for improvement" in the commit message I meant if someone wants to do a completely different design, like a crosshair thing or some circle with a spike (like a "Q") and a different color scheme I won't feel offended if someone fires up GIMP and draws something better.)

**Comment by JRottm** [comment]
I did try this, but it sucked when I put it in the minimap:
player_marker

**Comment by paramat** [comment]
The PR is an improvement, the current arrow is too fat.

**Comment by paramat** [comment]
Could you change it to indexed colour instead of RGBA? We try to use indexed if possible.
Does anyone know if this texture needs to be 512x512 instead of smaller? Does smaller (less empty transparent space) work?

**Comment by paramat** [comment]
In a world composed of red nodes this could become hard to see, maybe it needs a high-contrast and thicker border?

**Comment by JRottm** [comment]
> change it to indexed alpha colour instead of RGBA?

Tried that. Indexed means a pixel is either transparent or not, no gradual fade at the border. This means the white border can't extend past the arrow itself, which makes the white border thinner.

> know if this texture needs to be 512x512

Yes, it does. I tried to make it smaller, then it gets stretched to cover the whole minimap again, resulting in a **really** huge arrow. The space saving would be only 1 KB anyway.

> In a world composed of red nodes ...

Hmmm, yes, but it still has to look good. If I make more white then I have less red, harder to see in snow or I have a too huge arrow again. I tried something entirely different, as I posted above, but that looked crappy, too.

**Comment by paramat** [comment]
Ok :+1:

**Comment by JRottm** [comment]
Believe me, I tested **many** arrows before I posted my PR, and this is the one I *personally* liked best. Of course, if someone has a different taste feel free to fire up that GIMP.

**Comment by JRottm** [comment]
**Updated branch again.*** Reconsidered @paramat's comment about red background and made white outline a teeeeensy bit more pronounced. Hope to make everyone happy. :-)

Also note about RBGA and size: the new image is still a few bytes smaller than the original one was.

**Comment by paramat** [comment]
Nice :+1:

**Comment by JRottm** [comment]
Is there anything I'm still expected to do before this can be merged??

**Comment by paramat** [comment]
You can your image credits here https://github.com/minetest/minetest/blob/master/README.txt#L411
It seems many minimap texture and other texture credits are missing from there.

Core devs will then merge this PR once they get a chance (i will as soon as it's ready).

**Comment by paramat** [comment]
I can add your credit on merge.

**Comment by paramat** [comment]
7cd1251d83bd66a73fa7e9b676e6fe30e91e613a

**Comment by JRottm** [comment]
> image credits here [...]

I wouldn't claim "image credits" for a stupid arrow, just a few pixels high. It's not the Mona Lisa or something - but anyway...

> I can add your credit on merge.

Thanks @paramat.  :-)  :-)

**Pull request closed without merging**
