### PR TITLE
Night vision

### LINKED ISSUE #6509: Feature Request: Night Vision.
Would it be possible to add a player override setting that draws everything client-side in FULL brightness when enabled ?  This way we could toggle proper night vision per player which would make an amazing feature in-game :)

### LINKED ISSUE #8890: Allow mods to customize how light looks per player
It would be cool if mods were able to change how the lighting looks per player.

For example, if you enter some kind of hell dimension, you might want it to have some level of ambient light, so even the darkest light level would look a dim orange - or if you're wearing night vision goggles, all light levels would look bright.

This could be accomplished either by simply allowing mods to define four 'base colors' (for darkness, 100% artificial light only, 100% natural light only, and 100% both), or allowing mods to provide an array or image of what color should be used at every single possible light level.

This wouldn't provide support for true colored lighting, but it might help to give some atmosphere to different worlds or dimensions.

### PR DESCRIPTION
**Pull request by x2048**
This is early work to enable ambient light in caves and features like night vision in the games. Fixes #6509 and fixes #8890.

This is shader-specific implementation, but it should be possible to add similar code for fixed rendering pipeline.

## Plan
  - [x] Collect feedback
  - [x] Add server-side API to control the ambient brightness
  - [x] Add ambient color, see #8890
  - [ ] Integrate with set_lighting
  - [ ] Rebase
  - [ ] Add support for particles

This PR is Work in Progress

## How to test

* Install WorldEdit mod
* Start any game in single player get all privileges and go underground (fly + noclip).
* Type `//lua minetest.get_player_by_name('singleplayer'):set_ambient_light({brightness=0.5, color_tint="#ffd480"})`.
* You should now see all the caves with an orange tint.

### CODE REVIEW

**Comment by kilbith** [comment]
That should belong to a postprocessing framework.

**Comment by hecktest** [comment]
> That should belong to a postprocessing framework.

Sort of. For that to work you still need an unlit buffer.
But couldn't this live entirely in the shader? I remember people cheating in darkness by editing their shaders to just not use the lighting.

**Comment by x2048** [comment]
So you would like to wait for a new rendering pipeline to implement this feature, right?

Regarding shaders, first they are optional in Minetest, and lighting is not really done in shaders today, but glsl code has enough info and access to ruin lighting and cheat out, yes :)

Are there plans to drop support for fixed pipeline rendering?

**Comment by hecktest** [comment]
Not really but I'd rather not see it pollute too much c++ code, it's enough to just add a uniform for ambient light intensity and API for setting it. That should do until there's a general purpose Lua API for setting uniforms.

I do have plans for dropping support for the fixed pipeline and it's likely to happen, the set of machines that can run Minetest comfortably while not supporting at least OpenGL 2 is basically empty.

If you do wish to implement this in a way that supports the current fixed pipeline, you'd do me a big favor by making it easy to revert the changes once possible.

**Comment by x2048** [comment]
So, I've moved the logic into the shaders. The control parameters are brightness and color tint. Brightness essentially scales down the impact of MT light on the rendered output, and color tint is simply a factor applied to each rendered pixel.

The formula is:

    output color shade = (1 - (1 - input color shade from MT light levels) * (1 - brightness)) * color_tint

I've also added Lua API for it, just to try out. This is a draft, and feedback is welcome.

**Comment by hecktest** [comment]
Looks alright now, I'd just rename it from "ambience" to "ambient light" in code and API to make it unambiguous what this actually does.

**Comment by hecktest** [comment]
I just had an idea, perhaps you'd be willing to try it out: (Not mandatory, just a thought)

Since this feature now utilizes shaders, we could support specifying a ramp texture to control the whole node light range instead of just a lerp from ambient-or-0 to white. This would not only allow ambient light and night vision, but also provide a decent alternative for the botch job we call tonemapping.

**Comment by erlehmann** [comment]
> I do have plans for dropping support for the fixed pipeline and it's likely to happen, the set of machines that can run Minetest comfortably while not supporting at least OpenGL 2 is basically empty.

As mentioned on IRC some days back, **this is false**. I am writing this on a Thinkpad T60 which has been able to run Minetest for a long time and I have a bunch of other machines like that. While I do understand the benefits that shaders can bring, I suspect you have absolutely no idea on what kind of hardware people still run Minetest and develop mods.

Btw, it is not just me: Friends of mine reacted to the announcement of “dropping support” – instead of implementing a proper rendering abstraction that keeps older machines working and makes it easier for new machines – wtih a) astonishment and b) swearwords.

**Comment by erlehmann** [comment]
> This is shader-specific implementation, but it should be possible to add similar code for fixed rendering pipeline.

@x2048 what do you think of the BrightNight cheat implemented by @EliasFleckenstein03 ? Could you use that?

https://repo.or.cz/waspsaliva.git/commitdiff/f1760622ec4708decfe34e268a63a9d83d2978a7?hp=2675bcca1a3e8c59475ccb29d1afa9e19489a686

**Comment by x2048** [comment]
@erlehmann Can you point me at the IRC discussion?

**Comment by erlehmann** [comment]
@x2048 which IRC discussion?

**Comment by x2048** [comment]
@erlehmann 

> > the set of machines that can run Minetest comfortably while not supporting at least OpenGL 2 is basically empty.

> As mentioned on IRC some days back, this is false.

This one if possible.

**Comment by x2048** [comment]
> what do you think of the BrightNight cheat

Looking at the patch, Elias' changes are pretty basic, manipulating day/night ratio and will not work in caves or nether.

I go deeper and manipulate the actual color of vertices, which allows e.g. "barely visible" light in caves. I won't be able to use his cheat.

**Comment by erlehmann** [comment]
> @erlehmann
> 
> > > the set of machines that can run Minetest comfortably while not supporting at least OpenGL 2 is basically empty.
> 
> > As mentioned on IRC some days back, this is false.
> 
> This one if possible.

IIRC, the IRC discussion was basically @sfan5 and @celeron55 explaining to me why people want to leave fixed pipeline behind and write shaders instead. I think I understand it now. I doubt anyone disputes that Minetest is – among other things – the block game engine that runs on computers that are not supported by Minecraft.

Something that is important to keep in mind: It is not enough to look at what the vendor advertises for a setup to figure out what is actually working in Minetest. For example, I got abysmal OGLES performance (5 to 7 frames) and bad rendering errors on a machine on which I also get 25 to 27 frames with OpenGL 1.4. Both are apparently “supported”, but one choice is unplayable.

**Comment by x2048** [comment]
@erlehmann 
I found [this](https://irc.minetest.net/minetest-dev/2021-09-09#i_5873210) and [this](https://irc.minetest.net/minetest-dev/2021-09-09#i_5873030).

From the conversations it sounds like the core devs have settled on the decision to drop support for the fixed pipeline, so now would be the right time to fork the client.

@sfan5 @Warr1024 Can you confirm?

**Comment by sfan5** [comment]
From discussions and responses I have seen dropping support for OpenGL <2.0 is a done deal.

**Comment by x2048** [comment]
@sfan5  @rubenwardy This PR has reached a certain functional state: ambient brightness and color can be adjusted via Lua API when the client has shaders enabled. I'd like to remove the WIP label and collect some feedback on when needs to be done to get this PR in. Thank you.

**Comment by AFCMS** [comment]
I am getting a compilation error:
image

**Comment by x2048** [comment]
@AFCMS Fixed now, thank you.

**Comment by AFCMS** [comment]
OK, will checkout soon!

**Review by AFCMS — COMMENTED** [review]
- particles are not affected by brightness
- lightning affect block colors

mcl2:
screenshot_20220122_200255

mcl2 at night:

screenshot_20220122_200021


mcl2 with brightness 0.3 at night:
screenshot_20220122_200629

The grass block color is way too much affected (I didn't applied any color tint)

In devtest, this is less obvious. (Maybe because the grass block from mcl2 use color palettes?)

**Comment by x2048** [comment]
@AFCMS I found that desaturation is caused by the way we encode vertex color: each of the RGB channels encodes both color and light values, and A encodes natural/artificial light balance. As a result, nodes having low precomputed light also have low saturation.

I made an experiment and encoded vertex colors in HSV, which allowed separate light information into a different channel. This allows to preserve saturation and get night vision close to natural daylight.

The problem is that it spans well beyond the shaders and changes how we encode light and color in the meshes, possibly leading to errors.

**Comment by x2048** [comment]
Here is how it looks in experiment:

image

**Comment by erlehmann** [comment]
I think that the desaturated look is a bit ugly, but looks much more like actual night vision.

Because humans indeed have a hard time seeing colors in the dark.

**Comment by x2048** [comment]
Fixed in shaders, looks like this now:
image

**Comment by AFCMS** [comment]
> Fixed in shaders, looks like this now (brightness 0.4): image

Thanks! That looks amazing!

**Comment by rubenwardy** [comment]
Needs rebase

Also, you edited your description to be "ready for review" but it still had a WIP label so removed that

**Comment by x2048** [comment]
Changed back to WIP and added tasks to do.

**Comment by x2048** [comment]
Related to #12338, #12180, #12341

**Comment by kilbith** [comment]
Sorry but this still isn't the right approach to do night vision. The right one is passing trough postprocessing. You are doing the same mistake as tonemapping here...

**Comment by x2048** [comment]
Yes, I know this is not ideal. This is just what I could do with the current rendering pipeline.

**Comment by x2048** [comment]
Closing this PR for now

**Pull request closed without merging**
