### PR TITLE
Improve custom drowning values

### PR DESCRIPTION
**Pull request by BlockMen**
Allows e.g. more complex suffocation in nodes. The amount of breath lost is now specified by drowning value, while the damage is set via damage_per_second.

Explained:
If drowning = `<x>` and damage_per_second = 0 its behaves like now.
If drowning = 0 and damage_per_second = `<y>` its behaves like now.
If drowning = `<x>` and damage_per_second = `<y>` you are loosing x bubbles air every 2 seconds and get damage of y each second when breath == 0

### CODE REVIEW

**Comment by nerzhul** [comment]
Jenkins build passed

**Comment by PilzAdam** [comment]
This needs to be backwards compatible.

**Comment by BlockMen** [comment]
@PilzAdam done

**Comment by PilzAdam** [comment]
@BlockMen nobody likes it when stuff breaks after upgrading the engine; that's why we have and want backwards compatibility.

**Comment by BlockMen** [comment]
@PilzAdam Well, thats in general correct, but this wouldnt break a world neither it would make the game unplayable.

And what is your solution here? Are you suggesting a new nodedef field or how would you make it backwards compatible?

**Comment by PilzAdam** [comment]
I guess your current workaround is good enough.

**Comment by BlockMen** [comment]
@all don't merge, there is some issue when standing in lava and drowning in someliquid above.

**Comment by MT-Modder** [comment]
Could you add a ```drowning_speed``` field so you can do this:

if drowning = ```<x>``` and drowning_speed = ```<y>``` then you lose ```<x>``` bubbles every ```<y>``` seconds.

Instead of the fixed 2 seconds.

**Pull request closed without merging**
