### PR TITLE
Fixed comment

### PR DESCRIPTION
**Pull request by crazyBaboon**
Fixed comment as finalColorBlend() does not exist in the code base.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Somewhat trivial. Are there any further issues (code style etc) with the code that could be corrected?

**Comment by ClobberXD** [comment]
Very trivial indeed, but I think this should be merged as-is without extra irrelevant changes, just to make the PR non-trivial :)

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
There are several more improvements that can be made:
* Spaces after // in all comments.
* Improve sloppy English and grammar in most comments.
* Use full stops in multiline comments.
* Don't use them in single line comments.

**Pull request merged**
