### PR TITLE
Modify default font appearance.

### PR DESCRIPTION
**Pull request by everamzah**
Increase font size by 1.  ~~Make shadow opaque.~~

### CODE REVIEW

**Comment by Calinou** [comment]
Sounds good, although I would like to see a screenshot comparison (before-after).

**Comment by paramat** [comment]
Screenshots please.

**Comment by everamzah** [comment]
It really all depends on the user's DPI, I think.  Nonetheless, here's two screenshots at 96 DPI:

^ With these changes.

^ Traditional settings.

On the one hand, increasing the font size reduces the amount of text visible on the screen at any given time.  On the other hand, it's easier and more pleasant to read, in my opinion.

The thickening of the font shadow also increases the font's visibility.

**Comment by everamzah** [comment]
# 72 DPI
--
16a
^ With these changes.
15a
^ Traditional settings.

**Comment by paramat** [comment]
Increasing font size may be a problem because we already have text extending past the boxes.

**Comment by everamzah** [comment]
screenshot_20160915_210021
^ With these changes.
screenshot_20160915_210148
^ Traditional settings.

**Comment by paramat** [comment]
I support the opaque shadow, helps against bright sky or snow etc.

**Comment by ExeterDad** [comment]
Chat font is a huge improvement IMO. I struggle with default chat and often tune it out as it's too much bother to decipher while playing.

**Comment by paramat** [comment]
Trying it out, on my setup anyway i do prefer font size 16. 15 is ok but perhaps just very slightly too small.

**Comment by paramat** [comment]
And for me it doesn't cause text to exceed text boxes apart from a few cases where it already did.

**Comment by paramat** [comment]
Ok i like it :+1:

**Comment by sofar** [comment]
:+1:

I've had my font size set to 16 by default for a long time myself :)

**Comment by Fixer-007** [comment]
Maybe in chat, but not in default window.

**Comment by SmallJoker** [comment]
The font size change is fine - using 19 here for a long time.
What I don't like is the high contrast with the new shadow alpha of 255, this should be left to the old value.

**Comment by celeron55** [comment]
I personally have used font_size=18 for a long time; we definitely could go higher than 16.

**Comment by paramat** [comment]
With in-game text the high contrast is a little hard on the eyes. Perhaps a lower value for shadow? Or left as it is.

**Comment by paramat** [comment]
Font shadow alpha 193 is good.

**Comment by everamzah** [comment]
So change this PR to font_size = 16, and keep font_shadow_alpha at its current value of 128?  (It should be 127, IMO.)  That way this PR introduces a singular change?

**Comment by paramat** [comment]
I think 191 is ideal but what do others think? There's some discussion on IRC dev.

**Comment by everamzah** [comment]
Shadow alpha is now 127.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
679c8de63ffb7119f2b99b00883bc959f5917da4

**Pull request closed without merging**
