### PR TITLE
Fustrum cull blocks in updateDrawlistShadow

### PR DESCRIPTION
**Pull request by lhofhansl**
Add compact, short information about your PR for easier understanding:

I noticed that updateDrawlistShadow is slower than updateDrawlist (with the loops culler).
That should not be the case since they are doing essentially the same amount work.

Turns out that we can fustrum cull the blocks for shadows as well. (Before or after the shadow distance checks made no difference). @x2048 

## To do

This PR is Ready for Review.

## How to test

Pick a reasonably large viewing_range (500+). Turn on the "loops" culler (`set occlusion_culler loops`).
Load any map, look/fly around. View `updateDrawlist` and `updateDrawlistShadow` in the debug view and note how they mostly take the same time (xxxShadow will be slightly faster most of the time.)

### CODE REVIEW

**Comment by Desour** [comment]
(Additional fine-grained frustum-culling can happen `renderMapShadows`, similar to `renderMap`.)

This doesn't really work. Try looking away from (or orthogonal to) the sun. The shadow casters behind you (if in another block and >30+blocksize nodes behind any frustum plane) are culled away. You can see this especially well with a sun near the horizon.

What we could do instead is find a different convex 3d polytope.
E.g.. the frustum planes that have normals pointing away from the sun dir are fine to keep. And one could take all the corners of the frustum, project them on a plane perpendicular to sun dir, and then make a convex 2d polytope around these points, and extend this 2d polytope to 3d. (Sorry, I can't really explain this without visualisation (which I also can't really do for people not using the same head).)

**Comment by lhofhansl** [comment]
@Desour This is exactly the same that happens with the normal drawlist. Why would this be handled differently?

**Comment by lhofhansl** [comment]
I see now. You are right. Closing.

**Comment by Desour** [comment]
(I'd have an example but I'd need to make screenshots. You don't require it anymore anyways.)

I've tried to illustrate the clip planes I described earlier:
shadow_frustum

**Comment by lhofhansl** [comment]
@Desour I merged #13383 . Wanna do PR for your changes?

> But it doesn't seem to have a significant affect on performance in my tests.

That is probably the case. When I played (incorrectly) with the frustum culling, I got less of an improvement than #13383.

(Thanks, btw, for shaping my thinking on that!)

**Pull request closed without merging**
