### PR TITLE
Korean

### PR DESCRIPTION
**Pull request by Sorichan**
This is not translated perfectly
I am in the process of translation
but I want to check this file application

### CODE REVIEW

**Comment by est31** [comment]
Can you use the online weblate interface for that, as linked in  #4690 ?

PRs are not supposed to be used for translations.

Weblate will be imported into this place in the future automatically.

**Comment by Sorichan** [comment]
I first use github yesterdeay so I dont know modification #4690 
so I put up this file one more time **sorry**
but PR what you mean is public relation??

I dont PR
I just want to play korean so I try translation and I want to check " Is this file can apply? "
but because of my bed enlish I cant translation perfectly. so I add text file 
URL https://hosted.weblate.org/projects/minetest/minetest/ko/

Because I want to perfect translation in minetest

**Comment by est31** [comment]
PR is "pull request", which is what this thread and #4690 both are.

**Comment by Sorichan** [comment]
I dont know computer word
how use online?

**Comment by Sorichan** [comment]
oh I see  Im so stupid sorry
how committed with weblate ?
I just know only committed with Github

**Pull request closed without merging**
