### PR TITLE
Add search to advanced settings

### PR DESCRIPTION
**Pull request by rubenwardy**
screenshot_2016-11-23_23-17-06

* After search, the best result is selected
* Clicking search or pressing enter in the text field causes the next result to be selected (like F3). This loops.
* Keyword based, keywords can appear in any order or place and don't have to appear

### CODE REVIEW

**Comment by sofar** [comment]
This is how the server tab search should look too :(

**Comment by kaeza** [comment]
Tested. Works perfectly.

:+1:

**Comment by Zeno-** [comment]
I don't review Lua code very often so I won't. But for the concept, :+1: from me!

**Comment by kaeza** [comment]
In case before someone asks, and it is not clear enough, this supports localized strings, so non-english speakers may search settings in their native language.

Looking at the code, the only nits I have are the use of `string.find(x, ...)` instead of `x:find(...)`, and probably how the `elseif` block at [line 372](https://github.com/minetest/minetest/pull/4806/files#diff-5e304e32cb9b7555cb9d59001b444e2cR372) is split. Both of those are minor issues for me and it's fine either way.

**Comment by Wuzzy2** [comment]
Does it support pressing enter?

**Comment by rubenwardy** [comment]
Yes

**Comment by Fixer-007** [comment]
This is much needed, advanced settings are insanely complex.

**Comment by est31** [comment]
From reading the code it seems that pressing enter multiple times doesn't neccesarily go through the list of matching search results, right? That should be added IMO.

**Comment by octacian** [comment]
So.. any reason why this hasn't yet been merged? Seems to work alright to me, need to test again though. This is definitely something MT really needs though, in the server list too. +1

**Comment by sfan5** [comment]
@octacian 

it's called <b>ＦＥＡＴＵＲＥ ＦＲＥＥＺＥ</b>

**Comment by octacian** [comment]
@sfan5 right, I forgot about the freeze. I doubt I'll actually be really used to it till at least the 0.4.16 freeze :rotfl:

**Comment by rubenwardy** [comment]
Rebased

> From reading the code it seems that pressing enter multiple times doesn't neccesarily go through the list of matching search results, right? That should be added IMO.

Added as separate commit to make it easier to review. It should be squashed when merging

**Comment by rubenwardy** [comment]
This PR removes the ability to use `enter` to open/edit a setting, unfortunately. I'm not sure how you'd fix that

**Comment by DS-Minetest** [comment]
i dont think, its a big problem to lose the ability to open a setting with enter (i didnt even know that it is so)
the most people control the settings with mouse, not with keyboard since you have to use everywhere else in the main menu the mouse _, there would be too many settings to scroll through_ and you cant open the yellow setting tabs (with the + at the front) with enter

**Comment by MarkuBu** [comment]
Does search only works for localized strings or also for the technical names? Sometimes I don't know how it is translated and it is easier to search for the original text

**Comment by DS-Minetest** [comment]
This has no `WIP` label, **ＦＥＡＴＵＲＥ ＦＲＥＥＺＥ** is over and the feature would be very useful.
So, why isn't this merged?

**Comment by rubenwardy** [comment]
> This has no WIP label, ＦＥＡＴＵＲＥ ＦＲＥＥＺＥ is over and the feature would be very useful.
So, why isn't this merged?

Because no other core devs have reviewed it

> also for the technical names

yes. It searches in technical name, readable name, and description

**Comment by Zeno-** [comment]
:+1: from me for concept. If a person (even if they're not a core dev, but one of the long-term contributors) can review the Lua then I think this should be merged.

**Comment by Wuzzy2** [comment]
Looks good. I would make another enter press when the selected entry is the last one make select the first entry again.

**Comment by rubenwardy** [comment]
Now a keyword based search is used (like the server search) and the best result is auto selected, rather than the first

**Comment by sofar** [comment]
:+1:

code is simple, works as intended. I think this is ready for merge (for a while now).

**Pull request merged**
