### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Sorichan**

### CODE REVIEW

**Comment by sofar** [comment]
Don't we have a translation portal for this type of change?

*looks*

that's right: https://hosted.weblate.org/projects/minetest/minetest/

**Comment by est31** [comment]
Please use weblate for that. Also, have you tried the game with korean? Does it work?

**Comment by sfan5** [comment]
@est31 korean works if you replace the .ttf with a font that supports korean

**Comment by Sorichan** [comment]
I was use this site https://hosted.weblate.org/projects/minetest/minetest/ko/
I just translation file down and put up here 
I dont know why dont work...

**Pull request closed without merging**
