### PR TITLE
Make message times for sqlite busy condition configurable

### PR DESCRIPTION
**Pull request by Rogier-5**

### CODE REVIEW

**Comment by Rogier-5** [comment]
Update: fixed typo: added a missing '=' in minetest.conf.example

**Comment by sofar** [comment]
I have a hard time with commit messages this terse. Can you provide some motivation for adding the extra types in your first commit? If someone later reads the commit log, then it lacks any coherence or relation.

Just say something like "These are required to make sqlite busy handler parameters configurable in a subsequent patch." in your first commit.

As for the second commit, similarly, you don't provide any motivation why this is desired or needed, and I'm having a hard time understanding why you wouldn't just patch the default values and provide us with the motivation for choosing the new values in a commit message.

**Comment by Rogier-5** [comment]
> I have a hard time with commit messages this terse. Can you provide some motivation for adding the extra types in your first commit? If someone later reads the commit log, then it lacks any coherence or relation.

OK. Updated the commit message

> As for the second commit, similarly, you don't provide any motivation why this is desired or needed, and I'm having a hard time understanding why you wouldn't just patch the default values and provide us with the motivation for choosing the new values in a commit message.

Updated the commit message.

Also: est31 [indicated](https://github.com/minetest/minetest/pull/3481#issuecomment-166889909) that he preferred them to be configurable.

**Comment by sofar** [comment]
Excellent. And indeed if someone requests something, that in itself is perfectly valid to put into a commit message ;^)

**Comment by ShadowNinja** [comment]
Is this actually useful?  It seems like it adds a lot of code that nobody will ever use.
Even if one or two people will use it it might be better to just have them change the constants and recompile.

**Comment by est31** [comment]
Well, idk, probably @ShadowNinja is right. Its fairly easy to change them already, but I more doubt there is any use case to change them.

**Comment by nerzhul** [comment]
i agree with @ShadowNinja those options are dangerous for users and don't need to have a configuration for that. Constant modification is better.

**Comment by ShadowNinja** [comment]
Closing as me and nerzhul now oppose it, and est31 is at least neutral.

**Pull request closed without merging**
