### PR TITLE
Minetest SDL2 Irrlicht backed [WIP]

### PR DESCRIPTION
**Pull request by nerzhul**
Add compact, short information about your PR for easier understanding:

- Use our own irrlicht fork backed by SDL2 only in order to improve our portability & system user events support

## To do

This PR is a Work in Progress

- [ ] Make window rendering work*
- [ ] Handle SDL events

## How to test

Build the custom irrlicht from https://github.com/minetest/irrlicht/pull/9 MR

### CODE REVIEW

**Comment by nerzhul** [comment]
more cleanups may be needed on the X11 & windows portability part, but if you compile it in the current state will the irrlicht library it should work fine. I may continue to work on the irrlicht part in order to have cursor & proper key mapping

**Comment by TheBrokenRail** [comment]
Will there be a CMake option to disable the SDL stuff if you want to use mainline Irrlicht or ``ogl-es`` Irrlicht?

**Comment by sfan5** [comment]
We'll likely do more fixes to Irrlicht in the future so using mainline will not be supported.
A solution has to be thought of for `ogl-es` (considering we also need it for android).

**Comment by nerzhul** [comment]
the sdl stuff is not related to any GL (open gl or GL es), it's just the portability layer and inputs
the GL part is always on irrlicht where SDL window is exposed as a GL surface

**Comment by rubenwardy** [comment]
> the sdl stuff is not related to any GL (open gl or GL es), it's just the portability layer and inputs
> the GL part is always on irrlicht where SDL window is exposed as a GL surface

Support for OpenGL ES requires a different branch of Irrlicht, not the master branch. Any changes you'll make won't be in the og-es branch unless you port them across, and it would be good if things where in a single branch instead

**Comment by TheBrokenRail** [comment]
> > the sdl stuff is not related to any GL (open gl or GL es), it's just the portability layer and inputs
> > the GL part is always on irrlicht where SDL window is exposed as a GL surface
> 
> Support for OpenGL ES requires a different branch of Irrlicht, not the master branch. Any changes you'll make won't be in the og-es branch unless you port them across, and it would be good if things where in a single branch instead

I'm pretty sure the ``ogl-es`` branch supports regular GL as well. So you could just use that for everything. Especially since I think SDL2 supports Android.

**Comment by TheBrokenRail** [comment]
Just make sure to support touch events.

**Comment by rubenwardy** [comment]
Closing as WIP with no progress (and not much here anyway)

I would like to see this done, as it'll make input support better

**Pull request closed without merging**
