### PR TITLE
API lua get max lag

### PR DESCRIPTION
**Pull request by Dumbeldor**
#1259

### CODE REVIEW

**Comment by rubenwardy** [comment]
What are the usecases?

**Comment by nerzhul** [comment]
@rubenwardy if you look at #1259 permits to sync lag and show it in mods using HUD, for example

**Comment by sofar** [comment]
Lag makes sense from a client, but not from a server - what lag is the server seeing here? the slowest client? What if I have 20 players on the LAN and one using his phone from the cook islands?

**Comment by SmallJoker** [comment]
How about using the UDP RTT value from the client itself here?

**Comment by sofar** [comment]
@smalljoker does the *server* even see the client RTT value?

**Comment by sofar** [comment]
I think this is a red herring.

lag value has no meaning to the server. It means a *ton* to the client.

I'd say, let's drop this patch and make one for CSM instead, which is what I think you want.

**Comment by nerzhul** [comment]
no server never see RTT it's a pure connection attribte which is not exposed to session

**Comment by nerzhul** [comment]
@sofar an interesting use case can be Lua timer adjustements due to lag for a high level code

**Comment by sofar** [comment]
@nerzhul can't csm mods already rely in `dtime` and get accurate (enough) timing?

**Comment by nerzhul** [comment]
You can use dtime for current lag on this loop step yes

**Comment by orwell96** [comment]
The point in this is that it shows the server load.
max_lag is the time the server required longest to complete a server step. If this value is shown in a HUD, players can judge whether lag problems are on the server side (max_lag is high) or in their internet connection (their RTT is high)
An unpublished mod of mine shows the max_lag in the HUD, extracting it from the status. I find it very useful.
Indeed, Mods could track the value themselves analysing the dtime, but having a way to read this value from the engine is useful.

**Comment by nerzhul** [comment]
closing, CSM seems to be the best idea

**Comment by Fixer-007** [comment]
Sooooo?

**Pull request closed without merging**
