### PR TITLE
Set y-speed to zero if touching ground

### LINKED ISSUE #10543: get_player_velocity() inconsistently returns non-null vector for static player
##### Summary

`player:get_player_velocity()` returns non-null vector even if the player is not moving at all and touching ground (negative Y-component), see [this video](https://youtu.be/AGh4-vq5_Xc) - other times, it returns a constant null vector.

##### Steps to reproduce

```lua
minetest.register_globalstep(function()
    for _, player in pairs(minetest.get_connected_players()) do
        minetest.chat_send_all(minetest.pos_to_string(player:get_player_velocity()))
    end
end)
```

### PR DESCRIPTION
**Pull request by appgurueu**
Closes #10543

### CODE REVIEW

**Comment by sfan5** [comment]
This looks obvious but I wonder if this can't backfire in some edge case...

**Comment by LoneWolfHT** [comment]
Would this break ladders?

**Comment by appgurueu** [comment]
> This looks obvious but I wonder if this can't backfire in some edge case...

Yeah, it's indeed suspiciously simple. Might need some adjustments.

**Comment by TheTermos** [comment]
It's probably a good idea to start with trying to determine what the cause of a bug actually is.

**Comment by pyrollo** [comment]
I'm testing it with bouncing nodes (trampoline from xdecor) and it *seems* to lower the number of bounces.
Anyway, I'm wondering if y speed change should be in `collision.cpp` rather than `localplayer.cpp`.

**Comment by pyrollo** [comment]
Ok, I think this PR only hides the problem.

Problem seems to come from this truncation:

https://github.com/minetest/minetest/blob/master/src/collision.cpp#L485

The problem is, as speed is truncated, players stays slightly over the ground, at a small altitude. No further collision is detected and a non zero Y speed is kept. Like if player is continuously falling but its last movement, needed to actually touch the ground, is not achieved.

I have no idea yet about why this `truncate` is here.

**Comment by paramat** [comment]
:-1: This PR seems obviously unsuitable because it is applying a zero Y speed to the local player without any understanding of why this happens or what effects it could have. The effects are highly likely to be far worse than the current very minor issue.
'touching_ground' does not act in the way you might expect, so movement breakage is highly likely.

**Comment by TheTermos** [comment]
> I have no idea yet about why this `truncate` is here.

https://github.com/minetest/minetest/blob/33b2c5f5b1c565171296f26395d803b08f4575e9/src/collision.cpp#L69-L71

- truncate works on distance, not speed, the only instance that speed gets truncated is this here:
https://github.com/minetest/minetest/blob/33b2c5f5b1c565171296f26395d803b08f4575e9/src/collision.cpp#L263
this is because collisionmovesimple() sometimes receives very suspicious tiny velocity components (like 1e-40) which cause infinity when used as a divisor, but this only affects what's beyond the fourth decimal place and that's the input speed, so can't be the cause of this behavior.

- if a distance gets truncated, that means a collision has occurred, and that means the speed component in that direction has been set to zero.

Velocity is nonzero due to acceleration only briefly and only inside collisionmovesimple()

collision.cpp is the last place I'd look for the cause of this, localplayer.cpp already does all kinds of weird stuff with player physics so that's the usual suspect.

**Comment by pyrollo** [comment]
Great, so this `truncate` could be removed to solve the issue in a clean way.

> collision.cpp is the last place I'd look for the cause of this, localplayer.cpp already does all kinds of weird stuff with player physics so that's the usual suspect.

I had to trace with loads of outputs before getting into it.

**Comment by pyrollo** [comment]
Opened #10551 with the (hopefully) proper fix.

**Comment by TheTermos** [comment]
> Great, so this `truncate` could be removed to solve the issue in a clean way.

That's the opposite of what I said. 
Was any of that unclear?

**Pull request closed without merging**
