### PR TITLE
Fix transparent particles glitch

### LINKED ISSUE #10383: Visual glitch with semi transparent particles
##### Minetest version
```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
```
##### Summary
When particles with alpha channel textures overlaps, transparency is not properly applied.
Sometimes a foreground particles totally ignores background particles and clear background can be seen through transparent parts:
thebug

##### Steps to reproduce
Spawn particles with semi transparent PNG textures, in random order back or front to each other. Depending on the z-order, this problem can occur or not.

### PR DESCRIPTION
**Pull request by pyrollo**
This PR is an attempt to fix #10383

It disables writing to z-buffer for particles, preventing foreground particle transparent pixels from hiding background particle transparent pixels.

It seems to work fine with usual nodes an stuff on the background but I'm not sure it's always Ok.

## To do

This PR is Ready for Review.

## How to test

Spawn some particles using semi transparent textures, in different orders of apparition and different Z-orders. See if there is something bad in transparent pixels.

Code helping to test:
```
minetest.register_craftitem(":test:particle_stick", {
	description = "Particle stick",
	inventory_image = "default_stick.png^[colorize:#00FF0080",
	stack_max = 1,
	on_place = function(_, placer, pointed_thing)
		local pos = pointed_thing.above
		minetest.add_particle({
			pos            = pos,
			velocity       = { x = .1, y = .3, z = .2 },
			expirationtime = 3,
			size           = 20,
			texture        = "spot.png",
		})
	end,
})
```
With a spot.png having semi transparent pixels.

Example of with or without bug:

with or without

### CODE REVIEW

**Comment by numberZero** [comment]
Should be OK. Needs to be tested with translucent nodes ahead of or behind the particles.

**Comment by raymoo** [comment]
It seems to me like this would make it so that an opaque particle behind another opaque particle could be drawn in front of the foreground particle if it is drawn second. Even if you had code to handle opaque particles specially, you would have the same issue with mostly-opaque particles, but I think in either case it is only really apparent if you have particles of different colors. Summary of advantages / drawbacks as far as I can tell (I have not tested):

Advantages of this change
- Monochrome particles with transparency drawn on top of each other will look better.

Disadvantages
- Particles of different colors (opaque or transparent) will look bad when drawn on top of each other.

I think this PR should be tested with opaque / mostly opaque particles of mixed color.

**Comment by raymoo** [comment]
I think removing the depth buffer check could be improved by performing an incremental depth sort on the particles. This could be something simple like performing a few steps of insertion sort on the draw order every frame. Insertion sort is a good choice for particle depth sorting, since the depth ordering of particles will not change too much between frames, and insertion sort is fast on already-sorted data. Because each step of insertion sort makes the list more sorted (unlike some algorithms like quicksort), it is suitable for incremental sorting. That way you can limit the amount of time spent on sorting each frame to a constant, and if it's too out of order it will just happen over several frames.

**Comment by pyrollo** [comment]
Yes many tests have to be done before merging. I'm not expert of 3D graphic stuff so I'm interested in  every idea for testing.

@raymoo I thought Irrlicht sorted particles by distance when rendering. If it's not the case it may be a problem.

I'm wondering how depth buffer could manage transparent stuff. Seems rather incompatible concepts.

**Comment by raymoo** [comment]
Minetest doesn't use Irrlicht particles IIRC.

**Comment by raymoo** [comment]
According to http://irrlicht.sourceforge.net/docu/namespaceirr_1_1scene.html#a7862269bd1abc123929d4dbb8200d67f, it seems registering the particle for rendering as a transparent effect (https://github.com/minetest/minetest/blob/57df895cf93d79293a8b47802f9523bafcaa330f/src/client/particles.cpp#L117) should be depth sorting it already, from back to front. But that should also mean that it would render properly even with depth buffer enabled.

**Comment by raymoo** [comment]
The screenshots in https://github.com/minetest/minetest/pull/10398#issuecomment-692321679 show the the errors from this method look like.

**Comment by appgurueu** [comment]
> It seems to me like this would make it so that an opaque particle behind another opaque particle could be drawn in front of the foreground particle if it is drawn second. Even if you had code to handle opaque particles specially, you would have the same issue with mostly-opaque particles, but I think in either case it is only really apparent if you have particles of different colors. 

Precisely. We have to fix Z-sorting instead of just disabling the Z-buffer.

**Comment by rubenwardy** [comment]
This feels like better behaviour to me than what is currently done. We should have proper ordering at some point, but that doesn't preclude us from making it better now

**Review by rubenwardy — APPROVED** [review]

**Comment by appgurueu** [comment]
> This feels like better behaviour to me than what is currently done. We should have proper ordering at some point, but that doesn't preclude us from making it better now

Why merge this if #10398 provides a proper fix?

**Comment by SmallJoker** [comment]
@appgurueu Because this is a one-liner fix and the other PR is still WIP.

**Comment by appgurueu** [comment]
> @appgurueu Because this is a one-liner fix and the other PR is still WIP.

Except this isn't a fix. Disabling Z-writing is insane and introduces entirely new bugs as shown in https://github.com/minetest/minetest/pull/10398#issuecomment-692321679.

**Pull request closed without merging**
