### PR TITLE
Fix glitch that jolts players up edges

### PR DESCRIPTION
**Pull request by jordan4ibanez**
- Goal of the PR
Fixes a glitch that jolts players up edges of nodes. **"The Boink™"**
- How does the PR work?
Makes sure that the thing is firmly on the ground before committing to step up. 
- Does it resolve any reported issue?
No idea

## To do

This PR is Ready for Review.

## How to test
Try to make **"The Boink™"** happen with this change.

Here's a youtube video showing it in action for some reason. https://youtu.be/38UbIPhHimk?feature=shared

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
This may look like it causes some strange side-effect in gameplay but I found that there's no difference in the maximal node climbing height with or without the sneak glitch being active.

**Comment by Desour** [comment]
Shouldn't there be a physics override or so for this? I can imagine players complaining about pvp or parkour disadvantages with the new version.

**Comment by SmallJoker** [comment]
@Desour Would you please be so nice to provide an example where this change breaks a specific movement? If the node is too high to jump onto, the code will be executed when the player is about to fall down. I can imagine that the hiccup (that is already present in master) would only be delayed by a few milliseconds, thus not break anything.

Unless there's a clear negative difference in gameplay, I think that customizing this behaviour introduces unnecessary code and maintenance bloat.

**Comment by Desour** [comment]
Example:
* Build a staircase (with normal cube nodes).
* Hold jump and forward, to jump upwards.
* => You're faster in master.

**Comment by SmallJoker** [comment]
Right. Teleporting up (what step-up does) makes you move faster. That is a logical consequence of getting rid of the hiccup.

**Comment by jordan4ibanez** [comment]
I just came back to say hi again

**Comment by Zughy** [comment]
So is OP expected to add a physics override option (due to the label) or is it fine and we can proceed?

As someone who follows speedruns, it happens many times that new games get patched and speedrunners have to find a new way (shorter or longer) for a new record. I think this is no big deal, especially if we consider that it means more code burden for us - and it's not like there aren't many movement bug issues already

**Comment by jordan4ibanez** [comment]
> So is OP expected to add a physics override option (due to the label) or is it fine and we can proceed?
> 
> As someone who follows speedruns, it happens many times that new games get patched and speedrunners have to find a new way (shorter or longer) for a new record. I think this is no big deal, especially if we consider that it means more code burden for us - and it's not like there aren't many movement bug issues already. It takes no time to a server admin to remove one sec from the scoreboard to everyone (and frankly I don't know servers that feature time trial parkours anyway)

Please let me just merge this in so we can stop dealing with bugs and not harbor them anymore

**Comment by Desour** [comment]
I don't remember having seen any speedrunning in minetest either. But as said, this gives a pvp disadvantage. For some users it will be a reason to not upgrade.
We already have similar physics override flags, I don't see why there shouldn't be a new one for this case.

**Comment by Warr1024** [comment]
For parkour games, the big impact won't be stair climbing times, but jumps that used to be barely possible due to the "ledge grab" no longer being possible and requiring entire map areas to be reworked.

If an override is available for this, I would enable it and keep the legacy behavior at least in NodeCore (though I would try the new physics first in my other games), since hyper realistic movement is not a design goal and excess realism is likely to distract from the game.  If no override is available then I will probably just have to tell players that it's something outside of my control and they need to either adapt to it, or file an issue here.

**Comment by sfan5** [comment]
There have been enough uproars about the engine changing existing behaviour or "pulling the rug".
Proposing to just stop dealing with bugs and merge a breaking change anyway is not productive.

**Comment by appgurueu** [comment]
I think a physics override is insufficient: The code modified by Jordan applies to entities and players alike; this patch would hence also apply to entities with a stepheight > 0. We'd need an object property.

**Comment by Zughy** [comment]
@jordan4ibanez still want to work on this? @minetest/engine thoughts about what appguru has said?

**Comment by jordan4ibanez** [comment]
> @jordan4ibanez still want to work on this? @minetest/engine thoughts about what appguru has said?

You can steal it if you want

**Comment by Zughy** [comment]
No no, just wanted to know if I had to close it

**Comment by jordan4ibanez** [comment]
Oh yeah go for it

**Comment by appgurueu** [comment]
If people want it I could revive this and add backwards compat

**Comment by appgurueu** [comment]
The author revived it: #16971

**Pull request closed without merging**
