### PR TITLE
line_of_sight: Allow sight through sunlight_propagates nodes

### PR DESCRIPTION
**Pull request by RiZom-91**
Add the sunlight_propagates condition in the line_of_sight function. If the sun light can pass through a node then it should also be possible to see through it.

I think it is an improvement. If not just explain me why ! ;-)

### CODE REVIEW

**Comment by ShadowNinja** [comment]
@sapier This can be implemented in compatible ways and incompatible ways.  It isn't incompatible by it's very nature.

**Comment by 4aiman** [comment]
Didn't read the whole conversation, but I'm against the change if ignoring the additional nodes won't be optional.
(Thus, agreeing with  https://github.com/minetest/minetest/pull/1752#issuecomment-64010191)

**Comment by neoascetic** [comment]
I am +1 on this because I **can** see through glass. However, there should be function which checks if there are no nodes on a line between two positions. Awaiting next comment on this in 2017.

**Comment by paramat** [comment]
:-1: because of issues explained above.
Is old and unpopular can we close this?

**Comment by paramat** [comment]
I'll close in 1 month if no response from the author.

**Comment by RiZom-91** [comment]
@paramat I did not try to do anything since my last comment to be honest... I still don't know how to change a commit. I'm OK with closing this pull request ; I think someone would have do it by now, if it was really a usefull/wanted feature. :-) You're right I did not log in for a long time but I still check commits, issues, etc of the Minetest project once or twice a week !

**Comment by paramat** [comment]
Hi, thanks for the reply.

**Pull request closed without merging**
