### PR TITLE
Smooth yaw

### PR DESCRIPTION
**Pull request by SmallJoker**
As requested in #1283 

Demonstration video: https://youtu.be/fObL_M2SYiI
Sudden `set_yaw` changes (like carts that switch the direction) are now smooth too, which may look quite weird.

### CODE REVIEW

**Comment by paramat** [comment]
First test compiling your branch indicates possible problems.
Tried applying to latest master but:
"Applying: Add wrappedApproachShortest(), tidy up SmoothTranslator
Applying: Add SmoothTranslatorWrapped for yaw, use in GenericCAO
error: patch failed: src/content_cao.cpp:350
error: src/content_cao.cpp: patch does not apply
Patch failed at 0002 Add SmoothTranslatorWrapped for yaw, use in GenericCAO"
If you rebase i will test this.

**Comment by SmallJoker** [comment]
@paramat did you try `git am -3 6825.patch` or alternatively
```
wget https://github.com/minetest/minetest/pull/6825.diff
git apply 6825.diff
```

**Comment by paramat** [comment]
Ok will try -3.

**Comment by paramat** [comment]
Applying: Add wrappedApproachShortest(), tidy up SmoothTranslator
Applying: Add SmoothTranslatorWrapped for yaw, use in GenericCAO
fatal: sha1 information is lacking or useless (src/content_cao.cpp).
error: could not build fake ancestor
Patch failed at 0002 Add SmoothTranslatorWrapped for yaw, use in GenericCAO

**Comment by paramat** [comment]
Tried both methods, both failed.

**Comment by paramat** [comment]
Testing patch applied to master results in different behaviour, seems good at first try but will test more.

**Comment by paramat** [comment]
Here's my car mod for testing https://github.com/paramat/driftcar It uses 'dtime' to control the amount of turn so is very jerky in MT master branch. Comparing master to PR i seem to notice a very slight sluggishness in turning response, i guess this is inevitable due to the smoothing? Not necessarily a problem as mods can compensate.

**Comment by nerzhul** [comment]
@paramat dtime check is very strange usage as you should instead have a turn velocity + turn acceleration over time, is this like this ?

**Comment by paramat** [comment]
> you should instead have a turn velocity + turn acceleration over time, is this like this ?

Yes.

**Comment by paramat** [comment]
I assume this is a balance between smoothness and responsiveness? If so can this be re-balanced for a little more responsiveness and minimum acceptable smoothness?
I'll test carts next.

**Comment by paramat** [comment]
Testing carts, they still turn very rapidly at corners, not sluggish at all, it's actually quite difficult to tell it isn't an instant rotation. Seems fine for carts.

**Comment by paramat** [comment]
Tested more with my driftcar mod. The extra sluggishness is only very slight, not a problem. I assume it's not an actual object motion sluggishness but a clientside visual one.
The smoothness seems optimum, any less smooth and it would start to get jerky again.

**Comment by SmallJoker** [comment]
Thanks a lot for testing. Smoothing it better will be quite difficult (reference to my last post), so I'm happy that it's satisfying for you. However, more inputs would be nice, to see what other players think about this change. Maybe there's an edge case where smoothing is not wanted or simply looks wrong.

**Comment by paramat** [comment]
Looked through the code and it seems ok but i don't feel i understand it well enough to officially +1.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Good point, smoothing will then be needed for pitch and roll too.

**Comment by CoderForTheBetter** [comment]
Since this is already merged then I guess I will have to change my PR's code. May be a little hard.

**Pull request merged**
