### PR TITLE
[CSM] Add `on_dignode` callback

### PR DESCRIPTION
**Pull request by red-001**
Adds a `on_dignode` callback to the client, which can be to stop a node from being dug

### CODE REVIEW

**Comment by Fixer-007** [comment]
Why no description of PR?

**Comment by red-001** [comment]
I though the title described it well enough.

**Comment by nerzhul** [comment]
Nice, okay for me

**Comment by paramat** [comment]
@nerzhul @red-001 please link to the 2nd approval.

**Pull request merged**
