### PR TITLE
Rename “Irrlicht” to “IrrlichtMt” in documentation

### PR DESCRIPTION
**Pull request by Wuzzy2**
Since Minetest's Irrlicht fork was recently officially renamed to “IrrlichtMt”, this PR will reflect that change.

### CODE REVIEW

**Comment by sfan5** [comment]
I don't think it quite makes sense to rename this blindly so I suggest undoing the changes to `builtin/settingtypes.txt` and the first two in `CMakeLists.txt`.

**Comment by Wuzzy2** [comment]
But why? Minetest's Irrlicht fork was officially renamed to "IrrlichtMt", and Minetest depends on IrrlichtMt, not Irrlicht. So why not being consistent about it?
All strings that I touched are user-facing. I don't see the issue, honestly.

**Review by nerzhul — APPROVED** [review]

**Comment by sfan5** [comment]
"IrrlichtMt headers are required to build the server, but none found." is factually incorrect and for "The rendering back-end for Irrlicht" I don't think it matters at all to be exact about what the engine is called like.

**Comment by Wuzzy2** [comment]
Wait, what? Why is it factually incorrect? What is the truth then? o_O

**Comment by sfan5** [comment]
Currently the server can still be built with legacy Irrlicht headers. There is nothing incompatible in the subset the server uses so no reason to prevent this (yet).

**Comment by Wuzzy2** [comment]
I made some changes, please take another look. THX.

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
