### PR TITLE
Fix liquids refusing to flow in X+ or Z+ in some cases

### LINKED ISSUE #2399: Lava doesnt flow correct
Lava doesnt flow correct (x+, z+) when between water and lava is one block air:
screenshot_40070664
https://github.com/minetest/minetest_game/issues/425

### PR DESCRIPTION
**Pull request by sfan5**
fixes #2399

The bug and also reason why it only broke in X+ or Z+ direction is that when the engine considers an air node for liquid "inflow", it picks the first liquid type it sees. In the case with the bug that is the water. The water however can never flow there, since it is just a falling liquid and the lava is never considered.

A similar issue exists when source/flowing liquid is below.

## To do

This PR is Ready for Review.

## How to test

Test everything liquids could possibly do.

### CODE REVIEW

**Comment by oilboi** [comment]
Do it

**Comment by leorockway** [comment]
Works On My Machine

**Comment by KaylebJay** [comment]
Great, finally fixing this!

**Comment by Wuzzy2** [comment]
I am unable to reproduce the particular bug mentioned in the issue with this PR. Which suggests that it is fixed.
I have tested all scenarios that are listed in #2399. Important: They also work after updating from 5.2.0 to this PR. (So liquids will start to flow correctly immediately after the upgrade).

However, during testing, I discovered a different bug.

First, this is my testing setup in `devtest`:

https://satoshiupload.com/images/amd0UOc45y.png

The liquid I want to test is in the center, and 4 additional source blocks are around it. To pass the test, the center liquid has to flow after I placed it. Before I start the test, I make sure the center area is empty. This kind of test is PASSED. The center liquid that I used to test is a Test Liquid Source (I tried all possible ranges from 0 to 8).

However, when I do a little variation of the test, I discover a problem:

If I first place a Test Liquid Source, Range 3 in the center, all is fine and dandy. But when I place a Test Liquid Source, Range 4 INSIDE the existing liquid (thus replacing it), the old flowing liquid will first drain out (expected), but then the new liquid source refuses to flow:

It will look like this: https://satoshiupload.com/i/6B2m1Qk3w4

However, this is temporary. The liquid will start to flow when you place or remove a block next to it, or you restart the server.
This seems to be a different and possibly unrelated bug, however. I can also reproduce it in 5.2.0, so at least it does not seem to be caused by the PR.

PS: I strongly recommend to test this with `devtest`, as you have liquids with all possible ranges to play around with.

**Comment by oilboi** [comment]
Wooo

**Pull request merged**
