### PR TITLE
Fix incorrect pointer placement repo-wide

### PR DESCRIPTION
**Pull request by ClobberXD**
This PR attends to incorrect pointer placement, across the whole repo.

The corrections were performed manually by me, and weren't automated by a script. This is to prevent messing up other things like this example comment:
```
This is *not* the best way to do this, but hey, this is Minetest, and this is how we roll :D
            ^
```

Yes, there's a \*lot\* (ha!) of comments that use `*` around words for emphasis. :P

P.S. Do let me know if there's any way to automate this without messing up other things like comments, or badly-formatted mathematical expressions (e.g. `invList->setSize(8* 4)`)

****

I've corrected all occurrences of incorrect pointer placement, that matches either of the following regular expressions:

- **`\w(\*|&) \w`**  (moved the `*`/`&` operator after the space, for all matches)
  - `handleCommand_Interact(NetworkPacket* pkt);`
  - `NetworkPacket& NetworkPacket::operator <<(v3f dst);`
- **`\w(\*|&)(>|\))`** (added a space between the `*`/`&` operator and typename, for all matches)
  - `std::vector<EmergeThread*> m_threads;`
  - `} catch (SettingNotFoundException&) {}`

### CODE REVIEW

**Comment by ClobberXD** [comment]
Trimming the empty lines at the end of a couple of files (automatically done by VSCode) resulted in 19 more deleted lines, and there are no additions or removals to the actual code in this PR.

**Comment by SmallJoker** [comment]
Whereas this would be a nice improvement; it will surely result in a few PRs which need rebasing. The code should rather be updated gradually.

**Comment by paramat** [comment]
I appreciate and am impressed by so much work, but agree with the others. This is also too big/exhasting/monotonous to review. There are very many codestyle cleanups that need doing but doing them in bulk is problematic.

**Comment by ClobberXD** [comment]
I've also discussed with SmallJoker on IRC about this, and he suggested fixing all code-style issues, but on a per-directory basis. This way, the changed files can also be removed from the clang-format whitelist.

Thanks

**Pull request closed without merging**
