### PR TITLE
Coding style fixes

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by rubenwardy** [comment]
Code style pull requests aren't usually merged on their own as they tend to break other commits. To fix code style, you need to include it with other code.
That's the general tend. We'll see what the gives think.

Also, braces would need to be fixed. Might as well go all out. Remember that classes, structs, enums and functions put braces on a new line, they're the exception.

**Comment by nerzhul** [comment]
@rubenwardy of course, i have https://www.kernel.org/doc/Documentation/CodingStyle

I think, if this is too early for this, at one time minetest must fix all this problem and pull requests must be updated.

**Comment by SmallJoker** [comment]
Every pull makes the coding style a bit better. Just wait a while and it's like "how it should be".
Related: #1785

**Comment by sapier** [comment]
nerzhul we had this discussion quite often. Even if it was nice to fix it once it's not gonna be done this way. Everyone touching code is supposed to fix the coding style in there but we won't do it automaticaly. Especially because automatic tools always fail for corner cases where some formating is in gray area of coding style but way better readable then following cs to the word.

**Comment by nerzhul** [comment]
Okay, i understand :)

Closed

**Pull request closed without merging**
