### PR TITLE
GOTBLOCKS & DELETEBLOCKS: test packet size only once

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by kahrl** [comment]
The comparison `((s16)pkt->getSize() < 1 + count * 6)` is okay (not in danger of integer overflow) because `u8 count` is implicitly promoted to `int` when multiplied by `6`. But it would be better if this conversion was done explicitly, since a reader might fail to notice the implicit conversion.

**Comment by nerzhul** [comment]
@kahrl fixed

**Comment by kahrl** [comment]
:+1:

**Comment by Ekdohibs** [comment]
:+1:

**Pull request merged**
