### PR TITLE
Fix android gettext issue

### PR DESCRIPTION
**Pull request by Zeno-**
Also moved some functions around

### CODE REVIEW

**Comment by est31** [comment]
Confirmed that this fixes #2287.

**Comment by BlockMen** [comment]
Breaks umlauts and special chars under windows

**Comment by Zeno-** [comment]
Blockmen, are you using the PR version with 3 commits?

**Comment by BlockMen** [comment]
@Zeno- Sorry, didn't notice the update. Building again....

**Comment by Zeno-** [comment]
@BlockMen it's fixed (krock checked). Thanks

Thanks (heaps) also to the other people who tested this... you know who you are ;)

commit 5698e2b

**Pull request closed without merging**
