### PR TITLE
Add /setpassword and /clearpassword logging

### PR DESCRIPTION
**Pull request by est31**
This enables logging for these commands. Its very useful you have a team of people that can change passwords, and don't know who changed it for some user, when they shouldn't.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Using "change" instead of "set" would make it follow the same pattern.

Chang**ed**, change**s**.
Clear**ed**, clear**s**

**Comment by est31** [comment]
Changing assumes there already exists one. "set" describes more what we do. Do you support this even if it uses "set"?

**Comment by rubenwardy** [comment]
I suggested it as it would simplify the code. Is true though, doesn't quite
mean the same.

**Comment by nerzhul** [comment]
Approved, it's useful for admins. If one more, please merge :)

**Pull request merged**
