### PR TITLE
WoW-like item description position

### PR DESCRIPTION
**Pull request by lisacvuk**
I think this position makes it look cleaner than the current one.  
[It looks like this](http://imgur.com/pHc5eoC)

### CODE REVIEW

**Comment by rubenwardy** [comment]
That looks like a bug

Where is your cursor pointing?

**Comment by SmallJoker** [comment]
I quite like the current way of showing the tooltips. There's no hand like IRL that could cover the label and it's slimilar to those in various applications, such as Firefox, Gimp..
grafik

**Comment by lisacvuk** [comment]
Yeah, but they are supposed to be more like descriptions, and less like tooltips, in my opinion

**Comment by Ezhh** [comment]
I like the current tooltips and , as Krock has pointed out, the current positioning is quite normal. The screenshot for this also makes it look like the tooltip is above a different item.

**Comment by lisacvuk** [comment]
[A video to demonstrate it](https://youtu.be/PjBN-kwyLz4)

**Comment by rubenwardy** [comment]
I think they should be centered above the item slot, not to the left

**Comment by lisacvuk** [comment]
What about centered to the left side of the item?

**Comment by lisacvuk** [comment]
[Like this](http://imgur.com/t4CNlak)

**Comment by Wuzzy2** [comment]
I am opposed. There is nothing wrong with the current tooltip position.

**Comment by lisacvuk** [comment]
Okay then, why not make it an option? For example 'description_position' in item definition.

**Comment by Wuzzy2** [comment]
That's even worse. If it's made an option at all, it should be a client-only setting; the server or item definition should have no say over this.

**Comment by paramat** [comment]
Current seems good, upper-left looks awkward.
Lower-right is also the direction of the base of the pointer arrow so it's like the tooltip box is pointing with the arrow to the slot.
:-1: I prefer no change.

**Comment by nerzhul** [comment]
if we have an option to change the behaviour it's okay for me, but i don't like the current behaviour myself

**Comment by lisacvuk** [comment]
[What about this?](http://imgur.com/FQrotk4)

**Comment by paramat** [comment]
Where is the pointer relative to the box?

**Comment by lisacvuk** [comment]
Box no longer moves according to the pointer's position.

**Comment by paramat** [comment]
I see.

**Comment by dsohler** [comment]
Descriptions should stick with the cursor, below and moved to the right in relation to the cursor's bottom.

**Comment by paramat** [comment]
I still prefer current.

**Pull request closed without merging**
