### PR TITLE
Added option to disable entity selectionboxes. (Minecrafters rejoice)

### PR DESCRIPTION
**Pull request by TriBlade9**
Adds an 'entity_selectionbox' option to minetest.conf, **false** by default.

When set to false, mousing over an entity will not display a selection box. (a la Minecraft)
When set to true, it will have the same behavior as normal.

Why is the default false you ask?
  Simply because setting it to true is ugly. Most people (as far as I can tell) think so, and those that like it are   probably more used to Minetest, and therefore know how to change their configuration settings.

Enjoy!

### CODE REVIEW

**Comment by ObaniGemini** [comment]
Should this be closed or enhanced/rebased ?

**Comment by MoNTE48** [comment]
This is quite a good idea, but rebase need

**Comment by C1ffisme** [comment]
Just to spit out my two cents about@Calinou 's complaint about Minecraft's choice to make selection boxes hidden:

Minecraft usually balances hit-boxes to be convenient, while not OP (Think : Baby Zombies).
Also, Minecraft is a game, and does not need the feel of a development environment.

Minetest is much more of a development environment, and users often need to see where a hit-box is to debug it, such as if it's too big/small/doesn't cover the mob.

I support this pull if it's rebased/whatever it needs to be. It ruins the feel of a game to have hitboxes intruding gameplay.

**Comment by sofar** [comment]
#3992 is a rebased version of this patch.

**Comment by MoNTE48** [comment]
Please, close this

**Pull request closed without merging**
