### PR TITLE
Place schematic (on vmanip): Enable use of 'place center' flags 

### PR DESCRIPTION
**Pull request by paramat**
Place schematic (on vmanip): Enable use of 'place center' flags

For 'place schematic' and 'place schematic on vmanip' APIs.
Fix 'place center' code to properly centre schematics.
Fix some comments.
///////////////

For #7066 
@Gael-de-Sailly please could you test this?

### CODE REVIEW

**Comment by Gael-de-Sailly** [comment]
I just found the cause of the issue and fixed it in [my branch](https://github.com/Gael-de-Sailly/minetest/tree/schemflags2).

**Comment by paramat** [comment]
Correct, see https://github.com/minetest/minetest/blob/master/src/mapgen/mg_decoration.cpp#L363

**Comment by paramat** [comment]
Updated.
@Gael-de-Sailly since i'm busy could you test this updated PR, testing 'place schematic' too? Also please test nothing breaks when there is no 'flags' field used (for backwards compatibility).
Once tested i can probably merge this as trivial.

**Comment by Gael-de-Sailly** [comment]
All of this works. Both functions work as expected, and there is no bug when `flags` is omitted. I think you can merge.

**Comment by paramat** [comment]
Thanks.

**Comment by paramat** [comment]
c610643c4ca1d1c32ca3e400b5cb055f25401107

**Pull request closed without merging**
