### PR TITLE
Fix mapgen settings in minetest.conf being ignored

### PR DESCRIPTION
**Pull request by sfan5**
broken since e8a8185d24897ccf964327017effae81aa1c9d40

## To do

This PR is a Ready for Review.

## How to test

https://github.com/minetest/minetest/pull/9296#issuecomment-618700998

### CODE REVIEW

**Comment by paramat** [comment]
Thanks will test.
Serious bug.

**Comment by SmallJoker** [comment]
```
#              v-- MGV7_MOUNTAINS | MGV7_RIDGES | MGV7_CAVERNS
# defaultsettings: mountains,ridges,nofloatlands,caverns
#  + Global .conf: nomountains, noridges, floatlands
#  + Game   .conf: nomountains, ridges, nocaverns
#
#          wanted: nomountains, ridges, floatlands, nocaverns
#
# ==> Actual:
# mgv7_spflags = nomountains, ridges, floatlands, nocaverns


# minetest.conf
mgv7_spflags = nomountains, floatlands


# game/minetest.conf:
mgv7_spflags = nomountains, ridges, nocaverns
```

Works as expected.

**Comment by paramat** [comment]
> # minetest.conf:
mgv7_spflags = nomountains, floatlands

Note that this is a discouraged and sloppy way to set flags in .conf, because every flag should always be stated, with or without a preceding 'no'. The presence, or lack of, a preceding 'no' is what sets the value, not whether the flag is present.
It is better that a user states all flags so that it is clear what they are choosing.
Also, when using 'All Settings' menu, the resulting setting in .conf states all the flags.

However, it seems that we now have the proper fallback logic that, if a flag is not stated, it is not altered from the default.

**Comment by paramat** [comment]
Confirmed the bug in master, surprised and ashamed i did not notice this bug earlier.
Global mapgen flags set in .conf work fine.
Mapgen-specific flags set in .conf are ignored.

**Comment by paramat** [comment]
Tested PR, mapgen-specific flags set in .conf are now applied.
I do not understand the code here, but if SmallJoker considers the code ok i think it should be merged.

**Pull request merged**
