### PR TITLE
Enable the gamebar on Android

### PR DESCRIPTION
**Pull request by rollerozxa**
This PR enables the gamebar on Android and in addition removes code related to when the gamebar is not enabled (which becomes unused).

I have been playing Minetest on my phone with the gamebar enabled for a long while now and I believe enabling the gamebar on Android greatly improves the main menu user experience on mobile.

## Screenshots
How it looks like on two devices with different resolution and aspect ratio:

Vernee Apollo Lite (1920x1080, 16:9)
Screenshot_20211224-163741

Nokia 5.4 (1560x720, 19.5:9)
Screenshot_20211224-163144

## To do
This PR is Ready for Review.

## How to test
:iphone: :eyes: 

Also see so that there's no regressions in the local world tab related to the gamebar.

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Note to reviewers: Hide whitespace changes.

 * Desktop mode does still work
 * Devtest warning does still work
 * Code looks good.

**Comment by rubenwardy** [comment]
Rebase needed

**Comment by rollerozxa** [comment]
Messed up something while rebasing, will have to fix that

**Review by sfan5 — APPROVED** [review]
Works, also verified the devtest-only warning.

**Pull request merged**
