### PR TITLE
Set vertex color on upright sprites.

### PR DESCRIPTION
**Pull request by basicer**
This sets the vertex color on upright sprites so that they respect the colors object property similar to model.

### CODE REVIEW

**Comment by SmallJoker** [comment]
What visual effect does or will this change have? The comment above the section you changed suggests that this part will have no effect until we have directional lightning.

**Comment by basicer** [comment]
Here is an example of a WorldEdit like selection system with multiple selections.

image

They are all the same entity which has a white and transparent texture, and their color is set with `set_property`.  It's true that the global lighting will clobber the color values without the glow property set to -1.

**Comment by nerzhul** [comment]
can we have a test from other meshes to ensure we don't have strange colors ?

**Comment by basicer** [comment]
Not sure what you mean by test with other meshes, this only applies to upright sprites which only have one mesh (a quad).

**Comment by paramat** [comment]
Maybe nerzhul meant test an already-coloured texture, like the old MT player, but i see on IRC you already have. I support the concept but am just not knowledgeable enough about this part of the code to +1.

**Pull request merged**
