### PR TITLE
Add helper for holding down keys (callback registration function)

### PR DESCRIPTION
**Pull request by Arcelmi**
This patch adds three new helper functions.
If you use them, it'll be easier to register functions, which should be called if a player hold down a key for a special time. There is one function when a player press a key, release a key or hold down for some time. The last two functions also count the time from pressing the key.

I published them some time ago, as a mod. Forum topic: https://forum.minetest.net/viewtopic.php?f=9&t=18471
There you can also find the API.

### CODE REVIEW

**Comment by nerzhul** [comment]
interesting feature but i tend to prefer to reserve it for CSM only as such events are very very related to latency, you should update CSM doc too.

**Comment by dsohler** [comment]
Don't use CSM as excuse for not adding good and relevant core features. Keybinding, etc. should absolutely NOT be done via CSM but should be core functionality.

**Comment by raymoo** [comment]
Even if it's in CSM it should have a server component to make sure a client doesn't cheat the hold-down time.

**Comment by lisacvuk** [comment]
@raymoo Key hold-down detection is on the client already.
With mod channels, it would be better to have an API for getting any pressed keys in CSM, then send those to the server. Player can cheat here, as well, by using xdotool/autohotkey/similar. And client would only send when the key is pressed, not how long. Also, would be nice if we could bind to any key, not just the default ones. It would make it easier to open formspecs with gameplay-important stuff (character menus, for example).

**Comment by raymoo** [comment]
@lisacvuk The way I read this issue is that it wants to make it possible to register something to happen if a key is held down for a certain length of time, which is not a feature that I know to be implemented in the CSM API. I think there is another issue somewhere for allowing key input from more keys than currently possible.

**Comment by rubenwardy** [comment]
I'm not sure on the implementation. I feel like it needs engine support to trigger these events when the control packets are received, rather than this iteration on every tick

**Comment by raymoo** [comment]
It's necessary if you want it to be higher resolution than the control-sending rate, which is rather low.

**Comment by rubenwardy** [comment]
> It's necessary if you want it to be higher resolution than the control-sending rate, which is rather low.

The controls will only change when it receives a control packet at the control-sending rate

**Comment by raymoo** [comment]
@rubenwardy Ah, ok. For some reason I thought you meant to have the client send a "unclicked" event which could possibly be sent in between control updates.

I don't feel like C++ support is needed to handle unclicks at the same resolution as control updates since checking the controls for all players every tick from Lua doesn't seem expensive.

**Comment by paramat** [comment]
```
core.register_globalstep(function(dtime)
	for _, player in pairs(core.get_connected_players()) do
		local player_name = player:get_player_name()
		local player_controls = player:get_player_control()
		for cname, cbool in pairs(player_controls) do
```
This is in Lua, every step, every player has their controls scanned, then a loop goes through all controls. This will be of significant intensity for a very low priority feature, i see very little need for the feature. Best left to a mod.
:-1: Sorry.

**Pull request closed without merging**
