### PR TITLE
Fix world config menu ignoring `name` in `mod.conf`.

### PR DESCRIPTION
**Pull request by kaeza**
Also reorganize code to be cleaner.

See [forum topic](https://forum.minetest.net/viewtopic.php?f=5&t=13711&p=201068#p201060).

### CODE REVIEW

**Comment by kaeza** [comment]
Possible conflict with #3392.

**Comment by kaeza** [comment]
Do I need to remind devs that this is not exactly low priority?

**Comment by kilbith** [comment]
^ @est31 @paramat 

kaeza is highly trustable in Lua stuff.

**Comment by sofar** [comment]
I pulled this branch and performed a rename test:

```
mv inspector ins.pe-cto_r
```

restarted minetest with this patch applied, and confirmed that the UI displayed the "inspector" mod. Enabled it, started a subgame, and typed ```/mods``` and confirmed that ```inspector``` was listed.

:+1:

**Comment by paramat** [comment]
I'll +1 if another core dev checks the code.

**Comment by rubenwardy** [comment]
Code looks okay to me. (To avoid miscommunication, I'm not a core dev)

**Comment by Dragonop** [comment]
Setting name = modname in mod.conf works for me, is this a bug that only happens "sometimes"?

**Comment by sofar** [comment]
@Dragonop this happens when the folder name isn't ```modname``` but e.g. something like ```mod_na-me-v1231.zip##$$```

**Comment by kaeza** [comment]
@Dragonop In case it's not clear from the title, the issue this fixes is the world configuration dialog (Client Tab > Configure) does not respect the mod name.

A while ago, I coded a feature (#1062, of which only the [one commit](https://github.com/minetest/minetest/commit/c5defe7a11f58048acfa4568ea784f31d9ffa276) got in) which allows mods to specify the name of the mod in a `mod.conf` file, and makes the engine use that name for the mod regardless of the directory name.

Now, the engine (the server part, specifically) honors that configuration e.g. when the mod is put in a game's `mods` directory, or the world's `worldmods` directory, but I forgot to check the world configuration dialog, so if you put the mod in your user `mods` directory, you can't enable them at all unless you specifically rename the directory to match the actual mod name (which makes the new feature kinda useless).

This patch fixes that.

If you can, try using a non-patched client, and you will see sofar's example fail because it contains invalid characters. Now try a patched client, and you will see that you can now name the directory whatever you want and you can enable the mod correctly.

**Comment by ShadowNinja** [comment]
a594963a7dad2f1ea3d4904610033164983a1389

**Comment by Dragonop** [comment]
I see it now, thanks @kaeza and @sofar.

**Comment by kaeza** [comment]
@ShadowNinja, Thanks.

**Pull request closed without merging**
