### PR TITLE
[no squash] porting.h maintenance

### PR DESCRIPTION
**Pull request by sfan5**
## To do

This PR is Ready for Review.

## How to test

no need really

### CODE REVIEW

**Comment by srifqi** [comment]
Using self-compiled MinGW build on Windows 10,

| `fps_max` | `master` | This PR |
| ---------:| --------:| -------:|
|  30 FPS |  30±1 FPS |  30±1 FPS |
|  60 FPS |  61±1 FPS |  58±1 FPS |
| 120 FPS | 122±1 FPS | 115±1 FPS |
| 240 FPS | 244±2 FPS | 220±1 FPS |
| (trend) |  (higher) |   (lower) |

In some cases, the Minetest's FPS counter is lower (by around 1 FPS) than the Xbox Game Bar's FPS info using this PR version.

**Comment by sfan5** [comment]
Hm.
I can reproduce that it undershoots the target FPS in wine (if I trust our FPS counter), this would point towards a bug in the timer code.

**Comment by sfan5** [comment]
Some debugging code to add to `myusleep`:
```cpp
	auto start = getTimeUs();
	WaitForSingleObject(timer, INFINITE);
	auto end = getTimeUs();

	if (fabs(fabs(end-start) - usecs) > 100) {
		char buf[100];
		snprintf(buf, 100, "wanted to sleep %dus actually %dus", (int)usecs, (int)fabs(end-start));
		actionstream << buf << std::endl;
	}
	CloseHandle(timer);
```

I sometimes see it sleeping up to double the requested time for small amounts like 1000.
Inserting similar code into the Linux code path it never triggers for me.

It's weird because `CreateWaitableTimerExW` + `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION` is supposed to be more accurate way to sleep on win32.

**Comment by sfan5** [comment]
Well I've run out of things to try so I'll convert this PR to only the maintenance changes.

**Review by srifqi — COMMENTED** [review]
The code looks good to me. I can not test on other than Windows, though.

**Pull request merged**
