### PR TITLE
Fix: automatic selection / deselection of dependent mods at world configuration

### PR DESCRIPTION
**Pull request by kuklinistvan**
Hey there!

- Goal of the PR

I've noticed that at version 5.4.1 Minetest does not select the dependency mods automatically when I enable one from the  list during world configuration. I've found the lua script which is responsible for the dependency selection and I've also realized why it was broken - and meanwhile it could have been fixed easily with removing a couple lines, I wished for a more complete solution that also checks whether a mod was disabled on which other activated mods depend.

- How does the PR work?

Once a mod is toggled, a graph is built in which a node not only has references to its dependencies, but also to those mods which depend on the toggled mod. Depending on whether the user enabled and disabled the mod, the solution checks for whether additional mods should be enabled or disabled.

- Does it resolve any reported issue?

I did not find one, however, there could be an issue reported somewhere.

## To do

Ready for Review.

**Some disclaimers**

- I hereby acknowledge that due to the lack of the time to allocate to this effort, I did not read the coding conventions (I'm sorry :))
- I've added two dependencies - LuaLINQ (required, for it helped me write much cleaner queries than with loops) and Inspect (for debugging convenience - I think I removed its invocations mostly in the end).
     -  I did not find a place in the codebase where these go (if they external lua dependencies accepted at all), therefore I simply put to a place where it seemed reasonable (`bultin/common/lib`), placed the licenses, and initialized them in `mainmenu/init.lua`. There's a chance I've simply missed the canonical place of lua dependencies.
- I've actually branched at first from version 5.4.1 and rebased on top of `master` after the modifications were done. I did not test it yet on the `master` branch, however, on version 5.4.1 it seemed like it has resolved my problem with modding :)
- I have not written unit tests and I know I should have..
- I'm an enthusiastic code-newbie, however, this was the first time I worked with Lua. I'm sorry for the quality.

_All in all, I expect this PR to fail the requirements and I'm not sure when I will have the time to clean it up. I'm publishing my effort anyway as I have a couple hours in it. I hope I can save someone else's time when they investigate the problem this PR intends to solve._

## How to test

Run the game, grab some mods from ContentDB and create a world. Configure the world, and start selecting or deselecting mods.

### CODE REVIEW

**Comment by SmallJoker** [comment]
The fix is there, that's nice. However, I am really in doubt whether that justifies including one, let alone two, libraries. They might be helpful here, but that's a feature and does not belong into a bugfix PR.

**Comment by lhofhansl** [comment]
Can we fix the bug you mentioned in the description first? Then we can focus on this issue as improvement.

**Comment by kuklinistvan** [comment]
Hello,

this PR fixes the issue, the problem is that it does so by introducing two dependencies.

- Inspect can probably be simply removed at this point
- LuaLINQ queries can probably be replaced with loops

**Comment by SmallJoker** [comment]
This implementation is overly complex and should be done with Minetest API.

**Pull request closed without merging**
