### PR TITLE
README: Remove references to Minecraft and InfiniMiner

### LINKED ISSUE #8248: "An InfiniMiner/Minecraft inspired game." in engines readme?
##### Issue type
 - Documentation issue

##### Summary
The README.md of the engine says that Minetest is a game. It isn't, it's just an engine and the game is "Minetest Game". I know, this isn't really an issue, but it is inaccurate.

### PR DESCRIPTION
**Pull request by ClobberXD**
Closes #8248

Feel free to suggest improvements - I'm sure it can be improved. :)

### CODE REVIEW

**Comment by Xaleth** [comment]
Awesomesauce

**Comment by paramat** [comment]
Good to remove these references, even if true it's good to not refer to other games in a primary intro.

Please can we remove 'near-infinite'? It's even more ridiculous than 'infinite'.

**Comment by ClobberXD** [comment]
> Please can we remove 'near-infinite'? It's even more ridiculous than 'infinite'.

True - I just added it because the sentence was too short without it. What do you suggest I add/remove/replace?

**Comment by paramat** [comment]
Most voxel game engines have pretty big worlds so i don't think we need to mention world size in the first intro.

**Comment by ClobberXD** [comment]
Anything else left to address? Is the new sentence merge-worthy?

**Comment by SmallJoker** [comment]
I think that many Minetest players found this game by looking for an alternative to Minecraft. Removing this reference might reduce chances for these players to find Minetest.

**Comment by ClobberXD** [comment]
I too, am guilty of that sin, so to say. ;)

But as paramat noted, having such sentences right at the start of the README paints a bad picture. MT was probably inspired by these games in the very beginning, but it's got a life of it's own now - I'm sure you'll agree too. We're far from being inspired by these games now, and on the other hand, we're inspiring so many other forks and ripoffs in turn (just saying). :)

**Comment by paramat** [comment]
> I think that many Minetest players found this game by looking for an alternative to Minecraft.

Yes, but they don't discover MT through reading the README in the GitHub repo, web articles usually mention MT as being similar to MC and that's how people find MT.

**Comment by paramat** [comment]
Random thought:
"A free open-source voxel game engine with easy modding and game creation"
It was the easy modding that was the main attraction for me, and 'extensible' is not a commonly understood word, especially for foreign speakers.

**Comment by ClobberXD** [comment]
Sounds great. I've replaced the sentence with your suggestion. :)

**Comment by paramat** [comment]
:+1:

**Pull request merged**
