### PR TITLE
Standalone bundle for OSX (w/ dependencies!)

### PR DESCRIPTION
**Pull request by neoascetic**

### CODE REVIEW

**Comment by neoascetic** [comment]
Could someone help me test this on Windows please? Need to test that all dependencies are being copied to the package and it runs without any issues on clean OS without any of dependencies installed.

**Comment by nerzhul** [comment]
At first review, seems good for me

**Comment by neoascetic** [comment]
@ShadowNinja could you please review it? WIP and Testing labels are unnecessary now. Thanks.

**Comment by nerzhul** [comment]
pushed, thanks ca5df44edb1963d4c634390d33229ec928e284dc

**Comment by neoascetic** [comment]
Finally, thank you! :)

**Pull request closed without merging**
