### PR TITLE
Move object on_step execution to lua

### PR DESCRIPTION
**Pull request by HybridDog**
TODO:
* test if the object is removed (expose it to lua)

### CODE REVIEW

**Comment by nerzhul** [comment]
no. Please don't move this to pure lua, entities are shared between client & server and step is common to ALL entities and should be affected by same callback

**Comment by paramat** [comment]
:-1: Seems a bit extreme for a minor bug.

**Comment by HybridDog** [comment]
paramat, the bug can be fixed by adding a boolean to the entity which tells whether obj:remove() was executed.

**Comment by rubenwardy** [comment]
this is likely to be more performant, as it only switches between C++ and Lua twice overall, rather than twice for each step. But would need benchmarking

**Comment by HybridDog** [comment]
> But would need benchmarking

Yes, l need a situation in which a huge amount of objects causes lag with their on_step.
l tested it with a rather small amount of objects (32) in singleplayer, but the results were unusable, before the change executing the 32 steps in cpp took 0.25 ms and after the change it took 0.5 ms in cpp, l assume gcc noticed that the new luaentitysao step doesn't switch to lua and back and reduced the optimization balance from the cpp step function.

**Comment by nerzhul** [comment]
on JIT build maybe it can be better, but it's not the case in non JIT build, and also moving this to lua desync the step process from the entity step in a server loop process. The entity step should be synced with LuaSAO step.

If you want to know if an object will be removed there is already a flag m_pending_deactivation (if i remember), just expose it to Lua

**Comment by HybridDog** [comment]
> but it's not the case in non JIT build

People who don't use luajit usually don't care about performance, do they?

> The entity step should be synced with LuaSAO step.

No, the on_step in lua can take any time, whereas the time the LuaSAO step takes can be predicted (after the change). So optimizing the LuaSAO step and functions which call it may be improved.
And l remember modders having problems finding a bug because the bug occured in the on_step function of an entity and error handling didn't work there.

> as it only switches between C++ and Lua twice overall

lf you put the execution of registered functions to lua, it doesn't switch between c++ and lua more than without executing the on_steps.
https://gist.github.com/HybridDog/aeba934739beb29dc3b41892a55ed283

**Comment by nerzhul** [comment]
yes they need performance like any other people. Maybe a day we will upgrade to Lua 5.3 (i don't say we will do it, but it's possible that 5.1 will be deprecated at a moment and unmaintained).

on_step should be synced with entity itself as it's a callback for an active entity. If you are storing entity pointers in bad areas it's your code problem no engine problem. We provide API to real objects. 

Also if i remember Android (our more important population) is not using JIT.

**Comment by raymoo** [comment]
Oh, for some reason I was under the misunderstanding that on_step was already called from Lua.

**Comment by raymoo** [comment]
What if the C++, after processing all entity movement, called a Lua function that looped through all the entities and did their on_step? I don't think it matters too much whether an entity's on_step happens immediately after their movement or after all entities move.

**Comment by paramat** [comment]
> People who don't use luajit usually don't care about performance, do they?

They do. LuaJIT is poorly maintained and has memory usage issues, many have been forced to stop using it due to these issues and many consider it too much trouble to be worth using.
Because normal Lua is slower those who use it care more about its performance.

> l remember modders having problems finding a bug because the bug occured in the on_step function of an entity and error handling didn't work there.

That is no justification.

This seems a bad idea :-1:

**Comment by nerzhul** [comment]
I agree with closing, moving things to Lua is not an option we should stop trying to fix things by moving them to lua, it adds extra memory overhead, conversion overhead and moreover reduce possibilities to make minetest more performant if we want to do concurrent actions

**Comment by HybridDog** [comment]
> it adds extra memory overhead, conversion overhead

What's the overhead in this case?

> reduce possibilities to make minetest more performant if we want to do concurrent actions

If you make on_step concurrent, many mods would break l guess. So you'd rather add a function with a different name.

Anyway, l have no clue of this PR affects the overall performance.

**Comment by nerzhul** [comment]
sorry but minetest is not a Lua engine but a C++ engine extended by mods.

LuaEntity on_step is accurate with server loop, global step is less, also the overhead is simple: 1 extra Lua function pointer + 1 local variable per entity per loop step until Lua GC, also we loose any future interest with more intelligent Lua entities in core (like NPC i planed since months) because we loose the callback function.

**Comment by nerzhul** [comment]
Another point: the callback should be done at a precise moment of LuaEntitySAO::step and as you see it does an extra check you cannot do in Lua.

**Comment by HybridDog** [comment]
> And as you see it does an extra check you cannot do in Lua.

When you get objects with get_objects_inside_radius, you currently also catch those which have their remove() executed, that's a bug in my opinion. (The fix for the item double pick up is actually just a workaround)

**Comment by nerzhul** [comment]
For the item double pick up i will be glad to know where does it comes from, maybe item on ground should be LuaEntity child class in CPP permitting to do fast things (i implemented it with auto gathering like in minecraft)

**Comment by HybridDog** [comment]
When clicking a dropped item, a punch interact event is sent to the server.

The server then calls the on_punch function which adds the item to the player inventory and calls the remove() method of the object.
remove() does not instantly remove the object but tag it that it becomes removed (even not directly after returning from lua). So when get_objects_inside_radius() is executed, the object tagged as removed is also in this list (the bug).
The item_drop mod uses get_objects_inside_radius to find the items which can be remove()d and added to the player inventory. This caused the double pick up cheat.
To avoid the cheat, a workaround was added: The items are additionally tagged as removed in lua when clicking the item (the information about the item the object is carrying is removed).

After removing the object already, the removal is sent to the client.
#
The bug might alternatively be caused by players punching objects which are removed server-side but not yet client-side. But l guess it's the get_objects_inside_radius function.

**Comment by nerzhul** [comment]
okay, this is a desync between lua and core engine, it's why lua should extend C++ and not copy its objects... i see

**Pull request closed without merging**
