### PR TITLE
Registration dialog: Larger text field with scrollbars

### LINKED ISSUE #7022: First server join dialog is cut off
##### Issue type
 - Bug report
 
##### Minetest version
```
0.5.0-dev-87e08b1b
```

##### OS / Hardware
Operating system: GNU/Linux
CPU: x86_64

##### Summary
If you join a server for the first time, there appears a window with a warning. But the full text is cut off:

Cut off greeting text

##### Steps to reproduce
1. Join a server for the first time (new player name)

##### Considerations to fixing
When fixing this bug, keep translations in mind and please be generous with the space so other languages don't run out of space.

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #7022

XXL font:
reg_menu

Default settings:
reg_menu_regular

### CODE REVIEW

**Comment by nerzhul** [comment]
It's better, thanks.
I don't like all those static values in the code but it's better than before

**Comment by SmallJoker** [comment]
@Wuzzy2 I can see that you're not happy with the suggestion of using scrollbars but in combination with a slightly bigger text this should be acceptable. Extending the height of the formspec is surely possible but in my opinion this widescreen-format looks better.

**Comment by Wuzzy2** [comment]
Well, first of all, it's good to add the scrollbar automatically, obviously. This ensures you can always access the text. Like a fallback mechanism.

But for this particular dialog, you should still try to increase the height. Seriously, how can you possibly be against this? Having all text visible at once is better than having only a part of the text visible at once. The dialog does not compete with any other widget for screen space, so you can be fairly liberal.
Also, it's absurd that this fairly short text already requires a scrollbar.

A scrollbar should only appear if the screen height forces the dialog to become very small.

**Comment by SmallJoker** [comment]
> you should still try to increase the height.

The height is already raised from 90 to 120, which is a 33% increase in text space. The issue here is that the text is horribly aligned with a smaller font - even worse the bigger the formspec gets. It's absurd that we have to display that amount of text of which most of it is redundant. Luckily we have the possibility to center the text vertically, which allows (IMO) an acceptable text placement position.
If the space is still insufficient, we should better wait for another UI library to satisfy your desires.

XXL Font:
bildschirmfoto_2018-02-22_17-10-38
Default settings:
bildschirmfoto_2018-02-22_17-12-23

**Pull request merged**
