### PR TITLE
Backport for 5.9.1

### PR DESCRIPTION
**Pull request by SmallJoker**
PRs added according to https://github.com/minetest/minetest/pulls?q=is%3Apr+milestone%3A5.9.1+is%3Aclosed+sort%3Aupdated-desc

The commit order is the same as in master.

First number: 5.9.1 milestone PR
Second number: 5.9.1 milestone issue that it fixed
**X**: bugfix that is not part of the milestone

From oldest to newest

* 14962 **X**
* 15006 14972
* 15013 15011 (form name)
* 15003 14973
* 15016 (no issue#)
* 14963 (conflict: version number)
* 15034 (no issue#)
* 56123b2 15031
* 15007 14992
* 15044 **X**
* 15015 15008
* 15068 **X**
* 15064 **X**
* 15022 (conflict: protocol version)
* 15090 (conflict: use g_touchscreengui)
* 15094 (no issue#)
* 15079 **X**
* 15076 **X** (unsafety only; conflict: renamed variables)
* 14969 (not part of 5.10.0)
* 15111 15110
* 15122 15021
* 15123 15105
* 15124 commit 1. **X**
* 15128 **X**
* 15150 14999 (5.9.1 only. conflict: manual apply)
* 15098 15097 (conflict: use g_touchscreengui)
* 15087 14765 (maybe. merge conflict. manual apply of the first 3 commits (trivial))

If there are any stand-alone commits that need consideration, please let me know.

## To do

This PR is Ready for Review.

## How to test

1. The protocol version MUST BE SET to **45**
2. Do a functionality test

### CODE REVIEW

**Comment by sfan5** [comment]
"should be backported" list:
* a677d33bdffa110fe611e49e346c0bd99dafb5ca
* 3971b6afcc3dffc0d77c19dc1bb138a8ae0abfc9
* 538b8b9b3457bb492b2b10a4acf869ad0ca98c26
* 733a019bf5aefddb824e5643b791ca25fc620b03

"maybe" list:
* 5583831c40d51e5f63540ccfcda71b678564c21b
* 1298d6c0206a964f4f5cb5a94b8463340c7dbbf4
* 48e65ac846479c2712496851e635ef65b8e532b1
* e90ef85e7d8c9497585f1c413686a9f74da565e5

**Comment by red-001** [comment]
486dc3288d7b8e8c55bbc20dea11fef32fd7119b might be a performance improvement for mapgen.

**Comment by SmallJoker** [comment]
@red-001 Performance improvements are nice, but I don't think it's worth the effort to backport those for a patch release.

**Comment by red-001** [comment]
No worries, just thought I would flag it since it's a fairly small change. Actually if you look at the PR (#15114) the performance change is in a different commit from the non-pref changes - if that changes anything: ea804e7a4f4df2760f7bb1e4e80c73adf7699a9b

**Comment by sfan5** [comment]
> Perhaps I should remove 14969 because it also falls under that category

I disagree in this case. It fixes a regression that was accidentally introduced.

**Review by sfan5 — APPROVED** [review]
tested. works on Linux/X11

**Comment by sfence** [comment]
Ok, it is fine. Works also on macOS. Only a bad version of the Devtest game.

**Comment by sfan5** [comment]
note: we still have #15087 and #15098 in the milestone

**Comment by sfence** [comment]
There is a problem:

We have "green" from GitHub actions, but there are:

```
[FAIL] testStreamRead - 0ms

[FAIL] testGetModsWrongDir - 0ms

[FAIL] testGetModNamesWrongDir - 1ms
 
[FAIL] testIsBlockInSight - 0ms

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Unit Test Results: FAILED
    4 / 47 failed modules (5 / 298 failed individual tests).
    Testing took 7227ms total.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Error: Process completed with exit code 1.
```

in windows buuld: https://github.com/minetest/minetest/actions/runs/10762212193/job/29842270304

I see these errors also if I try Minetest on my laptop under Windows 11.

**Comment by appgurueu** [comment]
The CI is green because of https://github.com/minetest/minetest/blob/733a019bf5aefddb824e5643b791ca25fc620b03/.github/workflows/windows.yml#L124

This was explicitly disabled in https://github.com/minetest/minetest/commit/02fa33252a7d788ba3838ea1e99e802b36b496b4, suggesting that at least some of these unit tests have been failing for longer than this.

For two of them we have issues explaining why they are failing due to float precision issues & how we might fix them: https://github.com/minetest/minetest/issues/15119, https://github.com/minetest/minetest/issues/14879. I'm unsure about why `testGetMod*` ones are failing.

**Comment by wsor4035** [comment]
holding off on testing this till the windows build is resolved

**Comment by sfan5** [comment]
The windows build is fine, pick the MinGW one.

**Comment by wsor4035** [comment]
> The windows build is fine, pick the MinGW one.

tested, works

**Comment by rudzik8** [comment]
Tested on Linux Mint 22 with Linux 6.8.0-44-generic

**Comment by grorp** [comment]
Tested on Android 13, no unexpected problems found.

**Comment by sfence** [comment]
I have played this version for a few days on my M2 MacBook. It also looks fine.

**Comment by sfence** [comment]
I have a potential issue with this version. It has happened to me several times. I analyze it now, and it looks like it is not maintained by some mod as I think.
After some time of playing, Heart Bar goes away and gets back after reopening the game.
In my situation, the heart bar looks to be maintained by built-in Lua code.

**Comment by rubenwardy** [comment]
@sfence I don't see anything directly related to the statbars in the commit list, are you sure it's not also an issue in 5.9.0?

**Comment by sfence** [comment]
> @sfence I don't see anything directly related to the statbars in the commit list, are you sure it's not also an issue in 5.9.0?

I have no idea. It can be an older problem. This is the first time I see it.

**Comment by sfence** [comment]
Looks like this:
Screenshot 2024-09-15 at 16 55 43
Screenshot 2024-09-15 at 17 01 35

Now, I also try 5.9.0

**Comment by sfence** [comment]
@rubenwardy I just reproduced a very similar issue on 5.9.0 also.

**Pull request merged**
