### PR TITLE
[NOSQUASH] Two commits

### PR DESCRIPTION
**Pull request by sfan5**
first commit: fixes [a bug](https://irc.minetest.net/minetest-dev/2022-01-09#i_5919435) *and* adds a warning msg for a situation we currently can't resolve

second commit:
* wrap `os.setlocale` to disallow changing
* remove `os.tmpname`
* remove `core` table from **insecure env**

## To do

This PR is Ready for Review.

### CODE REVIEW

**Comment by appgurueu** [comment]
I don't like the first commit as it's impossible to detect the case occurring in order to resend the media later. Currently, I can work around the issue: If the callback is called for a player who wasn't connected at the time, the race condition must have occurred. I can then resend the media.

I don't like the second commit as it's overly restrictive. Granted, in a dev environment with modsec disabled (or in a requested insecure environment), everything would be available again. How can `debug.getinfo` be abused? It is immensely useful for debug purposes. If it's unavailable, external profilers like [this](https://gitlab.com/benrob0329/son_of_a_profiler) might cease to work.

I'd prefer fully keeping `os.setlocale` in order to be able to force certain locales for truly platform-independent mod behavior.

Removing `os.tmpname` is fine by me.

The `core` removal has huge potential for breakage. I believe there are mods who rely on `core`.

**Comment by sfan5** [comment]
> I don't like the first commit as it's impossible to detect the case occurring in order to resend the media later. [...]

It's true that no workaround is possible, but the callback doesn't help you in any way. When it's called that actually means the delivery was successful. In the case of the race conditions it ends up *not* being called (and no, detecting absence of a callback doesn't really work either).

> I'd prefer fully keeping os.setlocale in order to be able to force certain locales for truly platform-independent mod behavior.

And I'd prefer if mods didn't mess with things they have no business with.

> The `core` removal has huge potential for breakage. I believe there are mods who rely on `core`.

I think you misunderstood. `minetest.request_insecure_environment().core` is gone and any modder who thought this was a good idea was falsely thinking it is somehow secure.

**Comment by appgurueu** [comment]
> > I don't like the first commit as it's impossible to detect the case occurring in order to resend the media later. [...]
> 
> It's true that no workaround is possible, but the callback doesn't help you in any way. When it's called that actually means the delivery was successful. In the case of the race condition it ends up _not_ being called (and no, detecting absence of a callback doesn't really work either).

Alright, then add the warning. Thanks for clarifying.

> I think you misunderstood. minetest.request_insecure_environment().core is gone and any modder who thought this was a good idea was falsely thinking it is somehow secure.

I just remember reading mod code that used it a while ago, that's all. In most cases `minetest` could and should have been used instead. I'll grep through CDB releases to see if I can find something. Why not simply do `core = minetest`?

**Comment by sfan5** [comment]
> Why not simply do `core = minetest`?

This is the case and continues to be the case with this PR merged.

**Review by SmallJoker — APPROVED** [review]
LGTM. `os.setlocale()` still works as expected.

**Pull request merged**
