### PR TITLE
[WIP]Postprocessing Framework

### PR DESCRIPTION
**Pull request by ThomasMonroe314**
this is pretty much exactly what @numberZero  has done on #5932
I do have a feature planned that might bring this to another level.
I do NOT intend on implementing/keeping any type of postprocessing in this PR
All I want to do is create the framework for post-processing shaders to be built.

### CODE REVIEW

**Comment by ThomasMonroe314** [comment]
Now I need help because, at this point, it all compiles, but doesn't draw at all, there are no errors and I can't find where the problem is.

**Comment by rubenwardy** [comment]
Please do not steal other people's work without any credit whatsoever

**Comment by ThomasMonroe314** [comment]
@numberZero oh ok
@rubenwardy sorry I didn't realise that I was "stealing" his work.
I guess this is not needed.

**Comment by kilbith** [comment]
@numberZero Sorry, missed your message. It is indeed a good idea, and I was intending to implement a post-processing framework using framebuffers.

**Pull request closed without merging**
