### PR TITLE
Textures: New menu_header image

### PR DESCRIPTION
**Pull request by paramat**
Not quite happy with this yet, i might try adding a subtle brightness gradient for a more metallic look.
Letter shapes and shading are identical to the MTGame header.
Since this is the engine header it is intended to be abstract and universal, perhaps with a metallic look to imply an 'engine'.

### CODE REVIEW

**Comment by PilzAdam** [comment]
;_; Why always gray?

**Comment by kilbith** [comment]
:-1: Awful, sorry.

What about that ? 

header

**Comment by PilzAdam** [comment]
@kilbith too high-res. The low-res approach from @paramat is better.

**Comment by paramat** [comment]
Doesn't have to be grey, but is somewhat consistent with the previous.

kilbith i was inspired by exactly that, and even sampled the grey colour for mine.

**Comment by paramat** [comment]
I feel this needs stronger shading too to appear more shiny, and more defined against the light grey texture, i'll work on it.

**Comment by est31** [comment]
The color is ugly.

**Comment by est31** [comment]
:-1: to emphasize.

**Comment by paramat** [comment]
Yes i'm not happy with the texture, i might try a darker grey with a gradient

**Comment by BlockMen** [comment]
> Not quite happy with this yet ...

Why did you add the enhancement label then?

And :-1: from me aswell, this looks horrible.

**Comment by C1ffisme** [comment]
There seems to be a lot of debate on the header image. Why not make a post on the forum? We might have actual artists or graphics designers or people with really good aesthetics on there.

**Comment by donat-b** [comment]
:-1: The worst.

**Comment by C1ffisme** [comment]
This texture actually looks kind of... cheap. Okay, more than kind of. It looks *really* cheap. The design is just too bland, and the shading isn't very good. I actually like @kilbith 's outline better.

No offense meant, paramat.

**Comment by paramat** [comment]
Hm i opened this too early, before i was happy with it, and am paying the price =} Best i close this, i mostly agree with your comments.

**Comment by paramat** [comment]
> Why did you add the enhancement label then?

Blockmen that's obvious, it was intended to be an enhancement when improved, seems that by doing that you're just being unpleasant.

**Comment by BlockMen** [comment]
@paramat When even you (!) are not convinced by your work, then my question is legitim. Just the fact that it is different is no proove that it is an enhancement, intended or not.
Also, textures are always very controversial and depend on personal taste, labeling it as enhancement can cause protest. If you want take it as "just being unpleasant" then is that your problem.

**Comment by est31** [comment]
@BlockMen I fully agree: texture changes are very taste based, and labeling them enhancements is never a good thing.

I like @C1ffisme 's idea to do a contest on the forums. Of course after we agree that the old texture is bad :). Alternatively, we can have the old texture as normal contest entry, and if it "wins", nothing changes; like hmmmmm (I think it was him) suggested for the website. I however don't want to hold the contest, somebody else has to do it.

What do you think?

**Comment by kilbith** [comment]
I'd prefer a consultation of real artists rather than the frivolous plebs.

**Comment by BlockMen** [comment]
@est31 Sounds good to me, we could give it at least a try.

@kilbith and who would pay a real artist, or do you know one that would do that for free?

**Comment by kilbith** [comment]
Yes, there's one : Gambit. We extensively use his work in _game already. Alternatively, Kenney.

**Comment by rubenwardy** [comment]
Kenney has left this project, unless you can "invite" him back.

**Comment by paramat** [comment]
@BlockMen @est31 okay sorry to take it the wrong way but i can't understand this attitude.
The enhancement label is just to categorise a PR as something that is 'intended' to eventually be an improvement whether or not it actually is, or is considered to be by various people, or is a WIP. Most PRs are either 'enhancement' or 'maintenance' and i simply select the most suitable label.
> Just the fact that it is different is no proove that it is an enhancement, intended or not.
Also, textures are always very controversial and depend on personal taste, labeling it as enhancement can cause protest.

>  texture changes are very taste based, and labeling them enhancements is never a good thing.

These statements could be said of any PR. All PRs can be controversial and taste based, most are, there's usually someone who doesn't like it, this subjective attitude means no-one should ever use the label, therefore the label is obviously not subjective.

I attempted this header because i was encouraged by both PilzAdam and ShadowNinja, who both said they would like a shortened version of my MTGame header. Personally i'm fairly neutral and actually a little reluctant to take on the resposibility for possibly the most important image of the project.

**Comment by BlockMen** [comment]
>The enhancement label is just to categorise a PR as something that is 'intended' to eventually be an improvement whether or not it actually is, or is considered to be by various people, or is a WIP.

I disagree. The enhancement label should (like all labels) be given for a faster and better overview of the issues (and PRs) based on what they actually do. If it is not clear (or depends heavily on taste) it should be better be not labeled than "wrong". And for WIP, there is a label for ;)

IMO the "enhancement" label should be just added if at least the code adds 1.) new features (or improvements like speed up, etc) and 2.) has no regressions OR be considered by various ppl to be (like you said).

Ofc this is still not objective and (can be) based on personal taste, but textures are completly "taste based", there is nothing to measure their quality nor can they made be optional (unlike most code).

> Most PRs are either 'enhancement' or 'maintenance' and i simply select the most suitable label.

This definition makes the enhancement label useless at all, since a PR is an enhancement by definition (from the creators perspective).

**Comment by ShadowNinja** [comment]
Paramat's right.  "Enhancement" doesn't mean "perfect improvement that everyone can agree on", it just means that it's intended to be an improvement.  If it isn't an improvement you simply close it (after discussion).

I think that the image simply looks too bland.  You'll have a hard time coming up with something that doesn't look bland if you want to stay abstract and not use textures from mt_game though.

**Comment by BlockMen** [comment]
@ShadowNinja Wrong. If the intention "to be an improvement" is already enough then the label is useless at all, since nearly every pull request is intended to be an improvement an would get the label.

Also: textures are (more than code) taste based, so calling it per se an improvement is just "wrong".

Did you even read the discussion? I can't find any argument you would try to debunk...

**Comment by kilbith** [comment]
> textures are always very controversial and depend on personal taste

Art is a domain employing techniques and can be evaluated objectively. There are academies for that.

**Comment by BlockMen** [comment]
Art is always and in a special way taste based. Even if all art academies and 99% of the artist would say picture xy is "objectively" perfect, the/some ppl might still not like (or 1% of the artist).

Also, in which way is this relevant? Do we have an artist here that decides on our textures?

**Comment by kilbith** [comment]
My humble contribution...

capture d ecran de 2015-11-07 17-59-24

Raw image (128x16) : menu_header

Feel free to open a PR if you like it (hint : I won't).

**Comment by RHRhino** [comment]
@kilbith I like your version of the header. It's cute and it looks good! :+1:

**Comment by PilzAdam** [comment]
@kilbith looks too "industrial" to me. I'd expect something like this from technic_game.

**Comment by kilbith** [comment]
Yes the bolts were put to suit the theme of an "engine".

**Comment by ShadowNinja** [comment]
kilbith's texture is much better, I agree with PilzAdam on it beeing too "industrial" though.
I understand it's to make it look like an engine, but it seems like it's a bit too much.

**Comment by kilbith** [comment]
@paramat Thoughts on this ? ^

**Comment by kilbith** [comment]
Another try...

capture d ecran de 2015-11-09 16-12-54

Raw image (137x16) : menu_header

**Comment by BlockMen** [comment]
Although we have lowres/"pixly" textures a pixelart style header don't fit MT IMO. The whole UI is not more highres than pixelart style.

I would prefer a high(er) res header, more like @kilbith's first suggestion.

**Comment by ShadowNinja** [comment]
@kilbith: Your new texture isn't entirely generic, but I don't think we'll easily find a good one that is, and I like your new texture a lot.

**Comment by paramat** [comment]
@kilbith i like your first one, more universal so more suitable for an engine that might be running very different subgames. The industrial look suits the technical menu pages. Personally i prefer it to the current one.

**Comment by C1ffisme** [comment]
@BlockMen To be honest the UI of minetest needs to be changed completely. I'm getting tired of the font it uses, and the black boxes are a bit bland.

But, that's just my opinion.

**Comment by BlockMen** [comment]
@C1ffisme I guess most would agree that it needs an improvement, but just adding a completely different styled header won't "fix" anything.

**Comment by paramat** [comment]
Thinking about labels i now consider the 'enhancement' label unusable because everything can be considered this, so i don't use it anymore =)

**Comment by C1ffisme** [comment]
@BlockMen True, but we could use it as a start for a new style.

**Pull request closed without merging**
