### PR TITLE
Add find_surface_nodes_in_area Lua call which permit to only get the nodes which are under air nodes

### PR DESCRIPTION
**Pull request by nerzhul**
This permit to massively improve performance for mods like plantlife which needs to only know surface nodes

requested by @VanessaE

### CODE REVIEW

**Comment by C1ffisme** [comment]
Question : Can it accidentally return the floors of caves?

**Comment by nerzhul** [comment]
@C1ffisme yes, of course, but you have filters in this LUA call to prevent cave problem, like in find_area_nodes.

**Comment by ShadowNinja** [comment]
We use Lua, not LUA.  They're two separate languages (LUA is a fork of Lua with some extra language features).

**Comment by VanessaE** [comment]
I've given this a try and while it does seem to work, I can't be sure the mapgen is returning all of the blocks it should.  I am seeing patches and stripes of modified and unmodified terrain far out from the initial spawn point in my test map, and I'm pretty sure plants_lib can't do that, as it logs all blocks equally, and evaluates all logged blocks in the same manner.

**Comment by nerzhul** [comment]
Can you review @Zeno- and merge if okay ?

**Comment by nerzhul** [comment]
@VanessaE this patches doesn't play with mapgen, it only provide a block list, but filter content as you asked, if the upper node is CONTENT_AIR.

**Comment by ShadowNinja** [comment]
Apparently the `nodenames` (ahem, `node_names`) array holds surface nodes, not air nodes.  This means that most mods will have to generate a list of everything in minetest.registered_nodes that isn't `air` ar `ignore`.  This wastes a lot of time and memory.  Also, this only coulys `air` as a surface node.  Not other unwalkable nodes.  Some games, like moon games, have a special air node, while `air` is actually empty space.

**Comment by nerzhul** [comment]
Right, and i also noticed that we must ignore nodes which are air themselves, returning them is useless here too.
For the check one above it's perfectly normal, because the goal of this fucntion is to check if the upper node is air.

**Comment by paramat** [comment]
Mgv5 and mgv7 provide 'heightmap mapgen objects' which are usable within 'on generated', it might be possible to make mgv6 create a heightmap too, this would be the fastest way but of course only usable within 'on generated' immediately after a mapchunk is generated.

**Comment by paramat** [comment]
The correct way to find surface nodes is to search downwards in each column for the first walkable node, see 'Mapgen::updateHeightmap' in mapgen.cpp, perhaps that function could be used to do what you want?
I realised if i add a heightmap to mgv6 this can be used to stop large caves being generated above ground level, which may reduce the shadow bugs in mgv6. I'll probably work on this.

**Comment by VanessaE** [comment]
If you do that (search downward), this function will not be able to return surface nodes inside of caves (e.g. the floor thereof).

**Comment by nerzhul** [comment]
We need all surfaces nodes, not upper surfaces nodes :)

**Comment by nerzhul** [comment]
I rebased and don't return AIR_NODES which are under AIR_NODES, then we only have there blocks under AIR nodes.

**Comment by paramat** [comment]
I see, i misunderstood. Perhaps better to return all walkable nodes under non-walkable nodes? Since that is the current way to find surfaces in the code.

**Comment by VanessaE** [comment]
You don't want to do that either, because from time to time, you may need some non-walkable nodes to be returned as "surfaces" if they are themselves the target of a further operation - water for example, to generate lilies or similar on top.

**Comment by paramat** [comment]
Good idea.

**Comment by Zeno-** [comment]
The bug VanessaE noticed is unrelated

commit 0f556d0c7f8c98c7209416577aae4fcc0c1c2b32

NOTE: Changed the name of the Lua call in the commit immediately after: commit fdb9140825716be49c99e6a27bb123432b9cb285

**Pull request closed without merging**
