### PR TITLE
TouchScreenGUI: Replace buttonbars with grid menu

### LINKED ISSUE #7622: Combine the two menus on Android into one
There are two menus on Android:

* ... on the left for chat, inventory, and drop item
* gears on the right for settings

I'd like to see this combined into one menu on the right which covers the whole screen in a grid. Double tapping where this menu is should open then close it, as the position when the menu is opened should change into a cros to close it

### PR DESCRIPTION
**Pull request by grorp**
This PR resolves #7622. "Auto hide button bars" are removed and replaced with a single fullscreen grid menu.

https://github.com/user-attachments/assets/f19a06b1-e5c8-457e-8cf7-aa0ea7600fc1

- The biggest UX benefit is probably that users no longer have to guess what the icons do. Instead, there's a title below each icon.

- To reduce the disruption to the game caused by the menu, closing the menu doesn't absorb the touch event. This means you can close the menu and  e.g. start dragging the joystick again with the same tap.

- Getting rid of "auto hide button bars" allows me to massively simplify my touchscreen layout editor.

- With my touchscreen layout editor, the menu will be used as an overflow menu. The user will be able to add/remove buttons on the main screen. All buttons that are not on the main screen will be shown in the overflow menu.

- Since the menu is fullscreen, you can no longer e.g. continue holding the joystick while dropping an item. With a touchscreen layout editor, this will be less of a problem since users will be able to move frequently used buttons to the main screen.

## To do

This PR is a Ready for Review.

## How to test

Use the touch controls.

### CODE REVIEW

**Comment by Zughy** [comment]
I think the UI should be completely rethought (e.g. what happens when aux2 gets implemented?) but this is an improvement

**Comment by grorp** [comment]
Screenshot with new icon:

screenshot

**Comment by okias** [comment]
Thank you! Looks amazing.

**Comment by srifqi** [comment]
Suggestions (for next PRs?):
- Show the status text above the grid menu
- Still able to control the joystick if it has been pressed before opening the grid menu

**Review by SmallJoker — APPROVED** [review]
Works on Android 6.

**Pull request merged**
