### PR TITLE
FormSpec: 9-slice images, animated_images, and fgimg_middle

### LINKED ISSUE #9649: Add 9-sliced image[]
We have `button9[]` and `background9[]`, so the logical extension of this is to add `image9[]` (and maybe `animated_image9[]`).

`image9` is like `image[]`, except that is uses 9-sliced image, just like `button9` and `background9`.

### PR DESCRIPTION
**Pull request by v-rob**
Welp, sorry about this being in a new PR rather than reopening #10265, but GitHub's unhappy that I force pushed it to rebase before reopening.  So, here's a new one, with the review comments from the last one addressed.

---

This PR closes #9649 by adding an extra optional parameter to `image` and `animated_image` defining the 9-slice rect for the (animated) image to use.  It does _not_ make `image9` and `animated_image9`; `background9` is just an alias to `background` to allow old clients to not display errors before formspec versioning existed.  In addition, it also adds the `fgimg_middle` style property for image buttons

gif

## To do

This PR is Ready for Review.

## How to test

The above screenshot:

```lua
[[
formspec_version[4]
size[9,9]
style_type[button;bgimg=air.png;bgimg_middle=1]
label[1,0.8;bgimg_middle]
button[1,1;3,3;;]
style_type[image_button;fgimg=air.png;fgimg_middle=1]
label[5,0.8;fgimg_middle]
image_button[5,1;3,3;;;]
image[1,5;3,3;air.png;2,1]
label[1,4.8;9-slice image]
animated_image[5,5;3,3;;]] .. minetest.formspec_escape("[combine:16x32:0,0=air.png:0,16=ignore.png") .. [[;2;1000;1;1]
label[5,4.8;9-slice animated_image]
]]
```

Also make sure that all rect types work.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
What's `minetest.dmp`? Sounds like debugging info to me.

**Comment by v-rob** [comment]
Oh shoot, not again.  I hate how Visual Studio dumps these things all around...

**Review by rubenwardy — APPROVED** [review]
tested

**Review by ghost — APPROVED** [review]
Looks like this properly resolved my reviews from the original pr. From a quick test covering a few 9-slice mods and a small amount of test code it looks like everything is still works as expected, and the documentation is up to date.

**Comment by kilbith** [comment]
I'm trying to use the 9-slice property to an image of 400x400 px: https://github.com/minetest-mods/i3/blob/main/textures/i3_slot.png whose their corners are 60 px wide.

The following element:

`image[1,1;1,1;i3_slot.png;60]`

Results in:

Capture d’écran du 2022-07-03 23-03-06

Am I doing something wrong?

**Comment by Df458** [comment]
> Am I doing something wrong?

I think that's up to interpretation. What's happening here is that the edges are larger than the space available, and are overlapping as a result. I can think of 3 possible ways a 9-slice feature could handle this:
- Current behavior, overlap as needed.
  - Pros: Simple
  - Cons: See screenshot above
- Slice edge textures as needed
  - Pros: Works better with transparency, since there's no overlap
  - Cons: Can still look bad depending on the texture
- Scale down 9-slice texture to fit properly
  - Pros: Consistent use of full edge/corner texture regardless of sizes
  - Cons: Kinda defeats the point of 9-slices, since they're supposed to be a way to not scale border textures... though the worst of this can be alleviated a little by scaling consistently on both axes, it's still a compromise at best
- Use size to denote the size of the central slice, and expand the edges from those coordinates
  - Pros: Rendering is always perfect
  - Cons: You are now living in layout hell

Anyway, I've tested this in a pre-PR release and I can confirm that **this is not a regression**.

We're currently using the worst approach for your use-case, but sadly there's no 'good' way to 9-slice with edges larger than the content...options 2 or 3 would probably give you what you expect, though 2 might also just break super-hard depending on the size. 4 would give the best-looking results, but the background would also be roughly 4x larger than you expect sooooooooo~

With that said, I am open to PRs that change the method we use if it's well-justified.

**Comment by Df458** [comment]
To expand on that up to interpretation point, it really depends on what your use case for this 9-slice is.

If your border value is very large because this is meant for large elements (say, 3x3+) then you're doing it right and should see vastly better results at that scale.

If your border value is very large because this is meant to scale to fit small elements, then you're doing it wrong because 9-slice requires the source texture's border to match the desired rendered output and the image should be pre-scaled accordingly.

If your border value is very large because you want it to fit a wide variety of element sizes...¯\\\_(ツ)\_/¯ You'd be right with a 9-slice system that uses the 3rd approach, and wrong in other approaches. But that leads to questions like "is the approach wrong?" so it's not black and white. Such a use-case is not really compatible with how 9-slices typically function, so it may not even be the right feature in that case.

So as you can see, without knowing more I can only give a vague shrug of an answer

**Comment by kilbith** [comment]
Solution that works for me:

```Ruby
image[1,1;1,1;i3_slot.png^\\[resize:128x128;9]
```

Texture size is 512 px (with corners of 38 px), resized to 128 px (corners are now `floor(38/4)` px).

**Pull request merged**
