### PR TITLE
Menu header: Remove gaps

### PR DESCRIPTION
**Pull request by paramat**
screenshot from 2017-07-20 22-51-21

screenshot from 2017-07-24 18-54-32

^ 1280x720

The menu header was created from my MTGame header but with gaps added, which i never liked.

### CODE REVIEW

**Comment by SmallJoker** [comment]
I quite like these gaps we have right now. The render size modification is hacky this way and should be properly solved in C++ IMO.

**Comment by paramat** [comment]
> The render size modification is hacky this way and should be properly solved in C++ IMO.

Good point, ok will remove padding then we can work on size code also.

**Comment by paramat** [comment]
Done, we will need to work on sizing code as the header gets too big when using large window sizes, and overlaps the tabs.
Maybe i'll do that in this PR, not sure yet.

**Comment by paramat** [comment]
Closing, gaps were approved before and i'm not too bothered by them.

**Pull request closed without merging**
