### PR TITLE
Make world creation menu automatically generate a random world name

### PR DESCRIPTION
**Pull request by lisacvuk**
Why?
When making map generator mods, you need to recreate a world every time you make a change. Or make a new world. Which ends up in this.
```
lisac@Pingus-PC:~/.minetest/worlds$ ls
ssss              ssssssssssssssssssssssssssss  ssstttttttt  test            tsssttttt      tttt                         tttttttttttttttsssssssss
sssss             sssttt                        sststs       tssssssssttttt  tsstststststs  ttttttsssssssssssssssssssss  tttttttttttttttttttttttttttttttttttttttttttttttt
ssssssssssssssss  sssttttt                      stttssss     tsssstttt       tttsss         ttttttttttttttt
```
It is also a nice feature to have so that players don't spend 10 minutes picking a perfect name for their world. They can still choose one, of course.

### CODE REVIEW

**Comment by rubenwardy** [comment]
About about including the creation date iOS style?

**Comment by lisacvuk** [comment]
I think this is shorter and looks a bit nicer. I can do that though if people prefer it.

**Comment by nerzhul** [comment]
i have a name generator cpp class if needed, it can be used for mods with custom names on npcs for example

**Comment by lisacvuk** [comment]
That seems a bit of an overkill. This is simple, fast, and it works :P

**Comment by paramat** [comment]
Yes useful for me, i get tired of typing random names when rapidly starting new worlds (which happens a lot). Since this is mostly for dev work the names don't have to be carefully created.

**Comment by paramat** [comment]
Does the random name appear already present in the field? I hope not.
I assume there is already a check for if a duplicate random number is created.

**Comment by paramat** [comment]
Yes see #5589

**Comment by paramat** [comment]
Also, 'Unnamed' is better because in MT worlds have 'names' not 'titles'.
That other PR is being delayed due to it being based on a refactor (ugh), i'll ask the author if they will split it into a new PR, if they won't or are slow and if you want, you could submit that 2nd PR yourself.

**Comment by lisacvuk** [comment]
Updated, it also names worlds 'Unnamed' instead of 'Untitled'

**Comment by paramat** [comment]
Seems good but i need to test.

**Comment by neoascetic** [comment]
Let's implement [something like this](https://github.com/bearjaws/docker-names/blob/master/index.js), it is easier to remember and funnier :)

**Comment by nerzhul** [comment]
@neoascetic my name generator permits to generate name based on syllables it permits to have Caputera for example as a randomly generated name or Trokivol :D

**Comment by lisacvuk** [comment]
I'll make it generate funny names if people want it to. I appreciate the challenge :D

**Comment by lisacvuk** [comment]
Now generates World+ISO time. I can revert if needed.

**Comment by nerzhul** [comment]
i don't really like the date, it's not very game friendly, too technical for end users, a neutral name is better

**Comment by lisacvuk** [comment]
Reverted. Any further requests?

**Comment by paramat** [comment]
Date is no worse than a random 5 digit number.

**Comment by SmallJoker** [comment]
If using dummy names, then they should be descriptive: `Unnamed_mgv6_20170807_{random}`

**Comment by lisacvuk** [comment]
Can you please agree on one thing to do? I can't do all of those. :)

**Comment by paramat** [comment]
I recommend keeping it as it is, just a simple random number, then once merged we can change it if necessary.
I'll test then +1 this as it is.

**Comment by paramat** [comment]
:+1:

**Comment by Fixer-007** [comment]
This needs improvement, I agree with Krock about making it more descriptive, also Unnamed00001 is just horrible naming. Something like World_mgv6_20170807_{random} is much better IMO.

**Comment by paramat** [comment]
Date is not very useful as this is mainly for devs who rapidly create multiple worlds (and delete them again) in one day.

**Comment by lisacvuk** [comment]
I'm assuming people looking to play the game will probably choose a name; maybe even won't be aware of this feature. It is mainly for mapgen mod devs.

**Pull request merged**
