### PR TITLE
Fix player controls only being applied for the first move

### LINKED ISSUE #1460: Footstep sound repeats on ladders (and rapidy in other situations)
When you hold shift on a ladder - you reached the bottom - then it plays the "footstep" sound again and again.

Low priority

### LINKED ISSUE #10136: Jumping in 5.3.0 feels different than previous versions
##### Minetest version
```
5.3.0 release candidate 2 (e99415e0c5ae4a89907424d0f5f9f48ab94efbfa)
```

##### OS / Hardware
Operating system: Windows 10

##### Summary
Try jumping up a steep slope around 45 degrees by holding the jump button.  In 5.2.0 and below, jumping up the slope is faster as the player kind of jumps off the edge of the node.  In 5.3.0, if you jump up the same slope, the player does not jump off the edge of the node and has to squarely land before jumping again.  Consequently, jumping is much slower.  It's easy to tell if you try it yourself, but harder to describe.

This is also easily noticeable if you aim the mouse downwards and built a tower with nodes while constantly holding the jump button.  Much slower.

I would consider this a bug because some specifically-timed jumping things, e.g. an Inside the Box thing where you have to run fast up a slope before the door closes, will not work due to the slower jumping.  Plus, it just _feels_ wrongs when you're used to moving faster.

### PR DESCRIPTION
**Pull request by sfan5**
suggestion from https://github.com/minetest/minetest/pull/9891#issuecomment-634490776 (hence the commit also has @TheTermos as author)

fixes #10136, also fixes #1460

## To do

This PR is Ready for Review.

## How to test

Attempt to do this: https://0x0.st/iyX8.mp4
If this movement is possible, the PR works correctly.

### CODE REVIEW

**Comment by Zughy** [comment]
I've just tried but best case scenario it works for just 2-3 blocks, then it starts glitching again. I tried looking at different angles, same

**Comment by SmallJoker** [comment]
This PR improves "staircase" jumping a lot - especially in combination with #10025.
Though with higher walking speeds - for example 5 m/s - results in a wave-like movement (difficult to explain).
Whereas this is less smooth than seen in 5.2.0(-dev) I think it's a good improvement to the master behaviour.

**Comment by paramat** [comment]
Wow, i am impressed this fixes #10136 
Will test.

**Comment by paramat** [comment]
Probably needs lots of testing as movement changes are dangerous.
I will test slope climbing.

**Comment by TheTermos** [comment]
Controls being applied to every move can be already achieved in all versions of MT by setting fps to 105 and making sure the machine can handle steady 100+ (e.g flat mapgen with no deco) so this change shouldn't break anything unless something really weird is going on.

**Comment by v-rob** [comment]
Appears to keep the old behaviour perfectly fine; thanks!

**Comment by paramat** [comment]
TheTermos, that is good to know.

Just did a quick slope climb test of this PR, slope climbing is good, no noticeable difference to classic behaviour.

**Comment by SmallJoker** [comment]
Sneak glitch works, jumping works. What else needs testing?

**Comment by paramat** [comment]
Maybe merge it and release another 'release candidate' build and ask for a week of testing?

**Comment by sfan5** [comment]
If players with 100+ fps have already been testing "this" fix I don't think being so cautious about it is necessary.

**Comment by FriendlyGamer** [comment]
> If players with 100+ fps have already been testing "this" fix I don't think being so cautious about it is necessary.

I agree, in my opinion of this being available for the last 72 hours or so and if such "aggressive" testing was already completed why worry about it any more than people have to right?

**Comment by paramat** [comment]
Ok, that is fine by me, i do not understand the change as much as others do so was probably overcautious.
So anyway, lets merge this now. I would like to approve it but think that is unwise before i understand it well. Perhaps SmallJoker can approve?

**Comment by oilboi** [comment]
Tested and an fps difference changes whether or not it works: https://youtu.be/7e7AW8kY4G0

**Comment by sfan5** [comment]
Fast-climbing works for me with <30fps: https://0x0.st/iyvT.mp4

**Comment by v-rob** [comment]
Works for me the same in 60, 30, and 10 FPS.  I can't test above 60 (my computer isn't that fast), but I would assume that it works if 60 does.

**Comment by FriendlyGamer** [comment]
> Works for me the same in 60, 30, and 10 FPS. I can't test above 60 (my computer isn't that fast), but I would assume that it works if 60 does.

Probably not _much to worry about if_ it does requires serious computing power. Not everyone happen to have an I9 10900K with NVMes after all. Though you _might_ be able to push some more frames if you set your view lower and reduce graphic loads.

**Comment by paramat** [comment]
Tested at 25 FPS, still works as intended.

**Comment by random-geek** [comment]
Yay!

**Pull request merged**
