### PR TITLE
Credits: Remove my name

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by PilzAdam** [comment]
Why?

**Comment by Rui914** [comment]
I'm not active.

**Comment by PilzAdam** [comment]
Move to "Previous Contributors" then?

**Comment by Rui914** [comment]
I'm far from "contributor".
So, I feel the pressure.

**Comment by kwolekr** [comment]
Well, okay... if that's what you want.

**Comment by est31** [comment]
Note that many people listed as "contributor" don't contribute more than you. But if this is what you want...

**Comment by est31** [comment]
Merged df2c474d19c751bb1ee25c0a11e52490b909c06b

**Pull request closed without merging**
