### PR TITLE
LuaEntity: Depend collision on entity size

### PR DESCRIPTION
**Pull request by SmallJoker**
This PR is an attempt to prevent small LuaEntities from glitching into nodes, see #5966 and #5482.
It could be that TNT itself already places the entities into solid nodes.

EDIT: This PR does not prevent item entities from glitching into nodes (like with TNT), as they switch to `physical=false` once they're on solid ground to prevent superfluous collision detections.

### CODE REVIEW

**Comment by Fixer-007** [comment]
At least this happens: https://i.imgur.com/Ilghi28.png (github image attaching is broken for me)

**Comment by SmallJoker** [comment]
I'm afraid this isn't going to be fixed easily. Even when moving items slowly using
```Lua
	on_rightclick = function(self, clicker)
		if not clicker or not clicker:is_player() then return end
		self.object:set_velocity(clicker:get_look_dir())
	end,
	set_item = function(self, itemstring)
```
in `builtin/game/item_entity.lua`, the collision seems to be handled after adding the velocity to the last position.

**Comment by Fixer-007** [comment]
Relevant https://github.com/minetest/minetest/issues/5966#issuecomment-308541191

**Comment by SmallJoker** [comment]
Main issue fixed by another PR.

**Pull request closed without merging**
