### PR TITLE
Optimize PNG files

### PR DESCRIPTION
**Pull request by Bituvo**
Yet another trivial PR. I ran all of the PNG files through the minetest_game optimizer. I'm not sure how many kilobytes I saved, but I know it's more than one.

### CODE REVIEW

**Comment by oong819** [comment]
what's the different between optimized PNG and lossless compressed PNG?

**Comment by fluxionary** [comment]
> what's the different between optimized PNG and lossless compressed PNG?

the resulting image is identical, but the files are smaller. see https://linux.die.net/man/1/optipng

**Comment by Montandalar** [comment]
@Bituvo It looks like you have merged master into this branch. This project prefers the rebase workflow, where if a branch needs to be updated, it should be rebased and force pushed instead of merging master. This keeps the history cleaner. See: [.github/CONTRIBUTING.md](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#reviewing-pull-requests)

**Comment by sfan5** [comment]
FWIW it doesn't really matter what the contributor does to their branch since changes are squashed upon merging anyway.

**Comment by HybridDog** [comment]
The texture changes increase the repository size because both the old and new versions are saved in the history, and the texture sizes are probably not optimal, so a future recompression may further decrease texture sizes and increase the repository size.

I suggest to keep only file changes where the size reduction is at least 70% and to recompress them more aggressively with oxipng and advpng.
```bash
changed_files=$(git diff --name-only master...)
for f in $changed_files; do
	size_old=$(git cat-file -s "master:$f")
	size_new=$(git cat-file -s "@:$f")
	if ((size_old * 7 > size_new * 10)); then
		echo "$f"
	fi
done
```

```bash
# Requires imagemagick, oxipng and advpng

png_shrink() {
	file=$1
	size_initial=$(stat --printf='%s' "$file")
	size_prev=$size_initial
	while true; do
		if [[ $(convert "$file" -format "%[opaque]" info:) == "False" ]]; then
			# There is an alpha channel. Keep colour in transparent pixels.
			oxipng --nc --opt max --zopfli "$file"
			oxipng --nc --opt max "$file"
		else
			advpng --shrink-insane --recompress "$file"
			oxipng --opt max --zopfli "$file"
			oxipng --opt max "$file"
		fi
		size=$(stat --printf='%s' "$file")
		if [[ "$size" -eq "$size_prev" ]]; then
			break
		fi
		size_prev=$size
	done
	if [[ "$size_initial" -eq "$size_prev" ]]; then
		echo "No size reduction"
	else
		size_initial_ie=$(numfmt --to=iec-i "$size_initial")B
		size_final_ie=$(numfmt --to=iec-i "$size_prev")B
		echo "Size reduced from $size_initial_ie to $size_final_ie"
	fi
}

# Shrink only images which are small enough
png_shrink_large() {
	threshold=$1
	shift
	for f in $@; do
		num_pixels=$(identify -format '%[fx:w*h]' "$f")
		if ((num_pixels < threshold)); then
			echo "$f"
			png_shrink "$f"
		fi
	done
}

changed_files=$(git diff --name-only master...)
png_shrink_large 1000 $changed_files
```

**Comment by Emojigit** [comment]
Even if the git repository size is larger, the release sizes will be smaller. From an end-user point of view, I think it is good to have the textures compressed.

**Review by sfan5 — APPROVED** [review]

**Comment by Bituvo** [comment]
Will do.

**Comment by ExeVirus** [comment]
hate to bring this up, I wrote the optimize script a while back - just wanted to clarify a few things:
1. gorp: that should be exhaustive search, not heuristic based, so the only reason that you would get different results is possibly optipng version
2. HybridDog: careful - I had to modify the optipng (tried advpng, got same results) and how I do my script to ignore certain kinds of optimizations that break rendering of certain textures on AMD built-in GPUs. Really painful bug for some, really hard for us to test so we just avoid it by trusting that script haha.

**Pull request merged**
