### PR TITLE
Wieldmesh: Natural orientation depending on pitch

### PR DESCRIPTION
**Pull request by sfan5**
reopening #5175 wasn't possible, so here's this

> Demo : https://youtu.be/m2-Msf_nZw0 but best testing it yourself.

### CODE REVIEW

**Comment by VanessaE** [comment]
:+1:  but make the effect stronger - maybe halfway off of the screen at most, perhaps configurable.

**Comment by DS-Minetest** [comment]
Perhaps add a setting for how strong it is.

**Comment by SmallJoker** [comment]
No, adding a setting for this little effect is over-engineered. IMO fine as it is right now.

**Comment by sofar** [comment]
👍

**Pull request merged**
