### PR TITLE
Better enable_damage=false / 'immortal' group fix

### PR DESCRIPTION
**Pull request by sfan5**
This is essentially the better solution to #9022.

People keep running into(*) subtle issues because they are using an outdated version of 3d_armor.
But, subtle issues are bad because it doesn't provide a obvious indication that something went wrong and people are inclined to blame the engine instead of the <i>n</i>-year old mod they just installed from god knows where.

So instead this PR adds code to preserve the `immortal` group (it throws a warning instead).

(*) References:
- https://forum.minetest.net/viewtopic.php?p=360051#p360051
- https://forum.minetest.net/viewtopic.php?p=388908#p388908
- https://github.com/minetest/minetest/issues/9159
- https://github.com/minetest/minetest/issues/10161
- https://github.com/minetest/minetest/issues/9788#issuecomment-766514513

## To do

This PR is a Ready for Review.

## How to test

* Join a world with damage disabled
* Run `//lua local p=core.get_player_by_name("singleplayer");p:set_hp(0);p:set_armor_groups({})`
* Find that damage is still disabled and that the world still loads

### CODE REVIEW

**Comment by SmallJoker** [comment]
I don't like in particular that the immortal group is force-enabled in this case. I know that it's the most important part of this PR, but that would disallow mods to introduce PvP arenas (of some sort) or minigames on creative servers.

It definitely will solve all issues regarding outdated 3d_armor installations but I don't think adjusting the engine to fix old mods is the right approach.

**Comment by sfan5** [comment]
Well, the [current documentation](https://github.com/minetest/minetest/blob/3fa82326071d01b74b127d655578e2d17d20bfee/doc/lua_api.txt#L1747-L1749) is vague (and also incorrect) on what removing the `immortal` group should do.
For example the statbars will never appear when `enable_damage = false` regardless of the armor groups, the `/kill` command also assumes that players cannot be killed when damage is disabled.

The obvious alternative is to properly support per-player damage. This would be a bit more work but I can change this PR if that is the preferred approach.

**Comment by SmallJoker** [comment]
I see. Looks like there are more issues than 3d_armor alone. Since this is a server-side only feature, I'd agree keeping this PR as-is until the engine is *really* ready for per-player damage on `enable_damage = false` servers.

**Review by SmallJoker — APPROVED** [review]
LGTM

**Pull request merged**
