### PR TITLE
Get rid of `basic_debug` last minute

### PR DESCRIPTION
**Pull request by sfan5**
Changes kept minimal on purpose.

addresses #12011

### CODE REVIEW

**Comment by appgurueu** [comment]
What about all the translation files that mention `basic_debug`?

**Comment by sfan5** [comment]
Nothing. The string still exists but is simply unused.

**Review by SmallJoker — APPROVED** [review]
Works.

**Comment by appgurueu** [comment]
Why not actually grant `basic_debug` by default instead of entirely disabling this feature? Should be less code and more features, win-win.

**Comment by Wuzzy2** [comment]
Tested, works.

**Comment by SmallJoker** [comment]
@appgurueu Grant by default does (afaik) not affect existing players, and changing `default_privs` does not work on servers which have this variable specified in a configuration file. There would be no way to explicitly disable the auto-grant without a separate setting which is IMO the wrong approach to this features. Mod-controlled HUD flags would fit better into games to make changes on a per-player basis.

**Review by x2048 — APPROVED** [review]
Looks good. Would you want to make has_basic_debug global ans change to ALLCAPS (const)?

**Comment by sfan5** [comment]
This change is largely temporary so I don't think that's needed.

**Pull request merged**
