### PR TITLE
Added support for the Logitech F310 game controller

### PR DESCRIPTION
**Pull request by herbert-west2**
**NOTE: please view my latest comment for updates on this discussion / pull request :)**

I got this information by poking around in Wireshark and also with some experimentation with the code.

I've tested it, and it works.

### CODE REVIEW

**Comment by herbert-west2** [comment]
Here's a video of me playing the game using the controller. (The only thing that I used the mouse + KB for was for interacting with forms)

https://user-images.githubusercontent.com/108707524/196834607-8b630640-23f1-4408-97f5-ed55d99546fa.mp4

**Comment by herbert-west2** [comment]
Here's a video of me playing the Subway surfers game from the ContentDB marketplace with the MODE button in the middle of the controller engaged

https://user-images.githubusercontent.com/108707524/196839614-673b449d-ca47-41ec-947a-54ac76d8676c.mp4

**Comment by rubenwardy** [comment]
Minetest's gamepad support sucks. I recommend using an external program, that will allow you to use UIs as well: https://wiki.minetest.net/Gamepads

**Comment by herbert-west2** [comment]
Okay, so I have discovered something interesting that interferes with the current suitability of my pull request. This morning, I connected an XBOX controller to my PC and was surprised to find that the formats sent over USB for the Logitech and the XBOX controllers were identical.

I suppose that this means that the pull request must be re-done before it is suitable for acceptance. I do not know what format on the controller would be most satisfying for the user-base here, so perhaps there should be discussion about that prior to the code re-working. I have attached an OpenDocument spreadsheet to this post containing a description of the format that _I_ chose. If you have any qualms with this format, or there is already an established format that I do not know about, please let them known so that I can change them. :)
[MINETEST CONTROLLER INFO.ods](https://github.com/minetest/minetest/files/9832964/MINETEST.CONTROLLER.INFO.ods)

**Comment by herbert-west2** [comment]
In addition, I have a lot of free time on my hands and would love to give attempting to add full controller support a go. It will probably take more than a month to figure out, but hopefully I have something to show in a fork soon.

**Comment by rubenwardy** [comment]
The bindings vary based on the controller model, the OS, and the computer. It's unpredictable and completely broken

The solution is to use SDL_GameController. It gives you the xbox-like bindings for a large number of gamepads. SDL is supported and recommended by Steam, Valve use it for input for their games.

I have a branch where I've started this work, but I'm currently stuck as my gamepad driver keeps crashing. https://github.com/rubenwardy/minetest/tree/sdl_game_controller

**Comment by herbert-west2** [comment]
Interesting. I'll give it a look. Hopefully I can get something useful going.

**Comment by herbert-west2** [comment]
> I have a branch where I've started to implement use of SDL_GameController, but I'm currently stuck as my gamepad driver keeps crashing. Starting Minetest with this patch causes my gamepad to disconnect. Here's the branch, maybe you can get it to work: https://github.com/rubenwardy/minetest/tree/sdl_game_controller You need to compile with Irrlicht-Mt SDL2

I tried compiling your repo's branch, and indeed, there was a crashing problem. However, I cloned the normal Minetest repository and compiled it with Irrlicht-Mt SDL2, then copy-pasted your new joystick code in, and there was no crash. Trying with a fresh clone of the regular repo seemed to fix the problem.

However, the joystick code is a bit incomplete. It's nice to see *something* working, however. It's late, so I don't want to do anything else tonight, but perhaps I will put all this into a fork tomorrow and perhaps start fleshing out the joystick code a bit.

**Comment by herbert-west2** [comment]
I got your additions to build. When building this repo remember to checkout the sdl_game_controller branch and to use the irrlichmt SDL2

https://github.com/herbert-west2/minetest/tree/sdl_game_controller

Here's a video of it in use. (The joystick does not appear to support moving head or player yet; any movement of that type was from mouse. Jumping and zooming works, though.)


https://user-images.githubusercontent.com/108707524/197274032-22d405aa-359f-4829-87eb-1a16c46d699a.mp4

**Comment by rubenwardy** [comment]
Looks like I never got as far as implementing axes, so that sounds right. I'll try updating using the latest code and see if that solves my problem

**Comment by rubenwardy** [comment]
I no longer have the controller disconnecting issue, so I should be able to continue to work on it now

**Comment by herbert-west2** [comment]
That's great! :)

**Comment by rubenwardy** [comment]
Ok, movement/looking now works. I've also finished up support for all buttons, including dig/place

**Comment by herbert-west2** [comment]
Wow, this is great! Thank you!!!

**Pull request closed without merging**
