### PR TITLE
fix #2876 (fix player teleportation bug)

### LINKED ISSUE #2876: player:setpos and player:moveto do not really teleport player when player is sneaking
If you use `player:setpos(some_position)` or `player:moveto(some_position)` on the player object `player`, the player is not really set to `some_position` under these conditions:

* The player is standing on any solid node AND
* The player is currently sneaking (holding down the sneak key)

The player won't be teleported to the destination, instead the player is just moved to the edge of the node on which the player is currently standing, but interestingly, this is always towards the direction of the destination.

One way to quickly test this is by using the Mirror of Returning (https://forum.minetest.net/viewtopic.php?f=11&t=11224) or Point Teleporter (https://forum.minetest.net/viewtopic.php?f=11&t=9629).
Both mods directly call `setpos` when you use the item.

I think this is very unexpected for modders, it also seems to me the modder has zero chance to somehow “overwrite” this behaviour or to ignore the sneaking.

Tested in: 0.4.12

### PR DESCRIPTION
**Pull request by HybridDog**
#2876

### CODE REVIEW

**Comment by HybridDog** [comment]
Do l need to reword the commit that it begins with a big letter?

**Comment by rubenwardy** [comment]
The commit message is quite long. Put any additional info on a new line.

**Comment by HybridDog** [comment]
done

**Comment by est31** [comment]
Looks good :+1:

**Comment by rubenwardy** [comment]
I think it should be: 

> Fix player teleportation bug whilst sneaking
>
> Only set back position when sneaking if player wasn't teleported …
> by adding and using a bool "got_teleported" to player
> it fixes #2876

**Comment by HybridDog** [comment]
edited

**Comment by ObaniGemini** [comment]
:+1: 
Merge ?

**Comment by celeron55** [comment]
This seems to be the correct fix. :+1:

**Comment by paramat** [comment]
c0b6986e3875e6f42682c78fd5db0080a7bae651

**Pull request closed without merging**
