### PR TITLE
Reduce server FOV with forward speed.

### PR DESCRIPTION
**Pull request by lhofhansl**
Related to #6447 .
This will reduce the server FOV for retrieving and sending blocks, when a player moves in the direction (s)he is looking. This avoids rendering blocks that will soon be out of sight (the player is moving forward). If the player is looking in a different direction this effect it reduced or turned out (see dot product in the code)

The result is that rendering artifact are mostly visible on the side and not in front where the player is likely looking.

Check it out. Typically the rendering artifact are not noticed on the side, while the server sends fewer blocks and the client has to render fewer blocks as well.

The numbers can be tweaked still. Right now the speed factor is capped at 300 (i.e. 30 n/s). At fly speed (20 n/s) the fov is reduced by 40% reducing the number of blocks render by almost 3x. Can probably still increase the effect slightly to be 50% at 20n/s, for a 4x reduction in blocks (still with visible artifacts pushed to the sides).

### CODE REVIEW

**Comment by paramat** [comment]
To be clear you mean the FOV used for loading blocks is reduced, not the actual camera FOV?

**Comment by lhofhansl** [comment]
@paramat Yes. Server-side FOV so to speak. Pretty effective to save blocks sent and rendered.

**Comment by paramat** [comment]
Block load FOV reduces to 88% at walking speed.

**Comment by paramat** [comment]
Works ok, at 20n/s the blocks on the very edge of the view, which are of little importance to the scene, are not loaded but go out of view within 2s.
It seems that the dot product means that when view and velocity are at 90 degrees, when flying sideways, the effect is zero?

**Comment by paramat** [comment]
Only thing i was concerned about was the reduction when walking, but it's not really noticeable at all.

**Comment by paramat** [comment]
The stress test seems to be 30n/s while flying diagonally, because there is some chance of flying towards the unloaded areas, occasionally unloaded blocks get quite close, but i don't see this as a problem.

screenshot_20171024_054742

**Comment by paramat** [comment]
Ok i certainly support this, it will make things smoother when flying. The way it is tuned seems ok. I'd like other devs to look at this. I'll probably +1 a little later.

**Comment by lhofhansl** [comment]
Thanks for testing.
In the diagonal case the effect would also be reduced to 1/2 (assuming the player looks forward) the effect would be 66% of fov. Kindof a worst case.

One could also tilt the view cone somewhat in that direction.

**Comment by lhofhansl** [comment]
I can also limit the effect to 20n/s instead of 300n/s.
Btw. with ethereal and the crystal boots on the flying speed is 40n/s :)

**Comment by paramat** [comment]
I think tilting the view cone is overkill. I did think about limiting the effect to 20n/s, maybe.

**Comment by lhofhansl** [comment]
Then the question is: Is it better to lose some of the blocks on the side (in this worse case) or the block in front.

**Comment by paramat** [comment]
Since the worst case rare occurence is only for diagonal at 30n/s i don't see it as an issue. I will test but i guess the worst case screenshot i posted probably doesn't happen at 20n/s.
Blocks in front are more important of course.

**Comment by paramat** [comment]
It still happens at 20n/s but never mind :+1:

**Comment by lhofhansl** [comment]
I suppose I can do followup fixes in this area.
Generally the server should be able to generate blocks faster and the to render them faster. I looked at MC on Android and it seems we're doing better already :)

Perhaps moving away from the rigidity of Irrlicht will improve performance as well.

**Comment by lhofhansl** [comment]
0732bf73

**Comment by paramat** [comment]
I very often fly around at 20n/s and i think i noticed smoother behaviour, before i used to get momentary freezes. So this will be very useful for devs, server admin and anyone using fast vehicles.

**Pull request closed without merging**
