### PR TITLE
Grammar improvement, "right or left of the hotbar"

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by rubenwardy** [comment]
I believe this file is generated from `builtin/settingtypes.txt`

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/d0d8e469c1dce1b2eb757a664bd3c17216999df5/src/settings_translation_file.cpp#L1-L3


How to fix the grammar:
1) Replace the bad grammar in `builtin/settingtypes.txt` or wherever it is used (grep is your friend)
2) (optional) Generate the new `minetest.conf.example` and `settings_translation_file.cpp`

**Comment by paramat** [comment]
@comradekingu see #7726 , you edited  'settings_translation_file.cpp' in that PR too, and we explained that shouldn't be done and what to do instead.
Then in that PR and #6880 you stopped working and responding and didn't make the requested changes, eventually i made a commit myself to replace both https://github.com/minetest/minetest/commit/d6f2a1c4b8ab13cee92e2041b3410fe3548e88e6
The reviewing experience was therefore very frustrating and you wasted core dev's time. The result is i feel like reviewing your PRs is probably a waste of time.
So please co-operate this time.

**Comment by comradekingu** [comment]
Sorry about that, it was linked from Weblate with no instructions.

**Pull request closed without merging**
