### PR TITLE
Disable game bar and header on Android

### PR DESCRIPTION
**Pull request by rubenwardy**
From #7936

image

### CODE REVIEW

**Comment by stujones11** [comment]
:+1: I don't much see the point of this on any device, tbh.

**Comment by paramat** [comment]
Not necessary for creating worlds, but then how do you then view the worlds that exist for other games?

**Comment by paramat** [comment]
stujones11, because worlds are only shown for the game currently selected, which i think is obviously correct. The game icons are also nice to look at and wouldn't get seen otherwise.
I'd prefer to keep the gamebar for Android if possible for those reasons, but won't oppose this PR.

**Comment by stujones11** [comment]
> The game icons are also nice to look at and would never be seen otherwise.

This is a fair point, I guess it makes more sense to those with multiple games installed. However, keeping this for android does complicate the scaling and I would rather not see the overall menu size reduced for the sake of this feature.

**Comment by paramat** [comment]
Yes this PR does seem possibly the best and simplest solution.

**Pull request merged**
