### PR TITLE
Small changes in the style of controls

### PR DESCRIPTION
**Pull request by ngosang**
Lighter list and flat borders in controls.

### CODE REVIEW

**Comment by nerzhul** [comment]
Agree. @sapier , @kwolekr ?

**Comment by nerzhul** [comment]
capture d ecran de 2015-02-11 20 22 27
Left: old, right: new.
I think this is a good idea, but if some other users can review and talk with us ?

**Comment by nerzhul** [comment]
https://forum.minetest.net/viewtopic.php?f=5&t=11207

**Comment by sfan5** [comment]
I like these changes :+1:

**Comment by nerzhul** [comment]
I will push it in 2 hours if any objection.(

**Comment by nerzhul** [comment]
Commited thanks
4a6582c13c36cab457b78f32338c6bb4ab9ea58b

**Pull request closed without merging**
