### PR TITLE
File 'client/game' splitted into new folder

### PR DESCRIPTION
**Pull request by Unarelith**
Discussion still open for:
- Adding a `.cpp` to some of the lonely `.h`
- Creating an `Application` class to replace `game.h|cpp` (since this could replace some Game functions, this could probably be another PR)

Additional notice should be added somewhere that everything in the folder `client/game` should not be used elsewhere, except the static function `the_game`.

### CODE REVIEW

**Comment by paramat** [comment]
game

It's not too bad due to the capitals, but a little hard on the eyes having no spaces.
However i can see the point of matching the titles used in the code contained, so i've removed my -1, i just think we need to discuss this carefully as we'll be stuck with the choice for many years to come :)

**Comment by paramat** [comment]
Another issue is being careful to not be excessive with creating large numbers of small files, i'm not sure one file for every unit is a good idea, som eof these files are tiny, although i can see it makes finding things much easier. So i sort of like it but am also a little concerned about rushing a decision on such a radical change.

There are dev rules that are possibly relevant here:
" Don't use distracting and unnecessary amounts of object orientated abstraction. See Terasology as an example of what not to do.
As an addendum to the last point, don't randomly add unnecessary design patterns to your code, such as factories/providers/sources"

Again this needs careful discussion first.

**Comment by nerzhul** [comment]
as i said on irc, snake_case

**Comment by SmallJoker** [comment]
I'm OK with PascalCase but also welcome snake_case since it matches better the existing  file naming pattern.

**Comment by Quent42340** [comment]
Well, class files could be PascalCase and C-style files could stay snake_case or minetestcase, that would be a visual difference between them and I think it's important. When I look to MT code I don't know which files defines classes/struct/enums and which files don't..

Currently very few files have only one class definition inside them, so I'll split the others at some point anyway, matching their name with the chosen norm.

**Comment by nerzhul** [comment]
it's not java, don't do a such refactor please. just wait for the next release. It's not needed yet.

**Comment by Quent42340** [comment]
Don't worry I'll wait 5.0.0 to make other changes, probably to rebase this too. This discussion is about possible name convention change due to file splitting, it's not about the fact that's it good or not for 5.0.0.

**Comment by paramat** [comment]
As far as i know the author is busy but is intending to rebase this.

**Comment by Unarelith** [comment]
Yes I definitely intend to rebase this PR, but like my other refactorings, I'll need you to let me know when I can work on this.

This type of refactoring can cause serious conflicts with other PRs, so as soon as critical impacted PRs are merged, I'll work on this as fast as I can to get this merged quickly.

As far as I remember, this wasn't completely finished, so I probably won't rebase it but restart from scratch, I think it will be less time-consuming since a lot of modifications may have been done since I made this PR.

I'm completely free in August, but I'll be really busy starting from September, just so you know.

**Comment by paramat** [comment]
Great. In our last meeting we agreed to control the merging of PRs in order to let you rebase and merge your refactors / file moves without conflicts arising. Your formspec refactor will have to wait though as much other work is happening there currently.
See http://irc.minetest.net/minetest-dev/2019-06-29#i_5562012

Also i want to express how much i appreciate #7902 , it really reduces confusion, for years i've been thinking 'why isn't this file in client, have i misunderstood something?'.

**Comment by Unarelith** [comment]
Glad to hear that you like what I did in #7902

I really think there's a lot of design issues in Minetest, and I intend to fix most of them

I hope things will move quickly enough so that I can take advantage of my free time in August to move forward on most of my PRs... And I'm not necessarily talking about the formspec one, I agree there's more important PRs to merge first.

**Comment by Unarelith** [comment]
So this PR is outdated, or is just closed because I was inactive?

**Comment by paramat** [comment]
It was only closed due to no progress for (roughly) 6 months, this is still welcome and we will reopen this on progress. Good to see you around, was a little concerned when you did not appear in August.

**Comment by Unarelith** [comment]
It has no progress because you told me to wait until other PRs get merged, and nobody told me that I could continue my work on this PR in August... Every PR I made was delayed because other PRs had to be merged first. I'm happy if I can finally work on my PRs and get them merged.

**Comment by paramat** [comment]
Oh good point, sorry. Yes it was, and is, waiting for other stuff to happen. This probably should have remained open.

**Comment by Unarelith** [comment]
> We need to keep this in mind.

Yes please. But I kinda feel like none of my refactoring PRs will get ever merged, because I think there's always more important PRs to merge first. The issue is, if the code is getting bigger but without being refactored, it will only get harder and harder to review and to contribute to, just saying.

**Comment by paramat** [comment]
Good point, we may need to disrupt other PRs to get this done, if it is desired.

**Comment by Unarelith** [comment]
Do you remember what you said to me before 5.0.0 release? Something like:
> Currently 5.0.0 release is the most important, but after that your refactoring PRs are welcome

Well it's been almost a year now, and you still don't care about my refactoring PRs because I'll break other PRs. And yeah, I agree, this is gonna break some PRs. But it won't be hard for people to update their PRs because I'm just splitting one file into smaller files, and it can make things so much better for everyone.

**Smaller files = Less conflicts = Easier to review = Faster contributions**

Just think about that please.

**Comment by paramat** [comment]
We do care and they are welcome. Any delay is due to the usual reasons, being overwhelmed, little core dev time, stuff getting forgotten.
I agree we have to decide on and accept disruption of PRs for the benefits of this, there is no other way. What do other core devs think?

> and nobody told me that I could continue my work on this PR in August

You overestimated how organised we are =) It is best to assume we have forgotten stuff, and best to remind us with a comment when you have free time, asking if stuff can go ahead.

**Comment by Unarelith** [comment]
> We do care and they are welcome.

It's nice to read that.

> Any delay is due to the usual reasons, being overwhelmed, little core dev time, stuff getting forgotten.
> I agree we have to decide on and accept disruption of PRs for the benefits of this, there is no other way. What do other core devs think?

The issue is, my time isn't unlimited and I come back on this GitHub when I'm available, which is, this time, until the beginning of February.

> You overestimated how organised we are =) It is best to assume we have forgotten stuff, and best to remind us with a comment when you have free time, asking if stuff can go ahead.

Noted. I'll do that.

**Pull request closed without merging**
