### PR TITLE
Compute clarity per vertex instead of per fragment

### PR DESCRIPTION
**Pull request by numberZero**
This should improve performance significantly. See [my comment](https://github.com/minetest/minetest/issues/4335#issuecomment-411903979) in another issue for some data.

### CODE REVIEW

**Comment by Fixer-007** [comment]
No fps boost for me on i5-3450 / HD 2500 in that heavy jungle fly straight for 3 minutes test (literally within stat error).

**Comment by lhofhansl** [comment]
Unfortunately I also see no difference.

I'd expect it depends on the view distance, and on the resolution used.

You could imagine a scenario of a far view range where you'd end up with more vertexes than fragments. (Fragments are function of the output device - pixels, vertexes are a function of the complexity of the scene... Just to state the obvious :) ).

**Comment by numberZero** [comment]
Oh well, I use view range of 30–70 nodes usually...
So nvm, this is probably not the right thing to do.

**Comment by lhofhansl** [comment]
It's never entirely clear to me what's best done at the fragment and what's best at the vertex level.
If you have a super high-res screen and short view range this could be significant. If we even do LOD then do more things at the vertex level also would be beneficial.

**Pull request closed without merging**
