### PR TITLE
Move warnings about not being able to load the node to infostream.

### LINKED ISSUE #5246: Client spews node metadata messages for no reason.
I have a server mod that has a node that every 12 seconds replaces itself with the same node but a different param2. 

The *client* runs on a different machine and constantly emits the following warnings:

```
2017-02-15 22:18:31: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:31: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:18:44: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:44: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:18:57: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:57: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:19:09: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:19:09: WARNING[Main]: Map::removeNodeMetadata(): Block not found
```

There is no metadata used in this node.

The node is rotated randomly somewhat like this:

```
	on_timer = function(pos, node)
		-- make it self-rotate randomly
		minetest.set_node(pos, {name = "test:rotating_node", param2 = math.random(24) - 1})
	end,
```

### PR DESCRIPTION
**Pull request by red-001**
should fix #5246

### CODE REVIEW

**Comment by Ekdohibs** [comment]
This isn't a proper fix for this, see [my comment](https://github.com/minetest/minetest/issues/5246#issuecomment-280402734). `setNode` will exit due to not being able to load the node, but will only do so after the warning will be shown, it isn't a proper fix to just hide the warning.

**Comment by red-001** [comment]
It uses `getBlockNoCreateNoEx` so it wouldn't cause any exceptions. All it will do is return null / false / not work. I don't see why the user needs to be aware of this happening. The `getBlock` functions don't print a warning in the same situation so I don't see why metadata should.

**Comment by Ekdohibs** [comment]
@red-001 exactly, `removeMetadata` will not cause any exceptions because it uses `getBlockNoCreateNoEx`. However, `setNode` which is used a bit after this in the same function uses `getBlockNoCreate` (see [this](https://github.com/minetest/minetest/blob/master/src/map.cpp#L223)). Thus, the good way to fix this would be to change the code logic to raise the exception *before* removing metadata.

**Comment by sfan5** [comment]
Are you fucking serious, hiding warnings is not how you fix problems?

**Comment by red-001** [comment]
So why exactly should this be a warning? Does it cause any bugs?

**Comment by Ekdohibs** [comment]
@red-001 it should indeed be a warning, because `getNodeMetadata` (or `removeNodeMetadata`) should only be called on loaded blocks; here it is not a bug but in other cases it might be, so this message should not be ignored.

**Pull request closed without merging**
