### PR TITLE
Fix 'Download complete' dialog in the mods store

### PR DESCRIPTION
**Pull request by ngosang**
This patch fix the 'Download complete' dialog in the mods store and also removes several warnings from the store.

### CODE REVIEW

**Comment by ngosang** [comment]
I did something wrong and the old PR #2183 was closed. This is a new PR with the old code and a little fix from @JakubVanek.

**Comment by nerzhul** [comment]
Seems good for me. I'll test it this evening

**Comment by nerzhul** [comment]
can you fix whitespaces errors ?

Application : Fix 'Download complete' dialog in the mods store
/home/nerzhul/Devel/minetest/.git/rebase-apply/patch:16: trailing whitespace.
			return "size[6,2]label[0.25,0.75;" ..

**Comment by ngosang** [comment]
>can you fix whitespaces errors ?

Done.

**Comment by nerzhul** [comment]
PR accepted. Thanks
704453ff124eaca8ef1b6ff564810c4bebb9cf3f

**Pull request closed without merging**
