### PR TITLE
Adjust formspec spacing on the Client tab of the mainmenu

### PR DESCRIPTION
**Pull request by rubenwardy**
screenshot_2017-01-16_15-55-50

### CODE REVIEW

**Comment by sfan5** [comment]
:+1: however could you also add some space between the text box / button and the server list? they are too close together for my liking

**Comment by rubenwardy** [comment]
Will do. I'll try and make the spacing the same between all elements

**Comment by sfan5** [comment]
Much better.

**Comment by Fixer-007** [comment]
Notice how tabs override on top of MINETEST

**Pull request merged**
