### PR TITLE
Use inventory_image only for inventory item mesh

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by est31** [comment]
To fix #3668

**Comment by est31** [comment]
:+1:

**Comment by rubenwardy** [comment]
Won't this cause the inventory image to be used in the hand instead of the wield image?

**Comment by est31** [comment]
Mhhh possibly...

**Comment by RealBadAngel** [comment]
no it wont

**Comment by est31** [comment]
@kilbith can you test?

**Comment by paramat** [comment]
I guess 'getItemMesh' is not used for wieldmesh but is used for inventory? So seems a straightforward swapping of priority.

**Comment by RealBadAngel** [comment]
@paramat yes. it is using similar way to get the mesh as for wielded (code was done based on wielded, thats why i havent noticed the priorities should change)

**Comment by paramat** [comment]
:+1:

**Comment by rubenwardy** [comment]
I don't think wield item images should ever be used for the inventory images.

**Comment by RealBadAngel** [comment]
@rubenwardy its a fallback, same is used for wielded

**Comment by rubenwardy** [comment]
What was the previous behaviour?

**Comment by RealBadAngel** [comment]
@rubenwardy it was using the same sequence as wielded wielded_image->inventory_image
In this case we need it other way round.

**Comment by paramat** [comment]
Perhaps it's a good fallback as otherwise the more complex code below is executed.

**Comment by RealBadAngel** [comment]
ive left it that way because i was planning to unify wielded and inventory meshes, will have to keep in mind that priorities when coding that

**Comment by rubenwardy** [comment]
This does change behaviour:

brokenbehaviour

**Comment by RealBadAngel** [comment]
hmmm that shows wield_image is completely not needed here

**Comment by kilbith** [comment]
Tested. I confirm it works perfectly.

Also it doesn't change the behavior at all (using rubenwardy's example).

**Comment by rubenwardy** [comment]
> Tested. I confirm it works perfectly.
> Also it doesn't change the behavior at all (using rubenwardy's example).

RealBadAngel fixed it so it now works the same as before.

:+1:

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
Ready to merge it seems

**Comment by est31** [comment]
38e712260046f159aa201259569054bdf9793b7f

**Comment by rubenwardy** [comment]
Unit tests failed in the clang build - why is that?

**Pull request closed without merging**
