### PR TITLE
Formspec: Prevent editing non-writable textarea

### LINKED ISSUE #7010: Typing on the pause menu
##### Issue type
Bug report

##### Minetest version
0.5.0-dev

##### OS / Hardware
Confirmed reproducible on both Windows and Linux.

##### Summary
This:
mt_stupidpausemenu
(Thankfully changes are of course lost after you close the menu... but it's still wrong.)

##### Steps to reproduce
Just go to the pause menu. Click. Type things.

### PR DESCRIPTION
**Pull request by adrido**
This should fix #7010 

I apologize for the problems.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Alternative, prior PR: #6787

**Comment by adrido** [comment]
> Alternative, prior PR: #6787
Oh yes, havn't seen it. Is there a reason why it isn't merged yet?

**Comment by SmallJoker** [comment]
@adrido The usual reason: stalling due less developer time (same situation for me right now, sadly)

**Comment by SmallJoker** [comment]
Included in #6787 (merged now)

**Pull request closed without merging**
