### PR TITLE
Add TGA test nodes to devtest

### PR DESCRIPTION
**Pull request by erlehmann**
minetest-mod-devtest-testnodes-tga-use-texture-alpha

When writing documentation, it came up Minetest does not support all features of all file formats it processes.

In particular, some TGA file types (type 9 & 11) are not supported (and should not be added IMO).

The goal of this PR is to demonstrate Minetest's TGA support and help with debugging.

I have added 10 different nodes for different supported TGA types (1, 2, 3 & 10).

~Note that 16 bit A1R5G5B5 images are not included in this PR. Minetest supports those and one version of the `tga_encoder` mod generates them, but I have found no setting in GIMP to set color depth to 5 bit per color.~

## To do

This PR is Ready for Review.

## How to test

Start devtest and make sure that all test nodes with a texture that reads “TGA” actually render in inventory, hand and world.

Make sure that no TGA-related texture errors occur when loading devtest.

**Edit:** The grayscale TGA test node having a yellowish tint and no transparency is probably a bug in Minetest.

**Edit:** The alpha channel being ignored in the 16bpp textures I added is probably another bug in Minetest.

**Edit:** I have made the node drawtypes glasslike so that they do not have the wallhack appearance.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Looks good.

**Comment by erlehmann** [comment]
@rubenwardy pointed out that I forgot to use `use_texture_alpha`. I have updated the PR.

**Comment by erlehmann** [comment]
I figured out how to create A1R5G5B5 textures using imagemagick:

`convert textures/testnodes_tga_type2_32bpp_bt.tga -depth 5 textures/testnodes_tga_type2_16bpp_bt.tga`

I will update this PR accordingly.

**Comment by sfan5** [comment]
I think a C++ unittest is better suited for this.
Instead of testing all combinations of (possible TGA files) → (node appearances) it's less work to test (possible TGA files) → (decoded textures) and (decoded textures) → (node appearances) separately.

**Comment by erlehmann** [comment]
> I think a C++ unittest is better suited for this.

For figuring out if decoding works correctly: Yes. For someone trying to figure out how TGA formats work: No.

Right now the devtest nodes do a good job showing what works and what does not. A unit test would not do that.

E.g. if someone fixed the yellow tint in grayscale textures, a reviewer could verify that with a devtest node.

> Instead of testing all combinations of (possible TGA files) → (node appearances) it's less work to test (possible TGA files) → (decoded textures) and (decoded textures) → (node appearances) separately.

While true that an alternative version would have been less work, this code now exists and the alternative does not. It can still be replaced in the future. Meanwhile, it is better than nothing – and I doubt anyone complains if some nodes in devtest are removed later because they are no longer necessary for testing.

(Also, how would you store the reference images? Formats simpler than TGA were gutted, i.e. RGBA pixel arrays?)

I think the fact that these nodes already exposed two bugs (alpha channel ignored in A1R5G5B5 textures and yellow tint in grayscale pictures) shows that they can be helpful exactly as they are.

**Comment by lhofhansl** [comment]
I maintain my "One Approval" for the general idea of adding TGA test nodes.

**Comment by erlehmann** [comment]
I had a chat with @celeron55 about this PR. He suggested that I explain my motivation and goals here too.

I have created the TGA test nodes out of a personal need: There exist now several versions of the tga_encoder mod and there is no simple way to figure out if textures will work in a version of Minetest that a user has installed.

People who create textures also at times export textures in supported file formats with features that Minetest does not support. I have so far created both PNG and TGA files that Minetest would not load, but GIMP would load fine. In this light, having a library of test nodes for each supported media format would serve as an easy reference for what Minetest can actually do in a version. It would also mean that game and mod creators would have examples of already working combination of feature flags for a file format.

Here is a texture pack where I have given the author advice on how to export their files using mtpaint so that they are loaded correctly by Minetest: https://github.com/Li0nsDickachu/a_minetest_texturepack

I find it important to note that having incomplete support for a file format does not mean that it can not be used. For example, the A1R5G5B5 color mode support does not handle the alpha bit currently – but I have only sean it used so far for textures without transparency – because those work fine.

My long-term goal for Minetest that goes beyond this PR is to have a texture test node for each supported file type variant. I think that PNG should be next – the PNG test nodes made by @hecktest are not enough to figure out what combination of PNG feature flags works in Minetest. I am starting with TGA for three reasons:

1. TGA is the simplest useful image format that is still widely supported in viewing and editing software. There are not that many format options to choose from compared to other formats and the parsing code is relatively simple. The decoder for a format like that can be done at some point, so that it never needs to be touched again.

2. TGA is often used as a lowest-common-denominator reference format for reference pictures due to its low complexity and ability to represent RGBA textures – libjpeg-turbo, for example, contains a TGA decoder for exactly that reason. I definitely prefer having reference textures as TGA and not inline arrays.

3. When I improved the tga_encoder mod, I noticed that some combination of features are not supported. If support for any format improves in the future or if texture decoding depends on which library Minetest is compiled with, it is probably going to be useful if a developer can ask ordinary users to start devtest and make a screenshot of some texture test nodes.

Note that in the past I have several times suggested to expose not-yet fixed bugs by means of failing unit tests. My suggestions most often included compile options that highlighted existing bugs in the code (e.g. compiling code with `-fsanitize=undefined`). Not only where those suggestions not received well … if I am not mistaken, tests are only added as regression tests, not for any of the other purposes that I have outlined above. Additionally, media format support unit tests already got removed from irrlichtmt even though they would have been salvagable, which makes me doubt that adding more tests would actually be welcome.

**Comment by Wuzzy2** [comment]
The new DevTest was reworked specifically for the sole reason to test all the things (and not just a tiny fraction of things, like in the old Minimal Development Test). Test nodes are the bread and butter of DevTest and the more stuff they allow to test, the better. More and more test nodes have been added in the past and you might argue it's too much but in reality the test nodes just expose how complex Minetest has become. It's kind of irreducible complexity.
Adding test nodes specifically to test the TGA file format is a classic example. I would have added this to DevTest myself as well if I would have cared enough. So :+1: from me, who did the major DevTest rework.

While unittests are nice, eventually there is no way around manual testing. Unittests can't tell you that something will *look ugly* to you or if something *feels wrong* to the player.

Adding more DevTest nodes should normally be acceptable by default. I find it silly we are even arguing about the validity of test nodes. As long they test specific features of the engine, I think test nodes are good to go.

The only justification for rejecting this PR IMHO is when TGA images are planned to be removed from the engine soon.

Besides, the test nodes can probably happily co-exist with any unittest or automation anyway.

**Comment by erlehmann** [comment]
> The only justification for rejecting this PR IMHO is when TGA images are planned to be removed from the engine soon.

Removal of TGA was reverted after I pointed out that not only are they in use, e.g. in mcl_maps.

But even if they had not been used, TGA is probably the last format you want to remove from a game engine: Games and related software like (Minecraft, Steam etc.) still use it for obvious reasons – it is stupidly easy to read, stupidly easy to write (even when compressed), streamable, extremely fast to load with little CPU use and supports the most common color channel formats.

**Review by Df458 — APPROVED** [review]
I'm of two minds here:
- On one hand, this PR's nodes are _apparently_ incomplete judging by the TODO. I do also think @sfan5's proposal to verify support with unit tests has merit.
- On the other hand, we have this _right here, right now_. And it has already turned up at least one bug! Clearly, this has value in its current state.

I think I come out in support today, because this is a set of test nodes. Given that `devtest` is not intended for players (and indeed, we **actively tell players not to use it in the client**) the actual real-world "regression cost" of replacing these with another solution later is pretty much nil.

So, in this case I think we can take the "good" today and if someone wants to aim for "perfect" later they can do so without being hindered by this change.

**Comment by erlehmann** [comment]
> On one hand, this PR's nodes are apparently incomplete judging by the TODO.

I have made all of these manually, i.e. saved them, tweaked them and verified them & lost motivation at some point.
I believe the existing nodes actually do cover the range of possible options well right now. More can be added later.

> I do also think @sfan5's proposal to verify support with unit tests has merit.

I think that too! It's not mutually exclusive. The nodes are also for different purposes that unit tests could not help with.

> And it has already turned up at least one bug! Clearly, this has value in its current state.

Thanks! I also intend these nodes to be a help for testing if a bug is fixed – i.e. “place this node, is the background transparent?”.

> So, in this case I think we can take the "good" today and if someone wants to aim for "perfect" later they can do so without being hindered by this change.

The “perfect” solution for this mod would actually be to merge all the different versions of the `tga_encoder` mod that write different TGA variants (I counted at least four) into one version that can do them all *and* can do paletted stuff. I did not do this because it is effort. Also people who wonder which options of a file format are supported are much better served with files in a repository IMO.

**Pull request merged**
