### PR TITLE
Add wallmounted_to_dir function

### PR DESCRIPTION
**Pull request by Kalabasa**

### CODE REVIEW

**Comment by Rui914** [comment]
b12bdcc

**Comment by sofar** [comment]
Seems this is a duplicate, so it can be closed.

**Comment by paramat** [comment]
Please can someone link to the other PR? If it's identical this can be closed, otherwise both need considering.

**Comment by Rui914** [comment]
#3218

**Comment by sofar** [comment]
The other PR is merged.

**Pull request closed without merging**
