### PR TITLE
Sao refactor 2

### PR DESCRIPTION
**Pull request by Rogier-5**
Second part of #4760. See there for details.

### CODE REVIEW

**Comment by paramat** [comment]
Again, perhaps best merged after release.

**Comment by nerzhul** [comment]
I didn't rebased all because of conflicts, but part of this PR is here: https://github.com/minetest/minetest/pull/5020

**Comment by Zeno-** [comment]
Can this be closed?

**Comment by nerzhul** [comment]
yes, second part is here: https://github.com/minetest/minetest/pull/5022

**Pull request closed without merging**
