### PR TITLE
README.md: Improve version scheme text

### PR DESCRIPTION
**Pull request by paramat**
screenshot

Also remove a few inconsistent and unnecessary empty lines after section titles (they do not transfer to the MD format).

### CODE REVIEW

**Comment by paramat** [comment]
Updated see first post screenshot.

**Comment by ClobberXD** [comment]
`previousversion-dev.` could be changed to `previous_version-dev`, for readability

**Comment by paramat** [comment]
Hmm ok.

**Comment by paramat** [comment]
Done.

**Pull request merged**
