### PR TITLE
Better F6 profiler

### PR DESCRIPTION
**Pull request by SmallJoker**
## Goal
 * Make the profiler easier to read
 * Rename profilers to they make more sense
 * Drop useless profilers or merge with others

## Result
 * Lower default update interval to 2 seconds
 * Show `ScopeProfiler` results in milliseconds
 * Many removed variables used for time measuring, or such that did not do anything

screenshot_20190804_172329

## To do

This PR is Ready for Review.

## How to test

1) Join a world
2) Same in-game performance (you'd notice that if there were accidental changes in the code)
3) Open the F6 profiler -> monospace text, nothing's cut off
4) Open the F5 graphs -> must all display values when walking around

### CODE REVIEW

**Comment by paramat** [comment]
Does this do #4320 too? That would help a lot.

**Comment by SmallJoker** [comment]
@paramat No it does not but I could make the colors based on the profiler name's hash.

**Comment by paramat** [comment]
Ok a separate PR is fine, thank for considering.

**Comment by SmallJoker** [comment]
I see a few thumbs up (for the concept?) but no feedbacks on the profiler names. Do they make sense? What could be improved?

**Comment by SmallJoker** [comment]
Update.

grafik

**Comment by ClobberXD** [comment]
I'm sorry, I like the concept but I'm unable to take a look at the changes and/or test.

**Comment by SmallJoker** [comment]
@ClobberXD Thanks for the concept feedback. The profiler scopes can still be tweaked later if there are better suggestions :)

**Pull request merged**
