### PR TITLE
Replace occurences of 'wiki.minetest.net' with 'wiki.luanti.org'

### PR DESCRIPTION
**Pull request by veprogames**
Replace occurences of 'wiki.minetest.net' with 'wiki.luanti.org'

Note that I kept the IRC channel name #minetest-dev because I don't know if it changed. Did it change?

## To do

This PR is Ready for Review.

- [x] Replace Occurences

## How to test

Test if all the changed links work and do not 404

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]
> Note that I kept the IRC channel name #minetest-dev because I don't know if it changed. Did it change?

Not yet

**Comment by sfan5** [comment]
please rebase

**Comment by veprogames** [comment]
I don't know if I rebased correctly this time. For reference, I have this remote as `upstream`, and did `git rebase upstream/master` and `git rebase --contunue` until conflicts were resolved.

**Comment by sfan5** [comment]
That's fine. In this case a merge commit also wouldn't be a problem, since we squash the changes on merge.

**Pull request merged**
