### PR TITLE
Add player list, viewable by holding Tab

### PR DESCRIPTION
**Pull request by sfan5**
screenshot_3529713238

### CODE REVIEW

**Comment by nerzhul** [comment]
This function seems interesting sfan5, can you rebase ?

**Comment by C1ffisme** [comment]
Yes, yes, YES!!!! Please rebase and merge!

**Comment by Megaf** [comment]
I believe this should be a separate mod actually, in lua, built in into default. That could be enabled/disabled with a setting on minetest.conf on the server area.

player_list = true

**Comment by MirceaKitsune** [comment]
Separate mod or not, I believe this needs to be done in Lua, not hard coded in C++. It's possible and easier, and I already made a Pull Request in this sense long ago which I think got forgotten.

**Comment by nerzhul** [comment]
@sfan5 do we close this issue ?

**Comment by MirceaKitsune** [comment]
I support closing this simply because I think the feature should be done in Lua. I already scripted a player list like this and made a pull request long ago... I don't remember if for builtin or minetest_game, but I should probably find it and take another look.

**Comment by sfan5** [comment]
Rebased as requested by @nerzhul

**Comment by C1ffisme** [comment]
Why would you make it in lua? Then the list is only updated when player information is shared with lua code. It's faster to do it in C++, and we can get results right from the engine.

**Comment by nerzhul** [comment]
anything is faster in c++, but if mods wants to customize this, like all the Gui, why not ?
I was also for C++, but it's not closed for debate

**Comment by C1ffisme** [comment]
@nerzhul True, true. I see your meaning.

@sfan5 Do you think it's possible to support showing the face of each player behind their usernames? Just wondering...

**Comment by MirceaKitsune** [comment]
Regarding why I think this should be done in Lua: There is a simple function which generates a list of all players on the server. It either needs to run just once when the menu is opened, or be updated every say 10 seconds globally. When something can be scripted rather than being hard coded, I personally think it should be, so the code only handles the absolute basics.

**Comment by LeMagnesium** [comment]
The idea is good, coding it in Lua allows moders to do simple changes on it, if they want to use any new element, or change colours, etc... However it seems that the pull-request needs to be rebased again..
@C1ffisme : Showing faces of players by default (coded in minetest_game) is not useful, because by default, they have no particular skin. If you want to change this on your server, using a mod or adding it by yourself, it's fine, do so. But by default they all have the same face, so it's not interesting.

**Comment by kwolekr** [comment]
This is slated for implementation as a part of client-side modding (and would be quite trivial to do so given the intended interfaces)

In general, we're shying away from making the core more game-like and less engine-like.

**Comment by rubenwardy** [comment]
So, 5 years later :eyes:

**Comment by Megaf** [comment]
It's been that long already?
Is it implemented?

**Comment by sorcerykid** [comment]
Something like this should be implemented as a mod, not as part of the engine. This is why I would like to see a proper API for keybinding as well as a completely revamped HUD specification.

In my view, there should be no hard-coded GUIs at all in Minetest.

**Pull request closed without merging**
