### PR TITLE
Fixed authentication bug

### PR DESCRIPTION
**Pull request by gpcf**
Fixed bug #4602 by silently ignoring invalid lines in auth.txt

### CODE REVIEW

**Comment by SmallJoker** [comment]
That's not the right way to solve this problem IMO. What's the cause for invalid lines?

**Comment by gpcf** [comment]
Let me investigate. In what file is the code that handles registrations? I'll try to find it.

**Comment by nerzhul** [comment]
:-1:

**Comment by gpcf** [comment]
I can't find the cause of the problem, so I can't provide you with a better fix right now.

**Comment by gpcf** [comment]
Now it stops silently ignoring the lines, it logs the errors. An invalid line in auth.txt should not be a fatal error that prevents servers from starting.

**Comment by est31** [comment]
@gpcf silently ignoring the corrupted file is not how to solve the bug. If the file is corrupted, it usually means that player's login information is lost, and other players can log in as them, using their credentials. Therefore I'm against merging this change, not even as hotfix.

As the other devs seem to have similar opinions, I think I can close this PR now.

**Comment by gpcf** [comment]
It no longer silently ignores it, it outputs an error to the log. Besides, it is always only one line. IMHO, better than preventing the server from starting, but still worse than fixing the bug.

**Pull request closed without merging**
