### PR TITLE
[no-sq] Some Lua 5.2 backports

### PR DESCRIPTION
**Pull request by red-001**
Backports some Lua 5.2/LuaJIT features to Minetest's version of Lua 5.1. 
Since Lua 5.1 is about over a decade past its end of updates, and Minetest has modified the version bundled already it seems like a good idea to modify it to support some quality of life features from LuaJIT. 

See #15133 for the initial motivation behind the first part of this PR. 

Features ported:

- pairs/ipairs metamethods.
- `LUA_OK` macro definition.
- `lua_copy` C API function.
- xpcall being able to pass arguments

Features *not* ported:
- load/loadstring/loadfile changes - largely unnecessary as Minetest re-implements those functions for mod security.
- yielding across pcall/xpcall - would require a larger PR.

Each commit is a new change - review the PR commit-by-commit for a nicer (and hopefully easier to understand) diff.

Version control comments from both versions were kept in files with direct backports. No idea if those are meaningful to anyone but keeping them seemed harmless enough.

The changes are largely direct backports and as such all code is written in the Lua code-style not Minetest code style.

### Alternatives

Just require Minetest is built with LuaJIT or continue to accept that some installations of Minetest will have a different featureset.

### CODE REVIEW

**Comment by red-001** [comment]
Ran the Lua internal test suite and I didn't see any suspicious failures. Got some less optimal code generation that got flagged by it, but nothing that seemed like correctness issue.

If we are vendoring-in Lua 5.1 should we be running those tests ourselves in CI?

**Comment by red-001** [comment]
Everything seems to be working, see https://github.com/red-001/minetest/tree/mt_pull_15134_testing for the modified Lua 5.1 test suite used for verification.

**Comment by sfan5** [comment]
I think we should backport the bare minimum amount of patches, because we don't want to maintain a full-blown Lua fork ourselves.
So that would be just __pairs/__ipairs.
*Or* switch to Lua 5.2 proper and make the necessary changes (hopefully small) to keep compatibility with 5.1

I don't get the goal here. It's not like we will have identical behavior with LuaJIT either way, or will we?

**Comment by goodusername123** [comment]
I realize that this pull request is closed due to the realization that LuaJIT does not always have the rawlen function and metamethod stuff here always present/enabled (NOTE: even if it did there would still be compatibility problems due to https://github.com/LuaJIT/LuaJIT/issues/578) but I just want to come in here and leave some notes for future reference or for anyone really that stumbles upon the backports present here.

The backport of `__pairs` and `__ipairs` here in this PR worries me a bit because it carries with it a partial amount of a commit/change from Lua 5.2 intended for It's "[Light C Functions](https://www.inf.puc-rio.br/~roberto/talks/novelties-5.2.pdf#page=4)" system/concept/whatever of which doesn't exist in Lua 5.1
the relevant worrying commit/change that was partially picked up is here: https://github.com/lua/lua/commit/26d4a7396248623985b59d7e027cfecee561f446
I'm no expert when it comes to the internals of Lua but this strikes me as something that *could* possibly cause unforeseen problems somewhere down the pipeline or I'm just overreacting and the worst this might do is just clutter up the Lua 5.1 codebase,
either way it's cleaner and probably more safe just to cherry pick `__pairs` and `__ipairs` directly from this commit here: https://github.com/lua/lua/commit/ab09732986d551efea3f44367ec1221afea72c7d

Additionally the backport of `__len` for tables in this PR is a bit bigger then it needs to be due to it including a bit of rewriting/refactoring that was done alongside it in Lua 5.2 and a smaller backport/patch is available here: https://github.com/dubiousjim/luafiveq/blob/master/patches/table-len.patch

**Pull request closed without merging**
