### PR TITLE
[WIP] Remove unused headers

### PR DESCRIPTION
**Pull request by kilbith**
- Remove unused `#include`'d header files, forward declarations and functions.
- Use `#include` instead of forward declarations where it's appropriate.
- Add missing `static` to functions.

This is WIP, to my estimation I did 20 to 30% of the cleanup.

### CODE REVIEW

**Comment by kilbith** [comment]
Is there an interest in this or should I close?

**Comment by SmallJoker** [comment]
Compiling time won't be affected much de to `#pragma once` guards, but it's surely not wrong to remove unused or duplicated inclusions.

**Comment by pyrollo** [comment]
I like much this cleaning, it is necessary.

I don't clearly understand "Use #include instead of forward declarations where it's appropriate". When is it more appropriate to #include a file rather that just do a forward declaration ?

**Comment by kilbith** [comment]
As reported by Google's `cppclean`, some classes need to be `#included`, but I don't necessarily understand why as the compiler doesn't need to know the complete definition of these classes which are then used as pointer variables...

**Comment by pyrollo** [comment]
Yes that sounds strange. IMO, including headers unnecessarily increases dependencies between source files. If there is no good reason for doing it so, I would prefer keeping forward dependencies.

**Comment by kilbith** [comment]
Ok I get it now. `cppclean` advices to `#include` when the class is forward-declared in the header AND there's an unecesssary `#include` in the `.cpp` file to access the same class.

**Pull request closed without merging**
