### PR TITLE
Fix for ncurses lookup on arch linux

### PR DESCRIPTION
**Pull request by Falmarri**
Arch linux doesn't put it's ncursesw includes inside an ncursesw directory. This script ends up setting USE_CURSES as true, but doesn't pick up any of the headers.

https://bugs.archlinux.org/task/13994

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by sofar** [comment]
Yeah, fairly trivial I'd say. Probably want to merge this for 0.4.14?

**Comment by kwolekr** [comment]
:+1:

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/27ee8d8943080a5dd735c9faa47c726604bafdff

**Pull request closed without merging**
