### PR TITLE
Fix some more joystick issues

### PR DESCRIPTION
**Pull request by m42uko**
This PR fixes some issues with Joystick input:

* Don't use hard-coded 1024 as axis-to-key translation threshold, use the "configured" dead zone.
* Refactor getAxisWithoutDead to use abs() instead of doing manual comparisons.
* Fix handling of wasKeyPressed(), which caused joystick users to be unable to interact with objects (e.g. eating).
* Add dead zone as configurable parameter

## To do

This PR is a Ready for Review.

## How to test

* Set a high dead zone and check when the character starts walking
* Try to eat with a joystick

Other things shouldn't really have any effect apart from clear code. Also, no subsystem other than joystick input should be affected by this.

### CODE REVIEW

**Comment by m42uko** [comment]
This PR is ready for review now. Thanks :)

**Review by SmallJoker — APPROVED** [review]
LGTM.

> Try to eat with a joystick

Sadly no joysticks around to test that.

**Review by rubenwardy — APPROVED** [review]

**Comment by rubenwardy** [comment]
The deadzone on my controller is 10,000. Controller support on desktop sucks so much

**Comment by sfan5** [comment]
So does this PR work for you? Because it didn't for me: https://irc.minetest.net/minetest-dev/2020-12-08#i_5759924

**Comment by m42uko** [comment]
@sfan5, not sure whether you saw my reply the next day: https://irc.minetest.net/minetest-dev/2020-12-09#i_5760059

About never standing still: Did you check that the axis mapping is correct for your joystick (and OS). On my Linux installation, I have to use the default profile even for the XBox controller, and I can only use it o

**Comment by sfan5** [comment]
>  Did you check that the axis mapping is correct for your joystick (and OS)?

I have no idea how I'd check that. I've never done any configuration of my controller and never had to make it work in games.

**Comment by rubenwardy** [comment]
> I have no idea how I'd check that.

Using jstest-gtk

> I've never done any configuration of my controller and never had to in order to make it work in games.

In order for this to happen in Minetest, we need to include a database of controller bindings per platform. SDL has this, and is used by Steam for Steam Input

**Comment by m42uko** [comment]
Yep, (joystick) input in MT is a bit of a mess at the moment, hence why I'm trying to do at least some work on it. Finding a way to detect controller mappings (for example by making MT work with SDL's gamecontrollerdb.txt) is definitely on my list, but before I can get to this, I need to make the basic gamepad functionality work again (which imo also includes #10031).

I don't like working out-of-tree for very long and then having a single huge PR (which then never gets merged). That's why this PR doesn't fix *every* problem there is with joystick input at the moment, but it's a step into the right direction (I think). One might argue that a rewrite of the input system would be more appropriate than keeping this thing alive, but I do not feel confident enough to tackle a full rewrite / refactoring of the input code atm.

> I have no idea how I'd check that. I've never done any configuration of my controller and never had to in order to make it work in games.

You are right, you shouldn't have to check that or do anything for it to work. But current MT expects a certain mapping (might be Linux only), and it's even hard coded in the binary. For some gamepads, I have the problem that the RT / LT axes are mapped to the movement axes, which means I'll have to half-push the triggers for the character to stand still. But as I noted above, I first want to fix the fundamental problems in the gamepad logic, then move on to things like auto-detection of controller mappings.

**Comment by sfan5** [comment]
jstest-gtk shows the wrong mapping (Axis 2 is LT, 3 & 4 would be the second knob) but Minetest mostly works anyway.

But the problem I mentioned earlier remains.
The deadzone (here `joystick_deadzone=10000`) of the walk knob only works in one direction:

https://user-images.githubusercontent.com/1042418/102693542-b4cfce80-421b-11eb-844f-34995885d3bb.mp4

**Comment by m42uko** [comment]
Argh -- I can confirm this bug. I failed to notice it because my joystick axes' zero-point is always shifted in the "positive" direction. Thanks a lot for testing (and sorry for first dismissing your comment).

I have an idea as to what's causing it, I'll look into it asap.

**Review by sfan5 — APPROVED** [review]
Works correctly

**Pull request merged**
