### PR TITLE
Android settings optimization

### PR DESCRIPTION
**Pull request by MoNTE48**
What makes MultiCraft better. Part 1

### CODE REVIEW

**Comment by paramat** [comment]
This may not be a good idea: ```settings->setDefault("chunksize", "3");``` as this causes much more dense pseudorandom caves (especially in mgv6) and dungeons.

**Comment by MoNTE48** [comment]
@paramat, yes, but it significantly speeds up the generation of world. ARM is not so good doing it as x86

**Comment by sofar** [comment]
These settings may work well for android, but then they likely should just be set like this only in the android builds.

I'm not sure if others agree, but why not wrap these settings in
```
#ifdef ANDROID
...
#endif
```

?

**Comment by MoNTE48** [comment]
@sofar, are you so inconsiderate? That's exactly what I did!

**Comment by sofar** [comment]
I'm not inconsiderate.

Here's what I saw:



You could have just politely told me that this was inside such a section,

**Comment by MoNTE48** [comment]
@sofar, https://github.com/MoNTE48/minetest/blob/android2/src/defaultsettings.cpp#L338

**Comment by kwolekr** [comment]
TBH, none of these settings really improve the game, they just nerf Minetest by setting lower defaults for low-performance platforms in places it doesn't benefit much from.
:-1:

**Comment by MoNTE48** [comment]
how many tests you have done? You can confirm your words, or is it just a thought in the ear?

**Comment by ObaniGemini** [comment]
Minetest is an engine, it might be u=customizable, true.
Fact is it might be more customizable for modders/game creators than for players that just want to play. Players might not have to change their own settings to play a game/mod.

I think having fewer settings for user might be less confusing. At least if they exist hide them !
With our 200 options advanced settings menu, we might lose the begginers.

Minetest should have less options for players and more for modders imo. Putting everything as a player option is not a solution.

**Comment by PilzAdam** [comment]
@kwolekr well, Android devices are "low-performance platforms", aren't they? This PR may be a good idea, since Android users probably never tweak the settings, thus we need better default values for Android.

**Comment by rubenwardy** [comment]
:+1:

**Comment by paramat** [comment]
The lower performance settings may be a good idea, but i think the chunksize should stay at 5, if it's at 3 then Android worlds will be different for the same seed, due to how much the pseudorandom caves shape the landscape in mgv6.

**Comment by kilbith** [comment]
Aren't these Android devices gaining power exponentially each year ?

**Comment by MoNTE48** [comment]
@kilbith I do not quite understand you. I used the settings that were optimal for mioh players. I have more than 5 million downloads of the game and I do know what is best for them.

**Comment by kwolekr** [comment]
What I'm saying is that like 98% of the perceived improvement comes from setting the viewing range to 25.  Setting the view range so low is disastrous to gameplay.

**Comment by MoNTE48** [comment]
Yeah, check it has not been easy. In the console Google Play (to which none of the developers did not give access nrz) has a lot of filters for viewing the game a rating for each version. As you know, the slower the game works, the lower the average rating was after the upgrade. In minetest 2 performance issues: mapping the world and generating / saving changes. Technically, my phone for testing (Galaxy s6 edge) able to display range 100+ and FPS 60. However, it is very hot and the battery is consumed within 2 hours. Players do not like games that rapidly drain the battery because they use CPU / GPU maximum potential.

**Comment by MoNTE48** [comment]
Just some of the parameters to optimize the mobs and some other mods that use the entity. As well as clearing unused data to prevent memory overflow (and crash) for 512 RAM

**Comment by asl97** [comment]
@MoNTE48 most of those settings only apply to server (including singleplayer)

afaik, there isn't anything like mobs in the default game and it isn't that easy for average people to install mods direct on android (ie: without a computer).

most people probably play on server rather than host on their android device.
____

also, why `client_unload_unused_data_timeout` instead of `client_mapblock_limit`?
clearing data early would probably just cause more load than setting a mapblock limit to prevent memory overflow.

**Comment by celeron55** [comment]
Can people just prefer to not say anything if they don't use Minetest on Android? This PR clearly only affects Android.

Not that I use it either, but somebody has to say this.

There are so far two valid concerns in these comments:
- `chunksize` affecting map generation
- `client_unload_unused_data_timeout` being used instead of `client_mapblock_limit`

I just tested that `chunksize` is correctly set in map_meta.txt based on the setting when the world was created, so there really are no other issues than generation being different. I'm going to say that if the only apparent real Android user here, @MoNTE48, has decided that 3 is considerably better than 5, then I'm for it and I think others should too.

@MoNTE48: Can you check if `client_mapblock_limit` could be used instead of `client_unload_unused_data_timeout`?

**Comment by DonBatman** [comment]
@asl97 It is easy to install mods now. Rubenwardy made an app for that.
https://play.google.com/store/apps/details?id=com.rubenwardy.minetestmodmanager

I can only play on andriod for short periods because my LG G2 gets too hot. If these settings fix that then I would be happy.

**Comment by Fixer-007** [comment]
Default minetest 0.4.13 from f-droid:
singleplayer, ~24-26fps with mostly v_range 20, yoga tablet 10 (b8000h) / MTK MT8389 QuadCore 1.2GHz, 1GB RAM, 1280*800

Since auto v_range was removed in 0.4.13-dev, android version should be fine with 25 as you suggested. Default 50 could be too high, but we need more devices to test it.

**Comment by kwolekr** [comment]
@DonBatman, could you try these settings?  Try individual settings to see which ones have an impact or not?  We need an independent, objective review of this PR with real android users who a). know what they're doing and b). are not MoNTE48

**Comment by DonBatman** [comment]
default settings - 22fps
viewing_range = 25 - 22fps
max_block_generate_distance = 2 -21 fps
enable_3d_clouds = false -30fps
max_objects_per_block = 20 - 25fps
sqlite_synchronous = 1 - 25fps
gui_scaling = 1.1
server_map_save_interval = 20 - 26fps
client_unload_unused_data_timeout = 30 - about the same as default
active_block_range = 1 - about the same as default
chunksize = 3 - 25fps

If all then my fps stays around 30 whereas default would go anywhere from 14 to 45.

I Think most of these settings are a help.
The gui_scaling made it so I could press the buttons easier.

Will do more testing when I have a little more time

**Comment by MoNTE48** [comment]
@ Celeron55, thank you. Indeed, the problem is that the decisions taken on github not real players, and developers who do not use the version of Android.
If you have 2 options - to reduce the display range and leave the phone cold, or make a high range of the display and the phone will be very hot (and including throttling), then I choose the first option. And it is right.
---
I wrote some of the parameters to decide whether a memory overflow on devices with 512-1024 MB RAM.
---
"Client_unload_unused_data_timeout being used instead of client_mapblock_limit"
To be honest, I just did not check this option yet.
I think you're right, but there is a small problem. If I put this option 1000-2000 (I think it would be optimal), how much will decrease the uniformity of drawing at range view? I believe that this requires additional tests. Who wants to help me?

**Comment by DonBatman** [comment]
@MoNTE48 with client_mapblock_limit at 2000 I get around 1/3 the fps as with 1000.
I did not limit my fps and it was around 40 to 45 fps at 1000. At 2000 it dropped to around 12 to 16

**Comment by MoNTE48** [comment]
@DonBatman, wow. Thank you.
I'm a little surprised by the result. Android is really very, very weak device. It's like a computer which for 10 years.

**Comment by asl97** [comment]
@MoNTE48 if you are gonna be reducing server setting on android (for singleplayer and hosting), you should probably reduce the `liquid_loop_max` too.

**Comment by MoNTE48** [comment]
@asl97, That's right. Sorry :)
I'll see these settings as well. It is difficult enough to check all the settings yourself, it takes a long time.
I will update my pull request later.

**Comment by paramat** [comment]
> If I put this option 1000-2000 (I think it would be optimal), how much will decrease the uniformity of drawing at range view?

The default 5000 seems to use about 2-3GB of RAM, so to stay below 512MB RAM you might want to use 1000 or less.
View range 50 needs ((50 / 16 +1) * 2) ^ 3 = 512 mapblocks to keep everything visible loaded.
View range 25 only needs 64 mapblocks.

**Comment by MoNTE48** [comment]
@paramat, I do not like math :)
What is calculated when the distance rangeview?

**Comment by paramat** [comment]
Sorry i don't understand your question.

**Comment by MoNTE48** [comment]
Sorry..
When I turn on Android rangeview I see several times more. In how many times I see more? Where in the code set out?

**Comment by PilzAdam** [comment]
@MoNTE48 do you mean "full range view"? The thing that you toggle with "R" in the desktop version? This will display everything that the client has loaded; no range restrictions are applied.

**Comment by MoNTE48** [comment]
@PilzAdam Yes! Thank you! I understood. There are no settings or restrictions  for this?

**Comment by rubenwardy** [comment]
No restrictions. That's why it's called full range view.

**Comment by MoNTE48** [comment]
@rubenwardy, mapblock_limit affect this? After all, it limits the maximum number of blocks in the memory.

**Comment by Zeno-** [comment]
I just tried these changes on Android and although I have no hard data (I don't really know how to profile properly on Android[1]) and some of the settings _seem_ like they would make little difference, they do.

[1] I am basing my observations on watching the graphs and FPS

**Comment by DonBatman** [comment]
I think full view range should be limited on android. It only took less then 2 minutes to make the game unplayable when it is on.

**Comment by Zeno-** [comment]
Based on my observations (and surprise to be honest) I can only say that I approve of these changes unless there is something solid suggesting that they're not sound.

**Comment by MoNTE48** [comment]
@Zeno-, In Android Studio has a wonderful system monitor (I can see real time changes in RAM, CPU, GPU and memory load in the graph). Some settings help a little later.
Some settings are useful to those who use the mobs or other abm.

**Comment by paramat** [comment]
> mapblock_limit affect this? After all, it limits the maximum number of blocks in the memory.

Yes, if mapblock_limit is set to 512 you will see up to 512 mapblocks and no more. When walking forward the mapblocks behind you will disappear to keep the total at 512.

**Comment by DonBatman** [comment]
I did some testing on my Nexus 4. These settings make it a lot better. I don't have numbers but can say that it is smoother and more playable. 

@MoNTE48 thanks for helping.

**Comment by Zeno-** [comment]
merged a7be756

Myself and c55

**Comment by MoNTE48** [comment]
@Zeno-, but I did not added client_mapblock_limit :D

**Comment by Zeno-** [comment]
uncommitted

MoNTE48, please add a comment or something at least to say if the PR needs more work hehe

cheers

**Comment by MoNTE48** [comment]
@Zeno-, ready, and I'm sorry for the confusion. I would be grateful for some tips in the future. :)

**Comment by paramat** [comment]
Is mapgen still ok with the same amount of large caves in 1/5th the volume?

**Comment by MoNTE48** [comment]
@paramat, You should check it out, pls. I had some problems with caves (they are sometimes above the ground. But they were a long time, to change the 5 to 3

**Comment by paramat** [comment]
i'll give it a quick test, but i don't oppose chunksize 3, as long as players are happy.

**Comment by paramat** [comment]
In testing it's okay, more caves but not a problem, 3 is fine by me.

**Comment by MoNTE48** [comment]
@paramat "players are happy" - it is a pity that not all developers agree with you :)

**Comment by asl97** [comment]
@MoNTE48 personally, i would think keeping `client_unload_unused_data_timeout` the same would be better, less block loading "lag" as some people might put it.

the other server setting like `liquid_loop_max` doesn't really matter for me since it only affect singleplayer and hosting.

**Comment by MoNTE48** [comment]
A small change. If all is well, I squash commits, and it can be a merge.

**Comment by MoNTE48** [comment]
@DonBatman and @asl97 you can test last commit? If this good, @Zeno-, please, remove WIP labels and ad 0.4.14 milestone

**Comment by paramat** [comment]
```settings->setDefault("max_block_generate_distance", "2");```
I think this is too low, the world would only generate out to 32 nodes from the player.
For non-Android it is 7, a little more than a chunk, so for Android i think 3 + 1 = 4 = 64 nodes which is a reasonable view range.

**Comment by DonBatman** [comment]
@paramat Android is both high end and low end and everything in between. When we talk about computers we have to respect older hardware. Why not Android as well?

**Comment by Zeno-** [comment]
0f6e4a0

**Comment by ObaniGemini** [comment]
Myabe this should be implemented in an update for android ?

**Comment by paramat** [comment]
DonBatman ```settings->setDefault("max_block_generate_distance", "3");``` Wil have little impact on performance as that is largely affected by view range, it just means neighbouring mapchunks are reliably generated so that if a larger view range is used, lanscape looks better instead of stopping 32 nodes away, which is too close.
@MoNTE48 does 3 seem reasonable? We can do another commit to add this.

**Comment by MoNTE48** [comment]
@paramat,  I would like to introduce a new range view for Android today, there I was a little change this setting, too, if you do not mind.

**Comment by paramat** [comment]
Go ahead and we'll discuss in the new PR.

**Pull request closed without merging**
