### PR TITLE
Backport 5.8.1 (Android-only)

### PR DESCRIPTION
**Pull request by grorp**
This is my attempt at an Android-only 5.8.1 release. Please tell me if I have forgotten a commit or something.

The "pause rendering" stuff is intentionally omitted for being hairy (and also for requiring the creation of a new Irrlicht version by means of cherry-picking).

### CODE REVIEW

**Comment by AdityaMH** [comment]
TouchGUI revamp, redesign cdb  👀

**Comment by grorp** [comment]
I found a regression which should be fixed first: #14561

Also, this PR doesn't contain a commit produced by `util/bump_version.sh` yet

**Comment by grorp** [comment]
>  I suppose this is ready and only needs someone to produce and upload the Android build?

I think so.

**Comment by sfan5** [comment]
ping @rubenwardy

**Review by SmallJoker — APPROVED** [review]
Things tested: (Android 6.0, self-signed apk from GitHub actions)

:ballot_box_with_check: Minetest Game install from Content DB
:ballot_box_with_check: World creation (includes text input)
:ballot_box_with_check: Singleplayer world
:ballot_box_with_check: Formspec inputs / formspec close / tooltips / Stack movement / Crafting
:ballot_box_with_check: Autojump / node dig / node placement / node "rightclick"
:ballot_box_with_check: Settings dialogue
:ballot_box_with_check: Remote server join 

Works for me.

**Pull request merged**
