### PR TITLE
add support for the latest C++ standard

### PR DESCRIPTION
**Pull request by ghost**
Thus, people can use some of the new features listed here:
http://www.stroustrup.com/C++11FAQ.html

or here:
http://en.wikipedia.org/wiki/C%2B%2B11

with newer compilers

### CODE REVIEW

**Comment by crazyR14** [comment]
With all due respect why has this been closed within 24 hours.... why has it not been left for discussion. @kwolekr listed his reasons why it shouldn't be merged but what if other users have ideas on how to combat that. I understand your reasons, i just don't understand why this wasn't given a chance to be discussed further. heck only 2 core-developers commented on it and one of them barely said much.

To note I'm not a C++ developer. but I have a basic understanding due to developing in other languages. 
from my understanding IF C++11 was fully supported with all system's then its would likely drastically lower the code base of minetest. and the new features that @hdastwb has mentioned in various post would hopefully make minetest perform better?? 

All im saying is why are we knocking it before anyones had chance to talk about it properly.

I awaits to have my head bitten off and raged at :/

**Comment by nerzhul** [comment]
personally i agree with C++11 if windows 7 and more + supports it (windows XP isn't supported by M$) Ubuntu was okay, we must look at debian to see if it's supported. On archlinux it's good, on recent Fedora and redhat too, on FreeBSD it's good.

What we need to use in c++11, i think:

std::regex
std::mutex
std::thread

**Comment by kahrl** [comment]
I'm not convinced that we need to switch from jthread to std::thread/std::mutex. For example, on Windows std::mutex seems to be whole lot slower than critical sections (which is what JMutex uses): http://stackoverflow.com/a/24470878

**Comment by Zeno-** [comment]
I have said it before and I'll say it again: a lot of people still use LTS operating systems that do **not** support C++11. These are people who run servers. If we discount those people then the audience is decreased.

My VPS does not (fully) support C++11 and I know at least two other people who run (popular or semi-popular) servers that are in the same boat.

To switch to C++11 would require a compelling reason, IMO. This is not compelling enough.

**Comment by nerzhul** [comment]
We need to wait 2 years more :(

**Comment by Zeno-** [comment]
Maybe not 2 years.

But this PS was not and is not worth the effort and disruption (IMO)

**Comment by PilzAdam** [comment]
@nerzhul 

> Ubuntu was okay

No, there is a currently supported LTS version of Ubuntu that does not support c++11 (I happen to use it and as a core dev I'd like to be able to compile Minetes ;-))

**Pull request closed without merging**
