### PR TITLE
Add table.key_value_swap

### PR DESCRIPTION
**Pull request by HybridDog**
- Goal of the PR

A simple helper function which inverts a lua table

- How does the PR work?

See the code and api doc additions

- Does it resolve any reported issue?

No

- If not a bug fix, why is this PR needed? What usecases does it solve?

If you have a list of nodes, e.g. `{"farming:soil", "default:dirt", "default:stone", "default:mese", "default:cobble"}`, and you want to test if nodes at many positions are in this list, you probably do not want to iterate over the list for each node. The proposed function swaps keys and values, so you can use it to convert the list to a set (both are lua tables):
```lua
t = table.key_value_swap{"farming:soil", "default:dirt", "default:stone", "default:mese", "default:cobble"}

local n_found = 0
for i in 1,#nodes_list do
	local node = nodes_list[i]
	if t[node.name] then
		n_found = n_found+1
	end
end
```

## How to test

Try table.key_value_swap(table.key_value_swap(<your_table>)) and see if the table is still the same,
or simply test table.key_value_swap with some example tables.

### CODE REVIEW

**Comment by paramat** [comment]
Not sure if 'invert' is a clear function name to use, as that suggests reversing the order of the table entries (which is what confused me). Maybe a better function name can be used, like 'key_value_swap' or something?

**Comment by HybridDog** [comment]
> Maybe a better function name can be used, like 'key_value_swap' or something?

I have changed it. I called it `invert` before because it is similar to inverting a function.
https://en.wikipedia.org/wiki/Inverse_function 
`key_value_swap` is more easy to understand and descriptive.

**Comment by sorcerykid** [comment]
I feel like there would be much more utility by simply introducing a Set helper class that could solve many additional use-cases, including the example that you cited. Here's the constructor I use:

```
function Set( list )
        local data = { }
        local self = { size = 0 }

        for idx, key in ipairs( list ) do
                data[ key ] = true
        end

        self.values = function ( )
                local k
                return function ( )
                        -- use parens so only return key on each iteration
                        k = ( next( data, k ) )
                        return k
                end
        end
        self.exists = function ( key )
                return data[ key ] ~= nil
        end
        self.insert = function ( key )
                data[ key ] = true
                self.size = self.size + 1
        end
        self.delete = function ( key )
                data[ key ] = nil
                self.size = self.size - 1
        end
        return self
end
```

Your example above would then be:

```
t = Set{"farming:soil", "default:dirt", "default:stone", "default:mese", "default:cobble"}

local n_found = 0
for i in 1,#nodes_list do
	local node = nodes_list[i]
	if t.exists(i) then
		n_found = n_found+1
	end
end
```

**Comment by HybridDog** [comment]
> I feel like there would be much more utility by simply introducing a Set helper class […]

A Set helper class could be useful, too, but the table.key_value_swap function is more generic. It allows inverting tables which are not simple lists, e.g. a table which maps colour words to sRGB colour strings.
FYI, there's a PR about adding classes for datastructures: https://github.com/minetest/minetest/pull/7683

**Pull request merged**
