### PR TITLE
[Mapgen] Fix decoration bug in Valleys

### PR DESCRIPTION
**Pull request by duane-r**
Add a call to updateHeightmap. Remove unecessary code.

#5125

### CODE REVIEW

**Comment by duane-r** [comment]
When I do that, I get snow showing up in places it definitely shouldn't be. For some reason it only seems to be happening in the first chunk generated. Very strange.
grassy-problem-02

**Comment by paramat** [comment]
Very weird.

Problem with this PR is that this:

grassy-problem-01

Is worse than what happens at the moment. So although this is a bugfix the result looks worse, so i think this needs time and investigation. I certainly need to go through the mapgen code myself and clean it up.

**Comment by duane-r** [comment]
The grass issue seems to be connected to the layers of stone that generate at y=47.

**Comment by paramat** [comment]
@duane-r perhaps this PR could be re-opened and changed to just remove the unnecessary block of code? I assume just removing that doesn't create new bugs?

**Comment by duane-r** [comment]
Removing the unnecessary code was what gave me the line of grass, but I'm not convinced that it was the actual cause. It might just have made it more obvious.

**Comment by paramat** [comment]
Ok, something is really screwed up somewhere then.

**Comment by paramat** [comment]
My attempt #5148

**Pull request closed without merging**
