### PR TITLE
IEEE floats: Fix unit test in release mode

### PR DESCRIPTION
**Pull request by paramat**
PR for #7973 as author 'pgimeno' is not on GitHub.

### CODE REVIEW

**Comment by nerzhul** [comment]
please fix the author in the commit

**Comment by paramat** [comment]
Done.

**Comment by SmallJoker** [comment]
Are any other checks required to fix clang as well? http://irc.minetest.net/minetest-dev/2018-12-13#i_5458562

**Comment by pgimeno** [comment]
As it turns out, yes. Clang also lies, but about denormal support instead of NaN support, and I've found no direct detection other than check `__FAST_MATH__`. Replacing the first \#if like this makes it work for both:

```c++
#if defined(__GNUC__) && (!defined(__STDC_IEC_559__) || defined(__FAST_MATH__))
```

The test is an heuristic, it's not perfect, so it can fail if the build sets some exotic math optimization flags. It should work if building without changing flags.

**Comment by paramat** [comment]
Ok will change the '#if' line as described above.

**Comment by paramat** [comment]
Done.

**Comment by pgimeno** [comment]
LGTM. Thanks for creating the PR.

**Comment by paramat** [comment]
Author changed back to me, credit given in commit message instead.

**Comment by nerzhul** [comment]
@paramat please fix the commiter again. After that we can merge

**Comment by pgimeno** [comment]
https://gitlab.com/pgimeno/minetest/commits/pg-fix-ieee-test contains a commit actually authored by me.

**Comment by nerzhul** [comment]
8e4095f06832f4a786a77f4513f6fca9c1f6cc2b

**Pull request closed without merging**
