### PR TITLE
[CSM] minetest.set_node(pos)

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by nerzhul** [comment]
Doc ? what is the goal ? CSM should not write on client map

**Comment by rubenwardy** [comment]
:-1: don't see how this is useful for CSP or audiovisual affects

**Comment by red-001** [comment]
What's the use case for CSM being able to automate node placement?

**Comment by HybridDog** [comment]
> What's the use case for CSM being able to automate node placement?

You can use your own CSM mods to build houses on servers. This is great in my opinion, but it should only be enabled/allowed in creative mode.
And l'd prefer the `interact` function, where you can directly do what's possible in source code (placing, digging, using, secondary using, etc.). minetest.set_node is then just a wrapper implemented in lua which calls interact.

**Comment by paramat** [comment]
:-1: It has been agreed CSM should not write to map, only read.

**Comment by octacian** [comment]
Maybe this could be used only to temporarily write to the client map so as to change the appearance of some nodes locally? However, for this use case, I'd see that meta nodedef would be more useful. For one thing, less destructive although it'd only modify the client map

**Comment by nerzhul** [comment]
definitively not. Writing to client map permit to place solid node and cheat every protection/walls easily

**Comment by ExeterDad** [comment]
I appreciate the attempt... but this recipe for disaster freaks me out a bit.

**Comment by 12Me21** [comment]
Reminder that you can already cheat through protected walls by disconnecting from the internet, breaking through the wall, then reconnecting before you get timed out...

**Comment by paramat** [comment]
Yes we know, there is an issue for that i think.

**Comment by SmallJoker** [comment]
@12Me21 That is unrelated to this issue. The client knows about the map - heck, you can even enable the local map saving and do whatever you want locally as long you don't let the server know of your interactions. Continued in #7207

**Comment by Kimapr** [comment]
I think it would be extremely useful for SSCSM mods, like protection mods undoing undo lag. Please reopen this.

**Comment by paramat** [comment]
It is a feature that absolutely cannot be added.

**Comment by jastevenson303** [comment]
Just because the client sets a node, doesn't mean the server has to agree.

**Comment by ClobberXD** [comment]
I strongly disagree adding this to the CSM API. But SSCSM is a whole different story; IMO, it'd make perfect sense to expose this to the SSCSM API. After all, the whole objective of SSCSM is to distribute the server's load to the clients, and the server basically just supervises the lot. A perfect example is ofc, an area protection SSCSM - if the client already knows which nodes are protected and which aren't, the client can resolve protection violations all by itself, and the server needn't poke its pointy nose into the matter at all. The server would only be informed of this violation, asynchronously by the SSCSM.

**Comment by paramat** [comment]
I'm considering that nerzhul is MT's most enthusiastic promoter of CSM, and even he disapproves of this =) That should be an indication of extreme danger.
> the server needn't poke its pointy nose into the matter at all.

This is bad, not good. Protection obviously has to be managed by the server, as anything in the client can be hacked and abused, and protection is a critical safeguard. The benefit doesn't justify it.

**Comment by ClobberXD** [comment]
> I'm considering that nerzhul is MT's most enthusiastic promoter of CSM, and even he disapproves of this =)

CSM != SSCSM

This PR is only about adding this method to the CSM API, and all the related comments (incl. nerzhul's disapproval) are about adding this to the CSM API. However, https://github.com/minetest/minetest/pull/6045#issuecomment-532130094 suggested adding this to SSCSM, which is what I agreed with. That being said, discussion about SSCSM is probably offtopic in a CSM API PR :)

Btw, if you read my full comment, I said

> The server would only be informed of this violation, asynchronously by the SSCSM.

So what I meant is that the SSCSM would still report to the server about this violation, but asynchronously. i.e. the SSCSM already takes the necessary action, which isn't dependent on the server knowing it.

> anything in the client can be hacked and abused, and protection is a critical safeguard

SSCSM really shouldn't be hackable to the most extent. If it is, then our design is flawed. :)

**Comment by sfan5** [comment]
You are discussing the wrong thing here. This PR adds a function that send node placement to the server as if the user had placed it.
Allowing SSCSM to write to the client map (with certain restrictions) is an entirely different feature and does have a possibility of getting added.

**Comment by ClobberXD** [comment]
Yes, I realised that, sorry.

**Comment by paramat** [comment]
> SSCSM != CSM
This PR is only about adding this method to the CSM API, and all the related comments (incl. nerzhul's disapproval) are about adding this to the CSM API.

CSM means Client Side Modding so contains both client-provided CSM and SSCSM, the author didn't make it clear which types of CSM is meant.
nerzhul's comments also do not make clear which type of CSM he is referring to. However, it's possible that 'Allowing SSCSM to write to the client map (with certain restrictions)' might be acceptable to him.
> So what I meant is that the SSCSM would still report to the server about this violation

I know, but you seem to be suggesting the server no longer checks a node placement for being a protection violation, which is essential, as clientside checking can and will be abused using a hacked client, meaning even a single hacked client could then grief player builds. This is obviously not acceptable.
> SSCSM really shouldn't be hackable at all. If it is, then our design is flawed. :)

Anything clientside is hackable using a hacked client, it has nothing to do with bad design, it is simply inherently possible.

Anyway, it is a little too early to discuss SSCSM features when there has been no progress for over 2 years and no sign of progress. SSCSM may never happen. This issue is a waste of time.

**Pull request closed without merging**
