### PR TITLE
Fix freetype detection

### PR DESCRIPTION
**Pull request by AMDmi3**
Don't reinvent freetype detection, use working one from cmake. This fixed build w/freetype on FreeBSD.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Pretty much just reverts cb7bb736c70afa7e7dfc90545ad52992a35dc082, which was merged for a reason.

**Comment by AMDmi3** [comment]
Because it doesn't know that it doesn't work with pkgconfig. The problem is that it adds -lfreetype to link flags, but doesn't add -L/usr/local/lib in which libfreetype lives, so link fails. Using pkgconfig output directly is ill-formed with cmake anyway as it has more capable include/library search facilities which provide full path to the library instead of fragile -l/-L flags (however pkgconfig output may be used as a hint to them). Standard FindFreetype does this correctly, and as I remember, problems with changed freetype include layout and FT_FREETYPE_H to which cmake bugs in quoted commit refer were resolved long ago.

**Comment by kwolekr** [comment]
Can confirm that freetype detection is currently broken on FreeBSD.  This fixes it.

**Comment by Zeno-** [comment]
This was discussed and the seed of doubt was whether or not http://www.cmake.org/Bug/view.php?id=13959 is still an issue (despite it still being open). I believe that @est31 made some inquiries but I don't know what the final outcome of those inquiries was.

**Comment by est31** [comment]
Unfortunately, the inquiries were fruitless.

**Comment by nerzhul** [comment]
@kwolekr not sure this is broken, look at this jenkins build:

http://jenkins.unix-experience.fr/job/minetest%20-%20FreeBSD%20-%20Official/330/console

The system find freetype and this PR is not applied there

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/d2fc98e4a689288a04d07da49b673f39ffabf64b

**Pull request closed without merging**
