### PR TITLE
Update settings tab + some misc. clean-up

### PR DESCRIPTION
**Pull request by kilbith**
Fixes https://github.com/minetest/minetest/issues/3812
- Added a dropdown for the node highlighting (might be changed back to a checkbox).
- Added Tone Mapping checkbox.
- Support for multi-spaced float values in the advanced settings menu.
- Style cleaning, better flexibility and code reduction.

Tell me if I should remove or add anything else.

Cc: @PilzAdam @paramat

### CODE REVIEW

**Comment by Fixer-007** [comment]
You forgot about VBO, very important setting :}

**Comment by est31** [comment]
A checkbox for the node highlighting would be fine with me as well.

**Comment by paramat** [comment]
Actually now i would prefer a dropdown for 'box' or 'halo' in simple settings menu, as in this PR.

**Comment by paramat** [comment]
I'll test soon.

**Comment by paramat** [comment]
Tested, node highlighting and tone mapping options work fine.

**Comment by kilbith** [comment]
That's right, was unused and preferable to stay in advanced settings. Removed.

**Comment by Fixer-007** [comment]
VBO improves fps for many players, it should be easily accessible.

**Comment by kilbith** [comment]
This is already enabled by default. End of story.

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
Why allow multi spaced float values? One space should be enough for separation, no?

**Comment by est31** [comment]
Perhaps put the description into the commit msg as well.

Other than that: :+1:

**Comment by kilbith** [comment]
> Why allow multi spaced float values?

It is more error-tolerant and can only be positive. One can add one more space by inattention and be bothered trying to find why it doesn't work... The other types already support that by the way.

**Comment by est31** [comment]
Seems they do indeed... I redact my objection in that point then.

**Comment by est31** [comment]
Merged as 335ad705e6cb3cad4ba1a1e27d36d77d163777e8

**Comment by kilbith** [comment]
I was still cleaning something else... :-/

**Comment by kilbith** [comment]
@est31 Can you hard reset and leave me finish my work please ?

**Comment by est31** [comment]
Its outside of the ten minute window, sorry, seems you have to open a new PR. I haven't seen you were still working on this.

**Pull request closed without merging**
