### PR TITLE
Water surface shader.

### PR DESCRIPTION
**Pull request by RealBadAngel**
screenshot_1917005606

### CODE REVIEW

**Comment by nerzhul** [comment]
Hi @RealBadAngel , can you rebase please ?

**Comment by C1ffisme** [comment]
I like the looks of this, although on my laptop, I'll probably never get to use this shader.

**Comment by nerzhul** [comment]
@c1ffisme why did you say that ?
Shader code is cleaner and faster

**Comment by C1ffisme** [comment]
Well, basically, :+1: , even if I won't see this. My laptop is a Latitude.

**Comment by nerzhul** [comment]
oh, i see.
But it works on my optiplex with intel GPU at work, maybe it will work well with yours

**Comment by paramat** [comment]
Is this high-res water surface the default? It is unsuitable for the 16 pixel low-res abstract world of Minetest, looks completely out of place, too realistic and too high-res.

**Comment by indriApollo** [comment]
What is it with all the realism ? Minetest is a voxel game, consisting of CUBES. People which want different graphics/style should try Gmod instead. I'm not against this PR, as long as it isn't made default tho

**Comment by nerzhul** [comment]
I rebased this pr yesterday. It's good except the broken flowing water . for realism shader maybe have an option to switch ?

**Comment by paramat** [comment]
Yes shaders are optional, and players who like shaders will probably like a realistic water surface. (celeron55 doesn't like shaders, neither do i).

**Comment by nerzhul** [comment]
@RealBadAngel do you think you will continue this PR ?

**Comment by MirceaKitsune** [comment]
I'm eagerly waiting for news as well. This is one of the first new features I wish to see in Minetest.

**Comment by kilbith** [comment]
I think it ought not force using a HD texture for seeing the water reflection. Every low-res water texture should be sunlight reflective.

**Comment by HybridDog** [comment]
Could you add realistic water reflections?
http://imgur.com/gallery/mdNtE

**Pull request closed without merging**
