### PR TITLE
Add missing languages to settingtypes.txt

### LINKED ISSUE #10717: No zh_CN and zh_TW locale in the setting list but they are usable
##### Minetest version

This problem happens on both 5.3.0 and 5.4.0

##### Summary
I can't see `zh` lang options in the settings list, I can't use them by edit `minetest.conf` without edit `builtin/settingtype.txt` either.

I can use it in 5.4.0 with default lang, but I can't use it normally in 5.4.0 windows

##### Steps to reproduce
1. Try to find `zh_TW` or `zh_CN` in the lang list
2. You can't find them
3. Then, change the lang to `zh_TW` or `zh_CN` in `minetest.conf`
4. After you restart, the language change to blank
5. Change `builtin/settingtype.txt` , add two zh to it: `language (Language) enum   ,ar,ca,cs,da,de,dv,el,en,eo,es,et,eu,fil,fr,hu,id,it,ja,ja_KS,jbo,kk,kn,lo,lt,ms,my,nb,nl,nn,pl,pt,pt_BR,ro,ru,sl,sr_Cyrl,sv,sw,th,tr,uk,vi,zh_TW,zh_CN`
6. You can now use Chinese now
7. If you are using a Chinese computer, you can use Chinese without any change, but I don't know why my Chinese windows computer can't use it normally.

### PR DESCRIPTION
**Pull request by Emojigit**
Close #10717 

## How to test

1. Go to settings page with this fork
2. find language, you can find `zh_TW` and `zh_CN` there

### CODE REVIEW

**Comment by sfan5** [comment]
The list is missing a few others too, please change it to:
`,be,bg,ca,cs,da,de,dv,el,eo,es,et,eu,fi,fr,gd,gl,hi,hu,id,it,ja,jbo,kk,kn,ko,lt,lv,ms,nb,nl,nn,pl,pt,pt_BR,ro,ru,sk,sl,sr_Cyrl,sr_Latn,sv,sw,tr,uk,vi,zh_CN,zh_TW`

**Comment by Emojigit** [comment]
> The list is missing a few others too, please change it to:
> `,be,bg,ca,cs,da,de,dv,el,en,eo,es,et,eu,fi,fr,gd,gl,hi,hu,id,it,ja,jbo,kk,kn,ko,lt,lv,ms,nb,nl,nn,pl,pt,pt_BR,ro,ru,sk,sl,sr_Cyrl,sr_Latn,sv,sw,tr,uk,vi,zh_CN,zh_TW`

@sfan5 You list have missing languages. seems like all languages starts with `a` and some start with `b` are missing.

**Comment by sfan5** [comment]
The ones that are missing are so intentionally, since they don't work. See:
https://github.com/minetest/minetest/blob/437d01196899f85bbc77d71123018aa26be337da/src/CMakeLists.txt#L667-L675

**Comment by Emojigit** [comment]
> The ones that are missing are so intentionally, since they don't work. See:
> 
> /src/CMakeLists.txt 667-L675

@sfan5 Fixed

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
