### PR TITLE
L-system: Fix leaves cutting through stems

### PR DESCRIPTION
**Pull request by HybridDog**
See [moretrees](https://github.com/minetest-mods/moretrees/issues/34) for a description of the problem.
I tested it with a sequoia tree successfully.

### CODE REVIEW

**Comment by paramat** [comment]
Yes we has this problem in schematic-placed trees and added per-node force-place to schematics.
Trunk/branch nodes meed to force-place but leaves should not.
You could perhaps use an existing nodedef to determine force-placement.

**Comment by paramat** [comment]
The problem with this PR is that it only works with the leaves and fruit nodes of the currently generating tree, this needs to work with pre-existing nearby trees. So how about always placing trunk nodes without checking for leaves? But this can grief, so we need the leaf nodes used in L-system trees to have a particular value in a particular node parameter to act as a flag that it is a leaf or fruit, how about 'is ground content'?.

**Comment by HybridDog** [comment]
paramat, this PR is a simple fix for that moretrees issue, a flag in the nodedef indicating that trunks can replace the node when a tree grows would require every mod with this problem to update their leaves nodes.
Currently there's _is_ground_content_ and _buildable_to_ which indicate in which situations the node is allowed to get removed/replaced. Other flags, e.g. one that tells whether it can be replaced by a trunk node at tree growth, could be quite useful for L-system and other functions. Ignore and air would get this flag and the l-system would check this instead of ignore and air.

**Comment by paramat** [comment]
Yes this PR is an improvement certainly.
:+1: if tested.

**Comment by paramat** [comment]
4493d47a51dee4c785c009897ee4702850921503

**Pull request closed without merging**
