### PR TITLE
Improve occlusion culling accuracy.

### PR DESCRIPTION
**Pull request by lhofhansl**
Update: This is now improved accuracy of occlusion culling. If a block is visible it usually determined pretty quickly. If the block is a block is occluded, however, an extra set of 8 rays is sent out to improve accuracy, especially in tunnels and other "tight" scenarios. 
All performance improvements are removed.

Was:

Thinking about all this it occurred to me that the falsely occluded block probably have to with the extreme angles close to the camera. Indeed if that search just starts BS * 4 away from the camera I was not able to see any wrongly occluded blocks in all the scenarios I could find.

@Fixer-007 , @paramat any chance that you could repeat your tests with this?

### CODE REVIEW

**Comment by Fixer-007** [comment]
I can.

**Comment by Fixer-007** [comment]
It feels as bad as that PR you merged and fixed, still some visible occlusion blinking.

**Comment by lhofhansl** [comment]
Hmm... I clearly do not have right scenarios. I was "standing" behind a column of nodes looking past them. With #4922 I could see issues, with this not.

Btw. I tried disabling occlusion culling completely and with my H/W some scenes actually sped up (less CPU work), while others showed down (when most blocks are occluded)

**Comment by lhofhansl** [comment]
I'll update this pr with more ideas :)
But it is possible that the ray tracing is simply not precise enough and we need these hacks.

**Comment by lhofhansl** [comment]
It's not for merging (in case that wasn't clear :) )
Just throwing some stuff out for trying. 

Next thing to try: sending out more rays (to 1/2 the corners)

**Comment by lhofhansl** [comment]
Pushed a new commit that sends out twice as many rays (only if earlier tests still do not occlude the block).
This is trying a cube inside the mapblock of 1/2 the size.

I tried tunnel scenarios now. While it does not eliminate all glitches it's better than the default (where we require two occlusions). But it's also potentially twice the work on the CPU.

**Comment by Fixer-007** [comment]
This new change is pretty good, more occlusion and not many visible occlusion cases.

**Comment by lhofhansl** [comment]
Thanks @Fixer-007 are the glitches better or worse with the PR?
In tunnels it almost completely prevents the glitches that have bothered me forever, but I'm sure there're many other scenes. Another thing I'll try is to offset the starting points of the cast a bit away from the eye.

**Comment by lhofhansl** [comment]
(The offsetting didn't help)

With this, though, if there're fewer glitches than the default, this should be good.
W.r.t. to CPU, if the block is determined to be visible early on, than there's no extra cost. If the block is occluded, though, it now performs twice as many tests.

**Comment by Fixer-007** [comment]
Fewer glitches compared to original https://github.com/minetest/minetest/pull/4922

**Comment by lhofhansl** [comment]
@Fixer-007 sorry I meant against what is actually merged into MT right now (i.e. #4922 after the fix), is this net better or do you see more glitches?

In the tunnel scenarios I tested I see fewer glitches now.

**Comment by lhofhansl** [comment]
Some shots.
With PR:
screenshot_20161220_123845

Without (you see the end of the tunnel is incorrectly occluded):
screenshot_20161220_123807

With PR:
screenshot_20161220_124247

Without (you see only 168 blocks occluded as opposed to 226):
screenshot_20161220_124336

So this is (1) more accurate and (2) renders fewer blocks (when possible).

**Comment by lhofhansl** [comment]
OK... Factored the cube-corner checking into its own method, added useful (I think) comments to the occlusion code. Have a look.

**Comment by Fixer-007** [comment]
>i.e. #4922 after the fix

hard to say, I think it is mostly the same, but need careful check, didn't compared yet.

**Comment by paramat** [comment]
Will consider after release.

**Comment by lhofhansl** [comment]
Of course, this is not for .15

**Comment by lhofhansl** [comment]
I think we can remove the WIP label and replace it with "Testing".

**Comment by Fixer-007** [comment]
Will test it.

**Comment by Fixer-007** [comment]
This PR also causes this kind of occlusion lag: https://imgur.com/a/qoQX0
Compare it with build without this PR: https://imgur.com/a/Ik91r

**Comment by lhofhansl** [comment]
Hmm... Interesting. Cool test!

This is an effect that happens with occlusion culling, the only way I can think of to avoid that is not to occlusion cull.

Without this PR there's no culling in this scene (pretty sure at least, since there's only one block depth blocking the sight, and without this PR would not consider the blocks behind occluded).

So not sure where to go from here. Is not having this lag worth not doing the culling in many scenes?

**Comment by lhofhansl** [comment]
Of course, one can say the aim is to reduce visual artefacts. In that case one might want to add the extra accuracy *and* keep the requirement on two occlusions per ray. So we would cull slightly fewer blocks, but be more accurate in doing so.

**Comment by paramat** [comment]
From the effect of 'needed count = 1' i experienced i am getting a feeling 2 is needed, i don't really know why, you would think 1 is enough.
That this PR uses 1 may make occlusion worse even though you are testing more points.

**Comment by lhofhansl** [comment]
Yeah. I'm also thinking that for some reason needed count = 2 is not as bad as I thought, although - like you - I cannot explain why that would be.

**Comment by lhofhansl** [comment]
I'm also thinking that step_fac is too high. It means every step (initial BS * 1) we're increasing the step size by 10%. A step is in nodes (not blocks), 1.1^node_distance grows fairly quickly. It seems 1.05 would be better.
In the worst case (view_range = 4000) would still terminate after 107 step per ray (or 61 with 1.1), but be quite a bit more accurate.

Anyway. Now I'm back to tweaking knobs, not sure that would actually lead to anything.

**Comment by paramat** [comment]
Maybe the step factor is the reason for needing a count of 2? The step starts skipping nodes after only 8 steps.

**Comment by lhofhansl** [comment]
Unfortunately it's the opposite. The larger step size makes it more likely to _miss_ a node that could occlude a block.

**Comment by lhofhansl** [comment]
I think I'm not going to follow this line of thought any further.
If we wanted to make the accuracy twice as good (which is very apparent in tunnels and other tight setups, perhaps streets, etc) we could add this code (and leave needed_count as is at 2).

For each block that actually is completely occluded we double the effort to confirm that. For a view range of 200 that'd be on average perhaps 20 calculations per corner per visible block. I.e. 9 before, 17 with this pr.
The visible cone of view-range 200 would have about 6000 map blocks.

Assuming 1/2 the blocks are hidden we'd get about 20*9*3,000 = 540,000 vector calculations and retrieval of mapnodes. With the PR it'd be 20*17*3000 = 1,020,000. These are just guesses. Assuming we want to achieve 60 FPS, that'd be about 60m of these per seconds. Now this pretty pessimistic. I guess folks should do performance testing. In my tests the framerate is unaffected. And tunnels look far better.

I'll upload the PR to do that. I.e. leave needed count at 2, but send out more rays. Then folks can play with it, and if there's consensus we can merge it... Or not, if we feel it's overkill.

**Comment by lhofhansl** [comment]
Did just that. This is now strictly an improvement of occlusion culling accuracy at the expense of more CPU power used. Have a look, test it out. Scenes most improved should be tunnels and other likewise confines spaces.

Note that when a block is visible, we'll likely determine that quickly, and I do not expect more CPU to be used in that case. When blocks are completely occluded this would spend more time to prove that.

...

In general I now think that doing a breadth first search for visible blocks starting from the one containing the camera is a better approach than ray-casting.
That approach should be (1) perfectly accurate, in that it's ever mark a block occluded if it's visible, and (2) faster in terms of CPU, (3) as an added benefit the blocks would be sorted already in closest to furthest order as seen from the camera, so rendering on the GPU become cheaper.

I'd have to think a bit more about to do that exactly, especially how to calculate and prune the reachability graph.

**Comment by lhofhansl** [comment]
Another idea is just 3D directed flood filling the transparent parts and see which blocks can be reached that way.

**Comment by lhofhansl** [comment]
Another theory for why `needed_count = 2` is needed. It just bugs me that I could not explain why this is needed.

Consider the initial step size. It's `BS * 1`, but if we look sideways through a block we need up to sqrt(3) = 1.73 steps to clear the block. So looking a bit sideways it's quite likely that we'll see the same block twice. So we can start with `step = 1.73...` and step_fac = 1.05. We'll arrive at the roughly same number of a step (assuming a view_range of 200).

Or in `isOccluded` one could check whether the next step arrived on the block, if so, just continue on.

**Comment by lhofhansl** [comment]
Going to close this one. No need to keep this open while I experiment with stuff.

**Comment by sfan5** [comment]
we have the `WIP` label for that

**Comment by Fixer-007** [comment]
@lhofhansl 
Side question on culling, maybe you know: could v_range affect efficiency of culling? Since we change v_range in 10s, and not in 16s, could it be inefficient and cause more rendering in some cases? Say if I'm using default v_range 100, which is 6.25 nodes, but not 96 nodes. Just curious.

**Comment by lhofhansl** [comment]
Hi @Fixer-007 v_range does affect the efficiency, but that has nothing to do with whether we increment in 10's or 16's. It only culls nodes in the visible range.

**Comment by alexeysvrv** [comment]
Any progress?

**Comment by rubenwardy** [comment]
What's the status of this?

**Comment by Fixer-007** [comment]
It is very tricky to improve occlusion without visible picture degradation at least the way it was done in this PR.

**Comment by paramat** [comment]
@lhofhansl what's your opinion of this currently?

**Pull request closed without merging**
