### PR TITLE
Fix isDead()/autoforward crash

### LINKED ISSUE #9030: isDead() related crash on new world start
I am on commit 81c2370c8b1a66a279a5ff450c78caf5dfef77bf 6 commits back at this time.
Crash on new world start related to 'isDead()':

ERROR[Main]: /home/matstandard/minetestf/gitmods/minetest/src/client/localplayer.cpp:2c7: bool LocalPlayer::isDead() const: A fatal error occurred: LocalPlayer's CAO isn't initialized

To reproduce:
Enable autoforward, while moving leave world, re-enter world.

Important for 5.1.0 as we are considering what to revert in relation to 'isDead' stuff.
I'm fine with a full revert that would leave dead players creeping forward if they were using autoforward, this is a minor and amusing bug.

### PR DESCRIPTION
**Pull request by paramat**
Closes #9030

### CODE REVIEW

**Comment by ClobberXD** [comment]
A permanent, and yet an equally trivial solution, would be:

```cpp
// WARNING: Untested
if (player->getPlayerSettings().continuous_forward &&
		(m_client->activeObjectsReceived() && !player->isDead())) {
```

**Comment by paramat** [comment]
I'm happy to convert this PR into the patch above if preferred. Thanks for that.

**Comment by paramat** [comment]
Updated to patch and tested.

**Comment by ClobberXD** [comment]
Thanks :+1:

**Pull request merged**
