### PR TITLE
Fix modpack rename

### PR DESCRIPTION
**Pull request by numberZero**
Fixes part of #7370 
@Fixer-007

### CODE REVIEW

**Comment by Fixer-007** [comment]
Does not solve the problem.

**Comment by numberZero** [comment]
@Fixer-007 Does the modpack you try to rename contain the `mod.conf` file?

**Comment by rubenwardy** [comment]
Modpacks should not contain mod.conf

**Comment by Fixer-007** [comment]
>Modpacks should not contain mod.conf

@rubenwardy 
They do when you download via "Browse online content"

**Comment by rubenwardy** [comment]
Ah, I've made a bug there then

**Comment by paramat** [comment]
#7370 seems fixed, is this still needed?

**Comment by numberZero** [comment]
@Fixer-007 is rename part of #7370 fixed?

**Comment by Fixer-007** [comment]
I will check once more, without this PR.

**Comment by Fixer-007** [comment]
>@numberZero #7370 seems fixed, is this PR still needed?

Modpack rename does not work for me in vanilla (try homedecor), and this PR does not fix it as I stated earlier.

**Comment by paramat** [comment]
How does this relate to #7647 and #7892 ? is it replaced by 7892?
Marking as blocker as needs consideration as a bugfix for CDB.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/pull/8161

**Pull request closed without merging**
