### PR TITLE
Main menu background images

### PR DESCRIPTION
**Pull request by kilbith**
The current formspec for the main menu is austere, boring and untweakable. This pull includes a new style of design.

Please, click on the images (full-view) and set the zoom of your web-browser at 100% to see the real thing. Or download them for trying.

The full album : https://mediacru.sh/60c17d29204e

### CODE REVIEW

**Comment by kilbith** [comment]
@MoNTE48 : fixed, sorry.

**Comment by kilbith** [comment]
@ShadowNinja @PilzAdam 

Agree with you but every thing has its time, step by step. The menu has not been improved since years and no-one seems to be motivated about working on a complete formspec redesign. Do not expect that for a (long) while...

These textures is a step succeeded for the redesign. Visual comfort is much better just in adding them and people enjoy :)

**Comment by kilbith** [comment]
Update : removed the style 1 & tabs images because of incompatibilities and poor-rendering with some clients. Example here : http://i.imgur.com/zILhAuO.png

Style 2 (without the tabs) remains OK in any cases.

**Comment by kilbith** [comment]
This is a static visual applying. Inapplicable with the dynamic scaling configuration and I'd prefer a customizable stylizing.

**Comment by MT-Modder** [comment]
Oh okay.

**Pull request closed without merging**
