### PR TITLE
Breaking world limits. Part 1

### PR DESCRIPTION
**Pull request by proller**
- Goal of the PR
Start process of breaking 62000 nodes limit   
- How does the PR work?
Adding two alias types:
pos_t=s16 for nodes
bpos_t=s16 for blocks (can be changed to pos_t, but makes good visible difference between node and block coords)
adding configurable cmake variable:
USE_POS32=false
for switching pos_t=s32 , bpos_t=s32

all uses of map s16 changed to pos_t and bpos_t
now by default all types stays s16 inside - nothing broken. 

- Does it resolve any reported issue?
https://github.com/minetest/minetest/issues/8660
https://github.com/minetest/minetest/issues/10257

- If not a bug fix, why is this PR needed? What usecases does it solve?
62000^3 is too small for me.

## To do
(later in other prs)
Do something with object's v3f - its too buggy for big values.
Change them to doubles or keep v3s32 offset near pos
Fix teleport to huge coordinates

This PR is Ready for Review.

USE_POS32 broke client-server protocol, it can be enabled after fixing all bugs in some major versions. 

## How to test
cmake -DUSE_POS32=1 .

Now works with devtest game
dummy, leveldb, redis, postgres backends should work.
sqlite - sorry, need to change table.

part 1: this pr. Only s16->s32
part 2: https://github.com/minetest/minetest/pull/11910 add float -> double (smoother movement& objects)
part 3: https://github.com/minetest/minetest/pull/12142 add network compatibility with old clients

### CODE REVIEW

**Comment by TurkeyMcMac** [comment]
What's the plan for node position hashing? Maybe the function could return a string instead of a number.

**Comment by proller** [comment]
Already done with backward compatibility in leveldb and redis.
(btw WHY hashing to int used for string key-value bases? just save and read plain text coords...)

**Comment by TurkeyMcMac** [comment]
I was mostly talking about the API function `minetest.hash_node_position`.

**Comment by proller** [comment]
hash_node_position can use strings like "x,y,z"

**Comment by erlehmann** [comment]
> now by default all types stays s16 inside - nothing broken.

That sounds amazing, almost to good to be true. Do you have any proof of that?

**Comment by erlehmann** [comment]
Question: How to migrate old worlds?

**Comment by nerzhul** [comment]
i clearly don't like the name.
call it pos_t it's more standard like c++ types (uint32_t, size_t, etc). Use a typedef not a macro it's better and more modern.

Outside of the map size changes, at least a coordinated naming for this coordinates is appreciated :)

**Comment by appgurueu** [comment]
Agreed with nerzhul, it must be be `pos_t`. We may use `s32` internally, but in order for node hashes to fit into 52 bytes (so that `minetest.hash_node_position` can continue working), the best we can do is `s17`, which would double world size.

**Comment by proller** [comment]
> Question: How to migrate old worlds?
No need to migrate.
leveldb, redis : block positions less than 31000/16 still written in old int hashed format (but i strongly disagree with this, why need to convert to int for string keys?)
positions larger than 31000/16 wroten in new (old freeminer ;) format "aX,Y,Z"
postgres: uses 3 int columns, should work.
sqlite: sorry.

**Review by ShadowNinja — CHANGES_REQUESTED** [review]
SQLite3 can use the same method as LevelDB, the column type is actually only a suggestion -- all columns use dynamic typing.

And if there's a database that can't handle this change it needs to limit the world dimensions and check block position are in range, so that it doesn't just overwrite unrelated blocks and corrupt the world.

**Comment by appgurueu** [comment]
> SQLite3 can use the same method as LevelDB, the column type is actually only a suggestion -- all columns use dynamic typing.

SQLite numbers can use up to 8 bytes, which is enough for 21 bits per coordinate, allowing for roughly 1 million nodes in every direction.

But there's more to consider. We currently use floats in lots of places, for instance (entity positions, velocities, accelerations, rotations, most of rendering, ...). Those have 23 mantissa bits. We must ensure that we do not get any major errors there. Just bumping `v3s16` to `v3s32` is absolutely insufficient. Let me repeat: *You can't provide 32 bits for every coordinate.* You must reduce it.

**Comment by proller** [comment]
For sqlite best method of storing coordinates is splitting to three columns X, Y, Z and use multiindex on them.
If splitting too hard - one text field with "aX,Y,Z" format can be used.

Limiting coordinates is very simple. just find acceptable value and set MAX_MAP_GENERATION_LIMIT

**Comment by TurkeyMcMac** [comment]
I think we could stuff more than 52 bits of information into a Lua number. I think fitting 61 bits is possible.

For any integer from 0 to 2^48-1, the exponent shouldn't be more than 1023+47 (the 1023 is to offset the bias.) Therefore, the exponent bits should always be less than 10100000000 (binary).

Here is my proposal:
1. If the exponent bits are less than 10100000000, the coordinate hash should be parsed in the old 48-bit way.
2. Otherwise, the bits of the floating-point number can be considered like so:
    `b101bbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb`
    The free bits (`b`) can be split into the coordinates. X and Z can each get 22 bits and Y can get 17 bits.
3. When encoding hashes, the old way should be used if the coordinates can fit into 48 bits.
4. The code will probably have to be written in C++ since it needs type punning and stuff. If extra calling speed is needed, LuaJIT's `ffi` library can be used internally when available.

If implemented, this proposal would double world height and multiply world width by 64 along both the X and Z axes.

The advantage of this over 32-bit coordinates would mostly be compatibility. Users of `hash_node_position` and `get_position_from_hash` wouldn't notice anything unless they needed to the hash values. Old SQLite3 map databases could be migrated seamlessly.

I doubt there would be much performance impact, especially if `ffi` is used.

The size of the object position encoding would probably still have to increase.

Hopefully I haven't made any mistakes in my analysis here. I got my information from this article: https://en.wikipedia.org/wiki/Double-precision_floating-point_format.

**Comment by appgurueu** [comment]
> Users of `hash_node_position` and `get_position_from_hash` wouldn't notice anything unless they needed to the hash values. Old SQLite3 map databases could be migrated seamlessly.

Are you sure that serialization preserves both exponent and mantissa accurately? I'm certain that "integer" floats will be serialized properly by `minetest.write_json` and `minetest.serialize`, but I'm not sure the same holds for floats with exponents (it should, though).

The sign bit shouldn't be too much of a hassle to use.

**Comment by TurkeyMcMac** [comment]
You're right. Some of the numbers involved are very large. For example, this is a valid double-precision integer: 26815615859885194199148049996411692254958731641184786755447122887443528060147093953603748596333806855380063716372972101707507765623893139892867298012168192

`minetest.serialize` and `minetest.write_json` don't accurately encode such large numbers, but a scaled-back proposal will work:

1. The new representation is `b1000011 00bbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb bbbbbbbb`.
2. X and Z get 19 bits each, and Y gets 17 bits still.
3. The X and Z axes are now just octupled in length.

I think 55 bits is the most that can be fit, unless `minetest.serialize` and `minetest.write_json` are modified (which certainly could be done.) Of course, node position hashes could also just be changed into strings, though I don't know what the performance implications of this would be.

**Comment by v-rob** [comment]
In practicality, would any mods break if `minetest.hash_node_position()` returned an integer for values in the `s16` range and a string when outside that range?  That would make any existing databases with positions continue to work.  In theory, of course, a mod could be doing arithmetic on the number or packing it further or something, but does anyone know of a legitimate use-case for doing such a thing, and is the probability of a mod doing that very likely?

**Comment by appgurueu** [comment]
> In practicality, would any mods using normal usecases of `minetest.hash_node_position()` break if it returned an integer for values in the `s16` range and a string when outside that range? That would make any existing databases with positions continue to work.
> 
> In theory, of course, a mod could be doing arithmetic on the number or packing it further or something.

The only way to find out is to do a [quick search](https://www.google.com/search?q=%22minetest.hash_node_position%22), which reveals [mapgen using the hash as a seed](https://github.com/minetest-mods/mapgen_helper/blob/master/random.lua#L6).

**Comment by rubenwardy** [comment]
How are you handling compatibility?

**Comment by appgurueu** [comment]
> Enabling s32 types by default will take months or years and everybody who want can start testing and fixing lot of small bugs in another pr's

Then this feature should be removed.

**Comment by TurkeyMcMac** [comment]
I can see the process taking several months, but why would enabling s32 by default take multiple years?

**Comment by proller** [comment]
> I can see the process taking several months, but why would enabling s32 by default take multiple years?
I dont know how many exactly it take. but minetest development not very fast.

What should be done for enbling:
1. switching all float v3f world positions to double in same alias way (maybe i will do this)
   good news: lua already have double inside number type
   after making doubles BS can be setted to 1 (with fixing lot of bugs) - to make all coordinate position system same and remove all *BS /BS conversions

2. decide what to do with network protocol compatibility:
2.1 just bump proto version and make incompatible (subject for minetest 6.х)
2.2 OR write network compatibility code (convert pos_t to s16 before sending to old client, same to doubles)
      31000+ positions can be skipped or replaced with some dummy -31000,-31000,-31000

3. test anything with lot of players and servers (mods, load/save old worlds) with fixing many bugs

4. release with USE_POS32=1
5. remove old code under USE_POS32=0

**Comment by erlehmann** [comment]
> fixing lot of bugs

I like that part the most.

> write network compatibility code (convert pos_t to s16 before sending to old client, same to doubles)

I guess the server could pretend to teleport an old client approaching (30000,0,0) to (0,0,0) and keep sending mapblocks, with fake coordinates offset by (-30000,0,0) … ?

**Comment by AFCMS** [comment]
> I guess the server could pretend to teleport an old client approaching (30000,0,0) to (0,0,0) and keep sending mapblocks, with fake coordinates offset by (-30000,0,0) … ?

Would mess the basic debug HUD and all CSM using `minetest.localplayer:get_pos()`...
Would be better to just disallow old clients who try to connect a new server.

**Comment by nerzhul** [comment]
having x,y,z in database as a int64 is the best solution for having proper index resolution. if i remember pg already does it, but we need a conversion for other dbs

**Comment by Wuzzy2** [comment]
Replacing s16 with a typedef is a good idea regardless whether Minetest world size will actually increase later on.

**Comment by appgurueu** [comment]
> Replacing s16 with a typedef is a good idea regardless whether Minetest world size will actually increase later on.

Definitely. But there are some other, instable changes (such as the experimental s32 support) included which I feel should be part of a later world size increase PR.

**Comment by Zughy** [comment]
I see people commenting the code, but I'd like to put the spotlight on the idea behind the code, which I think is more important: why?

To me, Minetest height limit is already highly debatable (who exactly needs 62k blocks on the Y axis?), and at the same time it seems to miss a crucial aspect that, judging by the 40+ likes and 10+ hearts, people would really like to see speaking about worlds: different dimensions https://github.com/minetest/minetest/issues/4428 (there is also a "Supported by core dev" tag)

If Minetest had different dimensions, managing the space inside your world would be far easier, and maybe the reason that brought you to open this PR would be satisfied. I'm saying maybe because your answer to "why is this PR needed" simply was "62000^3 is too small for me". Which... well, it's a bit vague. I'm not against expanding the X or the Z, I just wanted to understand better

**Comment by erisMT** [comment]
> ... and at the same time it seems to miss a crucial aspect that, judging by the 40+ likes and 10+ hearts, people would really like to see speaking about worlds: different dimensions #4428 (there is also a "Supported by core dev" tag)

I think this belongs in #4428.
> If Minetest had different dimensions, managing the space inside your world would be far easier, and maybe the reason that brought you to open this PR would be satisfied.

Yes, this PR still needs Roadmap approval; however, we have yet to see efforts to bring this in Minetest in the way you describe (different attempts are in 4428).
If you are interested/ know how to implement this, simply open a new PR.

**Comment by rubenwardy** [comment]
> If you are interested/ know how to implement this, simply open a new PR.

Generally, we prefer that people discuss before opening big PRs to avoid disappointment after wasted work. Even if the issue is supported, it's worth talking about implementation ideas

**Comment by erisMT** [comment]
> > If you are interested/ know how to implement this, simply open a new PR.
> 
> Generally, we prefer that people discuss before opening big PRs to avoid disappointment after wasted work. Even if the issue is supported, it's worth talking about implementation ideas

Yes definitely, thanks. I saw they are a contributor already, so I assumed they know this.

**Comment by velartrill** [comment]
> i clearly don't like the name. call it pos_t it's more standard like c++ types (uint32_t, size_t, etc). Use a typedef not a macro it's better and more modern.
> 
> Outside of the map size changes, at least a coordinated naming for this coordinates is appreciated :)

type names ending in `_t` are reserved by posix, the suffix is not for use by user types https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

**Comment by v-rob** [comment]
> type names ending in `_t` are reserved by posix, the suffix is not for use by user types https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html

We really don't use POSIX, so its rules really don't apply to us.  In any case, we already use it (e.g. `content_t`).

**Comment by appgurueu** [comment]
> > type names ending in `_t` are reserved by posix, the suffix is not for use by user types https://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html
> 
> We really don't use POSIX, so its rules really don't apply to us. In any case, we already do this (e.g. `content_t`).

Still I don't like the type because it isn't actually a *position* but rather a *coordinate* as I have pointed out on part 2.

**Comment by bztsrc** [comment]
> sqlite - sorry, need to change table.

Why? [SQLite](https://www.sqlite.org/datatype3.html) does not use static typing. The documentation explicitly states: "If the TEXT value is a well-formed integer literal that is too large to fit in a 64-bit signed integer, it is converted to REAL" (read: the conversion is done automatically and transparently).

> We really don't use POSIX, so its rules really don't apply to us.

Yes you do and the rules apply to you when you compile Minetest on a POSIX system like Linux or MacOS. BTW POSIX does not use pos_t, only fpos_t, so this is fine, but maybe a different name would be much much better.

> Start process of breaking 62000 nodes limit

Otherwise I don't get why there's a need for this, the current s16 world size is f*cking huge.

> Change them to doubles or keep v3s32 offset near pos

Furthermore I don't get that double issue either. Floats can store values up 16 million, that's already 256 times more than the current world limit. Surely 16 million x 16 million x 16 million is enough for everyone for any (sane) use cases. I don't think breaking compatibility and *doubling* the required memory for the most basic types is a good idea when it's not absolutely necessary (plus calculations with doubles are a LOT slower than with floats, on ARM and on 32 bit x86 as well. It would definitely ruin the performance on handhelds, that is, if they have enough memory to store the data in the first place).

Just some random thoughts.

Cheers,
bzt

**Comment by TurkeyMcMac** [comment]
I wonder if using fixed-point numbers would be any faster. You might also be able to bring the size in memory down, e.g. 6 bytes instead of 8.

**Comment by v-rob** [comment]
> Yes you do and the rules apply to you when you compile Minetest on a POSIX system like Linux or MacOS.

Then we're already doomed.  A quick search brings up `content_t` (used absolutely everywhere), `override_t`, `biome_t`, `session_t`, and `cache_entry_t`, and there's very probably more.  In any case, naming the type feels very much like bikeshedding; there's more important things to discuss about this PR.  After the heavier discussion topics have been dealt with (such as whether this PR will even be merged), we can bicker about the name of the type.

> Otherwise I don't get why there's a need for this, the current s16 world size is f*cking huge.

And yet, many many people want a bigger world as evidenced by how many times people bring this up on IRC and the forums over and over and over.

---

For the record, I think I fall on the side of the fence that supports this PR.  I don't use even a fraction of the world space myself, but I know that other people go pretty wild in exploration and suchlike.  It's a very widely requested feature, to be sure.  In terms of height, 32-bit height isn't useful at all from a player's perspective, but for different dimensions, you could have 2^16 dimensions and have a world height of 2^16 still.  In theory, you could give every player their own world by dividing the world into (2^16)^3 cube sections and have way more than enough sections for every player that would ever join your server without decreasing each player's section beneath Minetest's current world size.

At the very least, having a type instead of raw `s16` is good from a design perspective, so at the very least, a subset of this PR is useful, even if you debate the 32-bit optional extension.  On those grounds at least, the PR should not be closed.

**Comment by appgurueu** [comment]
> > sqlite - sorry, need to change table.
> 
> Why? [SQLite](https://www.sqlite.org/datatype3.html) does not use static typing. The documentation explicitly states: "If the TEXT value is a well-formed integer literal that is too large to fit in a 64-bit signed integer, it is converted to REAL" (read: the conversion is done automatically and transparently).

Fully agreed, the SQLite "schema" can and should leverage SQLite's dynamic types for decent backwards compatibility.


> > Change them to doubles or keep v3s32 offset near pos
> 
> Furthermore I don't get that double issue either. Floats can store values up 16 million, that's already 256 times more than the current world limit. Surely 16 million x 16 million x 16 million is enough for everyone for any (sane) use cases. I don't think breaking compatibility and _doubling_ the required memory for the most basic types is a good idea when it's not absolutely necessary (plus calculations with doubles are a LOT slower than with floats, on ARM and on 32 bit x86 as well. It would definitely ruin the performance on handhelds, that is, if they have enough memory to store the data in the first place).

We simply need more precision. Float precision issues AFAIK have already been noticeable near world borders with the current limits and are particularly problematic for collisions. The max values of mantissa - exponent floats are bound to be *very* imprecise (think entire blocks of imprecision).

**Comment by appgurueu** [comment]
I have expressed my opinion regarding the structure of these PRs on [IRC](https://irc.minetest.net/minetest-dev/2022-02-25#i_5944157):

```
If I'm not mistaken, the massive code change which is responsible for the large diff and might create lots of merge conflicts mostly is just a type rename which should be rather easy to review
Therefore, I suggest you take out all problematic extension of types to double their widths (the -32 flags) and make that your "part 2"
proller: part 1 would then only be the abstraction of the types, replacing floats, v3fs and aab3f with the ocoord type-based types and s16s, v3s16s etc with the npos types. ocoord would be just an alias for float / f32 and npos one for short / s16.
That can't possibly break anything, should be easy to review (just ensure that AST-wise, the replacements were done only for types and at the proper places), yet should get most future merge conflicts out of the way.
```

**Comment by proller** [comment]
> > sqlite - sorry, need to change table.
> 
> Why? [SQLite](https://www.sqlite.org/datatype3.html) does not use static typing. The documentation explicitly states: "If the TEXT value is a well-formed integer literal that is too large to fit in a 64-bit signed integer, it is converted to REAL" (read: the conversion is done automatically and transparently).

Because now sqlite uses one 64 int column with  some_math(x,y,z) to fit in.
It should be changed in some way to three columns x,y,z with raw values (as in postgres). 
It can be done in next prs.

**Comment by appgurueu** [comment]
> > > sqlite - sorry, need to change table.
> > 
> > 
> > Why? [SQLite](https://www.sqlite.org/datatype3.html) does not use static typing. The documentation explicitly states: "If the TEXT value is a well-formed integer literal that is too large to fit in a 64-bit signed integer, it is converted to REAL" (read: the conversion is done automatically and transparently).
> 
> Because now sqlite uses one 64 int column with some_math(x,y,z) to fit in. It should be changed in some way to three columns x,y,z with raw values (as in postgres). It can be done in next prs.

You can't just break a backend (if a certain flag is enabled) and say that fixing it is up to future PRs.

**Comment by proller** [comment]
> You can't just break a backend (if a certain flag is enabled) and say that fixing it is up to future PRs.

sqlite backend prints error if flag enabled. Its temporary solution, subject for next prs.
if you want use sqlite backend - don't enable this flag.

**Comment by bztsrc** [comment]
> Then we're already doomed. A quick search brings up content_t (used absolutely everywhere), override_t, biome_t, session_t, and cache_entry_t, and there's very probably more.

Neither of these are defined by POSIX, so we're good :-)

> In any case, naming the type feels very much like bikeshedding; there's more important things to discuss about this PR.

You're 100% correct on this one.

> We simply need more precision. Float precision issues AFAIK have already been noticeable near world borders with the current limits and are particularly problematic for collisions.

More precision? The nodes are using discrete integer coordinates, and increasing the world size wouldn't make one node bigger, so the sub-node precision isn't affected and should be fine as is. Note that double needs 8 bytes, that's double of memory footprint and half the network throughput for everything, not to mention the performance penalty on many platforms.

> Because now sqlite uses one 64 int column

What I'm trying to say is, there's no such thing, "sqlite 64 bit int column" in the first place, sqlite does not use static fields. But I agree three columns indexed together would be much better. It would maybe even make it possible to import postgresql dumps into sqlite worlds and vice-versa as a bonus, so it's definitely something worth pursuing.

Cheers,
bzt

**Comment by Zughy** [comment]
I just want to point out again that the only reason the author provided was `62000^3 is too small for me.` and that the issues they wanted to solve are a couple *closed* issues, where actually the latter is a duplicate of the former (former which has a `won't add` label).  

I asked for a better explanation a few comments ago (https://github.com/minetest/minetest/pull/11843#issuecomment-1007015024), being completely ignored, yet they continue to push. I'd also like to underline how this and the other related PR have had a `Roadmap: needs approval` label for months (meaning they should have been closed a long time ago), but it doesn't seem to be that relevant according to the comments, only focused on the technical aspects; actually, you're gonna discuss these PRs in the next meeting.  

Let me get this straight: you are willing to spend your time on a couple PRs that require a lot of thinking, discussed before with basically always "no" as an answer, made by someone who provided no concrete reason and who only answers to technical questions, that may or may be not solved by other pointed out *open supported by core dev* issues (#4428), *whilst* having 120+ PRs open. This is:
1. masochism
2. really poor management of your time
3. disrespectful to other contributors 

I'm not saying this shouldn't be done at all (even if I find it quite useless, especially on the Y axis), but of all things Minetest need, an even broader map is not even in the top 10. And that's not me saying it, that's the roadmap issue (https://github.com/minetest/minetest/issues/10461), where no one said one thing about it. And if ever, reasons, usecases should be provided: here there is none. Please just close this thing

**Comment by appgurueu** [comment]
Agreed with @Zughy's points, but I feel one major point is missing: This PR risks massive breakage in multiple places and suggests entirely breaking client - server compat for newer servers using this feature.

**Comment by rubenwardy** [comment]
> This PR risks massive breakage in multiple places and suggests entirely breaking client - server compat for newer servers using this feature.

To state my opinion: I've very much against breaking client-server compatibility at this time, hard network breakages split communities.

**Comment by MisterE123** [comment]
Have to disagree with zughy here. The world being too small is an entirely valid reason in my opinion. 

Yes, the world is tall enough at 32000 above sea level. That allows for many realms. 
But what about the horizontal size? There are now lua and C++ mapgens that produce large-scale terrain. When you have continents that get cut off at the edge of the map because the world boundaries are too constrictive, its not nice. Also, when you go exploring, you can reasonably easily reach the edge of the map under normal conditions. That is a problem that this PR aims to solve. If this cannot go into minetest at this time due to breakage then I hope it is very seriously considered for the next major release when compatibility will be broken anyways.

**Comment by tigercoding56** [comment]
> > I guess the server could pretend to teleport an old client approaching (30000,0,0) to (0,0,0) and keep sending mapblocks, with fake coordinates offset by (-30000,0,0) … ?
> 
> Would mess the basic debug HUD and all CSM using `minetest.localplayer:get_pos()`... Would be better to just disallow old clients who try to connect a new server.

i think maybe this  could be an option enabled in the server settings  so the user can decide

**Comment by appgurueu** [comment]
> > > I guess the server could pretend to teleport an old client approaching (30000,0,0) to (0,0,0) and keep sending mapblocks, with fake coordinates offset by (-30000,0,0) … ?
> > 
> > 
> > Would mess the basic debug HUD and all CSM using `minetest.localplayer:get_pos()`... Would be better to just disallow old clients who try to connect a new server.
> 
> i think maybe this could be an option enabled in the server settings so the user can decide

There already is an option to reject clients attempting to connect with older (but still supported) protocol version (`strict_protocol_version_checking`).

**Comment by tigercoding56** [comment]
ups i did not know that althought then if its disabled the server could use that teleport to 0 0 hackish thing they deskriped or just make old clients only stay withhin the old world borders
------- Original Message -------

**Comment by sfan5** [comment]
Closed per coredev meeting today.
Whether increasing the world limit is worth doing/spending time on is unclear, individual improvements of this PR (such as replacing types) could be considered. There is agreement that a hard network incompatibility is not an option.

**Comment by tigercoding56** [comment]
> Closed per coredev meeting today. Whether increasing the world limit is worth doing/spending time on is unclear, individual improvements of this PR (such as replacing types) could be considered. There is agreement that a hard network incompatibility is not an option.
i seriously hope this is considered for minetest 6.0 (aka the next compatibility breaking change ) because   if this is not i imagine there being a conversation like this on the minetest forums someday "could we get a bigger world size " "at one point there was a PR to add a bigger world size  but  it would require too much work to port it to the latest version"   "how about we just increase the world size from scratch " "aren you joking minetest has 50 million lines of code that would break with that change "

**Comment by Pevernow** [comment]
Games are not developed for compatibility

The purpose of the game is mainly for players

But core developers don't necessarily know what players need

In many cases, compatibility is not the most important

I think we should launch relevant votes on the forum to ask players' opinions on innovative pull request

It's not just up to the core developers to make decisions.

Compared with minetest, minecraft has a more free development environment.

At least its community developers can modify the core of minecraft through mod (such as podium), rather than requesting mojang to accept their amendments.

If we can't merge this pull request now because you want to ensure stability, at least in minetest6 Actively discuss this issue in the development of Minetest6.0.

In fact, some community developers of minetest lost confidence because their correct PR was refused to merge.

**Comment by Pevernow** [comment]
Games are not developed for compatibility

The purpose of the game is mainly for players

But core developers don't necessarily know what players need

In many cases, compatibility is not the most important

I think we should launch relevant votes on the forum to ask players' opinions on innovative pull request

It's not just up to the core developers to make decisions.

Compared with minetest, minecraft has a more free development environment.

At least its community developers can modify the core of minecraft through mod (such as podium), rather than requesting mojang to accept their amendments.

If we can't merge this pull request now because you want to ensure stability, at least in minetest6 Actively discuss this issue in the development of Minetest6.0.

In fact, some community developers of minetest lost confidence because their correct PR was refused to merge.

**Comment by Pevernow** [comment]
Games are not developed for compatibility

The purpose of the game is mainly for players

But core developers don't necessarily know what players need

In many cases, compatibility is not the most important

I think we should launch relevant votes on the forum to ask players' opinions on innovative pull request

It's not just up to the core developers to make decisions.

Compared with minetest, minecraft has a more free development environment.

At least its community developers can modify the core of minecraft through mod (such as podium), rather than requesting mojang to accept their amendments.

If we can't merge this pull request now because you want to ensure stability, at least in minetest6 Actively discuss this issue in the development of Minetest6.0.

In fact, some community developers of minetest lost confidence because their correct PR was refused to merge.

**Comment by rollerozxa** [comment]
> Games are not developed for compatibility

And Minetest is a game engine. 

> In many cases, compatibility is not the most important

Yes, yes it is in this instance. Increasing the world limit in this way would mean yet another incompatible protocol version, potentially fragmenting the server landscape even more.

> Compared with minetest, minecraft has a more free development environment.

Minecraft modders effectively fork the game and mod it into something that is in many ways incompatible with the vanilla game. You cannot reasonably compare it to Minetest engine development.

**Comment by appgurueu** [comment]
> > Wrong. C++ can even be interpreted, and tampering with binaries is a possibility as well. It's just that this is horribly inconvenient (as is MC modding) and there's no point in doing it as the sources can be modified directly; just make a fork!
> Obviously, minetest has no shorter history than minecraft, but its share in the global market is very different. Why?

Wrong again. Minecraft was first by years, especially when it comes to having *a playable game*.

> Even if you say that minecraft's development environment is no longer friendly, why does minecraft have so many mature mod, unofficial versions, and various frameworks? If minetest's development environment is really more friendly than minecraft, why are minecraft's community developers unwilling to give up developing mod for a low-performance minecraft instead of working for the so-called "minetest with excellent environment"?

I dare to claim that this 99% boils down to popularity (and the possibility to earn money that comes with it). Minetest being FLOSS doesn't help in attracting modders who want to make money - it's way easier to monetize proprietary software.

> As I said earlier, backward compatibility is necessary But to a limited extent The 5.x version of the code only needs to be compatible with 5 x We cannot always consider ancient versions of code (such as 0.4 or 0.3), It's just a waste of our time

Yes, that's what semver means.

**Comment by servantoftestator** [comment]
Due to the inconsistent series of statements by the core maintainers in #12142 and this PR I believe this series of PR's, and any similiar PR's in the future, should either be locked or #8660 should have the "Won't Add" tag removed and the issue re-opened for future discussion and future implementation.

> We've decided not to do it at this time as we want to prioritise other things
> There is agreement that a hard network incompatibility is not an option.

Hard network incompatibility is unavoidable by the nature of these PR's and the issue referenced. Old clients will never be able to go beyond the old world limit on new servers. New clients on old servers will never be able to go beyond the old world limit. I based my statement in #12142 on #8660 having the "Won't Add" tag, therefore it is a true statement at that time.

**Comment by tigercoding56** [comment]
> Due to the inconsistent series of statements by the core maintainers in #12142 and this PR I believe this series of PR's, and any similiar PR's in the future, should either be locked or #8660 should have the "Won't Add" tag removed and the issue re-opened for future discussion and future implementation.
> 
> > We've decided not to do it at this time as we want to prioritise other things
> > There is agreement that a hard network incompatibility is not an option.
> 
> Hard network incompatibility is unavoidable by the nature of these PR's and the issue referenced. Old clients will never be able to go beyond the old world limit on new servers. New clients on old servers will never be able to go beyond the old world limit. I based my statement in #12142 on #8660 having the "Won't Add" tag, therefore it is a true statement at that time.

(joke) they are just scared of upsetting  the 3 people that will actually complain ,   have mercy for them and do not complain about the world size so much    ;P (/joke)   also i would mention the breaking updates minetest already has had as source that network incompatibility is unavoidable  1.** - 2.** - 3.** - 4.** - 5.**   (and hopefully 6.** will have a larger world size so i cannot reach it with my digtron in like 1 hrs

**Comment by servantoftestator** [comment]
Please be professional and discuss the PR or review/lock it. The unrelated joking and discussion just seems like spam. Even if three people will be upset by this change, it is something to consider their thoughts on the matter about what would upset them.

**Comment by tigercoding56** [comment]
> There were no 1 - 4. Everything before 5.x was 0.y.x.
aah i did not know that thx  i just assumed that the first number was incremented every breaking change

**Comment by tigercoding56** [comment]
> Please be professional and discuss the PR or review/lock it. The unrelated joking and discussion just seems like spam. Even if three people will be upset by this change, it is something to consider their thoughts on the matter about what would upset them.

sorry for joking i did not realize that   
as for considering the thoughts of other people ... maybe someone should make a poll and then ask the 3 people that would get upset why and fix the thing that upsets them (for example like having an setting to change how many bits are used to adress the world size so they do not feel their storage space is being wasted by the larger maps )

**Comment by MisterE123** [comment]
no, this just has to wait until a major version upgrade. people want this,
the devs are cool with it, its just badly timed, and there are more
important things to do. In the future, I think it will be merged, assuming
@proller is willing toepick it back up then.

**Comment by BasToTheMax** [comment]
Hi. Any updates?

**Comment by proller** [comment]
Yes, but use this branch - https://github.com/minetest/minetest/pull/12142

**Comment by DragonWrangler1** [comment]
It baffles me that prs are immediately closed (like #12142 ) Perhaps instead of closing it you should have reviewed it and tried to get it merged. By closing #12142 You just risked something like this never getting done. The excuse of waiting for a major release isn't a good one, because that line of thought puts a very high risk of this never being added. @proller has been very generous giving time to try to get this thing added and none of the developers seem to want it (A figure of speech. Due to the fact that everyone wants to wait til 6.0.0) What happens if 6.0.0 comes by and this isn't ready ? Wait til 7.0.0 and risk the same thing happening ? My advise is get this to where it works, has minimal bugs, and has backwards compat, then merge it. Remember: There may come a day when proller doesn't want to do this anymore, and apparently noone else wants to do this since it's "non-trivial" Proller offered a chance for adding something that hundreds of people want. Now. I'm curious to hear the opinion of Core Devs on this.

**Comment by mk-pmb** [comment]
Sorry for being late to this part of the party.

> Old clients will never be able to go beyond the old world limit on new servers.

They could, if the server does the necessary offset calculations. That way the client could be kept in a kind of "dream" where it thinks it is close to the world origin. Which would probably even help with the accuracy of client-side predictions, like how far a cart overshoots the track before it learns that the track has made a bend.

Having the server do the offset math would probably also keep the client's RAM requirements low (because it can use smaller number types), allowing to play reasonably well on weak devices. Which is one of the huge advantages over Minecraft. (Albeit I heard modern Minecraft has improved a lot in system requirements.)

For servers where the admins can't afford the extra CPU load for offset calculations, maybe we could offer a client-side proxy that shifts the burden.

**Comment by proller** [comment]
>That way the client could be kept in a kind of "dream" where it thinks it is close to the world origin
Its possible, server choose offset point on login, client cant exit 62km area around this point, should relogin near border to continue moving.
Long teleports outside this area will be broken, or we can save pos and kick player for forced relogin on border pass
Not hard to make this code, but some bugs will appear many months
But much easier to force players to update their clients

>  would probably also keep the client's RAM requirements low (because it can use smaller number types
No, ram usage difference should be less 1%
Cpu offset calculation is near zero comparing to other code

**Comment by mk-pmb** [comment]
> client cant exit 62km area around this point,

Why not? If a player strays too far from their offset origin, the server can just adjust the offset and teleport the player to 0,0,0. The server might even announce the intent to teleport beforehand, and provide some of the region data ahead of time. That way the player ideally won't even know they were teleported.
Similarly, to the client, long teleports will appear as being teleported to 0,0,0.
To keep the coordinate display in sync, the server could announce the new offset just for navigation purposes, if server admins even want their players to have reliable position information.

**Comment by proller** [comment]
Because player caches many things in current coordinate system, you should send "clear anything (map, objects,....)" to client
And simplest way to do it - kick/relogin

**Pull request closed without merging**
