### PR TITLE
Add settings for colors

### PR DESCRIPTION
**Pull request by Gael-de-Sailly**
[A topic on the forum](https://forum.minetest.net/viewtopic.php?f=5&t=12171)

We can set the 4 colors of the world config dialog, by minetest.conf (`color_1`, `color2`, `color_3`, `color_4`)

### CODE REVIEW

**Comment by C1ffisme** [comment]
Good idea, expecially for those with cases of color-blindness.

**Comment by est31** [comment]
I'm against making everything a setting. This just makes things more complicated. Its better to have good defaults that always work. What would be your proposed colors?

**Comment by Gael-de-Sailly** [comment]
Try it. The default colors are not changed if you don't put these fields on minetest.conf.

**Comment by Calinou** [comment]
:-1:

Instead, fix the default colors which are too saturated and hard to read.

**Comment by Gael-de-Sailly** [comment]
?

Why "Instead" ?
What's the problem ? I think you have not exactely understood what I'm saying. I know that I badly explain things in English.
The user is not forced to go into minetest.conf. Nothing will change, only the possibility to change it, only if you want.

But we can change defaults too if you want :)

**Comment by HybridDog** [comment]
l would like to have these settings.
ls it possible to change the green formspec text fields backgrounds colour?

**Comment by SmallJoker** [comment]
Please give the color variables better names, as example, change `mt_color_green` to `mt_color_item_selected` (or wherever it is used)

**Comment by est31** [comment]
I'm ok with adding extra settings now for colors, as the gnome guidelines [https://developer.gnome.org/hig-book/unstable/design-color.html.en](especially) [https://developer.gnome.org/accessibility-devel-guide/stable/idp4901104.html.en](recommend) making colors a settable option. They should however have more descriptive names, as @SmallJoker suggested.

**Comment by paramat** [comment]
See #2424 
Does this need re-thinking now we have coloured text merged?

**Comment by beyondlimits** [comment]
Something like this:
```
mt_color_default = "#FFFFFF"
mt_color_mod = "#FFFFFF"
mt_color_mod_default = "#0000FF"
mt_color_mod_enabled = "#00FF00"
mt_color_modpack = "#C0C0C0"
mt_color_modpack_enabled = "#008000"
mt_warning = "#FF0000"
```

**Comment by paramat** [comment]
No response from author for 2 years, long overdue close.

**Pull request closed without merging**
