### PR TITLE
Disable SDL2 for 5.9.0

### PR DESCRIPTION
**Pull request by rubenwardy**
See #14545 and https://forum.minetest.net/viewtopic.php?t=30864

### CODE REVIEW

**Comment by sfan5** [comment]
should be commented out from buildbot and `util/ci/common.sh` too

Given recent discussions in #minetst-dev I'm not really sure if we're actually going to disable SDL for release however.

**Comment by celeron55** [comment]
Should we agree on what the primary goal is now? I propose the primary goal is to get the release out ASAP, and my opinion is that this PR is the way to do that.

**Comment by rubenwardy** [comment]
> should be commented out from buildbot and util/ci/common.sh too

The CI passes as-is, I don't think we need to change these scripts just to revert it in a few days time

**Comment by sfence** [comment]
Some notebooks are missing numeric keyboards. So if shift+key stops working, users can be really confused.
I think we have to disable SDL2 for this release or fix this problem before release.

**Comment by v-rob** [comment]
I vote in favor of disabling SDL for this release, and then moving to scancodes for the next release.  That seems like the best way to prevent as much breakage as possible.

**Review by sfan5 — APPROVED** [review]
well then

tested win64 build, works fine.

**Comment by farribeiro** [comment]
Merge?

**Comment by sfan5** [comment]
> The CI passes as-is, I don't think we need to change these scripts just to revert it in a few days time

This causes the windows builds to ship with an useless `SDL2.dll`, btw.

**Comment by lhofhansl** [comment]
Note that SDL also breaks FSAA. +1 on disabling SDL for 5.9.0

**Comment by rubenwardy** [comment]
> This causes the windows builds to ship with an useless SDL2.dll, btw.

@sfan5 okay, updated those two scripts

**Pull request merged**
