### PR TITLE
Optimize PcgRandom::bytes()

### PR DESCRIPTION
**Pull request by ShadowNinja**
bytes() now copies in 32-bit chunks unstead of 8-bit chunks.  The result takes about half the time (tested in 1024 blocks of 65536; time went from 342ms to 169ms).
The value of the array now depends on the platform's byte ordering, which breaks the tests on non-little-endian architectures.  I just made the tests bail in this case because I'm too lazy to do conversions right now.

### CODE REVIEW

**Comment by est31** [comment]
Just before the PR gets merged the PcgRandom should be cross-platform and deterministic again.

**Comment by ShadowNinja** [comment]
@est31: That's not possible with this method, but I can see how it could be inportant for, eg, mapgen, so this might be unmergable.

**Comment by est31** [comment]
You can put an #ifdef that checks for endianness, with the old method as fallback

**Comment by paramat** [comment]
@kwolekr

**Comment by paramat** [comment]
Discussion http://irc.minetest.ru/minetest-dev/2016-02-27#i_4546257

**Comment by kwolekr** [comment]
:-1:

This is close to the original implementation of the function, before I realized it was broken for different endian architectures.  It's not even worth optimizing this function.  Isn't there somewhere else in minetest that actually needs work?

**Pull request closed without merging**
