### PR TITLE
document inventory sending behaviour

### PR DESCRIPTION
**Pull request by zeuner**
The current behaviour for player inventories in formspecs is surprising without more precise documentation.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Inventory lists with size 0 can also be sent to the client, but nothing will be shown at all.

**Comment by zeuner** [comment]
@SmallJoker: Considering that a larger inventory list is shown by
showing the slots without any border, what else would be expected for
showing an empty inventory list?

original message follows:

**Comment by rubenwardy** [comment]
It's worth documenting what would happen if the `list[]` element has a size which exceeds the inventory. I'm personally not sure

**Comment by zeuner** [comment]
@SmallJoker: looks good to me.

original message follows:

**Pull request merged**
