### PR TITLE
Fix stretched stars, render stars before sun and moon

### PR DESCRIPTION
**Pull request by random-geek**
This is a simple bugfix. I also moved the star-drawing code to before the sun and moon drawing code, so stars would not appear in front of the moon. 

**Before:**
unknown

**After:**
unknown2

P.S. This is my first engine pull, so I apologize in advance if this is invalid or unworkable.

### CODE REVIEW

**Comment by paramat** [comment]
Because the code has been moved the diff doesn't show what lines have been changed, please could you point out the changes?

**Comment by paramat** [comment]
Thanks.

**Comment by GreenXenith** [comment]
Does this conflict with https://github.com/minetest/minetest/pull/7691?

**Comment by stujones11** [comment]
screen
LGTM :+1:

**Comment by paramat** [comment]
screenshot_20180927_213648

^ PR

Tested to confirm stars are drawn behind the moon.

**Comment by sfan5** [comment]
ce2d33eb97238e2e050d065a8f0838749a0b31d0

**Comment by lhofhansl** [comment]
Actually this causes an issue with texture packs that set the sun texture.
See the following example with hdx-128:
screenshot_20181114_223100

Same without this PR:
screenshot_20181114_223210

The sun is actually *behind* me (so this is not the actual sun texture).
(Or perhaps I do not understand how overriding the sun texture work).

In any case, this does cause that weird rendering glitch with the HDX textures.

@random-geek @sfan5 @paramat

**Comment by paramat** [comment]
@Jordach mentioned something like this in #7853 first post "Ninja Edit: This also fixes sun.png and moon.png being wrongly applied to the sunrise/set glow faces."

**Pull request closed without merging**
