### PR TITLE
Artificial bank

### PR DESCRIPTION
**Pull request by juhdanad**
**WARNING: if you open your world with this version, it gets converted and you won't be able to open it with other versions anymore!**

The goal is this PR to change the light banks' meaning to sunlight + artificial light.

The request is still WIP, because the conversion sometimes causes dark blocks, and I don't know yet why.

What will change:
- the map format increases
- old server - new server: when first loaded, the world is automatically converted to the new format, erasing the old light information. This might slow down the map loading, but once the conversion is done, no more processing is required.
- old client - new server: the blocks get converted back when they are sent to the clients. Old clients should see no change in the lighting. Currently all `param1` values are converted, even if they contain no light information. I hope this won't cause any side effects.
- new client - old server: the client has to guess the amount of sunlight. The current implementation works well with artificial sources if they are either in direct sunlight or in darkness. But there is an ugly jump in brightness if the artificial light and sunlight meet each other, while the artificial source is in darkness. Again, currently all `param1` values are converted, even if they contain no light information. I hope this won't cause any side effects.
light_edge
- `sunlight_source` for nodes was introduced to make light calculations uniform. This property is not exposed to Lua yet.
- graphics: now artificial light sources are brighter if they are in sunlight. Since the light sources produce maximal brightness without sunlight, in sunlight their brightness is clamped.
light_clamp

I hope I did not forget anything. Please let me know what you think, how should this pull change!

### CODE REVIEW

**Comment by rubenwardy** [comment]
What's the advantages of this?

**Comment by Ferk** [comment]
Would this would allow sunset/sunrise color tint without affecting artificial light? (see #3299)
With an API like #5680 using this it might be useful for plants that can only grow on specific light or for solar panels.

But it's also true this has a lot of potential to break things...

**Comment by Ekdohibs** [comment]
@rubenwardy the possible advantages I see:
- allowing to change sunlight color
- faster light spreading (adding a light source only needs to recompute one light bank)
- possibly allows to make artificial light with light value 15 again (need to check)
- nodes that create sunlight below them as well (can be useful to prevent shadows)

All in all I think although this is an important change, it would be useful and I really would like it to be merged.

**Comment by paramat** [comment]
> old client - new server: the blocks get converted back when they are sent to the clients

> new client - old server: the client has to guess the amount of sunlight. [...] Again, currently all param1 values are converted,

Seems a significant amount of processing in both cases, so this would be best as a major breakage, for example for MT0.5. Also because it is such a major change a dev cycle is needed to consider and work on it.

> now artificial light sources are brighter if they are in sunlight.

Is the daylight light level added directly to artificial light level? This may look weird having a large area saturated at 15. That 2nd screenshot looks bad to me, how does that look with current code? I assume the screenshot is taken at dawn or dusk?

**Comment by juhdanad** [comment]
@rubenwardy I think @Ekdohibs listed all advantages.

@paramat the new->old conversion is relatively fast, one `max()` operation per node. And servers don't have to do old->new conversion when sending blocks.

Yes, the sunlight and artificial lights are added. The screenshot was taken at dawn, you can see the time at the top of the screenshot. I chose to add light because it is easy to colorize the sunlight that way. And the light source is brighter (clamped at 15) as well as its surroundings if there is sunlight. I have concentrated mainly on the light conversion, and not the graphics yet.

**Comment by paramat** [comment]
> I chose to add light because it is easy to colorize the sunlight that way

Colourising sunlight is very low priority, it would not be worth making things look wrong just for that (if things do indeed look wrong). I guess you mean making the world slightly red at dawn and dusk?
A direct adding of natural light to artificial light will be a large change in appearence, i will test to see the effect, my feeling is that it will look wrong if the combination of natural and artificial light is not a subtle increase.
The advantages listed sound good, but if things look bad it would not be justified.

**Comment by paramat** [comment]
>  the new->old conversion is relatively fast, one max() operation per node.

But for every node, 4096 per block.
> servers don't have to do old->new conversion when sending blocks.

In 3 situations there is conversion:
> old server - new server: when first loaded, the world is automatically converted to the new format,

> old client - new server: the blocks get converted back when they are sent to the clients.

> new client - old server: Again, currently all param1 values are converted

These 3 will be the majority of MT usage for a long time. Worlds develop over years and will therefore take years to convert all areas to the new format. Every node needs conversion so this will be a significant amount of processing.

This is likely to be controversial because it would be the biggest change to MT for 5 years, and involves a long period (years) of significant processing to update and maintain compatibility. So there needs to be very good reasons to do this, and while the advantages are nice they are possibly not enough to justify. It doesn't seem worth it to me.

**Comment by paramat** [comment]
light_clamp

^ PR

screenshot_20170503_054000

screenshot_20170503_054052

^ Current (also smooth lighting off)

Although you are still working on the graphics, i thought i would do a comparison.
Currently, light sources in daylight have a smoothly fading and subtle patch of light that looks good. The saturated bright area in the first screenshot is very ugly.

**Comment by numberZero** [comment]
> it may seem that adding natural to artificial light makes sense.

By itself, it doesn’t. Sunlight and artificial light have different scale. So, unless you are ready to introduce HDR, `max` seems to be better for now.

**Comment by numberZero** [comment]
> Currently all param1 values are converted, even if they contain no light information. I hope this won't cause any side effects.

#5717

**Comment by paramat** [comment]
:-1: due to https://github.com/minetest/minetest/pull/5687#issuecomment-298820192

**Comment by numberZero** [comment]
@paramat you ask for compatibility with in-dev versions, be them `master` or `0.4.14` or whatever.

> and will therefore take years to convert all areas to the new format.

It is possible to make MT convert the whole map at once.

> many people use old clients and servers.

That’s a problem. Would these versions be “LTS” or “stable” at least, we would have to support them all for a long time.  But these are *development* versions, so we are able to urge people to upgrade.

> But for every node, 4096 per block.

Compressing is done for every node too. It requires more server resources, really. And on the client side, everything pales beside the mesh generation.

**Comment by celeron55** [comment]
I think the current lighting better simulates the fact that in reality the sun is way brigher than any artificial lights, and separately they only look the same due to different exposures in a camera or the eye when you're in artificial light as compared to sunlight. When there's both, sunlight completely swamps most artificial light.

Really, and what is done in modern rendering, artificial lights *are* dimmer than sunlight, and then if you're inside, overall brightness is scaled up.

I wonder if there's any practical way of making this happen in Minetest? This gets to the graphics programming territory that I barely understand, and everybody else even less...

**Comment by Ekdohibs** [comment]
Well our *current* lighting can be simulated by this PR by just taking the max of artificial and natural light. How it is to be rendered after that, now that artificial and natural light can be separated, is a different issue -- we can just render it as is done now, make the artificial to be added to sunlight, or even take artificial light into account only if there is no sunlight. Using an artificial light bank strictly increases the information content of param1, and the information we already have is trivial to reconstruct.

**Comment by paramat** [comment]
To be fair i believe the author intends to work on the combination of sunlight and artificial light, as currently it obviously looks wrong.

**Comment by paramat** [comment]
> Really, and what is done in modern rendering, artificial lights are dimmer than sunlight, and then if you're inside, overall brightness is scaled up.

I wonder if there's any practical way of making this happen in Minetest?

Seems done already, artficial light goes to 14 for only a very few light sources (mese lamps which are considered bright enough to be grow lamps), sunlight goes to 15.
Because we have a new much brighter light curve we were able to reduce light level for fire, lava and torches, making the max of 14 reserved for 'grow lamp' type brightness.

**Comment by Ferk** [comment]
> I think the current lighting better simulates the fact that in reality the sun is way brigher than any artificial lights

Wouldn't this change make it even easier to simulate that? I'd guess there would be more control on just how much different both types of lighting are, and on how they would be combined. A 15 of artificial light could contribute less to the lighting than a 15 in natural light.

**Comment by celeron55** [comment]
Hmm... true, it should be possible to do that already. Well, do it then!

The problem in the first screenshot will be much less, or inexistent, depending on what the exact rendering style ends up being.

I do support the separation of sunlight and artificial light in memory and in the map format on disk.

**Comment by HybridDog** [comment]
The map data is compressed, so saving sun- and artificial light separately hardly increases disk usage l guess. You could then also increase the precision to 8 Bit light.

**Comment by Ferk** [comment]
@HybridDog the light is already separated and stored in 2 banks: daylight and nightlight
The intent of the PR is to change them to: natural-light and artificial-light

If anything, this probably will reduce disk usage, since underground lighting will only need to write to the artificial light bank, and natural light will be mostly zeroes, instead of having to write the same value for day and night for underground torches.

**Comment by paramat** [comment]
> Wouldn't this change make it even easier to simulate that?

As i explained there's no need to, as we have a new much brighter light curve which allowed us to reduce the light levels of torch, fire and lava, and allowed us to have super-bright 'grow lamps' that are artificial but also almost as bright as sunlight.

> A 15 of artificial light could contribute less to the lighting than a 15 in natural light,

The ability to have artificial light very nearly as bright as sunlight is needed and shouldn't be removed.
If artificial light is made significantly dimmer then players will find it too dim while finding sunlight too bright. Players have been complaining about the dimmness of artificial light for years so they won't tolerate it being any dimmer.

**Comment by paramat** [comment]
Added label due to the known bug and the work needed on visual light level when combining the banks.

**Comment by paramat** [comment]
Note that those torch-and-grass screenshots are taken at early morning, not with maximum sunlight, so artificial light is indeed currently swamped by sunlight, it makes an almost unnoticeable difference.

**Comment by Ferk** [comment]
@paramat note that currently the highest light level artificial light can produce is 14. Wasn't 14 slightly less bright than 15 in the last update of the light curve? (not by that much, though)

One interesting advantage of having artificial light separated is that light torches could extend their light 1 node further, since the value 15 won't be veto-ed.

**Comment by paramat** [comment]
Yes in the latest light curve 14 is very close to 15 due to gradient being zero at maximum.

**Comment by numberZero** [comment]
@paramat 14 is the same as 15:

`light.cpp:26`
```c++
// Length of LIGHT_MAX+1 means LIGHT_MAX is the last value.
// LIGHT_SUN is read as LIGHT_MAX from here.

u8 light_LUT[LIGHT_MAX+1];
```
where `LIGHT_MAX` is 14 and `LIGHT_SUN` is 15.
The difference you may see may go from color tuning that is used to make artificial light yellowish.

**Comment by numberZero** [comment]
Does this have any chance of being included in 0.5.0?

**Comment by paramat** [comment]
My previous objections about old clients are irrelevant if this is done for 0.5.0, so i have removed my -1, but on the understadning that the PR currently prouces bad looking results, however the author has stated there is still work to be done on the resulting light.
C55 has stated support for the basic idea but the implementation needs work.
If this is done then 0.5.0 is obviously the time to do it to remove the 'old client' issues. So please do work on it and improve it so it can be properly tested.

**Comment by paramat** [comment]
@juhdanad the obstacles to getting this merged will be much higher after 0.5.0 release due to old client/server issues, so now is the time to work on this and consider it.

**Comment by juhdanad** [comment]
Unfortunately there is a bug which I couldn't find yet: some map block become completely dark during the conversion. I have to find the cause before this can be merged.

**Comment by numberZero** [comment]
@juhdanad I have yet another suggestion:
Add supplementary per-mapblock lighting map, with 2 values for each column: 1. whether the sunlight can pass this column of the mapblock, and 2. whether there is sunlight (full) in this column at the bottom (not the top; that’s important if there are any sunlight-emitting lamps, which are necessary to prevent shadows from the floatlands) of the mapblock. (And probably one per-mapblock value: whether it needs lighting update.) Such maps should be stored separately from mapblocks, grouped in reasonably large (vertical) packs. That should help update lighting in deep mines properly when something happens on the ground, for example. But that may be helpful in other cases as well.

**Comment by HybridDog** [comment]
You could also make a blockmap, where for each mapblock information is stored which needs to be accessed when accessing information about neighbouring mapblocks.
For example there are many air-only chunks (sky) and completely sunlight-free chunks (underground), so you could use 2 bit per mapblock to save if the block is fully sunlighted (_0_), completely dark with param1=0 everywhere (_1_), without sunlight but artificial light (_2_) or something else (_3_).

**Comment by juhdanad** [comment]
@numberZero @HybridDog I'm afraid these ideas are about speeding up calculations, which should have their own PRs. What this PR needs is a bugfix.

I understand the vertical stack idea and find it useful, but to be honest, I intentionally did not fix direct sunlight spreading, because floatlands would generate huge shadows. First direct sunlight-emitting nodes should be added to the game (and ideally to the map generator).

@HybridDog's idea is about compression, if I understood it well. It is doable, but not in this PR. About the Hilbert-curve storage: the last accessed map block is cached, so if the same map block is required twice, it is returned from the cache. This already saves a lot of map block queries.

**Comment by paramat** [comment]
Perhaps close until a fix for the issue is found?

**Comment by juhdanad** [comment]
This will require an almost complete rewriting, so I'm closing this for now.

**Pull request closed without merging**
