### PR TITLE
Change DevTest textures of basenodes

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR is just for fun and not important. It might be controversial.

It will change all the textures of the `basenodes` in DevTest, i.e. the textures for the mapgen, like stone, sand, dirt, water, cobblestone, etc.

It will be a much simplified style with a minimal palette and high saturation and contrast. Like before, each basenode looks different and they can be easily told apart. Finally, there is a outline on every `basenodes` texture. This will form a grid pattern in large stretches of land.

## Screenshots

Fancy leaves mode:
https://satoshiupload.com/images/G646ZATKM1.png
https://satoshiupload.com/images/9INkhRF0un.png

Opaque leaves mode:
https://satoshiupload.com/images/BNMNcA51hQ.png

## Why?

Because the current textures look so sad, but the new textures look happy. I know, this is literally just the test game but I honestly think that even testing the engine should be fun. :D Of course this is very subjective.

But with the texture outlines, there's also a functional improvement in that the grid pattern makes it easier to count distances in your head.

If you think this PR is unjustified for any reason, feel free to reject it, no hard feelings. I know this PR is probably controversial.

### CODE REVIEW

**Comment by Thomas--S** [comment]
Wouldn't it be probably useful to update license information accordingly?

**Comment by Wuzzy2** [comment]
No. `LICENSE.txt` in DevTest:

> The same license as for Minetest applies.

This is still true. These textures are my own creation, and I will use the same license as before. So, nothing changes.

**Comment by SmallJoker** [comment]
These old 0.3.x (?) textures fit as well, and partially match to what's used in MInetest Game (style-wise). Don't get me wrong - the game looks "happier" due to the high saturation, but I really don't see any need to change textures of a testing game. People might just their own texture pack anyway.

**Comment by voxel-minetest** [comment]
lol they look cute. 
But I like the default ones of dev test. ;)

**Pull request closed without merging**
