### PR TITLE
Implement a autohiding button bar for settings buttons used every now an...

### PR DESCRIPTION
**Pull request by sapier**
...d then

The updated implementation can be used way more generic then the initial version

Sorry thought I could reopen the old pull once I'm completed. Sadly github prevents it.

http://imgur.com/zfSqJji,NUxEBYx

Better Icons are welcome!

Old Pull:
https://github.com/minetest/minetest/pull/2121

### CODE REVIEW

**Comment by ShadowNinja** [comment]
For the expand icon, use `Action Bar Icons/holo_dark/01_core_overflow/drawable-xxhdpi/ic_action_owerflow.png` from the pack I linked in the previous pull.

**Comment by sapier** [comment]
rebased to recent master

**Comment by MoNTE48** [comment]
Flight button can replace a double jump. Fast moving very laggy on my Galaxy Note 5. I empathize the owners of MTK-phone.

**Comment by sapier** [comment]
what s a "mtk-phone"?

**Comment by MoNTE48** [comment]
Cheap Chinese phone on the MTK. For example, Lenovo with a price of $ 60-120 (DualCore, 512-1G RAM)

**Comment by sapier** [comment]
512MB ram is absolute minimal requirement you'll have issues for various mods.
https://forum.minetest.net/viewtopic.php?f=42&t=9389&hilit=sapier+android contains a table with known good/bad devices. You're welcome to provide additional results for other phones I'm gonna add it once I find a way to reset my forum password ;-)

**Comment by MoNTE48** [comment]
1) Minetest use of resources as much as Asphalt 8. With one remark - Asphalt 8 can operate at maximum graphics on flagship ustroytsvo: Nexus 9, LG G4, Note 5, Galaxy S6 Edge, etc. Minetest preemlimo works, but not perfect on these ustrostvah. And this - the most powerful Android device with 2-4 GB RAM and Antutu score 50'000 +.
2) You know what I do for money. But because of this I can get a good test this game. Products with less than 1GB RAM and a 4 core CPU is very slow work. ARM6 and MIPS devices have 1-2 cores CPU and 256-512 RAM. You can not expect more than 3 FPS frames per second. It is not worth supporting! Support should be provided only ARMv7a, ARM64 (ARMv8) and x86 CPUs.

3) Have you tried minimap on Android? I tried. My FPS fell from 40 to 7 immediately when you turn on the phone and become very hot! :)

**Comment by sapier** [comment]
minetest ain't written for android so don't expect it to do things as they'd be required there ;-)

**Comment by est31** [comment]
Who approved this PR?

I don't think its small enough to live inside the "minimal fix" rule, as you [seem to want](http://irc.minetest.ru/minetest-dev/2015-12-18#i_4477503) to merge it under.

**Comment by MoNTE48** [comment]
It does not make sense on tablets and phones 5.5+ inches. The player must make more moves to press a button to it. This is silly!

**Comment by est31** [comment]
@MoNTE48 its good on smaller phones as now the buttons can be larger and one doesnt have to aim precisely. But agreed, the buttons should have been available by default on larger display sizes.

**Pull request merged**
