### PR TITLE
Convert Lua vectors into a proper Lua class

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes part of #3980

### CODE REVIEW

**Comment by rubenwardy** [comment]
Note that this isn't an entirely compliant Lua class. You'd need to redefine `new` when subclassing it.

**Actual subclassing method:**

```
MyVector = Vector:new()
MyVector.__index = MyVector
function MyVector.new(...)
    local obj = Vector.new(...)
    setmetatable(obj, MyVector)
en
function MyVector:foo()
    return 2
end

local mvec = MyVector:new(1, 2, 3)
```

**Ideal and standard Lua subclassing:**

```lua

```
MyVector = Vector:new()
function MyVector:foo()
    return 2
end

local mvec = MyVector:new(1, 2, 3)
```

This is due to backwards compatibility. I don't see this as a big problem, as subclassing will be very rare, and we could note about this in the API docs.

**Comment by paramat** [comment]
Needs profiling for any performance impact.
(LuaJIT doesn't make lowering performance okay, it is unreliably maintained and causes problems, many can't use it due to OOM)

**Comment by rubenwardy** [comment]
LuaJIT is maintained, it just has a memory limitation which will be removed soon with GC64. And yes, I will benchmark this but doubt there will be much performance loss

**Comment by rubenwardy** [comment]
Lua is 4% slower after this PR across my tests, ranging from 12% slower to 12% faster.
LuaJIT is 2% faster after this PR across my tests, ranging from 2% faster to 4% faster.

https://docs.google.com/spreadsheets/d/1LZC4X4J3qV9f1E4aDPTlkfzYLJZL3bD34xDU4eV6LzQ/edit?usp=sharing

<details>
<summary>Code</summary>

```lua
local ITR = 1000000
local clock = os.clock

do
	local start = clock()
	for i=1, ITR do
		vector.normalize({ x = 1, y = 2, z = 3 })--, { x = 3, y = 2, z = 1 })
	end
	print(clock() - start)
end

do
	local start = clock()
	for i=1, ITR do
		Vector.normalize({ x = 1, y = 2, z = 3 })--, { x = 3, y = 2, z = 1 })
	end
	print(clock() - start)
end
```

```lua
local ITR = 1000000
local clock = os.clock

do
	local vector2 = vector
	local vec = { x = 1, y = 2, z = 3 }
	local start = clock()
	for i=1, ITR do
		vector2.add(vec, { x = 3, y = 2, z = 1 })
	end
	print(clock() - start)
end

do
	local vec = Vector:new({ x = 1, y = 2, z = 3 })
	local start = clock()
	for i=1, ITR do
		vec:add({ x = 3, y = 2, z = 1 })
	end
	print(clock() - start)
end
```
</details>

**Comment by rubenwardy** [comment]
If you don't like that performance loss, there are some alternatives:

* Rename vector.new to vector.copy, and stop pretending it's a class.
* Keep them separate.
* Make a no-copy implementation for those that care about performance.

**Comment by paramat** [comment]
Ok no problem. I thought GC64 was only going to be usable on Windows only, good to hear it will come to Linux. And sorry for my slightly grumpy comment.

**Comment by stujones11** [comment]
Would it be possible to incorporate operator overloading, using metamethods perhaps?

I am sure I've seen examples of this before but have no idea how performance compares.

**Pull request closed without merging**
