### PR TITLE
Restore simple settings tab and add advanced settings as dialog

### PR DESCRIPTION
**Pull request by BlockMen**
Backport from https://github.com/blockplanet/blockplanet. Since I'm the copyright holder and doin this PR here it can be used ofc.

Might need some additional work on the translations, idk.

### CODE REVIEW

**Comment by est31** [comment]
This doesn't work, I've tried it.

**Comment by BlockMen** [comment]
@est31 used the wrong file, fixed.

**Comment by rubenwardy** [comment]
:+1:

**Comment by paramat** [comment]
:-1: For these reasons https://github.com/minetest/minetest/pull/3504#issuecomment-168362522

**Comment by RobertZenz** [comment]
@paramat The current settings dialog is *abysmal* from a users point of view. Not only is it *vast*, it is also hard to navigate because of the tree like structure combined with the small window.

While I find it a step upwards from the text only representation (mostly because of the grouping), it is several steps downwards especially for the "average" user.

**Comment by paramat** [comment]
I agree the branching and structure needs re-working, let's make it good (see comments in the other PR).

**Comment by PilzAdam** [comment]
:+1:

@paramat finding a structure that is usable by new players while also being expandable and potent enough to help advanced users is way too hard. Just displaying the old, stripped down version by default and offering the advanced view behind a button is good enough.

**Comment by paramat** [comment]
Okay :) i'm neutral now then.

**Comment by kilbith** [comment]
So what now ? @BlockMen you have your 2nd approval, could you please rebase it and merge ?

**Comment by kaeza** [comment]
BUMP.

The tree-based settings dialog is a huge usability nightmare for new users. It'd be fine as an "Advanced" button, but please restore the old simple settings dialog.

:+1:

**Comment by paramat** [comment]
Yes go for it, there's much demand for a simple alternative.

**Comment by C1ffisme** [comment]
Rather than having it as a tab, what about having it as a button on the advanced settings. It would say something like:

"Simpler settings dialog"

That way there aren't seven or eight tabs in the main minetest menu, which I find slightly overcrowded.

Of course, for the sake of common sense, I would make the old settings show in a tab, then press a button saying "Advanced Settings" to open the newer dialog.

**Comment by rubenwardy** [comment]
Have you even tried this PR, or read the code? That's exactly what this does: it adds a dialog with the advanced setting in.

**Comment by C1ffisme** [comment]
@rubenwardy I haven't, and that's probably not the smartest thing, but I assume that you are adding another tab, one to hold normal settings and one to hold advanced settings.

I guess I'll look at that code. Sorry If I'm speaking nonsense.

**Comment by Fixer-007** [comment]
Yes, I agree too, old settings dialog + advanced button inside will be much better.

**Comment by 0-afflatus** [comment]
Good. It is fairly common practice to present simple settings and have an advanced settings button or tab. I'm thinking of vlc as an example.

**Comment by paramat** [comment]
Labelled as a possible blocker for release.

**Comment by kilbith** [comment]
Some other dev will likely have to take this PR in charge since @BlockMen seems to have abandoned it.

**Comment by BlockMen** [comment]
@kilbith Yes, you are right. I'm not willing to rebase this, it should have been merged long time ago already, look on the date: 1st January...

**Comment by est31** [comment]
I agree to paramat making this a blocker. This precise PR doesnt have to be merged, but the stuff it does is certainly needed inside the next release.

**Comment by paramat** [comment]
Related PR #3504

**Comment by paramat** [comment]
Moving blocker label to the issue.

**Comment by kilbith** [comment]
@BlockMen Rebasing and merge roughly take 5 min. and you'd give a nice service to everyone. A new release is planned in one month and it's important to get that stuff done before.

**Comment by paramat** [comment]
Rebasing might be complex, perhaps someone would like to open a new PR based on this code? if @BlockMen is happy with that?

**Comment by kilbith** [comment]
I might try to do it.

**Pull request closed without merging**
