### PR TITLE
Chanke make command

### PR DESCRIPTION
**Pull request by niansa**
Change make command to automatically detect number of cores

### CODE REVIEW

**Comment by Calinou** [comment]
If you're aiming for better build performance, you could even add `ninja` to the list of dependencies to install then use these commands to build Minetest instead:

```bash
cmake . -G Ninja
cmake --build .
```

`cmake --build` is a build system-independent command that will invoke the appropriate command such as `make` or `ninja`. [Ninja](https://ninja-build.org/) usually performs better than GNU make and automatically uses all available CPU threads by default.

**Comment by MoNTE48** [comment]
(or `make -j$(sysctl -n hw.ncpu)` on mac)

**Comment by niansa** [comment]
Ok

**Comment by niansa** [comment]
I Closed this.

**Pull request closed without merging**
