### PR TITLE
[Do not squash me] Fix group setting bugs

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes tailing `}` reported in https://github.com/minetest/minetest/issues/8076#issuecomment-452564733
Fixes low-priority tailing comma #8077 (patch from @srifqi )

EDIT: **How to test**
1) In current master: Edit noise settings, save, reset to default, repeat. A bunch of closing brackets will be left over.
2) Same for this PR: The group setting are removed properly
3) With this PR: remove all mapgen flags on a setting. No tailing comma is written to the config.

### CODE REVIEW

**Comment by paramat** [comment]
Thanks, will test when i have time to.

**Comment by paramat** [comment]
Now testing (sorry for delay, have been very tired).

**Comment by SmallJoker** [comment]
Thanks for testing. If the code works for you as expected, then please approve the PR. I also tested it and it works fine.

**Comment by paramat** [comment]
:+1: i trust you.

**Comment by paramat** [comment]
80b90159390b55dfc698a31da6a8e1fb59d51eee
9512c2986e2d5b8388860a51cce2a75f37e67bf6

**Pull request closed without merging**
