### PR TITLE
Add PNG gamma test nodes to devtest

### PR DESCRIPTION
**Pull request by erlehmann**
### Goal of the PR

This PR is intended to enable developers and users to diagnose PNG gamma correction issues.

### How does the PR work?

The PR creates 18 test nodes with test textures from PNG suite.
<http://www.schaik.com/pngsuite2011/pngsuite.html#gamma>

### Does it resolve any reported issue?

No, but it will probably lead to reporting of issues with PNG gamma correction and help with debugging them.

### Does this relate to a goal in [the roadmap](../doc/direction.md)?

This PR relates to goal ”2.1 Rendering/Graphics improvements”:
> The priority is fixing the issues, performance, and general correctness.
> Once that is done, fancier features can be worked on, such as water shaders,
> shadows, and improved lighting.

### If not a bug fix, why is this PR needed? What usecases does it solve?

This PR enables developers to find and debug PNG gamma correction issues.
It should also allow users to figure out if the gamma is correct for their monitor.

### Supplementary Materials

Here is a screenshot that shows how Minetest 5.4.1 applies gamma correction wrong.
All of the textures in a row should look the same except for the numbers – but do not.

**Edit:** The bottom left node has a larger black bar where there should be a gradient.

minetest-game-devtest-testnodes-gamma-png

### CODE REVIEW

**Review by Df458 — COMMENTED** [review]
Gave the code and nodes a look, seems to do what it says on the tin. I can also reproduce some of the visual issues in the screenshot as well.

**Comment by rubenwardy** [comment]
@Df458  did you meant to approve?

**Review by Df458 — APPROVED** [review]

**Comment by sfan5** [comment]
Before adding a test for something it has to be considered whether that feature is even wanted.

On [IRC](https://irc.minetest.net/minetest-dev/2022-04-24#i_5965617) @erlehmann said that the issue highlighted by this PR needs to be fixed at render time, not decode time:
```
<erle> the gamma thing is not a texture decoding bug btw, just to clear that up. the values are correctly decoded. it is a rendering pipeline issue and currently it breaks for every PNG file with a gAMA chunk (except for gamma 1.0 i guess?)
<erle> if i am not mistaken for correct texture calculations (like blending) you need the raw pixel values, have to transform that into linear space which has to have a higher precision, do any work, then transform it back. you can *probably* try to hack it roughly by putting in some pow(pixels, gamma) and pow(pixels, 1/gamma) stuff in the texture decoding logic, but I think it does not belong there.
```
At this point this PR becomes a disguised feature request that is better titled "Revise the rendering pipeline to be gamma correct". I gathered that this would require the following:
1. Store textures <i>and any colors</i> in linear light with higher precision such as 16-bit or floating point textures
(Irrlicht does not even support this, nor does any other part of our code)
2. Do Gamma correction at the very end in the shaders
(AFAIK this is impossible with the fixed pipeline so we'd have to drop support for disabling shaders)

From the estimated amount of work and also being a feature approximately nobody cares about this would be rejected and so should this PR which just adds test. Incidentally I have found that browsers do not seem to implement gamma correction either...

**Comment by rubenwardy** [comment]
Discussed in core developer meeting. Closed as per comment above

https://irc.minetest.net/minetest-dev/2022-05-08#i_5971583

**Pull request closed without merging**
