### PR TITLE
Remote Media GET request to index.mth

### LINKED ISSUE #10369: Make remote media fully static and CDN compatible
## Problem

Currently the client sends a POST request to the server containing the hashes of the wanted files.
The server will answer with the hashes the server can provide.
This makes caching the server and it's hashes for future requests of files not possible.

On the other hand POST requests can't be handled on CDNs

## Solutions

We could make the client just send GET requests. The static index.mth file would just contain all files on the remote media server (This is already possible but not really recommend)

This is also backward compatible as clients sending POST request are also able to handle more than the needed hashes.
Only the remote media servers need to provide a static index.mth on GET requests.

## Additional context

This would also allow using the remote media servers for minetest servers not using a remote media server.

It just makes creating a remote media server a lot simpler.
Servers can be a just a gitlab page like [this](https://gitlab.com/lejo1/subgames-media).

Whole media collections are possible when we would support CDNs

### PR DESCRIPTION
**Pull request by Lejo1**
Closes #10369  

Caching could also be added but needs to be discussed first.

## How to test

Try the PR on a server with a static remote media_server like [this](https://github.com/Lejo1/mtmedia)

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
LGTM

**Comment by appgurueu** [comment]
Breaks backwards compatibility for no reason. Clients trying to request media from legacy remote media servers like @sofar's will be shown error messages.

**Comment by Lejo1** [comment]
> Clients trying to request media from legacy remote media servers like @sofar's will be shown error messages.

Yep, but it's only the case for remote media servers. There is kind of only the server by sofar. So it should be no Problem to add a static answer for get requests. This should be done before remote media gets more common used.

**Comment by appgurueu** [comment]
> > Clients trying to request media from legacy remote media servers like @sofar's will be shown error messages.
> 
> Yep, but it's only the case for remote media servers. There is kind of only the server by sofar. So it should be no Problem to add a static answer for get requests. This should be done before remote media gets more common used.

Sofar's server is not the only implementation, there also is [mine](https://github.com/appgurueu/minetest-media-server-java-edition) (it probably is unused though). I don't see the benefit of removing those few lines of code; add the GET request as additional feature if you want it.

**Comment by Lejo1** [comment]
The Post request ist just a design Problem.
Just see my Issue #10369

**Comment by appgurueu** [comment]
> The Post request is just a design Problem.

I disagree. The POST request is useful in case of slow connections and bloated media servers. The GET request can also be desirable though, as it requires less upload and works with a static media server. But just deleting the POST request is plain compatibility-breaking and will therefore have to wait until 6.x.

A proper implementation would send a different media server announcement, specifying the method to be used.

**Comment by Lejo1** [comment]
> But just deleting the POST request is plain compatibility-breaking and will therefore have to wait until 6.x.

That's just not true! As I said before the current client can also handle static answers.
So static servers will work than just like now.
Dynamic servers can just add a static answer for GET requests.

This only breaks compatibility for REMOTE MEDIA SERVERS. There are only a few so this is absolutely no Problem.

In addition to that media can also be fetched the normal way in case something goes wrong.

And third you can add multiple remote media servers. For example a static and a dynamic one.

**Comment by appgurueu** [comment]
> > But just deleting the POST request is plain compatibility-breaking and will therefore have to wait until 6.x.
> 
> That's just not true! As I said before the current client can also handle static answers.

Doesn't change the fact that it is technically compatibility breakage. Period.

> So static servers will work than just like now.

Yes?

> Dynamic servers can just add a static answer for GET requests.

Making them static servers.

> This only breaks compatibility for REMOTE MEDIA SERVERS. There are only a few so this is absolutely no Problem.

So you are agreeing that it is breaking compatibility, but arguing that the scope is limited and it is therefore "fine"? I'd like @sofar's input, as he is providing a fairly popular dynamic media server.

> In addition to that media can also be fetched the normal way in case something goes wrong.

Letting tasty error messages appear.

> And third you can add multiple remote media servers. For example a static and a dynamic one.

No you can't.

I don't see the benefits of this barbaric deletion other than the promotion of static bloat servers.

**Comment by Lejo1** [comment]
> Doesn't change the fact that it is technically compatibility breakage. Period.

WTF? It's backward compatible. It needs no breaking minetest release.

> Yes?

Yes!

> Letting tasty error messages appear.

This shouldn't happen. Just said that it's not so critical.

>> And third you can add multiple remote media servers. For example a static and a dynamic one.

> No you can't.

[Yep](https://github.com/minetest/minetest/blob/81c66d6efb9fb0ab8a03b40e2bc22aa49eff9a04/src/network/clientpackethandler.cpp#L679), you can it's just not documented.

> Why can't you the post request be kept, with the static index.mth as fallback, or the other way around?

The most CDNs or other hosting servers can't handle POST requests. So they return a error instead of the static file. 

> So you are agreeing that it is breaking compatibility, but arguing that the scope is limited and it is therefore "fine"? I'd like @sofar's input, as he is providing a fairly popular dynamic media server.

So lets's create another useless discussion consiting of just disaproval. Last time it was really productive.

You can think of this what you like. I know that you surly have spent a lot of time in creating an own minetest remote media server implementation.
Anyway please keep this professional and not personal.
I just think that a static remote media server is a better solution.

**Comment by appgurueu** [comment]
> WTF? It's backward compatible. It needs no breaking minetest release.

No it's not, you're removing dynamic media server support.

> This shouldn't happen. Just said that it's not so critical.

But it will if a media server doesn't support the GET request.

> [Yep](https://github.com/minetest/minetest/blob/81c66d6efb9fb0ab8a03b40e2bc22aa49eff9a04/src/network/clientpackethandler.cpp#L679), you can it's just not documented.

Interesting

> The most CDNs or other hosting servers can't handle POST requests. So they return a error instead of the static file.

So the purpose is just to make all Minetest clients adapt to your fairly specific usecase? You are removing functionality because your hosting is too limited?

This still is no good reason. You could (1) silence the error, or (2) change the order, so that the GET request is tried first. Compatibility breakage is entirely unnecessary.

> You can think of this what you like. I know that you surly have spent a lot of time in creating an own minetest remote media server implementation.

I have also spent some time creating my own dynamic implementation.

**Comment by rubenwardy** [comment]
I don't think this counts as a compatibility breaking change. No servers, worlds, or mods will be broken. Servers using media servers that don't support GET will continue to work

**Comment by sfan5** [comment]
I'd still like to hear @sofar's input on this.

> it can be done for free using GitHub Pages

Note that many free hosting services explicitly disallow using them as media CDN without actual site content. Github Pages doesn't from what I can see, but they have some usage limits: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#usage-limits

**Comment by Lejo1** [comment]
> Note that many free hosting services explicitly disallow using them as media CDN without actual site content.
Github Pages doesn't from what I can see, but they have some usage limits: https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#usage-limits

True, but there are anyway enough that does like [jsdelivr.com](jsdelivr.com) (Their Terms doesn't give a clear answer but I asked.)
Just see my "Test Static server" I listed some possible links there: https://github.com/Lejo1/mtmedia

**Comment by sofar** [comment]
to me, this is a regression. clearly this has an impact.

there are 2-3 dynamic implementations right now and quite a few servers use them. this regression means either lots of manual work for each server owner setting up their own remote media thing (barrier 1) or having clients hit their servers for much more media data.

Then on top of that it would remove any incentive to run a centralized remote media server since there no longer will be any efficiency in doing so (at scale). but people still need a media server so now everyone will need to setup their own static thing, and we know that that has turned into a zoo of scripts which again is a barrier for new server owners. "what script do you use?" ... "a python script for python2.7"...

At the code level, this also doesnt make sense. Why not try to POST first, and if that fails, try a GET? then you'd not break anything and make static sites work. but I guess that's slightly more code to write.

I get the feeling that lejo1 is still frustrated that he couldn't make mtmediasrv working 2+ years back. He could always use the public one I still run of course. 
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Lejo1** [comment]
> there are 2-3 dynamic implementations right now and quite a few servers use them. this regression means either lots of manual work for each server owner setting up their own remote media thing (barrier 1) or having clients hit their servers for much more media data.

Yep, sure! But on the other hand 2-3 is not a lot.

> Then on top of that it would remove any incentive to run a centralized remote media server since there no longer will be any efficiency in doing so (at scale). but people still need a media server so now everyone will need to setup their own static thing, and we know that that has turned into a zoo of scripts which again is a barrier for new server owners. "what script do you use?" ... "a python script for python2.7"...

There is not reason why people shouldn't use a centralized one like yours than. The difficulties are just different.

> At the code level, this also doesnt make sense. Why not try to POST first, and if that fails, try a GET? then you'd not break anything and make static sites work.but I guess that's slightly more code to write.

Yes, it is Genius! I just wrote the Code that way cause I thought that adding a simple GET request answere to the few remote media implementations shouldn't be a breaking change. Adding both ways is also a great idea.

> I get the feeling that lejo1 is still frustrated that he couldn't make mtmediasrv working 2+ years back. He could always use the public one I still run of course.

Come on really? I thought we want to take this professional.

I really don't care anymore about what you do of this. I wanted to make (in my oppinion) a improvment. It's your decison what to do about it and has nothing to do with any "trouble or disagreements" in the past.
I wonder if this is the default way to handle contributors.

**Comment by sofar** [comment]
> There is not reason why people shouldn't use a centralized one like yours than. The difficulties are just different.

Aside the double negative error here, this seems baseless:

Before I wrote mtmediasrv, someone else had already implemented the client side of it in the client. Clearly more than one person thought it would be a good idea that would serve many users. Maybe not for you, but definitely for many users.

Using a public remote media server is less work for a server owner than setting up even the simplest of remote media servers. It is literally one complex step less and only requires one to edit a file. You don't even need to ask for permission to use my prms on a server.

I think this patch was hasted, and you're arguing your way out of rewriting a better solution, one that people are willing to consider.

**Comment by rubenwardy** [comment]
The size of the public media server index file is much larger than I expected, so I no longer support this PR

Doing POST than GET is fine by me. Another alternative would be to have Minetest servers include remote server availability when sending hashes to fetch. This would be a bit like certificate pinning

**Comment by sfan5** [comment]
An automatic fallback to a GET request might still be useful. For example on certain CDN setups it's not possible/too compliated to configure POST requests for the desired behaviour.

**Pull request closed without merging**
