### PR TITLE
Say /setpassword is insecure

### PR DESCRIPTION
**Pull request by 56independent**
Manually write the following git change to Github because push does not work

```
From 856868b1e273c4ca26bc930d1212bf6d75909194 Mon Sep 17 00:00:00 2001
From: 56independent <emailchecker506@gmail.com>
Date: Fri, 16 Dec 2022 18:40:35 +0100
Subject: Say /setpassword is insecure for issue #8982


diff --git a/builtin/game/chat.lua b/builtin/game/chat.lua
index bbcdcf2d0..baab5212f 100644
--- a/builtin/game/chat.lua
+++ b/builtin/game/chat.lua
@@ -416,7 +416,7 @@ core.register_chatcommand("revokeme", {
 
 core.register_chatcommand("setpassword", {
 	params = S("<name> <password>"),
-	description = S("Set player's password"),
+	description = S("Set player's password (sent unencrypted, thus insecure)"),
 	privs = {password=true},
 	func = function(name, param)
 		local toname, raw_password = string.match(param, "^([^ ]+) +(.+)$")
```

This PR is a Ready for Review

## How to test

run `/setpassword` i guess

### CODE REVIEW

**Comment by rubenwardy** [comment]
You updated the wrong command

**Comment by 56independent** [comment]
How was it wrong? `/setpassword` seems to match what was on screen. Where was the troublesome command?

**Comment by rubenwardy** [comment]
You updated /clearpassword, not /setpassword. Make sure to check the files changed tab. Also, you don't need to close and make a new PR, you can update a PR by making a commit on the branch

**Comment by 56independent** [comment]
I have since fixed that issue now after an accidental button click leading to the wrong place (i wish issue 12324 was implemented).

**Comment by rollerozxa** [comment]
I'm pretty sure the issue means that the password should be sent securely over SRP or with network encryption, not just add a note to the command description saying that it's insecure.

**Comment by 56independent** [comment]
> I'm pretty sure the issue means that the password should be sent securely over SRP or with network encryption, not just add a note to the command description saying that it's insecure.

https://github.com/minetest/minetest/issues/8982#issuecomment-534325049

**Pull request merged**
