### PR TITLE
Optimize vertex calculations (maths), perf improvement

### PR DESCRIPTION
**Pull request by nerzhul**
Here is a bunch of mathematics improvements, factorizing some calculations.

### CODE REVIEW

**Comment by rubenwardy** [comment]
You need to squash your commits into a single commit before it is merged. Is this done?

How have you tested this PR to check for bugs?

**Comment by nerzhul** [comment]
@rubenwardy it's squashed.
Bugs have been tested with shader enabled. No modification in shader rendering.

**Comment by Zeno-** [comment]
commit 148fffb0f23fa437c67639ff3cc69177fb71d76a

**Comment by Zeno-** [comment]
Reverted. Causes issues with bumpmapping enabled.

**Comment by nerzhul** [comment]
Missing semycolon, it was fixed

**Comment by nerzhul** [comment]
T4im on IRC said that it fixed the problem. PR can now be safely pulled.

**Comment by Zeno-** [comment]
:+1: 

Please fix the whitespace errors though? :(

**Comment by rubenwardy** [comment]
I use Kate which strips all the whitespace from the end of lines - Minetest could use this.

**Comment by nerzhul** [comment]
I fixed spaces. I'm using geany which fixes also tabs, but not by default.

Please commit

**Comment by rubenwardy** [comment]
Looks good to me.

**Comment by Zeno-** [comment]
commit 46821f11566efa1da2ba74c9e95794d9e50d6812

**Pull request closed without merging**
