### PR TITLE
Fix to camera moving on its own

### PR DESCRIPTION
**Pull request by haolez**
Just a candidate fix. There are other possible solutions. It fixes the issue on my machine.

[Issue #4287 ]

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
Issue #4287

**Comment by paramat** [comment]
Hmm, i'm uncomfortable with this weird hacky fix, this only affects one person and 1 or 2 others have somehow fixed the problem (but can't remember how or don't know how).
Please could you try changing some touchpad settings on your laptop? As far as i can remember the fix was not in MT code but elsewhere.

**Comment by rubenwardy** [comment]
is dx never equal to 0.5? Surely this would be better:

```cpp
dx = (abs(dx) <= 1) ? 0 : dx;
dy = (abs(dy) <= 1) ? 0 : dy;
```

**Comment by SmallJoker** [comment]
`dx` and `dy` are both signed integers - no decimal places.

I tested this "fix" but slow mouse movements are now blocked automatically.

**Comment by haolez** [comment]
The correct fix is to track the odd value to its origin. I agree that the hack is not good enough, but I disagree that the number of affected users is surely low. We don't know that. Maybe some players are giving up even before reporting it, since this bug makes it impossible to play.


Let's keep digging! :)





On Wed, Jul 27, 2016 at 9:59 AM -0300, "SmallJoker" <notifications@github.com> wrote:












dx and dy are both signed integers - no decimal places.



I tested this "fix" but slow mouse movements are now blocked automatically.

**Comment by paramat** [comment]
> I tested this "fix" but slow, wanted mouse movements are now blocked automatically.

:-1: A better fix is needed.

**Comment by HybridDog** [comment]
What about enabling cinematic mode?

**Comment by paramat** [comment]
See #4287 it's a DPI issue.

**Comment by paramat** [comment]
@haolez perhaps this should be closed if you agree it's hacky?

**Comment by est31** [comment]
I think reading from a [comment in the issue](https://github.com/minetest/minetest/issues/4287#issuecomment-240298978) that the author is fine with the issue being closed.

**Comment by paramat** [comment]
Yeah, i think this should be closed then.

**Pull request closed without merging**
