### PR TITLE
Properly remove SAO when worldedges are overtaken

### LINKED ISSUE #2702: Bottom of the world weirdness
The bottom of the world (located at Y=-30912) behaves really weird.
It looks like an endless abyss and the background color constantly changes the color if you change your viewing angle.

Players can walk on it, but can't build on it.

But strangely, items, falling nodes can pass the bottom without problems.
This is problematic especially for falling nodes, because they don't seem to become normal nodes again. It also appears that falling nodes and items are stuck a couple of node lengths below the “bottom” and don't fall any further. I think the biggest problem here is that this stuff does not get deleted (or not deleted fast enough? Not sure).

What do you think about this? I have not really a good idea on how to change this.

### PR DESCRIPTION
**Pull request by nerzhul**
Also remove ServerMap::prepareBlock which is unused and empty

Fixes #2702 and #5824
Also fixes minetest/minetest_game#1469

Overrides #5856

### CODE REVIEW

**Comment by paramat** [comment]
Thanks. I'm not too bothered anymore about these being in MapgeParams, and we can always improve later, so i will test to get this in.

**Comment by paramat** [comment]
This possibly has a bug, investigating, do not merge.

**Comment by paramat** [comment]
This works if mapgen limit is 31000, but with any other setting it still acts as if the limit is 31000.
:-1:

**Comment by paramat** [comment]
Seems that mapgen limit is still set to the default value of 31000 when 'calcMapgenEdges()' is called.

**Comment by paramat** [comment]
Always calculates these values, whatever mapgen limit is set:

sao limit min: -309123.000000
sao limit max: 309273.000000

These values are correct for a mapgen limit of 31000 only.

**Comment by paramat** [comment]
Perhas call `void MapgenParams::calcMapgenEdges()` from `bool MapgenParams::saoPosOverLimit(const v3f &p) const` but once only on first call? I did this before and it worked.

**Comment by paramat** [comment]
Testing this:
```
bool MapgenParams::saoPosOverLimit(const v3f &p)
{
	if (!sao_limit_min)
		calcMapgenEdges();

	return p.X < sao_limit_min ||
		p.X > sao_limit_max ||
		p.Y < sao_limit_min ||
		p.Y > sao_limit_max ||
		p.Z < sao_limit_min ||
		p.Z > sao_limit_max;
}
``
Works so far.

**Comment by paramat** [comment]
Seems good.
Note the 'const' needs removing from the end of `bool MapgenParams::saoPosOverLimit(const v3f &p)`
Also of course revert
```
 	{
+		calcMapgenEdges();
 	}
```

**Comment by paramat** [comment]
I've tested the calculated values though and they are fine, so +1 if this is updated.

**Comment by nerzhul** [comment]
all points fixed

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
Retested :+1:

**Pull request merged**
