### PR TITLE
Add metatables to vectors (but keep old format)

### LINKED ISSUE #7196: Metatable support for vectors
##### Issue type
 - Feature request

##### Summary
I suggest to make use of Lua metatables (http://www.lua.org/manual/5.1/manual.html#2.8) in vectors.

So that this code works:

```
v = vector.new(1,2,3) 
v2 = vector.new(2,3,4)
v3 = v + v2
```

Where `v3 = v + v2` is equivalent to `v3 = vector.add(v, v2)`.

Basically this is just for syntactic sugar and to make code a bit more readable.

### PR DESCRIPTION
**Pull request by Desour**
#9612 grew too big and the change of the internal representation of the vectors is probably controversial, therefor this draft:

- PR does mostly the same as #9612 but:
  - There are less features/changes.
  - The internal representation isn't changed, it still is `{x=X,y=Y,z=Z}`.
-  Closes #7196.
- New features:
  - Indexing with numbers.
  - Calling a function directly with `:`.
  - Using operators.

## To do

This PR is a Work in Progress:
Although I do not expect any performace changes, people will probably still want to see this is true.

## How to test

There are new unittests:
`busted builtin`

Play around, use your mods and so on.

### CODE REVIEW

**Comment by pyrollo** [comment]
Some quick remarks:

- You could have the same code for old format and metamethod if you add to old format the ability to work with a scalar first argument (avoids duplication);
- Other operations could be added as methods (length, normalize, floor, round...). I'm not sure about performance impact having many entries in metatable. Anyway for code needing performance, scalar could still be used.

**Comment by Desour** [comment]
>You could have the same code for old format and metamethod if you add to old format the ability to work with a scalar first argument (avoids duplication);

I guess you are referring to `__add` not being exactly the same as `vector.add`.
I am aware of this. (I think, the other PR does this. (I will maybe change this there.))
I wanted `vector.func(v, ...)` to be the same as `v:func(...)` and there the first argument is always a vector, checking for it to be a number would be unnecessary.

>Other operations could be added as methods (length, normalize, floor, round...). I'm not sure about performance impact having many entries in metatable. Anyway for code needing performance, scalar could still be used.

All `vector.*` functions can already be used as methods. See last line in `metatable.__index`.

**Comment by Wuzzy2** [comment]
Question: What happens to games and mods that create vectors “by hand”, e.g. “`v={x=1,y=2,z=3}`”? This is fairly common practice, probably even more so than the `vector.new` method, I believe.

**Comment by Desour** [comment]
See https://github.com/minetest/minetest/pull/9612#issuecomment-780211563.

**Pull request closed without merging**
