### PR TITLE
Add basic_privs setting

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by est31** [comment]
:+1: I like this better than #3976

**Comment by rubenwardy** [comment]
Much simpler, too. Is it worth documenting in lua_api.txt?

**Comment by est31** [comment]
You mean fixing the docs? Yes, you can do it.

**Comment by sofar** [comment]
Ahh yes, this is nice!

**Comment by PilzAdam** [comment]
:+1: 

This doesn't belong into `lua_api.txt`, but I don't care that much.

**Comment by est31** [comment]
Ah well, its okay if its not documented in lua_api.txt too. Sorry I was mistaken and believed that the table case wasn't documented at all.

**Comment by rubenwardy** [comment]
I added a note there as that's one of the places I'd look before bothering to go into builtin/.

**Comment by PilzAdam** [comment]
@rubenwardy the problem is that it's not part of the API. What if the setting changes in the future? `lua_api.txt` might become inconsistent with `minetest.conf`.

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
17bfe2fe5b24aa7cf097bfe0a18dd3a66a0cee38

**Pull request closed without merging**
