### PR TITLE
Allow setting state to rotate camera about parent object

### PR DESCRIPTION
**Pull request by DevyHeavy**
The goal of this PR is to, ultimately, provide functionality allowing for the player camera to rotate about a parent object.

This PR works by using Irrlicht's built-in quaternion class to rotate specific objects and vectors the player's camera depends on.

**This is a draft**
Right now only the math of rotating some points relative to a parent objects/origin is done. Lua modding interface has not been completed yet. This PR is here as a draft so that, hopefully, others can join in on the discussion and help build this feature.

Here is an example of the state of this feature. Please note that at one point in the video the camera jolts, this is due to the boat rotation code, not this feature: [video](https://streamable.com/ujaywe)

## To do
This PR is a Work in Progress

- [ ] Test, develop, and verify that the rotation math actually works
- [ ] Add Lua modding functions like get/set_eye_attach_state(parent, state)

The biggest issue right now is that the feature only works when a boat is placed in one direction. Even then the camera does not behave as expected. One of the biggest goals is to make sure when looking down it is always at the boat as if you were standing on it.

## How to test
Download minetest-game and replace init.lua in the default 'boats' mod with the below code:

<details>
  <summary>Boat init.lua rotation testing code</summary>
  
  ```--
-- Helper functions
--

local function is_water(pos)
	local nn = minetest.get_node(pos).name
	return minetest.get_item_group(nn, "water") ~= 0
end


local function get_sign(i)
	if i == 0 then
		return 0
	else
		return i / math.abs(i)
	end
end


local function get_velocity(v, yaw, y)
	local x = -math.sin(yaw) * v
	local z =  math.cos(yaw) * v
	return {x = x, y = y, z = z}
end


local function get_v(v)
	return math.sqrt(v.x ^ 2 + v.z ^ 2)
end

--
-- Boat entity
--

local boat = {
	initial_properties = {
		physical = true,
		-- Warning: Do not change the position of the collisionbox top surface,
		-- lowering it causes the boat to fall through the world if underwater
		collisionbox = {-0.5, -0.35, -0.5, 0.5, 0.3, 0.5},
		visual = "mesh",
		mesh = "boats_boat.obj",
		textures = {"default_wood.png"},
	},

	driver = nil,
	v = 0,
	last_v = 0,
	removed = false,
	auto = false
}


function boat.on_rightclick(self, clicker)
	if not clicker or not clicker:is_player() then
		return
	end
	local name = clicker:get_player_name()
	if self.driver and name == self.driver then
		self.driver = nil
		self.auto = false
		clicker:set_detach()
		player_api.player_attached[name] = false
		player_api.set_animation(clicker, "stand" , 30)
		local pos = clicker:get_pos()
		pos = {x = pos.x, y = pos.y + 0.2, z = pos.z}
		minetest.after(0.1, function()
			clicker:set_pos(pos)
		end)
	elseif not self.driver then
		local attach = clicker:get_attach()
		if attach and attach:get_luaentity() then
			local luaentity = attach:get_luaentity()
			if luaentity.driver then
				luaentity.driver = nil
			end
			clicker:set_detach()
		end
		self.driver = name
		clicker:set_attach(self.object, "",
			{x = 0.5, y = 1, z = -3}, {x = 0, y = 0, z = 0})
		player_api.player_attached[name] = true

		minetest.after(0.2, function()
			player_api.set_animation(clicker, "sit" , 30)
		end)
		clicker:set_look_horizontal(self.object:get_yaw())
	end
end


-- If driver leaves server while driving boat
function boat.on_detach_child(self, child)
	self.driver = nil
	self.auto = false
end


function boat.on_activate(self, staticdata, dtime_s)
	self.object:set_armor_groups({immortal = 1})
	if staticdata then
		self.v = tonumber(staticdata)
	end
	self.last_v = self.v
end


function boat.get_staticdata(self)
	return tostring(self.v)
end


function boat.on_punch(self, puncher)
	if not puncher or not puncher:is_player() or self.removed then
		return
	end

	local name = puncher:get_player_name()
	if self.driver and name == self.driver then
		self.driver = nil
		puncher:set_detach()
		player_api.player_attached[name] = false
	end
	if not self.driver then
		self.removed = true
		local inv = puncher:get_inventory()
		if not (creative and creative.is_enabled_for
				and creative.is_enabled_for(name))
				or not inv:contains_item("main", "boats:boat") then
			local leftover = inv:add_item("main", "boats:boat")
			-- if no room in inventory add a replacement boat to the world
			if not leftover:is_empty() then
				minetest.add_item(self.object:get_pos(), leftover)
			end
		end
		-- delay remove to ensure player is detached
		minetest.after(0.1, function()
			self.object:remove()
		end)
	end
end



local function mul_mat3mat3(c, a, b)
  c[1], c[2], c[3],
  c[4], c[5], c[6],
  c[7], c[8], c[9]
    = a[1] * b[1] + a[2] * b[4] + a[3] * b[7]
    , a[1] * b[2] + a[2] * b[5] + a[3] * b[8]
    , a[1] * b[3] + a[2] * b[6] + a[3] * b[9]
    , a[4] * b[1] + a[5] * b[4] + a[6] * b[7]
    , a[4] * b[2] + a[5] * b[5] + a[6] * b[8]
    , a[4] * b[3] + a[5] * b[6] + a[6] * b[9]
    , a[7] * b[1] + a[8] * b[4] + a[9] * b[7]
    , a[7] * b[2] + a[8] * b[5] + a[9] * b[8]
    , a[7] * b[3] + a[8] * b[6] + a[9] * b[9]
end

local sin, cos, atan2, sqrt = math.sin, math.cos, math.atan2, math.sqrt

local function euler2matrix(rot)
  local a1, a2, a3 = rot.z, rot.x, rot.y
  local c1, s1 = cos(a1), sin(a1)
  local c2, s2 = cos(a2), sin(a2)
  local c3, s3 = cos(a3), sin(a3)

  return s1 * s2 * s3 + c1 * c3, s1 * c2, s1 * s2 * c3 - c1 * s3,
         c1 * s2 * s3 - s1 * c3, c1 * c2, c1 * s2 * c3 + s1 * s3,
         c2 * s3,               -s2,      c2 * c3
end

local function matrix2euler(m00, m01, m02, m10, m11, m12, m20, m21, m22)
  -- matrix to ZXY
  local a1 = atan2(m01, m11)
  local c2 = sqrt(m22*m22 + m20*m20)
  local a2 = atan2(-m21, c2)

  -- Shoemake's original
--  local a3 = atan2(m20, m22)

  -- Mike Day's replacement
  -- https://www.semanticscholar.org/paper/Extracting-Euler-Angles-from-a-Rotation-Matrix-Day/668137fa4b875d890f446e689eea1e334bcf6bf6
  local c1, s1 = cos(a1), sin(a1)
  local a3 = atan2(s1*m12 - c1*m02, c1*m00 - s1*m10)

  return {x = a2, y = a3, z = a1}
end


local mat1 = {0,0,0,0,0,0,0,0,0}
local mat2 = {0,0,0,0,0,0,0,0,0}

local rotate = function(obj, angles)
  local x, y, z = angles.x, angles.y, angles.z
  angles = obj:get_rotation()
  angles.x, angles.y, angles.z = -angles.x, -angles.y, -angles.z
  mat1[1], mat1[2], mat1[3],
  mat1[4], mat1[5], mat1[6],
  mat1[7], mat1[8], mat1[9] = euler2matrix(angles)
  local rotated = false

  if y ~= 0 then
    local c, s = cos(y), sin(y)
    mat2[1], mat2[2], mat2[3] = c,  0,  s
    mat2[4], mat2[5], mat2[6] = 0,  1,  0
    mat2[7], mat2[8], mat2[9] =-s,  0,  c
    mul_mat3mat3(mat1, mat2, mat1)
    rotated = true
  end

  if x ~= 0 then
    local c, s = cos(x), sin(x)
    mat2[1], mat2[2], mat2[3] = 1,  0,  0
    mat2[4], mat2[5], mat2[6] = 0,  c, -s
    mat2[7], mat2[8], mat2[9] = 0,  s,  c
    mul_mat3mat3(mat1, mat2, mat1)
    rotated = true
  end

  if z ~= 0 then
    local c, s = cos(z), sin(z)
    mat2[1], mat2[2], mat2[3] = c, -s,  0
    mat2[4], mat2[5], mat2[6] = s,  c,  0
    mat2[7], mat2[8], mat2[9] = 0,  0,  1
    mul_mat3mat3(mat1, mat2, mat1)
    rotated = true
  end

  if rotated then
    angles = matrix2euler(mat1[1], mat1[2], mat1[3],
                          mat1[4], mat1[5], mat1[6],
                          mat1[7], mat1[8], mat1[9])
    angles.x, angles.y, angles.z = -angles.x, -angles.y, -angles.z
    obj:set_rotation(angles)
  end
end



local rot = {0,0,0}

function boat.on_step(self, dtime)
	if self.driver then
		local driver_objref = minetest.get_player_by_name(self.driver)
		if driver_objref then
			local ctrl = driver_objref:get_player_control()
                        rot.x = 0
                        rot.y = 0
                        rot.z = 0
			-- Local yaw
			if ctrl.left then
				rot.y = rot.y + dtime * 1
			end if ctrl.right then
				rot.y = rot.y - dtime * 1
			end
			-- Local pitch
			if ctrl.up then
				rot.x = rot.x + dtime * 1
			end if ctrl.down then
				rot.x = rot.x - dtime * 1
			end
			-- Local roll
			if ctrl.jump then
				rot.z = rot.z + dtime * 1
			end if ctrl.sneak then
				rot.z = rot.z - dtime * 1
			end
			-- Inteded to be used in future as:
			--   self.object:rotate(rot)
			-- but currently self.object is userdata, not a table
			-- so for now it has to be done this way from Lua
			rotate(self.object, rot)

			self.object:set_pos(self.object:get_pos())
		end
	end
end


function boat._on_step(self, dtime)
	self.v = get_v(self.object:get_velocity()) * get_sign(self.v)
	if self.driver then
		local driver_objref = minetest.get_player_by_name(self.driver)
		if driver_objref then
			local ctrl = driver_objref:get_player_control()
			if ctrl.up and ctrl.down then
				if not self.auto then
					self.auto = true
					minetest.chat_send_player(self.driver, "[boats] Cruise on")
				end
			elseif ctrl.down then
				self.v = self.v - dtime * 1.8
				if self.auto then
					self.auto = false
					minetest.chat_send_player(self.driver, "[boats] Cruise off")
				end
			elseif ctrl.up or self.auto then
				self.v = self.v + dtime * 1.8
			end
			if ctrl.left then
				if self.v < -0.001 then
					self.object:set_yaw(self.object:get_yaw() - dtime * 0.9)
				else
					self.object:set_yaw(self.object:get_yaw() + dtime * 0.9)
				end
			elseif ctrl.right then
				if self.v < -0.001 then
					self.object:set_yaw(self.object:get_yaw() + dtime * 0.9)
				else
					self.object:set_yaw(self.object:get_yaw() - dtime * 0.9)
				end
			end
		end
	end
	local velo = self.object:get_velocity()
	if self.v == 0 and velo.x == 0 and velo.y == 0 and velo.z == 0 then
		self.object:set_pos(self.object:get_pos())
		return
	end
	local s = get_sign(self.v)
	self.v = self.v - dtime * 0.6 * s
	if s ~= get_sign(self.v) then
		self.object:set_velocity({x = 0, y = 0, z = 0})
		self.v = 0
		return
	end
	if math.abs(self.v) > 5 then
		self.v = 5 * get_sign(self.v)
	end

	local p = self.object:get_pos()
	p.y = p.y - 0.5
	local new_velo
	local new_acce = {x = 0, y = 0, z = 0}
	if not is_water(p) then
		local nodedef = minetest.registered_nodes[minetest.get_node(p).name]
		if (not nodedef) or nodedef.walkable then
			self.v = 0
			new_acce = {x = 0, y = 1, z = 0}
		else
			new_acce = {x = 0, y = -9.8, z = 0}
		end
		new_velo = get_velocity(self.v, self.object:get_yaw(),
			self.object:get_velocity().y)
		self.object:set_pos(self.object:get_pos())
	else
		p.y = p.y + 1
		if is_water(p) then
			local y = self.object:get_velocity().y
			if y >= 5 then
				y = 5
			elseif y < 0 then
				new_acce = {x = 0, y = 20, z = 0}
			else
				new_acce = {x = 0, y = 5, z = 0}
			end
			new_velo = get_velocity(self.v, self.object:get_yaw(), y)
			self.object:set_pos(self.object:get_pos())
		else
			new_acce = {x = 0, y = 0, z = 0}
			if math.abs(self.object:get_velocity().y) < 1 then
				local pos = self.object:get_pos()
				pos.y = math.floor(pos.y) + 0.5
				self.object:set_pos(pos)
				new_velo = get_velocity(self.v, self.object:get_yaw(), 0)
			else
				new_velo = get_velocity(self.v, self.object:get_yaw(),
					self.object:get_velocity().y)
				self.object:set_pos(self.object:get_pos())
			end
		end
	end
	self.object:set_velocity(new_velo)
	self.object:set_acceleration(new_acce)
end


minetest.register_entity("boats:boat", boat)


minetest.register_craftitem("boats:boat", {
	description = "Boat",
	inventory_image = "boats_inventory.png",
	wield_image = "boats_wield.png",
	wield_scale = {x = 2, y = 2, z = 1},
	liquids_pointable = true,
	groups = {flammable = 2},

	on_place = function(itemstack, placer, pointed_thing)
		local under = pointed_thing.under
		local node = minetest.get_node(under)
		local udef = minetest.registered_nodes[node.name]
		if udef and udef.on_rightclick and
				not (placer and placer:is_player() and
				placer:get_player_control().sneak) then
			return udef.on_rightclick(under, node, placer, itemstack,
				pointed_thing) or itemstack
		end

		if pointed_thing.type ~= "node" then
			return itemstack
		end
		if not is_water(pointed_thing.under) then
			return itemstack
		end
		pointed_thing.under.y = pointed_thing.under.y + 2.5-- + 0.5
		boat = minetest.add_entity(pointed_thing.under, "boats:boat")
		if boat then
			if placer then
				boat:set_yaw(placer:get_look_horizontal())
			end
			local player_name = placer and placer:get_player_name() or ""
			if not (creative and creative.is_enabled_for and
					creative.is_enabled_for(player_name)) then
				itemstack:take_item()
			end
		end
		return itemstack
	end,
})


minetest.register_craft({
	output = "boats:boat",
	recipe = {
		{"",           "",           ""          },
		{"group:wood", "",           "group:wood"},
		{"group:wood", "group:wood", "group:wood"},
	},
})

minetest.register_craft({
	type = "fuel",
	recipe = "boats:boat",
	burntime = 20,
})

  ```
</details>

### CODE REVIEW

**Comment by ClobberXD** [comment]
I haven't checked the code yet, but I'm wondering if it's a better idea to pass this as a boolean to `set_attach` instead - i.e. this property would be dictated by individual `set_attach` calls (this is also the proposed approach in #8552), rather than being handled as a separate player state.

I was also thinking of a best-of-both kind of state, wherein the player look dir isn't completely locked (which is what I assume this PR doing) but is instead offset by the parent look dir. This would allow players to look around freely when they're riding a boat, for example, although their view will be offset from the parent's look dir.

Regarding API design, I'm thinking something like this would be nice:

```
local attachment_props = {
    lock_view_dir = false,
    offset_view_dir = true,
    ...
}
set_attach(parent, bone, position, rotation, attachment_props)
```

What do you think, @DevyHeavy?

**Comment by DevyHeavy** [comment]
@ClobberXD having free and locked camera movement is planned. I didn't make it clear but that is sort of why I called the property 'state' in the title. There should be multiple states for locked and free movement as you mentioned. I made an edit to the suggesting in the main my main comment to reflect this, before I just used a bool.

As far as API, I was planning on introducing another function only accessible from player objects like 'set_eye_offset' is. Although, doing it this way means it needs to be clear in the documentation that the property only applies when the player is attached to an object. The exact implementation would probably be 'set_eye_attach_state(parent[lua_object], state[byte])'. 'state' could be 1 = normal don't rotate the camera (default), 2 = rotate the camera with free head movement, 3 = rotate camera without free head movement (still set pitch and yaw so mods can use it for controlling vehicles). 

Regarding your proposal, I know it would be explained in the documentation what the attachment properties do, but it does seem less clear that it only applies to players. 'set_attach' is used to attach any object to another, not just players. That's just my thought though.

**Comment by ClobberXD** [comment]
> it does seem less clear that it only applies to players. 'set_attach' is used to attach any object to another, not just players.

This is a good point though. While I feel that a `set_attach`-based implementation would be more intuitive, it's going to be a little more confusing than a player-only ObjectRef method.

**Comment by DevyHeavy** [comment]
Oh yeah, a large reason a player accessible function is necessary is so that the property can be set player-by-player. There may be a case where a mod only wants to set the view state when attached for some players and not others.

**Comment by ClobberXD** [comment]
> There may be a case where a mod only wants to set the view state, when attached, for some players and not others.

I don't see much of a use-case for this, but even if a mod does want this functionality, it's possible to check the player name and pass the set_attach argument accordingly. I'm still personally leaning towards the `set_attach` approach - it feels the most intuitive to me. Confusion can be lessened as much as possible through documentation. But I'm not saying you have to implement the set_attach way; I'm just voicing my thoughts. :)

**Comment by DevyHeavy** [comment]
Latest commit adds lua method `set_eye_attach_state(state)` and `get_eye_attach_state()` but I have not tested that they work yet. I have tested that the four camera states work.

The first supported camera state (for when attached to a parent object) is the default that has been in Minetest forever. For the second state, the target and up camera vectors rotate with the parent object. The third state rotates the camera position about the parent origin, but keeps the camera up and target vectors in the default absolute directions. Last, the fourth state fixes the camera view forwards but the view rotates relative to the parent (similar to state 2 just without free head movement).

Right now there is a bug where upon detaching the player from the parent the camera remains offset. Code style and format will be refactored and cleaned when basic functionality is finished and verified.

**Comment by DevyHeavy** [comment]
The latest commit (2de4982) fixes camera offset error when detaching the player from the parent object.

I have noticed two more bugs:
- Upon attaching the player to a parent the camera drastically shifts when using state 2 (free head movement but up and target vectors rotate). The shift in rotation is hard to pin down, but most likely occurs due to the relative up and target vector rotations.
- Chunks/mapblocks don't load when the player is attached using state 2 and the camera is rotated towards them. Turning the player all the way around (yaw) will at some point load the chunks. I am guessing that chunk loading is dependent strictly upon the player yaw. After attempting to fix the previous bug I'll check this bug again.

**Comment by DevyHeavy** [comment]
New bug: as the head node and thus the camera rotates with the parent the minimap does not update. Need to figure out how to make mapblock and minimap rotation use the absolute yaw of any rotation. Maybe figure out how to project the rotated target vector onto the xz-plane and find the 360-degree yaw value?

**Comment by DevyHeavy** [comment]
The latest commit fixes minimap rotation. Still need to figure out camera chunk loading.

Important question, player pitch and yaw remain local to the parent object in this PR's current state. Meaning, as the parent rotates and then the player head and camera the pitch, yaw, and N/S/E/W valeus are remain the same (as long as you are not moving the player head using the mouse at this point). My question is, should those values change? Should the values returned by get/set_yaw/pitch be local or absolute?

**Comment by sfan5** [comment]
Having `get_look_dir()` mismatch the actual look direction would be sorta problematic but it sounds like the other alternative isn't much better...

**Comment by DevyHeavy** [comment]
@sfan5, would adding a parameter to `get_look_dir()` that allows for retrieving the local (based on pitch and yaw values) and absolute look direction work? The absolute vector would just be `m_camera_direction` from `camera.h`.

**Comment by DevyHeavy** [comment]
Turns out that the camera direction used to load chunks is based on the pitch and yaw of the player. This pitch and yaw is sent from the client in `client.cpp` and is used in `clientface.cpp`. To answer my question from earlier, the pitch and yaw in the hud should be absolute.

**Comment by DevyHeavy** [comment]
Latest commit uses values of absolute pitch and yaw to do chunk loading and be shown in the player hud. What's next is introducing lua methods for getting and maybe setting absolute pitch and yaw (right now, getting/setting the local values still works as before).

Another issue still remains where the player's camera is rotated/transformed when attaching to a parent. If I make methods for setting the absolute pitch/yaw values then I will be able to fix this.

**Comment by rubenwardy** [comment]
Closing WIP PR due to inactivity

**Pull request closed without merging**
