### PR TITLE
Compress textures and fonts

### PR DESCRIPTION
**Pull request by MoNTE48**
Use PNGOUT, OptiPNG and DeflOpt. Compress ~350 kb without loss of
quality.
No visual changes.
Texture compression helps reduce the size of the code (as well as the whole game) and also slightly increases the performance. I use these tools for about 3 years, no problem.

### CODE REVIEW

**Comment by sfan5** [comment]
Why modify <code>.gitattributes</code> and <code>.gitignore</code>?

**Comment by paramat** [comment]
I have no opinion on the other items, but please do not compress these textures. Compression always reduces quality, even if it is conciously not noticeable it has an effect on visual quality. Our logo, header and sunrise for example are important images that should remain as they are, they are low res and small files anyway.

**Comment by PilzAdam** [comment]
@paramat this is lossless compression, it doesn't have any effect on the quality.

**Comment by MoNTE48** [comment]
sfan5, Removed empty line at the end of the file.

**Comment by kilbith** [comment]
@paramat I suggest you to read (and even test) some documentation about OptiPNG (among other tools) before being so assertive and full of beliefs.

**Comment by est31** [comment]
@MoNTE48 its a rule to have a trailing \n at the end of the file, because some editors have bugs otherwise.

**Comment by est31** [comment]
In some cases texture compression/optimisation can be harmful, e.g. if it makes pixels with full alpha fully black on the other channels. This leads to bugs if you drop the alpha e.g. for opaque leaves.

**Comment by est31** [comment]
I would agree to merging this (without the removal of trailing \n).

**Comment by sfan5** [comment]
Permanently making the git history larger than it would be anyway just for a save of 350KB is not worth it IMO

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/5d88501a5799dbee8623ce9920423948659368fa

**Pull request closed without merging**
