### PR TITLE
Revert "Change default keys for cam/minimap to C/V"

### PR DESCRIPTION
**Pull request by wsor4035**
Reverts minetest/minetest#9779

### CODE REVIEW

**Comment by wsor4035** [comment]
revert key bindings change to C and V, see https://github.com/minetest/minetest/issues/10617#issuecomment-723880076 comment
also see https://github.com/minetest/minetest/issues/10678 as a another example of people not liking it

**Comment by randomMesh** [comment]
I think this should not be reverted. The change was good and reasonable. See comments in #6374

**Comment by samarth-ramesh** [comment]
+1.
The key switch was annoying, ~~ngl, while i did change them back to old, it was very irritating~~. Years of muscle memory down the drain...
also, the issue of ctrl + (c|v|x) having special meaning in most desktops

**Comment by Wuzzy2** [comment]
As the person who changed the default keybinds, I reject this PR.

I stand 100% by my reasoning for switching to C for camera and V for minimap, because they are close to WASD, which is more convenient. Function keys are inconvenient to hit, but the minimap and camera keys are far too important to be "hidden" behind the function keys. Part of a good game design is to provide good and sane defaults for the controls. It's not just about "personal preference". The arguments against that change have not convinced me. 

> X, C & V shouldn't be used for anything other than copy / paste functions.

That argument is invalid because the context in which the C and V keys are relevant when you're playing, and there is no focus on any text field. My change did NOT break copy+paste in Minetest. Copy+Paste shortcuts still work perfectly well.

> imo, changing this keybind was dumb and never should have happened

That's not an argument.

> also see #10678 as a another example of people not liking it

Nothing in this issue indicates that the people did not like the change.

----

Obviously changing the default keys will temporarily confuse long-term players, that's an inevitability. If you use that argument, we wouldn't be able to change any default key bindings ever. Also note that both minimap and camera keys are re-bindable in the keys menu, so if anyone wants F7 back, they can do so.

The actual mistake was that this change was not announced prominently in the release notes or the News thread, since that one was easy to overlook. Next time a default key binding is changed, this should be taken into account. (But note I don't think another default key change is neccessary in the near future.)
That was the reason why people got confused.

**Comment by Wuzzy2** [comment]
To elaborate more on the C/V vs F7/F9 thing in more detail: You can hit C/V easily with your left hand (the "WASD hand") without moving it away, you just need to use your fingers.

But to hit F7/F9, you have to awkwardly move your "WASD hand" away from this part of the keyboard, especially since F7/F9 are more "to the right". Might not be true for *literally all* keyboards, but it's a rule of thumb.

Therefore, I stand by C/V.

**Comment by lhofhansl** [comment]
Wah? Why? What's wrong with the current keys?

**Comment by samarth-ramesh** [comment]
> Wah? Why? What's wrong with the current keys (C/V)?

They get in the way. The c/v keys are imo located at a prime location that can be bettter used. How often do you change your PoV while playing? 

> You can hit C/V easily with your left hand (the "WASD hand") without moving it away, you just need to use your fingers.

The idea is to make *slightly* less easy to change your PoV. It is imho not a very commonly toggled feature

**Comment by v-rob** [comment]
An argument can be made for multiple things: I think nearly all people use inventory more than changing the minimap and definitely third person mode, but it's mapped to the very far away `I` by default, so I set it to `Q`.  `Q` defaults to dropping items, but how many people do that on a regular basis?  I myself use `C` and `V` for toggling fly and noclip, respectively, because I use those a lot when playing creative.

It's difficult to argue preference, though.  Minetest's keybindings make little sense to me, but they're configurable, so whatever.

**Comment by lhofhansl** [comment]
Since it's configurable anyway, let's close this one please.

**Pull request closed without merging**
