### PR TITLE
[CSM] Add minimap API modifiers

### PR DESCRIPTION
**Pull request by nerzhul**
* Rename Mapper (too generic) to Minimap
* Add lua functions to get/set position, angle, mode for minimap
* Client: rename m_mapper to m_minimap
* Add minimap to core.ui namespace (core.ui.minimap)
* Add various functions to manage minimap (show, hide, toggle_shape)
* Cleanup trivial declaration in client

Note: this is a WIP, API is not linked with client at this moment, we just have the global design

### CODE REVIEW

**Comment by octacian** [comment]
It would be good to be able to also set the size of the minimap. I assume that by position you mean the ability to move it to a different place on the screen. Also, the ability to actually hide/show it in Lua as these features combined would allow for something like a map to be displayed when you had a map in hand.

**Comment by Fixer-007** [comment]
yeah, changing size is also good to have

**Comment by nerzhul** [comment]
It's now finished

**Comment by nerzhul** [comment]
@octacian i looked at the size, it's not simple to change it, i propose to let this idea for later for somebody who wants to refactor the minimap code to make it possible

**Comment by sofar** [comment]
:+1:, and yes, size should be added as well. On my 2560x1600 monitor, it's terribly small :)

good patch.

**Pull request merged**
