### PR TITLE
Re-enable texture pre-filters on wielditems, fixing #3178.

### PR DESCRIPTION
**Pull request by Warr1024**

### CODE REVIEW

**Comment by paramat** [comment]
@RealBadAngel any comment on this since it reverts a change you made in your commit? https://github.com/minetest/minetest/commit/60350699c792b816b20704d59cfbda0894cdba39

**Comment by est31** [comment]
#3178

**Comment by BlockMen** [comment]
:+1:

**Comment by RealBadAngel** [comment]
its ok

**Comment by est31** [comment]
And merged 900db310638531a8b9fb1a587f75a02a15ae0c24

**Pull request closed without merging**
