### PR TITLE
Remove mod_translation_updater.py and move it to minetest/modtools

### LINKED ISSUE #14495: Move mod_translation_updater.py to another repo (minetest/modtools)
I don't think that mod_translater_updater should have been added to this repo. It's out of place and is causing issues here.

* mod_translater_updater.py has had a few ~~bugs~~ teething issues, moving it to another repo would give space for unit tests. Distros could still install the mod tools script if they wished, in the same way they used to bundle minetest game
* another repo would give space for adding multiple python files, which would allow code reuse with other scripts
* another repo makes it much easier to get this script without having to download all of minetest
* Issues would be filed on the script's repo, not the engine repo
* Reviews could be done separately to the engine. There's no reason why we couldn't give a few interested modders write access here

This repo could be `minetest/translation_tools` or it could be a more general `minetest/modtools`, containing a single entry point that allowed running different scripts:

* extracting translations
* converting between po and tr
* validating translation files
* updating mod.conf files (from depends.txt for example)
* finding deprecated methods etc using semgrep

### PR DESCRIPTION
**Pull request by Zughy**
Closes #14495. Repo can be found here: https://github.com/minetest/modtools

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

**Comment by SmallJoker** [comment]
Why? This basically reverts https://github.com/minetest/minetest/pull/13739

**Comment by Zughy** [comment]
It doesn't, the script remains under the Minetest umbrella. There has already been a discussion in the issue I've linked and I've done exactly what the concept approved issue said: discussing this further will only bring to some bikeshedding; and, to be clear, I won't tolerate that yet again

**Comment by Zughy** [comment]
> The issue does indeed not state where the script should be put

Literally the title. Also, last lines of the first message

**Review by JosiahWI — APPROVED** [review]
Confirmed with `diff` that the moved files are the same between the two repositories.

**Comment by SmallJoker** [comment]
@Zughy 

> Literally the title. Also, last lines of the first message

Sorry. I don't understand what you mean. I was referring to #10852, which I initially misinterpreted.

**Comment by Wuzzy2** [comment]
I approve since the script is still under the Minetest organization.

Whether the script is directly in the Minetest repo, or in a Minetest-adjacent repo, I don't care.

**Pull request merged**
