### PR TITLE
Main menu style: Set to 'full' for Android, remove 'auto' option

### PR DESCRIPTION
**Pull request by paramat**
Initial work for #2600 
See comments of support https://github.com/minetest/minetest/issues/2600#issuecomment-134766359 and https://github.com/minetest/minetest/issues/2600#issuecomment-443699377
I can also remove simple menu code if or when full menu is confirmed ok for all Android devices.

### CODE REVIEW

**Comment by stujones11** [comment]
While I agree that additional worlds and sub game selection should be possible on mobile devices, I think this is an over-simplistic solution. Since the gui scaling improvements, the full menu is indeed useable but game header is truncated and pushed behind the form. Also note that the game selection bar is not part of the lua main menu so does not get compensated for scale. It does, however _just_ fit on my screen which is pretty wide aspect 2:1

screen

I would personally favour keeping the simple menu for mobile, except include an additional tab for game and world selection. At the very least, I think we need to do something about the background image.

**Comment by rubenwardy** [comment]
I suggest removing the game selection bar on Android, and flipping the "start game" form to have the list and 3 buttons on the left, and checks on the right

**Comment by rubenwardy** [comment]
Unfortunately this would be harder than I expected, due to the fields added by host server

> flipping the "start game" form to have the list and 3 buttons on the left, and checks on the right

I've done the first section though, in #7940. It also hides the header

**Comment by stujones11** [comment]
> I've done the first section though, in #7940. It also hides the header

In that case I don't see a problem with this :+1:

**Comment by paramat** [comment]
The simple menus for Android add a lot of code though, better to remove that and have PC and Android being as similar as possible.

**Comment by paramat** [comment]
Actually not WIP. I can remove simple menu code in a separate PR (probably best).

**Pull request merged**
