### PR TITLE
Introduce "access" map protection bypass priv.

### PR DESCRIPTION
**Pull request by sofar**
This privilege allows map protection bypassing for server operators
and world moderators.

Initially I had thought that bypassing protection mods would have been
something that could entirely be done inside mods and minetest_game,
but the concept of protection is defined in core, in the code of
core.is_protected().

I don't feel that it would be logical to introduce a protection
concept in core, but not some way around that for server operators
to maintain map parts that need fixing, ungriefing or cleanup.

Others had noticed the same problems, and proposed a patch to
minetest_game. That patch is fine by itself, but it fails to add
protection bypass functionality for digging normal nodes and placing
nodes.

So, instead, we indroduce the new priv "access" in core, and modify
'on_place_node' and 'node_dig' to allow bypassing node protections
if the player holds this priv.

Tested with protector redo by tenplus1.

A followup patch to Minetest Game will include allowing special checks
for doors, trapdoors, chests in Minetest Game.

Protection mods will likely want to mimic the changes in their relevant
code sections.

### CODE REVIEW

**Comment by sofar** [comment]
related: https://github.com/minetest/minetest_game/pull/602

**Comment by sofar** [comment]
Related minetest game patch: https://github.com/minetest/minetest_game/issues/881

**Comment by est31** [comment]
The naming is a bit bad, otherwise okay with me.

I'd go with something like `protection_bypass`, `protection-bypass` or something.

**Comment by sofar** [comment]
I'd strongly want to avoid long or complex names for this, especially no characters like ```-``` or ```_``` characters.

I agree that access isn't ideal, since that doesn't really catch everything. But I'm drawing a blank (even asked my wife) on a better term, and one that isn't 15+ characters. Landlord? Janitor? Housekeeping?

**Comment by est31** [comment]
Well, access is so general that a naive and new server admin can think that they need to give this priv to new players so that they can access the map (=play).

**Comment by 0-afflatus** [comment]
`protection_bypass` is self-explanatory. Does the length matter?

**Comment by est31** [comment]
> Does the length matter?

I think so

**Comment by 0-afflatus** [comment]
`unlock` ?

**Comment by C1ffisme** [comment]
@0-afflatus `unlock` sounds more like the privilege to turn locked items into unlocked items, rather than access them. But I'm sure it won't cause too much confusion.

**Comment by red-001** [comment]
@0-afflatus The privilege allows placing and digging nodes `unlock` doesn't make a lot if sense for that.

**Comment by sofar** [comment]
I'm OK changing this to ```protection_bypass```, there already is a permission with an underscore (basic_privs) so let's standardize on underscores instead of hyphens.

**Comment by sofar** [comment]
Renamed to ```protection_bypass```

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
Yes a more descriptive name is good.

**Comment by Ekdohibs** [comment]
:+1:

**Comment by sofar** [comment]
two approvals, @paramat - merge this before 0.4.14? That would allow merging of https://github.com/minetest/minetest_game/pull/881 as well (assuming you'd approve that one to get the two approvals.)

**Comment by est31** [comment]
I'm redacting my :+1: and think its better left to the protection mods to add such privs.

**Comment by sofar** [comment]
With a rewrite of the is_protected() api, this could indeed entirely be done in a mod.

**Comment by est31** [comment]
well the thing is, every mod that uses minetest.is_protected would have to add an "and not has protection_bypass" priv, that's a bad design.

:-1:  even.

I do agree that an overhaul of the protection API design is required, but we need to do it in a way thats most backwards compatible.

**Comment by sofar** [comment]
sadly, I don't see how a redesign of the protection API could be backwards compatible.

**Comment by est31** [comment]
It can be done, with some extensions... we would need to add a file between_mod_loads.lua or something like that to builtin/game which gets executed like the name sais between mod loads. It looks for whether the minetest.is_protected function got changed, and if it did it adds that function to the new API.

Perhaps we dont need a fully new file for that, its enough to call minetest.after_mod_load or sth.

**Comment by est31** [comment]
Okay, I think this can go in, but should only be temporary. See #3833 for the mid to long term discussion.

**Comment by paramat** [comment]
f627ef39e038089d977f4f671b11cd357b1dcd70

**Pull request closed without merging**
