### PR TITLE
Simplify Readme build steps

### PR DESCRIPTION
**Pull request by est31**
See disussion http://irc.minetest.ru/minetest/2014-09-22#i_3940514

### CODE REVIEW

**Comment by ShadowNinja** [comment]
I don't think git should be counted as a dependency.  The git way should be mentioned, but it shouldn't be shown as the only way.

**Comment by JakubVanek** [comment]
I think that you could also somehow add --depth 1 to git since the tarball doesn't contain .git at all.

**Comment by est31** [comment]
@JakubVanek `--depth 1` sounds good,  difference between a copy with history and a shallow one is 22 MiB thats alot. @ShadowNinja most people working with source will want to keep it updated. But I'll do two versions.

**Comment by sfan5** [comment]
There is also a new tarball url https://github.com/minetest/minetest/archive/master.tar.gz that uses the directory name `minetest-master` instead of `minetest-minetest-<commit id>`.
Can you change the instructions for minetest and minetest_game to reflect this change?

**Comment by est31** [comment]
The list of packages to install in the line above differs from the output of`apt-rdepends --build-depends --follow=DEPENDS minetest`. What do you think, should I change the list accordingly? The README list has these elements which apt doesn't:

* libbz2-dev
* libpng12-dev
* libjpeg8-dev
* libxxf86vm-dev
* libgl1-mesa-dev

It however misses these elements:

* imagemagick
* libjsoncpp-dev
* libleveldb-dev
* liblua5.1-dev
* libluajit-5.1-dev
* zlib1g-dev

And, I think, luajit is a must-have.

**Comment by PilzAdam** [comment]
@est31 leveldb is optional, Lua is not necessarily needed, since we bundle it in our source tree. LuaJIT is optional, so not a must have (also IIRC there are some platforms that don't support LuaJIT?).

**Comment by est31** [comment]
What about the other libs? What about those not appearing in the apt-rdepends list?

**Comment by Zeno-** [comment]
+1

**Comment by celeron55** [comment]
Suggesting usage of git in the documentation is a reasonable idea.

@est31:

libjsoncpp-dev - Might be optional (is it?), but it is required for the serverlist and modstore functionalities. So, practically everyone will want it.

zlib1g-dev - Is this the package name for zlib-dev for some reason? Zlib is needed for sure.

Libraries for additional functionality:
    imagemagick (dunno what this does here)
    libleveldb-dev (leveldb support; rarely needed)
    liblua5.1-dev (minetest uses a bundled one if this is not installed)
    libluajit-5.1-dev (for better performance)

Things that some variant or version of debian happens to need for the build while others don't. Seems to be some kind of things related to Irrlicht:
    libbz2-dev
    libpng12-dev
    libjpeg8-dev
    libxxf86vm-dev
    libgl1-mesa-dev

**Comment by celeron55** [comment]
da8199799db9981e6e34f34efa0abb9db16e5f0a

**Comment by sfan5** [comment]
> liblua5.1-dev (minetest uses a bundled one if this is not installed)

Minetest actually does not even try to use system-wide Lua libraries, if you set `LUA_LIBRARY` and `LUA_INCLUDE_DIR` CMake will fail because it expects LuaJIT.

**Pull request closed without merging**
