### PR TITLE
Try to fix build with gettext enabled

### PR DESCRIPTION
**Pull request by est31**
Reported by @Wuzzy2 (log excerpt here: http://lpaste.net/raw/349909). The build fails if gettext is enabled. Some mistake by weblate?

This PR is untested therefore the "try" in the title. Please test before merging.

### CODE REVIEW

**Comment by nerzhul** [comment]
As it blocks every builds, release including it's a blocker.

**Comment by Fixer-007** [comment]
I can confirm, I have the same errors.

**Comment by est31** [comment]
@Fixer-007 can you try again?

**Comment by Fixer-007** [comment]
successfuly compiled without msgfmt errors. log: http://pastebin.com/raw/snfCqdDq

**Comment by est31** [comment]
0614da3afffb7657452ef4ca8c1f2e1e82067f86

**Pull request closed without merging**
