### PR TITLE
Add disable_descend group to disable active descend in climbable or liquid node

### LINKED ISSUE #11452: Allow to disable descending in climbable or liquid nodes
This is a feature request.

## The situation
Currently, we have `disable_jump` which also disables climbing/swimming upwards in climbable nodes and liquids.

However, there is no such counterpart for the *downwards* direction. This feels like an awkward asymmetry.

## Solution
I suggest to add a new feature to nodes that disables the descending in climbable nodes and liquids. That is, if a node disables descending, pressing the Sneak key while in one of those nodes will do nothing. So this is analogous to how `disable_jump` works for climbable/liquid nodes right now, just for the other direction.

## Implementation

This feature request is fully implemented in #11377. Please give it a review, thanks! <3

### PR DESCRIPTION
**Pull request by Wuzzy2**
Fixes #11452

This PR adds the group `disable_descend` to disable players from *actively* climbing down / moving down in climbable or liquid nodes when you hit the Sneak/Aux1 key.

This is the logical counterpart to `disable_jump`, which disables climbing/moving upwards instead. I thought it was strange you could disable climbing upwards, but the other way.

## How to test

Check out the new climbable nodes in DevTest.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed. These PRs can also have preapproval if they fix an issue that is concept approved

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label

**Comment by Wuzzy2** [comment]
What a great way to discourage community members from contributing ever to Minetest again! Nobody even looked at this PR and it is already dead. Contributing to Minetest is so frustrating.

To be honest, this is a really shitty policy. Unless your goal is to get the number of contributors down to 0 as fast as possible.

**Comment by SmallJoker** [comment]
Well actually this is a very simple implementation and might open up some new possibilities for ITB-style puzzles.

**Comment by Wuzzy2** [comment]
Thank you, SmallJoker. Does this count as a concept approval? If yes, then please add the "supported by core dev label".

**Comment by Wuzzy2** [comment]
Bump.

**Comment by SmallJoker** [comment]
Needs rebase.

**Comment by Wuzzy2** [comment]
Rebased.

These are the DevTest nodes to test:

* `testnodes:liquid_nodescend` (new)
* `testnodes:climbable_nodescend` (new)
* `testnodes:liquid_nojump`
* `testnodes:climbable`
* `testnodes:climbable_nojump`
* `testnodes:climbable_move_resistance_4`

**Comment by Wuzzy2** [comment]
Fixes #11452.

(posted to force a link to appear at that issue)

**Comment by Zughy** [comment]
@Wuzzy2 rebase needed

**Comment by Wuzzy2** [comment]
Rebase completed. I have no right to remove the label.

**Comment by SmallJoker** [comment]
Checked my pending reviews and I seem to totally have forgotten about this one.
Sorry - apparently the PR needs a rebase again.

**Comment by Wuzzy2** [comment]
Rebase completed.

**Review by SmallJoker — APPROVED** [review]
Works

**Review by Desour — APPROVED** [review]
Tested, works. LGTM. :+1:

**Pull request merged**
