### PR TITLE
Add player sprite textures back into the engine as a fallback

### PR DESCRIPTION
**Pull request by paramat**
'player.png' and 'player_back.png' are hardcoded into the engine as
the default appearence of the player object, so the textures should
be present in the engine.
This results in a functional fallback sprite player for when a game
has no player appearence related code.
////////////////////////////

PRnoplayerapi

^ PR using MTG with player_api mod removed, player is functional

masternoplayerapi

^ Master branch using MTG with player_api mod removed, error message and dummy textures (pink monolith!)

Textures are hardcoded into the engine here:
https://github.com/minetest/minetest/blob/86d7f84b899a507e979f1845f2057cce6f84e743/src/content_sao.cpp#L879

How to test:
Use MTG with player_api mod removed.

This should be merged whether or not these textures are removed from the MTG player_api mod.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Counter-proposition: CC0 (me), looks better in case anyone wonders what this alien is.

player
player_back

**Comment by paramat** [comment]
I'd be happy to use an improved texture in this PR if core devs prefer.
SmallJoker i'll use those textures if you'll then +1
I'm not sure what documentation is needed? It seems already present:
https://github.com/minetest/minetest/blob/03f89e8ffca84e2ff2f6cea8dcee49b067280cc4/doc/texture_packs.txt#L86

**Comment by benrob0329** [comment]
I'd prefer the old textures for historical reasons, it's just the fallback and games can easily override it.

**Comment by SmallJoker** [comment]
@paramat I support moving the textures in either way. Mine were a suggestion to add a more detailed version rather than the alien.
The origin and license should be noted in https://github.com/minetest/minetest/blob/master/LICENSE.txt#L14

**Comment by paramat** [comment]
Credit and license for c55's textures are already present:
https://github.com/minetest/minetest/blob/b8131c3415ee8811ab98b537c080d203d8bee774/LICENSE.txt#L16-L17

Actually i prefer to use the classic textures because this engine fallback is intended to be identical to and replace the sprite fallback i want to remove from the MTG player_api mod.
So this PR seems ready.

**Comment by SmallJoker** [comment]
Feel free to merge this PR. Note that I won't approve the player_api-crippling PR in MTG.

**Comment by paramat** [comment]
Thanks.

However you misunderstand if you think player_api wil be 'crippled' by my proposed PR. Servers that use the sprite for players will now fallback to the engine sprite default so there will be no change of behaviour, that is my intent. I will open a PR soon that explains.

**Pull request merged**
