### PR TITLE
Keyboard shortcuts for chat commands

### PR DESCRIPTION
**Pull request by celeron55**
Continues spillz's work from #2445.

### CODE REVIEW

**Comment by celeron55** [comment]
I think this is ready to go, but this should be tested by more people.

**Comment by Fixer-007** [comment]
I will look at it.

**Comment by ObaniGemini** [comment]
\o/

**Comment by Fixer-007** [comment]
* It does not show warning when I assign command to some key, that is already assigned but not in keybindings menu, for example, 
Home
End
Page Up
Page Down
That keys change quicktune settings

* You can't use modificators on already assigned keys, for example:
Ctrl + Q
Shift + Q
Ctrl + Shift + Q
... will still show warning about Drop and even without that you can press Ctrl+Q and that will drop the item.

* Alt can't be used as modificator with other keys, Alt+Q is not possible, simple Alt still works, though.

* Ctrl-Shift-KEY will work as: Ctrl-KEY or Ctrl-Shift-Key

* Bizarre hotkeys possible: Ctrl+Left Control or Ctrl+Shift+Left Shift 0_o

**Comment by celeron55** [comment]
Personally I consider it a nice extra that this thing even got any combinations working; I was expecting it to not support any combinations. Anyway, if somebody wants to fix some of those issues, feel free to.

**Comment by ObaniGemini** [comment]
What's up with it ?

**Comment by rubenwardy** [comment]
The input system needs a clean up IMO, so I'd rather not add any more complexity

**Comment by AntonBoch1244** [comment]
need rebase mb.

**Comment by paramat** [comment]
I don't think this is worth doing :-1:

**Pull request closed without merging**
