### PR TITLE
Brighter sunrise and sunset

### PR DESCRIPTION
**Pull request by UgnilJoZ**
The sunrises are way too dark. Hope this doesn't break other stuff.

### CODE REVIEW

**Comment by paramat** [comment]
How it is currently seems okay to me but i'll check this in-game. I'm concerned that changing 'nightlength' affects other things, this may not be the way to do it.

**Comment by sofar** [comment]
I'm with paramat on this one. dusk/dawn look good to me.

**Comment by UgnilJoZ** [comment]
Changing the nightlength seemed the "simplest" way of doing this.
I do also like atmospheric twilight, but it seems to me it is too late on sunrise and too early on sunset causing the sky beeing too dark.

But I should have opened an issue first to ensure if this is seen the same way by others ;)

**Comment by sofar** [comment]
FYI I have no problems discussion ideas with the actual patch set submitted as PR, and I don't think other developers disagree. Given this is a one-liner, the best discussion is one where people can see the simplicity of the patch, so feel free to submit PR's directly in lieu of issue reports I'd say.

**Pull request closed without merging**
