### PR TITLE
Re-fix CAO mesh lighting with shaders disabled

### LINKED ISSUE #15397: All CAO models share the same lighting with shaders disabled
### Luanti version

Latest master (https://github.com/minetest/minetest/commit/60cd1e452957e2e924eedf9de6b46f6eb7833ccc).

Bisected to https://github.com/minetest/minetest/commit/65af606729f7e3c162bf0b77a02570697f784c66.

### Irrlicht device

SDL

### Operating system and version

Fedora 40

### CPU model

AMD Ryzen 5 3500U

### GPU model

AMD Radeon Vega 11 (integrated graphics)

### Active renderer

OpenGL 4.6.0 (Compatibility Profile), Mesa 24.1.4

### Summary

If you disable shaders, all entities are lit the same. This is particularly noticeable if you play on a crowded server like CTF: Other players will flicker.

I assume this is because of the shared mutable model light values: All entities which share the same model write to those, and whichever CAO happens to write last "wins"; all other ones will be lit wrongly. 

### Steps to reproduce

1. Disable shaders, maybe also set your video driver to `opengl`.
2. Place a maximum strength light source node.
3. Set `/time 0`.
4. Spawn one `testentities:mesh` next to the light source node, another one further afar.

The two meshes should be lit differently: One should be noticeably darker than the other. If they are lit the same, the bug is present. For me this often leads to the mesh which should be lit being darker (assuming it was spawned first):

Screenshot from 2024-11-07 20-31-08

but the other way around is also possible (I assume this probably depends on object IDs since we're using a sorted map).

### Fixing this

I believe this problem stems from the fact that all entities share the same meshes from the mesh cache, and hence share the same vertices and colors. Since all of this code runs in a step *before* all the drawcalls are run, only the last set colors are applied. Copying meshes could be considered but I am for multiple reasons, including performance, not a fan of this idea. An alternative would be to set the vertex colors in Irrlicht code, right at draw time.

I would have proposed the following patch to fix this by using the fixed lighting again (what exactly are the platform-specific problems with this?), to be applied directly after the bisected commit:

<details>

```diff
diff --git a/src/client/content_cao.cpp b/src/client/content_cao.cpp
index 5a8e1222f..042f97e4e 100644
--- a/src/client/content_cao.cpp
+++ b/src/client/content_cao.cpp
@@ -757,7 +757,7 @@ void GenericCAO::addToScene(ITextureSource *tsrc, scene::ISceneManager *smgr)
 			m_animated_meshnode->setScale(m_prop.visual_size);
 
 			// set vertex colors to ensure alpha is set
-			setMeshColor(m_animated_meshnode->getMesh(), video::SColor(0xFFFFFFFF));
+			setEmissiveColor(m_animated_meshnode, video::SColor(0xFFFFFFFF));
 
 			setSceneNodeMaterials(m_animated_meshnode);
 
@@ -921,9 +921,9 @@ void GenericCAO::setNodeLight(const video::SColor &light_color)
 		// instead of mutating meshes / buffers for everyone via setMeshColor.
 		// (Note: There are a couple more places here where setMeshColor is used.)
 		if (m_meshnode) {
-			setMeshColor(m_meshnode->getMesh(), light_color);
+			setEmissiveColor(m_meshnode, light_color);
 		} else if (m_animated_meshnode) {
-			setMeshColor(m_animated_meshnode->getMesh(), light_color);
+			setEmissiveColor(m_animated_meshnode, light_color);
 		} else if (m_spritenode) {
 			m_spritenode->setColor(light_color);
 		}
@@ -1376,6 +1376,7 @@ void GenericCAO::updateTextures(std::string mod)
 				material.MaterialType = m_material_type;
 				material.MaterialTypeParam = m_material_type_param;
 				material.TextureLayers[0].Texture = texture;
+				material.Lighting = true;
 				material.BackfaceCulling = m_prop.backface_culling;
 
 				// don't filter low-res textures, makes them look blurry
```

</details>

However it's not as trivial now that the `SMaterial::Lighting` field doesn't exist anymore. We would have to partially undo https://github.com/minetest/minetest/pull/15165.

It would be especially nice if we could get rid of `setMeshColor` here more generally, because then the workaround in https://github.com/minetest/minetest/commit/3064f3ccb769df03ef693bf8ce464481a627512a would become obsolete. It also sucks to be iterating all vertices on the CPU and then having to send that data to the GPU.

### PR DESCRIPTION
**Pull request by sfan5**
fixes #15397

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Tested on Linux (non-SDL)

:ballot_box_with_check: shaders off: The entities have correct lighting
:ballot_box_with_check: shaders on: The entities have correct lighting

Tested with the devtest mesh entity. upright sprites work too (tested just in case).

**Comment by appgurueu** [comment]
I think this should get a `// HACK` or `// FIXME` since the implications of this e.g. in terms of memory usage aren't great (but it should be acceptable given we don't handle large numbers of entities very well anyways).

**Comment by sfan5** [comment]
I opted not to add one because this code will be deleted right after 5.10 anyway.

**Review by appgurueu — COMMENTED** [review]
Tested, works. A quick estimate suggests that the additional memory usage should be tolerable.

I looked into `m_client->getMesh` and if I understand it correctly, setting `cache = false` will cause it to remove the mesh from the cache, hence it will be reloaded from file every time rather than cloned in memory. Is this intended, and if so, why is it acceptable?

**Comment by sfan5** [comment]
> hence it will be reloaded from file every time rather than cloned in memory. Is this intended, and if so, why is it acceptable?

Yes, that's equivalent. It seems we generally re-read meshes rather than clone them.
Is that a problem?

**Comment by appgurueu** [comment]
> Is that a problem?

It feels even dirtier than just cloning meshes, and it seems potentially problematic to me that when, say, a hundred entities are spawned, you get a hundred model reads. I could imagine this to cause e.g. frame stutter. I have not demonstrated that it does cause problems in practice, though.

**Comment by sfan5** [comment]
I once experimented on that (#11652) and model formats were at least more memory-efficient than raw vertices. Dunno about latency.
Yet how the "do not cache meshes" stuff works is not directly related to this fix.

**Pull request merged**
