### PR TITLE
Delete OpenGL ES 1.0 driver

### PR DESCRIPTION
**Pull request by sfan5**
I wanted to work on stuff and this is in the way sooner than expected.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Would migration code for `video_driver` make sense? If that setting is present on smartphones, it would be very annoying for them to correct it.

**Comment by sfan5** [comment]
if you have an invalid video driver it will automatically try available ones, so that should be fine.

**Review by SmallJoker — APPROVED** [review]
LGTM.

**Review by grorp — APPROVED** [review]
Looks good. The only leftover mention of the deleted driver I found via a quick grep is in `doc/android.md`, you could remove that.

**Pull request merged**
