### PR TITLE
Fix 'Download complete' dialog in the mods store

### PR DESCRIPTION
**Pull request by ngosang**
This patch fix the 'Download complete' dialog in the mods store and also removes several warnings from the store.

### CODE REVIEW

**Comment by ngosang** [comment]
Related with #2071. This fix solves that problem too.

**Comment by JakubVanek** [comment]
Because this PR includes almost everything from my PR, I am going to close my PR and here is remaining diff:
```
diff --git a/builtin/mainmenu/store.lua b/builtin/mainmenu/store.lua
index f0ddfce..b46c00d 100644
--- a/builtin/mainmenu/store.lua
+++ b/builtin/mainmenu/store.lua
@@ -122,9 +122,7 @@ end
 function modstore.showdownloading(title)
 	local new_dlg = dialog_create("store_downloading",
 		function(data)
-			return "size[6,2]label[0.25,0.75;" .. fgettext("Downloading") ..
-				" " .. data.title .. " " ..
-				fgettext("please wait...") .. "]"
+			return "size[6,2]label[0.25,0.75;" .. fgettext("Downloading $1, please wait...", data.title) .. "]"
 		end,
 		function(this,fields)
 			if fields["btn_hidden_close_download"] ~= nil then

```

**Comment by ngosang** [comment]
@JakubVanek I added your change.

**Comment by ngosang** [comment]
@JakubVanek I added your change.

**Pull request closed without merging**
