### PR TITLE
Android buttons: Inset 'rare controls', inset and resize 'gear icon' 

### PR DESCRIPTION
**Pull request by paramat**
Previously these were both inconsistently close to the screen edge.
'gear icon' has been enlarged to match the width of 'zoom' and 'aux'
buttons.
/////////////////////////////

I can't test this so no screenshot.

whatsapp image 2018-10-15 at 20 46 38 5

^ MT master

Previously these 2 buttons were too close to screen edge, inconsistent with other buttons and might be problematic when using a case. This PR also cleans up horrible codestyle.
Any testing welcome.

### CODE REVIEW

**Comment by stujones11** [comment]
Look okay for me
screen
Ignore the git-hash, I just applied the change to an existing build.

**Comment by SmallJoker** [comment]
That's now already much easier to use. To make it look a bit better, center the "rare controls" button so that it's on the same vertical line as the zoom and aux buttons.

**Comment by stujones11** [comment]
> To make it look a bit better, center the "rare controls" button

I personally think the gear button is too small compared to the other buttons. I would suggest that by increasing the size, it would naturally have the alignment.

**Comment by paramat** [comment]
Thanks for testing. The gear icon has no space around it in the texture frame https://github.com/minetest/minetest/blob/master/textures/base/pack/gear_icon.png so it will still need indenting.
I'll enlarge it to match the zoom and AUX buttons in width.

I'd rather not move the rare controls button in any further as it would intrude too much on the joystick. Also, all buttons have their outer edges aligned, not their centres.

**Comment by paramat** [comment]
Updated.

The gear icon texture has changed from 64x128 to 128x128, so the X insets of each side from screen edge are now (1.25 * button_size) and (0.25 * button_size) just like 'zoom' and 'aux'.
The gear image itself has been enlarged to be equal in width to the 'zoom' magnifying glass image.
As explained above i have left 'rare controls' as it is.

Any retesting much appreciated.

**Comment by stujones11** [comment]
Here's how it looks now

screen

LGTM :+1:

**Comment by paramat** [comment]
Thanks for testing.

**Pull request merged**
