### PR TITLE
CSM Events and Drawing Testing

### PR DESCRIPTION
**Pull request by v-rob**
Edit: This draft has since lost a sense of direction, and not everything pertains to the UI.  See this post:
> As a heads up: this draft PR is sort of turning into a big playground for messing around with drawing and textures and whatnot. It will definitely be split into many PRs, not all directly related to UI stuff. So don't be surprised if you see some weird commits with stuff that only seems superficially related to UI. (Most will be related, just some won't be). I'm still going to leave it open so everyone can see what's going on, but in no way will this ever be a real PR all together in one.

Accordingly, I'm removing the TODO list as the one I have is too long to keep updated here.  To look at what's going on, look at  [`client_lua_api.txt`](https://github.com/minetest/minetest/pull/10524/files#diff-245ed7e88224417a6c0be3a6a4bd85ca275fa9719e5a4928636f8f5fc77bab98) which has many things that have been added and others that will be added.

<details><summary><b>Old direction (and will be the direction for some of the UI PRs this will be split up into):</b></summary>

This draft PR adds a CSM API for drawing to the screen and receiving events from input devices like keyboard and mouse.  This is the essential prerequisite to a Lua-side GUI which is what I intend to replace formspecs with (see https://github.com/minetest/minetest/issues/6527#issuecomment-698646731 and onwards and https://forum.minetest.net/viewtopic.php?f=7&p=382529#p382529).  The main intent is for GUI and HUD replacement, not CSM, and so it may be isolated in some other part of builtin so that it can be loaded regardless of whether CSM is enabled or not.  According to my extensive testing (I didn't profile in milliseconds, but watched the framerate closely with a variety of tests), it is performant enough on both LuaJIT and plain Lua because it is practically no slower than equivalent formspecs.
</details>

## To do

This PR is a playground Work in Progress.  It will be split up into many PRs and closed after I've gotten enough finished.

Things I would like help with:
* How to draw a line?  `driver->draw2DLine` does not clip to a rect and I'm not certain if there's a good way to set the thickness.  Same goes for drawing other shapes, like circles or irregular filled polygons.
* How can I get touchscreen events working on non-Android systems?  Would be a very nice feature

I don't want to explain every single design choice here because that would take forever, but don't hesitate to ask questions about anything.

I'm quite open to suggestions and criticism.

### CODE REVIEW

**Comment by sorcerykid** [comment]
This all looks very promising! I'm very excited about the prospects of this new framework. Based on the description, I suspect it may address some of the feature requests that I had planned to submit awhile back:

**Popup Formspecs**
Popup formspecs would be ideally suited for displaying an ephemeral, non-modal GUI on the screen where the permanence of a HUD is not required. A simple use-case would be implementing Windows 10 style notifications in Minetest Game so that users could be alerted of certain game-related events on-the-fly. The following  non-interactive formspec elements would be supported: background[], background9[], image[], item_image[], animated_image[], hypertext[], box[], label[], vertlabel[].

**Formspec Page Transitions**
Minetest currently lacks support for animating the opening, closing, and updating of formspecs, resulting in a GUI that at times is far too abrupt. The introduction of page transitions would allow for a much more fluid presentation of graphical content in-game between state changes including but not limited to fade, dissolve, wipe_left, slide_up, square_in, circle_out.

**Full HUD Replacement**
I believe that Minetest's HUD, in its current form, is far too archaic and obtuse to remain viable in the long term, at least for serious game development. Consider, for example, the sheer complexity of updating a basic graphical leaderboard on the side of the screen. The entire API needs to be completely re-invented from the ground up if Minetest is to remain at all relevant in comparison to the myriad of other engines which offer a more feature-rich HUD.

NB: I wrote these proposals in the context of the current formspec API. So naturally, they would need to be adapted for this new framework. But I at least wanted to present what I had brainstormed thus far for your consideration. I think all three are absolutely worthy candidates for a next generation, CSM-based approach to the Minetest GUI.

**Comment by paramat** [comment]
This is interesting and good to see, but it is uncertain whether SSCSM will ever happen, or if it does it could be years away, it is already 3 years overdue.
In the recent roadmap brainstorm no core dev directly stated implementing SSCSM as a priority for the medium to long term, there were only indirect references to it.
IRC:
> 18:36 rubenwardy    I find it interesting that no one put SSCSM or CSM in their roadmap lists 👀
18:36 sfan5         too much work
18:36 Krock         CSM were a thing in 2017/18 and generally neglected now
18:37 Krock         not surprising IMO

SSCSM requires co-ordinated work by the most experienced core devs, but there is no indication of this happening in the short to medum term.

For each new CSM feature i think we need to first consider if it is justified knowing the uncertainty of SSCSM. Especially for large features such as this.
Is this still useful enough for Client-Provided CSM to be justified by only that? Of course, this assumes CPCSM is actually an official self-justified MT feature ('self-justified' meaning justified whether or not SSCSM happens).

I do not mind if the core devs collectively decide that CPCSM is now an official self-justified MT feature (even though that was never intended by anyone), but we are in a weird situation where we claim it is not, but continue to add new CSM features even though SSCSM is uncertain or at least years away.
If CPCSM is not intended to be an official self-justified feature, no new CSM features should be added until SSCSM is implemented, because they are only justified by SSCSM. New CSM features might be wasted effort, and they might make SSCSM more difficult to implement.
One of the original CSM devs, red-001, themselves halted CSM feature work because they considered more would just make SSCSM more difficult to implement.

I write this only because i am concerned it might be partially wasted effort. I feel some discussion is needed first.

I will open a separate issue related to this comment.

**Comment by v-rob** [comment]
@paramat 
This actually isn't designed with SSCSM or CSM in mind at all.  The idea is to make the GUI and HUD Lua-based instead of C++ based.  (I've discussed it in IRC a few times, I guess you haven't seen them).  My main reason is that I think that it will make development of them faster, less error-prone and laborious, and, if SSCSM ever happens sometime in the future, it will be completely extensible by Lua.

When the Lua-side GUI and HUD are created, then they will be loaded separately from the rest of CSM, so basically the API you see above and maybe one or two other things will be loaded.  So, it will still be Lua, but not CSM.

@sorcerykid 
I have a _lot_ of ideas for the new GUI/HUD.  The ones you have here, and quite a few more.  Layered GUIs are definitely in mind, and I've already resolved to replace the HUD based on the exact same code, so a `gui.Label` or whatever could just as easily be used on the HUD with all the same benefits.  Transistions and animations are a feature I've long wanted, but that will need a bit more drawing code than I've made at this point, and really someone with a little more expertise.  Sometime, after I gather my thoughts together, I'll write a post somewhere describing my thoughts.

**Comment by paramat** [comment]
v-rob, so are you saying that if SSCSM never happens this can be easily altered to be a formspec replacement?

Why not do this the other way around, code this to be independent of CSM and alter this if SSCSM is added?
Surely until SSCSM is implemented this is more useful being independent of CSM because it could actually be used? It seems useless as long as it is only usable by Client-Provided CSM which requires manual distribution of CSM mods to users.

**Comment by v-rob** [comment]
> v-rob, so are you saying that if SSCSM never happens this can be easily altered to be a formspec replacement?

A little more like the other way around: it was designed for the formspec replacement in the first place with SSCSM in mind as a future extension.  Currently this is in CSM because that was easiest to do (this is my first time working with C++ <-> Lua code), but it's going to have to be moved anyway, so yes, I suppose I can separate it from CSM in this PR.  If there are no objections, I'll put that in the checklist.

**Comment by paramat** [comment]
Well, wait for input from other core devs first, as i am not an expert in CSM and this area =)
I just needed some explanation of the overall approach of this in terms of CSM.

Also, i am unsure what the best approach is. I just had a thought that, until SSCSM happens, or if SSCSM never happens, this is actually still useable by having a CSMod built-in to the client? Is this the intention?

Because i am unsure i have no objections or requests currently, i will hide my earlier long comment as it was partially invalid and got sidetracked into another issue.

**Comment by Desour** [comment]
- Formspec and HUD implementation in lua would also need more functionality, like inventory interaction, a `register_on_screen_resize`, a `register_on_show_formspec`, preventing input events from being used by minetest (ie. mouse movement to camera movement) and more.
- Splitting this PR into drawing and event sounds like a good idea imo.
- Afaik there were plans to implement `ScreenDrawer` in lua by caching and sending everything to C++ at once. This PR doesn't seem to include this yet. Does it not increase performance or is performance good enough or what is the reason for this?

**Comment by v-rob** [comment]
> Afaik there were plans to implement ScreenDrawer in lua by caching and sending everything to C++ at once. This PR doesn't seem to include this yet. Does it not increase performance or is performance good enough or what is the reason for this?

After more testing, I found that caching and calling functions separately really has no difference, neither in Lua nor LuaJIT.  So, this is a lot nicer and more versatile as it's more interactive.  For instance, testing the color of a pixel is possible in this, but not in the batch call.

> Formspec and HUD implementation in lua would also need more functionality

Inventory interaction can come later.  Checking whether the screen resized is already possible with `ScreenDrawer:get_window_size` and comparing the difference from last frame.  Preventing input events is already planned for this PR, see the checklist where it says "Implement the ability to make events modal, i.e. take the cursor away from the game and allow it to be used externally like in formspecs, and allow changing the cursor."  The `register_on_formspec_input` will come much later after the new GUI has been created, and then the compatibility layer will be made.  So yeah, most of the things for the GUI specifically will come later.

> Splitting this PR into drawing and event sounds like a good idea imo.

Yes, it's getting kind of big.  I'm going to keep it in one PR for now so I can get everything done together.

**Comment by v-rob** [comment]
Possible future security issue: If we implement the Esc menu in Lua, what's to prevent a mod (either CPCSM or SSCSM) from overriding it somehow?  There are multiple avenues that this could happen through, like changing a global function or modifying a table entry containing event/drawing callbacks, and I don't think they can all be secured.  So, either we implement it in C++ or we allow modification but implement a universal exit-to-menu keyboard shortcut, or perhaps just Alt-F4.  Not especially fond of any of those, so ways to secure the `minetest.registered_on_draw/event` from being modified by mods would be appreciated.

**Comment by v-rob** [comment]
I am considering removing the `register_on_draw` callback as anything drawing to the screen ideally ought to be using the future GUI/HUD API instead of registering their own custom drawing which will likely conflict and overlay everything else.  `ScreenDrawer` wouldn't be changed, but will only be exposed in the `element:on_draw` callback or whatever.

**Comment by rubenwardy** [comment]
Really, you should consider any code that is in the same environment (or perhaps even sate) as SSCSM as compromised and untrusted

However, the API already allows exiting to the menu - there's a disconnect method iirc

**Comment by hecktest** [comment]
I don't understand, is this a GUI specific PR or a generic input and rendering one? Tying this to GUI in any way might be missing the forest for the trees.

**Comment by v-rob** [comment]
> I don't understand, is this a GUI specific PR or a generic input and rendering one? Tying this to GUI in any way might be missing the forest for the trees.

The events API will not be tied to the GUI in any way, but it will be used by it.  On the other hand, I'm still considering whether the drawing API should be tied to the GUI simply because of technical difficulties with sharing drawing between separate mods, specifically the last mod to register a drawing function will draw above everything else, whereas a custom drawn element can specify position in relation to other elements.  I don't particularly want them tied together, but we'll see.

**Comment by hecktest** [comment]
Callback priority issues could be solved by introducing a numerical priority parameter to sort the calls by. Then you could even assign numbers to the engine's own rendering stages, and allow the user to hook into any part of the process. The concept of persistent 'elements' should not exist in a global draw callback; all you need is the ability to set the material, push a matrix and draw some primitives or whole meshes. The GUI framework can then use this rendering system instead of maintaining its own.

It's your code and your time, but I strongly encourage straight up working on proper SSCSM since you're so close to it already. "What if it never gets made" is a self fulfilling prophecy.

**Comment by v-rob** [comment]
> Callback priority issues could be solved by introducing a numerical priority parameter to sort the calls by. Then you could even assign numbers to the engine's own rendering stages, and allow the user to hook into any part of the process.

While hooking into rendering stages is a good idea, I don't like the concept of priority numbers.  They sound good in theory, but the truth of the matter is that each mod expects to have the whole screen to itself, and when two mods expect that, they probably will conflict.  In that situation, z indexes aren't going to help because each mod is going to have an arbitrary number anyway.  It's really up to the person installing the mods to fix it at that point.  So, a `minetest.register_on_draw` callback might exist, but I'm not going to make it use priority numbers (although it may have rendering stages) because they really aren't going to help.

> all you need is the ability to set the material, push a matrix and draw some primitives or whole meshes

I personally want to stay away from drawing 3D things into the world in Lua (if that's what you're talking about).  I think it will lead to all sorts of abuses and barely working hacks.  If something 3D should be in the world, an entity is the best bet.  `ScreenDrawer` is for the UI alone; it's not designed for 3D with sorting and whatnot, but layered 2D drawing.  It will have 3D support to make things like #10320 and CSS `transform`/`perspective` possible, but that's about it.

**Comment by red-001** [comment]
So I was reading my email and this came up so I thought I would give my 2 cents.

> Possible future security issue: If we implement the Esc menu in Lua, what's to prevent a mod (either CPCSM or SSCSM) from overriding it somehow? There are multiple avenues that this could happen through, like changing a global function or modifying a table entry containing event/drawing callbacks, and I don't think they can all be secured

Might be best to implement core functionality in a separate Lua state from everything else as Rubenwardy suggested, with it being given priority over mod provided code (e.g. gets keypress events before the mod code, and can force being rendered on top of anything mods render). This is likely the only way to secure core functionality (escape menu, password change, game chat?, etc) from tampering by mods. I see you suggested running this in the same environment as CPCSM in #10530 but personally I think mods shouldn't be able to tamper with core functionality even if the user installs the mod themselves. If server provided formspec rendering is done in this Lua state it might be best to disable `loadstring`, just to make sure a buggy implementation can't result in arbitrary code execution.

**Comment by v-rob** [comment]
> Might be best to implement core functionality in a separate Lua state from everything else

This is a problem I've been trying to figure out.  If I implement the core GUI handling code in a separate state, there's no way to share a table between states (and if there was, it would be as insecure as if it were in the same state).  That would result in CSM having to use the SSM API to communicate across Lua states, removing the ability for custom elements, a key part of having it all in Lua.  Then again, if it were put in the SSCSM state, CPCSM would have to use the SSM API, and vice-versa, along with all the security issues.

On the other hand, the core GUI handling code can be implemented in C++, which can interface across all Lua states.  Custom elements could still be implemented in Lua, but core elements like buttons would also have to be C++ for security reasons as well so they couldn't be overwritten.  This removes a lot of dynamism and the benefit of quick, easy development in pure Lua.  It also would cause Lua custom elements, screen drawing, and events to be extra features instead of an integral part of the GUI system.  There would also be speed tradeoffs, making core elements faster and custom elements slower than a pure Lua implementation.

So, I really don't know.  If there's a way to share things between states in Lua without removing any dynamism, I'd take it, but it seems that might not be possible.

**Comment by benrob0329** [comment]
Why not have a default implementation which can be gotten and built upon?

**Comment by red-001** [comment]
Why is sharing a table needed? could have default rendering being done in one state and if another state wants a custom element it can pull in the same source code but then extend it to support whatever it needs and render that. 

E.g. a SPCSM mod wants some custom hud elements so the server disables the default ones if it detects a client running it's CSM mod and the CSM handles the hud rendering. 

Have the internal code render over server provided which would render over client provided, and vice-versa for keyevents. That means nothing can render over core UI and that sensitive input can be protected (password change, escape key during gameplay, anything else deemed important).

Alternatively could make the internal code just handle core UI and render mod formspecs and the HUD in either the CPCSM or SPCSM sandbox depending on the source. Would have the advantage of less code running in the highest privileged sandbox and maybe easier modification but the disadvantage that the SPCSM Lua state would need to be created even if the user has disabled SPCSM.

**Comment by rubenwardy** [comment]
What secure features are there exactly? Exiting to the main menu and closing minetest are both things that can be done from CSM currently, using `minetest.disconnect()` or causing a crash.

I guess the key binding and sound menus, if exported to Lua? How about having multiple instances of the GUI code for when this is done in the future, in a different state/environment

**Comment by red-001** [comment]
> What secure features are there exactly? 

Mostly just the password change dialog, even if that's not used a lot it would be best if it was secure and couldn't be replaced with a fake one. 

Multiple instances would work well I think, only disadvantage is the client will always need to create at least two Lua states.

**Comment by v-rob** [comment]
By secure, I mean that it shouldn't be possible for CSM to overwrite the Esc menu and other such menus.  While it could be a cool feature for games to integrate things more, a malicious mod might remove the Esc menu entirely, and some users who don't know about Alt-F4 or Alt-Tab wouldn't be able to exit the game.

My rationale for a shared table is so you could have a shared hierarchy so that you can have core, SSM, SSCSM, and CPCSM elements all in the same hierarchy.  The alternative is to make each have a separate state and hierarchy (actually, SSM could be in with core or SSCSM since SSM will always be completely secure because of the necessary limitations.  Perhaps have SSM in with core if SSCSM is disabled, or in with SSCSM if it is enabled).  The problem with these different states is z-indexing between states would be non-existent, drawing order things like a HUD layer and a GUI layer would be hardcoded, and overwriting default HUD stuff like the hotbar would require extra work.  That is better than C++, I suppose, and certainly secure since everything is in it's own state.

**Comment by red-001** [comment]
Hardcoded z-indexing between the different states doesn't seem like that bad of a thing, the player can fix CPCSM if it doesn't work nicely with what the SPCSM does (or disable SPCSM I suppose). And internal/secure should always get priority anyways. It seems rigid ordering between the different layers is more of a feature than a bug.

**Comment by v-rob** [comment]
I guess that's what I'll do then.  At any rate, nearly anything I could do here is still thousands of times better than formspecs :-)

Anyway, I'm slowly making progress on this.  I've only had about an hour a day to work on anything, but `ScreenDrawer` is slowly but surely approaching completion.  I'm currently working on 3D stuff like models and attempting planar transformations.  BTW, if anyone know how to draw clipped lines/circles/polygons and a gaussian-like blur filter, I'd be very appreciative if you could offer help because I think they'd be useful features.

**Comment by rubenwardy** [comment]
Just had a glance over the changes, I like the implementation so far

**Comment by v-rob** [comment]
I'm considering migrating `ScreenDrawer` to separate functions, e.g. `ui.draw_rect`, `ui.get_text_size`, etc because, while most of these aren't useful outside of screen drawing, I don't see much of a need to be creating a basically stateless object every frame.  Also, some like `get_image_size` could potentially be useful outside of plain drawing.

**Comment by rubenwardy** [comment]
That's okay with me, just make sure to keep it clean as a class in C++. Also, save `ui` for the Lua GUI/HUD library, perhaps naming the drawer `drawer` or `minetest.drawer`

**Comment by v-rob** [comment]
image

Well, I sorta lied.  I did figure out how to use transformations.  Scaling, skewing, rotating around any axis, translating, perspective, etc, anything you can do with Irrlicht's `core::matrix4`, all from Lua.  There are still kinks to work out, but transformations are quite viable.  (Many thanks to #9312)

**Comment by v-rob** [comment]
As a heads up: this draft PR is sort of turning into a big playground for messing around with drawing and textures and whatnot.  It will definitely be split into many PRs, not all directly related to UI stuff.  So don't be surprised if you see a bunch of weird commits with stuff that is seemingly unrelated to UI.

**Comment by v-rob** [comment]
I've been experimenting with the idea of custom textures:

https://www.youtube.com/watch?v=87iyesNooFI

I think the idea has a lot of potential.  Really, it came about as a by-product of my working on a highly capable drawing API.  Making the texture available in-game was a small extension.  It has multiple bugs, such as the impossibility of texture modifiers (it's pure ITexture, no associated IImage to allow it to be dynamic) making `crack_anylength.png` broken, some internal problems here and there, the chat shrinking (I really have no idea why that happens... It might be a problem with `draw_transformed_texture`).

Regardless, it's not PR ready by a long shot.  Nor will I fix the bugs and make it a PR yet because GUIs are higher priority, although somewhat less exciting.  Custom _textures_ will make it into the GUI PR for e.g. CSS `transform` or paint-like mods using render textures (simple enough), but not custom _in-game textures_ (which is where the bugs and problems are).

**Comment by v-rob** [comment]
Closing; I don't expect to work directly on this branch anymore.  The first split PR will hopefully be for events, but I have my doubts as I think it might be better to wait for SDL2 events before formalizing an API.  So, part of drawing might come first.

**Comment by sorcerykid** [comment]
> I've been experimenting with the idea of custom textures:

Cheers v-rob. Excellent work you've done, and I can see you're on the right conceptual path.

The demo video has me particularly intrigued. I've been wanting to develop a security camera mod, so the ability to render to a node surface would prove invaluable. You've opened a world of new possibilities for modding in Minetest.

**Comment by v-rob** [comment]
> The demo video has me particularly intrigued. I've been wanting to develop a security camera mod, so the ability to render to a node surface would prove invaluable. You've opened a world of new possibilities for modding in Minetest.

I would say that the biggest problem is that of when to update textures.  If there are 5 security cameras, that's 5 to update every frame.  If there are 500, then that's a _lot_ of textures per frame, all of them rendering a 3D scene.  The question is how to keep this number down given that any number of security cameras can be placed?  If one were to limit by proximity to the player, there could still be a few hundred within range of the player.  Or, in another example, if signs use custom textures for text, should all the text for every sign be generated at the start of the game?  That could be a lot of textures to generate on a big world.

**Comment by v-rob** [comment]
If we get SDL2 input, I worked out a possible API.  It's a near exact reflection of SDL's relevant API (although somewhat Lua-ified) meaning it's very large but has all the input functionality anyone could ever wish for.

<details><summary><b>API</b></summary>

* `minetest.register_on_event(function(event))`
    * Called every time an event (such as keyboard or mouse input) is fired after the
      engine uses it.
    * If this function returns `true`, all events handlers registered after this one will
      not be called.
    * To get the state of all events at the current time, use `minetest.get_event_state`.
    * `event`: A table describing the event. The table looks like this (example values):
        ```lua
        {
            -- The type of the event. Whatever value this is, there is a key in this table with
            -- the same name containing the event information. No other keys will be present in
            -- this parent table.
            type = "keyboard",

            -- A keyboard event. This event should **not** be used for textual input fields;
            -- instead, use the `text_input` and `text_edit` events.
            keyboard = {
                -- True if the key was pressed and false if released.
                down = true,

                -- True if the key has been held down and started repeating.
                again = false,

                -- The keycode of the button pressed according to the current keyboard layout.
                -- See `minetest.get_keycode_state()` for more information.
                keycode = "K",

                -- The keyboard-independent physical location of the button pressed on the keyboard.
                -- See `minetest.get_scancode_state()` for more information.
                scancode = "Y"
            },

            -- A text input event. Only happens when `minetest.set_text_input()` is set
            -- to `true`. This may be preceded by one or more `text_edit` events.
            -- Also see <https://wiki.libsdl.org/Tutorials/TextInput>.
            text_input = {
                -- The text that was inputted.
                text = "X",
            },

            -- A text compostion event for IME.  Only happens when `minetest.set_text_input()`
            -- is set to `true`. `minetest.set_text_input_rect()` should be used to control the
            -- position of the candidate list.
            -- Also see <https://wiki.libsdl.org/Tutorials/TextInput>.
            text_edit = {
                -- The text that is currently being edited with the IME.
                text = "abc",

                -- The cursor location inside the composition.
                start = 2,

                -- The length of the composition.
                length = 3,
            },

            -- The mouse moved.
            mouse_motion = {
                -- The position of the mouse after the motion.
                pos = {x = 10, y = 10},

                The amount the mouse moved relative to its last position.
                motion = {x = 5, y = 5}
            },

            -- A mouse button was pressed or released.
            mouse_button = {
                -- True if the button was pressed and false if released.
                down = true,

                -- The button that was pressed or released. One of "Left", "Middle", "Right",
                -- "X1", or "X2".
                button = "Left",

                -- The number of times the button was pressed in quick succession, i.e. one
                -- for a single-click, 2 for a double-click, etc.
                clicks = 1
            },

            -- A mouse wheel was scrolled.
            mouse_wheel = {
                -- The amount the wheel scrolled in the X and Y directions. For mouse wheels,
                -- the value is usually one or zero, but things like touchpads can have lesser
                -- or greater values.
                motion = {x = 0, y = 1}
            },

            -- A touchscreen was interacted with.
            touch = {
                -- Touchscreens usually can handle multiple touches independently. This is the
                -- finger/device generating this particular event.
                finger = 0,

                -- The type of the interaction. One of "motion", "down", or "up".
                type = "motion",

                -- The position of the finger.
                pos = {x = 10, y = 10},

                -- The amount the finger moved from its last position. Contains zeroes if not
                -- of type "motion".
                motion = {x = 50, y = 34},

                -- The amount of pressure applied in the range [0, 1].
                pressure = 1
            },

            -- A touchscreen was interacted with multiple fingers in a gesture.
            touch_gesture = {
                -- The number of fingers/devices involved in the gesture.
                num_fingers = 2,

                -- The amount the fingers moved in a rotating motion in (TODO: radians, degrees, what? Needs testing).
                rotate = TODO,

                -- The amount the fingers moved in a pinching/expanding motion. (TODO: Again, needs some units)
                pinch = TODO,

                -- The center of the gesture.
                center = {x = 49, y = 73}
            },

            -- A game controller axis was moved.
            -- Note: Game controllers are a subset of joysticks like Xbox or Playstation
            -- controllers. They have consistent layouts unlike joysticks, which may not have
            -- the same buttons, axes, or layout. Game controller events will only occur for
            -- supported joysticks, but joystick events will occur for all joysticks and game
            -- controllers as well.
            controller_axis = {
                -- The axis that was moved. See `minetest.get_controller_axes_states()` for
                -- possible values.
                axis = "Left X",

                -- The value of the axis in the range [-1, 1].
                value = -0.5
            },

            -- A game controller button was pressed or released.
            controller_button = {
                -- True if the button was pressed and false if released.
                down = true,

                -- The button that was pressed or released. See
                -- `minetest.get_controller_button_states()` for possible values.
                button = "X",
            },

            -- A joystick axis was moved.
            joystick_axis = {
                -- The index of the axis that was moved. The value is joystick-dependent,
                -- anywhere from 0 to 255.
                axis = 0,

                -- The value of the axis in the range [-1, 1].
                value = -0.5
            },

            -- A joystick button was pressed or released.
            joystick_button = {
                -- True if the button was pressed and false if released.
                down = true,

                -- The index of the button that was pressed or released. The value is
                -- joystick-dependent, anywhere from 0 to 255.
                button = 3
            },

            -- A joystick trackball was moved.
            joystick_trackball = {
                -- The index of the trackball that was moved.  The value is joystick-dependent,
                -- anywhere from 0 to 255.
                trackball = 0,

                -- The motion in the X and Y directions, each in the range [-1, 1].
                motion = {x = -0.5, y = 1}
            },

            -- A joystick POV hat was moved.
            joystick_hat = {
                -- The index of the hat that was moved.  The value is joystick-dependent,
                -- anywhere from 0 to 255.
                hat = 0,

                -- The value of the hat. See `minetest.get_joystick_hat_states()` for possible
                -- values.
                value = "up"
            },

            -- A file or text is either dragging over or was dropped onto the window.
            drag_drop = {
                -- The type of operation. One of "start" (the item is hovering over the window),
                -- "end" (the operation has completed), "file" (a file has just been dropped),
                -- or "text" (text has just been dropped).
                type = "file",

                -- If the type is "file" or "text", this is the text or file that was dropped.
                -- Otherwise, this is `nil`.
                value = "/path/to/file.txt",
            },

            -- An event related to the Minetest window. Only exposes information useful
            -- to games and mods, not external information.
            window = {
                -- The type of window event. One of "resize" (the window size was changed),
                -- "focus" (the window recieved focus), "blur" (the window lost focus),
                -- "enter" (the mouse entered the window), and "leave" (the mouse left the
                -- window).
                type = "resize",

                -- If the type is "resize", this is the new size of the window. Otherwise `nil`.
                size = {x = 1024, y = 600}
            }
        }
        ```

* `minetest.get_keycode_state()` -> state: Returns a table of the current state of the
  keyboard indexed by keycodes.
    * The table has the organization `{ [keycode] = true }` for each keycode that is
      currently held down.
    * Keycodes are values according to the current keyboard layout. For instance, a "Y"
      on a QWERTY keyboard would be a "K" on a DVORAK. Keycodes are recommended to be
      used for their meaning, like "I" for inventory.
    * For a comprehensive list of keycodes, see <https://wiki.libsdl.org/SDL_Keycode>,
      leftmost column.
* `minetest.get_scancode_state()` -> state: Returns a table of the current state of the
  keyboard indexed by scancodes.
    * The table has the organization `{ [scancode] = true }` for each scancode that is
      currently held down.
    * Scancodes are keyboard layout-independent values based on the physical location of
      the button on the keyboard. Often, this value is the same as the QWERTY keycode.
      Scancodes are recommended to be used for their position, like WASD for movement.
    * For a comprehensive list of scancodes, see <https://wiki.libsdl.org/SDL_Scancode>,
      leftmost column.
* `minetest.get_keymod_state()` -> state: Returns a table of the current state of
  keyboard modifiers.
    * The table has the organization `{ [keymod] = true }` for each modifier that is
      currently active.
    * Note that modifiers that are not currently held down may be active, e.g. keys
      like Caps Lock or if the Windows Sticky Keys feature is on, so
      `minetest.get_keycode_state()` and `minetest.get_scancode_state()` are not substitutes.
    * Possible modifiers (same name as their keycode/scancode counterparts):
        * "Left Shift"
        * "Right Shift"
        * "Left Ctrl"
        * "Right Ctrl"
        * "Left Alt"
        * "Right Alt"
        * "Left GUI"
        * "Right GUI"
        * "Numlock"
        * "CapsLock"
        * "ModeSwitch"
    * In addition, since it often doesn't matter whether the left or right modifier key is
      pressed, the following exist if either right or left is active:
        * "Shift"
        * "Caps": If caps lock or either shift is active
        * "Ctrl"
        * "Alt"
        * "GUI"

* `minetest.set_text_input(enable)`: Sets whether the `text_input` and `text_edit`
  events in `minetest.register_on_event` should be activated.
    * `enable`: Whether it should be enabled. Initially false when the game starts.
* `minetest.get_text_input()` -> enabled: Gets whether the `text_input` and
  `text_edit` events in `minetest.register_on_event` are activated.
* `minetest.set_text_input_rect(rect)` Sets the rectangle for the OS-drawn IME candidate
  list during `text_input` events.

* `minetest.get_mouse_button_state()` -> state: Returns a table of the current state of
  the mouse buttons.
    * The table has the organization `{ [button] = true }` for each button that is
      currently held down.
    * Possible buttons:
        * "Left"
        * "Middle"
        * "Right"
        * "X1"
        * "X2"
* `minetest.set_mouse_pos(pos)`: Sets the current position of the mouse inside the
  Minetest window.
    * Only works when the mouse is not captured. See `minetest.set_mouse_capture`.
* `minetest.get_mouse_pos()` -> pos: Gets the current position of the mouse inside the
  Minetest window.
    * Only works when the mouse is not captured. See `minetest.set_mouse_capture`.
* `minetest.set_cursor(cursor)`: Changes the current cursor.
    * Only visible when the mouse is not captured. See `minetest.set_mouse_capture`.
    * `cursor`: One of the following strings:
        * "none": Invisible cursor
        * "arrow": The default arrow pointer
        * "ibeam": An I-beam for input fields
        * "wait": A waiting cursor, like an hourglass or spinning circle
        * "waitarrow": The arrow pointer and wait cursor combined
        * "crosshair": A crosshair cursor
        * "no": A crossed out circle
        * "hand": A pointer hand
        * "sizenwse": A double arrow pointing northwest and southeast
        * "sizenesw": A double arrow pointing northeast and southwest
        * "sizewe": A double arrow pointing west and east
        * "sizens": A double arrow pointing north and south
        * "sizeall": A four pointed arrow pointing north, south, east, and west
* `minetest.get_cursor()` -> cursor: Gets the current cursor.
* `minetest.set_mouse_capture(capture)`: Sets whether the mouse cursor should be
  invisible and trapped within the Minetest window.
    * `capture`: Set to `true` to capture the mouse (like in-game) and `false` to make it
      visible (like in a menu).
* `minetest.get_mouse_capture()` -> captured: Gets whether the mouse cursor is currently
  invisible and trapped within the Minetest window.

* `minetest.get_touchscreen_state()` -> state: Returns a table of the current state of
  each finger on the touchscreen.
    * `state`: A table of finger states where each finger looks like this:
    ```lua
    {
        -- The position of the finger
        pos = {x = 23, y = 34},

        -- The amount of pressure applied in the range [0, 1].
        pressure = 1
    }
    ```

* `minetest.get_joystick_axes_states()` -> states: Returns the value of the axes on the
  joystick.
    * `states`: A table of axis states where each axis is a value in the range [-1, 1].
* `minetest.get_joystick_button_states()` -> states: Returns the value of the buttons
  on the joystick.
    * `states`: A table of button states where each button is `true` if pressed and
      `false` if not pressed.
* `minetest.get_joystick_hat_states()` -> states: Returns the value of the POV hats on
  the joystick.
    * `states`: A table of POV hat states where each hat is one of the following:
        * "leftup"
        * "up"
        * "rightup"
        * "left"
        * "center"
        * "right"
        * "leftdown"
        * "down"
        * "rightdown"

* `minetest.get_controller_axes_states()` -> states: Returns the value of the axes on the
  game controller.
    * The table has the organization `{ [axis] = state }` for each axis.
    * Each axis is a value in the range [-1, 1].
    * List of axes:
        * "Left X"
        * "Left Y"
        * "Right X"
        * "Right Y"
        * "Left Trigger"
        * "Right Trigger"
* `minetest.get_controller_button_states()` -> states: Returns the value of the buttons
  on the game controller.
    * The table has the organization `{ [button] = true }` for each button that is currently
      held down.
    * Possible buttons:
        * "A"
        * "B"
        * "X"
        * "Y"
        * "Back"
        * "Guide"
        * "Start",
        * "Left Stick"
        * "Right Stick"
        * "Left Shoulder"
        * "Right Shoulder"
        * "D-pad Up"
        * "D-pad Down",
        * "D-pad Left"
        * "D-pad Right"

* `minetest.set_clipboard_text(text)`: Sets the text in the OS's clipboard for copy, cut, and
  paste operations
    * `text`: The text to set the clipboard to.
* `minetest.get_clipboard_text()` -> text: Gets the text in the OS's clipboard, or nil if
  there is no text in the clipboard.

</details>

**Pull request closed without merging**
