### PR TITLE
Fixed falling through nodes with custom collision box on world load (…

### LINKED ISSUE #2784: Player doesn't clip on half blocks on world load
If the player is over a half block that's placed in the lower half of the node the player will not clip when you resume playing.

This is easily noticeable if you create a bridge made with the half block.

If the half block is in the upper part of the node it works correctly.

### PR DESCRIPTION
**Pull request by JohnWayne1986**
…fixes #2784).

### CODE REVIEW

**Comment by est31** [comment]
Looks good, though I wouldn't call it "custom collision box".

Also it would be best to have a [more properly formated commit message](http://chris.beams.io/posts/git-commit/), particularly: present tense, and more shorter first line.

**Comment by JohnWayne1986** [comment]
Thanks for the hints! I tried to follow the guide and changed the commit message accordingly (I read that it is fine to change history for a PR!?). I called it now "node box" like in the code comment.

**Comment by est31** [comment]
Very nice!

Its fine to change PR history for this project, yes.

**Comment by est31** [comment]
Merged in 8787d2e7e9671f3b5930ca9c41c6e0867b8a5a54

**Pull request closed without merging**
