### PR TITLE
Valleys C++ Mapgen

### PR DESCRIPTION
**Pull request by ghost**
This mapgen is based on the lua Valleys Mapgen and Mapgen V7. It creates natural looking terrain and includes a cave generation function that produces highly interconnected caves.

See also: https://forum.minetest.net/viewtopic.php?f=9&t=11430

### CODE REVIEW

**Comment by kilbith** [comment]
Awesome work, congrats.

c-demo-34

**Comment by MoNTE48** [comment]
:+1: I like this

**Comment by C1ffisme** [comment]
Does this allow using an image template just like the original mod?

**Comment by est31** [comment]
I like the idea of it being in the engine too.
Screenshot with vanilla mtgame:

screenshot

**Comment by duane-r** [comment]
>Does this allow using an image template just like the original mod?

I'm not sure we're thinking of the same mod. I've never seen it use an image template. At any rate, this mapgen won't.

**Comment by paramat** [comment]
Okay i will review, might take a while. If you want it *in* but hidden initially (only selectable by a mod, not by newbies) you can do that in 'emerge.cpp'.

**Comment by paramat** [comment]
Is 'noise_inter_valley_fill' 2D or 3D? It's defned as 3D n the ctor but is a 2D perlinmap in 'calculateNoise':

noise_inter_valley_fill = new Noise(&sp->np_inter_valley_fill, seed, csize.X, csize.Y, csize.Z);
noise_inter_valley_fill->perlinMap2D(x, z);

I'm surprised to see so few 3D noises, i seem to remember the lua version has many. Anyway that's a good thing.

**Comment by duane-r** [comment]
You're right, that is supposed to be 2D. That's the one 3D noise that slows everything down so much in the original (if you discount the caves). I made it 2D for speed.

**Comment by Gael-de-Sailly** [comment]
About this noise:

The 3D noise 6 (inter-valleys filling) was created to better make 2 types of mountains:
* Old, smooth mountains like the Vosges in France:
Vosges mountains
* Younger, higher, sharper mountains like the Alps:
Alps
The first can be easily made by 2D noise, the second can't. Around its highest point, a 2D noise has a small flat zone that makes impossible to build an alpine-like mountain. The other drawback of the 2D noise is that it's strictly impossible to make a vertical or overhanging cliff (except ugly square cliffs like in v6, that seems to be generated from booleans) that have a real interest for the game, I think. That's why I've indroduced this 3D noise to "fill" the inter-valleys terrain with sharp slopes and mountains.

In Lua VMG, these 2 types of mountains are created by giving a variable importance to this noise 6. This importance is determined by the 2D noise 5.

You may have noticed that: very often I prefer the terrain quality in spite of the slow mapgen. But if you have a slow computer or you want the mapgen to be very fast, e.g. for a server, I can understand that you want a lighter mapgen algorithm. I think that the best is a settable option for this 3D noise, like done for v7, with `mgv7_spflags = mountains, ridges`.

**Comment by paramat** [comment]
Thanks i see, 'noise_inter_valley_fill' should certainly be 3D noise then, terrain needs at least 1 3D noise to generate overhangs and sharp, spiky features. 3D noise is un-eased by default which creates the sharpness (see mgv5 for eased 3D noise, it's all smooth and blobby).
'noise_inter_valley_fill' only has 6 octaves which is not at all excessive, we only have 2 other 3D noises with 3 octaves each, so making 'noise_inter_valley_fill' 3D is no problem, the mapgen will still have less noise-processing than mgv7.

**Comment by paramat** [comment]
Please could you remove the profiling switch code and switch profiling by using 'commenting-out'?
I know the switch is useful for dev work but it is slower because at many places in the code you are checking the value of the switch. I know the speed difference is very small but adding/deleting comment symbols is not much work.

**Comment by paramat** [comment]
/////////////////// Mapgen Valleys flags
#define MG_VALLEYS_CLIFFS 0x02
#define MG_VALLEYS_RUGGED 0x04

Please could these be 0x01 and 0x02 instead?

**Comment by paramat** [comment]
river_size = (float)(sp->river_size) / 100;
river_depth = sp->river_depth + 1;
water_level = params->water_level;
altitude_chill = sp->altitude_chill;
lava_max_height = sp->lava_max_height;

humidity_adjust = sp->humidity - 50;
temperature_adjust = sp->temperature - 50;

These should all be in the form:
this->temperature_adjust = sp->temperature - 50;
See fractal mapgen for example.

**Comment by paramat** [comment]
"water_level = params->water_level;"
Not needed, 'water_level' is a global mapgen parameter and is already a global variable within mapgen files, you can just use it without initialising it anywhere in valleys mapgen files.
It's also missing from readParams() and writeParams().

**Comment by paramat** [comment]
In the constructor combine the '//// Terrain noise' and '// VMG noises' sections and call them all 'Terrain noise'. There's no need to separate them. Also add a space between the 2D and 3D noises.

**Comment by paramat** [comment]
"settings->setS16("mg_valleys_cave_water_max_height", cave_water_height);"
The variable name should match the settings name.

**Comment by paramat** [comment]
In the header you can delete this, 'ridge heightmap' is a mgv7-only thing:
"//s16 *ridge_heightmap;"

**Comment by paramat** [comment]
"s16 river_size;
s16 river_depth;
s16 water_level;
s16 altitude_chill;
s16 humidity;
s16 temperature;
s16 lava_max_height;
s16 cave_water_height;"

These are missing from 'MapgenValleysParams::MapgenValleysParams()' in the cpp file and then you have lines of the form:
"if (!settings->getS16NoEx("mg_valleys_temperature", temperature))
		temperature = 50;"
.. in 'readParams()', is there a reason? Perhaps these should be set in 'MapgenValleysParams::MapgenValleysParams()' as in mgfractal?

**Comment by C1ffisme** [comment]
@duane-r Yeah, we are. Stupid me, I was thinking of realterrain.

**Comment by Gael-de-Sailly** [comment]
@C1ffisme Indeed, including realterrain into the core is a very good idea too ! But here that's not the topic. Maybe we can discuss it on the forum.

**Comment by duane-r** [comment]
I've put the original algorithm for inter-valley filling in. It works, but produces a lot of odd terrain. It's extremely slow at the moment (especially at spawn) because it's generating unnecessary noise maps. However, if I can't fix the odd terrain, I won't bother with that. I'll probably kill this pull request and submit it again after everything's working and thoroughly tested, but take a look and see if the terrain is anywhere near the mark.

**Comment by paramat** [comment]
Thanks for your updates.
> It's extremely slow at the moment (especially at spawn) because it's generating unnecessary noise maps.

What do you mean by 'unnecessary noise maps'? It shouldn't be slow, the use of 3D noise is less than mgv7.

**Comment by duane-r** [comment]
>What do you mean by 'unnecessary noise maps'? It shouldn't be slow, the use of 3D noise is less than mgv7.

I have to break the height generator out into mapped and non-mapped noise versions. Previously, I just passed the noise values at a given point to the same function, but that won't work with the original algorithm. At the moment, every call to *AtPoint is creating a map. When I can get it to generate the terrain properly, I'll optimize.

Here's an example of the weird terrain (could be fun to build in though).

**Comment by paramat** [comment]
In 'generateTerrain()' you do this for each (x, z):
"s16 surface_y = (s16) noise_terrain_height->result[index];"
Surely this just creates a simple 2D noise surface, where do all the other noises have their influence?
Now that 'noise_inter_valley_fill' is 3D you need to check for terrain per-node, inside the y-loop, something like (line 658):
"} else if terrainAtPoint(x, y, z)
					// ground
					vm->m_data[i] = n_stone;"
With a new function 'terrainAtPoint(x, y, z)' that calculates whether terrain is present at a particular (x, y, z) point.

**Comment by paramat** [comment]
In 'baseTerrainLevelAtPoint()' you have:
"noise_inter_valley_fill->perlinMap3D(x, y, z);"
This should be:
"noise_inter_valley_fill->NoisePerlin3D(x, y, z);"
'baseTerrainLevelAtPoint()' is only ever used for player spawn, never for actual mapgen, because it has individual noise calls instead of using perlinmaps. Mapgen should only use the perlinmaps.

**Comment by duane-r** [comment]
>'baseTerrainLevelAtPoint()' is only ever used for player spawn, never for actual mapgen, because it has individual noise calls instead of using perlinmaps. Mapgen should only use the perlinmaps.

That's true. However, I can't send just one noise value, since the original algorithm cycles through each point in a column until it finds one that meets its conditions, then sets the terrain height there. So, I just generated a map to check whether or not the main function would work properly -- which it doesn't, at least at some points. Until I can fix that, there's no point bothering with the rest.

It does give me an idea of how most of the terrain will look. I'd like Gael-de-Sailly's opinion on it, especially.

**Comment by paramat** [comment]
Ah i found "noise_terrain_height->result[index] = mount;" so nevermind that issue.

**Comment by duane-r** [comment]
>I tried the mapgen, with the default of "fast" flag disabled, and it looks okay but as i wrote the 3D noise is failing, the terrain looks like 2D noise only.

I don't think the 3D noise is going to have the effects you're expecting. Take a look at the lua version to see what we're aiming for.

Here are two images of the same map, from the same location and angle.

Lua version:



C version:



Already, the landforms are extremely similar, if you discount the differences in soil thickness and vegetation. You won't see any (intentional) overhangs in either. The 3D noise isn't being used in the same way as in mapgen_v7.

**Comment by duane-r** [comment]
Closed for further maintenance.

**Comment by paramat** [comment]
> At the moment, every call to *AtPoint is creating a map
So, I just generated a map to check whether or not the main function would work properly

Aha i see now, yeah generating 6400 3D perlinmaps per chunk would be slow =)

**Pull request closed without merging**
