### PR TITLE
Reorganizing client and settings tabs

### PR DESCRIPTION
**Pull request by kilbith2**
Client tab : 
- Various moving/scaling for enhance the ergonomy.

Settings tab : 
- Added the "Node Highlighting" option.
- Added 2 dropdown lists for filters and mipmapping.
- Moved the dropdown drivers list for offset the middle column.
- Moved the Android part downward.

Tested and perfectly functional. Screenshots here : https://mediacru.sh/785348121907 (EDIT : settings tab screenshot outdated, see below).

### CODE REVIEW

**Comment by kaeza** [comment]
Could you make the server list a bit shorter and move the description label under it?

That should give more space for longer descriptions.

**Comment by MT-Modder** [comment]
:+1:  I love this change. Maybe the driver dropdown list could be labed just like gui scaling. And maybe it could be moved next to gui scaling instead of being with the filtering settings. I know celeron55 wants the menu totally rewritten but I only see that happening slowly over time with commits like these. Good work keep them coming kilbith.

**Comment by kilbith2** [comment]
@kaeza : no way :)

Reasons : 

1) A taller server list for a better overview.
2) I absolutely want to keep the checkboxes just under the server list.
3) The "mini-panel" for description is pleasant enough. The one in my screenshot is exceptionally long for the demo. Usually it's way shorter, check it.
4) If I move the description elsewhere, I'll have an unacceptable empty space and I think it already occupies the right place.

**Comment by PilzAdam** [comment]
Why is "Public serverlist" still a checkbox? Can you make it like a tab or so above the actual list?

**Comment by kilbith2** [comment]
@PilzAdam : I don't get your point... For obvious reason, the "Public serverlist" is useful for sorting the public servers or the favorites ones.

**Comment by MT-Modder** [comment]
I think what PilzAdam is saying is make the "Public serverlist" and the "favorites list" two separate tabs. I like that idea because new users will know there is a favorites list instead of accidentally coming across it by unchecking "public serverlist". I also think that the description box should have a scroll bar in case it's too long to fit.

**Comment by kilbith2** [comment]
About separate tabs, this is just a stupid idea that'd bring needless redundance. And I can't believe the "accident" example, this is really fetched. Sorry.

**Comment by MT-Modder** [comment]
If you were new to minetest how would you know about the favorites list? Would you automatically know that unchecking "public serverlist" gives you a list of favorites? Why and how is it stupid or redundant? With this logic pretty much all of the menu is redundant. Why should we even have tabs lets just combine all the tabs and make the whole menu a single page.

**Comment by ShadowNinja** [comment]
* Tabs make sense because they're two separate lists, but I don't think formspecs support this well.
  * Local map saving is still a sort of half-baked feature and not really suitable for widespread use (eg, it should have it's own directory).

**Comment by kilbith** [comment]
Oh right I apologize, I thought you were talking about a new tab next to the main ones.

Will see that later. WIP then.

**Comment by MT-Modder** [comment]
It's cool. Yeah that would have definitely been redundant :smile:

**Comment by kilbith2** [comment]
[Update] Client tab :

- agreeing with @ShadowNinja on IRC, I kept the checkbox under the list. Besides out the formspec support, tabs under the main tabs would be "heavy" visually.
- Removed the Map Saving option.
- Moved the serverlist & the fields slightly closer from the borders, and enlarged the description. It could contain enough space for the rules for example. However it's not intended to be a screed...

Well, I think I finalized my work now.

**Comment by MT-Modder** [comment]
Maybe you could change the "Public Serverlist" label to "Public Serverlist / Favorites" then. I still think the driver dropdown list looks a bit odd without a label. Otherwise good work :+1:

**Comment by SmallJoker** [comment]
The idea of using more space of the mainmenu is good but the Name and Password fields should have +/- the same length because this would lead to a weak password.

**Comment by kilbith2** [comment]
@SmallJoker : rubbish.

- You can't see the password, so doesn't matter.
- 8-9 caracters allowed until the shifting. Is that really weak ? This is more than the minimum requested on highly-secure websites (Google, PayPal, etc.).
- Average people usually use way shorter passwords than 8-9 caracters and it's quite enough.
- I don't feel shorten the name field because that's visible and I want that 99.9% of nicknames can be seen entirely.

**Comment by kilbith2** [comment]
OK, updated.

- Fixed (moved) the Android part.
- Add 2 dropdown lists for the filters and mipmap/aniso settings.

bsf

**Comment by MT-Modder** [comment]
:+1: Love it!

**Comment by SmallJoker** [comment]
A label for the render is needed. Newbies don't know what "OpenGL" means

**Comment by kilbith2** [comment]
> Newbies don't know what "OpenGL" means

Does really matter ? OpenGL is only one usable, others are awful.

**Comment by SmallJoker** [comment]
@kilbith2 A render could be broken and the people have no idea how to fix it. Adding a label on top of it wouldn't be bad.

**Comment by MoNTE48** [comment]
@SmallJoker yes!
@kilbith2 Good work!
Wait this on next commit :)

**Comment by kilbith2** [comment]
OK, fixed a little bug and added the labels... All is now perfectly functional & clear. 
@ShadowNinja @sapier If you want to test, please.

fdsf

**Comment by Zeno-** [comment]
Looks ok to me!

**Comment by kilbith** [comment]
@Zeno- has commented an old code / old commit.

**Comment by Zeno-** [comment]
commit 227e4807b4d6e2f7d59bbe662df9122128952739

**Pull request closed without merging**
