### PR TITLE
Mgv6: Use heightmap in placeTreesAndJungleGrass()

### PR DESCRIPTION
**Pull request by paramat**
Instead of findGroundLevelFull.

### CODE REVIEW

**Comment by MT-Modder** [comment]
Does this help/fix floating junglegrass and jungletrees?

**Comment by paramat** [comment]
No, those bugs are due to cave overgeneration, so are unavoidable with current cavegen methods.

**Comment by paramat** [comment]
Merged 37a62970252cb7128900bffb7a07872679738e43

**Comment by MT-Modder** [comment]
Oh okay thanks.

**Pull request closed without merging**
