### PR TITLE
Add "," between priv names on grant/revoke msgs

### PR DESCRIPTION
**Pull request by DiamondPlane**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Looks good but conflicts with #10693, which I'd prefer to see merged first.

**Comment by DiamondPlane** [comment]
Ok

**Comment by SmallJoker** [comment]
#10693 is now merged; please rebase this PR.

**Comment by DiamondPlane** [comment]
> #10693 is now merged; please rebase this PR so that it can be reviewed & merged as well.

Ok, I will.

**Comment by DiamondPlane** [comment]
@SmallJoker How do I rebase it?

**Comment by SmallJoker** [comment]
grafik
or https://learntechsystems.com/git-rebase-and-resolve-conflicts-through-the-github-desktop/ (if you're using GitHub desktop)

**Comment by DiamondPlane** [comment]
> Either using the button below
> grafik
> or https://learntechsystems.com/git-rebase-and-resolve-conflicts-through-the-github-desktop/ (if you're using GitHub desktop)

I press the button, then?

**Comment by DiamondPlane** [comment]
@SmallJoker Done.

**Comment by SmallJoker** [comment]
Superseded by #11126, but thanks for you efforts.

**Pull request closed without merging**
