### PR TITLE
Allow empty default for flag settings

### LINKED ISSUE #3356: A default absence of mapgen spflags cannot be edited in settings
@PilzAdam 
Both fractal and flat mapgens have options that are unset by default, so they have a blank spflags field in settings. If in settingtypes.txt the 'default' is left blank, with 2 spaces between 'type' and 'possible values' as advised, the flags cannot be edited in settings.
So currently i am setting the flat mapgen spflags as 'nolakes,nohills', which is possibly not ideal as 'no' is usually used to unset a flag that is set by default. This needs sorting out before we can unhide flat or fractal mapgens.

### PR DESCRIPTION
**Pull request by PilzAdam**
Fixes #3356

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
:+1: Thanks! will test and then merge.

**Comment by paramat** [comment]
@PilzAdam this does make the flags field appear in setings, but there's a new problem.
Once i have created a mgflat world with 'lakes, hills' i cannot then create a second mgflat world with an empty string for flags, it refuses to accept "" as a valid setting. I have tried a few different ways of adding "" into the 'possible values' field but no success, is this even possible and what is the correct way?

**Comment by PilzAdam** [comment]
@paramat I will look into this in a few days. This PR can stay on hold until it's fixed.

**Comment by paramat** [comment]
Ok thanks.

**Comment by paramat** [comment]
Bump =)

**Comment by PilzAdam** [comment]
@paramat I'm sorry, I currently don't have a lot of time.

This can be probably fixed by wrapping https://github.com/minetest/minetest/blob/master/builtin/mainmenu/tab_settings.lua#L495-L504 into an `if new_value ~= "" then` block. Can you test this?

**Comment by paramat** [comment]
Thanks, no problem, i'll try what you suggest and perhaps with some help i can fix it myself.

**Comment by paramat** [comment]
See #3541

**Comment by PilzAdam** [comment]
Closing in favor of #3541.

**Pull request closed without merging**
