### PR TITLE
enable luajit on the docker image

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
## Overview

This PR adds `luajit` to the "stock" minetest docker image.

It will allow faster lua execution through the `luajit` library.

There are 2 stages in the `Dockerfile`: build and package.
In the build stage the `luajit-dev` package is pulled in with all the libraries and headers.
In the package stage only the `luajit` package with the previously linked libraries is included.
The size-increase is around 800 kb.

## Stats

In my tests i had a 20x to 30x decrease in processing time for lua mapgens with jit enabled.

## State

This PR is Ready for Review.

## How to test

```bash
# buid the image locally
docker build . -t minetest-jit

# start the server part with the new image
docker run --rm -it --network host minetest-jit

# connect with a client to 127.0.0.1:30000
# everything should work as before (or faster)
```

### CODE REVIEW

**Comment by paramat** [comment]
> It will allow faster lua execution through the luajit library.

> In my tests i had a 20x to 30x decrease in processing time for lua mapgens with jit enabled.

I am confused, we can already use LuaJIT so why is the increase in Lua speed even mentioned in this PR?
I hope this does not force LuaJIT to operate at all times, that cannot be done as a lot of Lua mods cause OOM crashes with LuaJIT, especially Lua mapgens, which is why i have never used LuaJIT. LuaJIT must be optional as now.
Perhaps i have misunderstood =)

**Comment by sfan5** [comment]
This is solely for the docker image we provide ([see here](https://github.com/minetest/minetest#docker)), it doesn't change anything about the build process or what is/isn't required.

**Comment by nerzhul** [comment]
Are you sure we use it on build ? you just install package, we don't have options to pass to cmake ?

**Comment by BuckarooBanzay** [comment]
> Are you sure we use it on build ? you just install package, we don't have options to pass to cmake ?

It's auto-detected:
```
Step 21/30 : RUN mkdir build && 	cd build && 	cmake .. 		-DCMAKE_INSTALL_PREFIX=/usr/local 		-DCMAKE_BUILD_TYPE=Release 		-DBUILD_SERVER=TRUE 		-DENABLE_PROMETHEUS=TRUE 		-DBUILD_UNITTESTS=FALSE 	-DBUILD_CLIENT=FALSE && 	make -j2 && 	make install
 ---> Running in fdeb2f66a395
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- *** Will build version 5.4.0-dev ***
-- Found Irrlicht: /usr/lib/libIrrlicht.so  
-- Using GMP provided by system.
-- Found GMP: /usr/lib/libgmp.so  
-- Using bundled JSONCPP library.
-- Found LuaJIT: /usr/lib/libluajit-5.1.so (found version "") 
-- Using LuaJIT provided by system.
```

**Review by nerzhul — APPROVED** [review]

**Comment by HybridDog** [comment]
As far as I know, there are bugfixes in the latest luajit which are not included in the latest stable release, for example: https://github.com/LuaJIT/LuaJIT/commit/45a7e5073ce0a59465fef0b80bb08bd4e76b7979
Does it install the latest LuaJIT or the `LuaJIT 2.1.0-beta3` from 2017?

**Comment by BuckarooBanzay** [comment]
> As far as I know, there are bugfixes in the latest luajit which are not included in the latest stable release, for example: [LuaJIT/LuaJIT@45a7e50](https://github.com/LuaJIT/LuaJIT/commit/45a7e5073ce0a59465fef0b80bb08bd4e76b7979)
> Does it install the latest LuaJIT or the relatively old `LuaJIT 2.1.0-beta3` from 2017?

It installs `2.1.0_beta3-r6`

**Review by SmallJoker — APPROVED** [review]
LGTM

**Pull request merged**
