### PR TITLE
Log server announce on updates and deletes too

### PR DESCRIPTION
**Pull request by Tyler-2**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
I am troubleshooting an issue where the START announce seems to be sent, but the UPDATE never is... And I realized that the logs don't even tell you when the server is announcing itself. Seems to me like it should?

- How does the PR work?
Instead of only sending the announce-announcement when doing a START announce, send it any time you do any kind of announce.
- Does it resolve any reported issue?
Don't think so.
- If not a bug fix, why is this PR needed? What usecases does it solve?
The same use case as reporting the ANNOUNCE in the first place, but it also gives an indication of when the other announces are happening - which may be useful when troubleshooting things like... Why does my server get removed from the server list after 5 minutes.

## To do

Ready for Review. Though... somewhat lazily, because I don't really have a C++ environment so I'm kind of hoping that the tests will catch anything. Heads up to any reviewers... this PR is more of a suggestion than something thoroughly tested!

## How to test

Start a server with announce enabled and stop it after 6 minutes. You should see a START announce, an UPDATE, and a DELETE.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Good idea. Are you sure that code outputs "START" as action? enums are just fancy numbers, thus a translation to string is needed.
What do you think about this?
```
(action == AA_START ? actionstream : infostream) << "Announcing '" <<
	aa_names[action] << "' to " << g_settings->get("serverlist_url") << std::endl;
```

-> Outputs `Announcing 'start' to https://example.com`

**Comment by Tyler-2** [comment]
Ah, makes sense! I like it. So, something like that?

**Comment by Tyler-2** [comment]
BTW how do you view the action stream?

**Comment by SmallJoker** [comment]
@Tyler-2 This is logged to your `debug.txt` file when the `debug_log_level` setting is `action` or more verbose. In my case, this line is only shown in the console (log level = `warning`).

Dedicated servers should be started from command line anyway: `minetest --server --worldname foobar`

**Comment by Tyler-2** [comment]
The Debian package allows you to run minetest as a systemd service, so it's trivial to run multiple servers. But I don't know how it handles debug.txt... I can't find one on my system. It seems the unit's journal is the `chat` level output. I guess `chat_log_level = action` would do the trick in this case. Will have to wait 'til it trickles down to the repos to know for sure!

Thanks!

**Pull request merged**
