### PR TITLE
Make installer create its own Minetest folder

### PR DESCRIPTION
**Pull request by LoneWolfHT**
Second small installer PR

This changes the installer to create its own Minetest folder instead of having the user create it themselves. This prevents spewing the contents of Minetest everywhere when users change the install directory and expect the installer to create a folder to put it in

I've also disabled zip creation when RUN_IN_PLACE is false because the setting I used to implement the above caused it to extract a minetest folder containing a minetest folder containing the minetest files. I assume the zip is equivalent to the RUN_IN_PLACE one anyway?

My editor also removed some unnecessary whitespace it found
#
Screenshots of what the install process looks like and results in:
image

image

This won't allow renaming the folder during install but I don't think most users care about that. You can only have one version of Minetest downloaded with an installer at a time anyway AFAIK

### CODE REVIEW

**Comment by SmallJoker** [comment]
Is `Minetest-5.4.0-dev` the standard naming? What if people want to upgrade their installation? Will it remove the old files and install Minetest into the new location, or is that not intended?

**Comment by rubenwardy** [comment]
Yeah, the folder name should just be "Minetest"

**Comment by LoneWolfHT** [comment]
It looks like you can only have one version of Minetest installed via the installer at a time.
Updating works fine regardless of where you installed to. The installer doesn't need the user to tell it where Minetest is

**Review by SmallJoker — APPROVED** [review]
Looks good.

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
