### PR TITLE
Initial compatibility layer diagram

### PR DESCRIPTION
**Pull request by brylie**
Diagram showing compatibility layer that would allow resources to be sharred between voxel game engines/projects.

Related to discussion #6322

### CODE REVIEW

**Comment by Ferk** [comment]
This PR is not gonna be merged, there's already an issue open to discuss this.
It doesn't make sense to add documentation for an architecture that does not exist.
And even if it did, the diagram is too simple to be of any real use for it to be distributed with the code.

Creating an API that can be easy to implement for several engines requires knowledge of the innards of several of the engines and collaboration between the developers.

If you really want this I suggest you contact the teams from different voxel engines that are willing to add an extension API, have them look at Minetest's API and get them to point out the weaknesses of our current API and what aspects would make it more portable/flexible.

**Comment by paramat** [comment]
screenshot from 2017-08-29 17-34-00

**Comment by nerzhul** [comment]
i'm not interested in this, we have many things to do in core engine than thinking about a "cooperation" with terasology, our 0.5.0 is currently in heavy development and our roadmap is huge

**Comment by paramat** [comment]
:-1:

**Comment by nerzhul** [comment]
i don't see any issue on terasology github about a such relation, and i see you are not a terasology dev member, i think it's more utopist than realistic, sorry :(

**Comment by brylie** [comment]
> It doesn't make sense to add documentation for an architecture that does not exist.

The diagram is meant to help clarify the general goal of a compatibility layer, and is necessarily abstract. If we agree that other projects can adopt the Minetest API, then the architecture does, to some extent, exist.

> we have many things to do in core engine than thinking about a "cooperation" with terasology

Simply merging the diagram would not supersede any priorities of the Minetest developers.

**Comment by Ferk** [comment]
> The diagram is meant to help clarify the general goal 

Rather than clarify, this is prone to cause confusion. There's no place anywhere in the diagram that would make anyone think that this is a goal that has not been reached yet and that would probably take years to reach. It also uses terminology that is not seen or defined anywhere (like "plugins").

Check out the docs folder that you committed this to. The docs there do not state goals at all, they are meant to help understand the currently implemented architecture, people looking at the docs folder are likely to be confused by this diagram.

I still think it's best if you communicate with Terasology, we don't even know if they are interested one bit. Maybe they don't like Lua and any further work would be for nothing, so I'd say that should be the first thing to do.

**Comment by brylie** [comment]
> I still think it's best if you communicate with Terasology, we don't even know if they are interested one bit. 

I am planning to reach out to the Terasology devs, after fleshing out the idea a bit with the Minetest devs. 

This diagram is just a work-in-progress to reflect the current idea. I am glad to make changes to the diagram based on feedback, hence this pull request.

**Comment by rubenwardy** [comment]
> Are there any folders for design work? I.e. when planning a feature, where do the Minetest developers keep design documents?

dev.minetest.net

**Comment by paramat** [comment]
> I am planning to reach out to the Terasology devs, after fleshing out the idea a bit with the Minetest devs.

No MT core devs are remotely interested in rewriting MT to have a compatibility layer with Terasology, and i expect Terasology devs will be the same. Although some kind of simple co-operation might happen, MT core devs are not particularly interested in any kind of co-operation. So i can't see any fleshing out with devs happening, and no consensus is happening in your issue because there is no support.

So to avoid possibly wasting your time you should communicate with Terasology before anything else.
Adding this diagram now (or at any time) is ridiculous.

**Comment by rubenwardy** [comment]
A compatibility layer sounds more like an external third party project

**Comment by brylie** [comment]
> No MT core devs are remotely interested in rewriting MT to have a compatibility layer 
> core devs are not particularly interested in any kind of co-operation.
> no consensus is happening in your issue because there is no support.

@paramat your comments continue to be counter-productive, and misrepresent the idea of collaboration. 

Please refrain from projecting your opinions onto other people. Please also be respectful of other people's ideas/perspective, even though you may not understand or agree.

**Pull request closed without merging**
