### PR TITLE
Restore intended functionality to minimap markers

### PR DESCRIPTION
**Pull request by theviper121**
Add compact, short information about your PR for easier understanding:

Restores proper markers to the minimap

This PR is Ready for Review.

## How to test

View minimap with other objects around.

### CODE REVIEW

**Comment by ClobberXD** [comment]
@theviper121 What problem does this PR fix?

**Comment by SmallJoker** [comment]
@ClobberXD As soon an irrlicht node is attached, `getPosition` returns the position relative to its parent. This PR now shows all objects with nametags correctly.

**Comment by jastevenson303** [comment]
In my recent experience markers are not where the other player is.  It's
wrong -- is that what this fixes?

**Comment by ClobberXD** [comment]
@SmallJoker Thanks for the explanation :)

Upon testing, players are observed to be correctly marked on the minimap now. This PR works. :+1:

**Pull request merged**
