### PR TITLE
Add configurable key bindings for selecting next/previous hotbar item and changing the volume

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds configurable key bindings for:
- selecting next item in hotbar (default: `N`)
- selecting previous item in hotbar (default: `B`)
- increasing volume by 10% (default: `.`)
- decreasing volume by 10% (default: `,`)
- muting (set volume to 0%) (default: `M`)

The key bindings for hotbar item selection are additional to the number keys and the mouse wheel key binding; they do not replace them.

New `keymap_` settings are provided. Also the keybinding menu contains the new key bindings.

### CODE REVIEW

**Comment by est31** [comment]
* I think, if audio is already muted, the mute key should serve the role as unmute.
* There have been attempts to make the actions of mouse buttons customizable ( #2382 -- another rotting PR). If we have customizable mouse buttons (and wheel), one will need to be abled to assign the actions to keyboard keys too.

**Comment by paramat** [comment]
>     selecting next item in hotbar (default: N)
    selecting previous item in hotbar (default: B)
    increasing volume by 10% (default: .)
    decreasing volume by 10% (default: ,)
    muting (set volume to 0%) (default: M)

I feel these are not important enough to justify more key-press checks, for hotbar we already have number keys and a possible mousewheel.

**Comment by Wuzzy2** [comment]
Is there any real problem with having more key-press checks? Are they very “expensive” or what?

**Comment by kilbith** [comment]
> Is there any real problem with having more key-press checks?

Yes, they might be used for something else in the future and some of your suggestions add redundancy and are pointless (eg. the next/previous item keys - we already have the numbers and the mouse scroll, _dammit_).

The sound keys handling might be useful, though.

**Comment by Wuzzy2** [comment]
Too bad none of the mouse buttons/wheel can be re-assigned at the moment, also nothing can be mapped to mouse. :-(

Whatever. Do you want me to remove the keybindings for hotbar stuff? It would strip away some configurability as well.

BTW: Is it possible to explicitly assign nothing by default to a non-essential function? This might help reduce the number of occupied keys by default, while still leaving the possibility for players to customize for their needs.

**Comment by paramat** [comment]
> Is there any real problem with having more key-press checks?

I agree the extra processing is a tiny amount, but control checks are at a high frequency, and as a principle controls should be kept at a minimum and only be added for essential features. I agree we need game volume control in the pause menu, but it's not important enough to be another control.
Carbone should not have used a larger hotbar (and the option perhaps should not have been added) knowing so many people do not have a mousewheel. So the number keys are good enough.

**Comment by everamzah** [comment]
In Quake, you just /bind whatever key to whatever action you want.  This is lunacy!

**Comment by paramat** [comment]
I'm neutral now.

**Comment by Ekdohibs** [comment]
Replaced by #5598

**Pull request closed without merging**
