### PR TITLE
Docs: add missing backticks

### LINKED ISSUE #12420: Ultra-Minor Lua_API.txt correction
https://github.com/minetest/minetest/blob/213d3562bd29805e0bc8549a4e9e3aa2bf0f0349/doc/lua_api.txt#L4554

The line should read instead: (note the added closing backtick)
```
* `on_deactivate(self)`
```

### PR DESCRIPTION
**Pull request by Zughy**
Fixes #12420 

## To do

This PR is Ready for Review

## How to test
You should have a vast knowledge about how quaternion interpolation works, possibly flanked by a degree in astrophysics, to correctly verify that the operations inside the PR are indeed correct

### CODE REVIEW

**Review by appgurueu — CHANGES_REQUESTED** [review]
The turing machine has halted and I have come to the conclusion that this is indeed a much-needed correction. However I am concerned about the possible implications for backwards compatibility.

**Comment by SmallJoker** [comment]
As a Minetest member you might as well push trivial commits to master after announcing them on IRC (see dev wiki).

**Comment by rubenwardy** [comment]
> As a Minetest member you might as well push trivial commits to master after announcing them on IRC (see dev wiki).

Triagers don't have push/commit access

**Comment by appgurueu** [comment]
You missed the missing backtick on line 1195: ``* If `paramtype2="[color]wallmounted":``

**Comment by Zughy** [comment]
@appgurueu you're right, I should have avoided skipping my astrophysics classes that often, thanks for your calculations! Fixed

**Pull request merged**
