### PR TITLE
Minor tweaks __builtin:falling_node

### PR DESCRIPTION
**Pull request by Rui914**
･Remove unnecessary process
･Check staticdata in on_activate

### CODE REVIEW

**Comment by celeron55** [comment]
I restarted the travis build because it had failed due to some obscure key error.

**Comment by Ekdohibs** [comment]
Looks good

**Comment by est31** [comment]
4124e360cb676f68ee0d20ff7f9282f8f80f44c7

**Comment by celeron55** [comment]
(I tested this too, but est31 caught me up in merging it because I became tangled within a mess of git branches when I tried to do it in my outdated local repository... 8))

**Comment by est31** [comment]
lol

**Pull request closed without merging**
