### PR TITLE
Mark multiply and divide with two vectors as deprecated (Schur product and quotient)

### PR DESCRIPTION
**Pull request by Desour**
- `vector.add` with a scalar in the second argument and mul with two vectors (and sub and div) is very unnatural and useless.
Who needs the Schur product or quotient or a value added or subbed to/from all components?
I do not think that I have seen them being used in code anywhere.
- Therefor these functions are marked as deprecated.

## To do

This PR is a Ready for Review.

## How to test

Look at the documentation.

### CODE REVIEW

**Comment by paramat** [comment]
> Who needs the Schur product or quotient or a value added or subbed to/from all components?

These have always seemed odd and near useless to me too.

**Comment by sorcerykid** [comment]
I disagree. Adding or subtracting with a scalar as the second argument can be useful in applications where a radius is provided, and one simply wishes to compute the minimum and maximum positions from a position.

Here's a code snippet from my Protector Redux mod: 

```
local function lock_area( meta, source_pos, content_ids )
        local pos1 = vector.subtract( source_pos, config.protector_radius )
        local pos2 = vector.add( source_pos, config.protector_radius )

        local voxel_manip = minetest.get_voxel_manip( )
        local min_pos, max_pos = voxel_manip:read_from_map( pos1, pos2 )
        local map_buffer = voxel_manip:get_data( )
        local voxel_area = VoxelArea:new( { MinEdge = min_pos, MaxEdge = max_pos } )
```

It's kind of nice not having to create a temporary vector just for two statements, or to code it verbosely as 

```
        local pos1 = vector.subtract( source_pos, {
                x = config.protector_radius,
                y = config.protector_radius,
                z = config.protector_radius )
        local pos2 = vector.add( source_pos, {
                x = config.protector_radius,
                y = config.protector_radius,
                z = config.protector_radius )
```

In my view, I think having shorthands even if used infrequently can make code easier to understand and maintain.

**Comment by pyrollo** [comment]
When I first saw `add` and `sub` with scalar, I first thought this was useless. Then I saw how it was used in some code. Now my opinion is the same as Sorcerykid.

These two forms should not be deprecated as they are quite useful.

For `mul` and `div` forms, it's important to figure out if it's really useless.

**Comment by Desour** [comment]
Ah, I see, the weird add and sub are used for making cubes.
(I would probably not use it in such situations because giving three values is more clear and lies the emphasis on it being a cube.)

**Comment by paramat** [comment]
Good input, i did not think of radii.
I agree, we should only possibly deprecate the Schur product/quotient.

**Comment by Desour** [comment]
Another problem with the Schur product is that it would not be associative with the matrix product (if we will have it at some point):
```
((m * v) * w).x = (m[1][1] * v.x + m[1][2] * v.y + m[1][3] * v.z) * w.x
(m * (v * w)).x = m[1][1] * v.x * w.x + m[1][2] * v.y * w.y + m[1][3] * v.z * w.z
=> (m * v) * w != m * (v * w)
```

I'll remove the change to add and sub.

**Comment by pyrollo** [comment]
According to wikipedia Schur product "appears in lossy compression algorithms such as JPEG". Not likely to have a JPEG compression algorithm in Lua :)

**Review by pyrollo — APPROVED** [review]

**Comment by rubenwardy** [comment]
I reckon that `+` shouldn't support schur product at all, and there should be method for different types of product (dot, schur, ..)

**Comment by Desour** [comment]
> I reckon that `+` shouldn't support schur product at all, and there should be method for different types of product (dot, schur, ..)

You mean `*`.
I agree.
Should I add a `vector.schur` in this PR for replacement (just in case anyone needs it).

**Comment by paramat** [comment]
> Should I add a vector.schur in this PR for replacement (just in case anyone needs it).

Nah ... i doubt it is much needed, we could always add one later if users complain.

:+1:

**Comment by FreeLikeGNU** [comment]
I just noticed the commit and I use `vector.add` and `vector.multiply` for my witches spell effects:

```
local new_target_pos = vector.add(target_pos, vector.multiply(vector.direction(caster_pos, target_pos),strength))

new_target_pos.y = target_pos.y + height

target:set_pos(new_target_pos)

witches.magic.effect_line01(caster_pos,new_target_pos,50)
```

**Comment by sfan5** [comment]
`vector.add` is not affected by this.
And assuming `strength` in your code is a number, your use `vector.multiply` is not affected by this either.

**Comment by FreeLikeGNU** [comment]
Ah OK, I misunderstood.  My apologies.

**Comment by appgurueu** [comment]
Big mistake. I use this to scale vectors (to reverse the effects of visual scale, for instance).

**Comment by Desour** [comment]
There's always the possibility to change the docs again to make the schur product non-deprecated.
It was probably indeed a bad idea to make a PR just to mark something deprecated (considering it won't be removed in the foreseeable future anyways).

**Pull request merged**
