### PR TITLE
Use GitHub issue forms

### PR DESCRIPTION
**Pull request by rubenwardy**
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

image

## How to test

https://github.com/rubenwardy/issue_test/issues/new/choose

### CODE REVIEW

**Comment by rubenwardy** [comment]
Not sure the headings there actually help, might remove them

**Comment by hecktest** [comment]
Yuck, bureaucracy. Can we not?

**Comment by rubenwardy** [comment]
We already do the exact same thing with the issue template. This just makes it user friendly

It's not bureaucractic to request needed information in advance

**Comment by hecktest** [comment]
Required fields aren't very user friendly, they're annoying. Sometimes the OS isn't relevant and you know it, and sometimes a description of a bug suffices to reproduce it. The version and OS can usually be tucked away into one neat line of text, this will probably blow them up into half a page with huge headers. What for? This doesn't even prevent someone from just filling unnecessary fields with garbage in protest (or in confusion), and if it's an otherwise legitimate bug report, what do we do - delete it? Refuse to fix the bug? Ban the user? Spend our own time hammering it into the right shape? Who wins here, who does this serve?

Templates like these are good for corporations with dedicated testers who go through dozens of these daily and mindlessly execute the repro steps and tick boxes; we don't need to cargo cult that. Do what you will but be warned that you'll see less bugs submitted overall for each speed bump you add, this is basic UX. Some people just don't like filling out forms. It's degrading. We already have a template, does rigidly enforcing it actually provide any value? Just becaue GH has a feature, do we need to use it?

The feature request form is even dumber, how does a post like #11366 fit into that?

**Comment by v-rob** [comment]
Well, if the OS doesn't matter, put in "Any".  Summary and steps to reproduce should always be there.  However, I kind of agree that some feature requests can't fit into the feature request form without looking weird, although I guess it probably wouldn't be too hard to put a cursory thing under "Problem" and everything else in "Solutions" for things like #11366.

**Comment by rubenwardy** [comment]
I can only use a form for the bug report; the feature request has fewer fields and can work with just prefilled headings as it is now

**Comment by hecktest** [comment]
Just look at #11404 for a fine example of the bug template at work. Everything except the summary is just noise. What's wrong with letting the submitter wipe the template clean if it's not helpful, like we're able to do now?

**Comment by v-rob** [comment]
True, but there's very little noise.  Is a few lines of noise that are easy to ignore and easy to type (four, in this case: the "OS / Hardware" heading and the "Steps to Reproduce" heading) that bad in comparison to issues that leave out necessary information, especially the person wiping the template clean out of laziness?

**Comment by Warr1024** [comment]
I'm a little skeptical about the value of separate CPU, GPU, and OS fields.  Especially for mobile users, they're unlikely to know a lot of these specifics and "manufacturer and model" are more relevant for them.  I'd like to think there might be a way to express those questions such that somebody who doesn't know the technical details can still write a useful bug report.

A good bug report should always have (1) what you did, (2) what you expected, and (3) what you observed.  Those are clearly covered above, but it seems a bit awkward to me to have 2 crammed into 1 field and not have them in chronological order.  How sure are we that this is the best way to structure/order them?

**Comment by wwar-XeStro** [comment]
> Just look at #11404 for a fine example of the bug template at work. Everything except the summary is just noise.


I like keeping things simple, the issue you have mentioned (which i made) is related to controls in android as you can see, so the version of it CPU, GPU or whatever will not make change as this is how the controls work, not to mention i've tried multiple devises, also when you join a minetest server, you will see almost every android user complaining about the controls, so i do not see why that section is even needed in my issue.


About the version part, i've wrote the latest version i've experienced that issue with and said that every version because the android controls were never good, in 0.4x times it was even worse as the ability to sprint was not there which was added in 5.0 aswell as the ability to pess hold(use left click) while walking.. so even in this i do not see why the version can make any kind of noise, i wanted it simple, just the latest version i've tried. Also it is good to mention, i typed that issue with lots of support from a core dev :)


The steps to reproduce part, i've mentioned "play on android",  pretty simple yeah? in the summary part I'm talking about that we can not hit/dig while using sprint or sneaking, so i *thought* it is pretty understandable that when i say play on android, i mean join the game with any android devise that supports minetest and try to dig while sneaking.. i do not understand what you are talking about, everything i've mentioned was quite simple.. thank you o/

**Pull request closed without merging**
