### PR TITLE
Use nullptr everywhere

### PR DESCRIPTION
**Pull request by numberZero**
Should work.™

~If this does not compile, NULL was used wrongly somewhere.~

~Disclaimer: this is mostly `sed`’s work. That is why comments are affected. But strings should remain intact, esp. those with legitimate NULLs (i.e. SQL queries).~

### CODE REVIEW

**Comment by sfan5** [comment]
> That is why comments are affected. 
So comments about SQL now talk about this foreign concept called "nullptr", great.

**Comment by numberZero** [comment]
@sfan5 really? will fix right now. I thought I edited *these* files manually only.

**Comment by sfan5** [comment]
oh, didn't know you edited those manually
That's fine then.

**Comment by numberZero** [comment]
Now I’m a bit too sleepy to check the code; will do that tomorrow. Will probably fix some comments that became badly sounding.

**Comment by nerzhul** [comment]
Are you use C interfaces are compatible with nullptr ? I'm pretty sure it's not because NULL != nullptr and there are some comparison with NULL inside them.
the only compat possible is : if (!var) which has the same result with nullptr and NULL

**Comment by numberZero** [comment]
I should probably never code when I’m sleepy.
In this version I used a special parser, so that comments and strings are all kept intact now.

@nerzhul I don’t understand what you write. But remember that there is only one null pointer of each type, and both `NULL` (which is defined as literal 0 in C++) and `nullptr` (which has its own type, `nullptr_t`) are implicitly converted to it. That is, `(T*)NULL == (T*)nullptr` for any T (although `NULL != nullptr`)

**Comment by rubenwardy** [comment]
What actual improvement does this give? Because it seems like this will just cause issues with libraries without much gain

**Comment by numberZero** [comment]
> will just cause issues with libraries

What issues? `nullptr` and `NULL` are interchangeable *in proper (i.e. pointer) context*. The advantage of `nullptr` is that it can’t be used in non-pointer context, while `NULL` technically can, although not intended to. As MT with this patch compiles, `NULL` was used in pointer context only. (The only possible exception might be a function that have overloads [thus C++, not C] for pointer and integer argument, and was called with `NULL` (that is, integer). But such call should be considered a bug by itself IMO).

The advantage of changing everything to `nullptr` is consistency, as both `NULL` and `nullptr` are used currently. Actually, I don’t keen on this; I just feel that it’s better to do that once and forget `NULL` forever.

**Comment by numberZero** [comment]
Rebased.
Actually now I have a script that replaces `NULL` with `nullptr` in code only, not touching strings and comments, in given files (thus keeping plain C code intact), so rebase is not a problem.

**Comment by paramat** [comment]
Closed because too difficult to rebase?

**Pull request closed without merging**
