### PR TITLE
Minimap: "North" indicator arrow for circle minimap

### PR DESCRIPTION
**Pull request by sofar**
Replaces: #3730

This adds a simple, and small "North" indicator to the circular
minimap. The indicator is in a classical triangle-like arrow with a
little bit of shading to accentuate the shape and give it a little
bit depth. The indicator is stuck exactly at the edge as far outwards
as possible, and is not too intrusive but still easy enough to spot.

### CODE REVIEW

**Comment by sofar** [comment]
http://i.imgur.com/QuTR4Or.png

**Comment by nerzhul** [comment]
:+1:

**Comment by Zeno-** [comment]
:+1:

**Comment by DonBatman** [comment]
:+1:

**Comment by 0-afflatus** [comment]
:+1:

**Comment by ObaniGemini** [comment]
:+1:

**Comment by indriApollo** [comment]
:+1:

**Comment by C1ffisme** [comment]
Wow. You actually found the (very simple, actually) way to make it multi-lingual!

:+1:

**Comment by paramat** [comment]
:+1:

**Comment by sfan5** [comment]
:+1:

**Comment by Fixer-007** [comment]
Neutral %)

**Comment by kaadmy** [comment]
:+1:

**Comment by kilbith** [comment]
:facepunch:

**Comment by SmallJoker** [comment]
:+1:

**Comment by nerzhul** [comment]
Merged af799d4bd2d277a108154f815ff6b6b7a8394a9a

**Comment by Dragonop** [comment]
:+1:

**Comment by PilzAdam** [comment]
This is labeled incorrectly. It has four approvals, not two.

**Comment by ObaniGemini** [comment]
@PilzAdam : Then you should create 6 other labels :p

**Pull request closed without merging**
