### PR TITLE
Biome API: Enable decorations placed on water. Add schematic decoration force place flag

### PR DESCRIPTION
**Pull request by paramat**

### CODE REVIEW

**Comment by paramat** [comment]
Needs more testing before i push this.

**Comment by C1ffisme** [comment]
Decorations on water? Very nice. What mods are you and all mapgen makers planning?

I hope this gets merged! (Translation : :+1: )

**Comment by paramat** [comment]
None at the moment, but this enables lily pads.

**Comment by C1ffisme** [comment]
I'm starting to see this being used to add sailing boats you can raid, see dungeons, bouys...

Maybe for another pull request, what about decorations in the air?

**Comment by paramat** [comment]
Ah good ideas, and using the 'force placement' flag the hull and air witin the boat will now replace the water. also make sure to use the 'place centre y' flag such that the centre of the schematic is at water level.
Air decorations are much more difficult to code though so i'm not keen on implementing that.
This pull is now merged, despite what the messages in this thread say.

**Comment by ShadowNinja** [comment]
c7454d4732dee0f7364ccb8e07002df1a037b94d

**Pull request closed without merging**
