### PR TITLE
Fix grammar in registration confirmation dialog

### PR DESCRIPTION
**Pull request by srifqi**
See https://github.com/minetest/minetest/commit/792752997c5ae2aaa4f54d0a2e2af2a96d7d1e9f#r26833999

screenshot

### CODE REVIEW

**Comment by Ezhh** [comment]
Nice changes :)

Usually for something like the last part, you'd directly tell the user to "click <button name>" to confirm an action. (Yes, there are people who would otherwise retype their name then sit there staring at it.)

**Comment by paramat** [comment]
:+1:

**Comment by srifqi** [comment]
`"Please retype your password and click Register and Join to confirm account creation or click Cancel to abort."`

**Comment by Ezhh** [comment]
@srifqi Yes, that would be better and would conform to popular standards for user documentation.

**Comment by paramat** [comment]
The suggested change is ok for me.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
670f8afd1896c2a88d6aec926a82d561a8478412

**Comment by SmallJoker** [comment]
@Ezhh 
> Usually for something like the last part, you'd directly tell the user to "click < button name >" to confirm an action.

The user sees two buttons named "Register and Join" and "Cancel" - how difficult is it to click the right one to get the desired result? Mentioning the buttons in the text is nice but kinda superfluous, as they're labelled understandable and clear in their effect.

> (Yes, there are people who would otherwise retype their name then sit there staring at it.)

The text already mentioned the password and the only input field there hides the letters with asterisks. Nothing will help if that's not clear enough for players.

---
Just wanted to comment this request - the grammar fixing part of this PR is/was totally okay.

**Comment by Ezhh** [comment]
@SmallJoker When the choice is made to provide instructions, as it was here, they should be provided in full. I've worked on this kind of technical documentation professionally and this was always the expected approach, so I stand by what I said.

**Comment by jastevenson303** [comment]
This is UI, not technical documentation.

**Comment by Ezhh** [comment]
Technical documentation is used here as just a simple broad term for any kind of instructional material. This message is instruction to users. It doesn't matter if it happens to be in the UI.

If you honestly find it bad, just change it back.

**Comment by paramat** [comment]
It's fine as it is. It's not essential but the perfectionism and clarity is good.

**Pull request closed without merging**
