### PR TITLE
Fix media overriding regression

### LINKED ISSUE #12557: Mods can no longer override textures/media based on load order (devtest error)
##### Minetest version
```
Minetest 5.6.0-dev-d400a98ef (Linux)
```

##### Summary
screenshot_20220718_222429

##### Background

The dirt texture exists twice, possibly to test mod loading order in combination with texture overrides:
<pre>
./games/devtest/mods/basenodes/textures/default_dirt.png
./games/devtest/mods/unittests/textures/default_dirt.png
</pre>

suspect change: 06de82fd86678e0a1c260c67792c5cd192863edd

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #12557. Ruben replaced a [reverse iterator (`crbegin` & `crend`)](https://github.com/minetest/minetest/commit/06de82fd86678e0a1c260c67792c5cd192863edd#diff-24cd186c8d4fc53d29afe3e5c3b0a1c53fe9418edfb702996fc9a0ffdbbfa051L99) with a normal one. Reverted that and added a comment since this is a reregression (the second time mod media overriding was broken) so that this doesn't happen again.

### CODE REVIEW

**Comment by rubenwardy** [comment]
Would be nice to have a test for this in src/unittest/test_servermodmanager.cpp

**Comment by erlehmann** [comment]
I agree. If this has been broken twice, it should be tested in an automatic fashion.

Also, this commit is missing manual testing instructions. Just look at devtest and see that there are no error textures?

**Comment by appgurueu** [comment]
> I agree. If this has been broken twice, it should be tested in an automatic fashion.

Currently working on it (paths are a bit messy though; I suppose I'll go find the relevant paths using RegEx endswith).

> Also, this commit is missing manual testing instructions. Just look at devtest and see that there are no error textures?

See the linked issue (yes).

**Review by sfan5 — APPROVED** [review]
works

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
