### PR TITLE
Speed up some loops with OpenMP

### PR DESCRIPTION
**Pull request by MarkuBu**
This is just for testing. Currently only tested with GCC on Linux

### CODE REVIEW

**Comment by rubenwardy** [comment]
Related IRC discussion: http://irc.minetest.ru/minetest-dev/2016-06-19#i_4635046

**Comment by MarkuBu** [comment]
What are the real bottlenecks?

**Comment by asl97** [comment]
@MarkuBu afaik, network and the noisy objects.
you should probably ask on the irc since people who knows more about those bottlenecks are there.

**Comment by MarkuBu** [comment]
to really speed up noise someone has to implement simplex noise in OpenCL. But as far as I know no one wants simplex noise because of possible patent issues.

A little speed up would be an OpenMP implementation of perlin noise, but I have not the experience to do this. 

On the other hand: perlinMap3D is faster on my system then spreadLight() and I was able to reduce the time on a quad core more than half.

**Comment by Calinou** [comment]
> But as far as I know no one wants simplex noise because of possible patent issues.

[OpenSimplex](https://en.wikipedia.org/wiki/OpenSimplex_noise) could be used instead.

**Comment by MarkuBu** [comment]
I know. Maybe someone can port this

https://gist.github.com/tombsar/716134ec71d1b8c1b530

**Comment by HybridDog** [comment]
The github search field can be used:

https://github.com/jakogut/clsimplex
https://github.com/CJKay/OpenCLSimplexNoise ← obviously older

**Comment by paramat** [comment]
From what hmmmm says this is highly unlikely to be merged.

**Comment by MarkuBu** [comment]
> From what hmmmm says this is highly unlikely to be merged.
What exactly do you mean? OpenMP or Simplex Noise?

**Comment by paramat** [comment]
OpenMP. hmmmm is our technical mapgen and code architecture expert, and the dev who knows most about multithreading, so if he's not keen it's unlikely to happen.

**Comment by nerzhul** [comment]
:-1:

**Comment by MarkuBu** [comment]
Sorry, I accidentally mixed two pull requests

**Comment by kwolekr** [comment]
I don't understand how Simplex Noise would be "faster" than what we have now.  No idea what that discussion was about.  Not to mention, the output would be vastly different and completely break compatibility.

Anyway, about the PR itself:
 - A speedup of 1.6 milliseconds is not worth any of the future pain this change could bring in terms of support and maintenance requirements.
 - This patch would add a non-optional dependency on OMP support.  Do all supported compiler versions have OpenMP?  What about the distributions themselves?
 - The mapgen is already multithreaded but does not enable this by default due to issues with latency.
 - Also, what's up with converting *all* of the tabs to spaces in the files modified?  I'm not able to see the actual changes this PR makes.

Sorry, this is a big WONTADD.

**Comment by MarkuBu** [comment]
> A speedup of 1.6 milliseconds is not worth any of the future pain this change could bring in terms of support and maintenance requirements.

Please read the forum. This patch reduces the spreadLight function on a quad core from an average of 67ms to 28ms and the dungeons from 6.5ms to 3.8ms. And the 1.6ms are for each tunnel and each cave can have dozens of tunnels. 

> This patch would add a non-optional dependency on OMP support. Do all supported compiler versions have OpenMP? What about the distributions themselves?

Nearly any C++ compiler supports OpenMP and this patch changes absolutely nothing at the original code. Compiler without OpenMP just produce normal code.

> Also, what's up with converting all of the tabs to spaces in the files modified?

This was my fault. I use geany any my default setting was to convert any tab to space and normally I use two space for indent. I start a new clean repository with a branch for this. I close this issue

**Pull request closed without merging**
