### PR TITLE
Android: Do not submit text after pressing Enter key for multi-line text

### LINKED ISSUE #11225: Android: Can't Input Line Breaks in Formspec Multiline Text Fields
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: Android 10 (Lineage OS 17.1)

##### Summary

On the Android app, the "Enter" key is used for closing the popup editor window. So it is not possible to key in newlines when editing formspec multiline text input fields.

There is a workaround, but it is cumbersome: If you are using a keyboard, such as [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard), that can be opened without touching the formspec text input area, you can edit the formspec directly without opening a window.

A solution may be to have a setting to disable popup text input. Or dedicate the enter key to newlines instead of closing the popup (at least for multiline fields). The "Esc" key & Android action bar can always be used to close the popup window.

**Edit:** I think a simple workaround would be to have an option to disable the popup (if that doesn't already exist, I haven't checked). It would still be a bit cumbersome on small screens, but usable.

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
Make Android version able to write multi-line text.

**How does the PR work?**
The usage of the Enter key for submitting text is limited to single-line text (and password). Regular `EditText` is used (instead of `CustomEditText`) for multi-line text to not close the dialog after pressing the back button. A new button is added for submitting multi-line text.

**Does it resolve any reported issue?**
Yes, this tries to fix #11225.

## To do
This PR is a Ready for Review.

## How to test
There are many ways to test this. This is just one example.
1. Play any Minetest Game world in creative mode.
2. Pick a book from creative inventory.
3. Open the book by selecting it and tap-hold (left click).
4. Try to write the title and the content.
5. When writing the content, make sure that the Enter key is present in the IME and the back button only closes the IME.

### CODE REVIEW

**Comment by AntumDeluge** [comment]
There are still some issues on smaller screens. See my comments here: https://github.com/minetest/minetest/issues/11225#issuecomment-850933462

**Comment by AntumDeluge** [comment]
Seems to be working well now.

**Review by sfan5 — APPROVED** [review]
Looks good (not tested)

**Review by SmallJoker — APPROVED** [review]
LGTM

**Comment by AntumDeluge** [comment]
Please approve this for 5.4.2 ❤️

**Pull request merged**
