### PR TITLE
Server pushing media at runtime

### PR DESCRIPTION
**Pull request by sfan5**
Modders often want to send textures at runtime, which has previously used hacks like `[combine` to build a texture pixel by pixel.
Other suggested approaches are #9767, which packs pixels into a texture modifier (also bad) <i>or</i> adding a texture modifier that can read encoded PNG data.
The reason I dislike those approaches is that these workarounds can never be removed even if a proper solution arrives one day.

This PR implements (part of) "the" proper solution, which is:
* Mods can load additional media files at runtime
* New clients will receive them on connect
* Existing clients will have the files pushed to them, bypassing the usual media loading (e.g. caching or remote media)
* Mods can be sure that it is safe to use the texture immediately after calling `dynamic_add_media()`

## To do

This PR is a Work in Progress.

- [x] Should this apply to more than images?
- [x] Work out if client caching should/can be used
- [x] Figure out synchronization
- [x] Clean up code

## How to test

Standalone `/show` command that can show you images/audio/models ingame by specifying the filesystem path:
```lua
core.register_chatcommand("show", {
	func = function(name, param)
		if not core.dynamic_add_media(param) then return false, "error" end
		local basename = table.remove(string.split(param, "/"))
		local e = table.remove(string.split(basename, "."))
		basename = basename:gsub("%." .. e .. "$", "")
		if e == "ogg" then
			core.sound_play({name = basename}, {to_player = name})
		elseif e == "jpg" or e == "png" then
			core.get_player_by_name(name):hud_add({
				hud_elem_type = "image",
				position = {x = 0.5, y = 0.5},
				scale = {x = 1, y = 1},
				text = basename .. "." .. e
			})
		elseif e == "x" or e == "b3d" or e == "obj" then
			local pos = vector.add(core.get_player_by_name(name):get_pos(), {x=0, y=1, z=0})
			local entity = core.add_entity(pos, "__builtin:item")
			entity:get_luaentity():disable_physics()
			entity:set_properties({
				is_visible = true,
				visual = "mesh",
				visual_size = {x = 1, y = 1},
				textures = {"default_dirt.png"},
				mesh = basename .. "." .. e
			})
		else
			return false, "unhandeled " .. e 
		end
	end
})
```

For Crafter's skins mod:
```diff
diff --git a/mods/skins/init.lua b/mods/skins/init.lua
index c566736..c163786 100644
--- a/mods/skins/init.lua
+++ b/mods/skins/init.lua
@@ -114,13 +114,15 @@ end
 fetch_function = function(name)
     fetch_url("https://raw.githubusercontent.com/"..name.."/crafter_skindex/master/skin.png", function(data)
         if data then
+            local temppath = minetest.get_worldpath() .. "/skin_"..name..".png"
             local f = io.open(temppath, "wb")
             f:write(data)
             f:close()
 
-            local img = pngimage(temppath, nil, false, false)
+            local img = true
             if img then
-                local stored_texture = file_to_texture(img)
+                assert(minetest.dynamic_add_media(temppath))
+                local stored_texture = "skin_"..name..".png"
 
                 --print("===============================================================")
                 --print(stored_texture)
```

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
> Should this apply to more than images?

Depending on how long it takes to review and merge I'd say one at a time would work.

> Allow client to use its caching?

Maybe make it a setting? I can see being able to configure that would be useful

**Comment by Df458** [comment]
This seems like a very useful feature, but one more question that I think we should ask is:

How will this intersect with texture packs? A lot of dynamic textures probably need to be non-overridable (ie. skins, generated textures, that sort of thing). On the other hand, there are probably other use-cases where the textures *should* be overridable.

Any thoughts on this?

**Comment by rubenwardy** [comment]
What happens if you call this on `default_stone.png`?

**Comment by sfan5** [comment]
> > 
> 
> Maybe make it a setting? I can see being able to configure that would be useful

The question isn't so much whether we want to allow or not allow it. Leveraging client caching introduces additional complexity because the client will need to request the texture on its own and you might need to wait for that or swap the texture as soon as its available.

> How will this intersect with texture packs?

Currently texture packs apply even on dynamically sent media. I don't plan to change this.

> What happens if you call this on `default_stone.png`?

The server rejects it.
If somehow it happened anyway the client would replace the texture (I plan to disallow that) though nodes in the world wouldn't change their texture at all due to caching.

**Comment by Jordach** [comment]
@sfan5 allowing the sending of 3D models and sounds should be required in true honesty: I abhor having to exit Minetest, and then restart the world after exporting a model from Blender; or making changes to sounds with any DAW.

**Comment by oilboi** [comment]
Works great on Windows 10!

**Comment by Lejo1** [comment]
What about allowing per player media sending?

**Comment by DevyHeavy** [comment]
> Should this apply to more than images?
I think so. If meshes are done in someway than mods like [this (woolen mesh creator)](https://forum.minetest.net/viewtopic.php?t=20115) won't need a restart of the world to work, hopefully. 

Maybe this PR could help the development of VAEs on the Minetest roadmap as well?

**Comment by appgurueu** [comment]
Yes! Please! If possible, put this on the 5.3 milestone, can't wait to use it!

**Comment by sfan5** [comment]
This PR now addresses the initial usecase without doing everything people could possibly want:
* It is possible to dynamically load textures, sounds and models
* Media files can only be loaded additionally, existing ones can <b>not</b> be replaced
* The client will save the data to its cache for future server connects; there is an (intentionally) unused packet flag to disable this for possible(!) future use with server-generated textures

It's 271 line changes (w/o whitespace) and could reasonably possibly still get into 5.3.0

**Comment by appgurueu** [comment]
> The client will save the data to its cache for future server connects; there is an (intentionally) unused packet flag to disable this for possible(!) future use with server-generated textures

The main purpose of this would probably be server-generated media files. Therefore, you should consider making not caching the default.

Besides, an option for unloading media might be useful.

**Comment by oilboi** [comment]
I love this so much

**Comment by sfan5** [comment]
> The main purpose of this would probably be server-generated media files. 

Would it? A large usecase of this PR are player skins, which aren't generated by the server and reasonably static.

> Therefore, you should consider making not caching the default.

Since in this PR's current state you cannot "unload" added media, clients will have to redownload that media when rejoining a server so enabling caching makes perfect sense

**Comment by hecktest** [comment]
This is not a better replacement for string-embedded images and sounds; it solves a completely different (and more limited) problem domain.
Instead, ugly workarounds will be grafted onto this to do things that embedded assets would've solved elegantly. This is an exact opposite of a smart solution.

Consider a painting mod. Your solution will generate and upload a new image to every connected client for every pixel that the painter draws. Sounds pretty horrible. Same will be done for every snapshot of a signpost that's being edited. And the contents of every signpost and painting will be broadcast to every client.

Or, consider skyboxes that are generated based on a player's surroundings. Again, you do not want to send this to other players, or to keep those around at all.

Consider something like a captcha; yet again, there is no value in caching this or sending it to others.

The only things that seem worth doing with this API are, uh.... no, actually, I can't think of any use case for this that isn't horribly broken. Custom skins? How do you provide or edit them? Right... Do I have to download every custom file that a server has pushed in its lifetime when I log in? Downright horrible.

Dynamic assets are useful when they are ephemeral, and local.

**Comment by rubenwardy** [comment]
This is a good start, and a prerequisite to ephemeral and per-player dynamic media

**Comment by hecktest** [comment]
Well, no, you see, since those are files and they are handled and treated like files, we now must figure out a way to build PNG (size! dib won't cut it), OGG and X (or worse, b3d) files dynamically, from lua. Not an easy task by any means. Even if the engine provides this capability eventually, that's an unnecessary conversion step, and irrlicht might not provide encoders for those formats. Treating those like files is a logical mistake from the start, because none of the useful use cases need or want to deal with files.

Now consider the inverse, with a custom, optimized raw format embedded into a string. It's straightforward to generate the data dynamically, because this is the main mode of operation. No dependencies to encode files are needed, because zlib and base64 are already present in the engine. Temp names and handles are not needed, because the texture's content is its name. Locality isn't a problem, neither is replacement. The textures can still be mixed with modifiers as needed.
Functions could be provided to load irrlicht-compatible files into a raw representation for editing, but loading files from the disk is actually something you wouldn't do much of. (And, since you're doing the manipulation server side, you can reasonably handle it with a simple file format like ppm or dib.)

Magic strings would actually handle every use case from the get go. As it is, this PR can... uh, I don't know, let an admin add a new spiderman or grinch skin to his minetest_game without restarting the server? Pretty lame. Useful for debugging (if you do a whole awkward dance with new filenames), but it could be solved with a different API, specifically meant for a quiet update of the asset folder tree.

**Comment by sfan5** [comment]
> Your solution will generate and upload a new image to every connected client for every pixel that the painter draws

Correct, in its current state this feature is obviously not suitable for a painting usecase. See below however.

> signpost [...] skyboxes [...] captcha

Would you mind explaining how you came to assume that the feature this PR adds can never be extended or improved and will forever remain the way it is right now?

> Even if the engine provides this capability eventually, that's an unnecessary conversion step
> [...]
> Now consider the inverse, with a custom, optimized raw format embedded into a string. It's straightforward to generate the data dynamically

You call encoding a PNG an "unnecessary conversion step" but when it's a custom format it's suddenly not a problem anymore?

> No dependencies to encode files are needed, because zlib and base64 are already present in the engine. 

As you rightly point out the engine (even server-side) already has zlib, based on that it would be equally easy to write a simple PNG encoder.

> Temp names and handles are not needed, because the texture's content is its name.

Since the texture name would be its contents, how do you propose to solve the resulting inefficiency of having to resend the same texture over and over again when it already exists on the client?

<hr />
 
> let an admin add a new spiderman or grinch skin to his minetest_game without restarting the server? Pretty lame.

I am glad the rest of the community does not share your attitude of just complaining.
Everytime you report an issue or even just ask a question it shows that you think devs introduce bugs because they want to make your life harder or they are too incompetent, even new features are "lame" because you don't have an use for them.

**Comment by hecktest** [comment]
Great post, you addressed every problem I pointed out, except you didn't.
It's perfectly possible to graft asset streaming on top of this, just like it is possible to put a saddle on a cow and call it a horse.
Converting streamed, temporary assets to files at any point is brain damage. Do you have any idea how slow some decoders can be? (Bench the irrlicht mesh importers, and weep at the results.) Have you ever written an encoder yourself? Yes, using zlib on a bitmap results in a blob that's very similar to PNG, and it could be turned into a PNG by prepending a worthless header to it. That header will be pure dead weight. But we're just _lucky_ that the optimal way of sending images is so much like PNG; models, animations and audio will not be this easy to handle. Talking to irrlicht directly and using formats optimized for the job is much more sane than conjuring up files for the sake of... I don't know what. Are you just afraid of handling raw data?

You said something about not wanting to be stuck with a crippled solution until the end of time, but this is pretty dodgy. It's barely even related to the streaming problem.
When you're making a grand claim of inventing "the" proper solution and telling people to stop working on alternatives, and that they'll have to use your one true API to implement them in the future, be prepared for grand criticism to match. This community has a problem with shooting the messenger, and I happen to have this nasty habit of pointing out stupid when I see it. Upvote and heart one another all you want, call me a naysayer poopyhead, but I'm trying to _help_ here. My cranky attitude as of late has just been the result of each subsequent "stable" version exploding in my face even harder when tested. Where there's smoke, there's fire.

My advice is to salvage this code into an asset tree update API (very useful and nice and you'll be a cool guy and all the chicks on the internet will still like you), and stop trying to shoehorn streaming into it. Take it or leave it.

**Comment by sfan5** [comment]
> Converting streamed, temporary assets to files at any point is brain damage.

Who said you have to actually write a file to disk before sending it to a client?
Or does an image turn into a "file" as soon as it's encoded in PNG in your opinion?

> Talking to irrlicht directly and using formats optimized for the job

PNG is a format optimized for image handling, don't you agree?

> telling people to stop working on alternatives,

Please point out where I have said this.

> that they'll have to use your one true API to implement them in the future

Please point out where I have said this.

　
By the way, I also don't see an answer to this point from the last post:

> Since the texture name would be its contents, how do you propose to solve the resulting inefficiency of having to resend the same texture over and over again when it already exists on the client?

**Comment by hecktest** [comment]
String embedded textures are sent once per session, not over and over; caching them is usually not desirable because they're too volatile. These kinds of textures should be minimalistic anyway, counted in hundreds of bytes, which would not be heavier than a couple extra mapblocks being sent. Chances are they would be shorter than a ^[combine string building them out of named texture components. 
I'm talking here about something like one bit per pixel text.
If you're still concerned about efficiency, maybe the real, robust answer is to hash texture combining strings and cache their results.

>never said that
Calling this API "the" proper solution implies that you don't want things like ^[raw, and you call that a workaround. I don't have time to play github court proving who said or clicked what exactly; point is that this will now somehow close #6821 (why?), and #9767 has been canned in favor of this as well. So what I see is a good feature being snuffed out by a bad one.

**Comment by sfan5** [comment]
> String embedded textures are sent once per session, not over and over

Not really.
Every time you spawn a particle or particlespawner the entire texture name is sent. If you have an object, every time any of the properties changes the texture name is sent too.

But even if that wasn't the case (e.g. with the suggested hashing) consider this example:
You want to make a disco light that blinks in random colors, you have a 500 bytes texture built using whatever modifiers.
As soon as the color changes you have to send a new `...^[colorize:#aabbcc` texture, including the 500 bytes of data for the same base texture which the client already has.

> I don't have time to play github court proving who said or clicked what exactly;

<b>If you do not have "time" to substantiate your claims, do not claim that I have said things which I have not.</b>

> point is that this will now somehow close #6821 (why?),

It shouldn't, where do you see that?
image

> So what I see is a good feature being snuffed out by a bad one.

I think you are misunderstanding the description:
This PR addresses a common usecase\* by implementing native support instead of replacing a bad workaround (`[combine`) with a less bad workaround (`[image` or `[png` or ...).
It does not intend to cover every single usecase with dynamic textures and neither do I want to prevent the development of alternative approaches.

\* ask server owners about player skins if you don't believe me

**Comment by sorcerykid** [comment]
I'm very excited about this PR, in particular being able to push sound files to clients only as needed. That will help immensely with the DJ setup on my server as right now all audio tracks and samples have to preloaded by every client, which is obviously far from scalable.

> You want to make a disco light that blinks in random colors, you have a 500 bytes texture built using whatever modifiers.

It's interesting you bring this up since right now that is the exact approach I use for changinng colors of my disco ball and intelligent lights in my nightclub. How will this PR streamline those effects?

image

**Comment by sfan5** [comment]
> How will this PR streamline those effects?

Unless you use `[combine` to build the texture of the ball / lights on-the-fly, this PR won't change anything.
For your usecase it would be much better if entities provided hardware colorization so that clients wouldn't have to generate and cache countless textures with slightly different `[colorize` parameters.

**Comment by oilboi** [comment]
This is absolutely amazing, Excellent work!

**Comment by nerzhul** [comment]
PR is fine to me, great job

**Comment by KaylebJay** [comment]
Hopefully this will make it into 5.3.0! :)

**Pull request merged**
