### PR TITLE
Add black shadow to Android GUI controls, for light backgrounds.

### LINKED ISSUE #2456: Android GUI controls need shadows like chat text
GUI controls are currently plain white.  They get lost easily against a bright background, e.g. clouds in the daytime.  Adding a subtle shadow to them, like what was done for chat text in #1049, would improve visibility against all backgrounds.  Affects all current versions of the android build, up to and including 5698e2b.

### PR DESCRIPTION
**Pull request by Warr1024**
Resolves #2456.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
This should probably be done in code.

If not, a script to add the shadow should be added so that it's easy to add/change the images.  The originals should also be included so that they can be edited easily.

Maybe this could be done as part of the build process instead.

**Comment by MoNTE48** [comment]
IMHO these textures are terrible in themselves. I will ask my designer to draw something different and offer you.

**Comment by Warr1024** [comment]
The old images looked bad and were difficult to see.  These new textures look bad and are not difficult to see.  It sounds like an easy win to me.

Code would add complexity to the overall system and require maintenance, and this pull req does not add any code.  If you're thinking about how easily the original images can be edited in the future, then these images should have been SVG to begin with.  Adding SVG rendering to either the client or the build process, though, will not be trivial.

Independent of what you decide to do in the long run, merging these changes now will improve the interface now.  Merging this PR would allow us to have a less-bad interface while we're waiting to hear back from designers, or writing SVG renderers, or having bike-shed discussions, or whatever...

**Comment by Zeno-** [comment]
:+1:

**Comment by Warr1024** [comment]
Actually, the reason these images look so bad may be related to #2419, i.e. the fact that 2d image drawing is using nearest-neighbor scaling for non-integer resizing.  If we can fix that issue, the existing icons may look cleaner, as drawn on screen.

**Pull request closed without merging**
