### PR TITLE
Implement client node dig prediction

### PR DESCRIPTION
**Pull request by sfan5**
re-done #3891 because apparently nobody can be bothered

why is the prediction code _after_ the `on_dignode` callback?
`on_dignode` is supposed to say whether the node should be dug or not,
if it says not to dig the node prediction should not take place either.

### CODE REVIEW

**Comment by paramat** [comment]
The original was quite controversial, how have you resolved the issues?

**Comment by SmallJoker** [comment]
The implementation looks good. The different opinions about the CSM handling part in the previous PR weren't discussed to the death. @sfan5 prefers calling CSM first too, we should leave it this way.

:+1:

**Comment by sfan5** [comment]
5b3fbf9cf75f9f637c666d34e2489fef0cc035d9

**Comment by HybridDog** [comment]
@sfan5, I think you've missed something, as far as I can see there the server explicitly tests for air to decide if the mapblock needs to be re-sent: https://github.com/minetest/minetest/blob/6afbb06c7e552462ba2e682718488c9b13bfa0e5/src/network/serverpackethandler.cpp#L1287-L1294

If node_dig_prediction is "default:stone" but the dug node turns to "air" server-side, the mapblock is probably updated too late.

**Comment by sfan5** [comment]
Would you mind sending a PR to fix that?

**Comment by HybridDog** [comment]
I've tested it and the predicted node was immediately replaced with air each time after digging.
Sending the whole mapblock for each dug node only to inform the client that the prediction was right or wrong constitutes too much redundant overhead in my opinion, acknowledgements should suffice: #7602
That code is at least 4 years old, maybe all the mapblock sending is redundant now (needs testing).

**Pull request closed without merging**
