### PR TITLE
Add setting to customise stack max

### PR DESCRIPTION
**Pull request by rubenwardy**
eg:
```
default_stack_max = 34
```
in minetest.conf.

**To add this to a subgame:**

You should add the line to minetest.conf in your game's directory.
However, sometimes you may not want players to be able to override it.
To stop this, add the following lines before any items are defined:
```
minetest.nodedef_default.stack_max      = 123
minetest.craftitemdef_default.stack_max = 123
```

### CODE REVIEW

**Comment by HybridDog** [comment]
l would like this change.
:+1: 
:mouse2:        :mouse2:

**Comment by C1ffisme** [comment]
:+1:

**Comment by TheShadowZone12** [comment]
:+1:

**Comment by rubenwardy** [comment]
I will rebase soon.

**Comment by C1ffisme** [comment]
@rubenwardy BTW what is rebasing? I'm new to github.

**Comment by rubenwardy** [comment]
This code is a few months old, and since then the Minetest code has changed. Rebasing, in this context, is updating my code to work with the latest Minetest code.

**Comment by C1ffisme** [comment]
Ah. OK.

**Comment by rubenwardy** [comment]
Rebased.

**Comment by nerzhul** [comment]
just a question before i give you my +1, what happens if i reduce the max number and have greater stacks ?

**Comment by rubenwardy** [comment]
You don't lose any items. They keep in the too large stacks until you break
the stack up by taking items off. (For example if the new stack Max is 50,
you will still have above 50 stacks in the inventory, but you can't add to
them, only take off of them of move them.)

For an example, try /giveme stone 200 in current upstream master.

**Comment by nerzhul** [comment]
Ok then you have my +1

**Comment by PilzAdam** [comment]
I don't like that setting this in a mod only affects future registered nodes. If a mod wants to change stack_max, then it would need to go through all already registered nodes (from the game) and call override_item on them, which is quite ugly.

**Comment by rubenwardy** [comment]
In the current upstream you'd need to do exactly the same thing.

This pull request is aimed towards end-users and subgames. Mods can use the
method that they've used all along.

**Comment by ShadowNinja** [comment]
@PilzAdam That could be fixed by using metatables, if they aren't used already.  IIRC kaeza wrote a patch for that...

**Comment by rubenwardy** [comment]
Closing as it doesn't look like it's going to be merged

**Comment by benrob0329** [comment]
Why didn't this get merged? It had an overwhelming amount of 👍s !

**Comment by benrob0329** [comment]
Oh, nvm.

**Pull request closed without merging**
