### PR TITLE
10s timeout when connecting to server

### PR DESCRIPTION
**Pull request by SmallJoker**
Is a minetest.conf setting required for this feature?

### CODE REVIEW

**Comment by Calinou** [comment]
No, don't make settings for things that don't need it. If you need more than 30 seconds to connect to a server, your system *must* have something wrong. Even 10 seconds is very long already.

**Comment by nerzhul** [comment]
I agree with Calinou, configure this is useless and must only be managed by protocol itself, not user settings.

**Comment by SmallJoker** [comment]
This commit now also fixes a problem with new initialized `FpsControl` structs.

Successfully tested with MSVC on Windows XP.

**Comment by est31** [comment]
:+1:

**Comment by est31** [comment]
5f0b36b8b70faa36b20343342567471c8f50b7f2

**Pull request closed without merging**
