### PR TITLE
Distinct between 'walkable' and 'solid'

### PR DESCRIPTION
**Pull request by orwell96**
Collisions and 'attached nodes stick to' are 2 different things IMO.
I ran into this problem with my rails: I want them to be walkable (so you can walk them up like slopes) but don't want torches attached to them.
This adds the 'solid' definition key.
walkable: objects collide (only)
solid: attached (and falling) nodes stick to this node
the value of 'solid' defaults to the value of 'walkable'

### CODE REVIEW

**Comment by paramat** [comment]
I feel separating walkable and solid is going to be confusing because they have such similar meanings.

> I ran into this problem with my rails: I want them to be walkable (so you can walk them up like slopes) but don't want torches attached to them.

I don't feek this is enough justification, it's not much of a problem if torches can be attached to rails, this will rarely be attempted, and torches attached to the side of sloping rails is reasonable.

There needs to be more use case and justification for such a mojor change.

**Comment by C1ffisme** [comment]
@paramat One reason I can think of is if you were trying to make one of many 'authentic Minecraft subgames'. Certain nodes in Minecraft are 'transparent' and you cannot place torches, rails or some other nodes on top of them.

But, that's a not a reason worth the real effort. I think a better reason would be that having one setting do six things to a node's properties is a nightmare for documentation purposes. Having just one setting do one thing, (Walkable -> You collide with it, Solid -> Attached nodes stick to it.) is much more customizable, and much easier for someone documenting the API.

**Comment by paramat** [comment]
I think it's the opposite, this would add complexity for no good reason.
Preventing the placement of nodes on other certain nodes is a very minor issue, not really an issue at all. Best to allow it and leave it to the player to decide if it looks right or not, for example torch on glass (which i think should be allowed). And, i don't care about what Minecraft does :]

**Comment by orwell96** [comment]
I don't want to screw everything up. Torches on glass a.s.o is OK. That's why the 'solid' value defaults to the value of 'walkable': if you don't want, you don't have to set it.
I just think 'players and objects collide with this node' and 'attached nodes stick' are 2 completely different things which should not be affected by a single setting.

**Comment by orwell96** [comment]
Wait, the added clause in register_item should go behind the metatable setting!

**Comment by paramat** [comment]
More dev opinions?

**Comment by SmallJoker** [comment]
I can understand why you need this param but right now it only confuses. How can solid node not be walkable? That would also be possible with this code but sounds somewhat wrong. What I would like to see is a less confusing name: `mountable`, `sticky` or another if you have an idea.

**Comment by paramat** [comment]
:-1:
Generally, attached nodes can obviously be attached to walkable ('solid') nodes, and if something can be attached to a node that node will obviously be walkable, the 2 correlate closely.
You want to add another parameter for a very rare and specialist usage, instead you should write code into your node def to disallow attachment in certain situations.

**Comment by paramat** [comment]
Disapproved and no response from author.

**Comment by rubenwardy** [comment]
> Generally, if a node is walkable ('solid') you can obviously attach something to it, and if something can be attached to a node that node will obviously be walkable, the 2 correlate closely.

Not really true as walkable things can be less than a node box in size. Not sure what the torches code is like, but a group like "disable_node_attach" or similar may be a better implementation. TL;DR: this is better as a MTG issue

**Pull request closed without merging**
