### PR TITLE
Spread updating the drawlist over multiple frames.

### PR DESCRIPTION
**Pull request by lhofhansl**
ClientMap::updateDrawList can be expensive for larger distances. Easily 30ms or more on my fairly fast machine.

So this does two things:
1. Make the recursive culler "interruptible".
2. Give each invocation a 5ms budget. 5ms tested nicely (by itself it would still allow 200 FPS).

## To do

This PR is Ready for Review

- [x] Bit more testing
- [x] I have observed one-frame "flashes" when the camera pans around quickly. Probably due to the frustum culler re-fetched at each partial invocation.
- [x] Need to figure out how to store a lambda as member, or turn the frustum-culler into a struct/functor instead.
- [x] Check for memory leaks.
- [x] Think up a better heuristic for the time budget. Is 5ms always good? What about slower machines? Maybe allow for x% for the frame time?

## How to test

Load any world. Set a large view_range (and the matching server settings). I tried with 1000(!) and client_mesh_chunk set of 8 (but you'll see the improvement with smaller values too).
Observe how updateDrawList is smoothed out over multiple frame, reducing the visible jitter.

### CODE REVIEW

**Comment by lhofhansl** [comment]
This might be a bit hard to review. Basically:

- Calculating the visible blocks was moved from updateDrawList into a new class: VisibleBlockCalculator.
- Initialization was moved from the beginning of updateDrawList to the start method.
- updateDrawList now initiates the calculator to make partial progress upon each invocation.

**Comment by lhofhansl** [comment]
Fixed the panning issue by forcing a full drawList update when camera pans enough.
Also fixed a memory leak.

Of course that means that with camera panning there is no benefit. :(

**Comment by x2048** [comment]
> It this still worth it?

Of course! The stutter is most noticeable with continuous straight movement.

**Comment by lhofhansl** [comment]
One more stutter improvement: Do not update drawList and drawListShadow in the same frame (drawListShadow can take a few ms with many blocks)

**Comment by ndren** [comment]
Nit: Is it intended to be called VisbleBlockCalculator and not VisibleBlockCalculator? (Mostly curious!)

**Comment by lhofhansl** [comment]
@ndren Ehm. Yes. Lemme fix it.

**Comment by lhofhansl** [comment]
Minor cleanup and name fixes. I'll leave this now until some reviews.

**Comment by lhofhansl** [comment]
At view_range 1000 I have updateDrawList take almost 100ms.

**Comment by lhofhansl** [comment]
Another change: Made the budget for updateDrawList to be 25% of the frame drawtime. That was when drawing slows down the budget is increased.

I thought about more complex themes such as:
- Measure the total time one cycle of updateDrawList takes, and then spreading it out over frames such that it would take roughly 200ms, or
- Use the "blocks examined" count from the previous iteration, and divide by the number of frames that fit into 200ms, and then do that number blocks on each iterator

... but in the end this seemed not worse the effort.

**Comment by sofar** [comment]
Didn't review the code but I would try and write a simple heuristic that allocates a small budget to begin with and increases the budget when it exceeds it, but then scales it down dynamically when it drops below the allocation again. 

That way it auto scales based on need, and may handle system-to-system differences better, such as some other process consuming CPU cycles on the same core.

e.g. scale from 5% to 10%, 20%, 40% and cap at 80%.

**Comment by lhofhansl** [comment]
Thanks @sofar . The scale would have be found such that the overall thing finishes in about 200ms, so this would be a third option similar to the two I outlined above.

I feel like that would be more harm than good, and a budget based on the framerate is better and easier to track.

**Comment by lhofhansl** [comment]
Removed waiting for dependency...
See: https://github.com/minetest/minetest/pull/13225#issuecomment-1441207066

**Comment by lhofhansl** [comment]
Please review. :)

I think I would prefer to keep the budget logic as is and not make it fancier.
(I'd also be happy to cap an iteration to some number - 5ms or maybe 10ms, and be done with it.)

**Comment by x2048** [comment]
Would this PR still be needed with the latest changes in #13250?

**Comment by lhofhansl** [comment]
This is no longer needed.

**Comment by Desour** [comment]
Am I understanding it right that this was closed because #13250 improves the performance good enough that drawlist updates don't cause lag spikes?

--------

FYI, panning issues could easily be improved by using a larger fov for the frustum culler (=> rotates the planes). It currently just uses larger bounding sphere sizes (=> moves the planes), which probably works bad at higher distances.

**Pull request closed without merging**
