### PR TITLE
Mapgen: Add 4D fractal mapgen

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20150821_023205

### CODE REVIEW

**Comment by HybridDog** [comment]
maybe you could combine it with that to make it asymmetrical
https://github.com/slemonide/gen/blob/master/init.lua

**Comment by Amaz1** [comment]
This is awesome!
However, when I leave a world and then start it up again, something like this can happen: https://imgrush.com/_tcsomSicZ1U.png The terrain gets cut off and what hasn't generated is just air down to the sea. (It doesn't happen every time I stop a world, but when it does, I can get things to generate again...) I presume that this is unintended behaviour.

**Comment by paramat** [comment]
Oh crumbs that should not happen, will check this.

**Comment by paramat** [comment]
I managed to replicate your bug, and have now perhaps fixed it by stating the default parameters as floats by adding a '.0' to the end of them.

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by paramat** [comment]
Yes can replicate the bug, no idea yet of the cause. Each time the world is re-entered generation alternates between: no terrain, correct terrain, and a world completely full of terrain.

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by paramat** [comment]
Is Jenkins feeling ill? Recent PRs are all failing, this branch compiles for me.

**Comment by paramat** [comment]
Perhaps my use of 'get float no ex' to read parameters, or something to do with parameters in 'map meat txt', would explain why re-entering a world changes generation behaviour, i will try 'get float' instead.

**Comment by nerzhul** [comment]
@paramat i migrate jenkins host. Please note default on this pr is the android build

**Comment by paramat** [comment]
Often when the world is re-entered (exiting to menu and re-entering the world) generation alternates between: no terrain, correct terrain, and a world completely full of terrain.
Seems to affect julia mode more than mandelbrot mode.
Sea is unchanged so the bug is due to the 'get terrain at point' function.
The change of behaviour due to re-entering a wold makes me suspect something to do with how parameters are saved to and read from a world's 'map meta txt'. Perhaps something to do with data types, or how i use casts for x, y, z, or perhaps using floats instead of doubles in the ultra-sensitive ecursive function.

**Comment by paramat** [comment]
I get one failing check:
X jenkins-ci/android-nrz — Build finished. No test results found.
Perhaps this is due to what nerzhul wrote above:
> i migrate jenkins host. Please note default on this pr is the android build
This branch compiles and runs okay for me locally, so perhaps i can ignore that fail?

**Comment by paramat** [comment]
Unfinished and still has that mysterious bug, merged in hidden form so i don't have to keep manually rebasing e62eac49d590ca53fa250c0367dd9850729156b3

**Comment by nerzhul** [comment]
@paramat it seems you shouldn't ignore this portability issue and fix it. Every build from this commit fails now.
please fix it fast @paramat 
reported by @kilbith

**Comment by paramat** [comment]
@nerzhul i don't understand any of this, i haven't done anything to cause the default to be android build, i wouldn't know how to.

**Comment by PilzAdam** [comment]
@paramat I think you need to add the new file to the Android makefiles, too.

**Comment by paramat** [comment]
Ok will check.

**Comment by paramat** [comment]
Can't find any mention of mapgen files in build/android/Makefile.

**Comment by kilbith** [comment]
> Can't find any mention of mapgen files in build/android/Makefile.

... what's that ? https://github.com/minetest/minetest/blob/master/build/android/jni/Android.mk#L114

**Comment by paramat** [comment]
Thanks! will fix.

**Comment by paramat** [comment]
See #3233

**Pull request closed without merging**
