### PR TITLE
Make bitmap fonts work again

### LINKED ISSUE #11611: Remove (or preserve) non-TTF font support
XML code in IrrlichtMt was removed in minetest/irrlicht@729c214c003efb738c08f27817d569feb318dbf5, breaking this feature since we have PNG+XML [fonts](https://github.com/minetest/minetest/tree/master/fonts).
It would be possible to preserve this by switching XML out for a simpler text format that is read from Irrlicht. (stub code is still [here](https://github.com/minetest/irrlicht/blob/master/source/Irrlicht/CGUIFont.cpp#L65))

This is a reminder to either remove the remaining non-TTF code or do something to readd support *before* 5.5.0.

Removing non-TTF support has come up a bunch of times (see below) with the primary reasons being that almost nobody uses it, colored text does not work, bold/italic does not work and it only provides a limited character set.
* https://irc.minetest.net/minetest-dev/2017-02-14#i_4811037
* https://github.com/minetest/minetest/issues/9386#issuecomment-584288046
* https://irc.minetest.net/minetest-dev/2020-08-17#i_5722963

### PR DESCRIPTION
**Pull request by sfan5**
It was determined that *despite* nobody ever having done this, bitmap fonts can be used to get crisp pixel fonts in a way that TTF (currently) can't. So support has to stay for now.

fixes #11611
requires https://github.com/minetest/irrlicht/pull/78

## To do

This PR is Ready for Review.

## How to test

Build without freetype, start client.

### CODE REVIEW

**Comment by erlehmann** [comment]
1. You can disable FreeType at runtime.

2. The basic goal of having non-blurry pixel fonts seems to work.

3. I think that this change still breaks configurations that work in 5.4.1 (due to the filename change).

**Review by SmallJoker — APPROVED** [review]
Works. Tested with `freetype = false` using several font sizes.

**Comment by v-rob** [comment]
Please note: I disapprove of this unless it can be demonstrably be shown that bitmap fonts will not affect future Unicode support.

**Comment by erlehmann** [comment]
> I disapprove of this unless it can be demonstrably be shown that bitmap fonts will not affect future Unicode support.

I would expect the code paths to be separate, so what do you mean?

**Comment by v-rob** [comment]
Currently, Unicode codepaths are in `GCUITTFont` (arguably not the best place for it) and therefore bitmap fonts have no support for any Unicode outside of the BMP.  Moreover, Unicode depends heavily on not only character information, but also glyph information for laying out characters.  Bitmap fonts have _none_ of this glyph information, meaning properly integrating Unicode with them is significantly harder, if not impossible.

**Comment by erlehmann** [comment]
> There's a reason Freetype and other font libraries exist. Getting things right is hard.

@v-rob I am aware of such things. However, I do not understand how it would be a problem to improve the Freetype stuff, as long as no one expects bitmap fonts to be similarly powerful. I certainly would not expect any complex layout to work in a bitmp font – and if I need characters beyond the astral plane, I am willing to put in the work myself.

**Comment by v-rob** [comment]
Why should we implement language-specific features?  Making a font that only works with languages in the BMP without glyph substitution or surrogate pairs is just as bad as making a font that only works with ASCII.  You want a feature for your own benefit and don't care if it doesn't work for anyone else.

**Comment by erlehmann** [comment]
> Making a font that only works with languages in the BMP without glyph substitution or surrogate pairs is just as bad as making a font that only works with ASCII.

I have no idea what surrogate pairs have to do with this, but the only font I have meaningfully contributed to that is in wide use is GNU Unifont. It contains characters from the Astral plane to.

> It's OK that we don't have full Unicode support in Minetest yet because we have plans to fix it.

OK? In Minetest 5.4.1 I could see German umlauts rendered in the interface only with pixel fonts!
I have no idea why that is the case, but I am *probably* not the only user who figured that out.

> What is not OK is willfully adding features that exclude the possibility of full Unicode support.

This PR is not a new feature though: This stuff used to work and was broken by the removal of XML.
If the UCS-2 support in Minetest breaks somehow … would you also advocate for leaving it broken?

**Comment by v-rob** [comment]
> This PR is not a new feature though: This stuff used to work and was broken by the removal of XML.
> If the UCS-2 support in Minetest breaks somehow … would you also advocate for leaving it broken?

Of course not.  Unicode is an essential feature.  Bitmap fonts are not, as evidenced by the fact that **no one has cared that they've been broken on and off over the years!**  Seriously, if no one has cared, why should we keep it?  The _only reason_ this PR exists is because you've made such a big stink about it.  On the other hand, people would obviously care if Unicode broke entirely.

> It's OK that we don't have full Unicode support in Minetest yet because we have plans to fix it.

To clarify, it's not OK to have broken Unicode support, but the fact remains that we're trying to fix it, which is the important part.  You're advocating re-adding support for and maintaining something that is _fundamentally broken_ that _no one cares about_.  That's ludicrous, and I will continue to oppose it.

**Comment by v-rob** [comment]
Wait, wait, wait a minute; I made a discovery.  If the point of this PR is to allow crisp fonts... `CGUITTFont` already has crisp font support since it's built in for FreeType!  Flip one boolean in `fontengine.cpp` and your fonts are crisp:

```diff
diff --git a/src/client/fontengine.cpp b/src/client/fontengine.cpp
index f64315db4..74ece3b9f 100644
--- a/src/client/fontengine.cpp
+++ b/src/client/fontengine.cpp
@@ -309,7 +309,7 @@ gui::IGUIFont *FontEngine::initFont(const FontSpec &spec)
 #if USE_FREETYPE
        for (const std::string &font_path : fallback_settings) {
                gui::CGUITTFont *font = gui::CGUITTFont::createTTFont(m_env,
-                               font_path.c_str(), size, true, true, font_shadow,
+                               font_path.c_str(), size, false, true, font_shadow,
                                font_shadow_alpha);

                if (!font) {
```

And you get this for Minetest using the default TrueType font:

image
image

We can literally make a single setting `use_crisp_fonts`, and your fonts will automatically be crisp, no extra code needed.  No mucking around with bitmap fonts with Unicode problems and extra maintenance and the rest of that garbage.

**Comment by ExeVirus** [comment]
Interesting, 

So it just uses all or nothing raster as a setting, it's a lot better and basically as good as it mathematically can be for making a variable size font. 

If we could expose that option to modders in formspecs, that would be awesome. Also, eventually support ttf as media, but that's a different discussion.

**Comment by v-rob** [comment]
Another thing I'll drop here now: https://irc.minetest.net/minetest-dev/2021-12-09#i_5906260  This plus my last comment might invalidate the need for this PR.  I will look into it further as soon as I can.

**Comment by erlehmann** [comment]
@v-rob that sounds amazing! Feel free to ping me on IRC if I can help you testing this.

**Comment by erlehmann** [comment]
> This plus my last comment might invalidate the need for this PR

Only if someone does all the work of cutting out the pixel fonts & makes all the features that worked with it (like no colored fonts) work with TTF. It must also be impossible to get to the “no pixel font found but no freetype available” state so every user who activated this should have a seamless transition to a new version.

Since the next release is not a minor release, I see a clear path for deprecation of PNG+XML/TSV pixel fonts.

**Comment by v-rob** [comment]
#11848

**Pull request closed without merging**
