### PR TITLE
Fix typo in `builtin/game/register.lua`

### LINKED ISSUE #7421: on_grant and on_revoke callback bug
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-9f8582dc
Other data irrelevant.
```

##### OS / Hardware

Irrelevant.

##### Summary

./builtin/game/register.lua:448:
`			not def[priv]["on_" .. method](name, caller) then`
Should be:
`			not def["on_" .. method](name, caller) then`

'def' is the privilege's definition, so 'def[priv]' makes no sense. I was able to temporarily avoid this bug by adding a field to a privilege whose key was the name of the priv, and which contained the callbacks, confirming this is where the bug is from.

##### Steps to reproduce

Attempt to grant or revoke a privilege with on_grant or on_revoke callbacks.

### PR DESCRIPTION
**Pull request by numberZero**
Fix #7421

### CODE REVIEW

**Comment by paramat** [comment]
@rubenwardy

**Comment by numberZero** [comment]
Er, ...? This is in the Travis output:
```
Traceback (most recent call last):
  File "./util/travis/run-clang-tidy.py", line 271, in <module>
    main()
  File "./util/travis/run-clang-tidy.py", line 209, in main
    database = json.load(open(os.path.join(build_path, db_path)))
IOError: [Errno 2] No such file or directory: 'cmakebuild/compile_commands.json'
Clang tidy returned 1
```

**Comment by paramat** [comment]
That happens often, clang tidy is broken.

**Comment by nerzhul** [comment]
@paramat not exactly, the problem is clang-tidy is triggered when there is nothing changed in C++ code and the build doesn't like it :)

**Comment by sfan5** [comment]
90acb9b3a769fb949b7202b16e29418c945591a7

**Pull request closed without merging**
