### PR TITLE
Add mg spflags in dlg create world

### PR DESCRIPTION
**Pull request by srifqi**
Add special flags (`spflags`) in right of `mg_name` at create world dialog.
The `mg_name` is changed when you change your choice in the dialog, even when you press cancel.

### CODE REVIEW

**Comment by Zeno-** [comment]
This would  be better if it was a bit more user friendly...

**Comment by srifqi** [comment]
@Zeno- Like what? Another dialog?

@SmallJoker Thanks, you win again, as always, and thanks for fixing my "old" mistake. :D

**Comment by kwolekr** [comment]
The correct way to accomplish this would be to:
1). Query the flags supported by the setting
2). Create a checkbox control for each flag
3). Set each checked or unchecked based on the current setting value
4). When accepting input, reconstruct the flag string based on which settings are checked and which are unchecked

At the moment, there's no good way to query the flags supported by a setting at the moment. What might work right now is if you temporarily store the current value of the setting, numerically set the flags field to -1, read it back to get all available flags in the string format, then set the setting value back to what it was originally.

**Comment by srifqi** [comment]
@kwolekr: ._. *confused
A simple MORE explanation?

**Pull request closed without merging**
