### PR TITLE
Better Design for Dialogs ( Create World, Delete World, Rename Modpack, ...

### PR DESCRIPTION
**Pull request by fz72**
...Delete Mod)

after sapier changes to formspec, these dialogs are ugly on a window with 800 * 600. So I made the dialogs a little bit smaller.

### CODE REVIEW

**Comment by Jordach** [comment]
Screenshots of the change would be nice

-----Original Message-----

**Comment by fz72** [comment]
New:
bildschirmfoto vom 2015-01-26 16 27 38

Old:
bildschirmfoto vom 2015-01-26 16 28 19

**Comment by CraigyDavi** [comment]
This is a bug, most of these GUI elements shouldn't be this big in the first place. See #2118, #2114

**Comment by ngosang** [comment]
I made this changes also #2183.

**Comment by fz72** [comment]
@ngosang you changed the download complete dialog in the modstore. I changed the other dialogs.

**Comment by ngosang** [comment]
I tried it and looks better than before. Maybe with the buttons in the middle is better.

**Comment by SmallJoker** [comment]
A good change but it's trivial.

**Comment by nerzhul** [comment]
seems good @sfan5 @ShadowNinja @Zeno- @kahrl ?

**Comment by nerzhul** [comment]
Please fix whitespace issue:

Application : Better Design for Dialogs ( Create World, Delete World, Rename Modpack, Delete Mod)
/home/nerzhul/Devel/minetest/.git/rebase-apply/patch:41: trailing whitespace.
		
fatal: 1 ligne a ajouté des erreurs d'espace.

**Comment by fz72** [comment]
@ngosang which buttons do you mean?

**Comment by ngosang** [comment]
I do not remember but it's fine.

**Comment by fz72** [comment]
I think this can be closed since the fix of celeron55. #2348

**Pull request closed without merging**
