### PR TITLE
Import irrlicht sources into minetest

### PR DESCRIPTION
**Pull request by nerzhul**
Import irrlicht engine 1.8.4 in our tree and use it by default.

This will permit to leverage some issues where irrlicht has bug and we rely on them and we can never fix it due to the irrlicht undeadness.

I suggest we keep this as the default as we will need irrlicht engine modifications for some of our issues (wayland support, binding bugs on non QWERTY...) and do some engine cleanup to keep only the useful parts (if i remember there is an editor in irrlicht and some useless parts). This will also help to integrate more model formats as some requested

## To do

This PR is Ready for Review.

- [ ] Verify that CI is happy
- [ ] Integrate our own engine modifications on irrlicht directly on the forked source
- [ ] Delete irrlicht internal parts which already relies on external libs on MT (jpeg, zlib)

## How to test

Build & run, it will compile irrlicht statically and run

### CODE REVIEW

**Comment by MoNTE48** [comment]
@nerzhul, why is obsolete 1.8 instead of 1.9? Is it still not stable enough?
And isn’t it better to put this code in a separate repository?

**Comment by rubenwardy** [comment]
I would prefer that this is in a separate repository, and imported using cmake fetch content or submodules

**Comment by nerzhul** [comment]
it's another possibility

**Comment by nerzhul** [comment]
1.9 has many interesting changes but is also unreleased

**Comment by MoNTE48** [comment]
@nerzhul, what will change when the tag "release" is added to Irrlicht 1.9? If it works stably and has interesting features (including Android / iOS support!), what is the reason to use the version that was outdated many years ago?

**Comment by nerzhul** [comment]
i tend to prefer listen a dev team which tag, it's a contract but we can give it a try after using at least 1.8.4 itself by ourselfes, first

**Comment by sfan5** [comment]
I prefer to keep this in a separate repository too.

Regarding submodules: Do they get packaged too when you create a github release?
Also the frequent need to make "update \<submodule\> to \<hash\>" commits can be annoying.
Not sure about fetch content either, distro packagers might not like it when the build process downloads additionally files on its own.

If none of the solutions are good we can always require the user to either build the patched Irrlicht manually and pass the lib & include dirs <i>or</i> to provide a path where the other repo was downloaded so it can be built.

**Comment by orbea** [comment]
I think the likely result is that irrlicht will eventually be updated upstream and minetest will be stuck with an outdated and hardly maintained irrlicht fork.

**Comment by rubenwardy** [comment]
It's been almost 8 years since Irrlicht received a minor release, and 4 years since it received a patch release. I don't think we're at much risk of that, and if it does eventually happen we can just pull in the changes. Right now we're stuck on an outdated and completely unmaintained upstream version

**Comment by nerzhul** [comment]
@orbea irrlicht is stuck with no activity in 6 months and 1 patch release since... 7 years maybe. If i remember when i started develop MT we were in irrlicht 1.8.3, and not 1.8.4.
Many free games forked it to have it work properly with their game and do the necessary bugfixes, the problem is that these forks are tied to their game. For our need we are voxel engine world game, then we may modify it in this way.
I will open a gitlab repository with the irrlicht 1.8.4 in the minetest namespace.
I will start to port some changes from mt repo to it (we have in irrlicht_changes folder).

**Comment by rubenwardy** [comment]
Here you are: https://github.com/minetest/irrlicht

**Comment by nerzhul** [comment]
oh on github, okay i thought about gitlab but as you like

**Comment by sfan5** [comment]
> irrlicht is stuck with no activity in 6 months

The last commit is from [2 weeks ago](https://sourceforge.net/p/irrlicht/code/commit_browser).

> I will start to port some changes from mt repo to it (we have in irrlicht_changes folder).

I don't think that's a good idea, any changes that can be done without modifying Irrlicht should be kept out of it. Moving them back will just make it harder to move back to Irrlicht 1.9 when it comes out.

In general I would suggest an approach of making as few changes as necessary. Apply bugfixes, remove unused parts where easily possible (e.g. the bundled libraries), but nothing more than that.

**Comment by paramat** [comment]
> oh on github, okay i thought about gitlab but as you like

I prefer the repo being on GitHub too.

**Comment by nerzhul** [comment]
do you think 1.9 will come a day ? can be nice to fix many bugs

**Comment by orbea** [comment]
> do you think 1.9 will come a day ? can be nice to fix many bugs

Since there is obviously work being done in their upstream repo I think its possible, but the last stable release was in 2017 so they might not be all that concerned about stable releases.

It would be nice to ask them about it and remind them that there is interest.

Alternatively minetest could bump the requirement to the unstable 1.9 irrlicht (Minetest doesn't build with it currently) and then include a copy in the repo without forking it which will be used unless the user actually has a new enough irrlicht on their system. This way when 1.9 is released users will naturally be able to use the system version without additional changes.

That said I am not sure if there are any caveats in using the unstable 1.9 version besides the build problems.

**Comment by nerzhul** [comment]
irrlicht 1.9 doesn't support wayland or the various SDL things we just talked about, i'm not sure they will support it

**Comment by sfan5** [comment]
> It would be nice to ask them about it and remind them that there is interest.

They know: http://irrlicht.sourceforge.net/forum/viewtopic.php?p=305541

> (Minetest doesn't build with it currently)

says who?

**Comment by orbea** [comment]
> irrlicht 1.9 doesn't support wayland or the various SDL things we just talked about, i'm not sure they will support it

If they are implemented in a minetest specific fork, maybe it would be worth to spend the time to implement them upstream instead to reduce future maintenance burden.

**Comment by nerzhul** [comment]
the problem is the developer is alone, that clearly doesn't help. If someone has an account on their forum please ask if there is any help possible or something else, because he needs few days, an say summer :(.

**Comment by nerzhul** [comment]
the idea here is to have a vanilla irrlicht and implement our patches & cleanups on it. On 1.9 release we rebase & update MT and it works. i wait irrlicht 1.9 because technically it fixes many many memory useless copy done inside the code

**Comment by MoNTE48** [comment]
> On 1.9 release we rebase & update MT and it works.

It would also be nice to offer your patches in Irrlicht 1.9 until it is released.

> Works fine with the Irrlicht 1.9 from last year though, which is also what we use on Android.
Well, you use my fork, which so far DOES NOT use the latest version and includes several fixes. It would be easier if Minetest focused on 1.9. Then Android will also be able to use the latest version, and not use my fork.
In December, there were some changes that broke some things. But I preferred not to make patches, but suggest fix the support.

**Comment by nerzhul** [comment]
which artifact do you prefer on github to be used in this PR as a remplacement ? a debian package + a raw artifact with lib & headers ?

**Comment by sfan5** [comment]
Are you suggesting that CMake should automatically download a compiled variant and use it?

**Comment by rubenwardy** [comment]
> which artifact do you prefer on github to be used in this PR as a remplacement ? a debian package + a raw artifact with lib & headers ?

The source code

**Comment by nerzhul** [comment]
irrlicht doesn't use cmake by default, it needs to port irrlicht build to cmake, which is possible as i do in this pr for linux easily, for windows, macosx & android not sure it will be so easy

**Comment by rubenwardy** [comment]
CMake supports calling things like configure for submodules

**Comment by sfan5** [comment]
Why should cmake build Irrlicht at all? I get that it's for convenience but you can just let the user build Irrlicht.

**Comment by rubenwardy** [comment]
You don't want to link to the wrong wrong version of Irrlicht

**Comment by rubenwardy** [comment]
Minetest should also statically link to Irrlicht when using our fork, to avoid conflicting with system-wide installs that may be required by other packages

**Comment by nerzhul** [comment]
yep i'm totally in favor of static linking, like it's done in this PR, it's safer and ensure we use the right irrlicht version

**Comment by sfan5** [comment]
> You don't want to link to the wrong version of Irrlicht. 

Obviously, a configure check should be added to ensure people have the modified Irrlicht and not the upstream version.

**Comment by adrido** [comment]
Be careful when statically linking Irrlicht especially on Windows. Minetest has a direct dependency on zlib, Irrlicht depends on zlib and libpng which also depends on zlib. When you want to use the static version of Irrlicht, you also need to link the static version of zlib in Minetest and png. 

If you need a CMake script that works across multiple platforms you may take a look into https://github.com/microsoft/vcpkg/blob/master/ports/irrlicht/CMakeLists.txt (MIT-Licenced)

**Comment by orbea** [comment]
> Minetest has a direct dependency on zlib, Irrlicht depends on zlib and libpng which also depends on zlib. When you want to use the static version of Irrlicht, you also need to link the static version of zlib in Minetest and png.

So not only will minetest have a permanently out of date version of irrlicht, it will have permanently out of date versions of both zlib and libpng too... *sigh*

**Comment by sfan5** [comment]
> it will have permanently out of date versions of both zlib and libpng too... _sigh_

Not sure how you're coming to that conclusion.

There should be no issue linking Irrlicht statically but its dependencies (zlib, libpng, ...) dynamically, even on Windows. You just can't link the same library both statically and dynamically.

**Comment by orbea** [comment]
> Not sure how you're coming to that conclusion.

A friend recently worked on an old unrelated project and found it had a copy of zlib that was from before 2003. Given the speed of development in this project, do you really expect to be able to keep up with all the updates for a program like libpng?

This is what they call cargo culting.

**Comment by rubenwardy** [comment]
Cargo culting is copying code without understanding it. This is not copying code, it's changing how a dependency is linked. Zlib won't be included into our source tree, it'll be linked in such a way that both irrlicht and minetest can use the same version. If this is done dynamically, it's likely to use the system version that would already have been used

**Comment by orbea** [comment]
If zlib and libpng are not included in the source tree as suggested in comment https://github.com/minetest/minetest/pull/9879#issuecomment-630622121 then that would be better. Regardless, do you understand all of the irrlicht code, even between all of the core devs? How is that not cargo culting?

**Comment by rubenwardy** [comment]
It's not cargo culting because we're not copying code. We're forking and maintaining a dead dependency

**Comment by rubenwardy** [comment]
I suggest working on the irrlicht fork in the separate repo to fix a few of the issues because changing the minetest build system

**Comment by orbea** [comment]
> It's not cargo culting because we're not copying code. We're forking and maintaining a dead dependency

It was last updated 2 weeks ago as already mentioned, its not dead. At the risk of repeating myself, why not upstream the fixes so that everyone benefits? Rather than fork a code base that will just become out of date in time with very little hope of being well maintained by you guys.

**Comment by rubenwardy** [comment]
Irrlicht is already 8 or 4 years out of date, whichever way you think about it. Irrlicht is dead - the development version hasn't compiled for months. We've waited for years for upstream to get their shit together. Even if they start working on it again, having our own version of Irrlicht allows us to control the release cycle, and ensure that all our versions have the exact same version.

SuperTuxKart did this years ago. They even recently relicensed to a permissive license, which would allow backporting from it

I personally refuse to use SVN or the malware cesspool that is sourceforge

**Comment by sfan5** [comment]
> A friend recently worked on an old unrelated project and found it had a copy of zlib that was from before 2003. Given the speed of development in this project, do you really expect to be able to keep up with all the updates for a program like libpng?

rubenwardy already explained that we're not copying code, but there's one thing I wanted to mention:
zlib is a funny example, because for "ages" the newest version was 1.2.8 (28 Apr 2013) until a few years ago when there were a few updates up to 1.2.11 (15 Jan 2017) and news has been quiet since then. Not all projects move fast and require updating every month (or here, even once in 3 years).

> At the risk of repeating myself, why not upstream the fixes so that everyone benefits?

1) Nobody is saying that we are not going to upstream any fixes we make.
2) Part of the work is <i>backporting</i> fixes to 1.8.4, those changes are already upstream so that everyone benefits.

> Irrlicht is dead - the development version hasn't compiled for months.

Factually wrong.

> the malware cesspool that is sourceforge

I hear they've changed owners in the meantime so that's no longer a concern.

**Comment by nerzhul** [comment]
yeah sourceforge is not a problem anymore, but it remains the shitty SVN, irrlicht should move outside of it to permit easy contributions

**Comment by appgurueu** [comment]
I don't think this belongs in the source tree. If anything, it should be a submodule pointing to [the fork](https://github.com/minetest/irrlicht). Bloating 200k MT loc with 460k Irrlicht loc and mixing two sources in one repo like this doesn't seem to be a good idea.

**Comment by oleastre** [comment]
I'd like to start testing some irrlicht change (initially related to the keyboard). I see there is some work in the minetest irrlicht fork, but this PR also includes directly the irrlicht source.
So, is there somewhere a minetest branch that includes the irrlicht fork as a git module instead of this full import ? (Or I just override my irrlicht version)

**Comment by rubenwardy** [comment]
You should contribute to the minetest/irrlicht repo

**Comment by oleastre** [comment]
That one I understood from the comments. 
My question is more: is there some work done in minetest main to include the fork as a module, or should I replace my system irrlicht with the fork ?

**Comment by rubenwardy** [comment]
It will be done eventually, for now you can compile Irrlicht locally and link Minetest with it. You don't need to replace system Irrlicht. You can use cmake flags

**Comment by nerzhul** [comment]
use the irrlicht forked version. i have a nearly working version with XKB on wayland but irrlicht keymap is the breaking issue as far i see, because wayland xkb input is correct, and it's broken after keymap

**Pull request closed without merging**
