### PR TITLE
Add background to main menu

### PR DESCRIPTION
**Pull request by rubenwardy**
Requires #8611 to be merged first

Will look a lot better with #8600 merged

image

### CODE REVIEW

**Comment by DS-Minetest** [comment]
You can't see the clouds behind the formsepec anymore.

**Comment by paramat** [comment]
I don't think this is an improvement.

Instead, are you able to attend to #7060 ?

**Comment by rubenwardy** [comment]
The left and right edges will be improved by the 9slices pr, but I've decided not to do this

And #7060 is waiting on my styles pr which is waiting on consistent coordinates

**Comment by rubenwardy** [comment]
Here's the menu with 9slices. It's still not quite right, but is an improvement

image

**Pull request closed without merging**
