### PR TITLE
Android: remove broken alignment from Makefile

### PR DESCRIPTION
**Pull request by est31**
Alignment has been broken since we used spaces to align different tab indentation levels.

### CODE REVIEW

**Comment by nerzhul** [comment]
Okay for me, it's prettier

**Comment by est31** [comment]
What do you think is nicer: one space before the `\`, or no space at all?

**Comment by nerzhul** [comment]
One space is better for reading

**Comment by MoNTE48** [comment]
Good! :)

**Comment by est31** [comment]
please, vote here: https://forum.minetest.net/viewtopic.php?t=12247

**Comment by Zeno-** [comment]
We could always change the style guide to use spaces (not tabs) for indentation at the start of a multiline macro (or makefile in this case): :/

**Comment by est31** [comment]
Closed due to result of poll being in favour of the current model.

**Pull request closed without merging**
