### PR TITLE
Add Malay translation of builtin

### PR DESCRIPTION
**Pull request by mnh48**
## Goal of the PR
This PR adds the Malay translation for `builtin`.

## To do
This PR is Ready for Review.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
Maintainers: If the PR author does not react within the release time frame, I suggest to merge this anyway but with the faulty string cleared. That's still better than no translation at all.

**Comment by mnh48** [comment]
oh, let me push a fix for the missing parameter
(it would had been caught if it's on weblate for example as weblate does parameter check as well, but alas `builtin` is not on weblate for some reason)

**Comment by mnh48** [comment]
I've pushed the fix

**Comment by Wuzzy2** [comment]
Awesome! All checks pass now.

I've written a checker script by the way. https://codeberg.org/Wuzzy/minetest_check_translations

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
