### PR TITLE
[WIP]Add minetest.is_nothing(pos)

### PR DESCRIPTION
**Pull request by zaoqi-unsafe**

### CODE REVIEW

**Comment by sofar** [comment]
You shouldn't sent WIP patches that are this small. Please just test it and submit when it's ready.

**Comment by nerzhul** [comment]
This code should be in common lua part, because we need it client side too

**Comment by zaoqi-unsafe** [comment]
@nerzhul

**Comment by nerzhul** [comment]
why close it ?

**Pull request closed without merging**
