### PR TITLE
Make acc and vel deprecated in add_particle and search for acceleration and velocity instead

### LINKED ISSUE #1789: Velocity ignored in function minetest.add_particle
This some code spawns smoke - it does not have any velocity.

```Lua
minetest.add_particle({
	pos = pos,
	velocity = {x=0, y=2, z=0},
	size = 2,
	texture = "smoke_puff.png",
})
```

The velocity works fine with minetest.add_particlespawner()

![Example of a not moving smike particle]
(http://i.imgur.com/E517b5z.png)

### PR DESCRIPTION
**Pull request by TeTpaAka**
Fixes  #1789 and  #1280
Or should it check for the full words?

### CODE REVIEW

**Comment by est31** [comment]
I think you should check for full words, but still support "vel" and "acc", with a log message that its deprecated.
Could you also outline the issue in the commit message (doc and actual behaviour differed)?

**Comment by est31** [comment]
:+1:

**Comment by TeTpaAka** [comment]
Done.

**Comment by est31** [comment]
Perhaps do a `log_deprecated` call?

**Comment by TeTpaAka** [comment]
I forgot to do git add -u. That is what I am doing, but I didn't push it.

**Comment by est31** [comment]
ok

**Comment by obneq** [comment]
very much in support of a cleanup here. this should go further tho, this code gets the values in a weird way. i'm sure there is no need for the while loop and giant if statement.

**Comment by est31** [comment]
This is enough I think, further PRs can do more cleanup.

**Comment by TeTpaAka** [comment]
http://irc.minetest.ru/minetest-dev/2015-06-29#i_4302756
So should I remove the while loop and replace it with proper get*field() calls? Probably in the whole file?

**Comment by est31** [comment]
How do you mean that? I don't think this is the code he was speaking about, this is a lua api table parser, no enum, and no enumtostring.

**Comment by TeTpaAka** [comment]
OK, I thought he was talking of the lua interface, so not.

**Comment by obneq** [comment]
@TeTpaAka yes, that is what i meant.
@est31 seriously, are you a wizard?

**Comment by est31** [comment]
dd2e08e11764e045f4eb7a25475a8ecaa77b58de

**Pull request closed without merging**
