### PR TITLE
Add 3d_plantlike optional drawtype

### PR DESCRIPTION
**Pull request by RealBadAngel**
New drawtype that creates its own "extrusion" meshes out of 16px texture.
It can be enabled via settings same way as connected glass is.
Heres video on the end effect:
https://www.youtube.com/watch?v=L_Az4mEQEtI
And some screenshots:
screenshot_20151228_221409
screenshot_20151228_222219

### CODE REVIEW

**Comment by paramat** [comment]
Screenshots please.
What's the effect on speed of mesh generation? seems it might be heavy as this adds thousands of extra cubes.
Related to that, is the effect distance-limited? it would be unnoticeable beyond perhaps 32 nodes, and would be an unnecessary huge amount of processing, especially since a larger number of decorations are visible at a large distance.
Only the mushroom seems a little weird, it would be better as a 3D model.

**Comment by kilbith** [comment]
xinpiiq

**Comment by RealBadAngel** [comment]
@paramat Added the video in the first post. Also:
- this cant be area limited i afraid - this is not shaders related thing but regular mesh stuff. Shaders only do the waving.
- the effect is quite costly, you need rather modern GPU to handle that at decent framerate, thats because of higher number of polygons to display, but i havent tested that on any other GPU than mine, 5 yrs old GTX550TI

**Comment by NathanSalapat** [comment]
The Youtube video looks very nice. Would this be able to add to torches, so we aren't stuck with completely flat torches, or would that require complete different coding?

**Comment by RealBadAngel** [comment]
@NathanSalapat ive made such code long time ago (see http://i.imgur.com/6kkxmnQ.png) but i think in case of torches proper solution is to switch to mesh.

**Comment by sofar** [comment]
3d torches already work relatively nicely. With a fixed animated texture they should look fine.

**Comment by est31** [comment]
@paramat Yeah it would be really great if minetest would have multiple complexity versions of a mesh for a particular mapblock, and display them dependent on distance. But unfortunately we currently lack the infrastructure for this.

I really like what the PR wants to achieve (getting off the ugly "two textures in a cross" plantlike we have currently), and those with good hardware will now have an opportunity to use it.

**Comment by est31** [comment]
I can't review today anymore, will do it this week.

**Comment by paramat** [comment]
:-1: I wanted to be neutral about this but i feel ths cannot be accepted, sorry (this will make me unpopular again) although in isolation it looks okay to me.

Consider a mgv7 grassland scene with a modest 130 nodes view range and 1 long grass per 10 surface nodes, which is average.
Lets say the 3D plantlike effect is only noticeable within 30 nodes. The close 30x30 area has 900 nodes and 90 long grasses, each with 100 micro-voxels, that 9 000 extra cubes being rendered.
Now consider the distant 100x100 area, 10 000 nodes and 1000 long grasses, that's 100 000 extra cubes being rendered.
In total 109 000 extra cubes rendered, 100 000 or 92% of which is wasted processing because they are to distant to be effective. I can imagine players FPS droppng from 130 to 30 or less and i expect most would consider it not worth it and would prefer to have the view range their setup allows.
In return for a huge amount of mostly wasted processing we get a slightly thicker plantlike drawtype, not much of a change from a flat texture, it's not worth it.

The drawtype code should not rename the basic plantlike drawtype to refer to this effect, see the PR in mtgame https://github.com/minetest/minetest_game/pull/762

Dividing nodes into micro-voxels is crazy, the whole idea of a voxel game is that each node is a 'pixel' of the world, and each is a super-simple display of flat pixel art either as a cube or crossed textures. This visual simplicity is what frees up processing for more interestng things and what makes a realtime-rendered voxel world possible. 3D plantlike essentially is multiplying mesh processing by at least 100, at worst the division of a node into 16^3 is 4096 times more cubes to process.

This ultra-fine detail, as with normalmaps and parallax occlusion, is largely wasted because it is only visible up close, Minetest is more about landscape scenes and buildngs, large structures in the middle-to-far distance.

I've been reading celeron55's roadmap posts and this PR is the opposite of Minetest 's spirit, i feel normalmaps and parallax occlusion should not have been accepted either. This is not about my personal taste, although it seems like it because my taste is 99% aligned to the spirit of Minetest and celeron55's, i'm more standing up for the roadmap and Minetest's character now that celeron55 is not around much. These unsuitable fancy visuals keep creeping in and it's time it stopped. These things should be in a fork.

From the roadmap posts:

"Particularly, Minetest is not about making fancy-looking things at the cost of freedom."

"Don't mind the lesser visuals and take full advantage of them in how they make creating unimagined things easier. There are enough games in this world that focus on visuals by taking away from everything else, or by making everything else harder to do."

**Comment by paramat** [comment]
> I really like what the PR wants to achieve (getting off the ugly "two textures in a cross" plantlike we have currently)

If your visual tastes are this different to how Minetest is i don't think you should have much say in the visual style. This is like saying 'meh these ugly cubes' while referring to a voxel game.

**Comment by sofar** [comment]
I'm in agreement with @paramat here - I think this is taking it over the top by a fair margin, and I think there are a *lot* more improvements that could be done to improve minetest visually without such drastic changes. I'm not saying I dislike how this looks (I like it, actually) - but I think it'll become a burden in the long run and the current plantlike node already looks fine to me (I've submitted PR's even to enhance it, and some of the custom plants I've written use the same visual representation).

**Comment by RealBadAngel** [comment]
@paramat if you dont like particular option, or if you have slow box, you dont turn it on simple as that.
Youre as usual overreacting and want everybody around to accept your minimalistic taste. Propably the best minetest for you should be black and white, just two colors. Why dont you just fork minetest and remove everything concerning GFX from it?
About those big numbers you are mentionin, thats partially true. Possibly one character model in modern games have more polygons than that :P You can slow down the engine using any other drawtype including leaves. Again, dont have spare GPU power, dont turn it on. With low end box, old GPU, i can comfortably play with all those candies enabled. And yet i have an option to turn VBO on to double the speed. So what are you playin MT on? Commodore c-64 or what?

- another thing, existing plantlike was just two flat textures, 3d version is about  makin them micro cuboids thats correct. atm this pr enables emulation of old drawtype with the new one, but theres possibility to use the drawtype without emulation and design real plants (maybe l-system ?) in a 16x16x16 grid.

**Comment by sofar** [comment]
@RealBadAngel I wasn't joking, you are introducing a method that will create thousands little cuboids, if that isn't paraphrased by the term "drastic", disabled by default or not.

My PR's that create a tiny placement variation of plantlike nodes in the x,z plane are getting rejected for being "too drastic", and that's not even adding any new drawtypes, and that one was also disabled by default. And I admit myself it's a departure from the current minetest game rendering.

This isn't personal, either. I've disagreed with @paramat on plenty of PR's as well. Such is code.

**Comment by RealBadAngel** [comment]
@sofar problem with @paramat is that he is rejecting everything he don't like, and we do already know the he doesnt CARE about look of the game at all. Even smooth lighting is too much for him.

**Comment by sofar** [comment]
@RealBadAngel I'm pretty sure he cares, that's why @paramat  wrote 2 messages with 11 paragraphs of text and almost 600 words, and didn't blow you off with a "sorry, no" message.

Don't attack him as a person, that doesn't achieve anything.

His argument is that your fork to do more of these experiments is *entirely valid*. Should you become highly successful with it (and I think paramat would want you to be so), then he'll likely be more than eager to working with you, especially if you can avoid ad hominem attacks and keep the atmosphere positive (I know that's hard, this isn't my first OSS project).

He's basically inviting you to prove that celeron55's roadmap is wrong. You might want his help to do that, since if you can invalidate it, getting patches like these accepted might become a reasonable thing.

**Comment by RealBadAngel** [comment]
I dont claim that c55's roadmap is wrong, i say that both dont care about gfx at all. Especially @paramat.

@paramat highly popular demand is for better looking mt, not another game...
Btw, "This is like saying 'meh these ugly cubes' while referring to a voxel game." ?? Like really? Since when 2 flat textures are cubes?

**Comment by celeron55** [comment]
I'm going to say no.

If you want to do stuff like this, 3D model nodes already exist. There's no point in creating other 3D specializations.

**Comment by VanessaE** [comment]
Although c55 has since closed this, I'd like to make a comment:  @RealBadAngel rather than making microvoxels, you would have been much better off stacking say 10 copies of each of the two initial faces side by side, closely-spaced, to a thickness similar to what your microvoxel idea presented.

You would have ended up with far fewer faces that way, and still kept the "feel" of Minetest.  Paramat's 1000-node-average-visible example would raise from a poly count of about 4000 now, to 40'000 with that idea, rather than tens of millions of polys (~100'000 * 6 * 2) with your idea.

**Comment by RealBadAngel** [comment]
@celeron55 following that logic any built-in drawtypes are obsolete because there are meshes aviable...

**Comment by est31** [comment]
@paramat it's about adding this as an _option_, not the default. If you don't like it, just don't enable it.

Microvoxels rather embrace the voxellike type of minetest. With your logic, we shouldn't have any meshnodes, because they also allow subdivision.

**Comment by paramat** [comment]
RBA you have done good work in Mnetest which i appreciate, i hope you continue to contribute where it's appropriate. However much of what you do is just too fancy for Minetest (making it optional is no excuse), you need to recognise which is which and keep your more fancy stuff for a fork which i'm sure will be popular.

Currently in order to update a normalmap for a new texture, a particular program must be compiled and a complex method followed to get a good result, Gimp isn't capable. This is too much to ask, the huge normalmaps also make an irritating mess in the texture pack, they should be removed from Minetest Game and it's up to you to find a better implementation. The normalmap effect is itself is too fine-detailed and fancy and should never have been accepted, however i'm not sure we will be able to remove it, it is popular.

> want everybody around to accept your minimalistic taste.

> rejecting everything he don't like, and we do already know that he doesnt CARE about look of the game at all. Even smooth lighting is too much for him. 

As i wrote, i am only trying to preserve the spirit and character of Minetest, my tastes just happen to 100% align with it and celeron55's. You are trying to change Minetest into something completely diffierent and add features that are clearly unacceptable even as options.
I am making a fuss because i care.
I do like smooth lighting now.

>  theres possibility to use the drawtype without emulation and design real plants (maybe l-system ?) in a 16x16x16 grid.

Yes and that's even more scary as i explained, multiplying the number of cubes to process by 4096. For anything smaller than nodes we have nodeboxes, making 3D detail 16 times finer is too extreme it's better as a simple 2D texture, as plantlike drawtype already is.

> i dont rename the drawtype, its the completely new one.

Yes my mistake. It's messy, we shouldn't have to change the drawtype parameter it should be an option that affects plantlike.

What has happened here is similar to what happened with proller, unsuitable and messy stuff has crept in, a fork should be made and we need to clean up or remove some of RBAs work. I'm starting this process now, i will be unpopular but someone has to do this. I have the roadmap and the visual characer of Minetest on my side.

Est31, nodeboxes are fine because they are usually not hi-res, they also are never higher-resolution than they need to be, this PR is working towards a fixed 16^3 subdivision.

From your comments you seem to dislike much of MTGame, and much of the visual design of Minetest, you are a fan of these unsuitable shaders, this is all fine no problem, but i feel you should recognise this and admit your tastes are opposed to Minetest's character, and therefore stay neutral in visual design and shader PRs, i know you are already doing this somewhat by 'not commenting' on some topics.
Your work in engine is good and much appreciated.

**Comment by RealBadAngel** [comment]
@paramat, you dont even have a slightest idea on how to make textures and normalmaps, gfx and you are commenting its hard? another app is needed? gimp is not enough? any game developer will kill you with laugh.
Sorry but you are acting as a blindfolded fanatic, go on remove all my work, make mt black and white...

**Comment by kilbith** [comment]
My opinion : the truth is somewhere in between @RealBadAngel and @paramat philosophies.

Extremes are generally not healthy and should be avoided.

**Comment by paramat** [comment]
Sorry, my last paragraph was addressed to est31.

The normalmaps are a pain for MTGame devs, i have more free time than the other devs and even i can't be bothered with the process of creating a new normalmap every time we change a texture. It's a lot of work for an effect that is not suitable for Minetest and shouldn't have been added at all.

RBA, the 2 lead devs of Minetest are celeron55 and hmmmm, although unfortunately they have been inactive recently. Both are fed up with your work, your tastes and approach are the polar opposite of celeron55's and the roadmap, but despite this your attitude is "screw them they're not important" (to the creator of the game itself) and you continue to try and sneak in unsuitable features. This is amazing arrogance and denial of reality, when will you get the message? This will only frustrate you when some of your work is blocked.

A while ago you decided to start a fork, this was a good thing because you have lots of interesting ideas that should have an outlet despite being unacceptable for Minetest, it will also be less frustrating for you. I don't want to see your ideas and creativity go to waste.

**Comment by est31** [comment]
I don't contribute to mtgame because I dont want to lead taste based discussions. I like most parts of it, only sometimes there are changes which I hate.

If normalmaps are a pain for mtgame, then drop them from mtgame, e.g. drop the normalmap for a node when you update its texture for some reason. But that discussion has nothing to do with the discussion about removing support from the engine, entirely.

**Comment by est31** [comment]
Plantlike and torchlike are just simply ugly, in my eyes. Placing a single face into the middle of the world is just bad style, and can't be excused with "simplicity" arguments. If something can't be seen because its looked at from the wrong angle, its not "simple". This PR tries to improve upon this mess, **while still retaining the default to be the old approach**, I'm sad it got such disagreement by paramat and c55.

My views are shared by other core devs as well (eg blockmen, just take a look at his extruded torches PR), and they are similarly frustrated that minetest has no support for automatically displaying plantlike + torchlike in a non broken way.

**Comment by kilbith** [comment]
@paramat You're pressed to see RBA to get out, but can we afford currently to lose a long-term dev who is able to : 
- work on the VBOs and Irrlicht particles.
- give us proper signs (and thus get rid of sicky ones with entities).
- fix the mapblock updates causing a huge drop of FPS.
- overall giving us more FPS and share his knowledge on the audiovisual.
- etc.

Although you may have some valid points, just don't overshadow the qualities of RBA and what he has done for good during 4 years.

**Comment by BlockMen** [comment]
@est31 the extruded torches and plants where a PR by RBA. Mine was just a changed torchlike drawtype ;)

But yes, i kinda agree with what you said here.

**Comment by paramat** [comment]
kilbith i see what i wrote above:

> RBA you have done good work in Mnetest which i appreciate, i hope you continue to contribute where it's appropriate.

Est31 sorry i exaggerated. Plantlike is a good and obvious way to create a plant-like node in a super-simple way, perhaps another good way would be 4 textures all angled outwards slightly from a central point so always visible. Any sort of extrusion or conversion to cubes is ridiculous because you end up with something almost identical, but taking huge resources while only being visible close-up. From above my 4-angled textures idea would be much more visible than a thin extrusion.

**Comment by sofar** [comment]
I created a different mesh for plants myself using 4 upright textures (crops:corn). The variation in display of plants is enjoyable, and I have no problems adding more simple ways to draw plants. Maybe I'll come up with some more (mushrooms could benefit from that, for instance).

**Comment by PilzAdam** [comment]
I'd like to comment on one particular point that @paramat said very early in the discussion:

> Related to that, is the effect distance-limited? it would be unnoticeable beyond perhaps 24-32 nodes, and would be an unnecessary huge amount of processing, especially since a larger number of decorations are visible at a large distance.

@celeron55 recently did some work on farmeshes; the general idea being to lower the level of detail for mablocks that are farther away from the camera. This idea could be expanded to allow several layers of detail (like mip-mapping). The highest detail is only for mablocks close to the camera, it could contain more detailed models of nodes like the feature @RealBadAngel wants to add here. Then there are a number of ranges where the detail level is gradually lowered, to the point where even whole nodes are combined, like @celeron55's farmesh.

This idea should not be limited to built-in engine drawtypes. Mods should be able to provide different versions of the mesh of a node, with different detail levels. This way it would be relatively trivial to add visual effects like this PR wants to add.

@celeron55, is your farmesh system generic enough to already allow such things? How hard would it be to modify it in such a way?

**Comment by celeron55** [comment]
@PilzAdam it is not generic; it is simple and performant. What you describe is rather far from what it can do and I am not sure if that is something that should be at all based on it.

**Pull request closed without merging**
