### PR TITLE
Add support to show LUA mapgen mods in world creation dialog

### PR DESCRIPTION
**Pull request by orwell96**
This PR includes #5329.
If the option is_standalone_mapgen is specified in mod.conf, a mod is listed as mapgen option in the world creation dialog.
For more info see the documentation these commits add.

### CODE REVIEW

**Comment by orwell96** [comment]
For the case you describe, the functionality should not be enabled, since the mapgen is not standalone then.
An example for what this can be used for is the mod 'origin': it adds nothing but a single origin node at 0,0,0. So it's unuseful to select any core mapgen.

**Comment by paramat** [comment]
Yes. I was a little unreasonable earlier :)

**Comment by SmallJoker** [comment]
The idea is good. This would make Lua-based mapgens more attractive, even if they're slower than if they were made in C++.

**Comment by paramat** [comment]
:-1: Sorry. This is unnecessary, Lua mapgens are mods and are fine staying in mod selection.
If someone installs a Lua mapgen mod they will be aware of this so don't need it to appear in world creation.
This would probably cause problems. A Lua mapgen requires singlenode to be enabled, so singlenode needs to be selected in world creation. Although a mapgen can set the mapgen to be used, it can only do this after default has run, so default will not know that singlenode is being used, and in some cases it will need to know this to set correct options. Same goes for any subgame.
So, unnecessary, complex, probably problematic.

**Comment by nerzhul** [comment]
i agree with paramat but also for other reasons, main menu should show production grade and performance grade mapgen, lua mapgen are good for prototype a mapgen

**Comment by paramat** [comment]
The intention is good but there are issues.

> An example for what this can be used for is the mod 'origin': it adds nothing but a single origin node at 0,0,0. So it's unuseful to select any core mapgen.
EDIT: another candidate is https://github.com/CasimirKaPazi/unternull

If done, selecting a Lua mapgen in world creation would need to automatically select singlenode core mapgen. However, due to MT's world height, many or most Lua mapgens are able to run in singlenode but also as a stacked realm above mgv6, mgv7 etc. so the core mapgens still need to be selectable.
This would result in many Lua mapgens not appearing in the core mapgen selection dropdown.

Defining a 'standalone' mapgen is not possible as mods may be written afterwards that depend on it, therefore the Lua mapgen needs to still appear in the mods menu to be manageable.
It is useful that a Lua mapgen can be disabled for a game session for dev or experimental work, so again it needs to appear in the mods menu.
Maybe your PR does keep it in the mods menu, but then it is in 2 places which seems a bit messy.

The mapgen selection dropdown is the selector for the core mapgen, a Lua mapgen does not replace core mapgens, it adds nodes to them, usually adding to singlenode (air). So the selection of core mapgen is just as important and essential when using a Lua mapgen.

Mods are mods and belong in the mods menu, a user does not expect them to appear elsewhere.

**Comment by paramat** [comment]
Sorry, because i now mapgen well i see problems, and there is not much benefit, so i have to add a 'won't add' label.

**Pull request closed without merging**
