### PR TITLE
[nosquash] Devtest: Add jukebox and branding iron

### PR DESCRIPTION
**Pull request by Desour**
- The jukebox can be used to play sounds by giving a SimpleSoundSpec, sound parameters and ephemeral. It can also stop and fade the sound. The sound handle is stored in a table per jukebox pos hash, there's a Release button to drop the handle.
- The branding iron can be used to give objects names, i.e. `obj:1`. This is needed to pass objects in the sound parameter table.

Screenshot:
screenshot_20220917_000803

## To do

This PR is a Ready for Review.

Don't squash.
Review commits separately.
(A file was renamed.)

## How to test

* Place a jukebox.
* Play around with it.
* To check its usefulness, try for example to play a positional long or looped sound, and fade it with `gain=0, step=1`, and see how it takes 3 seconds, even though the given gain is (by default) 1. Such and other bugs can be tested with this tool.

### CODE REVIEW

**Comment by Desour** [comment]
(Trivially) rebased. (Then fixed a typo and made the loop field 4 wide, for consistency.)

**Comment by Desour** [comment]
Rebased.

**Comment by Desour** [comment]
Rebased.

**Comment by Desour** [comment]
Rebased.

**Review by sfan5 — APPROVED** [review]
The testing tools work but for some reason fading-in a sound doesn't work regardless of whether I do it from the sound parameter table or the simple sound spec.

**Comment by Desour** [comment]
> for some reason fading-in a sound doesn't work regardless of whether I do it from the sound parameter table or the simple sound spec.

Fading doesn't work for positional sounds, see #6748.

Thanks for review!

**Review by rubenwardy — COMMENTED** [review]
Looks good apart from the weird way you're reading/storing from the formspec

**Review by rubenwardy — APPROVED** [review]

**Comment by Desour** [comment]
Rebased (for faster compile), and squashed (for [nosquash]).

**Comment by sfan5** [comment]
Only issue I see is that the middle commit (75aed0906757fbdca7d70af237652133bd2937d7) won't work on its own because it doesn't create the replacement init.lua.

**Comment by Desour** [comment]
Idk how to fix that. If you squash it with another commit, it'll be ugly diffs.

**Comment by sfan5** [comment]
https://git-scm.com/docs/git-rebase#_splitting_commits

**Comment by Desour** [comment]
> https://git-scm.com/docs/git-rebase#_splitting_commits

How would splitting commits help? They are already separate commits.

**Comment by Desour** [comment]
(Leaving even only small pieces of code in `init.lua` already breaks the rename, btw., see <https://github.com/Desour/minetest/tree/jukebox_tmp2>.)

**Comment by sfan5** [comment]
:shrug:  then

**Pull request merged**
