### PR TITLE
Add color values to hex string function minetest.rgba

### PR DESCRIPTION
**Pull request by HybridDog**
Adoption from #2398

### CODE REVIEW

**Comment by HybridDog** [comment]
Is this function actually desired? Using minetest.rgba or directly string.format makes no difference other than compatibility, does it?

**Comment by nerzhul** [comment]
if it's a useless function why doing a PR ? if it's useful it should be documented

**Comment by HybridDog** [comment]
nerzhul, paramat asked for a PR

**Comment by nerzhul** [comment]
and this is a PR, but it's incomplete, we need docs. Please add doc for these calls.

**Comment by bigfoot547** [comment]
:+1: I had wished there was a function that did this on many occasions.
Please make up a better name for the PR, I thought that minetest.argb was the name of a file :).

**Comment by paramat** [comment]
Thaks for this.
See the original thread, it seems useful.

**Comment by HybridDog** [comment]
l added the documentation

**Comment by paramat** [comment]
Why is minetest.rgba a better function name than minetest.colorstring? It seems a function name should indicate the result not the input? Just wondering.

**Comment by paramat** [comment]
bc53c82bcf923d11725e3de8565eb4c7e435cd2b

**Pull request closed without merging**
