### PR TITLE
Fix tab_mods.lua bug

### PR DESCRIPTION
**Pull request by Rui914**
https://forum.minetest.net/viewtopic.php?f=6&t=11201
Fixed this bug.

### CODE REVIEW

**Comment by nerzhul** [comment]
Sorry but doesn't work for me.

**Comment by Rui914** [comment]
nerzhul, What is the version of your Minetest?
This code working in daily build version of Minetest.

**Comment by nerzhul** [comment]
I have tested your PR on master branch

**Comment by Zeno-** [comment]
OS, compiler and version etc would be useful to know

**Comment by nerzhul** [comment]
Archlinux with GCC 4.9.2

**Comment by Rui914** [comment]
screenshot from 2015-02-12 18 19 08
This code has been used even tab_texturepacks.lua.
Are you able to view the no_screenshot.png in the texture tab?

**Comment by Zeno-** [comment]
I'm on android  atm so I don't know my fedora 20 config/versions but I don't  seem to experience the issue at all

**Comment by Rui914** [comment]
nerzhul, if it is good, please send a screen shot.
I can't reproduce the problem in my environment.

**Comment by nerzhul** [comment]
Oh you are right. It fixes.
But i have the bug when i click on the repository mod. Please fix it too :)

**Comment by Rui914** [comment]
What bug?

**Comment by nerzhul** [comment]
When i click on repository button i have the bug too, not only on mod tab.

**Comment by Rui914** [comment]
It is not a Mod tab, Is it Mod store?

**Comment by nerzhul** [comment]
yes

**Comment by nerzhul** [comment]
If you can fix the two bugs together it's cool

**Comment by Rui914** [comment]
Repository address of has been set by /src/defaultsettings.cpp.
Is it, the repository can not receive bug?

**Comment by nerzhul** [comment]
it's not a problem with repository address.
I would mean the bug you fix in mod tab is also present in mod store window :)

**Comment by Rui914** [comment]
#2297

**Comment by nerzhul** [comment]
Perfect

**Comment by Rui914** [comment]
Yay!

**Comment by nerzhul** [comment]
Merged https://github.com/minetest/minetest/pull/2297

**Pull request closed without merging**
