### PR TITLE
Add core.MAX_MAP_GENERATION_LIMIT constant to builtin

### PR DESCRIPTION
**Pull request by kay27**
https://github.com/minetest/minetest/issues/10428

Add ability to process world edges well by adding ```core.MAX_MAP_GENERATION_LIMIT``` constant to Lua environment.

## To do

This PR is a Ready for Review.

### CODE REVIEW

**Comment by paramat** [comment]
I support adding the constant to builtin, but disagree with the partial and inconsistent adding of duplicated constant comments to constants.h.

Adding duplicated constant comments is a separate task because there are many constants that appear in builtin and C++, this documentation task should be done fully and consistently, or not at all.
If you really want to you could do this as a second commit, but every constant in builtin must be tracked down in the engine and comments added.

You are welcome to only add the constant to builtin in this PR and not do the documentation task, i will approve this.

**Comment by kay27** [comment]
> I support adding the constant to builtin, but disagree with the partial and inconsistent adding of duplicated constant comments to constants.h.
> 
> Adding duplicated constant comments is a separate task because there are many constants that appear in builtin, this documentation task should be done fully and consistently, or not at all.

Literally because of that, fully agreeing with you, I'd better keep it because the same comment is made at the [line 37 of light.h](https://github.com/minetest/minetest/blob/master/src/light.h#L31) for core.MAX_LIGHT constant.

> You are welcome to only add the constant to builtin in this PR and not do the documentation task, i will approve this.

There are no the traces of changing ```MAX_LIGHT``` (which has the comment), but ```MAP_BLOCKSIZE``` has [commented value 32](https://github.com/minetest/minetest/blob/master/src/constants.h#L80) and it isn't reflected for Lua - it would be dangerous to use it in Lua without this warning message. It would just lose the profit of doing that.

So would you please change your mind? :)

Sure I I can provide next pull request without the comments. But it would be better to make the comments... I found them not as bad, to be honest, and originally the text was constructed by someone of the project team, following the documentation style.

**Comment by paramat** [comment]
The reason i asked was because i saw PLAYER_MAX_HP_DEFAULT and PLAYER_MAX_BREATH_DEFAULT in builtin and C++ but warning comments are not present for those.

The commented-out alternative value of 32 for mapblock size (or any alternative value) will certainly never be used for various reasons, that could be deleted, it should have been deleted long ago =)
Also, it is unlikely MAX_MAP_GENERATION_LIMIT will change.
So warning comments for these are not important to add.
LIGHT_MAX is also unlikely to change.

Thanks for updating the PR.
:+1:

**Comment by SmallJoker** [comment]
`MAX_MAP_GENERATION_LIMIT` is inaccurate. I'd prefer to see a new API function that retrieves the world-specific min/max positions of the nodes that are actually generated in the world - because that may vary depending on the configuration. This would eliminate any need for manual border calculations.

**Comment by paramat** [comment]
SmallJoker,
Good point, i should have suggested that.
The actual min/max node positions are already calculated here https://github.com/minetest/minetest/blob/c6e3050357e8378ad15e7fa7a9aa80f3936fbc2d/src/mapgen/mapgen.cpp#L1099
With such an API, adding the constant is probably pointless.
I support such an API instead of this PR, but do not want to code it =) Any volunteers?
So this PR should be halted for the moment.

**Comment by kay27** [comment]
I don't think it's a good idea, to be honest, because the function isn't so nice. Why it divides 5 by 2 at its first line instead of multiply by 16 first, which would produce symmetric coordinate system? And more further questions.

But it still produces some acceptable values and the range [published](https://wiki.minetest.net/World_boundaries) in Wiki and used in many many mods.

I thought about it I decided to copy the function in Lua and, as it is only needs to be done during the initialization, it's nothing - won't cause any problems. So https://github.com/minetest/minetest/issues/10428 is just a Lua version of [MapgenParams::calcMapgenEdges()](https://github.com/minetest/minetest/blob/c6e3050357e8378ad15e7fa7a9aa80f3936fbc2d/src/mapgen/mapgen.cpp#L1101) which produces the same values...

I'd like to add it to API too but if I'd do that I'd first remove all the 16-bit coordinate limitations, next, I'd simplify the calculation of the boundaries and only then I'd add auto generation of constants.lua with filling it by the values @SmallJoker mentioned above.

Even if somebody will make it simpler - I have no idea how my PR would cause any conflicts :) Couldn't you please merge it and then we would continue to discuss the API?

**Comment by SmallJoker** [comment]
> only then add auto generation of constants.lua with filling 

My idea was to cover following case properly as well:
https://github.com/minetest/minetest/blob/c6e3050357e8378ad15e7fa7a9aa80f3936fbc2d/builtin/settingtypes.txt#L1458-L1461

The engine should be well capable providing the min/max node positions of the current world, hence a constant might not be required any more (where's no point in using space that has no terrain).
`31000` as a simple maximal limit is nice, but does not replace manual Lua calculations.

**Comment by kay27** [comment]
@SmallJoker I'd prefer something like ```core.mapgen_edge_min``` and ```core.mapgen_edge_max``` to be set, too. Would that be an API you're talking about? Or you mean something else?

**Comment by SmallJoker** [comment]
@kay27 I'm talking about an API function that returns these two variables to Lua:
https://github.com/minetest/minetest/blob/c6e3050357e8378ad15e7fa7a9aa80f3936fbc2d/src/mapgen/mapgen.cpp#L1124-L1126
Once the mapgen is initialized, these variables contain the exact minimal and maximal node positions that are generated on the map. Table fields within `core/minetest` would work too, but it's too easy to modify those by accident (table references). Hence I propose a function like;
`local minp, maxp = minetest.get_mapgen_edges()`

@paramat Is that also what you had in mind?

**Comment by kay27** [comment]
@SmallJoker We speak about the same variables but why you want a function? Calling the function always breaks the thread so it always cause slowing down, whilst pre-initialized variable, which we might even call a constant will give the same result without breaking the thread, using the stack to return and all the stuff related to function calls.

**Comment by paramat** [comment]
> I don't think it's a good idea, to be honest, because the function isn't so nice. 

Well ... =) ... i am MT's mapgen dev and i wrote that world edge code in mapgen.cpp. I probably know this topic better than you do (not meaning to be offensive), and that code gives the correct results.
> Why it divides 5 by 2 at its first line instead of multiply by 16 first, which would produce symmetric coordinate system?

It does that because that is how the coordinate system and mapgen works.
A symmetric coordinate system is a different system so that is offtopic here, we are not going to change the whole system and there is currently no need to.
You are thinking this backwards, that code depends on the coordinate system and mapgen, not the other way around.
That code does not detemine the mapgen edges, it just calculates where the edges are. The edges of mapgen are determined by the coordinate system and mapgen.
> I'd first remove all the 16-bit coordinate limitations

You write that as if it was trivial, it is a big and disruptive task and we do not think it is worth doing yet, it has been disapproved for now.
> Even if somebody will make it simpler - my current PR won't cause conflicts. Could you please merge it and then we would continue to discuss the API?

No. This is the wrong attitude.
With an API to get the values there is probably no point in adding the MAX_MAP_GENERATION_LIMIT constant.
We do not add stuff for no reason, obviously, and you should not ask us to do so.
It not causing conflicts is irrelevant. Someone has to explain how that constant is useful even with an API. It might be useful but i cannot see how yet.

> local minp, maxp = minetest.get_mapgen_edges()
paramat Is that also what you had in mind?

Yes. Once that code has run for other reasons, simply allow getting the values.

**Comment by kay27** [comment]
So well, thank you, now I learned that you know the topic better than me (but you didn't explain why we need to divide 5 by 2), and I also learned that I'm requesting the stuff without a reason (and since you renamed it it really became to look like that), I wish you a good luck @paramant, cause I have the feeling of wasting our time.

**Comment by SmallJoker** [comment]
> We speak about the same variables but why you want a function?

Reason:
> Table fields within core/minetest would work too, but it's too easy to modify those by accident (table references).

The exact min/max positions would depend on the current map settings, which are variable. Yes sure - these coordinates could be put into a global variable. It just happens to be a practice that's not used in Minetest for providing mapgen information (see `lua_api.txt`, `get_mapgen_setting` etc). Also such a function call would be very trivial and quick to execute (similar to `vector.add(a, b)`). Mods can also cache the values if wanted.

> but you didn't explain why we need to divide 5 by 2

Mapgen chunks (usually 5 * 5 * 5 mapblocks) are roughly centered around the origin (0,0,0). "Roughly" because (0,0,0) has to be the first node of the mapblock (0,0,0). Hence, the chunk size is halved and rounded down (if necessary) to fit.

**Comment by srutzky** [comment]
Hello all ( @kay27 , @paramat , and @SmallJoker ). For what it's worth, I would like to add my vote for this functionality. Specifically, what @SmallJoker suggested a few comments above:

```
local minp, maxp = minetest.get_mapgen_edges()
```

This would be quite helpful for at least one mod I'm developing. I sometimes like to set `mapgen_limit` much smaller for certain worlds (why? because there's a config option that allows me to 😉 ) and hence can't rely on the min / max values that assumed a `mapgen_limit` of 31000. For now I have code similar to what @kay27 came up with in #10428 , and what @argyle77 is using for the "borders" mod:

https://github.com/argyle77/borders/blob/master/settings.lua#L41-L68

Another benefit (in addition to the efficiency of not having to calculate an already calculated value) is avoiding a potential bug found in the code for the "borders" mod (and likely found in other projects that rely upon any combination of `mapgen_limit`, `chunksize`, or `water_level`), but not in @kay27 's code shown at the top of #10428 :

"borders" mod:

https://github.com/argyle77/borders/blob/b9cf7fb5fba49b31e19205bd19ffef4109055233/settings.lua#L91-L93

code from #10428:

```
local chunksize = math.max(1, tonumber(minetest.get_mapgen_setting("chunksize")) or 5)
local MAP_BLOCKSIZE = math.max(1, core.MAP_BLOCKSIZE or 16)
local mapgen_limit = math.max(1, tonumber(minetest.get_mapgen_setting("mapgen_limit")) or 31000)
```

The difference (for readers who might not be aware of it), is `minetest.settings:get()` vs `minetest.get_mapgen_setting()`. `settings:get()` checks _only_ the **minetest.conf** file, whereas `get_mapgen_setting()` also checks the **map_meta.txt** file. This is import for those of us who are silly enough to place any of those 3 settings into the world-specific **map_meta.txt** file.

I will look into submitting a PR to fix the "borders" mod as that should be fairly simple.

For this particular change (i.e. creating a `minetest.get_mapgen_edges()` API function), I would love to help but don't do C++. I'm sure I could copy / emulate other code in **Minetest** that has similar behavior, but I have no way to compile and test it (and no time to set up / configure the dev environment for it).

On the other hand, I could probably update the [World boundaries](https://wiki.minetest.net/World_boundaries) wiki page to include both the calculation:

https://github.com/minetest/minetest/blob/master/src/mapgen/mapgen.cpp#L1068-L1096

and where to find and/or set those constants and user-configurable values. Is there any reason to not post the calculation and other info? I can't think of any (especially since the new function suggested by @SmallJoker does not yet exist and no telling when it will be).

**Comment by kay27** [comment]
Why not to reopen it, or desired API functions ore other replacement added somewhere? I still need MAX_MAP_GENERATION_LIMIT in Lua to avoid possible bugs with configuration changes

**Pull request closed without merging**
