### PR TITLE
Add console height setting

### PR DESCRIPTION
**Pull request by Ezhh**
Adds a setting to adjust the height of the console.

### CODE REVIEW

**Comment by paramat** [comment]
If the code is good i support this.

**Comment by Zeno-** [comment]
This looks fine to me. My only question would be why is it using
```
		gui_chat_console->openConsole(core::clamp(
			g_settings->getFloat("console_height"), 0.1f, 1.0f));
```
and not
```
		openConsole(core::clamp(
			g_settings->getFloat("console_height"), 0.1f, 1.0f));
```

**Comment by Ezhh** [comment]
Amended based on Zeno's suggestion.

**Comment by Zeno-** [comment]
Thank you ezhh

:+1:

**Comment by Ekdohibs** [comment]
:+1:

**Pull request merged**
