### PR TITLE
Add precompiled header support

### LINKED ISSUE #8620: Pre-compiled headers for MT
Compiling takes a **lot** of time. This is true for incremental builds as well (i.e. re-compiling only the translation units that have changed). But a lot of time can be saved by using pre-compiled headers, as the non-MT header files take up a significant chunk of MT's compile-time. Pre-compiled headers can greatly reduce compile-time by pre-compiling the headers that don't change (or change very rarely), and compiling only the contents of the changed .cpp file itself when re-compiling. We can add all the headers we use, from C++ standard library, STL, Irrlicht, and Lua to a new header file (say, `pch.h`), and set it up as a pre-compiled header.

As almost all the files are going to be touched in the process, there is a (very) slight chance of conflicts with other PRs, but they'd just be a couple of lines, if at all. So I wouldn't worry much, from that angle.

I'm more than willing to setup pre-compiled headers for MT, if there's no objections from the core devs. Thanks in advance.

### PR DESCRIPTION
**Pull request by numberZero**
Closes #8620 

This code works on my system, but seems to be rather fragile. Didn’t even try to test this on MSVC.

Build time, without this PR:
* real	4m47,934s
* user	17m19,127s
* sys	1m1,711s

With this PR:
* real	3m34,461s
* user	12m35,680s
* sys	0m52,808s

As you can see, there is some difference. Not much in real time; PCH content may need tweaking for that.

The add_pch file is from the [IrrLichtBAW](https://github.com/buildaworldnet/IrrlichtBAW/blob/master/cmake/add_pch.cmake) with my modifications, probably some notice is needed.

@ClobberXD

### CODE REVIEW

**Comment by ClobberXD** [comment]
Awesome! I'll test this out today, thanks! :)

**Comment by ClobberXD** [comment]
Tested!

### Results

#### Without PCH; clean build
```
cmake . -DRUN_IN_PLACE=1
time make -j2
```
```
real	6m39.539s
user	11m15.143s
sys		0m33.346s
```

#### With PCH; clean build
```
cmake . -DRUN_IN_PLACE=1 -DUSE_PCH=1
time make -j2
```
```
real	4m26.332s
user	8m8.701s
sys		0m26.482s
```

### PC specs

- CPU: Intel Pentium G2030
- RAM: 8GB DDR3-1600
- Storage: 1TB HDD

****

As is evident from the results, using PCH indeed improves the build speed substantially (**~33% faster than a non-PCH build** on my PC). I'm sure this can also be improved to a noticeable extent, by optimizing the PCH. However this can be done later too (or dropped completely), as it could potentially involve some significant refactoring of the code-base.

**Comment by Calinou** [comment]
@ClobberXD What about incremental build times (recompiling after changing a single line in a file)? This is the main factor during development.

**Comment by paramat** [comment]
Is this such a good idea seeing as the author has warned against using pre-compiled headers in the issue? See https://github.com/minetest/minetest/issues/8620#issuecomment-506036950 onwards.
> incremental build times are the main thing people care about during development.

Presumably incremental builds will be no slower?

**Comment by ClobberXD** [comment]
### Incremental builds

Incremental builds were simulated by taking a clean build, and replacing incorrect indentation in [server.cpp#L1574](https://github.com/minetest/minetest/blob/bb14b7e9564b982ddcecb972218bfdae00cb4de4/src/server.cpp#L1574) with two tabs.

#### Without PCH

```
real	0m11.730s
user	0m10.915s
sys	0m0.937s

```

#### With PCH

```
real	0m10.891s
user	0m10.070s
sys	0m0.952s
```

****

Unfortunately, the compilation time difference here is negligible. Hopefully that won't be the case when we have an optimized PCH setup.

@Calinou

**Comment by numberZero** [comment]
@ClobberXD Try using faster linker (`-fuse-ld=gold`, for example). Sadly incremental linking isn’t supported in GNU LD, but partial linking is (`-r`), that may help as well (but is nontrivial to setup in cmake).

**Comment by numberZero** [comment]
@paramat This PR may be discussed at any time. Travis error is internal and unrelated to PCH.

BTW it lacks the “low priority” label which the base issue has. And it’s not much of a “feature,” more like “maintenance,” although the exact labeling is up to you ofc.

**Comment by nerzhul** [comment]
i don't see interest on it because it's in very huge majority incremental builds.

**Comment by kilbith** [comment]
If people cared of global warming, this should be merged yet.

**Comment by rubenwardy** [comment]
This looks good, will make CI faster especially. Need rebase and possibly adoption

**Pull request closed without merging**
