### PR TITLE
Make pkgmgr handle modpacks containing modpacks properly (Fix #10550)

### LINKED ISSUE #10550: pkgmgr.lua:472: attempt to index a nil value
When attempting to enable the dev_plays_minetest modpack with mobs and homedecor already enabled

5.4.0-dev, latest

```
ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): pkgmgr.lua:472: attempt to index a nil value
ERROR[Main]: stack traceback:
ERROR[Main]: 	pkgmgr.lua:472: in function 'enable_mod'
ERROR[Main]: 	dlg_config_world.lua:197: in function 'handle_buttons'
ERROR[Main]: 	fstk/ui.lua:137: in function 'handle_buttons'
ERROR[Main]: 	ui.lua:181: in function </home/ruben/dev/minetest/bin/../builtin/fstk/ui.lua:167>
```

### PR DESCRIPTION
**Pull request by EliasFleckenstein03**
If you try to enable a modpack that contains modpacks in the main menu, the pkgmgr would crash. This PR fixes it.
(See #10550)

This PR is Ready for Review.

## How to test

Try out the example rubenwardy mentioned in #10550.

### CODE REVIEW

**Comment by EliasFleckenstein03** [comment]
I honestly find it a bit weird that a PR that fixes a **crash** is not reviewed once within almost two weeks.

**Comment by rubenwardy** [comment]
We're currently preparing a release and I'd been looking at the milestone PRs and forgot about this

**Comment by EliasFleckenstein03** [comment]
Well since it fixes a crash I think it should be in the release.

**Review by SmallJoker — APPROVED** [review]
Works, although the GUI is unaffected; nested modpacks are not shown as modpacks and are always shown as enabled.

grafik

**Pull request merged**
