### PR TITLE
Add guardonce to CI

### PR DESCRIPTION
**Pull request by Awkor**
This is my first time working with GitHub workflows, so please let me know if there are any errors or possible improvements.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Thank you for this contribution. Whereas this would remind developers, I don't think this additional Action is required. C/C++ contributors are generally aware of the header guards. Additionally new files are added quite rarely which means this Action would run for no reason most of the time.
Generally I think it would be great if checks could be skipped when no relevant code was changed (e.g. documentation changes).

**Comment by rubenwardy** [comment]
I don't think this is needed. Pragma once isn't especially error prone, and this is something review will easily pick up

**Comment by Awkor** [comment]
A possible reduction of the frequency of the action could be achieved by using a [schedule event](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule).

But other than that, feel free to close this PR since your arguments are more than understandable.

**Comment by Awkor** [comment]
Also, just in case, here are the files guardonce complains about:
``` 
./src/util/md32_common.h
./src/script/lua_api/l_particles_local.h
./src/gui/guiButtonItemImage.h
./src/gui/guiButtonImage.h
./src/client/render/factory.h
```

**Pull request closed without merging**
