### PR TITLE
Translation updater: Add comment propagation

### LINKED ISSUE #13947: Translation updater: propagates template.txt comments through other files
### Summary
I expect comments in template.txt to be propagated through other files, as they're quite likely to be instructions for translators (actually I can't think of any other use). Practical example: https://gitlab.com/zughy-friends-minetest/a.e.s.-server-custom-mods/a.e.s.-terms-of-service/-/issues/2#note_1502143795

@Wuzzy2

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
This PR adds comment propagation into the mod translation updater script that propagates comments from the template file into the translation files.

**How does the PR work?**
The comments from the template file are written above the comments from the translation file itself. There is a simple check to make sure that the comments from the template file are not propagated twice.

**Does it resolve any reported issue?**
This PR tries to fix #13947.

**Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?**
Yes, I guess.

**If not a bug fix, why is this PR needed? What usecases does it solve?**
See #13947 

## To do

This PR is Ready for Review.

## How to test
1. Run the script in a mod with comments in the template file.
2. Make sure that comments in the template file are propagated/copied into the translation files.
3. In the translation files, add some comments below the propagated comment.
4. Rerun the script again.
5. The propagated comment should not change and should not copied twice.

### CODE REVIEW

**Comment by Zughy** [comment]
I don't think it should be an option. Comments should always be useful, I can't see a reason why the modder wants to add comments in the template that shouldn't propagate for translators of existing files

**Comment by srifqi** [comment]
Is an opt-out flag fine?

**Comment by Zughy** [comment]
I guess, but yet again I don't see why people would skip comments propagation. Maybe @rubenwardy , as he 👍d your suggestion

**Comment by rubenwardy** [comment]
An opt out would make more sense if you see a usecase for this. I haven't thought of any

**Comment by Zughy** [comment]
I'd say to avoid adding it for now and, if in the future someone complains by bringing an usecase, to add it only then

**Comment by srifqi** [comment]
I have removed the flag and added this new behaviour to the documentation/README.

**Review by SmallJoker — APPROVED** [review]
Added some comments to default/locale/template.txt and the comments are indeed propagated to the other files. Carrying over empty lines might be helpful too - if that's easy to implement. Aside from that the PR works well.

**Pull request merged**
