### PR TITLE
ContentDB: Fix repeated Forum URL prepending

### PR DESCRIPTION
**Pull request by veprogames**
When clicking on an content db item over and over again, the forum url would keep being prepended with `https://forum.minetest.net/viewtopic.php?t=`, so it would become, for example:

`https://forum.minetest.net/viewtopic.php?t=https://forum.minetest.net/viewtopic.php?t=1234`

> [!NOTE]
> This PR fixes the issue but right now assumes that **info.forums is always of type "number"**

Note that the renaming is addressed in #15372 

## To do

This PR is a Ready for Review.

- [x] Fix Prepending of URL

## How to test

Repeatedly open and close the same ContentDB item (e. g. Minetest Game) and then click on "Forum Topic"

### CODE REVIEW

**Comment by appgurueu** [comment]
Works, but I find it slightly hacky. I've sent you a PR for a fix I would consider less hacky: https://github.com/veprogames/minetest/pull/1.

**Comment by rubenwardy** [comment]
I've added `forum_url` to the ContentDB API

**Comment by appgurueu** [comment]
@veprogames now that your other PR has been merged, you would need to rebase; and now that rubenwardy has added `forum_url` to the API, you should get rid of the code that formats the forum URL. I've done that for you in my https://github.com/appgurueu/minetest/tree/contentdb-url-bugfix branch, but it seems I can't force push to this branch since edits by maintainers aren't allowed. (A simple PR won't work either, since this is a rebase.)

**Comment by veprogames** [comment]
Sorry, I don't really have experience with rebasing, I tried to. Is it correct like this? Is it possible for you to create a PR with your changes now, or should I implement it myself, or do I need to fix my rebase attempt?

**Comment by appgurueu** [comment]
> Sorry, I don't really have experience with rebasing, I tried to. Is it correct like this?

I'm afraid not. It looks like you applied the commits the wrong way around - instead of applying your commits on top of the commits in master, you applied the new commits in master on top of your old commits.

> Is it possible for you to create a PR with your changes now

It is. I'll just do that :+1: closing in favor of #15379 (I'll preserve your original authorship when squashing).

**Pull request closed without merging**
