### PR TITLE
FreeType: address font license issues

### PR DESCRIPTION
**Pull request by sofar**
It appears we were shipping font files without license text, and I
had my doubts about the bitmap fonts being usable directly.

This replaces existing TTF fonts with Apache-2.0 licensed fonts from
chome core (Cousine, Arimo, Tinos). Include the full license file
for all three fonts.

The Lucida Sans font bitmap is removed entirely for non-freetype
builds. There is therefore only mono fonts for non-freetype builds.

### CODE REVIEW

**Comment by sofar** [comment]
replaces #5225 

This does not require freetype.

It does remove proportional fonts from non-freetype builds entirely.

**Comment by sofar** [comment]
@sfan5 @celeron55 @nerzhul @ShadowNinja @Ekdohibs @Zeno- @sapier

**Comment by Zeno-** [comment]
:+1:

**Comment by paramat** [comment]
:+1:

**Pull request merged**
