### PR TITLE
Set color of scrollbar/dropdown button symbols and checkmarks to white

### PR DESCRIPTION
**Pull request by erlehmann**
Add compact, short information about your PR for easier understanding:

- Goal of the PR

I have a contrast vision issue and have difficulties seeing the symbols on scrollbar and dropdown buttons.

This patch increases the color contrast of the symbols on scrollbar and dropdown buttons.

- How does the PR work?

Before this patch, symbols on buttons for scrollbars and dropdowns were rendered black on dark background.

This patch sets the default rendering color for the symbols to white.

- Does it resolve any reported issue?

Fixes https://github.com/minetest/minetest/issues/13909

- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?

Yes, general correctness (black on dark gray is incorrect according to many accessability standards) and/or UI improvements.

## How to test

1. Start Minetest without this patch.
2. Open the settings dialog.
3. Verify that the symbols on scrollbar and dropdown buttons are black on dark background, like in this screenshot:

minetest-580-dev-settings-fail-1

4. Start Minetest with this patch.
5. Open the settings dialog.
6. Verify that the symbols on scrollbar and dropdown buttons are white on dark background, like in this screenshot:

minetest-580-white-symbols-on-scrollbar-and-dropdown-buttons

7. Check with different values of GUI scaling (I tested 1.0, 2.0, 3.0, 4.0) if the checkmarks are all white. Restart Minetest to get the checkbox to resize.
8. Verify that the checkmark in the mod loading dialog for a world still looks white (it should be a bit brighter than before even).

**Edit:** If the color in my screenshot appears off-white it is probably because I use redshift to adjust the display's color temperature.

### CODE REVIEW

**Review by rubenwardy — APPROVED** [review]
Looks and works good.

I checked checkboxes, scrollbars, dropdowns, tabheader, and the file dialog. All of which look correct.

**Review by sfan5 — APPROVED** [review]

**Comment by erlehmann** [comment]
@rollerozxa noticed that checkmarks are also white now (which improves contrast too).

I have since also changed the PNG icons for the checkmarks too and force-pushed that.

Please check with different values of GUI scaling (I tested 1.0, 2.0, 3.0, 4.0) if the checkmarks are all white.

**Comment by sfan5** [comment]
The checkbox images are `#e5e5e5` not white, intended?

**Comment by erlehmann** [comment]
> The checkbox images are `#e5e5e5` not white, intended?

Good catch. Not intended. I just invented the using mtpaint and only checked visually afterwards.

Given that the high resolution symbols previously also were not black I wonder if there was a good reason for it.

I will try to figure out if I can easily compress the contrast and still have it look good.

**Comment by erlehmann** [comment]
@sfan5 is the way I modified the images in https://github.com/minetest/minetest/pull/13915/commits/ecc8d0fea0eeef8134c0f089b858b50d04cbef14 okay for you? It definitely looks brighter to me as well.

**Comment by sfan5** [comment]
Hmm, no. It loses the transparency:
grafik

Also now that `checkbox_16.png` is white, `checkbox_16_white.png` can be removed and its uses replaced.

**Comment by rollerozxa** [comment]
It's probably a better idea to modify the source vector file in `android/icons/checkbox_tick.svg` to be white and then reexport it to the respective sizes, rather than to change the colour of the exported textures.

**Comment by erlehmann** [comment]
> Hmm, no. It loses the transparency:

I think I may have botched this when upping the contrast. I should not have done that.

> now that `checkbox_16.png` is white, `checkbox_16_white.png` can be removed and its uses replaced.

I do not think that this is recessarily true, as that texture is used in a different context (it is the success icon for mod loading).

> It's probably a better idea to modify the source vector file in android/icons/checkbox_tick.svg to be white and then reexport it to the respective sizes, rather than to change the colour of the exported textures.

You are probably right. :sweat_smile: 

By the way, the original inversion seems to have been wrong because it used the wrong inversion method.

**Comment by erlehmann** [comment]
I have used GIMP's “linear inversion” feature now. The resulting color is RGBA (254, 254, 254, 255) – is this good enough?

I have zoomed in onto the results so I (hopefully) did not miss any loss of transparency information this time.

If this is not ok, I will do the SVG thing, but if this is good enough I will not.

**Comment by oong819** [comment]
> I have used GIMP's “linear invert” feature now. The resulting color is RGBA (254, 254, 254, 255) – is this good enough?
> 
> I have zoomed in onto the results so I (hopefully) did not miss any loss of transparency information this time.
> 
> If this is not ok, I will do the SVG thing, but if this is good enough I will not.

sorry im new here but we cant just use 255,255,255,255? or its because of PNG optimize or some other stuff?

i growned up in an environment that made it hard for me to take complete control over files (aka Android)

**Comment by rubenwardy** [comment]
> I do not think that this is recessarily true, as that texture is used in a different context (it is the success icon for mod loading).
> 
> Edit: You can find the usage in builtin/mainmenu/dlg_config_world.lua. To me, it seems also to be inverted in a gray-ish way.
> 
> I have seen the “let's deduplicate stuff that is bit-wise identical” urge already in some projects. @rubenwardy what do you think

I added that variant, if the main ones become white then that can be removed. It's just used as a white icon in the config menu

**Comment by erlehmann** [comment]
> > I have used GIMP's “linear invert” feature now. The resulting color is RGBA (254, 254, 254, 255) – is this good enough?
> > I have zoomed in onto the results so I (hopefully) did not miss any loss of transparency information this time.
> > If this is not ok, I will do the SVG thing, but if this is good enough I will not.
> 
> sorry im new here but we cant just use 255,255,255,255? or its because of PNG optimize or some other stuff?

It is just that the method I used (“linear invert” in GIMP) resulted in this and I hope no one cares about a tiny difference.
The other two methods I used before were noticeably different (for people other than me, who can see contrast better).

Ultimately, inverting a picture based on perceptual brightness is not the same as inverting the byte values in the bitmap.
See: https://www.actionvfx.com/blog/the-difference-between-linear-and-logarithmic-color-space-and-why-you-should-care

> I added that variant, if the main ones become white then that can be removed. It's just used as a white icon in the config menu

Fine, I will replace it. Just to be clear: This means the icon in the mod loading dialog will *always* have to be a white checkmark.

**Comment by erlehmann** [comment]
I have removed `checkbox_16_white.png` and edited `builtin/mainmenu/dlg_config_world.lua` accordingly.

I also added `Co-authored-by:` lines to the commit messages to make clear this was a shared effort.

Anything else to do?

**Pull request merged**
