### PR TITLE
Fix superflous shader setting updates

### PR DESCRIPTION
**Pull request by rubenwardy**
> Improve rendering performance by ~40%

Originally by @gregorycu #2320, but I fixed it to work with Irrlicht 1.7.x
He should get all the credit :)

### CODE REVIEW

**Comment by ShadowNinja** [comment]
kagrl's comment about `SkyBackgroundColorProvider` apparently being useless still applies.

**Comment by rubenwardy** [comment]
It stops Sky being modified, but it shouldn't be difficult to removed. It is rather pointless. If no-one fixes this by then, I'll do it tonight (in 9 hours). I fixed this because it seems like an important change that was being stopped because of a simple Irrlicht version incompatibility.

**Comment by Zeno-** [comment]
I think the bigger problem is that there is unnecessary abstraction and the creation of "factories" when they're not really needed.

**Comment by ShadowNinja** [comment]
@rubenwardy In that case, the `const` keyword is all that's needed.

The factory pattern is also rather ugly if it can be avoided.

**Comment by celeron55** [comment]
If the factory pattern is really needed, the reasons should be explained as a comment in the code too, not just in this PR.

**Comment by Fixer-007** [comment]
Why that PR was closed?

**Comment by ObaniGemini** [comment]
I totally agree with you. Shaders have become a major point for Minetest's look nowadays.

**Comment by rubenwardy** [comment]
> Probably because of compiling errors

This PR was opened as a corrected version of the previous.
The real objects are above, the over use of factories and additional classes.

**Comment by gregorycu** [comment]
For the record, it wasn't really a factory. More like the provider pattern,
and "too much" is subjective.

Close if you want. I'm too busy to focus on minetest at the moment. Maybe
somebody else will notice the issues and create a fix.

**Pull request closed without merging**
