### PR TITLE
Added get/set player modes CSM Lua API

### PR DESCRIPTION
**Pull request by EvidenceBKidscode**
This PR is for exposing `free_move`, `fast_move` and `noclip` modes to the Client Side Lua API. It adds two methods :

- `minetest.get_player_modes()` for querying state of current player `free_move`, `fast_move` and `noclip`;

 - `minetest.set_player_modes(modes)` for setting state of current player `free_move`, `fast_move` and `noclip`;

### CODE REVIEW

**Comment by paramat** [comment]
I'm wondering why this is useful or needed?

**Comment by paramat** [comment]
Clang format checker is being silly again (see details of build fail), ignore it, please silence the warning by adding this file to the whitelist at https://github.com/minetest/minetest/blob/master/util/travis/clang-format-whitelist.txt

**Comment by DS-Minetest** [comment]
Imo it should rather generally be possible for some settings to be changed via csm, not just `free_move` and co..

I think, this should at least wait until there's sscsm. Or to say it with @paramat's argumentation (https://github.com/minetest/minetest/pull/7008#issuecomment-413657247):
>Its best to avoid adding non-essential CSM features as it makes server-sent CSM development (which is already understaffed and uncertain) more difficult. Too many low-priority CSM features have been added already. I feel that no new CSM APIs should be added until server-sent is added, so i feel this PR should be delayed.
:-1: until SSCSM is added.

**Comment by paramat** [comment]
Well, settings should only be settable by CSM for a good reason =)

Sorry to write this after your work, but i disapprove of adding new CSM features until server-sent CSM is added.
I also can't see a need or usefulness yet.
:-1: 

Currently it still seems uncertain whether SSCSM will happen. It's not just nerzhul's responsibilty, it's a critical feature that will require help from other core devs, but all core devs have very little time recently and we seem to have only 4 or 5 active core devs.
Without SSCSM, CSM is pointless and not worth adding features too. New features also make adding SSCSM more difficult.
It's now 2 years since client-provided CSM was added, with no progress on SSCSM.

In future please consider opening an issue before starting work on a PR to discuss your proposal, unless of course coding it has value for you whether it's merged or not.

**Comment by pyrollo** [comment]
Hi,

I was not aware of the SSCSM issue and I understand it.

The usecase of this change is to be able to force free_mode to all recently connected players. Other settings have been added because it was costless. Another way to achieve that could be to have settings sent by the server to the client.

IMO, Minetest lacks flexibility and adding such possibility adds some and permits to change its behavior with a simple Lua mod.

Good advice for the issue. Anyway, we are working on a project with specific needs and want to share our changes in minetest engine. So, anyway the dev has to be done. It's not that important to be merged.

**Comment by paramat** [comment]
> The usecase of this change is to be able to force free_mo[v]e to all recently connected players.

Ok thanks, but that's functionality, not a usecase, why is it useful and/or needed in MT? 'Adding flexibility' is too vague, otherwise we would have to add every feature that can be thought of.
Why in CSM instead of server mods?
"force free_mo[v]e to all recently connected players" is written from the server's perspective, but SSCSM doesn't exist yet and may be distant or never happen, so that use seems based on SSCSM existing.

**Comment by nerzhul** [comment]
hello @EvidenceBKidscode 
the PR is not complete, you don't check for rights to change those values which are handled by server in some parts.
Can you add the API restrictions needed on the set ?

**Comment by paramat** [comment]
No response/progress for 6 months so closing for now.

**Pull request closed without merging**
