### PR TITLE
Mgvalleys: Fix missing decorations and incorrect function order 

### PR DESCRIPTION
**Pull request by paramat**
Fix missing decorations at horizontal chunk borders by adding
'updateHeightmap()' after terrain generation.

Swap order of 'calculateNoise' and 'calcBiomeNoise' because
'calculateNoise' modifies the heat and humidity maps created in
'calcBiomeNoise'.

Remove confusing comment, code block is not just for mods and
seems essential for correct mapgen behaviour.
////////////////////////////////////////

Addresses #5125 see that thread for details.

This seems to fix missing decorations and incorrect biome lines, as well as fix the incorrect function order created by kwolekr's big mapgen commit https://github.com/minetest/minetest/pull/4135/files#diff-1257c51e7822e6071317c35f9e0531ae
Details of the incorrect function order are here https://github.com/minetest/minetest/issues/5125#issuecomment-276318063

kwolekr's error altered the distribution of biomes, so with this PR biomes will be discontinuous in new terrain, however mgvalleys is still unstable.

### CODE REVIEW

**Comment by duane-r** [comment]
Alright. I'm taking less medication today and I'm stepping through this precisely. However, I still get the same issue.

Here's before the patch:

grassy-problem-03

Here's after:
grassy-problem-04

Once again, there's a single layer of grassy dirt showing up at y=47. In this case, it actually looked normal before. Can anyone else confirm using my favorite test world, "boomer"?

**Comment by paramat** [comment]
Yes i just realised my patch is the same as yours, i need to retest and this PR will probably need work.

**Comment by paramat** [comment]
I confirmed the bug at that location.

**Comment by paramat** [comment]
Please test updated PR, this seems to fix all issues as well as fix the incorrect function order created by kwolekr's big mapgen commit in May 2016.

**Comment by duane-r** [comment]
Outstanding! The bugs seem fixed, and the terrain hasn't changed otherwise. Do you want to delete that unecessary code as well?

**Comment by paramat** [comment]
I discovered that that 'unnecessary' code is in fact necessary to fix the bug. The comment above it gives the wrong impression that it is there only for mods. I'll edit the comment.

**Comment by paramat** [comment]
326cc5df741120dcfdfef21a7acaef5322601764

**Pull request closed without merging**
