### PR TITLE
Mgv6: Remove addDirtGravelBlobs. Desert stone y >= -32. Remove generateExperimental

### PR DESCRIPTION
**Pull request by paramat**
Mgv6: Remove addDirtGravelBlobs, replaced by blob ore in Minetest Game

Desert stone above y = -32 not water_level
Remove unused generateExperimental()

### CODE REVIEW

**Comment by C1ffisme** [comment]
Sounds Good.

**Comment by nerzhul** [comment]
Okay for me

**Comment by paramat** [comment]
Added more changes:
Desert stone above y = -32 not water_level
Remove unused generateExperimental()

**Comment by paramat** [comment]
Merged 22730bbc0cab1d93cb8ad5580c76c73c812e1693

**Pull request closed without merging**
