### PR TITLE
Add secondary viewing range

### PR DESCRIPTION
**Pull request by HybridDog**
people can temporary and simply switch to a second value,
so if they want to see further but not necessarily everything, they do not have to suffer extremely low fps if a lot map is loaded

hit r holding aux1 to switch

sorry for my bad English

### CODE REVIEW

**Comment by sofar** [comment]
Your commit title is too long. I've asked you before not to do this. I don't mind incorrect English, but please make a short title and then write a summary 2 lines below, instead.

**Comment by sofar** [comment]
How is this different from pushing 'r'?

**Comment by HybridDog** [comment]
>Your commit title is too long.

sorry for the one line title, l need to stop using commit -m

>How is this different from pushing 'r'?

hitting r without holding e en-/disables full view range
hitting r holding e changes vrange to the secondary one

After toggling full view range, the whole loaded map is shown, which often causes low fps.
But if you set your view range (temporary) to 1000, you can see a lot without extremely low fps.

**Comment by nerzhul** [comment]
@HybridDog git commit -m permit you to do

git commit -m "my title
my description"

**Comment by HybridDog** [comment]
nerzhul, thanks, l'm lazily used to hitting enter in a terminal only when executing the command

**Comment by SmallJoker** [comment]
I doupt I'll ever have a view distance of more than 1000 with R enabled because the client unloads the blocks that weren't used for a specified time. This could be only helpful when you teleport a lot from one world edge to another. IMO, there's no need this addition to the regular full view range.

**Comment by paramat** [comment]
:-1:  I don't feel it's needed enough. I feel the implementation is over-complex and awkward having another setting for an alternative view range, many times in-game you will find you will want a view range different from the chosen alternative.

**Comment by Fixer-007** [comment]
I think you are overcomplicating it.

**Comment by HybridDog** [comment]
>Here's a tip: to speed up the adjustment of view range, look down at the ground or straight up, to increase FPS, helps when looking long-distance.

It didn't work for me.

**Comment by MoNTE48** [comment]
@HybridDog, good idea. I'll add this in MultiCraft, but in a slightly different form.

**Comment by HybridDog** [comment]
@proller, how do you think about adding this to freeminer?

**Comment by HybridDog** [comment]
>Here's a tip: to speed up the adjustment of view range, look down at the ground or straight up, to increase FPS, helps when looking long-distance.

It does not work.

**Comment by HybridDog** [comment]
>Here's a tip: to speed up the adjustment of view range, look down at the ground or straight up, to increase FPS, helps when looking long-distance.

It does not work.

**Pull request closed without merging**
