### PR TITLE
Halo: highlight selected face

### PR DESCRIPTION
**Pull request by RealBadAngel**
screenshot_20160221_061728

screenshot_20160221_062423

### CODE REVIEW

**Comment by kilbith** [comment]
For what is it useful exactly ? Seems to be just a gadget.

**Comment by RealBadAngel** [comment]
@kilbith it does exactly what you can see. It is a gadget but very useful imho.

**Comment by kilbith** [comment]
The crosshair already indicates me what face I'm pointing, no need to be distracted with such a box.

**Comment by MoNTE48** [comment]
:-1: I'm sorry, bad very ugly unnecessary

**Comment by RealBadAngel** [comment]
@kilbith crosshair is tiny, sometimes barely visible. it fits rather selection boxes not the halo.
Also this is meant to be optional.

**Comment by ObaniGemini** [comment]
@kilbith : If you played minetest you would understand that crosshair is not very helpful, even more with halo box.
:+1: for that feature, if we can disable it and if we can tweak it's color/alpha

**Comment by MoNTE48** [comment]
Yes, if it is an easily customizable through .conf, I am for! :+1:

**Comment by MoNTE48** [comment]
@RealBadAngel, It would be helpful if the color and transparency of the halo can be set up using the conf.

**Comment by RealBadAngel** [comment]
@MoNTE48 you can control it with texture used. no need for dumb settings

**Comment by C1ffisme** [comment]
:+1:

Even if the texture doesn't get merged, the functionality would be nice.

What about making the selected face look a lighter shade of blue, rather than green?

**Comment by RealBadAngel** [comment]
@C1ffisme i tried but found out that is slightly better visible to change the color a bit
Anyway i suggest trying this in game, screenshots doesnt give the feeling. (Halo is animated)

**Comment by MoNTE48** [comment]
you can post a short video on youtube?

**Comment by RealBadAngel** [comment]
@MoNTE48 i cant, im on mobile with limits. Compile the PR and try

**Comment by paramat** [comment]
I can see some use for this because the halo doesn't clearly show it's edges, so it's not always obvious which face you are pointing at. However i'm not sure if there is enough need to justify the extra complexity.

**Comment by sofar** [comment]
I see a lot of value in this. I'd like the highlighted surface to be lighter though, and not a different tone.

**Comment by wilkgr76** [comment]
Looks good :+1: 

What happens when you point the at stairs?

**Comment by paramat** [comment]
@sofar since you like this, would you like to open a new PR with your version of this code, so we can close this?

**Comment by kwolekr** [comment]
I think this feature looks neat, but only makes sense if the crosshair was disabled.  Perhaps there could be a pointing indicator type option.

**Comment by yyt16384** [comment]
Sometimes what face you are pointing at is not clear from crosshair, so I think this feature is useful even if crosshair is enabled.

**Comment by Wayward1** [comment]
I think this would be awesome with the crosshair disabled

**Comment by paramat** [comment]
I can't see any point disabling the crosshair, it makes everything difficult to select or target.
If anyone is interested in reworking this in a new PR please copy the code for your use, we would like to close this. @sofar ?

**Comment by wilkgr76** [comment]
@paramat, I agree. Just because we have node highlighting doesn't mean we
hide the crosshair too...

**Comment by Wayward1** [comment]
Agreed, I'm not saying the crosshair has to be disabled with this, just that it would be neat if it was an option

**Comment by paramat** [comment]
Well, i think the crosshair is always needed when HUD is on, to highlight something small (even with halo used) you still need to know where the screen centre is. So i don't think it should be optional.

**Comment by paramat** [comment]
Note this seems to use face normals, so does it depend on vertex tangents?

**Comment by sofar** [comment]
I don't think it needs vertex tangents.

I toyed around with this code and removed the -off- colour. I just made the highlighted face lighter, which is what I proposed earlier. It looks good to me. It's very neutral and inconspicuous, but helpful nonetheless:

daytime: 

nighttime:

**Comment by sofar** [comment]
Replaced by #4653

**Comment by paramat** [comment]
Closing due to new PR.

**Pull request closed without merging**
