### PR TITLE
fix minetest.afters calling minetest.after

### PR DESCRIPTION
**Pull request by HybridDog**
should fix that problem https://forum.minetest.net/viewtopic.php?p=190461#p190461

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by est31** [comment]
Honestly, I can't reproduce it:
```
2015-09-10 08:37:39: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2015-09-10 08:37:42: ACTION[Server]: timerfunction called, calling again in 5 seconds
2015-09-10 08:37:49: ACTION[Server]: timerfunction called, calling again in 5 seconds
2015-09-10 08:37:55: ACTION[Server]: timerfunction called, calling again in 5 seconds
2015-09-10 08:38:02: ACTION[Server]: timerfunction called, calling again in 5 seconds
2015-09-10 08:38:09: ACTION[Server]: timerfunction called, calling again in 5 seconds
```
Admittedly though, it isn't very precise.

**Comment by HybridDog** [comment]
>Honestly, I can't reproduce it

l think reproducing it doesn't work if other mods call minetest.after, maybe you used one?

**Comment by GunshipPenguin** [comment]
I can confirm that on my machine, I was experiencing this bug, and this PR fixed it. 

I was using minetest at commit 64a5eec1bd92a352995ac510b69e6051421ee774 and the latest dev minetest_game with no mods active besides my small example "timerfunction" mod that I posted in the forums.

est31, perhaps try testing for this bug with the same setup that I used? I'm not exactly sure why you can't reproduce it.

**Comment by HybridDog** [comment]
l don't think it's the case here, sometimes juajits behave different, e.g.
```
local t = {1}
for n,i in pairs(t) do
 	t[n] = nil
 	if i == nil then
 	 	-- this happens on some luajits (not the one l use)
 	end
end

**Comment by est31** [comment]
But it seems to make sense, so I :+1: it.

**Comment by GunshipPenguin** [comment]
Is there any way this can get merged? It seems to have been forgotten about.

**Pull request closed without merging**
