### PR TITLE
Prevent technically unsafe access with empty vector

### PR DESCRIPTION
**Pull request by gregorycu**
This flags an assert with Visual Studio

### CODE REVIEW

**Comment by nerzhul** [comment]
assert is better there than return because you will trigger undefined behaviour by doing more things

**Comment by nerzhul** [comment]
:+1:

**Comment by celeron55** [comment]
:+1:

-1 to the design of C++ and Visual Studio though.

**Comment by nerzhul** [comment]
Merged 87dcee6ac2058bbf5264ea7f82874bba67277252

**Pull request closed without merging**
