### PR TITLE
Check for out-of-bounds breath when setting breath_max

### LINKED ISSUE #8212: Players's breath can be greater than breath_max
##### Issue type
 - Bug report
 
##### Minetest version
```
a809f7361e8a7232b3c9ec241be5adcae96b3b2d
```

##### Summary
When a player's max. breath is reduced below their current breath, the current breath is not capped at the max. breath value. This is a bug because the documentation says:

```
 * `set_breath(value)`: sets players breath
     * values:
         * `0`: player is drowning
         * max: bubbles bar is not shown
         * See [Object properties] for more information
```
So mods that only check if `breath` is equal to `max` (rather than equal or greater) are screwed.

This is also inconsistent with HP. When max. HP are reduced below your current HP, your current HP get reduced as well.

##### Steps to reproduce

Step 1: Use the test mod from #8211 to make your current and max hp/breath easily visible
Step 2: Use `luacmd`
Step 3: `/lua me:set_properties({breath_max=100})`
Step 4: `/lua me:set_breath(100)`
Step 5: `/lua me:set_properties({breath_max=20})`

You now have 100 breath, which is more than your max. breath.

Tested in singleplayer only.

### PR DESCRIPTION
**Pull request by ClobberXD**
Actually fixes #8212 :)

### CODE REVIEW

**Comment by lhofhansl** [comment]
Looks like this is not compiling... :-1: 

```
dev/minetest/minetest/src/script/lua_api/l_object.cpp: In static member function ‘static int ObjectRef::l_set_properties(lua_State*)’:
dev/minetest/minetest/src/script/lua_api/l_object.cpp:770:27: error: ‘class ServerActiveObject’ has no member named ‘getBreath’
  770 |    prop->breath_max < co->getBreath())
      |                           ^~~~~~~~~
dev/minetest/minetest/src/script/lua_api/l_object.cpp:771:7: error: ‘class ServerActiveObject’ has no member named ‘setBreath’
  771 |   co->setBreath(prop->breath_max);
      |       ^~~~~~~~~
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:1805: src/CMakeFiles/minetest.dir/script/lua_api/l_object.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
^Cmake[2]: *** Deleting file 'src/CMakeFiles/minetest.dir/client/game.cpp.o'
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:245: src/CMakeFiles/minetest.dir/client/game.cpp.o] Interrupt
make[1]: *** [CMakeFiles/Makefile2:215: src/CMakeFiles/minetest.dir/all] Interrupt
make: *** [Makefile:152: all] Interrupt
```

**Comment by lhofhansl** [comment]
(PlayerSAO *) cast missing :)

**Comment by SmallJoker** [comment]
Turns out the PR wasn't just failing the checks due to LINT. I should really be more careful with PRs which look this simple. Sorry for the trouble.
a2848c9

**Comment by ClobberXD** [comment]
Sorry for not getting back earlier - I was busy IRL. I did fix that missing cast, but I forgot to push the changes. Sorry again.

**Pull request merged**
