### PR TITLE
Fix incompatibility of ItemStack:to_table() introduced by stack meta

### LINKED ISSUE #5181: Backwards incompatibility of the latest metadata changes
Minetest technic mod crashes in this line when metadata is nil: https://github.com/minetest-technic/technic/blob/master/technic/tools/mining_drill.lua#L265

This crash doesn't happen in builds without the latest metadata changes.

debug.txt:
```
2017-02-05 11:44:05: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'technic' in callback item_OnUse(): /usr/local/share/minetest/builtin/common/serialize.lua:189: attempt to call method 'byte' (a nil value)
2017-02-05 11:44:05: ERROR[Main]: stack traceback:
2017-02-05 11:44:05: ERROR[Main]: 	/usr/local/share/minetest/builtin/common/serialize.lua:189: in function 'deserialize'
2017-02-05 11:44:05: ERROR[Main]: 	...as/.minetest/mods/technic/technic/tools/mining_drill.lua:265: in function 'mining_drill_mk3_handler'
2017-02-05 11:44:05: ERROR[Main]: 	...as/.minetest/mods/technic/technic/tools/mining_drill.lua:398: in function <...as/.minetest/mods/technic/technic/tools/mining_drill.lua:397>
```

@rubenwardy

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #5181

### CODE REVIEW

**Comment by Zeno-** [comment]
lgtm

**Comment by Thomas--S** [comment]
I tested this PR now: It seems to work fine. The bug described in #5181 doesn't happen anymore.

**Comment by rubenwardy** [comment]
Tested using:

```lua
minetest.after(0.5, function()
	local itemstack = ItemStack("default:stone 99")
	itemstack:set_metadata("foobar")
	itemstack:get_meta():set_string("test", "123")

	local tb = itemstack:to_table()
	print(dump(tb))
	print(dump(ItemStack(tb):to_table()))
end)
```

confirmed working

**Comment by Thomas--S** [comment]
Thank you very much!

**Pull request merged**
