### PR TITLE
Remove HW_buffer_counter after irrlichmt fix to remove HWBufferMap

### PR DESCRIPTION
**Pull request by paradust7**
Fixes issue #12231, in conjunction with https://github.com/minetest/irrlicht/pull/99#issue-1215982558

### CODE REVIEW

**Review by sfan5 — APPROVED** [review]

**Comment by lhofhansl** [comment]
Cool... Happy to see my old hack removed!

**Comment by lhofhansl** [comment]
Wait. We merged this before the Irrlicht change. Let's either revert this or merge the Irrlicht change quickly.
(I didn't have a chance to test it, yet).

**Comment by SmallJoker** [comment]
I do not update IrrlichtMt often so that recent Minetest builds continue to work (and do not need `LD_PRELOAD` with an old IrrlichtMt build). That makes bisecting and compatibility testing much easier. So yes indeed, people might indeed not update IrrlichtMt in sync with Minetest.

**Comment by sfan5** [comment]
It's okay if people use irrlichtmt tagged at a revision, the compatibility `#if`'s can deal with this. What might cause problems is random git commits.

**Pull request merged**
