### PR TITLE
Mapblock mesh: Allow to use VBO

### PR DESCRIPTION
**Pull request by RealBadAngel**
No VBO, regular vertices:
screenshot_20160222_041958
No VBO, tangent vertices:
screenshot_20160222_042037
VBO, regular vertices:
screenshot_20160222_042127
VBO, tangent vertices:
screenshot_20160222_042203

### CODE REVIEW

**Comment by RealBadAngel** [comment]
screenshot_20160222_043257
screenshot_20160222_043453

**Comment by sofar** [comment]
Logged onto "Just Test" spawn area and fps went from ~28avg to ~45avg, sometimes making it up to 60fps (without VBO enabled it wouldn't even top 40fps)

**Comment by sofar** [comment]
Tested on an Intel HD 4000 system as well - after 30 minutes still at 1.0gb flat memory usage, not seeing any discernable memleaks.

**Comment by kilbith** [comment]
Tested on Intel HD 4400, on Megaf's server (same scene with lot of buildings around) : I went from ~45 FPS to ~50 FPS.

So roughly a +5 FPS increase with this PR :+1:

**Comment by Fixer-007** [comment]
Will test today and post in this comment.

**Comment by C1ffisme** [comment]
:+1: since it improves performance.

**Comment by RealBadAngel** [comment]
@Fixer-007 on the screenshots i havent got relief mapping enabled (its quite heavy duty stuff)

**Comment by MirceaKitsune** [comment]
At long last, there is a pull request for a working VBO patch! Thank you. I might try this out later, in any case a big :+1: to this feature.

**Comment by Fixer-007** [comment]
So far, no issues with VBO (mem or anything), also, huge fps improvement with 3770 included.

**Comment by cheapie** [comment]
Seems to be giving me a huge performance boost too. :+1:

**Comment by est31** [comment]
:+1: seems to clean up afterwards so the spooky leak issue should be fixed.

**Comment by kahrl** [comment]
:+1: as discussed in IRC

**Comment by Fixer-007** [comment]
Windows build for testers: 
[minetest-0.4.13-f3f4af3-win64-PR3763.zip](https://github.com/minetest/minetest/files/144937/minetest-0.4.13-f3f4af3-win64-PR3763.zip)

**Comment by paramat** [comment]
26 to 39 FPS with VBO PR, 50% increase (singleplayer, Intel Haswell Desktop integrated graphics).
Flying over landscape memeory use stabilises at only 1GB.
:+1:

**Comment by paramat** [comment]
======== Testing module TestThreading
Test assertion failed: thread_retval == thread
    at test_threading.cpp:107
[FAIL] testStartStopWait - 79ms
[PASS] testThreadKill - 403ms
[PASS] testAtomicSemaphoreThread - 13ms
======== Module TestThreading failed (1 failures / 3 tests) - 496ms

**Comment by paramat** [comment]
f9d727764fc9c74990fc979d4966a33882d0c19b

**Pull request closed without merging**
