### PR TITLE
Various anticheat improvements

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by est31** [comment]
It looks good, but what is the "Do 'interact' privilege check first" commit needed for?

**Comment by sfan5** [comment]
@est31 
It makes no sense to do the range check and report a cheat violation to Lua when the player can't interact generally anyway.

**Comment by est31** [comment]
Well, I guess a better error message means improvement

:+1:

**Comment by lhofhansl** [comment]
FWIW: :+1:

**Comment by tobyplowy** [comment]
@sfan5  https://youtu.be/Cgx6CEuZ4Vo you probably already know about this but Still

**Comment by Fixer-007** [comment]
There is another commit added here that prevents taking your bones after death by clicking Respawn and then bones.

**Comment by sfan5** [comment]
b16252dcae8c6b0e79c20fa4c3cbddc37ad377cb

**Comment by lhofhansl** [comment]
@sfan5 Seems that I am getting this in legitimate cases as well:
`2016-12-29 09:35:47: ACTION[Server]: Player Lars tried to access [node under=-179,23,193 above=-179,23,192] from too far: d=62.5343, max_d=40. ignoring.`

This is hitting some leaves with a diamond sword. Seems that it's picking up the `BS * 4.0` case.

**Comment by lhofhansl** [comment]
It seems itemDef range and hand range are always `-1`.

**Comment by lhofhansl** [comment]
Perhaps a guess, but perhaps the factor should be sqrt(3) ~= 1.73 instead of 1.5, if one reaches out diagonally. In fact the largest distance that was rejected I could manage was 67.53. 67.53/40 ~= 1.688.

**Pull request closed without merging**
