### PR TITLE
Batched rendering of particles

### LINKED ISSUE #1414: Particles are very slow
Minetest uses a custom particle(spawner) implementation using entities, this is very slow.
Irrlicht's built-in particles are much faster, as you can see [here](https://www.youtube.com/watch?v=5WnmQYLJzlE).

Irrlicht's particles don't support collision by default, but this can be done with particle affectors (see [here](https://www.youtube.com/watch?v=-brLc8uUeQk)).

EDIT: Done (but with issues) by #2587.

### PR DESCRIPTION
**Pull request by x2048**
Improves performance by rendering particles with the same texture as a single mesh buffer. Possibly resolves #1414 

Puts limits on how many particles can be drawn:
* 16K particles per texture.
* 64K particles in total.
* Within 200 nodes from the local player.

Example results:
AMD Renoir
34K particles on the screen
13 FPS on master
45 FPS on the branch. 

## To do

This PR is  Ready for Review.

## How to test

Minimal test:
1. Launch dev test
2. Get particle spawner
3. Spawn particles around and watch them animate and disappear. No glitches.

Example code for performance test:
```
local nodes = {}
local players = {}

local torch_colors = {
	"#0F0000",
	"#0F0800",
	"#080F00",
	"#080F00",
	"#000808"
}


minetest.register_abm({
	nodenames = { "default:torch" },
	interval = 1,
	chance = 1,
	catch_up = false,
	action = function(pos, node)
		local meta = minetest.get_meta(pos)
		local color = meta:get("colored_torch:color")
		if color == nil then
			color = torch_colors[math.floor(math.random() * #torch_colors) + 1]
			meta:set_string("colored_torch:color", color)
		end
		minetest.add_particlespawner({
			pos = { min = vector.add(pos, vector.new(-0.2, 0.35, -0.2)), max = vector.add(pos, vector.new(0.2, 0.45, 0.2)) },
			vel = { min = vector.new(-2, 7, -2), max = vector.new( 2, 5, 2) },
			acc = { min = vector.new(0, -6, 0), max = vector.new(0, -5, 0) },
			time = 1,
			amount = 160,
			exptime = 6,
			collisiondetection = false,
			collision_removal = false,
			glow = 14,
			texpool = {
				{ name = "flame_spark.png^[multiply:"..color, blend = "screen", scale = 3 },
			}
		})
	end
})
```

### CODE REVIEW

**Comment by rubenwardy** [comment]
Thanks so much!

**Review by appgurueu — COMMENTED** [review]
Minor concern: Won't this mess with particle-particle blending? (Since this can at best sort particle vertices per-texture).

(Only a minor concern because (1) particle-nonparticle blending doesn't work anyways and (2) particle-particle blending has only been fixed recently-ish (5.6 IIRC) (3) acceptable performance has priority (4) particle-particle blending will still work among particles that use the same texture or that use order-independent blend modes)

**Comment by lhofhansl** [comment]
I've had this enabled for a few days. Observed nothing undue. Works.

**Comment by Zughy** [comment]
Note for devs: if there are no major reviews, this PR can still get approved and merged

**Comment by appgurueu** [comment]
> I've had this enabled for a few days. Observed nothing undue. Works.

Have you tested with semitransparent particles with different textures?

**Comment by lhofhansl** [comment]
> Have you tested particle-particle blending among semitransparent particles with different textures?

No I have not.

**Comment by Desour** [comment]
Here's a rebased version, plus some small code quality improvements, like `irr_ptr` and code style: https://github.com/Desour/minetest/tree/x2048_particle-performance_rebased

**Comment by Zughy** [comment]
@Desour if you confirm you want to take care of this PR, feel free to close this one

**Comment by Desour** [comment]
I'd prefer if someone else adopts it.

**Comment by jordan4ibanez** [comment]
Hello there core dev teams, this is my child now. I have adopted it. Please give me the rights or whatever adoption requires

**Comment by rubenwardy** [comment]
@jordan4ibanez you just need to open a new pr for it

**Comment by Desour** [comment]
@jordan4ibanez Have you considered taking the rebased branch I've linked up there? It was meant to be used by the adopter.

(As there seems to be quite some confusion on why I didn't adopt this, let me clarify: Much of the work needed for this PR, i.e. testing that everything still works, especially with alpha blending issues and whatnot, is still left to be done. And this PR is not high on my already too long priority list.)

**Comment by jordan4ibanez** [comment]
Hello desour, please comment any issues on the new pr, thank you

**Pull request closed without merging**
