### PR TITLE
UTF8 in formspecs

### PR DESCRIPTION
**Pull request by est31**
Add UTF-8 for formspecs. I make sure this doesn't re-introduce #1166, by not using intlGUIEditBox for Irrlicht >1.9, also because entering special characters works there.

### CODE REVIEW

**Comment by est31** [comment]
will fix #1638

**Comment by est31** [comment]
@Calinou can you try whether this fixes #302 ?

**Comment by indriApollo** [comment]
I compiled your branch on ubuntu 15.04 against irrlicht 1.8.1 .
Special characters (éèç...)do work well (1000X thanks !)but I still can't type "7" when using an azerty layout.
It does work when switching to qwerty or by typing in the console.

Image

**Comment by RobertZenz** [comment]
@indriApollo Do you mean literally seven? In that case that sounds like a bug in Irrlicht, similar to #1898.

**Comment by est31** [comment]
b6387b4e0f43503ae139cb31a04f42c401378fdc
572990dcd3f43386860b5b14015ad722fb96ea83

**Comment by Rui914** [comment]
Freeze when I enter the Japanese in chat...

**Comment by est31** [comment]
It works for me. I don't have the font, but when I look at the chat from irc, I can see japanese characters. Does it work with the f10 console @Rui914. Also, please file a bug.

**Comment by Rui914** [comment]
Freeze in normal chat menu (T).
It not be logged.

**Comment by est31** [comment]
Does it work with f10 console?

**Comment by Rui914** [comment]
Yes, it works.
However, input of the console screen was working from before.

**Comment by est31** [comment]
you say you use klipper? then you don't actually enter characters with the keyboard, but paste them from clipboard?

**Comment by Rui914** [comment]
I can't enter without Klipper.

**Comment by est31** [comment]
[can you file a bug](https://github.com/minetest/minetest/issues)? this PR is merged.
Which writing system? Hiragana? Katakana? Kanji?

**Comment by Rui914** [comment]
>Hiragana? Katakana? Kanji?
All.

**Pull request closed without merging**
