### PR TITLE
Remove some old dead code. Fix some Clang warnings in SRP

### PR DESCRIPTION
**Pull request by nerzhul**
ng->N... will always evaluate to true and other are noticed by Clang but not by GCC.
This also remove some very old and disabled code in minetest.

### CODE REVIEW

**Comment by est31** [comment]
+1

**Comment by nerzhul** [comment]
will merge it in ~30min then thanks for the review :)

**Comment by nerzhul** [comment]
pushed

**Comment by nerzhul** [comment]
https://github.com/minetest/minetest/commit/aab7c83d0229c2c7aa3b60de3ca1b1a4eb326b55

**Pull request closed without merging**
