### PR TITLE
Network protocol documentation

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by SmallJoker** [comment]
Copy-paste does not improve any documentation. The network protocol header isn't an explanation of how the network is structured. We'd have a worse, less helpful documentation if this gets merged. :-1:

**Comment by zaoqi** [comment]
@SmallJoker 
But I do not know something about the network protocol, and no one else will write the network protocol.

**Comment by paramat** [comment]
:-1: For the reasons SmallJoker explain.

**Comment by Ferk** [comment]
Yeah.. rather than doing that, you could just place a link to the github file, which would be more up to date and with proper syntax highlight. Copy pasting would get outdated easily and would just be useless.
https://github.com/minetest/minetest/blob/master/src/network/networkprotocol.h

**Pull request closed without merging**
