### PR TITLE
Remove shadow_sky_body_orbit_tilt setting with the next major release

### LINKED ISSUE #13705: Remove shadow_sky_body_orbit_tilt setting
## Problem

The orbit tilt can already be changed through the API

## Solutions

There is no need to have a client setting for that. If you want to run some test with different angles, just use the API like you'd do with any other aspect of the engine

### PR DESCRIPTION
**Pull request by Zughy**
Partly fixes #13705 , it needs to disappear from settings as well (@rubenwardy ?)
See https://github.com/minetest/minetest/issues/13705#issuecomment-1658508029
## To do

This PR is Ready for Review.

## How to test
1. Stand on one leg
2. tilt your head by 57° to the right
3. start jumping
4. read

### CODE REVIEW

**Comment by grorp** [comment]
`shadow_sky_body_orbit_tilt` is a pure client-side setting, so removing it would be no compatibility breakage. You can hardcode a default value of `0.0f` for `body_orbit_tilt` instead of reading the default value from `shadow_sky_body_orbit_tilt`.

The setting was reintroduced to fix an uninitalized value on the client in some cases. See this comment by x2048:

> the problem was in not having a default value in SkyboxParams when deserialization fails of skips the value. I've returned the setting to act as a drop-in value in these cases.

_Originally posted by x2048 in https://github.com/minetest/minetest/issues/13340#issuecomment-1475063215_

It should cause no problems to have a hardcoded default value instead.

**Comment by Zughy** [comment]
@grorp I hope it's correct

**Comment by grorp** [comment]
This is what I meant. In theory, this should be backwards compatible, except for singleplayer-only games with a `shadow_sky_body_orbit_tilt` setting in their game-specific `minetest.conf`.

Going one step further, we could replace the `nil` server-side default value with a default value of `0.0` as well, but that could break mods which do something like this:

```
if not player:get_sky().body_orbit_tilt then
   player:set_sky({ body_orbit_tilt = 60 })
end
```

----

Anyway, this PR needs a zipgrep. And probably it should get a review by x2048 when you're ready.

**Comment by rubenwardy** [comment]
Searched in .lua and .conf files:

image

**Comment by Zughy** [comment]
@x2048 thoughts?

**Comment by SmallJoker** [comment]
I don't see how such minor change in settings would need any special treatment. The functionality is not lost. Simply remove all traces of `shadow_sky_body_orbit_tilt` and merge this thing. No need to make a big fuss about it.

**Comment by grorp** [comment]
@rubenwardy Could you do a zipgrep for "body_orbit_tilt" as well? Then we would know whether we can also remove the special `nil` logic for `body_orbit_tilt` in `set_sky`.

**Comment by rubenwardy** [comment]
> @rubenwardy Could you do a zipgrep for "body_orbit_tilt" as well?

This is also not present in any .lua or .conf files

**Comment by x2048** [comment]
@Zughy I guess you'll have to decide it without me: https://irc.minetest.net/minetest-dev/2023-10-01#i_6119219

**Comment by rubenwardy** [comment]
what action/change does this need?

**Comment by grorp** [comment]
> what action/change does this need?

Removing the `INVALID_SKYBOX_TILT` thing as well, it only exists because of the setting.

But I'd also be fine with just removing the setting and keeping the `INVALID_SKYBOX_TILT` thing.

**Comment by Zughy** [comment]
...and I've fucked up my git history

**Comment by Zughy** [comment]
Well, let's cut the chase: this PR was initially just a documentation PR. It's clear I have no idea of what I'm doing now and that grorp is babysitting me. Considering also the current git history, I simply invite anyone to take over, as I feel we're all wasting our time at the moment. Closing and labelling for adoption

**Pull request closed without merging**
