### PR TITLE
Allow flooding to cause item drops

### PR DESCRIPTION
**Pull request by cyisfor**
Non-air nodes can be defined as floodable, and now they'll drop their contents rather than just being replaced with air.

### CODE REVIEW

**Comment by PilzAdam** [comment]
AFAIK it's intentional that items are not dropped if they are flooded by water.

**Comment by est31** [comment]
IMO the engine should allow for whatever mods want, even for really bad ideas like letting liquids drop plants. Its a griefer's wet dream...

**Comment by Thomas--S** [comment]
I suggest to make the behaviour configurable.

**Comment by paramat** [comment]
Yes 'floodable' is to allow liquid to flow into vacuum, alien atmosphere, gas or any airlike nodes, which should not be dropped. There is some discussion somewhere about if or how to implement optional drops, but i am not keen on making liquid drop nodes as items. I'll post a link to the discussion when i find it.

**Comment by PilzAdam** [comment]
@est31 maybe change the floodable field to allow specifying that nodes should be dropped when flooded?

**Comment by sofar** [comment]
I don't think it can be as simple as this anyway.

If there is an `on_flood()` callback, at least you can pass the `liquid` as a parameter, so that the callback function can decide whether to have the node destroyed (by e.g. lava) or dropped (by e.g. water), or maybe something else (enable a generator of some sorts, or heat a furnace, etc.). 

I'm somewhat positive about the concept, but I think this is too simple.

**Comment by tenplus1** [comment]
@sofar - So an example for something like lava source would be:
```
on_flood = function(pos, liquidnode)
    if minetest.get_item_group(liquidnode.name, "water") > 0 then
        minetest.set_node(pos, {name = "default:obsidian"}
    end
end,
```
... thus saving on using an Abs to do the same action.

**Comment by paramat** [comment]
^ Good idea.

**Comment by sofar** [comment]
Yes, something like that is what I had in mind.

**Comment by Ferk** [comment]
An on_flood callback could be very useful to get rid of ABMs involving water. It could also for example be used to turn soil into soil_wet

**Comment by sofar** [comment]
:-1: I don't feel this is right, at all, and would be much more interested in seeing an on_flood() callback implementation as discussed above.

**Comment by paramat** [comment]
There is general dev agreement that an on_flood callback is the way to do this.

**Pull request closed without merging**
