### PR TITLE
Add keybinds for camera panning to allow keyboard-only gameplay

### PR DESCRIPTION
**Pull request by tmagik**
This is a DRAFT WORK-IN-PROGRESS for comment

That being said:

- Goal of the PR: enable keyboard only (or one-hand? .. see https://github.com/minetest/minetest/issues/11684 ) 
- How does the PR work: This adds support for using the keyboard only for controlling look direction

## To do

This PR is a Work in Progress 

## How to test

compile and use the arrow keys.

Currently "KEY_LEFT" is incorrectly mapped to both left, and jump.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Haven't looked the code, yet, but I support this idea.

**Comment by SwissalpS** [comment]
In addition to using arrow keys, maybe use the numpad keys too for players who have them.
That would allow diagonal looking: num_pad_7 -> up and left.
num_pad_5 would reset view to straight ahead.

**Comment by Montandalar** [comment]
I've never tried it, but isn't the idea of operating system features like Windows MouseKeys to provide this kind of functionality so that every individual application doesn't need to?

To focus on improving keyboard support, I would prioritise making it clear where the GUI selection lies for formspecs.

I'm not totally opposed to the idea, however.

**Comment by rubenwardy** [comment]
>  To focus on improving keyboard support, I would prioritise making it clear where the GUI selection lies for formspecs.

This is part of #11392

**Comment by ndren** [comment]
This sounds like a great thing to have, I like it. Is it WIP because it's missing something or is that because you were waiting for feature feedback?

**Comment by Zughy** [comment]
@lhofhansl assigning you due to your comment. If I'm mistaken, feel free to remove yourself!

**Comment by tmagik** [comment]
@ndren it in theory works for me, but on a Mac if I press the 'KEY_LEFT' it also triggers a jump so something is wrong, but I can't figure out what.

Do you get the same behavior on Windows/Linux?

**Comment by Montandalar** [comment]
Compiled and tested this. It is in a working but buggy state. The left arrow key will both jump and move the camera left, and the spacebar won't jump. Something non-obvious must have gone wrong in the control code. Something with enums, data types and switches possibly. Operating system is Linux/X11 (Debian 12).

A few other minor issues to address:
- This creates a fourth column on the "change keys" menu which falls off the edge due to insufficient width. This menu is already 3 columns wide, so it is probably better to add rows than columns.
- Intuitively to me, I would have thought the sensitivity settings would be found under Controls -> Keyboard and Mouse, but they're under Controls -> General.
- This doesn't expose the keys to the Lua API. Is this deliberate? What about the CSM API? (That probably shouldn't be different, but I want to discuss it so it's not overlooked.)

**Pull request closed without merging**
