### PR TITLE
Ability to define and use LUA wield animations

### PR DESCRIPTION
**Pull request by TheMrAmazing**
I found this old pull request: https://github.com/minetest/minetest/pull/7517
that added several wield animations in C++ that could be added to tools, such as an eating animation or a digging animation. It looks like it was rejected because you could not define new animations in LUA, making it not particularly useful for modding. I really liked the concept, so I added the ability to add new wield animations through the LUA.

This is my first time contributing, so I'm sure I've made some mistakes, but I'm happy to fix whatever is needed to get this feature added to the game

### CODE REVIEW

**Comment by sorcerykid** [comment]
I've long been waiting for a feature like this in the engine. Thank you for taking it on!

**Comment by TheMrAmazing** [comment]
So it looks like it's compatible now, anything else that I need to do before it can be merged?

**Comment by SmallJoker** [comment]
What is this? The history is completely wrecked.

**Comment by TheMrAmazing** [comment]
Sorry, it's my first pull request ever, I had no idea what I was doing. Is there something I can do to clean it up?

**Comment by SmallJoker** [comment]
Option 1:
1) `git format-patch {githash}` or `git format-patch HEAD~{number of commits to go back}` to export each relevant change
2) `git reset --hard upstream/master` where `upstream` is to be replaced by this repository's remote name
3) `git am -3 {0000-patchfile.patch}` apply each change in order and resolve conflicts

Option 2:
1) `git rebase -i HEAD~17`
2) Discard unwanted commits
3) Resolve conflicts
4) `git rebase upstream/master` (update to this repository's state)
5) Resolve rebase conflicts (if there are any)

**Comment by TheMrAmazing** [comment]
Ok, I'm just testing now, I think I've cleaned it all up

**Comment by paramat** [comment]
Actually the simplest way to clean this up is to:
* Make some kind of copy of the relevant changes, a text file, a screenshot, anything.
* Delete this branch.
* Start a new branch and start a completely fresh PR.

This is what i would do.

GitHub help section has a good and clear step-by-step guide to creating PRs, i recommend following that.

**Pull request closed without merging**
