### PR TITLE
minetest.after globalstep: Only test all jobs if at least one job expired

### PR DESCRIPTION
**Pull request by HybridDog**
If you e.g. execute 1000 times minetest.after with time 10s, it loops through the 1000 jobs at first when at least one is expired (10s),
before the PR it tested every (1000) job in every globalstep, so it performed lots of redundant loops through the jobs.

### CODE REVIEW

**Comment by nerzhul** [comment]
usecase ?

**Comment by DS-Minetest** [comment]
>usecase ?

I think this is for performance, not a feature.

**Comment by juhdanad** [comment]
A priority queue might be better. The `jobs` array should be sorted based on execution time, then you can write:

```
while (jobs[0] exists and should be executed)
    execute jobs[0]
    remove jobs[0]
end
```

This only checks the most relevant job/jobs every step.

**Comment by HybridDog** [comment]
juhdanad, l tried it but l didn't find an efficient workaround for the minetest.after in minetest.after execution.
```
 -- This mustn't cause an infinite loop.
local function f()
	minetest.after(0, f)
end
f()
```
https://github.com/HybridDog/minetest/commit/20f1e43f3b4e936038acbe75d676826020171461 (pairing heap)
https://github.com/HybridDog/minetest/commit/497cfef8921a294f67536b9a65650e6a2c0596c2 (sorted jobs table)

**Comment by rubenwardy** [comment]
Double buffering. Ie, queue any Minetest afters in a separate list when executing afters, then merge sort

**Comment by SmallJoker** [comment]
This solution is the easiest to speed up the whole job processing part (KISS). The next step would be inserting the new jobs in the correct table position to keep it sorted by time, basically a simplified version of HybridDog/minetest@497cfef . But it's not like we would have hundreds of `minetest.after` jobs in the queue, thus this looks way too over-engineered for now.
I'm fine with the current PR state.

**Comment by HybridDog** [comment]
rubenwardy, l tried it (the second link, quicksort instead of mergesort).
#
> basically a simplified version

l don't know how you could simplify that.

> it's not like we would have hundreds of [jobs]

If you have only a few minetest.afters, double buffering (overhead) and additional code (processor cache usage) would reduce performance l think.

**Comment by rubenwardy** [comment]
I was referring to a way to stop infinite loops when calling after in an after callback. If you double buffer so that any calls to after won't be executed until the next after, then this problem is fixed.

Also, there may well be hundreds of afters running depending on the number of players and the mods.

**Comment by rubenwardy** [comment]
@sofar was the last one to touch this code, and I remember it doing a sorted list before, so there's probably a reason this changed

**Comment by HybridDog** [comment]
So you mean moving the expired jobs from the priority queue to a temporary table and then executing the functions. Seems to work: https://github.com/HybridDog/minetest/commit/d47d5e188abb694f9024cb9e24d7f0c370a79ad1

> so there's probably a reason this changed

Maybe it's due to simplicity.

**Comment by raymoo** [comment]
A sorted list has the same asymptotic complexity since inserting is O(n) and so is searching the entire list. Since new jobs are likely to be placed near the end of the list (later end times), an average insertion probably went through most of the list anyway.

**Comment by HybridDog** [comment]
raymoo, l don't want this PR but the pairing heap.
https://github.com/minetest/minetest/pull/6070

**Comment by sofar** [comment]
These optimizations are premature, by a significant margin:

- I don't see data backing up any performance claims. There are some hypothetical claims of value but without some actual numbers in a real server, it's mostly just guess work if you ask me.
- none of this matters because the amount of timers running in most cases is small (half a dozen, most likely, is all that is queued) and the suggested optimizations likely don't do much better with that small of a queue.
- 95% of the server resources go to servicing ABMs, so you're not going to make any dent in server CPU time this way.

So, I think we should keep this code as simple as is. This and #6070 just increase the complexity and maintenance burden at no real benefit.

**Comment by nerzhul** [comment]
i agree with sofar, this loop is ridiculous compared to ABM load which should be optimized by moders there is only ~10-15 items in that list genrally

**Comment by raymoo** [comment]
@HybridDog I was just suggesting a reason why the queue code was changed originally. Also, I feel that a simple binary heap would have better real performance than pairing heaps in Lua, because pairing heaps require many new table allocations, but that would need benchmarking to see at what size pairing heaps become better.

**Comment by sofar** [comment]
@raymoo I have no issues with people exploring optimizations, even if they go this far, I just don't think that even if you find an optimization that actually has a measurable, and beneficial, impact, that applying it wouldn't weigh against the simplicity of the current code. 

To put it simply: there are bigger problems by several orders, no optimization here will fix that. So the cost (overhead, maintenance) of optimization isn't outweighed by the (miniscule) benefits.

**Comment by raymoo** [comment]
@sofar I'm not saying we should switch to some other queue implementation, just that I don't think pairing heaps would be a good choice if we did.

**Comment by HybridDog** [comment]
> because pairing heaps require many new table allocations

It doesn't look it https://github.com/HybridDog/minetest/commit/6a189cfd2aaead74d93718a243efe526eb793ce3

**Comment by nerzhul** [comment]
supersede by #6070

**Pull request closed without merging**
