### PR TITLE
Fix minetest.item_eat's replace_with_item, fixes #2292

### LINKED ISSUE #2292: Eating from stack removes the whole stack using replace_with_item

### PR DESCRIPTION
**Pull request by rubenwardy**
When a stack is bigger than 1, it adds the replace_with_item to the inventory rather than to the stack, which overwrites them.

From a patch submitted to better hud by @tenplus1

BlockMen/hud/issues/14

### CODE REVIEW

**Comment by rubenwardy** [comment]
From a patch submitted to better hud by @tenplus1

BlockMen/hud/issues/14

**Comment by PilzAdam** [comment]
`replace_with` sounds like a replacement to me, so IMO this is not a bug. If you want to add additional items to the player's inventory then use `on_item_eat`.

**Comment by rubenwardy** [comment]
It is when it replaces all of the stack, rather than replacing the item which you just ate. So it is a replacement.

If there is only one item left in the stack, it replaces that item at that location rather than adding to the inventory. If there is more than one item, it doesn't lose the spare items.

**Comment by C1ffisme** [comment]
:+1:

**Comment by ShadowNinja** [comment]
I agree with rubenwardy.

The code should be restructured a bit to reduce indentation, but otherwise it seems good.

**Comment by rubenwardy** [comment]
There are two uses that I can see of this:

* Bones after eating meat (you don't want to eat the whole stack)
* Slices of cake (admittedly the stack_max should be 1 here, but the eating the whole stack still applies)

**Comment by nerzhul** [comment]
I also agree that is the bug. This will be merged soon.

**Comment by nerzhul** [comment]
Commit efa977518a60c47f3c409449be202298900372e8

**Comment by MT-Modder** [comment]
Yes! Thank you.

**Pull request closed without merging**
