### PR TITLE
Remove legacy chat network code.

### PR DESCRIPTION
**Pull request by red-001**

### CODE REVIEW

**Comment by SmallJoker** [comment]
@nerzhul requested to keep the `// Obsolete` enum entries in the last cleanup PR: https://github.com/minetest/minetest/pull/6404#discussion_r137986506

**Comment by red-001** [comment]
Not sure how useful documenting that is if we are dropping compatibility.

**Comment by nerzhul** [comment]
yeah i prefer keep the current obsolete enum to remember some old behaviour, keeping them commented should do the trick :)

**Comment by red-001** [comment]
@nerzhul maybe just document it in a comment at the top of the file?

**Comment by sfan5** [comment]
Keeping them commented out or in a big comment at the top is useless.
If you want to keep them, just keep them inline with the `// Obsolete` hint.

**Comment by nerzhul** [comment]
then just remove the obsolete function, move it to deprecated handler ?

**Pull request merged**
