### PR TITLE
Change pitch fly binding, add button to change keys menu

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by NathanSalapat** [comment]
Does this just remove the default being set to L?

**Comment by paramat** [comment]
PR is updated again, it also adds the toggle to the key change menu.
Removing the keybinding means the feature is unusable until the user defines a key for it.
Some core devs consider pitch move confusing if accidentally toggles to 'on', but i can't see much of an issue so not sure if removing the keybinding is needed. The feature seems popular too.

**Comment by DS-Minetest** [comment]
This change won't affect the most players anyway in the next few months as 0.5 is already released now. I suggest waiting for input from players before changing everything.

**Comment by paramat** [comment]
I don't feel strongly enough to officially disapprove, but i prefer the keybinding is kept.
I approve of the keychange menu changes though.

**Comment by rubenwardy** [comment]
>  Some core devs consider pitch move confusing if accidentally toggles to 'on', but i can't see much of an issue so not sure if removing the keybinding is needed. The feature seems popular too.

https://forum.minetest.net/viewtopic.php?f=6&t=22299

**Comment by paramat** [comment]
Yes i saw that, it was accidental pressing of 'L' by one player. Maybe a few players have accidently pressed 'L' but the majority who don't are not reporting it, so it seems a bigger problem than it is.
Keys are accidently pressed all the time, but this is no argument to remove keybindings, anyone who knows about pitch move will realise it is enabled.

Perhaps best we make a forum news post warning of this new key.

**Comment by ClobberXD** [comment]
The Android UI also needs a new button for toggling pitch-move. Would that be possible to do in this PR itself?

**Comment by paramat** [comment]
Ugh, i think Android will have to go without pitch move until 5.1.0. After all there are still issues concerning pitch move.

For pitch move, maybe rebind it to 'G'? Less chance of being pressed when fumbling around for 'K'.
Also just noticed autoforward isn't listed as a control in the README.

**Comment by rubenwardy** [comment]
Yet another user has been confused by this binding.

It is very bad UX to put the key so close to the other key

**Comment by LoneWolfHT** [comment]
> Ugh, i think Android will have to go without pitch move until 5.1.0. After all there are still issues concerning pitch move.
> 
> For pitch move, maybe rebind it to 'G'? Less chance of being pressed when fumbling around for 'K'.

I use G to drop my items because it's too easy to accidentally hit Q while playing. I learnt this from another player and have probably spread it to at least 3 other players

**Comment by paramat** [comment]
P is good :+1:

**Comment by paramat** [comment]
> It is very bad UX to put the key so close to the other key

Yeah, like QWERTASDFZ =D

**Pull request merged**
