### PR TITLE
Camera: Code improvements, use Raycast

### PR DESCRIPTION
**Pull request by SmallJoker**
~This PR will make FOV changes smoother. Zoom in to notice the difference.~

Use Raycast to find visually colliding nodes
Use vector3d operators instead of handling X Y Z separate

This is 50% a bugfix and 50% maintenance.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Nice! Changing the FOV (#7557) on the fly will be much more pleasant now. :)

**Comment by paramat** [comment]
:-1: for smoothed zoom changes.

Zoom is primarily for use of telescopes, gunsights, binoculars. These are put up to the eyes for instant zoom change.
Changes of FOV are prone to causing visual discomfort. The discomfort is far, far worse, and sickening, when the FOV change is smoothed. I've noticed this when watching MC videos when FOV changes every time they run..

Personally i will never be able to use zoom again if this is done. If this is done please add an option, even if default on.

**Comment by SmallJoker** [comment]
@ClobberXD Actually when your camera distance is reduced due to collisions, it should be less jittery now to when moving the cursor since the exact positions are calculated. However, even if no difference is noticed it's fine as well.

**Comment by ClobberXD** [comment]
> @ClobberXD Actually when your camera distance is reduced due to collisions, it should be less jittery while moving the cursor since the exact node hitting positions are calculated. However, even if no difference is noticed it's fine as well.

Oh ok. I'm sorry I couldn't notice any difference, but at least nothing else is messed up. :)

**Comment by SmallJoker** [comment]
Oh and by the way: It looks like I accidentally fixed another issue where attachments were no longer selectable outside a radius of 200m around (0,0,0).

**Comment by GreenXenith** [comment]
Tested for entity collision/selectionbox outside of 200m. Works with both test script above and my own mod :+1:

**Comment by paramat** [comment]
`continueRaycast()` looks much more complex than the previous code, i guess due to it's generality, so i'm a little concerned about performance loss. Performance seems more important than using raycast.

Since this seems to fix a bug it seems valid for 5.0.0.

**Comment by paramat** [comment]
> Actually when your camera distance is reduced due to collisions, it should be less jittery while moving the cursor since the exact node hitting positions are calculated.

Might fix #2276

**Comment by paramat** [comment]
Sorry to write this after your good work, but i'm :-1: for using raycast, as it is far more complex than the current code, and this is being used in camera update which is run every frame, so can be 60+ FPS.

Unlike the previous code, `continueRaycast()` detects objects, so calls `getSelectedActiveObjects()` which loops through all objects, gets their selectionboxes and tests for a collision between the shootline and the selectionboxes. Very thorough but overkill for this purpose.
This is done every camera update.

https://github.com/minetest/minetest/blob/325bf680410e8012394e5f3ba5ba947c69034899/src/environment.cpp#L97
https://github.com/minetest/minetest/blob/9e36a880feec9fa478b63c6d6cc5bfb707ddd29c/src/client/clientenvironment.cpp#L454

Although it is thorough to account for objects it just isn't needed, we have no issues with simply testing for 'walkable' and the third person camera being inside objects isn't a problem. The only issue about third person camera behaviour seems to be #2276 
I think the performance gain of simple code far outweighs the questionable or very minor benefits.
The current code just tests for walkable and ignores objects.

The other part of this PR seems good though.

**Comment by GreenXenith** [comment]
> The other part of this PR seems good though.

Does this part include the entity attachment box fixes?

**Comment by paramat** [comment]
Good point, we need to find out what actually fixes that, perhaps it is the changes to the camera offset code?

**Comment by paramat** [comment]
> another issue where attachments were no longer selectable outside a radius of 200m around (0,0,0).

Please can someone open an issue for this? I can't find one.

**Comment by paramat** [comment]
Alternative PR #8033 is the camera offset changes only, to discover if those changes are the fix for the attachment bug.

**Comment by paramat** [comment]
I have confirmed the bug.

**Comment by GreenXenith** [comment]
@paramat you just closed #8033 because it wasn't actually working... but the collision boxes did in fact work, which shouldn't be a camera thing?
aka I am confused now. Does this PR fix the bug or not?

**Comment by paramat** [comment]
benrob0329 yes, for after 5.0.0.

**Pull request closed without merging**
