### PR TITLE
Dont make fastface if tile is not seamless

### PR DESCRIPTION
**Pull request by RealBadAngel**
mapblock mesh: Fix for issue #3378

### CODE REVIEW

**Comment by BlockMen** [comment]
Please make two seperate commits, one for the actual fix and one for the codestyle cleanup. See: http://dev.minetest.net/Git_Guidelines

**Comment by RealBadAngel** [comment]
@BlockMen i wont bother making cleanup again, it was just by the way...

**Comment by paramat** [comment]
:+1:

**Comment by nerzhul** [comment]
:+1:

**Pull request closed without merging**
