### PR TITLE
Connecting nodes: 2 small bugfixes.

### PR DESCRIPTION
**Pull request by sofar**
I spotted 2 minor but frustrating bugs with the connected nodes. The first cased nodes to connect to unwanted nodes. The other bug is pretty rare and would cause wrong connections for connections that shouldn't have connected back.

### CODE REVIEW

**Comment by sofar** [comment]
@paramat @ShadowNinja @est31 this probably should go into 0.4.14 - please review.

**Comment by est31** [comment]
:+1:

Probably should be squashed, its only two one liners, its easy enough to tell the difference between the two changes if the commit messages of both changes are retained.

**Comment by paramat** [comment]
:+1:

**Comment by sofar** [comment]
Squashed to a single commit. Thanks.

**Comment by est31** [comment]
Merged as 5a40a7dad8cbf46320c3b5dd1122808eb4919b62

**Pull request closed without merging**
