### PR TITLE
mg_schematic: fix leak-like behaviour, and small cleanup

### PR DESCRIPTION
**Pull request by est31**
See #3566.

### CODE REVIEW

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
Testing with roomgen memory use rose quickly to 3 GB but then stabilised, perhaps this is the heavy mesh data not a leak.

**Comment by kwolekr** [comment]
:+1:

**Comment by nerzhul** [comment]
:+1:

**Comment by est31** [comment]
0aac1b74037ba0f6b0526e81ad0ea7367e31c224

**Pull request closed without merging**
