### PR TITLE
Document how to make nametags background disappear on players' head

### LINKED ISSUE #10778: Nametag cannot be hidden for players
Caused by #10152

A nil or "" nametag on a player will display the player's name rather than a blank. This has always been the case.
The workaround to hide the player's nametag was to make it whitespace, but the recently added dim background has made the space visible:
hidenametag

We need a reliable way to hide nametags for all entities, including players. Can't be too sneaky with that thing above your head.

### PR DESCRIPTION
**Pull request by Zughy**
Closes #10778

I'm not a native speaker, but I've tried

## To do

This PR is Ready for Review.

## How to test

Read.

### CODE REVIEW

**Review by hecktest — CHANGES_REQUESTED** [review]
Consider:
```
-- If the object is a player, a nil or empty nametag is replaced by the player's name.
-- For all other objects, a nil or empty string removes the nametag.
-- To hide a nametag, set its color alpha to zero. That will disable it entirely.
```

**Comment by Zughy** [comment]
More concise, thanks. I also put a definition, as it was missing

**Review by SmallJoker — APPROVED** [review]
LGTM

**Review by rubenwardy — APPROVED** [review]

**Comment by LoneWolfHT** [comment]
Looking at this it's not obvious how to remove the background

**Pull request merged**
