### PR TITLE
Update Indonesian Language

### PR DESCRIPTION
**Pull request by srifqi**
As the title said

### CODE REVIEW

**Comment by nerzhul** [comment]
Hi, can you squash your commits please ?

**Comment by srifqi** [comment]
Excuse me, what do you mean "squash your commit"? I don't get it.

**Comment by nerzhul** [comment]
squash = merge your commits. 
Step 1: type git rebase -i HEAD~2
Step 2: change the last commit action in the editor to s
Step 3: merge the commit comments
Step 4: push with force to your PR branch

**Comment by srifqi** [comment]
Pardon me? What do you mean "HEAD~2"?

**Comment by srifqi** [comment]
Have I done right?

**Comment by nerzhul** [comment]
No :)

**Comment by srifqi** [comment]
Thanks @SmallJoker 
You win again :D

So, will this be merged?

**Comment by nerzhul** [comment]
Okay for me

**Comment by nerzhul** [comment]
jenkins rebuild please

**Comment by nerzhul** [comment]
jenkins build please

**Comment by nerzhul** [comment]
Thanks 7c19933a8cca173157e0c21923cafe56b2334708

**Comment by srifqi** [comment]
Okay, thanks for merge

**Pull request closed without merging**
