### PR TITLE
Remove minetestmapper from this repository

### PR DESCRIPTION
**Pull request by nerzhul**
It's now located at https://github.com/minetest/minetestmapper

### CODE REVIEW

**Comment by anton-tsyganenko** [comment]
you can also remove colors.txt

**Comment by SmallJoker** [comment]
This mapper script is deprecated but should be kept as an alternative to the C++ rewrite. We also have PR #3829 to improve the functionality.

**Comment by paramat** [comment]
This is the python mapper which is different from the C++ one, maybe it should be preserved somewhere?

**Comment by nerzhul** [comment]
maybe discuss about this on next meeting ?

**Comment by paramat** [comment]
But i agree it should be removed from the MT repo, just preserved somewhere.

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
+1 if colors.txt (and sectors2sqlite.py?) is/are removed too.

**Comment by ShadowNinja** [comment]
`colors.txt` needs to be removed.  Also, maybe remove `sectors2sqlite.py` too since nobody uses sectors anymore (does Minetest even support the block format that the script outputs?).

**Comment by rubenwardy** [comment]
I suggest that this is moved to a minetestmapper-python repo

**Comment by nerzhul** [comment]
Updated.

@rubenwardy if moved, add it to current minetestmapper in oldies ?

**Comment by expertmm** [comment]
preserved here since noone else is interested: <https://github.com/expertmm/minetestmapper-python>

**Pull request merged**
