### PR TITLE
Devtest: Add oddly sized checkerboard test nodes

### PR DESCRIPTION
**Pull request by erlehmann**
## Description

The code in the patch generates 25 checkerboard textures in different sizes and registers nodes for them in devtest.
The new nodes can be used to debug rendering issues related to non-16×16 textures sizes and/or texture scaling.

### Goal of the PR

Add nodes to help with debugging rendering and scaling issues.

### How does the PR work?

The code in this patch generates a bunch of checkerboard textures and adds nodes to display them.
The bottom left square is gray, so that separate nodes placed next to each other are easier to identify.

### Does it resolve any reported issue?

No, but it might lead to new reported issues.

**Edit:** To be clear, devtest is lacking nodes to test the handling of textures in non-16×16 sizes currently.

**Edit 2:** I have already found issues, but I want to wait filing them until this PR is merged, so they can be debugged better.

### Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?

[2.1 Rendering/Graphics improvements](https://github.com/minetest/minetest/blob/master/doc/direction.md#21-renderinggraphics-improvements).

### If not a bug fix, why is this PR needed? What usecases does it solve?

Having devtest nodes to check if texture scaling works okay is a prerequisite for finding and fixing bugs related to texture scaling and for checking if or how well a fix for these bugs actually works. Also having these texture sizes in devtest ensures that there is a quick check to see if oddly sized textures (I have seen 5×5 and 7×7 in the wild) would be negatively affected by changes relating to scaling.

## How to test

1. Start devtest.
2. Open the bag with everything (or how it is called).
3. Type “Checkerboard” in the search field and press the return key.
4. Look at the nodes. Is the inventory rendering okay? How do they look in the world? Anything weird?

## Screenshots

**Look at these screenshots in 100% scale, i.e. open the image separately to avoid browser downscaling affecting them.**

Nodes with the same tiling (e.g. 2×2) are supposed to look alike:

minetest-game-devtest-testnodes-checkerboard-remastered

Aisotropic filtering blurs some nodes stronger than others (@Desour this is a bug, right?):

minetest-game-devtest-testnodes-checkerboard-remastered-anisotropic-filtering

Anisotropic filtering does not affect node rendering in inventory:

minetest-game-devtest-testnodes-checkerboard-remastered-anisotropic-filtering-inventory

One mipmap (top row, third from the left) has the wrong brightness (due to Minetest's gamma-incorrect scaling maybe?):

minetest-game-devtest-testnodes-checkerboard-remastered-mipmap

**Edit:** Note that the mipmapping rendering issue in the screenshot also affects how the node is rendered in the inventory.

**Edit 2:** @celeron55 last night made the gamma fix from this comment https://github.com/minetest/minetest/issues/6917#issuecomment-359444125 work with recent irrlichtmt and told me about it on IRC in `#minetest`:

```
<celeron55> erle: https://github.com/celeron55/minetest/tree/hybriddogs_mipmap_custom
<celeron55> i patched it to work with latest master
<celeron55> it sharpens up distant mipmapped textures without making them noisy like disabling mipmaps does
<celeron55> it's weird that it can do that
<celeron55> the effect is subtle though. with a low dpi screen you probably notice it more
<celeron55> not sure
[…]
<celeron55> erle: you should make more comparison screenshots
```

With the mipmap scaling improvements by @HybridDog the node that is rendered too dark in the screenshot above seems to have the correct brightness both in the world an in inventory (compare the screenshots at 100% size to see the difference):

minetest-game-devtest-testnodes-checkerboard-remastered-mipmap-hybriddog

### CODE REVIEW

**Comment by Desour** [comment]
>Aisotropic filtering blurs some nodes stronger than others (@Desour this is a bug, right?):

The checkerboard textures in your screenshots are not sampled anisotropic (~ from the side).
The blurriness doesn't come from the anisotropic filtering, but from bilinear magnification, because on some platforms that seems to not be configurable independently.
Anyway, the different blurriness is to be expected, if the checkerboard textures have a different resolution, obviously.

I really don't want to discuss different existing issues in a PR that adds things.

**Comment by erlehmann** [comment]
> I really don't want to discuss different existing issues in a PR that adds things.

Understood, I just wanted a confirmation that it is not the *nodes* that were wrong.

**Comment by lhofhansl** [comment]
As for this PR, additional test nodes are good. Code looks reasonable.
I do faintly remember some discussion about TGA (deprecated then undeprecated or something). If that's not an issue then +1.

**Comment by erlehmann** [comment]
@lhofhansl I do not think this is an issue anymore. So is this a “supported by core dev” then?

**Comment by Zughy** [comment]
Author has been banned for a year, closing

**Pull request closed without merging**
