### PR TITLE
[2] Code cleanup in serverpackethandler

### PR DESCRIPTION
**Pull request by HybridDog**
* remove redundant vector int to float to int conversion
* send blocks (e.g. to undo placement prediction) only when pointing nodes, i.e. when pointed.node_undersurface is valid
* some style changes, e.g. reduced indentation, redundant comment removals, switch-case instead of long elseif chain

https://github.com/minetest/minetest/pull/9349/files?w=1

Previous PR: #8815

### CODE REVIEW

**Comment by nerzhul** [comment]
Hello,
can you extract the first two changes to another PR please. It's not easy to review with functional & fixes changes. Thanks

**Comment by HybridDog** [comment]
> Hello,
> can you extract the first two changes to another PR please.

I have created a PR for the getPeerId calls: #9689

**Comment by HybridDog** [comment]
rebased

**Comment by pyrollo** [comment]
Tested for dig, place, use actions. Works good.
Not tested anticheat features. I don't know if we have simple way to test them.

**Review by SmallJoker — APPROVED** [review]
Easier to review using the "Ignore whitespace changes" option.

Anticheat still works.
:ballot_box_with_check: 'interact' priv check
:ballot_box_with_check: Far object interactions
:ballot_box_with_check: Far node interactions
:ballot_box_with_check: Digging too fast

**Comment by HybridDog** [comment]
Thanks for the testing.

**Review by nerzhul — APPROVED** [review]
fine to me too, thanks

**Pull request merged**
