### PR TITLE
Add unittests to test player saving/loading

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by nerzhul** [comment]
@est31 @kwolekr @sfan5 @sofar @est31 @Zeno- review ? :)

**Comment by Zeno-** [comment]
unit tests... just merge ;)

**Comment by kwolekr** [comment]
I'm not sure this really tests anything aside from serialization... was hoping for something that does more...

**Comment by nerzhul** [comment]
In fact it's the only change we need for the refactor of SAO because i move attributes referenced into this test.
If you want more for other purposes, code it please. This test is to test the refactor.

**Comment by nerzhul** [comment]
Then merging

**Comment by kwolekr** [comment]
wtf...

**Pull request merged**
