### PR TITLE
Add main menu music score - "Mercury Rain" by Skaven/FC

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by RealBadAngel** [comment]
From the the legendary composer of the PC demoscene, with his approval.

**Comment by est31** [comment]
Which license should the music be released? It should perhaps be added to [this section](https://github.com/minetest/minetest/blob/master/README.txt#L373) of the readme, and the license should be explained in the README file too, e.g. [here](https://github.com/minetest/minetest/blob/master/README.txt#L364) (right now its only about textures and sounds, not about music).

**Comment by celeron55** [comment]
This cannot be added to the minetest repo purely by the technical reason of bloating up the repo by 1.5 megabytes forever even after it is removed from the engine, which is bound to happen at some point independently of whether it is initially used or not.

**Comment by RealBadAngel** [comment]
A game having music score is not bloating the repo. Its just a needed media file. This is not to be discussed.

**Comment by celeron55** [comment]
We need a way of providing media files without storing them indefinitely in git history. There are ways of doing it though; I'm open to doing such a set-up.

**Comment by RealBadAngel** [comment]
do you pay for github storage or what? it makes no sense of splitting the project

**Comment by celeron55** [comment]
Do you understand that git always downloads the full history whenever someone pulls the repo on their own computer? There is no way to make any historical files not be downloaded unless you don't download the history, which is not a real option when developing.

**Comment by RealBadAngel** [comment]
i do undertand. its 21st century. even on my phone i do have 75gbs limit ....

**Comment by RealBadAngel** [comment]
following your way we should keep also the textures elsewhere. not to mention all other sound files

**Comment by RealBadAngel** [comment]
core files have to be kept in this repo. its not limited to text(source) files only. it never was. we already are keeping there texures for example.

**Comment by celeron55** [comment]
I have hundreds of git projects on my computer, and if each one of them added one 1.5 megabyte file every month, I would be constantly drained from 3.6GB of free space every year. That would absolutely suck.

Yes, we should keep also the textures elsewhere, not to mention all other sound files. And also the bitmap fonts.

git-annex would probably be the best way of doing this: http://stackoverflow.com/a/6635160

It adds some steps into the workflow involving media files, but it would allow us to cycle all kinds of bloated media in and out from the engine without any concerns. What do others think?

**Comment by RealBadAngel** [comment]
Each game can add its own music score and override the engine's ones.
About the quality of the chosen score - this tune is a legend in PC demoscene and the creator of it is far more than just competent. You should be proud that he allowed to use his scores for our project not just happily reject it.
Google for what he have done for commercial games....

**Comment by celeron55** [comment]
I didn't say the creator of that track is not competent. I said the track is not suited to Minetest. It sets a wrong mood as far as I am concerned.

**Comment by RealBadAngel** [comment]
Your problem is that you dont see a need for music at all. Style of the music for you is a secondary problem. What im trying to do is to make game feel more complete. Without a music nowadays production is a damn joke.

**Comment by RealBadAngel** [comment]
and you wont get better music tiltle for this. not the one which could be called "a legend" already

**Comment by celeron55** [comment]
No. My problem is that music has to have a purpose other than just being music. To just get some music, people can just press "play" on their usual music player. Choosing a track to play is not the job of a game engine.

Minetest should have music that amplifies the mood of whatever is going on in Minetest.

**Comment by RealBadAngel** [comment]
We are not talking now about the music in the game. This is about main menu, dont mess up things.

**Comment by celeron55** [comment]
I request that if any other core developer than RBA wants music to be provided by the engine, they should comment here and state so.

**Comment by celeron55** [comment]
So my vote goes as follows:
1) If the music is added in a way that will not pollute the repo indefinitely, I am totally fine adding this and seeing how players react
2) If the music is added in a way that will pollute the repo indefinitely, the music selection will have to be made with a community-wide vote that includes a "no music" option, and to which anyone can submit a track prior to the vote.

**Comment by asl97** [comment]
@RealBadAngel 
:-1: too techno-ish for the default main menu music, as @celeron55 said, this is not suited to Minetest, at least not default minetest_game. nothing in the default is anything remotely techno-ish.

the default main menu music should be something that reflect minetest or the default minetest_game.
maybe something slow, soft and natural, something that `ease in` would be nice too.

**Comment by RealBadAngel** [comment]
minetest doesnt have my personal approval to use this tune.
i get this from Skaven and i will use it in my own fork.
It is strictly forbidden for anybody else to use it. HOWGH.

**Comment by PilzAdam** [comment]
@RealBadAngel lol.

For the record: I am against music in the engine. This should be provided by games, like the menu textures currently.

**Comment by paramat** [comment]
I agree with celeron55's artistic opinions on music in MInetest.
It's a subgame thing, and perhaps best in-game than in a menu since so little time is spent there. However MTGame is so neutral and universal it would be very difficult to choose music for it, whatever is chosen most would not like it, and music file sizes are huge, so i would prefer none.
I'm usually listening to my own choice of music when using Minetest, as most players would prefer to do, the lack of music is refreshing.

**Comment by jordan4ibanez** [comment]
This was closed? Pathetic. It's very empty without any music.

**Comment by C1ffisme** [comment]
I would be interested in seeing music in the game, especially since a good soundtrack can attract an audience. (And we can put soundtracks on Spotify or other music services so that it can be seen.)

It might be good to see if anyone in the community has any skill with composing music similar to C418's music for Minecraft. The music fits a game who's main theme is "blocky, without a set time period or canon".

Because of the file size, it might be a reasonable idea to have the music files stored in another repository, and require a manual downloaded by people who clone Minetest or get a dev build. The people that get a stable version of Minetest can have the music included.

**Comment by jastevenson303** [comment]
Sounds good, now do you know someone who could do this?  How about a forum
post?

**Comment by C1ffisme** [comment]
> How about a forum post?

A forum post would be good, or if that turns up no results, there are open-source musicians that have made good soundtracks for other games like Supertux, Supertuxkart, Frozen Bubble and the most likely dead Pingus.

(There's probably a pattern in there somewhere. Maybe we need to change our mascot into a penguin?)

**Comment by Fixer-007** [comment]
List of mods sorted by license: https://modarchive.org/index.php?request=view_by_license&query=publicdomain (you can select the one you need)

**Pull request closed without merging**
