### PR TITLE
[WIP] Rewrite filesystem helpers

### PR DESCRIPTION
**Pull request by ShadowNinja**
- Rewrite filesystem API to be like C++17 filesystem API.
- Switch to Windows "unicode" API (it's actually not true
  unicode, because it's limited to the 16-bit set, but it's
  better than 8 bits).  Note: this still doesn't add full
  Windows unicode support, we'll have to wrap all `fopen`
  calls (`fs::open`) and drop or replace `fstream` for that.
  Windows really sucks at unicode apparently.
  Should be a partial fix for #3588.
- Enable Windows long path support for filesystem helpers.
  (have to use unicode API and prefix '\\\\?\\' to paths)
- Change `.~mt` to `.mt~` (non-standard, broke `*~` ignore patterns).
- Rewrite safe write API to expose an `ostream` and support Windows unicode (`ostringstream::str` does a copy, and requires keeping the whole file in RAM).
- Move `filesys.*` to `util/` and renamed to `filesystem.*`.
- Make Doxygen API comments.
- Fix `minetest.conf` being saved twice on exit.
- `RecursiveDelete`: This used to be a no-op on Windows that just spun away the CPU scanning directories, and it was a huge hack on POSIX (it fork()ed and exev()ed `rm -rf`).  Because of this, `GetRecursiveSubPaths` and `DeletePaths` were used together to impliment `RecursiveDelete`.  I fixed RecursiveDelete and removed the other two (now unused) functions.
- Much more to be listed here later when I go through it all...

Testing:
- Compiles and runs on Linux.
- Compiles for Windows with MinGW.
- I at least remembered to update the build file for Android.

### CODE REVIEW

**Comment by PilzAdam** [comment]
This is barely reviewable. Can you split it up into separate commits?

**Comment by ShadowNinja** [comment]
@PilzAdam: Perhaps, but it would take quite a while since some of these changes are interdependant.

**Comment by paramat** [comment]
Not for 0.4.16, big risky refactor thing needing rebase and maybe splitting up.

**Comment by rubenwardy** [comment]
This is really way too big a change for a single commit. I suggest making commits as you go along for each bullet point, so we can review on a one-by-one basis

**Comment by paramat** [comment]
@ShadowNinja please split off what you can into separate PRs, and use multiple commits for what remains, 3000 line changes in 1 commit is unnacceptable and it will not get reviewed in this state.
PR is old, please work on it ir close it.

**Comment by paramat** [comment]
@ShadowNinja closing in 1 week.

**Comment by paramat** [comment]
Anyone interested in adopting this? If so is any of this useful seeing how old it is and the conflicts?
Closing in 1 month unless there is a reason not to.

**Comment by paramat** [comment]
Closing http://irc.minetest.net/minetest-dev/2017-10-01#i_5094868
Author has stated they have no time for MT. Adoption may still happen but with these conflicts this PR itself is unlikely to go anywhere.

**Comment by paramat** [comment]
ShadowNinja messaged me with this:

> Here's a project that I've built from the ground up that is roughly what I'd like the filesystem helpers to be. It's loosly modeled after std::filesystem, which we'll probably want to switch to once C++17 is widely deployed. https://github.com/ShadowNinja/CPFS

**Comment by paramat** [comment]
18:18 paramat      ShadowNinja i'll link to that from your closed PR
18:19 paramat      ShadowNinja does this mean you don't recommend #3653 is adopted, finished and merged? that the implementation should be different?
18:19 ShadowBot    https://github.com/minetest/minetest/issues/3653 -- [WIP] Rewrite filesystem helpers by ShadowNinja
18:22 ShadowNinja  paramat: That PR is still useful, but it was very WIP, so the final version will have to be rather different.
18:22 paramat      ok
18:23 ShadowNinja  Some things like the .mt~ thing could be easily merged seperately.
18:23 ShadowNinja  Also, RecursiveDelete is totaly fubar right now.

**Pull request closed without merging**
