### PR TITLE
Move fill_defaults to outside of core.register_privilege

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by ShadowNinja** [comment]
1. Why?
  2. Contains unrelated change.

**Comment by Rui914** [comment]
>>Why?
I think this doesn't have to be inside the core.register_privilege.
Or it is no need to define a function.

>>Contains unrelated change.
I wrote it wrong.
I'll fix it.

**Comment by kwolekr** [comment]
I have no idea what fill_defaults() is supposed to actually do, but it looks like it should not be a function at all.

**Comment by ShadowNinja** [comment]
kwolekr has a point.  I think it should just be expanded inline with some newlines to seperate it and a `-- Set default fields` comment.

**Pull request closed without merging**
