### PR TITLE
Remove new style water

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by paramat** [comment]
Don't bother with menu stuff yet as #3740 has to go in first.

**Comment by Calinou** [comment]
:+1:, it breaks smooth lighting (which does not affect new style water, but does affect waving water) and is not that needed with the waving water we have now.

**Comment by BlockMen** [comment]
We already have a discussion for this, a seconds location for that is not needed. Closing until a decission is made.
Discussion: https://github.com/minetest/minetest/issues/3734

**Comment by paramat** [comment]
That's an issue, this is the PR.

**Comment by kaeza** [comment]
:-1: I like NSW. And yes, I (intentionally) don't use smooth lighting, so I don't have the visual inconsistency.

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
A build failed in unit tests:

======== Testing module TestThreading
Test assertion failed: thread_retval == thread
    at test_threading.cpp:107
[FAIL] testStartStopWait - 86ms
[PASS] testThreadKill - 405ms
[PASS] testAtomicSemaphoreThread - 11ms
======== Module TestThreading failed (1 failures / 3 tests) - 503ms

**Comment by paramat** [comment]
8eb7ddb0a2f03ae514a96191f6edba9333ba2423

**Pull request closed without merging**
