### PR TITLE
[WIP] text to speech / tts

### PR DESCRIPTION
**Pull request by nOOb3167**
### Only having a Lua API versus bringing text-to-speech through engine features

Considered adding engine built-in functionality to speak out chat messages.
Decided against, having considered existing practice for chat message use.

For example: CTF server uses chat messages to broadcast:
- hints: "To talk to only your team, start your messages with /t."
- informational messages: "Map: Two Hills and Two Lakes by rubenwardy"
- status messages: "*** NICKNAME has joined the game"

The engine cannot guess which messages are meant to be spoken out.
A mod API was thus implemented.

### Type of API (CSM / non-CSM)

This type of API will gain utility once CSM mod sending (#7056) is available.

Adding a non-CSM API is possible.
The implementation would presumably use a network protocol for requesting text-to-speech (something alike clientpackethandler.cpp Client::handleCommand_PlaySound for client side, and matching plumbing for the server side).

CSM mod sending and mod communication channels (#6351) should be able to _simulate_ the above with fidelity. Thus only having a CSM API should suffice.

### Design of API

The way I see it from an API perspective, two separate use cases can be defined:

- A general purpose "speak out this message" case.
- A configurable case.

The general purpose case should accept just a text string. Text should be placed onto a queue, then spoken. A default text to speech transformation could be set by the engine, and/or be configurable by the user. (User interface could look something like this: https://eeejay.github.io/espeak/emscripten/espeak.html)

The configurable case should allow settings to be passed.

### Actually implemented parts

As this PR can still be made functionally complete while implementing just the general purpose case, it omits implementing the configurable case. No configurability is available at the moment.
minetest.text_to_speech(message) is defined for use by CSM.

### Text-to-speech library choice

Several text-to-speech engines appear to be available for Open Source use (Festival, FreeTTS, flite...).
Most seem outdated and/or unmaintained.
I've chosen espeak: https://github.com/espeak-ng/espeak-ng .
Their github is active, wikipedia indicates Android support is available (https://en.wikipedia.org/wiki/Comparison_of_speech_synthesizers#Text-to-Speech_Engines_on_Android).

### Attached zip containing video demonstration and example CSM mod

[espeakng2.zip](https://github.com/minetest/minetest/files/1759864/espeakng2.zip)

### Prior work

This PR depends on Global initialization of sound using SoundManagerGlobal (#7063).

### CODE REVIEW

**Comment by paramat** [comment]
I think the feature is too specialist and not useful enough to be worth adding, sorry.

**Comment by paramat** [comment]
My thoughts are (with my apologies):
* Listening to speech is much slower than reading a message, and i expect it will often not be able to keep up with in-game chat.
* Speech synthesis often has odd enunciation so is not particularly clear.
* Typos happen often in chat, visually a typo is quickly understood whereas a speech synth will make a weird noise.
* Speech will often coincide with in-game sounds or real life sounds.
* Being able to verbally talk to other players on an audio channel is an excellent multiplayer feature, i feel that players would prefer to use that.
* Implementing this is somewhat complex and involving a new library needs a very good reason.

**Comment by nOOb3167** [comment]
> - Being able to verbally talk to other players on an audio channel is an excellent multiplayer feature, i feel that players would prefer to use that.

This is in fact being worked on - but further away from a submittable state.

**Comment by Fixer-007** [comment]
I know Minecraft 1.12 has this, I wonder what are possible uses?

**Comment by paramat** [comment]
@nOOb3167 still WIP?

**Comment by ClobberXD** [comment]
Also needs rebasing to resolve merge conflicts

**Comment by paramat** [comment]
> This type of API will gain utility once CSM mod sending (#7056) is available.

Best wait, as the future of CSM and server-sent CSM is uncertain at the moment.
However, i think this PR should be disapproved anyway due to the many issues and lack of usefulness.

**Pull request closed without merging**
