### PR TITLE
Add server API abstraction layer

### PR DESCRIPTION
**Pull request by nerzhul**
This permit anybody to implement callback abstraction layer for any
language he wants.

The overhead of this if very very minimal on each api call, regarding the heaviness of the lua code which runs after calling this abstract layer.

The layer is intended to be run on server part only. Client has no sense to have other extension language than Lua as other are generally not so portable. It's intended to permit anyone with c++ skills to implement his own layer (JS, Python, Ruby, C++, PHP) layer behind minetest API to perform his calls

It implements stub libminetestapi.so permitting anyone to implement bindings on the api modules.

If we say we are an engine, engines are extensible, and yeah this usecase is one of the powerful possibilities to make an engine better :)

## To do

This PR is a Work in Progress

- [x] Review the code done by myself on github to ensure no callbacks are inverted
- [ ] Discuss about original function naming (rename some to have consistency across modules
- [x] Split module on the router permitting to have specialized modules only

## How to test

build & test, it just works

### CODE REVIEW

**Comment by appgurueu** [comment]
Looks very good! Could you add some elaborate Markdown documentation?

**Comment by nerzhul** [comment]
@appgurueu on which part ? how to implement your backend ?
i think i will add a "stub" backend in c++ directly in code to show you how to add one (and which can permit us to offload builtin to c++ directly to improve perfs when we want)

**Comment by nerzhul** [comment]
I splited that in modules, permitting to create tiny specialized module API instead of a big one , you can do like Lua implementation use inheritance to have the full one if you need

**Comment by nerzhul** [comment]
There is now a stub library support for whoever wants to add api bindings on the abstraction layer

**Comment by sfan5** [comment]
:-1:

There are several reasons why I fundamentally think these changes are not good:
* The feature is extremely niche, which is also because of its limitations.
Server owners that want to make use of this need to write their own C++ code, recompile the engine and their C++ "mods" if either of them changes and such mods will not be portable across engine versions.
I would not expect more than one server from the public list to actually use this feature and no modders to ever publish C++ code to be used.
* Unsolved (or unsolvable) conflicts: a simple example is `formatChatMessage`, a chat message can be formatted just once, you can either let Lua do it or let the external code do it, not both.
There are many cases like this, a luaentity can exist either in Lua or in external code. What does `get_luaentity()` return on an entity implemented externally?
But there are more questions: How does Lua see nodes registered externally? If external code provides auth handling, how does `minetest.get_auth_handler()` work from Lua? Can external code call custom or ordinary Lua node callbacks (`spawn_falling_node` / `node.on_blast`)? When coordination is required (e.g. `forceload_block`'s refcounting), how do those features work? If new nodes are registered externally, does Lua see them and can it call `preserve_metadata`, `can_dig`, ...?
* Overhead: Instead of directly calling the right method, any scripting call will go through the router which iterates a `std::vector` and unboxes an `std::shared_ptr`. I have not benchmarked this and I don't think it's <i>slow</i> either, but when you consider that 99% of people do not use this feature it is definitely unnecessary.
* Maintainability: In future development, every new scripting call would have to be added/changed in both the router and the actual Lua implementation.

I would also like to point to the discussion in https://github.com/minetest/minetest/issues/4064#issuecomment-621717624 where you were warned that a feature you work on "for your own needs" may not be generally fit for the engine.

**Comment by nerzhul** [comment]
thanks for your return,
the first point is not valid to me. If there is a such feature the server owner is aware and know what he does. On discord at least 2 server owners are interested. About the consumption in some callbacks, it should just be documented, as the callback handle it properly. About the code optimization for only a single element it can be interesting to see what compiler do, as here we have just one element in a vector for the whole process lifetime.

For the second point, as it's an advanced feature the implementer should be aware of that, as the lua stack is another standalone API. As i said this permit advanced features for advanced server owners, and i already know at least 3 (including me) interested and 2 old servers which impemented things in C++ which can convert to this code to make their fork more maintainable.

For the last point it's non suitable for me too. Adding 5 lines of code more in the router which are pretty simple is fairly easy, compared to the lua implement we will add.

The only valid point here is the overhead analysis, the other parts permit to have clearer API abstraction, which can help in terms of architecture too. And it permits alternatives, it's why an engine wants, permit alternatives, not only in Lua, for everybody. If it's not accepted, we just admit we are not an engine for me and we are a game in lua and nothing more :) (i know we already said we are an engine, but sorry we are not, we were never an engine, we have many games features in core, hello hp and breath which are not engine feature but game features :) )

**Comment by paramat** [comment]
A few others are interested in this so i do not consider it something for nerzhul's needs only, even if it was (unfortunately) stated that way. So i think this should be judged on the usefulness for general users.

It seems an interesting feature, but only of use to a very few people, Lua is fine for the vast majority of users.
The downsides are the extra complexity, extra maintenance, more bugs (all these when MT has increasingly limited core dev time and needs to prioritise effort) and a little performance loss, when Lua performance is critically important.
So overall i am not convinced it is justified. I think this is best confined to a fork of MT.
> If we say we are an engine, engines are extensible

> This PR permits alternatives, it's why an engine wants, permit alternatives, not only in Lua, for everybody. If it's not accepted, we just admit we are not an engine

This is a silly attempt to promote this feature by incorrectly portraying this as essential for MT being a game engine.
Being a game engine is not defined by 'having a scripting abstraction layer that allows modification to allow non-Lua scripting languages'.
The 'this is a game engine' argument can been used to try to justify anything.
> i know we already said we are an engine, but sorry we are not, we were never an engine, we have many games features in core, hello hp and breath which are not engine feature but game features :),  and they are not the only one. We have a client with rendering and shaders, then yes, we are a game.

It is not black-and-white like this, and is dependent on word interpretations and personal ideas of what a game engine is. I agree that MT is a much less pure 'game engine' than some others, but it is still more of a game engine than a game. It is obviously not a game, it does not function at all without a game added.
I would support moving HP and breath out of the engine if possible, i think others do too.

**Comment by nerzhul** [comment]
@paramat i like your comment, and what i think is maybe we need to have a minetest-staging, like wine-staging, which include non already ported patched to the minetest, permitting to have some more liberties about innovations some of us want to include in core, with maybe another team of devs, including some known contributors, trying to backport as many commits as possible to the core engine itself.
This is a good idea for server side innovation i think, and maybe client, with maybe 2 channels like wine does, for some who wants to test the staging part.

**Comment by paramat** [comment]
From core dev comments here and in the issue, seems disapproved.

**Comment by nerzhul** [comment]
this PR is not finished yet and may be discussed more. I don't see the 1 year lifetime passed.

**Comment by paramat** [comment]
sfan5 and i are :-1: , rubenwardy is somewhat opposed in the issue but not enough to officially disapprove.
This being unfinished does not seem relevant because the basic concept itself has been rejected. What changes are you planning that could change our minds? I cannot see how you can keep the basic concept.
PRs can be disapproved and closed before 1 year passes, there has never been a '1 year PR lifetime' rule, written or unwritten.

**Comment by FriendlyGamer** [comment]
> The downsides are the extra complexity, extra maintenance, more bugs (all these when MT has increasingly limited core dev time and needs to prioritise effort) and a little performance loss, when Lua performance is critically important.
> So overall i am not convinced it is justified. I think this is best confined to a fork of MT.

I agree, if what been stated (_only three_ owners) wants it why deal with these _disproportional_ overheads? That's not even a _10%_ of the servers' population.  

To me this is more than likely as a result to _hurt the engine overall_ than to actually help it by _considerably_ draining resources that are already _at all time low_.

**Comment by appgurueu** [comment]
I support this PR. It would be nice to use allow the usage of non-Lua scripting languages or different Lua versions, which requires such an abstraction layer.

**Comment by rubenwardy** [comment]
I think the way to do this would be to provide other benefits in terms of architecture. Currently, this just complicates the existing architecture by adding a router and interfaces. I think that the scripting interface is used in two many classes, and it would be good to think about reducing its scope / use / idk

**Pull request closed without merging**
