### PR TITLE
Fix misuse of AsyncTask

### PR DESCRIPTION
**Pull request by pangeneral**
I fix the problem of StrongReference and NotCancel.

### CODE REVIEW

**Comment by SmallJoker** [comment]
@MoNTE48 Does this look alright?

**Comment by MoNTE48** [comment]
Yes. I planned to relicense the MultiCraft code (LGPL3 => LGPL2) and do PR with all the changes to the Android part.
I can say that build/android will be completely new. But it can be controversial and it will be later, so now this PR looks good.

**Comment by paramat** [comment]
Is there a related issue? Is this essential for 5.1.0?

**Comment by ClobberXD** [comment]
@paramat #8787 is the corresponding bug report.

**Pull request merged**
