### PR TITLE
Fix flowing liquid waving into the floor

### PR DESCRIPTION
**Pull request by Desour**
In master, waving liquid can wave into the floor, and seems to appear. This is ugly, and bad gameplay-wise, because you can't see that there's liquid.

Weirdly, I haven't found an issue for this. (#8367 talks about it, and has screenshots, but is not about this issue.)

This PR scales the the wave y offset by the vertex height relative to the lower node border.

It's very simple, so is there a reason why we're not doing this already? Am I overlooking something.

Note: Liquids can still wave into the ground, just not the top faces. (=> Fixes not #14535.)

## To do

This PR is a Ready for Review.

## How to test

master:
master
pr:
pr
master, waveheight=2:
master_waveheight2
pr, waveheight=2:
pr_waveheight2

### CODE REVIEW

**Comment by superfloh247** [comment]
works "on top of blocks" but not below blocks.
and water "shines through" blocks

screenshot_20241104_164806

**Comment by superfloh247** [comment]
is it intentional that water now has "steps"?

screenshot_20241104_165452

**Comment by superfloh247** [comment]
BTW, screenshots from public world wunderwelt.one:30000 coords included in the screenshots

**Comment by Desour** [comment]
>is it intentional that water now has "steps"?

If it flows down, it has a step, yes, this also happens in master.
What's new is that if it flows as far as possible, the lower water is waved more down than the upper. But this is fine imo.

**Comment by Desour** [comment]
Breaks waterlilies.

**Pull request closed without merging**
