### PR TITLE
Handle too big connection commands gracefully

### LINKED ISSUE #11214: Server aborts if a connection command becomes too big
##### Minetest version

5.4.0

##### Summary

The engine will call `abort` when a sanity check fails. Among the sanity checks which are performed is a sanity check for the size of a connection command:

```cpp
sanity_check(c.data.getSize() < MAX_RELIABLE_WINDOW_SIZE*512);
```

I am not sure exactly a connection command is I assume it is basically a network packet to be transmitted to a client. The problem is that if this limit is reached the server will call `abort`. One of the cases were this condition can be reached is if the size of a players inventory exceeds this limit. Then the server will abort when trying to send the inventory data to the client.

The following error message is display when the sanity check fails.

```
2021-04-19 18:09:06: ERROR[ConnectionSend]: In thread 7f43db7fe700:
2021-04-19 18:09:06: ERROR[ConnectionSend]: minetest/src/network/connection.cpp:3f9: bool con::UDPPeer::processReliableSendCommand(con::ConnectionCommand&, unsigned int): An engine assumption 'c.data.getSize() < 0x8000*512' failed.
```

##### What should happen instead

I think the reasonable thing to do is to disconnect the client which would have received such a large packet. This is still disruptive for the client but it will not crash the server and disrupt everyone else. I also think an error message like "Disconnected. Reason: Maximum packet size exceeded" would be good.

##### Steps to reproduce

Put the following command in a mod and enable it on a devtest server. Run the `addheavyitem` command twice to reach the limit and crash the server. You also need to change inventory slots between the commands as it will replace the wield item.

```lua
minetest.register_chatcommand("addheavyitem", {
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		local item = ItemStack('basenodes:dirt')
		local s = "A"
		for i = 1, 23 do
			s = s .. s
		end
		local meta = item:get_meta()
		meta:set_string("test", s)
		minetest.get_player_by_name(name):set_wielded_item(item)
		return true, tostring(string.len(s))
	end
})
```

### PR DESCRIPTION
**Pull request by sfan5**
fixes #11214

I liked the suggestion with giving a straight error message to clients too but terminating conversation at the protocol level is simpler and safer.  

## To do

This PR is Ready for Review.

## How to test

see issue

### CODE REVIEW

**Comment by rubenwardy** [comment]
This seems like a bad idea, it could result in players being unable to join the server. It would be better to fix it at its cause, by limiting things that could cause large packets - such as meta in inventories

**Comment by sfan5** [comment]
I don't disagree that this would be preferable, but what is a good limit? And what would happen if mods hit the limit?
There's also the question on how to implement this. ItemStack's are only serialized when needed so once the engine notices that the meta is too long it is too late to blame a particular mod.

Some calculations:
If you set the limit at 16384 you can fit (less than) 1024 items until the engine limit is hit.
But actually the worst case for item meta are non-ASCII bytes where each expands to 6 bytes (`\u0001`), so that actually only leaves space for 170 items in an inventory.
In MTG a book can hold 10000 characters, you could hit the example 16k limit like that.
Another popular usecase is holding an inventory in a single item, the average length of an item name is 25 (in one of my worlds) so let's say 30; given a limit of 16k, this would mean enough space to hold 540 "simple" items.

**Comment by erlehmann** [comment]
From experience as a player on anarchy servers and developer of a game for Minetest (Mineclonia) I can offer additional information that might be crucial:

> This seems like a bad idea, it could result in players being unable to join the server. It would be better to fix it at its cause, by limiting things that could cause large packets - such as meta in inventories

@rubenwardy is entirely correct here that this is a bad idea. This patch introduces something that the Minecraft community calls “bookbanning”. The method works by forcing or tricking users to have items with big meta (portable chests with written books) in their inventory that make them unable to connect.

For years, Minetest anarchy players have been looking for a similar method in Minetest. It was eventually found that this seems impossible given how the engine is programmed – which I see as a good thing, as giving griefers the ability to ban accounts is probably a really bad idea.

> The server crashing also results in players being unable to join it. But it could be left like this, not like this is a common occurrence.

From a game developer perspective, the server crashing is *by far* the best thing that can happen here. Every time it happened on Clamity, Oysterity or some lesser known servers, people loudly complained and we fixed the issue that caused it. Meanwhile, when issues affected only a single or a few accounts, it took way longer to debug and fix the game, since admins did not care as much.

**Comment by erlehmann** [comment]
>  Another popular usecase is holding an inventory in a single item, the average length of an item name is 25 (in one of my worlds) so let's say 30; given a limit of 16k, this would mean enough space to hold 540 "simple" items.

Consider that portable chests (shulker chests) can hold books, enchanted items, handheld maps, all of which may have several kb of metadata (letters, lists of enchantments and dig times, map data and metadata etc.).

Then consider that these portable chests might even hold more portable chests and that this has been working for years.

The practical limit for the kind of inventories people have probably *much* larger than you think it is.

Maybe @ryvnf can chime in on where the practical limit is.

**Pull request closed without merging**
