### PR TITLE
Menu: Merge singleplayer and server tabs

### PR DESCRIPTION
**Pull request by octacian**
Related to #3818 

mt_merge

Renames "Singleplayer" tab to "Local Game" and adds a "Host Server" checkbox which when checked shows the "Announce Server" checkbox as well as the "Name/Password" and "Server Port" fields known from the "Server" tab and changes the "Play Game" button (renamed from "Play") to "Host Game". The "Server" tab is also removed and the "Client" tab renamed to "Play Online" as a result of this.

### CODE REVIEW

**Comment by nerzhul** [comment]
just a note, singleplayer name is used in source code in some places, how do you handle it ?
Is this possible to change name to singleplayer when unchecking host server ?

**Comment by bigfoot547** [comment]
Could there be a `puclic server` button?

**Comment by octacian** [comment]
@nerzhul Yes, I'm well aware of the fact that it is used which is why I didn't change it. The `name` of the tab is still `singleplayer`, only the `caption` has been changed to `Play`. However, I think I am aware of all the places the singleplayer name is used in reference to this tab, so I may give it a go and renaming it fully everywhere.

@bigfoot547 Whoops, I forgot the public server button. Added.

**Comment by sofar** [comment]
Not too bad, suggestion:

Put the world list on the left (including the 3 world editing buttons) but keep the play/host button at the right, make the world list slightly less wide perhaps, this will allow you to put the "HOST" or "PLAY" game below the server options list, which makes much more sense I think.

**Comment by C1ffisme** [comment]
I know this is a bit of a controversial opinion, and maybe a bit of a silly one, but I feel as if combining the tabs gives a feel of a more obscure, and possibly insecure, line between a hosted server and a singleplayer game.

That's probably just my silly opinion, although I'm sure that a few people who might not play a lot of multiplayer games might be thrown off by this. Just thought I'd throw this out in case anyone agreed, or to at least see a good counter-argument.

**Comment by Ferk** [comment]
> On second thought though, I'm undecided as to whether the "Client" tab should be renamed. What do you guys think?

Imho, "Client" is still not a good name, after all the client is also running when you host a game through the GUI. But "Multiplayer" is also not good, because you can also play with other people when hosting.

To me, the best name for that tab would be "Connect". Since it's about connecting to a remote server.

**Comment by sofar** [comment]
Other solutions we can consider:

"Join a game" vs "Host a game" - a "hosted" game without "allow others to join" would then be singleplayer.

Radical, but we could make a "singleplayer" and a "multiplayer" tab. The "multiplayer" tab would have "join" and "host" interfaces combined in some way.

**Comment by Ferk** [comment]
Maybe "Start game" and "Join".
"Start" is accurate but generic enough that could cover both singleplayer and hosting.
Some people might be confused by a "Host a game" tab when they might not have/want any connectivity.

**Comment by red-001** [comment]
does this break being able to pause the game in singleplayer mode or does that still work?

**Comment by rubenwardy** [comment]
Singleplayer/multiplayer seems more natural to me. It's worth seeing how other games split this

**Comment by nerzhul** [comment]
Agreed with @rubenwardy

**Comment by octacian** [comment]
@nerzhul Rebased.

@sofar At this point, I wasn't planning on radically redesigning the formspec. The tab names that have been changed here seem IMO to be short and to the point, which I think is best. The button text changes depending on whether "Host Game" is checked which makes things clear. I honestly don't think that trying to combine server with multiplayer would work or be at all worthwhile. Having the host game option in singleplayer means that a player can select a game and a world just like normal, and easily switch from plain singleplayer to hosted with the click of a button rather than having to first search through the server tab which ends up with a huge list if you have many subgames. And the issue of a huge list would also be apparent if it was somehow combined with the multiplayer tab.

And BTW, I have tested this on different subgames and it has been confirmed to still be functional.

@red-001 No, this does not break the ability to pause the game in singleplayer, singleplayer is still singleplayer and multiplayer is still multiplayer. This does not modify any of the mechanics of the modes but just changes how the multiplayer mode is accessed.

**Comment by ShadowNinja** [comment]
IMO "Public" should be something like "Advertise server", since it's really public either way unless you set a password.

**Comment by octacian** [comment]
I agree, there is probably a better name for Public. I didn't think to change it though, just left it as it always has been on the server tab. Considering that the setting is called `server_announce` maybe "Announce Server" would be best? It makes more sense overall. If anyone else can give some input on this that'd be great.

**Comment by nerzhul** [comment]
Maybe "Show in server list" is a better label and it's explicit :)

**Comment by paramat** [comment]
> "Multiplayer" is also not good, because you can also play with other people when hosting.

I agree. I think 'client' is good for now.

> IMO "Public" should be something like "Advertise server"

'Announce Server' is better, we should avoid the word 'Advertise' due to the unpleasant commercial association. Maybe 'Publicly announce server'?
'Show in server list' is unclear as it could mean show in this machine's local list, it is not clear about the public announcing.

> I wasn't planning on radically redesigning the formspec.

How you have designed this 'play' tab seems good, I like how it is almost identical to singleplayer unless you click 'host server'.

**Comment by octacian** [comment]
OK, I've decided to leave the "Client" tab as is, it is no longer renamed to "Multiplayer." The "Public" checkbox has been renamed to "Announce Server" as it both makes more sense and is easily traceable back to the `minetest.conf` example files.

Only other thing I'm thinking is that I maybe should try to rename the singleplayer tab entirely to play. At this point, only the caption has changed. Yes, it's true that it still works fine, but I feel as though this isn't quite the *right* way to leave things, and I personally believe that it's way easier just doing it right the first time. Thoughts?

**Comment by nerzhul** [comment]
@octacian i think Client can be renamed to "Online" , client doesn't mean anything player side
i hope we will find a consensus and merge this before release it's a real user experience improvement

**Comment by paramat** [comment]
I often use the 'client' tab to set up a server plus a separate client on one machine, i'm sure some do this on LAN too, so 'online' does not seem good.

**Comment by paramat** [comment]
I approve concept.

**Comment by octacian** [comment]
Personally "Online" just doesn't seem right, but if others agree that it is better I will happily change it. However, I think that the two best solutions are as follows:

* Leave as is, with "Play" (renamed from "Singleplayer") and "Client" (not changed)
* or, Do not rename "Singleplayer" and rename "Client" to "Multiplayer"

I consider the last one as it makes partial sense when considered alongside other games. For example, MC requires you to first select the world in singleplayer mode before you can make it multiplayer. For this reason, I believe the latter solution might be best as it gives a better name to "Client" while still making reasonable sense IMO.

Whatever we do though, we need to settle on this quickly, I'd really appreciate seeing this merged before 0.4.16 :D

**Comment by paramat** [comment]
> Leave as is, with "Play" (renamed from "Singleplayer") and "Client" (not changed)

Seems best, as the 'play' tab is not singleplayer if you host a server.

**Comment by Fixer-007** [comment]
Local / Internet

**Comment by paramat** [comment]
Please see discussion and new suggestions http://irc.minetest.net/minetest-dev/2017-05-20#i_4930872

**Comment by ShadowNinja** [comment]
We decided that "Local Game" and "Play Online" were good names for the play/client tabs.  @paramat apparently approves as long as @octacian is fine with the new names, and I'm fine with it too (although I think the files should actually be renamed).  @SmallJoker also approves.

**Comment by nerzhul** [comment]
@octacian can you modify the PR to let us merge it before feature freeze, tomorrow ?

**Comment by paramat** [comment]
. We decided that "Local Game" and "Play Online"

I'm not sure about 'local game' as this tab becomes host a server which is then not local.

**Comment by ShadowNinja** [comment]
@paramat: You're still hosting a local game with a local server even if it's accessible by non-local players.

**Comment by paramat** [comment]
Yeah, i'm neutral on that then.

**Comment by octacian** [comment]
I'm fine with the new names. I'll have the changes pushed within the next few minutes. Also, sorry, on Saturdays I'm not around until later in the evening.

**Comment by octacian** [comment]
I've made the requested changes, including renaming the files and tabs themselves. "tab_singleplayer" has been renamed to "tab_local" and "tab_multiplayer" to "tab_online". I also changed the `name` of the tabs in the tab definition. This should be good to go.

**Comment by nerzhul** [comment]
no problem @octacian we just need to be in the last feature merge phase :)

**Comment by nerzhul** [comment]
merged, thanks

**Pull request merged**
