### PR TITLE
5.0.1

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by nerzhul** [comment]
please release with those commits. We can do another release later for more commits, it's a patch we must be reactive :)

**Comment by paramat** [comment]
Thanks.
77cfc4fcd1d10d088e8a56e38bc195a5d6fe5e57 also needs merging to backport-5.

**Comment by paramat** [comment]
Another one for 5.0.1 #8396

**Comment by paramat** [comment]
#8401 needs adding to this once merged.

**Pull request merged**
