### PR TITLE
Fix glitching through block while sneak glitching

### PR DESCRIPTION
**Pull request by BlockMen**

### CODE REVIEW

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by nerzhul** [comment]
Jenkins build failed

**Comment by nerzhul** [comment]
Jenkins build passed

**Comment by kilbith** [comment]
Why closing ?

**Comment by BlockMen** [comment]
I'm not begging to get things merged anymore, this pull is for more than 3 months open.
With closing its clear for everyone that i won't touch this code/pull anymore.

If you want to use it, there: https://github.com/blockplanet/blockplanet/commit/c96384b3db53295351413ffb78afb6c5c9e587dd

**Pull request closed without merging**
