### PR TITLE
Increase the resolution of the logo shown on the about tab

### PR DESCRIPTION
**Pull request by grorp**
The Minetest logo on the about tab only has a size of 100x100 pixels, so it is scaled up and looks pixelated. This PR increases its resolution to 200x200 pixels.

Before this PR (first Android, then desktop):
screenshot before 1 screenshot before 2 

After this PR (first Android, then desktop):
screenshot after 1 screenshot after 2 

The logo still looks quite bad because Minetest doesn't seem to do proper interpolation when scaling, but I think it's an improvement. The file changed by this PR (`textures/base/pack/logo.png`) is also used as the window icon. This change doesn't cause any problems with the window icon for me (Linux, X11).

## To do

This PR is a Ready for Review.

## How to test

Open the about tab, verify that the Minetest logo looks less bad than before. Also verify that the window icon is still set correctly.

### CODE REVIEW

**Comment by oong819** [comment]
is it worth it? 🤔

**Comment by Desour** [comment]
The image in the about tab is currently quite blurry, so :+1:.

---

Did you re-export the svg or did you just upscale the png?

**Comment by grorp** [comment]
> Did you re-export the svg or did you just upscale the png?

I re-exported the SVG using Inkscape.

**Comment by Desour** [comment]
Minetest does a horrible job at downscaling the larger version of the image.
scrot
I've tried other sizes, many were even worse.
It looks like gui images are not even drawn with bilinear filter (tested with a different texture).

**Comment by grorp** [comment]
> Minetest does a horrible job at downscaling the larger version of the image. [...] It looks like gui images are not even drawn with bilinear filter [...].

I'm going to fix that issue first. Marking this PR as a draft for now.

**Comment by grorp** [comment]
Uh oh, this is way bigger than I thought...
#12581 #12608 #11574 #10733 #2419 6d61375cc7

**Comment by Zughy** [comment]
@grorp if you fix #10733, you'll be my hero.

**Comment by sfan5** [comment]
If it's just for the mainmenu we could add an internal use formspec directive that enables bilinear for images.
This can't be enabled by default for the simple reason that bilinear blurs pixel art.

**Comment by grorp** [comment]
What I did is, I separated the "texture filtering" property of Irrlicht materials into downscaling and upscaling. I then enabled bilinear filtering for 2D graphics just for downscaling. When it's just enabled for downscaling, it fixes the issue at hand and doesn't cause problems with pixel art. It could even look better in many other cases.

I'll open a PR soon. I don't know if this is enough to fix #10733, though.

**Comment by sfan5** [comment]
That's a clever fix.

> I don't know if this is enough to fix #10733, though.

Probably not because that issue is actually about integer scaling.
There's three separate problems:
* Downscaling looks bad because no bilinear (this here)
* Upscaling looks bad because no anti-aliasing unless you have an integer multiple (best described by #2419, IMO that should've been kept open)
* item and/or hotbar slots have weird sizes that don't lend themselves to exact pixel art (#10733)

**Review by sfan5 — APPROVED** [review]

**Comment by sfan5** [comment]
As a side note: why do we have these "odd" sizes and not just 256x256?

**Comment by grorp** [comment]
> As a side note: why do we have these "odd" sizes and not just 256x256?

Changed the size to 256x256 pixels.

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
