### PR TITLE
Add find_total_nodes_in_area with optional limit

### PR DESCRIPTION
**Pull request by cmdskp**
Provides a fast method for scripts to determine how many nodes (up to optional limit parameter) are in an area.

Searches in alternating direction y layers from the middle outwards to maximise efficient searching pattern (This is likely to find (up to the limit) nodes faster, as these are commonly arranged nearer the middle layer than on the top/bottom extremes of the bounding area. E.g. flowers, fires, water on surface planes).

The optional limit parameter allows early aborting the find when it finds that many.  Particularly useful for checking if there are n nodes(or of-a-group) in area quickly, without the result tables generation overhead of find_nodes_in_area.

### CODE REVIEW

**Comment by sofar** [comment]
- Please add a space between ```if (``` before the parentheses. Same for ```while (```, etc..
- maybe squash these three commits into one?
- if this is such an efficient way of searching, then why not replace the find_nodes_in_area with the same algorith?

you know a patch is worth getting looked at when people first comment on style

**Comment by paramat** [comment]
Apparently 'find nodes in area' searches the way it does because it tries to find the closest nodes, and is intended for a very small radius. So this PR might be a welcome function to complement it but should not replace.

**Comment by cmdskp** [comment]
@sofar I have added the spaces throughout, for code consistency - to match the new bits, I'd automatically done.  I will attempt to squash the commits to one when I have access to github's shell.

@paramat Concur, the advantage of utilising this search pattern is purely for early aborting code, like this new function only.

**Comment by rubenwardy** [comment]
I'd like to see this.

**Comment by cmdskp** [comment]
@sofar Commits squashed into one.

**Comment by sofar** [comment]
You shouldn't fix up the style errors in existing code that isn't changed by your functional changes, that just makes the commits harder to review and makes git history complex and hard to trace back.

Just fix the style errors in the code that you touch.

**Comment by sofar** [comment]
Aw! you don't need to close a PR to resbmit. Just git push -f to your personal branch and it gets updated. This way, the conversation history is kept, and people can see what changed over time.

**Comment by red-001** [comment]
@sofar He said on IRC that he can only use the github website.

**Comment by sofar** [comment]
Well, I wonder how he even pushes to github in the first place then. Shame though, working through the website is rather cumbersome.

**Pull request closed without merging**
