### PR TITLE
Valleys mapgen: Fix MSVC errors

### PR DESCRIPTION
**Pull request by SmallJoker**
- Remove already included files; sort by alphabet

### CODE REVIEW

**Comment by paramat** [comment]
Everything looks good apart from removing so many #includes, because the other mapgens have all these #includes present lets make that another PR and discuss it first, i should check with hmmmm whether they are needed or not.
Good work on the MYMIN/MYMAX myround and (double).

**Comment by est31** [comment]
When it builds without them, #includes aren't needed, are they?

Either way, :+1:  to the part that does the MYMIN/MYMAX.

**Comment by sofar** [comment]
if you can remove this many includes, it's likely that the corresponding ```.h``` file already includes them. In general, you should include them in the ```.cpp``` file as well, since a change in the ```.h``` includes shouldn't affect the ```.cpp``` file.

**Comment by SmallJoker** [comment]
All the `.h` files were already included in other `.h` files: 
`emerge.h` includes `map.h` and `mapgen.h`
`mapgen.h` includes `noise.h`, `nodedef.h` and `mapnode.h`
...

**Comment by paramat** [comment]
Okay seems good then :+1: will merge soon as it is.

**Comment by paramat** [comment]
Looks like this will conflict with #3590 and it will be much easier for you to rebase than him, so will wait for that to go in first.

**Comment by paramat** [comment]
If you don't mind it will be easier for me to ask duane-r to include these fixes when he updates #3590, then you won't have to do anything and it's one less merge to be done.

**Comment by SmallJoker** [comment]
Do your updates. I will wait for them and rebase these changes.

**Comment by paramat** [comment]
This PR is included entirely in duane-r's PR so this will be closed when that is merged.

**Comment by ShadowNinja** [comment]
:-1: on the include removals.  This has caused issues in the past when I removed some unnecessary includes from a header to slim it down.  Not including headers that you use is only O.K. if they're included by that file's header (eg, `object.c` can depend on includes from `object.h`, but not `settings.h`).

**Comment by SmallJoker** [comment]
No longer required to discuss this - everything can be found in pull ##3590

**Pull request closed without merging**
