### PR TITLE
Add autojump (increased stepheight).

### PR DESCRIPTION
**Pull request by KodexKy**
Adds option to increase stepheight by hotkey L for all platforms. It's on by default only on android, where it's been added as a checkbox on simple_main. I'd like to add a button to the in-game android gui, but that will wait for sapiers rework.

### CODE REVIEW

**Comment by sapier** [comment]
I'm against this pull, following our customizability rule stepheight should be configurable by mods(server). A client side setting to modify it would be useless or at least behaving quite strange.

Having this on android is only due to limitations of controls a android device faces. These are not present on PC so no reason to use ugly hacks here.

**Comment by PilzAdam** [comment]
I am against a client-side setting for this, too.

**Comment by MoNTE48** [comment]
Very good idea. I use this - all my users like auto jump.

**Comment by nerzhul** [comment]
I'm against this too

**Comment by nerzhul** [comment]
After discussing with @Zeno- we only need it on android not in PC. @sapier and @PilzAdam also agrees. Thanks anyway.

**Pull request closed without merging**
