### PR TITLE
Final update to credits before release

### PR DESCRIPTION
**Pull request by Zeno-**
Merge at final moment before release

### CODE REVIEW

**Comment by Zeno-** [comment]
cc @Rogier-5 can you please confirm you're ok with how you're attributed, or provide an alternative. Cheers.

**Comment by paramat** [comment]
As someone has commented, these lists of 'active' and 'previous' are awkward and arbitrary.
First we have to decide an amount of contribution that gets someone a mention, i think it should be all commit authors however small the commit.
Secondly we have to decide who is 'active', better to define it specifically as those who have committed during the last release cycle.
So, i would have 2 lists, the first is 'recent contributors', the second is everyone else, anyone who has authored a commit in engine or game. Both lists ordered by number of commits.
The lists would be large, so don't bother with email addresses, just their Github usernames. The second list can have multiple usernames on each line to save space.
Or, have email addresses in the first list only.

**Comment by paramat** [comment]
+1 if Rogier-5 is happy.

**Comment by Rogier-5** [comment]
Just 'Rogier \<rogier777@gmail.com\>' (instead of 'Rogier-5') will be fine.

Thanks.

**Comment by paramat** [comment]
:+1:

**Comment by Zeno-** [comment]
Thanks, Rogier. Updated

**Comment by sfan5** [comment]
d346875e8ecf9e25babdaef277c25f7cfdfd3b6b

**Pull request closed without merging**
