### PR TITLE
Add support for docker-compose

### PR DESCRIPTION
**Pull request by Niwla23**
This PR adds the ability to spin up a server by using docker-compose.
It solves the usecase where you want to use docker-compose to spin up a minetest server (templates wanted this info from me :grin: )

### CODE REVIEW

**Comment by rubenwardy** [comment]
This really doesn't make sense,  docker compose should be made on the user side not on the docker image side. This could be added to the readme as an example but not as a file in the repo

**Comment by Niwla23** [comment]
Why do you think so, @rubenwardy ? Many repos have a docker-compose file, why would you put a setup file in the README instead of the repo?

**Comment by rubenwardy** [comment]
Because it's pretty much just documentation - you wouldn't use the compose file in CI or directly, you use it locally when pulling the image to host a server

**Comment by Lejo1** [comment]
I think it would be more useful here to show more complex solutions like using postgresql.
A compose file is not needed for a single container.

**Pull request closed without merging**
