### PR TITLE
Update minetest.po (Japanese)

### PR DESCRIPTION
**Pull request by Rui914**

### CODE REVIEW

**Comment by Zeno-** [comment]
+1

**Comment by Zeno-** [comment]
@Rui914  perhaps someone should make you Japanese translation manager ☺

**Comment by nerzhul** [comment]
Hi @Rui914 can you squash your commits please ?

**Comment by Rui914** [comment]
I'm sorry, do not know how ...

**Comment by nerzhul** [comment]
@Rui914 use git --rebase -i HEAD~2 (where 2 is the number of the commits to squash)

**Comment by sfan5** [comment]
Just leave your commits as is, we can squash them when we merge the pull.

**Comment by Rui914** [comment]
I was able to maybe.
Thank you, everyone!

**Comment by Rui914** [comment]
Done.

**Comment by Zeno-** [comment]
commit b21230b329665492c9e9337860950a68b9ef40c1

**Pull request closed without merging**
