### PR TITLE
Mgvalleys: add notifier for massive caves

### PR DESCRIPTION
**Pull request by duane-r**
Add two gennotify events for each chunk of massive cave generated,
defining the smallest cube containing all of the space cleared.

I think the only useful information we can return for a multi-chunk cave is each cube outlining the cave's extent in the chunk. From that, you can guess the direction the cave is opening, assuming you don't just get the entire chunk's dimensions back. (If it's higher that the bottom of the chunk, it's probably a floor, etc.) I've already found it useful just to note that there **is** a massive cave in a chunk, without bothering with the dimensions.

I'm not sure I did this correctly, but it works

### CODE REVIEW

**Comment by paramat** [comment]
The intention is good but the implementation adds an unjustified amount of extra code into the cavegen y loop. I think we can simplify this to a single notify 'gennotify massive cave' that is a flag that a massive cave has been generated in a mapchunk, then any mod using this can do the hard work of searching for the open space of a massive cave.

How about this: make 'made a big one' a u32 that counts how many massive cave air nodes have been added, then if that is > some chosen limit notify and add event being minpos of that mapchunk.

**Comment by paramat** [comment]
To make the new gennotify type useful for other mapgens it could possiby have a more general name.
The existing cave gnnotify types are for the shared pseudorandom caves, so for this perhaps it can be called 'gennotify alternative cave'?

**Comment by duane-r** [comment]
>The intention is good but the implementation adds an unjustified amount of extra code into the cavegen y loop.

You might be over-optimizing. It should amount to six integer compares on most loops, and only if a massive chunk is generated. I don't see any difference in speed. I've tried to get hard numbers, but my cave generation times vary wildly even when I remove most of the code.

Anyway, I'm happy just to be notified that a massive cave is present.

>How about replacing the bool 'made a big one' with a u32 'massive cave air count' that counts how many massive cave air nodes have been added, then if that is > some chosen threshold (perhaps 1/8th mapchunk volume) notify of a massive cave and add a simple flag event: 'massive cave'.

It's much more important for my uses to know reliably if any bit of a massive cave is part of the chunk. How about this?

**Comment by paramat** [comment]
Okay i'll reconsider my opinion on this.

**Comment by paramat** [comment]
> It's much more important for my uses to know reliably if any bit of a massive cave is part of the chunk.

Yeah this is fine.

:+1: I'm happy with this.

**Comment by duane-r** [comment]
>The intention is good but the implementation adds an unjustified amount of extra code into the cavegen y loop.

You're right again. There's a much more efficient way to do it: https://github.com/duane-r/minetest/commit/6a744f300ff3bffa7f6f0c0c2e4ad2352f11f3bd This unloads two-thirds of the work to the outer loops. I don't know why that never occurred to me.

**Comment by paramat** [comment]
That's clever. I'm not sure if i'm happy for that to be the method merged, i need to consider and of course hmmmm's input will be needed.

Is calculating the maximum void-box in the mapgen particularly necessary for mods? Any mod triggered will be loading the entire mapchunk as a mapgen-object voxelmanip and will be scanning through this anyway, so perhaps just the simple 'gennotify alternative cave' flag is enough.

But then, for consistency we could have 'gennotify alternative cave begin' and  'gennotify alternative cave end' and then leave it to each mapgen to decide whether to do a complex calculation for both or just return a fixed pos for both as a simple flag.

**Comment by duane-r** [comment]
>Is calculating the maximum void-box in the mapgen particularly necessary for mods? Any mod triggered will be loading the entire mapchunk as a mapgen-object voxelmanip and will be scanning through this anyway, so perhaps just the simple 'gennotify alternative cave' flag is enough.

The main reason I've seen to notify is to keep things confined outside of massive caves, or inside them. If there were no other caves, you could just assume any open space below heightmap is good. If you want other types of caves, but you want really big caves to be special in some way, you need to be able to distinguish them.

I haven't found any way to do that from lua that's more efficient than just loading the massive cave noise again and checking every voxel. It would be more efficient to just dig the cave in lua if you have to do that, but you'd run into the problem of random lava from large caves appearing, unless you confine them to different depths. Not having to load a 3D noise twice saves valleys_c a considerable amount of time.

If you're going to notify, and you can't pass an exact description of the cave, you have to decide whether to err outside or inside the cave. Since I'm more worried about keeping things out, I'd prefer to err outside. (If you're dealing with liquids, it's much more important to keep things out than in, since you have a much greater volume of cave to police inside.) However, I also want to keep some things in, so the more precise a description I can get, the better.

A random open shape inside a cube should occupy more than half of the cube on average, so over half the time the sub-cube containing it will be equal to the whole chunk. So, less than a quarter of the time, knowing a sub-cube containing the massive cave bit will let you avoid contaminating half of the volume of the chunk, of which only a small amount will contain random caves (assuming you err outside the caves).

Looking at it that way, I'd say it's not worth bothering with unless it's absolutely necessary to keep them separated.

There's also the issue of trying to build big structures inside caves, but I haven't found any neat way to do that. The best I came up with is a combination of air-column checking and notification.

**Comment by paramat** [comment]
Removed my +1, i'm still unsure of the best implementation.

**Comment by duane-r** [comment]
How about a flag that indicates which faces of the chunk are touched by the space in a large cave? The easiest way would just be a vector with each component containing four bits (0 = none, 1, = positive, -1 = negative, any other number = both). That would give you some of the information defined by the cube containing the cave, but would take less cpu time. All you have to do is set the flag if cave is generated at any maximum or minimum. Also, it only requires one gennotify.

The absence of Y- tells you that you have some degree of floor; conversely a missing Y+ indicates some sort of ceiling, especially if X+- and Y+- exist. Any axis' positive and negative without any of the other axes' indicates a tunnel. All zeroes indicates a bubble.

**Comment by paramat** [comment]
Nice idea, i will try to get hmmmm's opinions on this.
It needs to be general for use with any alternative cave type in any mapgen.
We already have 3D noise tunnels which are currently not notified, and like 3D noise caverns are more difficult to do so, pseudorandom caves already have start/end points already computed and available.
For now i'm still not convinced new notifiers are worth it.

**Comment by duane-r** [comment]
>For now i'm still not convinced new notifiers are worth it.

So far, I seem to be the only one who's interested.

**Pull request closed without merging**
