### PR TITLE
Textures: Replace menu background fallback dirt_bg.png with empty sky texture

### LINKED ISSUE #3986: menu_clouds = false results in a black background
If you turn of clouds it makes the background black. Not sure if this is a bug or I am asking for a feature request. It should default to a nice background.

Shreenshot of what I get.
http://i65.tinypic.com/rvge4h.jpg

This is from master branch on github. downloaded 2 days ago.

### PR DESCRIPTION
**Pull request by paramat**
screenshot from 2016-04-20 07 35 31

To fix #3986 
To make the menu fallback background subgame-unversal the dirt texture is replaced with an empty sky texture 'sky_bg.png' colour-sampled from the skybox, it is therefore identical to the skybox without clouds. So now when 'menu_clouds = false' we get a sky without clouds.

### CODE REVIEW

**Comment by Zeno-** [comment]
+1 from me with the minor change discussed in IRC

**Comment by nerzhul** [comment]
Anoying background :(

**Comment by paramat** [comment]
Do you find the blue sky with clouds annoying too?

**Comment by nerzhul** [comment]
the problem with this blue only background is for eyes when you didn't have many light in your room

**Comment by Zeno-** [comment]
If it's annoying then *shrug*. It's still a trivial change and renaming to menu_bg.png is fine for now. After release we can probably look at changing it to something else and debate it for a few months :)

**Comment by paramat** [comment]
Updated to menu_bg.png.

The normal sky with clouds is brighter than this.

**Comment by SmallJoker** [comment]
Previously I saw this with a texture pack:


Blue looks a plain but fits because it's exactly what the setting does. It disables the clouds.

**Comment by kilbith** [comment]
Small hint : if your texture is plain color, you can reduce it to 1px.

**Comment by sfan5** [comment]
:+1:

**Comment by paramat** [comment]
With a texture pack you'll still get the dirt texture as a background.

**Comment by paramat** [comment]
9b437088dfff0303c99f70848f8f404b16ed1e55

**Pull request closed without merging**
