### PR TITLE
Cavegen: Place correct biome surface in tunnel entrances

### PR DESCRIPTION
**Pull request by paramat**
Previously in tunnel entrance floors only a single biome 'top' node was
placed and 'filler' nodes were missing.

Place 'top' and 'filler' nodes in tunnel entrance floors with depths
defined by the biome.
In tunnel entrances under rivers 'riverbed' nodes are placed to the
biome-defined depth.
/////////////////////////////////////////////////

This PR uses the code from biome generation and applies it to tunnel entrance floors, making any exposed tunnel floors more consistent with surrounding terrian.
Tested.

screenshot_20170215_004158

^ Without this PR, the biome material in the cave would be a single grass node with no dirt below.

### CODE REVIEW

**Comment by MarkuBu** [comment]
Never noticed that. It is more weird if trees are growing under stone in darkness

**Comment by paramat** [comment]
Biome surface material is only placed on tunnel floors that are open to the sky.

**Comment by paramat** [comment]
Approval from sfan5 http://irc.minetest.net/minetest-dev/2017-02-16#i_4812519

**Comment by paramat** [comment]
9aabfd5188ce42c98f5ccbe275776dee5ace057d

**Pull request closed without merging**
