### PR TITLE
Replace call to obsolete get_look_pitch().

### PR DESCRIPTION
**Pull request by sofar**

### CODE REVIEW

**Comment by sofar** [comment]
Ref: https://github.com/minetest/minetest_game/issues/1349

**Comment by sofar** [comment]
Should be trivial since get_look_vertical() is defined in the lua API in this very codebase, so there's no backwards compatibility issues with switching out this deprecated function.

**Comment by Rogier-5** [comment]
Why is this obsolete anyway ? Even if 'pitch' and 'yaw' are not intuitive enough (what other reason is there to replace 'pitch' and 'yaw' with 'vertical' and 'horizontal' ?), then there's no reason both can't coexist.

Also, entities don't have `get_look_vertical()` and `get_look_horizontal()`. They still use 'pitch' and 'yaw' (last time I checked the code). This is not very consistent...

**Comment by Rogier-5** [comment]
Actually, it seems (from the code; see #4229) that both return different values. That's apparently the reason for the new functions. So one should probably not simply be replaced by the other.

**Comment by sofar** [comment]
The vertical one is safe to replace afaics, the horizontal is not (I've had bugs in mods with look_yaw myself)

**Comment by sofar** [comment]
With patch, the placement of tree trunks still behaves the same as well (tested)

**Comment by Rogier-5** [comment]
> The vertical one is safe to replace afaics, the horizontal is not (I've had bugs in mods with look_yaw myself)

Should be quite safe indeed. It looks like the returned value isn't even being used. It seems like the entire call might just as well be removed altogether...

**Comment by sofar** [comment]
yowsa! Alright then, I'm gonna make sure we can luacheck this code :)

**Comment by sofar** [comment]
Remove the entire call and local `pitch`, instead.

**Comment by nerzhul** [comment]
Seems okay. @sofar it seems when i worked on #4612 i saw the get_look_pitch and i didn't find how it's interesting server side because it's not linked with client (if i remember)

**Comment by paramat** [comment]
380a4b6d60c3269d1d9c79c122ff5259989decd7

**Pull request closed without merging**
