### PR TITLE
Required CMake version increased

### PR DESCRIPTION
**Pull request by debagos**
Increased CMake version dependency.

### CODE REVIEW

**Comment by sfan5** [comment]
This is the wrong way to go about it.
CMake 3.11 happens to be required in the specific case you were testing, it's not generally required and shouldn't be. A workaround might be possible in this case which should be considered instead.

**Comment by debagos** [comment]
I see where you are coming from, but since I assume no one can compile Minetest with CMake < 3.11 without workarounds anymore, making a 3.11+ version a requirement seems sensible.
I'm very dopey when it comes to actual coding and scripting, but I guess the people who try to compile MT with ancient CMake versions are not capable of creating such a workaround and that will lead to frustration.
Ultimately it's your decision if you accept the PR, but I wonder how to justify a requirement which is known to be outdated and not working.

**Comment by sfan5** [comment]
I successfully built Minetest with CMake 3.10 doing nothing more than what is written in the README just today, documenting a minimum requirement of CMake 3.11 is not sensible.

> people who try to compile MT with ancient CMake versions are not capable of creating such a workaround and that will lead to frustration.

What I meant was that we can put a workaround into our CMake build files so it'd work even on older versions. Users can of course not be expected to figure a workaround themselves.

**Comment by debagos** [comment]
> I successfully built Minetest with CMake 3.10 doing nothing more than what is written in the README just today

The whole game or just the server, like me yesterday?
As @JosiahWI pointed out in https://github.com/minetest/minetest/issues/11564, the problem seems CMake 3.11+ features.

**Comment by nerzhul** [comment]
fixed by #11566

**Pull request closed without merging**
