### PR TITLE
Switch to Astyle formatting

### PR DESCRIPTION
**Pull request by ShadowNinja**
The clang-format style didn't really fit the current code style, and it doesn't work with our code style<sup>[1]</sup>.  The linting script is also much better now<sup>[2]</sup>, which should result in much faster styling.

This also removes some deleted threading files from the whitelist (Astyle currently considers unused whitelist entries an error -- although this can be changed if desired).

We have to build Astyle ourselves on Travis to get a new enough version -- but that shouldn't be an issue since Astyle is tiny (~10 sec download/build/install time)

[1]: Specifically, if you make it use "class Foo {" style instead of "class Foo\n{" style, it will trim all empty newlines before the class (same for structs, enums, etc).

[2]: Instead of linting whitelisted files and then ignoring the result, it doesn't lint them in the first place.  Also, the excludes are passed to Astyle, so there isn't any bash in the hot path.

TODO:
  * Find out what files pass with the current settings and de-whitelist them.

TODO later:
  * Potentially restyle some files (don't want massive diffs just for style, but the config matches the current style pretty well, so it shouldn't be _that_ bad.  e.g. running it on `main.cpp` only changes about 55 lines).

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Build succeeded, I just canceled the non-lint builds since I didn't actually change any sources.

**Comment by nerzhul** [comment]
i hope we can have at least as many files in whilelist as before :)

**Comment by ShadowNinja** [comment]
@nerzhul: I intentionally left that out since it would bloat the diff.  But I could do it as a separate commit.

**Comment by ShadowNinja** [comment]
Done.  I left the sha files on the whitelist since they're copied from other projects.

I also left sky.h and l_client.h on the list because Astyle sometimes adds a double continuation indent where we don't want it.  e.g.:
```C++
// Continuation indent is two tabs -- double continuation indent
// added because there's a continuation for the assignment and
// another continuation for the method call.
int very_long_variable_name = very->very->very->long_method_call(
>       >       >       >       arg1, arg2, arg3);
```

**Comment by nerzhul** [comment]
It's nice, can you rebase and possibly add a gitlab-ci step ?

I have currently

```

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
index d48dd5fc..54d5ece4 100644
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,7 @@
 # Pipelines URL: https://gitlab.com/minetest/minetest/pipelines

 stages:
+  - prechecks
   - build
   - package
   - deploy
@@ -55,6 +56,18 @@ variables:
     - dpkg -i ./*.deb

 ##
+## Prechecks (not OS dependent)
+##
+
+check:astyle:
+  stage: prechecks
+  image: base/archlinux
+  before_script:
+    - pacman --noconfirm -Sy archlinux-keyring
+    - pacman --noconfirm -Sy astyle
+  script:
+    - ./util/lint.sh
```

It is okay to test on gitlab CI side if the script path is okay, archlinux has astyle 3.0.1

https://gitlab.com/nerzhul/minetest/builds/18571083

**Comment by paramat** [comment]
@ShadowNinja can you work on this or does it need adoption?

**Comment by paramat** [comment]
Not keen on this. This seems to change our formatting to keep the linter happy, which seems the wrong way around, the linter cannot cope with our codestyle but i don't think we should change to conform to it.

**Comment by paramat** [comment]
Neglected, closing.

**Pull request closed without merging**
