### PR TITLE
Fix occlusion culling, again

### PR DESCRIPTION
**Pull request by lhofhansl**
Fixed glitches introduced with #4922... again.

### CODE REVIEW

**Comment by paramat** [comment]
:+1:

**Comment by est31** [comment]
:+1:

**Comment by Fixer-007** [comment]
Changed occlusion back to about pre-#4922 level.

**Comment by est31** [comment]
In theory, it should expose the same exact behaviour.

**Comment by lhofhansl** [comment]
Yeah. Exactly the same. Just calls it out as a hack.

**Comment by paramat** [comment]
Well i don't agree it's a hack, it's just MT occlusion culling, imperfect but does a reasonable job, and is possibly fairly optimal in balancing simplicity against effectiveness.

**Pull request merged**
