### PR TITLE
[WIP] Don’t copy TileSpecs

### PR DESCRIPTION
**Pull request by numberZero**
Includes #6904.
Should improve meshgen performance: TileSpecs are used to be slow to copy. Should not affect GPU load at all.

*diff: https://github.com/minetest/minetest/pull/6930/files/46b36798ffaa00e505b77b7d33e79d268d3f00d3..c7e7f025970b3240fd7a22f14035d88e4ffe15c5*

### CODE REVIEW

**Comment by numberZero** [comment]
Note: this is ready for testing. Remaining work is mostly moving&renaming.
For code changes belonging specifically to this PR, see the link in the first post.

**Comment by paramat** [comment]
Will test.

**Comment by Fixer-007** [comment]
I've applied PR6930 and did few benchmarks with fraps/processexplorer/tinytask, there is easily +/- 1% error in results, with this PR I got CPU time decrease by 1.5-2%, which is quite tiny, avg/min/max fps looked the same.

**Comment by paramat** [comment]
I guess the improvement will be faster mesh creation so that world comes into view faster.

**Comment by numberZero** [comment]
Profiling shows #6904 is generally the best for content-heavy mapblocks and negligibly worse than master for mostly solid ones. This PR is better than both for mostly-solid mapblocks but is substantially worse for content-heavy ones, probably due to worse cache usage.
CPU: Intel® Core™ 2 Quad Q9300 @ 2.50GHz
Closing this PR for now but investigating further; there must be better solutions.

**Comment by paramat** [comment]
Now that #6904 is merged will there still be a significant performance penalty having all drawtypes accepting 6 textures? I'm thinking about all those many leaves on trees having an effect if allfaces optional becomes slower.

**Comment by numberZero** [comment]
@paramat That should not matter. But I think the performance penalty will not be significant; smooth lighting is the heavies part IIRC.

**Pull request closed without merging**
