### PR TITLE
Add Indonesian translation of builtin

### PR DESCRIPTION
**Pull request by srifqi**
**Goal of the PR**
This PR adds the Indonesian translation for `builtin`.

## To do
This PR is Ready for Review.

### CODE REVIEW

**Comment by srifqi** [comment]
Colek Kak @SpicyOnta, barangkali mau ikut periksa terjemahannya (setelah sebelumnya membantu di minetest/minetest_game).

**Comment by Wuzzy2** [comment]
This is a full and up-to-date translation of the latest version of builtin. Great job!

I don't speak Indonesian, but technically, it looks OK.

**Comment by Wuzzy2** [comment]
Upon further review, I have found two technical mistakes:

```
Players online with the "@1" privilege: @2=Pemain daring dengan hak "@1":
```

The `@2` parameter is missing in the translation.

```
emergeblocks update: @1/@2 blocks emerged (@3%)=kabar emergeblocks: @1/@2 blok muncul
```

The `@3` parameter is missing in the translation.

Note that parameters are *not* optional and *must* be included in the translation.

**Comment by Wuzzy2** [comment]
Maintainers: If the PR author does not react within the release time frame, I suggest to merge this anyway but with the two faulty strings cleared. That's still better than no translation at all.

**Comment by srifqi** [comment]
Thank you for the review. I must have missed that.

**Comment by Wuzzy2** [comment]
Awesome! All checks pass now.
I have written a checker script by the way:

https://codeberg.org/Wuzzy/minetest_check_translations

**Review by sfan5 — APPROVED** [review]
lgtm

**Comment by srifqi** [comment]
Thank you for the merge!

**Pull request merged**
