### PR TITLE
Builtin: Add vector.floor helper function

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by nerzhul** [comment]
:+1:

**Comment by sofar** [comment]
Just merge this - I was about to submit the very same function myself :).

:+1:

**Comment by nerzhul** [comment]
Merged, thanks @sofar

**Comment by t4im** [comment]
`vector.apply(v, math.floor)`?

**Comment by sofar** [comment]
interesting, but it'd be pretty limited that way (only 1 vec). I'd make it `vector.apply(func, vec, ...)` instead.

**Comment by rubenwardy** [comment]
Vector.floor is more consistent with Vector.round

Vector.apply already exists btw.

**Pull request merged**
