### PR TITLE
Fix mods folder being read read twice with RUN_IN_PLACE=1

### LINKED ISSUE #15004: Duplicate entries for installed mods in Content Tab/Mod Select (+ other problems)
### Minetest version

```true
Minetest 5.10.0-dev-debug-48845de46 (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.2
Running on Linux/6.10.4 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Summary

image
image

### Steps to reproduce

Install something from CDB, maybe on a fresh MT instance

### PR DESCRIPTION
**Pull request by grorp**
should fix #15004

## To do

This PR is a Ready for Review.

## How to test

Use a RUN_IN_PLACE=1 build, have some mods installed, see that the mainmenu works again.

### CODE REVIEW

**Comment by sfan5** [comment]
I haven't checked related stuff closely but wouldn't it be better if the mainmenu code "just" dealt with duplicate mods correctly?
It's not unthinkable that a mod exists in both the share path and the user path, but in different versions or whatever.

**Comment by grorp** [comment]
> I haven't checked related stuff closely but wouldn't it be better if the mainmenu code "just" dealt with duplicate mods correctly?
> It's not unthinkable that a mod exists in both the share path and the user path, but in different versions or whatever.

Having the same mod in both path_user and path_share when they're different locations already seems to work fine.
Regardless, this PR is only meant to fix the regression.

**Comment by rubenwardy** [comment]
As grorp said - it's already possible to install the same package to multiple locations and these will turn up multiple times. The main menu is working as expected in this regard.

This PR fixes duplicate package entries when share and user dir are the same folder

**Review by sfan5 — APPROVED** [review]
lgtm

**Review by SmallJoker — APPROVED** [review]
Discovered this problem while testing another PR. I could not enable `mobs_redo` because the share path took priority. Glad to see that there's already a fix waiting.

**Suggestion:**

1. In https://github.com/minetest/minetest/blob/master/doc/menu_lua_api.md?plain=true#L285 :

```
share = "/usr/share/minetest/mods", -- only provided when RUN_IN_PLACE=0
```


---

master:
```
{
	is_name_explicit = true,
	name = "mobs",
	virtual_path = "share/mobs_redo",
	path = "MYMINETESTROOT/mods/mobs_redo",
	type = "mod",
	release = 0,
	dir_name = "mobs_redo",
	parent_dir = "MYMINETESTROOT/mods"
}
{
	is_name_explicit = true,
	name = "mobs",
	virtual_path = "mods/mobs_redo",
	path = "MYMINETESTROOT/mods/mobs_redo",
	type = "mod",
	release = 0,
	dir_name = "mobs_redo",
	parent_dir = "MYMINETESTROOT/mods"
}
```

PR:
```
{
	is_name_explicit = true,
	name = "mobs",
	virtual_path = "mods/mobs_redo",
	path = "MYMINETESTROOT/mods/mobs_redo",
	type = "mod",
	release = 0,
	dir_name = "mobs_redo",
	parent_dir = "MYMINETESTROOT/run/mods"
}
```

**Comment by j-r** [comment]
> > I haven't checked related stuff closely but wouldn't it be better if the mainmenu code "just" dealt with duplicate mods correctly?
> > It's not unthinkable that a mod exists in both the share path and the user path, but in different versions or whatever.
> 
> Having the same mod in both path_user and path_share when they're different locations already seems to work fine. Regardless, this PR is only meant to fix the regression.

I thought so, too, but actually this isn't true for modpacks. Sorry that I didn't test that enough and thanks for the fix, which is obviously fine.

But the same problem exists whenever there are multiple modpacks with the same name. Something like the following will fix that, but I have no clue whether that is the correct way; perhaps it's better/easier to disambiguate the modpack name.

``` lua
diff --git a/builtin/mainmenu/content/pkgmgr.lua b/builtin/mainmenu/content/pkgmgr.lua
index fc94b03fa..8cd30566c 100644
--- a/builtin/mainmenu/content/pkgmgr.lua
+++ b/builtin/mainmenu/content/pkgmgr.lua
@@ -320,7 +320,7 @@ function pkgmgr.render_packagelist(render_list, use_technical_names, with_icon)
                        color = mt_color_dark_green

                        for j = 1, #rawlist do
-                               if rawlist[j].modpack == list[i].name then
+                               if rawlist[j].modpack == list[i].name and rawlist[j].virtual_path:find(v.virtual_path, 1, true) == 1 then
                                        if with_icon then
                                                update_icon_info(with_icon[rawlist[j].virtual_path or rawlist[j].path])
                                        end
@@ -396,10 +396,10 @@ function pkgmgr.get_dependencies(path)
 end

 ----------- tests whether all of the mods in the modpack are enabled -----------
-function pkgmgr.is_modpack_entirely_enabled(data, name)
+function pkgmgr.is_modpack_entirely_enabled(data, name, virtual_path)
        local rawlist = data.list:get_raw_list()
        for j = 1, #rawlist do
-               if rawlist[j].modpack == name and not rawlist[j].enabled then
+               if rawlist[j].modpack == name and rawlist[j].virtual_path:find(virtual_path, 1, true) == 1 and not rawlist[j].enabled then
                        return false
                end
        end
@@ -436,7 +436,7 @@ local function toggle_mod_or_modpack(list, toggled_mods, enabled_mods, toset, mo
                -- Toggle or en/disable every mod in the modpack,
                -- interleaved unsupported
                for i = 1, #list do
-                       if list[i].modpack == mod.name then
+                       if list[i].modpack == mod.name and list[i].virtual_path:find(mod.virtual_path, 1, true) == 1 then
                                toggle_mod_or_modpack(list, toggled_mods, enabled_mods, toset, list[i])
                        end
                end
diff --git a/builtin/mainmenu/dlg_config_world.lua b/builtin/mainmenu/dlg_config_world.lua
index e8f49b230..6091ebe3a 100644
--- a/builtin/mainmenu/dlg_config_world.lua
+++ b/builtin/mainmenu/dlg_config_world.lua
@@ -216,7 +216,7 @@ local function get_formspec(data)

        if mod.name ~= "" and not mod.is_game_content then
                if mod.is_modpack then
-                       if pkgmgr.is_modpack_entirely_enabled(data, mod.name) then
+                       if pkgmgr.is_modpack_entirely_enabled(data, mod.name, mod.virtual_path) then
                                retval = retval ..
                                        "button[5.5,0.125;3,0.5;btn_mp_disable;" ..
                                        fgettext("Disable modpack") .. "]"
```

AFAICT the not ideal display of the duplicate mods and this modpack enabling issue are actually the cause of all problems reported in the context of this PR (and only indirectly caused by the two paths pointing to the same location, which of course is a good idea to have fixed).

**Comment by SmallJoker** [comment]
@j-r Would you please be so nice to comment this on https://github.com/minetest/minetest/issues/15004, or open a new issue? This PR is a dead-end (merged).

**Pull request merged**
