### PR TITLE
"#if undefined_constant < number" is always true

### PR DESCRIPTION
**Pull request by mazocomp**
This also partially fixes this issue https://github.com/minetest/minetest/issues/7254

### CODE REVIEW

**Comment by SmallJoker** [comment]
Looks good for me, but would you like to adjust the author email address to one which GitHub associates with your profile?

**Comment by mazocomp** [comment]
@SmallJoker, I can't, I only basically use git, after reinstalling the whole system I forgot to configure it.

**Comment by mazocomp** [comment]
Ok, quickly checking web interface gave me opportunity to link to my account...

**Comment by SmallJoker** [comment]
@mazocomp Here's how you could do this if configuring should be done later:
```sh
# Squash the two most recent commits, mark for commit
git reset --soft HEAD~2

# Commit changes, force author
git commit -m "TITLE MSG" --author "NAME <EM@IL.TLD>"
```

**Comment by mazocomp** [comment]
@SmallJoker Ok, thanks.

**Pull request merged**
