### PR TITLE
HOTFIX: Fix too agressive block culling

### PR DESCRIPTION
**Pull request by RealBadAngel**
screenshot_20160213_233554

### CODE REVIEW

**Comment by RealBadAngel** [comment]
Use slightly increased FOV angle in calculations ( +10%)

**Comment by est31** [comment]
Isn't this what `adjdist` etc calculation is used for? Or am I mistaken, or is the comment misleading?

**Comment by est31** [comment]
I mean this comment:

 	// Adjust camera position, for purposes of computing the angle,
 	// such that a block that has any portion visible with the
 	// current camera position will have the center visible at the
 	// adjusted postion

**Comment by RealBadAngel** [comment]
@est31 apparently its not enough

**Comment by est31** [comment]
Well, perhaps there's a bug hiding in that code...

so a fix there would be more proper. Other than that perhaps we can have a comment that states its only a hotfix for the issue.

**Comment by paramat** [comment]
What's weird is how this bug gets worse with distance, seemingly working well at close range.

**Comment by est31** [comment]
:+1: to the PR in its current form. If there is any change (if the commit appears below this message, not above), my :+1: is gone and I'll re-review.

**Comment by paramat** [comment]
Line 2223:
```
f32 block_max_radius = 0.866025403784 * MAP_BLOCKSIZE * BS;
```
I think this can be made a (static?) const. +1 when that's done.

**Comment by RealBadAngel** [comment]
@paramat thats not in focus of this PR, this is hotfix only for certain issue.

**Comment by paramat** [comment]
Ok :+1:

**Comment by Fixer-007** [comment]
Works for me, :+1:

**Comment by sofar** [comment]
Tested. No issues found.

**Comment by est31** [comment]
Merged as 1ec1a605d664b42a034cecb9f2e768fab3d738d4

**Pull request closed without merging**
