### PR TITLE
[no squash] Split touch controls from UI

### PR DESCRIPTION
**Pull request by okias**
- Goal of the PR

Prepare for touch screen autodetection.

- How does the PR work?

Split touchscreen controls from UI adjustment for touch screen devices.

- Does it resolve any reported issue?

No. But prepares ground for auto-detection of touch input, where changes in UI would be undesired.

- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?

Yes, it does improve touchscreen experience and clarity of the TS code.

- If not a bug fix, why is this PR needed? What usecases does it solve?

## How to test

Check the UI settings, check the touchscreen settings.

### CODE REVIEW

**Comment by okias** [comment]
Well, for UI, since Minetest has no TUI, UI implies always GUI. Anyway I'm ok with both.

**Comment by okias** [comment]
Tested latest changes, no regression spotted.

**Comment by grorp** [comment]
> Well, for UI, since Minetest has no TUI, UI implies always GUI. Anyway I'm ok with both.

There's one other (G)UI setting. That other setting is called `gui_scaling`, so we should use the term "GUI" for the new setting too to be consistent.

**Comment by okias** [comment]
Tested on the phone, works exactly as expected.

Next thing I'm wondering now, is the ability to ask system for landscape mode and lock (as minetest in portrait mode has a squashed not-much-usable controls.. and it probably doesn't make much sense to do it flexible that much).

**Comment by grorp** [comment]
> Next thing I'm wondering now, is the ability to ask system for landscape mode and lock (as minetest in portrait mode has a squashed not-much-usable controls.. and it probably doesn't make much sense to do it flexible that much).

Minetest on Android does that, how would we do it on Linux?

**Review by grorp — APPROVED** [review]
Looks good. Tested on Android. Needs squashing as mentioned above.

This is the first half of the changes from #14542. Thanks for splitting them into a separate PR.

I don't know what happened to the feature freeze and release plans btw ¯\\_(ツ)_/¯

**Comment by okias** [comment]
> > Next thing I'm wondering now, is the ability to ask system for landscape mode and lock (as minetest in portrait mode has a squashed not-much-usable controls.. and it probably doesn't make much sense to do it flexible that much).
> 
> Minetest on Android does that, how would we do it on Linux?

So far I've been told we would need new Wayland extension for that, which make sense. TBD for now.

**Comment by okias** [comment]
@sfan5 what do you think?

**Comment by grorp** [comment]
In case somebody is wondering "why do we need this?": It makes it possible to enable mouse/keyboard controls on your phone without menus becoming way too small. An example of what currently happens with `enable_touch = false` on my phone:

way too small mainmenu on Android

This PR would be reasonable to merge before 5.9.0.

**Comment by sfan5** [comment]
> @sfan5 what do you think?

Seems useful but haven't looked at the code closely.

**Comment by okias** [comment]
This needs a brief review and merge. It's a bit breaking over code-base changes, thou I just rebased.

**Comment by grorp** [comment]
After thinking about this again, my opinion is that this PR is necessary for 5.9.0. Otherwise Android users will get a broken experience when they set `enable_touch` to false. The other options would be hiding the setting for 5.9.0 or adding a warning, but why.

Consider this brokenness:

screenshot 1

screenshot 2

**Comment by sfan5** [comment]
> The other options would be hiding the setting for 5.9.0 or adding a warning, but why.

I would rather do that than risk bringing it new regressions just before a release.

**Comment by okias** [comment]
@sfan5 I think shipping it as it's could be good idea. If you disable GUI optimization for touchscreens, then well.. you'll get into troubles if you're on touchscreen.

Since except the checkbox, there is no functional changes, this should be pretty safe, right?

**Comment by sfan5** [comment]
We're never shipping 5.9 at this rate.

**Comment by grorp** [comment]
I would have worked on this two months ago if I hadn't thought we were "close to release" back then. But now, it looks like we're actually close to release (famous last words).

sfan5 was right about this kind of thing before, I guess he's right this time too.

**Comment by sfan5** [comment]
Needs a rebase.

**Comment by rubenwardy** [comment]
This breaks compatibility with the "enable_touch" setting. Given that it's been in a release, might be worth a simple migration

**Comment by grorp** [comment]
> This breaks compatibility with the "enable_touch" setting. Given that it's been in a release, might be worth a simple migration

Done in 8550c1c0d1bdae17b982c38b1d66c314c5da1d9c.

**Comment by SmallJoker** [comment]
Need to backport 1977517d7ab for 5.9.1 to not cause new issues caused by resolving merge conflicts.

**Pull request merged**
