### PR TITLE
Also show X11 icon if minetest is installed via make install

### PR DESCRIPTION
**Pull request by est31**
fix for #4323

**cc** @ShadowNinja @everamzah 

Needs testing.

### CODE REVIEW

**Comment by est31** [comment]
@everamzah can you test this PR whether it resolves the issue?

**Comment by everamzah** [comment]
minetest is still looking for icons in /usr/local/share/minetest/misc, but they are being installed to /usr/local/share/icons by make install.

**Comment by est31** [comment]
Do you have the warningstream output?

**Comment by everamzah** [comment]
```
2016-08-18 08:23:27: WARNING[Main]: Could not load icon file '/usr/local/share/minetest/misc/minetest-xorg-icon-128.png'
```

**Comment by est31** [comment]
@everamzah can you try again?

**Comment by everamzah** [comment]
Yep, it works!

**Comment by est31** [comment]
Nice, adding my own approval then.

**Comment by sfan5** [comment]
:+1:

**Pull request merged**
