### PR TITLE
Decouple liquid pointing from liquidtype

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR introduces a new node property called `liquid_raycast`. It takes one of 3 values:

* `true`: Node is considered to be a liquid for raycasting/pointing purposes. This means, RayCasts will consider this node to be a liquid, and items with `liquids_pointable=true`, too
* `false`: This is not the case
* `nil` (default). Automatic. If `liquidtype ~= "none"`, this is the same as `true`, otherwise `false`

This is a change from the current behavior. Currently, nodes are considered to be liquids for raycasting/pointing if `liquidtype ~= "none"`.

Note that the default value `nil` leads to exactly the current behavior, so existing nodes will not change in their behavior. This PR should be 100% backwards-compatible.

This PR will have the following benefits:

* You can now make liquid nodes that are not pointable at all (not even MTG buckets)
* You can now make nodes pointable by MTG buckets even if they don't have liquid flowing physics.

## Rationale

Basically, this PR is a part of my quest to decouple the various features of liquids into distinct, independent features. It is a contination of #10810.

I dislike the current behavior because it strongly couples the pointing behavior with liquid flow physics. E.g. setting `liquidtype` does two different things at once: 1) Enable liquid flowing physics and 2) change how raycasting/pointing works. Thus, `liquidtype` strongly couples two different things into one. This means that the two benefits I listed above are currently impossible, thus limiting flexibility.

## To do

This PR is Ready for Review.

## How to test

Test 1:
In DevTest, give yourselves `testnodes:fake_liquid_raycast` and place it. Point at this node with the hand. It should not be pointed. Point with it with the Liquids Pointer tool (`testtools:liquids_pointer`) or bucket. Now it should be pointed.

Test 2:
Give yourselves `testnodes:liquid_noraycast` and place it. It should be impossible to point it with any tool (both the source and flowing node), including the Liquids Pointer or Bucket.

Test 3:
Test if pointing still works as expected with the other nodes (both liquids and non-liquids).

Test 4:
Test with RayCast functions from Lua. (I did not do this myselves yet.)

### CODE REVIEW

**Comment by rubenwardy** [comment]
Thanks for the contribution! Unfortunately, this feature is not on the [roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md) and hasn't received a concept approval. Under the [new rules](https://github.com/minetest/minetest/blob/master/.github/CONTRIBUTING.md#code), non-roadmap non-bugfix PRs have 7 days to be concept approved, otherwise they should be closed.

If a core dev wants to support this PR, they may reopen it and apply the "Supported by core dev" label. In the future, you can open an issue first to get preapproval before working on something

**Comment by Wuzzy2** [comment]
:-(

How is "decoupling features that should have never been coupled in the first place" not on the roadmap? I wish that at least one person actually properly reviews this PR before murdering it.

**Comment by rubenwardy** [comment]
This feels like the wrong approach to me, and a weird API

Maybe it would be better to use groups, so the bucket would have a `pointable_at = { "group:liquid_pointable" }`. This feels less hardcoded and less specific. It's similar to collision groups / masks in other game engines

**Comment by Wuzzy2** [comment]
Sigh. Well, at least there is now a real reason for why this was rejected. That's at least something.

**Pull request closed without merging**
