### PR TITLE
Allow changing per-player FOV from Lua.

### PR DESCRIPTION
**Pull request by kaeza**

### CODE REVIEW

**Comment by bigfoot547** [comment]
It's a shame to have this code wasted. This is much needed.

**Comment by bigfoot547** [comment]
Dang. The feature freeze.

**Comment by Avamander** [comment]
So what's the status of this?

**Comment by sofar** [comment]
going to end up in CSM most likely.

**Comment by Avamander** [comment]
CSM?

**Comment by red-001** [comment]
**C**lient **S**ided **M**odding

**Comment by nerzhul** [comment]
See #5394

**Comment by Avamander** [comment]
Though as this is an API function, it would be weird if a client mod adds the feature.

**Comment by bigfoot547** [comment]
@kaeza Are you going to rework this PR?
I am very interested and want this merged.

**Pull request closed without merging**
