### PR TITLE
Camera: Don't count camera offset twice for Nametagged CAOs

### PR DESCRIPTION
**Pull request by RealBadAngel**

### CODE REVIEW

**Comment by nerzhul** [comment]
Okay for me. This cause a problem which set nametags on other places when players are far from 0,0,0 it's more noticeable

**Comment by rubenwardy** [comment]
`Camera: Don't count camera offset twice for Nametagged CAOs`?

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
5dbaa689677e89ee10e2c6e3a4e8eb57b79f3140

**Pull request closed without merging**
