### PR TITLE
Standardize the menu button order and sizes

### PR DESCRIPTION
**Pull request by SmallJoker**
Preview

### CODE REVIEW

**Comment by PilzAdam** [comment]
The look too far apart now. Maybe half the distance between them.

**Comment by SmallJoker** [comment]
You're right, the half width between the buttons looks much better.

**Comment by paramat** [comment]
Yes, buttons closer together looks better.

**Comment by kwolekr** [comment]
:+1:

**Comment by ShadowNinja** [comment]
:+1:

**Comment by kaadmy** [comment]
I like this.
+1

**Comment by MoNTE48** [comment]
:+1:

**Comment by SmallJoker** [comment]
Rebased.

**Comment by paramat** [comment]
Will merge soon.

**Comment by paramat** [comment]
30083d1e0070d0f86337a57ea36b6bba7fd52572

**Pull request closed without merging**
