### PR TITLE
C++11 patchset 6: forbid object copy using assigment/copy function delete

### PR DESCRIPTION
**Pull request by nerzhul**
C++11 implement function deleting, it's generally used to prevent some object copy
Remove DISABLE_CLASS_COPY (which needs to be private in C++03) and use proper C++11 copy/assignment function removal
In script API use this function removal on ScriptApiBase instead of ScriptApiClient/Server/MainMenu, this affect all ScriptApis

### CODE REVIEW

**Comment by SmallJoker** [comment]
At least for me it was easier to understand what `DISABLE_CLASS_COPY` does, instead of using the operator overloading "fix" directly.

**Comment by nerzhul** [comment]
it can be done i wasn't sure what is the best, then i can just change the macro and add the flag in the public part of the header, maybe with constructor to directly show copy is forbidden, C++11 permit to keep those function public, areyou okay with this ?

**Comment by Zeno-** [comment]
I preferred the macro as well mainly because it stood out

**Comment by nerzhul** [comment]
@Zeno- @SmallJoker i reintroduced it properly and move it with constructors

**Pull request merged**
