### PR TITLE
Confirm registration GUI: Remove positional strings to fix Windows bug

### LINKED ISSUE #7948: Player join confirmation shows incorrect formatted string
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-327bad2-327bad2-dirty (Windows)
```

##### OS / Hardware

Operating system: Windows 10

##### Summary
image

When using the daily development build from [nrz's daily Windows development builds](https://gitlab.com/minetest/minetest/pipelines), the join confirmation formspec does not show the server and player name as it should. Presumably the issue is from [here](https://github.com/minetest/minetest/blob/master/src/gui/guiConfirmRegistration.cpp#L97).

##### Steps to reproduce

Get one of nrz's daily Windows builds. Then try to join a server.

### PR DESCRIPTION
**Pull request by paramat**
Closes #7948 
@Fixer-007 @random-geek

### CODE REVIEW

**Comment by paramat** [comment]
This menu is disabled on localhost, so i added these changes to a version on MT just before the localhost change, and tested on a local server. Tests ok.

**Comment by srifqi** [comment]
Seems good. (Windows 10 64-bit)
screenshot

**Comment by paramat** [comment]
Removing from blockers.
IRC http://irc.minetest.net/minetest-dev/2019-02-19#i_5498408

> 19:36 sfan5      this issue does not affect the official windows builds

**Comment by SmallJoker** [comment]
This entirely defeats the purpose of `porting::mt_snprintf`. Is there no other solution for this issue?

**Comment by paramat** [comment]
The only solution is to fix `porting::mt_snprintf` for MinGW and msys2, but i doubt that will be done before release, so this at least removes some visual mess.

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-dev/2019-03-05#i_5505552

18:39 rubenwardy loads of people are getting the %1s$ or whatever confirmation dialog bug

So perhaps this can be merged for 5.0.1?

**Comment by pgimeno** [comment]
There are several other solutions.

One is to replace `%1$s` and `%2$s` with `%s`. That won't allow translators to change the order, but maybe that's fine.

Another one is something like this:

```c++
		static const std::string info_text_template = strgettext(
				"You are about to join the server at [SERVERNAME] with the "
				"name \"[USERNAME]\" for the first time. If you proceed, a "
				"new account using your credentials will be created "
				"on this server.\n"
				"You are about to join this server for the first time.\n"
				"If you proceed, a new account using your credentials "
				"will be created on this server.\n"
				"Please retype your password and click Register and "
				"Join to confirm account creation or click Cancel to "
				"Join to confirm account creation, or click Cancel to "
				"abort.");
		std::string::size_type pos = 0u;
		std::string find = "[SERVERNAME]";
		while ((pos = info_text_template.find(find, pos)) != std::string::npos) {
			str.replace(pos, find.length(), address);
			pos += address.length();
		}
		pos = 0u;
		find = "[USERNAME]";
		while ((pos = info_text_template.find(find, pos)) != std::string::npos) {
			str.replace(pos, find.length(), m_playername);
			pos += address.m_playername();
		}
```

**Comment by paramat** [comment]
Or use `%s` once and only alter username, i'd be ok with that, the server is obvious.
I'd prefer a simple low risk fix, this is going to be reworked anyway.

**Comment by pgimeno** [comment]
Hmm. From the manual of gettext:

>  On the few platforms where ‘printf()’, ‘fprintf()’ etc.  don’t support [the positional parameters] feature natively, ‘libintl.a’ or ‘libintl.so’ provides replacement functions, and GNU ‘<libintl.h>’ activates these replacement functions automatically.

I guess that needs `-DENABLE_GETTEXT=ON`? I wonder if the failing platforms had gettext off.

**Comment by paramat** [comment]
One problem though, this will change a translation string, so maybe just change these to non-positional `%s`. I can't see why the order needs changing, surely the text would then become nonsense?

**Comment by pgimeno** [comment]
The change to a translation string will happen either way, unless #8259 is fixed for good (or see below for an alternative, uglier fix).

For the translations of some texts, the English wording does not fit well within the grammar of the language, and needs to be rewritten in a way that sometimes changes the order of parameters. I don't know if it's the case here for some language; most probably it isn't. But the translators need to understand that they need two %s, that each means a different thing, which is not intuitive, and that order matters. It's much clearer with replacement variables similar to the example I posted (untested, BTW). I guess adding a parameter replacement function or just a plain string search and replacement function to the core would help.

An alternative (uglier) fix that doesn't change the translations is to use `%1$s` and `%2$s` as the text to search/replace in a scheme similar to the one I posted. Something along the lines of:

```c++
    static const std::string info_text_template = strgettext(
           "... (same text as before)");
    const std::string info_text = searchAndReplace(info_text_template, "%1$s", address);
    info_text = searchAndReplace(info_text, "%2$s", m_playername);
```

**Comment by sfan5** [comment]
IMO the server name should be removed and the username kept.

**Comment by pgimeno** [comment]
Works for me. I was offering an alternative that didn't involve a translatable string change.

While on it, please also consider a wording change to make it less verbose. I suggest:

> The account "%s" is not registered in this server. If you want to create the account, please confirm your password below.

And the form size can probably be reduced a bit.

**Comment by paramat** [comment]
Will update as requested by sfan5.

**Comment by paramat** [comment]
Updated but i need to test.

**Comment by paramat** [comment]
screenshot from 2019-03-08 10-54-27

I used a build from before confirmation was disabled on local host to test this code on a local server.
The client player's name was "client".

**Comment by paramat** [comment]
Sorry, this needs to be merged to 5.0.1 too, please can someone do that?

**Pull request merged**
