### PR TITLE
Mgvalleys: Add Dry Riverbeds

### PR DESCRIPTION
**Pull request by duane-r**
Lower water table where base humidity is low. ~~Add a pivot in the
humidity calculation and~~ compress the scale of the humidity noise when
humid_rivers is selected to reduce the chance of jungle trees showing up
too often. Correct misuse of surface_max_y in generateTerrain. Make
humidity calculations more readable.

Lowering the water table gradually produces dry riverbeds in deserts and dry plains.

Compressing the scale by 0.8 seems to produce the closest match to the  spread of the original humidity noise. Rivers always raise humidity by a factor of between 1 and 1.5+ when humid_rivers is set (1/1.25 = 0.8). However, the actual numbers vary widely depending on how many rivers are present. I tried to match the interquartile range of the humidity data with and without humid_rivers set.

~~Between the compression and the pivot forcing river humidity down instead of up, the average humidity goes down significantly, but this only tends to affect the tops of mountains, which is true to the intention of the original code. Jungles tend to be less common and more cohesive than after commit [80c7612e](https://github.com/minetest/minetest/commit/80c7612e76ca83fa69a6e709213026478edfe5ab), but jungle trees still show up in odd places sometimes.~~

example

### CODE REVIEW

**Comment by est31** [comment]
That looks great

**Comment by duane-r** [comment]
Whoops! Just spotted a serious flaw in my algorithm. The pivot is reversing the river humidity. Let me see if I can work around that.

**Comment by duane-r** [comment]
Ok, the pivot is out. I'll have to work on another fix for the jungle trees later.

**Comment by C1ffisme** [comment]
:+1:

**Comment by duane-r** [comment]
My apologies. Removing the pivot table seems to have triggered a slew of other issues. I'll put some more work in on this and resubmit.

**Pull request closed without merging**
