### PR TITLE
Rename doc/*.txt to *.md.

### PR DESCRIPTION
**Pull request by ensonic**
This selects appropriate highlighting in editors and makes the docs easier
to read on github.

### CODE REVIEW

**Comment by ensonic** [comment]
The toplevel README.txt is already handled in https://github.com/minetest/minetest/pull/5378

**Comment by SmallJoker** [comment]
Looks somewhat beautiful right now: https://github.com/ensonic/minetest/blob/2a03200/doc/world_format.md
This will need some work to convert everything to proper markdown.

**Comment by ensonic** [comment]
@SmallJoker I am happy to fix the markdown. Do you want me to do it in this PR or are subsequent PRs for each file okay.

**Comment by SmallJoker** [comment]
@ensonic I think this can be done in this PR. But it would be nice to have a seperate commit for each file.

**Comment by ensonic** [comment]
I'll extract world_edit from this PR since that is not yet converted.

**Comment by rubenwardy** [comment]
I think it is fine to rename these. It wasn't done before as it would break links - however, links are already broken when we add or remove content, as that shifts things around.

**Comment by ensonic** [comment]
I've split the PR into separate commits per file and reverted the renamed for those that aren't good markdown. I'll convert those as separate PRs. Thanks for the quick review!

**Comment by SmallJoker** [comment]
1) `menu_lua_api.txt` isn't proper Markdown either
2) The Lua API file is linked from many different locations, renaming it would break all links, so it might be better to keep this untouched

Basically the same problem for renaming the other files but in contrast they're not that important.

**Comment by ensonic** [comment]
@SmallJoker according to
```
find . -type f -exec grep -Hn "lua_api.txt" {} \;
```
all links have been updated.

**Comment by SmallJoker** [comment]
@ensonic Talking about links like those:
[Minetest Dev Wiki](http://dev.minetest.net/index.php?search=lua_api.txt&title=Special%3ASearch)
[Forum search result](https://forum.minetest.net/search.php?keywords=%2Blua_api.txt&terms=all&author=&fid%5B%5D=3&fid%5B%5D=5&fid%5B%5D=6&fid%5B%5D=47&sc=1&sf=all&sr=posts&sk=t&sd=d&st=0&ch=300&t=0&submit=Search)
These won't and can't be updated. If there's no way to add an alias for `lua_api.txt` this will be very annoying to navigate to the new file over and over again.

**Comment by DS-Minetest** [comment]
Well, it could look like http://rubenwardy.com/minetest_modding_book/lua_api.html .
And static links to headlines would be possible: https://github.com/minetest/minetest/blob/master/doc/client_lua_api.md#screenshotpng
Would it be a big problem just to copy always the file and rename it and so have both? I think the answer is yes.

**Comment by ensonic** [comment]
I can certainly re-add a .txt version and point people to the markdown version. Alternatively, did anyone tried to add the docs to the source and use a tool like ldoc to extract them?

**Comment by paramat** [comment]
:-1: These docs need to stay as .txt files for quick and easy opening anywhere without requiring MD.
Devs are used to how they appear in .txt format, MD format is irritatingly over-pretty..

**Comment by rubenwardy** [comment]
>  for quick and easy opening anywhere without requiring MD.

They're just text files. You open them the same way as a text file, no need for a different program

> I am used to how they appear in .txt format, MD format is irritatingly over-pretty.

FTFY

> These docs are not easier to reference on Github in MD display.

You can link to a section, which means that the link will pretty much always be maintained. However, you can't link to a specific bullet point which is a problem :/

**Comment by paramat** [comment]
Ok, still opposed for other reasons, this change would drive me insane, i've only just acclimatised to the change of lua_api.txt to MD formatting, it was changed when i had only just got used to it in normal formatting.

**Comment by paramat** [comment]
MD display makes everything too spaced out and decorated, instead of concise blocks of text, it takes much more scrolling to navigate.

**Comment by ensonic** [comment]
So what about putting the docs into the code and using a documentation generator? Personally I find that this would help to keep things up to date.

**Comment by DraggonFantasy** [comment]
I also like the idea of documentation generator, because it makes easier to add auto-completion to Lua editors.

For example, I've created a Vim plugin, that extracts API info from .txt files and adds Minetest API auto-completion. But the format of API description in .txt files is pretty arbitrary, so the plugin fails to "find" some functions.  
With documentation generator this problem is solved, because it's format is much more strict and (probably) easier to parse

**Comment by paramat** [comment]
> putting the docs into the code and using a documentation generator? Personally I find that this would help to keep things up to date.

Why? What's wrong with the current situation where those who prefer a MD display can open a txt. file in MD display. Most people refer to these docs in txt. form and are used to them in txt. form.
A txt. form is the most basic form possible and therefore the most flexible and universal.
This is just extra unnecessary work for us. Celeron55 has always insisted that these docs remain as txt. files.
How would this keep things up to date? We already keep lua_api.txt up to date on every PR merged.
:-1:

**Comment by nerzhul** [comment]
i'm okay with MD as many users will use github to read docs, and markdown syntax is easily readable, but please finish the PR

**Comment by paramat** [comment]
As far as i know the MD formatting needs a lot of work in those files first.

**Comment by paramat** [comment]
Please can we at least keep a copy in .txt form too for each doc?

**Comment by paramat** [comment]
Ok if the display on Github can include a table of contents that links to sections (as at rubenwardys site) that would be useful indeed to find stuff. I just request there is a .txt version too present in the repo.

**Comment by paramat** [comment]
Discussion http://irc.minetest.net/minetest-dev/2017-03-26#i_4840360

**Comment by paramat** [comment]
It's very useful to visit lua_api.txt and click the line number to generate a link to that line, we do this very often to link to single lines:
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2869
This cannot be done with a MD file.
So it is essential to at least keep the .txt version.

**Comment by nerzhul** [comment]
Sorry to said that paramat but MD permit to link lines, add metadata (like external links), add anchors and more. Look at this README.md https://github.com/Icinga/puppet-icinga2

**Comment by ensonic** [comment]
@paramat linking to a line number won't be a stable link. But for discussion (if the link is git-hash + line number) you can do the same. Having both xxx.txt and xxx.md sound like this will be double work to keep up-to-date. I have not found a definite answer to what git would do with a symlink, but it is probbaly not a good idea.

I mostly started this PR, since I noticed that lua_api.txt has been formatted and I found it nicer to read on github, if the markdown is rendered instead of been shown verbatim. I don't mind if you ask me to delete this PR, but be prepared that more people wast time to migrate stuff ...

Again, consider a doc tool. That gives you lots of benefits like consistent formatting of the docs, all kinds of indices, reports about doc coverage, etc. Right now as someone new to write mods, I find it hard to find the right API for the job.

**Comment by paramat** [comment]
> linking to a line number won't be a stable link.

Yes i know, but it's ok for a temporary referral, which we do a lot on IRC "see line ...".

> Sorry to said that paramat but MD permit to link lines,

You can't link to an individual line, as stated above individual bullet points cannot be linked to, you can only link to sections.

I agree having 2 docs would duplicate updating effort so that's not a good idea.

I agree having a fully linked version is useful but we already have Rubenwardy's site for that, and it's easy for anyone to open their copy of a doc in MD display locally or download the .txt doc and open locally.

So sorry but i am strongly opposed to any change :-1:

**Comment by paramat** [comment]
Since you're interested, would you be interested in improving the MD formating of lua_api.txt so that it has a table of contents that link to each section?

**Comment by red-001** [comment]
It's possible to link to markdown files if you don't mind them only being displayed as a text file.
https://github.com/minetest/minetest/blame/master/doc/client_lua_api.md#L9

**Comment by ensonic** [comment]
I'll delete my PR and let you guys figure how you want your docs to be.

**Comment by nerzhul** [comment]
hmm you are a little bit rude, why not improve your PR instead of closing it ?

**Comment by ensonic** [comment]
Sorry, but there was not clear suggestion for what I am supposed to do except "no markdown" please. I still have the changes. But really, please figure how you want your docs to be done and then I am happy to help. The intention of this PR was that the markdown gets rendered as markdown on github, improving the existing markdown would be a different PR.

**Comment by nerzhul** [comment]
i'm also in favor of standard markdown readable by GH, Gitlab or markdown readers

**Comment by paramat** [comment]
Whatever we decide, a well-MD-formatted lua_api.txt with contents linking to sections will be very helpful if you are interested.

**Comment by rubenwardy** [comment]
> with contents linking to sections will be very helpful if you are interested

This really should be handled by the viewing software (eg: Github) not us :/

**Comment by paramat** [comment]
> This really should be handled by the viewing software

Is MD not capable of creating a table of contents that link to sections? I mean like https://github.com/minetest/minetest/blob/master/CONTRIBUTING.md

**Comment by paramat** [comment]
Nerzhul why is client_lua_api.md a MD file? Although i can link to a section i can't link to a line in a large section so this makes it hard to use as a reference.
Please can we change it to a .txt file?

**Comment by nerzhul** [comment]
it's a MD because it was a consensus between CSM and end users. Can you give is a concret example for your link issue ?

**Comment by paramat** [comment]
But MD is inconsistent with the corresonding lua_api.txt file. Whichever form we choose it should be consistent. Also, all other docs on /doc are .txt. This should never have been MD to start with.

It's obvious, but, let's say i am on IRC and want to refer someone to minetest.decompress().
With .txt i click the line, copy URL and post it in IRC, done.
With MD i copy the URL of the section, post it and then have to write "search down for 'minetest.decompress()'", the person then has to search for it. Less convenient for both people.
These sections can get big, just look at lua_api.txt.

**Comment by sofar** [comment]
at work we've actually gone to `rst` format. The conversion is not easy, but github renders rst reasonably well, and rst2(man, html, etc) tools are widely available. 

Sadly, I'm not a fan of the .md extension. The file looks better without github markdown reading, but links and indices are broken.

**Comment by Fixer-007** [comment]
Installed/shipped/compiled minetest should have *.txt versions in distribution

**Comment by ShadowNinja** [comment]
We discussed this in the Minetest developer meeting and were generally positive, but:
  * The Windows build should install `.txt` versions instead of `.md` versions so that Windows users can easily read them.
  * A dummy file could be left in place of `lua_api.txt` pointing them to the new file.

**Comment by paramat** [comment]
> We discussed this in the Minetest developer meeting and were generally positive

I wasn't :)

**Comment by nerzhul** [comment]
generally != all :D

**Comment by rubenwardy** [comment]
:-1:

We need to improve the format of the file to make the subheadings better first, before renaming to .md

**Comment by paramat** [comment]
Never .md, see #6707 for reasons. Such files are impossible to work with on Github.
MD formatting is fine in docs, so that people have the option to open it as MD, but the file has to be .txt.
Exceptions are README and CONTRIBUTING, maybe ICENCE too, since these are not technical docs worked with a lot by devs.

**Pull request closed without merging**
