### PR TITLE
Mainmenu: Improve "Join Game" tab

### PR DESCRIPTION
**Pull request by sfan5**
adopted #9505, thanks to @appgurueu for the initial work

differences to old menu:
* categories "favorites", "public servers", "incompatible servers" instead of star indicator on every row
* changed player count view
* take lag+ping into account for bar indicator
* merge pvp & heart icon columns (pvp takes priority)
* small layout changes, visually differentiated right side using a background

differences to 9505:
* both the list and the right side were made 1 unit bigger (it's pretty much the same size as all main tabs now)
* search/clear/refresh weren't reordered
* made text fields on the right bigger to match all others 

## Screenshots

<b>Before</b>:
crop1

<b>After</b>:
crop2

## To do

This PR is Ready for Review.

However I'd appreciate advice on the following points
- [x] better icon for "Public Servers"

### CODE REVIEW

**Comment by GreenXenith** [comment]
>  better icon for "Public Servers"

Many applications use the 🌐 icon to represent "web"/"internet"/"public".
Alternatively, 👥 or 📢.

**Comment by Wuzzy2** [comment]
I like the new layouting!

Bugs:
* If you click on a favourite server, then on the word "Public Servers", the button "Delete favourite" is still there and if you click it, ERROR
* If you delete a favourite, the button “Delete favourite” always disappears, even if the new selected entry is also a favourite server

**Comment by Wuzzy2** [comment]
Also, there is apparently no way to favourite a server anymore? Previously, all servers that you visit automatically become favourite, but this no longer happens. And there is also no button to add to favourite list, meaning it seems to be impossible to add anything to favourites.

**Comment by sfan5** [comment]
No those are all bugs, they're fixed now. "Visit server -> becomes favorites" worked/works for me however.

**Comment by Wuzzy2** [comment]
OK, the crashes are gone. The button “Delete favourite” is still visible when the line “Favourites” or “Public Servers” is selected. Granted, the button no longer crashes, but I think the button should be removed altogether when one of those special lines is selected, as the existence of this button does not make sense in this situation.

Apart from that, I think it is OK.

**Comment by nerzhul** [comment]
i like the changes :)

**Review by nerzhul — APPROVED** [review]

**Comment by SmallJoker** [comment]
main menu address vs port proportions
I think the port field deserves a little more space. This is at GUI scaling `0.9`, and (almost) 1080p window.

**Review by SmallJoker — APPROVED** [review]
LGTM. I cannot decide on the background color but the field proportions are better now.

**Comment by kilbith** [comment]
Man, this is really bad UI. Everything looks crammed now. :vomiting_face:

**Comment by sfan5** [comment]
You mean the search box / buttons / table? The rest of the menu looks pretty much the same.

**Pull request merged**
