### PR TITLE
Allow to set shader for a node, add special and normal texture defs f…

### PR DESCRIPTION
**Pull request by RealBadAngel**
…or a tile
Remove hardcoding water surface shader

### CODE REVIEW

**Comment by est31** [comment]
In which way is this different from #3391 ?

**Comment by RealBadAngel** [comment]
@est31 Ive removed forcing filters

**Comment by paramat** [comment]
I don't think i can +1 this, it adds 'normal texture' which we don't use anymore. Also it's preparation for your new water shaders, which we're not sure about. I think the removeal of new style water and waving water has to be something seperate, so that temporarily we have no water shader, while we discuss its replacement.

**Comment by paramat** [comment]
I don't much understand this yet, but what concerns me currently is the addition of 'normal_texture', this suggests a direction of requiriing difficult to create normalmap textures, someting that is now refused in MTGame and should be refused for other subgames too. However it is possible with further explanation of this PR that i have got the wrong impression.

This PR shouldn't be presented as being necessary for the removal of waving water, that should be seperate and done first.

**Comment by rubenwardy** [comment]
> someting that is now refused in MTGame and should be refused for other subgames too

Seriously? You're trying to dictate the graphical style of other third party subgames now?

**Comment by C1ffisme** [comment]
@rubenwardy 

> should be

I think this is just a suggestion. As in, subgames should probably give up on using this. Mostly so that one subgame doesn't have flat textures, while another has big thick textures on each block. But that is an opinion. A subgame's direction has the direction of it's owner(s).

**Comment by paramat** [comment]
That's my opinion, and is in line with celeron55's roadmap which asks that the visuals for new nodes are easy to make (ie with Gimp), that applies to all subgmaes not just MTGame. RBAs full plan for MTHD is that every node has 3+ sets of textures, i'm concerned (perhaps wrongly) this PR is part of that.

**Comment by est31** [comment]
Well they are easy to make, nevertheless the engine should also have support for improved visual appearance. Its the same for meshnodes with custom models. They require additional work as well, people who want to do something quick and simple can do nodeboxes or that ugly plantlike thing.

So I fully agree with @rubenwardy here.

Either way, the PR has a :-1: from me as well, out of other reasons though.

**Comment by paramat** [comment]
Sorry, my comments went a bit too far, was in a bad mood, removed.
Since we currently have the ability to create normalmaps for nodes that should of course be supported, even if MTGame doesn't use them.

**Comment by MirceaKitsune** [comment]
Just a heads up: As most of you probably know by now, RealBadAngel died yesterday due to complications after his heart attack two weeks ago. RIP, you did some amazing things for Minetest!

Back on the topic of the pull request: If someone wishes the code to be finished, we will need new developers to work on it. I spoke frequently with RealBadAngel in PM about his new shaders, but never looked at the actual code and can't say I know it. Both for the project but also in his memory, I'm hoping that someone else will finish what he started and get this merged into core, once the feature is in an acceptable form.

**Comment by paramat** [comment]
This is part of a cleanup involving removing waving water, see #3759

**Comment by est31** [comment]
Ermm @paramat it has nothing to do with it. This change doesn't anything we need imo.

**Comment by paramat** [comment]
Okay, i guess i meant "according to RBA", see discussion iin #3759

**Comment by Ferk** [comment]
This PR does remove hardcoded water shader, check out [this line]( https://github.com/minetest/minetest/pull/3616/files#diff-70868aa6d6b96c0c1623c761500d23c4L941).

It also allows space for a better replacement, since it allows to define the shaders per-node (no security concern, @est31, since it doesn't send them over the network, I'm not sure of the reasons for your :-1:). It avoids any more hardcoded shaders by letting the games (or mods) decide what shaders they want, if they want them.

**Comment by paramat** [comment]
Would anyone like to take this over in a new PR? then we can close this.

**Comment by paramat** [comment]
:-1: This is for normalmaps and for what was to be future work by RBA, so i feel if some of this is needed it should be completely rethought and reworked.

**Comment by paramat** [comment]
Closing because unpopular and for my reasons above.

**Pull request closed without merging**
