### PR TITLE
Fix strange behavior when dragging&dropping from MTG creative inventory 

### LINKED ISSUE #13961: Strange behavior when dragging&dropping from MTG creative inventory (since #13146)
##### Minetest version

Probably all versions since 252c79d53a10a28d08cb46d45a39ba9fd6343ed0 (#13146)

```
Minetest 5.8.0-dev-252c79d53a (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Fedora Linux 37 (Workstation Edition)

##### Summary

> I found the following issue that might be worth having a look into:
> 
> 1. Use the MTG infinite source creative inventory
> 2. Drag & drop an ItemStack from the creative inventory onto another ItemStack of identical types
> 3. The ItemStack count combines but the dragged ItemStack is not released
> 4. When tapping again into any other empty or ItemStack of identical types, another copy is taken from the creative inventory.
> Expected: release the dragged ItemStack when releasing the finger press.

_Originally posted by @SmallJoker in https://github.com/minetest/minetest/issues/13872#issuecomment-1784080329_

This happens on desktop as well and seems to be a regression from 252c79d53a10a28d08cb46d45a39ba9fd6343ed0. On the previous commit (23f7aab354f52fa67578cf8ebbbf7fa06da1068e), it works correctly.

##### Steps to reproduce

See the quote from SmallJoker above.

### PR DESCRIPTION
**Pull request by sfence**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
Fix #13961
- How does the PR work?
Update inventory in case move is not allowed and update `m_selected_amount`
- Does it resolve any reported issue?
#13961
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?

## To do

Ready for Review.

## How to test

See #13961

### CODE REVIEW

**Comment by sfence** [comment]
Is it safe to remove lines:
```
	// Don't update when dragging an item
	//if (m_selected_item && (m_selected_dragging || m_left_dragging))
	//	return;
```
https://github.com/sfence/minetest/blob/297434ca80ba7ea94fd9286a537c0584d4c6a69a/src/gui/guiFormSpecMenu.cpp#L3802-L3804
?

I am not able to judge if it can cause any problems in other situations.

**Comment by grorp** [comment]
I haven't (yet?) looked or tested closely, but I've already found a bug: Your changes cause crashes when using the "left-drag to distribute evenly" feature introduced by #13146.

SIGSEGV

```
#0  InventoryList::changeItem (this=0x0, i=2, newitem=...)
    at /mt/src/inventory.cpp:600
#1  0x000000000058d954 in GUIFormSpecMenu::OnEvent (this=0x33ff690, event=...)
    at /mt/src/gui/guiFormSpecMenu.cpp:4740
#2  0x00000000008b05e7 in irr::gui::CGUIEnvironment::postEventFromUser (this=0xebc9e0, event=...)
    at /mt/irr/src/CGUIEnvironment.cpp:533
#3  0x00000000008ada76 in irr::CIrrDeviceStub::postEventFromUser (this=0xb0cb70, event=...)
    at /mt/irr/src/CIrrDeviceStub.cpp:168
#4  0x00000000008aa088 in irr::CIrrDeviceSDL::run (this=0xb0cb70)
    at /mt/irr/src/CIrrDeviceSDL.cpp:857
#5  0x000000000047c380 in RenderingEngine::run (this=<optimized out>)
    at /mt/src/client/renderingengine.h:152
#6  Game::run (this=this@entry=0x7fffffffd018) at /mt/src/client/game.cpp:1159
#7  0x000000000048d5c5 in the_game (kill=0xac3540 <porting::g_killed>, input=0x14b8b80, rendering_engine=0xbe06e0, 
    start_data=..., error_message="", chat_backend=..., reconnect_requested=<optimized out>)
    at /mt/src/client/game.cpp:4566
#8  0x000000000043cfda in ClientLauncher::run (this=0x7fffffffd6a0, start_data=..., cmd_args=...)
    at /mt/src/client/clientlauncher.cpp:209
#9  0x00000000007dfe13 in main (argc=1, argv=0x7fffffffde68) at /mt/src/main.cpp:263
```

**Comment by sfence** [comment]
@grorp 
Caused by the mentioned commented lines.

I use more complex condition. I do not see SIGSEG now.

**Comment by appgurueu** [comment]
(Ignore the linked PR, that was probably a typo.)

This doesn't seem to fix the issue in its current state (https://github.com/minetest/minetest/pull/14656/commits/7d8361b8433dc9419369ceb4cb6ac4366254ed9e): If I hold down the left mouse button (drag), there's still the strange behavior.

[Video](https://github.com/minetest/minetest/assets/34514239/f2954c71-949b-46e0-9ee3-a47ae35cb9c1)

Am I missing something?

**Comment by sfence** [comment]
@appgurueu Looks like a special situation. I did not test it with one item in the inventory.

**Comment by sfence** [comment]
@appgurueu Video situation should be fixed now.

Works also with pickup and `left_dragging` items.

I suggest testing with all inventory features which cams with #13146.

**Comment by sfence** [comment]
It looks like this solution breaks picking up from the chest. I have to analyze it.

**Comment by sfence** [comment]
See https://github.com/minetest/minetest/issues/13961#issuecomment-2189540478

**Comment by sfence** [comment]
Original problem described in #13961 should fixed, I see no SIGSEG.

The question is if the observation from https://github.com/minetest/minetest/issues/13961#issuecomment-2189540478 should be also somehow fixed.

**Comment by grorp** [comment]
Crashed again when I tried to test it...

https://github.com/minetest/minetest/assets/82708541/6e1f030c-2437-49f2-86a5-404f074aa7ab

```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000000000715589 in InventoryLocation::operator== (this=0x3fb92c0, other=...)
    at /mt/src/inventorymanager.h:75
75			if(type != other.type)

(gdb) bt

#0  0x0000000000715589 in InventoryLocation::operator== (this=0x3fb92c0, other=...)
    at /mt/src/inventorymanager.h:75
#1  GUIInventoryList::ItemSpec::operator== (this=0x3fb92c0, other=...)
    at /mt/src/gui/guiInventoryList.h:48
#2  0x0000000000707faf in GUIFormSpecMenu::OnEvent (this=0x3eb9290, event=...)
    at /mt/src/gui/guiFormSpecMenu.cpp:4523
#3  0x0000000000bad039 in irr::gui::CGUIEnvironment::postEventFromUser (this=0x133be20, event=...)
    at /mt/irr/src/CGUIEnvironment.cpp:533
#4  0x0000000000ba8b02 in irr::CIrrDeviceStub::postEventFromUser (this=0x11f7150, event=...)
    at /mt/irr/src/CIrrDeviceStub.cpp:168
#5  0x0000000000ba13dc in irr::CIrrDeviceSDL::run (this=0x11f7150)
    at /mt/irr/src/CIrrDeviceSDL.cpp:823
#6  0x0000000000562ba1 in RenderingEngine::run (this=<optimized out>)
    at /mt/src/client/renderingengine.h:154
#7  Game::run (this=this@entry=0x7fffffffcca0) at /mt/src/client/game.cpp:1170
#8  0x0000000000563f48 in the_game
    (kill=kill@entry=0xe8db48 <porting::g_killed>, input=0x179ade0, rendering_engine=0xfa9f00, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffd01f) at /mt/src/client/game.cpp:4580
#9  0x00000000004f20cf in ClientLauncher::run (this=this@entry=0x7fffffffd840, start_data=..., cmd_args=...)
    at /mt/src/client/clientlauncher.cpp:214
#10 0x00000000004c086d in main (argc=<optimized out>, argv=<optimized out>) at /mt/src/main.cpp:264
```

And another one, this time in MTG:

https://github.com/minetest/minetest/assets/82708541/8ebef4f9-0c13-48a0-89be-310f1c8fa302

```
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
InventoryList::changeItem (this=this@entry=0x0, i=6, newitem=...) at /mt/src/inventory.cpp:600
600		if(i >= m_items.size())

(gdb) bt

#0  InventoryList::changeItem (this=this@entry=0x0, i=6, newitem=...) at /mt/src/inventory.cpp:600
#1  0x00000000007074a6 in GUIFormSpecMenu::OnEvent (this=0x3d68c90, event=...)
    at /mt/src/gui/guiFormSpecMenu.cpp:4741
#2  0x0000000000bad039 in irr::gui::CGUIEnvironment::postEventFromUser (this=0x1409fc0, event=...)
    at /mt/irr/src/CGUIEnvironment.cpp:533
#3  0x0000000000ba8b02 in irr::CIrrDeviceStub::postEventFromUser (this=0x11f73f0, event=...)
    at /mt/irr/src/CIrrDeviceStub.cpp:168
#4  0x0000000000ba1286 in irr::CIrrDeviceSDL::run (this=0x11f73f0)
    at /mt/irr/src/CIrrDeviceSDL.cpp:723
#5  0x0000000000562ba1 in RenderingEngine::run (this=<optimized out>)
    at /mt/src/client/renderingengine.h:154
#6  Game::run (this=this@entry=0x7fffffffcca0) at /mt/src/client/game.cpp:1170
#7  0x0000000000563f48 in the_game
    (kill=kill@entry=0xe8db48 <porting::g_killed>, input=0x179fc40, rendering_engine=0xfab580, start_data=..., error_message="", chat_backend=..., reconnect_requested=0x7fffffffd01f) at /mt/src/client/game.cpp:4580
#8  0x00000000004f20cf in ClientLauncher::run (this=this@entry=0x7fffffffd840, start_data=..., cmd_args=...)
    at /mt/src/client/clientlauncher.cpp:214
#9  0x00000000004c086d in main (argc=<optimized out>, argv=<optimized out>) at /mt/src/main.cpp:264
```

**Comment by sfence** [comment]
I see the crashes.
I still have not found a good fix.

**Comment by nininik0** [comment]
This should be enable-able, as I find this useful on Android, we can't just hold shift and tap items to get many from a chest of everything, and i usually do this to get a certain item amount without lag delay when i have to tap the item from the chest, then tap my inventory, doing this a lot in fast intervals causes a insane lag delay. However when using this weird inventory behavior, it does not lag and is actually useful to me and other Android players.

**Comment by Zughy** [comment]
@sfence any update?

**Comment by sfence** [comment]
No update. I will close it because #14832 looks to be active.

**Pull request closed without merging**
