### PR TITLE
Add keep_newlines argument to wrap_text

### PR DESCRIPTION
**Pull request by theFox6**
If keep_newlines is true, every new line given in the input text is also contained in the output text.

### CODE REVIEW

**Comment by theFox6** [comment]
Well this looks more clean than #7232

**Comment by theFox6** [comment]
Can be added please?

**Comment by SmallJoker** [comment]
Testing mod:
```Lua
local texts = {
--                                               | 50 is here
[[

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy]],

[[eirmod tempor invidunt ut labore et dolore
magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo
dolores et ea rebum. Stet clita]]
}

print("core.line_break(text, 50)")
for i, text in ipairs(texts) do
	local lines = core.line_break(text, 50)
	print("\t" .. table.concat(lines, "\n\t"))
	print("")
end
print("core.wrap_text(text, 50, true, newlines)")
for i, text in ipairs(texts) do
	local lines = core.wrap_text(text, 50, true, true)
	print("\t" .. table.concat(lines, "\t")) -- new lines contained
	print("")
end

print("core.wrap_text(text, 50, true, no newlines)")
for i, text in ipairs(texts) do
	local lines = core.wrap_text(text, 50, true, false)
	print("\t" .. table.concat(lines, "\n\t"))
	print("")
end
```

But it does not contain new lines? This is the output:
```
core.wrap_text(text, 50, true, newlines)
		Lorem ipsum dolor sit amet, consetetur sadipscing	elitr, sed diam nonumy	

	eirmod tempor invidunt ut labore et dolore		magna aliquyam erat, sed diam voluptua. At vero	eos et accusam et justo duo		dolores et ea rebum. Stet clita	

```

**Comment by theFox6** [comment]
The previously contained newlines were converted into table splits, I've added a note for that to the documentation. I can change the behavior so it wraps into table lines and puts the newlines in as characters if you want that.

**Comment by rubenwardy** [comment]
It would be great to have some unit tests for this, see the `tests` folders in builtin

**Comment by SmallJoker** [comment]
https://irc.minetest.net/minetest-dev/2022-07-03#i_5990806

Concept approved.

**Comment by Zughy** [comment]
Hello @theFox6 , sorry for the delay. Now that the PR has been conceptually approved, do you think you can take care of the rebase?

**Pull request closed without merging**
