### PR TITLE
Fix code-style in src/client/

### PR DESCRIPTION
**Pull request by ClobberXD**
- Fixes all aspects of code-style that the LINTER cares about.
- Removes corresponding clang-format whitelist entries.

### CODE REVIEW

**Comment by rubenwardy** [comment]
This is a bad idea for the same reason as the other PR - it breaks other PRs and forks

**Comment by ClobberXD** [comment]
Indeed. I'd really like to fix code-style once and for all, but due to the massive number of merge conflicts that it'll give rise to, I thought I'd fix it one sub-dir by one. I guess `src/client` is still a lot. :/

Can I safely work on smaller and/or less frequently touched sub-dirs of `src/`? e.g.
- `client/render`
- `client/mapgen`
- `threading`
- `util`
- `content`
- `server`
- `irrlicht_changes` (Far from small, but the least touched)

**Comment by paramat** [comment]
> Fixes all aspects of code-style that the LINTER cares about.

This is a very bad idea. Maybe you don't know yet, but much, or even most, of what the linter complains about is perfectly fine code, it simply can't cope with MT's codestyle or the many ways of making code more readable.

What the linter complains about is only a guide to finding possible codestyle issues, what it complains about is absolutely not a reliable list of what's wrong with codestyle.
Changing a file so that the linter no longer complains will mean a few good fixes, but overall the code will be in a worse state than before, and less readable.
Codestyle should be improved according to MT codestyle rules, not by what the linter reports.

This is what was so wrong with Krock suggesting in IRC that files should be changed such that they can be removed from the whitelist.
What was suggested, and what you have done, has the same problems as expressed by SmallJoker:
> Whereas this would be a nice improvement; it will surely result in a few PRs which need rebasing. The code should rather be updated gradually.

'Gradually' is not a directory at a time, so SmallJoker is somewhat contradicting themselves.

This is still far too big to review, that should be obvious. For codestyle cleanups i suggest one file at a time, not a directory at a time. A whole file of codestyle improvements is more than enough to review in one go.

We're already adding mess to the code with all the 'clang format on/off' lines (which i think are a mistake), we must avoid making a mess of MT code just to align with a bad linter. Good codestyle is more important than aligning to a bad linter. Maybe the linter can be improved or we can use a better one, if so.

The linter is only there to suggest improvements. Any automated codestyle check can never be intelligent enough to cope with human judgement used to make code readable, so most files can never be removed from the whitelist. This is why 75% of files are on the whitelist.

There are already 3 issues about the linter problems, see #8467 #6034 #6766
In my issue you can see how ridiculous the linter is, it drops a bomb on mapgen files.

:-1: very strongly opposed. This will make code less readable and waste a huge amount of human-judged code readability decisions.

Please, before making big PRs, discuss with more than one core dev. You seem to be hyperactive (which is good) but without careful consideration first, and without enough common sense.

**Comment by ClobberXD** [comment]
Fair points.

> For codestyle cleanups i suggest one file at a time, not a directory at a time.

I was thinking of a similar approach too. From IRC:

> <ANAND> How about fixing code-style of only the touched files of the PRs I make?
> <+sfan5> that makes them hard to review
> <ANAND> Hard to review if I squash all the changes into a single commit. What if the code-style commit is separate from the PR's main commit?

**Comment by paramat** [comment]
Yes, a commit that combines codestyle changes with something else is very difficult to review.
However, having the codestyle changes in a separate commit, or a follow-up PR is fine.

If a codestyle commit is included in a PR, it's best it comes after the non-codestyle commit, because then the non-codestyle commit is changes acting on code people are used to, which makes it easier to review.

However, a bugfix/feature PR often results in several updating commits being added after the codestyle commit, this can then get complex as it's difficult to keep the codestyle and non-codestyle commits separate on merging (as they should be). It's probably best to make the codestyle cleanup a separate follow-up PR.

For example 5b8363af0084786a7e949ae8fa16bde046f8ffda followed soon after by 0cc85a7dc6d7840c47dbd9a9193f5eaaee10dad3

**Comment by ClobberXD** [comment]
Hmm... from your earlier comment, is the linter not set up to work with MT's code-style? Of course, it's not possible to tune it in every single aspect, but from what you say, it seems like there's a huge difference between MT's code-style, and the style linter enforces. I guess I should read up on the three linter issues before anything else. :)

**Pull request closed without merging**
