### PR TITLE
Add textures for air and ignore items

### PR DESCRIPTION
**Pull request by Wuzzy2**
Air and `ignore` had the “unknown node” textures which I think are wrong and confusing (since these nodes are not actually “unknown”), so I added wield/inventory textures for these special nodes:

Screenshot of air and ignore textures

(Air on slot 4, `ignore` on slot 5)

I18N note: The words on the images represent the itemstrings, and not the item names, so they are correct across languages.

Experiment with alternative textures (not part of PR, tell me if you like those more): https://i.imgur.com/J02bHF7.png

I know, these nodes are not supposed to be collected by the player at all, but they still might end up in an inventory because of mod errors or `/giveme`. And it really doesn't hurt to have these textures. :-)

### CODE REVIEW

**Comment by bigfoot547** [comment]
I like the second textures more.
They look more professional(?)
But :+1: !

**Comment by Wuzzy2** [comment]
Yeah, the text version was chosen to somewhat resemble `unknown_node.png`, `unknown_item.png` and `unknown_object.png`.

**Comment by paramat** [comment]
Certainly air and ignore should not have unknown textures, so this is good even if rarely seen. I prefer the text textures as they are clear, match the nodename and are consistent with unknown.
:+1:

**Comment by red-001** [comment]
prefer the text textures.

**Comment by sofar** [comment]
Either are fine with me. :+1:

**Pull request merged**
