### PR TITLE
Textures: New 'smoke puff' texture from TNT mod

### PR DESCRIPTION
**Pull request by paramat**
screenshot_20160926_173316

screenshot_20160926_173312

^ This commit
Note how the pixels are roughly correctly sized to match world pixels, unlike the current texture.
The current texture uses alpha translucency which probably causes depth-sorting issues #95 

screenshot_20160925_222403

^ Current

### CODE REVIEW

**Comment by MoNTE48** [comment]
I think that we can simply remove it. It looks very badly, and sometimes simply do not need.

**Comment by HybridDog** [comment]
l don't like the new one because
the current one can be transformed randomly so it looks like there are many different puff textures: https://github.com/HybridDog/nuke/blob/master/init.lua#L730 and
the new one looks like rotated squares.

l also think it should be removed because it's a remnant and mods should use individual textures in lieu of using the same one.

**Comment by Fixer-007** [comment]
I dislike new one, I think keep the old one, do not remove it completely.

**Comment by paramat** [comment]
Yeah my suggestion is not great, but the current is very ugly. Please do suggestother smoke puffs you know of from mods.

**Comment by paramat** [comment]
I feel we should use a 16x16 resolution texture to be more consistent with the default textures, part of the reason the current puff looks bad is because it is too high in resolution. I should actually make this texture 16x16 and enlarge it in the code.

Apart form that, perhaps we can consider a new type of texture for this use of 'something just disappeared / died / went pop'? Something more cartoony and abstract and not necessarily smoky (just not a blood splatter).

**Comment by C1ffisme** [comment]
@paramat Certaintly not anything violent... I know that in Minecraft, the player or mob "keels over" by rolling the model over. ('Roll' as in yaw, pitch, and roll.)

**Comment by Megaf** [comment]
:+1:  I think the new one it's ok. I would rather use none of them and maybe a different approach, the the suggested texture looks better in my opinion.

**Comment by paramat** [comment]
It's not a great texture but it's an improvement and we can improve it later.

**Comment by sofar** [comment]
:+1: better pixel size consistency. plenty of improvement potential left, but this is good.

**Comment by paramat** [comment]
61e112b43b5b9aec3791110b27db0f4f6ab8a85f

**Pull request closed without merging**
