### PR TITLE
Add support for mesh items

### PR DESCRIPTION
**Pull request by sapier**
Example:
```lua
 minetest.register_craftitem("default:steel_ingot", {
  	description = "Steel Ingot",
 	inventory_image = "default_steel_ingot.png",
 	mesh = "character.b3d",
 	meshtexture = "character.png",
 })
```
http://imgur.com/y9ixW4r http://imgur.com/xYEUIzs http://imgur.com/z4hlJgb

### CODE REVIEW

**Comment by MoNTE48** [comment]
I still do not see any benefit. You should have corrected the bug and distortion wilditem on many devices.

**Comment by Calinou** [comment]
:+1:, since this is actually an extendable system.

**Comment by sapier** [comment]
Monte can you be more precise about which bug you're talking about? maybe You should create a issue for it if it doesn't already exist?

**Comment by MoNTE48** [comment]
https://forum.minetest.net/viewtopic.php?f=6&t=10862&hilit=wield+odd

**Comment by sapier** [comment]
we've got a bugtracker here in github for a good reason
btw I think about removing your comments from this pull as they're quite offtopic

**Comment by kaeza** [comment]
I'll just repeat my :+1: here

**Comment by sofar** [comment]
I'm quite alright with this patch, it's a nice expansion that may offer benefits in-game to *especially* tools, and optional. :+1:

**Comment by est31** [comment]
Has this PR been approved by any core dev except @sapier? This is certainly not trivial, so requires approval by at least two core devs.

**Comment by est31** [comment]
Unless there is approval of this change by day after tomorrow (Dec 31, 00:00 CET), I will revert the two commits of this PR due to missing approval by two core devs.

So anybody from @minetest/team-minetest or @sapier , please tell me which core dev except sapier has approved the change.

**Comment by sapier** [comment]
actually this is quite close to trivial. Sorry for misinterpreting the minetest/people list as current coredev list. I fixed my mistake.

**Comment by est31** [comment]
The minetest/people list includes also the website contributors. Perhaps it can be made more clear by making the team-minetest team public, currently its hidden.

**Comment by est31** [comment]
thanks.

**Comment by celeron55** [comment]
Wait, wait, wait. What's the status of this now? Github noticed this got merged and removed this from open PRs, and didn't notice it was removed and now it's not in open PRs anymore.

Does this have to be re-created now?

**Comment by est31** [comment]
It seems the PR has to be re-created in order to be "reopened".

And if it then has proper agreement by at least 2 devs, it can be merged.

**Pull request merged**
