### PR TITLE
Show singlenode mapgen to menu

### LINKED ISSUE #5867: Show singlenode option in mapgen selection
Before now i have been unsure about this and hmmmm has stongly disapproved, but now i feel this should be present, many people have asked for it and it will actually help certain situations when a mod is detecting mapgen.
I will do this, could do this now but it is not a bugfix.

### PR DESCRIPTION
**Pull request by nerzhul**
Fix #5867

i'm not sure it's good to show it to main menu as singlenode for me is only air

### CODE REVIEW

**Comment by paramat** [comment]
:+1: 
That was hmmmm's argument, hiding it to avoid confusion or disappointment for newbies who don't yet understand it is meant to be empty. However i can't remember anyone complaining about it before, but we have had many users asking for it to be re-added to the menu, so many i had to make a Github gist to refer people to when they ask.

Some mods select options depending on mapgen, but singlenode has to be enabled by a mod and that mod may be loaded after a mod that detects mapgen.
This resulted in Nyan Cats appearing in singlenode even though they were not meant to, because default loaded before any mod that enables singlenode. In this way re-adding it to menu will help.

**Comment by red-001** [comment]
If it's to be re-added it should be named something easier to understand, like `Empty world` or something to that effect.

**Comment by paramat** [comment]
That would break stuff for no good reason.
'singlenode' is accurate, it is a mapgen consisting of a single node, air by default, but could be stone or water or anything. A world of stone wuld not be empty. I think the odd name is enough to warn players it may be something different.

**Comment by red-001** [comment]
how would that break stuff? I'm not saying the internal name should  be changed just the user visible name. E.g. in the drop down dialog

**Comment by paramat** [comment]
That would confuse modders for no good reason, and i've just explained that the name is fone.

**Comment by nerzhul** [comment]
i'm neutral about the name if it's correctly documented

**Comment by paramat** [comment]
Yes we are planning to add descriptions of mapgens somewhere, maybe even in an in-menu help tab, there is an ssue for mapgendocumentation.

**Comment by paramat** [comment]
To clarify, hmmmm's concern was nothing to do with the name, he considered that fine. The concern was giving a bad impression to someone who doesn't know what the mapgen is for yet. Mainly though his attitude was because the mapgen is for lua mapgens that generate everything, the mapgen mod itself would select singlenode so hmmmm didn't see a reason to select it in the menu. However people like to use it for testing or using with WorldEdit.

The name should describe a mapgen that is composed uniformly of only 1 node, whatever that is, so 'single node' is accurate, short and also mentions 'node'.

**Comment by red-001** [comment]
Yes and changing the name would mean that new players would know what it is for. Singlenode might make sense to modders but there is no way a new player would know what it means.

**Comment by paramat** [comment]
> Yes and changing the name would mean that new players would know what it is for

No, 'empty' does not explain the usage.
'empty' is incorrect anyway, it is by default a world full of 'air' which is not emptiness, or a world full of any node, like stone, that would not be 'empty'. You do realise that the intended usage of singlenode is to define the node that fills the world? It is only 'air' as a default.
The only node that represents emptiness in MT is 'ignore'.

**Comment by XtremeHacker** [comment]
As long as we have a doc decribing what it is, I think that could help, maybe even with a little tooltip referring to the said ingame documentation?  
I don't mind writing some documentation, as long as I know what info I'm going off of.

**Comment by DS-Minetest** [comment]
Pff, there's no need for a doc, the player will look what it is since it's new and will see that it is a world only filled with air.

**Comment by SmallJoker** [comment]
Since we've also got the mapgen "flat", this option should be re-enabled to give the players the possibility to start in a empty world if they want.
:+1:

**Pull request merged**
