### PR TITLE
Fix MSVC build

### PR DESCRIPTION
**Pull request by SmallJoker**
Build broken by 98e36d7

The compiler complained about the missing `M_PI`.

### CODE REVIEW

**Comment by nerzhul** [comment]
Sorry i'm against including it in header. Which cpp file complains about it ? M_PI is not called in environment.h

**Comment by red-001** [comment]
Both `content_sao.cpp` and `treegen.cpp` include `environment.h` and they use `M_PI`.

**Comment by sfan5** [comment]
In that case the needed header file should be included by `content_sao.cpp` and `treegen.cpp` and not some random header that happens to be shared between those two.

**Comment by SmallJoker** [comment]
Moved it to the two files.

**Comment by sfan5** [comment]
dd282e646c42e3524bc546372c6a648e99b3c9db

**Pull request closed without merging**
