### PR TITLE
Global code architecture improvement + SAO split

### PR DESCRIPTION
**Pull request by Quent42340**
I originally made my fork as an example for #7899 but since @nerzhul told me it could be potentially merged, I'm here.

The goal is to improve global code architecture (first 2 commits) and to split `content_sao.h/cpp` (third commit).

### CODE REVIEW

**Comment by rubenwardy** [comment]
src/engine/ doesn't make sense to me, as the whole thing is the engine.
Are you intending to provide helper libraries in other folders, or something?

Good progress though, this has bothered me for a long time

**Comment by Quent42340** [comment]
> src/engine/ doesn't make sense to me, as the whole thing is the engine.
Are you intending to provide helper libraries in other folders, or something?

True, doesn't currently make sense. But it will help a bit since there's already `src/client/`, so we can't make another `src/client` folder, that's why I came up with `src/engine/client` in the first place.

> Note that moving files already is perfectly fine. It's the breaking up of files which will cause PRs to break

Yep, that's the main issue, but as I said on #7899, I could adapt existing PRs to the new architecture.

**Comment by SmallJoker** [comment]
Moving the client-specific files to its own directory is a good decision, but I for my part, I would prefer to keep the server/client shared files in the main `src/` directory for
1) faster file access (clicking, browsing)
2) less PR breakage

I think the SAO split part would better belong into a new PR, because moving the files alone already causes a huge diff - unless you can squash it into two commits: file movement and SAO split-up. Speaking of the SAO changes: The file names currently do not match our naming pattern, could you please either use lowercase  for them?

**Comment by rubenwardy** [comment]
> faster file access (clicking, browsing)

I personally using the file select feature in my editor to find files, and rarely use the file browser. The benefits of better grouping out weigh this, imo

**Pull request closed without merging**
