### PR TITLE
Update czech translation

### PR DESCRIPTION
**Pull request by JakubVanek**
Hello everybody,
I updated Czech translation and modified some word forms. In addition I want to ask: what means "Touch free target"?
Thanks for developing this game,
Jakub Vaněk

### CODE REVIEW

**Comment by kaeza** [comment]
>what means "Touch free target"?

I asked the same question on the dev IRC channel. [Here](http://irc.minetest.ru/minetest-dev/2014-12-13#i_4060278)'s the response, according to ShadowNinja/Tesseract:

>It means you can touch to place/dig anything on the screen instead of having to point the cursor at it.

**Comment by ShadowNinja** [comment]
> What means "Touch free target"?

LOL, I've been asked this a lot of times.  That string should probably be changed to something that someone might understand. #2055

**Comment by JakubVanek** [comment]
Great, thanks. Also noticed issue [#2053](https://github.com/minetest/minetest/issues/2053)

**Comment by JakubVanek** [comment]
Added new strings from pull #2176 and commits before ca217d0, now it is complete.

**Comment by nerzhul** [comment]
Committed, thanks: 2630f45fdf9888038a5f0e08319dd0d4d1ce5e82

**Pull request closed without merging**
