### PR TITLE
Improve shadow rendering with non-default camera FOV

### PR DESCRIPTION
**Pull request by x2048**
Improve filtering of distant shadows, see #11341. 

This PR corrects two things:
* shadow frustum calculation when camera FOV is not default, e.g. when using Zoom.
* getPenumbraRadius() in the node fragment shader to adjust the minimum filter radius for perspective, which improves most of the cases of distant shadow filtering.

This PR is Ready for Review.

## How to test

Enable dynamic shadows, choose one of the following parameter sets:
* shadow_filters=1, shadow_soft_radius=1
* shadow_filters=2, shadow_soft_radius=1
* shadow_filters=1, shadow_soft_radius=2
* shadow_filters=2, shadow_soft_radius=4

Look at distant shadows and move around, notice that the overall shape of the shadow does not change significantly and gets less sharp with distance.

Use Zoom to look at distant objects.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Do you have a before and after image? In what I am testing, I'm not seeing a difference.

**Comment by x2048** [comment]
@lhofhansl @0xLiso I have also added adjustment of shadow frustum for zoom. Can you take a look?

**Comment by 0xLiso** [comment]
> @lhofhansl @0xLiso I have also added adjustment of shadow frustum for zoom. Can you take a look?

No, but I like it. If you want we can merge both solutions.

**Comment by lhofhansl** [comment]
The two changes are conflicting now. :)

**Comment by lhofhansl** [comment]
Now the shadows are seen much further with zoom. In the example I tried the shadows started to fade at a distance of around 60, and about 200 with zoom.

**Comment by x2048** [comment]
Yes, I expand the shadow distance propostionately to the FOV/zoom. Thought that was the desired behavior that using zoom gives you shadows at the place you are looking at...

What would be your expectation?

**Comment by lhofhansl** [comment]
Yep. When I added zoom some time ago I adjusted depth to keep the volume constant. Maybe we want something similar here?

**Comment by lhofhansl** [comment]
I think this one is good.

**Comment by x2048** [comment]
@lhofhansl  I've reused your distance adjustment function to reduce the amount of different math in the code.

**Comment by lhofhansl** [comment]
Thanks @x2048 . Tested. Works. I'll leave my "One approval" up.

**Comment by lhofhansl** [comment]
Looks like the softshadow setting is treated as an integer, even though it allows float values. A setting of 1.99 has no effect.
(Different, unrelated issue, but I I thought I'd mention it here.)

**Comment by lhofhansl** [comment]
One problem that does happen is when the camera offset changes, there is one frame where the shadows are incorrect (using the old offset I assume). You can see that when you fly around, every 200 nodes in any direction that will happen. I do not think that is a big problems (the clouds also suddenly readjust in that case), but wanted to mention it.

**Comment by lhofhansl** [comment]
@x2048 Wanna change that to getFloat in shader.cpp and then we can merge this (pending another approval)...?

**Comment by x2048** [comment]
Sure

**Comment by lhofhansl** [comment]
Also, is there any way to the filtering more stable? It's quite jittery (especially when you lower the shadow map update interval). Or maybe it's not the filtering but the shadow itself due to rounding...?

**Comment by x2048** [comment]
@lhofhansl I've now changed the formula for minimum filter radius to reduce jitter and produce better distant shadows. Some jitter may still be there with low and medium SM texture resolutions. Can you check on your side?

**Comment by lhofhansl** [comment]
I think it's slightly better. The real problem is that shadows themselves are jittery, there is only so much one can do about this with filtering (you can see that when you turns all filtering off, reduce the shadow map update interval), not sure there is anything really that can be done about it.

This one is still good. Let's get this in as it is now (including your latest changes) and file additional PRs.

Thanks for working on this. (A larger feature like this will take some time to settle.)

**Review by SmallJoker — APPROVED** [review]
Looks good.

**Pull request merged**
