### PR TITLE
Windows: Skip cmd for release builds

### PR DESCRIPTION
**Pull request by adrido**
This skips the cmd window on startup for release builds. Startup time is much faster then.

The `/INCREMENTAL:NO` just solves a linker warning (Linking with `/LTCG` does not allow `/INCREMENTAL`)

### CODE REVIEW

**Comment by SmallJoker** [comment]
:-1:  The console window is helpful to develop mods and finding bugs. Compared to the debug.txt file all new lines can be viewed in the console instantly.

**Comment by adrido** [comment]
Yes I understand that it might usefull, but here I have some points against it:

- Most players just want to play, and there is the console window just annoying. 
- Some young players might get irritated by seeing the console. (they does not know what it is)
- No other program uses such a console window. 
- The console on windows before windows 10 is really useless, it is not even resizeable. 
- If someone want instant notice about what happens in the code, he can simply replace print(...) with minetest.chat_send_all(...)
- A real application window makes a more native and finished look
- If I remember correctly there is no console window on Linux popping up
- On debug builds the console is still available

**Comment by nerzhul** [comment]
@SmallJoker cmd for debug build okay, but seems lgtm for release builds, it's not very proper and "profesionnal"

**Comment by adrido** [comment]
I added the cmake option `ENABLE_CMD_WINDOW FALSE CACHE BOOL "Shows the cmd window in Release builds"`. If someone want it, its easy to enable.

**Comment by sofar** [comment]
:+1: default disable, maybe this could actually be an option in minetest.conf, but, it seems @SmallJoker's concern for debug builds is entire covered this way.

**Comment by SmallJoker** [comment]
@sofar This is a compiler parameter, thus it could be quite hacky to add a minetest.conf setting for the console window.

> I want you to think about whats better for the whole Minetest project, and not only think about whats better for you :wink:
@adrido Yes, that's true. My comment should only represent my own opinion - not meant as a downvote from a coredev. Blocking this PR if there are people who would like to have this window away would be nonsense. However, thanks for adding the CMake param in :)

**Comment by nerzhul** [comment]
@SmallJoker i think covering the whole usage are good, but for a end user point, console it crap, just permit to enable it for developers is good

**Comment by adrido** [comment]
> @adrido Yes, that's true. My comment should only represent my own opinion - not meant as a downvote from a coredev. Blocking this PR if there are people who would like to have this window away would be nonsense. However, thanks for adding the CMake param in :)

Phew 😅 I thought this would end up in one of that "controversial" PR that does not have any future. 

This PR changes the subsystem to Windows, this have to be done on link time. Its not possible to change the subsystem on run time. There exist (hacky) ways within the Windows API to allocate a new cmd window at runtime, but I does not know if this would have the wanted effect.

**Comment by tobyplowy** [comment]
@adrido i made an issue about this a while ago I'm happy that someone took the time to fix this

**Comment by nerzhul** [comment]
@sfan5 @Zeno- what is your opinion on this PR ?

**Comment by sfan5** [comment]
agree that it's useful

**Comment by adrido** [comment]
> however it's missing the code that does the same for MinGW

If [this document](https://linux.die.net/man/1/ld) is a trusted source, the command line arguments might be 
`--subsystem "windows" --entry=mainCRTStartup`, but I does neither know if this is the official documentation, nor I can verify that it works. Feel free to test it and create a PR to this branch, or a separate PR later.

**Comment by Fixer-007** [comment]
* How do I remove DOS command windows?
*    In the link step add a "-mwindows" switch to the command line.
from http://www.mingw.org/wiki/FAQ

**Comment by Fixer-007** [comment]
@adrido

**Comment by adrido** [comment]
Maybe the MinGW stuff should be added by someone who have more experience with MinGW than me. I does not like to blindly write code, that I cannot test. 
I hope this can be considered to merge in current state, and someone else creates a separate PR for doing the same with MinGW later.

**Comment by Fixer-007** [comment]
I can test it, I already pasted info above.

**Comment by sfan5** [comment]
I have used `-mwindows` before and can confirm that it has the intended effect (not tested it on MT tho).

**Comment by Fixer-007** [comment]
I've tried it with -mwindows and had a success - no cmd window, starts up and runs fine, icon is visible in taskbar (but not in alt+tab taskbar switcher, but I'm ok with that)
Here is what I did:
in src/CmakeLists.txt I found line https://github.com/adrido/minetest/blob/e85637b4e3d44112ba04fdf0cc456482805692ab/src/CMakeLists.txt#L771
and made it like this:
```
	if(MINGW)
		set(OTHER_FLAGS "${OTHER_FLAGS} -mthreads -fexceptions")
		if(NOT ENABLE_CMD_WINDOW)
			set(OTHER_FLAGS "${OTHER_FLAGS} -mthreads -fexceptions -mwindows")
		endif()
	endif()
```

**Comment by adrido** [comment]
Thanks for testing, but if it does not show up inside the ALT-TAB task switcher, something seems wrong to me. Or could that be because of your Windows version? It looks a bit older.

**Comment by Fixer-007** [comment]
Icon in alt-tab mode is visible in console only, if you disable console, the behaviour for main window is the same as before. That can be improved later. I'm interested in getting this PR in for both msvc and mingw.

**Comment by adrido** [comment]
Ahh Sorry, did not understand you correctly. I understand that the whole Minetest application is not displayed in Task switcher 😆 . The Icon that is displayed in the Taskbar is the "Application Icon" that icon that's displayed in the "Classic" Task switcher is the "Window Icon". Since Windows 7 (Vista maybe too) the Window is displayed as a thumbnail. As long as Minetest does not have a proper Window Icon set there is nothing to display. If I remember correctly, the Window icon is hard coded by the Irrlicht engine to "`irrlicht.ico`"
Dont know if there exist other ways to set it, but just copy the "`minetest-icon.ico`" from `misc\` to the "`bin\`" folder and rename it to "`irrlicht.ico`". Then it should display the proper Window Icon 😉.

Could you please check, if it also work if you do:
```
	if(MINGW)
		set(OTHER_FLAGS "${OTHER_FLAGS} -mthreads -fexceptions")
		if(NOT ENABLE_CMD_WINDOW)
			set(OTHER_FLAGS "${OTHER_FLAGS} -mwindows")
		endif()
	endif()
```

**Comment by Fixer-007** [comment]
>Dont know if there exist other ways to set it, but just copy the "minetest-icon.ico" from misc\ to the "bin\" folder and rename it to "irrlicht.ico". Then it should display the proper Window Icon 😉.

Indeed! I did this and now I see proper icon for minetest everywhere (Windows 7 sp1)

>Could you please check, if it also work if you do

Yes it does work.

**Comment by adrido** [comment]
Done. Thanks for your tests.

**Comment by Fixer-007** [comment]
Hmm, so for msvc it is hidden for release builds only, but for mingw - for any release (release, debug), it needs additional detector for CMAKE_BUILD_TYPE=Release

**Comment by adrido** [comment]
Done.

**Comment by rubenwardy** [comment]
Is it possible to create a batch file to start with the console?

**Comment by adrido** [comment]
No, thats not possible. This is changing the subsystem where the application is running on. This have to be made at compile/ link time, and cannot be done on run time.

**Comment by Fixer-007** [comment]
Tested :+1:

**Comment by tenplus1** [comment]
Removing console would be a pain for mod makers when it comes to errors, having to refer to debug.txt all the time instead of simply looking at the cmd window...  Also, if cmd was removed and minetest was made a windows program only a console would have to be added for just such checking so we would need someone to add that beforehand, which in itself comes with separate problems like when Mt crashes and closes the console window with it.

**Comment by Fixer-007** [comment]
@tenplus1 http://ophilipp.free.fr/op_tail.htm

**Comment by Fixer-007** [comment]
Relevant: https://stackoverflow.com/questions/13100785/mingw-build-gui-application-with-console

**Comment by adrido** [comment]
I found a simple way to dynamically allocate a console window within pidgin source code. [sarcasm] And it also leads all that useless crap to that console too (like it did before). hope that spam makes people happy again 😛  [/sarcasm]
screenshot 3

@Fixer-007 you answered while i was compiling and taking that screenshot. Its similar to the last answer of your link. 😆 

That solution does require some more programming to do it right, so I may need some more days.
Just a question to coredevs, how should the commandline argument be called to make the console visible?

**Comment by celeron55** [comment]
What happens if Minetest is started from a console? Does it create a new console or use the existing one?

**Comment by celeron55** [comment]
For that option, I'd suggest simply "--console".

**Comment by Ezhh** [comment]
I use console a lot from Windows version of MT. If it can be an option to enable, and then I run the game as usual and the console is there, it's great, otherwise this will be a huge annoyance. (And if it's not there by default, having to enable an option each time I test a client (and, I assume, then restart the game?) would also be a (slightly) lesser annoyance by itself.

**Comment by adrido** [comment]
My idea is to check if `AttachConsole(ATTACH_PARENT_PROCESS)` is successfull, then its called from a parrent console. If not, allocate a new console. So this is better then the console window before, because it does not open a new console if there is already one.I Just did some tests, and it works as expected. :-)
I does currently not know what happens if the parent process is not a cmd window.  I assume it does not open a cmd window

**Comment by celeron55** [comment]
It looks like we need to also add the option to pop up the console window like it currently does, and also make that behavior configurable in minetest.conf. We can't just decide people shouldn't like the current behavior.

**Comment by rubenwardy** [comment]
--console is enough if you also add a batch file
Whichever is cleaner

**Comment by Fixer-007** [comment]
Tried it on mingw build:
+ no console window as intended
+ when starting minetest.exe --console from command prompt the text is printed and waits, no minetest window appear:
```
d:\xxx\minetest-0.4.15-26f4a5c2-win64\bin>Allowed options:
  --address <value>     Address to connect to. ('' = local game)
  --config <value>      Load configuration from specified file
  --console             Starts with the console (Windows only)
  --gameid <value>      Set gameid ("--gameid list" prints available ones)
  --go                  Disable main menu
  --help                Show allowed options
  --info                Print more information to console
  --logfile <value>     Set logfile path ('' = no logging)
  --map-dir <value>     Same as --world (deprecated)
  --migrate <value>     Migrate from current map backend to another (Only works when using minetestserver or with --server)
  --name <value>        Set player name
  --password <value>    Set password
  --port <value>        Set network port (UDP)
  --quiet               Print to console errors only
  --random-input        Enable random user input, for testing
  --run-unittests       Run the unit tests and exit
  --server              Run dedicated server
  --speedtests          Run speed tests
  --terminal            Feature an interactive terminal (Only works when using minetestserver or with --server)
  --trace               Print enormous amounts of information to log and console
  --verbose             Print even more information to console
  --version             Show version information
  --videomodes          Show available video modes
  --world <value>       Set world path (implies local game) ('list' lists all)
  --worldname <value>   Set world by name (implies local game)
```
+ same for starting it via LNK file

**Comment by adrido** [comment]
yeah its not finished. that was just a backup of my current work

**Comment by Fixer-007** [comment]
Oh, do I need to delete that message?

**Comment by adrido** [comment]
:) hmm dont care

**Comment by Fixer-007** [comment]
Deleted my messages to not confuse, I will wait for final version.

**Comment by adrido** [comment]
should work now except for reading the setting. I does not find the point when the settings-file got parsed, and g_settings is available.

**Comment by Fixer-007** [comment]
Status?

**Comment by nerzhul** [comment]
i don't like windows but it's inacceptable for end users to have an opened cmd, minetest is not a Dos game on Windows 95

**Comment by sofar** [comment]
Looking at this patch it adds all the options needed for the console to be easily reachable:

 * --console option
 * minetest.conf option
 * console is started when relevant (e.g. server is started)

So, :+1: (But I can't test).

**Comment by Fixer-007** [comment]
I will test this

**Pull request merged**
