### PR TITLE
[don't squash] Bump IrrlichtMt to newest revision

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by sfan5** [comment]
Question: should the version check be made `==` instead of `>=` in release builds?
It's not guaranteed that a newer IrrlichtMt version is going to be incompatible, but no clear guidance of which IrrlichtMt version to use has confused users in the past.

**Comment by SmallJoker** [comment]
@sfan5 A fixed irrlichtMt version seems to be the most reliable option IMO (i.e. `==`). This way the locked step pace we're going can be ensured.

**Review by SmallJoker — APPROVED** [review]
Looks good, concept :+1:

**Comment by sfan5** [comment]
`==` check added for release builds

**Pull request merged**
