### PR TITLE
[CSM] allow the client to access and modify settings in the `client.` namespace.

### PR DESCRIPTION
**Pull request by red-001**
This also syncs some of the related documentation with `lua_api.txt`

### CODE REVIEW

**Comment by SmallJoker** [comment]
I'm not sure about the concept. Server mods are able to modify all settings apart from `secure.`, so why should CSM be disallowed to do the same?

**Comment by DS-Minetest** [comment]
@SmallJoker I think, this is because in future servers should be able to send clientmods to clients, and these server sent mods shall not configure something of the player.

**Comment by ShadowNinja** [comment]
Discussed on IRC.  I don't like the way the namespacing's done.  I think this could work if you used setting groups instead.  This way you shouldn't need the `isClient` stuff (and if you still need an `isClient` function I think there's probably a better way of doing it than storing a boolean in the Lua state).

**Comment by paramat** [comment]
@red-001 

Since CSM is controversial, needs re-assessing. Is this useful for server-sent CSM?

**Comment by paramat** [comment]
neglected, closing.
@nerzhul maybe you want to adopt this if it's important?

**Pull request closed without merging**
