### PR TITLE
Add a search field to the multiplayer tab

### PR DESCRIPTION
**Pull request by cdqwertz**
This pull adds a search field to the multiplayer tab. 

search_field

### CODE REVIEW

**Comment by est31** [comment]
Okay, best to compare this with #4472 to find out which one is better.

**Comment by SmallJoker** [comment]
This version offers only searching by title. The other one also allows to do in-line filters, which is very helpful when searching for other criterias.

**Comment by kahrl** [comment]
The caption on the button should be either "Search" (like in #4472) or an icon commonly associated with search, such as a magnifying glass. "?" makes me think that this button might display some help.

**Comment by est31** [comment]
+1 @kahrl 's suggestion, but it should be consistent with the search button inside the Minetest Game creative inventory. Maybe they adapt their search button as well?

**Comment by red-001** [comment]
Couldn't this be closed now?

**Pull request closed without merging**
