### PR TITLE
Reduce block load glitches

### LINKED ISSUE #7541: Disable day-night diff block retrieval for underground blocks
Currently we do not send block beyond `block_send_optimize_distance` unless they are at "ground level" (i.e. their day and night light differs).

This culls a lot of block, but leads to very annoying glitches at the deep oceans, and make caves practically useless.

To make this better we can check `block->getIsUnderground()` in addition to `block->getDayNightDiff()` as a heuristic. That leads to more blocks being loaded, but removes most of the glitches.

As a test I did the following (view range 300).
- default: 971 blocks are in range
- only remove blocks when it is not underground: 1453 blocks are in range
- disable the distance optimization: 4089 blocks are in range

So we get much better mileage than disabling the optimization, while we get most of the benefits.
Could make this optional via a setting, but I feel like this optimization was always too aggressive for setups where it matters.

Thoughts?

### PR DESCRIPTION
**Pull request by lhofhansl**
Fixes #7541 . See comments there.
This will load more blocks, but remove almost all glitches of blocks that are visible but not loaded. The deep ocean glitches and large underground cave glitches are gone.

This will not cause many more blocks underground, due to server side occlusion culling.

For an above ground scene this might load 50% more blocks over the default setting.
(For comparison disabling the optimization completely would load almost 5x as many blocks.)

Note that this is just an improved heuristic. It won't help in above ground level caves or above ground deep lakes.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Could make this configurable too.

**Comment by paramat** [comment]
Good idea but not sure if this needs to be optional. I actually play with serverside occlusion culling off so i can see caves when flying underground doing dev work.
'is underground' seems to be decided by a block being above or below 'water_level'.

**Comment by lhofhansl** [comment]
> not sure if this needs to be optional

You mean it should be optional? It will strictly return more blocks to the client.
I'm not a fan of too many options, especially when they are related or dependent on each other. Can we collapse some?

Perhaps we can combine this, optimize distance, and server occlusion culling into one "aggressive optimization" setting...? But that would give less control over the individual settings.

Easiest is of course to add another config option for this. Default on.

**Comment by paramat** [comment]
> You mean it should be optional?

No i mean i can't decide :) However since serverside occlusion culling is default on then i think i'm ok with no setting.

I disagree with any kind of combined settings.

> In that case you want to the distance optimization off as well, right?

Yes. Currently i set the optimisation distance quite high and switch serverside occlusion culling off.

**Comment by paramat** [comment]
:+1:

**Comment by lhofhansl** [comment]
Cool. Going to merge tomorrow.

**Comment by lhofhansl** [comment]
ba7cf30df93836247a9232c285ca85659d6578e5

**Pull request closed without merging**
