### PR TITLE
[Experimental] Remove fast faces.

### PR DESCRIPTION
**Pull request by lhofhansl**
Rebased from #6903 courtesy of @numberZero 

Removes fast faces completely. Since fast faces show as CPU hogs now, I spent a few minutes rebasing that PR.
I'm not attached to this, I just want folks to be able to try it out. At least we can start a discussion. 

## How to test

Load any world and test. Look at FPS and jitter.

### CODE REVIEW

**Comment by lhofhansl** [comment]
From @numberZero on the original PR:

```
Note: I just realized it computes lighting wrongly. Fixing that is possible but is non-trivial.
Note: I can’t test performance/stutter/etc. myself as my new CPU is too fast, it can handle way more load.
Note: This PR is experimental and may not be a good decision.
```

**Comment by lhofhansl** [comment]
Anybody who understand the lighting code better: Any ideas what @numberZero meant, and how to fix it?

**Comment by numberZero** [comment]
Did you test it with flat lighting? I don’t remember the code but 
wouldn’t be surprised if it would be all black in that case.

16.02.2023 01:04, lhofhansl пишет:

**Comment by lhofhansl** [comment]
> wouldn’t be surprised if it would be all black in that case.

You are exactly right.

**Comment by numberZero** [comment]
To my understanding, it should be OK with smooth lighting. But with flat lighting, `drawAutoLightedCuboid` just can’t be used as it is designed to get lighting from the node being rendered, while for a solid node lighting should be gathered from the neighbours.

**Comment by lhofhansl** [comment]
Thanks @numberZero

**Comment by lhofhansl** [comment]
Closing in favor of #13216

**Pull request closed without merging**
