### PR TITLE
Fix rounding error in g/set_node caused by truncation to float

### LINKED ISSUE #1154: Rounding error means (for example) wrong node is read
Example lua code:

   node1 = minetest.get_node({x=34,y=-56,z=-108.49999951571})
   node2 = minetest.get_node({x=34,y=-56,z=-108.49})

These ought to read the same node, but they don't.

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #1154

### CODE REVIEW

**Comment by paramat** [comment]
Code seems ok. Since this is done only for `read_v3s16` i guess there is very little memory use impact?
I assume there is no performance impact.
The issue fixed seems minor so i'm just hoping there is no disadvantage to doing this.
I'm very close to approving.

**Comment by rubenwardy** [comment]
There will be no performance or memory impact. It simply goes from double-float-int to just double-int, and thus avoids the rounding error. The only issue is duplicated code, but to fix that would require templates or macros. Neither of which I'm fond of

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
026ad912af0ad147071da79201a335ec84bd6ce9

**Pull request closed without merging**
