### PR TITLE
Optimizer flags are set by ports/user, ok?

### PR DESCRIPTION
**Pull request by mazocomp**
https://marc.info/?l=openbsd-ports&m=152430251624488&w=2

### CODE REVIEW

**Comment by sfan5** [comment]
Unless there is some significant difference between patches to master vs. backports, there is no need to create separate pull requests as I will just cherry-pick them when the backports branch gets updated.

**Comment by sfan5** [comment]
You should've kept the PR to merge into `master` and closed this one.

**Comment by mazocomp** [comment]
@sfan5 Oh, what an implicit language, should I close these two and reopen those two?

**Comment by sfan5** [comment]
Yes please

**Pull request closed without merging**
