### PR TITLE
Display Gamma: Fix documentation

### PR DESCRIPTION
**Pull request by Thomas--S**
Overlooked in #4873

### CODE REVIEW

**Comment by Zeno-** [comment]
+1 but check with @sofar about the default gamma of 2.2

**Comment by Thomas--S** [comment]
According to [settingtypes.txt](https://github.com/minetest/minetest/blob/master/builtin/settingtypes.txt#L447) the default value is 2.2

**Comment by rubenwardy** [comment]
Do not edit minetest.conf.example directly, instead use edit settingtypes.txt

**Comment by Thomas--S** [comment]
oh, ok. settingtypes is already updated, so this PR seems unnecessary.

**Comment by rubenwardy** [comment]
Ah, so the settingstype.txt and minetest.conf.example is out of sync

The generator isn't run automatically

**Comment by paramat** [comment]
> The generator isn't run automatically

For good reason, see my comment about the noise parameter docs that need to be preserved in .conf that cannot be generated.

**Pull request merged**
