### PR TITLE
Revise old MacOS compiling workaround

### PR DESCRIPTION
**Pull request by superfloh247**
this 9 years old workaround is not needed on Apple Silicon

### CODE REVIEW

**Comment by sfan5** [comment]
It's unfortunately not documented why this line exists but I don't think `-Os` is a "workaround" (for what?).

**Comment by superfloh247** [comment]
git blame says it's from this commit https://github.com/minetest/minetest/commit/c410e9182d322a8c095ef94fbadf4d8f541e6b98 

"OS X compatibility fixes" from 2014 - not needed today anymore

**Comment by sfan5** [comment]
Sounds like we can remove it entirely then.

**Comment by superfloh247** [comment]
Maybe, but I can test only on relatively new MacOS on Apple Silicon.

**Comment by TurkeyMcMac** [comment]
I tried compiling with `-O3` on a Mac from 2014 or so. The program seemed to run fine.

**Comment by sfan5** [comment]
Can you change the PR then?

**Comment by superfloh247** [comment]
I don't know enough about cmake to change more than that small bit I touched.

**Pull request closed without merging**
