### PR TITLE
Add code to support raillike group names

### PR DESCRIPTION
**Pull request by Novatux**
See https://github.com/minetest/minetest_game/pull/448

### CODE REVIEW

**Comment by PilzAdam** [comment]
Whats the benefit over `minetest.registered_nodes["deafult:rail"].groups.connect_to_raillike`?

**Comment by Novatux** [comment]
It's shorter, and it allows for example two mods to be independant while having their raillike nodes connecting; or for example a mod like carts that would work without depending on a particular mod to provide rails - any mod with the minetest.raillike_group("rails") would work.

**Comment by PilzAdam** [comment]
Seems reasonable.

**Comment by ShadowNinja** [comment]
:+1:

**Comment by Novatux** [comment]
https://github.com/minetest/minetest/commit/75622c30beb390b7ed578010a00390aa971b3951

**Pull request closed without merging**
