### PR TITLE
Fix crash on passing false as value in table to table.copy(t)

### LINKED ISSUE #2293: table.copy fails if one of input table's keys has a value of “false”
Try this ultra-short mod and see how Minetest 0.4.11 fails:

```
table.copy({key=false})
```

Instead of copying the table, Minetest shows me this error message:
```
ERROR: /usr/share/minetest/builtin/common/misc_helpers.lua:510: bad argument #1 to 'pairs' (table expected, got boolean)
```

It also happens recursively to subtables. This code causes the same error:
```
table.copy({key={key=false}})
```

In contrast, this mod works:
```
table.copy({key=true})
```

If you have luacmd installed, it may be faster to test it with this mod.

### PR DESCRIPTION
**Pull request by est31**
Fixes #2293.

### CODE REVIEW

**Comment by est31** [comment]
changed commit message so that nobody thinks this now allows `table.copy(false)`.

**Comment by ShadowNinja** [comment]
* `copyiftable` -> `copy_if_table` -> `copy_val`
  * Missing spac after comma in second call to ^.
  * Function format is `[local ]function x()`, not `[local ]x = function()`
  * Maybe the helper function should be inlined.
  * Local functions are not global by definition, the `do end` is unnecessary.

**Comment by est31** [comment]
This method also works, and doesn't need a helper function.

**Comment by ShadowNinja** [comment]
:+1: (although I'd remove the superfluous parenthesis)

**Comment by Zeno-** [comment]
commit 7c5accf60501e0ff7fd8f44af963b71da9ac8045

**Pull request closed without merging**
