### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by Zeno-**

### CODE REVIEW

**Comment by Zeno-** [comment]
Need to add other relevant people and review the list

**Comment by Zeno-** [comment]
@paramat 
@est31

**Comment by rubenwardy** [comment]
What's the qualification for "Active Contributor"? 2 or more commits in the last 2 months?

ShadowNinja says this: #1671
(Do not bump that pull request, reply here)

**Comment by Zeno-** [comment]
@rubenwardy, yes I think the definition by @ShadowNinja is fairly accurate (IMO).

**Comment by rubenwardy** [comment]
Put maybe 3 or more in last 2 months: https://github.com/minetest/minetest/graphs/contributors?from=2015-01-04&to=2015-03-04&type=c

As for bug requests, maybe reporting 2 or more mediums or blockers. But that is a different type of contribution, that is contribution via feedback rather than contribution via contribution.

**Comment by Zeno-** [comment]
It's kind of a tough decision to make and/or quantify really :)

**Comment by Zeno-** [comment]
@paramat, @rubenwardy, @est31

Please let me know how you would like your name to appear in the list so this PR can be finalised ;)

**Comment by rubenwardy** [comment]
Just `rubenwardy` is good, thanks :)

**Comment by est31** [comment]
I'd prefer `est31 <MTest31@outlook.com>`.

**Comment by paramat** [comment]
I'd prefer not to give an email address if that's okay, i would like simply:
paramat
In lower case letters.

**Comment by Zeno-** [comment]
@paramat  no problems

**Comment by rubenwardy** [comment]
There isn't really much point of non core devs supplying their email addresses.

**Comment by Zeno-** [comment]
@rubenwardy not much reason not to as well.  I think it's fine leaving it up to the individual's preference

**Comment by kwolekr** [comment]
Remember to add gregorycu

**Comment by est31** [comment]
@gregorycu ^

**Comment by nerzhul** [comment]
@Zeno- can you merge please ? :)

**Comment by Zeno-** [comment]
e3d69f2920539e2fdecf9d6ce948e7b1b1da998a

**Pull request closed without merging**
