### PR TITLE
Mgv7: Avoid spawn on disabled mountain terrain, optimise 

### PR DESCRIPTION
**Pull request by paramat**
'getSpawnLevelAtPoint()' did not account for disabled mountains, it
was possible to be spawned in mid-air where a mountain surface would
have been.

Avoid check for river area if rivers are disabled.
/////////////////////////////////////////////////////

### CODE REVIEW

**Comment by kwolekr** [comment]
Looks good for what it does, but what about if ridges are disabled now?

**Comment by paramat** [comment]
There seems to be no need to worry about the rivers, as the code simply avoids those areas and there's no harm in avoiding those areas when rivers are disabled.

**Comment by paramat** [comment]
Actually i will skip the river noise check if they're disabled.

**Comment by paramat** [comment]
Updated and tested.

**Comment by kwolekr** [comment]
:+1:

**Comment by paramat** [comment]
56ea77ea96b62059c03ba53c15da56c72ea7e140

**Pull request closed without merging**
