### PR TITLE
Fix clipped content tab description

### LINKED ISSUE #7669: Description text clipped in content tab
screenshot from 2018-08-21 01-08-45

^ Modpack

screenshot from 2018-09-06 03-36-02

^ Mod (with description edited to 1 line)

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes #7669

grafik

### CODE REVIEW

**Comment by paramat** [comment]
Thanks.

**Comment by paramat** [comment]
The code seems ok but i'm not sure whether to call it trivial. Anyway if you consider it trivial do merge.

**Comment by Ezhh** [comment]
Compare before this PR:
before
With this PR:
after

This loses both the background and the depends info.

I don't know if it's ideal, but the error is just caused where description.txt has an empty line, so I was able to fix it just by adding `desc = string.gsub(desc, "\n", " ")` without need of changing anything else.

**Comment by paramat** [comment]
^ Tested and confirmed all that.
The black text box should stay i feel.

**Comment by paramat** [comment]
Not sure if it's an empty line that causes this, i find that a 1-line description (with no empty lines) causes the bug.

**Comment by Ezhh** [comment]
> Not sure if it's an empty line that causes this...

One line description, no empty line:
one
One line description, followed by empty line:
two

**Comment by paramat** [comment]
Ok by 'empty line' i was thinking a line with whitespace.

**Comment by SmallJoker** [comment]
@paramat @Ezhh Black background added.
It's time to use textareas since the line split method in combination with text lists does not allow copying text or a nice display for smaller GUI scaling factors (or larger fonts).

**Comment by paramat** [comment]
Box is dark blue instead of black, depends missing with this description:
```
The biome spawning and management library for Plantlife, Moretrees, Tiny Trees, and other mods that originally depended on plants_lib from the plantlife modpack. zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzzzzzzz zzzzzzzzzzzzzzz zzzzzzzzzz zzzzzzzzzzzz zzzzzzzzz zzzzzz
blah
blah
blah

space and blah
```

**Comment by paramat** [comment]
Base of box unaligned with other boxes.

**Comment by paramat** [comment]
Retesting.

**Comment by paramat** [comment]
Depends works now. Dark blue seems unavoidable? Box base alignment needs tuning.

**Comment by SmallJoker** [comment]
Dark blue box reference: http://irc.minetest.net/minetest-dev/2018-09-06#i_5402185

**Comment by paramat** [comment]
:+1:

**Pull request merged**
