### PR TITLE
Add scripts to find and update translations.

### PR DESCRIPTION
**Pull request by Ekdohibs**
This pull request provides two scripts, one similar to xgettext and the other to msgmerge to find and update the new client-side translations. Both scripts are adapted from [intllib](https://github.com/minetest-mods/intllib), which is licensed under the LGPL-compatible Unlicense.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
Please don't forget to merge/review this before 0.5.0

**Comment by SmallJoker** [comment]
The Lua code looks good but could you please provide some short instructions and possibly also a mod where this can be tested?

**Comment by Wuzzy2** [comment]
PLEASE PLEASE PLEASE get it into 0.5.0.
I cannot stress enough how important a toolchain is for making client translations *actually* useful in development.
As a modder, it will be WAY harder to manage client translations if there's no toolchain.

Even `intllib` has a toolchain.

**Comment by srifqi** [comment]
@SmallJoker I just copied from the source code. I agree that this should also be documented somewhere.

```
Usage: findtext.lua [OPTIONS] FILE...

Extract translatable strings from the given FILE(s).

Available options:
 -h,--help Show this help screen and exit.
 -o,--output X Set output file (default: stdout).
 -a,--author X Set author.
 -l,--lang X Set language name.
```

```
Usage: updatetext.lua [OPTIONS] TEMPLATE CATALOG...

Update a catalog with new strings from a template.

Available options:
 -h,--help Show this help screen and exit.
 -o,--output X Set output file (default: stdout).

Messages in the template that are not on the catalog are added to the catalog at the end.

This tool also checks messages that are in the catalog but not in the template, and reports such lines. It's up to the user to remove such lines, if so desired.
```

**Comment by srifqi** [comment]
@SmallJoker I just copied from the source code. I agree that this should also be documented somewhere.

```
Usage: findtext.lua [OPTIONS] FILE...

Extract translatable strings from the given FILE(s).

Available options:
 -h,--help         Show this help screen and exit.
 -o,--output X     Set output file (default: stdout).
 -a,--author X     Set author.
 -l,--lang X       Set language name.
```

```
Usage: updatetext.lua [OPTIONS] TEMPLATE CATALOG...

Update a catalog with new strings from a template.

Available options:
 -h,--help         Show this help screen and exit.
 -o,--output X     Set output file (default: stdout).

Messages in the template that are not on the catalog are added to the
catalog at the end.

This tool also checks messages that are in the catalog but not in the
template, and reports such lines. It's up to the user to remove such
lines, if so desired.
```

**Comment by Wuzzy2** [comment]
@Ekdohibs: Are you still interested to complete this PR by adding the requested usage instructions?

**Comment by paramat** [comment]
@Ekdohibs see requests, will reopen on progress.

**Comment by Wuzzy2** [comment]
Wait, what? You closed this, despite this being quite important and part of the 5.0.0 milestone?

**Comment by Wuzzy2** [comment]
*News Flash!*

p_gimeno reworked `findtext.lua`:

https://notabug.org/pgimeno/minetest/src/translation-toolchain/util/findtext.lua

And I have written a simple text for `lua_api.txt`:

```
Creating and maintaining translation files
------------------------------------------
Minetest has scripts to help you create and maintain the translation files.

Use `util/findtext.lua` to create the first version of translation files
and `util/updatetext.lua` to update them.

Workflow: For a simple mod named `example` with some translatable strings in
`init.lua`, this is what you need to do:

* Create the `locale` directory in your mod
* Call `findtext.lua init.lua -o locale/example.tr`
* Copy `locale/example.tr` to create the various translation files for
  different languages

If you are need to update the translations, do this:

* Recreate `locale/example.tr` with `findtext.lua` (see above)
* Call `updatetext.lua locale/example.tr locale/example.*.tr`

To learn more about the syntax of these strings, call them with
the `--help` argument.
```


All this stuff should probably be moved to another PR eventually …

**Comment by pgimeno** [comment]
> p_gimeno reworked findtext.lua:

More like added a bugfix to deal with Lua strings that contain escaped characters. The commit is here: https://notabug.org/pgimeno/minetest/commit/0947907a9d16dede6c5609147df90785196bf2f8 or alternatively in GitLab: https://gitlab.com/pgimeno/minetest/commit/0947907a9d16dede6c5609147df90785196bf2f8

To import it to an existing Minetest repo and fetch only these commits:

```
git remote add pgimeno https://gitlab.com/pgimeno/minetest
git fetch pgimeno translation-toolchain
git checkout translation-toolchain
```

**Pull request closed without merging**
