### PR TITLE
Add an empty, default tool capabilities tables

### PR DESCRIPTION
**Pull request by AlexYst**
This fixes the segfault explained at <https://github.com/minetest/minetest/issues/7215>.

### CODE REVIEW

**Comment by rubenwardy** [comment]
What happens if you try and dig with an empty slot with this? Does it correctly not allow you to?

**Comment by AlexYst** [comment]
Digging (or rather, attempting to dig) with nothing in your hand has no effect. Nodes don't break and you just wave your hand in the air.

**Comment by SmallJoker** [comment]
I agree with @rubenwardy. This issue should be looked up and fixed in C++ in the node digging code. If the tool caps are not defined, their definition field is set to `NULL/nullptr`, which means that this value is not handled correctly there when reading the item definition.

**Comment by AlexYst** [comment]
Alright, sounds good. Someone else'll have to fix this then though; I don't know C++ yet.

**Comment by SmallJoker** [comment]
The underlying issue of this PR is non-existent in 0.4.17-dev. Closing.

**Pull request closed without merging**
