### PR TITLE
Add IrrlichtMT as a submodule

### LINKED ISSUE #13034: Set submodules for minetest_game and IrrlichtMt
## Problem

minetest_game and IrrlichtMt repositories are not linked properly with main minetest repo. Let's say new version of IrrlichtMt will break compatibility with minetest. Doind sumple `git clone` or `git pull` for IrrlichtMt will download newest, not compatible version.

Current linking of repositories:
```
minetest --- manual link --- minetest_game
        \--- manual link --- IrrlichtMt
```

Current set of download instructions:
```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest/
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
```

Current set of update instructions:
```
git pull
cd games/minetest_game
git pull
cd lib/irrlichtmt
git pull
```

## Solutions

Git submodule is great way to add repository. It is pointing to other repos which are not cloned by default and not much additional data will be stored in the main repo. Also submodule can point to exact commit, so if compatibility will broke by, for example, IrrlichtMt git submodule will not checkout new commits. It will stay with last accepted by main repo.

New linking of repositories:
```
minetest --- git address & ID --- minetest_game
        \--- git address & ID --- IrrlichtMt
```

New set of download instructions:
```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest/
git submodule init
```

New set of update instructions:
```
git pull
git submodule update --recursive
```

## Alternatives

Not known by me.

## Additional context

Issue fastly closed 10 years ago without proper discussion: https://github.com/minetest/minetest/issues/73

If you ask I can prepare an example.

### PR DESCRIPTION
**Pull request by numberZero**
Irrlicht is a mandatory dependency and it *has* to be fetched from that very specific repo (or a fork thereof). So it is natural to add it as a submodule. Fixes #13034

## To do

This PR is Ready to Review.
- [x] CI scripts
- [x] buildbot
- [x] Readme

## How to test

1. Clone
2. Build
3. Run

### CODE REVIEW

**Comment by runsy** [comment]
this makes sense

**Comment by sfan5** [comment]
issue asking for this: #13034

what also needs to be changed is:
* cmake to remove the obsolete way of using it
* CI scripts & buildbot to not try to download/use separate irrlichtmt
* buildbot
* the README to suggest using `--recursive`
* update https://github.com/minetest/benchmarks

**Comment by numberZero** [comment]
> cmake to remove the obsolete way of using it

I’d keep the possibility of building Irrlicht separately. E.g. to build a debug version of Minetest with release version of Irrlicht (AFAIK Meson would allow that, but CMake doesn’t).

> update https://github.com/minetest/benchmarks

Oops, that’s something new. Will need to check that out.

**Comment by sfan5** [comment]
> I’d keep the possibility of building Irrlicht separately. E.g. to build a debug version of Minetest with release version of Irrlicht

Eh, then you get the "irrlichtmt might not be the revision MT expects it to be" problem again. Personally I don't see the need but maybe we can put it behind a big warning and keep it.

**Comment by lhofhansl** [comment]
As I stated in the issue, I'd prefer an option to build IrrlichtMt separately, at least for now.
I suppose in that case, we do not need to change the CI, buidbot, and .../benchmarks, yet.

**Comment by numberZero** [comment]
Seems to work now.

> we do not need to change the CI, buidbot, and .../benchmarks, yet.

I suppose you don’t want to track Irrlicht version in two places (submodule and irrlichtmt_tag).

**Comment by numberZero** [comment]
Android build still uses prebuilt Irrlicht, for the reasons you stated.
And it may be actually better for CI to use prebuilt Irrlicht too, but for the exact commit specified as the submodule. It is even possible (albeit nontrivial) with GitHub CI AFAIK.

**Review by sfan5 — APPROVED** [review]
As far as I'm concerned we can go ahead with this.

**Comment by nerzhul** [comment]
submodules are a pain to manage, it's a second command to handle, IDE are not always working well with it. I'd rather propose to just integrate irrlicht in minetest/minetest directly, it also permit to increase feeback loop from users

on 15 years of devs, the submodule on git on a team always failed, then with a community with various skills, it will just generate more support and more errors

**Comment by numberZero** [comment]
> integrate irrlicht in minetest/minetest directly

To my knowledge the plan was to do just that but strip it down first. But the latter needs a lot of time. Until that it has to be referenced *somehow*, and, um, do you mean `irrlichtmt_tag.txt` is better than a submodule?

**Comment by numberZero** [comment]
I just realized missing Android support is a bigger issue than I thought. Basically, it makes this a non-solution for cases where MT change depends on specific Irrlicht version (like #13321): Android build will simply break, with no easy way to fix. Granted, current Android dependency management is rather fragile already, it always pulls “latest release” of the bundle and expects it to be compatible with the MT version being built. There is something to think on...

**Comment by sfan5** [comment]
> it will just generate more support and more errors

problems with the current approach:
* users have to manually clone the matching irrlichtmt version
* distros may package irrlicht-mt separately only to be surprised that they have to update it in lockstep anyway
* we have to tag and build a new "revision" everytime we want to make dependent changes in MT

**Comment by SmallJoker** [comment]
:+1: I too support having IrrlichtMt as a submodule to improve the lockstep situation we currently have.

**Comment by Desour** [comment]
It would be good to have a short description of the recommended workflow for working with the irrlichtmt submodule, e.g. something like a TL;DR of <https://git-scm.com/book/en/v2/Git-Tools-Submodules>.

This should include:
* What to do on pull if the current working dir has no submodule, but the repo cloned in-place. (Aka how upgrade from the old system.)
* What to do on pull.
* How to create feature branches.
* How to rebase.
* And probably more.

**Comment by Zughy** [comment]
@numberZero rebase please (also https://github.com/minetest/minetest/pull/13215#issuecomment-1518696429)

**Comment by nerzhul** [comment]
@numberZero here is my advice, as a people working in a big company with IT people and 700 developers. we had some programs using git submodule, with inner sourcing contributions, which is close to MT model you will propage with this PR.
git submodule is just a hell daily. Each time people is updated it require a commit on the caller and also all people should ensure git pull and git submodule update --init is done, which is error prone in multiple cases. 
Also when you forgot that, you start to commit and then you have a wrong submodule, it's a hell to recover from the wrong submodule version, sometimes you need to edit .git/modules folder directly to solve the issue locally without loosing your changes (and i'm a really power user in git). I won't think adding such complexity in minetest repository, which will lead to weird bugs or support is good for us. I already imagine people saying hey this is crashing/not working, because he forgot to update the submodule, submodule compatible with upstream version one, but leading to issue.
Clearly no go for me.

Merge irrlichtMT in minetest/minetest repo directly in lib/irrlicht, conservating or not the history (easily do-able with git). This will close the desync painful issue we have currently because there is no link other than doc for the repos

**Comment by nerzhul** [comment]
here is some articles illustrating what i said, and submodule is for git advanced aware users, most of our contributors are not

* https://medium.com/@uttamkini/sharing-code-and-why-git-submodules-is-a-bad-idea-1efd24eb645d
* https://news.ycombinator.com/item?id=31792303
* https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

**Comment by sfan5** [comment]
To automatically build IrrlichtMt on android too (not rely on precompiled binaries) -> https://github.com/minetest/minetest/compare/master...sfan5:minetest:irr-alongside-android

Requires some very minor changes to https://github.com/minetest/minetest_android_deps obviously.

**Comment by numberZero** [comment]
> To automatically build IrrlichtMt on android too (not rely on precompiled binaries) -> [master...sfan5:minetest:irr-alongside-android](https://github.com/minetest/minetest/compare/master...sfan5:minetest:irr-alongside-android)

I guess the only reason that wasn’t done earlier was #13357, but you solved that already.

> Requires some very minor changes to https://github.com/minetest/minetest_android_deps obviously.

Like https://github.com/minetest/minetest_android_deps/pull/4? (note that simply removing Irrlicht would break *all* Minetest/Android builds, not just CI ones, as fetching the latest `deps` is hardcoded in the build process itself)

**Comment by numberZero** [comment]
> Merge irrlichtMT in minetest/minetest repo directly in lib/irrlicht, conservating or not the history (easily do-able with git). This will close the desync painful issue we have currently because there is no link other than doc for the repos

It’s up to you, core devs. I’ve offered the submodule as a temporary solution, and abandoned it due to some hairy Android problems (I hate Android development, sorry) that **sfan5** solved with #13528 (in a proper but risky way IMO) by now. But if you ask to go straight to merging, I’m okay with that. Sure, there will be more bureaucracy on each PR into Irrlicht, but OTOH it should be easier to tailor its API this way as it would be possible to change the API and usage sites in the same PR.

Oh, and one note. It’s not `lib/irrlicht`, it should be `src/irrlicht` IIUC, as `lib` is for third-party stuff.

**Pull request closed without merging**
