### PR TITLE
Add "preloads.txt" file for mods.

### PR DESCRIPTION
**Pull request by Ekdohibs**
Implements #1532.

### CODE REVIEW

**Comment by paramat** [comment]
If you're happy with this PR feel free to add your own approval and the 'one approval' label.

**Comment by paramat** [comment]
@Ekdohibs old PR, still want to keep it open?

**Comment by paramat** [comment]
@Ekdohibs ? Will close in 1 month.

**Comment by Ekdohibs** [comment]
This is too old and needs rebase, it would be easier to code it again from scratch. Closing.

**Pull request closed without merging**
