### PR TITLE
Trigger on_rightclick regardless on the formspec meta field

### PR DESCRIPTION
**Pull request by SmallJoker**
Fixes issue #6195, trivial 3-line code patch.

### CODE REVIEW

**Comment by sfan5** [comment]
If the next version isn't 0.5 (compat break) this needs to be documented as depending on the client version, meaning modders can't rely on the callback being called.

**Comment by paramat** [comment]
I approve concept.

**Comment by Wuzzy2** [comment]
I briefly tested with my testing mod from the issue.
It worked as requested.

**Comment by paramat** [comment]
4381fe0a0a0921e6ba79c072045be2dc04be646a

**Pull request closed without merging**
