### PR TITLE
Add disclaimer to client_lua_api.md

### PR DESCRIPTION
**Pull request by rubenwardy**
also txt -> md

### CODE REVIEW

**Comment by Fixer-007** [comment]
"Mods are contained and ran solely on the server side. "

Typo?

**Comment by sofar** [comment]
Not a bug in this PR.

:+1: trivial

**Comment by sofar** [comment]
May want to get an OK on the `md` part of the patch from @nerzhul and @red-001 maybe?

**Comment by nerzhul** [comment]
@sofar i approved it on IRC yesterday. Okay for me, merging

**Comment by paramat** [comment]
This shold not have been changed to MD when all other docs, and lua_api.txt, are .txt.

**Pull request merged**
