### PR TITLE
Catch C++ -> Lua exceptions with PUC Lua

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
  - This PR aims to bring Lua API exception handling with PUC Lua in line with LuaJIT.
- How does the PR work?
  - A wrapper macro is added. It takes a `lua_CFunction` and returns a `lua_CFunction` that handles C++ exceptions. With LuaJIT this macro is a no-op. It is called on all Lua API functions.
  - Compiling Lua is C++ solves a separate issue from this. Without this PR, exceptions are caught, but the error object is a function instead of what it should be: the error message.
- Does it resolve any reported issue?
  - No.
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
  - No.
- If not a bug fix, why is this PR needed? What usecases does it solve?
  - This is a bug fix.

## To do

This PR is Ready for Review.

## How to test

1. Compile Minetest using the bundled Lua.
2. Enable devtest unit testing.
3. Put this code into a mod:
    ```lua
    local succeeded, message = pcall(minetest.get_content_id, "jkfdkjfkj")
    if not succeeded then minetest.log("error", message) end
    ```
3. Load a devtest world with the mod enabled.
4. The unit tests should pass.
5. You should see the error message generated by `minetest.get_content_id` but the world should not crash on startup.

### CODE REVIEW

**Comment by sfan5** [comment]
Huh, I thought this already worked on its own.

**Comment by TurkeyMcMac** [comment]
@sfan5 LuaJIT catches exceptions because of [these lines](https://github.com/minetest/minetest/blob/f5040707fe7cf9f24274379598527d6298c5818c/src/script/cpp_api/s_base.cpp#L105-L111). I expect the issue does not often manifest itself because (1) most people probably use LuaJIT and (2) `pcall` is not used very often to catch API function errors (AFAIK).

**Comment by SmallJoker** [comment]
This seems to be quite error-prone to manually call this function in all necessary places. Wouldn't following work as well?

```C++
// Wraps a global function in the script_exception_wrapper if needed
// With LuaJIT, script_exception_wrapper is already used through LUAJIT_MODE_WRAPCFUNC.
#if USE_LUAJIT == 0
#undef lua_pushcfunction
#define lua_pushcfunction(L,f) lua_pushcclosure(L, (f), 0)
#define lua_pushcfunction(L, f) lua_pushcclosure(L, [](lua_State *L) -> int { return script_exception_wrapper(L, f); }, 0)
#endif
```

According to LuaJIT's header files and http://www.lua.org/manual/5.1/manual.html, this is guaranteed to be a macro.

**Comment by TurkeyMcMac** [comment]
@SmallJoker In order to construct the wrapper function, the inner function must be constant/global. Changing `lua_pushcfunction` would make it fail to compile for some arguments. Here, for example: https://github.com/minetest/minetest/blob/e35cfa589a11bbfbdbe9c815553842b472da2b41/src/script/lua_api/l_base.cpp#L92-L101

**Comment by SmallJoker** [comment]
> In order to construct the wrapper function, the inner function must be constant/global.

Well then, couldn't you capture the function name like this? `[f](lua_State *L) -> int { ....`

**Comment by TurkeyMcMac** [comment]
The type `lua_CFunction` must be a plain C function, not a closure.

**Comment by TurkeyMcMac** [comment]
Another way would be something like this:

```cpp
#define lua_pushcfunction(L, f) ( \
    lua_pushcclosure(L, f, 0), \
    lua_pushcclosure(L, [](lua_State *L_) -> int { return script_exception_wrapper(L_, lua_tocfunction(L_, lua_upvalueindex(1))); }, 1) \
)
```

I don't know what the performance implications would be.

**Comment by sfan5** [comment]
I admit I didn't read the part that said "Compiling Lua is C++ would solve a separate issue from this" but it would be useful to have an explanation what separates this issue from the other and why.
The issue with your code sample isn't that the exception _isn't_ caught, the exception is incorrectly handled (`type(message)` ends up `"function"`).

**Comment by sfan5** [comment]
> Without this PR, exceptions are caught, but the error object is a function instead of what it should be: the error message.

So, do you know why that happens? I don't.

**Comment by TurkeyMcMac** [comment]
I don't know either, except that it's due to how Lua interacts with foreign C++ exceptions it catches. When Lua throws an exception, I think it stores the error object in the `lua_State`. When it catches a foreign exception, the error object in the Lua state is incorrect.

**Comment by TurkeyMcMac** [comment]
Can you try merging this branch into your local repo then test whether the issue persists?

**Comment by TurkeyMcMac** [comment]
A big benefit of compiling Lua as C++ is ensuring C++ destructors are called when a Lua error is thrown. I think this should be retained.

I may open a separate PR for the closure solution.

**Comment by sfan5** [comment]
> Can you try merging this branch into your local repo then test whether the issue persists?

It's fixed then.

> A big benefit of compiling Lua as C++ is ensuring C++ destructors are called when a Lua error is thrown. I think this should be retained.

I'd think as long as you wrap all cfunctions in `script_execution_wrapper` then C++ exceptions and destructors will work correctly.

**Comment by TurkeyMcMac** [comment]
> I'd think as long as you wrap all cfunctions in script_execution_wrapper then C++ exceptions and destructors will work correctly.

If Lua is not compiled as C++, it throws its exceptions using `longjmp`. This will bypass destructors. For example, if `luaL_checkstring` throws an error, some destructors may be missed.

**Comment by sfan5** [comment]
Ok, right. Then we're back at square one: it's impossible to make basic error handling work with plain Lua without patching Lua itself and _even_ if you do it's a huge bother.

**Comment by TurkeyMcMac** [comment]
I suppose patching Lua would be doable, and would probably be the cleanest solution. I'll look into it.

**Comment by sfan5** [comment]
I bet it's doable but distros will be unhappy that they cannot de-vendor Lua anymore.

**Comment by TurkeyMcMac** [comment]
Out of curiosity, which distros configure Minetest to use PUC Lua?

**Comment by sfan5** [comment]
* Debian/Ubuntu: [patch](https://salsa.debian.org/games-team/minetest/-/blob/master/debian/patches/rawlua.patch) but on [few architectures only](https://salsa.debian.org/games-team/minetest/-/blob/master/debian/control#L21)
* Gentoo: [patch](https://gitweb.gentoo.org/repo/gentoo.git/tree/games-action/minetest/files/minetest-5.4.1-system_puc_lua.patch), user choice

**Comment by TurkeyMcMac** [comment]
Closing in favor of https://github.com/minetest/minetest/pull/12445.

**Pull request closed without merging**
