### PR TITLE
Add secure require() function

### PR DESCRIPTION
**Pull request by rubenwardy**
This is required to include pure-Lua libraries without disabling the security sandbox, requiring an insecure environment, or having to massively modify the library.

Require is the defacto way of including another Lua file or module in Lua. The behaviour of require is as follows:

* Check to see if the package is already loaded. If so, return its previous return value (stored in `package._LOADED`)
* Search for the package in the the search path (`package.path`)
* If found, load the package use loadfile and store its return value in `package._LOADED` for latter usage

To make this function secure, it needs to be reimplemented with knowledge of mod security's safe paths. It also needs to use our own version of loadfile in order to prohibit bytecode and C libraries.

```
ERROR[Main]: ModError: Failed to load and run script from /home/x/dev/minetest/bin/../mods/xploit/init.lua:
ERROR[Main]: /home/x/dev/minetest/bin/../mods/xploit/init.lua:2: module 'socket' not found:
ERROR[Main]: 	blocked by mod security './socket.lua'
ERROR[Main]: 	blocked by mod security '/usr/share/luajit-2.0.5/socket.lua'
ERROR[Main]: 	blocked by mod security '/usr/local/share/lua/5.1/socket.lua'
ERROR[Main]: 	blocked by mod security '/usr/local/share/lua/5.1/socket/init.lua'
ERROR[Main]: 	blocked by mod security '/usr/share/lua/5.1/socket.lua'
ERROR[Main]: 	blocked by mod security '/usr/share/lua/5.1/socket/init.lua'
ERROR[Main]: 	no file '/home/x/dev/minetest/bin/../mods/xploit/socket.lua'
ERROR[Main]: stack traceback:
ERROR[Main]: 	[C]: in function 'require'
ERROR[Main]: 	/home/x/dev/minetest/bin/../mods/xploit/init.lua:2: in main chunk
ERROR[Main]: Check debug.txt for details.
```

## Todo

- [x] Fix vulnerability with cached required
- [x] Fix package insertion not working in CSM
- [x] Change module not found message to include `(blocked by security)` on blocked paths

## How to test

```lua
local function good(name)
	local status, err = pcall(function() require(name) end)
	if not status then
		minetest.log("error", "Failed: require(" .. name .. ")")
		minetest.log("error", err)
	else
		minetest.log("action", "Succeeded: require(" .. name .. ")")
	end
end

local function bad(name)
	local status, err = pcall(function() require(name) end)
	if status then
		minetest.log("error", "Should have failed: require(" .. name .. ")")
		minetest.log("error", err)
	else
		minetest.log("action", "Successfully failed: require(" .. name .. ")")
		minetest.log("action", err)
	end
end

local original_path = package.path

local function set_path(path)
	package.path = path
end

local function reset_path()
	package.path = original_path
end

set_path(minetest.get_modpath("reqtest"))
good("one")
good("two")

set_path("./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib/lua/5.1/?.lua;/usr/lib/lua/5.1/?/init.lua")
bad("socket")
reset_path()
```

### CODE REVIEW

**Comment by rubenwardy** [comment]
If it's not possible to dofile another mods lua file, then this introduces a vulnerability:

* Mod A requires a file as `require("a.foobar");`
* Mod B can now do `require("a.foobar");` and get the result of that file **without checks**

This could be fixed by storing `_LOADED` more securely and also including the result path

**Comment by nerzhul** [comment]
please note i'm interest about this because our dofile model is just old and obsolete. Require is the proper way to do good lua coding

**Comment by numberZero** [comment]
It will be very nice to have `require` in mods) Just note that binary package load is still an interesting feature that should be available to trusted mods, if enabled.
Also, mods might legitimately want to require() other ~libs~ mods’ files sometimes, although that’s not how it works currently.

**Comment by rubenwardy** [comment]
Trusted packages can use the insecure require to load binary packages.  I'm not sure how to let mods require other mods' files, I guess the mod could whitelist files in its mod.conf file maybe. I'd like to leave that to a future PR though

**Comment by rubenwardy** [comment]
So, I'm unsure of what to do. In normal Lua, require will only run the module once and cache the result until the vm exits. This is fine, as everything is trusted. In our sandboxed Lua with untrusted mods, this would result in a mod being able to get the returned value of another mod's include as require would return the cached value.

I mean, server-side modding is pretty insecure anyway. It's very easy to leak an insecure environment reference if you don't know what you're doing.

Possible solutions:

* **Per-mod require** - Each mod has it's own returned value cache. This would introduce a lot of issues when multiple mods use the same library which modifies the global environment or has a resource handle.
* **Store path with cached value** - Two mods may bundle the same library, but only one would be allowed to use it.
* **Give up** - add a big fat warning

**Comment by numberZero** [comment]
Ugh, GH ignored my email... Okay, here is it:

As long as mods share the whole Lua state, security is impossible. Separate environments (coroutines or even just dedicated _G’s may be fine) are mandatory for that. Separating states would also give the opportunity to separate threads as well.

So, as we may not enforce security, the library should not put much things into the table which it returns. Namely, it should only put functions and maybe some primitive values, and protect it the same way registered_nodes are protected. Of course that requires metatable manipulations to be unavailable to untrusted mods.

P.S. For real sandbox, see https://gitlab.com/numzero/libluabox =)

**Comment by rubenwardy** [comment]
Ok, I've decided that all mods should share the values returned by `require()`. If a mod wants to force a particular version, they can temporarily change `package._LOADED`

**Comment by SmallJoker** [comment]
So is this PR only missing the documentation?

**Comment by rubenwardy** [comment]
I wanted to warn that `require()` shouldn't be used by mods to load normal mod files, but I'm not sure if this needs to be documented. There's also no place to document general Lua things, except for `[Helper functions]`.

**Comment by rubenwardy** [comment]
Added a test script to the OP, I've also found a bug because of it

**Comment by rubenwardy** [comment]
The error was due to the code trying to load a directory as a Lua file, because the `package.path` was wrong - it was `X` rather than `X/?.lua;X/?/init.lua`

**Comment by rubenwardy** [comment]
Fixed the crash

**Comment by rubenwardy** [comment]
I've decided to go with proper unit tests for now using #9184, which makes this PR slightly less required given that I made this so I could do integration tests. This could still be good to have, though

**Comment by rubenwardy** [comment]
Closing as there seems to be no interest at this time

**Pull request closed without merging**
