### PR TITLE
Some new translations, some tokens improved

### PR DESCRIPTION
**Pull request by balacobaco**
Some new translations, some tokens improved

### CODE REVIEW

**Comment by PilzAdam** [comment]
Could you please use our web-interface to translate? https://hosted.weblate.org/projects/minetest/minetest/

**Comment by rubenwardy** [comment]
He can't: https://forum.minetest.net/viewtopic.php?f=3&t=13460

**Comment by kilbith** [comment]
Obscure report. Not our problem. To close.

**Comment by PilzAdam** [comment]
@kilbith not obscure; I have the similar problems.

**Comment by kilbith** [comment]
@PilzAdam Then an issue should be opened. Those PRs are closed on sight usually.

**Comment by est31** [comment]
https://github.com/nijel/weblate/issues/886

**Comment by est31** [comment]
I've pushed the commits in weblate to this repo, so that you can rebase onto them.

**Comment by est31** [comment]
Still needing a rebase.

**Comment by SmallJoker** [comment]
Dead pull. Please reopen once it's rebased.

**Pull request closed without merging**
