### PR TITLE
Snake case for screen options in minetest.conf

### PR DESCRIPTION
**Pull request by Dumbeldor**
@nerzhul

### CODE REVIEW

**Comment by SmallJoker** [comment]
How about backwards compability?

**Comment by Dumbeldor** [comment]
I do not know. Better not change?

**Comment by Dumbeldor** [comment]
But I do not think that's a problem. It just reinitialises the config that the player had.

**Comment by JosephTheTank13** [comment]
Nice

**Comment by nerzhul** [comment]
Seems LGTM, but do we include this or not in this release, that's the question.
@minetest/team-minetest please answer to this question :)

**Comment by SmallJoker** [comment]
Looks good to me aswell. This PR is rather trivial and thus, unlikely to have side effects.

**Comment by ShadowNinja** [comment]
Looks good, I'd push it to after 0.4.16 though.

**Comment by paramat** [comment]
Missing docs update.

**Pull request merged**
