### PR TITLE
Re-add Droid Sans as fallback font (Reverts part of eb490)

### LINKED ISSUE #5231: Chinese & Japanese characters don't appear
caused by #5230 

which also replaced droidsans for no reason
it's licensed under apache 2.0: https://github.com/minetest/minetest/blob/f17c9c45dc30a388675d46418d278a4a029206e2/README.txt#L552

### PR DESCRIPTION
**Pull request by sofar**
This reverts the removal of Droid Sans as fallback font. The
license for this font was never an issue. The replacement
Tinos font is not nearly as complete as this font, and can't
function as a replacement.

I've attempted to fix all the attribution and license strings,
and used the strings as provided by e.g. google for attribution
to make sure they're correct.

Last, I've removed a bunch of executable bits on files that do
not need them.

Fixes #5231

### CODE REVIEW

**Comment by sofar** [comment]
@sfan5 please check!

**Comment by sfan5** [comment]
<pre>
% wget -qO- https://github.com/minetest/minetest/pull/5234.patch | git am
Applying: Revert part of eb49009d023e6e3b5d59a97b8fb5fed5eee83296 (#5230)
.git/rebase-apply/patch:540: trailing whitespace.
  
.git/rebase-apply/patch:542: trailing whitespace.
  
error: patch failed: fonts/Arimo-LICENSE.txt:1
error: fonts/Arimo-LICENSE.txt: patch does not apply
error: patch failed: fonts/Cousine-LICENSE.txt:1
error: fonts/Cousine-LICENSE.txt: patch does not apply
error: patch failed: fonts/Tinos-LICENSE.txt:1
error: fonts/Tinos-LICENSE.txt: patch does not apply
Patch failed at 0001 Revert part of eb49009d023e6e3b5d59a97b8fb5fed5eee83296 (#5230)
</pre>

**Comment by sofar** [comment]
Shrug, that's just `git am` being dumb, I have the exact same issue if I try to do that. Even github doesn't complain about it not applying...

I fixed the trailing whitespace, though.

**Comment by rubenwardy** [comment]
git am royally sucks

```
git checkout HEAD~10
git checkout -b branchname
git pull https://github.com/sofar/minetest.git fonts3
git pull upstream master --rebase
```

**Comment by sfan5** [comment]
This makes chinese characters work but causes non-chinese characters to disappearn (with `language = zh_CN`)

**Comment by sofar** [comment]
Interesting, you'd think that the fallback-full font would have all the characters. No idea how to progress from this.

**Comment by sfan5** [comment]
Tested and works :+1:

can be merged in this state
<b>HOWEVER</b> the community might want to comment on the font choices (aka whether we should move back to Liberation Sans/Mono)

**Comment by paramat** [comment]
Tried to merge using git am but did not apply.

**Pull request merged**
