### PR TITLE
Add nick colors to chat

### PR DESCRIPTION
**Pull request by rubenwardy**
Based on @SmallJoker's [colored_names](https://github.com/SmallJoker/colored_names/blob/master/init.lua) mod.

This greatly improves chat readability imo.

image

## To do

This PR is Ready for Review.

### CODE REVIEW

**Comment by SmallJoker** [comment]
> "This really should be an engine feature though" ~ rubenwardy, 2018

This CSM belongs to my default setup for years, hence I totally forgot that other people might like this to be integrated into Minetest. Thanks for the PR.

**Comment by Wuzzy2** [comment]
:-1: because it cannot be disabled.

**Comment by rubenwardy** [comment]
It can be disabled server-side

**Comment by Wuzzy2** [comment]
That's even worse. :-( Ideally, how the chat names look to you should be a client-side setting.

**Comment by hlqkj** [comment]
> :-1: because it cannot be disabled.

Up. What if one doesn't like the colors? Or has color-blindness too...

That aside I like it! Personally I'd like more it you leave the `>` and `<` chats white.

**Comment by EliasFleckenstein03** [comment]
Why exactly does it need to be a part of the builtin rather than a mod?

**Comment by benrob0329** [comment]
This does seem like more of a game-level issue, as different games will want to do different things with the chat colors (such as mentions, multiple channels, rank, etc)

**Comment by rubenwardy** [comment]
It's already possible for games to do this, this is about better defaults and improved experience

**Comment by nerzhul** [comment]
for me it's a client side setting, clearly not a server side one. No need server to modify the chat. What about the interaction with the CSM chat mods too ?
:-1: for me. It's clearly a feature which must be handled on CSM side. In the core CSM if you prefer than a mod, but warning, if you add it in core, it's clearly not in the path that mods should handle everything, and we may re-integrate some "game-friendly" features in core :)

**Comment by rubenwardy** [comment]
I'm happy to look into making this a client feature, but remember that CSM is not intended for user modifications, but for more server/game possibilities

**Pull request closed without merging**
