### PR TITLE
 Update minetest.conf.example and settings strings and locale files

### PR DESCRIPTION
**Pull request by Wuzzy2**
Because some of the advanced settings were not translatable after the previous update.

Scripts used:

- The bottom of `builtin/mainmenu/dlg_settings_advanced.lua`
- `util/updatepo.sh`

### CODE REVIEW

**Comment by paramat** [comment]
LINT complaints are unrelated.
@rubenwardy do merge if you're sure this is correct (it seems so).

**Comment by paramat** [comment]
:+1:

**Comment by nerzhul** [comment]
Wtf updatepo should never be run as the regular user to prevent bad code stats...

**Comment by Wuzzy2** [comment]
Sorry. :-(

**Comment by paramat** [comment]
Oops sorry my fault.

**Pull request merged**
