### PR TITLE
Silence invalid clang format warnings in guiScrollBar.cpp

### PR DESCRIPTION
**Pull request by paramat**
Also fix order of mapgen files in whitelist.

### CODE REVIEW

**Comment by nerzhul** [comment]
if you make linter useless just drop the code rules and merge code without lint.

**Comment by stujones11** [comment]
I actually took great care to make sure this file did pass the lint check. It seems pointless to me even bothering with this if new files are to be whitelisted because of a pointless style change in a subsequent commit.

**Comment by paramat** [comment]
Silly comment nerzhul. The linter is already mostly useless anyway.

stujones11, making sure code passes the lint check is usually a very bad idea, because 95% of it's requests are ridiculous and make code less readable, as a good coder i'm sure you've noticed.
The valid requests should be attended to, the rest ignored by either whitelisting just before merge, or using 'clang format on/off' in the code (which i prefer wasn't used to avoid the mess).

**Comment by ClobberXD** [comment]
> because 95% of it's requests are ridiculous and make code less readable

Couldn't it be fine-tuned to match MT's code style better?

**Comment by SmallJoker** [comment]
@ClobberXD Many tried, many failed. It does not offer enough parameters to adjust it exactly to our code style.

**Comment by ClobberXD** [comment]
Wow, that sucks. But why then, are we using a LINTER whose requests are invalid 95% of the time? o_O

Should we maybe start looking for alternatives to clang-format?

**Pull request merged**
