### PR TITLE
Fix texture tear issue

### PR DESCRIPTION
**Pull request by RealBadAngel**
Waiting to get reports if it fixes the issue for other users.

### CODE REVIEW

**Comment by Fixer-007** [comment]
I will test it, maybe someone compiles windows binaries for it :+1:

**Comment by RHRhino** [comment]
**YES IT WORKS FOR ME TOO!** :+1: :smile:

**Comment by HybridDog** [comment]
l didn't know minetest uses zbuffer

**Comment by paramat** [comment]
:+1:

**Comment by nerzhul** [comment]
:+1:

**Comment by est31** [comment]
52eea799285998d9d9595945f89c27a0be64b090

**Pull request closed without merging**
