### PR TITLE
lua_api.txt: Remove tooltip checkbox[] element

### PR DESCRIPTION
**Pull request by everamzah**
https://github.com/minetest/minetest/issues/4317

### CODE REVIEW

**Comment by rubenwardy** [comment]
If it was depreciated, then you should add a note about it so that if someone comes wondering what the parameter in an element does, they can find out

**Comment by everamzah** [comment]
It straight up does not work, and results in a warning message printed on the screen.
screenshot_20160714_104907


That is a different meaning to deprecated?

**Comment by rubenwardy** [comment]
oh, ok :+1:

**Comment by paramat** [comment]
:+1:

**Comment by paramat** [comment]
97c763158c3efd733bca1b4b46fb82c135df09f7

**Pull request closed without merging**
