### PR TITLE
Light space perspective shadow mapping

### LINKED ISSUE #11358: Jagged north-to-south-aligned shadow edges
##### Minetest version
Minetest engine/client is at git commit dc165fe9, master branch, and was built thusly:

<details><summary>[Show build script...]</summary>

```bash
#!/bin/bash

# If needed, compile and install MT Irrlicht
# ~/Scripts/build-Irrlicht-MT.sh

pushd .

export CXXFLAGS="-O3"

cd /home/vanessa/Minetest-related/minetest-engine
rm -f CMakeCache.txt

make clean
cmake . -DRUN_IN_PLACE=0 -DCMAKE_BUILD_TYPE=Release \
	-DENABLE_FREETYPE=true -DENABLE_LEVELDB=true \
	-DENABLE_GETTEXT=true \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DIRRLICHT_LIBRARY=/usr/lib/x86_64-linux-gnu/libIrrlichtMt.so \
	-DIRRLICHT_INCLUDE_DIR=/usr/include/irrlichtmt/
make -j8

# install them

echo "sudo make install..."
sudo make install

popd
```
</details>

MInetest-Irrlicht is at git commit `d7127df9`, master branch, and was built thusly:
<details><summary>[Show build script...]</summary>

```bash
#!/bin/bash

pushd .

export CXXFLAGS="-O3"

# Build MT's fork of irrlicht first

cd /home/vanessa/Minetest-related/irrlicht-mt-fork/
rm -f CMakeCache.txt

cmake . -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr
make clean
make -j8
echo "sudo make install irrlicht..."
sudo make install

popd
```
</details>

##### OS / Hardware

Operating system:  Debian "bullseye"
CPU: Phenom II X6 1055T, 2.8 GHz

GPU model: AMD R9 280X (official `amdgpu` driver)
OpenGL version: 4.6

##### Summary

(In all images below, my player model is facing east, and the game time is locked at 06:00 am, unless otherwise indicated)

The edges of shadows which run north-to-south, that is, shadows cast by a horizontal strip of nodes such as a ledge or wall running north-to-south, have a rather bad jagged look.

Shadow edges running east to west, such as that produced by a tall column or pole, mostly look okay, with only a slight ripple that probably wouldn't be noticeable in a normal game setting, if one isn't looking for them.

For example:

image

Here, I'm looking straight down from a height of about 27 meters from the surface.  Near the top of the image, you can see jagged north-to-south edges formed by the terrain, while closer to the bottom of the image, you can see two columns casting shadows with long east-to-west edges.

Reminds me of a cross-section of a Fresnel lens:

image
<sup>(Image credit:  https://en.wikipedia.org/wiki/Fresnel_lens#/media/File:Fresnel_lens.svg )</sup>

Getting a little closer to one of the jagged shadows:

image

On all edges where it's apparent, that central bit (i.e. the center of the "Fresnel lens cross-section" effect) where the direction of the jaggies switches) follows when I move around, but always stays aligned along north-to-south shadow edges.

The higher-up I am, the more jagged the edges look, because the on-screen size of the jaggies stays the same while the terrain shrinks away "under" them (that is, compared to the nodes themselves, the jaggies are proportionally huge at larger distances).  Conversely, the closer I am, the less-pronounced the jaggies get (i.e. proportionally smaller relative to the odes).  For example:

image

The closer the game time is to noon, the straighter the jagged edges become.  Here, for example, is a small overhang at 11:00 am:

image

The smaller the object, the fewer jagged peaks there are, so on small stuff like signs, the shadows look bent or curved, even though they technically are not.  For example (game time is set to 08:00am):

image

##### Steps to reproduce

Set your shader settings thus:
```
enable_waving_water = true
enable_waving_plants = true
enable_waving_leaves = false

enable_dynamic_shadows = true
shadow_map_color = false
shadow_filters = 1
shadow_levels = 3
shadow_map_texture_size = 2048
shadow_strength = 0.4
shadow_map_texture_32bit = true
shadow_map_max_distance = 350
shadow_soft_radius = 1
```

Load any world.  Shown above is just a random minetest_game test world.

### PR DESCRIPTION
**Pull request by x2048**
This PR adds Light Space Perspective Shadow Mapping based on [work of Michael Wimmer et al.](https://www.cg.tuwien.ac.at/research/vr/lispsm/shadows_egsr2004_revised.pdf).

The goal is to improve the quality of shadow maps by using more of the texture surface while keeping single-pass shadow generation process. The approach also removes the distortion causing 'curved' SM texels.

The intent of the PR is to improve the quality of shadows specifically at Very Low and Low presets that use low-resolution SM texture and, combined with #11747, resolve or improve #11762. It also resolves #11358 at Very Low preset and improves  #11743 for more quality presets.

## LiSPSM

LiSPSM combines Uniform and Perspective Shadow Maps by manipulating the light frustum to match the perspective of player's camera as close as possible in order to increase the density of SM texels close to the player.

Strength of perspective transformation is controlled by parameter n, which is calculated from the player's camera parameters and then blended with 'infinity' (1/1E5) based on angle between player's view and light direction.

## To do

This PR is Ready for Review.

items in the PR:
* [x] Implement light frustum calculation
* [x] Remove perspective distortion from SM shaders and shadow sampling
* [x] Remove perspective distortion from PCF and Poisson filters
* [ ] Tune the light frustum for constant pixel density

## How to test

* Turn on shadow mapping and set soft shadow radius to 1.0 (minimum and default)
* Start a game and observe the shadows.
* Shadow edges should appear uniformly sharp, also for distant shadows.
* While jagged at some presets, edges do not have Fresnel lens pattern (see #11358)

### CODE REVIEW

**Comment by x2048** [comment]
@hecktest I know you had an [opinion](https://github.com/minetest/minetest/issues/11600#issuecomment-919392384) on shadow mapping. What do you think about this change?

**Comment by lhofhansl** [comment]
Tested and works fine generally.

The main observation is the shadow quality is now very view angle dependent. When looking from roughly the direction of the sun the shadows look great, when looking from angles opposite to the sun it is much worse (shadow fade, get jagged, etc).
Seems to be faster overall.

**Comment by x2048** [comment]
Yesm there is a challenge in tuning the light frustum so that the quality of the shadow is consistent. That's what I am working on right now.

**Comment by Andrey2470T** [comment]
Tested. Great work!

Advantages:

- **Pretty good FPS even with ultra-high quality enabled**. This is main thing that wondered me, FPS don't drop so slowly as in the Liso's implementation. Even with ultra-high quality it holds to the adequate values (30-50 grades), with ultra and let alone lower qualities it runs at all 60 as if it was disabled.
-  **The shadows move almost ideally smoothly**. Comparing to the Liso's PR they move slower and without jerks. This is nice.

Shortages:

- **Bad quality generally**. The shadows much twitch and wave when moving, creating a distinct effect of the ripple on the water. I noticed this effect decreases at moving away from them and can disappear quite at certain distance. Also, the ripple is very dependent from the player view angle. At around 0 degrees if counting off from the direction to the sun, nothing is notable. At +90/-90 degrees, there are sharp waving edges on the shadows. Well and at +180/-180, they stay less abrupt, however the ripple effect appears worse.

>
>The intent of the PR is to improve the quality of shadows specifically at Very Low and Low presets
>
Actually, at low/very low the implementation works much worse than higher. The edges of the shadows stay very "pixelated" and sharp. So, the lower quality the worse the shadows.

Also, I ocassionally discovered in this PR the digging animation of the player is actually broken. It happens only in your branch, the default minetest and minetest_game works as expected. The animation doesn't play when the player is standing, but only when moving. Any other sort of the default animation works fine:


https://user-images.githubusercontent.com/25750346/143954055-7e2ef0a6-8ff8-41f5-ba6b-86eb0ce256c8.mp4

**Comment by lhofhansl** [comment]
@x2048 And thanks for continuing to work on this. I realize the atmosphere around this has been ... not perfect.

Happy to review and test an update if/when you have one.

**Comment by x2048** [comment]
Sure. I have been keeping silence, and work on this has slowed down, but the ambition to improve shadow mapping is still there.

I am experimenting with light frustum to get consistent shadow quality, and I'll share once I get results I'm happy with.

**Comment by x2048** [comment]
@lhofhansl @Andrey2470T I've done some improvements and rebased to the latest master.
* There should be less of shadow dancing (it cannot be eliminated completely, according to the paper)
* The shadow quality should now be more consistent on average, except when looking exactly away from the sun.
* Presets have been corrected to match the actual shadow render distance between LiSPSM and PSM in the master branch.

**Comment by Andrey2470T** [comment]
Started testing today. As soon as I had joined the world I noticed the strange thing at once: the time actually just... stopped. The sun looks like static and also `/time` cmd displays always `06:00` current time. Does this problem relate to your PR?

**Comment by x2048** [comment]
@Andrey2470T can you check your time_speed setting to be 72 (the default) and not 0? Setting time_speed to 0 will freeze the time, and it is not part of this PR.

**Comment by Andrey2470T** [comment]
Yes, I have checked and it was really set to 0. I just wonder because I didn't change that setting.

Generally, to be honest I didn't notice any perceptible enhancement of the shadow quality. From your last commit, I discovered only two new things: 1. The player digging animation got fixed. 2. The shadows blinkings is a new bug. They peridically appear and disappear. As I understood, it depends on the player view angle relatively to the sun/moon position. If angle between the player view direction and the sun direction is around less 45 degrees, this bug doesn't appear, otherwise it does:

https://user-images.githubusercontent.com/25750346/147852149-0b31db8e-42e0-45db-bb7f-3d8f02edb053.mp4

**Comment by x2048** [comment]
@Andrey2470T I tried but could not reproduce the issue you are facing. From the video, it looks like an occlusion culling problem similar to the one in master. I consciously disabled occlusion culling for shadow mapping in the latest commit to remove the problem.

**Comment by lhofhansl** [comment]
Will try today. I doubt that this change has the ability to stop time :)

**Comment by lhofhansl** [comment]
I really do not think that we should disable occlusion culling outright. That has enormous(!) performance implications.
Also note that the server performs occlusion culling as well, so blocks not visible from the Camera are not even sent to the client.

We can consider disabling occlusion culling when shadows are enabled (at least on the client).

(Unrelated: See the IRC discussion about making you a core-dev.)

**Comment by lhofhansl** [comment]
Close shadows are very jittery now. I.e. look at the players own shadow while standing on the ground.

**Comment by lhofhansl** [comment]
Thanks for the update... The last version causes strange effects where based on viewing angle shadows appear or disappear (sometimes partially, sometimes totally).

**Comment by x2048** [comment]
This is one of the basic limitations of the LiSPSM approach compared to non-linear perspective distortion that we use today. When looking away from the sun (e.g. at your own shadow), it degrades to uniform shadow map, and to keep the shadow quality close to the viewer I have to narrow down the light frustum. As a result shadow map will cover a much smaller area compared to the case when the sun is on the side or above (90 degrees between sun light and camera view vectors). So you can think of the shadow area reduction as a necessary measure to keep the quality of the shadow.

I have one idea I would like to try to improve the situation, but eventually we need to make a decision whether LiSPSM is worth it quality-wise, so that I don't spend more time on something that is not going to be adopted.

**Comment by Andrey2470T** [comment]
The shadows got now a strange glitch: they (or their parts) smoothly appear and disappear depending on the player's perspective (see videos):

https://user-images.githubusercontent.com/25750346/148702742-cba68ed1-ed1d-48a3-9e7f-8daf299c59f4.mp4

https://user-images.githubusercontent.com/25750346/148702762-a3954b45-4827-4512-b176-46d7c17beb90.mp4

**Comment by x2048** [comment]
@Andrey2470T Can I have your world seed and position? This is not something I observed in development.

**Comment by Andrey2470T** [comment]
I didn't enter any seed when creating the world, so it doesn't have that. What do you mean by 'position'? Position of what?

**Comment by x2048** [comment]
Seed and position are displayed in the debug info if you press F5.

**Comment by Andrey2470T** [comment]
Seed: 8758985475942908480. Position: (x = -54.9, y = 21.7, z = -56.5).

**Comment by lhofhansl** [comment]
@x2048 This one is different. The shadow flickers on and off, sometimes is displayed 1/2 only, when you just change the direction of the camera a few degrees. I'll attach an image when I get a chance.

**Comment by x2048** [comment]
@Andrey2470T @lhofhansl  I found the place on the videos, but I could not reproduce the issue.

I suspect it's the latest change in the shaders, 0b4d7fa, so I've reverted it. Can you try now?

**Comment by Andrey2470T** [comment]
@x2048 Thanks, I see it is fixed now, but there are intermittent blinks of the shadows:

https://user-images.githubusercontent.com/25750346/149414225-017582aa-e228-4692-8d8d-b148551b2944.mp4

**Comment by lhofhansl** [comment]
Any chance for rebasing?

**Comment by x2048** [comment]
As soon as I get to my laptop...

**Comment by x2048** [comment]
@Andrey2470T I cannot reproduce the flicker. Do you hane the mapgen, seed, position and time?

**Comment by Andrey2470T** [comment]
@x2048 yes, I provided you that info above: https://github.com/minetest/minetest/pull/11782#issuecomment-1010378511

**Comment by x2048** [comment]
@lhofhansl  There were no conflicts with the master, but still rebased.

**Comment by lhofhansl** [comment]
(Sorry if the rebase was unnecessary.)

This looks much better! No more weird flickering (at least not more than before), no 1/2 shadows rendered, etc.
There's still angle-dependent brightness, but that can be mitigated - it seems - with the shadow render distance; and looks like this is on your TODO list anyway.

How do we decide to replace the current shadow implementation with this one? What would you look for to decide?

**Comment by Andrey2470T** [comment]
Since your last commit 0c9fc8c589579386ceee2089cf3a7693f98e58c5, the shadows are casted only from objects, for some reason nodes don't cast them anymore. :/

Also, I see those blinks are finally fixed! Thanks.

**Comment by x2048** [comment]
@Andrey2470T  I cannot reproduce the issue in my worlds. Does it appear in any world you play or only in a specific case (mapgen+seed+position)?

**Comment by Andrey2470T** [comment]
@x2048 yes, in any one.

**Comment by Andrey2470T** [comment]
And as a proof of that, I can provide a next screenshot:
Снимок экрана от 2022-02-15 13-01-07

In the given case, the sun is located behind of you. Therefore, you see a shadow that you are casting in front of you. But those dirt with grass blocks and grass plants also should cast them, but as you see they don't cast. That's obviously a bug.

**Comment by x2048** [comment]
@Andrey2470T So it's primarily when you look at your own shadow, but not when you look "to the side", right?

**Comment by Andrey2470T** [comment]
This happens not depending on where I am looking at.

**Comment by Andrey2470T** [comment]
@x2048 do you have that bug? Without fixing that, it is even impossible to test the shadows with the newest changes because they are just not rendered.

**Comment by x2048** [comment]
@Andrey2470T I cannot reproduce the problem, shadows are rendered in all worlds I try. I increased distance to the light since I noticed it was causing flicker with distant shadows.

**Comment by x2048** [comment]
@Andrey2470T I cannot reproduce the problem, shadows are rendered in all worlds I try. I increased distance to the light since I noticed it was causing flicker with distant shadows.

**Comment by lhofhansl** [comment]
@x2048 Do you have energy continuing this one?

**Comment by x2048** [comment]
@lhofhansl As mentioned on IRC, I had to change priorities away from Minetest for a period. I plan to get back and focus on shadows and brightness API.

I will also move certain enhancements from this branch to the main. As for LiSPSM itself, there are clear issues with shadow quality that are difficult to overcome, and performance benefits are not that significant. Now I'd like to make adjustments to frustum in the main branch to improve the shadow quality.

**Comment by Andrey2470T** [comment]
@x2048 do you see the shadows rendered as before in the newest commit? Personally, I can not see shadows casted from nodes, but only from objects. Also, does anybody have the same problem at all, except me or is this particular only for me?

**Comment by x2048** [comment]
@Andrey2470T Yes, all shadows render normally for me.

**Comment by x2048** [comment]
@Andrey2470T I upgraded to the latest Irrlicht, and all map shadows render fine.

I suggest to stop spending time on this PR, since #12166 is now the preferred PR, adding a similar improvement without the such severe edge cases.

**Comment by x2048** [comment]
Most fixes from this PR have been merged into the master branch, which also received a better distortion of SM texture.

**Pull request closed without merging**
