### PR TITLE
Give the ASCII console splash a facelift

### PR DESCRIPTION
**Pull request by GreenXenith**
The current console splash is super inconsistent and messy.  
Top: Old; Bottom: New
image

Changes:
* Make letters consistently thicc
* Give `t`s a corner-dot (right side for balance)
* Add drips (`\/`) to vertical parts (`i` and `t`s)
* Remove drips from not-vertical parts (`e`s and `s`)
* Move the `s` stinger (`>`) to the correct place
* Make the `t`s crosses not cut into them
* Fix `e` shapes (remove side `_` on first, fix middle `\` on second)

### CODE REVIEW

**Review by Df458 — APPROVED** [review]
Tested, works. I'd like to give people a chance voice their opinions before we merge, but I'm fine with this.

**Comment by SwissalpS** [comment]
Why is the corner dot above the 'i' on the left while above the 't's it's on the right?

Otherwise I welcome the change :D

**Comment by GreenXenith** [comment]
> Why is the corner dot above the 'i' on the left while above the 't's it's on the right?

> (right side for balance)

**Comment by SwissalpS** [comment]
> And also it fits better on a sharp right angle instead of the slanted side.

Wouldn't it look better if all were on the right side though? No slants there and would be consistant direction of light.

**Comment by Desour** [comment]
The current seems to be the "graffiti" font.

These two generators seem to give about the same output:
https://patorjk.com/software/taag/#p=display&f=Graffiti&t=minetest
http://www.network-science.de/ascii/

**Comment by GreenXenith** [comment]
> Wouldn't it look better if all were on the right side though?

That's a fair point. I'll move the dot.

> The current seems to be the "graffiti" font.
> These two generators seem to give about the same output:

Makes sense. But now its graffiti-redo :)

This is probably worth squashing on merge.

**Comment by Zughy** [comment]
Go for it, it's trivial and nicer than before

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
