### PR TITLE
Log deprecated messages only once per line

### PR DESCRIPTION
**Pull request by SmallJoker**
- Default to deprecated handling `log`
- New `minetest.log("deprecated", "msg", <depth>)` optional parameter

**Sample terminal output** (full backtrace only visible with log level `info`)
```
Loaded texture: /data/Minetest/run/games/subgames/menu/icon.png
2018-12-09 13:33:26: WARNING[Main]: Function 'setting_getbool': Call to deprecated function. Instead, use the minetest.settings object. (at /data/Minetest/run/bin/../mods/worldedit/worldedit/init.lua:45)
[OK] Mesecons
2018-12-09 13:33:26: WARNING[Main]: Function 'set_mapgen_params': set_mapgen_params is deprecated; use set_mapgen_setting instead (at /data/Minetest/run/bin/../mods/lab/init.lua:22)
2018-12-09 13:33:26: WARNING[Main]: core.env:[...] is deprecated and should be replaced with core.[...] (at /data/Minetest/run/bin/../mods/lab/init.lua:23)
<SNIP MT LOGO>
2018-12-09 13:33:29: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2018-12-09 13:33:29: WARNING[Server]: Function 'get_entity_name': Deprecated call to "get_entity_name (at /data/Minetest/run/bin/../mods/lab/init.lua:7)
2018-12-09 13:33:29: WARNING[Server]: Function 'get_look_pitch': Deprecated call to get_look_pitch, use get_look_vertical instead (at /data/Minetest/run/bin/../mods/lab/init.lua:8)
2018-12-09 13:33:29: WARNING[Server]: Function 'add_particle': Deprecated add_particle call with individual parameters instead of definition (at /data/Minetest/run/bin/../mods/lab/init.lua:18)
2018-12-09 13:33:30: WARNING[Server]: Function 'get_entity_name': Deprecated call to "get_entity_name (at /data/Minetest/run/bin/../mods/lab/init.lua:33)
2018-12-09 13:33:30: WARNING[Server]: Function 'get_look_pitch': Deprecated call to get_look_pitch, use get_look_vertical instead (at /data/Minetest/run/bin/../mods/lab/init.lua:34)
2018-12-09 13:33:33: WARNING[Main]: Deprecated formspec element "invsize" is used
```

**Test script**
```Lua
local players = {}

core.register_on_joinplayer(function(player)
	local inv = player:get_inventory()
	inv:set_list("hand", {"default:cobble"})
	players[#players + 1] = player
	player:get_entity_name()
	player:get_look_pitch()

	core.after(5, function()
    	core.show_formspec(player:get_player_name(), "lab:testy",
    		"invsize[9,7]"..
    		"no_prepends[]"..
    		"list[current_player;hand;8,6;1,1;]"
    	)
	end)
	
	core.add_particle(vector.new(), vector.new(), 
		vector.new(), 20, 1, false, "default_dirt.png")
end)

core.set_mapgen_params()
core.env:set_mapgen_params()

local time = 0
core.register_globalstep(function(dtime)
	time = time + dtime
	if time < 3 then
		return
	end
	time = time - 3
	for i, player in ipairs(players) do
		player:get_entity_name()
		player:get_look_pitch()
	end
end)
```

### CODE REVIEW

**Comment by nerzhul** [comment]
Nice job

**Comment by SmallJoker** [comment]
Rebased and reverted the default setting value of the deprecated API handling (due to #8322).

**Comment by SmallJoker** [comment]
Is anyone interested in this PR? Asking to see whether it's worth rebasing.

**Comment by sfan5** [comment]
The depth parameter to `core.log()` sounds useful, line logging isn't really necessary IMO.

**Comment by SmallJoker** [comment]
No future.

**Pull request closed without merging**
