### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by rubenwardy**
Created using the following bash script.

I went as far as a score of 4, which means to appear on the credits, since 0.4.16 you need to have either:

* Made a commit with more than 100 changes
* OR made at least 4 commits

-----------

```sh
#!/bin/bash

OUT=$PWD
rm $OUT/results.txt

TMP=$PWD/tmp
mkdir -p $TMP
mkdir -p $TMP/emails
rm $TMP/*

merge() {
	echo Merging $1 into $2
	cat "$TMP/$1.dat" >> "$TMP/$2.dat"
	rm "$TMP/$1.dat"
}

cd ~/dev/minetest
entries=`git log --pretty=format:"%h	%an	%ae" "80dc961..HEAD"`

echo "Gathering commit data..."

IFS=$'\n'
for line in $entries
do
	hash=$(echo "$line" | cut -f1)
	author=$(echo "$line" | cut -f2 | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
	email=$(echo "$line" | cut -f3)
	email_safe=$(echo "$email" | sed 's/@/.at./g' | tr -dc '[:alnum:].' | tr '[:upper:]' '[:lower:]')

	if [ -f "$TMP/emails/$email_safe.email" ]; then
		author=$(cat $TMP/emails/$email_safe.email | sed 's/^ *//;s/ *$//')
	fi
	echo $author > $TMP/emails/$email_safe.email

	commit=$(git show $hash --numstat --pretty=format:"")

	if echo $commit | grep -iq ".cpp\|.h\|.lua\|.cmake\|.gradle\|Makefile"; then
		commit=$(echo "$commit" | sed 's/[^0-9\t ]*//g' | sed 's/[\t ]/\n/g' )
		lines=$(echo "$commit" | awk '{s+=$1} END {print s}')
		# echo $lines
		if (( $lines > 3000 )); then
			echo "30" >> "$TMP/$author.dat"
		elif (( $lines > 1000 )); then
			echo "20" >> "$TMP/$author.dat"
		elif (( $lines > 100 )); then
			echo "10" >> "$TMP/$author.dat"
		else
			echo "1" >> "$TMP/$author.dat"
		fi
	fi
done || exit $?

merge you hybriddog
merge locblot loicblot
merge dnieljuhsz juhdanad
merge vitaliy numberzero
merge andrewward rubenwardy
merge paulouellette pauloue
merge jeanpatrickguerrero kilbith
merge vanessadannenberg vanessae
merge anands clobberxd
merge aukekok sofar
merge nathanalcourant ekdohibs
rm $TMP/translations.dat
rm $TMP/updatescript.dat

echo "Summing..."

cd $TMP
for filename in *.dat; do
	sum=$(awk '{s+=$1} END {print s}' "$filename")
	echo "$sum	$filename" >> $OUT/results.txt
done || exit $?

echo "Sorting..."

sort -gr $OUT/results.txt > $OUT/results_sorted.txt
```

### CODE REVIEW

**Comment by rubenwardy** [comment]
More people could be added from this release, but frankly I cba to go through and find out the correct information for them all. Volunteers welcome for this

**Comment by sofar** [comment]
:+1:, and I love seen the big list of additions. Fantastic work.

**Comment by rubenwardy** [comment]
The names are currently sorted by my arbitrary heuristic. May be a good idea to just sort alphabetically

**Comment by rubenwardy** [comment]
And here's the raw output:

```
1037	loicblot.dat
519	paramat.dat
315	smalljoker.dat
161	rubenwardy.dat
109	numberzero.dat
93	stujones11.dat
75	red001.dat
70	pauloue.dat
68	juhdanad.dat
63	hybriddog.dat
60	muhammadrifqipriyosusanto.dat
47	vincentglize.dat
46	bendeutsch.dat
45	larshofhansl.dat
45	ekdohibs.dat
36	wuzzy.dat
32	clobberxd.dat
28	sfan5.dat
28	lhofhansl.dat
24	ezhh.dat
24	dta7.dat
23	thomass.dat
23	raymoo.dat
23	elijahduffy.dat
21	noob3167.dat
20	adelcoding1.dat
19	adrido.dat
16	rui.dat
14	kilbith.dat
14	estebanirm.dat
13	shadowninja.dat
11	vaughanlapsley.dat
11	coderforthebetter.dat
10	thoughtjigs.dat
10	quentinbazin.dat
10	maksim.dat
10	kahrl.dat
10	galc.dat
10	dharkael.dat
10	aspen.dat
5	zeuner.dat
5	tre.dat
5	sofar.dat
5	robblanckaert.dat
5	jozefbehran.dat
4	randomgeek.dat
4	pedrogimeno.dat
4	lisacvuk.dat
4	juozas.dat
4	jensrottmann.dat
4	ds.dat
3	tetpaaka.dat
2	zeno.dat
2	texmex.dat
2	tenplus1.dat
2	pavelpuchkin.dat
2	jessemcdonald.dat
2	gaeldesailly.dat
2	ashtrayoz.dat
1	xzcx.dat
1	waywardone.dat
1	vlapsley.dat
1	vanessae.dat
1	tukkek.dat
1	treer.dat
1	sokomine.dat
1	shivajiva101.dat
1	sapier.dat
1	qrchackofficial.dat
1	porygonzrocks.dat
1	pierreyvesrollo.dat
1	otdav33.dat
1	orwell96.dat
1	nanoproject.dat
1	miqlas.dat
1	minduser00.dat
1	midgard.dat
1	michaelmuller.dat
1	meme.dat
1	mazocomp.dat
1	martinrenold.dat
1	luiscceres.dat
1	lourensrich.dat
1	leonidbobrov.dat
1	kumajjw.dat
1	kevinabrams.dat
1	jordanirwin.dat
1	jdcodeit.dat
1	jcalve.dat
1	jamesalexanderstevenson.dat
1	greg.dat
1	gituser2194.dat
1	fixer.dat
1	estebaniruizmoreno.dat
1	dtimcummings.dat
1	dopik.dat
1	cx384.dat
1	chimneyswift.dat
1	casimir.dat
1	carlespastorbadosa.dat
1	brian.dat
1	bluebird.dat
1	asl97.dat
1	alex.dat
```

**Comment by nerzhul** [comment]
wow i'm first :p

**Comment by SmallJoker** [comment]
Thank you for this update. It's great to see this script to not forget a contributor.

**Comment by paramat** [comment]
To be merged as one of the last PRs to include as many contributors as possible.

**Comment by Wuzzy2** [comment]
Best commit messages ever!

**Comment by rubenwardy** [comment]
> Best commit messages ever!

Thanks, I try

**Comment by paramat** [comment]
> More people could be added from this release, but frankly I cba to go through and find out the correct information for them all. Volunteers welcome for this

Why would more be added if you have included all with score 4+?
:+1: Seems ok as it is now.

**Pull request merged**
