### PR TITLE
Devtest: Update biome registrations

### PR DESCRIPTION
**Pull request by paramat**
A simple PR that modernises the biome registrations.

Merge after #9928 , there do not seem to be any conflicts, but just to be safe.

* Adds an '_under' deep underground biome. Tests variation of cave liquids.
* Defines riverbed nodes where necessary (in all biomes near and above sea level). Needed for Mapgen Valleys. Sloping rivers now have sandy riverbeds.
* Defines dungeon nodes, including mossy cobble alternative wall nodes and cobble stair nodes. The dungeon nodes are no longer all set to the fallback cobble node.
* Defines cave liquid nodes. Water only in shallow underground ('_ocean' biome), water and lava in deep underground ('_under' biome). The cave liquid nodes are no longer set to the fallback nodes.

screenshot_20200524_192204

screenshot_20200524_193004

### CODE REVIEW

**Comment by paramat** [comment]
Thanks, will merge once i fix the conflict.

**Comment by paramat** [comment]
Replaced by rebased version #9936

**Comment by paramat** [comment]
Messed up rebase and branch during the stage of being an empty commit.
Replaced by #9936

**Comment by sfan5** [comment]
You know that you can always get back the old state before pushing?

**Pull request closed without merging**
