### PR TITLE
Minimal: Add river water nodes

### LINKED ISSUE #5120: "Minimal dev test" failed to resolve node
Decided to report it here:

```
NodeResolver: failed to resolve node name 'mapgen_river_water_source'.
```

PR available: https://github.com/minetest/minetest/pull/4907

### PR DESCRIPTION
**Pull request by paramat**
Is a base terrain node needed by any core mapgen with sloping rivers.
////////////////////////

Fixes #5120
Replaces #4907
Tested.

### CODE REVIEW

**Comment by C1ffisme** [comment]
I know that I'm being a little dramatic about such a small change, so I'll just ask and not argue with the answer I get:

Wouldn't it be simpler to make river water not a core mapgen required node?

A lot of nodes required by v6 such as Desert Stone will use "mapgen_stone" if no "mapgen_desert_stone" exists, so why not do the same for water? Especially since most of the minimal textures look incredibly ugly and the minimal game isn't supposed to be anything other than an engine development subgame that loads faster than MTG.

**Comment by paramat** [comment]
Yeah this gets asked quite often, it's due to our new sloping rivers in mgvalleys and future core mapgen.
Because normal water is renewable the sources can spread horizontally and therefore overrun river banks further down a slope. Also, range 8 means that even if that does not happen, flowing water can overrun river banks further downslope if the river is steeper than 1 in 8.

Mgvalleys may not have particularly steep river slopes but future mapgens will, especially the mountain streams at high altitude.
I was perhaps the first person to create a lua mapgen with sloping rivers (for example 'watershed' mod), and quickly discovered why normal water cannot be used, it creates a horrible mess. MTGame river water is a result of my experience with lua mapgen work.

**Comment by paramat** [comment]
Not really a feature. I don't care much about minimal, but the base terrain nodes should be present, river water is the 4th one along with air, stone and water, and is now as important as those.

**Comment by C1ffisme** [comment]
Ok, I'm fine with that.

**Pull request merged**
