### PR TITLE
Improvements to colored shadows

### PR DESCRIPTION
**Pull request by x2048**
A number of improvements to colored shadows:
* Fix minetest#11361 - apply vertex color when rendering colored shadow
* Remove visual artifacts in colored shadows by disabling the trilinear filter when sampling SM texture. No visual impact since filtering is done in shaders
* Make colored shadows more prominent by applying them with multiplication instead of mix().
* Avoid rendering colored shadow on surfaces that are turned away from sun.

This PR is Ready for Review.

## How to test

* Enable colored shadow
* Install [stained_glass](https://content.minetest.net/packages/andersje/stained_glass/) mod
* `/giveme stained_glass:stained_glass`
* Place a number of stained glass blocks
* Use painter from unified_dyes mod to color the blocks yellow, red, green or blue
* Observe the casted shadows, they should match the color of the blocks

### CODE REVIEW

**Comment by lhofhansl** [comment]
Doesn't seem to work:
screenshot_20210811_142849

Maybe I am missing something...

**Comment by x2048** [comment]
Hmmm... Here's how it looks here:
image

One thing that bothers me is that original Minetest shaders are written with special loader that handles e.g. GLES vs GL variation, but shadow shaders are GL-only. Might be a problem here if e.g. vertex color is not communicated as gl_Color.

**Comment by lhofhansl** [comment]
Lemme try again.

**Comment by x2048** [comment]
Colored shadows are generally desaturated due to how the shader works, but that's a topic for another PR.

This PR however seems to have a problem with abriglass mod producing phantom edge lines in shadows.

**Comment by x2048** [comment]
@lhofhansl I've decided to include saturation fix into this PR and fixed color artifacts. Should look better now.

**Comment by x2048** [comment]
@VanessaE Would you also like to take a look how colored shadows look with this PR?

**Comment by lhofhansl** [comment]
Missed this one. Lemme test tomorrow. (sorry about the delay)

**Comment by lhofhansl** [comment]
Works.
Thanks @x2048

**Comment by VanessaE** [comment]
Works fine for me.  The shadows' colors are a little subtle maybe, but it works fine.

**Pull request merged**
