### PR TITLE
Add 4 missing fallback/default textures

### PR DESCRIPTION
**Pull request by Wuzzy2**
This PR adds the missing default/fallback textures to the engine:

* `heart.png`
* `bubble.png`
* `crack_anylength.png`
* `wieldhand.png`

The first 3 are just pulled from minimal.

The final one is just a green rectangle to match the color of our current `player.png`/`player_back.png`. I believe these files are deliberately ugly to force modders to replace them?

I claim no credit to any of these files. So I assume there's a default license. Right?

## Justification

This is basically the logical continuation of https://github.com/minetest/minetest/commit/b52a79076d2e209686fca678fc574fab71b67359

## How to test

* Create an empty game, add some test nodes: A node that is diggable, a node in which you drown
* Generate a simple world with these test nodes
* Start the game
* Look at your hearts and wieldhand
* Dig the diggable test node and check the crack texture
* Go into the drowning node and check your bubbles

## Caveat

It appears the `wieldhand.png` textures is not used by the engine default. When I look at my hand, I see a missing texture.

This appears to be a bug / missing feature in Minetest. However, `wieldhand.png` is mentioned in docs.

However, this apparent bug should not block this PR, as the bugfix would be just to properly use the `wieldhand.png`.

### CODE REVIEW

**Comment by Wuzzy2** [comment]
Question: Would it make sense to also remove these textures from Minimal Development Test as redundant?

Or is it intentional this test game includes the textures explicitly?

**Comment by Wuzzy2** [comment]
Oh, and the “caveat” is addressed in #8846.

**Comment by sfan5** [comment]
> Question: Would it make sense to also remove these textures from Minimal Development Test as redundant?

Yes

**Comment by Wuzzy2** [comment]
Okay, removed it.

I just noticed my PR has a problem. Now these textures are forced upon all games, overriding the game-provided files. E.g. Minetest Game's `heart.png` is not used anymore, the fallback `heart.png` file is. This is true for the other added files, too. And also `player.png` and `player_back.png`, which were recently added by @paramat.

Either my PR is buggy or I just uncovered an existing bug.

Either way, this PR can not be merged before we figure out what happened here.

**Comment by paramat** [comment]
That's weird that the engine fallback textures override those in a game, seems it should really be the other way around.
Anyway, once that is fixed this PR is a good idea.

**Comment by Wuzzy2** [comment]
I think a fix of the fallback problem should be in another PR.

**Comment by paramat** [comment]
I agree.

**Comment by paramat** [comment]
Issue for the underlying problem #8955 
PR to fix problem #8974

**Comment by sfan5** [comment]
Why is the heart.png you added bigger (1.8 KB) than the one removed from minimal (248 B)?

**Comment by paramat** [comment]
#8974 merged, this PR can now go ahead (after release).

**Comment by SmallJoker** [comment]
@Wuzzy2 Likely all texture licenses can be treated like `player*.png` (https://github.com/minetest/minetest/pull/8823#issuecomment-523145964).
This is a simple PR, but why did "heart.png" change? Does it need licensing?

**Comment by Wuzzy2** [comment]
`heart.png` is from Minimal.

**Pull request merged**
