### PR TITLE
[WIP] Add NPC API

### PR DESCRIPTION
**Pull request by Dumbeldor**
The goal of this PR is to lay the foundations for a robust and extensible NPC API by mods, standardizing practices and connecting with the client in a more advanced way for a better user experience.

The first commit is to create a new entity type in the core to specialize a LuaEntitySAO to the NPC role. For the moment it has exactly the same functionality as LuaEntitySAO, but will be allocated more functions in future commits.

The aim of the PR is to open the discussion to a unified API, and to identify the needs of such an API.

### CODE REVIEW

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/issues/1667#issuecomment-290555777
@sofar is working on this, maybe collaborate?

**Comment by rubenwardy** [comment]
This bothers me, as I think CSM should be worked on to be made more useful given that it's the thing that triggered this major release. We still don't have any communication channels / event communication, or any stuff useful for client-side prediction

**Comment by C1ffisme** [comment]
When you say "NPC" are you referring to intelligent, non-hostile mobs (if "character" in "NPC" refers to simply "person"), or just any mobs in general?

**Comment by nerzhul** [comment]
@paramat the sofar approach is a little bit similar than we want to implement core side, the event idea is a must have, the action maps too.

@rubenwardy the PR is not developped by CSM API owners, but i can develop mod channels if needed :)

**Comment by nerzhul** [comment]
@C1ffisme NPC = non player character, in every RPG it's non player entities :)

**Comment by sofar** [comment]
I fail to see how the current luaentitysao couldn't function in the way that this new sao that you're making, and I wonder if it's worth doing all this infrastructure without actually understanding where differentiation would be useful and where it just hurts.

Maybe the question to ask is: Why do we need a new SAO object?

This is why I'm so opposed to throwing mobs into core right away, and why I think it was justified to remove them as has happened a long time ago. What we actually need is npcs (== monsters, villagers, fake players, bots, etc.) that are fully featured and then focus much, much later on the actual problems that they have from a core engine side of things.

I have yet to see arguments that are convincing that my approach (essentially, experiment and grow entity_ai until the cracks appear in core engine design) is deficient. It also benefits from the fact that it actually does the last-mile delivery of functionality in the form of functional npcs (monsters, whatever) in a demonstrable and usable way. Growing from the core out again doesn't solve the nasty design gaps that the other mob engines have, at all, and has the risk of avoiding to actually retrospect on what it means to make actually useful NPCs in a structural way.

If you're actually wanting to implement something like entity_ai's driver model, why not contribute and take it to the limit so we can determine whether the design was bad or not, and help deliver actual game content to prove this? I hate to see an academic exercise start from scratch too, that's just completely ignoring the chance to actually learn something useful from it. If anything I'd want people to show me that entity_ai's design concepts are flawed.

too much text, I feel like I've written most of this before already.

**Comment by nerzhul** [comment]
personnaly, i don't want any lua part i want a performant backend with a good API. Lua is not intended to run on many steps properly without overhead. NpcSAO is just what you need to plug the Npc::Property thing you call entity_ai. It should be more intelligent and optimized than a LuaEntitySAO, to reduce memory cost and CPU overhead permitting to have thousands of entites working properly

**Comment by sofar** [comment]
> It should be more intelligent and optimized than a LuaEntitySAO

how? why?

Don't get me wrong, but, it sounds like a nice thing but if there is no substantial design backing it up then it's a waste of engineering time.

> Lua is not intended to run on many steps properly without overhead

performance claim. I say it's unfounded claim, without any actual data.

If you have to c->lua once every entity on_step, then you're not going to optimize anything away if after all your work you still have to do one c->lua every on_step. So, can you demonstrate that you can eliminate the call out to on_step()? If not then there is almost no point in doing this.

**Comment by C1ffisme** [comment]
@nerzhul But does "character" refer to "person" or just "sentient entity"?

@sofar If someone is willing to code mobs into the game, I'm willing to at least see what comes out of their work. Even if this pull never gets merged, at least we can see what not to do.

**Comment by nerzhul** [comment]
@C1ffisme it's mostly humanoids, animals, creatures, see https://en.wikipedia.org/wiki/Non-player_character

**Comment by C1ffisme** [comment]
@nerzhul Wikipedia may use one definition, but Dumbeldor might be using another. Although judging from the comments in this pull request, I'm guessing the definition stretches to animals and monsters.

**Comment by hkzorman** [comment]
As the developer of a NPC mod, I find this thread very interesting. I think, from my experience, I can reconciliate sofar's and nerzhul's arguments.

In my experience, the most expensive operation NPCs perform on steps is movement and consequently, pathfinding. This is a crucial functionality that is currently not built in on Minetest (minetest.find_path() never works for me). I use Mark Bu's pathfinder (which is in Lua), and while it does the work, in my numerous tests I feel this is the most expensive operation. I get very noticeable server lag whenever many NPCs try to use pathfinding code and move to certain locations. My NPCs move at two node per second, however there is terrible lag, misplaced movement whenever a few of them are walking around. I believe that, if movement (basically, pathfinding and movement prediction) is handled from C++, this will receive a noticeable performance boost.

Another point where C++ could help boost performance is in area scanning. By these, I basically mean that a NPC is to be smart, it needs to be aware of its surroundings, and for that, it should be able to scan nearby nodes on a close radius. This is also slow in Lua and I notice, again, server lag whenever my NPCs try to search for nodes around themselves using any minetest.find_nodes* function.

The rest of operations that NPCs may do can be (and should be) done in Lua. Also, I feel much more stronger that the engine handles movement than node search. I think movement is the most expensive and the definite area that the engine can handle and benefit mods. 

Therefore, I see good on a new server object that handles these specifics. The rest of the behavior can still sit in Lua, I guess.

**Comment by Ferk** [comment]
> Therefore, I see good on a new server object that handles these specifics.

The question is whether it's needed a new server object to handle those specifics. I don't think there's disagreement on what those specifics are, or lack of will in fixing them.

This PR, as it is, and as it's likely to remain given the lack of a plan, doesn't implement a solution to the problems you indicate.

The main source of lag is the client-server communication and the client-side prediction. And I hope to have those two things also for any kind of entity that is not an NPC. Like movement of items, boats, carts, etc. and any kind of entity modders might want to give a movement to but that do not classify as "Characters".

I don't think it will matter that much in terms of performance whether the AI is done in C++ or Lua.  It'll mostly matter in terms of allowing flexibility for mods and increased maintenance burden to the engine.

**Comment by paramat** [comment]
@Dumbeldor this is neglected, needs adoption?

**Comment by paramat** [comment]
Neglected so closing for now, reopen on progress.

**Comment by Fixer-007** [comment]
Add "Adoption needed"?

**Comment by paramat** [comment]
I don't think so, not yet anyway, i expect the author(s) will continue work on this.

**Pull request closed without merging**
