### PR TITLE
Lua_api.txt: Add warnings of l-system lighting bug

### PR DESCRIPTION
**Pull request by paramat**
See #3421 for details of this bug.
Merge this if we do not fix the bug in time for release.

### CODE REVIEW

**Comment by PilzAdam** [comment]
So, if we can't fix it then we just document it?

**Comment by paramat** [comment]
Maybe this should wait until just before release, in case we do fix it.

**Comment by Ekdohibs** [comment]
:+1: for this to be merged in 0.4.14, but the issue should be fixed as soon as possible (maybe 0.4.15)

**Comment by est31** [comment]
:+1:

**Comment by paramat** [comment]
a279426d126631e82f49f5b9d1d7bfb2c580396d

**Pull request closed without merging**
