### PR TITLE
Fix issue #4005 and update depends

### PR DESCRIPTION
**Pull request by MoNTE48**
Curl 7.48.0
SQLite 3.12.2
Fix OpenSSL build (GMP was required as dependency)

### CODE REVIEW

**Comment by paramat** [comment]
Thanks for this.

**Comment by Wayward1** [comment]
This does build successfully

**Comment by est31** [comment]
Ahhhh shit. The solution is obvious of course.

**Comment by est31** [comment]
:+1:

**Comment by est31** [comment]
Can you add "Android" somewhere to the commit message, to let people know its about android. Also, would be cool if you added to the third line of the commit message that GMP was required as dependency.

**Comment by MoNTE48** [comment]
@est31, done. Do not worry, many basic things are very difficult to me.

**Comment by paramat** [comment]
:+1:  I'll fix the commit message when i merge.

**Comment by kwolekr** [comment]
:+1:

**Comment by paramat** [comment]
26a9a85129db3c769a9deecf905640858dc48ed8

**Pull request closed without merging**
