### PR TITLE
Keep scroll position constant in ChatBuffer::deleteOldest()

### LINKED ISSUE #4051: Chat does not scroll properly
Often I see the ever increasing gap in chat (opened with t), so I need to scroll it down regularly: https://i.imgur.com/7ckuaJH.png
kahrl mentioned his code that can help fix this: kahrl@b1fefe8

### PR DESCRIPTION
**Pull request by kahrl**
Fixes #4051.

### CODE REVIEW

**Comment by paramat** [comment]
Thanks.

**Comment by Fixer-007** [comment]
Very important fix of annoying problem.

**Comment by est31** [comment]
I think some people had this issue with my server console as well.

**Comment by est31** [comment]
(second part of #3492)

**Comment by tenplus1** [comment]
It would be nice to have a /clear command as well to remove ALL chat and start fresh.

**Comment by Zeno-** [comment]
:accept:

**Comment by paramat** [comment]
2cdd9b4ab6cfc878dafb88aa8446b12cf2f94278

**Pull request closed without merging**
