### PR TITLE
Add an option to disallow guest connection (disabled by default)

### PR DESCRIPTION
**Pull request by nerzhul**
This add an option to prevent guest connection on the server. 
I know there is a mod to prevent it, but handling this in core is faster, as we could handle this on _INIT packet, mods cannot.

### CODE REVIEW

**Comment by nerzhul** [comment]
This fixes #1059

**Comment by SmallJoker** [comment]
It's better to have positive settings like `allow_guests_names` also, you could use a string lower function and simply check if it starts with `guest`.
But else, the codes look good.

**Comment by nerzhul** [comment]
we have disallow_empty_password and disable_anticheat, then changing the negative of the option is not required here.
Lower the string is slower than comparing the 5 char twice.

**Comment by rubenwardy** [comment]
Guest usernames are bit of a non-feature, IMO.

**Comment by gregorycu** [comment]
Even if the core is "faster" I don't think this is one of those cases we should optimise for speed.

We don't really have a concept of "guest connection" it's just disallowing people with "guest" at the start of their name.

I think the concept of a guest connection is one that is worth perusing, but I think it should be a flag on the connection, not the mere fact the name starts with "guest", if you catch my drift.

**Comment by PilzAdam** [comment]
I object to moving this to core; it's perfectly fine to handle this in mods.

A better "fix" for this problem would be to not automatically fill the nickname field with "Guest#####".

**Comment by nerzhul** [comment]
At this time it's not, unfortunately @gregorycu .

I added a function to prevent too short names.

@PilzAdam i agree, but the mod is mandatory for most of the servers. I suggest you to add it into minetest_game if you don't want it in core. We must have this function embedded into minetest/minetest_game.

**Comment by kilbith** [comment]
> I object to moving this to core; it's perfectly fine to handle this in mods.

Not all admins are aware of the NoGuest mod, which is rather essential for the serious servers.

**Comment by gregorycu** [comment]
I agree with @PilzAdam 

An admin is setting up a serious server and can't be bothered finding suitable mods?

It's not essential at all, it's a nice-to-have.

**Comment by kilbith** [comment]
> It's not essential at all, it's a nice-to-have.

I disagree. When you manage a server, you have to identify clearly your players by a distinct naming and this requirement is essential for administer them.

If it's essential, it should go hardcoded.

EDIT: opinion based on _experience_, same for nerzhul...

**Comment by nerzhul** [comment]
If most of servers used it it's because it's not a must have but it's mandatory. If this is needed for manage a server (not adding content), it should be added either on core or in minetest_game.

**Comment by gregorycu** [comment]
@kilbith I don't know, I find a 5 digit number easier to remember than a name with weird spelling. In any case, your argument doesn't hold as people could simply call themselves g453435. It's adding two settings that we have to support that actually don't give anything meaningful.

@nerzhul Just because something is widely used, doesn't mean it's mandatory.

I'm sure server owners also have additional rules in any case. I know VanE filters out numbers for instance. If there are mods that give you explicit control over every component of the name, why would you bother to configure a server config in addition to that. And I don't think the answer is to save 0.02ms.

**Comment by nerzhul** [comment]
@gregorycu the regexp you mention is in the mod she is using, yes. If we are switching to c++11 later i could use std::regex to solve the issue by adding a regex parameter (tested, it works very well).

**Comment by kilbith** [comment]
> I don't know, I find a 5 digit number easier to remember than a name with weird spelling

Sorry, but you don't seem to have ever managed a public server with, averagely, 10-30 _GuestXXXX_ online and trying to address something or tracking actions to few of them. It's really a pain and confusing.

**Comment by gregorycu** [comment]
@nerzhul What if you wanted to validate the username against an externam DB? A ban-list? A white-list? There are infinite options available, and we should make them all possible and spend out time reimplementing features and increasing the number of settings.

@kilbith You can draw whatever conclusions you want about me. That is your right.

Fundamentally nothing can be said to change my mind, so you guys can save your breath. You also don't need to convince me, so there is no reason not to :)

**Comment by nerzhul** [comment]
you don't need a database if you have regexp. Increasing the number of settings permit to have a rich environment. minetest is a game and there are players and server admins, it's not only a developper playground like someones think.

@gregorycu i don't try to convince you then don't try to convince me. :)

**Comment by gregorycu** [comment]
I'm not trying to convince you, I'm trying to convince the other person that has to give a +1.

**Comment by Calinou** [comment]
> A better "fix" for this problem would be to not automatically fill the nickname field with "Guest#####".

:+1:, the guest system should just go away. I think it was initially added by proller.

**Comment by rubenwardy** [comment]
I agree with removing the guest system.

**Comment by nerzhul** [comment]
I also agree but we need to keep a compat at this time of the devel because some servers always runs with master branch

**Comment by crazyR14** [comment]
someone mentioned "A custom regex" that is actually a good idea. 

In the config have an option to allow regexing against usernames..
then another option which is a table of regex's to check against if the abaove option is true.


that would allow server owners to customise it to suit them. and at the same time would mean that servers that dont wish to use that, dont havwe to.

Btw i agree nearly all serious servers use the guest mod. having 100+ usernames that begin with guest is a nightmare

**Comment by nerzhul** [comment]
in fact @crazyR14 it's me, but we need portable regex, and it's not very simple with windows.... std::regex are part of c++11 but this is not time to switch.

**Comment by ShadowNinja** [comment]
1. The `minetest.conf.example` format is messed up.
  2. I prefer positive setting names, and yes, there are some negative ones, it doesn't mean we have to do that to all of them.
  3. Guest usernames shouldn't even be a thing.  Just remove them and let server owners use a mod until versions with this misfeature drop out of use.

**Comment by nerzhul** [comment]
This PR mustn't exist anymore. There are mods for that

**Pull request closed without merging**
