### PR TITLE
clientiface.cpp: Reset m_nothing_to_send_pause_timer when invoking setBlockNotSent()

### PR DESCRIPTION
**Pull request by orwell96**
As stated in [this forum thread](https://forum.minetest.net/viewtopic.php?f=6&t=12748), I noticed that there is a 2 seconds interval in which inventory changes are shown on the client. yyt16384 found the source of these 2 seconds:
m_nothing_to_send_pause_timer is set to 2.0 every time there are no changes to make, but this timer is not resetted when SetBlockNotSent or setBlocksNotSent are invoked. So in worst case, the changed block will be sent over 2 seconds too late.
With this change, changed inventories are updated almost immediately, but it causes additional connection load.
Please notice that I am a C++ newbie and if I did anything wrong, please let me know. I don't know how threading works and what would happen the functions are called in different threads, this maybe could cause inconsistencies.
This will probably only be a temporary solution until [this pull request](https://github.com/minetest/minetest/pull/3166) gets merged.

### CODE REVIEW

**Comment by Fixer-007** [comment]
Inventory lags are indeed very annoying, I hope developers will look at your PR.

**Comment by est31** [comment]
I have tested the patch and it works great. I have three (minor) issues with the patch:

1. There is an added line with trailing spaces (space signs before line end), trailing spaces should be removed

2. The `=` operator should have spaces around it

3. Why set it to 0.1? Why not 0? Then it will be fixed in the directly next server step, not having to wait a round.

:+1:  if those issues are fixed.

**Comment by HybridDog** [comment]
>Why set it to 0.1? Why not 0? Then it will be fixed in the directly next server step, not having to wait a round.

l assume that putting e.g. 10 items at once into a chest would send each single one instead of all at once, 0.1 seconds is a not noticeable delay (in this case) and it's better than appearing lags if sth becomes coded wrongly.

**Comment by est31** [comment]
@HybridDog the `RemoteClient::GetNextBlocks` function is only invoked once per server step. Probaby its reduced to 0 anyway until the next time it gets called, even with the current value.

**Comment by MoNTE48** [comment]
Yes, +1! That would be good, even if it is a temporary solution!

**Comment by kahrl** [comment]
:+1: to idea and implementation (once the things @est31 mentioned are fixed)

It would be nice if somebody who operates a popular server could check how much this affects bandwidth usage.

**Comment by Fixer-007** [comment]
If this really fixes that annoying inventory bug then this is really important PR to merge.

**Comment by kilbith** [comment]
@est31 You should fix the things you mention by yourself. It's time to merge this right now.

**Comment by orwell96** [comment]
@kilbith @est31 I fixed the things that were mentioned regarding code style.

**Comment by est31** [comment]
Merged as e17fbb31d6db3e6d2d9b68f5793ad8b2146f7bcc
(with small modifications)

**Comment by HybridDog** [comment]
according to http://de.drachen.wikia.com/wiki/Leviathan, @kilbith is a parasitic worm

**Pull request closed without merging**
