### PR TITLE
Add new ContentParamType2 "CPT2_DEGROTATE"

### PR DESCRIPTION
**Pull request by est31**
This might break some mods, but it is important for all uses of the param2 to
be documented.

This doesn't need a serialisation version or network protocol version change,
as old clients will still work on new servers, and it is bearable to have
new clients getting non rotated plants on old servers.

### CODE REVIEW

**Comment by paramat** [comment]
+1.

**Comment by est31** [comment]
b0523adc5f673208b5414cf49c6640e4fc148b87

**Comment by HybridDog** [comment]
>break some mods

How exactly does it break them?

**Comment by est31** [comment]
Plants don't get rotated, if the mod doesn't specify the paramtype2, which hasn't been required (or possible) before.

**Comment by HybridDog** [comment]
ok, param2 of the nodes is kept, too, l assume

ls it possible to "link" param2 to param1 that e.g. when the light level changes, the rotation also becomes different?

**Pull request closed without merging**
