### PR TITLE
Per Node Enabled Digging/Placing Animation

### PR DESCRIPTION
**Pull request by Jordach**
- Enables turning wield digging and placing off for specific nodes, items and tools; or keeping them enabled.
- This PR is useful for games (or mods) that use left mouse button for shooting or other various uses that do not need to use punch/place animation. This effect can be seen on Rubenwardy's CTF server.

## To do

Verify that connections to 5.1 and earlier 5.2-dev servers keep full place/digging animations.

Ready for Review.

## How to test

[no_wield_anim.zip](https://github.com/minetest/minetest/files/4394712/no_wield_anim.zip)

Drop this mod into `/mods` and use `/giveme`
```
/giveme test:wield_node_on
/giveme test:wield_node_off
/giveme test:wield_item_on
/giveme test:wield_item_off
/giveme test:wield_tool_on
/giveme test:wield_tool_off
```

## What it doesn't do:

Adds mod defined animations for digging / placing.

### CODE REVIEW

**Comment by SmallJoker** [comment]
The idea is good. What would you think about sending a number `wield_anim_speed` instead?
`0` would disable the animation, and `2` indicates double speed (for fast swords, for example).

**Comment by Jordach** [comment]
> The idea is good. What would you think about sending a number `wield_anim_speed` instead?
> `0` would disable the animation, and `2` indicates double speed (for fast swords, for example).

Good lord I did not think of that! That would actually fix a problem I have in my prototype game where digging in third person doesn't match first person.

**Comment by rubenwardy** [comment]
Largely made redundant by #10411

**Comment by sfan5** [comment]
Though I'd say the chances for this PR are higher since the other PR is large and a bit unfinished in places.

**Comment by paramat** [comment]
@Jordach 
> Good lord I did not think of that! That would actually fix a problem I have in my prototype game where digging in third person doesn't match first person.

Was this implemented? If not, PR is WIP?

**Comment by TheMrAmazing** [comment]
> Though I'd say the chances for this PR are higher since the other PR is large and a bit unfinished in places.

It is large, but I don't really see a way around that if you want to read animations in from LUA. As to it being unfinished, I've been checking back every day for feedback, I'm willing to do what it takes to get it integrated.

**Pull request closed without merging**
