### PR TITLE
Prevent spawning in rivers with valleys mapgen.

### PR DESCRIPTION
**Pull request by duane-r**
Returns an unusable value when asked for an altitude in a river, to prevent people getting wet during spawn.

This could adversely affect decorations (if they're ever placed on rivers), lighting (if the commented code in isBlockUnderground is ever uncommented), or anything else that chooses to use getGroundLevelAtPoint in the future.

### CODE REVIEW

**Comment by paramat** [comment]
Ah you beat me to it :+1:

**Comment by paramat** [comment]
:+1:  with the above change.
Do you want to combine the removal of whitespaces with this?

**Comment by paramat** [comment]
Thanks will merge once squashed.

**Comment by paramat** [comment]
:+1:

**Comment by duane-r** [comment]
That's all the whitespace I've found so far, mostly from line endings.

>getGroundLevelAtPoint is only ever used for player spawn

The only thing that worried me was line 142 of mg_decoration.cpp, but that only comes into play if there's no heightmap, and I can't think of how that would happen.

**Comment by paramat** [comment]
That calls 'findGroundLevel()' in mapgen.cpp, a different and precise function.

**Comment by paramat** [comment]
752d8202061b1092daacb1f7056ace4d5aabef01

**Pull request closed without merging**
