### PR TITLE
update .gitignore: ignore ninja files

### PR DESCRIPTION
**Pull request by HybridDog**
l used ninja instead of make to compile minetest successfully. But git didn't ignore these files yet:
```
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ninja_deps
	.ninja_log
	build.ninja
	rules.ninja

nothing added to commit but untracked files present (use "git add" to track)
```
l found out about ninja there:
https://github.com/Secretchronicles/TSC/issues/540#issuecomment-217260177

### CODE REVIEW

**Comment by est31** [comment]
:+1: why not

**Comment by nerzhul** [comment]
can you add .idea/* also to your PR ? could be good for jetbrains ide like CLION

**Comment by nerzhul** [comment]
Thanks @HybridDog

**Comment by Zeno-** [comment]
+1

**Comment by sofar** [comment]
Really?  ... how much faster are your compiles because of nonja? I doubt it makes a significant dent.

**Comment by sofar** [comment]
I found http://hamelot.io/programming/make-vs-ninja-performance-comparison/

Doesn't seem to really be worth the time to switch to me.

**Comment by paramat** [comment]
0f184d77c871b564b773b7fb81e7a3f16a197813

**Comment by HybridDog** [comment]
>how much faster are your compiles because of nonja? I doubt it makes a significant dent.

ln my test it's ~ 3 times faster.

$ time make
[…]
real	3m40.816s
user	3m16.636s
sys	0m17.456s

$ time ninja
[…]
real	1m22.141s
user	4m28.780s
sys	0m19.632s

note that make uses one thread and ninja 6 ones, my pc has 2x2 (2 cores with hyperthread)

**Comment by rubenwardy** [comment]
What about make -j3

**Comment by HybridDog** [comment]
>What about make -j3

ldk

**Comment by sofar** [comment]
a rebuild on my system is like no time:

```
real	0m0.394s
user	0m0.490s
sys	0m0.133s
```

comparing non-parallel build with a parallel ninja is just *dishonest*.

**Comment by HybridDog** [comment]
>comparing non-parallel build with a parallel ninja is just dishonest.

it's like comparing starting a minetest server with the mesecons mod enabled and then without the mesecons mod,
the first time starting the server takes long but then it starts fairly immediately because most stuff is already present in memory

**Comment by nerzhul** [comment]
Ninja is not the purpose of this PR, please open an issue if you want to support it.

**Pull request closed without merging**
