### PR TITLE
Update Gradle to 5.5.1

### PR DESCRIPTION
**Pull request by hannesa2**
Simply update to Android Studio 3.4.2

### CODE REVIEW

**Comment by SmallJoker** [comment]
What are the benefits? Users with older versions will probably not be able to build Minetest any more, am I seeing this right?

**Comment by hannesa2** [comment]
It needs no explanation, why to be up do date with most recent build tools is not wrong.
On the other hand, why it should be frozen to an old version, there I see no benefit.

But concerning your doubt: Older (at least >=  3.1.x) versions **still can build** (and they should update there IDE anyways)

**Comment by hannesa2** [comment]
btw: current master has an issue with Travis

**Comment by rubenwardy** [comment]
Minetest can't be compiled with Android Studio. The correct description for this would be "Update Gradle to 3.4.2"

**Comment by SmallJoker** [comment]
The reason why the required GCC version is not pushed upwards continuously is that many people use stable OS' where their repositories tend to be outdated in favour of stability. Hence I asked whether the new configuration would be usable with older versions as well, which is apparently not an issue.

**Comment by hannesa2** [comment]
> Little nickpick: Minetest can't be compiled with Android Studio. 

There is a checked-in Android Project. And I can at least compile it. So your sentence makes more new questions as it answers one.

The only thing I see what really can't compile yet is Travis
```
E: Unable to locate package clang-7
E: Unable to locate package clang++-7
E: Couldn't find any package by regex 'clang++-7'
```

> The correct description for this would be "Update Gradle to 3.4.2"

If you want change it to Gradle context, it's "Update Gradle to 5.5.1"

**Comment by MoNTE48** [comment]
> Little nickpick: Minetest can't be compiled with Android Studio. The correct description for this would be "Update Gradle to 3.4.2"

What if I tell you what he can? Would such a PR be interesting?

**Comment by rubenwardy** [comment]
It's possible to change Minetest to be compiled with Android Studio, but Minetest can't currently

**Comment by MoNTE48** [comment]
@rubenwardy Well, the question was whether such a PR is interesting .This is a lot of work, and I would not want to do another PR, which will be forgotten due to the fact that no one else in Minetest understands this.
Building MultiCraft via Android Studio on Windows takes 1 min 8 sec on my PC.
1 button to build multiple architectures and get signed ARM+x86 APKs

**Pull request merged**
