### PR TITLE
Add transfer_player function to request client move to new server

### PR DESCRIPTION
**Pull request by grapereader**
This is my crack at an implementation for the following issues:
https://github.com/minetest/minetest/issues/10041
https://github.com/minetest/minetest/issues/5813
And, to a lesser extent:
https://github.com/minetest/minetest/issues/4428

On calling `minetest.transfer_player(name, address, port)`, the server sends a disconnect message of type `SERVER_ACCESSDENIED_TRANSFER` with the IP and port packed into customMessage.

Clients that support this new message type will disconnect and reconnect to the new address:port, using the same username and password as was used to connect to the current server.

Clients that do not support this new message will fall back gracefully. They disconnect and display the destination server address in the disconnection message box (in reality, this is the content of customMessage, which has the packed format address;port).

Eagerly open to suggestions for how this can be improved, with the end goal of finally getting this much-needed feature into the game. 😁

Edit: I should add that it is my view that synchronization be left for server owners to sort out. There's so many ways to coordinate between servers (HTTP, IRC, shared databases, and so on) I don't think it's necessary to introduce an engine feature for it. This sorts out the key obstacle: moving players from one server to another, without taking any stance on how synchronization (if any) should be performed.

### CODE REVIEW

**Comment by EliasFleckenstein03** [comment]
Actually, this can already be done using a proxy which provides a cleaner way to do this.
Check out https://github.com/HimbeerserverDE/multiserver for more info.

**Comment by grapereader** [comment]
> 
> 
> Actually, this can already be done using a proxy which provides a cleaner way to do this.
> Check out https://github.com/HimbeerserverDE/multiserver for more info.

This is awesome

**Comment by Wuzzy2** [comment]
> Clients that support this new message type will disconnect and reconnect to the new address:port, **using the same username and password as was used to connect to the current server.**

This sounds like a great way to leak passwords to untrusted parties.

**Comment by grapereader** [comment]
> 
> 
> > Clients that support this new message type will disconnect and reconnect to the new address:port, **using the same username and password as was used to connect to the current server.**
> 
> This sounds like a great way to leak passwords to untrusted parties.

Except Minetest uses SRP to avoid exactly this.

**Comment by Wuzzy2** [comment]
Ah, nice.

**Comment by grapereader** [comment]
I do think there are many possible criticisms about this implementation. But it is the minimum-viable-product.

Adds no new packets; no new protocol version. Uses the existing disconnect logic. Etc.

But the existence of a reverse proxy changes everything. I figured it would be impossible since the client doesn't even have a _notion_ of changing worlds.

But that linked multiserver project seems to have done it. Props to them.

**Comment by oiaohm** [comment]
The username and password thing.    There are different single sign on options that exist that can be used.   But I do see that the transfer_player function should support the case where the user/player will get a dialog from client asking for user name and password for the server transferring to with the possibility of the client storing a password list.    This would provide way for their to be a lobby server with portals leading to many different servers including creating your own local instance of minetest with your own portals leading to the servers you regularly play on.   This does lead to the question of start and stop on demand local minetest instances.

**Comment by BuckarooBanzay** [comment]
Bump!
Is there an issue with this pr?
I'm kinda interested in this feature... 🤔 
Also: needs a rebase...

**Comment by MisterE123** [comment]
please rebase and get this merged!

**Pull request closed without merging**
