### PR TITLE
Reset all network-related changes

### PR DESCRIPTION
**Pull request by kwolekr**
This PR removes all of the controversial network changes made since https://github.com/minetest/minetest/commit/15c037614f6f7193cef4bfd1da45d83ef2fef393.  Directly reverting the changes in question was not possible due to the massive amount of difficult merge conflicts, so the approach taken instead was to cherry-pick all good commits to upstream @ ffdf8de (this was done on a best-effort basis; some could not be committed due to merge conflicts).

Commits skipped over:
0d1eedcccc8b83fd5f5a9a75389fe8ac97d2c697
aa474e4501f460ba853dc70ff4d97cbd061e6704
82482ecd9d45036da38335f7dd96232450338a28
b214cde5b4a833e1826ec6850b95bf1938c8b0a0
2066655aae2022384fc12a10c04dccfd2996f0ac
7e088fdfe3c77083606bce955624aef1da59bb32
40bf1d7b5f2a190ae89885c9ea99f52c476ea6be
1b2f64473ed4f222d3b7f02df853730d4382105e
7e56637ed07d9f32b4bd9049009cf7e1e4cff884
64ff966bae99813229dff6629fd9131a91ba7484
51057a56f540f4e74b424e22c94357e5cb5268b2
009149a073ac02dd412af3c203979157976c0dd8
cf4045ff0f7c96614e64b2b336e62a240f443ea6
e357577cb2c18fe29610ed406e01d8d1fda6bb89
49f84b76bcacb6de9544ebaf0a05c9f76ccf33b1
b019221c30f58ce1944d8f2421b40b31ba364716
7880ff74b65040ccb90bc30ba520d4a4215d45a0
146f77fdb750833c649de7159a0833c398e14a4d
a704c04f00bfea4b77550169fa08105c2ee0dfd0

Commits with conflicts:
038d3a31dfa6c382a5a5a57f2ce367d1cd67fb9f
e9eda2b0d0019890cd404e4af25b7adf349e288f
708337dfc2b3871dc6de983e781e4a4a60a1881d  - modified client.cpp manually; shadow changes to packethandlers/client.cpp
36e8ba9ce2d9eafb1f36e76e86113ed47afe8f7f - modified main.cpp manually; add ALLOW_ZWRITE_ON_TRANSPARENT set
3b6480c5b0c968ad9f5a7cfb7ca494989be03629  - modified server.cpp manually; change wrapDegrees -> modulo360f
5a5854ea9d0bc346b00f48f40b538b7a8d68b37a
c09d026f0561ee3c6db821a7e193716f724a0e4a
3c91ad8fc2b7a7888503e85d31bfe286afa6560d

An enormous amount of harm has been made to Minetest.  This won't solve all the issues, but it's a good start.

### CODE REVIEW

**Comment by ShadowNinja** [comment]
Why?

**Comment by kwolekr** [comment]
They need to go.  I support what the commits try to do in theory, but:
 - They introduce too many stability and performance regressions
 - The quality of their implementation is rather low
 - The author openly refuses support maintenance in the current commits
 - They are largely superficial
 - They are purposely made difficult to revert
 - They are a clear indication of what's to come later in the pending branch (i.e. a general disregard for the codebase)

After all is fixed, maybe some developer will implement similar changes along with a network translation layer for reverse compatibility, and without the obvious big agendas.

**Comment by kwolekr** [comment]
Rebasing this is rather difficult due to the nature of what it does.  You'd need to temporarily revert conflicting commits after Mar. 6th

**Comment by nerzhul** [comment]
have you got any proof ?
You are superficial, please stop whine and help the project with solid arguments instead of a list of superficial ideas without funding.
There are no stability regression, many servers are running with these patches since 1 month without any problem, please stop.

**Comment by nerzhul** [comment]
I let this not funded PR opened 3 days. @kwolekr you have 3 days to proove what you are saying.

**Comment by nerzhul** [comment]
@kwolekr closed.

**Comment by est31** [comment]
I can comment here

**Comment by Zeno-** [comment]
This can remain open for discussion... sure, it's controversial but that doesn't mean it cannot be discussed.

**Comment by nerzhul** [comment]
I'm open for discussion but this PR is not founded. IRC is a zone of discussion :)

**Comment by nerzhul** [comment]
To answer the thing you say on the NetworkPacket with size 0 with no crash, please read the code instead of trolling. It's a bytebuffer modelized with a vector and the size is dynamic, but we could allocate the memory if the packet size is static directly to improve the buffer performance. Atm, because of the compat on master we can't calculate the size before allocating the packet and/or it's more expensive to calcul it before allocating the NetworkPacket.
Then read the code and stop trolling with bad things. Next: find a bug, don't report a non proven thing. code is like a science, it's exact. Your PR is not exact it's based on suppositions.

**Comment by kwolekr** [comment]
Still keeping this open, just for the possibility =]
There's still a lot wrong with the Network changes but they seem to be slowly getting worked out.
It might be a smart idea to look at all the cases where packets were sent as unreliable and see if they still work as intended.

**Comment by nerzhul** [comment]
this PR is unmergeable and will not be merged. you can make other PR if you see problems and explain what is each problem to solve possible issues you see.

**Comment by sfan5** [comment]
This should remain open for discussion.

**Comment by nerzhul** [comment]
The discussion is on IRC, this PR will not be merged. Or do a atomic PR.

**Comment by kwolekr** [comment]
nerzhul, you simply do not have the authority to do this.  I suggest taking your head out of your ass.

**Comment by nerzhul** [comment]
I'm the network maintainer. Please be polite you're not the king on its golden chair.

**Comment by kwolekr** [comment]
I don't care whether you've been designated "network maintainer" or not.  The decision is to leave this open.  End of discussion.

**Comment by nerzhul** [comment]
No. You don't have rights to do anything. There are rules. Stop that, NOW.

**Comment by kwolekr** [comment]
At the time I created this PR I felt that something this radical was needed to give attention and exposure to network issues.  At this point everybody seems fairly aware, and obviously this can't get merged just due to merge conflicts alone, so I'll close it.

From here on, matters related to network changes should be discussed through Issues and perhaps something like the forums.

**Pull request closed without merging**
