### PR TITLE
Stop autoforward on BACKWARD key-press (if autoforward is active)

### PR DESCRIPTION
**Pull request by tukkek**
This is a documentation update for pull request #7414, as requested by @paramat.

### CODE REVIEW

**Comment by tukkek** [comment]
`README.md` makes no mention of autoforward so I don't think it needs to be updated.

**Comment by paramat** [comment]
Yes, i mean documentation of backwards key disabling autoforward, it would have to be added to the 'WASD move section'. However i'm not sure if altering README is necessary, it's certainly of less importance. I suggest don't add it and wait until tomorrow (EU time) for input from another dev.
The docs you have added are good enough so will transfer approvals to here and close the other PR.

**Comment by tukkek** [comment]
Renaming this since it's replacing the previous pull request.

Will it be helpful if @sfan5 adds his approval here as well? If so, please do so @sfan5, this is literally the same code as the previous thread (but with some more documentation added) :)

**Comment by tukkek** [comment]
Thanks everyone!

**Pull request merged**
