### PR TITLE
Crafting optimization

### PR DESCRIPTION
**Pull request by gamefreq0**
Changes the crafting system to allow bulk crafting with less strain on the client and server, and also adds shift-click crafting to craft up to one full stack of output. Cleans up a TODO of the mouse shortcuts PR #13146, and improves performance related to crafting. Branch renamed and new PR created (previously PR #13714) to reflect the intended scope of the changes

This PR is a Work in Progress.

- [ ] Needs unit test
- [ ] Needs further bug testing

### CODE REVIEW

**Comment by fluxionary** [comment]
this sort of change to behavior has potential consequences for interaction w/ e.g. the [stamina mod](https://github.com/minetest-mods/stamina), which decrements stamina per crafting event. taking into the account the size of the resulting stack isn't a great solution either because some recipes may produce a large amount of items. 

this has even more dire consequences for my in-development [staminoid mod](https://github.com/fluxionary/minetest-staminoid) which aborts crafting and drops the items on the ground if you run out of stamina while crafting. 

note that a major reason for some crafting being expensive for servers was fixed w/ #13234, which barely didn't make it into 5.7.0.

**Comment by gamefreq0** [comment]
Regarding things that do something per crafting event, couldn't you calculate the maximum number of events you could support given some criteria, and call the crafting with `min(desired_crafts, max_crafts_could_do)` (to put it into pseudo-code)? I could look at trying to integrate a Lua hook to allow mod authors to intercept the desired number of crafts, and modify it as necessary, which would both open the door for things like GLCraft to queue up a given number of crafts, or stamina depletion to be calculated prior to triggering the crafting operation.

**Comment by Desour** [comment]
If I see it correctly, what this PR does is doing multiple crafts at once by decrementing the input items by more than 1 each (as opposed to doing the craft multiple times in a loop).
But you're missing the craft check for multiple operations at once, right?

I'm not sure if this approach is good. I doubt decrementing the craft grid is any expensive operation. The bottleneck is probably rather in the craft check (please correct me!).

What we could do instead is cache craft recipe checks. If we only have one entry in the cache, the craft check for bulk crafting is already basically free, because it's always a cache hit.

**Comment by gamefreq0** [comment]
To the best of my knowledge, from what I looked at, there's at least two serializations and deserializations every time the input is decremented, one for the server, and one for the client. I'm not versed enough in profiling code to be able to interpret the results I got from gprof, and I didn't quite have the patience to test with Valgrind the other day, but I suspect that while caching craft checks would be a good thing to do, that it's only part of the problem here, and that the overhead of talking back and forth between the client and server for each crafting operation is contributing enough to make even the current changes useful.

**Comment by fluxionary** [comment]
> Regarding things that do something per crafting event, couldn't you calculate the maximum number of events you could support given some criteria, and call the crafting with `min(desired_crafts, max_crafts_could_do)` (to put it into pseudo-code)? 

i haven't dug into this very deep, but the problem is how to *prevent* crafting according to external conditions. i can imagine an api that asks to craft a certain number of times, and gets told that only some smaller number of those crafts actually get to execute. but that's a fairly large API change, and i'm not aware of any meaningful performance issues in crafting once #13234 is accounted for.

some sort of optimization might be possible and warranted, but the critical issue is that the same callbacks need to be called for each craft result, and those need to possibly abort the crafting.

**Comment by gamefreq0** [comment]
It would seem that the majority of the mouse shortcuts code was written about a month before that optimization was merged, which might explain why shift-click crafting had been limited to one operation previously. I've gone ahead and opened a new PR just enabling that code, but I can revisit this if there are further performance concerns blocking that other PR.

**Pull request closed without merging**
