### PR TITLE
Shader and material system

### PR DESCRIPTION
**Pull request by hecktest**
**This PR is a Work in Progress**
The code should compile but it'll definitely fail to link until the GL proc address issue is resolved.

This is a draft of a replacement for shaders and materials. It's currently being written against pure OpenGL and STL; figuring out a way to bind it back to irrlicht is something that should be done last.

When complete, this system will:
- Allow runtime toggling of `#define` controlled shader features (those pesky shadows...)
- Allow per-material and per-shader control of said features
- Allow runtime modification of materials without having to destroy and remake them
- Handle shaders and materials by reference
- Allow runtime reassignment of shaders
- Query data about uniforms from OpenGL instead of having to know and hardcode it in advance
- Allow per-object and per-node uniform assignment, which will be trivial to hand over to script control
- Decouple an important part of the renderer from Irrlicht's crusty ancient ways
- Provide pretty much anything else you'd expect from a modern game engine in the shaders department

todo:
- [x] Concept
- [x] Types
- [x] Uniform API
- [x] Uniform memory management
- [x] Uniform state migration
- [x] Setting GL uniform state
- [x] Setting GL fixed state
- [x] Fixed state in materials
- [x] Variant generation
- [x] Variant selection
- [x] Mutually exclusive features
- [x] Feature toggling API
- [ ] Make necessary Irrlicht modifications
- [ ] Modify scene nodes to use the new materials
- [ ] Hammer into MT code style

### CODE REVIEW

**Comment by Pantyhose-X** [comment]
Shader https://www.shadertoy.com/browse

**Comment by hecktest** [comment]
Fixed the wall of errors, now I've got to actually finish this, replace all existing shader and texture usage with it, and then somehow punch through irrlicht to get the necessary proc addresses.

**Comment by Pantyhose-X** [comment]
Model uses a similar [Blender Shader](https://styly.cc/tips/blender_shader_beginner/) specification mechanism

**Comment by lhofhansl** [comment]
@hecktest Do you plan to finish this?

**Comment by hecktest** [comment]
@lhofhansl 
Yes, I just need to do some things to irrlicht first to make it work:
- Reduce video drivers to one common subset for all platforms (GLES2 feature level)
- Expose the GL functions
- Remove remaining SMaterial and SLight usage, delete irrlicht's material system
- Hook into the rendering process so that I can set my materials

Relevant activity:
#11395
minetest/irrlicht#48 
#11424 (discussion)

**Comment by Andrey2470T** [comment]
Is there currently a progress? And also would this PR provide some modding API for assigning materials for nodes/entities which would define their ambient/diffuse/specular components?

**Pull request closed without merging**
