### PR TITLE
Get movement setting instead of hard coded value

### LINKED ISSUE #2356: Anticheat says player moves too fast regardless of `movement_speed_fast` parameter
I'm trying to set up the `sprint` mod on a linux server and facing this problem. Also, `movement_speed_walk` and `movement_speed_fast` are affecting actual default player speed so probably anticheat should have another separate `max_player_speed` option or allow mods to set `max_player_speed` for each player individually.

### PR DESCRIPTION
**Pull request by asl97**
Fix #2356 

i figure fixing it in server.cpp would be way too complex for me to do it so i keep it simple and read the setting in player.cpp

### CODE REVIEW

**Comment by rubenwardy** [comment]
Is player.cpp run client side? Wouldn't this read the client setting if the server doesn't send them?

**Comment by est31** [comment]
Can the fix be a bit more proper? I think I understand what you want to achieve, but can you move the code that reads the defaults to the RemotePlayer class? So move the constructor from player.h to player.cpp and override behaviour of the superclass.

**Comment by est31** [comment]
@rubenwardy the constructor @asl97 changed is ran both by client and server. And yes, if the server missed to send actual values, it would read the client settings. Therefore and because I think its more proper the changes should be done to RemotePlayer only.

**Comment by PilzAdam** [comment]
This doesn't seem to be a proper fix.

**Comment by asl97** [comment]
@est31 @PilzAdam i know, which is why i said `it might be pretty bad if the server fails to send the movement` on the irc which nobody reply.
http://irc.minetest.ru/minetest-dev/2015-12-02#i_4465203

**Comment by est31** [comment]
Looks good :+1:

**Comment by BlockMen** [comment]
19f73e4efc14622b4d020c9d373176cd7801e37f

**Pull request closed without merging**
