### PR TITLE
Don't use day light sky unless fly and noclip priviledges are given and noclip and free_move are enabled

### LINKED ISSUE #4640: [discuss] free-move sky color in caves
I know it's by design, and I think this came up before, but with the current logic that always has the default sky color when free-move is enabled it looks dorky in caves (invisible portions of the cave are bright).

As a test I disabled that logic to see what would happen with free-move enabled and it looks fine in all cases I tested (above ground day/night, in large caves day/night) - much better than what Minecraft does in fact.

As there was specific code to do that, I'm sure there's a good reason and I'm missing something.
Perhaps performance?

Anyway, if anybody wanted to try as well here is a super trivial patch to do that:
```
diff --git a/src/game.cpp b/src/game.cpp
index ed2673c..ad8536f 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -4097,17 +4097,12 @@ void Game::updateFrame(ProfilerGraph *graph, RunStats *stats,
        float direct_brightness;
        bool sunlight_seen;
 
-       if (g_settings->getBool("free_move")) {
-               direct_brightness = time_brightness;
-               sunlight_seen = true;
-       } else {
-               ScopeProfiler sp(g_profiler, "Detecting background light", SPT_AVG);
-               float old_brightness = sky->getBrightness();
-               direct_brightness = client->getEnv().getClientMap()
-                               .getBackgroundBrightness(MYMIN(runData->fog_range * 1.2, 60 * BS),
-                                       daynight_ratio, (int)(old_brightness * 255.5), &sunlight_seen)
-                                   / 255.0;
-       }
+       ScopeProfiler sp(g_profiler, "Detecting background light", SPT_AVG);
+       float old_brightness = sky->getBrightness();
+       direct_brightness = client->getEnv().getClientMap()
+                       .getBackgroundBrightness(MYMIN(runData->fog_range * 1.2, 60 * BS),
+                               daynight_ratio, (int)(old_brightness * 255.5), &sunlight_seen)
+                           / 255.0;
 
        float time_of_day = runData->time_of_day;
        float time_of_day_smooth = runData->time_of_day_smooth;
```
I'll run with this change going forward (my son and I like to fly around in Nether :) ).
Feel free to close if this is 100's time this came up.

### PR DESCRIPTION
**Pull request by lhofhansl**
Simply sky-color fix.

Fixes  #4640 and #4187

Only when a player enables noclip and free_move does it make sense to show the day-light sky. In all other cases (i.e. either the noclip or fly priviledges are given or player did not enable noclip or free_move) we should show the brightness adjusted sky.

### CODE REVIEW

**Comment by lhofhansl** [comment]
Hmm... I might have screwed up the commits. The diff is correct though. Can you squash the commits when you integrate?

**Comment by paramat** [comment]
The first 2 commits are not needed.

**Comment by paramat** [comment]
:-1: This quadruples the amount of setting and priv checks per frame. If we change this let's keep it to one only, perhaps just 'noclip'?
Also, should this setting value be cached as a constant instead of getting it per-frame?

**Comment by lhofhansl** [comment]
Fair enough.

Perhaps we could change the code to a single check for "noclip" instead of "free_move" (or probably in addition to "free_move"). I think that's what most folks would want as noclip is the "real" cheat...? It seems many folks play with fly mode enabled.

Otherwise let's close this one.

**Comment by Fixer-007** [comment]
>Accidently having fly enabled when without the priv

it happens to me all the time, it is annoying and adds bad feeling of poorly written minetest (why the hell player should care about this ____ "enabled but no priv"? It should be fixed in some way or another.

**Comment by lhofhansl** [comment]
I agree that it leaves sometimes a bad impression for those who use Minetest the first time with incorrect settings. Personally, I just find it annoying that I cannot fly in a cave without loosing the entire cave experience, but I can just have a local patch. But it's clearly not the end of the world.

I love the xkcd you linked, will use in the next meeting with my team :)

**Comment by paramat** [comment]
Sure we could consider deciding it on noclip instead of freemove, that may be better actually, let's see what others think. Checking for both noclip and freemove may not be much better because the 2 are so often used together.

**Comment by paramat** [comment]
Ok i agree with deciding this on noclip, as creative servers probably grant freemove to players and it would be preferable to keep dark sky in that case.

**Comment by lhofhansl** [comment]
I bodged the commit history now... Will create a new PR. Sorry about this.

**Comment by lhofhansl** [comment]
Created #4646 instead.

**Pull request closed without merging**
