### PR TITLE
Require 'waving = 3' in nodedefs to enable liquid waving shader 

### PR DESCRIPTION
**Pull request by paramat**
Require 'waving = 3' in nodedefs to enable liquid waving shader

Makes the liquid waving shader per-nodedef like waving leaves/plants,
instead of being applied to all liquids.
Like waving leaves/plants, liquid-type waving can be applied to meshes
amd nodeboxes.
//////////////////////////////

screenshot_20190323_023224

^ At last in MTG river water and lava doesn't have to wave.

screenshot_20190323_235032

^ Opaque works.

screenshot_20190323_023604

^ Waving nodeboxes are fun

Screenshot from 2019-03-24 00-17-53

^ Call this 'Waving liquids' (only settings menu text changed).

Attends to #5694 
Rebased and improved version of #5897 which was abandoned by the author.

Previously, when the waving water shader was enabled, all liquid nodes waved, there was no use of `waving = 1` in nodedefs as used by the waving leaves and waving plants shaders.
Now, waving water is consistent with the other waving shaders. `waving = 3` is required in a nodedef to allow a liquid node to wave when the client enables the waving water shader.
Meshes and nodeboxes can also use `waving = 3` to ripple vertically.

### CODE REVIEW

**Comment by pgimeno** [comment]
In its current form, my patch to #8369 makes the bottom of the node wave too (because the vertex shader lacks information to distinguish top vertices from bottom vertices). I wonder how that fact affects this PR.

**Comment by paramat** [comment]
I can't see how this PR affects your experiment in #8369 , as this just restricts the shader to certain nodes. Can you explain further?
This slightly addresses that issue in terms of dangerous nodes like lava, if waving is not essential for a particular liquid it can be turned off to properly see the true edge of the node.

**Comment by pgimeno** [comment]
I'm thinking mainly about things that are not liquids, like the waving nodeboxes. Actually the bottom waves either way, just the distance to the next upwards vertex is bigger, so never mind.

**Comment by paramat** [comment]
Ah i see, your patch is intended for full cube liquid nodes and may not be suitable for meshes and nodeboxes. We can reassess your patch and see it behaves once this PR is merged.

**Pull request merged**
