### PR TITLE
Improve desktop file

### PR DESCRIPTION
**Pull request by apoleon**
This commit adds keywords to the desktop file. Keywords are useful in modern desktop environments such as GNOME3 or KDE to improve search requests.

### CODE REVIEW

**Comment by nerzhul** [comment]
I approve

**Comment by rubenwardy** [comment]
No "video game" or similar?

**Comment by sfan5** [comment]
a6dd6199385fccd0659232b3a4425e9d125c297c

**Comment by apoleon** [comment]
On Tue, 20. Jan 11:44 rubenwardy <notifications@github.com> wrote:
>    No "video game" or similar?

Feel free to choose any keywords you like. However they should not be
redundant with the values of Name and GenericName.

http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

"A list of strings which may be used in addition to other metadata to
describe this entry. This can be useful e.g. to facilitate searching
through entries. The values are not meant for display, and should not be
redundant with the values of Name or GenericName."

**Pull request closed without merging**
