### PR TITLE
Improve irr_ptr

### PR DESCRIPTION
**Pull request by numberZero**
`irr_ptr` improvements for #10636 and #10658. I hope new documentation is more clear.

### CODE REVIEW

**Comment by sfan5** [comment]
Looks good but please fix clang-format's complaints: https://github.com/minetest/minetest/pull/10808/checks?check_run_id=1711452120

**Comment by numberZero** [comment]
These fixes make the code look worse (less uniform). Compare:
```c++
template <typename ReferenceCounted>
bool operator==(const ReferenceCounted *a, const irr_ptr<ReferenceCounted> &b) noexcept
{
    return a == b.get();
}

template <typename ReferenceCounted>
bool operator!=(const irr_ptr<ReferenceCounted> &a, const irr_ptr<ReferenceCounted> &b) noexcept
{
    return a.get() != b.get();
}

template <typename ReferenceCounted>
bool operator!=(const irr_ptr<ReferenceCounted> &a, const ReferenceCounted *b) noexcept
{
    return a.get() != b;
}
```

```c++
template <typename ReferenceCounted>
bool operator==(const ReferenceCounted *a, const irr_ptr<ReferenceCounted> &b) noexcept
{
    return a == b.get();
}

template <typename ReferenceCounted>
bool operator!=(const irr_ptr<ReferenceCounted> &a,
        const irr_ptr<ReferenceCounted> &b) noexcept
{
    return a.get() != b.get();
}

template <typename ReferenceCounted>
bool operator!=(const irr_ptr<ReferenceCounted> &a, const ReferenceCounted *b) noexcept
{
    return a.get() != b;
}
```
Does that worth it?

**Comment by sfan5** [comment]
I don't mind it that much.

**Comment by randomMesh** [comment]
> These fixes make the code look worse (less uniform).

The code would look like the [Sign of the horns](https://en.wikipedia.org/wiki/Sign_of_the_horns). 

I'd either leave it as it is or cripple all three template functions in order to maintain uniformity.
I wise man once said "It doesn't matter how you do it, but be consistent."

**Comment by numberZero** [comment]
> I don't mind it that much.

@sfan5 don’t mind what, breaking the check or breaking uniformity?

**Comment by sfan5** [comment]
Breaking uniformity. But really just pick what you prefer out of applying clang-format suggestions or disabling clang format for this code section.

**Comment by numberZero** [comment]
@sfan5 #10792

**Review by rubenwardy — APPROVED** [review]

**Comment by rubenwardy** [comment]
> These fixes make the code look worse (less uniform). Compare:

You should be able to apply the break to the other functions too, to keep uniformity

But I also don't mind between this, not having uniformity, or using `// clang-format off`

**Comment by numberZero** [comment]
okay, used `// clang-format off`

**Pull request merged**
