### PR TITLE
Pathfinder: Send errors to `warningstream`.

### PR DESCRIPTION
**Pull request by kaeza**
Avoids spamming the chat about several errors.

### CODE REVIEW

**Comment by sofar** [comment]
yes please

**Comment by paramat** [comment]
:+1:

**Comment by nerzhul** [comment]
it's a bit hacky not ? warning is a log level, like critical, the best question is why do we show errors to chat ?

**Comment by paramat** [comment]
I can see good reason to spam chat with these errors.

**Comment by Fixer-007** [comment]
Players don't need to see those errors (including serialisation one), thats for devs only.

**Comment by kaeza** [comment]
@paramat showing errors in chat may be useful in some cases. This is not one.

**Comment by paramat** [comment]
I agree, maybe my comment was badly worded. 'If' these errors are not needed in chat then +1.

**Comment by SmallJoker** [comment]
Only the particular error message `failed to update cost map` should be changed. That seems to be only an information that it failed to find the path. The other errors indicate a more serious problem, thus changing the error handling for all of them looks wrong to me.

**Comment by Wuzzy2** [comment]
Pushing an error to the in-game chat should only be done if something went very wrong. If this is the case, it is actually good that these errors are annoying, it gives a strong motivation to fix the underlying bugs. :D

But in this case, I don't see why it is even considered to be an error when the pathfinder failed to find a path. Isn't this just part of normal pathfinding? These messages are warnings *at best*, because I don't see the “error”.

Summary: :+1:

**Comment by paramat** [comment]
What this PR needs is details of what messages are appearing and why they don't need to be in chat, how can devs judge the PR otherwise?

**Comment by paramat** [comment]
:+1: Warning stream is fine, no need to spam chat.

**Comment by paramat** [comment]
09f2cd0264993e7b81d84d77bfc670b40ef82444

**Pull request closed without merging**
