### PR TITLE
Mainmenu: Priorize non-modpack mod for "enabled" status colorization

### PR DESCRIPTION
**Pull request by snowyu**
Add compact, short information about your PR for easier understanding:

- Resolved the issue #11552

## To do

This PR is Ready for Review.

## How to test

See issue #11552

### CODE REVIEW

**Comment by Emojigit** [comment]
Close #11552 (try to link them)

**Comment by SmallJoker** [comment]
Did you check whether this PR now highlights the mod which is used by Minetest? The mod loading order for conflicting names is not defined anywhere, and might be based on alphabetical sorting rather than modpack vs normal installation.

**Comment by snowyu** [comment]
Yes, I've checked the case. I assume that the algorithm of preparemodlist is roughly correct. It just does not check whether the mod comes from modpack or global. Do you think it is caused by a wrong sorting algorithm in preparemodlist?

**Comment by SmallJoker** [comment]
> It just does not check whether the mod comes from modpack or global

Yes there's no way of knowing without using the actual C++ functions for that. This PR only makes sense if the "global" mod is used, rather than the modpack one. Otherwise it would be misleading information.

**Comment by snowyu** [comment]
So, I think the right way should be to export the c++ function as lua api.

**Comment by rubenwardy** [comment]
Closing in favour of #11784

**Pull request closed without merging**
