### PR TITLE
[no squash] Irrlicht import

### PR DESCRIPTION
**Pull request by Desour**
First commit just copies irrlichtmt (as of https://github.com/minetest/irrlicht/commit/124708784fdc4321d5983cdbfb889e62fbd25f40) to `<root>/irr/`.

Second commit makes use of this irrlichtmt version, and removes a bunch of now useless stuff.

Related: #13642

Note: `lib/irrlichtmt` is still gitignored. This is good because you can still bisect this way, and also we don't mess with repos lying around there.
Users can decide themselves when they want to delete it, but they have to do it manually.

Co-authored by sfan5.

## To do

This PR is Ready for Review.

## How to test

* Build.
* Watch the CI.
* Check and test build artifacts.
* Read through other commits. Reproduce 1st commit if you want.

### CODE REVIEW

**Comment by Desour** [comment]
The CI on ubuntu 20.04 is failing because of SDL2, see also:
https://github.com/minetest/irrlicht/blob/05c8bc831485077f7fffe05b186936928249de75/.github/workflows/build.yml#L64

And the mingw stuff downloads dependencies from @sfan5's website.

I need help here.

**Comment by sfan5** [comment]
one more: please amend the import commit with an author like `import <script@mt>` so the commit stats don't get thrown way off.

**Comment by appgurueu** [comment]
Perhaps I'm missing something, but https://github.com/minetest/minetest/pull/14483/commits/60b1249992220db6953395a531082659ab47ae70 seems to just copy the sources? This would lose history entirely, as opposed to a [subtree merge](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges) which would preserve history.

**Comment by sfan5** [comment]
My plan never was to do a subtree merge.

**Comment by Desour** [comment]
> Perhaps I'm missing something, but [60b1249](https://github.com/minetest/minetest/commit/60b1249992220db6953395a531082659ab47ae70) seems to just copy the sources? This would lose history entirely, as opposed to a [subtree merge](https://docs.github.com/en/get-started/using-git/about-git-subtree-merges) which would preserve history.

Yes, it's just a copy. AFAIK, this is what we planned to do.

> one more: please amend the import commit with an author like `import <script@mt>` so the commit stats don't get thrown way off.

:chart_with_upwards_trend: :no_entry_sign: 
Will do after CI ran.

**Comment by Desour** [comment]
Re-copied from current irrlichtmt master, and squashed.

>please amend the import commit with an author like `import <script@mt>`

This is done, btw.. Github still shows my profile picture because I'm the committer, and it doesn't know the `import <script@mt>` author.

**Comment by nerzhul** [comment]
cannot we import this properly in git mode keeping irrlicht mt commits ? there is a way to merge repo

**Comment by sfan5** [comment]
Reasons for not doing a subtree merge (IMO):
* irrlicht svn history is only partial anyway
* pulling in lots of changes because we *just* reformatted and moved the code (also the CRLF conversion earlier)
* irrlicht repo can be kept around as archive for a while
* not sure if that creates a merge commit, we like to avoid those

**Review by sfan5 — APPROVED** [review]

**Comment by Desour** [comment]
>not sure if that creates a merge commit, we like to avoid those

And if it doesn't, it would instead add around 500 commits on top of our history.

I also prefer the current choice of just copying it in.

(Self-approving.)

**Comment by lhofhansl** [comment]
I think we want to get rid of as much of Irrlicht as we can. The history is less and less important. With all the changes we did, chances are we cannot integrate anything from/to upstream anyway - and that is assuming that Irrlicht upstream isn't mostly dead anyway.

Count as in favor of just copying the files over (not history) - and then remove as much as we can of Irrlicht over time.

**Comment by lhofhansl** [comment]
Can we move ahead with this, or is there further discussion to have?

**Comment by celeron55** [comment]
The goal of forking Irrlicht was to fuse Minetest and irrlicht together to enable customizing the entire rendering system to suit MT's special use case which will never be Irrlicht's goal in its upstream.

It doesn't seem to me like a bad time to do the repo import now - irrlichtmt is relatively problem free and has shrunk a lot from its original size. While we have had a very fluctuating availability of graphics programmers to improve, optimize and modernize the rendering, there has been enough progress to validate the sanity of the plan.

Part of this is removing everything unneeded from Irrlicht to make it manageable and appetizing for new development. Irrlicht contains vast amounts of stuff that is of no use and no interest to us, and is only a burden. Not including the history of irrlichtmt in the minetest repo fits all this well enough.

**Comment by grorp** [comment]
Re opinions needed: I like this 👍

**Pull request merged**
