### PR TITLE
ellipsis, added

### PR DESCRIPTION
**Pull request by leela52452**
[source](https://hosted.weblate.org/projects/minetest/minetest/source/review/?type=check%3Aellipsis)

### CODE REVIEW

**Comment by SmallJoker** [comment]
paramat seems to be opposed to the ellipsis. https://github.com/minetest/minetest/pull/7726/files#r217747402

And for my part - I don't see how this improves anything. ASCII is good enough here.

**Comment by paramat** [comment]
Ezhh dislikes it too https://github.com/minetest/minetest/pull/7726/files#r217749403
I can't see any benefit. The ellipsis is 3 dots crammed into a tiny space and therefore visually unclear, almost looks like an underscore.
It's not present on keyboards, which is not helpful for development.
:-1:

**Comment by rubenwardy** [comment]
This is the better character to use in user interfaces - Android, for example, shows a warning when you type three dots

**Comment by paramat** [comment]
Hmm in fact, can't we just remove those uses of '...' as they are unnecessary? I would support that.

**Comment by Calinou** [comment]
It's a good idea to add an ellipsis to denote tasks that may take a while (several seconds). However, the Unicode ellipsis character `…` may not display correctly in builds where FreeType isn't enabled, so we should keep using the ASCII approximation `...`.

**Comment by HybridDog** [comment]
Some broken fonts do not have all Unicode characters; using ASCII dots is generally more reliable in my opinion.

**Comment by SmallJoker** [comment]
> (Does the default bitmap font include the … character?)

Bitmaps: No (might depend on the converted font, though)
XML fonts: Yes

**Comment by DS-Minetest** [comment]
> The ellipsis is 3 dots crammed into a tiny space and therefore visually unclear, almost looks like an underscore.

That depends on whether you use a monospace font.
> It's not present on keyboards, which is not helpful for development.

Well I can write an ellipsis (with qwertz): `AltGr + . -> …`

The code style guidelines don't allow to write non-ASCII chars in source code:
>Do not use characters in C++ files from outside the ASCII character set. 

https://dev.minetest.net/Code_style_guidelines#Miscellaneous
Hence the utf-8 `0xE2 0x80 0xA6` has to be used, I guess.

(I don't care whether … or ... is used.)

**Comment by SmallJoker** [comment]
No apparent benefit for me. Also no merge in sight according to the different opinions.

**Pull request closed without merging**
