### PR TITLE
Replace get/set_nametag_color by get/set_nametag_attributes

### PR DESCRIPTION
**Pull request by TeTpaAka**
The old methods had a too narrow function.

### CODE REVIEW

**Comment by C1ffisme** [comment]
There are nametag colors? I wish I knew about this.

**Comment by TeTpaAka** [comment]
It got merged today. It shouldn't be used right now because I replaced it with this request.

**Comment by C1ffisme** [comment]
Cool.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/18c2f16c138f4b40b4705507b46d24e1518e4705

**Pull request closed without merging**
