### PR TITLE
[FormSpec] Add 'mesh' element.

### PR DESCRIPTION
**Pull request by Andrey2470T**
Revives #10261 . Also fixed a bug with setting 'mouse_control' property. Now it is enabled on default.

## How to test
1. Create and go to a minetest world in 'dev_test' game.
2. Summon '/test_formspec' cmd.
3. Switch to 'Scenes' tab.

### CODE REVIEW

**Comment by pyrollo** [comment]
Duplicate with #10320

#10320 preserves more commit information (authoring in particular).

**Comment by Andrey2470T** [comment]
But really does that have any importance it conserves the author`s commits? My PR is different only in that it has 'mesh' element called as in the original PR, not 'model' as in yours.

**Comment by Andrey2470T** [comment]
And also my PR had been created two minutes earlier than SmallJoker`s one. So actually it can not be named "duplicate".

**Comment by rubenwardy** [comment]
You authored the commits as if you were the sole author. SmallJoker's PR correctly attributed kilbith

**Comment by Andrey2470T** [comment]
May I ask for how had I to do it? I don`t know how to attribute anothers` commits.

**Comment by pyrollo** [comment]
> But really does that have any importance it conserves the author`s commits?
Of course. First it is a matter of respect to the original author. Legally copyright states that you cannot change the author without his consent. GPL states the same.

> May I ask for how had I to do it? I don't know how to attribute anothers' commits.
You can do that with git commit --author : https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt

I guess SmallJoker pulled the PR with all commit information and created a new one based these commits.

**Pull request closed without merging**
