### PR TITLE
Add Android drivers to the video_driver drop-down menu

### PR DESCRIPTION
**Pull request by Wayward1**
Adds the Android video drivers ogles1 and ogles2 to the video_drivers drop-down menu so Android users don't have to manually edit the minetest.conf

### CODE REVIEW

**Comment by paramat** [comment]
ogles1 is ok but why ogles2 if it causes bugs? Is this temporary to make Android dev easier?

**Comment by red-001** [comment]
@paramat same reason we have null, software and burningsvideo?

**Comment by Wayward1** [comment]
That, and simplifying development and testing, and it also helps address the issue mentioned [here](https://github.com/minetest/minetest/issues/5600#issuecomment-298174586) where it appears certain devices use the wrong driver by default.

**Comment by stujones11** [comment]
> Why ogles2 if it causes bugs?

It looks like there is an easy fix for that :)

> Is this temporary to make Android dev easier?

I can testify that it does just that, but android users should not be forced to edit the config to change drivers for whatever reason. Also consider those working on RPi builds, etc.

**Comment by paramat** [comment]
Ok, i'm just hesitant to add an option that is known to not work, but since altering .conf on Android is, i assume, difficult maybe it's ok temporarily.

**Comment by red-001** [comment]
`null` straight up causes a core dump on startup, but that's still in the enum

**Comment by red-001** [comment]
Then I suggest removing `null` and `software` and maybe also burnings video, the first two cause straight up crashes on start up requiring editing minetest.conf to even get minetest to work again and the third causes graphical glitches in my experience.

**Comment by Wayward1** [comment]
> i'm just hesitant to add an option that is known to not work

That may soon change, as mentioned [here](https://github.com/minetest/minetest/issues/5600#issuecomment-359897482)

As for editing the .conf, it does add some steps to the development and testing process, especially on certain devices that don't have a built-in file manager.

**Comment by stujones11** [comment]
I suggest not removing anything, maybe even add ogles3. These are 'advanced' settings, after all and you shouldn't really be messing with these unless you understand exactly why you are doing it.

However, in the case of some android users, it automatically defaults to ogles2 (unconfirmed) and to quote @nerzhul from #5600 'Editing .conf is unacceptable on android'.

**Comment by sfan5** [comment]
> maybe even add ogles3

Second time I'm saying this: Irrlicht does not support OpenGL ES 3.0, there is no `ogles3` option for video drivers.

**Comment by stujones11** [comment]
> Irrlicht does not support OpenGL ES 3.0

That was meant to be somewhat ironic but hey, we can always live in hope :)

**Comment by paramat** [comment]
Ok fine for me then :+1:

**Comment by stujones11** [comment]
While I still maintain that these advanced options are fine, it would be much nicer if we only got those applicable for a given platform. This is of course not possible with the current system, however, in the case of android it would be possible to alter that file using the stream editor after copying the assets in the `Makefile`
```
	cd ${APP_ROOT}/assets ||  exit 1; 
	sed -i 's/opengl null.*$$/ogles1 ogles1,ogles2/' Minetest/builtin/settingtypes.txt; \
```
Works for me :)

**Comment by paramat** [comment]
See #6971 that makes ogles2 work, this can be merged with that.

**Pull request merged**
