### PR TITLE
Complete collision rewrite

### PR DESCRIPTION
**Pull request by scrain777**
This PR is for a rewrite of the collision code using an inverted index data structure.

The goal is to provide reliable collision detection for mobs. The current collision implementation makes a list of collision boxes near where the mob is moving, and looks through the whole list repeatedly, trying to check if the mob will collide with any of them.

The new data structure efficiently identifies the collision boxes in the order they collide with a moving query box. Each dimension of the boxes are indexed, and the indexes are placed into a heap so that the algorithm can track when boxes pass into or out of the space of the query box in one dimension. When a box already overlaps in 2 dimensions and crosses over into the 3rd detection, a collision is registered. To detect if the query box is supported (standing on ground, stepping up against a wall), look for boxes that are adjacent to the required face and overlap in the other two dimensions.

There are many reported problems with entities failing to properly detect collisions while moving. This also resolves issues with collision unit tests.

## To do

This PR is a Work in Progress

- [X] There is currently mangling of memory that occasionally fails unit tests, including segmentation faults and values being overwritten in memory. I'm making a PR largely to see what valgrind reports (I am developing on Windows). The offending bug overwrote the most significant 16 bits of a u32, so that narrows the hunt to 16-bit operations, or perhaps freeing memory that was not allocated.
- [ ] Finish writing a query for collision detection with linear motion. (Basic movement.)
- [ ] Write a query for collision detection and loss-of-support on one face detection with linear motion. (Stepping up against a wall, stepping forward over a wall.)
- [ ] Write a query for collision detection and loss-of-support on two faces detection with linear motion. (Stepping up when the entity collided directly into a corner.)
- [X] Write unit tests for the query context classes.
- [ ] Write unit tests for the queries.
- [ ] Rewrite collision detection logic using the queries.
- [ ] Resolve bugs identified by unit tests.
- [ ] Field test extensively.
- [ ] Compare performance characteristics (esp. memory and processor time) with existing implementation.

## How to test

1. Build with unit tests enabled.
2. Run the unit tests. look for failures in the TestInvertedIndex and TestCollisionQuery groups.
3. Run minetest. Build a tall wall around a space. Leave a gap and build another tall wall a few blocks out from the first wall. Spawn 10 mobs that won't kill each other inside the first wall. Sit on top of the wall and wait a while to see if the mobs cross over into the space between the walls.

## Future directions

- If the entity is moving very fast, the number of possible collision boxes is very large, and there may be many collision boxes that share space with the query box in one dimension, even though they are far away in other dimensions. This implementation will have to track them, in case they eventually share space in the other dimensions. Depending on how this works in practice it may be beneficial to separately index each block, and only attend to boxes that are in an active block.  Incidentally, the number of collision boxes in an index would be much smaller, so that the memory used for each could be cut in half. 

- When there are multiple entities moving in an area, they could all share the same inverted indices.

- Explore whether this implementation could be extended to detect entities that collide during movement instead of treating the other entities as immobile.

- If the indexes could be updated efficiently when nodes change, the data structure for each active block could be kept in memory for reuse rather than rebuilding it repeatedly. Or, they could be cached if there were a way to invalidate them when a block changes.

- The new implementation would be amenable to incorporating more physics during query execution (friction, spring coefficients, continuous acceleration). Performance overhead is probably reasonable.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Performance comparisons will also be interesting to see afterwards.
I'd like to put @TheTermos who also looked into collisions recently into the loop - also for feedbacks and design considerations.

**Comment by TheTermos** [comment]
> Build a tall wall around a space. Leave a gap and build another tall wall a few blocks out from the first wall. Spawn 10 mobs that won't kill each other inside the first wall. Sit on top of the wall and wait a while to see if the mobs cross over into the space between the walls.

This description is most vague, have you found an issue with the current implementation?
If so, can you file an issue giving a more detailed description?

**Comment by TheTermos** [comment]
> I'd like to put @TheTermos who also looked into collisions recently into the loop - also for feedbacks and design considerations.

**Inverted index structure**

> If the entity is moving very fast, the number of possible collision boxes is very large, and there may be many collision boxes that share space with the query box in one dimension, even though they are far away in other dimensions.

This affects nodeboxes the most, but they are already nicely aligned with the node grid. It's really simple math to retrieve only the boxes contained in nodes that are on the moving boxes path, and in order of colliding.
In fact I developed such a function in lua as a part of support for entites of arbitrary collisionbox size, it's only a few lines of code and it's c++ counterpart is going to be faster and orders of magnitude less complex than inverted index, so II isn't the best possible solution.
However it may potentially be useful for object boxes which aren't node aligned. The way I see it
- make the inverted index structure a separate abstract object not related to collision detection or any other aspect of the engine, this way it won't increase overall complexity.
- see if it can be used to  improve for example `ServerEnvironment::getObjectsInsideRadius()`. I doubt it would noticeably affect collision detection, but may improve the lua interface `get_objects_inside_radius()` which unlike CD, there were actually complaints about performance of.

**Rewrite:**
A I said elsewhere, IMO rewrite is in order, but doing it before #9346 is resolved makes little sense, like building a complex structure on mud. Also considering:
- there weren't ever any performance issues related to CD I'd know of.
- there are no known issues with the current implementation so far.
- this idea has been triggered by an issue that has long been resolved.
- it addresses possible issues that than happen under extreme conditions (large values of dtime/velocity), but these conditions are already symptoms of other problems or lead to other problems not necessarily related to CD, MT simply doesn't handle these conditions very well overall, so while better CD support for these conditions is good to have, it wouldn't be of much benefit at this particular time.

My opinion: Now the effort is better spent on #9346 (maybe even much needed #9806 lol nvm I'm a dreamer), then collision rewrite.

**Comment by maikerumine** [comment]
I have a suspicion that this rewrite is causing major game crashes with mods that use entities / objects that are moving.
I have done many different tests with different mobs api's and even tried to fix a few nil issues, to no avail.
It seems like an object gets deleted while on step and returns nil for the value originally.

Does this mean we need to nil check every variable in our mods with objects?


Typical error is:
`2020-08-19 19:48:33: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'mobs' in callback luaentity_Step(): D:\MT\500\minetest-5.3.0-win64\bin\..\mods\mobs/api.lua:408: attempt to compare nil with number
2020-08-19 19:48:33: ERROR[Main]: stack traceback:
2020-08-19 19:48:33: ERROR[Main]: 	D:\MT\500\minetest-5.3.0-win64\bin\..\mods\mobs/api.lua:408: in function 'func'
2020-08-19 19:48:33: ERROR[Main]: 	...-5.3.0-win64\bin\..\builtin\profiler\instrumentation.lua:106: in function <...-5.3.0-win64\bin\..\builtin\profiler\instrumentation.lua:100>
`

Any thoughts?

**Comment by rubenwardy** [comment]
Closed due to inactivity

**Pull request closed without merging**
