### PR TITLE
Mark Redis database backend as deprecated

### PR DESCRIPTION
**Pull request by sfan5**
**Context**
Redis isn't really a good key-value *database* but more of a cache.
This is evidenced by how it [presents itself](https://github.com/redis/redis/?tab=readme-ov-file#what-is-redis) and stuff like [eviction algorithms](https://redis.io/docs/latest/develop/reference/eviction/), which would cause terrible data loss if applied to Minetest worlds, as well as keeping all data in RAM, which is inconvenient and unnecessary for MT.
A big selling point for redis is also distributedness, which is relevant for web applications (lots of concurrent processes, clusters, ...) whereas Minetest is a single-threaded, single-instance application.

**Description**
There's probably nobody really using redis so I propose deprecating and eventually removing it.
This PR both adds a deprecation message and will automatically turn all Redis access read-only with 5.10.0 (or whichever version is next).

**Alternatives**
People who require a networked database can switch to Postgres.
People who don't can switch to SQLite or LevelDB.
Worth noting that both Postgres (own implementation) and SQLite (via the OS) keep often used data right in RAM, so this isn't a property exclusive to Redis.
If someone absolutely wanted to remove disk access latency from world loading they can use sqlite on tmpfs and I'm sure postgres can also can also be configured in this manner.

### CODE REVIEW

**Comment by appgurueu** [comment]
There's also the "dummy" backend for servers like CTF which save the static map data that needs to be persisted in schematics and want the relatively small map to be very fast at runtime, hence want to keep it entirely in RAM.

Considering this, it seems very likely to me that we can deprecate Redis. If it turns out that we missed a use case, the affected people will complain about the deprecation, so that we can reconsider it. (Ideally, they would complain about it right now, but it is likely that this discussion doesn't reach them, and likely isn't worth the effort to seek them out.)

**Comment by HybridDog** [comment]
Redis has been renamed to [Redict](https://redict.io/posts/2024-03-22-redict-is-an-independent-fork/).

**Comment by sfan5** [comment]
> If it turns out that we missed a use case, the affected people will complain about the deprecation, so that we can reconsider it.

Someone could go and post this on the forums and/or Discord. It's more likely to be seen by relevant people that way.

**Comment by wsor4035** [comment]
> Someone could go and post this on the forums and/or Discord. It's more likely to be seen by relevant people that way.

already was posted in the minetest discord shortly after this pr was made. just posted it to a more targeted group as well

**Comment by sfan5** [comment]
approved on IRC -> https://irc.minetest.net/minetest-dev/2024-05-26#i_6173695

**Pull request merged**
