### PR TITLE
remove zh_* from GETTEXT_BLACKLISTED_LOCALES

### LINKED ISSUE #4638: Don't ship with broken languages
There are a few languages which are broken in minetest, like hebrew, as minetest doesn't support RTL and doesn't ship a font that supports hebrew. The issue can be seen as a packaging problem, and left to people creating minetest executables, but in the best case it'd be managed in the master branch, as packaging should be as trivial as possible.

An English fallback is in this case much better than a broken language support because Minetest at least is usable.

Languages confirmed to work/not work: (complete list)
- [x] : English, obviously
- [ ] : Belarusian, translations seem empty
- [x] : Catalan, looks fine to me (@sfan5)
- [x] : Czech, already in minetest for a long time
- [x] : Danish, already in minetest for a long time
- [x] : German, already in minetest for a long time
- [x] : Esperanto, looks fine to me (@sfan5)
- [x] : Spanish, already in minetest for a long time
- [x] : Estonian, already in minetest for a long time
- [x] : French, already in minetest for a long time
- [ ] : Hebrew, confirmed broken on IRC (fonts, RTL)
- [x] : Hungarian, already in minetest for a long time
- [x] : Indonesian, looks fine to me (@sfan5)
- [x] : Italian, already in minetest for a long time
- [x] : Japanese, confirmed by @sfan5
- [x] : Lojban, looks fine to me (@sfan5)
- [ ] : Korean, confirmed broken by @sfan5 (fonts)
- [ ] : Kyrgyz, confirmed broken by @sfan5 (fonts)
- [x] : Lithuanian, looks fine to me (@sfan5)
- [x] : Norwegian, already in minetest for a long time
- [x] : Dutch, already in minetest for a long time
- [x] : Polish, already in minetest for a long time
- [x] : Portuguese, already in minetest for a long time
- [x] : Portuguese (Brazil), already in minetest for a long time
- [x] : Romanian, already in minetest for a long time
- [x] : Russian, already in minetest for a long time
- [x] : Serbian (Cyrillic), looks fine to me (@sfan5)
- [x] : Swahili, looks fine to me (@sfan5)
- [x] : Turkish, looks fine to me (@sfan5)
- [x] : Ukrainian, confirmed by @Fixer-007
- [ ] : Chinese (simplified), ???
- [ ] : Chinese (traditional), ???

### PR DESCRIPTION
**Pull request by zaoqi**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
- How does the PR work?
- Does it resolve any reported issue? (partially) #4638 #9198

## To do

- [x] change https://github.com/minetest/minetest/blob/37f771a95bd54e2072f07783df142da4a91e7bff/po/zh_CN/minetest.po#L871 to `yes`

### CODE REVIEW

**Comment by zaoqi** [comment]
How to correctly change this line?
https://github.com/minetest/minetest/blob/37f771a95bd54e2072f07783df142da4a91e7bff/po/zh_CN/minetest.po#L871

**Comment by SmallJoker** [comment]
I already corrected those several weeks ago:
https://hosted.weblate.org/translate/minetest/minetest/zh_Hant/?q=needs_fallback_font&type=all&ignored=False&checksum=&offset=
https://hosted.weblate.org/translate/minetest/minetest/zh_Hans/?q=needs_fallback_font&type=all&ignored=False&checksum=&offset=

No need to change it. It'll be done automatically for the next release.

**Comment by zaoqi** [comment]
@SmallJoker 
The next version was released, but `po` in the master branch has not been updated.

**Comment by SmallJoker** [comment]
:+1:

**Pull request merged**
