### PR TITLE
ActiveObjectMgr::getActiveSelectableObjects

### PR DESCRIPTION
**Pull request by numberZero**
Add compact, short information about your PR for easier understanding:

- Goal of the PR:
  Simplify math
- How does the PR work?
  shootline drawio
- Does it resolve any reported issue?
  No.
- Does this relate to a goal in [the roadmap](../doc/direction.md)?
- If not a bug fix, why is this PR needed? What usecases does it solve?

## To do

This PR is a Work in Progress.
- [x] Add unit tests
- [x] Sort out commits
- [ ] (maybe) Update docs

## How to test

Check that object selection works as usual. Pay attention to rotating selection boxes.

### CODE REVIEW

**Comment by sfan5** [comment]
Can we get some basic unittests for this?

**Comment by Desour** [comment]
So you're essentially replacing the cuboid with a cylinder, right? Looks fine.

**Comment by numberZero** [comment]
> Can we get some basic unittests for this?

Done

> So you're essentially replacing the cuboid with a cylinder, right? Looks fine.

Yes

Is there a way to add a diagram to the docs?

**Review by sfan5 — APPROVED** [review]
seems reasonable

**Comment by sfan5** [comment]
> Is there a way to add a diagram to the docs?

You can drop it into `doc` if you consider it important enough.

**Review by Desour — APPROVED** [review]
Works. Code looks fine.

**Pull request merged**
