### PR TITLE
Camera: Improve arm inertia

### PR DESCRIPTION
**Pull request by kilbith**
Addresses @paramat excellent suggestions in #6063. This PR features : 
- Smooth acceleration when moving the arm ;
- Smooth deceleration when not moving ;
- Proper movement vectoring.

And it fixes the wieldmesh being glitched or hidden in some contexts.

### CODE REVIEW

**Comment by paramat** [comment]
Will test.

**Review by nerzhul — APPROVED** [review]

**Comment by ThomasMonroe314** [comment]
sounds good to me

**Comment by paramat** [comment]
Yes much better, i like how it returns along a vector to the centre.
2 suggestions:
A faster return.
Arm inertai in Y seems a little weird as you are tilting your head up and down instead of turning your body and arm. So i think my personal ideal would be the motion of this PR acting in X plus the pre-arm-inertia 'vertical offset due to view pitch' in Y.

**Comment by kilbith** [comment]
> my personal ideal would be the motion of this PR acting in X plus the pre-arm-inertia 'vertical offset due to view pitch' in Y.

So to be clear, you only want an inertia along the X axis and just a raw displacement on the Y axis ?

**Comment by SmallJoker** [comment]
Nice, I tested this patch as well and it's a great improvement to the current (new) implementation.
In terms of return speed I agree with paramat. The Y behaviour is exactly as it should be but might look a bit strange due the large movement in this axis.

**Comment by paramat** [comment]
Actually, thinking further, when moving your view in Y the arm is moving to, so inertia in Y seems fine.
My only request is a faster return, otherwise fine.

**Comment by VanessaE** [comment]
A small amount of vertical inertia makes sense if one assumes that the player is raising their hand when they look up, i.e. to be ready to dig/punch what they see.

**Comment by kilbith** [comment]
PR updated with faster return. I could add a speed setting if people wish.

**Comment by paramat** [comment]
VanessaE yes exactly what i thought.

**Comment by paramat** [comment]
I'd prefer no return speed setting, just a well chosen value.
Tested, much better but i'd prefer a little faster still, however if others like this as it is i have no objection.

**Comment by nerzhul** [comment]
i'm okay with the current behaviour

**Review by SmallJoker — APPROVED** [review]
Works nicely.

**Comment by paramat** [comment]
51104d9cd445da21adc731fb820bbb7d82b45d64

**Pull request closed without merging**
