### PR TITLE
Allow custom values for item wear bar via meta

### PR DESCRIPTION
**Pull request by DS-Minetest**
Allow to set the wear bar of an item with item metadata.
The field "wear_bar" is used. Values range from `1`(empty) to `0`(full).

I've used this to test:
```lua
minetest.register_chatcommand("bla", {
	params = "",
	description = "",
	privs = {},
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		local item = player:get_wielded_item()
		local meta = item:get_meta()
		meta:set_string("wear_bar", param)
		player:set_wielded_item(item)
		return true, "bla"
	end,
})
```
Screenshot:
screenshot_20190403_194125

Todo: test

Fixes: #6448

### CODE REVIEW

**Comment by rubenwardy** [comment]
This feels hacky to me

**Comment by stujones11** [comment]
> This feels hacky to me. The distinction between tools and items should probably be removed instead

Ideally, I would like to see #3551 implemented, however, this is far from trivial. This simple patch would offer pretty much the same possibilities without the disruption. IMO there _should_ be a distinction between tools and items, however, some things don't quite fit into either category, like armor or guns. This would allow modders to bridge that gap if need be.

However, adding this would not prevent such refactor in future version, It just offers more flexibility. I also think that this is highly unlikely to happen anytime before version 6.0.0 (assuming anyone even takes it on) I have looked at sapier's original PR and it's absolutely massive!

**Comment by DS-Minetest** [comment]
Documentation is added.

**Comment by stujones11** [comment]
I have done some testing and this works perfectly for my armor requirements :+1: 

screenshot_20190404_220518

**Comment by DS-Minetest** [comment]
Please review, approve or merge.

**Comment by SmallJoker** [comment]
Whereas this PR works es intended, I don't think it's the best solution. As @rubenwardy mentioned, the distinction should be clear. A saner solution is to allow meshes for items and tools.

**Comment by paramat** [comment]
sfan5 thumbed-up rubenwardy's comment, so that's 3 core dev disapprovals.

**Pull request closed without merging**
