### PR TITLE
Mainmenu: Unify favorite servers with main serverlist

### PR DESCRIPTION
**Pull request by kilbith**
This PR unifies the favorite servers list with the main serverlist. Favorite servers, marked with a star, are moved on top of the list and can be removed individually.

Also cleaned some code around since it was a big mess. I split the commits to ease the reviewing.

capture d ecran de 2016-04-18 19-50-31

### CODE REVIEW

**Comment by sofar** [comment]
I haven't tried this yet but it seems a logical change and reduces UI complexity... so, good.

**Comment by nerzhul** [comment]
:+1:

**Comment by Fixer-007** [comment]
What I don't like here is "Del. Favorite" button, another way to do is to add greyed stars to all servers and just click on one to add to favourites (and it move it up to top), or click on star again to remove it from favourites.

**Comment by PilzAdam** [comment]
This idea is great.

**Comment by kilbith** [comment]
> This idea is great.

Which one ? What suggests Fixer-007 is impossible currently.

**Comment by PilzAdam** [comment]
@kilbith I was commenting on the PR; if I was replying to @Fixer-007 then I would prefix my comment with "@Fixer-007".

**Comment by Ekdohibs** [comment]
:+1:

**Comment by nerzhul** [comment]
Because this add a better user experience, should be added to 0.4.14.
Please note this approval label is ridiculous :)

**Comment by SmallJoker** [comment]
What about unlisted servers? How can they be in the favourite list?

**Comment by kilbith** [comment]
> what about unlisted servers? How can they be in the favourite list?

Oops, looks like I broke the implementation lately. Fixed.

capture d ecran de 2016-04-20 10-35-14

**Comment by Zeno-** [comment]
8cf26bb0bbc94de437342c84c7b0854feb8957e8

**Pull request closed without merging**
