### PR TITLE
[Concept] Smooth shader-based animation

### PR DESCRIPTION
**Pull request by numberZero**
As usual, just smoother. Test it on lava (note: bump mapping and parallax must be disabled for this to work).
screenshot_20171222_211604
Note: the code is entirely wrong currently and is not intended to be merged.

### CODE REVIEW

**Comment by rubenwardy** [comment]
I can imagine this being faster than regenerating the mesh constantly. What's the status of this?

**Comment by paramat** [comment]
Does this work by visually interpolating between adjacent frames?

**Comment by numberZero** [comment]
> Does this work by visually interpolating between adjacent frames?

Exactly. With a 3D texture, that would be done automatically (only with filtering enabled, though); with a 2D texture array, that would be way simpler. In this example, that is done manually from a 2D texture containing the whole strip, but that means artifacts are likely on the edges as GPU can blend across frame boundary, not to say that that’s just crappy.

> Is it possible to create a texture array / 3d texture from a sprite map?

IIRC the format OpenGL expects is identical to vertical strip we use for animation. 2D maps would have to be processed before passing to OpenGL, but that’s not a problem.

**Comment by paramat** [comment]
> Note: the code is entirely wrong currently and is not intended to be merged.

So closing.

**Comment by kilbith** [comment]
@hecktest PTAL.

**Pull request closed without merging**
