### PR TITLE
Remove `irrlicht_changes` directory

### PR DESCRIPTION
**Pull request by v-rob**
The `irrlicht_changes` directory is misleading because it only contains three things: `CGUITTFont.cpp/h` and `irrUString.h`, which aren't actually changes to Irrlicht but extensions, and `static_text.cpp/h`, which should be grouped with all the other Irrlicht GUI element changes in the `gui` directory.

Changes:
* `irrlicht_changes/CGUITTFont.cpp/h` -> `gui/guiTTFont.cpp/h`
* `irrlicht_changes/irrUString.h` -> `util/ustring.h` (These unicode string utilities actually appear really nice; it's a pity we don't use them more.  They even conform to STL naming conventions.)
* `irrlicht_changes/static_text.cpp/h` -> `gui/guiStaticText.cpp/h`
* `class irr::gui::StaticText` -> `class GUIStaticText`, like all other GUI elements.
* `CGUITTFont` and `ustring` have been moved out of the `irr` namespace since they don't actually belong there.
* A notice has been added to `guiTTFont.cpp/h` and `ustring.h` that the classes have been modified and how they have been modified, in accordance with their licenses (without this PR, they violate the license).

Little testing is needed; just make sure freetype fonts and static texts still appear to work fine (which they should).  Mostly make sure it compiles properly.

### CODE REVIEW

**Comment by TheTermos** [comment]
When I tried making a PR that would change position precision to f64, I ended up putting vector3d.h and aabbbox3d.h in irrlicht_changes because apparently type conversion override can be done only in the same file where that type's declaration is, and I haven't found a way around it.

So even if there's nothing of importance in that directory at the moment, the directory itself may be potentially useful some day.

**Comment by v-rob** [comment]
To put `irrlicht_changes` back, it's only a matter of re-adding it to CMakeLists and such files.  However, I hope that we will start using our own Irrlicht in the near future for SDL2 support, so changes would probably go there instead.  I could leave the directory in but empty, but I don't see much of a point since it's so easy to re-add.  Either way, it doesn't make a big difference to me.

**Comment by nerzhul** [comment]
to be honest, i think this PR won't be merged for 5.4, and as we seems to plan irrlicht lib fork on next release, those files are meant to be moved to the irrlicht fork directly

**Comment by v-rob** [comment]
Seems that most of these are going to be backported.  Still, it doesn't make sense to backport our GUI because it's too integrated with our own code.

**Pull request closed without merging**
