### PR TITLE
Upload higher quality image and new design

### PR DESCRIPTION
**Pull request by SaiPanneerselvam**
Made a new menu header for the game, check issue #15428 for more information.

### CODE REVIEW

**Comment by Zughy** [comment]
Hi there,
Thanks for the PR but this is not a professional logo(type). Readability is bad, kerning is arbitrary, no explanation was provided to justify your choices. I appreciate your efforts, but if you don't have any professional art experience or an art background, please leave these things to artists

**Comment by SaiPanneerselvam** [comment]
> Thanks for the PR but this is not a professional logo(type). Readability is bad, kerning is arbitrary, no explanation was provided to justify your choices. 
Will I be able to try again?
> (source: I'm a professional artist)
Then why does the logo look like it was typed in a text editor? (CHECK #15428 )

**Comment by Zughy** [comment]
> Will I be able to try again?

You can, but since you don't seem to have enough experience in the field, please don't. No one can become a professional (in whatever field) in a week or so.

> Then why does the logo look like it was typed in a text editor?

Because I didn't do it. We needed something fast for the release

> i don't think someone would look at a main menu logo and think, why is the space between the a and n very less?

This confirms my first point

**Comment by Wuzzy2** [comment]
Yeah, the proposed logo is somehow even worse. You don't even have to be an artist to recognize that. The color choice is also weird.

**Comment by SaiPanneerselvam** [comment]
Wuzzy2: I was thinking Sky and Grass colors

**Pull request closed without merging**
