### PR TITLE
Timed move

### PR DESCRIPTION
**Pull request by sapier**
minor glitches:
"end position" is not exact as it depends on dtime variance

### CODE REVIEW

**Comment by HybridDog** [comment]
Can this be used for making carts change their velocity at the corners without flying away?

**Comment by paramat** [comment]
Interesting, could you explain what this would enable?

**Comment by sapier** [comment]
Atm minetest client does already predict movement for entities already moving or accelerating. In case of lag this can result in runaway entities. Using the time limit you can make them stop after some reasonable time even if the lag exceeds this limit.

@HybridDog partial, you could use it for this too yes but it'd be quite limited as you could only have exactly one change ... and you'd have some offset as it's time based and I doubt you'll be precise enough. Yet with some limitations and care you could at least drastically improve the situations you want to fix.

**Comment by HybridDog** [comment]
>I doubt you'll be precise enough

If the minetest.after is fixed, l could make it remember how long some function took to execute and subtract that time (l used that for rocket launcher explosions https://github.com/HybridDog/nuke/blob/master/init.lua), but l think l can't detect the connection delay.

**Comment by sapier** [comment]
@HybridDog does this work on network gaming too? Imho network jitter should cause way more drift in end positions then local function runtime

**Comment by HybridDog** [comment]
idk, maybe it's possible to show a formspec to a player which immediately closes, when it arrived, and sends the fields back?

**Comment by sapier** [comment]
@HybridDog are you sure this comment is related to this pull? If it is I don't understand what you're talking about as the pull doesn't have any connections to formspecs

**Comment by HybridDog** [comment]
l just guessed a way which could allow mods to measure the connection delay to the client.

**Comment by paramat** [comment]
@sapier if you're happy with this PR feel free to add your own approval and the 'one approval' label.

**Comment by raymoo** [comment]
Is there a concrete example where you would only need one velocity change?

Also, another idea to prevent drifting is to have an optional start position for the new velocity. This would allow the path to be corrected at the time of the velocity change.

**Comment by sapier** [comment]
Well not sure what is so hard do understand, this feature is basically a lag effect reduction feature. You can avoid lag causing entities to run away and be reset by a (delayed) arriving new position message

**Comment by rubenwardy** [comment]
I feel like extending `move_to` would be a better approach

* Add a time option
* Add a tweening option, eg:
    * constant
    * speed up - constant - slow down

And maybe add keyframes for more complicated situations. (athough this is arguable)

> Well not sure what is so hard do understand, this feature is basically a lag effect reduction feature. You can avoid lag causing entities to run away and be reset by a (delayed) arriving new position message

The entities running away is due to us using *extrapolation* rather than *interpolation*. Using interpolation mostly solves the entity arriving late problem. I believe gaffer on games has a nice tutorial on this.

------

Note overall I'm neutral and would not oppose this PR

**Comment by HybridDog** [comment]
For compatibility reasons l think the second argument of setvelocity etc. should be a table with the second time and second velocity fields. Then you can also e.g. add fields for configuring synchronization and don't need to follow a strange parameter order.

**Comment by nerzhul** [comment]
SAO should really have better API than raw movements. Destinations , path finding are better thigns

**Comment by paramat** [comment]
IRC:
19:07 nerzhul     it's not a good mean to solve this, we need a better API for movements, especially for SAO and it will be added in 0.5 i think
19:08 paramat     i'm neutral
19:08 rubenwardy  I think moving to proper interpolation would be better, or keyframes. That's just seems like a bit of a weird API to me
19:09 rubenwardy  but neutral overall too

**Comment by HybridDog** [comment]
A timed move can be very useful, imagine carts which change their direction on the corner instead of driving off the track and being teleported back.

**Comment by MarkuBu** [comment]
Maybe related to https://github.com/minetest/minetest/issues/5681 ?

> In case of lag this can result in runaway entities.

In my case there is no lag. I play singleplayer on a local PC.

**Comment by nerzhul** [comment]
@HybridDog as i said, it's not a timed move, we should have a REAL protocol packet to transmit what a SAO want permitting client to calculate the move without glitching, like in every MMO in fact.

For example: TOCLIENT_ENTITY_MOVE uint64 (entityID), topos(v3f) etc

**Comment by HybridDog** [comment]
How about TOCLIENT_ENTITY_COMMAND u8 (command) <command_params>?
It can be used to support 256 commands for changing entity behaviour for the client without adding an individual packet for each prediction or whatsoever entity related command.

**Pull request closed without merging**
