### PR TITLE
Add enter_button[] to press button on enter key

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes search box creative inventory problem:

    enter_button[creative_search]
    button[2.1,3.4;0.8,0.5;creative_search;?]

Alternative fix: submit event to server and let server deal with it

### CODE REVIEW

**Comment by est31** [comment]
Related issue: #2743

**Comment by SmallJoker** [comment]
Not only the creative, but also unified_inventory and various mods with single text input fields can profit from this change. :+1:

**Comment by est31** [comment]
What about adding a property to text input fields instead, allowing to have multiple different outcomes when pressing enter at different places?

**Comment by rubenwardy** [comment]
replaced by: #4417

**Pull request closed without merging**
