### PR TITLE
Fixed spelling inconsistency

### PR DESCRIPTION
**Pull request by DerZombiiie**
coloured -> colored

### CODE REVIEW

**Review by Df458 — APPROVED** [review]
Trivial, LGTM

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/pull/12448#issuecomment-1159477111

Whereas contributions are welcome, such PRs lead nowhere.

**Comment by appgurueu** [comment]
> [#12448 (comment)](https://github.com/minetest/minetest/pull/12448#issuecomment-1159477111)
> 
> Whereas contributions are welcome, such PRs lead nowhere.

I agree that it would be beneficial to make larger PRs, fixing multiple typos at once to reduce the overhead. However I think that what really leads nowhere is the handling of such PRs: This should have been merged already. If you see a valid typo fix PR, just glance over it and hit the merge button. Takes no five seconds.

**Comment by sfan5** [comment]
I have some more changes I want to make to lua_api.txt, could incorporate these into my next PR.

...or not

**Comment by Df458** [comment]
> I have some more changes I want to make to lua_api.txt, could incorporate these into my next PR.
> 
> ...or not

Make 'em yourself then

**Comment by debagos** [comment]
@appgurueu 
> If you see a valid typo fix PR, just glance over it and hit the merge button. Takes no five seconds.

I agree, the stance to not merge them because "too trivial", is ridiculous.
I saw a few PR here already where people just fixed typos but they got rejected. I checked two of them, they never made a PR again. To project one's thoughts, I would do the same. Why would you help again, when you got rejected because "you didn't do enough".
In my opinion that is actively preventing people form getting involved, even though you actually tried to improve something, readability.
Can someone please explain rationally why it's a good idea to not merge them right away? Thanks.

**Pull request merged**
