### PR TITLE
Add custom mod library C bindings tutorial

### PR DESCRIPTION
**Pull request by jordan4ibanez**
Add compact, short information about your PR for easier understanding:

- Goal of the PR
To teach people how to do things like chat relays in minetest.
- How does the PR work?
Creates a very small tutorial.
- Does it resolve any reported issue?
I don't think so.
- Does this relate to a goal in [the roadmap](https://github.com/minetest/minetest/blob/master/doc/direction.md)?
N/A
- If not a bug fix, why is this PR needed? What usecases does it solve?
I have seen this question asked 5 (probably more) times and no one ever seems to give a minimal reproducable example.
With this PR, I hope to allow the guidance of people asking things like "How do I make a chat relay?" to one location.
This is currently only for C, but can be extended with different languages if needed.

This PR is Ready for Review.

### CODE REVIEW

**Comment by rubenwardy** [comment]
I don't think this is something for the official Minetest documentation, might be better on the forums or as a blog blog

Also, you're missing insecure env stuff

**Comment by DragonWrangler1** [comment]
Out of curiosity. Why are C libraries blocked by mod security ?

**Comment by rubenwardy** [comment]
Because they can be used to escape the mod security sandbox

**Comment by DragonWrangler1** [comment]
> Because they can be used to escape the mod security sandbox

Ah. I didn't think about that detail. Thanks for the explanation @Rubenwardy

**Pull request closed without merging**
