### PR TITLE
Implement DatabaseException for databases

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by nerzhul** [comment]
Travis seems to be unstable...

**Comment by nerzhul** [comment]
@est31 , @sfan5 @kwolekr @Zeno- please review for merge

**Comment by est31** [comment]
@nerzhul  that's #3786

**Comment by est31** [comment]
looks good

**Comment by nerzhul** [comment]
@est31 approval ? I can merge ?

**Pull request merged**
