### PR TITLE
Add chat command params info to lua_api.txt

### LINKED ISSUE #4843: Undefined and inconsistent chat command parameter description syntax
The parameter description of most chat commands (`param` field) seems to follow a rough rule, but when you look closely it is a bit inconsistent and the syntax very much looks like an ad-hoc syntax.

After going through the builtin commands, it seems that both “/” and “|” are used for alternations, and that “[text]” is both used for signifying a parameter `text`, which is optional, or the literal text “text”. This is bad as this makes the syntax ambigious. What may be worse is that other modders could come up with an even worse ad-hoc syntax, leading to inconsistency across mods.

IMO this inconsistency is unacceptable. IMO the following things need to happen:

* Formally define the syntax of the command parameter description (and try to keep it as simple and lightweight as possible)
* Make all builtin commands obey this syntax

Here is my proposed addition to `lua_api.txt`, mostly based on the existing builtin commands:

---

#### Parameter syntax guidelines

Please follow the following syntax rules for the parameter description:

* `<param>`: Placeholder for parameter `param`
* `[text]`: “text” can be omitted
* `text1 | text2 | text3`: Alternation: One of “text1”, “text2” or “text3” (scope is one word)
* `(word1 word2) | (word3 word4)` Use round brackets to group multiple words
  together for the alternation
* All other text is literal

Other guidelines and hints:

* Use `[<param>]` to signify an optional parameter `param`
* A “word” is defined as any string without whitespaces
* Program your command in a way so that its parameter syntax is simple
* Use the simplest possible command description which is still complete
* Avoid special characters in your parameter syntax

Special characters:

    <>[]()

---

If you give green light for this, I am going to write a PR with updated `lua_api.txt` and chat commands.
Please give your comments about my proposed semi-formal syntax. If you have suggestions to simplify it even further without loss of information, that would be greatly appreciated! :-)

### PR DESCRIPTION
**Pull request by Ezhh**
Fixes #4843 by adding chat commands params info to lua_api.txt.

### CODE REVIEW

**Comment by paramat** [comment]
Fine except for consistency i think line continuation for bullet points should be indented by 2 spaces:
```
* `<>` signifies a placeholder to be replaced when the command is used. For example, 
  when a player name is needed: `<name>`
* `[]` signifies param is optional and not required when the command is used. For 
  example, if you require param1 but param2 is optional: `<param1> [<param2>]`
* `|` signifies exclusive or. The command requires one param from the options
  provided. For example: `<param1> | <param2>`
* `()` signifies grouping. For example, when param1 and param2 are both required,
  or only param3 is required: `(<param1> <param2>) | <param3>`
```

**Comment by Ezhh** [comment]
@paramat I might be missing something, but use of two spaces doesn't appear consistent. 

Go right to the top of lua_api.txt and check bullets from line 3. The first level bullets are as I have them. From line 32 you'll see bullets preceding code boxes the same way I've done them as well.

It's quite possible my previous PRs removed anything with 2 spaces, since the majority of the document was using 4 spaces to a tab.

**Comment by paramat** [comment]
Yes its not consistent, i should have realised consistency is non-existent in this document. But i still prefer it for clarity :+1:

**Comment by Ezhh** [comment]
I might force myself to go through the bullet indentation next after this is merged. Hadn't realised how bad it is before. No one will probably notice such a change but... now it's going to annoy me if it doesn't get fixed. :)

**Comment by paramat** [comment]
Oh my example may have confused due to how the whole text is indented, i meant:
```
+Note that in params, use of symbols is as follows:
+
+* `<>` signifies a placeholder to be replaced when the command is used. For example, 
+  when a player name is needed: `<name>`
+* `[]` signifies param is optional and not required when the command is used. For 
+  example, if you require param1 but param2 is optional: `<param1> [<param2>]`
+* `|` signifies exclusive or. The command requires one param from the options
+  provided. For example: `<param1> | <param2>`
+* `()` signifies grouping. For example, when param1 and param2 are both required,
+  or only param3 is required: `(<param1> <param2>) | <param3>`
```

**Comment by Ezhh** [comment]
Some parts have the two spaces in normal text where there is no other indentation, so I think this is fine. It's just a case of deciding what's wanted and then trying to get the rest of the document consistent with that as well. I'll be happy to do this in a new  PR, and just ask that one will be merged quickly since it will mean going through the full file.

**Comment by paramat** [comment]
We should decide first before it's done so that it can be merged immediately before conflicts.

**Comment by Ezhh** [comment]
I've said I'm happy with the way it's done here (2 spaces). But you're the dev, so let me know what you want.

**Comment by paramat** [comment]
Personally, for a bullet point line continuation i prefer an indent such that the following lines are aligned with the first line instead of aligned with the asterisk or up-arrow, as my request here.

**Comment by Ezhh** [comment]
Which is what two spaces does?

**Comment by paramat** [comment]
Sorry, i'm tired. I was stating my general preference for lua_api.txt. This PR is fine and will be merged.
Of course, i forgot that the rest will have to be consistent with this PR, so, i'll decide now that my request is how it should be as it seems obviously clearer.
If no objections to that decision we'll merge this today sometime.

**Comment by Ezhh** [comment]
This has two approvals and is extremely trival. Is there any reason it needs to wait? I ask this because I'd be able to work on the next PR today, but this obviously needs to be merged first. If you only do this this evening, I probably won't have time for another week.

**Comment by paramat** [comment]
Ok, i'll wait a few minutes for responses then merge.

**Comment by srifqi** [comment]
I agree with paramat about line indentation. This may be merged first and then there should be another PR to do line indentation fix.

**Comment by paramat** [comment]
8349a3db1072e3a805482e91c442f9a158ea60b1

**Comment by paramat** [comment]
#6912 merged.

**Pull request closed without merging**
