### PR TITLE
Fix instant dig bug #5728

### LINKED ISSUE #5728: Block instadig after tool switch
How to: place obsidian, start mining it with diamond shovel, while mining it switch to diamond pickaxe, obsidian will be instamined.

Bug was reported by vita from Hometown server and confirmed by me on engine de028fc

Regression in 7f4cdbc "Fix click-digging torches (#5652)"

Debug output thanks to @nerzhul (details: http://irc.minetest.net/minetest-dev/2017-05-08#i_4911760)

```
2017-05-08 18:57:53: ERROR[Main]: Hey i'm there here is the value 2 - trying diam pickaxe and stopped half-way
2017-05-08 18:57:54: ERROR[Main]: Hey i'm there here is the value 0 - trying diam shovel and switching to diam pickaxe during mine, instamine vvv
2017-05-08 18:57:57: ACTION[Server]: singleplayer digs default:obsidian at (10,45,-8)
2017-05-08 18:57:57: ERROR[Main]: Hey i'm there
```

Another try with cleaner output:
```
2017-05-08 18:59:55: ACTION[Server]: singleplayer places node default:obsidian at (10,45,-8)
2017-05-08 18:59:58: ERROR[Main]: Hey i'm there here is the value 0
2017-05-08 18:59:59: ACTION[Server]: singleplayer digs default:obsidian at (10,45,-8)
2017-05-08 18:59:59: ERROR[Main]: Hey i'm there
```

Demo of the bug:
instadig

### PR DESCRIPTION
**Pull request by lisacvuk**
Fixed issue #5728, I hope I did it the right way.

### CODE REVIEW

**Comment by pilino1234** [comment]
Use 1 tab (instead of 4 spaces) for indent to fix the code style

**Comment by lisacvuk** [comment]
https://www.youtube.com/watch?v=e0x5sPoUe0I&feature=youtu.be

**Comment by lisacvuk** [comment]
@pilino1234 I did use tabs, but apparently my editor changed it to spaces :( I'll fix it

**Comment by Fixer-007** [comment]
Please rename it to something better.

**Comment by pilino1234** [comment]
I'd say this is [trivial], [bugfix], possibly even [high priority], can this be merged soon please?

**Comment by nerzhul** [comment]
it will be merged when 2 coredev will test it. I will do it, ti's a sensible feature, i hope we don't trigger cheating (after merging this) just 1 month before release

**Comment by pilino1234** [comment]
> i hope we don't trigger cheating 
you're fixing cheating by merging this though 😉

**Comment by lisacvuk** [comment]
@pilino1234 Not everyone knows about this bug. Merging the fix would alert them

**Comment by pilino1234** [comment]
Lolwut. So if we don't report bugs they don't exist either??

If there's a bug in the game, it should be fixed asap, especially if it affects gameplay like this one does. Merging this isn't gonna alert anybody any more than the discussion of it already has, so there's that.

**Comment by nerzhul** [comment]
Sorry but you don't fix it: https://youtu.be/G0u35fDmoow

**Comment by Fixer-007** [comment]
Funny, you fixed diam pickaxe-shovel instamining and introduced instamining for wooden shovel or pickaxe, it simply instamines without any preparations. Can confirm.

**Comment by lisacvuk** [comment]
https://youtu.be/OeAqRJc4WYk

**Comment by paramat** [comment]
So does this PR fix the bug or not?

**Pull request closed without merging**
