### PR TITLE
lua API for deregistering single biomes

### PR DESCRIPTION
**Pull request by zeuner**
Instead of implementing a mgv6-like "nojungles" (https://github.com/minetest/minetest_game/pull/1661) setting, deregistering the unwanted biomes from a mod seems like the right approach. However, there doesn't seem to be an API function that allows doing so without having to bother with biome registration internals (having to re-register all the biomes not meant to be removed).

### CODE REVIEW

**Comment by paramat** [comment]
Seems reasonable.

**Comment by MarkuBu** [comment]
But if you deregister. Biome you get a lot of error messages. All biome decorations fail to register to a non existing biome 

Or am I wrong?

**Comment by paramat** [comment]
I recently downgraded the messages about decorations not finding biomes from 'error' to 'info', to make optional biomes much easier to work with, see #5386

**Comment by zeuner** [comment]
@MarkuBu: If so, then minetest.clear_registered_biomes will lead to even more problems. Anyway, we cannot expect all mods to be compatible with each other.

**Comment by zeuner** [comment]
Regarding implementation: The local make_wrap_deregistration helper function should be suitable to define deregistration functions for all tables defined through make_registration_wrap if necessary.

**Comment by paramat** [comment]
I'm neutral.

**Comment by zeuner** [comment]
It's appreciated.

original message follows:

**Comment by zeuner** [comment]
Good to hear. This should reduce mod complexity for smaller
biome-related customizations.

original message follows:

**Comment by zeuner** [comment]
Can you elaborate on the contra side?

original message follows:

**Comment by paramat** [comment]
Well i'm not strongly opposed, it's just that clearing and re-registering all the biomes is the recommended and standard method if you want to change something, it's just a bit of copy-paste into a mod then remove whatever you want, quick and easy, done in a minute.

However people must be really lazy because they complain so much about such a simple task, they complain about 'having to write a mod to do something' when very many aspects of Minetest are only possible by adding a simple mod, this is completely reasonable and how MT works.

So this feature is unnecessary code bloat for lazy people. Thinking more on it i do disapprove, but i couldn't stop it anyway.

It seems to me that if you remove a single biome you are likely to want to change some other things as well, so the user will often need to use the re-register method anyway.

**Comment by zeuner** [comment]
I do agree with avoiding engine bloat. But I think that providing
unregister functions does more than avoiding having to write mod
code. Clearing and unregistering requires more assumptions on how the
engine works than calling an unregister function, so it will more
easily break when something is changed.

In order to have a really lean and mean core, it would be great to
completely move things like the biome infrastructure to mods.

original message follows:

**Comment by paramat** [comment]
The Biome API has to be in engine C++ for speed.

**Comment by zeuner** [comment]
I'm not saying it would be feasible right now. But AFAICT, it has
to be in C++ due to specialized lookups that have to work
quickly. With a more generic engine-supported database, it may be
possible to implement fast biomes and other niceties from mods. Until
then, I think it makes sense to allow basic manipulations with minimal
exposure of internals.

original message follows:

**Comment by paramat** [comment]
How could biome infrastructure be completely in Lua mods? We don't want to add C++ to mods and probably never will.

**Comment by zeuner** [comment]
No, C++ mods are not what I envisioned (or consider as beneficial).

But I think that the biome infrastructure could be abstracted, moving
parts of it to Lua.

original message follows:

**Pull request merged**
