### PR TITLE
Fix pointers casting

### PR DESCRIPTION
**Pull request by Selat**
C-style pointer casting doesn't perform runtime check so it's not safe.

### CODE REVIEW

**Comment by nerzhul** [comment]
Please rebase and squash your commits, else i'll close the PR on next saturday (21 feb)

**Comment by Selat** [comment]
Rebased.

**Comment by nerzhul** [comment]
build doesn't work

**Comment by Selat** [comment]
It looks like I've missed a curly bracket while rebasing this pull request. Everything should work now.

**Comment by Zeno-** [comment]
I don't think this is a good idea in a game where performance is criticial

**Comment by nerzhul** [comment]
i agree with @Zeno- , managing it ourself is the most important part

**Pull request closed without merging**
