### PR TITLE
Correct gravity calculation

### PR DESCRIPTION
**Pull request by EliasFleckenstein03**
## Problem
The Minetest engine calculates gravity different from the real world. After the new speed is calculated by adding gravity * dtime to it, it is applied to position by adding speed * dtime. However, this is wrong, since the speed is assumed to be the value that it actually just reached at the end of the step over the entire step. Yes, this has a practical impact.

Currently the new position is wrongly calculated by:
image
This approach would be correct if velocity was constant. However, this is an accelerated movement, so
image

Generally correct is:
image
Since the velocity is linearly increasing (gravity is constant), this resolves to:
image

## Solution
This PR adds the `new_acceleration` field to physics_override. This field is opt-in, so that it does not break existing games/mods. If the field is enabled, you will notice that you can jump higher than before unless you also change `movement_jump_speed` or `movement_gravity`. This is to be expected, since gravity has been calculated incorrectly before. Projects that want to use the new formula have to adjust these settings.

If you want the player to be able to jump 1.25 nodes high at a gravity of 9.81, set the jump speed to 4.95 (approximately). The formula is
image
This formula works IRL. Do the math or just try it out if you don't believe me.

## To do

Currently, the pull request only fixes the physics calculation for players.

- [ ] Fix server-side luaentity acceleration code in case it's wrong like the client side player acceleration code. Find a way to make these correct luaentity physics opt-in. Also apply this to the client side prediction of the server-side luaentitiy accelerations, if there is any.
- [ ] Find a fix for the following scenario: A player with <5.5.0-dev client joins >=5.5.0 server that has new_gravity enabled and a lower jump speed configured, can jump lower than other players
- [ ] Adjust fall damage since the speed at that the player collides with the ground will be lower than before

## How to test
```lua
minetest.register_on_joinplayer(function(player)
	player:set_physics_override({new_acceleration = true})
end)
```

Btw: I used this http://www.sciweavers.org/free-online-latex-equation-editor tool for the equation images, since GitHub markdown does not support inline latex or any other way to embed equations.

### CODE REVIEW

**Comment by EliasFleckenstein03** [comment]
Note: this has partly been discussed in #9520

**Comment by SmallJoker** [comment]
What's the error caused by this miscalculation? For example: how much does the maximal jump height change? This calculation is done many times per client step, hence the old speed is almost identical to the new speed. This should only cause minor differences.

**Comment by appgurueu** [comment]
I believe this should be extended to entities as well.

**Comment by EliasFleckenstein03** [comment]
It does have a significant impact, since the error adds up. The way this affects me is that if you use e.g. a gravity of 32 (Minecraft value) with a calculated jump speed of 8.94 to reach 1.25 blocks, it's just entirely wrong and you can barely jump at all.

If don't have a formula for the old jump speed based on gravity and jump height, but the current default jump speed is 6.5, and the new one would be around 4.95. This is definitely significant.

**Comment by EliasFleckenstein03** [comment]
Crock: with new_gravity and old movement_speed_jump, I can jump over 2 blocks high.

**Comment by EliasFleckenstein03** [comment]
Btw, with new_gravity, a gravity of 9.81 and a jump speed of 4.95 the movement feels very unnatural - this is because in real life you'd normally not jump 1.25 meters high.

A way to fix this is by using a high gravity value (Minecraft does this: 32). Or just not using the new_gravity code.

**Comment by EliasFleckenstein03** [comment]
To solve the issue with fall damage, it might be an elegant approach to have a fall_damage_multiplier in physics_override that determines the speed at which the player is damaged. As a side effect, this would also allow modders to just disable fall damage entirely - in a neat and backwards compatible way.

**Comment by rubenwardy** [comment]
Haven't looked into this PR, but the standard approach to this is to use suvat:

```cpp
// s = ut + 1/2 at^2
position += velocity * time + 0.5f * acceleration * time * time;

// v = u + at
velocity += acceleration * time;
```

**Comment by EliasFleckenstein03** [comment]
That approach does the same as mine, except in other words basically.

**Comment by SmallJoker** [comment]
I might be a bit late with this question, but why exactly do we need this to be change? Whereas the physics will be (hopefully) accurate, this change does lead to yet another player object property which will be an everlasting piece of legacy/compatibility code.

**Comment by Wuzzy2** [comment]
> To solve the issue with fall damage, it might be an elegant approach to have a fall_damage_multiplier in physics_override that determines the speed at which the player is damaged. As a side effect, this would also allow modders to just disable fall damage entirely - in a neat and backwards compatible way.
Should I add such a field?

This already exists, but as a player armor group (`fall_damage_add_percent`). :P

**Comment by appgurueu** [comment]
> I might be a bit late with this question, but why exactly do we need this to be change[d]?

See https://github.com/minetest/minetest/issues/12340

**Comment by sfan5** [comment]
relevant:
```
20:34 <+MTDiscord> <Warr1024> If it could be switchable, like the way there's that "new player movement" option, then I'd probably just enable it for my game.
20:34 <appguru> Not just players, all entities
20:34 <+MTDiscord> <Warr1024> I mean I'm thinking like per-world.
20:35 <+MTDiscord> <Warr1024> you enable it, it's replicated to the client, and it makes every thing in the world operate with the corrected math.  Not everything needs to be all that fine-grained.
20:35 <+MTDiscord> <Warr1024> People can start migrating to it for an eventual 6.0 cutover, and stuff that relies on the old behavior can keep compat.
20:36 <+MTDiscord> <Warr1024> then for 6.0 I guess you just flip around the default and deprecate/remove the old jank math.
```

**Pull request closed without merging**
