### PR TITLE
Update Spanish language

### PR DESCRIPTION
**Pull request by ngosang**
I am a native speaker. I have corrected all the mistakes I've found.

### CODE REVIEW

**Comment by kaeza** [comment]
Some of the capitalisation changes are wrong IMHO, as the old texts were more consistent with the english texts (e.g. "Menú **P**rincipal" -> "Menú **p**rincipal"; the original text is "Main Menu", not "Main menu").

You should also change the `Last-Translator` field.

Everything else, :+1:.

**Comment by ngosang** [comment]
The capitalization changes are intended. As you can see in the old translation screenshots the use of capital letters is arbitrary.
http://imgur.com/Pb7tHT7
http://imgur.com/TtzRNsl
http://imgur.com/HF1M3FC
I think the right thing it's to change them for uniformity.
http://imgur.com/KXwCoDX
Furthermore, there are different rules in Spanish about capital letters. They are only justified at the start of the sentences and for own names.
Btw, I'm going to change the source code to complete the traslations but it will take time. https://forum.minetest.net/viewtopic.php?f=6&t=11043
Regards, ngosang.

**Comment by ngosang** [comment]
I added translations from the latest dev. version.

**Comment by ngosang** [comment]
I think it's complete now. I compiled the latest version and I looked all texts of the GUI.
@kaeza You can recheck the changes. I explained above why I have not respected the capital letters but if there is a majority against I can change it back.

**Comment by kaeza** [comment]
@ngosang Fair enough. TBH, I don't really care too much about caps, just being a bit picky :)

:+1:

**Comment by Zeno-** [comment]
commit d4786d8d5deae316b67159e63aa36821199878af

**Pull request closed without merging**
