### PR TITLE
Fix Android build

### PR DESCRIPTION
**Pull request by stellio**
Add HyperText.cpp to Android.mk LOCAL_SRC_FILES list

## To do
 
Ready for Review.

### CODE REVIEW

**Comment by MoNTE48** [comment]
More conflicts. I have already done PR for this!!! 😭

**Comment by paramat** [comment]
So probably best to not merge this PR.

**Comment by nerzhul** [comment]
@MoNTE48 it's why i would like to have tiny PR to fix things one by one, also permitting to do a better bisect. I will  try to take more time on your PR to find another thing we can merge (and yeah you may need to rebase again, but we reduce the merge time for each feature)

**Comment by MoNTE48** [comment]
My PR is ready 6 or more days ago. I want to split it. Please merge iconv PR first

**Comment by nerzhul** [comment]
@MoNTE48 can you link me the exact iconv pr i will take a look, thanks

**Comment by MoNTE48** [comment]
is it so hard for you to see the list of PRs?
https://github.com/minetest/minetest/pull/9117

**Pull request closed without merging**
