### PR TITLE
Append "-debug" to version string when compiled with "-DCMAKE_BUILD_TYPE=Debug"

### PR DESCRIPTION
**Pull request by bigfoot547**

### CODE REVIEW

**Comment by paramat** [comment]
Seems useful, i once got confused by not knowing if i was in a debug build.

**Comment by bigfoot547** [comment]
Thank you @paramat

**Comment by nerzhul** [comment]
@paramat can i count your opinion as a +1 and merge it ?

**Comment by paramat** [comment]
I approve concept but am not certain about the code, so i cannot give an official +1.

**Comment by paramat** [comment]
But, since it is simple, if you are sure the code is correct, go ahead and call it 'trivial'.

**Pull request merged**
