### PR TITLE
Collision detection tweak #2

### PR DESCRIPTION
**Pull request by TheTermos**
This is a rerun of #9327 which showed promising results, except for issue #9351 which was player clipping through terrain in case of perfect diagonal edge collisions, known as 'the pyramid glitch' (described therein) 

The goal is to find the optimal value for the d uncertainty radius, such as minimizing glitches caused by it (#6886, #9143, #9305) while not introducing new ones (#9351)

The pyramid glitch can occur with any d value, including the old one, given velocity and/or dtime values are great enough. 
The criteria i used: I tried to reproduce the glitch with player on fast move, the safe value I arrived at was 0.3f.

## To do

This PR is Ready for Review.

## How to test

build a structure as shown here https://github.com/minetest/minetest/issues/9351#issuecomment-581193960 move around it and try to get player to clip into a node.

### CODE REVIEW

**Comment by style-nine** [comment]
I tried this out, and it seems to fix the problem on my system.

**Comment by paramat** [comment]
Seems a good idea to merge this, as it is an improvement and it will get more testing that way. However i think it may be best to revert to the original value for release 5.2.0, not sure, needs consideration.

**Comment by TheTermos** [comment]
> However i think it may be best to revert to the original value for release 5.2.0, not sure, needs consideration.

Either way is fine, even if this turns out to make things better it can't solve all issues. Ultimately the d has to go and the current solution is beyond repair imo.

I already developed a new d-less version of AxisAllignedCollision() which seems airtight and handles face, edge and corner collisions without a hitch, I'll try to update #9343 with it till the end of the week. Should be faster too.

**Comment by sorcerykid** [comment]
I'm inclined to agree with @paramat. As much as I look forward to @TheTermos's collision detection fixes, I think it's the safest bet to revert to the original values for 5.2, rather than rushing with a fix that has the potential to introduce more unanticipated bugs. At least by the following release we should have a rock-solid algorithm in place once and for all :)

**Comment by paramat** [comment]
Tested, i can no longer reproduce the glitches i could before.
:+1: as it is obviously better than current code, and merging will being more testing so that we can judge whether to revert later.

**Comment by TheTermos** [comment]
>  as it is obviously better than current code, and merging will allow more testing so that we can judge whether to revert later.

Just updated #9343 with the solution I think might be the thing.

I understand the risks of releasing insufficiently tested code, but since we're about test driving, please consider taking that one for the ride instead.

Anyway, it's not like there's a deadline to be met which our families' livelihood depends on, and just maybe it turns out good enough for a slight delay to be worthwhile. Having working collision detection as of 5.2 would be something.

**Comment by paramat** [comment]
It is far too risky to merge a collision rewrite like #9343 shortly before a release, even this PR would be a risk. We intend to release 5.2.0 in a few weeks.

**Comment by TheTermos** [comment]
I could disagree, but I think I just stumbled upon a can of worms - sneak glitch/old sneak code.
See, it's not just about checking one more node above sneak node, it entirely relies on collision being broken. Decent collision detection and sneak glitch option are mutually exclusive.
I wish we're done with 5.2 the soonest.

**Comment by paramat** [comment]
Ha ... sneak jump/glitch stuff is a nightmare indeed =)

**Comment by TheTermos** [comment]
> Maybe we could have both old and new collision code, and use the newer when new movement code is selected? Those who like sneak jump/glitch usually use the old movement code, and i personally believe we should remove sneak jump/glitch simulation from the new movement code, because including it is again causing problems and restrictions for the future. But, the other core devs disagree.

This could work.
I had to rewrite updateSneakNode() because it was guilty of setting player position inside nodes, but old_move() doesn't call it, so making sneak glitch work only with old move seems the second best option, just after ditching the glitch.

**Pull request merged**
