### PR TITLE
ContentDB: Add Update All and download queuing

### LINKED ISSUE #7369: Browse online content: List only installed, update all [FR]
##### Issue type

 - Feature request
 
Adding simple checkbox/whatever to:
+ Show list of installed addons
+ Update all of them

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #7369 and #10212

Screenshot_2020-06-05_15-36-34
Screenshot_2020-06-05_15-36-21
Screenshot_2020-06-05_15-36-41
Screenshot_2020-06-05_15-36-46
Screenshot_2020-06-05_15-28-10

### CODE REVIEW

**Comment by ClobberXD** [comment]
The `x downloading, y queued` text seems long enough to be clipped in low DPI displays. Maybe a line-break would be better here?

**Comment by rubenwardy** [comment]
image

**Comment by ClobberXD** [comment]
The line-break makes it look much better, thanks. Tested with 4 pending updates. Clicking "Update all [4]" immediately began to download 3 packages while the 4th one was queued. And packages were updated correctly. PR werks. :+1:

There's one thing though - the status text looks just like a normal label. Would be a good idea to highlight the text somehow? Borders? Or maybe surrounding the text with a box that is coloured according to the status?

**Comment by LoneWolfHT** [comment]
Was going to test this but then had a thought:
Will this download over my git-cloned mods that have the release number set to 0?

**Comment by rubenwardy** [comment]
Only if they have a release and author set, and a matching ContentDB package. You should **not** be setting release in mods not downloaded from ContentDB

**Comment by LoneWolfHT** [comment]
huh, I vaguely remember someone telling me I should do that. I'll fix that then

**Comment by paramat** [comment]
This feature will close #10212

**Pull request merged**
