### PR TITLE
Android: Fix asset upgrade crash by removing LICENSE.txt directory

### LINKED ISSUE #10049: Android asset upgrade fails
When updating from 5.0.1 to 5.3.0, the app will crash due to a LICENSE.txt folder

The contents are as follows:

```
minetest/
└──  LICENSE.txt/
    └── lgpl-2.1.txt
```

##### Steps to reproduce
Install the app from the play store, then install the release candidate

##### Solutions

1. Don't include LICENSE.txt, as it's not especially needed anyway
2. Delete everything that shouldn't be saved before updating, to remove old files
3. ...

### PR DESCRIPTION
**Pull request by rubenwardy**
The LGPL license technically requires it to be distributed to end users (although, this isn't always done in practice)

Fixes #10049

cc/ @MoNTE48 

### Alternatives

sfan5 preferred this solution.

Alternatives:

* Keep file name as lgpl-2.1.txt
* don't include it at all (monte prefers this)

### CODE REVIEW

**Comment by MoNTE48** [comment]
We almost finished the more elegant solution, which would make the unpacking almost instant and the update very reliable, but probably it is no longer required?

**Comment by rubenwardy** [comment]
> We almost finished the more elegant solution, which would make the unpacking almost instant and the update very reliable, but probably it is no longer required?

Who is we and what are you referring to?

**Comment by MoNTE48** [comment]
> Who is we and what are you referring to?
MultiCraft devs

**Comment by jastevenson303** [comment]
>The LGPL license technically requires it to be distributed to end users

Fulfilling this requirement is as easy as a self-addressed stamped envelope.  It doesn't need to accompany the source distribution any more than you need to explicitly note your artistic work is copyrighted.

All that actually matters is that you provide the license text if someone asks you for it.

**Comment by rubenwardy** [comment]
Well, I'd prefer to er on the side of less code, which would be one of the alternatives

**Pull request closed without merging**
