### PR TITLE
Increase defaults for viewing_range, active_object_range and related settings

### PR DESCRIPTION
**Pull request by lhofhansl**
As discussed in #10571

Note that I did not touch the Android defaults. Should be increase those too? (They are woefully low.)

### CODE REVIEW

**Comment by red-001** [comment]
What are the android defaults right now?

**Comment by lhofhansl** [comment]
Here are the relevant ones:
```
	settings->setDefault("viewing_range", "50");
	settings->setDefault("max_block_generate_distance", "5");
	settings->setDefault("client_mapblock_limit", "1000");
```

And some more interesting ones:
```
	settings->setDefault("active_block_range", "2");
	settings->setDefault("max_objects_per_block", "20");
	settings->setDefault("server_map_save_interval", "15");
	settings->setDefault("max_simultaneous_block_sends_per_client", "10");
	settings->setDefault("emergequeue_limit_diskonly", "16");
	settings->setDefault("emergequeue_limit_generate", "16");
```

**Comment by paramat** [comment]
The new values seem reasonable.
Block Cache of 7500 is a moderate and reasonable increase, and is the volume of a sphere of radius 194 nodes, enough for the new default view range of 190.
I would like to see some consideration by other core devs before a merge, but will approve anyway :+1: 

Note for future: minetest.conf.example is regularly auto-generated from settingtypes.txt, so is wasted work including it in PRs (it should perhaps be 'gitignored').

**Review by nerzhul — APPROVED** [review]

**Comment by lhofhansl** [comment]
I'll remove minetest.conf.example before I merge. What's the tool called to generate it?

**Comment by paramat** [comment]
I removed my approval for this for 2 reasons:

1. I made a mistake, i did not test this. If i had i would have noticed the bad stutter discussed in #10683 . Although the changes of this PR may not be the cause or the primary cause of that stutter, i would not have agreed to setting changes that would make the stutter worse.

2. See https://github.com/minetest/minetest/issues/10571#issuecomment-739328469

**Comment by lhofhansl** [comment]
We can roll the server side changes. But I want to state my express disagreement with this.

**Pull request merged**
