### PR TITLE
Debundle Minetest Game

### LINKED ISSUE #9509: Ship MTEngine with no games, choose and install from the Content Database (after main menu improvements)
I searched and could not find an issue for this, but the idea is mentioned in a few different places, and in one place by rubenwardy.

I would really like focus to be removed from MTGame, and for MTEngine to be considered a neutral 'game engine' for which many games are available, with MTGame being just another game (although a very significant and much used one due to how much uses it as a modding base).

Whatever games are bundled with MTEngine, they are more likely to be used instead of downloading from the Content Database, and will therefore unfortunately tend to influence the perception of the MTEngine, which then makes it a case of whether the user likes the (probably small number of) games that have been bundled. Chance of disappointment is therefore high.

By being forced to download a game from the Content Database, there is a higher chance the user will find something they like.
This also gives a good impression due to the variety of games avaialble for MTEngine.

Shipping with no games will probably have to wait until after changes to main menu, to help guide users to the Content Database to download a game.
The Content Database should probably have a list of 'featured games' (games known to be high quality) which will include MTGame (but not top of the list). MTGame should have an improved description to manage expectations of it.

Shipping with no games will make releases smaller and releasing simpler, especially compared to the previous idea of bundling a variety of games with MTEngine.

### PR DESCRIPTION
**Pull request by rollerozxa**
Closes #9509.

This PR debundles Minetest Game from the engine. The necessary preparations for improving UX with no game installed has already been resolved with #13550.

Requires:

* #13850
* #13906 
* #13807

## To do
This PR is Ready for Review.

## How to test
See that there are no mentions of it left in READMEs or buildscripts or such.

### CODE REVIEW

**Comment by sfan5** [comment]
Note that merging this will make #13800 a blocker, is there a prospect of anyone working on it soon?

**Comment by rubenwardy** [comment]
I suggest making those two things prerequisites of this PR

**Review by grorp — COMMENTED** [review]
I think `games` should be removed from here:

https://github.com/minetest/minetest/blob/690506b7586f1bdd264b50a8cf8188256baad751/android/app/src/main/java/net/minetest/minetest/Utils.java#L38-L45

**Comment by rubenwardy** [comment]
Remaining things before debundling:

1. Android needs to either uninstall MTG or migrate to the CDB
2. Handle the case where MTG is uninstalled with MTG worlds. This is #13800
3. Handle the case where an old version remains installed. This would be the case on Windows if the user updates by extracting the zip over an existing install. Update detection only works when installed from CDB, so users won't receive update notifications in this case

**Comment by rollerozxa** [comment]
> I think `games` should be removed from here:

yep, otherwise it will repeatedly extract the zip on android if you don't have any games installed...

**Comment by sfan5** [comment]
> 3\. This would be the case on Windows if the user updates by extracting the zip over an existing install.

Hopefully users don't actually do this because there's a bunch of things that could break in more or less subtle ways if done.

**Comment by rollerozxa** [comment]
> > 3. This would be the case on Windows if the user updates by extracting the zip over an existing install.
> 
> Hopefully users don't actually do this because there's a bunch of things that could break in more or less subtle ways if done.

This was how I would update Minetest on Windows, by extracting `bin` and `builtin` over my existing Minetest install. That's what happens when user and share data are all mixed up in a mess like the Windows builds currently are.

**Comment by rollerozxa** [comment]
For cases where #13800 wouldn't be able to detect updating from an existing install containing MTG worlds, I feel like it should be important to inform users via Minetest community channels that MTG will be debundled in 5.8.0, and that if they want to continue playing with MTG it can be reinstalled from the content browser. ([like this forum thread I made about it](https://forum.minetest.net/viewtopic.php?f=3&t=29867))

**Comment by SmallJoker** [comment]
Removed the label because #13799 is not too important and by the looks of it, the other dependencies were resolved too.

Relevant discussion: https://irc.minetest.net/minetest-dev/2023-10-15#i_6122535

**Comment by rubenwardy** [comment]
Still need to uninstall mtg when the Android app updates

**Comment by grorp** [comment]
> Still need to uninstall mtg when the Android app updates

Since #13906 also works on Android, merging that PR would change this to-do from a must-have to a nice-to-have.

**Review by grorp — COMMENTED** [review]
Found a leftover mention of MTG:

https://github.com/minetest/minetest/blob/09dd49f81f702f5ab0032ffe4d1f2211939ff6d7/doc/lua_api.md?plain=1#L1380

I think we can just remove that line altogether.

**Review by rubenwardy — APPROVED** [review]
Works

**Comment by rubenwardy** [comment]
> Found a leftover mention of MTG:
> 
> https://github.com/minetest/minetest/blob/09dd49f81f702f5ab0032ffe4d1f2211939ff6d7/doc/lua_api.md?plain=1#L1380
> 
> I think we can just remove that line altogether.

I noticed this but felt like it didn't matter either way

**Comment by srifqi** [comment]
If we want to truly remove any references to Minetest Game,

https://github.com/minetest/minetest/blob/09dd49f81f702f5ab0032ffe4d1f2211939ff6d7/doc/lua_api.md?plain=1#L62

https://github.com/minetest/minetest/blob/09dd49f81f702f5ab0032ffe4d1f2211939ff6d7/doc/texture_packs.md?plain=1#L43-L45

https://github.com/minetest/minetest/blob/09dd49f81f702f5ab0032ffe4d1f2211939ff6d7/games/devtest/mods/initial_message/init.lua#L6

**Comment by rollerozxa** [comment]
Referencing Minetest Game for examples in documentation sounds okay to me, but that devtest initial message could use being changed. Or even removed, since devtest isn't bundled with builds of the engine anymore and there are already warnings when creating a devtest world pointing you to the content browser if you're running in place inside of the source tree.

**Review by srifqi — APPROVED** [review]
Except other references about Minetest Game (discussed before), this PR looks good to me.

PS The unpacking/unzipping in the Android version is faster, too, without MTG.

**Comment by rollerozxa** [comment]
> However, I think the Devtest chat message still has value, as an additonal reminder. Removing the second sentence would be enough IMO.

Alright, I have done that, should be enough for now.

**Review by grorp — APPROVED** [review]
Let's do this! :)

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
