### PR TITLE
Minimap: Add NESW to round overlay

### PR DESCRIPTION
**Pull request by RealBadAngel**
screenshot_20160218_130638

### CODE REVIEW

**Comment by Dragonop** [comment]
Nice :+1:
Why not adding something that points where the player is?

**Comment by RealBadAngel** [comment]
@Dragonop always in the middle. Adding a marker there would cover area there, so you wont see on minimap what you are actually building around you

**Comment by Dragonop** [comment]
@RealBadAngel And what about a square, not colored, a really thin line, just the borders? At least that way there is a reference on where you are in the minimap.

**Comment by paramat** [comment]
I prefer the minimap without NESW, cleaner looking, there's not much need for this and we have f5 and cloud drift already.

**Comment by Fixer-007** [comment]
I like minimap with NESW :)

**Comment by paramat** [comment]
I think the font can be improved, it looks a bit hi-res and out of place alongside MT fonts.

**Comment by rubenwardy** [comment]
I think that just an arrow pointing to N/z+ would be okay. Also localised and doesn't imply a magnetic north pole as such

**Comment by RealBadAngel** [comment]
screenshot_20160219_163036

**Comment by PilzAdam** [comment]
@RealBadAngel at least for German "E" (east) has to be localized to "O" (Osten).

**Comment by RealBadAngel** [comment]
thats not text, either that or nothing. arrows doesnt give any useful info.

**Comment by Fixer-007** [comment]
Looks good

**Comment by paramat** [comment]
I like rubenwardy's suggestion, i'm not keen on NESW.

**Comment by 0-afflatus** [comment]
I think Rubenwardy's suggestion is a good compromise.

**Comment by rubenwardy** [comment]
I don't mind that much

**Comment by NathanSalapat** [comment]
XYZ would seem to be the better way to go, as in the cubic world we don't have poles.

**Comment by rubenwardy** [comment]
> XYZ would seem to be the better way to go, as in the cubic world we don't have poles.

Is however less user friendly - this is why I would prefer a simple arrow.

**Comment by RealBadAngel** [comment]
@rubenwardy "follow the arrow direction" or go "opposite the arrow, then to the left of the arrow, no no that left" ;)

**Comment by kilbith** [comment]
The "N" can't be localized btw, it stands for "Norris", the name of Chuck.

**Comment by nerzhul** [comment]
NSEW is better for players than XYZ which doesn't make sense. It's a minimap, and then a map. A map use NSEW.

**Comment by paramat** [comment]
This is not school :)

**Comment by Dragonop** [comment]
It's not my point: why would you use a simplified version when you can use the actual thing.

**Comment by 0-afflatus** [comment]
If this is do-able with a texture, we don't need to define it in the engine. Then we can all have the minimap we want. No?

**Comment by PilzAdam** [comment]
To be clear, this gets a :-1: from me if can't be localized.

Maybe pass the texture path through gettext first? Or render the labels as text instead of images?

**Comment by rubenwardy** [comment]
Maybe supporting localised textures could be a nice feature. Then again, it should probably be text in most cases

**Comment by paramat** [comment]
Using text and localising it is over complex when a single arrow for +Z / North can be used.
:-1: For NESW, i might +1 a subtle arrow though.

**Comment by 0-afflatus** [comment]
A single arrow for +Z / North would be 'mostly harmless'.

**Comment by RealBadAngel** [comment]
OK, lets say we will make there an arrow. How would you explain to users what the hell that arrow is?

**Comment by paramat** [comment]
No need, it's fairly obvious, if not they will soon discover it is +Z or 'upwind'.

**Comment by paramat** [comment]
More opinions on this?

**Comment by sofar** [comment]
I'd prefer a single arrow pointing north. It avoids all the localization problems, and does what most people need it to do. Letters can go in a locale-specific texture pack.

**Comment by 0-afflatus** [comment]
The engine should not be dictating this at all. Isn't this customisable already? It should be.

**Comment by sofar** [comment]
@0-afflatus 

The engine provides the default texture. Texture packs can override the default texture.

Despite the discussion here, the minimap is, and remains, a map.

Now, I would like to invite *everyone* here on this thread who thinks the map doesn't need a "north" indicator at minimum to do the following: (this isn't directed at anyone in particular):

1. go to a local gas station
2. ask for a map that does not have a north indicator
3. insist that a north indicator is not needed and all parts of the map that would indicate direction, including longitude/latitude markers, grid lines, etc., should be removed from all maps
4. argue with gas station attendant that people are lazy by having these symbols
5. argue that he shouldn't call the police because the customer is always right
6. argue with the local police officer that the gas station attendant is just ignorant and his maps are making the problem worse

Or, you could just support the inclusion of the *one* element on a map that belongs on a map - an arrow pointing north. ;)

A map without a north indicator is just a pretty picture. Maybe we should call it "pretty mini picture" instead of "minimap"?

**Comment by Zeno-** [comment]
Does a compass really need need localisation for NESW? 

> Although modern compasses use the names of the eight principal directions (N, NE, E, SE, etc.), older compasses use the traditional Italianate wind names of Medieval origin (Tramontana, Greco, Levante, etc.)
(https://en.wikipedia.org/wiki/Compass_rose)

**Comment by 0-afflatus** [comment]
> The engine provides the default texture. Texture packs can override the default texture.

Great, so it's a non-issue for me.

**Comment by ObaniGemini** [comment]
I think for a better visibility and looking, only North indicator should be kept.

**Comment by rubenwardy** [comment]
:+1: at this point I don't care whether it's an arrow, just an N or NESW.

**Comment by Zeno-** [comment]
+1

**Comment by paramat** [comment]
Not NESW or N, let's keep it as abstract and multi-language as possible, if we add anything just a small arrow for +Z.

**Comment by sofar** [comment]
Someone needs to do the artwork and make a new PR.

**Comment by RealBadAngel** [comment]
Hi Sofar i have alredy Login and psw als RBA

**Comment by 0-afflatus** [comment]
> Hi Sofar i have alredy Login and psw als RBA

May I suggest an official explanation and introduction here, as we are all still in shock?

**Comment by Dragonop** [comment]
> A map without a north indicator is just a pretty picture. Maybe we should call it "pretty mini picture" instead of "minimap"?
We could call it "top-down mode", and it would make as much sense as looking at _yourself_ in 3rd person. A player with such magical abilities could easily have this kind of "feature" too.
Jokes aside, +1 for an arrow that points north. What color, tho?

**Comment by paramat** [comment]
Note any messages from 'RBA' are probably his close friend who is now using RBA's computer.

**Comment by sofar** [comment]
I've made a PR with just a simple North indicator arrow - no letters, in #3971.

**Comment by nerzhul** [comment]
a solution was found

**Comment by tanmayameher** [comment]
Thank you so much brother for contributing so much for minetest i really enjoy your technic mod. So sad that you are not among us. RIP RealBadAngel

**Pull request closed without merging**
