### PR TITLE
Fix Android player_stepheight for snow nodebox

### PR DESCRIPTION
**Pull request by MoNTE48**

### CODE REVIEW

**Comment by paramat** [comment]
Do you mean snow nodebox? That was made thicker a while ago.
What's the issue here?

**Comment by MoNTE48** [comment]
@paramat, yes.

**Comment by paramat** [comment]
:+1: 
Ah yes Android has auto-jump.

**Comment by paramat** [comment]
@MoNTE48 can you test that this still does not allow jumping onto a node + half slab?

**Comment by MoNTE48** [comment]
@paramat, node + half slab is 0.75.

**Comment by paramat** [comment]
Ok thanks that's fine then.

**Comment by paramat** [comment]
Note that jumping up node + snow nodebox is a little more difficult but possble in PC MT.

**Comment by paramat** [comment]
Approved by hmmmm http://irc.minetest.ru/minetest-dev/2016-05-03#i_4601158

**Comment by paramat** [comment]
bb925479a56e7b961e3520024c20b74245640035

**Pull request closed without merging**
