### PR TITLE
Add show_statusline_on_connect setting

### LINKED ISSUE #4790: Let mods suppress or modify the initial message sent by server on player join.
Whenever a player joins a server, the first message they see is the server status information, followed by the MoTD, if one is set. It would be great if it were possible to modify this message, or even suppress it completely. I searched a little bit through the code for likely keywords to see if there was any function in core that I could override to do this, but didn't find any. I don't know if this can be easily implemented, or if it would require changes in C++, but I think that server owners especially would find this useful.

An example use would be the ability of a mod to override the message in such a way that players with an invisibility priv (such as a hidden admin) are not shown in the client list that is sent to players connecting.

### PR DESCRIPTION
**Pull request by nerzhul**
This permits to disable statusline if you doesn't want to use this

Fixes #4790

### CODE REVIEW

**Comment by rubenwardy** [comment]
Please use imperative commits

> Add enable_statusline_on_connection setting

**Comment by nerzhul** [comment]
@rubenwardy amended

**Comment by sapier** [comment]
what about calling this setting "show" or "send" instead of "enable" as the statusline exists neither if it's sent or not. The difference is merely it's not sent and therefore not shown to client.

**Comment by nerzhul** [comment]
approval by @sfan5  on irc

**Pull request merged**
